Step 2 : 상품 목록 화면 구현 (리나, 찌로)
yagom-academy/ios-open-market pull request #10
Opened 2021-01-31 07:49 UTC by zziro95

@cmindy 
안녕하세요 민디 Step2 구현내용 확인부탁드려요:)

[구현내용]
- UISegmentedControl 사용하여 테이블뷰, 컬렉션뷰 보여주기
- 테이블뷰, 컬렉션뷰에 조회한 데이터 전달해서 올려주기!!
- 상품등록(+) 버튼을 통해 새로운 상품을 등록하는 화면으로 이동하기
- 처음 목록을 로드할 때, LaunchViewController를 보여주기, 데이터를 전달받으면 첫번째 화면으로 전환
- 제약조건을 이용해 discountedPrice가 없을 경우 알맞은 자리에 UI 배치
- 아래로 스크롤 할때 페이지가 없을때까지 추가 페이지 보여주는 기능

[고민 내용]
- 리로드할때 이미지 다시 불러와서 깜빡거리는 현상 해결방법,.,.🥺
  - 리로드 할때 테이블뷰와 컬렉션뷰 전체를 리로드하다보니 이미지를 다시 불러와서 깜빡거리는데 이전에 올라온 데이터말고 새로운 데이터만 리로드 할 수 있는 방법이 있는지.. 해결하지 못했습니다.

각자 push pull 하는 과정에서 충돌이 많이 일어나 커밋이 지저분합니다,. 다음에는 좀 더 신경써서 작업해보겠습니다!!

2021-02-01 12:53 UTC, cmindy requested changes
리나찌로~~ 고생 많으셨습니다. 몇가지 코멘트를 남겨놓았으니 확인해보세요! 🥁 

+ LayoutConstraint가 발생하고 있네요. 레이아웃 제약이 잘못 걸린 것 같습니다. 🙏 
![image](https://user-images.githubusercontent.com/33537899/106461177-c2919880-64d7-11eb-8f84-05a8d1d677d7.png)

2021-02-01 12:53 UTC, cmindy commented on OpenMarket/OpenMarket/ViewController/GridViewController.swift
> +}
ListViewController와 코드가 중복이 되는데, 비슷한 형식으로 중복되는 코드라면 개선해볼 수 있을 것 같네요.

2021-02-01 12:53 UTC, cmindy commented on OpenMarket/OpenMarket/ViewController/GridViewController.swift
> +                        debugPrint(error.localizedDescription)
LaunchViewController에서 네트워크 연결에 실패한 뒤 스크롤을 하게 되면 네트워크 요청이 연속으로 일어나는 것 같네요 👀 
콘솔에 프린트해서 처리하는 것 말고 오류가 난 경우에 대비해 볼 수 있을까요?

2021-02-01 12:53 UTC, cmindy commented on OpenMarket/OpenMarket/ViewController/GridViewController.swift
> +            }
LoadingCell로 데이터를 주고 이에 따라서 셀의 상태나 뷰가 설정되는 방식은 어떻게 생각하시나요? 어떤 장단점이 있을까요?

2021-02-01 12:53 UTC, cmindy commented on OpenMarket/OpenMarket/ViewController/GridViewController.swift
> +            }
> 리로드할때 이미지 다시 불러와서 깜빡거리는 현상 해결방법,.,.🥺
리로드 할때 테이블뷰와 컬렉션뷰 전체를 리로드하다보니 이미지를 다시 불러와서 깜빡거리는데 이전에 올라온 데이터말고 새로운 데이터만 리로드 할 수 있는 방법이 있는지.. 해결하지 못했습니다.

지금 네트워크가 연결로 오류가 안돼서 확인은 할 수가 없네요. 😿 간단하게 보면 flag 값을 이용해 볼 수도 있을거고, `NSCache`도 이용해볼 수 있겠네요. 여러가지 방법이 있으니 조금 더 찾아보시고 직접 구현해보셔도 좋습니다 :)

2021-02-01 12:53 UTC, cmindy commented on OpenMarket/OpenMarket/ViewController/CustomCell/ProductTableViewCell.swift
> +    let stockLabel = UILabel()
클로저를 이용해서 생성시에 기본 속성을 설정해줄 수도 있습니다. 🦖 
https://docs.swift.org/swift-book/LanguageGuide/Initialization.html

2021-02-01 12:53 UTC, cmindy commented on OpenMarket/OpenMarket/ViewController/Extension.swift
> +    }
이 함수가 `Int`의 extension 에 있는게 맞을까요? Int 전반적으로 쓰이는 함수가 아닌 것 같은데 어떻게 생각하시나요~?

2021-02-01 12:53 UTC, cmindy commented on OpenMarket/OpenMarket/ViewController/GridViewController.swift
> +}
사용하지 않는 거면 남겨두어야 할까용?

2021-02-02 12:10 UTC, zziro95 commented
@cmindy 
## 수정 및 논의 사항

### [1번]
> Launch 화면에서 로딩이 완료되어야지만 마켓화면을 볼 수 있군요 🤔
미리 로딩을 해준다는 측면에서 어느정도 이점을 가져갈 수는 있겠지만, 불러와야할 데이터의 양이 늘어나게 되면 사용자가 앱이 동작되고 있는지 의심할 수도 있을 것 같아요~
마켓화면을 먼저 표시해주고 해당 화면에서 데이터가 로딩 중임을 알 수 있도록 변경해보는 건 어떨까요?

테이블뷰가 화면에 있는 상태에서, 인디케이터가 잘 안보일 것이라고 생각되어 LaunchScreen을 활용해보았는데요!
민디가 말한 것처럼, 데이터의 양이 늘어나면 계속 LaunchScreen만 보이니까 앱이 정지된 것처럼 보일 수도 있을거라는 생각이 들었어요.
그래서 민디가 해준 조언을 바탕으로, launch 화면에서 indicator를 띄워봤는데 이런 방향은 어떨까요?

#### 현재화면
<img width="200" alt="스크린샷 2021-02-01 23 13 44" src="https://user-images.githubusercontent.com/49546979/106471919-7b120900-64e5-11eb-92ca-a64c3622e7f6.png">


### [2번]
> 두개의 섹션으로 표시가 되고 있는데, 섹션을 어떤 기준? 이유로 나누게 되신 건지 궁금합니다 🙋‍♀️

> 로딩 부분을 셀로 처리하신 이유가 궁금해용! 👀

두 가지가 같은 이유 때문인데요, 스크롤을 하면 추가적으로 데이터를 불러오게 했고 그걸 시각화하려고 했습니다!
첫번째 섹션은 실제 데이터가 나오는 섹션이고, 두번째 섹션은 로딩셀이 나오는 부분입니다.
두번재 섹션에서 인디케이터를 보여주는 이유는, 이 방법이 하단으로 내렸을때 데이터가 나온다는걸 보여줄 수 있는 것 같았고, 
처음 테이블뷰 화면에서 인디케이터를 보여주지 않은 것 처럼 테이블 뷰 위에 인디케이터가 잘 보이지 않을 것이라 생각되어서 했습니당..!
하단에 셀은, 모든 페이지를 다 보여줬을때는 마지막 페이지라는 문구를 띄우는 역할로 변경되고요.
이러한 이유로 섹션을 2개로 나누고, 두번째 섹션을 로딩셀로 처리하였습니다.

#### 현재화면
<img width="200" alt="스크린샷 2021-02-01 22 30 09" src="https://user-images.githubusercontent.com/49546979/106472024-9bda5e80-64e5-11eb-933c-20900482f343.png"><img width="200" alt="스크린샷 2021-02-01 22 30 00" src="https://user-images.githubusercontent.com/49546979/106472029-9d0b8b80-64e5-11eb-8687-a02f9b87f776.png">
<img width="200" alt="스크린샷 2021-02-02 20 45 02" src="https://user-images.githubusercontent.com/49546979/106595905-9d645f00-6597-11eb-994e-72c4b7833478.png"><img width="200" alt="스크린샷 2021-02-02 20 45 07" src="https://user-images.githubusercontent.com/49546979/106595907-9e958c00-6597-11eb-9600-6dc99f9478f1.png">



### [3번]
> LoadingCell로 데이터를 주고 이에 따라서 셀의 상태나 뷰가 설정되는 방식은 어떻게 생각하시나요? 어떤 장단점이 있을까요?

와우... 이 방법을 생각 못했는데, 해보니까 정말 깔끔하고 좋은거같아요.
장점은 collectionView(cellForItemAt) 함수가 많은 일을 하고있는 것을 나누어 가질 수 있는 것 같고, 보기에 깔끔해졌어요.
단점은... tableView에서 확인하기 어렵다...?

### [4번]
> 클로저를 이용해서 생성시에 기본 속성을 설정해줄 수도 있습니다. 🦖
https://docs.swift.org/swift-book/LanguageGuide/Initialization.html

앗, 저희가 논의했던 부분인데요! 실제 현장(?)에서는 클로저를 사용해서 기본 속성을 주는 편인가요?
클로저로 만들었다가, 위쪽이 너무 헤비해보이고 또 따로 제약을 줘야해서 한번에 하자 하고 내렸는데 실제로는 어떻게 사용하는지 궁금해요.

### [5번]
> 이 함수가 Int의 extension 에 있는게 맞을까요? Int 전반적으로 쓰이는 함수가 아닌 것 같은데 어떻게 생각하시나요~?

이 어플 내부에서 Int들에는 모두 필요하다고 생각되어서 사용했습니당! 그런데 민디의 이야기를 들으니 고민스럽네요🤦🏻‍♀️
ViewController를 extension해서 사용하는게 나을것같나용..? 잘 모르겠어요🤨

### [6번]
> 지금 네트워크가 연결로 오류가 안돼서 확인은 할 수가 없네요. 😿 간단하게 보면 flag 값을 이용해 볼 수도 있을거고, NSCache도 이용해볼 수 있겠네요. 여러가지 방법이 있으니 조금 더 찾아보시고 직접 구현해보셔도 좋습니다 :)

저희가 이 부분을 TableView의 insertRows 메서드와 CollectionView의 insertItems 메서드를 이용하여, 전체를 리로드하지 않고 스크롤을 하게될때 추가되는 데이터만큼 셀을 추가하는 방법으로 시도해보았습니다. 
그런데 TableView는 insert, reload, delete와 같은 작업을 하기전후로 beginUpdates, endUpdates메서드를 부르지만 CollectionView에는 그러한 메서드가 없어서 따로 분기를 타야했으며,
CollectionView에서는 insertItems를 하지 않아도 자동으로 데이터들이 추가로 표시되는 현상이 있었고,
또한 tableView에서 insert를 하면서, section만을 reload하는 것에서 오류가 발생하는 등.... 오늘 하루를 치열하게 이 부분과 싸워 보았지만 __실패했습니다...🤦🏻‍♀️__

결론적으로 TableView와 CollectionView의 동작방식에 대해 좀 더 깊게 알아봐야할 것 같다고 생각이 들었고, 좀 더 많은 시간 투자가 필요하다는 것을 깨달았습니다.😂
그리고 오늘 하루를 저것만 해결하는데 투자하다보니, 야곰이 해줬던 말이 떠올랐습니다.
그건 바로 '적혀진 요구사항을 충실히 구현하고, 추가적인 기능에 너무 시간을 쏟지마라.'는 이야기였습니다!
저희는 이미지가 깜빡 거리는 현상을 해결하는 것은, 요구사항이라기 보다는 (저희가 하고싶은) 추가적인 기능이라는 생각이 들었습니다.
그래서 저희는 이 부분을 step1에서의 패키지 만드는과 같이 프로젝트 마무리단계에 다시 보려고 하는데,
민디의 생각은 어떤지 알고싶습니다..🥺🥺🥺🥺🥺

2021-02-03 15:34 UTC, cmindy reviewed
코멘트 남겨놓았으니 확인해보세요! 💃

[1번]
이건 어떻게 보면 기획적인 측면일 수도 있어서 두분이 생각하시기에 충분하다면 좋습니다.

[2번]
와우 이런 세심한 부분까지 신경쓰시다니 멋져요.
아이폰의 설정앱을 보시면, 전형적인 테이블뷰로 구성되어있고 각각 섹션이 확실하게 나눠져있는 것을 보실 수 있을 거예요. 현재 화면에 보이는 모습으로는 섹션이 나눠진 것은 알 수 없고 그냥 마지막 셀에 표시되는 것처럼 보이고 있지 않나요? (아닐수도..막눈 죄송 😂 ) 
이런 맥락 + 위에 말씀해주신 의도에 따르면 섹션을 나누는 것은 한 번 더 고민해봐야하지 않나 싶어요. footer나 마지막 셀에 보여주는 것으로도 충분한 것 같습니다. 
케바케긴하지만 저는 보통 데이터 타입에서 구분이 필요할 때 다른 섹션을 설정해주는 것 같아요. (어떻게 구성하느냐에 따라, 그리고 사람마다 달라질 수 있는 부분입니다...ㅎㅎ) 

[3번]
ㅎㅎ 요렇게 바로 답변 가능한 건 코멘트에 답글로 남겨주셔도 됩니당 ❣️ 여기가 너무 길어지는 것 같아서 ㅜㅜ

[4번]
앗하~ 역시역시 찌로리나는 다 논의를 하셨었군요.
음 맞아요. 클로저 선언을 하게 되면 그런 문제가 있을 수 있죠. 이건 사실 가독성 문제긴 한데,, 찌로리나가 합의하셔서 더 좋다고 생각하시는 쪽으로 코드를 작성해주시면 됩니다 :) 찌로리나가 곧 실제 현장 아니겠씁니까 ~~ 😎 
저는 코드로 레이아웃을 잡는 경우에는 클로저로 속성 설정하는걸 애용하는 편이예요. UILabel이라면 font, color처럼 기본적인 속성들 위주로 설정하고 있습니다. 코드로 레이아웃을 잡으면 constraint 코드만으로도 너무 복잡해져서.. 최대한 기본적인 것들은 모아놓으면 조금 깔끔해지더라구요 ㅎㅎ! 제 의견도 한 번 참고해보셔용.

[5번]
상황에 따라 다르긴 하겠지만 요구사항이 변경되었을 때를 생각해보시면 좀 더 결정하는데 도움이 될 것 같네요. 
extension을 하게 되면 해당 타입이 그 메서드를 갖게 되는 거니까요. 세부적인 동작이라면 부분적으로 확장을 하거나 다른 방법을 찾아볼 수도 있겠죠. 얘는 이 타입에서 범용적으로 쓰인다 하면 타입을 확장해도 좋구요. 역시 모든 것은 트레이드 오프,,?


[6번]
와 많은 고민과 공부를 하셨군요.ㅠㅠ 👍  지금 문제점을 해결하려고 노력했던 과정들이 어떤방식으로든 다 도움이 되니까요ㅎㅎ 실패라고 생각하시기 보다는 나중에 아 머야 껌이네~ 🍯 를 하기 위한 발판정도로 생각해볼까요?! 어떤 걸 선택하셔도 응원합니다. 요구사항 먼저 만족하고 가보시죵

2021-02-03 15:34 UTC, cmindy commented on OpenMarket/OpenMarket/ViewController/ListViewController.swift
> +extension ListViewController: UITableViewDelegate {
사용하지 않는 Delegate가 채택되었네요 👀

2021-02-03 15:34 UTC, cmindy commented on OpenMarket/OpenMarket/ViewController/Extension.swift
> +    func loadNextPage(for view: Reloadable?, completionHandler: @escaping (Result<Bool, OpenMarketError>) -> ()) {
앗 이렇게 UIViewController를 확장해서 메서드를 공통으로 사용하게 되면 예전처럼 각 뷰컨에서 API 요청하는 방식이 더 나을 것 같네요.
UIViewController를 확장하게 되면 모든 뷰컨이 이 메서드를 갖게 됩니다. 현재는 모든 화면에서 이 메서드를 쓰고 있긴 하지만, 화면이 추가되는 경우나 다른 경우를 생각해보면 다음 페이지를 불러오지 않아도 되는 화면인데도 이 메서드를 갖게 되는거겠죠

2021-02-03 15:34 UTC, cmindy commented on OpenMarket/OpenMarket/Model/Network/MockURLSession.swift
> -import Foundation
제거해도 되나요? 🤓

2021-02-03 17:27 UTC, zziro95 commented on OpenMarket/OpenMarket/ViewController/ListViewController.swift
> +extension ListViewController: UITableViewDelegate {
테이블뷰의 ScrollView가 스크롤 됬을 때 다음페이지의 내용을 추가해주는 기능을 구현하기위해 채택해주어야 한다고 알고 있어 채택하였습니다.!

2021-02-03 17:27 UTC, zziro95 commented on OpenMarket/OpenMarket/ViewController/Extension.swift
> +    func loadNextPage(for view: Reloadable?, completionHandler: @escaping (Result<Bool, OpenMarketError>) -> ()) {
Insertable이라는 프로토콜을 생성후, extension을 통해 기본구현을 하여 ListViewController와 GridViewController, LaunchViewController에 채택해 줌으로써 해결하였습니다.

2021-02-03 17:27 UTC, zziro95 commented on OpenMarket/OpenMarket/Model/Network/MockURLSession.swift
> -import Foundation
<img width="327" alt="Screen Shot 2021-02-04 at 1 02 05 AM" src="https://user-images.githubusercontent.com/73584872/106784367-9882d680-668f-11eb-9740-e844a9d82846.png">

`UIKit` 프레임워크는 UI 포함한 앱 개발을 할때, disk-base file에 속한 데이터의 구조를 구성하는데 사용되고, 
`Foundation` 프레임워크는 텍스트처리, 날짜 및 시간 계산 등과같은 앱에 대한 기본 기능 계층을 구성할 때 사용합니다.
저희는 NSDataAsset을 사용하기 위해 `UIKit`을 import하였고, UIKit 프레임워크에 Foundation이 import 되있기 때문에 제거하였습니다.

2021-02-05 13:36 UTC, cmindy approved these changes
고생하셨습니다 ! 😸 
코멘트를 남겨놓긴 했는데, 일단 이 스텝은 넘어가고 다음 스텝 진행하면서 수정해볼까요?

2021-02-05 13:36 UTC, cmindy commented on OpenMarket/OpenMarket/ViewController/Extension.swift
> +    func reloadNewCell(view: Reloadable)
이 `reload~` 들이 `Insertable` 프로토콜 안에 있네용 ? `Relodable`과 `Insertable` 두 프로토콜의 역할이 무엇일까요..? 인터페이스들도 응집도가 높게 합쳐지는게 좋지 않을까요?

2021-02-05 13:36 UTC, cmindy commented on OpenMarket/OpenMarket/ViewController/Extension.swift
> +                for row in (lastCount)...(count - 1) {
product가 하나도 없으면 문제가 발생할 것 같네용?

2021-02-05 13:36 UTC, cmindy commented on OpenMarket/OpenMarket/ViewController/Extension.swift
> +    var isTableView: Bool { get }
한 파일안에 여러 프로토콜, 익스텐션들이 모여있는데 용도 등에 따라 파일을 구분하는게 좋지 않을까요?

2021-02-05 13:36 UTC, cmindy commented on OpenMarket/OpenMarket/ViewController/Extension.swift
> +    func numberOfRows(inSection section: Int) -> Int { return 0 }
CollectionView에서는 스크롤했을 때 테이블 뷰와 동작이 조금 달라보이네요. 리스트를 끝까지 로드해야와지만 셀들이 표시되고 있는 것 같습니다.

2021-02-05 13:36 UTC, cmindy commented on OpenMarket/OpenMarket/ViewController/Extension.swift
> +            let lastCount = view.numberOfRows(inSection: 0)
음 섹션이 없으면 어떻게 되나요? 😮

2021-02-05 13:36 UTC, cmindy commented on OpenMarket/OpenMarket/Model/OpenMarketData.swift
> +    var lastItemCount = 0
이 변수는 왜 추가된건가용?

2021-02-05 13:38 UTC, merged