오픈마켓 [STEP 2] 요한, 줄라이
yagom-academy/ios-open-market pull request #102
Opened 2022-01-14 09:09 UTC by YohanBlessYou

@july911 @yohanblessyou
안녕하세요 콘 @protocorn93
STEP2 PR 제출합니다! 이번에도 궁금한 점 위주로 정리했어요

(시간이 부족해서 Progress Indicator와 일부 디테일한 UI는 요구사항대로 하지 못했습니다🥲)

## 궁금한 점

### 🐥 1. Grid -> List 전환이 느린 문제 🐥 

현재 코드에서 Grid <-> List 전환 구현 방식은 하나의 CollectionView에 대해 `collectionViewLayout`과 `dataSource`를 바꾸어주고 `snapshot`을 새로이 넣어주는 방식입니다. 서버로부터 받아온 Product 데이터가 추후 변경되는 것은 배제하고 `products` 프로퍼티에 저장하여 사용하기에 최초 1회 이후부터는 빠르게 구동할 것이라 예상하였으나, 위와 같이 Grid <-> List 전환이 매우 느린 (특히, Grid->List) 문제가 있었습니다

이를 개선하기 위해 어떤 방향으로 생각해보면 좋을지 의견이 궁금합니다!

### 🐥 2. Custom cell은 defaultConfiguration를 쓸 수 없는지 🐥
[WWDC-Modern Cell Configuration](https://developer.apple.com/videos/play/wwdc2020/10027/)에서 defaultContentConfiguration 사용을 강조하는데, Custom Cell의 경우 defaultContentConfiguration이 custom cell에 추가한 UI 요소들을 갖고 있지 않아 설정해줄 수가 없었습니다

Custom Cell의 경우 defaultContentConfiguration없이 기존방식대로 설정해줘야 하는지 궁금합니다!

```swift
class CustomListCell: UICollectionViewListCell {
    let nameLabel: UILabel
    let priceLabel: UILabel
    ...
}

class ViewController: UIViewController {
    ...
    dataSource = UICollectionViewDiffableDataSource<Section, ProductListAsk.Response.Page>(collectionView: collectionView) {
        (collectionView, indexPath, item) -> UICollectionViewCell? in
        let cell = collectionView.dequeueConfiguredReusableCell(
            using: cellRegistration,
            for: indexPath,
            item: item
        )
        let config = cell.defaultContentConfiguration()
        config.nameLabel.text = "이름" // 불가
        config.priceLabel.text = "1000원" // 불가
        ...
}

```

### 🐥 3. 클로저 문법의 사용 🐥

![](https://i.imgur.com/TVA3Lcl.jpg)
-> 사진 1 

이번 프로젝트를 하면서 유난히 제네릭과 후행클로저 문법을 많이 접한 것 같습니다. 그 중에서도 두가지 문법(..?), 표현방법은 특히 이해가 가지 않아 질문드립니다. 
1. 첫번째 사진1 에서 NSCollectionLayoutSection을 리턴해주고 있는데, 정의부에 가서 보니 (section, layoutEnvironment) ->  NSCollectionLayoutSection을 UICollectionViewCompositionalLayoutSectionProvider 라는 함수 typelias 로 묶어서 생성자로 넣어주고 있는 모습을 보았습니다. (사실 잘 이해 못한거 같기도 합니다..)
저희는 `using: configuration`과는 다르게 `NSCollectionLayoutEnvironment` 에 대한 어떠한 설정도 해주지 않았는데 왜 코드가 동작할까요 .. 

```swift
@available(iOS 14.0, tvOS 14.0, *)
extension NSCollectionLayoutSection {

    public static func list(using configuration: UICollectionLayoutListConfiguration, layoutEnvironment: NSCollectionLayoutEnvironment) -> NSCollectionLayoutSection
}
```

```swift
public typealias UICollectionViewCompositionalLayoutSectionProvider = (Int, NSCollectionLayoutEnvironment) -> NSCollectionLayoutSection?
```

```swift
 public init(sectionProvider: @escaping UICollectionViewCompositionalLayoutSectionProvider)
```

2022-01-15 02:16 UTC, protocorn93 requested changes
@YohanBlessYou @July911  촉박한 일정 속에서 두 분 모두 고생하셨습니다! 

피드백에 앞서 먼저 Modern CollectionView를 코드로 실천해주신점 매우 휼륭하다고 생각해요!! 아마 이제는 점점 기존의 방식은 레거시가 되고 (특히 UI(CollectionView/TableView)DataSource는 더더욱..) 새로운 방법을 주된 방법으로 사용하지 않을까 싶어요! 

또한 전체 레이아웃을 코드로 작성해주신 점도 매우 인상깊어요! 이렇게 다양한 방법을 통해 레이아웃을 그려보는 연습은 매우 중요해요! 

---

## 궁금한 점 

> 🐥 1. Grid -> List 전환이 느린 문제 

네 이 이유는 명확합니다! 

1. 네트워크 통신 후 뷰 갱신을 메인 쓰레드에서 진행하고 있지 않습니다. (관련 코멘트 남겼습니다)
2. 이미지 로딩시 `Data(contentOf:)` 생성자를 사용하고 있습니다. [문서](https://developer.apple.com/documentation/foundation/nsdata/1413892-init)를 한번 확인해보시면 이것을 사용해선 안된다는 것을 단번에 이해하실 수 있을 것 같아요! (‼️**synchronously**‼️) 

이 부분에 대해서는 수정 부탁드릴게요! 



>  🐥 2. Custom cell은 defaultConfiguration를 쓸 수 없는지

저도 해당 영상은 보았지만 실제로 이를 사용해본 경험은 없네요! 아직은 기존 방법을 고수하고있습니다. (iOS 14부터 사용해서 그런 것도 있구요!) 하지만 이에 관련해서 몇 가지 글들을 찾아보았는데, 이것이 도움이 되실 것 같아요! 

- [블로그 글](https://www.biteinteractive.com/cell-content-configuration-in-ios-14/.)
- [스택오버플로우](https://stackoverflow.com/questions/63075418/how-to-use-ios-14-cell-content-configurations-in-general)



> 🐥 3. 클로저 문법의 사용 

네~ 우리가 인자로 넘기는 후행 클로저는 `escaping`이죠 그리고 이는 즉, 지금 당장 이 클로저를 호출하는 것이 아니라 내부적으로 언젠가 호출할 것이라는 겁니다. 그리고 그 주체는 당연히 `UICollectionViewCompositionalLayout` 객체가 되겠죠. 이 객체가 내부적으로 여러분이 넘겨준 클로저를 호출할 때 인자를 넣어서 호출할거구요. 즉 기본적으로 `NSCollectionLayoutEnvironment` 인스턴스를 넣어서 호출해줄겁니다. 그렇기 때문에 이를 그대로 `NSCollectionLayoutSection.list(using:, layoutEnvironment: )` 넣어주어도 무방합니다! 

---

## 추가 의견 

1. 테이블뷰나 셀에서 이미지 다운로드가 필요할 경우 이를 적절히 핸들링해줄 필요가 있습니다. (캐싱, 다운로드 취소 등) 보통 이런 기능을 갖고 있는 이미지뷰를 별도로 만들어서 사용하기도 합니다! 셀 안에서 이미지를 다운로드할 경우 참고할만한 애플 문서를 참고해드리겠습니다! 
   - [애플 문서](https://developer.apple.com/documentation/uikit/views_and_controls/table_views/asynchronously_loading_images_into_table_and_collection_views)
2. 현재 종종 디코딩 실패가 나는데요. 원인을 살펴보니 서버에서 내려오는 `price`는 소수점을 허용합니다. 그렇기 때문에 디코딩 에러가 발생하는데요. 이에 대한 코드 수정도 필요해보입니다! 

<img width="1539" alt="스크린샷 2022-01-15 오전 10 34 52" src="https://user-images.githubusercontent.com/20634806/149605058-2a0e3bf6-a544-422c-8e37-81e2b0414479.png">

<img width="1527" alt="스크린샷 2022-01-15 오전 10 35 45" src="https://user-images.githubusercontent.com/20634806/149605060-aea4ea89-3848-46e3-8e9e-f3dddc7ac0a9.png">

3. `Resources`로 몇몇 파일이나 디렉토리를 묶어볼 수 있을 것 같아요. (`LaunchScreen`, `Assets`) 또한 저는 `Applications`라는 디렉토리로 `AppDelegate.swift, SceneDelegate.swfit, info.plist`들을 종종 묶곤합니다. (info.plist 위치가 변경이 되면 `build settings`에서도 경로 변경이 필요해요!)

2022-01-15 02:16 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +    private enum Section: Hashable {
개인적으론 하나의 콜렉션 뷰가 리스트, 그리드 두 개의 레이아웃을 모두 가져가는 것보단,  각각 다른 뷰 컨트롤러를 메인 뷰컨트롤러에 임베드하고, segmented control로 이 둘을 스위칭하는 것이 더 바람직하지 않나 싶습니다. 

그렇게 되면 리스트 형태 화면과 그리드 형태 화면 이 둘을 각각 재사용하기도 훨씬 수월하지 않을까요?!

2022-01-15 02:16 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +        frame: view.bounds,
현재 가로-세로 orientation 변경에 콜렉션 뷰가 대응되지 못하고 있습니다. 제약을 사용해서 레이아웃을 잡는다면 이를 해결할 수 있지 않을까요?

2022-01-15 02:16 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +    private var dataSource: UICollectionViewDiffableDataSource<Section, ProductListAsk.Response.Page>!
`dataSource` 프로퍼티도 충분히 `lazy var`를 통해 생성해줄 수 있을 것 같아요. 그러면 불필요한 강제언랩핑도 피할 수 있을 것 같습니다!

2022-01-15 02:16 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +    override func viewDidLoad() {
`viewDidLoad` 안의 코드들의 추상화 레벨이 통일성이 없다보니까 가독성이 떨어지는 것 같아요. 코드 구조도 연관되어 있는 코드들끼리 묶어두는 것이 좋아보여요. 

```swift
override func viewDidLoad() { 
  super.viewDidLoad() 

  attribute()
  layout()
  configure()
}
```

저는 보통 위의 구성대로 코드를 작성합니다. 한 줄 짜리 코드라도 추상화 레벨을 맞추면 보다 가독성이 좋아질 수 있어요!

2022-01-15 02:16 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +        let bounds = CGRect(
음 저는 보통 이런 경우에는 굳이 들여쓰기를 통해서 인자를 넘겨주지 않는데, 조금은 과하지 않나라는 생각도 드는데 두 분의 의견은 어떠신가요? (말은 이런 경우라고 했지만 저도 정확히 그 예시를 들기 어려운데 `CGRect`의 경우에는 조금 과한 느낌이 들어서 코멘트 남깁니다!)

2022-01-15 02:16 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +        let spacing = 10.0
저는 개인적으로 테이블뷰나 콜렉션뷰의 레이아웃을 그릴 때 사용하는 상수들은 뷰 컨트롤러 정의부 상단에 별도의 네임스페이스로 정의해둡니다. 

```swift
class SomeViewController: UIViewController { 
  // MARK: Inner types 
  enum Dimensions { 
    enum CollectionView { 
       static let spacing: CGFloat = 10 
       static let ... 
    }
  }
}
```

은근히 이런 값들이 자주 변경되는 것을 자주 경험하는데 그때마다 찾아 수정하는게 번거롭고, 유지보수성도 떨어지더라구요. 이렇게 네임스페이스를 통해 관리하면 값의 변경도 쉽고 유지보수도 용이하더라구요!

2022-01-15 02:16 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +                self.applySnapShot(section: section)
네트워크 응답을 받고 뷰를 갱신해줄 때 아래와 같은 경고문구가 뜹니다. 이것이 무엇을 의미하며 어떻게 해결할 수 있을까요? 

<img width="1422" alt="스크린샷 2022-01-15 오전 10 36 45" src="https://user-images.githubusercontent.com/20634806/149604018-436197c0-e66d-4e2f-bb62-21ae1e333e51.png">

2022-01-15 02:16 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +                    print(APIError.decodingFail.localizedDescription)
에러에 관련해서도 보다 사용자 친화적인 형태로 제공되는게 좋을 것 같아요! 이를 위해선 두 가지가 필요해보여요! 

1. 알럿
2. 에러 문구 워싱

2022-01-15 02:16 UTC, protocorn93 commented on OpenMarket/OpenMarket.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 14.0;
타겟 버전을 14.0으로 올리신 이유가 있을까요?

2022-01-15 02:16 UTC, protocorn93 commented on OpenMarket/OpenMarket/Model/NetWork/ParsingType/ProductListAsk.swift
> +        struct Page: Decodable, Hashable {
`Page`는 왜 `Hashable`을 채택해야할까요?

2022-01-15 02:16 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +            (collectionView, indexPath, item) -> UICollectionViewCell? in
현재는 그렇지 않지만 종종 `UICollectionViewDiffableDataSource` 생성자로 들어가는 클로저 안에서 `self`를 사용해야할 경우가 있는데, 이때 `[weak self]`는 꼭 잊지마세요!

2022-01-15 02:16 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +        self.dataSource.apply(snapshot, animatingDifferences: false)
전통적인 `UICollectionVIewDataSource` 프로토콜을 채택해서 사용할 때와 Diffable DataSource를 사용할 때를 비교해보았을 때, 어떤 방법을 더 선호하시나요? 그리고 그러한 이유가 궁금합니다! 
(왜 애플은 Diffable DataSource를 내놓았을까요!)

2022-01-15 02:16 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/CollectionViewGridCell.swift
> +    let imageView: UIImageView = {
접근제어자가 누락된 것 같아요!

2022-01-15 02:16 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/CollectionViewGridCell.swift
> +        imageView.image = UIImage(systemName: "pencil")
기본 이미지를 위해 넣어주신걸까요? placeholder 목적이라면 빈 이미지 + 배경색으로도 충분히 이를 나타낼 수 있을 것 같아요!

2022-01-15 02:16 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/CollectionViewGridCell.swift
> +        stackView.addArrangedSubview(stockLabel)
`stackView`가 `lazy var`이니, 포함하는 뷰들에 대해 접근이 가능할텐데요. 생성자를 통해 뷰들을 한번에 배열로 넣어주지 않고 `addArrangedSubview`를 매번 호출해서 넣어주신 이유가 궁금하네요!

2022-01-15 02:16 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/CollectionViewGridCell.swift
> +        addSubview(stackView)
이 코드는 `configureAutoLayout` 메서드 안으로 들어가도 좋을 것 같아요

2022-01-17 08:25 UTC, July911 commented on OpenMarket/OpenMarket/View/CollectionViewGridCell.swift
> +        addSubview(stackView)
무조건 init 안에 들어가야 된다고만 생각했는데, configureLayout() 안에 들어가니 조금 더 쉽게 읽히는것 같습니다 감사합니다 !

2022-01-17 08:26 UTC, July911 commented on OpenMarket/OpenMarket/View/CollectionViewGridCell.swift
> +        stackView.addArrangedSubview(stockLabel)
생성자를 통해 한번에 바꿔주는 방향으로 수정했습니다. 콘이 지적해주신 이유가 함수를 한번씩 호출해주는 성능상의 이유인지, 가독성 때문인지 궁금합니다 !

2022-01-17 08:26 UTC, July911 commented on OpenMarket/OpenMarket/View/CollectionViewGridCell.swift
> +        imageView.image = UIImage(systemName: "pencil")
테스트한다고 만들어준거였는데 삭제를 못했었네요..... 수정했습니다.. 죄송합니다..

2022-01-17 08:26 UTC, July911 commented on OpenMarket/OpenMarket/View/CollectionViewGridCell.swift
> +    let imageView: UIImageView = {
접근제어자 추가했습니다 ! 세세한 부분까지 지적해주셔서 감사합니다. :)

2022-01-17 08:30 UTC, July911 commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +        self.dataSource.apply(snapshot, animatingDifferences: false)
음 .. 사실 이 부분에 대하여 이야기를 나눠보았는데, 전통적인 방법에서 reloadData를 하나, 스냅샷을 찍어서 apply 를 하나 성능상의 큰 차이가 있을까? 라는 의문이 있었습니다. 어차피 data가 바뀐다면 그에 맞춰서 뷰는 변해야 하는데, 오히려 스냅샷을 찍어서 적용을 시키는것이 더 큰 비용이 들 수도 있다는 생각을 했습니다. 콘의 생각은 어떠신가요 ..? 
또한 , UI와 데이터간의 근원(..?) 이 같다 라는게 장점일 것 같다는 이야기를 나누었습니다. -> (모델을 거치지 않고 바로 업데이트 가능)

2022-01-17 08:33 UTC, July911 commented on OpenMarket/OpenMarket.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 14.0;
modernCollectionView 스타일을 사용하기 위해서, 적용 최소버전인 14.0으로 올려주었습니다 !

2022-01-17 08:35 UTC, July911 commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +                    print(APIError.decodingFail.localizedDescription)
알럿같은 경우에는, 현재 사용자에게 보여지는 부분에서 아직은 괜찮다고 생각이 들었습니다.
만약 데이터를 받아오는 과정이나 상품의 재고가 부족할 경우 다음스텝에서는 꼭 필요한 기능이라고 생각이 들었고 
위의 두가지 이유로 다음스텝에서 각자 구현하기로 했습니다 !  :) 감사합니다

2022-01-17 08:37 UTC, YohanBlessYou commented
오늘 줄라이와 함께 피드백해주신 부분 읽어보고 의견나누며 반영해보았습니다!

특히 큰댓글 1번으로 피드백주신게 중요하면서 저희가 간과하고 있던 내용이었는데 짚어주셔서 감사합니다 :)

## 큰댓글

> 1. 네트워크 통신 후 뷰 갱신을 메인 쓰레드에서 진행하고 있지 않습니다. (관련 코멘트 남겼습니다)
2. 이미지 로딩시 Data(contentOf:) 생성자를 사용하고 있습니다. 문서를 한번 확인해보시면 이것을 사용해선 안된다는 것을 단번에 이해하실 수 있을 것 같아요! (‼️synchronously‼️)

먼저 네트워크 작업임에도 main sync로 동작하는 `Data(contentOf:)`를 global thread에서 동작하도록 변경하였습니다. 이후, 이미지를 UI에 업데이트할 때와 snapshot을 apply할 때 메인스레드에서 진행하도록 변경하였더니 해당 부분이 해결되었습니다!

---

## 추가의견
>1. 테이블뷰나 셀에서 이미지 다운로드가 필요할 경우 이를 적절히 핸들링해줄 필요가 있습니다. (캐싱, 다운로드 취소 등) 보통 이런 기능을 갖고 있는 이미지뷰를 별도로 만들어서 사용하기도 합니다! 셀 안에서 이미지를 다운로드할 경우 참고할만한 애플 문서를 참고해드리겠습니다!

피드백주신 내용에 대해서 필요한 부분이라 공감하였습니다! 다만, 이번주부터 시작되는 오픈마켓2에 관련 내용이 포함되어 있다고 해서, 그때 함께 구현하는건 어떨까싶습니다!

>2. 현재 종종 디코딩 실패가 나는데요. 원인을 살펴보니 서버에서 내려오는 price는 소수점을 허용합니다. 그렇기 때문에 디코딩 에러가 발생하는데요. 이에 대한 코드 수정도 필요해보입니다!

price 타입을 `Int`로 지정하였는데 말씀해주신대로 소수점을 허용한다는 점을 알게 되어 `Double`로 전부 변경해주었습니다. API 문서에 `Decimal`로 표기되어 있는데 이는 정수와 소수를 전부 포함하는 용어라고 하더라구요 🥲

2022-01-17 08:54 UTC, YohanBlessYou commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +    private enum Section: Hashable {
말씀해주신것처럼 segmented control이 전환될때마다 새로 그리는게 아닌 미리 그려놓고 전환만 하는 방식이 합리적이라고 생각했습니다. (특히, 이미지 파일을 직접 저장하고 있지 않다보니 매번 네트워킹을 요구하는..)

다만, 피드백주신 내용 중 큰 변화가 필요한 것들은 이번주부터 시작되는 오픈마켓2에서 각자 구현해보는건 어떤가하는 의견이 나왔습니다! 비록 리뷰는 다른 분이 해주시겠지만.. 개인작업 경험도 필요할 것 같다고 서로 공감하였습니다

2022-01-17 08:55 UTC, YohanBlessYou commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +        frame: view.bounds,
혹시 이 부분은 오토레이아웃을 말씀하신걸까요? DM으로 따로 질문드리겠습니다

2022-01-17 09:00 UTC, YohanBlessYou commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +    private var dataSource: UICollectionViewDiffableDataSource<Section, ProductListAsk.Response.Page>!
말씀해주신 내용에 공감하여 고치려다보니.. 초기화코드가 `configureListDataSource()` 메서드의 일부와 중복된다는 것을 발견하였습니다. 재사용성을 위해선 기존의  `configureListDataSource()` 내용 중 일부를 분리하는게 필요합니다

다만, 이를 위해선 생각보다 많은 수정이 필요해서 (ex. 코드실루엣을 맞춰놓은 `configureGridDataSource`도 함께 바꿔야 함) 이 부분도 개인으로 해보고자 합니다!

2022-01-17 09:02 UTC, YohanBlessYou commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +    override func viewDidLoad() {
말씀해주신대로 왜 이렇게 만들었을까 싶을 정도로 추상화 레벨이 맞지 않았습니다. 이와 관련하여 저희는 UI Component별로 (CollectionView / MainView) 메서드를 나누어 보았습니다

2022-01-17 09:04 UTC, YohanBlessYou commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +        let bounds = CGRect(
이 부분은 저희가 나름대로 정한 줄바꿈 rule에 따른 것인데요~ 한 줄이 99칸을 넘으면 위와 같이 줄바꿈+들여쓰기 형식으로 사용하도록 통일해보았습니다. 이 rule을 사용하다보니 경우에 따라 말씀해주신것처럼 과한 느낌이 나는 경우도 있는데요.. 그럼에도 주관적인 부분이라 여겨져 당장 바꾸기보단 사용해보면서 rule을 점차 개선해나가보겠습니다!

2022-01-17 09:08 UTC, YohanBlessYou commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +        let spacing = 10.0
이런 상수값들을 따로 모아놓는 것이 훨씬 깔끔하다고 느껴져 반영하였습니다

다만, 현재 코드처럼 해당 상수가 한 곳에서만 사용된다면 경우에 따라 약간의 불리한 점도 있지않을까 하는 생각도 들었습니다. 한 곳에서만 사용되므로 재사용성이 없음에도 코드를 읽다가 상수값을 확인하기 위해 네임스페이스 정의부로 왔다갔다 하며 읽어야 하는 점이 있었습니다

2022-01-17 09:11 UTC, YohanBlessYou commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +                self.applySnapShot(section: section)
UI 업데이트는 메인스레드에서 수행해야 한다는 rule에 의한 경고로 판단했습니다

다만, 이 부분은 write가 아닌 read만 하기에 별도로 처리하지 않았었는데 혹시 이렇게 뷰렌더링과 무관한 프로퍼티 read만 하는 경우에도 메인스레드에서 해야하는건지 궁금합니다!

2022-01-17 09:15 UTC, YohanBlessYou commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +                    print(APIError.decodingFail.localizedDescription)
이 부분도.. 상대적으로 큰 작업으로 생각되어 개인으로 해보고자 합니다..! 너무 미루는 것 같지만.. 지금 급하게 변경하면 이런 사용자 친화적인 형태의 아웃풋이 왜 필요할까를 생각하기보단 피드백 받은 내용을 반영하는데 급급해질듯해서.. 양해 부탁드리겠습니다!

2022-01-17 13:23 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/CollectionViewGridCell.swift
> +        stackView.addArrangedSubview(stockLabel)
개인적으론 가독성에 무게를 두어 코멘트를 남겼습니다. 내부적으로 어떻게 구현되어있는지에 대해서는 잘 모르겠으나, 성능상으로는 큰 차이가 없을 것으로 생각됩니다.

2022-01-17 13:27 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +        self.dataSource.apply(snapshot, animatingDifferences: false)
먼저 DiffableDataSource를 최초로 소개하는 [WWDC 영상](https://developer.apple.com/videos/play/wwdc2019/220/)을 시청해보시는걸 권장드려요. 

먼저 DiffableDataSource는 이전 스냅샷과 이후 스냅샷을 비교(diff)하여 변경된 부분에 대해서만 갱신을 해줍니다. 그렇기 때문에 무엇이 변경되었는지를 알아야 하기 때문에 아이템들이 고유하다는 `Hashable`을 채택해야하구요! 그렇기 때문에 성능면에서도 훨씬 우수합니다. 

또한 기존의 방법을 사용하면서 가장 많이 겪었던 이슈 중 하나가 셀을 삭제하거나 삽입할 때 인덱스 에러를 굉장히 자주 겪게되는데, 위와 같은 방식의 비교로 이러한 데이터소스 변경 그리고 이에 따른 애니메이션 효과도 보다 쉽고 안전하게 적용할 수 있어요!

2022-01-17 13:28 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +        let spacing = 10.0
네네! 이건 저의 스타일입니다! 말씀해주신 단점도 확실히 있는 것 같아요! 저는 그것과 유지보수성 사이에서 유지보수성에 조금 더 무게를 두었던거구요 😄 이런 트레이드오프 과정을 통해 코드를 작성하고 구조를 설계해내가시면 됩니다!

2022-01-17 13:29 UTC, protocorn93 commented on OpenMarket/OpenMarket/Model/NetWork/ParsingType/ProductListAsk.swift
> +        struct Page: Decodable, Hashable {
아래 DiffableDataSource 관련 코멘트에 설명 추가해놓았습니다!

2022-01-17 13:30 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductListViewController.swift
> +        let bounds = CGRect(
네네 좋아요! 그런 기준이 궁금했습니다!

2022-01-17 13:46 UTC, merged