오픈마켓2 [STEP 1] 신나
yagom-academy/ios-open-market pull request #108
Opened 2022-01-20 12:21 UTC by smart8612

안녕하세요! @corykim0829 코리!~
Step1 구현을 진행하고 나서 PR 요청을 보내봅니다.
코드에 부족한 부분이 많지만 중간 점검 처럼 피드백을 받고 더 좋은 프로젝트로 개선시켜보고자 합니다 🥳
잘 부탁드립니다~ 😄

---

## 의존성 환경

- `CocoaPods` 을 통하여 `SwiftLint` 를 사용하고 있습니다!

## 구현한 부분

    상품 등록/수정 페이지에서 키보드가 UI를 가리지 않도록 구현하였습니다.
    텍스트 입력창이 화면에 가려지면 스스로 키보드 위에 위치하도록 구현하였습니다.
    
    
![Untitled](https://user-images.githubusercontent.com/25794814/150336296-d261f9c4-b50b-47e7-9c24-94ff21381454.gif)

    입력하고자 하는 텍스트 필드에 포커싱 되도록 스크롤을 위치시키도록 구현하였습니다.
    키보드 상단의 툴바에서 Done 버튼을 클릭하면 다음으로 입력해야할 텍스트 필드를 자동으로 찾아줍니다.
    
    
![Untitled2](https://user-images.githubusercontent.com/25794814/150336353-5579f98d-4953-4def-bfcd-f7a94fe0a0c7.gif)

    
    텍스트 필드의 특성에 알맞은 키보드로 변경됩니다.
    이미지가 화면의 가로폭을 벗어나면 스크롤 뷰가 활성화 됩니다!
    
    
![RPReplay_Final1642674806](https://user-images.githubusercontent.com/25794814/150336638-5efc64d0-3eeb-45cb-b374-65e063d0f4da.gif)

    
    이미지를 캡쳐하거나 사진첩에서 기존의 이미지를 불러올 수 있습니다.
    

![RPReplay_Final1642675130](https://user-images.githubusercontent.com/25794814/150336691-c41ebf28-52b1-43ad-9042-f7504c67d169.gif)

### TextEditer 및 키보드 관련 동작 구현 과정

- [애플 키보드 프로그래밍 가이드](https://developer.apple.com/library/archive/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/KeyboardManagement/KeyboardManagement.html#//apple_ref/doc/uid/TP40009542-CH5-SW1)를 참고하여 구현하였습니다.
- 키보드 스크롤 관련 기능 구현 과정
    
    **시스템은 키보드가 표시되면 앱에게 기본 정의된 Notification 메시지를 쏴줍니다.**
    
    - [UIKeyboardWillShowNotification](https://developer.apple.com/documentation/uikit/uiresponder/1621576-keyboardwillshownotification)
    - [UIKeyboardDidShowNotification](https://developer.apple.com/documentation/uikit/uiresponder/1621602-keyboarddidshownotification)
    - [UIKeyboardWillHideNotification](https://developer.apple.com/documentation/uikit/uikeyboardwillhidenotification)
    - [UIKeyboardDidHideNotification](https://developer.apple.com/documentation/uikit/uikeyboarddidhidenotification)

**Notification을 통해 iOS 장치 혹은 상태에 따라 정확하게 키보드의 크기를 가져올 수 있습니다.**

- 키보드의 크기를 알아야 하는 이유는 키보드 아래에 인터페이스가 놓였을 때 사용자가 제어할 수 있도록 불러와야 하기 때문입니다.
- Notification Center의 userinfo를 통해 키보드의 frame 크기에 접근할 수 있습니다.
- notifiaction → userinfo → keyboardDidShowNotification

**키보드 프레임의 높이만큼 ScrollView의 ContentView(bound) inset을 조정해줍니다.**

    구현 방법:
    (1) 키보드의 크기를 가져옵니다.
    (2) 스크롤 보기의 하단 콘텐츠 삽입을 키보드 높이로 조정합니다.
    (3) 대상 텍스트 필드를 보기로 스크롤합니다.

**키패드에서 다음 버튼을 클릭했을 때 포커싱 되는 텍스트 필드를 전환시켜줍니다.**

- 각 텍스트 필드는 UIView 이기도 하기에 ui 객체를 식별하기 위한 tag 값을 지정시켜줄 수 있습니다.
- 현재 view의 다음번 tag를 가진 뷰가 존재한다면 해당 뷰를 firstResponder로 설정시켜줍니다.
- 존재하지 않으면 현재 뷰를 firstResponder 해제하여 키보드가 종료되도록 구현합니다.
- 직접 키보드가 종료되는 기능을 구현해야 하는 이유는 키보드를 띄우는 것은 iOS의 역할이지만 해제하는 것은 앱의 책임이기 때문입니다.

**키패드의 타입을 NumberPad로 설정하면 return 키가 사라지는 현상을 해결하였습니다.**

- 텍스트 에디터를 클릭하면 키보드가 등장합니다.
- 키보드의 상단부에 위치한 inputAccessory 뷰에 done 아이템이 포함된 툴바를 구현시켰습니다.
- done 버튼이 클릭되면 다음 텍스트 필드를 찾아주거나 키보드를 종료시킵니다.

- PageSheet alert 창에 배경을 눌렀을 때 자동으로 dismiss 되도록 구현하였습니다.
    - 별도의 제스처 인식기나 responder chain을 활용하여 터치이벤트를 감지하고 alert 창이 dismiss 되도록 구현하려고 고민했었습니다.
    - alert 창에 cancel 버튼을 추가하는 것 만으로도 운영체제가 위 기능을 대신 구현시켜주어서 예상보다 쉽게 구현되었습니다.
    
- Dynamic Type 및 접근성 레이블을 지원하도록 구현했습니다.
    - Xcode의 접근성 검사기를 통해 특이사항이 발생되지 않도록 구현하였습니다.
    - Dynamic Type이 적용되어 시스템 상황에 따른 동적으로 폰트 크기가 변동되도록 구현하였습니다.
    - VoiceOver 동작시에도 UI요소가 의미하는 바가 정확히 전달 될 수 있도록 접근성 레이블을 지정시켜주었습니다.

![RPReplay_Final1642677267](https://user-images.githubusercontent.com/25794814/150336990-9157b4c1-ca63-42fe-a8f6-3539a641d3b3.gif)

---

## 고민한 부분

- **고차함수와 extension을 적극적으로 활용하여 읽기 쉬운 코드를 작성하려고 노력했습니다.**
    - 즉, 복잡한 구현은 extension을 통해 기본 구현으로 갖고 있도록 하여 함수 호출부의 가독성을 높히고자 노력했습니다.
    - ViewController와 Utilities 폴더의 extension에 세부 코드가 작성되어있습니다.
    
    ```swift
    // ProductUpdateViewController.swift
    func updateImageStackView() {
        productImageStackView.subviews.forEach { $0.removed(from: productImageStackView, whenTypeIs: UIImageView.self) }
        model.currentImages.forEach { productImageStackView.insertArrangedSubview(UIImageView(with: $0), at: 0) }
    }
    ```
    

- **네트워크 처리 로직과 데이터 처리 로직을 ViewController가 아닌 별도의 객체를 통해 처리하도록 구현하였습니다.**
    - 각 Scene은 ViewController를 통해 관리되어야 합니다.
    - 화면에서 보여져야 할 데이터(이미지 등)는 모두 modelManager 객체를 통해 처리됩니다.
    - 네트워크 처리가 필요한 경우 ProductNetworkManager를 통해 처리됩니다.

- **객체간에 메시지를 주고받는 방법으로 클로저를 활용하였습니다.**
    - B객체에게 A객체의 메서드를 핸들러 형태로 전달시켜주어 B에서 A객체의 메서드를 실행시켜줄 수 있도록 구현해보았습니다.
    - 이 관계는 ViewController ↔  Model ↔ Network 객체 사이에서 자주 사용되었습니다.
    
    ```swift
    class ProductNetworkManager<T> {
        
        private let urlSessionProvider: URLSessionProvider
        
    		// 코드 예시는 다음과 같습니다.
        var dataFetchHandler: ((T) -> Void)?
        
        init() {
            urlSessionProvider = URLSessionProvider(session: URLSession.shared)
        }
    }
    ```
    

---

## **궁금한 부분**

- 오픈마켓 프로젝트에서 상품을 등록할 때 사용되는 판매자 ID, 패스워드, 식별자에 관한 정보를 AppConfigure의 타입 프로퍼티를 통해 앱 내에서 전역적으로 사용할 수 있도록 관리하고 있습니다. 어디서나 개인정보가 담겨있는 변수에 접근할 수 있다는 측면에서 보안성이 좋지 못한 방식을 사용했다고 생각합니다. 실무에서는 이와 같은 민감한 정보를 어떤 방식으로 처리해오고 있는지 궁금합니다.

- 앱 내부에서 alert 창에 띄울 경고 메시지 문자열을 코드상에 직접 작성해주는 방식으로 관리하고 있는데, 언어가 바뀌거나 메시지를 바꿔야 할때 관리의 어려움이 있을 것 같아서 대안을 찾아보고 있습니다. ㅠㅠ

- 추후에 사용될 상품수 페이지에서도 상품 등록 페이지를 공통으로 사용할 수 있도록 구현하고자 목표하였습니다.
    
    UI 공통적으로 사용되는 기능은 ProductUpdateViewController에 구현하고 이 클래스를 상속하여 상품등록 페이지를 구현하는 ProductCreateViewController를 구현해둔 상태입니다. 앞으로 상품 수정에 필요한 코드는 ProductUpdateViewController 를 상속하는 상품 수정 컨트롤러를 추가적으로 생성할 계획입니다.
    
    상품 목록을 의미하는 ProductPageViewController에서 네비게이션 아이템의 생성 버튼을 클릭했을 때 ViewController간 정의된 `productCreateModifySeque` 를 perform 하여 화면전환을 구현하고 있습니다. 
    
    이 때, 목적지 뷰 컨트롤러인 ProductCreateViewController에 모델 인스턴스를 주입하여 주도록 구현했습니다. 모델 주입 관련 코드는 상위 클래스인 ProductUpdateViewController 에 작성되어있습니다. 
    
    추후에 있을 상품 수정에 관한 모델을 작성했을 때, 해당 모델을 주입 시켜서ProductUpdateViewController 코드를 재사용할 수 있도록 구현하기 위함입니다. 
    
    생각은 위 내용처럼 하긴 했는데,,,, 스토리 보드에서 scene 에 등록할 수 있는 ViewController가 1개여서,,, 하나의 Scene을 상품 생성용과 상품 수정용으로 사용하는 것을 위와 같이 구현하는 것이 적절할까 고민하고 있습니다.

2022-01-21 09:53 UTC, corykim0829 requested changes
.

2022-01-21 11:26 UTC, corykim0829 requested changes
수고 많으셨습니다 신나!!! 👏👏👏

키보드 처리 관련하여 많은 공부를 하시고 잘 적용하신 부분이 인상깊었어요! 👏👏👏

시스템 상황에 따라 폰트 크기 변동 적용과 접근성 적용하신거 보고 정말 감탄했습니다!! 👍

---

## 궁금한 부분

1. 오픈마켓 프로젝트에서 상품을 등록할 때 사용되는 판매자 ID, 패스워드, 식별자에 관한 정보를 AppConfigure의 타입 프로퍼티를 통해 앱 내에서 전역적으로 사용할 수 있도록 관리하고 있습니다. 어디서나 개인정보가 담겨있는 변수에 접근할 수 있다는 측면에서 보안성이 좋지 못한 방식을 사용했다고 생각합니다. 실무에서는 이와 같은 민감한 정보를 어떤 방식으로 처리해오고 있는지 궁금합니다.

➡️ 사용자 관련 정보는 실무에서는 서버측에서 처리하기 때문에 프론트에서는 크게 걱정하지 않아도 되는 부분이에요. 물론 지금 처럼 민감한 정보를 전역 변수로 처리하면 안됩니다! 보통은 사용자 토큰을 만들어서 이를 통해서 서버와 통신을 하는 방법을 사용합니다!

2. 앱 내부에서 alert 창에 띄울 경고 메시지 문자열을 코드상에 직접 작성해주는 방식으로 관리하고 있는데, 언어가 바뀌거나 메시지를 바꿔야 할때 관리의 어려움이 있을 것 같아서 대안을 찾아보고 있습니다. ㅠㅠ

➡️ 이러한 문구도 변수로 관리하는게 좋습니다! enum안에 static으로도 많이 관리해요!

3. 추후에 사용될 상품수 페이지에서도 상품 등록 페이지를 공통으로 사용할 수 있도록 구현하고자 목표하였습니다.

UI 공통적으로 사용되는 기능은 ProductUpdateViewController에 구현하고 이 클래스를 상속하여 상품등록 페이지를 구현하는 ProductCreateViewController를 구현해둔 상태입니다. 앞으로 상품 수정에 필요한 코드는 ProductUpdateViewController 를 상속하는 상품 수정 컨트롤러를 추가적으로 생성할 계획입니다.

상품 목록을 의미하는 ProductPageViewController에서 네비게이션 아이템의 생성 버튼을 클릭했을 때 ViewController간 정의된 productCreateModifySeque 를 perform 하여 화면전환을 구현하고 있습니다.

이 때, 목적지 뷰 컨트롤러인 ProductCreateViewController에 모델 인스턴스를 주입하여 주도록 구현했습니다. 모델 주입 관련 코드는 상위 클래스인 ProductUpdateViewController 에 작성되어있습니다.

추후에 있을 상품 수정에 관한 모델을 작성했을 때, 해당 모델을 주입 시켜서ProductUpdateViewController 코드를 재사용할 수 있도록 구현하기 위함입니다.

생각은 위 내용처럼 하긴 했는데,,,, 스토리 보드에서 scene 에 등록할 수 있는 ViewController가 1개여서,,, 하나의 Scene을 상품 생성용과 상품 수정용으로 사용하는 것을 위와 같이 구현하는 것이 적절할까 고민하고 있습니다.

➡️ 지금 구현하신 코드는 ViewCotroller에 의존이 큰 것 같아요. 그래서 modelManager와 같은 객체가 실질적인 일을 처리할 수 있도록 하는게 좋을 것 같아요!

2022-01-21 11:26 UTC, corykim0829 commented on OpenMarket/OpenMarket/Controller/ProductCreate/ProductUpdateModelManager.swift
> +struct Form {
이 객체만 보면 어떤 역할을 하는지 알기 힘들 것 같아요. 따로 파일로 분리하고 조금더 명확한 네이밍이 필요해보입니다!

2022-01-21 11:26 UTC, corykim0829 commented on OpenMarket/OpenMarket/Controller/ProductNetworkManager.swift
> +                        self.dataFetchHandler?(data)
init 함수에서 urlSessionProvider을 지정하는 특별한 이유가 있을까요? 제가 봤을 때에는 init 함수에서 dataFetchHandler 클로저를 설정하게 하면 좋을 것 같아요.
이렇게 되면 dataFetchHandler 클로저가 nil로 처리되는 경우도 방지할 수 있을 것 같아요!

2022-01-21 11:26 UTC, corykim0829 commented on OpenMarket/OpenMarket/Controller/ProductNetworkManager.swift
> +                print(error)
요청 후 성공, 실패 여부에 따라서 처리가 필요해보입니다!

2022-01-21 11:26 UTC, corykim0829 commented on OpenMarket/OpenMarket/Controller/ProductCreate/ProductCreateModelManager.swift
> +        return true
networkManager에서 정상적으로 요청이 확인 됐을 때에만 process에 true 처리를 하면 좋을 것 같아요. 근데 현재 프로토콜에 명시되어있는 process 함수에서 Bool 타입을 반환해서 처리하는 방법은 조금 어색해보입니다.
함수 파라미터를 클로저로 하면 더 사용하기에도 쉽고 읽기도 쉬운 코드가 될 것 같아요! 그 과정에서 여기 구현된 process 함수도 더 깔끔하게 정리할 수 있을 것 같아요!

2022-01-21 11:26 UTC, corykim0829 commented on OpenMarket/OpenMarket/Controller/ProductCreate/ProductCreateModelManager.swift
> +class ProductCreateModelManager: ProductUpdateModelManager {
ProductCreateModelManager와 ProductUpdateModelManager는 전혀 다른 행동을 하는 객체 같아서 ProductUpdateModelManager가 프로토콜 같지 않아요.
조금 더 프로토콜 스럽게 이름을 지으면 좋을 것 같아요!

2022-01-21 11:26 UTC, corykim0829 commented on OpenMarket/OpenMarket/Controller/ProductCreate/ProductCreateModelManager.swift
> +        didSet { imagesDidChangeHandler?() }
여기에도 이 클로저가 nil일 경우가 있을 것 같아요!

2022-01-21 11:26 UTC, corykim0829 commented on OpenMarket/OpenMarket/Controller/ProductCreate/ProductCreateViewController.swift
> +// MARK: - Configure View Controller
주석과 MARK 사용으로 깔끔하게 정리한 부분 좋습니다 👍

2022-01-21 11:26 UTC, corykim0829 commented on OpenMarket/OpenMarket/Controller/ProductCreate/ProductCreateViewController.swift
> +            print("photoLibrary Not Available")
print문이 아닌 Alert와 같은 방법으로 사용자에게 오류를 처리해주면 좋을 것 같아요 :)

2022-01-21 11:26 UTC, corykim0829 commented on OpenMarket/OpenMarket/Controller/ProductPage/ProductPageViewController.swift
> +        guard let topViewController = destination.topViewController as? ProductCreateViewController else {
그냥 topViewController보다는 어떤 ViewController인지 명확한 이름으로 변수명을 지으면 좋을 것 같아요!

2022-01-21 11:26 UTC, corykim0829 commented on OpenMarket/OpenMarket/Utility/Extension+UIKit.swift
> +import UIKit
지금은 extension이 많지 않아서 하나로 관리하는게 괜찮지만 UIKit에 클래스가 많다보니 나중에는 이 파일이 비대해질 수도 있습니다! 그래서 각 UIKit 클래스마다 파일을 만드는게 좋아요! 참고하세요 :)

2022-01-24 09:30 UTC, smart8612 commented on OpenMarket/OpenMarket/Controller/ProductCreate/ProductUpdateModelManager.swift
> +struct Form {
* 해당 객체는 상품을 등록하는 페이지에 양식으로부터 모델에서 사용할 데이터만 추리기 위해 정의한 Form 타입이었습니다.
* 추후 다른 View 에서도 모델과 통신하기 위하여 다양한 Form이 발생할 수 있는 만큼 좀더 세부적인 네이밍을 채택하였습니다.

```swift
struct ProductRegisterForm {
    let name: String
    let price: String
    let currency: String
    let discountedPrice: String?
    let stock: String?
    let description: String
}
```

2022-01-24 09:38 UTC, smart8612 commented on OpenMarket/OpenMarket/Controller/ProductNetworkManager.swift
> +                        self.dataFetchHandler?(data)
* 기존에 방식에서는 네트워크 관리자 객체를 생성할 때 외부에서 클로저를 설정해주도록 구현되어있었습니다.
* 클로저 캡처를 응용하여 외부에서 실행시킬 메서드를 프로퍼티로 지정해주는 방식 대신에 completionHandler를 통해 메서드의 인자로 처리해주는 방식으로 개선시켜보았습니다.
* 프로퍼티를 활용하는 방식보다 함수를 호출하는 시점에서 동작 꾸러미를 설정해주는 것이 더 유연한 방법이 될 수 있다고 생각했기 때문입니다.
* 한편 여전히 함수의 인자로 받는 클로저가 nil 상태일 수도 있도록 옵셔널 타입으로 선언해두었습니다.
* 요청이 완료된 이후에 사용자가 별도의 동작을 수행하고 싶지 않을 수 있기 때문입니다!

```swift
func createProductRequest(data: Data, images: [Image], completionHandler: (() -> Void)? = nil, failureHandler: ((Error) -> Void)? = nil) {
    urlSessionProvider.request(.createProduct(sellerID: AppConfigure.venderIdentifier, params: data, images: images)) { (result: Result<CreateProductResponse, URLSessionProviderError>) in
        switch result {
        case .success(_):
            completionHandler?()
        case .failure(let error):
            failureHandler?(error)
        }
    }
}
```

2022-01-24 09:42 UTC, smart8612 commented on OpenMarket/OpenMarket/Controller/ProductNetworkManager.swift
> +                print(error)
* 위에서 언급한 것처럼 completionHandler 및 failureHandler를 함수의 인자로 받을 수 있도록 설계하여 네트워크 동작이 성공하거나 실패한 경우에 따라 별도의 사용자 정의 코드가 수행될 수 있도록 수정해보았습니다!

* 예를 들어 현재 상품 정보를 추가하는 화면에서 네비게이션 바에 있는 추가 버튼 아이템을 클릭 했을 때 성공 동작, 실패동작을 함께 넘겨주는데 이 코드는 네트워크통신의 성공 여부에 따라서 선택적으로 수행됩니다!
``` swift
@IBAction func doneButtonClicked(_ sender: UIBarButtonItem) {
    activityIndicator.startAnimating()
    do {
        try model.process(forms, completionHandler: completionHandler, failureHandler: failureHandler)
    } catch {
        failureHandler(error: error)
    }
}
```

2022-01-24 09:46 UTC, smart8612 commented on OpenMarket/OpenMarket/Controller/ProductCreate/ProductCreateModelManager.swift
> +        return true
* 네트워크 통신 뿐만 아니라 입력된 형식에서도 글자수 제한 혹은 이미지 개수 제한 등의 추가적인 제약조건을 충족해야합니다.
* 데이터 메니저의 process 메서드에서 문제가 발생할 경우 문제의 세부 내용이 담긴 LocalizedError를 던지도록 구현하였습니다.
* 사용자는 상품 등록 버튼을 클릭하였을 때 발생하는 알림창의 메시지를 확인하여 문제점을 해결할 수 있습니다.

``` swift
func process(_ form: ProductRegisterForm, completionHandler: (() -> Void)? = nil,
                 failureHandler: ((Error) -> Void)? = nil) throws {
        try validate(form: form)
        
        guard let currency = Currency(rawValue: form.currency) else { throw ProductCreateError.unknownCurrency }
        
        let params = CreateProductRequestParams(
            name: form.name,
            descriptions: form.description,
            price: form.price.convertToDecimal(),
            currency: currency,
            discountedPrice: form.discountedPrice?.convertToDecimal() ?? 0,
            stock: form.stock?.convertToInt() ?? 0,
            secret: AppConfigure.venderSecret
        )
        
        guard let json = try? JSONEncoder().encode(params) else { throw ProductCreateError.encodingError }
        networkManager.createProductRequest(
            data: json,
            images: parsedImages,
            completionHandler: completionHandler,
            failureHandler: failureHandler
        )
}
```

2022-01-24 09:48 UTC, smart8612 commented on OpenMarket/OpenMarket/Controller/ProductCreate/ProductCreateModelManager.swift
> +class ProductCreateModelManager: ProductUpdateModelManager {
* ViewController와 모델간의 의존성을 줄여서 뷰컨을 재사용할 수 있도록 만드는 것이 목적이었습니다.
* 다만, 말씀 주신 것처럼 역할이 불분명한 부분이 존재하는 것 같아서 현재의 코드에서는 해당 프로토콜을 제거한 상태입니다!

2022-01-24 09:52 UTC, smart8612 commented on OpenMarket/OpenMarket/Controller/ProductCreate/ProductCreateModelManager.swift
> +        didSet { imagesDidChangeHandler?() }
* 네트워크 통신이 비동기적으로 이뤄진 후에 데이터가 실제로 갱신되면 handler 메서드를 실행시키고자 하는 것이 목적이었습니다.
* 이번 구현에서 Model과 ViewController가 서로 통신하기 위해  NotificationCenter를 활용한 관찰자 모델을 적용해보았습니다.
* 따라서 프로퍼티 옵저버가 반응할때 Notification 메시지를 쏴주도록 구현하여 클로저가 nil 인 경우는 해결되었습니다.

```swift
class ProductCreateModelManager {
    
    let networkManager = ProductNetworkManager()
    
    private var images: [UIImage] = [] {
        didSet {
            NotificationCenter.default.post(name: .modelDidChanged, object: nil)
        }
    }
    // ****
}
```

2022-01-24 09:54 UTC, smart8612 commented on OpenMarket/OpenMarket/Controller/ProductCreate/ProductCreateViewController.swift
> +// MARK: - Configure View Controller
아무래도 ViewController가 각종 뷰의 delegate 역할을 하며 일부 유틸리티 기능이 뷰컨에 구현되면서 코드의 양이 많아진 경향이 있었습니다. 조금더 코드를 분류해두어 생산성을 높히기 위해 노력했습니다!~

2022-01-24 09:56 UTC, smart8612 commented on OpenMarket/OpenMarket/Controller/ProductCreate/ProductCreateViewController.swift
> +            print("photoLibrary Not Available")
* 처음 구현할 때 print 구문을 통해 추상적으로 구현해두고 놓쳤던 부분인 것 같습니다!
* 제안해주신 방법이 문제가 발생했을 때 사용자가 취해야 할 액션에 가이드를 줄 수 있는 것으로 사료되어서 Alert를 활용한 구현 방식을 채택하였습니다!

2022-01-24 09:57 UTC, smart8612 commented on OpenMarket/OpenMarket/Controller/ProductCreate/ProductCreateViewController.swift
> +            print("photoLibrary Not Available")
```swift
private func openCamera(_ action: UIAlertAction) {
        guard UIImagePickerController.isSourceTypeAvailable(.camera) else {
            let title = "카메라를 사용할 수 없습니다."
            let message = "카메라를 사용할 수 있는 환경인지 확인해주세요!"
            presentAcceptAlert(with: title, description: message)
            return
        }
        
        imagePicker.sourceType = .camera
        present(imagePicker, animated: true)
    }
    
    private func openPhotoLibrary(_ action: UIAlertAction) {
        guard UIImagePickerController.isSourceTypeAvailable(.photoLibrary) else {
            let title = "앨범을 사용할 수 없습니다."
            let message = "앨범을 사용할 수 있는 환경인지 확인해주세요!"
            presentAcceptAlert(with: title, description: message)
            return
        }
        
        imagePicker.sourceType = .photoLibrary
        present(imagePicker, animated: true)
}
```

2022-01-24 10:05 UTC, smart8612 commented on OpenMarket/OpenMarket/Controller/ProductPage/ProductPageViewController.swift
> +        guard let topViewController = destination.topViewController as? ProductCreateViewController else {
* 상품 목록 화면에서 상단에 추가 버튼을 클릭했을 떄 넘어가는 ViewController가 있을 때, 해당  ViewController를 재사용하기 좋게 만들어보고자하는 목적으로 프로그램 적 방법을 통해 화면 전환을 구현하게 되었습니다. 
* 이번 리팩토링에서 중복되는 화면 혹은 구현에 대해서 nib를 활용한 템플릿 뷰를 구현하였으며, 새로운 ViewController에서 재사용할 View를 얹는 방법으로 중복구현을 막고자 하는 방식을 채택해보았기 때문에 현재 부분의 코드는 제거되었습니다.

2022-01-24 10:06 UTC, smart8612 commented on OpenMarket/OpenMarket/Controller/ProductPage/ProductPageViewController.swift
> +        guard let topViewController = destination.topViewController as? ProductCreateViewController else {
![Screen Shot 2022-01-24 at 7 06 18 PM](https://user-images.githubusercontent.com/25794814/150762707-2135a95b-0ec1-4178-adee-277935caac80.png)

2022-01-24 10:08 UTC, smart8612 commented on OpenMarket/OpenMarket/Utility/Extension+UIKit.swift
> +import UIKit
좋은 팁 감사드립니다! 스텝 투를 구현해보면서 UIKit 클래스에 대한 익스텐션 구현이 늘어나는 문제점을 조금더 경험해보고 파일 분리해보는 시간을 가져보고자 합니다 🥳

2022-01-24 11:19 UTC, smart8612 commented
이번 리팩토링에서 핵심 기조는 다음과 같습니다. 
1. ViewController가 더 적은 일을 하도록 나누고자 노력했습니다.
    - Delegate 객체, 모델 객체, 네트워크 객체 등 좀더 세밀하게 역할을 나누었습니다.
    - 공통적으로 사용되는 기능의 경우 extension을 통해 공통 모듈로 분리해주었습니다.
2. 상품수정, 상품 등록과 같이 공통의 View 를 사용하는 경우 별도의 View nib 를 통해 템플릿을 생성하여 재사용성을 높히고자 노력했습니다.
    - 스토리보드는 전체 화면의 전개에 관한 Overview를 보여줄 수 있는 수단으로써 장점이 있습니다.
    - nib를 통한 템플릿 뷰를 선언해주는 것은 재사용이 용이한 View를 작성하는 수단으로써 장점이 있습니다. (반면 이야기 전재를 담아내기 어렵습니다.)
    - 코드를 통한 View 작성 방식은 위 방법으로 구현하기 어려운 화면 구성을 구현할 수 있다는 장점이 있지만 코드가 나타내는 화면 구성을 이해하기 어렵다는 단점이 있습니다.
    - 위 고민 끝에 nib로 만든 재사용 성이 높은 View를 스토리보드 상의 Scene에 프로그래밍 방식을 통해 SubView를 추가시켜주는 방식을 사용하게 되었습니다.
    -  다음 스텝에서 새로운 화면을 구성할 때 기존에 nib로 정의한 View를 손쉽게 생성할 수 있게되었습니다.
    -  상품 수정에 관한 ViewController를 구현할 떄에도 공통기능을 정의한 ProductUpdateViewController를 상속하여 정의하면 공통 모듈을 최대한 재사용할 수 있는 구조가 됩니다!
3. 상품 등록 과정에서 문제가 발생할 경우 사용자가 어떤 행위를 취해야 하는지 알림창을 통해 알려줄 수 있도록 구성하였습니다.
4. 이전에 이미지 압축 기능을 구현하지 못하여 카메라로 찍은 고해상도의 이미지가 업로드 되지 않는 현상을 해결하였습니다.

---

한편 여전히 프로젝트에 잔류하고 있는 문제점이 있습니다. 
1. AppConfigure에 작성해둔 사용자 식별정보를 현재의 경우 어떤 방식으로 관리해보는 것이 좋을지 여전히 고민입니다.
    - 사용하는 순간에는 사용자 정보를 메모리에 올려두어야 활용할 수 있는만큼 전역 변수가 아닌 방법 중에는 파일의 형태로 관리하다가 필요할 떄 불러오는 방식을 염두해보고 있습니다 (키체인을 활용해보는 방안)

2022-01-28 08:42 UTC, smart8612 commented
[주요 수정 사항 입니다!]
1. 상품 정보, 상품 수정, 상품 세부 정보, 상품 제거 등의 핵심 데이터 및 서비스 로직을 관할하는 공통의 모델로 ProductModelManager 클래스를 정의하였습니다.
2. 상품에 관한 전반적인 네트워크 통신을 관할하는 ProductNetworkManager 객체에 NSCache를 활용하여 이미지 캐싱을 구현하였습니다.
    - 이미지 정보의 캐싱 정보가 중복되지 않도록 해당 객체를 싱글턴 인스턴스로 사용하고 있습니다.
    - 즉, 각 모델이 네트워크 매니저의 싱글턴 인스턴스를 참조하여 사용하며, 그에 따라 앱 내부에서 공통으로 이미지 캐싱 정보를 사용하게 되었습니다.
3. 동일한 모델 데이터에 대하여 각 화면에 알맞은 모습으로 변환시켜주는 모델 객체로써 각 화면에 관한 ViewModel로 사용하였습니다.
    - 각 화면에서 자료를 보여주는 방법을 지정해주고, 사용자의 의도가 담긴 이벤트가 발생했을 때, 의도를 해석하여 서비스 로직으로 처리해줍니다.
4. 상품수정과 상품 등록 뷰컨트롤러에 대한 키보드 처리 등의 공통 기능을 클래스 상속을 활용하여 구현해보았습니다.
    - ProductUpdateViewController에서 상품 갱신에 필요한 키보드 처리 등의 공통 기능을 구현하였습니다.
    - 이를 상속받아 구현한 상품 수정 뷰컨과 상품 등록 뷰컨은 이미지 등록 가능 여부로 구현이 갈리게 되었습니다.
5. 상품 수정, 상품 등록과 같은 공통 뷰에 관한 중복 구현을 방지하기 위해, XIB 및 커스텀 클래스를 활용하여 모듈화 시켜주었습니다.
    - 지난번 말씀드린 스토리보드, XIB, 코드 방식의 UI 구현의 이점을 최대한 활용하는 것이 목표였습니다.
    - 스토리보드를 통해 앱의 전체적인 화면 구성을 설명하고 실제 화면(뷰)는 XIB를 통해 모듈화된 뷰를 사용하였으며, 협업시 코드 충돌을 최소화시키기 위해 가능한 뷰를 뷰컨의 뷰계층에 추가하는 작업 등을 코드로 구현해주었습니다.
    - 이와 비슷한 뷰의 재사용 예시는 상품 명단의 컬렉션뷰 셀의 커스텀 클래스를 정의해준 부분과, 이미지 페이지네이션 모듈을 (imageSlider) 를 구현한 부분이 포함되어있습니다.
    - 특히, 뷰가 데이터를 가지면 안된다는 측면에서 delegation (데이터 소스) 방식을 활용하여 뷰와 데이터 로직을 분리시켜주었습니다.

2022-01-28 08:48 UTC, smart8612 commented
![RPReplay_Final1643359439](https://user-images.githubusercontent.com/25794814/151515703-668271dd-2386-4fb5-944e-e7a67dedb417.gif)

2022-01-30 05:11 UTC, corykim0829 requested changes
2주간 정말 수고 많으셨습니다 신나!

이번 프로젝트 기간 동안 다양한 접근 방법을 고려해보시고 코드를 깊게 고민해보고 직접 구현까지 하시는 모습 정말 감명깊었어요!

뷰 구현도 모두 고민해보고 직접 해보신 부분도 아주 좋았습니다 👍

---

이번 작업에서는 ViewModel을 추가하셔서 로직을 변경하셨는데, 컨트롤러의 책임을 많이 덜어내려고 하시는게 보이는 좋은 시도였습니다. 👍
제가 리뷰에서도 언급했지만, 뷰모델은 모델을 가지고 관리하여 뷰에게 알맞은 데이터를 넘겨주는 역할입니다. 그렇기 때문에 뷰모델이 뷰를 가지고 있거나 직접 뷰를 업데이트하면 뷰모델의 성격을 잃게 됩니다.
이 부분을 잘 고려해보시고 리팩토링 해보면 좋을 것 같습니다!

아래 링크에서 뷰모델, 뷰, 모델 간의 역할을 한번 확인해보면 좋을 것 같아요!
https://www.vadimbulavin.com/modern-mvvm-ios-app-architecture-with-combine-and-swiftui/

2022-01-30 05:11 UTC, corykim0829 commented on OpenMarket/OpenMarket/Controller/ProductDetail/ProductDetailViewModel.swift
> +class ProductDetailViewModel {
ViewModel은 데이터 로직만 가지고 직접적으로 View는 업데이트 하지 않도록 구조를 변경해보세요!

2022-01-30 05:11 UTC, corykim0829 commented on OpenMarket/OpenMarket/Controller/ProductDetail/ProductDetailViewModel.swift
> +    }
음 이렇게 내부에서 한번 더 처리해서 넘겨주는 거면, 프로토콜에서 변수로 선언하는게 더 깔끔할 것 같아요!
그리고 UIView 타입을 파라미터로 받는 이유가 따로 있나요? 사용하고 있지도 않고, 뷰모델에 뷰단이 필요할 일이 없어보입니다!

2022-01-30 05:11 UTC, corykim0829 commented on OpenMarket/OpenMarket/Controller/ProductUpdate/ProductUpdateViewController.swift
> +    private func keyboardWasShown(_ notification: Notification) {
능동적인 표현으로 하는게 조금 더 읽기 좋아요! 참고하세요 :)
viewDidLoad, viewDidAppear를 참고해봐도 좋을 것 같아요

2022-01-30 05:11 UTC, corykim0829 commented on OpenMarket/OpenMarket/Controller/ProductDetail/ProductDetailViewModel.swift
> +    private let model: ProductModelManager
변수명은 model인데 ModelManager가 있는게 조금 어색하네요. ViewModel로 바꾸면서 ModelManager의 역할을 ViewModel이 하게 됩니다. 여기 model 변수는 정말 모델만 가지고 있도록 변경해주세요!

2022-01-30 05:11 UTC, corykim0829 commented on OpenMarket/OpenMarket/Model/ProductNetworkManager.swift
> +    static let shared = ProductNetworkManager()
`이미지 정보의 캐싱 정보가 중복되지 않도록 해당 객체를 싱글턴 인스턴스로 사용하고 있습니다.`라고 하셨는데, 이 부분은 직접 확인을 해보셨나요?
싱글톤 여부에 따라서 캐싱이 되는지 한번 확인해보면 좋을 것 같아요!

2022-01-30 05:11 UTC, corykim0829 commented on OpenMarket/OpenMarket/View/ProductPage/OpenMarketCollectionViewCell.swift
> +class OpenMarketCollectionViewCell: UICollectionViewCell {
코드로 구현한 부분 아주 좋습니다 :)

2022-01-30 05:11 UTC, corykim0829 commented on OpenMarket/OpenMarket/View/ImageSliderView/ImageSlider.swift
> +    private let xibName = "ImageSlider"
String(describing:) 함수를 사용하면 nibName 처리가 더 수월해요~ 참고하세요!

2022-01-30 05:11 UTC, corykim0829 commented on OpenMarket/OpenMarket/Controller/ProductUpdate/ProductModify/ProductModifyViewController.swift
> +        viewModel.viewDidLoad()
이런 부분도 ViewModel에서 뷰단 코드가 제거되면 필요없는 코드 같아요.

2022-03-24 13:50 UTC, closed without merging