Step1 오픈마켓 찌루루 & 소대
yagom-academy/ios-open-market pull request #11
Opened 2021-02-01 04:03 UTC by zdodev

안녕하세요 @AppleCEO 마지막 PR Step 1 리뷰 부탁드립니다!

1. 모델 타입 구현
- request, response body 데이터가 필요한 부분은 Decodable 프로토콜을 사용하여 구현해보았습니다.
- API response body(아이템 조회, 수정, 등록의 응답)은 ItemSpecificationResponse 모델 하나를 사용해보았습니다.

2. 네트워크 통신 구현
- URLRequest 구현부와 Datatask 부분을 분리하여 구현해보았습니다.
- HTTPRequest 타입에서 API에 맞는 URLRequest을 만들고 NetworkLayer 타입에서 전송을 담당합니다.
- 상품 등록 및 상품 수정 시 request를 multipart/form-data 형태로 만들어서 전송합니다.

3. API 테스트 구현
- 각 API의 테스트를 구현해보았습니다.
- 상품 삭제의 경우 id 파라미터 값을 변경해야 합니다.

코드를 구현하면서 가장 고민을 한 부분이 네트워크 레이어를 어떻게 구성할지 가장 큰 고민이었습니다. HTTP 전송 데이터를 만들고 응답 데이터 처리 부분을 좀 더 깔끔하고 더 적은 코드로 사용할 수 없을까 싶었는데, 전송 시 전달해야 할 데이터(경로, body data,header)와 응답받은 데이터를 구체적으로 명시해야 하다보니 더 깔끔하지 못한 코드를 작성한 것 같습니다. 어떻게 하면 더 깔끔하게 작성할 수 있는지 이에 대한 피드백 부탁드립니다!!🙇‍♀️🙇‍♂️

2021-02-01 04:28 UTC, AppleCEO requested changes
고생하셨습니다 찌루루 & 소대
커밋 메시지가 더 명확하면 좋을 것 같습니다.
고민에 대해서는 어떤 부분이 깔끔하지 않다고 생각하시는지 궁금합니다.
적은 코드보다 이해하기 쉬운 긴 코드가 더 좋은 코드라고 생각합니다.
한발 짝 뒤에서 바라보면 개선할 점들이 보일 것 같습니다.
화이팅입니다!

2021-02-01 04:28 UTC, AppleCEO commented on OpenMarket/OpenMarket/HTTPRequest.swift
> +struct HTTPRequest {
구조체 이름으로 좀 부적합한 것 같습니다.
이런 포괄적인 이름은 이미 어디에서 쓰이고 있을 수 있어서 충돌이 일어날 수 있습니다.

2021-02-01 04:28 UTC, AppleCEO commented on OpenMarket/OpenMarket/HTTPRequest.swift
> +                 .deleteItem(let id):
보통 케이스는 한 줄에 작성을 합니다.
이렇게 세줄로 나눴을 때 장점과 단점은 무엇일까요?

2021-02-01 04:28 UTC, AppleCEO commented on OpenMarket/OpenMarket/HTTPRequest.swift
> +        }
가드 렛 구문이 과하게 반복되고 있는 것 같네요.
어떤 식으로 개선할 수 있을까요?

2021-02-01 04:28 UTC, AppleCEO commented on OpenMarket/OpenMarket/HTTPRequest.swift
> +        }
if let 구문도 계속 반복되고 있네요.
함수의 길이가 20줄 이상 길어지면 함수가 하나의 동작만을 하지 않는 것으로 의심할 수 있습니다.
어떻게 개선할 수 있을까요?

2021-02-01 04:28 UTC, AppleCEO commented on OpenMarket/OpenMarket/HTTPRequest.swift
> +    func itemList(_ page: Int) -> URLRequest? {
메소드 이름은 보통 동사로 시작합니다.
itemList 라는 메소드명은 프로퍼티로 착각할 수 있을 것 같네요!

2021-02-01 04:28 UTC, AppleCEO commented on OpenMarket/OpenMarket/HTTPRequest.swift
> +    func itemSpecification(_ id: Int) -> URLRequest? {
옵셔널로 반환값을 지정해보셨군요 👍

2021-02-01 04:28 UTC, AppleCEO commented on OpenMarket/OpenMarket/Model/ItemModificationRequest.swift
> +         password: String) {
이렇게 줄바꿈을 하면 오히려 가독성을 헤칠 수 있습니다.
구조체인데 초기화 함수를 선언한 이유가 있나요?

2021-02-01 04:28 UTC, AppleCEO commented on OpenMarket/OpenMarket/ViewController.swift
> -
사용하지 않는 코드를 지우는 것은 아주 좋은 습관입니다! 🥇

2021-02-01 04:28 UTC, AppleCEO commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    func testRequestItemList() throws {
테스트의 이름은 내용을 안보더라도 알 수 있을 정도로 명확해야 합니다.
아이템 리스트를 요청해서 어떤 결과를 예상하는지도 이름에 적혀있으면 좋겠네요~

2021-02-01 14:27 UTC, jae57 commented on OpenMarket/OpenMarket/Model/ItemModificationRequest.swift
> +         password: String) {
해당 객체는 수정시에 request body 로 쓰이는 객체인데요, 기본 초기화함수로는 수정할 값을 제외한 나머지는 일일이 nil을 넣어서 생성해줘야하는데 이러한 번거로움을 덜고자 optional 인 값에 대해 기본값 nil 을 세팅해주는 초기화함수를 선언했습니다.

2021-02-02 04:10 UTC, zdodev commented
안녕하세요. @AppleCEO 빠른 리뷰 감사합니다!

리뷰 내용참고하여 수정해보았습니다 리뷰 부탁드립니다!

구조체 이름으로 좀 부적합한 것 같습니다. 이런 포괄적인 이름은 이미 어디에서 쓰이고 있을 수 있어서 충돌이 일어날 수 있습니다.
- HTTPRequest라는 이름이 타입의 역할을 구체적으로 표현하고 있지 못하다고 생각하여 OpenMarketHTTPRequest로 수정해보았습니다.

보통 케이스는 한 줄에 작성을 합니다. 이렇게 세줄로 나눴을 때 장점과 단점은 무엇일까요?
- 가독성의 차이가 있다고 생각합니다. 한 줄이 너무 길어질 경우 세로로 작성했을 때 가독성이 더 좋았었습니다.

가드 렛 구문이 과하게 반복되고 있는 것 같네요. 어떤 식으로 개선할 수 있을까요?
- 옵셔널을 최대한 걷어내고, 명령문을 일일이 나열하는 것이 아닌 반복문을 사용하여 간결하게 표현해보았습니다.

if let 구문도 계속 반복되고 있네요. 함수의 길이가 20줄 이상 길어지면 함수가 하나의 동작만을 하지 않는 것으로 의심할 수 있습니다. 어떻게 개선할 수 있을까요?
- 위와 같이 옵셔널을 최대한 걷어내고, 반복문을 사용해보았습니다.

메소드 이름은 보통 동사로 시작합니다. itemList 라는 메소드명은 프로퍼티로 착각할 수 있을 것 같네요!
- 동사형으로 메서드명을 수정해보았습니다.

테스트의 이름은 내용을 안보더라도 알 수 있을 정도로 명확해야 합니다. 아이템 리스트를 요청해서 어떤 결과를 예상하는지도 이름에 적혀있으면 좋겠네요~
- 테스트 이름을 작성하는 법을 참고하여 테스트 이름을 수정해보았습니다.

2021-02-02 04:23 UTC, AppleCEO approved these changes
찌루루 & 소대 고생하셨습니다
고민한 점들이 많이 보이는 코드였습니다.
다음 스텝 진행하면서 코멘트들 참고해주세요.

2021-02-02 04:23 UTC, AppleCEO commented on OpenMarket/OpenMarket/OpenMarketHTTPRequest.swift
> +            }
저는 이 방식을 선호합니다.
```swift
case .searchItem(let id), 
     .modifyItem(let id), 
     .deleteItem(let id):
    return "/item/\(id)"
}
```
이 방식은 빠르게 보다가 뎁스가 하나 들어갔다가 왜 나오지? 라고 의심할 수 있습니다.

2021-02-02 04:23 UTC, AppleCEO commented on OpenMarket/OpenMarket/Model/ItemModificationRequest.swift
> +    init(title: String? = nil, descriptions: String? = nil, price: Int? = nil, currency: String? = nil, stock: Int? = nil, discountedPrice: Int? = nil, images: [Data]? = nil, password: String) {
이 부분 struct 에 기본값을 넣어주는 방식으로 초기화 함수를 제거하는 것은 어떨까요?

2021-02-02 04:23 UTC, merged