오픈마켓2 [STEP 1] Jiseong, chacha
yagom-academy/ios-open-market pull request #110
Opened 2022-01-20 14:02 UTC by ChaminLee

안녕하세요 도미닉! @AppleCEO 
오픈마켓 2 Step 1(브랜치는 Step3) 구현 완료하여 PR보내드립니다. 
이번에도 잘 부탁드리겠습니다.🙇🏻‍♂️

ViewController의 역할을 최대한 분리해주고자 노력했으며, 중복된 코드 또한 줄여보고자 했습니다!

---

### 고민했던 점 

#### 1. 상품 등록/수정 `ViewController`의 공통 기능 구현 

컨테이너 뷰의 레이아웃을 잡는다거나, alert를 띄우는 등 등록/수정 ViewController에서 공통적으로 필요로하는 기능들을 프로토콜 기본구현으로 제공해봤습니다. 다만 Objective-C 메서드들은 프로토콜 기본 구현이 불가하다는 점에 한계를 직접 경험해본 것 같습니다. 이에 상속과 프로토콜 기본 구현 관련하여 고민을 해봤습니다.

- 상속
    - 다중 상속이 불가능하다
- 프로토콜 기본 구현 
    - Objective-C 프로토콜은 기본 구현이 불가능하다.

(아래 질문 3번과 이어지는 부분이어서 아래 질문에 더 작성해두겠습니다!)

#### 2. `UIImage` 이미지 크기 조정 

UIGraphics를 사용하여 이미지 크기를 조절해주었습니다. `UIGraphicsBeginImageContextWithOptions()` 메서드를 호출하여 비트맵을 만들고 `UIImage.draw(in:)`로 원하는 사이즈만큼 줄인 뒤, `UIGraphicsGetImageFromCurrentImageContext()` 메서드를 통해 크기가 조정된 이미지를 얻었습니다. 이후 `UIGraphicsEndImageContext()`를 호출하여 비트맵을 제거 처리해주면서 이미지 크기를 조정하는 로직을 구현했습니다. 

#### 3. 키보드 사용에 따른 ScrollView inset 조정

textField나 textView에 텍스트 작성시 화면이 작은 iPod Touch의 경우 키보드가 이벤트 발생 뷰를 가려버리는 문제가 있어 키보드가 올라옴에 따라 스크롤 뷰의 `contentInset.bottom`을 키보드의 높이만큼 지정하여 키보드가 텍스트필드나, 텍스트뷰를 가릴 일이 없도록 구현하였습니다.

#### 4. View와 ViewController 분리 

뷰와 뷰컨트롤러의 책임을 덜기위해 둘 사이에 `ProductRegisterManager`라는 객체를 생성하였습니다.

매니저는 뷰를 알고있어 뷰의 특정 속성값을 알 수 있고, 뷰컨트롤러는 매니저를 알고있기에 매니저가 구한 뷰의 속성값을 받기만 하면 되게끔 하여 뷰컨트롤러의 책임을 덜어주었습니다.

#### 5. 이미지 추가/삭제 

이미지의 경우 5개까지 추가 가능하기에, 추가된 이미지가 5개가 되면 추가 버튼을 `isHidden = true`하여 숨겨주었습니다. 이 부분은 숨김 처리하는 것 보다, 추후에 alert를 주어 최대 등록 개수를 알려주거나, 추가 버튼 내에서 현재 등록된 개수/최대 개수를 나타내주는 방식으로 수정하면 좋을 것 같다고 생각했습니다. 

또한 이미지를 등록하는 과정에서 추가한 이미지를 제거할 수 도 있어야 한다고 생각해서 제거 버튼을 구현해주었습니다. 이 부분은 `UIImageview`와 `UIButton`을 가지는 컨테이너 뷰를 만들어서 커스텀하게 구현해주었습니다. 

### 궁금한 부분 

#### 1. 이미지의 크기를 고정값(상수)로 주는 것이 좋은 방법인가요?

이미지의 크기에 고정값을 주어 개발자가 설정한 크기로만 이미지가 그려지도록 하는 것에서 dynamic type에 대해 동적이지 못하다는 생각이 들어 위와 같은 궁금증을 가지게 되었습니다. 크기가 절대 변하지 않도록 할 것인 뷰의 경우는 고정값을 주어도 되는지 궁금합니다.

통상 현업에서는 디자이너분이 모든 기기의 해상도에서 고려한 고정된 이미지 크기를 정해주시는지, 혹은 이 또한 개발자가 기기별로 확인하여 그 크기를 정하는 것인지도 궁금합니다.

#### 2. 이미지 용량 제한에 대한 이미지 리사이징 해결책이 바람직한가요?

등록 가능한 이미지 용량이 300kb이라는 것을 보고, 이미지를 리사이징 해주면 되겠다고 생각을 했었습니다. 다만 이미지가 특정한 크기로 리사이징 되면, 추후에 크게 보여야 할 부분에서 문제가 생길 것 같은데 이 문제를 해결하기 위해서 리사이징이 아니라 화질을 낮춘다거나 다른 방식을 사용했어야 하는지 궁금합니다! 

또 실제로 현업에서는 이미지 용량과 관련해서 주로 어떤 방식으로 처리하고 있는지도 궁금합니다!

#### 3. 두 개 이상 view controller에서 동일한 기능을 필요로 한다면 보통 어떤 식으로 공통화해주는지 궁금합니다. 

앞서 고민한 내용에서 언급한 것 처럼 공통되는 일반 메서드들은  protocol 기본구현으로 해결해주었습니다. 하지만 Objective-C 메서드의 경우(`UITextFieldDelegate`, `UITextViewDelegate`에서 지원하는 기능같은 것들)는 프로토콜 기본구현이 불가능하기 때문에 상속으로 해결해주려고 생각해봤는데 이 아이디어가 적합한 방법인지 궁금합니다. 

이에 아직은 중복된 코드들을 전부 공통화해주지는 못한 것 같은데 주로 이러한 상황에서 상속과 프로토콜 기본 구현을 통해 공통화를 많이 해주시는지 혹은 다른 방법이 있다면 어떤 식으로 구현해주시는지 궁금합니다!

#### 4. Delegate pattern이 적합하게 사용되었는지 궁금합니다. 

`ProductRegisterManager`와 `ProductRegisterViewController`간에 image picker 뷰를 띄워주기 위해 사용하였고, `ImagePickerController`와  `ProductRegisterViewController`간에 선택된 이미지를 등록시켜주기 위해 delegate pattern을 사용하였습니다. 

이 두 경우 delegate pattern이 바람직하게 사용된 것인지, 아니라면 개선할 부분이 있을지 궁금합니다!

2022-01-22 01:12 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다
@ChaminLee & @yim2627  고생하셨습니다.
어려운 과제였을텐데 잘 해내셨군요!

질문에 대한 답변
1. 이미지의 크기를 고정값(상수)로 주는 것이 좋은 방법인가요?
- 상황에 따라 다를 것 같습니다. 예를 들어 가장 위에 왼쪽에 엑스 버튼 같은 것은 고정된 값을 줍니다. 셀 안에 이미지같은 가변적으로 바뀌어야하는 이미지는 오토레이아웃을 줍니다. 보통 컬렉션 뷰에서 셀의 크기를 화면의 1/2, 1/3 등으로 주는데요. 그렇게 만들어진 셀에 오토레이아웃으로 안 쪽으로 10 들어온 곳에 오토레이아웃을 걸어서 셀의 크기에 따라 이미지의 크기가 가변적으로 바뀌게 구성합니다.
2. 이미지 용량 제한에 대한 이미지 리사이징 해결책이 바람직한가요?
- 케이스 바이 케이스일 것 같은데요. 저희는 압축한 이미지로 업로드하고 있었습니다. 그래도 이미지의 용량이 커서 최근에는 width, height 중에 큰 쪽을 기준으로 1080이 넘으면 큰 쪽을 1080에 맞추고 다른 쪽은 큰 쪽이 줄어든 비율만큼 줄여서 업로드하고 있습니다. 해상도를 줄여도 용량이 확실히 줄어드는 효과가 있더라고요. 특별히 현업에서 정해진 방법은 없고 회사마다 다를 것 같습니다.

3. 두 개 이상 view controller에서 동일한 기능을 필요로 한다면 보통 어떤 식으로 공통화해주는지 궁금합니다.
- 상속을 많이 사용하는 것으로 알고 있습니다. 스타일쉐어에 경우 자주 쓰는 기능들을 추가한 뷰컨트롤러를 만들어놓고 거의 모든 뷰컨트롤러를 만들 때 그 뷰컨트롤러를 상속 받아서 사용하기도 하더라고요. 이 부분은 조금 어려운 내용도 많을 것 같아서 현재는 프로토콜을 많이 사용해보는 것으로도 괜찮지 않을까 생각이 드네요.

4. Delegate pattern이 적합하게 사용되었는지 궁금합니다.
- 네 이렇게 많이 사용합니다. 패턴은 보통 정답이 있는 것이 아니라 참고할 만한 방식이라서요. 이 패턴에 대해 이해하고 있는 방식으로 코드를 작성해서 의도한 대로 동작하면 잘 된 것이라고 생각합니다~


1. 이미지의 크기를 고정값(상수)로 주는 것이 좋은 방법인가요?

2022-01-22 01:12 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controllers/ImagePickerController.swift
> +class ImagePickerController: UIImagePickerController {
어떤 이미지를 선택하는지 이름이 더 길어지면 좋겠네요!
보통 기본으로 생성되는 ViewController 같은 이름은 명확하지 않아서 수정해주면 어떤 역할을 하는 이미지 피커 컨트롤러, 뷰컨트롤러인지 이름으로 예측할 수 있어서 좋습니다~

2022-01-22 01:12 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controllers/ImagePickerController.swift
> +}
딜리게이트를 만들어보셨군요~ 버튼을 눌렀을 때 동작을 넘길 때 등 어떤 동작을 다른 객체에게 위임할 때 좋은 구조이죠. 👍 
보통 프로토콜도 다른 파일로 분리해줍니다. 이 프로토콜도 다른 파일로 분리하면 좋을 것 같네요!

2022-01-22 01:12 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controllers/MainViewController.swift
> -
의미없는 공백을 지워준 것 좋습니다~ 💯

2022-01-22 01:12 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controllers/ProductModifyViewController.swift
> +        return true
else가 없는 것 좋네요! 🔢

2022-01-22 01:12 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controllers/ProductModifyViewController.swift
> +
예전에 비해 의미없는 공백이 줄었네요! 🥇

2022-01-22 01:12 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controllers/ProductRegisterManager.swift
> +            .map { ImageData(fileName: "\(UUID().uuidString).png", data: $0, type: .png) }
리턴 아래에 코드가 있는 것은 어색한 것 같네요! 다른 상수에 이 내용들을 넣고 리턴에서 그 상수 하나만 리턴해주는 것도 좋겠네요!
너무 여러 줄이 엮여있는 것 같은데 하나마다, 불필요하다고 생각하면 의미있는 줄 숫자만큼 묶어서 상수에 할당해줘도 좋을 것 같습니다.
예를 들면
```swift
let productCustomView = productInformationView.imageStackView.arrangedSubviews.filter { $0 is ProductImageCustomView }
let ~ = productCustomView.compactMap { $0 as? ProductImageCustomView }
...
```
이런 식으로요 ㅎㅎ
그리고 저는 현업에 가기 전까지는 축약형보다 기본형을 활용해보는 것을 추천합니다.
완전히 구조를 이해하지 못하고 $0 를 넣어서 어떻게 하다보면 코드가 잘 실행될 수 있는데요.
아직 기본형으로 어떤 값을 어떤 구조로 넣어야하고 이 값을 어떻게 이용할 수 있는지 긴 코드로 구조를 보는 것에 먼저 익숙해지고 그 뒤에 완전히 이해하고 자유롭게 쓸 수 있게 되면 필요에 따라 줄였다가 늘렸다가 사용하는게 좋을 것 같아요~
참고로 .compactMap 이런 식으로 입력하고 떠블 클릭을 하면 기본형이 자동으로 만들어집니다!
![Jan-22-2022 09-26-09](https://user-images.githubusercontent.com/47517256/150616508-c1b9280c-4544-4a87-8a76-5401c853f322.gif)

2022-01-22 01:12 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controllers/ProductRegisterManager.swift
> +        return ProductRegisterInformation(name: name, descriptions: descriptions, price: price, currency: currency, discountedPrice: discountedPrice, stock: stock, secret: secret)
리턴에서 생성자를 사용하는 것보다 위에서 생성하고 리턴에 넣어주는 것이 좋겠네요!
리턴은 최대한 간결하게 유지하는 것이 좋습니다~

2022-01-22 01:12 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controllers/ProductRegisterViewController.swift
> +class ProductRegisterViewController: UIViewController, ProductManageable {
ProductManageable 프로토콜 관련 코드들을 extension 으로 빼내보는 것은 어떨까요? ㅎㅎ

2022-01-22 01:12 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controllers/ProductRegisterViewController.swift
> +            presentAlert(viewController: self, title: "입력된 상품 가격이 없습니다.", message: "한 자리 이상의 상품 가격을 입력해주세요.")
오류 메시지들을 열거형으로 따로 모아보면 어떨까요? 🔢

2022-01-22 01:12 UTC, AppleCEO commented on OpenMarket/OpenMarket/Extensions/UIImage+resize.swift
> +    }
메소드명이 적절하네요~ 💯

2022-01-22 01:12 UTC, AppleCEO commented on OpenMarket/OpenMarket/Extensions/UIImage+resize.swift
> +        return resizedImage
이 부분 if let 을 사용해보면 어떨까요?
guard let 을 사용한 코드와 if let 을 사용한 코드 중 어떤 코드가 더 좋아 보이시나요

2022-01-22 01:12 UTC, AppleCEO commented on OpenMarket/OpenMarket/Extensions/UIView+firstResponder.swift
> +        }
부정의 부정이 또 나왔군요!
if 를 쓰면 읽기 좋을 것 같은데요~

2022-01-22 01:12 UTC, AppleCEO commented on OpenMarket/OpenMarket/Views/CustomTextField.swift
> +        self.inputAccessoryView = hasToolBar ? createToolBar() : nil
생성하는 코드도 있으니 삼항 연산자가 좀 복잡해보이네요.
개선해 볼 수 있을까요?

2022-01-22 01:12 UTC, AppleCEO commented on OpenMarket/OpenMarket/Views/ProductImageCustomView.swift
> +        }
기본형으로 바꿔볼 수 있을까요?
저는 $0 을 거의 사용하지 않아요!

2022-01-22 01:12 UTC, AppleCEO commented on OpenMarket/OpenMarket/Views/ProductImageCustomView.swift
> +        }
저는 forEach 보다 for in 이 읽기 쉽고 좋은 코드라고 생각이 드네요.
forEach 와 for in 각각 어떤 장점과 단점이 있을까요?
영어처럼 읽히는 코드는 어떤 코드일까요?

2022-01-22 01:12 UTC, AppleCEO commented on OpenMarket/OpenMarket/Views/ProductInformationView.swift
> +        }
view 라고 명확하게 이름을 정해서 사용한 것 좋습니다! 🥇

2022-01-24 06:07 UTC, ChaminLee commented on OpenMarket/OpenMarket/Controllers/ImagePickerController.swift
> +class ImagePickerController: UIImagePickerController {
말씀주신 것 처럼 기존 `ImagePickerController `에서 `ProductImagePickerController`로 변경하여 명확히 해주도록 하겠습니다

2022-01-24 06:15 UTC, yim2627 commented on OpenMarket/OpenMarket/Views/ProductImageCustomView.swift
> +        }
저희의 개인적인 생각으로는 가독성의 경우 크게 차이가 없지않을까... 생각이 들었습니다.
다만 축약형을 사용할 경우 가독성이 떨어질 수 있겠다 생각합니다.

forEach와 for in의 차이는 루프를 끊을 수 있냐 없냐라고 생각합니다.

for in 의 경우 반복문 내부의 조건에 부합하지않을 시 break를 하게된다면, 반복문 전체를 탈출해버리는 반면에 forEach의 경우 반복문 전체를 탈출하는 것이 아닌 해당 클로저를 탈출하는 것이기 때문에 또 다음 요소를 순회한다는 차이점이 있을 것 같습니다.

2022-01-24 06:20 UTC, yim2627 commented on OpenMarket/OpenMarket/Controllers/ImagePickerController.swift
> +}
PickerDelegate와 PickerPresenter를 파일 분리해주었습니다!

2022-01-24 06:40 UTC, ChaminLee commented on OpenMarket/OpenMarket/Controllers/ProductRegisterManager.swift
> +        return ProductRegisterInformation(name: name, descriptions: descriptions, price: price, currency: currency, discountedPrice: discountedPrice, stock: stock, secret: secret)
생성을 해두어 변수에 할당한 뒤에 해당 변수를 반환하는 방식으로 수정했습니다!

2022-01-24 06:40 UTC, ChaminLee commented on OpenMarket/OpenMarket/Controllers/ProductRegisterManager.swift
> +        return ProductRegisterInformation(name: name, descriptions: descriptions, price: price, currency: currency, discountedPrice: discountedPrice, stock: stock, secret: secret)
생성을 미리 해두어 변수에 할당한 뒤에 해당 변수를 반환하는 방식으로 수정했습니다!

2022-01-24 06:44 UTC, ChaminLee commented on OpenMarket/OpenMarket/Views/ProductImageCustomView.swift
> +        }
넵 수정했습니다!

2022-01-24 06:46 UTC, ChaminLee commented on OpenMarket/OpenMarket/Controllers/ProductRegisterManager.swift
> +            .map { ImageData(fileName: "\(UUID().uuidString).png", data: $0, type: .png) }
말씀주신 것 처럼 우선 축약형은 제거하였고, 의미 구분에 따라 변수를 생성하여 나누어주었습니다!

2022-01-24 06:47 UTC, ChaminLee commented on OpenMarket/OpenMarket/Controllers/ProductRegisterViewController.swift
> +            presentAlert(viewController: self, title: "입력된 상품 가격이 없습니다.", message: "한 자리 이상의 상품 가격을 입력해주세요.")
`AlertMessage` 열거형 타입을 생성하여 하드 코딩된 부분을 개선했습니다!

2022-01-24 07:10 UTC, ChaminLee commented on OpenMarket/OpenMarket/Extensions/UIImage+resize.swift
> +        return resizedImage
두 경우를 모두 고려해봤는데요! if let으로 하게 될 경우 `return nil`이 외부에 나오게 되는데 이러한 모습이 아니라 실제 기대되는 값(`resizedImage`)이 마지막 return에 오는 것이 더 읽기 좋다고 생각해서 유지하려고 합니다! 

어떻게 생각하시는지 궁금합니다!

2022-01-24 07:13 UTC, ChaminLee commented on OpenMarket/OpenMarket/Extensions/UIView+firstResponder.swift
> +        }
if문으로 변경하여 이중 부정문 수정하였습니다! 계속 유의해야겠네요..!

2022-01-24 07:24 UTC, AppleCEO commented on OpenMarket/OpenMarket/Extensions/UIImage+resize.swift
> +        return resizedImage
정답은 없는데요. 이런 경우에는 if let 이 좋을 것 같기도 하네요. 한 번 정도 사용되는 값이 있는 경우에 저는 if let 을 쓰는 편이에요. 이 값이 있는 경우 안 에 있는 것들을 실행하라는 것이 좀 명확하게 느껴져셔요. 그리고 이 안에서만 resizeImage 를 사용할 수 있으니 그런 것도 분명한 것 같아요.

```swift
if let resizedImage = UIGraphicsGetImageFromCurrentImageContext() {
      UIGraphicsEndImageContext()
      return resizedImage
}
return nil  
```

2022-01-24 07:27 UTC, AppleCEO commented on OpenMarket/OpenMarket/Views/ProductImageCustomView.swift
> +        }
영어처럼 읽히는 코드는 for in 이라고 생각해요
for view in [productImageView, deleteButton]
이건 거의 영어처럼 읽히죠~

2022-01-24 07:31 UTC, AppleCEO requested changes
로직만 확인해주세요~

2022-01-24 07:31 UTC, AppleCEO commented on OpenMarket/OpenMarket/Extensions/UIView+firstResponder.swift
> +        if !isFirstResponder {
이 부분 로직 상 if isFirstResponder { 로 되야되는 거 아닌가요? ㅎㅎ

2022-01-24 07:31 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controllers/ProductRegisterManager.swift
> +            }
길어지더라도 있어야할 것으로 예샹되는 곳에 코드들이 있는 것이 더 좋은 코드입니다.
이런 구조에도 익숙해져보면 좋겠네요!

2022-01-24 07:31 UTC, AppleCEO commented on OpenMarket/OpenMarket/Views/CustomTextField.swift
> +        }
오호... 보기 좋습니다!

2022-01-24 07:37 UTC, merged