오픈마켓1 [STEP 2] 호랭이
yagom-academy/ios-open-market pull request #111
Opened 2022-01-21 07:52 UTC by horeng2

@ryan-son 라이언 안녕하세요!
응원과 도움 많이 주신 덕분에 늦었지만 오픈마켓1 스텝2 PR을 올리게 됐습니다 😊

진행하면서 막히는 부분이나 힘든 부분이 꽤 있는데, 
대부분 코드에 대한 사용법과 개념 이해부족으로 인한 것들이라서
여기저기 부딪혀가면서 사정없이 구르는 중입니다...☠️

PR은 코드의 대략적인 흐름과 고민한점, 조언이 필요한 부분, 트러블슈팅 위주로 적었습니다.
리뷰 잘부탁드리겠습니다! 감사합니다.

---

## 코드의 흐름

코드의 흐름을 간단하게 요약하자면 아래와 같습니다.

1. 뷰컨트롤러의 `viewDidLodad`에서 `getDecodedData` 실행으로 `productListData`에 데이터를 저장합니다.
    
    → `getDecodedData`메서드는 ViewController에 있으며, 내부에서 `getData`메서드를 호출하여 뷰컨트롤러의 `ProductList`라는 객체에 데이터를 디코딩하여 입력하는 역할입니다.
    
    → `getData`메서드는 URLSessionProvider클래스에 있으며, url을 이용한 데이터통신으로 데이터를 받아옵니다.
    
    → 데이터 저장 후 메인스레드를 이용하여 `reloadData`를 실행합니다.
    
2. 뷰컨트롤러의 SegmentedController의 상태값에 따라 `collectionView(cellForItemAt)`메서드에서는 ListCell 또는 GridCell을 반환하고, FlowLaout에 필요한 값들도 각각 다르게 반환합니다.
3. ListCell, GridCell 클래스 내부에서 `awakeFromNib`을 이용하여 셀의 레이어를 설정하고, 셀 내부 요소에 데이터값을 입력합니다.

## 고민한 점

- 데이터를 비동기로 불러온 뒤 바로 셀이 생성되어서 셀의 데이터에 nil값이 들어가는 문제를 해결하기위해 고민했고, 데이터요청을 한 뒤 메인스레드를 이용해서 `reloadData()`를 하는 방법을 사용했습니다.
- Cell 클래스의 `updateCell`메서드에서 이미지 불러오기를 완료하기 전에 셀에 값이 들어가는 것을 방지하기 위해서 이미지를 이미지뷰에 넣어주는 부분을 메인스레드 async로 실행하도록 하였습니다.
- 셀의 레이어를 설정하는 코드가 `collectionView(cellForItemAt)`메서드 내부에 있었는데, 셀이 디큐될 때마다 이 코드가 실행되어 프로그램이 무거워지는 것을 방지하기 위해서 Cell타입 내부의 `awakeFromNib()`메서드로 이동하였습니다.
- 데이터통신으로 받아온 이미지를 화면에 나타낼 때, 에셋에서 불러올 때처럼 `Image(name:)`으로 한참 시도했다가 뭔가 이게 아니라는 것을 깨닫고....`Data(contentsOf: URL)` 형식으로 불러와서 사용했습니다.
- FlowLayout이 제대로 적용되지 않는 것에 대해서 고민하다가, flowLayout객체를 만들고 이를 콜렉션뷰객체에 할당해주어야 한다는 것을 알았습니다.

## 조언을 얻고 싶은 부분

콜렉션뷰를 리스트 형식으로 표현할 때, 테이블뷰를 사용할 때처럼 셀 사이에 경계선을 넣고싶었는데 전체 테두리를 하는 방법은 찾았지만 셀 아래에만 선을 넣는 방법을 찾지 못했습니다...일단은 UIView를 이용해서 넣었는데, 콜렉션뷰를 이용할 때 이와 같은 경우 사용할 수 있는 방법이 있을까요?

## 트러블슈팅

- 뷰 구현 시, 처음에는 컨테이너뷰를 사용하며 메인뷰컨-테이블뷰컨/콜렉션뷰컨 사이에 `prepare`를 사용해서 데이터를 넘겨주려고 시도했습니다. 하지만 데이터를 넘겨주는 과정의 관리가 쉽게 되지 않아서 공부를 더 해본 결과, 이번 프로젝트의 경우에는 컨테이너뷰의 사용이 적합하지 않다는 판단을 했고, 모든 뷰를 초기화 후 콜렉션뷰로 진행하였습니다. 뷰컨트롤러 위의 콜렉션뷰가 1개 있고, SegmentedController의 상태값이 따라서 셀의 표현방식이  달라지는 방식입니다.
- 하나의 셀 타입에서 SegmentedController 상태에 따라 오토레이아웃을 다르게 주려고 시도했으나, 다른 오토레이아웃을 가진 셀들이 모두 함께 재사용되다보니 오토레이아웃이 겹칠 때 우선순위가 명확하지 않았던 문제가 있어서 오토레이아웃이 셀에 남아있는 등 관리에 어려움을 겪었습니다. `NSLayoutConstraint.deactivate()`을 사용해서 모두 지워주는 방식도 시도해봤지만, 셀이 deque되는 시점과 deactivate되는 시점이 확실하지 않아서 완전히 해결되지 않았습니다. 이후 조언을 얻은 뒤에 `ListCell`, `GridCell` 두가지 타입의 셀을 만들도록 수정하는 방법으로 해결했습니다.

2022-01-23 19:40 UTC, ryan-son requested changes
호랭이, 고생 많으셨습니다! 어려운 과정 진행하고 계신데 혼자서도 열심히 진행하시며 문제를 해결해 나가시는 모습이 멋지네요! 👏

코드의 흐름을 설명해주셔서 작성해주신 내용을 읽기가 한 결 더 수월했어요. PR 내용을 읽어보기만해도 한 주 동안 얼마나 빠르게 성장하고 계신지 느껴졌고, 남들과 같은 방식을 택하기보다 스스로 생각한 방식으로 밀고 나가시는 모습 등 저도 호랭이에게 많은 점을 배우고 있고, 또 배워야 한다고 생각합니다.

## 조언을 얻고 싶은 부분

> 콜렉션뷰를 리스트 형식으로 표현할 때, 테이블뷰를 사용할 때처럼 셀 사이에 경계선을 넣고싶었는데 전체 테두리를 하는 방법은 찾았지만 셀 아래에만 선을 넣는 방법을 찾지 못했습니다...일단은 UIView를 이용해서 넣었는데, 콜렉션뷰를 이용할 때 이와 같은 경우 사용할 수 있는 방법이 있을까요?

네, 편의성으로 제공하는 방식은 없고, 지금처럼 UIView를 통해 만들어주거나, CALayer를 sublayer에 추가하는 방식을 이용할 수 있습니다. iOS 14.0부터 사용가능한 [테이블뷰 모양의 컬렉션뷰](https://developer.apple.com/documentation/uikit/uicollectionviewcompositionallayout/3600951-list)에서는 구분선을 표시 여부와 모양을 설정할 수 있도록 편의성 API를 제공하네요. [이 문서](https://developer.apple.com/documentation/uikit/uicollectionlayoutlistconfiguration)와 문서 내부의 아래 토픽들을 참고하세요.

## 개선을 생각해볼 수 있는 점
개별 코멘트 이외에 개선을 고려해볼 수 있는 점입니다.
- 셀의 `prepareForeReuse()` 메서드를 통해 셀이 재사용되기 전 기존 데이터나 스타일을 초기화하여 셀을 기본 상태로 되돌림 (현재 segmented control을 통해 이동할 경우 셀의 이미지가 기존 것에서 바뀌는 현상을 개선할 수 있습니다)

## 이해하지 못한 점
> - Cell 클래스의 `updateCell`메서드에서 이미지 불러오기를 완료하기 전에 셀에 값이 들어가는 것을 방지하기 위해서 이미지를 이미지뷰에 넣어주는 부분을 메인스레드 async로 실행하도록 하였습니다.

'이미지 lazy loading을 통해 이미지를 불러오기 전에도 셀에 값을 넣을 수 있도록'이라는 의미인가요?

이해하기 어려운 코멘트가 있거나 도움이 필요하면 언제든지 말씀해주세요~! 😊

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/Decoder.swift
> +    func parsePageJSON (data: Data) -> ProductList? {
공백이 하나 들어갔네요~ 😋

```suggestion
    func parsePageJSON(data: Data) -> ProductList? {
```

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/Decoder.swift
>          }
이미 아시겠지만 throwing function을 사용할 때 디코딩 실패 시 에러 발생 이유를 알리지 않고 단순히 `nil`을 반환하고자 한다면 optional try 문법을 사용해볼 수 있을 것 같아요.

```suggestion
        let pageJSON: Data = data
        guard let decodedPageJSON = try? decoder.decode(ProductList.self, from: pageJSON) else {
            return nil
        }
        return decodedPageJSON
```

기본 프레임워크에서 제공하는 메서드들은 대부분 에러 발생 시 발생 이유를 자세히 알려주기에 개인적으로는 메서드 사용자의 입장을 고려해서 에러 발생 원인을 알려주는 것이 좋다고 생각합니다.
처리 방법은 아래 중에서 선택할 수 있을 것 같아요. 호랭이는 어떤 것이 좋을 것 같은지, 아니면 다른 의견이 있는지 이야기 나누어보았으면 좋겠어요~!
1. 출력문 (로그)
2. 동일하게 throw 메서드로 구성하여 메서드 사용자에게 처리를 맡김
3. Result 타입을 통해 에러 반환
4. [컴파일러 전처리문](https://docs.swift.org/swift-book/ReferenceManual/Statements.html#ID538)을 이용해 디버그 모드에서는 `preconditionFailure(_:)`, `assertionFailure(_:)`를 통해 런타임 에러 발생 유도, 릴리즈에서는 에러 발생 시 무시

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/Model/StringExtension.swift
> +    func insertComma() -> String {
`String` 타입의 확장이니 모든 문자열에서 이 메서드를 확인할 수 있을 것 같아요. 그런 경우에는 이 메서드의 이름만으로는 어떤 기능을 수행하는 메서드인지 알아보기가 쉽지 않을 수 있겠어요. 숫자에 구분점을 추가한다와 같은 명확한 이름을 사용하거나 문서화 주석을 통해 어떤 일을 수행하는 메서드인지 알려준다면 함께 일하는 동료에게 도움이 될 것 같네요!

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/Model/StringExtension.swift
> +    }
- 이미 아시겠지만 실패 시 nil이 발생할 때 [nil 병합 연산자 (Nil-Coalescing Operator)](https://docs.swift.org/swift-book/LanguageGuide/BasicOperators.html#ID72)를 통해 기본값을 넘겨줄 수 있어요. 옵셔널 처리의 편의를 위해 자주 사용하는 것은 지양해야할 일이지만, 실패해도 큰 영향이 없는 경우에는 실패했다는 사실과 이유를 로그 정도로만 보여주고 처리할 수도 있다고 생각합니다. 
- 오타가 있네요~ 아래 기능을 이용하면 오타가 발생하면 화면에서 빨간 밑줄로 알려줘서 저는 편하게 이용하고 있어요. 우측 클릭으로 오타가 발생한 단어를 맞는 단어로 바꿀 수 있도록 추천도 해줍니다.

![image](https://user-images.githubusercontent.com/69730931/148696813-e78c69c2-c036-4391-b746-e480b38b7498.png)

![image](https://user-images.githubusercontent.com/69730931/148696869-d82810a5-c809-47a9-b899-599952314520.png)

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/Network/MockURLSession.swift
> +//                  completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTask
테스트는 이후에 하시는 걸로 계획하고 계신가요~?

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/Network/RequestType.swift
> +    func url(type: RequestType) -> String {
열거형의 인스턴스 메서드인데 매개변수로 동일한 타입의 인스턴스를 요구하고 있네요. 동일한 인스턴스를 의미하는 것이라면 타입 메서드 또는 연산 프로퍼티 형식으로 변경한다면 매개변수 없이도 동일한 기능을 제공할 수 있을 것 같아요~

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/Network/URLSession.swift
파일 이름과 안에 있는 타입이 달라 혼동을 줄 수 있을 것 같아요. 물론 파일 이름과 내부에 있는 타입이 언제나 동일한 이름으로 설정할 필요는 없지만(요구사항인 프로토콜 또는 간단한 타입이 동일한 파일에 위치하는 경우) 가능하다면 동일하게 맞추어 주는 것이 좋아보입니다~!

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/Network/URLSession.swift
>                    }
네트워킹에 실패할 경우 몇 번 상태코드로 실패했는지 알면 디버깅에 굉장한 도움이 되더라구요. 에러에 상태코드를 포함할 수 있다면 더 좋겠어요~!

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/Network/URLSession.swift
> +               return completionHandler(.failure(.unknownFailed))
알 수 없다는 내용보다는 옵셔널의 의미를 해석해서 데이터가 비어있다 정도의 문구를 사용하면 어떨까요?

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/Network/URLSession.swift
>          task.resume()
task를 상수로 받아두었으니 이 메서드의 사용자에게 지금 만들어진 task를 취소할 수 있도록 task를 반환해주는 것도 좋은 방법일 것 같아요~

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/GridCell.swift
> +    @IBOutlet weak var stock: UILabel!
상위 레이어에 인터페이스 빌더의 인터페이스가 공개되지 않도록 접근제한자를 설정할 수 있어요. 키워드의 순서는 어떻게 배치해볼까요?

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/GridCell.swift
> +    }
Nib이 무엇인지, nib이 깨어난다는 것이 어떤 의미인지, 어느 시점에 이 메서드가 동작하는지 공부해보셨나요~? 이런 내용은 반복적으로 등장할거라 잘 알아두면 실무에서도 많은 도움이 됩니다! 또, 공식 문서를 읽어보면 아래와 같은 내용이 작성되어 있어요.

> You must call the super implementation of awakeFromNib to give parent classes the opportunity to perform any additional initialization they require. [awakeFromNib()](https://developer.apple.com/documentation/objectivec/nsobject/1402907-awakefromnib)

이와 같이 클래스를 상속하여 어떤 요소를 재정의하게 될 경우 해당 메서드가 상위 클래스(super class)에서 구현한 내용을 이용하여야 하는지에 대해 알아보는 것이 좋습니다. 상위 클래스에서 구현한 내용이 하위 클래스의 인터페이스를 통해 동작하지 않을 경우 SOLID 원칙의 리스코프 치환 원칙 (LSP)를 위반하게 되어 의도치 않게 해당 인터페이스를 사용하는 사용자들에게 혼동을 줄 수 있으니 유의해주세요~

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/GridCell.swift
> +        DispatchQueue.global().async {
GCD (Grand Central Dispatch)를 이용해보셨군요! 지금 상황처럼 `Data(contentsOf:)` 메서드와 같은 동기 메서드를 이용할 때 메인 스레드의 UI 블로킹을 방지할 수 있습니다.
한 발 더 나아가서 global()의 의미와 QoS (Quality of Service), sync와 async의 개념까지 공부해보시면 좋을 것 같네요~ 그 이후에 일반 global()을 사용했을 때 어떤 QoS가 지정이 되고, 어떤 상황에서 어떤 QoS를 이용하여야 할지에 대해서도 생각해보시면 좋습니다! 먼저 이 문서를 통해 시작해볼까요? [global(qos:)](https://developer.apple.com/documentation/dispatch/dispatchqueue/2300077-global)

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/GridCell.swift
> +            let imageData = try? Data(contentsOf: imageURL)
애플에서는 네트워킹 작업에 `Data(contentsOf:)` 메서드를 사용을 지양할 것을 권장합니다. 그 이유와 대안을 [이 문서](https://developer.apple.com/documentation/foundation/nsdata/1407864-init)에서 밝히고 있으니 참고하세요~

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +class ViewController: UIViewController {
함께 개발하는 개발자가 있다면 타입의 이름만으로 어떤 ViewController인지 알 수 있도록 명확한 이름을 지어보는건 어떨까요?

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +    @IBOutlet weak var switchLayoutController: UISegmentedControl!
- 타입 안에서 호랭이만의 IB/타입/인스턴스 프로퍼티, 메서드에 따른 정렬 방식이 있나요?
- UI 요소들은 이름에 타입 이름을 일부 포함하면 사용하는 입장에서 타입을 예상할 수 있어 더 좋을 수 있어요.

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +    @IBAction func switchLayout(_ sender: Any) {
IB 요소와 더불어 외부에 공개하지 않아도 되는 인터페이스들은 접근제한을 설정해볼까요?

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +        collectionView.collectionViewLayout = flowLayout
flowLayout을 이용해보셨군요! CompositionalLayout 같이 새로운 API 공부도 좋지만 저는 개인적으로 기존 메서드들을 잘 익히는 것이 중요하다고 생각합니다. 회사의 레거시 코드들은 모두 예전 방식을 사용하고 있을테니깐요.

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +        }
- 내용이 많다면 메서드로 만드는 것도 고려해볼 수 있겠어요. 
- 향후에 실행될 escaping closure에 ViewController의 인스턴스인 self가 캡처링되고 있네요. **특정한 상황**에서는 이런 경우에 캡처링된 요소가 메모리에서 해제되지 않아 메모리 누수를 일으킬 수 있어요. 아래 내용을 학습해봅시다!

1. 특정한 상황은 어떤 경우일까요?
2. 캡처링된 요소가 메모리에서 해제되지 않는 이유는 무엇인가요?
3. 어떻게 메모리에서 해제될 수 있게 만들어줄 수 있을까요?

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +        let urlSessionProvider = URLSessionProvider()
함수 내부에서 구체적인 타입에 의존하기 보다 `ViewController` 인스턴스를 초기화할 때 사용할 타입을 주입 받아 사용할 수 있도록 만들어보는건 어떨까요? 그 후에 `Decoder`, `URLSessionProvider`와 같이 구체적인 타입보다 동일한 인터페이스 (공개된 프로퍼티/메서드)를 요건으로 하는 추상적인 타입을 요구사항으로 해서 테스트에도 용이하게 만들 수 있겠어요. 덤으로 SOLID의 의존성 역전 원칙 (DIP)도 준수할 수 있겠네요.

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +        }
parsedData는 이미 productListData와 동일한 타입으로 변환되었는데 completion handler를 통해 전달하지 않아도 되지 않을까요? 여기에서 바로 parsedData를 productListData에 할당할 수 있어 보이는데, 호랭이는 어떤 것을 의도했나요?

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +extension ViewController: UICollectionViewDataSource {
준수하는 프로토콜 별로 extension을 구분하는 방식 👍

2022-01-23 19:40 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +        }
수많은 시행착오 끝에 여기까지 오셨다는게 느껴지네요. 고생하셨습니다. 👏

2022-01-23 19:46 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +        }
ViewController에서 이러한 메서드를 이용만 할 수 있도록 중간에 네트워킹을 수행하는 타입이 있으면 좋을 것 같아요.

2022-01-24 16:08 UTC, horeng2 commented on OpenMarket/OpenMarket/Decoder.swift
>          }
출력문의 경우 간단하게 코딩을 할 수 있지만, 단순하게 에러를 프린트만 해주기 때문에 에러의 형식을 특정해줄 수 없으며,형식 안정성이 떨어질 수 있다고 생각했습니다. 2번 방법의 경우에도 throw만 해줄 뿐 크게 다르지 않을 것 같습니다. 이부분은 라이언의 피드백을 바탕으로 찾아보며 공부한 내용을 적은 TIL에 정리해두었습니다!
[2022.01.24. 호랭이 TIL🐯: 에러처리에 Result타입 or 컴파일러 제어문 사용하기](https://camp.yagom-academy.kr/camp/611931356143323c8b376dc3/boards/614c48258a9fd23b353b0734/articles/61eec6d82947bf40f08f3597)

나머지 3번과 4번의 방법중에서, 한번 사용해봐서 조금은 익숙한 Result 타입을 이용한 방법으로 수정해봤습니다. 컴파일러 전처리문을 이용하는 부분은 처음 보는 방식인데, 이부분은 프로젝트가 끝난 뒤 방학 때 시도해보겠습니다!!
Result 타입을 이용하면 아래와 같은 장점이 있다고 생각합니다.
- 에러 형식이 명시적으로 선언된다.
- 타입 캐스팅 없이 에러 처리가 가능하다.
- 형식 추론을 통해 에러 처리 코드가 단순해진다.
- 작업의 결과를 성공과 실패로 명확히 구분 가능하다.
- get 메소드로 에러 처리 코드를 더욱 단순하게 구현할 수 있다.

2022-01-24 16:47 UTC, horeng2 commented on OpenMarket/OpenMarket/Decoder.swift
>          }
이어서, Result타입의 반환값을 뷰컨트롤러에서 사용할 때 성공 실패 여부에 따라 파싱된 데이터를 반환 또는 에러를 출력하는 메서드를 별도로 만들었습니다. 
기존의 getDecodedData메서드에서는 getParsedData메서드를 호출하여 데이터를 파싱하고 그것을 이용하여 getData메서드 호출로 데이터를 로드하는 역할을 모두 하고 있었는데, 파싱된 데이터를 반환하는 메서드를 getParsedData라는 이름으로 별도로 분리하고 기존의getDecodedData메서드는 명확한 역할을 나타내기 위해서 loadData로 리네이밍 했습니다.

2022-01-24 17:07 UTC, horeng2 commented on OpenMarket/OpenMarket/Model/StringExtension.swift
> +    func insertComma() -> String {
insertCommaInThousands라는 이름으로 리네이밍하고, 문서화 주석도 이용해봤습니다!

2022-01-24 17:25 UTC, horeng2 commented on OpenMarket/OpenMarket/Model/StringExtension.swift
> +    }
닐병합연산자를 사용할 때마다 뭔가 찝찝했는데 그런 경우에는 괜찮을 수도 있는거군요! 감사합니다 닐병합연산자를 사용하는 방안으로 수정했습니다 👍
오타가 종종 있는데 꿀팁도 감사합니다👍👍👍

2022-01-24 17:30 UTC, horeng2 commented on OpenMarket/OpenMarket/Network/MockURLSession.swift
> +//                  completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTask
이 코드는 스텝1에서 Mork세션 생성과 이를 이용한 테스트코드 작성이 요구사항에 있어서 작성했던 건데, 현재는 사용하고 있지 않아서 주석처리 해놨습니다. 현재까지로는 지금 진행중인 코드에 대한 테스트 계획은 없습니다..😂

2022-01-24 17:36 UTC, horeng2 commented on OpenMarket/OpenMarket/Network/URLSession.swift
네 동일하게 변경했습니다!

2022-01-24 17:57 UTC, horeng2 commented on OpenMarket/OpenMarket/Network/URLSession.swift
>                    }
에러의 상태코드를 출력할 수 있는 코드를 추가했습니다!

2022-01-24 18:04 UTC, horeng2 commented on OpenMarket/OpenMarket/Network/URLSession.swift
> +               return completionHandler(.failure(.unknownFailed))
에러타입의 케이스명을 변경했습니다!

2022-01-24 18:14 UTC, horeng2 commented on OpenMarket/OpenMarket/Network/URLSession.swift
>          task.resume()
향후 task를 취소할 수 있는 기능을 구현할 수 있도록 task를 반환하도록 수정했습니다!

2022-01-24 18:26 UTC, horeng2 commented on OpenMarket/OpenMarket/View Controller/GridCell.swift
> +    @IBOutlet weak var stock: UILabel!
private 접근제한을 설정했습니다. 키워드의 순서는 커스텀셀 상단에서 하단으로 배치되는 순서대로 배치했는데, 더 좋은 방법이 있을까요?

2022-01-24 18:46 UTC, horeng2 commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +class ViewController: UIViewController {
ProductListViewController으로 리네이밍 했습니다!

2022-01-24 18:51 UTC, horeng2 commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +    @IBOutlet weak var switchLayoutController: UISegmentedControl!
보통은 IBOutlet, 타입, 프로퍼티, 메서드 순으로 작성합니다. 해당 부분은 코드를 작성하면서 수정을 놓친 부분이라 정정했습니다! UI요소들에 타입 이름을 포함하도록 수정도 함께 했습니다.

2022-01-24 19:03 UTC, horeng2 commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +    @IBAction func switchLayout(_ sender: Any) {
ProductListViewController 내부의 프로퍼티와 메서드에 접근제한을 설정했습니다.

2022-01-24 19:04 UTC, horeng2 commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +        collectionView.collectionViewLayout = flowLayout
네 CompositionalLayout은 방학때 추가적으로 공부해보려구요!

2022-01-25 03:02 UTC, horeng2 commented on OpenMarket/OpenMarket/Network/RequestType.swift
> +    func url(type: RequestType) -> String {
타입메서드를 매개변수 없이 사용할 수 있도록 수정했습니다!

2022-01-25 03:17 UTC, horeng2 commented on OpenMarket/OpenMarket/View Controller/GridCell.swift
> +    }
네 공부를 더 해보고 오늘 TIL로 작성해보도록 하겠습니다 👍

2022-01-25 03:44 UTC, horeng2 commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +        }
관련 내용을 알아보고 TIL에 적은 적이 있습니다.
[2022.01.13. 호랭이 TIL🐯: escaping closure](https://camp.yagom-academy.kr/camp/611931356143323c8b376dc3/boards/614c48258a9fd23b353b0734/articles/61e03056f680980601ab13a6)

메모리 누수를 겪는 상황은 타입 내의 메서드에서 escaping클로저를 사용하는데 그 클로저 내부에서 해당 타입의 프로퍼티를 참조하는 경우입니다. 이 경우 자신을 참조하는 것이 되어 강한 순환참조가 발생하여, 객체에 nil을 할당해도 메모리에서 해제되지 않습니다. 이것은 약한 참조를 통해 해결할 수 있습니다.

공부한적이 있는데도 막상 사용할때는 생각도 못했네요..😂 해당 내용을 코드에 적용하여 수정했습니다.

2022-01-25 04:15 UTC, horeng2 commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +        }
해당 부분에서 바로 parsedData를 productListData에 할당하고 viewDidLoad의 내부에서 `DispatchQueue.main.async` 실행 전에 데이터를 넣어주지 않으면, 앱 실행 후 segmentedControl을 누르기 전까지 리스트에 아무것도 뜨지 않는 문제가 있었습니다. 순서 때문이라고 판단하고, `DispatchQueue.main.async`의 reloadData 실행 전에 반드시 데이터가 할당되도록 한 의도였는데, 혹시 제가 잘못생각하고 있는 부분이 있을까요? 🧐

2022-01-25 04:18 UTC, horeng2 commented on OpenMarket/OpenMarket/View Controller/GridCell.swift
> +        DispatchQueue.global().async {
감사합니다! 해당 부분 공부해보고 오늘 TIL에 적어보도록 하겠습니다 👍

2022-01-25 05:24 UTC, horeng2 commented on OpenMarket/OpenMarket/View Controller/GridCell.swift
> +            let imageData = try? Data(contentsOf: imageURL)
loadImage라는 메서드를 만들어서 이를 통해 url을 UIImage로 변환하여 사용할 수 있도록 했습니다.

2022-01-25 05:55 UTC, horeng2 commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +        }
DataManager라는 별도의 타입으로 분리했습니다!

2022-01-25 06:11 UTC, horeng2 commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +        let urlSessionProvider = URLSessionProvider()
의존성 주입을 위해서 그동안은 해당 타입을 생성할때 프로퍼티로 주입하거나 내부에서 init을 이용하는 방식을 사용했습니다. 사실 의존성주입이라는 개념이 단순히 '처음엔 타입만 지정해주었다가 사용할 때가 되면 그 때 객체를 생성해준다' 정도로만 이해하고 있어서 올바른 시도였는지는 모르겠으나, 뷰컨트롤러는 호출해서 사용하는 것이 아니기 때문에 생성시 프로퍼티로 주입하는 것이 불가능했고, 내부에 init을 이용하려고 시도했더니 아래와 같은 오류 문구가 떴습니다. 
![image](https://user-images.githubusercontent.com/87305744/150920840-5ff183db-94bb-4dd6-b561-18a45888b29a.png)
현재는 리뷰해주신 코드의 부분은 별도의 DataManager라는 타입으로 분류해놓은 상태이고, 이 타입을 뷰컨트롤러에서 사용하기 위한 과정에서 의존성 주입을 해야할 것 같은데 이런 경우 어떤 방식으로 의존성 주입을 해야하는 걸까요...? 방법이 막막해서 이리저리 찾아보고 고민해보다가 질문 드립니다...🥲

2022-01-26 15:10 UTC, ryan-son commented on OpenMarket/OpenMarket/Network/MockURLSession.swift
> +//                  completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTask
테스트는 코드에 신뢰성을 부여하는 작업으로 프로젝트가 커지면 커질수록 힘을 발휘합니다. 시간이 되실 때 꼭 경험해보시는 것을 추천드릴게요~

2022-01-26 15:12 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/GridCell.swift
> +    @IBOutlet weak var stock: UILabel!
정해진 방법은 없습니다. 본인만의 기준을 만들면 되고, 지금도 충분히 좋은 방법이라고 판단됩니다!

2022-01-26 15:21 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +        }
> 메모리 누수를 겪는 상황은 타입 내의 메서드에서 escaping클로저를 사용하는데 그 클로저 내부에서 해당 타입의 프로퍼티를 참조하는 경우입니다. 이 경우 자신을 참조하는 것이 되어 강한 순환참조가 발생하여, 객체에 nil을 할당해도 메모리에서 해제되지 않습니다. 

약한 참조로 캡처링 하지 않은 경우에는 메모리 누수가 일어날까요? 약한 참조를 하지 않는 경우에 실제로 그런 현상이 발생하는지 디이니셜라이저를 이용해서 알아봅시다!

2022-01-26 15:23 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +        let urlSessionProvider = URLSessionProvider()
에러문구와 같이 `super.init`을 호출해주시면 됩니다. 물론 지정 이니셜라이저를 불러야하죠. 이 부분이 너무 어렵거나 집중하고 싶은 주제와 거리가 있는 것 같다면 이런 주제가 있다는 정도만 알아두시고 다음에 공부해보셔도 되겠습니다!

2022-01-26 15:32 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +        }
저는 아래와 같은 방식으로 ViewController 내부에서 escaping closure를 통해 데이터를 주고 받을 필요는 없지 않을까 하는 의도였습니다. 호랭이가 잘못 생각하고 계신 부분은 없어요~

```swift
  override func viewDidLoad() {
      super.viewDidLoad()
      ...
      getDecodedData()
  }
  
  func getDecodedData() {
      let decoder = Decoder()
      let urlSessionProvider = URLSessionProvider()
      
      urlSessionProvider.getData(requestType: .productList(pageNo: 1, items: 10)) { result in
          switch result {
          case .success(let data):
              guard let parsedData: ProductList = decoder.parsePageJSON(data: data) else {
                  return
              }
            self.productListData = parsedData
            DispatchQueue.main.async {
                self.collectionView.reloadData()
            }
          case .failure(let error):
              print(error)
          }
      }
  }
```

2022-01-26 15:49 UTC, ryan-son approved these changes
호랭이, 고생 많으셨습니다!

현재 상태에서 별다른 이견이 없어 머지합니다. 기존에 남겨둔 코멘트를 살펴보시며 공부해보시면 좋겠습니다 (TIL 남기시려고 하신 부분 등).
이번에 남겨둔 코멘트는 취사선택하셔서 필요하다고 판단되는 경우 다음 스텝에서 반영해보시면 되겠습니다!

화이팅! 💪

2022-01-26 15:49 UTC, ryan-son commented on OpenMarket/OpenMarket/Decoder.swift
>      let decoder = JSONDecoder()
외부에 들어내지 않아도 될 요소들은 꼭 숨겨주세요~

2022-01-26 15:49 UTC, ryan-son commented on OpenMarket/OpenMarket/Model/Common/Currency.swift
>      case KRW
케이스를 대문자로 작성하신 이유가 있나요?

2022-01-26 15:49 UTC, ryan-son commented on OpenMarket/OpenMarket/Model/DataManager.swift
> +        let urlSessionProvider = URLSessionProvider()
이후에 `DataManager`도 테스트를 위해 이러한 요소들을 추상화하여 외부에서 주입 받도록 하는 것도 좋겠네요. 의존성 역전..!

2022-01-26 15:49 UTC, ryan-son commented on OpenMarket/OpenMarket/Model/StringExtension.swift
> + */
문서화 주석 좋네요! 지금은 아래와 같이 뜨지만 이 내용을 메서드 바로 위의 위치로 변경하면 이 위치까지 찾아오지 않아도 호랭이의 설명을 확인할 수 있어요~!

![image](https://user-images.githubusercontent.com/69730931/151195205-708fec07-cb83-4cac-b27c-a8b001cce793.png)

![image](https://user-images.githubusercontent.com/69730931/151195465-1c107b89-0f54-400e-b5df-35430736c59a.png)

2022-01-26 15:49 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/ListCell.swift
> +    }
앞서 말씀드렸듯이, 재정의(override)한 메서드가 부모 타입에서 정의한 메서드를 호출하여야 하는지 알아보는 것이 좋아요. `awakeFromNib()`은 어땠나요?

2022-01-26 15:49 UTC, ryan-son commented on OpenMarket/OpenMarket/View Controller/ListCell.swift
> +        }
메모리 누수가 일어날까요, 아닐까요? 디이니셜라이저를 통해 알아봅시다~!

2022-01-26 15:49 UTC, merged