오픈마켓1 [STEP 2] 고사리
yagom-academy/ios-open-market pull request #113
Opened 2022-01-21 12:14 UTC by FIIIIN

안녕하세요, Cory!! 다사다난한 오픈마켓 1의 Step 2 PR을 요청드립니다😄

추가적으로 궁금하시거나 말씀하실 내용은 코멘트 혹은 DM으로 편하게 말씀해주시면 감사하겠습니다!

잘 부탁드립니다🙏

---

## 1. 고민한 점

1-1. 같은 데이터를 다른 형태(Grid와 List)로 띄우는 방식을 고민했습니다.

- Commit `feat: 팀프로젝트로 진행하였던 코드를 개인 레퍼지토리로 이동` 이전에는 ContainerView 두 개를 띄우고, 버튼에 따라 사용자에게 일정 뷰만을 노출하도록 설계했습니다.
    - 이때 ContainerView가 각각의 생명주기를 가지는 것이 공동데이터를 비동기로 불러오고 그것을 노출하는 방식과는 어울리지 않다는 것을 파악하여 설계를 변경했습니다.
- 현재는 CollectionView와 TableView를 모두 하나의 View가 소유하며 버튼에 따라 일정 뷰만을 노출하도록 설계했습니다.
    - 이 방법은 메모리가 낭비된다는 문제가 존재할 수 있지만, 두 개의 View가 동일한 생명주기를 가지기 때문에 선택하게 되었습니다.
    - 사용자의 입장에서, SegmentedControl을 눌렀을 때 현재 보고 있는 정보를 다른 레이아웃으로 볼 수 있다는 기대를 할 것이라고 생각했습니다. 레이아웃이 변경될 때마다 통신을 한다면 뷰 전환 도중에 추가된 정보를 새로이 띄울 수 있어 사용자 경험의 측면에서 유리하지 못하다고 판단했습니다.

1-2. StoryBoard로 작업하던 중  Code-based UI 로 변경하였습니다.

- StoryBoard로 구현한 라벨 등이 시뮬레이터나 View Hierarchy에서는 보이지 않는 등의 문제가 장시간 해결되지 않았고, Code-based UI 를 급하게 채택하게 되었습니다.

## 2. 트러블슈팅

#### 2-1.
* 문제 상황: imageView에 constraint를 추가해도 셀 경계를 넘어서 이미지가 로드되는 현상을 해결하기 위해 아래와 같은  방법을 시도하였습니다.

* 해결 방법: cell의 content를 모두 담고 있는 ContainerStackView가 self에게 추가되는 것이 아닌, ContentView에게 추가되도록 코드를 변경했습니다.

```swift
// 방법 1
extension UIImage {
    func squareImage(length: CGFloat) -> UIImage? {
        let originWidth: CGFloat = self.size.width
        let originHeight: CGFloat = self.size.height
        var resizeWidth: CGFloat = length
        var resizeHeight: CGFloat = length
        
        UIGraphicsBeginImageContext(CGSize(width: length, height: length))
        
        let sizeRatio = length / max(originWidth, originHeight)
        if originWidth > originHeight {
            resizeWidth = length
            resizeHeight = originHeight * sizeRatio
        } else {
            resizeWidth = originWidth * sizeRatio
            resizeHeight = length
        }
        
        self.draw(in: CGRect(x: length / 2 - resizeWidth / 2,
                             y: length / 2 - resizeHeight / 2,
                             width: resizeWidth, height: resizeHeight))
        
        let resizeImage = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        
        return resizeImage
    }
}

// 방법 2
containerStackView.clipsToBounds = true
```

#### 2-2.
* 문제 상황: 아래와 같은 런타임 에러가 발생하였습니다.

> Thread 1: "Unable to activate constraint with anchors <NSLayoutXAxisAnchor:0x6000038c5500 \"UIImageView:0x7fe49711bca0.leading\"> and <NSLayoutXAxisAnchor:0x6000038c5540 \"UIStackView:0x7fe497115920.leading\"> because they have no common ancestor. Does the constraint or its anchors reference items in different view hierarchies? That's illegal.”
> 
* 해결:
    * `different view heirachies` 라는 것은 접근 권한이 없는 view를 의미하는 것으로 해석했습니다.
    * 접근 권한이 없는 view에게 constraint를 걸어준 것이 해당 런타임 에러가 발생한 원인이라는 추측으로 `부모 View에게 constraint을 걸어주도록 변경`하였고, 문제가 해결되었습니다.

* #### 참고 이미지: 문제가 되었던 코드

![](https://i.imgur.com/ZzPDmLT.png)

#### 2-3.
* 문제 상황: Main에서 TableView와 SafeArea 간의 제약이 걸리지 않았습니다.
* 해결: 새로이 생성한 TableView로 다시 시도하였고, 문제가 해결되었습니다. 하하...

## 3. 조언을 얻고 싶은 부분

3-1. ViewController에서 통신을 요청하고, 성공 분기에 따라 뷰컨의 프로퍼티에 데이터가 들어간 이후 main에서 비동기로 reloadData()를 요청하는 모습입니다. 리로드의 타이밍, 혹은 뷰를 그리는 행위는 main.async로, 데이터 통신은 global().async로 요청하는 것이 적절한지 궁금합니다.

```swift
func loadProductList() {
        getDecodedData { (result: Result<ProductList, NetworkError>) in
            switch result {
            case .success(let data):
                self.productList = data
                DispatchQueue.main.async {
                    self.productCollectionView.reloadData()
                    self.productTableView.reloadData()
                }
            case .failure(let error):
                print(error)
            }
        }
    }
```

3-2. 해당 런타임 오류가 발생하였을 때, 다시 시도를 하면 문제없이 빌드되는 모습을 보이는데 이건 무시해도 되는 류의 이슈일까요...?

![](https://i.imgur.com/G5T4CIj.png)

2022-01-23 15:45 UTC, corykim0829 requested changes
수고 많으셨습니다 고사리 :)

트러블 슈팅 기록한 것은 아주 좋습니다 :)

개인적으로는 collectionView와 tableView를 모두 사용한 것은 효율적이지 못한 것 같아요. 여유가 된다면 다른 방법을 찾아보는 것도 좋을 것 같습니다!!

리뷰 내용은 피드백 반영해서 다음 스텝 때 같이 수정해서 보내주세요!

> 3-1

뷰단 업데이트는 무조건 메인 쓰레드에서 처리되어야합니다! 지금 보내는 네트워크 요청은 기본적으로 어느 쓰레드에서 되는지 확인해보세요!

2022-01-23 15:45 UTC, corykim0829 commented on OpenMarket/OpenMarket/Extension/String+Extension.swift
> +extension String {
Foundation과 UIKit의 관계를 한번 알아봐서 import하는 것을 줄일 수 있을 것 같아요.
또한 import 부분과 코드 구현부 사이에 개행을 주면 더 읽기 좋은 코드가 될 것 같아요 :)

2022-01-23 15:45 UTC, corykim0829 commented on OpenMarket/OpenMarket/Model/Common/Image.swift
> +struct Image: Codable {
지금은 괜찮지만 그냥 Image라고 하면 추상적이여서 추후에 다른 이미지 관련 객체를 만들 때에 어려움을 겪을 수 있어요! 참고하세요 :)

2022-01-23 15:45 UTC, corykim0829 commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +                    return
decoder가 디코딩에 실패하면 그냥 return 처리만 하지 않고 이에 대해서 처리해줄 수 있으면 더 좋을 것 같아요

2022-01-23 15:45 UTC, corykim0829 commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +    override func viewDidLoad() {
viewDidLoad안에 코드들을 함수로 추출해서 정리하면 더 읽기 좋은 코드가 되어서 어떤 일을 하고 있는 코드인지 한번에 알 수 있을 것 같아요!

2022-01-23 15:45 UTC, corykim0829 commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +                print(error)
실패하면 print 처리 대신 다른 방법으로 유저에게 피드백을 줄 수는 없을까요?

2022-01-23 15:45 UTC, corykim0829 commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +        3
매직넘버는 상수로 정리해주세요!

2022-01-26 12:26 UTC, FIIIIN commented on OpenMarket/OpenMarket/Extension/String+Extension.swift
> +extension String {
UIKit을 import하면 Foundation도 함께 import 되는군요! 해당 내용 수정했습니다.

2022-01-26 12:30 UTC, FIIIIN commented on OpenMarket/OpenMarket/Model/Common/Image.swift
> +struct Image: Codable {
마땅히 생각나는 네이밍이 없어서 `ImageInformation`으로 리네이밍해보았는데, 혹시 더 괜찮은 아이디어 있으시면 공유 부탁드립니다🙏

2022-01-26 12:39 UTC, FIIIIN commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +                    return
해당 gaurd문을 통과하지 못할 경우, 구체적인 사유를 프린트하도록 리팩토링 진행하였습니다!

2022-01-26 12:44 UTC, FIIIIN commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +    override func viewDidLoad() {
delegate나 datasource, Cell과 관련된 코드들은 viewDidLoad()에 그대로 들어있는 편이 자연스럽다고 판단하여 특정 페이지만을 노출하는 isHidden부를 함수로 추출하여 정리하였습니다.

메서드명은 `showTableViewFirst()`입니다..!!

2022-01-26 14:26 UTC, FIIIIN commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +                print(error)
ViewController 익스텐션으로 alertError()를 선언하여, 말씀하신 것처럼 유저에게 피드백을 줄 수 있는 방향으로 수정하였습니다🙋‍♀️

2022-01-27 12:05 UTC, corykim0829 commented on OpenMarket/OpenMarket/Model/Common/Image.swift
> +struct Image: Codable {
Product 객체에서 사용되는 이미지라면, ProductImage 같이 네이밍을 하면 Product에서 사용하는 이미지 객체인걸 더 명확하게 표기해줄 수 있을 것 같아요!

2022-01-27 12:06 UTC, corykim0829 commented on OpenMarket/OpenMarket/View Controller/ViewController.swift
> +                    return
넵 프린트문도 좋지만, 클라이언트 단에서 alertController를 띄우는 것과 같은 피드백을 주면 좋습니다!

2022-01-27 16:45 UTC, merged