오픈마켓 2 [STEP 1] aCafela coffee, 호댕
yagom-academy/ios-open-market pull request #117
Opened 2022-01-24 13:34 UTC by yanghojoon

안녕하세요, @protocorn93 
오픈마켓 2 Step 1 마무리되서 PR 보내드립니다! 
생각보다 고려할 내용이 많아 늦어졌네요... 😅

이번 프로젝트도 잘 부탁드립니다 🙏

## 🤔 고민한 점

### 1️⃣ Dismiss interactively를 사용

기존에는 스토리보드의 attribute Inspector에서 keyboard 설정을 `Dismiss on drag`로 했습니다. 하지만 드래그를 할 때마다 키보드를 닫을 필요는 없다고 판단했고 키보드를 닫을 수 있는 액션은 필요하다고 판단하여 `Dismiss interactively`를 사용했습니다. 

키보드를 닫을 수 있는 액션에 `TextView`나 `TextField`가 아닌 다른 곳을 터치하면 `Tap gesture recognizer`를 통해 키보드를 닫을 수 있도록 구현은 해놓았으나 이는 사용자가 알 수 없을 수도 있겠다고 판단하여 `Dismiss interactively`를 사용하는 것이 적합하다고 판단했습니다. 

### 2️⃣ 키보드가 컨텐츠를 가리지 않을 것

키보드가 컨텐츠를 가리지 않도록 하는 방법에 대해 고민했습니다. 
처음에는 아래처럼 view.frame의 origin을 직접 변경하는 방식을 선택했습니다. 

```swift
@objc private func keyboardWillShow(_ sender: Notification) {
    if let keyboardFrame = sender.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue {
        let keyboardRectangle = keyboardFrame.cgRectValue
        let keyboardHeight = keyboardRectangle.height
        view.frame.origin.y = -keyboardHeight
    }
}

@objc private func keyboardWillHide(_ sender: Notification) {
    view.frame.origin.y = 0
}
```

하지만 이렇게 했을 때 화면 자체가 올라가면서 위에 있는 내용을 볼 수 없는 문제가 발생했습니다. 
따라서 화면 자체를 위로 올리는 것이 아닌 스크롤 뷰의 contentInset을 키보드의 높이만큼 늘리는 방법을 선택했습니다. 

```swift
scrollView.contentInset.bottom = keyboardHeight
```

이런 식으로 scrollView의 하단 contentInset을 키보드만큼 주어 위에 있는 내용도 확인할 수 있으면서 컨텐츠도 가리지 않도록 구현했습니다. 

### 3️⃣ 실시간 입력값 유효성 검증

> **Dynamically validate field values.**
It’s frustrating when you have to go back and correct mistakes after filling out a lengthy form. Whenever possible, check field values immediately after entry so users can correct them right away.
> 

> 사용자가 입력한 정보를 잘못 입력했을 때 텍스트 필드에 인라인으로 오류 메시지를 나타낸다. 이때 오류 메시지는 레이블과 구분되는 디자인을 권장한다.
[https://brunch.co.kr/@chulhochoiucj0/20](https://brunch.co.kr/@chulhochoiucj0/20)
> 

![t1 daumcdn net](https://user-images.githubusercontent.com/90880660/150791333-e7a7cdf7-3c88-422c-954f-8f24590b675b.png)

HIG 문서에서 TextField를 통해 받은 데이터의 유효성을 실시간으로 검증하라는 내용이 있었습니다. 따라서 기존에는 Done 버튼을 누를 때만 상품 등록 내용이 적합하게 작성되었는지 검증했지만, textField의 내용을 수정할 때마다 유효성을 검증해야겠다고 판단했습니다. 

디자인의 경우 레이블의 경우 이미 PlaceHolder를 통해 보여주고 있었기 때문에 오류 메세지는 TextField의 상단에 표시되도록 구현했습니다. 

```swift
.addTarget(self, action: #selector(textInputDidChange(_:)), for: .editingChanged)
```

실시간으로 값을 점검하기 위해 위 코드를 사용하여 수정될 때마다 `textInputDidChange(_:)` 메서드가 호출될 수 있도록 했습니다. 

다만 TextView의 경우 addTarget 메서드가 존재하지 않아 TextView만 `UITextViewDelegate`의 메서드인 `textViewDidEndEditing` 를 호출해 사용했습니다. 해당 메서드의 경우 실시간이 아닌 TextView의 수정이 끝났을 때만 호출되는 문제가 있었는데 이는 아직 해결하지 못했습니다. 

### 4️⃣ 이미지를 크롭 및 리사이즈

명세에서 이미지가 정사각형으로 크롭이 되어 들어가있었고, 이미지의 용량도 300KB 미만으로 넣어야 했기 때문에 이미지를 크롭하고 리사이즈하는 방법에 대해 고민했습니다. 

이미지 크롭의 경우 가로 세로 길이를 비교하여 짧은 쪽을 기준으로 크롭을 하는 방식을 선택했습니다. 

```swift
func cropSquare() -> UIImage? {
    let imageSize = self.size
    let shortLength = imageSize.width < imageSize.height ? imageSize.width : imageSize.height
    let origin = CGPoint(
        x: imageSize.width / 2 - shortLength / 2,
        y: imageSize.height / 2 - shortLength / 2
    )
    let size = CGSize(width: shortLength, height: shortLength)
    let square = CGRect(origin: origin, size: size)
    guard let squareImage = self.cgImage?.cropping(to: square) else {
        return nil
    }
    return UIImage(cgImage: squareImage)
}
```

또한 이 조건의 경우 이미지 선택이 완료되었을 때 이뤄져야 하기 때문에 **imagePickerController(_:didFinishPickingMediaWithInfo:)** 메서드에서 조건을 추가해줬습니다. 

<img width="785" alt="스크린샷 2022-01-24 오후 10 13 46" src="https://user-images.githubusercontent.com/90880660/150791141-b002649c-c0ee-4abb-9478-c74357913df9.png">

origin의 경우 가운데로 크롭이 될 수 있도록 그림처럼 origin을 이동시켜줬습니다. 

## ❓ 질문

### 1️⃣ 뷰컨 분리 실패

주로 `ProductRegistrationViewController.swift` 파일이 문제입니다.
프로퍼티도 많고, 중복되는 코드도 제법 있습니다. 복잡하기도 합니다.

line 86 `textInputDidChange(_ sender: Any?)` , line 497 `inspectInput()` 이 두 함수는 `if` 가 많습니다. `else if` 를 써야하거나 언래핑된 결과값이 필요해서 `if` 를 썼기에 분리하지 못했습니다.
line 160 `registerProduct()`, line 209 `modifyProduct()` 는 리턴 타입과 `productId` 프로퍼티가 다릅니다.
line 534 `inspectMaximumDiscountedPrice` 부터 line 577 `inspectMinimumName` 의 함수는 line 86 `textInputDidChange(_)` 에서 사용하려고 분리했습니다. 그런데 오히려 더 복잡해 보일지 걱정됩니다.

데이터 소스는 아래 코드의 `presentImagePicker()` 때문에 분리하지 못했습니다.

```swift
// ProductRegistrationViewController.swift
// line 656
button.addTarget(self, action: #selector(presentImagePicker), for: .touchUpInside)
```

### 2️⃣ iOS 14.0에서 자동으로 컬렉션뷰에 배경색이 설정되는 문제

iOS 15.0에서는 문제가 없었지만 iOS 14.0에선 segmented Controll을 통해 컬렉션뷰로 이동할 때 검은 색으로 배경이 바뀌는 문제가 있었습니다. 물론 아래 코드를 추가하여 문제를 해결하긴 했습니다. 

```swift
collectionView.backgroundColor = .systemBackground
```

다만 아직 왜 이런 현상이 일어나는지는 찾지 못했습니다...🥲 
혹시 콘은 왜 이런 현상이 발생하는지 알고 계실까요?

### 3️⃣ 꽃 사진만 자동으로 180도 회전이 되는 문제

UIImage 크롭 후에 생기는 문제입니다.
시뮬레이터에 미리 준비된 사진 중에서 꽃 사진이 뒤집혀서 나옵니다. 다른 사진은 문제가 없습니다.

<img width="506" alt="스크린샷 2022-01-24 오후 10 06 18" src="https://user-images.githubusercontent.com/90880660/150791645-840059cc-67ea-44ed-a885-622c82f31c93.png">

### 4️⃣ 이미지 피커에서 더블 클릭을 하는 경우 이미지가 2개 올라가는 문제

이미지 피커가 닫히지 전에 두번 누르면, 2개 올라갑니다. 이를 막을 방법이 있을까요?

### 5️⃣ TextView의 수정을 실시간으로 알 수 있는 방법

저희 코드에서 TextView는 입력이 끝나야 유효성을 검증합니다.
유저가 위의 텍스트 필드부터 입력했다면, 상품설명을 쓰던 유저가 텍스트 필드처럼 입력중에 검증될 것이라 예상할 것입니다. 그래서 지금 상황은 혼란스러울 듯 합니다. 좋은 방법이 있나요?

2022-01-26 00:46 UTC, protocorn93 requested changes
와! 두 분 모두 너무 고생하셨어요! 이렇게 CRUD 기능은 우리가 새로운 프레임워크나 개발도구 혹은 방법론을 공부하고 실습해볼 때 좋은 예제가 되는 기능입니다. 

쉽지가 않았을텐데 두 분 모두 수고하셨습니다! PR에 남겨주신 글과 코드 코멘트 이전에 몇 가지 말씀드리고 싶은게 있어요! 

1. 줄바꿈이 너무 빈번하게 일어납니다.
- 거의 모든 `,`(콤마)에서 줄바꿈이 일어나는데, 개인적으로는 코드 읽기가 어려웠던 것 같아요. 물론 인자가 많아지면 길어지기 때문에 불가피할 수 있지만, 이번 프로젝트에선 유난히 가독성이 떨어졌던 것 같아요. 일단 이건 개인의 스타일 차이일 수 있으니 조금만 고민해주시면 될 것 같아요!

2. 현재 새 게시물을 추가할 때 사진이 많아지면 화면이 굉장히 오랫동안 멈춰있습니다. 먼저 이 화면에서 로딩 인디케이터는 필요해보입니다. 그리고 이렇게 화면이 아예 freeze되는것은 방지해야할 것 같아요.
---

## 고민한 점 

### 2. 키보드가 컨텐츠를 가리지 않을 것

제가 정말 싫어하지만 반드시 구현해야 하는게 스크롤뷰 상황에서의 키보드 대응입니다...! 하지만 반드시 구현해야하는게 맞고! 호댕과 아카페라가 구현한 방법을 많이들 사용합니다! 잘 구현하셨어요!!

### 3. 실시간 입력값 유효성 검증 

`textView(_:shouldChangeTextIn:replacementText:)` 
`textField(_:shouldChangeCharactersIn:replacementString:)`


저는 보통 실시간으로 입력된 값을 검증해야할 때면 이 메서드를 사용합니다. 입력된 값이 실제 뷰에 그려지기 전에 어떤 조작을 할 수 있는 메서드로 여기서 검증을 해보면 어떨까요? 

### 4 이미지를 크롭 및 리사이즈 

이런 부분까지 고려하시고 쉽지 않은 접근법인데 훌륭하게 문제를 해결하신 것 같아요! 

---

## 질문

### 뷰컨 분리 실패

1. `textInputDidChange`에 대해서는 코멘트 남겨놓았습니다!
2. `inspectInput`은 결국 입력된 값들에 대한 일괄적인 검증이 들어가고 이러한 코드가 모여있는 곳이기에 이곳에 `if`가 많아지는건 괜찮다고 생각해요. 산발적으로 퍼져있다면 문제가 될 수 있지만 어쨋든 누군가는 이러한 역할을 해야하고 `if`문이 한 곳에 모여있기 때문에 적절한 선택을 하신 것 같아요! 
3. `registerProduct`, `modifyProduct`이 두 메서드는 분리될 필요가 있지만, 내부에는 비슷하고 동일한 코드들이 몇개 보이는데 내부를 조금 더 분리해내볼 수 있지 않을까 생각됩니다! 
4. `inspect-` 메서드로 분리한건 전 오히려 좋았다고 생각해요! 

### iOS 14.0에서 자동으로 컬렉션뷰에 배경색이 설정되는 문제 

이 현상은 저는 현재 재현이 되지 않는데 혹시 가능하시다면 영상이나 gif 첨부 가능할까요?

### 꽃 사진만 자동으로 180도 회전이 되는 문제 

<img width="957" alt="스크린샷 2022-01-26 오전 9 37 12" src="https://user-images.githubusercontent.com/20634806/151083196-3e8c6069-6cac-4154-b85c-ec5418af929f.png">

이 이슈는 저도 원인 파악이 잘 안되네요. 델리게이트 메서드의 인자로 넘어오는 info에서 바로 확인해보아도 애초에 꽃 이미지는 거꾸로된 상태로 넘어오고있네요. 다른 캠퍼들도 이 문제를 겪고 계신건가요?

### 이미지 피커에서 더블 클릭을 하는 경우 이미지가 2개 올라가는 문제

이 문제는 `picker.isBeingDismissed` 이 프로퍼티로 방지할 수 있지 않을까해요! 

### TextView의 수정을 실시간으로 알 수 있는 방법

이 방법에 대해서는 위에 코멘트 남겨놓았습니다! 

### 이미지 리사이즈에 메모리가 많이 필요한 문제

음.. 이 이슈는 저도 좀 더 공부를 해봐야할 것 같은데, 당장 드는 생각은 다운샘플링 기법을 통해서 이미지를 핸들링하면 메모리 이슈를 줄일 수 있다는 글을 몇 번 보고 공부해본 적이 있습니다. Downsampling이란 키워드로 학습을 해보시면 힌트를 얻을 수 있지 않을까 라는 생각이듭니다.

2022-01-26 00:46 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    private let productRegistrationViewControllerIdentifier = "ProductRegistrationViewController"
이전 스탭에서 셀의 identifier를 관리하는 방법에 대해 코멘트를 남겼고, 수정하신걸로 알고있습니다. 셀이나 뷰컨트롤러도 동일하게 작업해볼 수 있을 것 같아요. 또한 nib 이름과 클래스명 그리고 (reuse)identifier를 동일한 값으로 가져간다면 위와 같은 하드코딩 상수를 제거할 수 있을 것 같아요.

2022-01-26 00:46 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/ProductsDataSource.swift
> +    func productId(at index: Int) -> Int? {
아래 `vendorId(at:)` 메서드도 그렇고 인덱스 기반으로 값을 접근할 때 안전하게 가져오기 위함인것으로 보입니다. 

현업에서는 이를 `Array` extension을 통해 보다 쉽게 사용하고 있는데요. `products[safe: index]`와 같은 문법으로 사용하고 있어요. 이를 구현해서 사용해보시길 권장드립니다.

2022-01-26 00:46 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +        if section == 0 {
이 코드는 삼항연산자를 이용하면 보다 가독성이 좋지 않을까요? 

`return section == 0 ? images.count : 1`

2022-01-26 00:46 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +        } else {
또한 이 상황에선 굳이 `else`를 사용하지 않아도 될 것 같네요.

2022-01-26 00:46 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +        if indexPath.section == 0 {
`IndexPath`를 사용하면서 `section`을 다루게될 일이 종종 있는데, `section`을 유의미한 값으로 치환해서 사용하면 가독성이 더 좋아질 수 있어요. 

```swift
enum Section: Int { 
  case firstSection = 0
  case secondSection
}

...

guard let section = Section(rawValue: indexPath.section) else { return } 

switch section { 
  case .firstSection: 
    ...
  case .secondSection:
    ...
}
```

2022-01-26 00:46 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +        } else {
`if-else` 블록안의 코드도 별도 유의미한 이름을 갖는 메서드로 분리하는게 좋을 것 같아요.

2022-01-26 00:46 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +        )
이 두 메서드도 하나의 메서드로 묶어보면 좋을 것 같아요!

2022-01-26 00:46 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +    @objc private func textInputDidChange(_ sender: Any?) {
텍스트 필드가 다수이고, `UITextFieldDelegate` 메서드를 구현해야하는 상황이 아니라면 `sender`로 이벤트 송신자를 구분하지말고 `objc` 메서드를 텍스트필드/뷰마다 하나씩 구현해주는게 좋을 것 같습니다.

2022-01-26 00:46 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +            }
이 부분도 별도 이미지 처리 메서드로 분리해보시면 좋을 것 같아요.

2022-01-26 00:46 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +            textField === stockTextField {
현재 활성화된 텍스트 필드는 `isFirstResponder`로도 구분할 수 있을거에요!

2022-01-26 00:46 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/ProductsDataSource.swift
> +    }
배열을 인덱스로 접근할 때 보다 안전하게 값에 접근하기 위해 작성된 코드로 보입니다. 
실제 프로젝트에서도 이러한 방법은 자주 사용되는데 방법이 조금 다릅니다!

`Array`를 extension해서 새 subscript를 구현해주는데요. 사용법은 `someArray[safe: index]` 입니다. 이를 한번 구현해보시겠어요? 검색을 통해서도 쉽게 구현법을 찾으실 수 있을거에요!

2022-01-26 00:46 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
이 부분이 콜렉션뷰 델리게이트 메서드에도 존재하는데 중복 코드를 줄여볼 수 있지 않을까요?

2022-01-26 00:46 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +    }
생성과 수정을 `convenience init`을 통해 구분해준 점 좋은 것 같아요!

2022-01-26 00:46 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +    ) -> Result<NetworkTask.SalesInformation, ProductRegistrationError> {
`Result`로 결과를 반환한 점 좋은 것 같습니다! 저도 이런 방법을 선호합니다!

2022-01-26 00:46 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +    private func modifiySalesInformation(
수정된 정보를 취합하는 메서드로 이해했습니다. 위에 새로 작성한 정보를 취합하는데 메서드와 중복된 코드가 많이 보이는데 어떻게 줄여볼 수 있을까요?

2022-01-26 00:46 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +    @IBAction func tapBackground(_ sender: UITapGestureRecognizer) {
사소하지만 이 메서드도 접근제어자가 추가되면 좋겠네요!

2022-01-26 00:46 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +    private var completionHandler: (() -> Void)?
completion을 받아 동작 후 처리를 해주도록 한 점 좋은 것 같아요!

2022-01-26 00:46 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +    private let secret = "-3CSKv$cyHsK_@Wk"
`identifier`와 `secret`의 용도를 설명해주실 수 있으신가요??

2022-01-26 07:45 UTC, yanghojoon commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    private let productRegistrationViewControllerIdentifier = "ProductRegistrationViewController"
이전 만들었던 프로토콜을 활용하여 하드 코딩 상수를 제거했습니다! 
만들어놨던 것을 적극적으로 활용하지 못했군요 🥲

다만 StoryBoard 이름의 경우 타입 명과 차이가 있어 이는 ProductRegistrationViewController의 타입 프로퍼티로 가지고 있도록 수정했습니다.

2022-01-26 07:55 UTC, aCafela-coffee commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    private let productRegistrationViewControllerIdentifier = "ProductRegistrationViewController"
> 2. CollectionView cell 각각 xib로 구현
CollectionView의 GridCell, ListCell을 각각 xib파일을 생성하여 storyboard로 구현하였고 두개의 xib에 대한 코드는 ProductCell 하나의 cell로 구성
https://github.com/yagom-academy/ios-open-market/pull/93

이렇게 하면 위 경우에 문제가 있을것 같아요. 이런 경우엔 어떻게 하는지 궁금합니다.

2022-01-26 08:19 UTC, yanghojoon commented on OpenMarket/OpenMarket/Controller/ProductsDataSource.swift
> +    func productId(at index: Int) -> Int? {
Array의 extension을 사용하여 미리 guard 문 내부에 있는 내용을 구현하여 수정했습니다.

2022-01-26 08:27 UTC, yanghojoon commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +        } else {
else를 사용하지 않고 바로 return을 해도 무방했군요! 
else는 삭제했습니다.

2022-01-26 08:28 UTC, aCafela-coffee commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +        if section == 0 {
삼항연산자를 사용하도록 수정했습니다.
다만 if문 보다 가독성이 좋은지는 모르겠습니다. 🧐

2022-01-26 08:39 UTC, yanghojoon commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +        if indexPath.section == 0 {
말씀해주신대로 0, 1 같은 값이 아니라 유의미한 값으로 바꾸는 것이 더 가독성이 좋다고 판단되어 수정했습니다.

2022-01-26 08:56 UTC, yanghojoon commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +        } else {
버튼을 만드는 함수와 imageView를 만드는 함수로 분리했습니다.

2022-01-26 09:01 UTC, yanghojoon commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +    @objc private func textInputDidChange(_ sender: Any?) {
이 부분은 `UITextFieldDelegate`메서드로 구현을 해서 지금 그대로 유지했습니다.

2022-01-26 09:22 UTC, yanghojoon commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +            }
분리 완료했습니다!

2022-01-26 09:23 UTC, yanghojoon commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +            textField === stockTextField {
오 이런 방법이 있었군요! 수정했습니다.

2022-01-26 09:35 UTC, yanghojoon commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
아예 동일한 메서드였군요. 분리 완료했습니다. 추가로 id가 16일 경우 alert도 띄워줘야 해서 해당 코드까지 포함해서 분리했습니다.

2022-01-26 10:21 UTC, aCafela-coffee commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +    private func modifiySalesInformation(
중첩 타입을 만들고, 이 타입을 반환하는 함수를 만들어서 합쳤습니다.

2022-01-26 10:24 UTC, yanghojoon commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +    private let secret = "-3CSKv$cyHsK_@Wk"
현재 프로젝트 명세에는 로그인 기능이 따로 없어서 저희한테 개인적으로 부여된 id와 secret을 상수로 두어 해당 id로 상품을 등록하고 수정할 수 있도록 했습니다. 
API 명세에서 상품 수정과 등록에 id와 secret을 요구하고 있어 사용했습니다.

2022-01-26 10:50 UTC, yanghojoon commented
추가로 코멘트 달아주신 부분에 대한 내용입니다. 

## 해결됨

### 실시간 입력값 유효성 검증

`textView(_:shouldChangeTextIn:replacementText:`

`textField(_:shouldChangeCharactersIn:replacementString:)`

위 메서드를 사용하도록 수정합니다.

### 이미지 피커에서 더블 클릭을 하는 경우 이미지가 2개 올라가는 문제

`picker.isBeingDismissed` 프로퍼티를 확인하여 문제를 해결했습니다. 

### Done버튼 로딩 인디케이터

registerProduct(), modifyProduct() 함수에서 `UIActivityIndicatorView.isHidden = true` 이 프로퍼티를 변경하면 함수가 끝나기 전에는 표시되지 않았습니다.

이를 GCD를 사용하여 해결했습니다.

## 미해결

### 줄바꿈이 너무 빈번하게 일어납니다

한 줄의 최대 글자수를 99자로 제한했습니다. 따라서 매개변수가 길 경우 전부 줄바꿈을 해주도록 하여 해당 규칙을 유지했습니다. 

혹시 이런 경우 어떤 식으로 줄바꿈을 하는 것이 가독성이 더 좋을지 궁금합니다. 

### 꽃 사진만 자동으로 180도 회전이 되는 문제

다른 캠퍼들의 경우 이런 문제는 없는 것 같습니다 🥲😵‍💫

저희도 크롭 전에는 문제가 없는데 크롭을 하면서 꽃 사진만 뒤집히네요...

### iOS 14.0에서 자동으로 컬렉션뷰에 배경색이 설정되는 문제

해당 상황을 영상으로 캡쳐했습니다.

https://user-images.githubusercontent.com/90880660/151150071-36068f59-1e77-45bf-9fb2-490b434bad3c.mp4

2022-01-26 13:33 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +    private let secret = "-3CSKv$cyHsK_@Wk"
그렇다면 이 값들은 api 요청을 담당하는 객체나 혹은 모델들이 갖고 있어야하는 정보이지 않을까 싶어요.

2022-01-26 13:34 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +        if section == 0 {
네네! 저도 삼항연사자를 많이 사용하지 않는데, 둘 중 하나의 경우라면 종종 사용하긴합니다!

2022-01-26 13:38 UTC, protocorn93 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    private let productRegistrationViewControllerIdentifier = "ProductRegistrationViewController"
위 경우라는게 잘 이해가 가질 않는데, `ProductCell` 프로토콜을 사용해서 두 셀을 추상화하신걸 말하시는걸까요? cell을 dequeue하는데는 크게 문제가 없어보입니다.

2022-01-26 14:48 UTC, protocorn93 commented
@yanghojoon @aCafela-coffee 

> 줄바꿈

저는 라인 최대 글자수를 제한해두지 않는 편이에요. 너무 길어진다 싶으면 하긴하죠! 사실 이 기준이라는게 매우 애매한 것 같아요! 어떻게 보면 개인의 코딩 스타일이기도 하구요. 저는 개인적으론 라인 최대 글자수를 조금 여유를 두는편이 어떨까 싶어요! 하지만 역시 개인의 스타일이기에 당장 수정을 하거나 그럴필요는 없습니다! 다만 제가 익숙하지가 않아서 가독성이 떨어진 부분도 있습니다. 

> 꽃 이미지 회전되는 이슈 

저도 관련된 이슈를 찾아보고 해결해보려 했으나 지금은 딱히 해결방안이 보이지 않네요. 근데 비슷한 이슈를 경험한 사례들이 많아 보입니다. 
"CIImage cropping lose orientation"로 검색을 했을 때 많은 글들이 보이기도하구요. 

꽃 사진을 선택했을 때
`UIImage(cgImage: squareImage)`의 결과의 `imageOrientation`은 `.up`이며
`UIImage(cgImage: squareImage, scale: self.scale, orientation: self.imageOrientation)`의 결과의 `imageOrientation`은 `.down`입니다. 아래 생성자를 사용해 이미지를 생성하면 꽃도 정상적으로 노출되긴하네요

반명 다른 사진들은 모두 `imageOrientation`이 `.down`입니다. 이러한 차이점들을 한번 분석해보시면 좋을 것 같네요. 

> iOS 14.0에서 자동으로 컬렉션뷰에 배경색이 설정되는 문제

이 이슈는 작성해주신대로 `.systemBackground`로 지정해주시는걸로 진행해야할 것 같네요. OS 버전 이슈인 것 같기도하구요! 이 부분은 저도 좀 더 실험해보도록 하겠습니다.

2022-01-27 05:36 UTC, aCafela-coffee commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    private let productRegistrationViewControllerIdentifier = "ProductRegistrationViewController"
그 경우가 맞아요.
dequeue에는 문제가 없지만, 프로토콜로 identifier를 관리하는게 직관적인지 의문이 들어서 한 질문이었어요.

프로토콜로 관리할 수 있는 부분은 그렇게 하고, 안되는건 다른 방법으로 관리해도 되겠네요.

2022-01-27 05:46 UTC, aCafela-coffee commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +    private let secret = "-3CSKv$cyHsK_@Wk"
api 요청을 담당하는 타입의 타입 프로퍼티로 변경했습니다.

2022-01-27 06:17 UTC, aCafela-coffee commented
<img width="506" alt="스크린샷 2022-01-27 오후 3 12 19" src="https://user-images.githubusercontent.com/70484506/151302093-6b007bf2-cb88-448e-a998-09f9193e98aa.png">
UIImage.imageOrientation 프로퍼티를 생각 못했네요. 이걸 볼 생각을 못했네요. 🙂

전에 앨범에서 사진 정보를 보려고 했는데, 크래시가 나서 사진 정보를 못보고 있었어요.

2022-01-27 10:22 UTC, merged