오픈마켓2 [STEP 1] 줄라이
yagom-academy/ios-open-market pull request #122
Opened 2022-01-25 14:45 UTC by July911

@protocorn93  
안녕하세요 콘 ...! 
너무 PR이 늦어졌네요 .. 사실 다 구현하지도 못했지만, 일단 
조언을 얻고자 된 부분만 보냅니다 ... 
늘 힘내라고 해주시고 잘하고있다고 말씀해주셔서 감사합니다 :) 

## 🐣공부한점🐣

### 1️⃣코드로 AutoLayout 잡기 
이번 프로젝트는 ... 올 코드로 스토리보드를 지우고 해봤는데, UI요소들간의 스택뷰 -> 스크롤뷰 -> 뷰 로 이어지는 뷰의 계층구조를 이해하는데 
큰 도움이 된 것 같습니다. 물론 시간은 오래 걸렸지만, 값진 경험이었던 것 같습니다.  
특히 스크롤뷰의 frameLayoutGuide와 contentLayoutGuide 의 차이에 대해서 공부하게 되었습니다. 
frameLayoutGuide 는 화면에 보여지는 Scrollview의 크기이고, contentLayoutGuide 는 전체 스크롤뷰의 크기라고 이해했습니다! 

### 2️⃣멀티파트폼 
멀티파트폼 데이터로 post를 보내는 기능을 구현했습니다 . 오타..수정하는데 큰 어려움을 겪었습니다 . 
### 3️⃣캐시구현
NSCache 로 캐싱을 해주어, 용량이 큰 (서버에서 통신의 비용이 큼) 이미지를 빨리 로드할 수 있게 했습니다. 
### 4️⃣diffableDatasource 
DataSource 배정 -> snapshot -> DiffableDataSource -> dequeue로 이어지는 흐름을 이해했습니다 ! 

### 🐣궁금한점🐣

### 1️⃣노티피케이션의 활용  + delegate 패턴 사용 
delegate 패턴을 사용하려고 했으나, Manager 가 ViewController 한테 주어야하는 메시지가 뭔지 모르겠습니다.

![스크린샷 2022-01-25 오후 11 13 00](https://user-images.githubusercontent.com/90888402/150993015-6ff87a4e-2151-42b3-8b9f-962366e57c42.jpg)
 

--> 사진 1 

![스크린샷 2022-01-25 오후 11 12 46](https://user-images.githubusercontent.com/90888402/150993100-2cee0857-b0b3-438e-9525-68e669917781.jpg)

--> 사진 2 

사진 1 에서 프로퍼티로 만들어준 뷰컨에 사진2의 delegate 에서 어떻게 전달을 해주어야 할까요 ..? 

### 2️⃣리사이징 (모르고 사용) 
```swift
extension UIImage {
    func resizing(size: CGSize, scale: CGFloat = UIScreen.main.scale) -> UIImage {
        let imageSourceOption = [kCGImageSourceShouldCache: false] as CFDictionary
        let data = self.pngData()! as CFData
        let imageSource = CGImageSourceCreateWithData(data, imageSourceOption)!
        let maxPixel = max(size.width, size.height) * scale
        let downSampleOptions = [
            kCGImageSourceCreateThumbnailFromImageAlways: true, kCGImageSourceShouldCacheImmediately: true, kCGImageSourceCreateThumbnailWithTransform: true, kCGImageSourceThumbnailMaxPixelSize: maxPixel] as CFDictionary
        
        guard let downSampledImage = CGImageSourceCreateThumbnailAtIndex(imageSource, 0, downSampleOptions) else {
            return UIImage()
        }
        
        let newImage = UIImage(cgImage: downSampledImage)
        
        return newImage
    }
```

모르는 메서드 ... 사용해도될까요 ..? 
공부 하면서 사용하긴했는데, 이해가 아예 안되는 코드를 기능 구현을 위해 추가한적은 처음이라 
혼란이 옵니다.이럴 경우, 아는 다른 아는 메서드를 사용하는게 맞을까요 ? 
아니면 이러한 상황에 익숙해지는게 나을까요?  

### 3️⃣뷰와 뷰컨의 구분 + 뷰컨의 비대화 
뷰컨트롤러가 너무 커져버렸습니다. 그래서 상속과 프로토콜, 상속과 채택을 통한 공통기능 구현이 어렵습니다. 뷰 (UI 요소)를 따로 빼주는게 맞을까요??

2022-01-26 13:31 UTC, protocorn93 requested changes
@July911 너무 고생하셨어요! 기능의 완성도는 아직은 미흡하지만 전체적으로 훌륭한 가독성과 역할별로 잘 나누어진 메서드들로 코드를 이해하고 줄라이가 어느 부분에서 어려움을 겪고 계신지 이해할 수 있었습니다! 

## 공부한점 

> 코드로 레이아웃 잡기

이런 연습은 매우 중요한 것 같아요. 더불어 코드로 레이아웃을 작성하는데 익숙해지시면 Snapkit도 한번 사용해보시는걸 권장드려요! 

> 캐시 구현 

아주 훌륭한 접근 방법이에요!! 

## 궁금한점 

> 노티피케이션의 활용 + delegate  패턴 사용 

`PostManager`는 보아하니 상품 등록  api 요청을 담당하는 객체로 보여요. 그렇기 때문에 먼저 `delegate`는 불필요해보입니다. `ImageLoader` 처럼 `completion`을 인자로 받고 사용하는 곳에선 결과를 받아 처리하는 코드를 클로저에 작성해주면 되지 않을까 싶어요. 

> 리사이징 

다운샘플링을 해주셨군요! 훌륭해요! 

네네 문제를 해결하기 위해선 모르는 코드도 사용해야할 때가 있습니다. 여기서 변수, 클래스 하나하나 모두 이해하면 너무 좋죠. 하지만 여기서 이해해야할 개념은 다운샘플링입니다. 이 개념을 이해하고 이를 구현한 코드를 이해하고 주변 요소들을 이해해나가는 과정으로 학습을 해보시는걸 권장드려요! 

모르는 코드를 사용할 수는 있으나, 추후 학습은 반드시 따라와야겠죠! 그리고 이는 이미지 핸들링에 특화된 코드고 지식이기에 어느정도 이해하고 넘어가는 수준까지 학습하셔도 무방하다고 생각해요. 본인이 생각하시기에 보다 확실히 이해하고 싶고 이를 응용하고 싶다면 보다 깊은 수준의 이해를 위한 학습이 추가로 필요하겠죠! 

> 뷰와 뷰컨틔 구분 + 뷰컨의 비대화 

뷰 컨트롤러의 비대화는 MVC 구조에서는 어쩔 수 없다고 생각해요. 이를 위해 다양한 패턴들이 등장하죠! 대표적으로 MVVM이 있습니다.  MVVM의 구조대로 코드를 작성하게 된다면 뷰컨트롤러에는 화면 레이아웃과 관련된 코드 + 사용자 인터렉션을 뷰모델에 전달해주는 코드만 남게되겠죠! 

비즈니스 로직은 모두 뷰모델로 들어가게 됩니다. 그에 따라 관련 프로퍼티도 함께 이동하겠죠! MVVM에 관해 상당히 많은 글들과 영상이 있습니다. 모두 도움이되고 유익한 자료들이지만 그들에 앞서 [이 영상](https://youtu.be/M58LqynqQHc)을 먼저 보시는걸 권장해드려요. 

결국 뷰 컨트롤러가 비대해지는것은 MVC 구조라면 어쩔 수 없는 결과이고 다양한 아키텍처르 통해 이러한 문제를 해결할 수 있습니다.

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/Model/ImageLoader.swift
> +        if let imageData = ListDataStorager.cachedImages.object(forKey: urlString as NSString) {
캐시를 사용해 리소스를 줄인 점 훌륭합니다!

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/Model/NetWork/Extension/String+Extension.swift
> +        guard let number = Double(self) else {
프로퍼티 이름은 `decimal`인데 `Double`로 타입 캐스팅을 해주는 이유가 궁금하네요!

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/Model/NetWork/ParsingType/ProductDelete.swift
> +        let discountedPrice: Double
기능 명세와 디스코드 히스토리를 보았을 때 `Double`보단 `Decimal` 타입이 좀 더 알맞아보이네요

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/Model/NetWork/Protocol/JSONResponseDecodable.swift
> +protocol APIAble: JSONResponseDecodable & APIRequestable {
`APIable`이 맞는 철자법같습니다. 네이밍이 모호하기도하네요!

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/ImageCollectionViewCell.swift
> +        imageView.frame = self.bounds
frame 기반으로 레이아웃을 잡아주기보단 오토레이아웃으로 잡아주는건 어떨까요?

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/ImageCollectionViewCell.swift
> +    }()
다른 뷰 코드들은 프로퍼티 선언부가 객체 생성자 혹은 라이프사이클 메서드보다 위에 위치하는데 `imageView`도 이와 맞춰가면 좋을 것 같아요!

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/ImageCollectionViewCell.swift
> +    }()
또한 `let`으로 선언되어도 무방해보이며 `updateImage(to:)` 메서드를 통해 이미지를 할당하니 `private`으로 가져가는게 좋아보여요

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/ImageCollectionViewCell.swift
> +    func layoutImageView() {
접근제어자가 필요해보이네요!

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/RegisterImageView.swift
> +    }()
위 두 뷰 컴포넌트는 `lazy var`로 선언될 필요가 없어보이네요! 접근제어자 역시 필요해보입니다.

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/RegisterImageView.swift
> +        productEnrollImageView.translatesAutoresizingMaskIntoConstraints = false
저는 `translatesAutoresizingMaskIntoConstraints = false` 역시 뷰 선언부에 함께 작성합니다.

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarketTests/NetworkingTests.swift
> +//    }
주석은 제거해주시는게 좋아요!

사소할 수 있지만 추가로 코멘트를 남기자면, 실제로 제가 속한 팀의 프로젝트에도 이러한 주석처리로 남아있는 코드가 종종 있습니다. 이를 그때그때 제거해주지 않으면 다른 팀원이 보기엔 이 코드에 대한 히스토리를 모르기 때문에 함부로 지우기도 애매하고 그런 상황이 발생합니다. 또한 주석 처리한 개발자도 이를 잊어버리게 되면 영영 이런 코드는 지워지지 않고 계속 남아 혼선을 일으킬 수 있어요! 

되게 사소할 수 있지만 협업을 하고 지속적으로 프로젝트를 디벨롭해나가는데 의외로 걸림돌이 될 수 있어요!

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/Model/PostManager.swift
> +}
`PostManager`에 대한 코멘트는 PR 코멘트에 대한 답변으로 대체하겠습니다!

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductPageViewController.swift
> +    private var isPaging: Bool = true
프로퍼티 선언 순서도 고려해보시면 좋을 것 같아요. 

```swift 
// MARK: - Inner types 

...

// MARK: Views 

...

// MARK: Properties


```

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductPageViewController.swift
> +    private var gridDataSource: UICollectionViewDiffableDataSource<Section,page>?
데이터소스도 `typealias` 처리해주면 어떨까요?

`typealias  ListDataSource = UICollectionViewDiffableDataSource<Section, page>`

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductPageViewController.swift
> +        gridCollectionView.delegate = self
이 두 줄의 코드도 `configureCollectionView` 내부에 위치하면 좋을 것 같아요

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductPageViewController.swift
> +        if position > (collectionView.contentSize.height-100-scrollView.frame.height), isPaging {
계산식을 작성할 때는 연산자와 대상 사이는 띄어쓰기를 해주시는게 좋습니다!

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductRegisterViewController.swift
> +    @frozen enum ImageSection: Hashable {
`@frozen`을 사용하신 이유가 궁금하네요

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductRegisterViewController.swift
> +        postManager.delegate = self
이 영역의 코드들도 각각 메서드로 분리해볼 수 있을 것 같아요.

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductRegisterViewController.swift
> +    private var imageDataSource: UICollectionViewDiffableDataSource<ImageSection,UIImage>?
```swift
private lazy var imageDataSource: ImageDataSource = createDataSource()
```
와 같은 코드로 데이터소스를 생성해주고 할당해주면 불필요한 옵셔널을 제거할 수 있을 것 같아요!

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductRegisterViewController.swift
> +    private var registerImage = RegisterImageView()
`registerImageView`라는 네이밍이 더 적절할 것 같아요!

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductRegisterViewController.swift
> +        checkReadyToPost()
`params`가 뷰컨트롤러 프로퍼티로 존재하는데, 그럴 필요가 있나 싶네요! 

`post` 메서드 안에서 로컬 변수로 존재하는게 관리차원에서 수월하지 않나 싶어요. 뷰컨트롤러 프로퍼티로 위차한다면 해당 프로퍼티에 접근하는 메서드들에서 값의 상태를 고려하게 되더라구요. 하지만 인자로 넘어온 값이라면 이러한 상태에 대해서 신경을 쓰지 않아도 됩니다.

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductRegisterViewController.swift
> +        if readyToPost ?? false {
`readyToPost`도 `checkReadyToPost`가 반환해주는게 어떨까요?

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductRegisterViewController.swift
> +        let secretKey = "$4VptmhDPzSD3#zg"
이 값은 뷰컨트롤러 내부에 위치하지 않는게 좋아보여요. 네트워크 요청을 하는 곳에서 알고 있어야 하는 정보가 아닌가 싶어요

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/CollectionViewGridCell.swift
> +        ImageLoader.load(from: item.thumbnail) { (result) in
이미지 로드는 뷰컨트롤러에서 진행하고 결과만 셀에 넘겨주는 방법에 대해서는 어떻게 생각하시나요?

2022-01-26 13:31 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductRegisterViewController.swift
> +       }
코드 indent가 안맞네요!

2022-01-27 03:50 UTC, July911 commented on OpenMarket/OpenMarket/ProductPageViewController.swift
> +    private var gridDataSource: UICollectionViewDiffableDataSource<Section,page>?
와 정말 ...좋은 방법이네요 가독성이 훨씬 올라갔습니다 ! 감사합니다 :)

2022-01-27 03:59 UTC, July911 commented on OpenMarket/OpenMarket/ProductRegisterViewController.swift
> +    @frozen enum ImageSection: Hashable {
final 비슷한 느낌으로 사용한거같은데, 알아보니 적절하지 않은것 같아 수정했습니다. 
공식문서를 보고 적절한지 확인하고 사용하도록 하겠습니다. 감사합니다 :)

2022-01-27 04:16 UTC, July911 commented on OpenMarket/OpenMarket/ProductRegisterViewController.swift
> +    private var imageDataSource: UICollectionViewDiffableDataSource<ImageSection,UIImage>?
기존코드 
```swift 
private func configureCellDataSource() {
        let cellRegistration = UICollectionView.CellRegistration<ImageCollectionViewCell, UIImage> {
            (cell, indexPath, item) in
        }
        
        imageDataSource = collectionViewDataSource(collectionView: imageCollectionView) {
            (collectionView, indexPath, item) -> UICollectionViewCell? in
            let cell = collectionView.dequeueConfiguredReusableCell(
                using: cellRegistration,
                for: indexPath,
                item: item
            )
            cell.updateImage(to: item)
            
            return cell
        }
    }
```

2022-01-27 04:16 UTC, July911 commented on OpenMarket/OpenMarket/ProductRegisterViewController.swift
> +    private var imageDataSource: UICollectionViewDiffableDataSource<ImageSection,UIImage>?
수정코드 
```swift
collectionViewDataSource(collectionView: imageCollectionView) {
            (collectionView, indexPath, item) -> UICollectionViewCell? in
            let cell = collectionView.dequeueConfiguredReusableCell(
                using: cellRegistration,
                for: indexPath,
                item: item
            )
            cell.updateImage(to: item)
            
            return cell
        }
```

2022-01-27 05:09 UTC, July911 commented on OpenMarket/OpenMarket/View/CollectionViewGridCell.swift
> +        ImageLoader.load(from: item.thumbnail) { (result) in
코멘트 주신 내용의 의미를 VIewController내부의 dequeue하는 부분에서 image 를 로드하고 씌어주라는걸로 이해해도 될까요??

2022-01-27 05:19 UTC, July911 commented on OpenMarket/OpenMarket/Model/ImageLoader.swift
> +        if let imageData = ListDataStorager.cachedImages.object(forKey: urlString as NSString) {
감사합니다 !!! :) 열심히했는데 뿌듯하네요 확실히 더 빨라진거같습니다

2022-01-27 06:42 UTC, July911 commented on OpenMarket/OpenMarket/Model/NetWork/Extension/String+Extension.swift
> +        guard let number = Double(self) else {
String extension이라, 숫자가 아닌 문자열이 들어오는 상황에 대처하기 위해서 이렇게 작성했습니다!

2022-01-27 06:43 UTC, July911 commented on OpenMarket/OpenMarket/Model/NetWork/Protocol/JSONResponseDecodable.swift
> +protocol APIAble: JSONResponseDecodable & APIRequestable {
수정하였으나, 필요없는 프로토콜이라 판단이 되어서 삭제했습니다! 감사합니다 👍

2022-01-27 06:47 UTC, July911 commented on OpenMarket/OpenMarket/Model/NetWork/ParsingType/ProductDelete.swift
> +        let discountedPrice: Double
decimal 타입이 있는걸 처음알았습니다 ... 너무 무지하네요 제가 
덕분에 알게되었습니다. 명세를 좀 더 꼼꼼하게 확인해봐야겠네요 감사합니다!!!

2022-01-27 07:16 UTC, July911 commented on OpenMarket/OpenMarket/ProductRegisterViewController.swift
> +        postManager.delegate = self
```swift
    override func viewDidLoad() {
        super.viewDidLoad()
        configureView()
        
        configureCellDataSource()
        setDelegateToOwn()
       
        addSubviews()
        configureNavigationItem()
        configureUIItemLayouts()
      
        addTapGesture()
        addTargetToRegisterImage()
    }
```
기능별로 분류해주었습니다 ! :) 감사합니다 더 가독성이 올라갔어요 !

2022-01-27 12:17 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/CollectionViewGridCell.swift
> +        ImageLoader.load(from: item.thumbnail) { (result) in
네네! ImageLoader 호출은 뷰 컨트롤러에서 진행하고 컴플리션 핸들러에서 `cell.이미지할당메서드` 해줄수있을 것 같아요. 

저는 셀도 뷰컨트롤러의 버튼처럼 뷰컨트롤러 위에 올라가있는 뷰로 취급합니다.

2022-01-27 12:18 UTC, merged