오픈마켓2 [STEP 1] 숲재
yagom-academy/ios-open-market pull request #125
Opened 2022-01-26 11:57 UTC by forestjae

쿠마 안녕하세요 ! @leejun6694 
오픈마켓 2 스텝 1 PR보내드려요!!
하다보니 욕심도 나고, 중간중간 트러블이 있어서 약속된 기한을 많이 어기게 되었네요 😭
잘부탁드립니다 !!

# 구현 내용
![Simulator Screen Recording - iPhone 13 Pro - 2022-01-26 at 20 19 35-min](https://user-images.githubusercontent.com/76479760/151154961-cc823479-2e2c-4186-9555-3e0b02c05b75.gif)

![Simulator Screen Recording - iPhone 13 Pro - 2022-01-26 at 20 38 09](https://user-images.githubusercontent.com/76479760/151156952-7eb8b118-f73e-4298-bcc1-0aec27f40094.gif)

- `URLCache` 를 사용한 이미지 캐싱을 구현하였습니다.
- 상품 수정/등록화면의 상위 클래스인 ManageProductVC를 만들고 수정/등록 화면은 상속을 통하여 구현했습니다.
- 300KB 가 넘는 이미지는 이미지 등록시점에 압축합니다.
- 상품등록 화면에서 등록할 이미지를 보여주는 콜렉션 뷰는 Horizontal ModernCollectionView를 사용하여 구현하였습니다.
- 상품등록 화면에서 입력한 요소들이 적절한지를 검증하는 별도의 메서드를 만들었습니다.
    - 해당 검증을 통과하지 못하면 Alert으로 어느부분이 통과하지 못했는지 알려줍니다.
    - 검증을 통과하면 상품 등록 네트워킹을 진행합니다.
- 텍스트 뷰에서 현재 커서위치에 따라 내용이 가리지 않게 화면을 조정하는 기능을 구현했습니다.

(* 상품 수정은 현재 뼈대만 만들어놓고 스텝 2에서 구현하려고 합니다!)

# 고민한 내용
### 캐싱

캐싱의 경우 용량이 큰 이미지에 대해서만 진행하였습니다. Caching 정책과 디스크 Chacing을 쉽게 설정해 줄 수 있는 `URLCache` 를 사용하여 구현하였습니다. 

### 컬렉션 뷰

오픈마켓1 프로젝트와 마찬가지로 모던 컬렉션 뷰를 사용하여 상품등록화면에서의 이미지 컬렉션 뷰를 구현하였습니다. 다만 Horizontal 컬렉션 뷰이기 때문에 CompositionalLayout에서의 Scroll Direction Configuration을 Horizontal로 지정해야 된다는것을 간과해서 엄청 헤맸네요 😂

### 입력내용 검증

상품등록 화면에서 입력내용을 검증하는것을 별도의 타입에서 진행하도록 하였습니다. 일부 항목에 대해서 검증을하는것이 아닌 전체 항목에 대해서 한꺼번에 검사를 하고 부족한 부분을 Alert으로 띄워주었습니다.

# 해결이 되지 않은 점

### 텍스트 뷰 키보드 대응

 위에 구현내용에서 말씀드렸다시피, TextViewDelegate와 CaretRect메서드를 사용하여 현재 커서의 위치를 추적하여 키보드에 내용이 가리지 않게 구현했습니다. 다만, 아래와 같이 다른곳을 터치하여 textview의 편집이 끝난 후 다시 textView로 focus를 가져가게 되면 기존에 입력된 offset값이 저장되어 있는건지 원하는대로 동작하지 않는 현상이 발생합니다. textView.caretRect(for: start)부분에서 textview의 foucs를 해제하기 이전의 offset값을 한번 반환 주어서 발생하는 문제로 보이는데 해결하지 못했습니다. 

해당 기능은 상용앱에서는 필수적으로 구현되어야 할 기능같은데 혹시 구현에 참고할만한 라이브러리나 쿠마의 의견을 부탁드립니다ㅜㅜ

```swift
func textViewDidBeginEditing(_ textView: UITextView) {
        //...

        guard let start = textView.selectedTextRange?.start else {
            return
        }

        let offset = textView.caretRect(for: start)
        let cursorOffsetY = offset.origin.y + textView.frame.origin.y + 22
        let targetOffsetY =
            offset.origin.y - frameLayoutHeight.constant + textView.frame.origin.y + 22

        if cursorOffsetY >= scrollView.frameLayoutGuide.layoutFrame.height {
            scrollView.contentOffset.y = targetOffsetY
        }
    }
```
![Simulator Screen Recording - iPhone 13 Pro - 2022-01-26 at 20 46 01](https://user-images.githubusercontent.com/76479760/151157933-0cd21e49-19a1-446a-be54-fe3f7b81807f.gif)

# 조언을 얻고 싶은 부분

### 하나의 상위 뷰컨을 상속하는 형태의 구현

뷰 컨트롤러의 상속은 이번에 처음 해보게 되었는데요, 최대한 공통적인 기능을 상위 뷰컨에 담고 하위 뷰컨에서는 필요 시 override하거나 추가 구현을 하여 만들어 보았습니다. 이런식의 구현이 맞는건지, 좀 더 개선해 볼 부분이 없는지 궁금합니다!

### View의 역할

두번째 화면을 구현하면서, 화면의 핵심이 되는 뷰인 StackView를 `ProductRegisterView` 라는 별도의 커스텀 뷰로 분리하였습니다. 다만 이렇게 하니, delegate설정이나 뷰 요소의 값을 가져오거나 할때 별도의 함수를 구현해서 값을 전달해야 하는 상황이 발생했습니다. 또, View에서 하지말아야 할 view요소 외적인 계산이나 기능을 구현해 주는데에 애를 먹었습니다. 이러한 방식으로 커스텀 View를 구현할때 View의 역할은 어느정도까지로 한정해야되는지 궁금합니다 !

읽어주셔서 감사합니다!

2022-01-28 02:50 UTC, leejun6694 requested changes
숲재 안녕하세요!
step 1 구현하시느라 고생 많으셨습니다.
Cache 도 사용해보고, 구현하시면서 다양한 고민을 해보신게 코드에 보이네요 : )
다만, 코딩 컨벤션이나 사소한 실수들이 눈에 보입니다. 이런 점들이 기본을 해치게 되면서 아쉬운 점으로 남네요ㅠㅠ
그리고 pr 하나에 코드 양이 너무 많아서, 구조나 더 깊게 확인해야하는 부분들을 제가 놓쳤을 수도 있습니다. 추후에 프로젝트를 진행하시다가, 하나의 pr 이 너무 길어질 것 같으면 끊어서 제출하는 것도 방법이 되겠네요!
참고 부탁드립니다~~!

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/CacheManager.swift
> +class CacheManager {
👍 👍 👍

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/CacheManager.swift
> +               in: .allDomainsMask,
들여쓰기가 어긋난 부분 같네요

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/CacheManager.swift
> +        if self.imageCache.cachedResponse(for: request) == nil {
중복되는 프로세스가 생기게 될 것 같습니다.
`cachedResponse` 의 data 가 있는 경우, 바로 핸들링하고 아닌 경우 download 하는건 어떨까요?
그리고 좀 더 안전성을 더해서, data 로 이미지를 불러오기를 실패하는 케이스도 download 가 진행되면 어떨까 생각됩니다.

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/CacheManager.swift
> +    static func downloadImage(
access control ...!?

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Domain/Catalog/ProductsCatalogViewController.swift
> +    var isPagingable: Bool = true
type 정의가 생략 가능합니다 : )

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Domain/Catalog/ProductsCatalogViewController.swift
> +    @objc func touchUpRegisterButton() {
access control...!

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Domain/Catalog/ProductsCatalogViewController.swift
> +        self.present(navigationController, animated: true)
프로젝트 전반적으로 `self` 가 명시되는 곳과 명시되지 않는 코드들이 있습니다.
하나의 규칙으로 통일성을 주면 좋을 것 같습니다

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Domain/Catalog/ProductsCatalogViewController.swift
> +            view = grid
굳이 투스텝으로 할 필요가 있을까...? 생각이 듭니다 ㅎㅎ

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Domain/Catalog/ProductsCatalogViewController.swift
> +//        collectionView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
pr 제출 시엔, 가급적 주석은 제거해주세요 : )
주석이 필요한 사유가 있다면, 작성 부탁드립니다.

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Domain/ManageProduct/AddImageHeaderView.swift
> +            addButton.heightAnchor.constraint(equalTo: self.widthAnchor)
오잉, 네 방향의 layout 이 모두 잡혔는데, 이 코드가 추가된 이유가 있을까요?

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Domain/ManageProduct/AddImageHeaderView.swift
> +        addButton.translatesAutoresizingMaskIntoConstraints = false
중복된 코드로 보입니다.

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Domain/ManageProduct/ManageProductManager.swift
> +class ManageProductManager {
앞뒤로 Manage 가 있어서 조금 어색하네요 😆

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Domain/ManageProduct/ManageProductManager.swift
> +        if !form.nameIsAppropriate {
`form` 의 항목이 늘어나면 여기 If 문도 덩달아 쭉 길어지겠네요.
더 좋은 방법이 있을지 고민해볼까요?

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Domain/ManageProduct/ManageProductManager.swift
> +                compressedImageData = data
`return` 을 바로 해도 문제는 없겠네요ㅎㅎ

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Domain/ManageProduct/ManageProductManager.swift
> +    var nameIsAppropriate: Bool {
Bool type 의 경우, 의문문으로 정의되면 좋겠네요ㅎㅎ

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Domain/ManageProduct/ManageProductManager.swift
> +        return true
`return price != ""`
로도 구현이 가능하겠네요
다른 친구들도..?

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Domain/ManageProduct/ManageProductManager.swift
> +    var description: String {
rawValue 로 string 값을 두는건 어떨까요?

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Model/Product.swift
>      case KRW
KRW, USD 가 대문자여서 어색하네요..!
enum 의 case 가 대문자로 정의된 이유를 알 수 있을까요?

2022-01-28 02:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Domain/ManageProduct/RegisterProductViewController.swift
> +        do { let result = try manageProductManger.isAppropriateToRegister(form: form)
줄바꿈이 필요할 것 같네요...!

2022-01-28 03:08 UTC, forestjae commented on OpenMarket/OpenMarket/CacheManager.swift
> +               in: .allDomainsMask,
다른 경우에는 줄바꿈 시 자동으로 맞춰 주던데, 무슨 이유인지 이건 `ctrl + i` 를 눌러도 저런식으로 이상하게 줄이 맞춰지는군요 😂 줄 맞추어 수정해 주었습니다.

2022-01-28 03:32 UTC, forestjae commented on OpenMarket/OpenMarket/CacheManager.swift
> +        if self.imageCache.cachedResponse(for: request) == nil {
좋은 지적이십니다!! cachedResponse를 확인하는 과정이 중복되어 있기에 해당 과정을 하나로 줄이고 캐시로드와 이미지 변환 실패시 다운로드를 재 진행하는 것으로 로직 변경하였습니다.

```swift
static func fetchImage(imageURL: URL, completionHandler: @escaping (UIImage) -> Void) {
        let request = URLRequest(url: imageURL)

        self.loadImageFromCache(request: request) { result in
            switch result {
            case .success(let image):
                completionHandler(image)
            case .failure:
                self.downloadImage(request: request) { image in
                    completionHandler(image)
                }
            }
        }
    }
```

2022-01-28 03:37 UTC, forestjae commented on OpenMarket/OpenMarket/Domain/Catalog/ProductsCatalogViewController.swift
> +        self.present(navigationController, animated: true)
지난번에도 지적받았던 건데.. 고치지 못한것 같습니다. 

self키워드가 꼭 필요한 곳에만 붙여주는게 좋을까요? 쿠마는 self키워드를 어떤 기준으로 붙여주시는지 궁금합니다!

2022-01-28 03:42 UTC, forestjae commented on OpenMarket/OpenMarket/Domain/Catalog/ProductsCatalogViewController.swift
> +            view = grid
수정하였습니다!

2022-01-28 03:47 UTC, forestjae commented on OpenMarket/OpenMarket/Domain/ManageProduct/AddImageHeaderView.swift
> +            addButton.heightAnchor.constraint(equalTo: self.widthAnchor)
정사각형으로 하기 위해 추가해논 코드인데, 말씀해주신대로 layout이 모두 잡힌 상황이고 이미 cellLayout에서 정방형으로 설정해주고 있어 해당 코드를 삭제하였습니다!

2022-01-28 03:48 UTC, forestjae commented on OpenMarket/OpenMarket/Domain/ManageProduct/AddImageHeaderView.swift
> +        addButton.translatesAutoresizingMaskIntoConstraints = false
삭제하였습니다!

2022-01-28 04:04 UTC, forestjae commented on OpenMarket/OpenMarket/Domain/ManageProduct/ManageProductManager.swift
> +                compressedImageData = data
아래와 같이 수정하라는 의도가 맞으실까요? 
```swift
            } else {
                compressedImageData = data
                return compressedImageData
            }
```

2022-01-28 04:12 UTC, forestjae commented on OpenMarket/OpenMarket/Domain/ManageProduct/ManageProductManager.swift
> +    var description: String {
다른 rawValue가 필요한 상황이 아니기에 CustomStringConvertible을 굳이 사용할 필요가 없겠네요!

CustomSTringConvertible프로토콜은 rawVlaue를 별도로 가지고 있으면서 String Descriptions이 필요할 때 사용하는 것으로 이해하면 될까요?

2022-01-28 04:14 UTC, forestjae commented on OpenMarket/OpenMarket/Domain/ManageProduct/ManageProductManager.swift
> +    var nameIsAppropriate: Bool {
isAppropriateName과 같은 형태로 수정하였습니다.

2022-01-28 04:15 UTC, forestjae commented on OpenMarket/OpenMarket/Model/Product.swift
>      case KRW
ㅠㅠ 기본적인 컨벤션 실수를 해버렸네요... rawValue값을 별도로 부여하였습니다!

2022-01-28 05:41 UTC, forestjae commented on OpenMarket/OpenMarket/Domain/ManageProduct/ManageProductManager.swift
> +class ManageProductManager {
UpdateProductManager로 네이밍 변경했습니당

2022-01-28 06:01 UTC, forestjae commented on OpenMarket/OpenMarket/Domain/ManageProduct/ManageProductManager.swift
> +        if !form.nameIsAppropriate {
이 방법 때문에 엄청 고민을 많이 했는데요...

enum을 활용하면서 if문을 쓰지 않을 수 있는 방법을 찾지 못했습니다 ㅜㅜ.. 혹시 힌트를 주실만한게 있을까요?

2022-01-29 14:23 UTC, leejun6694 commented on OpenMarket/OpenMarket/Domain/Catalog/ProductsCatalogViewController.swift
> +        self.present(navigationController, animated: true)
저는 꼭 필요한 부분만 붙여주고 있습니다ㅎㅎ 꼭 필요하다는걸 강조하는 효과를 줄 수 있습니다 : )

2022-01-29 14:23 UTC, leejun6694 commented on OpenMarket/OpenMarket/CacheManager.swift
> +               in: .allDomainsMask,
앗 그런가요...?

2022-01-29 16:02 UTC, leejun6694 commented
> 하나의 상위 뷰컨을 상속하는 형태의 구현

네, 뷰컨트롤러 상속도 좋은 경험이 되셨을 것 같습니다. UI 나 기능들이 공통적으로 사용된다면, 상속도 좋은 방법이지만 저는 ViewController 는 가급적 상속을 하지 않는 편입니다. 사실 상속 자체를 많이 사용하지 않습니다..ㅎㅎ
UI 의 경우, 공통적으로 쓰이는 View 를 따로 만들어서 넣어주기도 하고, 기능들도 manager 나 model 을 공유해서 사용 등 방법은 여러가지가 있습니다 : )
제 의견은 우선 참고만 하시고, 이와 관련된 공부나 자료를 찾아보면서 숲재만의 스타일을 만들어가시길 추천드립니다~~!

> View의 역할

음.. view 의 역할은 custom view 라고 하더라도, 우리가 알고 있는 view 역할이여야 합니다ㅎㅎ
delegate 는 거의 아마 필요한 경우가 많겠지만, 외적인 계산이나 기능은 view 구현에선 지양해야할 것 같네요...!

2022-01-29 16:07 UTC, leejun6694 approved these changes
UI 구현과 처음 접해보는 기능들로 기간이 길어졌지만, 끝까지 프로젝트 구현하느라 고생 많으셨습니다 : )
아쉬운 부분이 조금 있는데, 연휴가 지나고 디스코드에서 같이 얘기해봐요ㅎㅎ

2022-01-29 16:07 UTC, merged