오픈마켓 II [STEP 1] 고사리
yagom-academy/ios-open-market pull request #128
Opened 2022-01-28 05:29 UTC by FIIIIN

안녕하세요 코리! @corykim0829

눈 깜짝할 사이에 시간이 흘러버렸네요....🤯

패닉된 상황에 문제 파악을 위한 단계를 제시해주셔서 큰 도움이 되었습니다🙏

이번 리뷰도 잘 부탁드려요!!

---

## 1. 고민한 점

> 1-1.
> 

상품 등록 페이지와 수정 페이지가 동일한 루트를 타지 않고, 후자의 경우 step 2에서 구현하는 상세 페이지의 정보를 통해 들어가기 때문에 이후 진행하려고 하였으나 시간 부족의 이유로 상품 등록 페이지만 구현하게 되었습니다.

> 1-2.
> 

상품 등록 페이지와 수정 페이지의 공통기능을 상속이나 POP로 분류하여 viewController 각각의 책임을 줄일 수 있었으나, 위의 이유(상품 수정 미구현) 때문에 책임을 줄이기 어려웠습니다. 해당 문제는 `extension을 별도의 파일에서 관리`함으로써 조금이라도 가독성을 높일 수 있도록 진행했습니다.

1-3.

textField와 달리 `textView`에는 placeHolder를 지정하는 메서드가 없어 `textViewDidEndEditing`과 `textViewDidBeginEditing` 두 메서드를 사용하여 비슷한 기능을 구현하였습니다.

## 2. 트러블 슈팅

> 2-1.
> 

문제상황: status code 400과 함께 JSON parse error가 발생했습니다.

![](https://i.imgur.com/TxvZCga.png)

해결: 데이터와 행 나눔을 한꺼번에 데이터 형 변환하지 않도록 수정하였습니다.

```swift
body.append(encodedData)
body.append(string: "\r\n")
```

> 2-2.
> 

문제상황: 아무런 메세지 없이 400 에러가 발생했습니다.

![](https://i.imgur.com/nOVKsWy.png)

해결: params 내부에 위치한 secret 키의 오타를 수정하였습니다.

> 2-3.
> 

문제상황: 레이아웃 작업을 모두 메인 스레드에서 작업하라는 런타임 에러가 발생했습니다.

![](https://i.imgur.com/gGr6fLo.png)

해결: alert을 present해주는 것 또한 UI와 관련된 작업이었고, main.async로 수정하였습니다.

> 2-4.
> 

문제상황: 시뮬레이션의 키보드가 노출되지 않고 오류메세지를 띄우는 문제가 발생했습니다.

![](https://i.imgur.com/3Cp7Zkf.png)

해결: I/O → Keyboard → Connect HardWare Keyboard 설정을 껐다 켜는 것으로 문제를 해결했습니다.

> 2-5.
> 

문제상황: `unrecognized selector sent to instance` 런타임 에러 메세지가 발생했습니다.

![](https://i.imgur.com/P7V6eSv.png)

해결: `#selector(self.pickImage(_:))` 와 같이 셀렉터의 형식 변경하였습니다.

> 2-6.
> 

문제상황: 커밋하는 과정에서 아래와 같은 에러메세지가 발생했습니다.

```swift
error: pathspec '.../contents' did not match any file(s) known to git.
```

해결: 깃 케이스의 설정을 변경했습니다. (`git config core.ignorecase false --global`)

> 2-7.
> 

문제상황: 400 에러와 함께 `Failed to parse multipart servlet request` 메세지가 발생했습니다.

![](https://i.imgur.com/ezoH5lk.png)

해결: httpBody의 형식에 문제가 있었고, 이를 수정하였습니다.

## 3. 조언을 얻고 싶은 부분

> 3-1.
> 

지난 PR에서 collectionView와 tableView를 모두 사용한 것이 효율적이지 못하다는 이야기를 해주셨는데, 그 이유가 궁금합니다. `Consider using a table instead of a collection for text.` HIG의 해당 내용을 토대로, 각각의 뷰가 가지는 특징을 유지하는 것이 나을 것이라고 판단하였는데, 개발 효율의 측면에서는 다르게 볼 수 있을까요?

> 3-2.
> 

이미지의 용량을 낮추는 방법을 고민하였습니다. 해당 프로젝트의 경우, 사이즈를 줄임으로써 용량을 낮추도록 하였습니다. 특정 이미지의 경우 여전히 용량문제가 해결되지 않는 이슈가 발생하여  [WWDC 2018 Image and Graphics Best Practices](https://developer.apple.com/videos/play/wwdc2018/219/) 를 보았고, 여기서 소개된 DownSampling 코드를 아래와 같이 이해해보았습니다.

`CGImageSource를 Thumbnail 객체로 만드는 과정에서 사이즈를 줄이고, 이때 이미지를 디코딩하면 메모리 사용량이 줄어들 수 있다.`

이 외에도 `jpegData(compressionQuality:)` 메서드 등 여러 방법이 있는 것 같은데, 현업에서 사용되는 방법은 어떤 것이 있을지 궁금합니다!

- 디스플레이에 따라서 포인트 당 가지는 픽셀이 다르다는 HIG 내용이 있던데, 그렇다면 원하는 용량까지 줄이기 위해서 `jpegData(compressionQuality:)` 를 사용하는 것이 이번 프로젝트의 요구사항과 어울릴까요?

> 3-3.
> 

viewController가 너무 많은 책임을 가지고 있다는 생각이 들었는데, 어떤 방향으로 수정이 가능한 지에 대해서 고민하다가 시간이 가버렸네요....🥲 실제 적용에 참고하기 좋은 자료나 문서가 있을까요?

> 3-4.
> 

키보드가 나타날 때 화면 전체가 150 위로 올라갈 수 있도록 지정해주었는데, 환경에 따라 문제가 될 수 있는 매직넘버일까요? 만약 그렇다면, 기기 개별로 지정해주어야 하는 건지 궁금합니다.

2022-01-28 12:41 UTC, corykim0829 requested changes
2주간 수고 많으셨습니다! 고사리 :)
이슈사항들을 고민해나가며 모두 해결해 나가는 모습이 보기 좋았습니다 👍 
정말 고생하셨어요!

한번 제가 프로젝트를 실행해보니 상품 추가 버튼을 누르면 딜레이가 생기고 상품 추가 환영에서 cancel 버튼을 누르면 앱이 크래시가 나네요! 확인해보고 수정하면 좋을 것 같습니다!

또한 전반적으로 매직넘버(숫자들 문자열값들 포함)가 많아서 정리가 필요해보입니다!

### 3. 조언을 얻고 싶은 부분

> 3-1

하나의 collectionView로도 구현이 가능해서 굳이 collectionView, tableView 두개를 사용해서 구현하지 않아도 된다는 의도로 말씀 드렸었어요!

> 3-2
이번 요구사항에서는 크게 상관이 없을 것 같습니다! 이미지 처리에 따라서 메모리 사용량을 확인해보면 좋을 것 같아요. WWDC에 소개된 방법을 사용하는게 더 최적화된 방법이기는 합니다!
https://nsios.tistory.com/154 여기를 참고해보세요!

> 3-3
음 일단은 MVC 패턴으로 구현한거기 때문에 컨트롤러가 커지는 것은 어쩔 수 없고 iOS 특성상 뷰컨트롤러가 커지는 것은 어쩔 수 없습니다. 그래서 디자인 패턴을 사용해서 다른 객체한테 책임을 전가해서 뷰컨트롤러를 줄이는 방법이 있습니다. 이 부분은 MVVM 패턴과 같은 다른 패턴을 공부해보면 좋을 것 같아요!

> 3-4
키보드의 높이를 가져올 수 있는 코드가 있어요. NotificationCenter를 통해서 키보드 프레임 값을 가져올 수 있습니다.

2022-01-28 12:41 UTC, corykim0829 commented on OpenMarket/OpenMarket/Extension/Double+Extension.swift
> +    func addDemical() -> String {
addDecimal이라는 함수명을 보면 리턴값이 Void일 것 같은 느낌이 들어요. 명사형으로 네이밍하면 더 좋을 것 같아요!

2022-01-28 12:41 UTC, corykim0829 commented on OpenMarket/OpenMarket/Extension/UIImage+Extension.swift
> +    func compressedImage(targetSize: CGSize) -> UIImage {
extension 함수를 네이밍할 때에는 사용할 때 한번 더 확인해보면 좋습니다. UIImage의 extension인데 Image라는 단어가 들어가면 만약 `let productImage = UIImage()`에서 `productImage.compressedImage()`로 사용되게 되어서 Image라는 단어가 중복됩니다!
`productImage.compressed()` 처럼 깔끔하게 써도 좋을 것 같아요 ㅎ

2022-01-28 12:41 UTC, corykim0829 commented on OpenMarket/OpenMarket/Extension/UIViewController+Extension.swift
> +        }
이쪽 코드를 더 깔끔하게 정리할 수 있을 것 같아요!

2022-01-28 12:41 UTC, corykim0829 commented on OpenMarket/OpenMarket/View Controller/Main/ViewController+TableView.swift
> +        let cell = productTableView.dequeueReusableCell(withIdentifier: "TableViewCell")
identifier를 String값으로 쓰지 않고, 상수로 관리하면 좋을 것 같습니다.

2022-01-28 12:41 UTC, corykim0829 commented on OpenMarket/OpenMarket/View/CollectionViewCell.swift
> +    func setUpCell() {
이 함수에서 너무 많은 일을 하고 있는 것 같아요 분리하면 좋을 것 같습니다!

2022-01-28 12:41 UTC, corykim0829 commented on OpenMarket/OpenMarket/View/CollectionViewCell.swift
> +    func setUpCell() {
또한 접근제어자도 다시 고민해보면 좋을 것 같아요!

2022-01-30 08:09 UTC, FIIIIN commented on OpenMarket/OpenMarket/Extension/UIImage+Extension.swift
> +    func compressedImage(targetSize: CGSize) -> UIImage {
말씀해주신 것처럼 불필요한 단어 중복이라고 생각하여 image를 빼는 방향으로 리네이밍 진행했습니다! 다만 이렇게 뺐을 때, 파라미터와의 연결이 자연스럽지 않다고 생각하여 `compressed(to targetSize:)` 로 매개변수 레이블을 더해보았습니다😄

2022-01-30 08:13 UTC, FIIIIN commented on OpenMarket/OpenMarket/Extension/UIViewController+Extension.swift
> +        }
불필요한 클로저가 덧붙었네요..! `handler:  nil`로 리팩토링 진행했습니다

2022-03-24 13:50 UTC, closed without merging