Step2 innie 태태
yagom-academy/ios-open-market pull request #13
Opened 2021-02-05 03:51 UTC by innieminnie

안녕하세요~ @AppleCEO 도미닉~!~!
리뷰부탁드립니다 ㅎㅎ 

[주요구현사항]
- 오토레이아웃을 전부 코드로 구현했습니다.
- POST method를 Content-type: multipart/form-data 방식으로 변경하여서 구현했습니다. (httpbody 생성과정 구현)
- ProductRegistration 구조체를 따로 만들어서 POST request시 필요한 데이터 형식을 모았습니다.
- 기존의 네트워크 연결부인 dataTask메소드가 각 기능별로 따로 있었는데, 하나의 메소드로 합쳤습니다.
- Step1의 'GET'하여 상품목록 보여주는 내용을 ListViewController와 GridViewController로 나누어서 각각의 뷰컨트롤러에서 동작하도록 한 후, ViewController의 ChildViewController로 두 컨트롤러를 등록해주었습니다.

[개선할점]
- GET호출을 한 번만 하는 것이 아니라 ListViewController와 GridViewController 각각에서 호출하고 있습니다. 이 과정에서 각각의 뷰가 보여주는 내용이 달라질 수 있는 문제가 발생할 수 있어 다른 방식으로 고민중입니다.

2021-02-05 04:49 UTC, AppleCEO requested changes
고생하셨습니다.
뷰컨트롤러들이 모여있는 폴더명을 컨트롤러로 지은 이유가 있나요?
고민할 점들 남겨놨습니다.
화이팅입니다!

2021-02-05 04:49 UTC, AppleCEO commented on OpenMarket/OpenMarket/Cell/ProductGridViewCell.swift
> +        productNameLabel.setContentCompressionResistancePriority(.defaultHigh, for: .horizontal)
이 부분을 label을 생성할 때 적용시킬 수 있을까요?

2021-02-05 04:49 UTC, AppleCEO commented on OpenMarket/OpenMarket/Cell/ProductListTableViewCell.swift
> +}
이 extension 은 ProductListTableViewCell 과 직접적인 연관은 없는 것 같습니다.
어디로 옮길 수 있을까요?

2021-02-05 04:49 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controller/GridViewController.swift
> +        return productList.count
리턴을 생략할 수도 있지만 더 익숙해질 때까지 리턴을 써주는 것이 좋습니다.
써주는 것 좋았습니다! 👍

2021-02-05 04:49 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controller/GridViewController.swift
> +        cell.productPriceLabel.text = "\(product.currency) \(price.addComma())"
숫자에 콤마를 찍어주는 애플에서 제공하는 기능이 있습니다.
그 방식을 사용해보면 어떨까요?

2021-02-05 04:49 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controller/GridViewController.swift
> +
이 부분 공백 두 줄은 어떤 의미인가요?

2021-02-05 04:49 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controller/GridViewController.swift
> +}
이 부분은 왜 남겨두셨나요?

2021-02-05 04:49 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controller/ListViewController.swift
> +}
delegate를 사용하지 않는다면 delegate를 self로 할당하지 않고 이 부분을 지우는 것이 더 좋습니다.

2021-02-05 04:49 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +    let gridView = GridViewController()
listView 보다는 listViewController라는 이름이 더 좋을 것 같습니다.
어떻게 생각하시나요?

2021-02-05 04:49 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +    @objc private func didTapSegment(segment: UISegmentedControl) {
segment를 사용해보셨군요 💯

2021-02-05 04:49 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +        else {
} else { 라고 하는 것이 스위프트스러운 문법입니다.

2021-02-05 04:49 UTC, AppleCEO commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +            gridView.view.isHidden = true
이 if문의 조건인 bool 값을 isHidden에 바로 넣어볼 수 있을까요?

2021-02-05 04:49 UTC, AppleCEO commented on OpenMarket/OpenMarket/ProductInformationGridCell.swift
> +        stockLabel.textAlignment = .center
이 부분도 위에 선언하는 부분에 추가하면 어떨까요?

2021-02-05 04:49 UTC, AppleCEO commented on OpenMarket/OpenMarket/ProductInformationGridCell.swift
> +            stockLabel.trailingAnchor.constraint(equalTo: thumbnailImageView.trailingAnchor),
아이폰SE 에서는 글자가 튀어나오네요.
어떻게 개선해볼 수 있을까요?
![image](https://user-images.githubusercontent.com/47517256/106990725-2c4fc200-67b8-11eb-8062-a80d57b7ae14.png)

2021-02-05 04:49 UTC, AppleCEO commented on OpenMarket/OpenMarketTests/MockModel/MockAPI.swift
> +    }
이렇게 줄바꿈을 하는 것은 아주 좋은 습관입니다 🥇

2021-02-05 04:49 UTC, AppleCEO commented on OpenMarket/OpenMarketTests/MockOpenMarketTests.swift
> +//                XCTAssertEqual(productList.items[3].registrationDate, response?.items[3].registrationDate)
사용하지 않는 코드면 지우는 것이 좋습니다.
깃에 남아있기 때문에 원할 때 언제든 다시 가져올 수 있으니까요.

2021-02-06 02:24 UTC, innieminnie commented
코멘트 남겨주신 부분 위주로 수정해보았습니다! @AppleCEO

2021-02-06 03:16 UTC, merged

2021-02-06 03:16 UTC, AppleCEO commented
고생하셨습니다~