오픈마켓 [STEP 1] Red, 마이노
yagom-academy/ios-open-market pull request #137
Opened 2022-05-11 06:01 UTC by Mino777

안녕하세요  엘림!! @lina0322 
STEP1 PR 보내드립니다!!
잘부탁드립니다!! 🙇‍♂️🙇‍

---
## UML

![](https://i.imgur.com/K1idRzo.jpg)

---

## 고민했던 것들
1. 실제 네트워크 통신과 무관한 테스트
- URLSessionProtocol을 활용해 APIProvider의 urlSession에 StubURLSession의 주입이 가능하도록 구현하였습니다.
- 기존의 네트워킹 Flow에서 중간에 Session을 StubURLSession으로 바꾸어 주면서 sampleData, response, error를 반환해주는 dataTask 메서드의 completion에 가짜 데이터를 넣어주었습니다.
- Response 데이터를 조작할 수 있게 되면서 네트워크 통신을 하지 않고도 예상되는 값을 테스트해줄 수 있었습니다.

2. Request(dataTask 과정) 메서드의 재사용
- 서버에 요청하는 메서드를 Generic하게 구현 하여 Endpoint를 주입받아 하나의 메서드로 다른 각각의 API들의 요청에서 재사용될 수 있도록 구현해보았습니다.

3. Endpoint 구현
- 요청에 필요한 모든 정보들을 하나의 객체로 구현하여 관리하기 쉽도록 구현해보았습니다.
- EndpointStorage에서 해당 객체를 가지고 각각의 API에 맞게 생성하여 사용할 때 해당되는 Endpoint를 EndpointStorage에서 가져와 APIProvider에 주입하여 사용할 수 있도록 구현해보았습니다.

---

## 조언을 얻고 싶은 내용
* Query, Path 등을 String 으로 넣는 것이 아니라 Date 형태로 바꾸는 과정이 유의미한가?
* DTO 가 존재하는 이유
* Result 타입 사용으로 인한 switch 중첩
* sessionDataTask 의 init 이 deprecated 된 이유

### Query, Path 등을 String 으로 넣는 것이 아니라 Date 형태로 바꾸는 과정이 유의미한가?
Query 의 경우 String 타입을 직접적으로 넣어 주지 않기 위해 Encodable 타입으로 받고 Encodable 의 extension 으로 딕셔너리에 넣어 값을 반환해주는 로직을 구현했습니다. 

```swift
final class EndPoint: Requestable {
    ...
    var path: String
    var queryParameters: Encodable?
    ...
}
```

```swift
func generateURL() -> Result<URL, NetworkError> {
        let fullPath = "\(baseURL)\(path)"
        guard var urlComponents = URLComponents(string: fullPath) else {
            return .failure(.urlComponet)
        }

        var urlQueryItems = [URLQueryItem]()
        if let queryParameters = queryParameters?.toDictionary() {
            switch queryParameters {
            case.success(let data):
                data.forEach {
                    urlQueryItems.append(URLQueryItem(name: $0.key, value: "\($0.value)"))
                }
            case.failure(let error):
                return .failure(error)
            }
        }
          
        urlComponents.queryItems = urlQueryItems.isEmpty == false ? urlQueryItems : nil

        guard let url = urlComponents.url else {
            return .failure(.urlComponet)
        }
        return .success(url)
    }
```

```swift
extension Encodable {
    func toDictionary() -> Result<[String: Any], NetworkError> {
        do {
            let data = try JSONEncoder().encode(self)
            guard let jsonData = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
                return .failure(.decodeError)
            }
            return .success(jsonData)
        } catch {
            return .failure(.decodeError)
        }
    }
}
```
그런데 Path 의 경우 파라미터를 받을 이유가 없어 그냥 String 으로 넣어주었습니다.

Path 도 Data 타입으로 변환 후 들어가는 것이 맞을까요?
(코드의 통일성과 String 사용 지양을 위해)
아니면 String 을 직접적으로 넣어도 문제가 없을까요?
아니면 Data 로 바꾸는 과정 자체가 조금은 과한 구현 이었을까요?

### DTO 가 존재하는 이유
라이브러리 등에서 DTO 라는 객체를 사용 한다는 예시를 보아서 DTO 라는 객체를 따로 생성해 주었습니다. 
현재 `EndPointStorage` 에서 객체를 생성해서 사용하고 있습니다. 
그런데 이 객체를 제거하고 내부 로직을 조금 수정하면 객체가 필요하지 않습니다. 
DTO 를 사용하는 이유가 무엇일까요?
DTO 로직 자체를 잘 못 짠 것인지 아니면 지금 상황에서는 DTO 를 생성하지 않는게 맞는 것인지 궁금합니다. 

### Result 타입 사용으로 인한 중첩
오류 처리를 유용하게 하기 위해서 throw 메서드가 너무 많이 생기지 않도록 Result 타입을 활용했습니다. 하지만 JSON -> Dictionary를 위한 `JSONSerialization.data(withJSONObject:)`메서드에 내부적으로 throw가 구현이 되어있어 불가피하게 do - catch문도 사용할 수 밖에 없었습니다.
그러다보니 
Requstable 프로토콜 extension 의 generateUrlRequest 메서드 내부 구현의

```swift 
if let bodyParameters = bodyParameters?.toDictionary() {
    switch bodyParameters {
    case.success(let body):
        if body.isEmpty == false {
            do {
                urlRequest.httpBody = try JSONSerialization.data(withJSONObject: bodyParameters)
            } catch {
                return .failure(.decodeError)
            }
        }
    case.failure(let error):
        return .failure(error)
    }
}
```
if, switch, do catch 등의 중첩이 생겼습니다. 
이 중첩을 해결하려고 메서드를 분리 하려고 하면 bodyParameters 를 전역으로 빼주어야 하더라구요.
이 중첩을 어떻게 해결하는 것이 좋을까요?

### sessionDataTask 의 init 이 deprecated 된 이유
![](https://i.imgur.com/4DzUmiV.png)
sessionDataTask init 이 deprecated 되었다고 뜨는데, deprecated 된 이유가 있을까요? 
init 이 deprecated 되었다면, 초기화를 어떤 방식으로 해주어야 하는 것일지 궁금합니다!

2022-05-12 13:38 UTC, lina0322 requested changes
안녕하세요, 두 분! 반갑습니다~~

이번 프로젝트 잘 부탁드려요🙇🏻‍♀️
많은 고민과 시도가 담겨있는 코드였네요!
처음으로 네트워크 테스트하시는 것 같은데도 상당히 깔끔한 코드였습니다.👍

---
### 1. Query, Path 등을 String 으로 넣는 것이 아니라 Date 형태로 바꾸는 과정이 유의미한가?

Data 말씀하시는거겠죠??
우선, Query에 왜 String을 직접적으로 넣지 말아야한다는 생각을 하셨나요?
String을 입력할때 휴먼 에러때문에 걱정하시는건지..??👀
여러분들은 어땠나요? 이 부분이 과다하고 여겨지셨나요?ㅎㅎㅎ

### 2. DTO가 존재하는 이유

DTO가 필요한 경우도 있죠! 
여러분이 이렇게 느낀 이유는, 사실 지금 그닥 데이터가 복잡하지 않고
사실상 내려오는 정보들을 모두 사용하는데, 굳이 DTO라는 틀을 만들어서가 아닐까요?
제 의견을 물어보신다면, 저는 생성하지 않았을 것 같아요😅
하지만, 이번에는 공부하는 거니까 이렇게 가지고 다음 스텝도 시도해보면서 몸소 장단점을 느끼는 것도 좋겠네요.

### 3. Result 타입 사용으로 인한 중첩

내부에서 JSONSerialization 사용하시는 이유는 어떤걸까요?
```swift
if body.isEmpty == false {
            do {
                urlRequest.httpBody = try JSONSerialization.data(withJSONObject: bodyParameters)
            } catch {
                return .failure(.decodeError)
            }
        }
```
를 통째로 하나의 함수를 만들어 분리시킬 수는 있겠네요.

### 4. sessionDataTask 의 init 이 deprecated 된 이유

제가 애플ㅇ ㅣ아니라 이유까지는 정확히 모르겠지만😭
관련해서는 [URLProtocol](https://developer.apple.com/documentation/foundation/urlprotocol)을 사용하시라는 힌트를 드릴 수 있을 것 같아요!

--- 

코멘트는 아래에 남겨 두었어요!
여러분들이 시도하려고 하셨던 구조나 로직은 되도록 가져가면서, 기본적으로 수정해야하는 것들 공부해야하는 것들 위주로 코멘트 남겨드렸고(스텝을 하나하나 진행해 나가다보면 여러분들 스스로 아 이건 잘짰었네, 아 이건 고쳐야겠네 하는 것들이 보일거에요!ㅎㅎ)
이해 안 가시는거나 더 궁금한거 있으면 메세지 주세요~😀

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Common/Constants.swift
> +enum Constansts { }
무엇을 위한 enum인가요?👀

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        view = mainView
view로드가 완료된 다음에 view를 변경했네요?🤔

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Extension/Data+Extension.swift
> +extension Data {
모든 Data가 decode라는 함수를 꼭 들고있어야할 필요가 있는가에 대한 의문이 들긴하네요!🧐

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Extension/Encodable+Extension.swift
> +extension Encodable {
encode 관련 함수는 여기에 Encodable에 extension하셨네요👀

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/Products.swift
> +    let pageNo, itemsPerPage, totalCount, offset: Int
보통 한줄에 하나씩 선언하는 컨벤션이 더 흔한 것 같습니다.🫡

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/Products.swift
> +        case pageNo = "page_no"
축악어가 있는 것으로 보이네요?😳

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/Products.swift
> +struct Item: Codable {
`Encodable`, `Decodable`, `Codable`에 대해서 간단히 설명해주실 수 있을까요~
또 모든 struct에 Codable을 가지고 있는 것 같은데요. 모두 필요한 상태인가요??👀

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/Products.swift
> +        case issuedAt = "issued_at"
단순히 스네이크 케이스에서 카멜케이스로 변경하는 거라면 디코더에 설정이 가능한것으로 알고있는데, decoder를 좀 더 공부해볼까요?🙂

물론 지금처럼 CodingKeys를 사용하는 것이 좀 더 유연해서, 저는 더 선호하는 편이긴 합니다🙏

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
> +struct ProductsImage: Codable {
파일마다 하나씩 선언해주시는게, 생각보다 나중에 유지보수하기 편하실거에요🙏

그리고 이거 ProductsImage인데, 제품`들`의 이미지인가요?

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
> +    let url, thumbnailURL: String
URL은 URL이라는 타입이 있는데 String이네요🤔

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket.xcodeproj/project.pbxproj
> -				C70FB10325BEF61D00C9924E /* Assets.xcassets */,
MainStroyboard를 없애고 코드로 진행하시나 보네용! 이유가 궁금합니다👀

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
> +    let succeed: Bool
`isSuccess`라는 이름은ㅇ ㅓ떨까요?🧐

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
> +struct Vendor: Codable {
Vendor는 혹시 어떤 의미로 사용하셨나요? 제가 궁금해서ㅎㅎ..

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +extension URLSession: URLSessionProtocol {}
파일 분리 추천드립니다!🙏

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +    init(urlSession: URLSessionProtocol = URLSession.shared) {
LGTM👍

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +            }.resume()
이 요청 만약에 취소하고 싶으면 어떡하죠?👀
(너무 어려우면 이번에 패스해도 좋아요~)

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +extension APIProvider {
extension은 어떤 기준으로 하고계신가용??😀

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +            completion(.failure(NetworkError.unknownError))
unknownError가 맞나요??🤔

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +        guard (200...299).contains(response.statusCode) else {
`200..<300`은 어때요?? 그냥 두 분의 의견이 궁금합니답ㅎㅎ

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +            completion(.failure(NetworkError.invalidHttpStatusCode(statusCode: response.statusCode)))
statusCode를 같이 보내준 것 GREAT👍

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +        }
`emptyData`처리도 좋아요!!

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/EndPoint/EndPoint.swift
> +}
Constants를 하나로 만들어서 fileprivate extension로 활용하시는 것도 좋은 것 같아요!
근데 혹시 EndPoint 내부에서만 사용할거라면 EndPoint가 들고있어도 되는건 아닐까~? 하는 생각이 드네요?🧐

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/EndPoint/EndPointStorage.swift
> +    static func getProductsDetail(id: String) -> EndPoint {
줄 바꿈 있는것도 좋을거같ㅇㅏ요~
또, swift에서 메서드 명 get으로 시작하는걸 비추천하고있어요. 이유를 찾아보면 좋겠네요💪

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/Error/NetworkError.swift
> +}
어떤건 error로 끝나고 어떤건 안끝나고 하네용ㅎ_ㅎ

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
좋은 시도에요! 
window, scene은 각각 어떤 개념인가요?
또 makeKeyAndVisible은 어떤 역할을하는 메서드인가용?👊

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarket/View/MainView.swift
> +        fatalError("init(coder:) has not been implemented")
논리적으로 생각했을땐 여기에 들어올 일이 없을 것 같지만...
그렇다해서 꼭 fatalError로 앱을 터트릴 위험을 만들 필요가 있나요?😀

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarketModelTests/NetworkProductListTest.swift
> +    var sut: APIProvider<Products>!
test가 3개로 나누어져있는데, 전부 APIProvider를 테스트하는 것이네용ㅎㅎ 
동일한 기능을 테스트하는 것 같아요??👀

2022-05-12 13:38 UTC, lina0322 commented on OpenMarket/OpenMarketModelTests/TestDouble/StubURLSession.swift
> +final class StubURLSession: URLSessionProtocol {
stub와 mock, testDouble은 각각 어떤 개념일까요?👀

2022-05-12 13:53 UTC, cherrishRed commented on OpenMarket/OpenMarket/Network/Error/NetworkError.swift
> +}
Error 로 끝나는 네이밍으로 통일해 주었습니다!

2022-05-12 13:55 UTC, Mino777 commented on OpenMarket/OpenMarket/Common/Constants.swift
> +enum Constansts { }
상수들을 관리하기위한 NameSpace 입니다!
전역으로 사용하는 상수의 경우 이 곳에 넣어주고,
한 곳에서만 사용하는 상수의 경우 Extension으로 넣어주었습니다!
감사합니다!

2022-05-12 14:03 UTC, cherrishRed commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        view = mainView
`loadView` 메서드 안에서 하는 것으로 변경해주었습니다.
그런데 검색해보니 `loadView` 는 일반적인 경우 많이 사용하지 않는다고 들었습니다. 
(스토리보드나 인터페이스 빌더에서 사용할 경우 오류가 난다고 들었는데...맞나요?)

`viewDidLoad` 안에서 뷰를 변경하면 생기는 불이익이 무엇인지 궁금합니다.

2022-05-12 14:06 UTC, Mino777 commented on OpenMarket/OpenMarket/Extension/Data+Extension.swift
> +extension Data {
저희도 원래는 APIProvider가 decode 메서드를 가지고 있는 형태였는데, 뭔가 APIProvider의 역할과 안맞는 느낌이 들어서 빼주었습니다!
그런데 엘림 말대로 모든 Data 타입이 들고있는건 좋지 않다고 생각해서 APIProvider 파일안에 fileprivate으로 정의해주었습니다!
감사합니다!

2022-05-12 14:08 UTC, cherrishRed commented on OpenMarket/OpenMarket/Extension/Encodable+Extension.swift
> +extension Encodable {
`Requestable` 로 해당 extension 을 이동하고 `fileprivate` 으로 처리 해 주었습니다.

2022-05-12 14:16 UTC, Mino777 commented on OpenMarket/OpenMarket/Model/Products.swift
> +    let pageNo, itemsPerPage, totalCount, offset: Int
엘림 말씀대로 하나씩 선언하는 컨벤션으로 수정하였습니다!
감사합니다!

2022-05-12 14:17 UTC, Mino777 commented on OpenMarket/OpenMarket/Model/Products.swift
> +        case pageNo = "page_no"
앗..! API에 있는대로 작성하다보니 축약어들이 생겼네요..!
다음부터는 해당 부분들 놓치지 않도록 하겠습니다!
감사합니다!

2022-05-12 14:17 UTC, Mino777 commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
> +struct ProductsImage: Codable {
ProductImage로 수정하였습니다!
감사합니다!

2022-05-12 14:18 UTC, Mino777 commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
> +    let url, thumbnailURL: String
URL 타입들로 변경하였습니다!
감사합니다!

2022-05-12 14:19 UTC, Mino777 commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
> +    let succeed: Bool
isSuccess 로 변경하였습니다!
감사합니다!

2022-05-12 14:24 UTC, Mino777 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +extension URLSession: URLSessionProtocol {}
각각 URLSessionProtocol, URLSession+Extension으로 파일 분리하였씁니다!
감사합니다!

2022-05-12 14:25 UTC, cherrishRed commented on OpenMarket/OpenMarket/Model/Products.swift
> +        case issuedAt = "issued_at"
```swift 
  let jsonDecoder = JSONDecoder().keyDecodingStrategy = .convertFromSnakeCase
```
이런식으로 설정하면 JSONDecoder 로도 SnakeCase 를 CamelCase 로 바꿔줄 수 있다는 사실을 알았습니다!
감사합니다 엘림!

2022-05-12 14:25 UTC, cherrishRed commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +extension URLSession: URLSessionProtocol {}
넵 파일 분리해 주었습니다!

2022-05-12 14:35 UTC, cherrishRed commented on OpenMarket/OpenMarket.xcodeproj/project.pbxproj
> -				C70FB10325BEF61D00C9924E /* Assets.xcassets */,
storyBoard 가 무겁기도 하고, storyBoard를 열 때 마다 변경사항이 생겨서 커밋을 칠 때 불편함을 느꼈습니다!
또 스스로 스토리보드에서 무엇을 변경해 주었는지 알기가 어려워 오히려 코드보다 더 헷갈린다는 의견을 서로 나누고 스토리 보드를 없애고 진행하기로 했습니다!

2022-05-12 14:36 UTC, cherrishRed commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
> +struct Vendor: Codable {
Vendor 이라는 객체가 서버에서 받아올때 부터 존재해서 만들어 주었습니다!
혹시 네이밍을 여쭤보신 것이라면, 저희가 추측하기로는 판매자의 정보 인것 같은데 정확하지 않아 
서버에 존재했던 이름은 Vendor 로 만들어 주게 되었습니다.

2022-05-12 14:37 UTC, Mino777 commented on OpenMarket/OpenMarket/View/MainView.swift
> +        fatalError("init(coder:) has not been implemented")
```swift
required init?(coder: NSCoder) {
        super.init(coder: coder)
    }
```
으로 변경해보았습니다!
감사합니다!!

2022-05-12 14:37 UTC, cherrishRed commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +            completion(.failure(NetworkError.unknownError))
unknownError 가 아닌데 저희가 잘못 사용한 것 같네요ㅠㅠ
`responseError` 라는 케이스를 추가하고 `responseError` 로 설정해 주었습니다.

2022-05-12 14:42 UTC, Mino777 commented on OpenMarket/OpenMarketModelTests/NetworkProductListTest.swift
> +    var sut: APIProvider<Products>!
다시 생각해보니 더미로만 APIProvider를 테스트하는 것이 맞는 것 같습니다.
결국엔 서버에서 내려주는 값이 달라지면 실제 네트워킹을 하는 테스트는 실패할 것이기에 실제 네트워킹을 하는 테스트는 삭제하였씁니다!
감사합니다!

2022-05-12 14:45 UTC, cherrishRed commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +        guard (200...299).contains(response.statusCode) else {
`200..<300`쪽이 읽기 더 편할 것 같습니다! 변경해 주었습니다!

2022-05-13 01:08 UTC, cherrishRed commented on OpenMarket/OpenMarket/Network/EndPoint/EndPoint.swift
> +}
EndPoint 에서만 사용되기 때문에 EndPoint 안으로 넣어주어도 될 것 같습니다!
그런데 enum 자체를 내부에 넣으라는 것인지 정확히 이해가 되지않았습니다. 
extension 인 상태로 내부로 넣을 수가 없어서 
타입 프로퍼티로 빼주었는데요, 이런 방식을 이야기 하신게 맞을까요?

2022-05-13 01:16 UTC, Mino777 commented on OpenMarket/OpenMarket/Model/Products.swift
> +struct Item: Codable {
#### Encodable
- Data를 Encoder에서 변환 해주려는 타입으로 바꿔주는 인코드 메서드를 가지고있는 프로토콜입니다.
- Ex) Swift -> JSON

#### Decodable
- Data를 원하는 Model 형식으로 Decode해주기 위한 프로토콜입니다.
- Ex) JSON -> Swift

#### Codable
- Encodable과 Decodable 타입을 묶어놓은 Typealias입니다.

현재로서는 Decoding만 진행하면 되기 때문에 Decodable로 변경하도록 하겠습니다!
- `모든 struct에 Codable을 가지고 있는 것 같은데요. 모두 필요한 상태인가요??`

현재 모델들은 모두 Decodable이 필요하다고 생각하는데 혹시 필요하지 않은 모델이 있는걸까요?
감사합니다!

2022-05-13 01:24 UTC, Mino777 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +extension APIProvider {
저희는 기능의 성격이나 Flow를 기준으로 진행을 했었습니다.
기존에는 해당 Extension에 Decode 메서드까지 있어서 요청 메서드를 제외한 에러를 체크해주고 디코드 해주는 private한 메서드들을 Extension으로 뺐었습니다!
혹시 엘림은 어떤 기준으로 extension 해주시나요?!
감사합니다!

2022-05-13 01:48 UTC, cherrishRed commented on OpenMarket/OpenMarket/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
#### window 
View 의 상위 객체입니다. 
View 들을 묶고 UI 배경을 제공하는 역할을 합니다. 
기본적으로 하나의 뷰가 필요하기 때문에 SceneDelegate 에 window 가 선언되어 있습니다. 

#### scene
multifle window 를 지원하기 위해서 생긴 기능으로 사용자가 1개의 앱의 2개의 화면을 multifle window로 띄우고 있다면 scene이 2개라고 말할 수 있습니다.

#### makeKeyAndVisible
현재의 뷰를 보여주고 이 뷰를 가장 앞에 있도록 만들어 주는 메서드 입니다.

2022-05-13 01:48 UTC, cherrishRed commented on OpenMarket/OpenMarketModelTests/TestDouble/StubURLSession.swift
> +final class StubURLSession: URLSessionProtocol {
#### test Double 
실제 객체와 비슷하지만 테스트를 위해서 만들어진 객체를 의미합니다. 
test Double 을 사용하면,
* 테스트 속도 개션 
* 다른 객체에 의존하지 않고 테스트 대상 객체만 테스트 가능 
등의 장점이 있습니다.

테스트 객체의 붙이는 네이밍에 어느정도 규칙이 있습니다.

#### Dummy
가장 많이 사용하는 객체 입니다. 
내부에 기능이 정상적으로 작동하지 않습니다.

#### Stub
실제 동작하는 것처럼 만들어 주는 객체입니다.
원래 객체에서 테스트를 해야할 기능만 최소한으로 구현해 줍니다. 

#### Mock
실제 동작하는 것처럼 만들어 주는 객체입니다.
실제 객체와 아주 유사하게 거의 모든 기능이 동작하도록 구현해 줍니다. 
Stub 을 상태 기반 테스트 
Mock은 을 행위 기반 테스트 라고 말하기도 합니다.

2022-05-13 01:49 UTC, Mino777 commented on OpenMarket/OpenMarket/Network/EndPoint/EndPointStorage.swift
> +    static func getProductsDetail(id: String) -> EndPoint {
정확하진 않지만, API Design Guidelines의 `불필요한 단어를 생략하라`라는 규칙을 어기는 것 같다고 추측해보았습니다! 맞을까요?! 가이드라인에서 get에 관한 레퍼런스를 찾지 못했습니다😭
https://soojin.ro/blog/english-for-developers-swift
해당 블로그에서 getter 메서드의 경우 명사형으로 진행한다는 글을 보고 productsList, productsDetail 이런식으로 명사형으로 수정해보았습니다!
DTO, Endpoint 부분 줄 바꿈 하였습니다!
감사합니다!

2022-05-13 03:20 UTC, cherrishRed commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +            }.resume()
저희가 이부분에 대해서 공부를 해보고 있는데, 시간이 조금 걸릴 것 같습니다!
공부를 조금 더 확실히 하고 나서 다음 스텝에서 구현해 보도록 하겠습니다😁

2022-05-13 03:21 UTC, Mino777 commented
@lina0322 
피드백 모두 반영해보았습니다!!
정말정말 좋은 리뷰들 너무 감사드립니다😆🙇‍♂️
피드백 중 URLSession 취소 관련한 피드백의 경우 저희가 좀 더 학습해보고 챌린지 하는게 좋을 것 같아서 해당 피드백만 다음 스텝에서 도전해보도록 하겠습니다!!
감사합니다🥰

---

1. Query, Path 등을 String 으로 넣는 것이 아니라 Date 형태로 바꾸는 과정이 유의미한가?

확장성 부분에서 파라미터들을 받아서 바로 String 으로 바꾸게 되면 받는 파라미터의 개수가 달라질 때마다 구현부를 바꿔야 해서 확장성이 떨어진다고 느꼈습니다. 그래서 딕셔너리로 바꿔주는 방식을 우선을 가져가는 방향으로 이야기 했습니다 😄


2. DTO가 존재하는 이유

다시 생각해보니, DTO를 활용하는 경우 쿼리 파라미터를 받을 때 확실히 코드의 양과 편의성이 증가하는 시너지가 있다고 생각이 들어서 DTO의 경우 한번 가져가보면서 엘림 말씀대로 몸소 장단점을 느껴보는 것으로 하였습니다🙇‍♂️

3. Result 타입 사용으로 인한 중첩

내부에서 JSONSerialization을 사용하는 이유로는 Dictionary -> Data로 변환 해주기 위해 사용하였습니다.
해당 부분은 해결하지 못하였습니다😭
메서드에 메서드로도 넣어보고, 인아웃 파라미터를 사용도 해보았는데 최종적인 문제로
```swift
if body.isEmpty == false {
            do {
                urlRequest.httpBody = try JSONSerialization.data(withJSONObject: bodyParameters)
            } catch {
                // 해당 부분을 리턴해줘야하는 부분
                return .failure(.decodeError)
            }
        }
```
do - catch 문에서 failure를 리턴해줘야 하는 문제 때문에 Switch 문에서 리턴을 강제하다보니 아래 코드블럭들이 never execute 되는 문제때문에 해결해주지 못했습니다😭

4. sessionDataTask 의 init 이 deprecated 된 이유'
앨림이 주신 힌트로  `URLSessionDataTaskProtocol` 이라는 것을 생성해서 `StubURLSession` 이 URLSession 의 상속을 받는 것이라 아니라
`URLSessionDataTaskProtocol` 를 채택하도록 만들어 주었습니다. 

이렇게 되면 init 도 상속을 받지 않기 때문에 init 이 deprecarted 된 문제가 해결 되었습니다.

2022-05-14 08:01 UTC, lina0322 commented on OpenMarket/OpenMarket/Common/Constants.swift
> +enum Constansts { }
상수를 한곳에서 관리한다는 것은 좋은 아이디어 같아요!
다만 오히려 큰 프로젝트라면 각각의 클래스가 내부에 들고있는게 더 관리하기 편할 수 있다는 생각이 들어서 말씀드렸습니다👀

2022-05-14 08:03 UTC, lina0322 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        view = mainView
1. 일단 viewController는 자체 view를 가지고 있는데, 왜 다른 view로 바꾸고 싶었나용?
2. loadView에서 뷰컨 자체 뷰를 로드하던지, 여러분이 설정한 뷰를 로드해야하는게 맞는 사이클이라고 생각되어요.
뷰컨의 자체뷰를 굳이 로드하고, 그 뷰의 로드가 완료된 다음에 바꿔줄 필요가 있나요??

2022-05-14 08:04 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/Products.swift
> +struct Item: Codable {
저는 Codable을 가지고 있는 것에 대해서 말씀드렸습니다!
인코딩이 필요한 경우에는 인코딩을, 디코딩이 필요하면 디코딩을, 둘 다 필요하면 코더블을 붙이는 것은
기능 뿐만아니라 다른 개발자들이 코드를 읽을때도 이해하기 쉽게 해주는 부분이 있습니다.
처음에는 전부 코더블이여서, 모든게 인코딩과 디코딩에 쓰이는 것 처럼 보이고 있어어요~

2022-05-14 08:05 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
> +    let url, thumbnailURL: String
URL로 바로 decode했을때 문제는 없을까요?👀

2022-05-14 08:07 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +extension APIProvider {
내부에 Private만 있는 거라면 private extension을 했을떄 어떻게 되나용?

나누는 기준은 정말 개인 취향과 회사 컨벤션에 따라 다르지만, 저는 프로토콜로만 나누는 편이긴해요ㅎㅎ

2022-05-14 08:07 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/EndPoint/EndPoint.swift
> +}
아하 제 말의 뜻은 classs 내부에 priavet enum으로 선언하는 것이었습니닷!

2022-05-14 08:10 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/EndPoint/EndPointStorage.swift
> +    static func getProductsDetail(id: String) -> EndPoint {
굳굳 좋습니다. 좋은 자료를 찾아봤네요! 

[공식 문서 링크](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html)도 첨부해드리니까 한번 읽어보세용!

2022-05-14 08:11 UTC, lina0322 commented on OpenMarket/OpenMarket/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
하나 더, appDelegate와 sceneDelegate는 무엇인가요? sceneDelegate가 없어도 앱이 동작하나요?
(요것도 지금 어렵다면 나중에 학습해도 좋아요~)

2022-05-14 08:12 UTC, lina0322 commented on OpenMarket/OpenMarket/View/MainView.swift
> +        fatalError("init(coder:) has not been implemented")
넵, 여기서도 frame init에서 하는 동작을 동일하게 해주면 좋겠어요~

2022-05-14 08:20 UTC, lina0322 approved these changes
고생하셨습니다~ 추가로 달아드린 내용은 다음 스텝에 적용 부탁드릴게요!!👍

2022-05-14 08:20 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/Products.swift
> +    let createdAt, issuedAt: String
리뷰가 일부분만 반영되고, 반영되지 않은 부분들이 보이네요!
하나를 바꿀때, 다른곳은 안바꿔도 되는지 살펴보는 것도 중요한 일 중에 하나라고 생각되어요~

2022-05-14 08:20 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +}
여기서만 사용할것인긴 하지만, 이렇게 되면 나중에 찾기가 어려울거같은데요. .흠🤔
data에 extension을 할거면 전체를 사용하게 하고, 따로 사용하는 곳이 정해져있는거라면 객체를 만드는게 낫지 않을까요..??

2022-05-14 08:20 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/EndPoint/EndPoint.swift
> +final class EndPoint: Requestable {
final은 어떤 역할을 하고있나요?

2022-05-14 08:20 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/EndPoint/EndPoint.swift
> +    private static let defaultURL = "https://market-training.yagom-academy.kr/"
static을 붙여준 이유가 궁금합니당~

2022-05-14 08:20 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/EndPoint/EndPointStorage.swift
> +    static func productsDetail(id: String) -> EndPoint {
어디는 함수끼리 줄바꿈을 해주고, 어디는 안해주고, 어디는 init과 프로퍼티가 붙어있고 떨어져있고 해요!
의도를 하고 있는건가용? 어떤 의도인지 잘 모르겠어서ㅎㅎ;

2022-05-14 08:20 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/EndPoint/Requestable.swift
> +    }
이것도 마찬가지에욥!
fileprivate의 기능에 뭔가 꽂힌 것 같은데, 무조건 좋은거나 영원한 답은 없다는 사실~

2022-05-14 08:20 UTC, merged

2022-05-16 01:31 UTC, cherrishRed commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        view = mainView
1. 자체 view 는 커스텀하기 제한적이기 때문에 미리 customView 를 만들어 대채해 주었습니다. 
2. 자체 view를 사용하지 않을 것이기 때문에 전자가 맞는 것 같습니다!
감사합니다!

2022-05-16 01:50 UTC, Mino777 commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
> +    let url, thumbnailURL: String
우선 URL로 바로 decode 했을 때 JSONDecoder가 자동으로 잘 디코딩 해주는 것 까지는 확인을 하고서 왜 자동으로 되는가에 대해서 알아보았는데 확실한 레퍼런스는 찾지 못했습니다😭
추측으로는 URL타입이 채택하고있는 프로토콜들이 (Decodable, CustomStringConvertible 등등) 내부에서 자동으로 디코딩을 해주는게 아닐까..? 라는 생각을 해보았습니다!
엘림이 질문해주신걸로 봐서는 뭔가 URL로 바로 디코드하는 경우 문제가 있을 것 같은데 어떤 문제가 있을까요?
감사합니다!

2022-05-16 01:55 UTC, Mino777 commented on OpenMarket/OpenMarket/Model/Products.swift
> +    let createdAt, issuedAt: String
해당 부분과 required init 관련 부분들이 중간에 커밋이 꼬이면서 수정이 안된 것 같습니다ㅠㅠ
앞으로는 한번 더 체크하겠습니다!
감사합니다!

2022-05-16 01:56 UTC, cherrishRed commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +extension APIProvider {
private extension 으로 선언하게 된다면 내부에 있는 모든 메서드나 프로퍼티들이 private 으로 동작하게 됩니다!

2022-05-16 02:06 UTC, cherrishRed commented on OpenMarket/OpenMarket/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
원래는 app delegate 에서 모든 것을 관리 했으나 
iOS 13에서 UI Life Cycle와 관련된 모든 작업은 UISceneDelegate로 이관되었습니다.
(아마도 multifle scene 의 개념이 나오면서 부터 인 것 같습니다.)

#### App Delegate
* 앱의 가장 중요한 데이터 구조를 초기화하는 것
* 앱의 scene을 환경설정(Configuration)하는 것
* 앱 밖에서 발생한 알림(배터리 부족, 다운로드 완료 등)에 대응하는 것
* 특정한 scenes, views, view controllers에 한정되지 않고 앱 자체를 타겟하는 이벤트에 대응하는 것.
* 출시 시 Apple Push Notification 서비스 등 필요한 서비스 등록
* AppDelegate 에서 응용프로그램의 전체 생명주기를 담당한다.

#### Scene Delegate
* UI의 상태변화를 메소드들을 통해 application에게 알리는 역할

Scene Delegate 가 없이 iOS 13 이전의 것 처럼 작업할 수도 있는 걸로 알고 있지만, 
애플 공식문서에서 이제는 Scene Delegate 를 사용하라는 권고사항이 있는 것으로 알고 있습니다.

2022-05-16 02:22 UTC, Mino777 commented on OpenMarket/OpenMarket/Network/EndPoint/EndPoint.swift
> +    private static let defaultURL = "https://market-training.yagom-academy.kr/"
해당 값을 이니셜라이즈에서 사용을 했어야해서 static을 붙여주었습니다!
해당 부분은 enum 안으로 넣어주었습니다
감사합니다!

2022-05-16 02:24 UTC, Mino777 commented on OpenMarket/OpenMarket/Network/EndPoint/EndPointStorage.swift
> +    static func productsDetail(id: String) -> EndPoint {
저희가 컨벤션을 놓친 것 같습니다ㅠㅠ
앞으로는 최대한 맞추어서 커밋 진행하겠습니다!
감사합니다!

2022-05-16 02:28 UTC, cherrishRed commented on OpenMarket/OpenMarket/Network/EndPoint/EndPoint.swift
> +final class EndPoint: Requestable {
final 키워드를 붙이게 되면 더이상 상속을 할 수 없는 클래스가 됩니다!
상속을 할 가능성이 없기 때문에,
final 로 선언된 요소들은 직접 호출하기 때문에 성능적으로 더 이점이 있습니다!