오픈마켓 [STEP 1] papri, Tiana
yagom-academy/ios-open-market pull request #138
Opened 2022-05-11 10:50 UTC by Kim-TaeHyun-A

안녕하세요 올라프⛄️
@1Consumption 
step1 PR 보냅니다. 잘 부탁드려요🙇‍♀️🙇‍♀️

---

### 구현내용

Product, OpenMarketProductList
: 서버에서 받아올 Data에 매칭하기 위한 모델, 각각 

HTTPManager.swift
: 서버와 네트워크 통신을 담당하기 위한 모델

OpenMarketTests
: Product, OpenMarkerProductList로 JSON 형태의 데이터가 디코딩 되는지 테스트
: HTTPManager의 loadData(), listenHealthChecker() 호출 시 completionHandler가 수행되는지 테스트

StubURLSessionTests
: 네트워크 통신 없이 의존성 주입을 활용해 테스트 케이스 작성

---
### 고민한 점 및 질문
1. test double
* test double이란 테스트를 진행하기 어려운 경우 대신하여 테스트를 진행할 수 있도록 만들어주는 객체라고 합니다. 따라서, 네트워크 통신을 직접하지 않고(외부적인 요인에 영향을 받지 않는 상태로) 테스트할 수 있습니다.
    * HTTPURLResponse타입의 dummyResponse를 만듭니다. -> dummyData에 임의의 데이터와 dummyResponse를 넣습니다. -> stubURLSession에 dummyData를 넣습니다. -> HTTPManager의 urlSession이 stubURLSession이 되도록 합니다. -> httpManager.loadData 메서드에 completionHandler를 전달하고 completionHandler가 호출되는지 확인합니다.
* dummy : 객체 전달이 주된 목적이고 정상적으로 동작하지 않습니다. 
    * DummyData가 data, reponse, error, completionHandler를 가집니다. completion()를 통해 completionHandler를 처리합니다.
* stub : Dummy가 실제로 동작하는 것처럼 만들어 실제 코드를 대신해서 동작해 주는 객체입니다.
    * StubURLSession에서는 dummyData를 프로퍼티로 가지고 dataTask메서드(URLSessionProtocol에서 구현하기를 요구한 메서드)를 구현합니다. 해당 메서드는 단순히 StubURLSessionDataTask를 생성해서 반환합니다.
    * StubURLSessionDataTask는 URLSessionDataTask를 상속받고 dataTask의 인자로 전달된 dummyData와 completionHandler를 통해 dummyData를 만듭니다. 이때, url은 사용되지 않습니다. resume() 메서드를 오버라이딩하여 completionHandler가 동작하도록 구현합니다.
* 의존성 주입 : 하나의 객체가 다른 객체의 의존성을 제공하는 기술로 결합도를 낮춥니다. 
    * URLSessionProtocol를 구현하고 URLSession과 StubURLSession에서 이를 채택합니다. HTTPManger에서 URLSessionProtocol 타입의 urlSession 프로퍼티를 가져서 해당 프로토콜을 준수하는 어떤 타입이든 사용가능합니다.

2. 비동기 테스트
* HTTPManager의 listenHealthChecker()와 loadData() 메소드는
비동기적으로 동작하는 URLSession.shared.dataTask()를 호출하기 때문에 비동기적으로 작업을 처리합니다.
* 이러한 비동기 메소드를 테스트하기 위해 expectation(description:), fulfill(), wait(for: timeout:) 라는 세가지 테스트 메소드를 활용했습니다.
    * expectation(description:) 으로 어떤 것이 수행되어야하는가에 대한 description을 지정하고,
    * fulfill()를 정의된 expectation이 충족되는 시점에 호출하여 동작이 수행되었음을 알립니다.
    * wait(for: timeout:)은 for: 에 expectation을 배열로 담을 수 있습니다. 배열에 들어간 expectation이 모두 timeout으로 지정해둔 시간 동안 fulfill되길 기다립니다.

3. 서버에서 데이터 fetch
* competionHandler를 사용하는 방식과 delegate를 사용하는 방식 중에 전자를 사용해서 구현했습니다.
* product 목록(2.5. 상품 리스트 조회)과 product 상세내용(GET2.4. 상품 상세 조회)을 가져오는 경우 url을 제외한 내부 구현이 동일해서 둘 다 loadData 메서드를 사용해서 GET 합니다.
* 현재 API 서비스의 동작여부 및 Listen을 확인하는 Application HealthChekcer의 경우 따로 받아오는 데이터가 없어서 별도의 메서드(listenHealthChecker)로 구현했습니다. statusCode를 통해 성공여부를 확인합니다.

4. result type
* 네트워크 성공과 실패를 명확하게 보여주기 위해서 Result type을 사용했습니다.
* dataTask의 completionHandler가 throws가 아니라서 에러를 던져서 처리하는 것을 불가능합니다. 따라서 completionHandler에 실패한 결과나 성공한 결과를 담도록 구현했습니다.

5. StubURLSessionDataTask 이니셜라이저
```
'init()' was deprecated in iOS 13.0: Please use -[NSURLSession 
dataTaskWithRequest:] or other NSURLSession methods to create instances
```
init을 사용하지 않는 방식으로 구현하려고 했으나 실패했습니다😢
해결하기 위해 공부해야 할 키워드를 알려주실 수 있으실까요?😭

2022-05-11 17:54 UTC, 1Consumption requested changes
안녕하세요~ 파프리, 티아나! 잘 부탁드립니다.

비동기 테스트, 의존성 주입... 많이 생소하고 어려웠죠?
저도 맨 처음에 개념을 잡는 데 오래 걸렸던 게 생각나네요.

어느 정도 리서치해보고 적용해보셨는데, 아쉬운 점이 있어서 코멘트로 남겼어요.

아래는 코멘트 달아주신 부분에 대한 제 생각입니다.
----------------------------------------
test double
* test double이란 테스트를 진행하기 어려운 경우 대신하여 테스트를 진행할 수 있도록 만들어주는 객체라고 합니다. 따라서, 네트워크 통신을 직접하지 않고(외부적인 요인에 영향을 받지 않는 상태로) 테스트할 수 있습니다.
    * HTTPURLResponse타입의 dummyResponse를 만듭니다. -> dummyData에 임의의 데이터와 dummyResponse를 넣습니다. -> stubURLSession에 dummyData를 넣습니다. -> HTTPManager의 urlSession이 stubURLSession이 되도록 합니다. -> httpManager.loadData 메서드에 completionHandler를 전달하고 completionHandler가 호출되는지 확인합니다.
* dummy : 객체 전달이 주된 목적이고 정상적으로 동작하지 않습니다. 
    * DummyData가 data, reponse, error, completionHandler를 가집니다. completion()를 통해 completionHandler를 처리합니다.
* stub : Dummy가 실제로 동작하는 것처럼 만들어 실제 코드를 대신해서 동작해 주는 객체입니다.
    * StubURLSession에서는 dummyData를 프로퍼티로 가지고 dataTask메서드(URLSessionProtocol에서 구현하기를 요구한 메서드)를 구현합니다. 해당 메서드는 단순히 StubURLSessionDataTask를 생성해서 반환합니다.
    * StubURLSessionDataTask는 URLSessionDataTask를 상속받고 dataTask의 인자로 전달된 dummyData와 completionHandler를 통해 dummyData를 만듭니다. 이때, url은 사용되지 않습니다. resume() 메서드를 오버라이딩하여 completionHandler가 동작하도록 구현합니다.

> ☃️ 말씀해주신 Dummy는 정상적으로 동작하지 않는다고 하셨는데, completionHandler를 통해 검증이 이루어진다면 제대로 작동하는거 아닐까요? 아직 Test Double에 대한 이해가 부족한 거 같습니다. 아래 링크를 공부해보세요.
https://martinfowler.com/articles/mocksArentStubs.html
https://academy.realm.io/posts/making-mock-objects-more-useful-try-swift-2017/

<br>

StubURLSessionDataTask 이니셜라이저
```
'init()' was deprecated in iOS 13.0: Please use -[NSURLSession 
dataTaskWithRequest:] or other NSURLSession methods to create instances
```
init을 사용하지 않는 방식으로 구현하려고 했으나 실패했습니다😢
해결하기 위해 공부해야 할 키워드를 알려주실 수 있으실까요?😭

> ☃️ 지금 방식은 URLSessionDataTask를 상속받기 때문에 어쩔 수 없이 이니셜라이저를 사용해야 할 듯 합니다... 이런 방법이 싫다면 URLSessionDataTask를 서브클래싱 하지 않고 [URLProtocol](https://developer.apple.com/documentation/foundation/urlprotocol)을 사용하는 방법도 있으니 알아보면 좋을듯 합니다.

나머지는 코멘트를 참고해주세요.

2022-05-11 17:54 UTC, 1Consumption commented on OpenMarket/OpenMarket/Test/Test Double/StubURLSession.swift
> +}
이 코드들이 프로덕트에 들어가야하나요?

2022-05-11 17:54 UTC, 1Consumption commented on OpenMarket/OpenMarket/Test/Test Double/URLSessionProtocol.swift
> +extension URLSession: URLSessionProtocol { }
이건 Test Double이라고 말할 수 있나요?

2022-05-11 17:54 UTC, 1Consumption commented on OpenMarket/OpenMarket/Model/HTTPManager.swift
> +        let requestURL = hostURL + TargetURL.healthChecker.string
이부분도 TargetURL에서 한번에 반환하면 어떨까요? 여기서 조합해야하는 이유가 있을까요?

2022-05-11 17:54 UTC, 1Consumption commented on OpenMarket/OpenMarket/Model/HTTPManager.swift
> +            }
clientError라고 표현한 이유가 있을까요?
그리고 error를 enum의 연관값으로 같이 보내면 좋겠습니다.

2022-05-11 17:54 UTC, 1Consumption commented on OpenMarket/OpenMarket/Model/HTTPManager.swift
> +            }
serverError라고 단정할 수 있나요?
400번대 에러는 서버의 문제일까요?

2022-05-11 17:54 UTC, 1Consumption commented on OpenMarket/OpenMarket/Model/HTTPManager.swift
> +            }
데이터가 비어있는 경우도 처리되면 좋겠습니다.

2022-05-11 17:54 UTC, 1Consumption commented on OpenMarket/OpenMarket/Model/HTTPManager.swift
> +        task.resume()
이 task를 취소하고 싶다면 어떻게 해야할까요?

2022-05-11 17:54 UTC, 1Consumption commented on OpenMarket/OpenMarket/Test/Test Double/StubURLSession.swift
> +}
completionHandler를 통해 검증을 하는 거 같은데, dummy라고 부를 수 있을까요?

2022-05-11 17:54 UTC, 1Consumption commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +class OpenMarketTests: XCTestCase {
이 테스트파일의 이름은 어디까지를 포함하나요? 너무 이름이 추상적인데요.

2022-05-11 17:54 UTC, 1Consumption commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    }
에러가 발생하면 애초에 전제가 잘못된 테스트 아닐까요?
그리고 어떤걸 테스트하는건가요? 파프리와 티아나가 만든 기능이 아니라 애플에서 제공하는 API를 테스트 하는걸까요?

2022-05-11 17:54 UTC, 1Consumption commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    }
테스트 코드에서 직접 네트워킹까지 하는건가요? 만약 네트워크에 연결되어있지 않다면 이 테스트는 항상 실패하지 않을까요?

2022-05-11 17:54 UTC, 1Consumption commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    }
모두 잘못된 테스트 같습니다. HTTPManager의 생성자로 URLSessionProtocol을 채택한 Mock 객체가 들어가야 할 거 같아요.
서버에서 내려주는 리스폰스가 달라지면 이 테스트는 실패할겁니다. 실제 네트워킹을 하면 안됩니다.

2022-05-11 17:54 UTC, 1Consumption commented on OpenMarket/StubURLSessionTests/StubURLSessionTests.swift
> +}
의존성 주입을 통한 테스트를 진행하셨군요! 네트워크에 의존하지도 않았고요. 항상 같은 값이 들어가기 때문에 테스트에 영향도 없을거고요.
다만 dummy와 stub, mock의 차이를 명확히 했으면 좋겠습니다.

2022-05-13 03:14 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Test/Test Double/StubURLSession.swift
> +}
이 파일은 테스트케이스에서만 사용되는 것이라서 테스트 모듈로 옮기는 것이 좋아보입니다.

하지만 URLProtocol을 채택하는 Mock객체를 만드는 리팩토링 과정에서  필요 없는 파일이 되어서 삭제했습니다.
[fded7b7](https://github.com/yagom-academy/ios-open-market/pull/138/commits/fded7b7bb96b1afc78a5a4f2d3a8dc725fa5ab07)

2022-05-13 03:15 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Test/Test Double/URLSessionProtocol.swift
> +extension URLSession: URLSessionProtocol { }
프로토콜 정의 및 채택이어서 test double(테스트를 위해 실제 객체인 것처럼 하는 객체)가 아닙니다.

하지만 이것도 URLProtocol을 채택하는 Mock객체를 만드는 리팩토링 과정에서 필요 없는 파일이 되어서 삭제했습니다.
[fded7b7](https://github.com/yagom-academy/ios-open-market/pull/138/commits/fded7b7bb96b1afc78a5a4f2d3a8dc725fa5ab07)

2022-05-13 03:16 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Model/HTTPManager.swift
> +        let requestURL = hostURL + TargetURL.healthChecker.string
연산 프로퍼티로 한번에 반환하도록 수정했습니다.
[a5cfc6c](https://github.com/yagom-academy/ios-open-market/pull/138/commits/a5cfc6c24c70d0eb89e0ea5378bee5517355c896)

2022-05-13 03:18 UTC, papriOS commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    }
실제로 서버와의 네트워킹이 제대로 진행되는지 궁금하여 진행해본 테스트였습니다! 
말씀해주신대로 해당 파일을 삭제하고 실제 네트워킹을 하지 않는 Mock객체를 통해 테스트를 진행하였습니다
[fded7b7](https://github.com/yagom-academy/ios-open-market/pull/138/commits/fded7b7bb96b1afc78a5a4f2d3a8dc725fa5ab07)

2022-05-13 03:19 UTC, papriOS commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    }
넵 맞습니다! 해당 파일을 삭제하고 [fded7b7](https://github.com/yagom-academy/ios-open-market/pull/138/commits/fded7b7bb96b1afc78a5a4f2d3a8dc725fa5ab07)
네트워크 연결을 하지 않고 Mock객체를 통해 Test를 진행하도록 하였습니다.

2022-05-13 03:21 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Model/HTTPManager.swift
> +            }
공식문서에서 해당 부분에서 clientError 처리하는 메서드를 호출하여 clientError라고 구현했습니다.
[Fetching Website Data into Memory](https://developer.apple.com/documentation/foundation/url_loading_system/fetching_website_data_into_memory)

조언해주신대로 clientError와 serverError를 구분하지 않고 invalidStatusCode로 수정했습니다!
연관값을 사용하는 경우 원시값을 사용할 수 없어서 LocalizedError를 사용했습니다.
[90e58a9](https://github.com/yagom-academy/ios-open-market/pull/138/commits/90e58a90b4a204450ab91a8e58eb8cf85a0e9d42)

2022-05-13 03:25 UTC, papriOS commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    }
제공된 Mock 데이터를 활용하여 모델이 네트워크 통신의 결과 데이터(실제 네트워크 통신 아님 주의)를 문제없이 표현하고 활용할 수 있는지 단위 테스트(Unit Test)를 수행하라는 요구사항을 보고,
네크워크 통신 결과 데이터가 제공된 mock데이터인 json파일이라고 생각하였습니다.
그래서 해당 json 파일을 Asset에 저장하고, 로컬에 저장된 json파일을 decode할 수 있도록 Decodable 프로토콜을 확장해 parse메소드를 구현했는데, 이를 테스트 하라는 것으로 이해했습니다.
다시보니 의미가 없는 테스트임을 깨달아 삭제하였습니다! [fded7b7](https://github.com/yagom-academy/ios-open-market/pull/138/commits/fded7b7bb96b1afc78a5a4f2d3a8dc725fa5ab07)
감사합니다!

2022-05-13 03:25 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Model/HTTPManager.swift
> +            }
4xx가 client errors인 것을 확인했고 조언해주신 것처럼 invalidStatusCode로 하나의 에러 케이스로 수정했습니다!
[90e58a9](https://github.com/yagom-academy/ios-open-market/pull/138/commits/90e58a90b4a204450ab91a8e58eb8cf85a0e9d42)

2022-05-13 03:27 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Model/HTTPManager.swift
> +            }
데이터가 비어있으며 emptyData error로 실패처리하도록 수정했습니다.
[d3cbd44](https://github.com/yagom-academy/ios-open-market/pull/138/commits/d3cbd4486684401e4a1510a468ec3ba1aba09e23)

2022-05-13 03:27 UTC, papriOS commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +class OpenMarketTests: XCTestCase {
해당 테스트파일을 삭제하고, [fded7b7](https://github.com/yagom-academy/ios-open-market/pull/138/commits/fded7b7bb96b1afc78a5a4f2d3a8dc725fa5ab07)
HTTPManager가 그 역할을 제대로 수행하는지 확인하기 위한 [f3d8c28](https://github.com/yagom-academy/ios-open-market/pull/138/commits/f3d8c281b849643269a14c5afdfa10a1c816cac8) HTTPManagerTests 파일을 생성하였습니다.
[7ed7bbe](https://github.com/yagom-academy/ios-open-market/pull/138/commits/7ed7bbeb37081dfb5f28bbb7447c1b279ddc0662)

2022-05-13 03:31 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Model/HTTPManager.swift
> +        task.resume()
URLSessionDataTask?를 반환 타입으로 수정하고, task를 반환하도록 수정했습니다.

조언해주신 것처럼 cancel메서드를 호출하는 것은 HTTPManager의 역할이 아니기 때문에 cancel 메서드는 구현하지 않았습니다.
[5e3bfac](https://github.com/yagom-academy/ios-open-market/pull/138/commits/5e3bface5004e6ae4081ae6c270a61189ee7d2f9)

2022-05-13 03:32 UTC, papriOS commented on OpenMarket/StubURLSessionTests/StubURLSessionTests.swift
> +}
현재는 URLProtocol을 상속하는 subclass로 UnitTest를 진행하는 방향으로 바뀌어 해당 파일을 삭제하였습니다!
[fded7b7](https://github.com/yagom-academy/ios-open-market/pull/138/commits/fded7b7bb96b1afc78a5a4f2d3a8dc725fa5ab07)

2022-05-13 03:37 UTC, papriOS commented on OpenMarket/OpenMarket/Test/Test Double/StubURLSession.swift
> +}
dummy는  passed around되지만 실제로 사용되지 않는 object로, 주로 그냥 파라미터 자리를 채우기 위해 사용됩니다!
completionHandler를 통해 제대로 data,response, error를 받아온 것인지 검증을 하기 때문에,
expectation을 부여받은 mock이라고 봐야할 것 같습니다!
(이 파일은 URLProtocol의 subclass를 활용한 unitTest를 진행하는 방법을 선택하여, 현재 삭제된 상태입니다)

2022-05-13 03:47 UTC, papriOS commented on OpenMarket/StubURLSessionTests/StubURLSessionTests.swift
> +}
dummy와 stub, mock의 차이에 대해서 올라프가 공유해주신 링크를 통해 공부해보았습니다!
```swift
let dummyResponse = HTTPURLResponse(url: url, statusCode: 200, httpVersion: nil, headerFields: ["Content-Type" : "application/json"])
let dummyData = DummyData(data: data, response: dummyResponse, error: nil)
let stubURLSession = StubURLSession(dummyData: dummyData)
```
* dummyResponse는 단순 매개변수로서의 역할만 수행하기 때문에 dummy가 맞는 것 같습니다
* dummyData과 stubURLSession은 둘 다 completionHandler를 통한 검증을 진행하기 때문에, 테스트 외부에 대해선 응답하지 않는 stub이 아닌 mock이라고 생각됩니다!

2022-05-13 04:17 UTC, papriOS commented
### 저희의 MockURLProtocol object도 이렇게 behavior Verification을 진행하고 있는 게 맞는지 의문이 들어 코멘트를 남깁니다!🤔

mock과 stub의 차이에 대해 올라프가 공유해주신 링크를 통해서 공부했을 때, 가장 큰 차이로서 mock은 behavior verification을 진행하고, stub은 status verification을 진행하는 것이 있음을 알았습니다.

링크에 따르면 Mock 객체는 expectation을 부여하고 미리 프로그래밍된 object입니다.
여기서 말하는 expectation은 mock 객체가 받을 것이라고 예상되는 call들로 이해하였습니다.
Mock객체는 expectation이 충족되었는지, 즉 불려야할 method(MockURLProtocol의 경우 dataTask 메서드)가 불렸는지를 verify해야하고, 이것이 behavior verification을 진행하는 것이라고 이해했습니다.

[보내주신 자료](https://academy.realm.io/posts/making-mock-objects-more-useful-try-swift-2017/)에 의하면 expecation이 충족 되었는지를 확인하기 위해 
```swift
class MockCook: CookProtocol {
    var cookRamenCallCount = 0
    var cookRamenLastBowls = 0
    var cookRamenLastSoup: RamenSoup?
    var cookRamenLastExtras: [String] = []

    func cookRamen(
                   bowls: Int,
                   soup: RamenSoup,
                   extras: [String]) -> Void {
        cookRamenCallCount += 1
        cookRamenLastBowls = bowls
        cookRamenLastSoup = soup
        cookRamenLastExtras = extras
    }

		func verifyCookRamen( 
				        	bowls: Int,
				        	soup: RamenSoup,
				        	extras: [String]) -> Void {
	    	XCTAssertEqual(cookRamenCallCount, 1);
        XCTAssertEqual(cookRamenLastBowls, bowls);
        XCTAssertEqual(cookRamenLastSoup, soup);
        XCTAssertEqual(cookRamenLastExtras, extras)
	}
}
```
다음과 같은 verifyCookRamen() 메소드를 구현하였습니다.


우선 저희는 Mock에 verify의 메서드가 있다면 이는 위의 코드처럼 매개변수로 외부 요인을 전달하고 내부에서 대응하는 결과를 확인한다고 생각합니다.

![](https://i.imgur.com/ba1njaD.png)

아래 코드에서는 static 프로퍼티인 requestHandler 클로저에서 expectaion을 받고 결과적으로는 HTTPManager 객체의 메서드의 completionHandler에서 대응하는 반응을 보이기 때문에 behavior verification이 제대로 진행됐다고 생각합니다.


```swift
import XCTest
import Foundation

class MockURLProtocol: URLProtocol {
    static var requestHandler: ((URLRequest) throws -> (HTTPURLResponse, Data))?
    
    override class func canInit(with request: URLRequest) -> Bool {
        return true
    }
    
    override class func canonicalRequest(for request: URLRequest) -> URLRequest {
        return request
    }
    
    override func stopLoading() { }
    
    override func startLoading() {
        guard let handler = MockURLProtocol.requestHandler else {
            XCTFail("Received unexpected request with no handler set")
            return
        }
        do {
            let (response, data) = try handler(request)
            client?.urlProtocol(self, didReceive: response, cacheStoragePolicy: .notAllowed)
            client?.urlProtocol(self, didLoad: data)
            client?.urlProtocolDidFinishLoading(self)
        } catch {
            client?.urlProtocol(self, didFailWithError: error)
        }
    }
}
```

```swift
func test_listenHealthChecker_호출하면_StatusCode가_200인지_확인() {
        // given
        MockURLProtocol.requestHandler = {request in
            let exampleData = self.dummyProductListData
            let response = HTTPURLResponse(url: request.url!, statusCode: 200, httpVersion: nil, headerFields: nil)!
            return (response, exampleData)
        }
        
        let expectation = XCTestExpectation(description: "It gives StatusCode 200")
        
        //when
        httpManager.listenHealthChecker { response in
            switch response {
            case .success(let response):
                
                // then
                XCTAssertEqual(response.statusCode, 200)
            default:
                break
            }
            expectation.fulfill()
        }
        wait(for: [expectation], timeout: 5)
    }
```

⛄️올라프는 어떻게 생각하시나요?? 
MockURLProtocol이 mock으로서의 역할을 잘 수행하였는지, 저희가 mock에 대해서 이해한 바가 맞는지 확인받고 싶어 코멘트 남깁니다!!

2022-05-14 01:23 UTC, 1Consumption approved these changes
Mock에 대해서 제대로 이해한게 맞습니다~ 파프리 티아나👏👏👏 

몇가지 코멘트를 남겼는데, 이건 다음 스텝을 진행하면서 반영해도 좋아요. 머지하겠습니다.

고생하셨습니다!

2022-05-14 01:23 UTC, 1Consumption commented on OpenMarket/HTTPManagerTests/HTTPManagerTests.swift
> +    }
이 테스트도 사실 의미없어 보이긴 하네요.

2022-05-14 01:23 UTC, 1Consumption commented on OpenMarket/HTTPManagerTests/HTTPManagerTests.swift
> +    }
이 두 코드 모두 특정 프로퍼티만 비교하면서 assertion을 진행하고 있는데요, 그 정보가 identifier가 될 수 있을까요?
Equatable을 통해 객체 자체를 비교하는건 어떨까요?

2022-05-14 01:23 UTC, merged