오픈마켓 I [STEP 1] mmim, cathy
yagom-academy/ios-open-market pull request #141
Opened 2022-05-11 14:54 UTC by JoSH0318

@Monsteel  토니!!! 안녕하세요!!!
STEP1 PR 입니다.
잘부탁드립니다 🙇‍♂️

---

## UML
<image width="500" src="https://i.imgur.com/isTPzq2.jpg"/>

--- 

### 고민한 점(트러블 슈팅)
1️⃣ 서버와 통신하지 않고 Mock 데이터로 통신하기
- **URLSessionProvider**구조체에선 URLSession과 request를 만들어 서버에 보내고 **get()** 메서드를 통해 **dataTask(with:)** 를 호출하고 data를 받는 역할을 한다.
- 이 구조체는 서버와의 통신을 위해 만든 타입이고, 때문에 서버와 통신하지 않은 Mock 테스트를 하는 방법에 대해서 고민했다.
- **URLSessionProvider** 구조체는 `session: URLSession` 프로퍼티를 갖는다.
- 때문에 **URLSessionProvider**와 **URLSession**의 결합도가 높다.
> 결합도가 높아서 재활용성이 낮고, 유지/보수가 힘들고, 단위 테스트가 어렵다.
- 결합도를 낮추기 위해서 **URLSession** 타입과 테스트를 위한 **MockURLSession** 에 **URLSessionProtocol**을 채택하였고, `session: URLSessionProtocol`로 변경하였다.
- 이를 통해 URLSessionProvider 초기화할 때, 필요한 URLSession을 의존성 주입할 수 있게 됐다. 
- ex) URLSessionProvider(session: MockURLSession())
    
2️⃣ DummyData 만들기
- 서버에서 받을 수 있는 똑같은 형태의 JSON 파일을 Dummy 데이터로 활용하여 테스트하는 방법에 대해서 고민했다.
- 서버에서는 dataTask()를 통해 `Data, URLResponse, Error`을 받아온다.
- 따라서 우리가 활용할 Dummy data 또한 Data 타입이어야 한다는 것을 알 수 있다.
- JSON파일을 Asset에 추가하고, Asset으로부터 NSDataAsset() 메서드를 통해 JSON파일을 로드했다. 
- NSDataAsset의 data 연산프로퍼티를 통해 Data 타입으로 변경하여 Dummy data로 활용했다.
    
3️⃣ dataTask(with: URL) vs dataTask(with: URLRequest) 
- URLSession의 dataTask 메서드를 호출할 때, 파라미터로 request 또는 url을 넣어준다.
- httpMethod의 기본값은 "GET" 이기 때문에 `request.httpMethod`에 "GET"을 명시할 필욘없다.
- 하지만 이후에 POST, PATCH 등 다양한 요구사항의 생길 것을 예상하여 `dataTask(with: URLRequest)`을 사용하고 `request.httpMethod`에 "GET"을 명시하는 것을 선택했다.

4️⃣ query값 입력받기
- 이번 프로젝트엔 `{{api_host}}/api/products?page_no=1&items_per_page=10`에서 본 것처럼 `?` 이후에 있는 쿼리값이 존재한다.
- 따라서 쿼리값을 입력받아 원하는 경로, 쿼리에 맞는 정보를 얻을 수 있도록 구현하는 것을 고민했다.
- **URLComponents** 타입은 URL을 구성하는 구조로써 `queryItems`라는 배열형태의 프로퍼티를 갖는다.
- 이 프로퍼티에 쿼리스트링을 주입할 수 있다.
```swift
// URLComponents을 초기화해준다.
guard var urlComponents = URLComponents(string: hostApi + path) else {
    return
}
// 여러개의 쿼리스트링이 존재할 수 있음. 
// 따라서 파라미터로 입력받은 딕셔너리 타입의 값을 mapping하여 [URLQueryItem]로 만들어준다.
let query = parameters.map {
    URLQueryItem(name: $0.key, value: $0.value)
}
//queryItems에 [URLQueryItem]을 할당
urlComponents.queryItems = query
//URL 타입으로 변환
guard let url = urlComponents.url else {
    return
}
```
- 위와 같은 방법으로 URL에 호스트 API와 path, 쿼리스트링을 주입할 수 있다.

4️⃣ escaping closure
```swift
    func get(completionHandler: @escaping (Result<T, NetworkError>) -> Void) {
        ...
       guard let response = response as? HTTPURLResponse,
            (200...299).contains(response.statusCode)
       else {
           completionHandler(.failure(.statusCodeError))
           return
      }
    }
```
`get()`메서드에서 `completion closure`는 서버에 URL요청 후 비동기로 실행되기 때문에 `@escaping`을 선언해줘서 네트워크 요청 처리가 끝난 후 실행해야할 것을 `completion handler`에 작성해주었다.
위와 같이 `statusCode`가 200대라는 조건이 충족되지 않으면 실패했을 때의 `escaping closure`를 실행시켜준다.

5️⃣ 비동기로 테스트하기
`dataTask` 메서드가 비동기적으로 작업을 처리하기 때문에 `expectation(description:)`, `fulfull()`, `wait(for:timeout:)` 메서드를 사용하여 테스트하였다.
```swift
let promise = expectation(description: "")
    sut = URLSessionProvider<ProductsList>(path: "/api/products",
                                           parameters: ["page_no": "1", "items_per_page": "20"])
    let data = 69
    sut.get { result in
      switch result {
      case .success(let products):
        XCTAssertEqual(products.lastPage, data)
      case .failure(_):
        XCTFail()
      }
      promise.fulfill()
    }
    wait(for: [promise], timeout: 10)
```
- `expectation(description:)` : 수행되어야 하는 내용을 description으로 정해준다.
- `fulfull()` : 정의한 expectation가 충족될 때 호출한다.
- `wait(for:timeout:)` : expectation을 배열로 전달해서 배열의 모든 요소가 `fulfill`될 때까지 기다린다.

### 질문사항
1️⃣ JSON과 매칭할 모델타입을 구현할 때...
아래와 같이 오픈마켓API에서는 `상품 상세 조회`에 images와 venders가 존재합니다.
<image width="400" src="https://i.imgur.com/2xlfBr2.png"/>
하지만 `상품 리스트 조회`에서는 각각 pages 내에 있는 항목과 위의 내용과 다릅니다.
<image width="400" src="https://i.imgur.com/vaEaC10.png"/>

저희는 JSON과 매칭할 모델타입에 images와 venders를 위한 타입도 만들었지만
테스트할 때, 오류가 생겼습니다.
예상하건데, `상품 리스트 조회`에서 받을 수 있는 Data에는 images와 venders가 없어서 매칭할 수 없어 생기는 오류로 예상했습니다.

이부분은 이후 STEP에서 진행하는 추가적인 부분인가요? 아니면 저희의 실수였을까요 😭?

2️⃣ 전체적인 설계 구조?
저희가 서버와의 통신이 처음이라서 많이 힘들었는데요 😭 
특히 어떠한 구조로 코딩해야할 것 인지에 대한 부분이 가장 어려웠습니다.
저희 코드의 설계 구조(?)적인 부분에서 조언을 받고 싶습니다.

3️⃣ URLSessionDataTask의 init() ❗️deprecated???
저희가 Mock 테스트를 위해서 MockURLSession에서 URLSessionDataTask을 초기화해야 합니다.
그런데 아래와 같이 `init() ❗️deprecated`됐다는 경고가 뜹니다.
![](https://i.imgur.com/LGCjARc.png)
추천 방법이나 대체되는 방법을 제시하지 않아... 어떤 대안책이 있을지 모르겠습니다 😭

2022-05-12 09:14 UTC, Monsteel requested changes
안녕하세요 mmim, cathy~ 🙌
Step1 진행하시느라 수고 많으셨습니다 ㅜ

REST 통신은 처음이시다 보니, 막히시는 부분이 많으셨군요 😭
그래도 잘 진행해 주셨습니다! 리뷰내용 중 궁금하신 내용이 있으시거나, 진행하시면서 어려운 부분이 있으시면 편하게 언제든지 DM부탁드려요 😊

자, 우선 코드에 대한 리뷰는 몇가지 남겼는데, 확인해주시면 감사하겠구요, 남겨주신 질문사항에 대한 답변을 이곳에 작성해 볼게요 :)

> 1️⃣ JSON과 매칭할 모델타입을 구현할 때...
> 아래와 같이 오픈마켓API에서는 `상품 상세 조회`에 images와 venders가 존재합니다.
> <image width="400" src="https://i.imgur.com/2xlfBr2.png"/>
> 하지만 `상품 리스트 조회`에서는 각각 pages 내에 있는 항목과 위의 내용과 다릅니다.
> <image width="400" src="https://i.imgur.com/vaEaC10.png"/>
> 
> 저희는 JSON과 매칭할 모델타입에 images와 venders를 위한 타입도 만들었지만
> 테스트할 때, 오류가 생겼습니다.
> 예상하건데, `상품 리스트 조회`에서 받을 수 있는 Data에는 images와 venders가 없어서 매칭할 수 없어 생기는 오류로 예상했습니다.
> 
> 이부분은 이후 STEP에서 진행하는 추가적인 부분인가요? 아니면 저희의 실수였을까요 😭?

해당 부분은 REST API 특성에 대해 먼저 아시면 좋을것 같은데요,

RestAPI의 특성상 부득이하게 필요한 데이터 이상으로 서버에서 데이터를 받아오는 문제([over fetching](https://intrepidgeeks.com/tutorial/overfetching-underfetching)) 이슈로부터 자유롭지 못한데요, 이런 문제를 해결하기 위해서는, API별로 필요한 데이터들만 내려주는 일반적인 해결책이 있습니다.

야곰이 설계한 API도 Over fetching 문제를 경계하기 위해 의도적인 설계로 보입니다. 🙌

_c.f) `상품 리스트 조회` API에서 Images(모든 이미지를) 내려주는 것 보다, thumbnail(썸네일 이미지)만 내려주는것이, 불필요한 데이터를 조회하지 않아도 되어 비교적 효율적이겠죠?_

현업에서도 이러한 상황에 처할때가 많은데, 이럴때는 어떻게 하는것이 좋을까요? 🙋🏻‍♂️
두분이서 요 질문에 대해 고민해보시면 좋을 것 같아요 ☀️

> 2️⃣ 전체적인 설계 구조?
> 저희가 서버와의 통신이 처음이라서 많이 힘들었는데요 😭
> 특히 어떠한 구조로 코딩해야할 것 인지에 대한 부분이 가장 어려웠습니다.
> 저희 코드의 설계 구조(?)적인 부분에서 조언을 받고 싶습니다.

Step1까지 진행해주신 부분을 보았을 때 따로 개선이 필요한 구조는 없어 보입니다.
프로젝트를 진행하시면서 구조에 대한 피드백이 필요하다고 판단되면 피드백 할 수 있도록 할게요 🙌

> 3️⃣ URLSessionDataTask의 init() ❗️deprecated???
> 저희가 Mock 테스트를 위해서 MockURLSession에서 URLSessionDataTask을 초기화해야 합니다.
> 그런데 아래와 같이 `init() ❗️deprecated`됐다는 경고가 뜹니다.
> ![](https://i.imgur.com/LGCjARc.png)
> 추천 방법이나 대체되는 방법을 제시하지 않아... 어떤 대안책이 있을지 
> 모르겠습니다 😭

음 `URLSessionDataTask`의 구현부를 살펴보면 인스턴스를 생성하는 대안을 제시하고 있습니다!
참고하시면 좋을 것 같군요! 🚀
<img width="1238" alt="스크린샷 2022-05-12 오후 5 53 34" src="https://user-images.githubusercontent.com/52942409/168035533-24ab04c4-3b6c-49e6-8e63-443065188dbb.png">

mmim, cathy~! 첫 STEP1 진행하시느라 다시한번 수고 많으셨습니다 🙌
리뷰 내용에 대해 이해가 되지 않거나, 궁금한점이 있으시면 언제든 편하게 말씀 부탁드립니다~! 🙏

2022-05-12 09:14 UTC, Monsteel commented on OpenMarket/OpenMarket/Model/Products.swift
> +  let pageNumber: Int?
API spec상 optional선언이 불필요해 보이는데, optional로 선언하신 이유가 있나요? 🙋🏻‍♂️

2022-05-12 09:14 UTC, Monsteel commented on OpenMarket/OpenMarket/Model/Products.swift
> +    case items = "pages"
이렇게 `CodingKeys`를 설정할 때, 필드의 이름이 차이가 나게되면, 같은 정보를 보는데에도 다른 이름으로 부르는 경우가 생겨서
개인적으로 모델 타입을 구현할 때 서버의 필드 이름을 통일하는것을 선호합니다!

만약 서버팀과 함께 커뮤니케이션 하는 상황을 생각해보면,
iOS 개발자는 items 라고 부르고, 서버 개발자는 pages라고 부르게 되어, 서로 혼돈이 생기게 됩니다.

현업에서는 이러한 용어의 차이로 인해서 발생하는 문제를 해결하기 위해 [UbiquitousLanguage](https://martinfowler.com/bliki/UbiquitousLanguage.html#:~:text=Ubiquitous%20Language%20is%20the%20term,language%20between%20developers%20and%20users.)를 정의하여 해결하기도 하는데요,
해당 케이스에서는 서버팀과 함께 통일된 네이밍에 대해 논의하기는 어려운 상황이니, API Spec에 따라 네이밍을 정해서 통일할 수 있을 것 같아요 ✍🏻

2022-05-12 09:14 UTC, Monsteel commented on OpenMarket/OpenMarket/Model/Products.swift
> +struct ProductsList: Codable {
`Decodable`을 채택해도 될 것 같은데, `Codable`을 사용하신 이유가 있을까요? 🙋🏻‍♂️

2022-05-12 09:14 UTC, Monsteel commented on OpenMarket/OpenMarket/Model/URLSessionProvider.swift
> +  func get(completionHandler: @escaping (Result<T, NetworkError>) -> Void) {
`escaping` 클로저를 활용해서 아주 잘 구현해 주셨습니다 🚀

2022-05-12 09:14 UTC, Monsteel commented on OpenMarket/OpenMarket/Model/URLSessionProvider.swift
> +            (200...299).contains(response.statusCode)
`200..<300` 으로도 표현할수도 있어요 🙌

2022-05-12 09:14 UTC, Monsteel commented on OpenMarket/OpenMarket/Model/URLSessionProvider.swift
> +    request.httpMethod = "GET"
요 `httpMethod`는 enum을 활용해서 정의하면 이후 확장성에 더 좋을것 같은데, 어떠세요?! 🙋🏻‍♂️

2022-05-12 11:20 UTC, JoSH0318 commented on OpenMarket/OpenMarket/Model/Products.swift
> +  let pageNumber: Int?
decode 해주는 과정에서 nil값에 대한 처리를 해주고 있기 때문에 토니 말씀대로 없어도 될 것 같습니다! 🤓
수정했습니다!

2022-05-12 11:26 UTC, JoSH0318 commented on OpenMarket/OpenMarket/Model/Products.swift
> +    case items = "pages"
이 부분에 있어서 생각을 전혀 안해봤던 것 같아요 🤭
API Spec에 따라서 이름을 통일하였습니다!

2022-05-12 11:45 UTC, JoSH0318 commented on OpenMarket/OpenMarket/Model/URLSessionProvider.swift
> +    request.httpMethod = "GET"
이번 STEP에는 GET만 사용해서 그 부분까지 생각을 못했던 것 같아요 😱
enum 으로 네임스페이스를 구현하는 것으로 수정했습니다. 
이후에 POST, PATCH 등 기능이 생길때마다 추가하도록하겠습니다. 👍

2022-05-12 11:55 UTC, JoSH0318 commented on OpenMarket/OpenMarket/Model/URLSessionProvider.swift
> +            (200...299).contains(response.statusCode)
수정했습니다!

2022-05-12 11:57 UTC, cathy171 commented on OpenMarket/OpenMarket/Model/Products.swift
> +struct ProductsList: Codable {
한글의 경우 encoding 해야할 경우가 있을 것 같아 Codable을 채택했었는데 생각해보니 필요가 없을 것 같아서 Decodable로 수정하였습니다..!!

2022-05-12 12:26 UTC, Monsteel commented on OpenMarket/OpenMarket/Model/URLSessionProvider.swift
> +            (200...299).contains(response.statusCode)
오호 요런 코멘트는 참고만 하셔도 되어요ㅎㅎ 😇

2022-05-13 02:56 UTC, Monsteel approved these changes
수고많으셨습니다~! 🙌🙌🙌🙌

2022-05-13 02:56 UTC, merged