오픈 마켓 [STEP 1] Eddy, marisol
yagom-academy/ios-open-market pull request #142
Opened 2022-05-11 16:41 UTC by marisol-develop

안녕하세요 @jungseungyeo 첫 번째 PR 보냅니다!
첫 번째 PR인데 내용도 어렵고 저희가 작성한 코드에 확신이 적네요ㅠㅠ
많이 지적해주시고 리뷰해주시면 공부해서 반영 잘하도록 하겠습니다!!

## 📝 UML
![](https://i.imgur.com/7gT8slu.jpg)

---

## 🧐 고민한점 & 해결방법

### 📌 1. URL을 어떻게 조합해서 만들어줘야 할까?

네트워크에 요청을 보내는 GET 역할을 하는 execute 메서드에서 사용할 url을 어떻게 만들어줄지 고민했습니다.
공통으로 사용되는 hostAPI, path 등을 API enum에 static let으로 선언해주고, case 별로 돌면서 enum 메서드에서 연관값을 입력받아 쿼리를 완성한 뒤에, hostAPI와 Path와 쿼리를 합쳐 url을 만들어주었습니다.

```swift
enum API {
    static let hostAPI = "https://market-training.yagom-academy.kr"
    static let productPath = "/api/products"
    static let healthCheckerPath = "/healthChecker"
    
    case productList(pageNo: Int, itemsPerPage: Int)
    case productDetail(productId: Int)
    case healthChecker
    
    func generateURL() -> String {
        switch self {
        case .productList(let pageNo, let itemsPerPage):
            return API.hostAPI + API.productPath + "?page_no=\(pageNo)&items_per_page=\(itemsPerPage)"
        case .productDetail(let productId):
            return API.hostAPI + API.productPath + "/\(productId)"
        case .healthChecker:
            return API.hostAPI + API.healthCheckerPath
        }
    }
}
```

### 📌 2. 하나의 NetworkManager로 네트워크 통신 성공시 여러 타입의 데이터를 디코딩하기 위한 제네릭 타입 사용

Product, ProductDetail, Application HealthChecker 3가지 타입의 데이터를 하나의 GET 메서드를 사용해서 가져올 수 있도록 NetworkManager에 Decodable을 채택하는 제네릭 타입을 선언해주었습니다. 처음에는 ProductNetworkManager와 HealthCheckerNetworkManager 2개의 타입을 만들어주었는데, String이 Decodable 프로토콜을 채택하고 있다는 것을 알게되어 하나로 사용할 수 있었습니다.

---

## ❓ 궁금한점

### 📌 1. dataTask 속 error의 에러처리 표현
dataTask에서 data, response, error 가 있는데 각각 guard 문을 통해 failure 상황을 처리해주려고 했습니다. 
```swift
session.dataTask(with: url) { data, response, error in
    guard error == nil else {
        completion(.failure(.error))
        return
    }
```
이곳에서 completion이 실패했을 때 에처를 처리하기 위해 enum으로 모아서 했는데 이곳에서 나는 에러가 무엇일지 정확하게 판단하기 어려웠습니다. 
serverError, transportError 둘 중 하나가 날 것이라고 구글링 결과 나왔는데, serverError는 statusCode에서 처리가 되는 게 아닌가 싶습니다..! 
그래서 정확하게 어떤 에러가 나는지 파악이 어려워서 네이밍을 선정하기 어려웠습니다. 이곳에서 나는 에러는 전송이 실패한 에러일까요? 아니면 다른 에러일까요?

### 📌 2. init Deprecated
저희가 init를 StubURLSessionDataTask에서 사용해서 dummyData와 completion를 초기화해주려고 했습니다.
```swift
init(dummy: DummyData?, completionHandler: DataTaskCompletionHandler?) {
    self.dummyData = dummy
    self.dummyData?.completionHandler = completionHandler
}
```
이것을 사용하면 이렇게 경고창이 계속 뜨더라구요.. 이를 근데 아래서 제안한 방식으로 바꿔야할지..? 아니면 이것을 사용해도 무방할지 모르겠었습니다..ㅠㅠ 예시를 찾아봐도 코드가 obj-c 같은 코드들인데.. 왜이것을 제안하는것인지..? 이 방식을사용해야하는지 궁금합니다!
```
'init()' was deprecated in iOS 13.0: 
Please use -[NSURLSession dataTaskWithRequest:] 
or other NSURLSession methods to create instances
```

### 📌 3. test code에서 강제언래핑 사용가능여부
강제 언래핑을 사용하지 않아야 하고, 이는 앱 크러쉬가 날 수도 있기에 조심해야한다고 생각합니다.
하지만 test code에서는 앱의 사용에 지장이 없을 뿐더러 정확한 환경 속에서 테스트한다고 생각해서 
강제 언래핑을 사용해도 되지 않을까? 생각을 했었습니다.
물론 옵셔널 바인딩을 통해 풀어줄 수도 있지만.. 확실하다고 생각하는 부분을 강제언래핑으로 하면 안될까하는 생각을 했었는데 린생의 생각은 어떤가요?

### 📌 4. HTTPURLResponse 에 대한 궁금증
저희가 dummyData를 test할 시 response에 아래와 같이 성공케이스 조건을 넣도록 사용했습니다.

```swift
let response = HTTPURLResponse(url: url,
                                       statusCode: 200,
                                       httpVersion: nil,
                                       headerFields: nil)
```
이곳에서 저희가 궁금했던게 어떤 곳에서는 httpVersion를 명시한 곳도 있고 이렇게 nil로 한곳도 있는데, 이게 지정이 필요하지 않는 곳인가요? 또한 만약 httpVersion이 1.1이랑 2가 있다면 서로 통신이 불가능하거나 수신이 안될 수 있나요? 
그리고 headerFields 부분이 오는 곳이 응답의 헤더필드를 말하는 것 같은데, GET은 body는 없지만 헤더는 요청과 응답에 포함되는 것으로 아는데, headerFields가 nil로 하더라도 되는 이유가 궁금하네요..! 혹시 저희가 header에 어떤 것도 안넣은 것일까요? GET으로 보낸다고는 한거같은데 왜 응답에는 nil로 처리한것인지 궁금합니다!

2022-05-12 08:09 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Network/API.swift
> +    static let healthCheckerPath = "/healthChecker"
이런식으로 구조를 가져가면 api가 생성 될 때 마다 라인이 길어지지 않나요?
api를 가지는 protocol을 가지고 있으면 좋을거같아요

2022-05-12 08:56 UTC, jungseungyeo requested changes
에디, 마리솔 고생하셨습니다. 

🧐 고민한점 & 해결방법

## 📌 1. URL을 어떻게 조합해서 만들어줘야 할까?

`해당 기능을 구현하는데 잘 적용이 되는 구조인거 같아요. 하지만 설계상 문제가 될 여지가 있는 부분같아요.
1. api 갯수가 많아 질 수록 라인수는 늘어나게 된다.
2. Method의 형태로 api url이 달라질수없다.

이러한 문제가 있어요. 이 문제는 protocol을 사용해서 추상화를 하여 해결하면 좋을거같아요.
`

##❓ 궁금한점

### 📌 1. dataTask 속 error의 에러처리 표현

`보여주신 부분에서는 error가 우리가 설정한 에러가 아닌 알 수 없는 에러가 존재하는 경우로 판단하면 좋습니다. 즉 서버에서 내려주는 에러의 형태가 되는거죠, 우리가 정의하지 에러인경우는 해당 에러를 그대로 노출하면 될거같아요. 특별하게 무엇을 파싱하거나 그럴 수 있는 형태가 아니기 때문에 그대로 노출 하는 형태를 많이 합니다.
따라서 정의 한 NetworkError에서 case error ->  case error(Error) 로 변경을 하여 에러 객체를 담을 수 있게 수정 후 전달 하면 좋을거같습니다. ㅎㅎ
`

### 📌 2. init Deprecated

`해당 경고는 iOS 13이전에는 URLSession 객체가 싱글톤이 아니여서 사용이 가능했지만 13이상부터는 싱글톤이 되면서 사용을 권하지 않아요. 

이 부분을 그래서 의존성 주입으로 해결을 할 수 있어요.  URLSessionProtocol를 보시면 URLSession에 의존성을 넣어주었죠? 이렇게 되면 우리가 정의한 URLSessionProtocol를 넣어줄 수 있게 되는거죠. 

위와 같은 방법으로 URLSessionDataTask를 상속 받는게 아니라 프로토콜을 주입하여 해결하면 될 거같아요. 

이렇게 설명을 해도 잘 이해가 안될거같아요. 괜찮은 시간 알려주시면 코드로 보여드릴겠습니다.

`


### 📌 3. test code에서 강제언래핑 사용가능여부

`넵 저도 어차피 강제 언래핑을 해도 된다고 생각해요, 크래시가 안나는것은 테스트의 실패이기 떄문에 저도 강제언래핑으로 많이 사용하고 있습니다.`

### 📌 4. HTTPURLResponse 에 대한 궁금증

`어떤 질문인지 잘 이해가 안되는거 같아요..ㅠㅠ `

![image](https://user-images.githubusercontent.com/32052386/168032156-dac541c5-caff-4a7f-8ec3-9c337101701d.png)

`문서를 보면 headerFields A dictionary representing the header keys and values of the server response. -> headerFields 서버 응답의 헤더 키와 값을 나타내는 사전입니다. 이라고 설명을 하고 있어요. 이 값을 dataTask를 수행후 전달 되는 값을 의미해요. `

에디, 마리솔 고생하셨습니다. 코멘트를 단 부분 수정해주시고, 시간 알려주시면 한번 만나서 질문 주신 내용 보여드리겠습니다 :) 수고하셨습니다.

2022-05-12 08:56 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Network/API.swift
> +    func generateURL() -> String {
generateURL()를 보면 RESTAPI를 형태에서 get이라는 method만 지원을 하고 있어요. RESTAPI의 형태와 맞게 method를 보고 형태가 정해지면 좋을거같아요.

2022-05-12 08:56 UTC, jungseungyeo commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    func test_Product_dummy데이터의_totalCount과_예상값이_일치한다() {
예상값이 일치라기보다는 값 몇이랑 일치한다라고 해주면 더욱 이해하기가 편할거같습니다.

2022-05-12 08:56 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Network/StubURLSession.swift
> +final class StubURLSessionDataTask: URLSessionDataTask {
이 값은 테스트 할 때 사용하는 객체라서 여기보다는 테스트 타켓으로 설정하면 좋을거같아요. 
파일도 여기보다는 OpenMarketTests 밑에 있어야 될거같아요.

2022-05-12 08:56 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Network/StubURLSession.swift
> +final class StubURLSession: URLSessionProtocol {
이 객체도 테스트에서 사용하는 객체인거 같아요. 타켓 설정이 test로 변경하고 파일 위치를 테스트하는 부분으로 옮기면 좋을거같아요.

2022-05-12 08:56 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Network/URLSessionProtocol.swift
> +extension URLSession: URLSessionProtocol { }
의존성을 주는 부분 너무 좋습니다 ㅎㅎ

2022-05-13 08:09 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Network/API.swift
> +    static let healthCheckerPath = "/healthChecker"
```swift
enum HTTPMethod: String {
    case get = "GET"
    case post = "POST"
    case put = "PUT"
    case delete = "DELETE"
}

protocol APIable {
    var hostAPI: String { get }
    var path: String { get }
    var param: [String: String]? { get }
    var method: HTTPMethod { get }
}
```
이렇게 프로토콜을 사용해서 재사용성을 높일 수 있도록 했습니다!

2022-05-13 08:09 UTC, marisol-develop commented on OpenMarket/OpenMarket/Network/StubURLSession.swift
> +final class StubURLSessionDataTask: URLSessionDataTask {
테스트 쪽으로 파일 이동했습니다!😃

2022-05-13 08:09 UTC, marisol-develop commented on OpenMarket/OpenMarket/Network/StubURLSession.swift
> +final class StubURLSession: URLSessionProtocol {
이것도 같이 이동 시켰습니다!

2022-05-13 08:10 UTC, marisol-develop commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    func test_Product_dummy데이터의_totalCount과_예상값이_일치한다() {
넵 예상값들을 숫자로 넣어주었습니다 ㅎㅎ

2022-05-13 08:10 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Network/API.swift
> +    func generateURL() -> String {
위에 제안해주신 방식으로 프로토콜을 나눈 다음, 각각의 HTTP method에 따라 분리구현이 가능하도록 수정했습니다. 현재에는 GET방식 뿐이라 나머지 부분은 비워둔채로 두었습니다!

```swift
        switch api.method {
        case .get:
            session.dataTask(with: api) { response in
                guard response.error == nil else {
                    completion(.failure(.error))
                    return
                }
                
                guard successRange.contains(response.statusCode) else {
                    completion(.failure(.statusCode))
                    return
                }
                
                guard let data = response.data else {
                    completion(.failure(.data))
                    return
                }
                
                do {
                    let decoder = JSONDecoder()
                    let result = try decoder.decode(T.self, from: data)
                    completion(.success(result))
                } catch {
                    completion(.failure(.decode))
                }
            }       
        case .post:
            print("post")
        case .put:
            print("put")
        case .delete:
            print("delete")
        }
```

2022-05-13 08:44 UTC, marisol-develop commented
안녕하세요 린생! @jungseungyeo 
STEP1 수정해보았습니다!🙇‍♀️

어제 시간내셔서 의존성 주입과 추상화에 대한 자세한 설명해주셔서 정말 감사드립니다.🙏
열심히 듣긴했는데 내용이 어려워서, 저희가 이해한 방향이 맞는지 여쭤보고 싶습니다!

URLSessionDataTask의 init 기능이 deprecated 되어, 이를 사용할 수 없는데
URLSession의 dataTask에서 리턴할 때 의존을 하고 있었습니다.

그렇기 때문에 URLSession에서 DataTask를 리턴하고 그 DataTask를 execute에서 .resume()해주는 것이 아니라,
리턴값이 없는 `dataTask(with api: APIable, completionHandler: @escaping DataTaskCompletionHandler)` 메서드를 명시한 프로토콜을 채택해서 위 메서드에서는 파라미터로 받은 api로 url을 만들어주고, 실제 dataTask 메서드에서 그 url로 DataTask를 생성하고 .resume()까지 해주도록 변경했습니다. 이를 통해 deprecated 된 URLSessionDataTask의 init을 사용하지 않을 수 있었습니다.

이런 흐름이 맞는지, 저희가 혹시 제대로 이해하지 못한 부분이 있는지, 아니면 추상화가 더 필요한 부분이 있을지 말씀해주시면 감사하겠습니다!🙇‍♀️

---

### STEP 1 추가 코멘트 

### 📝 구조 설명

- `URLSessionProtocol`: URLSession과 StubURLSession에 의존성을 주입해주기 위한 프로토콜

- `URLSession` : dataTask 메서드를 실행하여 URLSessionDataTask를 생성하고 resume하여 서버로부터 data, statusCode, error를 전달받아서 NetworkManager에게 전달하는 객체

- `APIable`: hostAPI와 path, parameter, HTTPMethod를 갖는 프로토콜

- `StubURLSession`:URLSessionProtocol을 활용하여 data, statusCode, error를 포함한 가짜 response를 만들어서 NetworkManager에게 전달하는 객체

- `NetworkManager`: URLSession으로부터 받아온 reponse를 HTTPmethod방식에 따라 구분하여 error, statuscode, data를 확인 후 data를 디코더하여 그 값을 내보내는 객체

---

### ❓ 추가 질문

#### 📌 get 이외에 post/put/delete의 처리

NetworkManager의 execute 메서드에서 URLSession으로부터 받은 HTTPMethod 정보에 따라 다르게 처리해주기 위해서 switch문을 작성했는데요, post/put/delete에 대해서는 처리가 어떻게 달라져야 할지 아직 몰라서 구현을 해두지 않은 상태입니다🥲 이 부분은 STEP2에서 구현을 해도 될까요??

#### 📌 StubDataTask 제거
저희 생각에 이 구조체는 초기화도 사용 못하고 DataTaskCompletionHandler에서 저희가 만들어준 Custom Response 타입을 사용하고 실제로도 이를 활용해서 데이터를 받도록 했기 때문에 StubDataTask는 불필요하다고 생각해서 없앴습니다. 그리고 이를 테스트 사용 시에도 잘 되는 것은 확인했는데 이게 적절한 구조와 설계였는지 궁금합니다!!

2022-05-13 11:02 UTC, jungseungyeo approved these changes
에디, 마리솔 고생하셨습니다.

구조를 보면서 좋아졌다고 생각이 듭니다 :) 

### 📌 get 이외에 post/put/delete의 처리

`이것은 request 형태의 대한 이해도와 설계의 익숙함이 아직 부족하여 발생하는 원인인거 같습니다. 사실 두 형태는 크게 다르지는 않지만 delete, put, post와 같은 메소드는 body에 담기게 되고 decode형태가 json 형태로 전달이 됩니다. 이러한 형태는 URLRequest에서 body에 포함하면 될거 같습니다 ㅎㅎ`

`body의 담기는 형태와 url의 담기는 형태가 추상화를 시키면 좋겠죠? 3가지는 body에 담는 역할을 하는 부분을 만들어서 해결해보면 좋을거같아요 ㅎㅎ`

### 📌 StubDataTask 제거

`넵 좋습니다 하지만 실제 api를 쏘게 되면 변경 될 요지가 있어는 보여요 하지만 이번 스텝에서 개선 할 부분은 아니거 같아 이렇게 이번 스텝을 마무리하고 실제 api를 호출하면 더 보안해보면 좋을거같습니다. `

에디 마리솔 고생하셨습니다. 한주동안 많은 고민한게 느껴지네요 다음 스텝에서 현재 하지 못한 post,put, delete까지 같이 마무리 부탁드립니다 :) 고생하셨습니다.

2022-05-13 11:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Network/APIable.swift
> +    var method: HTTPMethod { get }
제가 github에 있는거라 똑같아졌네요 ㅎㅎ.. 그래도 너무 좋습니다 어제 이야기 한 부분 처럼 잘 이해한거 같아 좋네요

2022-05-13 11:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +            print("delete")
막상 구성은 했는데 어렵지? 다음 스텝에서 한 번 더 고민하고 적용하면 좋을거같네요 ㅎㅎ

2022-05-13 11:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Network/URLSessionProtocol.swift
> +    func dataTask(with api: APIable, completionHandler: @escaping DataTaskCompletionHandler) {
좋습니다 이것이 solid 원칙에서 LSP를 지키고, OCP를 지키는 원리라고 이해하면 더욱 좋을거같습니다 :)

2022-05-13 11:03 UTC, merged