오픈 마켓 [STEP 1] 두기, minseong
yagom-academy/ios-open-market pull request #143
Opened 2022-05-12 04:18 UTC by doogie97

@jungseungyeo
안녕하세요! 린생! STEP4 완료해서 PR보냅니다!
API통신이 처음이라서 객체분리도 어떻게 해야할지 모르겠고 공부하면서 사용을 하다보니 부족한 부분이 많습니다
사소한 부분이라도 조언해주시면 정말 감사하겠습니다 린생!
잘부탁드립니다!😁😄

## 고민한 점

#### 1. test만을를 위해 session을 var로 선언해야할까요?
![](https://i.imgur.com/4Mv0hM8.png)

실제 사용에 있어서 NetworkHandler가 선언된 이후 session은 변경될 일이 없다고 생각하는데 test만을 위해서 var로 선언하는 것이 맞는건지... 여쭤보고 싶습니다!

#### 2. testfile에서 target Membership을 통해 코드에 접근하는 것과 @testable을 통해 접근하는 것의 차이점이 있을까요??
![](https://i.imgur.com/Ukutc1g.png)
- 테스트 파일들과 본 프로젝트를 확실하게 구분하려면 오픈마켓의 타겟을 추가하는건 아닌 것 같다는 생각이 들어 @testable을 통해 접근하는 방법이 좋다고 생각했습니다
>린생의 의견이 궁금합니다.

#### 3. URLSessionDataTask의 init()이 deprecated가 떠서 대체방법을 찾고자 했습니다
![](https://i.imgur.com/GNayw6P.png)

그러나 잘 찾지 못하였습니다. 물론 deprecated가 뜬 상태로도 초기화가 잘 되긴 하지만 이 방법 외에 URLSessionDataTask의 초기화를 하는 방법이 궁금합니다.

#### 4. 따옴표따옴표??
![](https://i.imgur.com/x8cbHUI.png)
서버에서 String을 받아 올 때 위와 같이 `""OK""` 이런식으로 받아오게 되는데 `""` 를처리해주기 위해 로직`trimmingCharacters(in: ["\""])`을 추가해 주었는데 원래 이렇게 테이터가 들어오는지, 원래 이렇다면 위 처럼 제거해서 비교하는게 올바른 방법인지 궁금합니다.

#### 5. 파일path를 탐색 할 때 파일명이 빈 문자열이면 형태가 맞는걸 추적하는지 궁금합니다
![](https://i.imgur.com/pEY7lXh.png)
위와 같은 로직을 통해 path를 탐색 할 때

![](https://i.imgur.com/JNvo0lx.png)
이렇게 빈 문자열을 넣어줘도 추가된 json파일을 잘 추적하였습니다(json파일 비교해도 저 값이 맞음)

![](https://i.imgur.com/5gKhI6w.png)

근데 다른 json파일 추가해주면 정확한 이름이 할당되기 전까지 또 추적을 못했습니다

저희가 추측하기로는 파일의 타입을 "json"으로 지정을 해줬고 "json"파일이 하나이기 때문에 자동으로 추적을 해준건가? 하는 생각은 하였으나 실제로도 그런지 궁급합니다.

2022-05-12 11:20 UTC, jungseungyeo requested changes
# 고민한 점

### 1. test만을를 위해 session을 var로 선언해야할까요?

`코멘트를 달았지만 안됩니다. 이 부분은 추상화를 하고 외부에서 데이터 은닉화를 위반하여 매우 위험한 코드입니다. 의존성 주입을 하는 방식으로 해결하면 좋을거같습니다.`

2. testfile에서 target Membership을 통해 코드에 접근하는 것과 https://github.com/testable을 통해 접근하는 것의 차이점이 있을까요??

`target Membership로 접근하게 되면 앱이 실행 할 때 (실제 동작) 테스트 객체도 같이 빌드 시간에 포함이 됩니다. 따라서 좋은 방법은 아니예요, @testable을 통해서 가져오는 방법이 좋습니다. `

3. URLSessionDataTask의 init()이 deprecated가 떠서 대체방법을 찾고자 했습니다

`맞아요 이 부분 iOS13부터 사용을 못하게 되었습니다. 그래서 다른 방식으로 해결을 해야 합니다.
우리가 필요한 것은 결과 값이죠, 결곽값을 받는 protocol을 설정 후 사용하고 URLSession에 주입 후 주입하는 방식으로 해결하면 좋을거같습니다. 

이 부분은 아무래도 글로 하면 매우 어려울거같아 시간 괜찮을때 제가 코드 레벨에서 설명 한 번 해드리겠습니다 :) 
`

### 4. 따옴표따옴표??

`흠... 정확히 어떤 건지 모르곘네요.. 한번 더 설명 부탁드립니다 .`

### 5. 파일path를 탐색 할 때 파일명이 빈 문자열이면 형태가 맞는걸 추적하는지 궁금합니다

`흠... 그렇지 않을거같아요. 추측이지만 Bundle 문제일 확률이 있을거같아요, 아니면 타켓 설정이 안되어 있다던지.. 아니면 경로가 설정이 안되어 있는 거라고 추측이 됩니다. 하나만 있을때 동작이 되는 건 아닙니다.`

두기, 민서 코멘트를 단 거 처럼 몇가지 수정 사항이 있습니다. 코멘트 달고 수정해주시면 좋을거같습니다.
혹시 궁금한 점이 있으면 언제든지 물어봐주세요 :)

2022-05-12 11:20 UTC, jungseungyeo commented on OpenMarket/NetworkHandlerTest/NetworkHandlerTest.swift
> +    func test_getData호출시_데이터를잘가져오는지() {
한글로 작성 한 부분 너무 좋습니다 

몇가지 수정이 있으면 좋을거같아요.
한글도 give, when, then 패턴을 지켜서 작성하면 좋을거같습니다.
`예를 들어 URLSession이 생송되고(give), getData를 호출하여 DataDocoder가 성공하면(when), id값이 20이 된다(then).` 와 같이 매우 구체적이면서 실행해야되는 부분을 표현해주면 좋을거같습니다.

2022-05-12 11:20 UTC, jungseungyeo commented on OpenMarket/NetworkHandlerTest/NetworkHandlerTest.swift
> +                let _ = try DataDecoder.decodeItemPage(data: data)
실패의 경우는 반드시 실패를 알려주어야 됩니다. try에서 error를 발생하지 못했다면 그냥 통과하고 성공으로 표시가 될거예요 try 밑에 XCTFail()를 추가해서 의도 한 코드가 진행 안 된 경우 실패를 알려주세요 :)

2022-05-12 11:20 UTC, jungseungyeo commented on OpenMarket/NetworkHandlerTest/TestDouble/StubURLSession.swift
> +    let dummyData: DummyData
stub객체라서 은닉화를 안한건가요?

2022-05-12 11:20 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/DataDecoder.swift
> +    static func decodeItemPage(data: Result<Data, APIError>) throws -> ItemPage {
밑의 static func decodeItemDetail(data: Result<Data, APIError>) throws -> ItemDetail 함수와 크게 다르지 않는거 같아요 제네릭을 활용해서 두 함수를 하나의 함수로 만들 수 있을거같습니다.

위의 decodeHealthCheck 함수도 동일하군요

2022-05-12 11:20 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/NetworkHandler.swift
> +    var session: URLSessionProtocol = URLSession(configuration: .default)
객체형 프로그램에서 은닉화를 지켜주세요 :)

2022-05-12 11:20 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/NetworkHandler.swift
> +    func getData(pathString: String, completionHandler: @escaping (Result<Data, APIError>) -> Void) {
getdat라는 함수 명으로는 REST API에서 method get만 지원하고 있어요, 이렇게 코드가 작성되면 각 method마다 함수가 생길거같습니다.

method와 상관없이 추상화가 가능한 구조면 좋을거같습니다. 

추상화를 할려면 protocol을 활용하면 좋은데요. api를 구성해야하는 protocol을 요소를 정의하고 채택하여 주입하는 방식으로 구현하면 될거같습니다. :)

2022-05-12 11:20 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/Protocol/ItemProtocol.swift
> +protocol ItemAble {
itemable이라는 프로토콜의 의도는 무엇인가요?

2022-05-12 11:20 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/Protocol/URLSessionProtocol.swift
> +extension URLSession: URLSessionProtocol {}
의존성 주입하는 부분이 좋네요 ㅎㅎ

2022-05-12 11:20 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/NetworkHandler.swift
> +    var session: URLSessionProtocol = URLSession(configuration: .default)
이 변수가 노출되어 언제 변경이 되어도 이상 할 게 없는 변수가 되어버리는거 같습니다. 

테스트코드에서 stub를 변경하는 부분 때문으로 생각이 되지만 이건 초기화 혹은 의존성을 주입하는 방식으로 해결하면 좋을거같습니다.
객체지향의 은닉화를 위반하여 작성하면 좋지 않습니다.

2022-05-13 01:55 UTC, doogie97 commented on OpenMarket/NetworkHandlerTest/TestDouble/StubURLSession.swift
> +    let dummyData: DummyData
stub객체라서 크게 신경쓰지 않았던 것 같습니다
말씀해주신 대로 은닉화 진행 하였습니다!

2022-05-13 01:59 UTC, doogie97 commented on OpenMarket/OpenMarket/Model/Protocol/ItemProtocol.swift
> +protocol ItemAble {
itemDetail에 있는 정보들은 page내에 있는 item에 있는 정보를 모두 갖고 있기에 모델을 만듦에 있어 편리하려고 생성하였습니다

2022-05-13 03:09 UTC, doogie97 commented on OpenMarket/OpenMarket/Model/DataDecoder.swift
> +    static func decodeItemPage(data: Result<Data, APIError>) throws -> ItemPage {
```swift
    static func decode<T: Codable>(data: Result<Data, APIError>, dataType: T.Type) throws -> T {
        switch data {
        case .success(let data):
            do {
                let itemPage = try JSONDecoder().decode(dataType, from: data)
                return itemPage
            } catch {
                throw APIError.decodeError
            }
        case .failure(let error):
            throw error
        }
    }
```
말씀하신 대로 제네릭을 활용해 타입을 매개변수로 받아서 하나의 함수로 변경하였습니다!

(이 과정에서 String뿐만 아니라 Int나 Doubel 같은 타입들이 Decodable과 Encodable을 이미 채택하고 있는 것을 알게되었습니다!)

2022-05-13 03:25 UTC, Minseong-yagom commented on OpenMarket/OpenMarket/Model/NetworkHandler.swift
> +    var session: URLSessionProtocol = URLSession(configuration: .default)
접근제어자 변경해주고 초기화를 통해 주입해주는 방식으로 수정하였습니다!

2022-05-16 03:30 UTC, doogie97 commented on OpenMarket/OpenMarket/Model/NetworkHandler.swift
> +    func getData(pathString: String, completionHandler: @escaping (Result<Data, APIError>) -> Void) {
HTTP Method별로 분기를 나눠 처리를 해줄 수 있는 로직으로 변경하였습니다

다만 해당 메서드 네이밍의 경우 request와 response를 동시에 나타낼 수 있는 naming이 생각이 나지 않아 일단은 communicate라는 이름을 지어주긴 했는데 더 적합한 이름이 어떤게 있을까요?

2022-05-16 06:31 UTC, jungseungyeo approved these changes
두기, 민성 많은 내용을 수정하셨네요 ㅎㅎ 
고생많으셨습니다.

코멘트에서 method의 관련된 코멘트를 추가하였는데요. 부분은 다음 스텝에서 이어지는 느낌이라 다음 스텝에서 고민하고 적용해주시면 좋을거같습니다 
고생하셨습니다.

2022-05-16 06:31 UTC, jungseungyeo commented on OpenMarket/NetworkHandlerTest/TestDouble/StubURLSession.swift
>          let sessionDataTask = StubURLSessionDataTask()
이놈이 존재하면 warning이 발생할 수 밖에 없어요. 다른 방법으로 대체하면 좋을거같습니다 :) 

이 부분은 다음 스텝에서 하면 좋을거같아요 ㅎㅎ

2022-05-16 06:31 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/NetworkHandler.swift
> +        request.httpMethod = httpMethod.string
method는 여기 뿐만 아니라 URLRequest 생성시 url에 파라미터를 담기 수 있는 형태인지 body에 담겨야 하는지도 결정해주어야 합니다 .ㅎㅎ 이 부분은 다음스템에서 적용 부탁드립니다 :)

2022-05-16 06:31 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/NetworkHandler.swift
> +    private let baseURL = "https://market-training.yagom-academy.kr/"
baseURL이 여기 있고 은닉화 되어 있네요 ㅎㅎ 너무 좋습니다

2022-05-16 06:31 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/NetworkHandler.swift
> +    func getData(pathString: String, completionHandler: @escaping (Result<Data, APIError>) -> Void) {
디코에서 이야기 한 거 처럼 request로 함수명을 하여 viewcontroller가 요청을 하고 completionHandler -> reponse가 된다면 괜찮을거라는 생각이 듭니다

2022-05-16 06:31 UTC, merged