오픈 마켓 [STEP 1] Taeangel, Malrang
yagom-academy/ios-open-market pull request #144
Opened 2022-05-12 13:36 UTC by malrang-malrang

@stevenkim18 안녕하세요 스티븐!

PR 날짜를 넉넉히 잡았다고 생각했는데....요...
프로젝트에서 필요한 개념들을 이해하는데 시간도 오래걸리고 너무어려웠습니다 🥲
좀더 공부가 필요할것같습니다!
공부하면 좋을 개념들 키워드를 많이 알려주시면 감사하겠습니다! 🤭
STEP1 PR 잘부탁드리겠습니다! 🥳

## 조언을 받고싶은점
### 1. MockURLSessionDataTask init 관련 Error
```swift
class MockURLSessionDataTask: URLSessionDataTask {
    private let closure: () -> Void

    init(closure: @escaping () -> Void) {
        self.closure = closure
    }

    override func resume() {
        closure()
    }
}
```
에서 'init()' was deprecated in iOS 13.0: Please use -[NSURLSession dataTaskWithRequest:] or other NSURLSession methods to create instances
라는 오류 문구가 나오는데 어떤방법 키워드를 공부해야 해결할수있을지 궁금합니다!

### 2. 테스트를 하기위한 Mock 객체에서의 강제언래핑
```swift
func dataTask(
        with urlRequest: URLRequest,
        completionHandler: @escaping DataTaskCompletionHandler
    ) -> URLSessionDataTask {
        let successResponse = HTTPURLResponse(
            url: urlRequest.url!,
            statusCode: 200, httpVersion: "",
            headerFields: nil
        )

```
테스트를 위한 목객체를 만들었는데 목객체에도 강제언래핑을 지양해야하는지 궁금합니다!

2022-05-13 18:01 UTC, stevenkim18 requested changes

2022-05-13 18:01 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Model/ProductCatalog.swift
> +struct ProductCatalog: Codable {
개인적인 의견이지만 Catalog 가 목록이라는 단어가 있긴 하지만..

`ProductList`가 조금 더 직관적인 네이밍이지 않을까 싶네요 ㅎㅎ 어떻게 생각하시나요? 아니면 더 좋은 이름이 있을까요?

2022-05-13 18:01 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Model/ProductCatalog.swift
> +struct ProductCatalog: Codable {
이 모델이 Encoding(객체 -> json)도 하는 모델인가요? 

꼭 Codable을 채택해야 될까요?

2022-05-13 18:01 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Model/ProductCatalog.swift
> +        case itemspPerPage = "items_per_page"
오타가 있네요 ㅎㅎ

2022-05-13 18:01 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Model/ProductCatalog.swift
> +        case prevPage = "has_prev"
lastpage가 정수라서 nextpage, prevpage도 정수형 처럼 느껴집니다.

원래 json 값 처럼 has가 들어가야 더 bool 타입 처럼 느껴지는데.. 어떻게 생각하시나요?

2022-05-13 18:01 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Model/Product.swift
> +}
codingKeys 사용하신 것은 매우 잘하셨습니다!!!

jsonDecoder 프로퍼티 중에서 스네이크케이스에서 카멜케이스로 바꿔주는 기능이 있습니다!! 한번 찾아보시겠어요?

그렇게 되면 enum 타입은 모두 지워도 제대로 동작합니다!
(엄청 중요한건 아니니 30분 이상 시간은 사용하지 마시고 못찾으시면 여쩌봐주세요!!)

2022-05-13 18:01 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Network/Endpoint.swift
> +//  API.swift
파일 이름과 타입이름이 다르네요!

2022-05-13 18:01 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Model/ProductCatalog.swift
> +//  NetWork.swift
여기도 파일이름과 타입이름이 다르네요 ㅎㅎ

2022-05-13 18:01 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Model/Product.swift
> +//  Products.swift
여기도.. ㅎㅎ

2022-05-13 18:01 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Network/URLSessionProtocol.swift
> +typealias DataTaskCompletionHandler = (Data?, URLResponse?, Error?) -> Void
typealias를 사용하셨군요!! 잘하셨습니다!!!

2022-05-13 18:01 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Network/URLSessionProvider.swift
> +    func getData(
Swift API 디자인 가이드에서 get은 어떨 때 함수명에 쓰일까요? 

조금 더 좋은 네이밍은 없을까요?

2022-05-13 18:01 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Network/URLSessionProvider.swift
> +    }
함수가 너무 깁니다. 

여러 함수로 나눠볼까요?

2022-05-13 18:01 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Network/URLSessionProvider.swift
> +            }
guard으로 하신 것은 매우 보기 깔끔하네요  👍

2022-05-13 18:01 UTC, stevenkim18 commented on OpenMarket/OpenMarket/URLHealthcheckerTests/URLHealthcheckerTests.swift
> +}
실패하는 테스트 케이스는 없을까요?

2022-05-13 18:01 UTC, stevenkim18 commented on OpenMarket/OpenMarket/URLProductCatalogTests/URLProductCatalogTests.swift
> +        sut.getData(from: .productList(page: 2, itemsPerPage: 10)) { result in
테스트 이름은 `fetchData`인데 함수이름은 `getData` 네요!

2022-05-13 18:01 UTC, stevenkim18 commented on OpenMarket/OpenMarket/URLProductTests/URLProductTests.swift
> +}
이 테스트 케이스만 보고 2085번을 요청하면 id가 14가 온다가 어떻게 성공하는 케이스 인줄 알 수 있나요?

테스트를 조금 더 일반화하거나 테스트 이름만 봐도 이제 어떤 테스트인지 대략적으로 감이 와야 합니다!!

2022-05-13 18:01 UTC, stevenkim18 commented on OpenMarket/OpenMarket/URLProductTests/URLProductTests.swift
> +}
그리고 Error 케이스가 6개인데 실패하는 테스트는 한개도 없네요 🥲

코드 커버리지를 측정해보지는 않았지만 아마 낮게 나올 것 같습니다.
실패하는 케이스도 만들어주세요!!

2022-05-13 18:10 UTC, stevenkim18 commented
태엔젤, 말랑 스탭1 하시느라 너무 고생많으셨어요!!
질문은 언제든지 환영입니다!!! 많이 질문해주시고 저한테 얻어갈 것들 많이 가져가세요!!

<br>

> 1. MockURLSessionDataTask init 관련 Error

네 맞습니다 ㅜㅜ `URLProtocol`을 활용해서 mock테스트 하는 것을 찾아보세요!!
<br>

>  2. 테스트를 하기위한 Mock 객체에서의 강제언래핑

강제 언레핑을 지양하기는 해야하지만 위에서 예외처리를 잘 해주었고 절대로 nil이 날 경우가 아니라면 저는 사용해도 괜찮다고 생각해요.
`urlRequest.url`이 언제 nil이 되는 경우를 알아보세요. 매개변수로 이상한 url만 넘겨주지 않는다면 앱이 크래쉬 날일은 없습니다.
제가 알기로는 빈 문자열을 URL에 넣으면 nil되는 걸로 알고 있습니다. `URLRequest` 에서 url을 빼는 것은 조금 더 찾아보셔야할 것 같아요

2022-05-14 03:16 UTC, malrang-malrang commented on OpenMarket/OpenMarket/Model/ProductCatalog.swift
> +        case itemspPerPage = "items_per_page"
자잘한 실수가 많았군요 ㅠㅠㅠ 꼼꼼히 검토하도록 하겠습니다!!🥲

2022-05-14 03:16 UTC, malrang-malrang commented on OpenMarket/OpenMarket/Model/ProductCatalog.swift
> +struct ProductCatalog: Codable {
그렇군요! 디코딩만 가능하면되기 때문에 Decodable 을 채택하는것이 더 좋을것 같습니다!

2022-05-14 03:17 UTC, malrang-malrang commented on OpenMarket/OpenMarket/Model/ProductCatalog.swift
> +struct ProductCatalog: Codable {
게속...productList 와 productCatalog 를 고민했습니다..!! 
아무래도 List 가 좀더 직관적일것 같습니다!! ㅎㅎ

2022-05-14 03:44 UTC, malrang-malrang commented on OpenMarket/OpenMarket/Model/Product.swift
> +}
JsonDecoder 프로퍼티중 keyDecodingStrategy 요녀석이 있는것은 알고있었으나 사용해본적이 없었습니다!
이번 기회에 활용해보았는데 enum CodingKeys 를 제거해도 제대로 파싱 되는것을 확인했습니다! 😁
적용해서 수정하였습니다! :)

2022-05-14 03:55 UTC, Taeangel commented on OpenMarket/OpenMarket/Model/ProductCatalog.swift
> +        case prevPage = "has_prev"
```
    let hasNextPage: Bool?
    let hasPrevPage: Bool?

```
로 네이밍 변경하였습니다.

2022-05-14 03:55 UTC, Taeangel commented on OpenMarket/OpenMarket/Network/Endpoint.swift
> +//  API.swift
이름 수정했습니다!

2022-05-14 03:55 UTC, Taeangel commented on OpenMarket/OpenMarket/Model/ProductCatalog.swift
> +//  NetWork.swift
ㅠㅠ 네

2022-05-14 03:56 UTC, Taeangel commented on OpenMarket/OpenMarket/Model/Product.swift
> +//  Products.swift
ㅠㅠ네 수정했습니다

2022-05-14 04:40 UTC, malrang-malrang commented on OpenMarket/OpenMarket/Network/URLSessionProvider.swift
> +    func getData(
get 메서드는 값을 얻어 올때 사용됩니다!
하지만 결과 값까지 반환되기 때문에 fatch 가 더 적절해보이기에 수정하였습니다! 😄

2022-05-14 04:41 UTC, malrang-malrang commented on OpenMarket/OpenMarket/Network/URLSessionProvider.swift
> +    }
네! 해당 함수 URLRequest 를 만들어주는 부분과 
디코딩 하는 부분을 따로 분리 하였습니다! 😁

2022-05-14 04:49 UTC, malrang-malrang commented on OpenMarket/OpenMarket/URLProductCatalogTests/URLProductCatalogTests.swift
> +        sut.getData(from: .productList(page: 2, itemsPerPage: 10)) { result in
앗..! 테스트 코드에서 변경하는것을 체크하지 못했습니다 ㅠ 
수정하였습니다! :)

2022-05-14 05:12 UTC, Taeangel commented on OpenMarket/OpenMarket/URLProductTests/URLProductTests.swift
> +}
product의 값은 항상 같은 값을 테스트 할 수 없어 product 테스트는 삭제하였습니다.

2022-05-15 10:21 UTC, malrang-malrang commented on OpenMarket/OpenMarket/URLProductTests/URLProductTests.swift
> +}
해당 부분 MockURLSession 에 flag 를 두어 flag 가 true 라면 조건에 통과하는 satusCode 200 을 주고 false 라면 satusCode 400 을 주도록 변경하여 StatusCodeError 를 테스트하는 테스트 함수를 구현해두었습니다! 

조언해주셔 감사합니다 ! 😁

2022-05-16 00:44 UTC, stevenkim18 commented on OpenMarket/OpenMarket/URLProductTests/URLProductTests.swift
> +}
URLProtocol 을 사용하면 모든 애러 케이스에 대한 테스트가 가능한 걸로 알고 있어요 ㅎㅎ

2022-05-17 00:08 UTC, stevenkim18 commented
수정하신 코드 잘 봤어요!!! 크게 문제되는 점 없어서 머지하겠습니다!!

다음 스탭에서 collectionview로 화면 한개 구현해보시고 이후에 테스트 등에 대해서 더 고민해주세요!!

고생하셨습니다!!!

2022-05-17 00:08 UTC, merged