오픈마켓 [STEP 2] Red, 마이노
yagom-academy/ios-open-market pull request #146
Opened 2022-05-17 09:16 UTC by Mino777

안녕하세요 엘림!! @lina0322
STEP2 PR 보내드립니다!!
잘부탁드립니다!! 🙇‍♂️🙇‍

## 고민한점 

### Modern CollectionView
CompositionalLayout과 DiffableDataSource + Snapshot을 활용하여 CollectionView를 구현하였습니다.
List의 경우 UICollectionLayoutListConfiguration을 사용하여 TableView를 대체할 수 있었지만, 해당 구조체의 경우 iOS 14 이상에서만 사용 가능하여 사용하지 않고 List를 구현하였습니다.

### 첫 데이터 로드에 대한 요구사항
`처음 목록을 로드할 때, 사용자에게 빈 화면만 보여주는 대신, 로드 중임을 알 수 있게 해주세요`
데이터를 로드하는 시간이 너무나도 짧아서, 해당 요구사항을 진행하려면 인위적으로 viewDidLoad()가 되는 경우 indicator를 시작하고, 1~2초 뒤에 request를 하여 성공하면 indicator를 정지하는 식으로 진행했어야 했습니다.
그래서 해당 부분의 경우 Image 부분에만 indicator를 사용하여 현재 Image가 로드 중인지 아닌지에 대한 확인이 가능하도록 구현하였습니다.

### Pagenation
API의 쿼리 파라미터 pageNumber를 사용하여 사용자가 한 페이지의 일정 콘텐츠까지 보았을 때 추가적으로 다음 페이지의 데이터를 끊김없이 볼 수 있도록 구현하였습니다.

### Cache
이미지의 경우 셀이 사용될때마다 매번 request를 해야하는 문제점이 있었습니다. 해당 문제를 해결하기 위해 메모리캐싱을 사용하여 캐싱된 이미지의 경우 request를 하지 않고 바로 캐시에 저장되어 있는 이미지를 사용하는 방법으로 해결하였습니다.
현재 ImageChcheManager가 APIProvider를 가지고있고, loadImage 라는 메서드로 직접 요청과 캐싱을 모두 하고있는데 이런 구조가 괜찮은 구조인지 궁금합니다!

### 셀을 바꾸는 것에 대한 비용
list 와 grid 를 변경할 때, 여러가지 방법을 생각했습니다. 
1. listCollectionView gridCollectionView 가 들어있는 뷰를 각각 만들고 segment 를 이용해서 ishidden 을 이용해서 뷰를 숨겼다 나타냈다 한다. 
    😄 우리가 생각한 장점 : 비용이 아주 적게 든다. 
    😞 우리가 생각한 단점 : 각 뷰간의 싱크가 맞지 않으므로 강제로 싱크를 맞춰주어야 한다.
    
2. 셀과 레이아웃 변경하기
    😄 우리가 생각한 장점 : 적당한 비용
    😞 우리가 생각한 단점 : 뷰를 다시 로드해야 한다. 
    
3. 하나의 collectionView layout 에서 오토레이아웃 변경하기 
    😄 우리가 생각한 장점 : 자연스럽고 예쁜 애니메이션이 자동으로 구현 됨.
    😞 우리가 생각한 단점 : 비용이 많이 든다. 오토레이아웃 충돌 가능성 높음.

이 방법들 중에 적당한 비용과 적당한 장점이 있는 2번째 방법을 선택해 구현해 주었습니다.
1번의 방법은 잘 쓰지 않는 방법이라고 들었는데 이유가 무엇인가요? 
저희가 생각한 장단점 들이 맞을까요?  

## 조언 받고 싶은 내용

### 애니메이션 효과 
저희의 경우 셀과 레이아웃 자체를 변경하기 때문에 애니메이션 효과를 줄 수 없었습니다. 
reload() 를 시도하기 때문에 list grid 를 이동할 때, 셀의 모양이 바뀐다는 느낌보다는 미세하게 셀들이 다시 그려진다는 느낌이 들었습니다. 물론 paging 과 caching 을 적용하고 있어서 아주 크게 바뀌는 느낌은 아니지만 미세하게 그런 것이 느껴졌습니다.
지금 상황에서 애니메이션을 주는 방법이 있는지 궁금합니다. 
아니면 애니메이션까지는 아니더라도 사용자가 느끼기에 reload() 되고 있지 않다라고 생각하게 끔 develope 할 수 있는 방법이 무엇이 있나요?

### 뷰의 constraints, attribute등의 쓰이는 매직 넘버 관리
View에서 쓰이는 매직 넘버들의 관리를 어떤식으로 해야할까요? 다 하나씩 Namespace로 각각 네이밍을 붙여서 관리를 해주는것이 맞는건지 궁금합니다!

### Data(contentsOf: ) 와 url session 의 차이점
야곰이 활동학습에서 이미지데이터를 받는 2가지 방식을 소개해 주셨습니다.
하나는 `Data(contentsOf: )` 을 통한 방식이고 나머니 하나는 `url session` 을 통한 방식이었습니다. 저희는 이미 구현해 놓은 `url session` 이 존재했기 때문에, 여기에 메서드를 추가하는 방식으로 구현했습니다. 
그런데 `Data(contentsOf: )` 를 사용한 방법과의 차이가 궁금합니다. 
저희가 시도해 보았을 때에는 기술 사이에 큰 차이는 느끼지 못했고, 정보를 찾지 못했습니다.😭

### alert 관리법
저희는 alert 는 자주 재사용이 일어나는 요소라고 생각되어서 Builder pattern 을 이용하여, `AlertProduct` 라는 객체와 `AlertBuilder` 클래스 `AlertBuilderable` 라는 프로토콜을 만들어서 관리해 주었습니다. 
재사용성도 높고, 메서드로 만들었을 떄, 파라미터를 많이 받아야해서 메서드가 길어지는 단점을 보완해 주는 것 같았습니다. 그런데 구현 해야하는 양은 적지 않아서 고민이 되었습니다. 
엘림은 alert 관리를 어떤 방식으로 하시는지 알고 싶습니다!

alert 자체는 ViewContoller 에서 띄우는 로직으로 작성하였는데요, 모델이나 View 에서 발생하게 되는 오류도 모두 ViewContoller 에 가져와서 띄우려고 하다보니 ViewContoller 에서 호출하지 않아도 되는 것도 ViewContoller 호출하는 일이 발생하는 것 같습니다.
사실 alert 가 UI 적인 요소이기 때문에 View 에서 띄워도 괜찮지 않나? 하는 생각도 듭니다. 
MVC 구조에 맞게 alert 를 관리하려면 어떻게 해야 하는 걸까요?

### URL Session 취소 
지난 PR 에서 엘림이 이야기 해주신 취소를 cancel() 메서드를 이용해서 구현하려고 하였습니다. 그런데 지금 프로젝트에서 어느 부분에서 취소 기능을 사용해야하는지 모르겠습니다. 😭😭😭
또 만약 취소 기능을 구현하게 된다면, 데이터가 저장되는 중인지, 이미 저장이 완료되었는지와 같은 상태를 알아야 하는데, 그렇게 되면 메모리에 데이터를 저장하게 됩니다. 이미지를 모델에 저장해서 가지고 있어도 되는 것이 맞나요? 조언 부탁 드립니다!

2022-05-19 12:51 UTC, lina0322 requested changes
두 분 반갑습니다! 오랜만인거같네요ㅎㅎ
이번 프로젝트가 아주 힘들었을텐데, 잘 해가고 있는 모습을 보니 기분이 좋네요!!
마지막까지 화이팅 해서 이번에도 많이많이 배워봅시다👊

---

### 1. 셀을 바꾸는것 

저는 사실 1번을 선호해서.... 왜 잘 쓰지 않는 방법이라고 했을까요?😅 제가 오히려 궁금하네요.
화려한 애니메이션을 원한다면 3번도 나쁘지 않을 것 같아요.
지금 구현하신 2번도 좋고요ㅎㅎ 정답은 없고, 회사마다 사람마다 선호하는게 다르고 상황따라 달라서 꼭 이게 더 좋아! 이렇게는 말하기 어려운거같아요 항상ㅎㅎ
그리고 2번과 3번중에 3번이 비용이 많이 든다고 하신 근거는 어떤걸까용??

### 2. 애니메이션
전혀 안느끼게 해주려면 위에서 1번 방식을 사용해야하지 않았을까용?
또, 애니메이션을 완전 주려면 3번을 사용했어야 했을것 같은데요ㅎㅎ..
요 부분에 있어서는 생각나는 아이디어가 없네요😓

### 3. Data(contentsOf: ) 와 url session
음, 일단 사용하면서 차이를 못느낀 이유는 이미지가 크지 않아서? 일수도있어요!!
고화질 바탕화면 주소를 받아보면.. 스크롤이 멈추는걸 느낄 수 있을 것 같네요~
검색해도 정보가 안나온다니 안타깝네여ㅠㅠ 혹시 이렇게 검색하면 어떨까요
`Data(contentsOf: ) 를 사용하면 안되는 이유` 
여기서도 원하는 답을 찾이 못한다면, 저에게 메세지 주세요~😆

### 4. alert
구조와 상관 없이 지금처럼 작업하시는 것 좋아보입니다! 
이런 패턴은 이렇게, 저런 패턴은 저렇게 하는 것들도 있지만
extension이나 protocol을 사용하는 것 처럼 어떤 패턴이든 상관없이 여러분이 편하고
재사용성이 좋게 만들고, 또 다른 사람들이 봤을때 이해가 잘 되는 코드면 훌륭하다고 생각해요
(그리고 좀 더 실력을 만들어서 메모리까지 고려를..!!)

### 5. URL Session 취소
아주 간단하고 당장 가능한 예를 들자면,
지금 cell 화면에서 사라지면, 우리는 그 셀을 reuse하기 위해 컨베이너 벨트 바깥(?)으로 내보내죠.
그리고 다음 데이터를 담아오는데, 만약 이미지 파일이 엄청나게 크다면
여러분이 image = nil을 하는건 세팅된 이미지를 변경하는거고
여러분의 휴대폰은 계속 서버에 통신하면서 이미지를 끝까지 다운받으려고 노력할거에요ㅎㅎㅎ
요정도면 느낌이 올까요??
(이미지 주소를 어엄청 큰 배경화면들로 임의로 변경해서 진행해보세요! 캐싱안되게해서!!)

---

지난 스텝에도 이번 스텝에도 깔끔한 코드 좋습니다ㅎㅎㅎ
하지만 하나에 꽂히면 너무 사랑하시는 부분이 있는 것 같아요ㅋㅋㅋㅋㅋ🤣
그것이 이번엔 lazy네요, 자 lazy는 언제 필요할까요? 
왜 사람들은 lazy를 안붙인 변수도 선언할까요ㅎㅎㅎ
이번에도 열심히 공부해봅시다 

화이팅!

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    private lazy var datasource = makeDataSource()
dataSource를 뷰 모델이 관리하면 어떨까요?🙏

프로젝트 규모가 조금씩 커지고 있어서, 코드 양이 많아질 것 같은데요!
뷰컨이 꼭 들고있어야 하는게 아니라면 뷰 모델로 옮겨보는건 어떨지요💪

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    private lazy var imageCacheManager = ImageCacheManager<Products>(apiService: productsAPIServie)
imageCache하는건데 Products라는 타입을 알아야하나요??👀
MainViewController이 들고있는게 다소 어색해보이기도 해요!

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    private let productsAPIServie = APIProvider<Products>()
api 통신하는 부분을 따로 가지는 부분 아주 좋습니다. 다만 이것도 뷰 모델로 이동하는게 더 좋을거같네요😳

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    private var currentPage = 1
ViewController가 가지고 있어야 하는 데이터들인가욥?

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        )
흠, mainView를 따로 만들어서 view를 분리한 상태인데, 
register Cell을 하는건 view의 역할로 보는게 좋을까요, viewController의 역할로 보는게 좋을까요?👀
여러분의 의견이 궁금합니다.

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        mainView.segmentControl.addTarget(self, action: #selector(changeLayout), for: .valueChanged)
좋습니다! 혹시 segmentControl에 중복되게 addTarget을 할 수 있을까요?👀

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    }
보통 이런 경우에는 `segmentControlValueChanged` 이렇게 네이밍하는 것 같기도해욥!
ex) `nextButtonDidTap`

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +// MARK: API Request Method
API Request Method 뷰 모델로 분리해주세요.
혹은 뷰 모델 내부에 service 만들어서 API도 아예 따로 들고있는 것도 방법일거같아욥!

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        productsAPIServie.request(with: endpoint) { [weak self] result in
weak self가 없으면 어떻게되나요?

클로저에는 항상  self 앞에 `weak가 필요한가요??😀
(요거는 지금 조금 어려울 수 있어서, 다음에 공부할 거리에 남겨두어도 좋습니닷!)

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +                }
에러 알람을 보여주는 부분이네요👀

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +                UICollectionViewCell in
`UICollectionViewCell in` 이거는 윗줄에 있는게 더 보기 편하지 않나요?ㅎㅎㅎ;;
저만 그럴수도...😅

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +                    }
오엥? 왜 여기서 작업하는거에용? 어떤 이미지인가욥🤔

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +            snapshot.appendSections([.main])
섹션이 나중에 추가되면 귀찮겠어요..🤣

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
오 저는 스크롤 offset을 이용해서만 진행했는데, 이런 방법도 있네요!👍
여러번 호출될 위험은 없을ㄲㅏ요??😀

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Extension/UICollectionViewCell.swift
> +}
좋은 방법이에요. 
그런데 보통 이렇게 Cell에다가 바로 extension하지 않고, 따로 프로토콜을 만들어서 셀에 넣어주는 경우가 더 흔한 것 같네요~
이유가 뭘까요..🤔

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Extension/UILabel.swift
> +    }
String쪽에 extension하는거랑은 어떤 차이가 있을까요??

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/DTO/ProductsListDTO.swift
> +    }
DTO라는 이름이 약간 어색하기도..?😊

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
> +    let thumbnail: URL
thumbnail 뒤에 URL 붙여주세욥! 
URL인지, 이미지인지, 주소값인지 구분이 어려울 것 같아요.
근데 위에있는 url은 뭔가요...?

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +import UIKit
하나만 합시다. 하나만 해도 되는 이유는 뭘까요?😀

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/Util/AlertBuilder.swift
> +final class AlertBuilder: AlertBuilderable {
저는 아주 보기 좋은 것 같아요!!!😊
다만 HIG에 alert를 자주 보여주는건 자제하라고 적혀있다는 사실만 찾아 보고갑시답~

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +    override func prepareForReuse() {
super 호출 안해도되나요?

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +    private lazy var productStackView: UIStackView = {
왜 lazy 키워드를 붙였나용? lazy는 어떤 기능을 하나요??🧐

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +        NSLayoutConstraint.activate([
하나로 해서 내부에서 엔터치는것 보다는 이쪽 컨벤션을 더 선호하는건가욥?ㅎㅎㅎ

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +        layer.cornerRadius = 10
셀을 원형으로 만들려면 어떻게해아할까요ㅎㅎㅎ

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarket/View/MainView.swift
> +        let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1/2),
위쪽이랑 아래쪽 컨벤션 통일해주세욥!

2022-05-19 12:51 UTC, lina0322 commented on OpenMarket/OpenMarketModelTests/NetworkDummyModelTests.swift
> +    func test_requestImage를호출할때_예상값을반환() {
실제 네트워크를 테스트하는건가요??

2022-05-20 02:54 UTC, Mino777 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    private lazy var datasource = makeDataSource()
엘림 말씀 처럼 datasource, API Request 등의 로직들을 모두 ViewModel로 이전했습니다.
감사합니다!!

2022-05-20 02:56 UTC, Mino777 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    private lazy var imageCacheManager = ImageCacheManager<Products>(apiService: productsAPIServie)
엘림 말씀 처럼 전혀 필요 없었습니다!!
해당 부분 제네릭 삭제 및 ViewModel로 옮겼습니다.
감사합니다!!

2022-05-20 02:56 UTC, Mino777 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    private let productsAPIServie = APIProvider<Products>()
모두 옮겼습니다 감사합니다!!

2022-05-20 02:57 UTC, Mino777 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    private var currentPage = 1
모두 옮겼습니다!
확실히 ViewController의 코드 양이 줄어서 훨씬 깔끔해진 것 같습니다
감사합니다!!

2022-05-20 02:58 UTC, Mino777 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        )
생각해보니 같진 않지만 느낌이 View의 addSubview와 비슷한 느낌이라고 생각이 들어서
해당 부분은 View의 역할이라고 생각이 되었습니다!
MainView로 옮겼습니다.
감사합니다!

2022-05-20 03:00 UTC, cherrishRed commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    }
네이밍 조언 감사합니다! 확실히 `segmentControlValueChanged` 더욱 알아보기 편한 것 같습니다.

2022-05-20 03:01 UTC, cherrishRed commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        mainView.segmentControl.addTarget(self, action: #selector(changeLayout), for: .valueChanged)
잘 몰라서 실험을 해 보았는데 여러개 중복도 잘 작동 했습니다!

2022-05-20 03:10 UTC, Mino777 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +// MARK: API Request Method
APIService, API Method 모두 ViewModel로 이전하였습니다!
감사합니다!

2022-05-20 03:13 UTC, cherrishRed commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        productsAPIServie.request(with: endpoint) { [weak self] result in
escaping 클로저의 경우 메서드가 종료되고나서 언제 실행될 지 예측을 할 수 없기 때문에
강한 참조를 할 경우에 RC 가 올라서 메모리에서 해지되지 않는 문제가 생길까봐 weak 을 붙여 주었던 것 같습니다. 
항상 필요하지는 않지만, 이번 프로젝트에서 의미없이 weak 을 붙였던것 같습니다.
지금 화면이 하나밖에 존재하지 않아서 앱을 실행하는 중에 ViewController 나 ViewModel 이 메모리에서 내려올 일이 없는데 weak 을 붙여 준 것 같습니다. 

우선은 weak 을 제거 했습니다!!

2022-05-20 03:16 UTC, Mino777 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +                UICollectionViewCell in
윗줄에 있는게 더 보기 편한 것 같습니다ㅎㅎㅎ
수정하였습니다!

2022-05-20 03:17 UTC, Mino777 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +            snapshot.appendSections([.main])
Section에 CaseIterable을 채택해
해당 부분에서 allCases로 모든 섹션 케이스를 담는것으로 변경하였습니다!
감사합니다!

2022-05-20 03:22 UTC, Mino777 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
저희가 테스트 해보았는데 여러번 호출되는 경우는 찾지 못했습니다😭
혹시 어떤 상황에 여러번 호출되는걸까요??
스크롤 offset을 이용하는게 더 좋은 방법일까요??

2022-05-20 03:27 UTC, cherrishRed commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +                    }
이 이미지는 셀에 들어가는 item.thumbnail 이미지 입니다. 
저희가 생각하기로는 url 을 통해서 이미지를 받아와야 하기 때문에 ViewController 에 있는 것이 적합하다고 생각했습니다. 

다른 분들도 조언해주시기로 UIImage 에 extension 을 해서 사용하는게 어떻냐 라고 이야기 하셨고 학습 활동 중에 KingFisher 라이브러리가 이러한 방식을 사용한 다는 것을 알게 되었습니다.
그런데 이런 방법을 사용하면 Cell 에서 이 메서드를 부르게 될 것 같은데, Cell 은 뷰와 같은 측면으로 생각하고 있어서 Cell 내부에서 네트워크 통신을 하는 것이 옳은지 확신이 들지 않아서 코드를 바꾸지 않았습니다. 

이에 대한 엘림의 조언을 듣고 싶습니다!

2022-05-20 05:32 UTC, cherrishRed commented on OpenMarket/OpenMarket/Extension/UILabel.swift
> +    }
String 쪽에 하는 것이 더 확장성이 있다고 생각이 됩니다. 
그래서 확장성을 높이는 쪽으로 Double, NSMutableAttributedString 확장으로 코드를 수정해 보았습니다.

2022-05-20 05:38 UTC, cherrishRed commented on OpenMarket/OpenMarket/Model/DTO/ProductsListDTO.swift
> +    }
DTO(Data Transfer Object) 의 약자로 데이터 통신을 위한 객체로 사용하고 있어서 이름을 DTO 로 붙인 것인데...
어느 지점에서 어색하다고 하시는지 구체적으로 알고 싶습니다!

2022-05-20 05:39 UTC, Mino777 commented on OpenMarket/OpenMarket/Extension/UICollectionViewCell.swift
> +}
저희 생각에는 UICollectionViewCell이 identifier가 필요하지 않는 상황이 한번이라도 있다면 엘림 말씀처럼 프로토콜을 만들어서 넣어주는 것에대한 의문이 없을텐데, cell들은 모두 identifier가 무조건 있어야되는 부분이어서 아예 extension으로 빼놓았었습니다.
프로토콜로 넣어주는 경우가 더 흔한 이유가 너무 궁금합니다!!
감사합니다!

2022-05-20 05:43 UTC, cherrishRed commented on OpenMarket/OpenMarketModelTests/NetworkDummyModelTests.swift
> +    func test_requestImage를호출할때_예상값을반환() {
`stub` 객체를 사용하여 네트워크를 이용하지 않고, asset 에 있는 data 를 올바른 형식으로 잘 받아오는지를 검사했습니다!

2022-05-20 05:45 UTC, Mino777 commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
> +    let thumbnail: URL
thumbnailURL로 수정하였습니다!
위에있는 url은 상세 화면에서의 사진 이미지의 url이고 thumbnail은 말그대로 썸네일 이미지 URL입니다!
감사합니다!

2022-05-20 05:47 UTC, Mino777 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +import UIKit
앗, 저희가 놓쳤네요ㅠㅠ UIKit안에 Foundation이 import되어 있기 때문에 UIkit만 import해도 됩니다!
감사합니다!

2022-05-20 05:48 UTC, Mino777 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +    override func prepareForReuse() {
앗 저희가 놓친 것 같습니다ㅠㅠ 수정하였습니다!
감사합니다!

2022-05-20 05:48 UTC, Mino777 commented on OpenMarket/OpenMarket/View/MainView.swift
> +        let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1/2),
줄바꿈 통일하였습니다!
감사합니다!

2022-05-20 05:50 UTC, cherrishRed commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +    private lazy var productStackView: UIStackView = {
lazy 는 빌드 할 때 값을 할당하지 않고 나중에 프로퍼티를 사용하기 직전에 할당해 주는 것으로 알고 있습니다. 
빠른 빌드를 위해 lazy 를 사용했습니다!

2022-05-20 05:53 UTC, Mino777 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +        NSLayoutConstraint.activate([
각 컴포넌트별로 따로 NSLayoutConstraint를 해주는게 개발할 때 보기 편하다고 느껴서 이런식으로 진행 했습니다!
엘림은 어떤식으로 진행하시나요?!
감사합니다!

2022-05-20 06:03 UTC, cherrishRed commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +        layer.cornerRadius = 10
실험을 해보니
`width` 와 `height` 의 비율을 1:1 로 한 후에
`layer.cornerRadius` 를 `width / 2` 설정해 주면 되었습니다. 
`clipsToBounds = true` 로 해주면 subview 들이 원 밖으로 삐져나가도 화면에 잘려서 나타나게 됩니다.

2022-05-20 09:33 UTC, Mino777 commented
안녕하세요 엘림!! @lina0322
STEP2 리펙토링 완료 했습니다!

2주동안 좋은 리뷰 주셔서 감사합니다!!🙇‍♂️🙇‍

>1. 셀을 바꾸는것
>그리고 2번과 3번중에 3번이 비용이 많이 든다고 하신 근거는 어떤걸까용??

런 타임 중에 오토레이아웃에 변화를 주는 경우 비용이 많이 든다고 알고 있었습니다. 
(사실 근거는 잘 모르겠네요😭)
다른 팀이 3번으로 한 경우에 애니메이션을 주고 빠르게 segment 를 작동하면 앱이 터지는 경우도 보았는데 왜 그런 것 일까요?


>2. Data(contentsOf: ) 와 url session
>
>음, 일단 사용하면서 차이를 못느낀 이유는 이미지가 크지 않아서? 일수도있어요!!
>고화질 바탕화면 주소를 받아보면.. 스크롤이 멈추는걸 느낄 수 있을 것 같네요~
>검색해도 정보가 안나온다니 안타깝네여ㅠㅠ 혹시 이렇게 검색하면 어떨까요
>Data(contentsOf: ) 를 사용하면 안되는 이유
>여기서도 원하는 답을 찾이 못한다면, 저에게 메세지 주세요~😆

학습활동에서 야곰이 이야기 해주시기로 Data(contentsOf: ) 은 동기로 작동하고 
url session 은 비동기로 작동한다고 이야기 해주셨습니다. 

다른 이미지가 큰 프로젝트로 실험을 해보았는데, 확실히 Data(contentsOf: ) 가 느렸습니다. 
Data(contentsOf: ) 를 사용할 때 는 비동기 로직을 같이 구현해 주어야 할 것 같습니다.



>3. URL Session 취소
>
>아주 간단하고 당장 가능한 예를 들자면,
>지금 cell 화면에서 사라지면, 우리는 그 셀을 reuse하기 위해 컨베이너 벨트 바깥(?)으로 내보내죠.
>그리고 다음 데이터를 담아오는데, 만약 이미지 파일이 엄청나게 크다면
>여러분이 image = nil을 하는건 세팅된 이미지를 변경하는거고
>여러분의 휴대폰은 계속 서버에 통신하면서 이미지를 끝까지 다운받으려고 노력할거에요ㅎㅎㅎ
>요정도면 느낌이 올까요??
>(이미지 주소를 어엄청 큰 배경화면들로 임의로 변경해서 진행해보세요! 캐싱안되게해서!!)

엘림이 디스코드로 말씀 해주신대로 UIImageView에서 이미지를 로드하는 방식으로 변경 후 URLSessionDataTaskProtocol를 URLSessionDataTask로 다운 캐스팅해서 task를 가져오는 방식으로 구현했습니다. 삭제의 경우prepareForReuse 메서드에서 task의 상태값이 completed가 아닌 경우에만 해당 task를 삭제하는 방식으로 구현했습니다!

감사합니다!

## 추가적인 질문 

### 캐시 용량 
캐시를 적용하고 앱을 실행하였을 때 캐시가 메모리를 너무 많이 먹는 것 같습니다. 
거의 1기가 가 넘기도 했습니다. 
일단은 임시방편으로 캐시의 countlimit 을 100 으로 해 두었는데요,
캐시 용량을 줄일 수 있는 다른 방법이 궁금 합니다.

2022-05-22 14:21 UTC, lina0322 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        productsAPIServie.request(with: endpoint) { [weak self] result in
저는 여기는 오히려 네트워크 쪽이라서, 얼마든지 self가 해제될 수 있을 것 같아서 weak 필요할 수 있을 것 같습니다🙏
[참고 문서](https://medium.com/@almalehdev/you-dont-always-need-weak-self-a778bec505ef) 한 번 참고해보시면 좋겠어욥💪

2022-05-22 14:23 UTC, lina0322 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
반드시 좋은 방법은 없는 것 같아요!
만약에 기획에서 아래에 닿은 후에 로딩 표시 보여주면서 사용자가 인지하게끔하려면 offset이 필요할 것 같고
지금처럼 자연스럽게 한다면 willDisplay가 좋을 겉 같습니당😀

2022-05-22 14:40 UTC, lina0322 commented on OpenMarket/OpenMarket/Extension/UICollectionViewCell.swift
> +}
저도 사실 이렇다 하는 명확한 이유는 없지만, 적어도 제가 사용하는 이유중에 하나는
1. extension보다 protocol로 되어있을때 좀 더 명확히 알 수 있는 것 같아요
저 같은 경우에는 회사에서도 하고, 여기서 리뷰하기도하고, 동아리에서도 코드 작성을 하는데 
요런 프로토콜이 있는지 없는지 보고
아, 내가 이거 구현해서 해야하는구나, 아 여기 있구나 하는 걸 알 수 있는 것 같습니답.
2. 두번째로는 보통 요런거 구현을 하면, 내부에서 register하는거나 dequeue하는 것들도 함수로 다시 만드는 것 같아요
해당 기능들은 또 모든 셀에는 필요한 것이 아니라서 protocol에서 구현하는 것 같고요!
제 생각에는 두가지 이유가 있을 것 같은데, 제 의견을 들어보시니 어떠실까용ㅎㅎ

2022-05-22 14:42 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/DTO/ProductsListDTO.swift
> +    }
보통 이런 종류의 모든 객체들은 데이터 통신을 위한 객체인데, 굳이 DTO를 붙이지 않아도? 
ProductList만으로도 충분히 역할을 하는 것 같아서욥!
왜 굳이 필요하다고 느끼셨나욥??👀

2022-05-22 14:47 UTC, lina0322 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +    private lazy var productStackView: UIStackView = {
[공식 문서](https://docs.swift.org/swift-book/LanguageGuide/Properties.html)에서 lazy 변수는 
속성의 초기 값이 필요하지 않거나, 또는 필요할 때까지 수행해서는 안 되는 복잡하거나 계산 비용이 많이 드는 설정을 필요로 할 때 유용하다고 나와있어요.
해당 변수들이 초기값이 필요하지 않거나, 복잡하거나, 계산 비용이 많이 든다고 판단하신걸까용?👀
또, lazy같은 경우 속성이 한 번만 초기화된다는 보장은 없다고 되어있는데, 이 변수들은 안전할까용??🤔

2022-05-22 14:47 UTC, lina0322 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +        NSLayoutConstraint.activate([
저는 그냥 줄바꿈으로 한거같아요ㅎㅎㅎ 
이건 제 개인 취향..🤭

2022-05-22 14:54 UTC, lina0322 commented
여러분~ 2주간 고생 많으셨어요!

아래는 질문에 대한 답변입니다🎉

--- 

> 다른 팀이 3번으로 한 경우에 애니메이션을 주고 빠르게 segment 를 작동하면 앱이 터지는 경우도 보았는데 왜 그런 것 일까요?

뭔가 터지는 에러 문구가 궁금하네요ㅎㅎ
앱이 터지는 이유는 매우 다양하지만, 앵간한(???) 애니메이션에는 안터질텐데... 저도 알려주세요ㅎㅎ;

> 캐시 용량을 줄일 수 있는 다른 방법이 궁금 합니다.

캐시한다는거 자체가 다운로드 안받고 미리 저장하려고 하는거니까, 너무 용량을 많이 차지한다면 
용량으로서도 제한 하는 방법도 있고, 음... 개수나 용량을 줄이는거 외에는.. 
자체적으로 이미지를 압축하거나 할 수는 없는거라서 따로 방법은 없는 것 같습니다!🙏

---

추가적으로 궁금하거나 어려운 거 있으면 편하게 메세지 주세요~~✉️
고생하셨습니다💕

2022-05-22 14:54 UTC, lina0322 approved these changes
여러분~ 2주간 고생 많으셨어요!

아래는 질문에 대한 답변입니다🎉

--- 

> 다른 팀이 3번으로 한 경우에 애니메이션을 주고 빠르게 segment 를 작동하면 앱이 터지는 경우도 보았는데 왜 그런 것 일까요?

뭔가 터지는 에러 문구가 궁금하네요ㅎㅎ
앱이 터지는 이유는 매우 다양하지만, 앵간한(???) 애니메이션에는 안터질텐데... 저도 알려주세요ㅎㅎ;

> 캐시 용량을 줄일 수 있는 다른 방법이 궁금 합니다.

캐시한다는거 자체가 다운로드 안받고 미리 저장하려고 하는거니까, 너무 용량을 많이 차지한다면 
용량으로서도 제한 하는 방법도 있고, 음... 개수나 용량을 줄이는거 외에는.. 
자체적으로 이미지를 압축하거나 할 수는 없는거라서 따로 방법은 없는 것 같습니다!🙏

---

추가적으로 궁금하거나 어려운 거 있으면 편하게 메세지 주세요~~✉️
고생하셨습니다💕

2022-05-22 14:55 UTC, merged