오픈마켓 I [STEP2] Donnie, 우롱차
yagom-academy/ios-open-market pull request #148
Opened 2022-05-18 06:16 UTC by westeastyear

안녕하세요 @TTOzzi !!
[STEP 2] PR 보냅니다 🙇🏻‍♂️
이번에도 잘 부탁드리겠습니다 😘
괜찮으시다면 이번 PR도 이야기 나누면서 함께 했으면 좋겠습니다 😆

## 🧐 고민한 점 및 해결한 부분

### 1. `ListCell`을 구현하기 위해 `customCell`을 만들어 등록하는 방식과, `Modern cell configuration` 방식중에 어떤것을 사용할지 고민하였습니다.
> - `customCell`을 만들어 등록하는 방식이 익숙하여 자주 사용했었는데, 이번에는 `default`로 지원되는 값들이 있고 구현되는 코드가 적은 `Modern cell configuration`방식을 사용하였습니다. 
> - 하지만 세세한 부분을 커스텀하기까지는 난이도가 있었고 자유도가 적어 사용하기 어려웠습니다. 러닝커브가 있어서 저희를 고생하게 만든 녀석입니다.

<br>

### 2. 통신해서 얻은 객체가 이미지 `url`을 가지고 있는데, 이러한 이미지를 다시 다운로드를 어느시점에 할것인지에 대하여 고민이 있었습니다. 
> - `init` 메서드를 변경하여 디코딩할때 이미지값도 같이 가져오도록 변경하였습니다.

```swift
init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(Int.self, forKey: .id)
        vendorId = try container.decode(Int.self, forKey: .vendorId)
        name = try container.decode(String.self, forKey: .name)
        thumbnail = try container.decode(String.self, forKey: .thumbnail)
        currency = try container.decode(String.self, forKey: .currency)
        price = try container.decode(Double.self, forKey: .price)
        bargainPrice = try container.decode(Double.self, forKey: .bargainPrice)
        discountedPrice = try container.decode(Double.self, forKey: .discountedPrice)
        stock = try container.decode(Int.self, forKey: .stock)
        createdAt = try container.decode(String.self, forKey: .createdAt)
        issuedAt = try container.decode(String.self, forKey: .issuedAt)
        thumbnailImage = convertImage()
    }
```

<br>

### 3. 재사용되는 `Cell`로 인한 레이블의 `Color`변화를 초기화 하기 위해 고민하였습니다.
> - `GridCell`에서 의도치 않은 `textLabel`의 색상변화가 있었습니다. 할인이 있을때만 색깔이 빨간색이되어야 하는대 셀이 재사용되면서 빨간색이 남아있는 경우가 있었습니다.
> - `GridCollectionViewCell` 클래스 내부에 아래와 같이 초기화하는 코드를 작성해주어 해결하였습니다.

```swift
override func prepareForReuse() {
        super.prepareForReuse()
        productPrice.attributedText = nil
    }
```

<br>

## 😆 조언을 받고 싶은 부분
### 1. `Modern cell configuration`을 더 잘 이해해기 위해서는? 
> - `Modern cell configuration`을 적용하기 위해 많은 구글링과 강의를 보면서 따라했는데, `UICollectionViewDiffableDataSource`과 `NSDiffableDataSourceSnapshot`에 대한 이해가 여전히 부족합니다.
> - 어찌어찌 팀원의 도움으로 구현에는 성공하였지만, 코드를 이해하기너무 어렵고 해석에 대한 갈증을 느끼고 있습니다.
> - `generic`과 `closure`가 합쳐져 있는 코드를 어떻게 이해해야 좋을지 조언 부탁드립니다. 앞으로 이러한 코드가 많이 있을텐데 걱정이 앞서고 있습니다.😭
```swift
// 예시
dataSource = UICollectionViewDiffableDataSource<Section, ProductInformation>(collectionView: collectionView) {
    (collectionView: UICollectionView, indexPath: IndexPath, identifier: ProductInformation) in
    
------중략-------
    
var snapshot = NSDiffableDataSourceSnapshot<Section, ProductInformation>()
    snapshot.appendSections([.main])
```

<br>

### 2. `NetworkAble`의 구조에 대하여
> - `session`을 변수로 선언하여 사용하고 있는데, 이 변수가 외부에서 사용이 되지않음으로 매개변수로 들어가는게 더 좋은구조인거 같습니다. 
> - 또한 이로인해 필수로 구현해야되는 변수도 사라져서 더 좋은거 같습니다. 
> - 하지만 한 객체 내에서 통신할때 하나의 세션만 쓴다고 생각하면 지금 구조도 괜찮은거 같기도합니다.(구현을 다하고 나니까 단점이 보이네요 ㅎㅎ) 
> - 또치의 생각은 어떠한가요?
```swift
protocol NetworkAble {
    
    var session: URLSessionProtocol { get }
    
    @discardableResult
    func requestData(
        url: URL,
        completeHandler: @escaping (Data?, URLResponse?) -> Void,
        errorHandler: @escaping (Error) -> Void
    ) -> URLSessionDataTask?
}
```

<br>

### 3. `UIActivityIndicatorView`가 `stopAnimating()` 이후 뷰에서 사라져 버립니다.
> - `LIST`에서 `GRID`로 화면이 전환될때 재사용할려고 다시 `startAnimating()`해도 변화가 없으며 뷰를 디버깅해도 보이지가 않습니다... 
> - `UIActivityIndicatorView`의 특성일까요? 다시 재사용하려면 원하는 부분에서 `view.addSubView()`를 해주어야 하는 걸까요?

<br>

### 4. `error handling`을 어떻게 해야될지 모르겠습니다.
> - 사용자에게 alert을 띄워주는게 좋을까요?

<br>

## 🥄 삽질한점 🥄
### 1. `UICollectionViewListCell` 커스텀
> - `UICollectionViewListCell`을 커스텀 하기 위해 많이 많이 찾아봤습니다. 
> - 그중에 저희와 가장 유사한 형태를 참조하여 작성하였는대 코드가 좀 어려워서 저희에게 필요한 코드만 추출하기 힘들었습니다. [@참고링크](https://leechamin.tistory.com/555)

<br>

2022-05-18 06:30 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/DataType/PageInformation.swift
> +    private(set) var pages: [ProductInformation]
이부분은 let으로 다시 바뀌는게 맞는거 같습니다. ProductInformation에서 이미지를 String -> UIimage 하는 방법을 실행하다가 바꾼건대 다시 못바꿧네요. ㅎㅎ 다시 바꾸도록 하겠습니다.

2022-05-18 06:30 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/DataType/ProductInformation.swift
> +    }
처음 데이터를 입력할때 이미지도 같이 가져오면 나중에 사용하기 편리할꺼라고 생각하여 Init(from decoder: Decoder)를 사용하였습니다. 아무래도 struct 타입이다 보니 나중에 image를 삽입해주기 까다로워서 그런것도 있고요.

2022-05-18 06:30 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/NetworkAble.swift
> +}
기존 Network 객체를 통해서 이 함수를 사용하던것을 프로토콜 기본 구현으로 변경하였습니다.

2022-05-18 06:30 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/MainViewController.swift
> +        }
적절한 에러처리가 생각나지 않아 일단 비워놓았습니다.

2022-05-18 17:39 UTC, TTOzzi requested changes
안녕하세요 도니, 우롱차! 
코멘트 확인하시고 의견에 차이가 있거나, 이해가 어려운 부분이 있다면 내일 정리해서 말씀해주세용 😊
그럼 내일 뵙겠습니다~(12시 지났으니 오늘이군요..) 고생하셨습니다! 🙇 

### `Modern cell configuration`을 더 잘 이해해기 위해서는?

음 남겨주신 글만으론 명확히 어떤 부분에서 generic, closure의 해석이 안되고 이해가 어려운지 잘 모르겠어요 :thinking:
내일 같이 이야기해보시죠~

### `NetworkAble`의 구조에 대하여

우선 `NetworkAble` 프로토콜을 구현하고, 프로토콜의 `extension`으로 로직을 구현하신 이유가 궁금해요 :eyes:
프로토콜의 요구사항으로 프로퍼티를 가지는 것에 대해선 프로토콜의 구현 목적이 어떤 것이냐에 따라 다를 것 같습니다.

추상화를 통해 객체간 계층을 둬서 의존성을 분리하는 것이 목적이라면, 외부에서 필요로 하는 것에 대한 요구사항만 가지면 될 것 같구요.
공통 로직을 묶어서 여러 곳에서 사용하기 위함이라면, 기본 구현으로 구현되는 로직에서 필요로 하는 값을 가져야 할 것 같아요.

> `session`을 변수로 선언하여 사용하고 있는데, 이 변수가 외부에서 사용이 되지않음으로 매개변수로 들어가는게 더 좋은구조인거 같습니다.

지금 말씀하신 부분은 두 가지 목적이 섞인듯한 느낌인데 구현상 문제는 없으나 `NetworkAble`를 채택한 곳에서 `requestData`를 래핑한 메서드를 만들거나, `NetworkAble`을 채택한 객체를 사용하는 곳에서 `URLSessionProtocol`을 가지고 있어야 할 것 같아요. 그게 과연 좋은 구조일까 의문이 들긴 합니다 :thinking:

### `UIActivityIndicatorView`가 `stopAnimating()` 이후 뷰에서 사라져 버립니다.

음 `startAnimating()` 을 호출하면 정상 동작해야 할 것 같은데.. 구현하셨던 부분이 코드에 남아있지 않아서 정확히 어떤 문제가 있는건지 모르겠어요.
요것도 낼 이야기해보아요 :slightly_smiling_face:

### `error handling`을 어떻게 해야될지 모르겠습니다.

관련해서 코멘트 남겼습니다!

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +    var status = 0
`status`는 어떤 상태를 나타내는 값인가요? 👀 
변수명과 값, 모두 의미를 명확하게 표현할 수 있도록 바꿔볼 수 있을 것 같아요 🤔

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +    var itemsPerPage = 40
외부에서 접근하지 않는 값이라면 `private`을 붙여주세요!
그리고 이 값들은 뷰컨이 갖고있기보단, 별도의 모델로 분리하는 게 좋을 것 같아요 🤔 
이 값들이 여기 있으면, 관련 로직이 모두 뷰컨에 몰려서 구현될 것 같네요.

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +    var collectionView: UICollectionView!
이 두 프로퍼티도 `!`를 사용하지 않고 선언하도록 구현하면 더 좋을 것 같아요.
`!`를 사용하면 언제든 앱에서 크래시가 발생할 확률을 안고 가게됩니다.

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +    }()
요기 레이아웃 선언부와 아래에 `collectionView`의 레이아웃을 스위칭해주는 부분을 `UICollectionView`를 상속받는 별도의 커스텀 뷰를 만들어 뷰컨에서 분리해줄 수 있을 것 같아요.

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +        self.collectionView.register(ListCollectionViewCell.self, forCellWithReuseIdentifier: ListCollectionViewCell.identifier)
요것도 `configureCollectionView` 메서드 안으로 묶어줄 수 있지 않을까요? 👀 
따로 선언해두신 이유가 궁금해요.

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +    @objc func changeSegmentedControl(sender: UISegmentedControl) {
이 메서드도 외부 접근이 없다면 `private` 명시해줄 수 있을 것 같습니다!
추가로 메서드의 이름이 `SegmentedControl`을 바꿔주고 싶을 때 직접 호출해야할 것만 같은데, `SegmentedControl`을 변경하다~ 보단 `SegmentedControl`이 변경되었다~ 를 나타낼 수 있는 이름이면 더 좋을 것 같아요.

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +            collectionView.reloadData()
자기자신의 프로퍼티에 접근할 때 `self`를 명시하는 기준이 궁금해요 👀

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +        activityIndicator.startAnimating()
메서드 이름은 `configureCollectionView`인데 `activityIndicator`를 추가하고 `startAnimating`까지 호출해주고 있네요 🤔 
메서드 이름을 보고는 예상하기 어려운 동작인 것 같아 따로 분리해주는 게 좋을 것 같아요.

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +            (collectionView: UICollectionView, indexPath: IndexPath, identifier: ProductInformation) in
각각의 인자의 타입 선언은 생략해줄 수 있을 것 같아요.

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +            switch self.status {
여기서 `self`를 생략하면 어떻게 되나요? 👀

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +    private func configureDataSource(pageNo: Int, itemsPerPage: Int) {
현재 이 메서드는
- DataSource를 만드는 것
- SnapShot을 만들고 apply 하는 것
- 서버에 요청을 보내고 받아온 응답을 디코드하는 것

3가지 역할을 하고 있는 것 같아요.
각각의 로직을 분리해볼 수 있을까요?

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +        }
뷰컨이 `NetworkAble` 프로토콜을 채택하고 `pageNo`, `itemsPerPage` 와 같은 네트워크 통신에 필요한 값들을 갖고있다보니 관련 로직이 모두 뷰컨에 구현되어버린 것 같아요.
네트워크 통신과 관련된 로직은 별도의 객체를 만들어 분리하고, 뷰컨에서는 응답을 받아 그에 맞는 뷰 렌더링 처리만 해주도록 변경하면 더 좋을 것 같습니다 🙂

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +        }
이 부분은 네트워크 통신에 실패했을 때 호출되는 부분인 것 같네요.
위에서 `guard`로 예외처리된 `url`이 없는 상황, 받아온 응답 디코드를 실패한 상황에서도 에러처리가 함께 되어야 할 것 같아요.
사용자에게 무언가 실패했음을 알려주기 위한 알러트나 에러 화면을 표시하는 등의 처리를 해줄 수 있을 것 같습니다.
추가로 네트워크 통신을 재시도 할 수 있도록 구현해주면 더 좋을 것 같구요!

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +            self.dataSource.apply(snapshot, animatingDifferences: true)
여기서도 `self`를 지우면 어떻게 될까요? 👀 
`escaping` 클로저에서의 캡처와 순환 참조에 대해 공부해보시면 좋을 것 같습니다.

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +}
요건 없어도 될 것 같아요!

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/DataType/ProductInformation.swift
> +import UIKit
`Foundation`과 `UIKit`은 각각 어떤 역할을 하는 건가요? 👀

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/DataType/ProductInformation.swift
> +struct ProductInformation: Codable, Equatable, Hashable {
위와 비슷한 맥락으로.. `Equatable`과 `Hashable`은 어떤 차이가 있나요?

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/DataType/ProductInformation.swift
> +        guard let url = URL(string:thumbnail), let data = try? Data(contentsOf: url) else {
`Data`의 `init(contentsOf:)`는 어떤 방식으로 동작하나요? 👀 
이미지 데이터는 대체적으로 크기가 큰 편인데, `init(contentsOf:)`를 사용하면서 발생할 수 있는 문제는 어떤 게 있을까요?

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/DataType/ProductInformation.swift
> +    }
처음 데이터를 받아 디코딩하는 시점에 이미지까지 한 번에 받아오면 사용하기엔 편리하겠지만, 불필요한 리소스의 낭비가 생길 것 같아요.
지금 당장 화면에 보여지지 않을 이미지까지 다 받아오게 되고, 만약 사용자가 메인화면에서 스크롤하지 않고 앱을 종료하거나 화면을 넘어가게 된다면 사실상 필요 없는 이미지를 위해 네트워크 통신 -> 이미지 변환 작업을 한 것이 될거예요.
추가로 지금은 이미지를 동기적으로 받아오고있어 이미지를 모두 받아올 때 까지 로딩화면을 표시하게 될 것 같구요 🤔 

`CollectionView`는 화면을 표시하는데에 필요한 만큼의 셀만 만들어두고 그 셀들을 재사용하는 방식으로 동작하는데, 이 시점에 맞춰서 이미지를 받도록 변경하면 좀 더 효율적인 구현을 할 수 있을 것 같습니다.
(물론 필요한 시점에 이미지를 받도록 변경하면 지금보다 구현이 더 복잡해집니다. 이미지 캐싱, 이미지를 받기 위한 네트워크 통신이 끝나기 전 셀이 재사용되는 경우 등 고려해야할 부분이 생각보다 많을거예요 🙂)

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/NetworkError.swift
> +enum NetworkError: Error, LocalizedError {
음 `LocalizedError`를 채택하셨다면, `LocalizedError`가 제공하는 기능을 사용할 수 있도록 구현도 해주면 더 좋을 것 같아요 🙂

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/OpenMarketApi.swift
> +    var pathString: String {
`URL`에서 `path`는 어떤 부분인가요? 👀
추가로 아래에서 URL을 반환하는 프로퍼티가 구현되었으니, 여긴 `private`으로 숨겨줘도 될 것 같아요.

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +    }
요렇게 셀마다 공통으로 `identifier`를 가지면서 중복되는 코드를 `extension`으로 분리해 구현하기도 합니다.

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +    }()
여긴 클로저로 생성하지 않아도 될 것 같아요 🤔

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +        numberFormatter.numberStyle = .decimal
`configureContent`는 매번 셀이 `dequeue`될 때 마다 불리고 있는데, 그 때 마다 항상 새로운 `NumberFormatter`를 생성해주는 것 보단 하나만 만들어두고 재사용하는 게 효율성 측면에서 좋을 것 같아요 🤔 
포맷팅하는 작업을 뷰에서 하는 게 아닌 별도의 객체로 분리할 수 있다면 더 좋을 것 같구요.

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +        }
데이터를 뷰에 표현하기 위한 문자열 가공 로직이 `ListCollectionView`와 `GridCollectionView`가 완전히 동일한 것 같아요.
중복되는 코드를 줄여볼 수 있을까요?

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +        setConstraint()
셀이 재사용될 때 마다 이 메서드를 호출하면 레이아웃이 무한으로 쌓이게 될 것 같아요 😯

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarketJSONTests/OpenMarketJSONTests.swift
> +final class OpenMarketJSONTests: XCTestCase, NetworkAble {
이 테스트가 앱에서 사용중인 네트워크 통신 로직이 정상 동작함을 보장해주기 위해선 실제로 앱에서 사용중인 네트워크 객체를 테스트해야 하지 않을까요?
현재 구현에선 (다른 객체로 분리해줘야 할 것 같긴 하지만..) `NetworkAble`을 채택하고 있는 `MainViewController`가 될 것 같네요.
만에하나 실제 앱에서 사용중인 타입으로 테스트가 어렵다고 하더라도, `XCTestCase`에 채택하고 테스트하기 보단 `NetworkAble`를 채택한 별도의 타입을 만들어 테스트해야 할 것 같아요.
`XCTestCase`가 가지고 있는 로직이 결과에 영향을 줄 수도 있으니까요 🙂

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarketJSONTests/OpenMarketJSONTests.swift
> +        let url = URL(string: urlString)!
`pathString`보단 구현해두신 `url`을 사용하면 더 좋을 것 같아요.

2022-05-18 17:39 UTC, TTOzzi commented on OpenMarket/OpenMarketJSONTests/OpenMarketJSONTests.swift
>          wait(for: [promise], timeout: 10)
사소하지만.. 실제 네트워크 통신을 하는 테스트가 아닌, 모의 객체를 활용한 테스트는 사실상 비동기로 동작하지 않으니 `expectation`을 없애줘도 될 것 같아요 🤔

2022-05-19 12:21 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/MainViewController.swift
> +    var status = 0
segment index를 나타내기 위한 값인대 이 변수를 제거하고 segment index를 사용할 예정입니다.

2022-05-19 12:23 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/MainViewController.swift
> +    var itemsPerPage = 40
앗 이부분은 외부에서 나중에 접근이 가능하지 않을까라고 생각해서 이렇게 했습니다. 다른페이지에서 이 페이지의 정보를 바꿔서 조회할수도 있지않을까요? delgate 메서드를 사용할때처럼요.

2022-05-19 12:24 UTC, westeastyear commented on OpenMarket/OpenMarket/MainViewController.swift
> +    var collectionView: UICollectionView!
"!"를 빼는 방향으로 리펙토링 하겠습니다.

2022-05-19 12:26 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/MainViewController.swift
> +        self.collectionView.register(ListCollectionViewCell.self, forCellWithReuseIdentifier: ListCollectionViewCell.identifier)
이 부분은 기능구현 급급하여 디테일을 챙기지 못했습니다.

2022-05-19 12:27 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/MainViewController.swift
> +    @objc func changeSegmentedControl(sender: UISegmentedControl) {
넵 private을 붙이고 `changeSegmentedControl` -> `changedSegmentedControl` 로 변경하겠습니다.

2022-05-19 12:28 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/MainViewController.swift
> +        activityIndicator.startAnimating()
이 부분도 기능 구현에 급급하여 디테일 챙기지 못했습니다. ㅠㅠ 분리하도록 하겠습니다.

2022-05-19 12:30 UTC, westeastyear commented on OpenMarket/OpenMarket/MainViewController.swift
> +            collectionView.reloadData()
이 부분은 저의 차례일때 많이 나타나는 부분이였습니다. 자신의 프로퍼티에 접근할때 저는 self를 명시하고 우롱차는 하지않는 스타일인데 서로가 컨벤션을 정해두지 않아 나타난 현상이라고 생각합니다. 리펠토링할때 팀원과 협의후 수정하도록 하겠습니다.

2022-05-19 12:32 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/MainViewController.swift
> +            (collectionView: UICollectionView, indexPath: IndexPath, identifier: ProductInformation) in
앗 알겠습니다.

2022-05-19 12:34 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/MainViewController.swift
> +            switch self.status {
이 친구는 dataSource의 클로저에 담기는 친구라서 안써주면 빨간줄이 나옵니다. 왜냐면 dataSource 입장에서는 이 status가 어디에서 온 status인지 모르기 때문이죠.

2022-05-19 12:35 UTC, westeastyear commented on OpenMarket/OpenMarket/MainViewController.swift
> +    private func configureDataSource(pageNo: Int, itemsPerPage: Int) {
각각의 역할에 따라 분리하도록 하겠습니다.

2022-05-19 12:39 UTC, westeastyear commented on OpenMarket/OpenMarket/MainViewController.swift
> +        }
새로운 객체를 만들고 NetworkAble을 채택하고 로직을 분리하는 방향으로 하겠습니다.

2022-05-19 12:40 UTC, westeastyear commented on OpenMarket/OpenMarket/MainViewController.swift
> +        }
예를들어 기본값인 이미지로 10개중에 1를 처리하고 스크롤을 다시할때 받아오는 방식

2022-05-19 12:42 UTC, westeastyear commented on OpenMarket/OpenMarket/MainViewController.swift
> +            self.dataSource.apply(snapshot, animatingDifferences: true)
이 친구도 클로저로 들어가는 친구여서 self를 지우면 안됩니다. 이유는 위에 있었던 질문과 비슷한 이유입니다.

2022-05-19 12:43 UTC, westeastyear commented on OpenMarket/OpenMarket/MainViewController.swift
> +}
삭제하도록 하겠습니다. 습관을 따라 미리 만들어 두었는데 필요가 없었네요...

2022-05-19 12:48 UTC, westeastyear commented on OpenMarket/OpenMarket/Model/DataType/ProductInformation.swift
> +import UIKit
UIKit 안에 Foundation이 있는 구조로 알고 있는데, 디테일을 챙기지 못하였습니다. 
UIKit은 Apple 플랫폼에서 앱을 구축하기 위한 그래픽, 이벤트 기반의 프레임워크이고, Foundation은 데이터 저장, text 처리, 날짜 및 시간 계산, 정렬 및 필터, 네트워킹을 포함한 앱 기능과 프레임워크의 기본이 되는 프레임워크입니다.
Foundation은 삭제하도록 하겠습니다.

2022-05-19 12:52 UTC, westeastyear commented on OpenMarket/OpenMarket/Model/DataType/ProductInformation.swift
> +struct ProductInformation: Codable, Equatable, Hashable {
Hashable을 사용한 이유는 데이타 소스에 저장하기 위함이었고, Equtable은 테스트시 비교를 위해 채택을 하였었습니다.
Hashable을 사용하려면 Equtable이 필요한것으로 알고 있습니다. 
(우롱차뇌피셜)비교가 가능해야 값이 유일한지를 알수가 있을거라고 생각이 들었습니다.

2022-05-19 13:11 UTC, westeastyear commented on OpenMarket/OpenMarket/Model/DataType/ProductInformation.swift
> +    }
플레이스홀더 이미지로 처리, prepatching 사용?

2022-05-19 13:44 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/MainViewController.swift
> +    var status = 0
enum 으로 관리하는 방법이 더 좋겠군요!

2022-05-19 13:46 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/MainViewController.swift
> +    var itemsPerPage = 40
private(set)으로 하던가 private으로 해놓는다. 필요할때 private을 해제하거나. 추후 init() 으로 주입으로 구현하도록 한다.

2022-05-19 13:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/MainViewController.swift
> +    }()
UICollectionView를 상속받는 별도의 커스텀 뷰를 만들어 layout을 변경하는 메소드를 구현하여 사용한다.

2022-05-19 13:50 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/MainViewController.swift
> +    @objc func changeSegmentedControl(sender: UISegmentedControl) {
segmentedControlChanged

2022-05-19 13:57 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/DataType/ProductInformation.swift
> +struct ProductInformation: Codable, Equatable, Hashable {
equatable 지우도록 하겠습니다.

2022-05-19 14:04 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/DataType/ProductInformation.swift
> +        guard let url = URL(string:thumbnail), let data = try? Data(contentsOf: url) else {
여러개 쓰래드에서 병렬적으로 하거나 기존 구현된 Networkable으로 데이터를 받아오도록 사용하는게 좋다.

2022-05-19 14:07 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/OpenMarketApi.swift
> +    var pathString: String {
path라는 단어는 Url에서 이미 쓰이고 있는 단어로 혼동의 여지가 있을수 있다 그러므로 urlString 정도로 바구는게 맞다.

2022-05-19 14:09 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +        numberFormatter.numberStyle = .decimal
수정 완료했습니다.

2022-05-19 14:11 UTC, westeastyear commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +        }
뷰에 보여주기 위한 가공하는 로직을 객체로 분리 뷰모델이 되는데 이걸 셀로 전달해서 사용하는방법
뷰모델을 나누지 않겠다하면 상위 셀 프로토콜로 로직을 분리 상속으로 분리를 하던 셀리 프로토콜을 채택을 한다던지 프로토콜의 메서드를 사용하다는 느낌?

2022-05-19 14:12 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +        }
객체를 선언하고 그 객체에서 데이터를 할당한뒤 cell에 넘겨주는 방식으로 설계해보겠습니다.

2022-05-19 14:15 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +        setConstraint()
기존에 있는 레이아웃을 업데이트 하는 방식으로 수정하겠습니다.

2022-05-19 14:16 UTC, dnwhd0112 commented on OpenMarket/OpenMarketJSONTests/OpenMarketJSONTests.swift
> +final class OpenMarketJSONTests: XCTestCase, NetworkAble {
객체를 만들어서 수정하는 방식으로 다시 설계하겠습니다.

2022-05-19 14:16 UTC, dnwhd0112 commented on OpenMarket/OpenMarketJSONTests/OpenMarketJSONTests.swift
> +        let url = URL(string: urlString)!
넵 알겠습니다.

2022-05-19 14:17 UTC, dnwhd0112 commented on OpenMarket/OpenMarketJSONTests/OpenMarketJSONTests.swift
>          wait(for: [promise], timeout: 10)
wait 부분을 제거하도록 하겠습니다.

2022-05-20 06:52 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/MainViewController.swift
> +            switch self.status {
weak 에 대해서는 나중에 생각해보자.

2022-05-21 12:40 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +        }
수정완료 했습니다.

2022-05-21 12:40 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +    }()
수정완료했습니다.

2022-05-21 12:40 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +    }
수정완료했습니다.

2022-05-23 12:09 UTC, dnwhd0112 reviewed
@TTOzzi 
안녕하세요 또치 수정 완료했습니다! 뷰 전환시( grid -> list, list -> grid) 콘솔창에 경고 로그가 쌓이는거 같은대 수정은 엄두가 안나네요. 이야기 나눴던것중에 cell에서 공통적인 layout을 변경시키는 부분은 제외하고 수정완료했습니다.(이부분은 UICollectionViewListCell 을 사용하기 때문에 변경이 쉽지않은거 같습니다)

2022-05-23 12:09 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/MainViewController.swift
> +            self.dataSource.apply(snapshot, animatingDifferences: true)
또치... 어느 클로저에서 weak 를 사용해야 될지 잘 판단이 안됩니다 ㅜㅜ, 이부분에서 weak를 쓴 이유는 나중에 mainViewController가 사라졌을때 동작되는것과 순환참조를 막기 위해서 입니다.(로직상 그런일은 없을꺼 같긴 하지만요)

2022-05-23 12:09 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/Network.swift
> +
싱글톤 패턴으로 구현하는 바람에 delegate 변수를 가지지 못하게 되었습니다.(thread unsafe 함으로 변수를 제거하였습니다.)
```swift
weak var delegate: MainViewDelegate?
```
이로 인하여 메소드에서 delegate를 받는 형식으로 구현하였습니다.

2022-05-23 12:09 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +        lastDataTask = network.setImageFromUrl(imageUrl: product.thumbnail, imageView: productImage)
이전 DataTask가 남아있으면 취소하도록 구현하였습니다.

2022-05-24 10:41 UTC, TTOzzi approved these changes
안녕하세요~ 도니, 우롱차!
> 이야기 나눴던것중에 cell에서 공통적인 layout을 변경시키는 부분은 제외하고 수정완료했습니다.(이부분은 UICollectionViewListCell 을 사용하기 때문에 변경이 쉽지않은거 같습니다)

이 부분은 레이아웃 변경 부분이라기보단, 서버에서 받아온 데이터를 뷰에 보여주기 위한 데이터로 가공하는 로직을 말씀드린거였어요!
요건 뷰모델이라는 개념에 대해서 차근차근 공부해보시고, 나~~~중에 적용해보시면 좋을 것 같습니다 🙂 
남겨드린 코멘트 보시고 수정이 필요한 부분이 있다면 다음 스텝 진행하면서 천천히 수정해보아요.
고생하셨습니다! 🙇

2022-05-24 10:41 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +    private var itemsPerPage = 40
흠 여전히 뷰컨이 페이지 정보를 갖고있군요 🤔 
뷰는 받은 정보를 그대로 보여주기만 하고, 요청에 필요한 부가적인 정보는 다른 객체가 가지도록 하는 게 좋을 것 같아요.

2022-05-24 10:41 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +        case ViewType.list.rawValue:
`rawValue`를 꺼내서 분기를 나누기보단, `ViewType`의 생성자를 활용하면 더 깔끔하게 처리할 수 있을 것 같습니다.

2022-05-24 10:41 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +        network.requestDecodedData(pageNo: pageNo, itemsPerPage: itemsPerPage, delegate: self)
`requestDecodedData`를 보고 메서드가 정확히 어떤 처리를 하고 있는지, DecodedData가 어떤 타입을 의미하는 것인지 알 수 있을까요? 👀 
비동기 데이터 전달에 뷰컨을 넘기도록 구현하신 이유도 궁금해요.
이름은 `delegate`라고 지었으나 구현 방식은 일반적으로 생각하는 Delegate 패턴과 차이가 있는 것 같아서요 🤔

2022-05-24 10:41 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +        case ViewType.list.rawValue:
여기도 `ViewType`의 생성자를 활용하면 더 깔끔해질 것 같습니다 🙂

2022-05-24 10:41 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +extension MainViewController: MainViewDelegate {
`MainViewDelegate`는 무엇의 동작을 위임하기 위한 프로토콜이며, 누가 위임받은 건가요? 👀

2022-05-24 10:41 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/Network.swift
> +    func setImageFromUrl(imageUrl: URL, imageView: UIImageView) -> URLSessionDataTask? {
여기서 이미지 데이터를 받아온 이후, `UIImageView`에 이미지 할당까지 처리해 줄 필요가 있을까요? 🤔 
이미지 할당을 해주기 위해 `UIImageView`와 강하게 결합된 구조가 되어버린 것 같습니다.
여기선 이미지 데이터 받아오고 캐싱까지만 해주고, 할당은 여기서 반환한 응답을 받아 처리해주는 게 더 좋을 것 같아요.

2022-05-24 10:41 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/Network.swift
> +    func requestDecodedData(pageNo: Int, itemsPerPage: Int, delegate: MainViewDelegate?) {
위 두 메서드는 이미지 데이터 다운로드, 캐싱을 처리하는 로직이라 어느 화면에서든 공통으로 사용할 수 있을 것 같은데, 이 메서드는 메인 화면에서만 사용할 수 있는 메서드인 것 같아요 🤔 
프로젝트 전체에서 공통으로 사용할 이미지를 처리하는 객체와 네트워크 통신을 활용해 메인에서 사용할 데이터를 가공해주는 객체를 따로 분리하면 더 좋을 것 같아요.
지금은 하나의 객체에서 두 가지 역할을 하고 있는 것 같습니다.

2022-05-24 10:41 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/OpenMarketApi.swift
> +import UIKit
여긴 `UIKit`을 지워줘도 될 것 같아요.

2022-05-24 10:41 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/Network.swift
> +    func setImageFromUrl(imageUrl imageUrlString: String, imageView: UIImageView) -> URLSessionDataTask? {
사소하지만.. 메서드 호출부에서 한 문장으로 읽힐 수 있도록 선언하면 가독성이 더 좋을 것 같아요.
ex) `func setImage(receivedFrom imageUrl: String, to imageView: UIImageView)`

2022-05-24 10:41 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +        guard cellContentLayouts == nil else { return }
사실상 "1회만 호출" 과 동일한 로직인 것 같은데, 생성 시점이 아닌 `configureContent`에서 매번 호출해줘야 하는 이유가 궁금해요 👀

2022-05-24 10:41 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/view+extension.swift
> +//  view+extension.swift
사소하지만(22) 이 파일만 소문자로 시작하는 이유가 있을까요?

2022-05-24 10:41 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/view+extension.swift
> +}
파일명이 `view+extension`이라 `UIView`와 관련된 `extension`만 있을 것 같은데, `NSMutableAttributedString`의 `extension`도 여기있네요 🤔 
따로 파일로 분리해주면 더 좋을 것 같아요.

2022-05-24 10:41 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/view+extension.swift
> +}
개인적인 생각으론 `ViewType`은 연관성 있는 타입인 `MainCollectionView`와 함께 있는 게 자연스러울 것 같아요 🤔 
이름도 어떤 뷰의 타입을 나타내는 것인지 더 명확하게 바꿔주면 더 좋을 것 같구요.

2022-05-24 10:41 UTC, TTOzzi commented on OpenMarket/OpenMarketJSONTests/OpenMarketJSONTests.swift
> +final class OpenMarketJSONTests: XCTestCase, NetworkAble {
테스트 코드는 잠깐 보류..? 인걸까요 ㅎㅎ
테스트 코드를 수정하면서 구조의 문제점을 발견하는 경우도 꽤 있습니다.
테스트 코드 작성이 어려운 구조는 좋지 않은 구조일 확률이 높거든요.
이건 나중에 여유있을 때 수정해보아요 🙂

2022-05-24 10:42 UTC, merged

2022-05-24 10:53 UTC, TTOzzi commented on OpenMarket/OpenMarket/MainViewController.swift
> +            self.dataSource.apply(snapshot, animatingDifferences: true)
![IMG_0140](https://user-images.githubusercontent.com/50410213/170018654-9fe53825-024b-4450-8a03-db519fcc9429.PNG)
잘 설명된 이미지가 있네요!

2022-05-24 12:06 UTC, westeastyear commented on OpenMarket/OpenMarket/MainViewController.swift
> +    private var itemsPerPage = 40
아직 정확하게 이해가 안된것 같습니다. `pageNo`와 `itemsPerPages`를 어디에 두어야 할지 누가 가지고 있어야 하는지 잘 모르겠습니다...

2022-05-24 12:07 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/MainViewController.swift
> +extension MainViewController: MainViewDelegate {
MainViewDelegate 는 사실 네트워크에서 에러처리 알람을 나타내기 위해서 사용한건데요. 네이밍이 명확하지 않은거 같습니다. ㅠ

2022-05-24 12:10 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/Network.swift
> +    func setImageFromUrl(imageUrl: URL, imageView: UIImageView) -> URLSessionDataTask? {
네트워크에서 비동기로 이미지 데이터를 받아오기 때문에 리턴해주는거는 힘들다고 생각했습니다. 그러면 이미지 할당은 그럼 escaping handler에서 작동하도록 변경하는게 나을까요?

2022-05-24 12:12 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/Network.swift
> +    func setImageFromUrl(imageUrl imageUrlString: String, imageView: UIImageView) -> URLSessionDataTask? {
앗 정말이네요. 한문장으로 읽힐 수 있도록 하는게 신경쓰기 힘드네요! 고쳐보겠습니다.

2022-05-24 12:24 UTC, westeastyear commented on OpenMarket/OpenMarket/MainViewController.swift
> +        case ViewType.list.rawValue:
수정하였습니다..!

2022-05-24 12:34 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/MainViewController.swift
> +        network.requestDecodedData(pageNo: pageNo, itemsPerPage: itemsPerPage, delegate: self)
delegate는 사실 고민을 좀 많이 했습니다.
1. Network 를 class로 구현하여 singleton 으로 사용하는 방법 -> 이 경우 일반적인 delegate 패턴으로 사용하는게 불가능 합니다. (이유: thread unsafe합니다. 중간에 delegate가 바뀔수 있음)
2. Network를 struct로 구현하여 delgate 값을 넣어줌 -> 이 경우 일반적인 delegae 패턴으로 사용 가능합니다.

처음에 2번을 택했다가 이경우 Network를 연결하는 객체가 너무 많이 생길수 있다는 생각에 1번으로 고쳤습니다. 또치의 의견을 참고해서 바꾸고 싶습니다!

2022-05-24 13:37 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/MainViewController.swift
> +        network.requestDecodedData(pageNo: pageNo, itemsPerPage: itemsPerPage, delegate: self)
delegate 삭제하고 escaping Handler로 처리하도록 수정하였습니다. 또한 NetworkAble에 제네릭으로 추가하여 공용으로 사용하도록 바꿨습니다!

2022-05-24 13:54 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/Network.swift
> +    func requestDecodedData(pageNo: Int, itemsPerPage: Int, delegate: MainViewDelegate?) {
이미지를 다운받게 해주고 다운받은 이미지는 핸들러에서 처리하도록 변경했습니다.

2022-05-24 13:56 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/OpenMarketApi.swift
> +import UIKit
넵 지우도록 하겠습니다.

2022-05-24 14:02 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/View/view+extension.swift
> +//  view+extension.swift
없습니다 ㅎ... 수정하도록 하겠습니다.

2022-05-24 14:02 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/View/view+extension.swift
> +}
네 감사합니다.

2022-05-24 14:07 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/View/view+extension.swift
> +}
넵 layoutType으로 수정하였습니다.