오픈마켓 I [STEP 2] Taeangel, malrang
yagom-academy/ios-open-market pull request #150
Opened 2022-05-18 09:43 UTC by Taeangel

@stevenkim18 

안녕하세요 스티븐 우선 listcell 부분만 구현해서 PR보냅니다! 
고민했던것들과 질문들 작성했습니다 
스티븐이 보시고 세세한것들이라도 좋으니 comment부탁드립니다! 
잘부탁드립니다.  😃  👍 

## 고민했던 것들(트러블 슈팅)
>1️⃣ **이미지를 텍스트로 변경하여 label text 에 할당 하는 방법🤔**
>
>![](https://i.imgur.com/ddvA786.png)
>
>위의 사진에 보이는 `discloser indicator` 이미지를 기존에는 이미지뷰를 추가하여 구현하였다.
>
>하지만 레이아웃 관련 에러가 생겨 디스클로저 인디케이터가 늘어나는 상황이 발생했고 이를 해결하기위해 인디케이터 이미지의 고정 크기를 설정해주는것이 아니라 텍스트로 변환 하여 인디 케이터 이미지를 `label text`에 할당 주는 방법을 사용했다.
>
>**변경 전 코드**
>```swift
>private lazy var accessoryImage: UIImageView = {
>        let imageView = UIImageView()
>        imageView.image = UIImage(systemName: "chevron.right")
>        imageView.translatesAutoresizingMaskIntoConstraints = false
>        imageView.tintColor = .lightGray
>        return imageView
>    }()
>```
>**변경 후 코드**
>```swift
>private lazy var accessoryLabel: UILabel = {
>        let label = UILabel()
>        let attachment = NSTextAttachment()
>        attachment.image = UIImage(systemName: "chevron.right")?.withTintColor(.lightGray)
>        let attachmentString = NSAttributedString(attachment: attachment)
>        let attributedStr = NSMutableAttributedString(string: attachmentString.description)
>        label.attributedText = attachmentString
>        return label
>    }()
>```
>
>**변경 후 코드**
>
>2️⃣ **서버에서 가져온 데이터를 어떻게 화면에 보여줄수 있을까?? 🤔**
>
>기존 만들어두었던 서버와 통신하는 `URLSessionProvider` 를 활용해 `UIApp` 을 만들기 위해 `ViewController`에서 아래의 코드처럼 서버에서 데이터를 가지고오도록 했다.
>```swift
>class OpenMarketViewController: UIViewController {
>    private let segmentControl = UISegmentedControl(items: ["list", "grid"])
>    private var collectionView: UICollectionView?
>    private var network: URLSessionProvider<ProductList>?
>    private var productList: [Product]? {
>        didSet {
>            DispatchQueue.main.async {
>                self.collectionView?.reloadData()
>            }
>        }
>    }
>    
>    override func viewDidLoad() {
>        super.viewDidLoad()
>        network = URLSessionProvider()
>        getData(from: .productList(page: 1, itemsPerPage: 110))
>        setup()
>        addsegment()
>    }
>    
>    func getData(from: Endpoint) {
>        network?.fetchData(from: from, completionHandler: { result in
>            switch result {
>            case .success(let data):
>                self.productList = data.pages
>            case .failure(_):
>                print("")
>            }
>        })
>    }
>}
>```
> `viewDidLoad`에서 `getData()`메서드를 호출하여 서버에서 받아온 데이터를 파싱에 성공하면 저장 프로퍼티 `productList` 에 값이 할당되고 `productList` 의 값이 변경될때마다 `CollectionView` 의 `reloadData()`메서드를 사용해 `CollectionView` 를 갱신하도록 해주었다.
> 
>그후 서버에서 가져온 데이터를 `CollectionViewDataSource` 에서 활용하도록 해주었다.
>```swift
>extension OpenMarketViewController: UICollectionViewDataSource {
>    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
>        guard let cell = >collectionView.dequeueReusableCell(withReuseIdentifier: >ListCell.identifier, for: indexPath) as? ListCell else {
>            return UICollectionViewCell()
>        }
>        
>        guard let product = productList?[indexPath.item] else { 
>            return return UICollectionViewCell()
>        }
>        
>        guard let url = product.thumbnail else {
>            return UICollectionViewCell()
>        }
>    
>        network?.fetchImage(from: url, completionHandler: { result in
>            switch result {
>            case .success(let data):
>                cell.update(image: data)
>            case .failure(_):
>                break
>            }
>        })
>        
>        cell.update(data: product)
>        
>        return cell
>    }
>    
>    func collectionView(_ collectionView: UICollectionView, >numberOfItemsInSection section: Int) -> Int {
>        return productList?.count ?? .zero
>    }
>}
>```
>이미지를 제외한 데이터들은 `viewDidLoad` 단계에서 서버에서 받아오고 `cellForItemAt` 단계에서 서버에서 이미지를 가져오도록 구현하였다.
>
>**서버에서 이미지를 가져오는 코드**
>```swift
>    func fetchImage(
>        from url: String,
>        completionHandler: @escaping (Result<UIImage, NetworkError>) -> Void) {
>        guard let imageurl = URL(string: url) else {
>            completionHandler(.failure(.urlError))
>            return
>        }
>        
>        var urlRequest = URLRequest(url: imageurl)
>        urlRequest.httpMethod = "GET"
>        
>        requestImgae(with: urlRequest, completionHandler: completionHandler)
>    }
>    
>    func requestImgae(
>        with request: URLRequest,
>        completionHandler: @escaping (Result<UIImage, NetworkError>) -> Void
>    ) {
>        let task = session.dataTask(with: request) { data, urlResponse, error in
>            
>            guard error == nil else {
>                completionHandler(.failure(.clientError))
>                return
>            }
>            
>            guard let httpResponse = urlResponse as? HTTPURLResponse,
>                  (200...299).contains(httpResponse.statusCode) else {
>                completionHandler(.failure(.statusCodeError))
>                return
>            }
>            
>            guard let data = data else {
>                completionHandler(.failure(.dataError))
>                return
>            }
>            
>            guard let image = UIImage(data: data) else {
>                return
>            }
>            
>            completionHandler(.success(image))
>        }
>        task.resume()
>    }
>```
>
>3️⃣ **코드베이스로 Cell 의 레이아웃을 설정하는 방법? 🤔**
>코드로 cell의 레이아웃을 설정할때 스택뷰에 넣어서 정렬하는 방식과 frame 활용해 CGRect 설정을 해주어야 할지에 대해 고민하였고
>    
>크기와 위치를 고정하기보다는 스택뷰에 넣어 정렬하는 방식을 택하였습니다.
>
>#### 질문한것들
>
>1️⃣ **오토레이아웃 관련 에러**
>현재`stockStackView`에서만 Width and horizontal position are ambiguous for UILabel 에러가 발생하는데 좋은 해결 방법이 있을까요~?
>![](https://i.imgur.com/vskIXOF.png)
>
>2️⃣ **이미지 관련에러**
>현재 `prepareForReuse`에 이미지설정을 해주지 않는데 이미지가 변경되는 에러가 발생하지 않습니다.
>스크롤을 빠르게 내린후 다시 위쪽으로 스크롤을 하게될경우 셀이 재사용되면서 이미지가 잘못 들어갈것이라 예상 했는데 이미지가 각각의 셀의 위치에 맞게 잘 적용되는것을 확인했습니다!
>
>왜 `prepareForReuse`을 해주지 않았는데도 이미지 `bug`가 발생하지 않았는지 궁급합니다.

2022-05-19 09:38 UTC, malrang-malrang commented
@stevenkim18 안녕하세요 스티븐! PR후 지금까지 진행한것으로 업데이트 해두었습니다!
Grid 뷰를 그리고, ViewController 를 좀더 가볍게 수정하는 작업을 했습니다!

확인 부탁드리겠습니다!

2022-05-19 16:18 UTC, stevenkim18 commented
`Controller` 폴더안에서 cell이라는 폴더를 만들 수도 있어 cell들을 관리하면 더 좋을 것 같아요.

`SegmentControl`과 `FlowLayout`도 뷰컨은 아니라서 어떻게 폴더로 관리하면 좋을 지 고민해주세요!!

2022-05-19 17:09 UTC, stevenkim18 requested changes

2022-05-19 17:09 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Controller/FlowLayout.swift
> +}
커스텀 `UICollectionViewFlowLayout`를 따로 만드신 이유가 있을까요?

2022-05-19 17:09 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Controller/GridCell.swift
> +    }()
cell에 모든 뷰들을 다 lazy로 선언하신 이유가 있나요?

2022-05-19 17:09 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Controller/GridCell.swift
> +        return stackView
공백에 있네요 ㅎㅎ PR을 보내시기전에 한번 더 통일성 있는 코드를 위해서 점검해주세요!!

2022-05-19 17:09 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Controller/GridCell.swift
> +    }
update 함수가 많은 일을 하고 있네요.

각각 뷰들에 값을 넣는 부분을 함수로 빼면 더 좋지 않을까요?

저라면 loadName, loadStock, loadPrice 등 으로 private 함수로 만들 것 같아요 ㅎㅎ

2022-05-19 17:09 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Controller/GridCell.swift
> +        NSLayoutConstraint.activate([
개행!

2022-05-19 17:09 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Controller/GridCell.swift
> +    private func addsubViews() {
`addSubVIews`!!!!

2022-05-19 17:09 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Controller/GridCell.swift
> +    private func layout() {
layout보다는 `constraintLayout`을 하거나 더 좋은 함수 이름이 있지 않을까요?

2022-05-19 17:09 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Controller/LayoutType.swift
> +}
`flowLayout`을 static 변수로 관리하는게 조금 이상해 보입니다. 
이렇게 선언하면 앱 코드 내부 어디서나 `flowLayout`이 접근 가능해서 수정할 수도 있습니다.

물론 뷰컨에서 분리하시려는 시도는 좋았습니다. 하지만 뷰를 static 변수로 사용하는 경우는 저는 보지 못했습니다.
어디에서 flowLayout을 관리하면 좋을지 고민해봐주세요!!

2022-05-19 17:09 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Controller/ListCell.swift
> +    }()
UIImageView로 안하시고 UILabel로 구현하신 이유가 있을까요?

2022-05-19 17:09 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
> +    }
무엇을 `setup`하는 함수인가요?

2022-05-19 17:09 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
> +    private func addsegment() {
`addSegment`

2022-05-19 17:09 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
> +                })
코드가 identifier를 제외하고 모두 중복되네요! 어떻게 하면 중복을 줄일 수 있을까요?

2022-05-19 17:09 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
> +                })
image를 서버에서 가져오는 코드는 꼭 뷰컨에 있어야 할까요?
cell에 있으면 어떨까요?

2022-05-19 17:09 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Utils/Extension/String.swift
> +}
extension으로 기능들을 빼신 것은 매우 잘하셨습니다.

extension을 잘 활용하시면 중복되는 코드는 매우 많이 줄고 
핵심 로직만 드러낼 수 있습니다!!

2022-05-19 17:09 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Utils/Extension/UIStackView.swift
> +}
매우 잘하셨습니다!!

UIStackView는 이니셜라이져에서 초기화 할 때 UiView 배열을 넣어서 생성하는 것도 가능합니다!

2022-05-19 17:09 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Utils/Extension/UIStackView.swift
> +}
`... `을 사용하는 문법은 저도 처음 알았네요 👍

2022-05-19 17:09 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
> +                print("")
네트워크 요청이 실패 했을 때는 어떻게 처리하는 것이 좋을까요?

2022-05-19 17:11 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Controller/ListCell.swift
> +    }()
아 위에 고민했던 점에 적어두셨군요!

2022-05-20 04:49 UTC, malrang-malrang commented on OpenMarket/OpenMarket/Controller/FlowLayout.swift
> +}
음... 이부분은 스티븐의 설명을 듣고 이해했습니다! 
ViewController 를 좀더 가볍게 만들고 LayoutType 에서 플로우 레이아웃을 관리하려고 분리했으나 
ViewController 에 있어도 괜찮을것같습니다!

2022-05-20 04:53 UTC, malrang-malrang commented on OpenMarket/OpenMarket/Controller/GridCell.swift
> +    }()
lazy 를 써야할 이유가 없는데 사용한것 같습니다!
제거하도록 하겠습니다!

2022-05-20 04:54 UTC, malrang-malrang commented on OpenMarket/OpenMarket/Controller/GridCell.swift
> +        return stackView
아앗...ㅜㅜ 매번 확인한다고 하는데 놓치는 부분이 많습니다 ㅠㅜㅜ
이런 부분을 꼼꼼히 확인해야하는데 말이죠 ㅜㅜㅜ😭

2022-05-20 04:54 UTC, Taeangel commented on OpenMarket/OpenMarket/Controller/GridCell.swift
> +        return stackView
아네 ㅠㅠ 알겠습니다.

2022-05-20 04:55 UTC, Taeangel commented on OpenMarket/OpenMarket/Controller/GridCell.swift
> +    }
```
 func configure(data: Product) {
        loadImage(data: data)
        loadName(data: data)
        loadStock(data: data)
        loadPrice(data: data)
    }
```
각 메서드로 분리하였습니다.

2022-05-20 04:55 UTC, Taeangel commented on OpenMarket/OpenMarket/Controller/GridCell.swift
> +        NSLayoutConstraint.activate([
ㅠㅠ 개행 확인하겠습니다.

2022-05-20 07:44 UTC, Taeangel commented on OpenMarket/OpenMarket/Controller/GridCell.swift
> +    private func addsubViews() {
addSubVIews ㅜㅜ

2022-05-20 07:45 UTC, Taeangel commented on OpenMarket/OpenMarket/Controller/GridCell.swift
> +    private func layout() {
constraintLayout 네이밍이 더 좋을것 같네요!

2022-05-20 08:24 UTC, Taeangel commented on OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
> +    }
setupCollectionView로 네이밍을 변경하였습니다.

2022-05-20 08:25 UTC, Taeangel commented on OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
> +    private func addsegment() {
setupSegmentControl으로 변경하였습니다.

2022-05-20 08:26 UTC, Taeangel commented on OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
> +                })
```swift
private func loadImage(data: Product) {
        
        guard let stringUrl = data.thumbnail else {
            return
        }
        
        guard let url = URL(string: stringUrl) else {
            return
        }
        
        thumbnailImageView.fetchImage(url: url) { image in
            DispatchQueue.main.async {
                self.thumbnailImageView.image = image
            }
        }
    }
```
cell에서 이미지를 넣는 방식으로 변경하였습니다.

2022-05-20 11:16 UTC, malrang-malrang commented on OpenMarket/OpenMarket/Controller/LayoutType.swift
> +}
그렇군요..! 
이부분은 오늘 하루종일....삽질해서 수정했습니다!
이부분과 관련해서 궁금한점이 생겼는데요!
맨아래 코멘트에 궁금한점은 작성해두겠습니다! 🫠

2022-05-20 11:17 UTC, malrang-malrang commented on OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
> +                })
이부분...한참을 삽질했습니다..!
Cell을 프로토콜 로 추상화를하여 해결했습니다!

확인후 더좋은 방향이있었는지 코멘트 해주시면 감사하겠습니다!

2022-05-20 11:22 UTC, malrang-malrang commented on OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
> +                print("")
이부분은 함수가 종료되도록 처리를 해두었습니다..! 
이부분은 얼럿으로 처리를해야 적절했을까요..!?
셀의 이미지등 정보들이 없는 상태로 표기 해두면 좋을것같은데요..!

2022-05-20 11:33 UTC, malrang-malrang commented
궁금한점이 생겨 코멘트로 남겨두겠습니다!!

UICollectionView 의 인스턴스를 생성할때 layout 을 넣지 않으면 에러가 생기기때문에 UICollectionViewFlowLayout 인스턴스를 만들어 넣어주고 
그후 List모드 일때와 grid모드 일때 만들어둔 UICollectionViewFlowLayout 인스턴스의 설정을 변경해주려 했습니다! 어떤 이유에서 안되는것인지 
찾지 못했습니다 ㅠㅠ drawLifeCycle 의 문제였을까요!?

현재는 각각 모드를 변경할때마다 UICollectionViewFlowLayout 인스턴스를 생성하고 있습니다!
지금방식으로 사용하게되면 모드를 바꿀때마다 UICollectionViewFlowLayout의 새로운 인스턴스가 생성되고 제거되기 때문에 이러한 문제를 해결할수있는 좋은 방법이있을까요~?

2022-05-24 05:38 UTC, merged