오픈마켓 I [STEP 2] cathy, mmim
yagom-academy/ios-open-market pull request #151
Opened 2022-05-18 10:38 UTC by JoSH0318

@Monsteel 안녕하세요! 토니!🎀
STEP2 PR 입니다!
잘부탁드립니다! 

---

### 고민한 점(트러블 슈팅)
1️⃣ stroyBoard vs code UI 구현
- STEP2를 시작하기 전, UI 구현에 있어 어떠한 방법을 선택할 지 고민했다.
- 각각 장단점이 있는 것 같다.
    - storyBoard 장점: UI 구현이 빠르다. / 직접 눈으로 UI의 구성을 확인할 수 있다. / 여러 기능을 찾아보지 않고 간단하게 사용할 수 있다.
    - storyBoard 단점: 변경 사항 commit을 파악하기 어렵다. / 유지, 보수가 어렵다.
    - code 장점: storyBoard에 비해서 가볍다. /  변경 사항을 파악하기 쉽다. / 충돌 가능성이 낮다.(확인이 용이해서) / UIKit 구조, 원리를 학습하기 좋다.
    - code 단점: 코드가 길어진다. / 시간이 다소 걸린다. / 화면을 파악하기 힘들다.
- 이러한 점들을 비교했을 때, 협력과 리뷰, 학습에 도움이 된다는 점에서 code로 구현하는 것을 선택했다.

2️⃣ List, Grid 화면 전환에 대한 고민
- 셀의 프로토타입을 두개 만드는 방법과 하나의 셀에서 레이아웃만 변경하는 방법 중에서 고민했다.
- 처음에는 셀을 두개 생성하는 방법으로 진행하다가 코드의 중복이 너무 많아서 레이아웃을 변경하는 방법으로도 구현해봤지만, 첫번째 방법과 동일하게 코드의 중복이 많아졌고 하나의 셀을 공유하면서 발생하는 `side effect` 도 많았다. 
- 또한 외부 개발자가 봤을 때 구현한 내용을 바로 이해하기 힘들다는 점에서 가독성이 좋지 않다는 문제점도 있었다. 
> ❗️ 결국 처음의 방법대로 셀을 두 개 생성하여 구현하였는데, 더 좋은 방법이 있을 지 궁금하다.

3️⃣ collectionview contentsOffset 문제와 고민
- List 형식의 Layout에서 Grid 형식으로 화면전환할 때, Grid 형식의 collection view의 시작이 아래쪽인 문제가 생겼다.
- 0번째 index의 cell이 아닌 2번 index의 cell이 기준점이 되는 듯 한 현상이었고, 그 원인에 대해서 고민했다.
> ❗️ 결국 명확한 원인을 찾을 수 없었다. 
> 하지만 cell의 contents size height 만큼 offset이 아래쪽에 있다는 것을 확인했고,
> collection view의 layout이 변경될 때, `collectionView.contentsOffset`을 변경해주는 방법으로 문제를 해결했다.

<image width="600" src="https://i.imgur.com/FkYdHJY.png"/>  

4️⃣ reuseCell에 대한 고민
- 빠르게 List, Grid layout을 번갈아가며 변경하면 ListCell에 잘못된 이미지가 로드되는 버그가 생겼고, 이를 해결하기 위해 고민했다.
- cell이 reuse 되면서 생기는 버그로 판단했다.
- 또한 cell의 imageView에 이미지가 로드되는 UI update 작업이 main thred에서 이루어지지 않는다고 판단했다.
- 이러한 근거로 해당 버그를 해결하기 위해 세 가지를 수정했다.
    1. Cell의 prepareForReuse() 메서드를 override하여 reuseCell의 요소들을 reset해주었다.
    2. `collectionView.indexPath(for: cell) == indexPath`인 값들만 UI setUp 메서드를 호출할 수 있도록 했다.
    3. UI를 setUp 해주는 메서드를 `DispatchQueue.main.async`로 처리해주었다.
```swift
DispatchQueue.main.async {
    if collectionView.indexPath(for: cell) == indexPath {
        cell.setUpListCell(page: page)
    }
}
```

5️⃣ collectionView layout은 어떤 것을 선택할까
- compositionalLayout, flowLayout, listCell 방식 중 어떤 것이 이번 프로젝트에 적합할지 고민했다.
- modern collection view를 경험하는 것이 이번 프로젝트의 요구사항이다.
- 따라서 가장 먼저 composiotionalLayout을 생각했다.
    - 복잡한 layout이 요구될 때 용이하다.
    - 유연하고 어느 상황이든 적용이 가능하다.
    - 하지만 이번 프로젝트는 단순히 cell이 순서대로 나열되는 형식이다.
- listCell
    - iOS 14.0 이상이 요구된다. 
- flowLayout
    - 흐름, 순서에 따라 cell이 배치된다.
    - iOS 13.0 부터 지원된다.
    - 따라서 이번 프로젝트에 적합한 스펙이라고 판단했다.

6️⃣ Diffable DataSource, Snapshot 사용
- 처음에는 CollectionViewDataSource를 VC에 채택시켜 data source를 구현했지만, modern collection view를 적용하고자 Diffable DataSource를 적용하기로 결정했다.
- 모델 타입에 Hashable을 채택하고 diffableDataSource를 생성하여 collectionView와 연결해주었다. 
- 그 후 cell을 만들고 register된 셀에 데이터를 넣어주고 데이터가 변경될 때마다 collectionView에 특정 시점의 데이터 상태를 나타내는 snapshot을 만들어주고 DataSource에서 apply를 호출해주었다.
```swift
  private func makeDataSource() -> DataSource {
    let dataSource = DataSource(collectionView: collectionView, cellProvider: {
      (collectionView, indexPath, page) ->
      UICollectionViewCell? in
      if self.segmentedControl.selectedSegmentIndex == 0 {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "ListCell",
                                                      for: indexPath) as? ListCell
        // somecode
        return cell
      } else {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "GridCell",
                                                            for: indexPath) as? GridCell
        // somecode
        return cell
      }
    })
    return dataSource
  }
//...
  private func applySnapshot(animatingDifferences: Bool = true) {
    var snapshot = Snapshot()
    snapshot.appendSections([.main])
    snapshot.appendItems(pages)
    dataSource.apply(snapshot, animatingDifferences: animatingDifferences)
  }
```

### 질문사항
1️⃣ cell prototype을 두개 만들면서 발생하는 많은 중복 코드
고민했던 점에 작성했던 것과 같이 저희는 두 개의 셀 프로토타입을 만들어서 구현하였는데 두 개의 셀의 label, imageView, stackView등의 구성과 레이아웃이 비슷한 것이 많아서 중복코드가 많습니다. 중복되는 코드를 줄이기위해서 cell을 한 개 만드는 방법밖에 없을까요?? 저희 코드에서 개선하기위해선 어떻게 해야할 지 여쭤보고 싶습니다!

2️⃣ paging 관련 질문
이번 STEP에서 추가 구현으로 스크롤 페이징을 해보려고 했습니다. view controller에 `UICollectionViewDataSourcePrefetching` 프로토콜을 채택하여 페이징 관련 메서드를 구현해보고자 했지만...실패했습니다.
itemsPerPage가 20인 경우를 기준으로 view에 보여진 Cell의 수가 일정수준(19개 정도)일 때, page에 1을 더해주고, 그 이후에 api에서 데이터를 get하는 메서드를 호출해주는 방법을 생각해봤습니다. 하지만... 실패했습니다. 😭
아직 그 방법이 덜 숙지된 것인지 감을 잡지 못해서 어떠한 키워드로 공부를 하는 것이 좋을지 조언 부탁드립니다.🙇‍♂️

3️⃣ collectionView contentsOffset
GridCell화면에서 첫번째 셀, 두번째 셀이 safeArea안에서 잡히지 않고 넘어가버리는 것을 확인하고 collectionView의 Anchor를 safeArea에 잡아주었는데, 해결이 되지않아서 cell의 contentsOffset을 한개의 셀의 높이만큼 변경해주었습니다. 
해결은 되었지만 셀의 위치를 임의로 맞춰준 것이기 때문에 다른 좋은 방법이 있을지 궁금합니다. 
그리고 이러한 현상이 일어나는 원인이 잘못된 로직 때문인 것인지 다른 이유가 있는 것인지 궁금합니다.

2022-05-19 09:29 UTC, Monsteel requested changes
안녕하세요 cathy mmim~ 🙇🏻‍♂️
STEP2도 수고 많으셨습니다 ☀️

### 고민하신점
1️⃣ stroyBoard vs code UI 구현
 -> 효용의 가치를 비교한, 이유있는 결정 아주 좋습니다. 💯

2️⃣ List, Grid 화면 전환에 대한 고민
-> 우선 어떤 SideEffect가 있었는지 상세하게 적어주시면 좋을것 같아요!

말씀주신 문제에 대한 제 생각을 말씀드려볼게요! 참고만 부탁드립니다.
중복이 되는 Cell을 하나로 만들고, 상속을 받아 사용하는 방법도 있을 것 같고
protocol을 통해서 반드시 있어야 하는 요소들에 대해 코드단에서 정의해서 반드시 구현하는 방법으로 필드를 누락하는 등의.. 개발자의 실수를 막을 수 있을것 같아요.

3️⃣ collectionview contentsOffset 문제와 고민
-> 뭔가 viewdebug에서 확인되는 경고와 연관이 있지는 않을까요? 🙋🏻‍♂️
<img width="409" alt="스크린샷 2022-05-19 오후 5 40 56" src="https://user-images.githubusercontent.com/52942409/169258173-b8bd6cde-3332-43e1-98ad-dd39c4416433.png">

4️⃣ reuseCell에 대한 고민 -> ✨✨
5️⃣ collectionView layout은 어떤 것을 선택할까 -> 🚀🚀
6️⃣ Diffable DataSource, Snapshot 사용-> ☀️☀️

### 질문사항
1️⃣ cell prototype을 두개 만들면서 발생하는 많은 중복 코드
-> 위에 고민하신점에서 남긴 답변과 동일합니다!

2️⃣ paging 관련 질문
-> 실패하신 이유들에 대해 조금 더 자세하게 말씀해 주시면 도움이 될 것 같습니다.
사실 이 부분은 사용에 대한 부분이라 제가 조언을 드리기에는 뭔가 애매함이 있네요.. 😇

3️⃣ collectionView contentsOffset
-> 이 부분도 위에 고민하신점에서 남긴 답변과 동일합니다!

2022-05-19 09:29 UTC, Monsteel commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    layout.itemSize = CGSize(width: self.view.bounds.width/2 - 15,
15가 무엇인지, 2가 무엇인지 명확하게 알 수 있도록 변수에 담아서 표현해보는건 어떨까요? 🙋🏻‍♂️

2022-05-19 09:29 UTC, Monsteel commented on OpenMarket/OpenMarket/Util/Extension/CALayer+Extension.swift
> +//  CALayer+Extension.swift
오 네이밍 좋습니다.
참고로 `ClassName+ExtensionName`형식의 convention은 Objective-C에서 사용되던 네이밍 convention을 모방한 것입니다. _cf: https://stackoverflow.com/a/26320397_

2022-05-19 09:29 UTC, Monsteel commented on OpenMarket/OpenMarket/Util/Extension/CALayer+Extension.swift
> +//  CALayer+Extension.swift
extension을 담고있는 폴더의 이름이 extensions로 표현되면 더 좋을것 같아요 🙌

2022-05-19 09:29 UTC, Monsteel commented on OpenMarket/OpenMarket/Util/FontSize.swift
> +  static let title = 18.0
오호 enum으로 감싼 상수 좋습니다. 🚀

2022-05-19 09:29 UTC, Monsteel commented on OpenMarket/OpenMarket/Util/Extension/Int+Extension.swift
> +  func convertCurrency() -> String {
Currency라는 표현보다 더 좋은 표현은 없을까요? 단순히 ,를 찍는 행위를 Currency로 바꾼다고는 보기 어려울것 같아요.

2022-05-19 13:37 UTC, cathy171 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    layout.itemSize = CGSize(width: self.view.bounds.width/2 - 15,
`cellCountPerRow`, `listCellCountPerColumn`, `gridCellCountPerColumn`와 같이 의미가 명확한 상수를 네임스페이스로 구현했습니다! ☺️

2022-05-19 13:39 UTC, cathy171 commented on OpenMarket/OpenMarket/Util/Extension/Int+Extension.swift
> +  func convertCurrency() -> String {
numberStyle을 decimal을 바꾼다는 의미로 `formatToDecimal`로 변경하였습니다!

2022-05-20 15:41 UTC, Monsteel reviewed
별도의 리뷰는 없고, 간단한 궁금증 한가지만 남겨보았습니다 🚀
수고 많으셨습니다 밈, 캐시  ❤️

2022-05-20 15:41 UTC, Monsteel commented on OpenMarket/OpenMarket/Util/Constants.swift
> +//  Constants.swift
Constants를 Util로 구분하신 이유가 있으신가요 ?!
뭔가 성격이 다른 느낌이 들어서요!

2022-05-20 15:41 UTC, Monsteel commented on OpenMarket/OpenMarket/Util/FontSize.swift
> +enum FontSize {
요 부분도 Constants와 같이 Util로 분류하신 이유가 있으신지 궁금합니다 🙋🏻‍♂️

2022-05-21 03:41 UTC, JoSH0318 commented on OpenMarket/OpenMarket/Util/Constants.swift
> +//  Constants.swift
아직 파일 분리에 조금 미숙한 것 같습니다 😅

생각해보니 성격이 조금 다른것 같습니다!
Util은 모듈 전역에서 자유롭게 접근해서 사용하는 느낌인 것 같습니다.
그리고 실제로 Constants는 Layout에서만 사용하고 있어서 
중첩 타입으로 Layout 안에 넣어주었습니다!

2022-05-21 03:44 UTC, JoSH0318 commented on OpenMarket/OpenMarket/Util/FontSize.swift
> +enum FontSize {
이 부분도 위의 코멘트 댓글과 비슷하게 잘 못된 위치에 있는 것 같아요!
ListCell, GridCell에만 사용되고 있네요 😅
그리고 현재는 두 Cell의 폰트 사이즈가 같지만,
기획에 따라서 Cell마다 차이가 생길 수도 있다는 생각이 들었습니다.
따라서 이 또한 두 Cell 타입 안에 중첩 타입으로 FontSize를 넣어주었습니다.

2022-05-23 01:16 UTC, Monsteel approved these changes
수고하셨습니다 🎉🎉

2022-05-23 01:16 UTC, merged