오픈마켓[STEP2] papri, Tiana
yagom-academy/ios-open-market pull request #152
Opened 2022-05-18 14:23 UTC by papriOS

안녕하세요 올라프⛄️
step2 PR 보냅니다.
잘 부탁드립니다.🙇‍♀️🙇‍♀️

### 구현 내용
#### UI
* 스토리보드를 제거하고 코드로 UI를 구현하였습니다
* 하나의 collectionView의 layout이 List Layout 과 Grid Layout 두가지 모두로 보일 수 있도록 구현하였습니다
    * ProductListCell과 ProductGridCell을 만들어 주었습니다
        * 두 cell 모두 같은 UI요소에 같은 정보를 띄우기 때문에 CellUIComponent를 구현하여 코드의 중복을 방지해보았습니다
        * segmentedControl이 변경 될 때마다 프로퍼티를 setCollectionViewLayout 매서드의 매개변수로 전달합니다.

#### collectionView

* Layout object
각 레이아웃 스타일에 맞게 createGridLayout, createListLayout 매서드를 구현하고UICollectionViewLayout 인스턴스를 만들어서 프로퍼티에 저장합니다.

* DataSource
snapshot에 section은 최초 한 번만 추가합니다.
snapshot으로 셀에 데이터를 넣습니다.

#### collectionViewCell
list와 grid에서 공통적으로 사용되는 요소를 한 파일(CellUIComponent)이 구현했습니다.
list와 gird에서 각각 구현하려는 레이아웃에 맞게 stackview 내부 뷰에 요소를 배치했습니다.
state에 값에 대한 상태를 추가하기 위해 configurationState를 오버라이딩하고 updateConfiguration 매서드를 통해 셀 값이 세팅되도록 구현했습니다.

---

### 고민한 점 및 질문 사항

#### 무한 스크롤
새로운 데이터를 받아서 보여줘야 하는데 계속 같은 내용을 반복해서 보여주는 것 같습니다.
append하는 item으로 중복된 값을 snapshot에 append하는 것이 문제인 것 같은데 해결 방법이 궁금합니다.
collectionView(_ collectionView: UICollectionView, prefetchItemsAt indexPaths: [IndexPath]) 메서드에서 fetchData(index: Int)로 index를 전달해서 새로 스크롤해서 접근하는 셀의 인덱스에 해당하는 데이터가 캐시에 없으면 값을 서버에서 로드하려고 했으나 인자로 전달되는 값이 예상과 달라 중복된 데이터가 로딩되는 것 같습니다.🤔

#### 목록을 로드할 때, 빈 화면을 대신할 무언가  
스크롤을 했을 때 아직 로딩되지 않은 셀을 사용자에게 보여주고 싶은데 기본 셀을 넣어주는 위치를 잘 모르겠습니다.😢

#### 이미지 레이아웃 설정
```swift
NSLayoutConstraint.activate([
            thumbnail.heightAnchor.constraint(equalTo: contentStackView.heightAnchor),
            thumbnail.heightAnchor.constraint(lessThanOrEqualToConstant: 60),
            thumbnail.widthAnchor.constraint(equalTo: thumbnail.heightAnchor)
        ])
```
이미지 제약 사항 설정할 때 고정값을 주지 않으면 제대로 나오지 않는 것 같습니다.(아래에서 위로 스크롤을 했을 때 separator가 두껍게 나오거나 셀의 높이가 작게 나옵니다.) 비율로 값을 제공하고 싶은데 어디를 기준으로 잡는 것이 좋을지 궁금합니다.
또 lessThan이 아닌 equal로 했을 때 레이아웃 에러가 나오는 이유가 궁금합니다.

2022-05-19 01:56 UTC, 1Consumption requested changes
안녕하세요 티아나 파프리~ 고생하셨습니다.

컬렉션뷰도 어려운데, compositional layout, diffableDataSource도 같이 쓰느라 많이 어려웠을 거 같아요..!
그래도 잘 작성해주신 거 같아 다행입니다! 아직 미숙한 점이 있지만 이부분은 차차 나아질거라 생각해요!

아래는 고민한 점에 대한 제 생각을 적어봤어요.

### 고민한 점 및 질문 사항

#### 무한 스크롤
새로운 데이터를 받아서 보여줘야 하는데 계속 같은 내용을 반복해서 보여주는 것 같습니다.
append하는 item으로 중복된 값을 snapshot에 append하는 것이 문제인 것 같은데 해결 방법이 궁금합니다.
collectionView(_ collectionView: UICollectionView, prefetchItemsAt indexPaths: [IndexPath]) 메서드에서 fetchData(index: Int)로 index를 전달해서 새로 스크롤해서 접근하는 셀의 인덱스에 해당하는 데이터가 캐시에 없으면 값을 서버에서 로드하려고 했으나 인자로 전달되는 값이 예상과 달라 중복된 데이터가 로딩되는 것 같습니다.🤔

> ⛄️중복 요청에 대한 처리를 해주고 있나요? 지금은 `네트워크 요청 중이면 요청을 보내지 않는다` 라는 코드가 없어서 계속 같은 요청을 보내는 상황 같습니다(요청을 보내는 와중에도). 그러면 중복되는 데이터가 계속 내려와서 화면에 보여지겠죠.

#### 목록을 로드할 때, 빈 화면을 대신할 무언가  
스크롤을 했을 때 아직 로딩되지 않은 셀을 사용자에게 보여주고 싶은데 기본 셀을 넣어주는 위치를 잘 모르겠습니다.😢

> ⛄️ 좀 더 자세한 설명이 필요합니다! 어떤걸 말하는지 정확히 모르겠어요!
혹시 스켈레톤UI를 말씀하시는걸까요?

#### 이미지 레이아웃 설정
```swift
NSLayoutConstraint.activate([
            thumbnail.heightAnchor.constraint(equalTo: contentStackView.heightAnchor),
            thumbnail.heightAnchor.constraint(lessThanOrEqualToConstant: 60),
            thumbnail.widthAnchor.constraint(equalTo: thumbnail.heightAnchor)
        ])
```
이미지 제약 사항 설정할 때 고정값을 주지 않으면 제대로 나오지 않는 것 같습니다.(아래에서 위로 스크롤을 했을 때 separator가 두껍게 나오거나 셀의 높이가 작게 나옵니다.) 비율로 값을 제공하고 싶은데 어디를 기준으로 잡는 것이 좋을지 궁금합니다.
또 lessThan이 아닌 equal로 했을 때 레이아웃 에러가 나오는 이유가 궁금합니다.

> ⛄️ 이부분도 좀 더 자세한 설명이 필요합니다!

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 14.0;
min version을 올린 이유가 있을까요?

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    var currentSnapshot: NSDiffableDataSourceSnapshot<Section, Product>! = nil
프로덕트 코드에서 강제언래핑은 지양해주세요. 모두 옵셔널로 선언해도 될 값입니다.
그리고 외부에서 알아야하는 값인가요?

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    lazy var baseView = BaseView(frame: view.bounds)
lazy var일 이유가 없어보입니다. frame을 정하기 위함이라면 오토레이아웃으로 제약사항을 거세요.

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        view = baseView
view를 바꾸고 싶다면 다른 라이프사이클을 찾아보세요.

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    }
외부에서 몰라도 되는 펑션 같습니다.

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
비즈니스 로직을 view에서 가져서 이상합니다. 다른 역할을 가진 레이어로 분리해주세요.

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        self.configureDataSource()
이 메소드는 매번 불려야하나요? cell registration이 발생하는 메소드 같은데요.

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +
의도된 공백인가요?

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
불필요한 분기문 같습니다.

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        let ifFirst = currentSnapshot == nil
`isFirst`가 좀 더 맞는 네이밍 같습니다.

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +}
prefetching과 paging은 다른 개념입니다.
paging은 말 그대로 데이터를 나눠서 받는 것이고, prefetching은 데이터를 미리 받는 것입니다.
따라서 현재 상황은 다음 페이지에 해당하는 `시점`을 파악해야 하기 때문에 여기는 적합하지 않은 것 같고... `willDisplay` 메소드를 활용해보는건 어떨까요?

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/RegisterProductViewController.swift
> +    }
필요한 코드인가요?

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/Model/Product.swift
> +    let identifier = UUID()
UUID 말고 다른 방법은 없을까요?

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/BaseView.swift
> +        return segmentedControl
아래 `attribute()` 메소드가 있는데, 이 코드와 차이는 뭔가요?
코드를 메소드와 클로저로 나누는 기준이 궁금합니다.

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/CellUIComponent.swift
> +    }()
lazy var를 사용한 이유가 있나요?
여기뿐만 아니라 lazy var를 많이 사용하고 계신데, 이유가 있을까요?

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ProductGridCell.swift
> +    }
이미 newItem이라는게 매개변수 레이블로 들어가있으니 아래와 같이 바꾸는게 나아보입니다.
```suggestion
    func update(_ newItem: Product) {
        guard item != newItem else { return }
        item = newItem
        setNeedsUpdateConfiguration()
    }
```

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ProductGridCell.swift
> +        setNeedsUpdateConfiguration()
이 메소드를 호출해준 이유는 뭔가요?

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ProductGridCell.swift
> +        cellUIComponent.thumbnailImageView.image = image
layout 메소드를 매번 불러주는 이유가 있을까요? 데이터를 반영하려는 의도를 가진 코드 같은데요. 이 부분은 model이 전달될 때 해도 되는거 아닐까요?

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ProductGridCell.swift
> +    }
이부분은 view에서 할 일이 아니라 다른 레이어에서 할 일 같습니다.
또한 url을 data로 변경하는 작업이 메인스레드에서 일어나고 있나요? 백그라운드 쓰레드에서 일어나고 있나요?

2022-05-19 01:56 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ProductGridCell.swift
> +    }
이미지를 받아오는 작업은 비동기 작업입니다. 그런데 셀이 재사용되면서 이전 이미지 리퀘스트가 남아있고, 해당 리퀘스트에 대한 리스폰스로 이미지가 넘어오면서 원치않는 이미지가 반영되는 이슈는 없었나요?
있었다면 이 메소드의 특성을 활용해 task를 취소해줘야합니다.

2022-05-19 08:34 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 14.0;
setNeedsUpdateConfiguration()
UICellConfigurationState
UIConfigurationStateCustomKey
UICollectionLayoutListConfiguration
UICollectionViewCompositionalLayout.list(using: configuration)
UICollectionView.CellRegistration<ProductListCell, Product> { }
collectionView.dequeueConfiguredReusableCell(using: listCellRegisteration, for: indexPath, item: itemIdentifier)

is only available in iOS 14.0 or newer
위 메서드나 타입을 사용하게되면 위와 같은 에러가 나옵니다.
그래서 target 버전을 올리게 되었습니다.😢

2022-05-19 12:32 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    var currentSnapshot: NSDiffableDataSourceSnapshot<Section, Product>! = nil
접근 제어자 수정([b404da5](https://github.com/yagom-academy/ios-open-market/pull/152/commits/b404da5f66589cc1d9c7507aa482f7223de2e53d))하고 강제 언래핑하지 않도록([563a7de](https://github.com/yagom-academy/ios-open-market/pull/152/commits/563a7de9b7a1230adae3542980774b5a0affc8fd)) 수정했습니다.

2022-05-19 12:47 UTC, papriOS commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    lazy var baseView = BaseView(frame: view.bounds)
[0755250](https://github.com/yagom-academy/ios-open-market/pull/152/commits/0755250481f9e4289f47d5c1c2d758955e9e2c71)
BaseView에 layout()메소드를 만들어 오토레이아웃으로 제약을 걸어주었습니다.

2022-05-19 13:14 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        view = baseView
올라프가 얘기하시는 다른 라이프사이클이 혹시 viewWillAppear() 일까요?

지금은 상관없지만 셀을 눌렀을 때 화면전환을 하면(push로 화면전환) 매번 viewWillApear이 호출될 것 같습니다. 그러면 매번 view를 갱신하게 되는데 이 과정이 매번 필요할까 의문이 듭니다.

혹시 다른 라이프사이클에서 view를 바꾸는 것을 권하신 이유가 있을까요?

2022-05-19 13:14 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    }
접근 제어자 수정했습니다! ([b404da5](https://github.com/yagom-academy/ios-open-market/pull/152/commits/b404da5f66589cc1d9c7507aa482f7223de2e53d))

2022-05-19 13:29 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
조언해주신 것처럼 데이터를 가져오는 타입을 따로 만들어서 그 타입의 메서드를 뷰 컨트롤러에서 호출하는 것으로 수정했습니다.

[a1c7f32](https://github.com/yagom-academy/ios-open-market/pull/152/commits/a1c7f32b4c625e4a0ebe08031bff43f44514dfee)

2022-05-19 13:49 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        let ifFirst = currentSnapshot == nil
is로 시작하게 네이밍 변경했습니다!

[563a7de](https://github.com/yagom-academy/ios-open-market/pull/152/commits/563a7de9b7a1230adae3542980774b5a0affc8fd)

2022-05-19 13:50 UTC, papriOS commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        self.configureDataSource()
configureDataSource() 메소드에서는 cell registration과 dataSource 설정 두가지를 모두 진행합니다.
저곳에서 dataSource 설정을 해주지 않는다면 segmetedControl의 값을 변경했을때 girdCell이 나오질 않아서, 설정은 해줘야했기 떄문에  cell registration이 이뤄지는 부분은 따로 메소드로 빼주어 viewDidLoad()에서 수행하도록 하였습니다.
[61010c7](https://github.com/yagom-academy/ios-open-market/pull/152/commits/61010c73f424d15d402aab0acab5a811ebb2ed81)

2022-05-19 13:50 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +
불필요한 공백 삭제했습니다!

[563a7de](https://github.com/yagom-academy/ios-open-market/pull/152/commits/563a7de9b7a1230adae3542980774b5a0affc8fd)

2022-05-19 14:15 UTC, papriOS commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
segmentedControl에서 선택된 값에 따라 collectionView에서 사용될 cell의 종류가 달라져야하기 때문에 분기문을 작성해 보았습니다. 불필요한 분기문 같다 말씀해주셨는데, 왜 그리 말씀해 주셨는지 잘 모르겠습니다... 😭 저희가 DiffableDataSource에 대한 이해가 부족해서 그런걸까요.. 힌트를 조금만 더 부탁드립니다!!

2022-05-19 14:25 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +}
감사합니다! 조언해주신 메서드를 사용해서 paging 진행했습니다!

[73a8982](https://github.com/yagom-academy/ios-open-market/pull/152/commits/73a8982a1ef11740134a1244f68b9e99dbfc939d)

2022-05-19 14:29 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/RegisterProductViewController.swift
> +    }
불필요한 코드 삭제했습니다.

[b86f376](https://github.com/yagom-academy/ios-open-market/pull/152/commits/b86f376e7c3a81ff4298c5a3baf9e4fcb9bb9e1f)

2022-05-19 14:54 UTC, papriOS commented on OpenMarket/OpenMarket/View/BaseView.swift
> +        return segmentedControl
아래의 `attribute()` 메소드는 `BaseView`의 요소를 설정하기 위함이므로 해당 클래스의 메소드로 작성하였습니다.
위의 코드는 BaseView의 프로파티인 segmentedControl를 설정하는 부분이라, 메소드로 빼내기 보단 클로저로 작성해보았습니다.

2022-05-19 15:13 UTC, papriOS commented on OpenMarket/OpenMarket/View/CellUIComponent.swift
> +    }()
lazy 키워드를 사용하게 되면 초기화 시점을 해당 변수가 처음 참조, 이용되는 시점으로 지연할 수 있다고 알고있습니다. 
저희가 UI 컴포넌트 프로퍼티들에 lazy를 붙이면 사용되는 시점에 클로저내 연산으로 메모리에 올라가게 하여 리소스 낭비를 막을 수 있다고 생각해 사용해 본 것입니다!
다만 생각해보니, CellUIComponent의 UI컴포넌트들 중 초기화 시점이 늦춰져야 하는 경우가 있다면 lazy를 써야겠지만 지금 해당 프로젝트에서는 그런 경우가 없어 var로 사용해도 될 것 같습니다

2022-05-19 15:44 UTC, papriOS commented on OpenMarket/OpenMarket/View/ProductGridCell.swift
> +        setNeedsUpdateConfiguration()
> The system calls this method automatically when the cell’s [configurationState](https://developer.apple.com/documentation/uikit/uitableviewcell/3601056-configurationstate) changes, as well as in other circumstances that may require an update.
이라는 공식문서 내용을 뒤늦게 확인했습니다! 불필요하여 삭제했습니다.
[b83ebaf](https://github.com/yagom-academy/ios-open-market/pull/152/commits/b83ebaf7fc4401d74f6ac92529e9d75d95bf5dd7)

2022-05-19 15:48 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/View/ProductGridCell.swift
> +        cellUIComponent.thumbnailImageView.image = image
cell을 초기화하는 과정에서 layout()을 호출해서 레이아웃 설정을 진행하기 때문에 굳이 여기서 호출할 필요가 없어보입니다.
불필요한 코드로 판단하여 삭제했습니다.

[5ac68b8](https://github.com/yagom-academy/ios-open-market/pull/152/commits/5ac68b85cd3017fa57651fc7858b8aacb67b69f6)

2022-05-19 15:54 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/View/ProductGridCell.swift
> +    }
조언해주신 것처럼 수정 진행했습니다!

[1e5067b](https://github.com/yagom-academy/ios-open-market/pull/152/commits/1e5067b1670d191e185f485b65285ddd4c6e072e)

2022-05-20 01:30 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/View/ProductGridCell.swift
> +    }
DataProvider 타입에서 fetchImage 메서드를 가지도록 수정했습니다.
또한, image를 cell에 넣는 부분이 main thread에서 수정하도록 수정했습니다.
dataTask로 이미지를 비동기적으로 가져오도록 했습니다.

[dbada19](https://github.com/yagom-academy/ios-open-market/pull/152/commits/dbada1927ee74b19c166f6123987c7f55fb43683)

2022-05-20 02:17 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/View/ProductGridCell.swift
> +    }
수정된 코드로 시뮬레이션을 돌리면 문제가 생깁니다.😢
grid로 갔다가 list로 올 때 이미지가 처음에는 sync가 맞지 않다가 1초 뒤에 sync가 맞아지는 문제가 생겼습니다.
왜 이런 문제가 생기는지 궁금합니다😭

2022-05-20 02:18 UTC, papriOS commented on OpenMarket/OpenMarket/View/ProductGridCell.swift
> +    }
cell이 프로퍼티로 imageFetchTask를 갖도록 하여,
updateConfiguration() 메소드가 호출이 되면 이미지를 받아오는 task를 해당 프로퍼티에 할당하고, 
prepareForReuse() 메소드에서 task를 취소할 수 있도록 수정해보았습니다!
[c8d62a1](https://github.com/yagom-academy/ios-open-market/pull/152/commits/c8d62a1f0dd065dede887a3b1e1288d7e1358772)

2022-05-20 02:36 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Model/Product.swift
> +    let identifier = UUID()
```swift
    func address(of object: UnsafeRawPointer) -> String {
        let address = Int(bitPattern: object)
        return String(format: "%p", address)
    }
    
    mutating func hash(into hasher: inout Hasher) {
        hasher.combine(address(of: &self))
    }
```

UUID를 사용하지 않는다면 위와 같은 방식으로 구분할 수 있을 것 같은데요.
위 방식이 적절한지와 다른 방법이 있는지가 궁금합니다🤔

2022-05-25 00:39 UTC, 1Consumption approved these changes
머지할테니 다음 스텝에서 반영하고 마무리 하시죠.

2022-05-25 00:39 UTC, 1Consumption commented on OpenMarket/OpenMarket/Scene/SceneDelegate.swift
> +        }
여기서 버전분기를 치지말고 MainViewController 내부에서 버전 분기를 치면 안되나요? 왜 클래스를 나눴을까요?
이러면 중복되는 코드가 발생하지 않을까요?

2022-05-25 00:39 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ContentUpdatable.swift
> +}
클래스로 상속을 해도 될 거 같은데, 그러지 않고 프로토콜 기본 구현으로 제공한 이유가 있을까요?

2022-05-25 00:39 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewControllerUnderiOS14.swift
> +}
DiffableDataSource의 미니멈 타겟은 13인데, 여기서는 왜 사용하지 않았나요? Step2의 핵심 경험은 `Modern Collection View 활용` 입니다.

2022-05-25 00:48 UTC, merged