오픈마켓 [STEP 2] marisol, Eddy
yagom-academy/ios-open-market pull request #153
Opened 2022-05-19 09:08 UTC by kimkyunghun3

안녕하세요 @jungseungyeo 두 번째 PR 보냅니다!
요번 스텝에서 많은 것을 배운 것 같으면서 어려운 부분이 많았네요😢
최선을 다해서 작성해서 보내드립니다!
잘부탁드립니다 😊

## 📝 구조 설명

### 기본 구조
- `MainViewController`: productView에서 구성한 view를 올리고, 네트워크 통신을 통해 받아온 데이터를 cell에 뿌려주는 역할
- `ProductView`: segmented control, collectionView, listLayout과 gridLayout을 구성하는 역할
- `ListCollectionViewCell`: MainViewController의 dataSource에서 받아온 데이터로 cell을 list 형태로 구성하는 역할
- `GridCollectionViewCell`:MainViewController의 dataSource에서 받아온 데이터로 cell을 grid 형태로 구성하는 역할 

## 🧐 고민한점 & 해결방법
### 📌 1. list cell과 grid cell에 dataSource의 data를 어떻게 뿌려줄까?
 
처음에 MainViewController의 makeDataSource 메서드 내부에서 데이터들을 가지고 cell을 구성해주었는데요, 그렇게 하다보니 makeDataSource 메서드가 너무 길어지고 역할 분리도 애매해졌다는 생각이 들었습니다. 그래서 configureCell이라는 메서드에 파라미터로 product를 받도록 하고, cell 내부에서 파라미터의 product 데이터로 cell을 구성해주도록 변경했습니다.

### 📌 2. collectionView의 cell에 구분선을 어떻게 만들어 줘야 할까?

cell마다 구분선을 주는 방법에 대해 오래 고민했습니다ㅠㅠ 다른 캠퍼들에게 조언을 구해 view를 얇게 만들어서 넣는 방법이 있다는 것도 알게 되었고, CALayer를 extension해서 bottom에 구분선을 넣어주는 방법도 알게 되어, CALayer를 extension하는 방법을 채택했습니다.
혹시 footer나 다른 방법으로도 구현할 수 있는 방법이 있을까요? 린생은 어떤 방법을 사용하시는지 궁금합니다!

```swift=
extension CALayer {
    func addSeparator() {
        let separator = CALayer()
        
        separator.frame = CGRect.init(x: 10, y: frame.height - 0.5, width: frame.width, height: 0.5)
        
        separator.backgroundColor = UIColor.systemGray2.cgColor
        self.addSublayer(separator)
    }
}
```

---

## ❓ 궁금한점
### 📌 1. List화면에서 Grid 갔다가 List로 넘어갔을 때 AccessoryUI 쪽이 더 생겨나는 버그
처음에 동일한 셀을 제대로 초기화하지 않고 사용하기에 문제가 발생한다고 생각했습니다. 
그래서 prepareForReuse() 메서드를 활용해서 하면 될 것이라고 생각했는데, 코드를 작성해보고 했으나 저희가 이해를 못한것인지 아니면 코드가 적절하지 않았던 것인지 제대로 작동이 되지 않습니다. 왜 이런 문제가 발생한 것일까요?

<img src="https://i.imgur.com/LjYL1Sp.png" width="500" height="800"/>

prepareForReuse는 두 cell에 작성했습니다
```swift

// ListCollectionViewCell
override func prepareForReuse() {
    super.prepareForReuse()
    productImage.image = UIImage(systemName: "swift")
    productName.text = nil
    currency.text = nil
    price.text = nil
    bargainPrice.text = nil
    stock.text = nil
    accessoryStackView.removeFromSuperview()
}

// GridCollectionViewCell.swift
override func prepareForReuse() {
    super.prepareForReuse()
    productImage.image = nil
    productName.text = nil
    currency.text = nil
    price.text = nil
    bargainPrice.text = nil
    stock.text = nil
}

```

### 📌 2. Layout 설정 한 것이 적절하게 동적으로 대응한 것인지?
저희가 레이아웃에서 일명 숫자를 활용해서 constraint를 맞추는 곳이 많아서 이렇게 해도 될지 궁금합니다. 이렇게 하게되면 동적으로 처리가 안될 것 같은데.. 저희가 다르게 생각해봐야 될까요? 

### 📌 3. DataSource 메서드 내부를 밖으로 캡슐화해서 빼는 방법이 없는지?
```swift 
guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: GridCollectionViewCell.identifier, for: indexPath) as? GridCollectionViewCell else {
    return UICollectionViewCell()
}

DispatchQueue.main.async {
    if collectionView.indexPath(for: cell) == indexPath {
        cell.configureCell(productDetail)
    }
}
```
이와 같은 코드가 분기에 따라 거의 동일하게 이루어지고 있어서 재사용성 있게 만들고 싶었는데, 이를 밖에서 메서드로 만들어서 호출하는 방법이 떠오르지 않습니다.

indexPath를 파라미터로 받으면 될 것 같은데, 그외에도 다른 요소들이 또 필요한 것같아서 메서드로 분리하다가 실패했는데 이 부분도 분리가 가능할지 궁금하네요!

### 📌 4. GridLayOut 보여줄 때 첫 화면의 위치
처음 GridLayout으로 가게되면 스크롤이 맨위에 있지 않고 바로 하나의 그룹 아래에 놓여져 있습니다. 원래 의도대로라면 GridLayout으로 가게되면 첫번째의 셀이 보여줘야되는데 이처럼 되는 현상이 무엇 떄문에 그런 것일까요? 이를 강제로 처음에 보여주게 만드는 방법을 사용해야할까요? 아니면 reuseCell과 같은 문제로 생긴 부분일까요?

### 📌 5. segmented control에서 selected되지 않은 segment의 색상 지정

선택된 segment는 selectedSegmentTintColor와 setTitleTextAttributes로 색을 정해줄 수 있었는데요,
selected되지 않은 segment에 대한 속성을 지정해줄 수 있는 방법을 찾지 못했습니다ㅠㅠ
LIST가 선택된 상태일때 GRID가 blue가 될 수 있도록 지정할 수 있는 방법이 있을까요?!

2022-05-19 13:24 UTC, jungseungyeo requested changes
고생하셨어요 마리솔, 에디 

# 🧐 고민한점 & 해결방법

### 📌 1. list cell과 grid cell에 dataSource의 data를 어떻게 뿌려줄까?

`맞아요 configure이라는 ui를 업데이트하는 함수를 만들고 내부에서 매핑을 해주는게 일반 적입니다 :) `

### 📌 2. collectionView의 cell에 구분선을 어떻게 만들어 줘야 할까?

`흠.. 사실 기본 CollectionView를 사용하면 가능합니다. 하지만 커스텀이 불가능하여 일단적으로 만들어주는 편이예요. 만들어 주었다고 이상할수있지만, 괜찮습니다. 저도 자주 사용하는 방법입니다. `

# ❓ 궁금한점

### 📌 1. List화면에서 Grid 갔다가 List로 넘어갔을 때 AccessoryUI 쪽이 더 생겨나는 버그

`원인을 보니 문제가 많이 보이네요. 

1. cell configureCell에서 addSubview를 하고 있음
2. prepareForReuse()에서 configureCell에서 넣어준 view를 remove하고 있지 않음

위의 두가지 문제로 보이네요. 값을 controller에서 정리를 하지 않고 오다보니 view에서 로직이 부가 되게 되면서 발생하는 문제가 근본적인 문제로 보여요.

이 뷰를 넣을지 말지는 view가 결정하는게 아닌 controller가 결정 된 상태에서 동작이 되어야 될거같네요.

### 📌 2. Layout 설정 한 것이 적절하게 동적으로 대응한 것인지?

`대체로는 비율로 적용하긴 합니다. 하지만 고정으로 해야 되는 경우도 있어서 이건 유동적으로 변경해서 작성하면 될 거 같습니다.`

### 📌 3. DataSource 메서드 내부를 밖으로 캡슐화해서 빼는 방법이 없는지?

`흠.. 이 부분을 뺴낼려면 할 수 있는데 어차피 configure에서 한번 타입캐스팅이 되어야 하지 않나요? 구지 한다면 제네릭을 활용하여 넣어줄 수 있을거같긴한데 그것 보다는 지금의 형태가 더 맞는거 같아요. ㅎㅎ `

### 📌 4. GridLayOut 보여줄 때 첫 화면의 위치
![image](https://user-images.githubusercontent.com/32052386/169302609-f8ed5524-e3c1-42e1-8e60-feec4efa2836.png)

![image](https://user-images.githubusercontent.com/32052386/169302693-ec24a64e-3098-45c3-b890-78c89dee25e7.png)

`위의 이미지를 보면 시작 점 높이가 다른거 같아요. 위의 높이를 맞쳐준다면 해결이 될거같네요.`

### 📌 5. segmented control에서 selected되지 않은 segment의 색상 지정

`흠.. 선택되지 않는 화면은 backgroundColor를 보여주고 있지 않나요? 이 부분을 말하는게 맞을까요? `

에디, 마리솔, collectionView를 그리는 과정에서 문제가 좀 보여요. 코멘트를 달아서 해당 부분 수정해주세요 :)

2022-05-19 13:24 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/GridCollectionViewCell.swift
> +    var stock: UILabel = UILabel()
접근 제어자를 꼭 붙여주세요 :)

2022-05-19 13:24 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/GridCollectionViewCell.swift
> +        }
위의 계산 로직은 controller에서 해주어야 될거같아요 뷰의 역할은 보여주는 역할로 생각해주세요 controller에서 가공 된 정보를 넣어주세요 :)

2022-05-19 13:24 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/GridCollectionViewCell.swift
> +        productStackView.addArrangedSubview(stockLabel)
위의 코드도 하나의 extension을 활용해서 addArragedSubviews 라는 함수를 만들수있을거같아요

2022-05-19 13:24 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ListCollectionViewCell.swift
> +    private lazy var accessoryStackView = makeStackView(axis: .horizontal, alignment: .top, distribution: .fill, spacing: 5)
함수로 만들어 준 부분 좋네요 :)

2022-05-19 13:24 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Extension/CALayer+.swift
> +        separator.frame = CGRect.init(x: 10, y: frame.height - 0.5, width: frame.width, height: 0.5)
```suggestion
        separator.frame = CGRect(x: 10, y: frame.height - 0.5, width: frame.width, height: 0.5)
```

주로 협업에서는 .init이라는 함수를 축약해서 사용하는 편입니다 :)

2022-05-19 13:24 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Extension/String+.swift
> +    func strikeThrough() -> NSAttributedString {
필요한 기능을 확장해서 사용하는 모습 좋습니다 :)

2022-05-19 13:24 UTC, jungseungyeo commented on OpenMarket/OpenMarket/View/ProductView.swift
> +        }
위의 방법은 좋지 않아 보여요. 

1. 객체지향 은닉화 위반 
2. 불 필요한 default 값의 존재 
3. gridLayout, listLayout의 분리하여 관리가 필요

위의 3가지 이유가 될 수 있을거 같아요. 

Mordern Collection View의 장점 중 하나가 비동기 적으로 ui를 변경 할 수 있는게 있습니다. 

![image](https://user-images.githubusercontent.com/32052386/169291461-dfd14591-de47-487e-8e4b-691f52206a7f.png)

위의 그림 처럼 49번 라인에서 layout을 활용하면 비동기 적으로 변경이 가능 할 거 같아요.

비동기로 할려면 필요한 요소가

1. 뷰의 상태가 필요
2. 각 layout을 비동기적으로 주입

이런 코드가 들어가 있어야합니다. 

https://lickability.com/blog/getting-started-with-uicollectionviewcompositionallayout/#section-provider <- 글에서 
section provider를 참고해주세요 :)

2022-05-19 13:24 UTC, jungseungyeo commented on OpenMarket/OpenMarket/View/ProductView.swift
> +    func configureLayout() {
접급제어자를 꼭 붙여주세요 :)

2022-05-19 13:24 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +                if self.productView.segmentedControl.selectedSegmentIndex == 1 {
index로 구분하는 거는 좋지 않아요 특정 enum 값으로 변경 후 상태 값의 맞게 변경 하는 코드로 수정해주세요

2022-05-19 13:24 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +                        if collectionView.indexPath(for: cell) == indexPath {
인덱스를 검사하는 이유는 무엇인가요?

2022-05-19 13:24 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +                    DispatchQueue.main.async {
DispatchQueue의 시점이 잘 못 되어 있는거 같아요. 이 동작이 되는 시점을 reloadData()를 하게 되는 데 이 때 스레드를 메인으로 해준다면 문제가 없을거같아요.

reloadData를 호출하는 곳에서 DispatchQueue를 한다면 밑의 DispatchQueue와 같이 하나로 통일 할 수 있을거같아요.

2022-05-19 13:24 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +                    }
위의 코멘트 확인 해주세요 :)

2022-05-19 13:24 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/Products.swift
> +    var name: String
var로 변경한 이유가 있나요?

2022-05-19 13:24 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Application/SceneDelegate.swift
> +        self.window?.rootViewController = navigateViewController
코드의 통일성은 중요해요 ㅎㅎ self를 아래와 위에 적용을 안했다면 여기도 동일하게 사용하지 않으면 좋을거같아요 ㅎㅎ

2022-05-19 13:24 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/GridCollectionViewCell.swift
> +        configurePriceUI()
재사용시 append를 하고 있다면 prepareForReuse()에서 remove를 해주어야 될거같네요. 기존에 사용했던 ui의 형태가 그대로 노출되고 있습니다.

2022-05-20 05:52 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Controller/GridCollectionViewCell.swift
> +    var stock: UILabel = UILabel()
내부에서만 쓰이니까 private 붙여서 수정했습니다!

2022-05-20 05:52 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/View/ProductView.swift
> +    func configureLayout() {
`private` 붙여서 수정했습니다!

2022-05-20 06:38 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Extension/CALayer+.swift
> +        separator.frame = CGRect.init(x: 10, y: frame.height - 0.5, width: frame.width, height: 0.5)
축약으로 수정했습니다 :)

2022-05-20 06:39 UTC, marisol-develop commented on OpenMarket/OpenMarket/Controller/GridCollectionViewCell.swift
> +        productStackView.addArrangedSubview(stockLabel)
UIStackView를 extension하여 addArrangedSubviews로 한번에 여러 view들을 추가해줄 수 있도록 했습니다!

```
extension UIStackView {
    func addArrangedSubview(_ views: [UIView]) {
        for view in views {
            self.addArrangedSubview(view)
        }
    }
}
```

2022-05-20 06:39 UTC, marisol-develop commented on OpenMarket/OpenMarket/Extension/CALayer+.swift
> +        separator.frame = CGRect.init(x: 10, y: frame.height - 0.5, width: frame.width, height: 0.5)
감사합니다 ㅎㅎ 축약했습니다!

2022-05-20 06:40 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/View/ProductView.swift
> +    func configureLayout() {
이 부분이 실제 사용되는 곳이 MainViewController 에서 호출되기 때문에 접근제어를 더 좁게 할 수 없을 것 같은데, 다른 의도가 있으셨던 것인가요?

2022-05-20 06:41 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Model/Products.swift
> +    var name: String
저희가 어떤거 누르다가 잘못 수정되었나봐요ㅠㅠ 상수로 다시 바꾸었습니다! 주의하겠습니다!

2022-05-20 06:41 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Application/SceneDelegate.swift
> +        self.window?.rootViewController = navigateViewController
앗..위에서 안썼는데 갑자기 썻군요..인지하지 못했었습니다. 다음부터 신경써서 통일하게 유지하겠습니다!

2022-05-20 06:43 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Controller/GridCollectionViewCell.swift
> +        configurePriceUI()
말씀해주신 것을 보고 확인해보니 그대로 노출되고 있어서 사용되는 StackView에 있는 할당된 subViews들을 모두 반복문을 통해 제거해주었습니다!
```swift
// ListCollectionViewCell.swift
    override func prepareForReuse() {
        super.prepareForReuse()
        priceStackView.arrangedSubviews.forEach {
            $0.removeFromSuperview()
        }
        
        productStackView.arrangedSubviews.forEach {
            $0.removeFromSuperview()
        }
        
        accessoryStackView.arrangedSubviews.forEach {
            $0.removeFromSuperview()
        }
        
        entireProductStackView.arrangedSubviews.forEach {
            $0.removeFromSuperview()
        }
    }

// GridCollectionViewCell.swift
    override func prepareForReuse() {
        super.prepareForReuse()
        productStackView.arrangedSubviews.forEach {
            $0.removeFromSuperview()
        }
        
        priceStackView.arrangedSubviews.forEach {
            $0.removeFromSuperview()
        }
    }
```

2022-05-20 06:52 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +                        if collectionView.indexPath(for: cell) == indexPath {
저희가 배운 거에서 Prefetch와 Cache부분이 정확하게 이해하지 못해서, 그 전에 활동학습 때 배운 바로는 이와 같이 쓴 이유로는 만약 고화질 이미지를 업로드하게되면 이미지 업로드 되는 시점에 길어지게 되고 유저가 그 시점에 스크롤하게 되면 동일한 셀에 뿌려지지않는 오류가 발생할 수 있습니다.
그래서 이를 방지하기 위해서 클로저 캡쳐를 통해 indexPath, cell를 처음 이미지 업로드하려는 시점에 캡쳐해둔 다음 이미지 업로드가 완료되었을 때 보이는 셀과 indexPath의 위치가 동일하게 되면 이미지를 뿌려주고 그게 아니면 업로드한 이미지를 버려줌으로써 이상한 셀에 뿌려지는것을 방지하기 위해 썼습니다. 혹시 이 의도가 잘못되었나요?

2022-05-21 02:19 UTC, merged

2022-05-21 08:34 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/View/ProductView.swift
> +        }
먼저 enum를 통해 rawValue를 활용해서 은닉화를 하도록 했습니다. 그래서 이로 인해 불필요한 default switch문을 없앨 수 있었습니다. 또한 내부에서 메서드를 통해 어떤 Layout인지 확인 후 그에 적절한 Section를 return 했습니다. 
```swift
private enum LayoutType: Int {
    case list = 0
    case grid
    
    func section() -> NSCollectionLayoutSection {
        switch self {
        case .list:
            let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0), heightDimension: .fractionalHeight(1.0))
            let item = NSCollectionLayoutItem(layoutSize: itemSize)
            item.contentInsets = NSDirectionalEdgeInsets(top: 0, leading: 7, bottom: 0, trailing: 7)
            
            let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0), heightDimension: .estimated(70))
            let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize, subitem: item, count: 1)
            
            let section = NSCollectionLayoutSection(group: group)
            section.contentInsets = NSDirectionalEdgeInsets(top: 5, leading: 5, bottom: 5, trailing: 5)
            
            return section
        case .grid:
            let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1/2), heightDimension: .fractionalHeight(1.0))
            let item = NSCollectionLayoutItem(layoutSize: itemSize)
            item.contentInsets = NSDirectionalEdgeInsets(top: 10, leading: 10, bottom: 10, trailing: 10)
            
            let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0), heightDimension: .estimated(270))
            let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize, subitem: item, count: 2)
            
            let section = NSCollectionLayoutSection(group: group)
            section.contentInsets = NSDirectionalEdgeInsets(top: 5, leading: 5, bottom: 5, trailing: 5)
            
            return section
        }
    }
}
```

이제 그리고 이를 위에서 말씀해주신 초기화 방식에서 Layout를 결정할 수 있으므로 segmentedControl에서 정해진 LayoutType를 이곳에서 초기화해주면 변경이 자유롭게 되는 것을 확인할 수 있었습니다.

```swift
    private lazy var layouts: UICollectionViewCompositionalLayout = {
        return UICollectionViewCompositionalLayout(sectionProvider: { _, _ in
            return LayoutType.section(self.layoutType)()
        }, configuration: .init())
    }()
```

2022-05-21 08:44 UTC, marisol-develop commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +                    DispatchQueue.main.async {
여기서 DispatchQueue.main.async를 사용했던 이유는, cell에 데이터를 뿌려주고 cell의 UI를 관리하는 부분이라고 생각했기 때문이었습니다.

reloadData를 하는 시점은 layoutType이 didSet되었을 때인데, 이때 DispatchQueue.main.async를 해줘야 한다는 말씀이실까요? 

reloadData 하는 시점에서 main.async를 해주고 현재 makeDataSource 내에서의 스레드 설정을 없애면 데이터가 로드되지 않는 것 같습니다ㅠㅠ

DispatchQueue를 하나로 어떻게 통일할 수 있을지 아직 잘 이해를 못했습니다ㅠㅠ🥲

2022-05-21 08:57 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +                if self.productView.segmentedControl.selectedSegmentIndex == 1 {
아래처럼 수정했습니다!
```swift
 guard let layoutType = LayoutType(rawValue: self.productView.segmentedControl.selectedSegmentIndex) else { return UICollectionViewCell() }
                
                switch layoutType {
                case .list:
                    guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: ListCollectionViewCell.identifier, for: indexPath) as? ListCollectionViewCell else {
                        return UICollectionViewCell()
                    }
                    
                    DispatchQueue.main.async {
                        if collectionView.indexPath(for: cell) == indexPath {
                            cell.configureCell(product)
                        }
                    }
                    
                    return cell
                    
                case .grid:
                    guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: GridCollectionViewCell.identifier, for: indexPath) as? GridCollectionViewCell else {
                        return UICollectionViewCell()
                    }
                    
                    DispatchQueue.main.async {
                        if collectionView.indexPath(for: cell) == indexPath {
                            cell.configureCell(product)
                        }
                    }
                    
                    return cell
                }
            })
        
```