오픈 마켓 [STEP 2] 두기, minseong
yagom-academy/ios-open-market pull request #154
Opened 2022-05-19 11:37 UTC by doogie97

@jungseungyeo
안녕하세요! 린생! STEP2 완료해서 PR보냅니다!
근데 지금 
![image](https://user-images.githubusercontent.com/82325822/169284410-6272f666-103b-413b-9bad-5123d3bc11a9.png)
위와 같이 충돌이 발생했는데 코드에 대한 리뷰는 받아야 할 것 같아 PR보내게 되었습니다...!
충돌은 빠르게 해결해보도록 하겠습니다!

잘부탁드립니다!😁😄

## 고민한 점

### 1. 세그먼트 움직였을 때 셀의 위치
![](https://i.imgur.com/AGR6dc8.png)
list모드 최 상단에서 grid모드로 바꿨을 때 cell의 위치가 최 상단이 아닌 현상이 있었습니다
스크롤 해보고 바꿔보고 했을 때 어느 정도 위치를 공유 하는 것 같기는 한데 왜 grid는 최상단의 cell이 바로 나오지 않는지 궁금합니다

### 2. cell들을 하나로 묶어주기 위한 추상화

cell이 두개로 나눠져 있다보니 셀을 구성해주는 메서드가 두개가 생겼습니다
그래고 해당 로직은 ListCell인지 GridCell인지만 다르고 모두 동일해서 메서드를 통합해주고자 cell의 추상화를 시도하였습니다

![](https://i.imgur.com/vOYLIxE.png)
위와 같이 ItemCell의 구성 요소에 필요한 타입들을 기본 변수로 설정하고

![](https://i.imgur.com/GG1sqs4.png)
ItemCell 구성시 해당 뷰에 직접 접근하는게 아닌 기본 변수의 요소들로 뷰를 구성하게 처리하였습니다

### 3. cell을 불러올 때 마다 서버에서 data를 가져오는 문제
![](https://i.imgur.com/65c6dJU.png)

위와 같이 셀을 설정하는 `setCellComponents`메서드가 서버에서 data를 가져오는`getItemPage`메서드 안에 있다보니 getItemPage를 셀 구성시마다 호출해야하는 문제가 생겼습니다

그래서 이 문제를 해결하고자 한번 가져온 data(=ItemPage)를 전역으로 두기로 하였습니다. 

그런데 이렇게 하면 최초 어플 실행시 뷰가 업데이트 되지 않는 상황이 발생함
![](https://i.imgur.com/5ce7zIG.png)

왜그런가 고민해봤더니 getItem안에 있는 request는 escaping 메서드로 그 안에서 setCellComponents를 실행하게 되면 서버에서 데이터를 받아 오고나서 cell세팅을 시작하였습니다
근데 이걸 나눠서 실행하게 되면 데이터는 데이터대로 가져오고 setCellComponents는 setCellComponents대로 실행이 되는데 최초 어플 실행시에는 전역에 설정한 itemPage가 nil이기 때문에 cell구성이 되지 않는 상황이 발생하였습니다

결론적으로 빈 초기화를 할 수 없는 itemPage가 아닌 Item배열을 전역으로 두었으며 빈 배열을 만들고 아이템에 변경사항이 생길 때 마다 collectionView를 reload하게 하였습니다
(cell에서는 ItemPage내에서도 Item의 요소들만 사용하기 때문에 이렇게 하였습니다)

#### 4. 로컬 캐시 구현
캐시 구현은 사실 Bonus Step의 요구 사항이지만 오늘 활동학습에서 배웠는데 NSCache의 경우 적용 방법이 어렵지 않기도 했고 아직 PR 요청 전이어서 NSCache를 통해 아래와 같은 문제를 해결해 보고자 하였습니다

문제점 - item같은 경우에는 전역으로 저장해주만 이미지의 경우는 계속해서 다운로드를 해주고 있는 로직이기 때문에 이미지를 사용할 때마다 서버로부터 요청하는게 비효율적이라고 생각

+이미지만 캐싱한 이유

NsCache의 딕셔너리의 value값으로 오려면 class만 올 수 있는 것으로 확인했습니다
근데 data모델들은 struct로 구성을 했고 이걸 class로 다 바꿔줘야 할까? 라고 고민하던 중
1페이지에 20개의 아이템이 있는 json파일의 크기를 봤더니 5kb밖에 안됐다(이미지는 하나당 24kb정도 되는 것으로 확인)
api에 있는 모든 아이템을 다 가져온다고 하더라도 350kb밖에 안되서 굳이 class로 바꿔 캐싱을 해줄 필요없이 배열에 저장해도 괜찮다고 생각이 들어 이미지만 cache를 사용하게 되었습니다

2022-05-19 11:56 UTC, doogie97 commented
![스크린샷 2022-05-19 오후 8 42 39](https://user-images.githubusercontent.com/82325822/169287520-287cd5f3-ae50-4538-b3b0-c3a1d59c064b.png)

PR 보낸 후 github에서 제공하는 conflict 해결 기능이 있어서 이거로 해결하였습니다!

2022-05-19 15:41 UTC, jungseungyeo requested changes
고생하셨습니다. 두기, 민성 

### 1. 세그먼트 움직였을 때 셀의 위치
![image](https://user-images.githubusercontent.com/32052386/169335780-9288e3c5-74f9-42a4-a556-dc9d1899ac8d.png)

`코드를 확인해보니 indexPath가 그리드 뷰로 변경이 0으로 시작하지 않아서 발생하는 문제같네요.

위 이미지를 보면 2부터 시작하고 있어요. 그래서 collectionview를 reload하면 3번째 이미지로 포커스가 되는거같습니다. 

openMarketCollectionView.scrollToItem(at: .init(item: 0, section: 0), at: .top, animated: false)
`

### 2. cell들을 하나로 묶어주기 위한 추상화

`이 부분은 고민 해 볼 필요가 있을거같아요. 추상화 작업은 좋지만 프로퍼티가 노출되게 되어서 좋지 않아요. 프로퍼티는 노출하지 않는 방식으로 추상화되면 더욱 좋을거같아요.`

### 3. cell을 불러올 때 마다 서버에서 data를 가져오는 문제

`흠.. 질문이 무엇인지 이해가 잘 되지 않네요..ㅠ 다시 질문해주시면 좋을거같아요 ㅎㅎ`

### 4. 로컬 캐시 구현

`캐시를 적용하신 부분 좋습니다.  그래도 이부분은 imageView를 확장해서 구현하면 더욱 좋을거같아요. 이 코드를 전역적으로 공통화 로직으로 이용 될 수 있는 코드로 의존적으로 함수를 작성하는 것 보다는 전역적으로 사용 가능한 함수를 만들면 더욱 활용도가 좋을거같아요 ㅎㅎ`

두기, 민성 고생하셨습니다. 

몇가지 수정 사항이 있습니다. 

1. 캡슐화
2. index 조건
3. protocol의 적용

위의 3가지가 크게 수정이 필요해보입니다. 특히 protocol인데요. ItemCellable로 추상화는 좋지만 값을 노출하지 않는 방법으로 해주면 좋을거같아요 또 setCellComponents에서 어차피 collectionViewCell로 타입캐스팅을 한다면 구지 추상화를 할 필요가 있나요? 이 부분 고민해서 수정하면 좋을거같아요 :) 

추상화를 하면서 객체지향을 위반하지 않는 방법으로 하면 좋을거같아요 :)

2022-05-19 15:41 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/GridCell.swift
> +    }
위의 코드들은 캡슐화를 모두 위반하고 있어요. 캡슐화를 지키면서 사용하는 방법을 사용해주세요. 또 내부에서 분기 처리가 되어 있어요 view의 역할을 한번 고민하고 적용하면 좋을거 같아요.

2022-05-19 15:41 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ListCell.swift
> +    }
위의 코드 보다는 configure와 같은 함수를 적용하여 ui를 업데이트하면 좋을거같아요. 위의코드가 존재하여 외부에서 값이 접근이 되어 은존성이 생성되고 있어요. 또 위의 값은들 특정 값을 가지고 있죠? 이러거는 model과 같은 느낌을 주고 있어요. view에서 값을 모르게 하는게 중요해요

2022-05-19 15:41 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +    private let gridCellName = String(describing: GridCell.self)
이 값이 프로퍼티로 있지말고 생성시 직접 주입해주면 좋을거같아요. 프로퍼티로 존재하면 관리를 해야 되어서 가독성이 떨어질거같아요.

2022-05-19 15:41 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +                self.openMarketCollectionView.reloadData()
model이 저장되면 ui를 업데이트하네요 ㅎㅎ 너무 좋습니다.

2022-05-19 15:41 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +    private func getImage(itemCell: ItemCellable ,url: String, indexPath: IndexPath) {
이 부분은 uiImageView를 extension하여 구현하면 더 좋을거같아요. image를 가져오는 코드는 여기서만 사용하지않고 전역적으로 사용할거같아요. 공통코드를 작성하여 해결하면 좋을거같아요.

2022-05-19 15:41 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +                itemCell.stock = self.items[indexPath.row].stock
캡슐화를 위반하고 있어요. 캡슐화를 꼭 지켜주세요.

2022-05-19 15:41 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +        if sender.selectedSegmentIndex == 0 {
index로 값을 비교하는거는 좋지 않아요 enum을 활용하여 상태값을 두고 사용해주세요 :)

2022-05-19 15:41 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +        if collectionViewSegment.selectedSegmentIndex == 0 {
위의 코멘트와 동일하게 index로 값을 비교하지말고 상태값으로 비교하면 좋을거같아요.

2022-05-19 15:41 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ItemCellPotocol.swift
> +    var stock: Int { get set }
이 프로토콜은 역할이 모호한거 같아요 추상화하는거는 좋지만 프러퍼티를 노출하면 안될거같아요.

2022-05-19 15:41 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +                break
실패의 경우도 작성해주세요 :)

2022-05-19 15:41 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +            gridCell.layer.borderWidth = 1
이거는 gridcell 내부에서 설정 되면 더욱 좋을거같아요.

2022-05-19 15:41 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +        if indexPaths.last?.row == items.count - 1 {
이 부분 좋아요 ㅎㅎ 여기도 개선 점이 좀 보여요. 요청을 하고 서버의 응답이 요지 않고 있는 경우 이 함수를 다시 true가 되는 경우가 있을거같아요. 수정하면 좋을거같아요. :)

2022-05-20 02:45 UTC, doogie97 commented on OpenMarket/OpenMarket/Controller/GridCell.swift
> +    }
말씀해주신 대로 프로퍼티가 아닌 메서드를 통해 추상화를 하여 캡슐화를 시켜주었습니다

2022-05-20 02:52 UTC, doogie97 commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +            gridCell.layer.borderWidth = 1
gridCell로 이동하였습니다!

2022-05-20 06:56 UTC, doogie97 commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +                break
getItemPage실패에서는 다시 데이터를 불러올 수 있도록, getImage실패에서는 임시 이미지를 할당할 수 있도록 처리해 주었습니다

2022-05-20 07:06 UTC, doogie97 commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +        if indexPaths.last?.row == items.count - 1 {
이 부분은 저희가 잘 이해를 하지 못했습니다

전역으로 설정해둔 hasNext를 말씀하시는거라면 마지막 페이지를 제외하고는 false인 경우가 없고 false에서 true로 바뀌는 로직도 없어서 어떤 경우가 다시 true가 될 것이라고 생각하셨는지 궁금합니다!

2022-05-21 02:19 UTC, merged