오픈마켓 II [STEP 1] Red, 마이노
yagom-academy/ios-open-market pull request #155
Opened 2022-05-25 17:07 UTC by Mino777

안녕하세요 엘림!! @lina0322
STEP3 완료 했습니다!
남은 일정동안 일정이 맞지않아서 너무 급하게 진행하다보니 부족한 점이 많습니다😭
이번 프로젝트도 잘 부탁드립니다! 항상 좋은 리뷰 주셔서 감사합니다!!🙇‍♂️🙇‍

## 저번 리뷰에 대한 reple

> 저는 여기는 오히려 네트워크 쪽이라서, 얼마든지 self가 해제될 수 있을 것 같아서 weak 필요할 수 있을 것 같습니다🙏
참고 문서 한 번 보시면 좋겠어욥💪

self 해제 될 수 있다는 부분은 이해했는데,
그게 네트워크 쪽인 것과 무슨 상관 관계가 있는 것인지 이해하지 못했습니다.😭😭

>제가 생각하는 이유 두가지를 간단히 말하자면!
extension보다 protocol로 되어있을때 좀 더 명확히 알 수 있는 것 같아요
저 같은 경우에는 회사에서도 하고, 여기서 리뷰하기도하고, 동아리에서도 코드 작성을 하는데
요런 프로토콜을 채택 했는지 안했는지 보면서
아, 내가 이거 구현해서 해야하는구나, 아 여기 있구나 하는 걸 알 수 있는 것 같습니답.
두번째로는 보통 요런거 구현을 하면, 내부에서 register하는거나 dequeue하는 것들도 다시 랩핑해서 만드는 것 같아요
해당 기능들은 또 모든 셀에는 필요한 것이 아니라서 protocol에서 구현하는 것 같고요!
제 생각에는 두가지 이유가 있을 것 같은데, 제 의견을 들어보시니 어떠실까용ㅎㅎ

넵 프로토콜이 조금 더 청사진 같다는 느낌을 받았습니다.
그렇게 수정하였습니다. 감사합니다.😁

## 프로젝트 참고사항
### 수정 기능
현재 수정 부분에서 요구사항에 수정에 대한 API가 없는 부분과 수정시에 identifier 설정 및 secret 설정 부분에 대한 내용이 없어서 우선 UI만 구현해두었습니다.
Main 화면에서 각 셀을 선택하는 경우에 상세화면 API로 데이터를 받아 수정모드의 화면으로 전환되도록 우선 진행하였습니다.

## 고민한 점
### textView keyboard hide
textView 작성시에 keyboard가 올라오는 경우 바깥의 뷰를 터치해야 내려가게끔 진행을 하면 범위가 너무 작아 어려움이 있었습니다. 그래서 해당 부분의 경우 키보드에 툴바를 넣어주어서 키보드를 내려주는 버튼을 만들어 주었습니다.

### Post 후 Main 화면의 데이터를 리로드하는 시점
등록 화면에서 Post를 한 후에 메인 화면으로 이동했을 때 데이터를 리로드하는 부분에서 Notification을 사용할지, 메인 화면의 생명주기에서 리로드를 해줄지 고민하였고, 메인 화면의 생명주기에서 리로드를 하는 것으로 진행하였습니다. Post 요청 메서드에서 escaping closure를 통해 요청을 성공 했을 때 dismiss가 되도록 하였습니다. 

### 특정한 셀에만 button 을 추가하는 기능 
imagePicker 를 불러오기 위한 마지막 셀을 만들어 주기 위해, 
처음에는 trailing footer 를 추가해야 겠다고 생각했습니다.
composition layout 에서 footer 를 추가하는 기능이 iOS14 버전부터 사용가능했기 때문에, composition 과 flow layout 의 기능을 섞어서 사용해야 하는 일이 일어났습니다. 😞😞😞

구현을 해보았지만 스크롤이 될 때 footer 도 같이 나타났다 사라질 것이라는 저희의 예상과 달리 footer 가 고정이 되어서 움직이지 않았습니다. 
<img src="https://i.imgur.com/mPwsPxq.png" width="300">

그래서 header footer 가 아니라 section 을 나눠보자! 라고 생각하고 다른 section 에 넣어주려고 시도하였으나 `NSDiffableDataSourceSectionSnapshot` 도 iOS14 버전부터 지원을 하여 iOS13 버전까지 진행해야하는 이번 프로젝트에는 적용을 못할 것 같았습니다. 😞😞😞

그래서 결국에 같은 셀로 구현을 하고 이미지를 만들어 넣어주었고, last index 인 셀에만 button 을 넣어주어, imagePicker 가 나올 수 있도록 구현했습니다!

## 조언이 필요한점 

### DTO 에 관한 네이밍

>보통 이런 종류의 모든 객체들은 데이터 통신을 위한 객체인데, 굳이 DTO를 붙이지 않아도?
ProductList만으로도 충분히 역할을 하는 것 같아서욥!
왜 굳이 필요하다고 느끼셨나욥??👀

해당 부분의 경우 쿼리, 바디를 위한 Request용 모델이라고 생각하여 DTO를 붙였었습니다!
다시 생각해보니 굳이 DTO라고 네이밍에 없어도 상관이 없을 것 같아 DTO는 제거하였습니다.
그런데 그러다보니 post를 위한 모델의 경우ProductsPost 라는 네이밍을 하였는데, 구조체의 네이밍에 http method를 넣는 것은 지양해야될까요?!

### scrollView!!!
textView 에 keyboard 가 가려지지 않게 하기 위해서, scrollView 자체의 contentInset 을 올려주고, managingView.topScrollView.scrollRectToVisible 을 조정해 주었습니다.

```swift
@objc private func keyboardWillShow(_ notification: Notification) {
    guard let userInfo = notification.userInfo,
          let keyboardFrame = userInfo[UIResponder.keyboardFrameEndUserInfoKey] as? CGRect else {
        return
    }
    managingView.topScrollView.contentInset.bottom = keyboardFrame.size.height

    let firstResponder = managingView.firstResponder

    if let textView = firstResponder as? UITextView {
        managingView.topScrollView.scrollRectToVisible(textView.frame, animated: true)
    }
}
```
그런데 textView 의 
```swift
textView.isScrollEnabled = false
```
로 설정해주었고 Hugging Priority 를 같은 stack 뷰의 있는 객체 중에 가장 낮게 설정해 주었습니다.

isScrollEnabled 를 false 로 한 것 때문인지, 만 아래까지 글자를 쓰게 되면 스크롤은 내려가지 않지만 보이지 않는 부분에서 계속 글자가 입력되는 현상이 일어나고 있습니다.

오히려 isScrollEnabled 의 속성을 true 로 바꾸면 아래로 내려갈 때는 문제가 없지만 위의 있는 글자들이 보이지 않습니다.😭😭😭
이 부분을 어떻게 해결해야 할까요? 

### 공통기능을 상속을 통해 구현 했을 때 캡슐화
이번에 공통기능에 class 를 사용하는 요소들이 많아서, 상속을 이용해 구현하였습니다. 그러니 부모 class 가 가지고 있는 요소들을 자식 요소들이 받아서 사용해야하기 때문에 대부분 private 을 풀어주게 되었습니다. 
이럴 경우 캡슐화가 재대로 이루어 지지 않는 것 같은 느낌을 받았습니다.
상속의 경우 자식에게 캡슐화가 이루어지지 않는 것은 당연한 것이니 이렇게 구현해도 괜찮은 걸까요? 엘림의 의견이 궁금합니다.

2022-05-27 12:52 UTC, lina0322 requested changes
또 만나서 반가워요~~ 
이번에도 힘내봅시다. 아마 힘든 한주였을거라고 생각되는데...ㅎㅎ 
두분 괜찮으셨나요??

---

### self
네트워크 통신된 부분은 비동기로 completion이 호출되는데, 이 때 self가 없는 상황일 수 있지 않을까요?
예를 들어 화면에 들어갈 이미지를 요청하고 다운로드중에, 그 화면을 닫았는데 completion이 호출되고 내부에 self를 사용한다면??🤔

### DTO
ㅎㅎㅎ차라리 Post보다 DTO가 나은 것 같ㄱㅣ도..... 그냥 Products가 되긴 어려웠을까용??
사실 이것도 회사나 사람마다 다를 수 있어서, 붙이는 곳도 있는 걸 알고있긴해욥😅

### scrollView
음, hugging을 가장 낮게 했다는건 자리가 비어있을때 내가 늘어나겠다는건데, 의도하신게 맞죠? 
원하는 view의 방향을 정확히 모르겠는데
일단 키보드 나왔을때 화면의 view자체 높이를 변경하거나 bottom을 올려주면 어떨까요?
iOS 키보드가 화면을 가릴때로 구글에 검색했더니
[이 글](https://icksw.tistory.com/87)이 가장 먼저 보이네요. 보면서 한 번 따라해보심을 추천드립니다.

### 캡슐화
어쩔 수 없는 부분이 분명히 있을거에요! 그래도 최대한 private을 빼지않게 노력해보면 좋을거같아요~

--- 

추가로 동작을 해보면서 느꼈던 부분들인데요.

상세페이지 갔다가 나오면 스크롤이 튀는 것 같아욥.

그리고 list에서 grid갔을때, list가 분명히 스크롤 안한상태인데 grid에서 상단이 짤립니다.

또, 상품 등록하러 들어갔다가 취소했을때 이전에 보여진 목록과 다른 목록이 보여욥..
서버가 이렇게 실시간으로 데이터를 바꾸진 않을 것 같은데ㅎㅎ;

등록한 다음에 제거가 맨 위에 있을 것 같은데.. 안그렇더라고요. 요건 서버에서 시간순으로 안줘서인가요?

이런것들 확인을 하고싶은데 refreshControl이 없더라고용~ 가능하면 구현 부탁드립니다🙏

등록할때 제목을 입력하거나, 가격을 입력하고나서 다음 칸에 가고싶은데 자동으로 넘어가지 않고 키보드를 가리는 기능만 있네요. 포커스 이동해주실 수 있을까요?

그리고 뷰 터치했을때, 입력 가능한 부분이면 포커스 이동하고, 사진이나 기타 다른 아무리 작은 뷰라해도 입력과 관련 없는 부분이면 키보드 내릴 수 있도록 해주세요!!

마지막으로 등록 눌렀을때 에러가 발생한(입력을 잘못한?) 텍스트 필드 혹은 뷰로 포커스 이동해주세욥ㅎㅎㅎㅎ

아, 찐찐막 
![스크린샷 2022-05-27 오후 8 41 16](https://user-images.githubusercontent.com/49546979/170692658-8389212d-e0ce-4de1-bb2d-30d61b5a36eb.png)

왜 인지 모르겠는데 저기 사진 등록 셀 아래보면 얇게 옆에 사진 하단이 남는데(???????) 이건 이유가 짐작이 안가네요ㅎㅎ 제 시뮬레이터 문제인거같기도하고 한번만 확인해주세요.

참고로 저는 iPhone12 iOS15.4 시뮬레이터에서 돌려보았습니다!!

요런식으로 아마 회사가게되면 다양한 QA 이슈들이 찾아올거에요ㅎㅎㅎ...
이번 스텝에 소화할 수 있는 것과, 다음 스텝에 녹여낼 수 있는 것, 그리고 기술적으로나 공수가 너무 많이 든다거나 하는 다양한 이유로 불가능한 것들을 구분해서 말씀해주시면 좋을 것 같아요.
(하지만 최대한 이번 스텝에서 모두 해결할 수 있으면 좋겠어요😭)

즐거운 주말 푹 쉬시고, 또 힘내서 달려봅시다ㅎㅎ
궁금한거, 이해안되는거, 막히는거 역시나 또 메세지로 말씀해주세요.

화이팅🎉

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Error/InputError.swift
> +    case imageIsFull
개인적으로 imageIsFull은 뭔가 사이즈가 꽉찬거같은 느낌이네요

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Extension/UITextField.swift
> +    func addKeyboardHideButton(target: Any, selector: Selector) {
모든 textField에서 필요하다고 판단하신거죠?👀

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Extension/UIView.swift
> +    var firstResponder: UIView? {
이 부분은 어떤 기능을 위해서 넣으신건지 설명해주실 수 있나욥?👀

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/DTO/ProductsPost.swift
> +    let boundary: String = UUID().uuidString
boundary는 어떤 역할을 하나요?🫡

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/DTO/ProductsPost.swift
> +struct ImageInfo: Encodable, Hashable {
Hashable은 어떤 프로토콜일까요?
이 구조체 다른 파일로 옮기면 어때요?🤔

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
> +    let vendor: Vendor?
productDetail이랑 ProductsPost이 매우 비슷해보이는데요.
Codable로해서 하나의 객체로 진행하긴 어려웠을까요?👀

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +    func retrieveProduct(with endpoint: Requestable, completion: @escaping (Result<T, Error>) -> Void)
retrieve? 검색하는건가욥? 어떤의미로 사용했을까요!🙂

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +    @discardableResult
오! 좋습니다. 이거 외에도 어떤 Attributes들이 있을까요??🤔

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/EndPoint/Requestable.swift
> +    func generateUrlRequestMultiPartFormData() -> Result<URLRequest, NetworkError> {
ㅎㅎㅎ multi part form 괜찮았나요..?😉

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Main/View/MainViewController.swift
>          viewModel.requestProducts(by: viewModel.currentPage)
뷰가 다시 나타날때마다 기존의 데이터를 다 비워주네요.
그리고 현재 페이지를 불러오는뎀.. 저는 첫 페이지는 다시 볼 수 없는건가요?🤔

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Main/View/MainViewController.swift
> +    @objc private func moveRegisterView() {
show, present등의 표현이 더 좋고, 여긴 selector니까 addButtonDidTap으로 가는것도 좋겠어요!

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Main/View/MainViewController.swift
>                      cell.updateLabel(data: item)
이미지 캐셔를 넘겨줘야하나요? 다소.. 구조가 어색하다는 생각이 들어요.
또 updateImage와 updateLabel 둘 다 cell을 set up - configure하는 동작이니, item만 넘겨서 하나의 함수로 만드는게 더 올바른 동작이될거같아요.

숙제 : cell.configure(data: item) 과 같이 하나로만 동작하게 해보기!😉

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Protocol/AlertDelegate.swift
> +}
AlertDelegate를 하나로해서 양쪽에서 다 사용하긴 어렵나요?🥹

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Main/View/MainViewController.swift
> +        let id = viewModel.items[indexPath.row].id
배열에 바로 index를 넣었는데, out of range라면 앱이 터질 수 있어요. 안전한 방법은 없을까요?😭

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Main/View/MainViewController.swift
> +            DispatchQueue.main.async {
좋아요, 왜 main에 async하게 작업했나요?
sync하게 작업하면 어떻게되죠?ㅎㅎ main queue에서는 어떤작업들이 이뤄지나요?😎

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Main/ViewModel/MainViewModel.swift
> +    private let productsDetailAPIService = APIProvider<ProductDetail>()
Provider가 T를 갖는 것 보다, 내부 함수가 T를 가졌다면 어땠을까요?🤔

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Main/ViewModel/MainViewModel.swift
>      var items: [Item] = []
items가 외부에 노출되면 위험하진 않을까요??😓

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Managing/Modify/View/ModifyViewController.swift
> +final class ModifyViewController: ManagingViewController {
modify랑 edit 둘 다 보이는거같은데 다르게 사용중인가욥?🙃

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Managing/Modify/View/ModifyViewController.swift
> +    }
LGTM👍

super.init과 self.init의 차이는 무엇인가요?
또 convenience, required init 이런것들은 어떤걸까요!!

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Managing/Modify/View/ModifyViewController.swift
> +        fatalError("init(coder:) has not been implemented")
전 앱이 터지는걸 반대하는편이긴한데... 여러분의 선택이겠쮸..🙃

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Managing/Modify/View/ModifyViewController.swift
> +        if productDetail.currency == "KRW" {
"KRW" 이렇게 rawValue를 그대로 비교하는것말고 다른 방법은 없나요!

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Managing/Modify/View/ModifyViewController.swift
> +        managingView.productDescriptionTextView.text = productDetail.productsDescription
뷰 내부를 채우는거, 뷰 자체에 data만 넘겨주고 할 순 없을까요?

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Managing/Modify/View/ModifyViewController.swift
> +        managingView.setUpBarItem(title: "상품수정")
String 모아서 관리해주면 참 좋겠어요😀

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Managing/Modify/View/ModifyViewController.swift
> +            // 수정해서 통신하는 로직
TODO 붙여주면 더 좋겠네욥!

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Managing/Modify/View/ModifyViewController.swift
> +    private func makeDataSource() -> UICollectionViewDiffableDataSource<ModifyViewModel.Section, ImageInfo> {
modern collection view 작업해보니 어떤가요ㅎㅎ
기존 방식과 어떤 차이를 느끼셨어요??

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Managing/View/ManagingView.swift
> +                productDescriptionTextView
stackview에 넣은 이유가 궁금해욥
각각 자리를 잡을 수 도 있었을 것 같아서요ㅎㅎ

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Managing/View/ManagingView.swift
> +    }()
textField들은 다 같은 모양을 가지고, placeHolder만 다른거같은데 좋은 방법 없을까요?😀

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Managing/View/ManagingView.swift
> +        backgroundColor = .systemBackground
다크모드하면 어떻게될까용! 우리 앱 다크모드에 안전합니까?

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Managing/View/ManagingViewController.swift
> +        view.addSubview(managingView)
viewController의 뷰를 managingView로 교체한게아니라, view에 subview로 사용하셨네요👀

2022-05-27 12:52 UTC, lina0322 commented on OpenMarket/OpenMarket/Util/ImageCacheManager.swift
> +    let apiService: APIProvider<Products>
Products로 변경한 이유가 궁금합니닷!

2022-05-28 14:17 UTC, Mino777 commented on OpenMarket/OpenMarket/Error/InputError.swift
> +    case imageIsFull
exceededNumberOfImages 이미지 개수 초과로 네이밍 변경해보았습니다!
감사합니다!

2022-05-28 14:18 UTC, cherrishRed commented on OpenMarket/OpenMarket/Extension/UIView.swift
> +    var firstResponder: UIView? {
해당 기능은 사용자 입장에서 있다가 없다가 하는 것보다 모든 텍스트 필드에 있으면 좋다고 생각하여 구현하였습니다.

2022-05-28 14:23 UTC, Mino777 commented on OpenMarket/OpenMarket/Extension/UIView.swift
> +    var firstResponder: UIView? {
현재 입력하는 시점의 firstResponder를 리턴받기 위해 구현하였습니다!
textField의 경우 아무리 작은 화면에서도 키보드에 가리지 않아서 textView의 경우에만 해당 프레임만큼 올리고 싶을 때 사용하였습니다.
감사합니다!

2022-05-28 14:24 UTC, cherrishRed commented on OpenMarket/OpenMarket/Model/DTO/ProductsPost.swift
> +    let boundary: String = UUID().uuidString
boundary는 multipartform 에서 body 에 포함되어있는 다른형태의 데이터를 구분하는 것이 boundary 의 역할 입니다!

2022-05-28 14:24 UTC, cherrishRed commented on OpenMarket/OpenMarket/Extension/UITextField.swift
> +    func addKeyboardHideButton(target: Any, selector: Selector) {
해당 기능은 사용자 입장에서 있다가 없다가 하는 것보다 모든 텍스트 필드에 있으면 좋다고 생각하여 구현하였습니다.

2022-05-28 14:25 UTC, Mino777 commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
> +    let vendor: Vendor?
해당 부분은 따로 두는 것이 개발자가 사용할 때 구분하기 쉽다고 생각해서 분리하였습니다!
하나의 객체로 진행하는 것이 더 나은 방향일까요?
감사합니다!

2022-05-28 14:27 UTC, Mino777 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +    func retrieveProduct(with endpoint: Requestable, completion: @escaping (Result<T, Error>) -> Void)
get을 대체하려고 열심히 찾아보았는데 해당 단어로 get을 대체하는 사례가 많아서 사용해보았습니다!
감사합니다!

2022-05-28 14:28 UTC, cherrishRed commented on OpenMarket/OpenMarket/Scene/Managing/View/ManagingView.swift
> +    }()
UITextField 를 만들어 주는 메서드를 생성해 placeHolder 를 파라미터로 받도록해 중복되는 코드들을 없앴습니다. 
감사합니다 엘림!

2022-05-28 14:30 UTC, cherrishRed commented on OpenMarket/OpenMarket/Scene/Managing/View/ManagingView.swift
> +                productDescriptionTextView
stack View 에 넣으면 code 로 주어야 할 제약의 양이 줄어들고 각각의 개체가 아니라 stackView 만 관리해 주면 되어 편하다고 느껴서 사용했습니다!

2022-05-28 14:32 UTC, cherrishRed commented on OpenMarket/OpenMarket/Scene/Main/ViewModel/MainViewModel.swift
>      var items: [Item] = []
items 가 외부에 노출되지 않도록 items 프로퍼티 자체를 삭제하고 snapshot 안에 넣어서 관리하는 방식으로 바꿨습니다!

2022-05-28 14:36 UTC, cherrishRed commented on OpenMarket/OpenMarket/Scene/Main/View/MainViewController.swift
> +            DispatchQueue.main.async {
main 에 sync 를 할 경우 교착상태가 일어나 앱이 죽어버릴 수도 있습니다.
그래서 main 에는 항상 async 로 코드를 보냅니다!
UI 와 관련된 작업들은 모두 main 쓰레드에서 해주어야 합니다!

2022-05-28 14:37 UTC, Mino777 commented on OpenMarket/OpenMarket/Scene/Main/View/MainViewController.swift
>          viewModel.requestProducts(by: viewModel.currentPage)
해당 부분 로직 모두 수정하였습니다!
감사합니다!

2022-05-28 14:39 UTC, cherrishRed commented on OpenMarket/OpenMarket/Scene/Managing/View/ManagingView.swift
> +        backgroundColor = .systemBackground
네 다크모드의 지원은 세세하게 하고 있지 않아서 다크 모드 설정시에도 하얀화면이 보이도록 우선은 변경하였습니다.

2022-05-28 14:39 UTC, Mino777 commented on OpenMarket/OpenMarket/Scene/Main/View/MainViewController.swift
> +    @objc private func moveRegisterView() {
해당 부분 addButtonDidTap으로 변경하였습니다!
감사합니다!

2022-05-28 14:43 UTC, cherrishRed commented on OpenMarket/OpenMarket/Model/DTO/ProductsPost.swift
> +struct ImageInfo: Encodable, Hashable {
Hashable 은 hash 값을 가지고 있는 것을 보장해주는 프로토콜 입니다. hash 를 가지고 있다는 것은 고유한 값을 가지고 있다는 것을 의미합니다.
이 구조체를 분리하라는 말씀이신가요? 새로운 파일로 분리하는 것인가요? 아니면 어떤한 파일로 옮겨가는 것일까요? 잘 이해를 하지 못했습니다 😭

2022-05-28 14:44 UTC, Mino777 commented on OpenMarket/OpenMarket/Scene/Main/View/MainViewController.swift
>                      cell.updateLabel(data: item)
해당 부분 configure 메서드 부분 하나로 수정하였습니다!
이미지 캐셔의 경우 한번 이미지캐셔를 생성해서 넘겨주는 것이 좋을 것 같아서 viewModel에서 한번 생성을 한 후에 생성 된 이미지캐셔를 넘겨주고 있습니다.
해당 부분은 어떤식으로 개선하는것이 좋을까요?
감사합니다!

2022-05-28 14:51 UTC, cherrishRed commented on OpenMarket/OpenMarket/Scene/Managing/Modify/View/ModifyViewController.swift
> +    }
super.init 은 상속받은 부모의 인스턴스를 사용하기 위해서 부모의 init 을 물려받아 초기화 하는 것 이라고 생각하고 있습니다. 

초기화에는 
Designated Initializer (지정 초기화)
Convenience Initializer (편의 초기화) 
등의 메서들이 있습니다. 

지정 초기화는 반드시 구현되어야 합니다. 

편의 초기화 메서드 내부에서는 구현을 하기 전에 중복을 피하기 위하여 지정 초기화 메서드를 호출해야 하는데
이럴 때 self.init 을 활용해 호출합니다. 

 required init 은 상속 받은 클래스에서도 꼭 구현해 주어야 하는 init 을 의미합니다.

2022-05-28 15:02 UTC, Mino777 commented on OpenMarket/OpenMarket/Scene/Main/View/MainViewController.swift
> +        let id = viewModel.items[indexPath.row].id
indexPath를 optional로 만들어주고, 바인딩을 통해 안전하게 사용할 수 있도록 수정하였습니다!
감사합니다!

2022-05-28 15:04 UTC, Mino777 commented on OpenMarket/OpenMarket/Scene/Managing/Modify/View/ModifyViewController.swift
> +final class ModifyViewController: ManagingViewController {
edit의 경우에 미처 지우지 못한 것 같습니다ㅠㅠ
edit 관련 네이밍 모두 수정하였습니다!
감사합니다!

2022-05-29 11:29 UTC, Mino777 commented on OpenMarket/OpenMarket/Scene/Managing/Modify/View/ModifyViewController.swift
> +        managingView.setUpBarItem(title: "상품수정")
네임스페이스로 모두 관리하도록 수정하였습니다!
감사합니다!

2022-05-29 11:35 UTC, Mino777 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +    @discardableResult
자주 사용되는 Attributes로는
버전에 따른 분기 처리에 사용하는 available
프로그램의 탑 레벨을 알려주는 main
objective-c 코드를 선언할 때 사용하는 objc 등이 있습니다!
그 외에것들은 아직 써보지 못해서 나중에 써볼 때 한번 더 학습 해보겠습니다!
감사합니다!

2022-05-29 11:37 UTC, Mino777 commented on OpenMarket/OpenMarket/Network/EndPoint/Requestable.swift
> +    func generateUrlRequestMultiPartFormData() -> Result<URLRequest, NetworkError> {
처음에 이미지의 파일 이름에 .jpg를 붙여주지 않아서 서버에서 메세지도 없는 0번 코드 에러를 던져주어서 해당 부분 디버깅하느라 많이 힘들었습니다 흑흑..
그래도 한번 성공해보니 형식이 아주 조금은 익숙해진 것 같습니다😆

2022-05-29 11:46 UTC, Mino777 commented on OpenMarket/OpenMarket/Protocol/AlertDelegate.swift
> +}
요구되는 알럿의 내부 방식이 다르기 때문에 결국 메서드를 나누어야 되서 각각의 delegate가 갖고있어야하는 메서드가 다릅니다ㅠㅠ 해당 부분 어떤식으로 개선하는게 좋을까요🥺

2022-05-29 11:56 UTC, Mino777 commented on OpenMarket/OpenMarket/Scene/Main/ViewModel/MainViewModel.swift
> +    private let productsDetailAPIService = APIProvider<ProductDetail>()
Provider가 아닌 내부 메서드가 T를 가지게되면서 외부에서 해당 메서드를 사용할 때 해당 모델로 추론하도록 하여 하나의 APIProvider만 생성하여 쓸 수 있도록 수정하였습니다!
감사합니다!

2022-05-29 12:09 UTC, Mino777 commented on OpenMarket/OpenMarket/Scene/Managing/Modify/View/ModifyViewController.swift
> +        fatalError("init(coder:) has not been implemented")
해당 부분은 productDetail을 required에서도 초기화를 해줘야하는데 그러려면 productDetail의 init을 커스텀해주어서 더미 객체로 초기화를 해주는 식으로 작업을 해줘야합니다. 그런데 저희가 스토리보드나 nib 파일을 사용하지 않기 때문에 해당 view가 스토리보드같은 파일을 사용해서 초기화가 되면 안되는 부분이기 때문에 fatal error를 노출 시키는게 맞지 않을까..? 라는 생각이 들어서 굳이 저렇게 작업을 해주면서 까지 fatal을 안해주는게 맞을까 라는 생각이 들었습니다. 해당 부분도 productDetail을 수정해서 fatal을 최대한 안써주는게 맞을까요?
감사합니다!

2022-05-29 12:16 UTC, Mino777 commented on OpenMarket/OpenMarket/Scene/Managing/Modify/View/ModifyViewController.swift
> +        if productDetail.currency == "KRW" {
Currency라는 Enum을 만들어서 각각 Response Model들의 currency 타입으로 사용해서 case로 비교 할 수 있게 수정하였습니다!
감사합니다!

2022-05-29 12:19 UTC, Mino777 commented on OpenMarket/OpenMarket/Scene/Managing/Modify/View/ModifyViewController.swift
> +        managingView.productDescriptionTextView.text = productDetail.productsDescription
뷰 내부에 메서드를 만들어서 data만 넘겨주도록 수정하였습니다!
감사합니다!

2022-05-29 12:30 UTC, Mino777 commented on OpenMarket/OpenMarket/Scene/Managing/Modify/View/ModifyViewController.swift
> +    private func makeDataSource() -> UICollectionViewDiffableDataSource<ModifyViewModel.Section, ImageInfo> {
가장 큰 차이점은 아무래도 reloadData를 하지 않아도 되는 부분인 것 같습니다!
그저 apply 단일 메서드를 사용해서 변경된 snapshot을 datasource에 apply만 해주면 collectionview의 row와 따로 동기화 해주는 작업이 없어도 안전하게 collectionview를 업데이트 해주는 부분이 정말 좋았던 것 같습니다! 스무스한 애니메이션은 덤!😆

2022-05-29 12:49 UTC, Mino777 commented on OpenMarket/OpenMarket/Scene/Managing/View/ManagingViewController.swift
> +        view.addSubview(managingView)
앗! 해당 부분 교체하는 방식으로 수정하였습니다!
감사합니다!

2022-05-29 12:51 UTC, Mino777 commented on OpenMarket/OpenMarket/Util/ImageCacheManager.swift
> +    let apiService: APIProvider<Products>
해당 부분은 viewModel에서 해당 APIProvider를 또 만들어주어야 해서 변경한 것 같습니다. 지금은 APIProvider의 제네릭을 제거했습니다!
감사합니다!

2022-05-29 14:19 UTC, Mino777 commented
@lina0322 
안녕하세요 엘림!!
1차 피드백 반영 완료하였습니다!

---

## 피드백 반영 부분
> 상세페이지 갔다가 나오면 스크롤이 튀는 것 같아욥.
> 또, 상품 등록하러 들어갔다가 취소했을때 이전에 보여진 목록과 다른 목록이 보여욥.. 서버가 이렇게 실시간으로 데이터를 바꾸진 않을 것 같은데ㅎㅎ;
> 등록한 다음에 제거가 맨 위에 있을 것 같은데.. 안그렇더라고요. 요건 서버에서 시간순으로 안줘서인가요?

해당 부분들은 모두 datasource 부분 로직이 잘못되어있어서 발생하던 부분들이었습니다😭 모두 수정하였습니다!

> 그리고 list에서 grid갔을때, list가 분명히 스크롤 안한상태인데 grid에서 상단이 짤립니다.

해당 부분은 list, grid cell 각각의 group size가 달라서 발생하는 현상같은데 최대한 계산을 해서 싱크를 맞춰보았습니다. 혹시 이 부분을 계산이 아닌 다른 방법으로 싱크를 맞출 수 있는 방법이 있을까요?😭

> 이런것들 확인을 하고싶은데 refreshControl이 없더라고용~ 가능하면 구현 부탁드립니다🙏

collectionview의 refreshControl 구현해두었습니다!

> 등록할때 제목을 입력하거나, 가격을 입력하고나서 다음 칸에 가고싶은데 자동으로 넘어가지 않고 키보드를 가리는 기능만 있네요. 포커스 이동해주실 수 있을까요?

상품명의 경우엔 키보드 타입이 디폴트이어서 리턴키를 누르는 경우에 포커싱을 컨트롤 할 수 있었습니다. 하지만 가격, 수량 같은 경우에 넘버패드 타입으로 진행을 하다보니 리턴키가 없고, 숫자 개수의 제한도 없다보니 포커싱 컨트롤을 어떤식으로 해야할지 모르겠습니다😭 우선 상품명의 경우에만 구현해두었습니다!

> 그리고 뷰 터치했을때, 입력 가능한 부분이면 포커스 이동하고, 사진이나 기타 다른 아무리 작은 뷰라해도 입력과 관련 없는 부분이면 키보드 내릴 수 있도록 해주세요!!

view에 아예 gesture를 넣어주어서 입력과 관련없는 부분의 경우엔 모두 키보드 내리도록 구현하였습니다!

> 마지막으로 등록 눌렀을때 에러가 발생한(입력을 잘못한?) 텍스트 필드 혹은 뷰로 포커스 이동해주세욥ㅎㅎㅎㅎ

발생한 에러를 이용해서 분기처리하여 각 에러에 맞는 리스폰더로 포커싱하도록 구현하였습니다!

> 왜 인지 모르겠는데 저기 사진 등록 셀 아래보면 얇게 옆에 사진 하단이 남는데(???????) 이건 이유가 짐작이 안가네요ㅎㅎ 제 시뮬레이터 문제인거같기도하고 한번만 확인해주세요.
참고로 저는 iPhone12 iOS15.4 시뮬레이터에서 돌려보았습니다!!

해당 부분은 우선 제 xcode에 있는 모든 시뮬레이터로 돌려보았는데 발생하지 않았습니다😭 저희도 이유가 아예 짐작이 안가서 해당 부분은 반영하지 못했습니다😭

다른 반영 사항들은 코멘트를 통해 반영 여부 남겨두었습니다!
감사합니다!!

2022-05-31 12:26 UTC, lina0322 commented on OpenMarket/OpenMarket/Extension/UITextField.swift
> +    func addKeyboardHideButton(target: Any, selector: Selector) {
textField에 extension하는것도 방법인데, 가지고있고 자주 쓰는거라면
custom한 TextField를 만들어서 사용해도 좋을 것 같아요.
그럼 add 호출자체도 init에서 해버릴수도ㅎㅎ

2022-05-31 12:26 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/DTO/ProductsPost.swift
> +struct ImageInfo: Encodable, Hashable {
설명이 부족했네요!ㅎㅎ 객체별로 파일을 따로두면 어떨까했는데, 관련있어서 두신거라면 괜찮습니답~

2022-05-31 12:28 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
> +    let vendor: Vendor?
encode하는 data랑 decode하는 data가 동일해보이는데 굳이 따로 있을 필요가 있나 생각했어요👀
그래서 codable이 존재하는게 아닐까..? 라는 생각이 있었습니다🙇🏻‍♀️
선택은 여러분의 몫이지만, 시간이 된다면 하나로 작업해보는 것도 좋을 것 같아요!

2022-05-31 12:29 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Main/View/MainViewController.swift
>                      cell.updateLabel(data: item)
혹시 싱글턴은 의도적으로 사용하지 않는걸까요?👀

2022-05-31 12:30 UTC, lina0322 commented on OpenMarket/OpenMarket/Protocol/AlertDelegate.swift
> +}
내부 방식이 다르지만, 이름이 상당히 유사해서 비슷한 동작을 할 것 같은 느낌이네요.. 흠🤔
만약 하나로 합치는 거고, 알럿창을 보여주는거니
타이틀이나 디스크립션을 받을 수 있고, 내부에서 동작할 행동도 클로저로 받을 수도 있을 것 같다는 생각은 드네요!

2022-05-31 12:32 UTC, lina0322 commented on OpenMarket/OpenMarket/Scene/Managing/Modify/View/ModifyViewController.swift
> +        fatalError("init(coder:) has not been implemented")
요건 사람마다 의견이 다를 것 같아요.
차라리 터트리고 터지는 부분을 찾는것도 방법이니까!
하지만 저는 앱이 강제로 꺼지는 것은 사용자에게 좋은 경험은 아닐 것 같다는 생각이 들었습니다ㅎㅎ

2022-05-31 12:41 UTC, lina0322 approved these changes
두 분 짧은 시간동안 코드가 많이 발전했어요~~ 정말 좋습니다!
달아들인 코멘트나 추가적으로 필요한 수정들은 다음 스텝에서 함께합시다!!!

이번 스텝도 고생하셨어요👍

2022-05-31 12:41 UTC, lina0322 commented on OpenMarket/OpenMarket/Extension/Collection.swift
> +}
LGTM💕

2022-05-31 12:41 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/Currency.swift
> + }
요거 통신 주고받을때 사용해서 Codable 채택하신거죱?

2022-05-31 12:41 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
> +    let productsDescription: String?
갑자기 보다보니 product 내부라서 그냥 description도 나쁘지않을거같네욥ㅎㅎ

2022-05-31 12:41 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
>      let images: [ProductImage]
요거 마치 UIImage 배열같아보여서, 네이밍 한 번 더 고민하면 좋을 것 같아욥

2022-05-31 12:41 UTC, lina0322 commented on OpenMarket/OpenMarket/Network/APIProvider/APIProvider.swift
> +    func retrieveProduct<T: Decodable>(
LGMT👍

2022-05-31 12:41 UTC, merged

2022-06-01 14:31 UTC, Mino777 commented on OpenMarket/OpenMarket/Model/DTO/ProductsPost.swift
> +struct ImageInfo: Encodable, Hashable {
현재 imageInfo 타입을 datasoruce의 itemIdentifierType으로 사용하고 있어서 hashable을 채택하였습니다!

2022-06-01 14:32 UTC, Mino777 commented on OpenMarket/OpenMarket/Scene/Main/View/MainViewController.swift
>                      cell.updateLabel(data: item)
의도적으로 싱글턴은 최대한 지양해보려고 했었습니다!
그런데 imageCacheManager 같은 경우엔 추후 범용성이나 타입의 특성을 봤을 때
싱글턴이 적합한 것 같아 변경하였습니다!
감사합니다!

2022-06-01 14:34 UTC, Mino777 commented on OpenMarket/OpenMarket/Protocol/AlertDelegate.swift
> +}
해당 부분은 Main에서 product, productDetail 두 api를 모두 갖고있어서 어쩔 수 없이 분기가 필요했었던 부분이었는데 detail api를 DetailVC로 옮기면서 분기가 필요없어졌습니다!
엘림 말씀대로 다시 합쳤습니다!
감사합니다!

2022-06-01 14:34 UTC, Mino777 commented on OpenMarket/OpenMarket/Model/Currency.swift
> + }
넵 맞습니다!

2022-06-01 14:35 UTC, Mino777 commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
> +    let productsDescription: String?
description으로 변경하였습니다!

2022-06-01 14:35 UTC, Mino777 commented on OpenMarket/OpenMarket/Model/ProductsDetail.swift
>      let images: [ProductImage]
imageInfos로 변경해보았습니다!