오픈마켓 II [STEP 1] papri, Tiana
yagom-academy/ios-open-market pull request #160
Opened 2022-05-27 13:44 UTC by Kim-TaeHyun-A

# 오픈마켓2 [STEP1] papri, Tiana  

@1Consumption 
안녕하세요 올라프⛄️
step1 PR 보냅니다. 
부족한 점이 많지만 잘 부탁드립니다🙇‍♀️🙇‍♀️

---

## 오픈마켓1 리뷰 반영 답변

### MainViewController와 MainViewControllerUnderiOS14 중복 코드 문제 
MainViewController 내부에서 버전 분기를 하는 것이 어떤지 말씀해 주셨는데, MainViewController의 경우 프로퍼티 중 타입이 ios14이후에서만 적용되는 것이 있어 분기처리가 까다롭다 느껴졌습니다. 그래서 BaseViewController을 만들어
중복되는 부분은 해당 클래스(BaseViewcontroller)에서 상속 받도록 리팩토링을 하였습니다.

### iOS13 지원하는 VC에서 diffable 사용 안한 이유
여러 방식으로 collection view을 경험하고 싶다는 생각에 diffable을 사용 않고 구현을 진행했습니다.

### 프로토콜 기본 구현으로 제공한 이유
ContentUpdatable 프로토콜은 특정 기능을 묶고 있습니다.

상속을 위해 클래스를 만든다면 일반화를 위해 공통부분을 부모 클래스로 생성할 것 같습니다. 지금 구조에서는 특정 기능(content를 update하는 기능)을 따로 빼고 싶은 상황이라서 protocol을 사용해서 각 클래스가 기능을 추가할 수 있도록 구현했습니다.

만약, 상속을 하게 되면 일반적인 구조(공통 구조/ 기능)에서 구체화된 기능을 추가하는(구체화의) 느낌으로 구현될 것 같습니다.

올라프가 프로토콜 채택이나 상속을 선택하시는 기준은 무엇인지 궁금합니다!

--- 

## 고민한 점 및 질문 

### 1. custom method override
![](https://i.imgur.com/GNsLVc8.png)
상속 과정에서 custom method가 Objective-C compatible하지 않으면 override할때 extension 에서는 불가능함을 알게 되었습니다.
가독성 측면에서 override한 메소드의 위치가 좋지 않은 것 같은데, 이런 경우 BaseViewController에서 appltListLayout() 같은 메소드를 정의하지 않는 게 오히려 나은 지 궁금합니다.

### 2. 키보드 종류 확인하고 텍스트뷰 레이아웃 설정하기
* 상황:  
기본 키보드는 자동완성 기능을 지원해서 숫자패드보다 높이가 더 큽니다.
한 키보드를 기준으로 레이아웃을 설정하면 키보드의 종류가 바뀌었을 때 텍스트 뷰가 제대로 보이지 않습니다.

* 방법:
notification에서 받는 데이터를 바탕으로 구별하려고 했습니다.
아래와 같이 키보드의 크기에 따라 다른 값을 받습니다.
```swift
		{name = UIKeyboardWillShowNotification; userInfo = {
        UIKeyboardAnimationCurveUserInfoKey = 7;
        UIKeyboardAnimationDurationUserInfoKey = "0.25";
        UIKeyboardBoundsUserInfoKey = "NSRect: {{0, 0}, {375, 336}}";
        UIKeyboardCenterBeginUserInfoKey = "NSPoint: {187.5, 980}";
        UIKeyboardCenterEndUserInfoKey = "NSPoint: {187.5, 644}";
        UIKeyboardFrameBeginUserInfoKey = "NSRect: {{0, 812}, {375, 336}}";
        UIKeyboardFrameEndUserInfoKey = "NSRect: {{0, 476}, {375, 336}}";
        UIKeyboardIsLocalUserInfoKey = 1
        
        {name = UIKeyboardWillShowNotification; userInfo = {
            UIKeyboardAnimationCurveUserInfoKey = 7;
            UIKeyboardAnimationDurationUserInfoKey = 0;
            UIKeyboardBoundsUserInfoKey = "NSRect: {{0, 0}, {375, 291}}";
            UIKeyboardCenterBeginUserInfoKey = "NSPoint: {187.5, 666.5}";
            UIKeyboardCenterEndUserInfoKey = "NSPoint: {187.5, 666.5}";
            UIKeyboardFrameBeginUserInfoKey = "NSRect: {{0, 521}, {375, 291}}";
            UIKeyboardFrameEndUserInfoKey = "NSRect: {{0, 521}, {375, 291}}";
            UIKeyboardIsLocalUserInfoKey = 1;
        }}
```

이때, 키보드 종류에 따라 다른 레이아웃을 적용하려니 이전 레이아웃이 active해서 제대로 적용이 안되는 것 같습니다. 이를 해결하기 위해 클로저 프로퍼티(numberPadLayout, defaultPadLayout, originPadLayout)로 관련된 레이아웃을 지정하고 하나씩 activate 합니다.

* 결과:
키보드가 나타나면 키보드의 높이에 맞게 텍스트뷰(description란)의 크기가 조절되도록 구현했습니다.
키보드가 사라지면 텍스트뷰는 화면을 아래 끝까지 채워집니다.
키보드의 종류가 바뀌면(ex. 숫자패드) 텍스트뷰
의 크기는 더 커집니다.
![](https://i.imgur.com/U3VWx1U.gif)

* 문제:
고정된 값(하드코딩)으로 레이아웃을 설정해서 iphone 11 Pro 에서만 이쁘게 나옵니다.😢

### 3. 전반적인 구조
상품 수정과 상품 등록 화면이 UpdateProductViewController에서 모두 진행이 됩니다. 이때문에 해당 파일에 너무 길어졌습니다. viewcontroller를 작게 만들고 싶은데 조언해주실 수 있으실까요?😢
지금은 등록과 수정이 분기문을 사용해서 하나의 VC에 구현되었습니다. 이 때문에 추가된 코드가 많지 않다고 생각합니다. 그래도 각각이 다른 VC에서 구현되는 것이 좋은지 지금도 괜찮은지 고민입니다.🤔

### 4. HTTPManager 코드 중복
HTTPManager는 healthcheck, data load, data post, data patch 를 하는 메소드를 구현해 두어 서버와 통신하는 역할을 수행하도록 했습니다. 이 과정에서 메소드 내부에 URLRequest를 생성하는 부분을 제외하고 중복되는 부분이 상당히 많음을 느꼈습니다. 
리팩토링을 어떤 방향으로 진행할까 고민 중입니다.
알라모파이어의 request 메서드를 살펴보니 매개변수로 HTTP method를 구별하는데요. 저희도 이와 같이 하나의 메서드를 사용하고 내부에서 switch문으로 적절한 메서드를 호출하도록 리팩토링하는 것 좋을 것 같다는 생각이 듭니다. 올라프는 어떻게 생각하시나요?
```swift
AF.request("https://httpbin.org/get")
AF.request("https://httpbin.org/post", method: .post)
AF.request("https://httpbin.org/put", method: .put)
AF.request("https://httpbin.org/delete", method: .delete)
```

### 5. post, patch 실패 처리 방식
서버에 데이터를 업데이트하는 것을 실패하는 경우 지금은 사용자에게 아무런 정보도 주지 않습니다. 경고문을 띄우는 것으로 해결할 생각인데 혹시 다른 방법이 있을지 궁금합니다🤔

### 6. enter를 눌렀을 때 프로퍼티에 값 반영
숫자 키보드의 경우 엔터가 없지만 저희가 구현한 방식은 enter를 눌렀을 때만 값이 반영됩니다.
입력값을 관리하는 프로퍼티에 값을 넣어주는 시점이 언제가 적절한지 고민입니다.

### 7. post 문제
iOS 13 버전과 iOS 15버전이 동일한 코드로 실행되는데 iOS13 에서는 Post가 제대로 되지 않는데 어디를 수정해야 할지 잘 모르겠습니다. 조언해주실 수 있으실까요?(iOS15 기기에서는 잘 돌아갑니다😢)

### 8. pull 하면 refresh
refresh control을 사용해서 스크롤을 내리면 값이 업데이트 되도록 구현했습니다.
기존 데이터를 삭제하고 새로운 데이터를 서버에서 받아서 넣도록 구현했습니다.
매끄럽게 새로운 데이터가 로드되지 않는 것이 고민입니다.🤔
![](https://i.imgur.com/5rJUdkt.gif)

2022-05-29 16:21 UTC, 1Consumption commented
### 프로토콜 기본 구현으로 제공한 이유
ContentUpdatable 프로토콜은 특정 기능을 묶고 있습니다.

상속을 위해 클래스를 만든다면 일반화를 위해 공통부분을 부모 클래스로 생성할 것 같습니다. 지금 구조에서는 특정 기능(content를 update하는 기능)을 따로 빼고 싶은 상황이라서 protocol을 사용해서 각 클래스가 기능을 추가할 수 있도록 구현했습니다.

만약, 상속을 하게 되면 일반적인 구조(공통 구조/ 기능)에서 구체화된 기능을 추가하는(구체화의) 느낌으로 구현될 것 같습니다.

올라프가 프로토콜 채택이나 상속을 선택하시는 기준은 무엇인지 궁금합니다!

> ☃️ 저도 기능 단위로 나눠야한다면 프로토콜을 사용하고 있습니다!
반면 상속을 사용해야 하는 경우는 특정 메소드의 시점을 잡고싶을 때 사용합니다.

``` swift 
class A {
    
    func a() {
        b()
        c()
    }

    func b() {
    }

    func c() {
    }
}

class B: A {
    
    override func a() {
        super.a()
        print(#function)
    }

    override func b() {
        super.b()
        print(#function)
    }

    override func c() {
        super.c()
        print(#function)
    }
}
```

### custom method override
![](https://i.imgur.com/GNsLVc8.png)
상속 과정에서 custom method가 Objective-C compatible하지 않으면 override할때 extension 에서는 불가능함을 알게 되었습니다.
가독성 측면에서 override한 메소드의 위치가 좋지 않은 것 같은데, 이런 경우 BaseViewController에서 appltListLayout() 같은 메소드를 정의하지 않는 게 오히려 나은 지 궁금합니다.

> ☃️ 흠... 글쎄요... 저는 View의 layout을 위해 상속을 하는 상황을 만들지 않을 거 같아요. 이걸 하나의 클래스 내부에서 버전 분기로 해결할 수 있겠네요.

### 키보드 종류 확인하고 텍스트뷰 레이아웃 설정하기
* 상황:  
기본 키보드는 자동완성 기능을 지원해서 숫자패드보다 높이가 더 큽니다.
한 키보드를 기준으로 레이아웃을 설정하면 키보드의 종류가 바뀌었을 때 텍스트 뷰가 제대로 보이지 않습니다.

* 방법:
notification에서 받는 데이터를 바탕으로 구별하려고 했습니다.
아래와 같이 키보드의 크기에 따라 다른 값을 받습니다.
```swift
		{name = UIKeyboardWillShowNotification; userInfo = {
        UIKeyboardAnimationCurveUserInfoKey = 7;
        UIKeyboardAnimationDurationUserInfoKey = "0.25";
        UIKeyboardBoundsUserInfoKey = "NSRect: {{0, 0}, {375, 336}}";
        UIKeyboardCenterBeginUserInfoKey = "NSPoint: {187.5, 980}";
        UIKeyboardCenterEndUserInfoKey = "NSPoint: {187.5, 644}";
        UIKeyboardFrameBeginUserInfoKey = "NSRect: {{0, 812}, {375, 336}}";
        UIKeyboardFrameEndUserInfoKey = "NSRect: {{0, 476}, {375, 336}}";
        UIKeyboardIsLocalUserInfoKey = 1
        
        {name = UIKeyboardWillShowNotification; userInfo = {
            UIKeyboardAnimationCurveUserInfoKey = 7;
            UIKeyboardAnimationDurationUserInfoKey = 0;
            UIKeyboardBoundsUserInfoKey = "NSRect: {{0, 0}, {375, 291}}";
            UIKeyboardCenterBeginUserInfoKey = "NSPoint: {187.5, 666.5}";
            UIKeyboardCenterEndUserInfoKey = "NSPoint: {187.5, 666.5}";
            UIKeyboardFrameBeginUserInfoKey = "NSRect: {{0, 521}, {375, 291}}";
            UIKeyboardFrameEndUserInfoKey = "NSRect: {{0, 521}, {375, 291}}";
            UIKeyboardIsLocalUserInfoKey = 1;
        }}
```

이때, 키보드 종류에 따라 다른 레이아웃을 적용하려니 이전 레이아웃이 active해서 제대로 적용이 안되는 것 같습니다. 이를 해결하기 위해 클로저 프로퍼티(numberPadLayout, defaultPadLayout, originPadLayout)로 관련된 레이아웃을 지정하고 하나씩 activate 합니다.

* 결과:
키보드가 나타나면 키보드의 높이에 맞게 텍스트뷰(description란)의 크기가 조절되도록 구현했습니다.
키보드가 사라지면 텍스트뷰는 화면을 아래 끝까지 채워집니다.
키보드의 종류가 바뀌면(ex. 숫자패드) 텍스트뷰
의 크기는 더 커집니다.
![](https://i.imgur.com/U3VWx1U.gif)

* 문제:
고정된 값(하드코딩)으로 레이아웃을 설정해서 iphone 11 Pro 에서만 이쁘게 나옵니다.😢

> ☃️ 말씀해주신 문제점 처럼 하드코딩을 하게되면 특정 기기에서만 제대로 나오는 경우가 발생하겠네요.
collectionView의 bottomConstraint를 캐싱하고, 키보드의 높이만큼 constant를 변경하면 어떨까요?

``` swift
final class ViewController: UIViewController {

    private var bottomConstraint: NSLayoutConstraint?
    
    func layout() {
        bottomConstraint = collectionView.bottomAnchor.constraint(equalTo: view.bottomAnchor)
        
        NSLayoutConstraint.activate([
            // some constraints...
            bottomConstraint
        ].compactMap { $0 })
    }
    
    @objc
    private func keyboardWillShow(_ notification: Notification) {
        guard let keyboardBounds = notification.userInfo?["UIKeyboardBoundsUserInfoKey"] as? NSValue,
              let keyboardHeight = keyboardBounds.cgRectValue.height else {
            return
        }
        
        bottomConstraint?.constant = keyboardHeight
    }
    
    @objc
    private func keyboardWillHide(_ notification: Notification) {
        bottomConstraint?.constant = .zero
    }
}
```

### 전반적인 구조
상품 수정과 상품 등록 화면이 UpdateProductViewController에서 모두 진행이 됩니다. 이때문에 해당 파일에 너무 길어졌습니다. viewcontroller를 작게 만들고 싶은데 조언해주실 수 있으실까요?😢
지금은 등록과 수정이 분기문을 사용해서 하나의 VC에 구현되었습니다. 이 때문에 추가된 코드가 많지 않다고 생각합니다. 그래도 각각이 다른 VC에서 구현되는 것이 좋은지 지금도 괜찮은지 고민입니다.🤔

> ☃️ viewController가 view의 역할 이외의 역할을 하고 있지는 않은가요? 코멘트에 남겼으니 참고해보세요.

### HTTPManager 코드 중복
HTTPManager는 healthcheck, data load, data post, data patch 를 하는 메소드를 구현해 두어 서버와 통신하는 역할을 수행하도록 했습니다. 이 과정에서 메소드 내부에 URLRequest를 생성하는 부분을 제외하고 중복되는 부분이 상당히 많음을 느꼈습니다. 
리팩토링을 어떤 방향으로 진행할까 고민 중입니다.
알라모파이어의 request 메서드를 살펴보니 매개변수로 HTTP method를 구별하는데요. 저희도 이와 같이 하나의 메서드를 사용하고 내부에서 switch문으로 적절한 메서드를 호출하도록 리팩토링하는 것 좋을 것 같다는 생각이 듭니다. 올라프는 어떻게 생각하시나요?
```swift
AF.request("https://httpbin.org/get")
AF.request("https://httpbin.org/post", method: .post)
AF.request("https://httpbin.org/put", method: .put)
AF.request("https://httpbin.org/delete", method: .delete)
```

### post, patch 실패 처리 방식
서버에 데이터를 업데이트하는 것을 실패하는 경우 지금은 사용자에게 아무런 정보도 주지 않습니다. 경고문을 띄우는 것으로 해결할 생각인데 혹시 다른 방법이 있을지 궁금합니다🤔

> ☃️ 말씀하신대로 알러트를 띄우는 방식이 괜찮아보입니다~

### enter를 눌렀을 때 프로퍼티에 값 반영
숫자 키보드의 경우 엔터가 없지만 저희가 구현한 방식은 enter를 눌렀을 때만 값이 반영됩니다.
입력값을 관리하는 프로퍼티에 값을 넣어주는 시점이 언제가 적절한지 고민입니다.

> ☃️ 이건 그냥 정책의 문제 같은데요. 얼마나 자주 저장할지에 대해 팀 내부에서 정하고 그에 맞게 구현하면 되겠습니다.

### post 문제
iOS 13 버전과 iOS 15버전이 동일한 코드로 실행되는데 iOS13 에서는 Post가 제대로 되지 않는데 어디를 수정해야 할지 잘 모르겠습니다. 조언해주실 수 있으실까요?(iOS15 기기에서는 잘 돌아갑니다😢)

> ☃️ 어떤 에러가 발생했는지도 같이 알려주면 좋겠습니다. 에러 로그도 있으면 좋고요. 이부분만 가지고는 어떤 상황인지 알수가 없네요.

### pull 하면 refresh
refresh control을 사용해서 스크롤을 내리면 값이 업데이트 되도록 구현했습니다.
기존 데이터를 삭제하고 새로운 데이터를 서버에서 받아서 넣도록 구현했습니다.
매끄럽게 새로운 데이터가 로드되지 않는 것이 고민입니다.🤔
![](https://i.imgur.com/5rJUdkt.gif)

> ☃️ refresh를 begin해야 하는 시점에 end를 해서 동작이 어색합니다. 또 서버에서 받아오는 응답이 너무 빨리와서 어색해보이는 거 같네요. 응답을 의도적으로 1초 정도 느리게 받았더니 자연스럽네요. 

``` swift 
    @objc func refreshCollectionView() {
        dataProvider.pageNumber = 1
        dataProvider.fetchData() { [self] products in
            DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
                guard var currentSnapshot = currentSnapshot else {
                    return
                }
                currentSnapshot.deleteItems(currentSnapshot.itemIdentifiers)
                currentSnapshot.appendItems(products)
                dataSource?.apply(currentSnapshot)

                DispatchQueue.main.async {
                    self.refresh.endRefreshing()
                }
            }
        }

        DispatchQueue.main.async {
            self.collectionView?.refreshControl?.beginRefreshing()
        }
    }
```

2022-05-29 16:36 UTC, 1Consumption requested changes
안녕하세요! 파프리 티아나. 고생 많으셨습니다👍

대부분의 내용은 코멘트로 달았고, 따로 적어주신 궁금한 점에 대한 답변은 아래에 달았어요. 

-----------------------------------------------

### 프로토콜 기본 구현으로 제공한 이유
ContentUpdatable 프로토콜은 특정 기능을 묶고 있습니다.

상속을 위해 클래스를 만든다면 일반화를 위해 공통부분을 부모 클래스로 생성할 것 같습니다. 지금 구조에서는 특정 기능(content를 update하는 기능)을 따로 빼고 싶은 상황이라서 protocol을 사용해서 각 클래스가 기능을 추가할 수 있도록 구현했습니다.

만약, 상속을 하게 되면 일반적인 구조(공통 구조/ 기능)에서 구체화된 기능을 추가하는(구체화의) 느낌으로 구현될 것 같습니다.

올라프가 프로토콜 채택이나 상속을 선택하시는 기준은 무엇인지 궁금합니다!

> ☃️ 저도 기능 단위로 나눠야한다면 프로토콜을 사용하고 있습니다!
반면 상속을 사용해야 하는 경우는 특정 메소드의 시점을 잡고싶을 때 사용합니다.

``` swift 
class A {
    
    func a() {
        b()
        c()
    }

    func b() {
    }

    func c() {
    }
}

class B: A {
    
    override func a() {
        super.a()
        print(#function)
    }

    override func b() {
        super.b()
        print(#function)
    }

    override func c() {
        super.c()
        print(#function)
    }
}
```

### custom method override
![](https://i.imgur.com/GNsLVc8.png)
상속 과정에서 custom method가 Objective-C compatible하지 않으면 override할때 extension 에서는 불가능함을 알게 되었습니다.
가독성 측면에서 override한 메소드의 위치가 좋지 않은 것 같은데, 이런 경우 BaseViewController에서 appltListLayout() 같은 메소드를 정의하지 않는 게 오히려 나은 지 궁금합니다.

> ☃️ 흠... 글쎄요... 저는 View의 layout을 위해 상속을 하는 상황을 만들지 않을 거 같아요. 이걸 하나의 클래스 내부에서 버전 분기로 해결할 수 있겠네요.

### 키보드 종류 확인하고 텍스트뷰 레이아웃 설정하기
* 상황:  
기본 키보드는 자동완성 기능을 지원해서 숫자패드보다 높이가 더 큽니다.
한 키보드를 기준으로 레이아웃을 설정하면 키보드의 종류가 바뀌었을 때 텍스트 뷰가 제대로 보이지 않습니다.

* 방법:
notification에서 받는 데이터를 바탕으로 구별하려고 했습니다.
아래와 같이 키보드의 크기에 따라 다른 값을 받습니다.
```swift
		{name = UIKeyboardWillShowNotification; userInfo = {
        UIKeyboardAnimationCurveUserInfoKey = 7;
        UIKeyboardAnimationDurationUserInfoKey = "0.25";
        UIKeyboardBoundsUserInfoKey = "NSRect: {{0, 0}, {375, 336}}";
        UIKeyboardCenterBeginUserInfoKey = "NSPoint: {187.5, 980}";
        UIKeyboardCenterEndUserInfoKey = "NSPoint: {187.5, 644}";
        UIKeyboardFrameBeginUserInfoKey = "NSRect: {{0, 812}, {375, 336}}";
        UIKeyboardFrameEndUserInfoKey = "NSRect: {{0, 476}, {375, 336}}";
        UIKeyboardIsLocalUserInfoKey = 1
        
        {name = UIKeyboardWillShowNotification; userInfo = {
            UIKeyboardAnimationCurveUserInfoKey = 7;
            UIKeyboardAnimationDurationUserInfoKey = 0;
            UIKeyboardBoundsUserInfoKey = "NSRect: {{0, 0}, {375, 291}}";
            UIKeyboardCenterBeginUserInfoKey = "NSPoint: {187.5, 666.5}";
            UIKeyboardCenterEndUserInfoKey = "NSPoint: {187.5, 666.5}";
            UIKeyboardFrameBeginUserInfoKey = "NSRect: {{0, 521}, {375, 291}}";
            UIKeyboardFrameEndUserInfoKey = "NSRect: {{0, 521}, {375, 291}}";
            UIKeyboardIsLocalUserInfoKey = 1;
        }}
```

이때, 키보드 종류에 따라 다른 레이아웃을 적용하려니 이전 레이아웃이 active해서 제대로 적용이 안되는 것 같습니다. 이를 해결하기 위해 클로저 프로퍼티(numberPadLayout, defaultPadLayout, originPadLayout)로 관련된 레이아웃을 지정하고 하나씩 activate 합니다.

* 결과:
키보드가 나타나면 키보드의 높이에 맞게 텍스트뷰(description란)의 크기가 조절되도록 구현했습니다.
키보드가 사라지면 텍스트뷰는 화면을 아래 끝까지 채워집니다.
키보드의 종류가 바뀌면(ex. 숫자패드) 텍스트뷰
의 크기는 더 커집니다.
![](https://i.imgur.com/U3VWx1U.gif)

* 문제:
고정된 값(하드코딩)으로 레이아웃을 설정해서 iphone 11 Pro 에서만 이쁘게 나옵니다.😢

> ☃️ 말씀해주신 문제점 처럼 하드코딩을 하게되면 특정 기기에서만 제대로 나오는 경우가 발생하겠네요.
collectionView의 bottomConstraint를 캐싱하고, 키보드의 높이만큼 constant를 변경하면 어떨까요?

``` swift
final class ViewController: UIViewController {

    private var bottomConstraint: NSLayoutConstraint?
    
    func layout() {
        bottomConstraint = collectionView.bottomAnchor.constraint(equalTo: view.bottomAnchor)
        
        NSLayoutConstraint.activate([
            // some constraints...
            bottomConstraint
        ].compactMap { $0 })
    }
    
    @objc
    private func keyboardWillShow(_ notification: Notification) {
        guard let keyboardBounds = notification.userInfo?["UIKeyboardBoundsUserInfoKey"] as? NSValue else {
            return
        }
        
        let keyboardHeight = keyboardBounds.cgRectValue.height
        
        bottomConstraint?.constant = -keyboardHeight
    }
    
    @objc
    private func keyboardWillHide(_ notification: Notification) {
        bottomConstraint?.constant = .zero
    }
}
```
https://user-images.githubusercontent.com/37682858/170880814-9f52d1fd-f641-46b8-836a-c88cf130297a.mp4

### 전반적인 구조
상품 수정과 상품 등록 화면이 UpdateProductViewController에서 모두 진행이 됩니다. 이때문에 해당 파일에 너무 길어졌습니다. viewcontroller를 작게 만들고 싶은데 조언해주실 수 있으실까요?😢
지금은 등록과 수정이 분기문을 사용해서 하나의 VC에 구현되었습니다. 이 때문에 추가된 코드가 많지 않다고 생각합니다. 그래도 각각이 다른 VC에서 구현되는 것이 좋은지 지금도 괜찮은지 고민입니다.🤔

> ☃️ viewController가 view의 역할 이외의 역할을 하고 있지는 않은가요? 코멘트에 남겼으니 참고해보세요.

### HTTPManager 코드 중복
HTTPManager는 healthcheck, data load, data post, data patch 를 하는 메소드를 구현해 두어 서버와 통신하는 역할을 수행하도록 했습니다. 이 과정에서 메소드 내부에 URLRequest를 생성하는 부분을 제외하고 중복되는 부분이 상당히 많음을 느꼈습니다. 
리팩토링을 어떤 방향으로 진행할까 고민 중입니다.
알라모파이어의 request 메서드를 살펴보니 매개변수로 HTTP method를 구별하는데요. 저희도 이와 같이 하나의 메서드를 사용하고 내부에서 switch문으로 적절한 메서드를 호출하도록 리팩토링하는 것 좋을 것 같다는 생각이 듭니다. 올라프는 어떻게 생각하시나요?
```swift
AF.request("https://httpbin.org/get")
AF.request("https://httpbin.org/post", method: .post)
AF.request("https://httpbin.org/put", method: .put)
AF.request("https://httpbin.org/delete", method: .delete)
```

> ☃️ dataTask의 completionHandler 부분은 하나의 메소드로 추상화 할 수 있어보입니다. 하지만 이 메소드를 사용하는 get, post, put, delete는 각각 별도의 메소드로 다른 동작을 가지는게 좋겠네요.

### post, patch 실패 처리 방식
서버에 데이터를 업데이트하는 것을 실패하는 경우 지금은 사용자에게 아무런 정보도 주지 않습니다. 경고문을 띄우는 것으로 해결할 생각인데 혹시 다른 방법이 있을지 궁금합니다🤔

> ☃️ 말씀하신대로 알러트를 띄우는 방식이 괜찮아보입니다~

### enter를 눌렀을 때 프로퍼티에 값 반영
숫자 키보드의 경우 엔터가 없지만 저희가 구현한 방식은 enter를 눌렀을 때만 값이 반영됩니다.
입력값을 관리하는 프로퍼티에 값을 넣어주는 시점이 언제가 적절한지 고민입니다.

> ☃️ 이건 그냥 정책의 문제 같은데요. 얼마나 자주 저장할지에 대해 팀 내부에서 정하고 그에 맞게 구현하면 되겠습니다.

### post 문제
iOS 13 버전과 iOS 15버전이 동일한 코드로 실행되는데 iOS13 에서는 Post가 제대로 되지 않는데 어디를 수정해야 할지 잘 모르겠습니다. 조언해주실 수 있으실까요?(iOS15 기기에서는 잘 돌아갑니다😢)

> ☃️ 어떤 에러가 발생했는지도 같이 알려주면 좋겠습니다. 에러 로그도 있으면 좋고요. 이부분만 가지고는 어떤 상황인지 알수가 없네요.

### pull 하면 refresh
refresh control을 사용해서 스크롤을 내리면 값이 업데이트 되도록 구현했습니다.
기존 데이터를 삭제하고 새로운 데이터를 서버에서 받아서 넣도록 구현했습니다.
매끄럽게 새로운 데이터가 로드되지 않는 것이 고민입니다.🤔
![](https://i.imgur.com/5rJUdkt.gif)

> ☃️ refresh를 begin해야 하는 시점에 end를 해서 동작이 어색합니다. 또 서버에서 받아오는 응답이 너무 빨리와서 어색해보이는 거 같네요. 응답을 의도적으로 1초 정도 느리게 받았더니 자연스럽네요. 

``` swift 
    @objc func refreshCollectionView() {
        dataProvider.pageNumber = 1
        dataProvider.fetchData() { [self] products in
            DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
                guard var currentSnapshot = currentSnapshot else {
                    return
                }
                currentSnapshot.deleteItems(currentSnapshot.itemIdentifiers)
                currentSnapshot.appendItems(products)
                dataSource?.apply(currentSnapshot)

                DispatchQueue.main.async {
                    self.refresh.endRefreshing()
                }
            }
        }

        DispatchQueue.main.async {
            self.collectionView?.refreshControl?.beginRefreshing()
        }
    }
```
https://user-images.githubusercontent.com/37682858/170880455-22701310-fdb7-4076-832b-3ea7e833d789.mp4

또는 begin 시점에 empty snapshot을 적용하는 방법도 있습니다.
``` swift 
DispatchQueue.main.async {
    self.collectionView?.refreshControl?.beginRefreshing()
    let emptySnapshot = NSDiffableDataSourceSnapshot<Section, Product>()
    self.dataSource?.apply(emptySnapshot)
}
```
https://user-images.githubusercontent.com/37682858/170880443-13973040-7854-4429-9c78-161459348b83.mp4

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/BaseViewController.swift
> +        configureHierarchy(collectionViewLayout: listLayout ?? UICollectionViewLayout())
여기는 ?? 로 대체할 값을 넣어줄게 아니라 guard 문으로 언래핑 해줘야하지 않을까요? listLayout이 없다면 정상적인 동작을 못하니 guard문에서 에러처리를 하는게 나아보입니다.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/BaseViewController.swift
> +            collectionView?.setCollectionViewLayout(gridLayout, animated: false)
애니메이션을 꺼준 이유가 있을까요?

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/BaseViewController.swift
> +    }
collectionViewLayout을 파라미터로 받지만 listLayout를 적용하네요. 그리고 94번째 라인의 collectionView도 guard 문으로 감싸서 언래핑 후 에러가 있다면 에러 처리를 함이 나아보입니다.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    private var refresh = UIRefreshControl()
var인 이유가 있을까요? 그리고 프로퍼티 이름이 동사인게 어색합니다.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
>          dataSource?.apply(currentSnapshot ?? NSDiffableDataSourceSnapshot())
여기도 옵셔널 바인딩 후 에러처리를 해주세요.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        dataProvider.pageNumber = 1
pageNumber가 몇인지 view는 궁금하지 않습니다. view는 이벤트를 전달만 할 뿐이니까요.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
cellForItem 메소드를 부르는 이유가 있나요? 그냥 indexPath만 비교하는 것과 차이는 뭔가요?
그리고 self를 강하게 캡쳐한 이유가 있을까요?

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
>              }
MainViewController에서 해야할 일인가요?
`DataProvider`와 `HTTPManager`의 차이는 뭔가요?

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewControllerUnderiOS14.swift
> +    private var isFirstSnapshot = true
안쓰이는 프로퍼티 같습니다.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewControllerUnderiOS14.swift
> +        }
중복되는 코드가 발생하네요. 여러가지 이유가 있지만 view관련 분기를 쳐야한다면 클래스 단위가 아니라 클래스 내부에서 쳐야하는 이유 중 하나입니다.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +    }()
특정 indexPath의 cell이 TextCell라고 특정 할 수 있나요? 
지금은 가능한 코드입니다만, 혹시 셀이 추가되거나 뷰의 구조가 바뀌면 guard문을 통과하지 못할수도 있습니다.
그럴때마다 이 코드를 수정해야겠군요.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +    }
이미 init 메소드가 있는데 사용하지 않고 따로 메소드를 만든 이유가 있을까요?
이전에도 비슷한 피드백을 드렸던 거 같습니다.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +        setUpNavigationItem()
이건 viewDidLoad에서 할 일 같습니다.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +        configureHierarchy(collectionViewLayout: collectionViewLayout ?? UICollectionViewLayout())
가드문을 사용해주세요.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +    }
constraint의 activate 상태를 변경하는 것보다는 constant를 변경하는게 어떨까요? 그리고 특정 값을 하드코딩으로 넣는 것은 지양해주세요.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +        }
view에서 할 일이 아니라고 생각됩니다. 이전 코멘트에서도 적었지만, view는 이벤트를 전달만 할 뿐입니다.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +        collectionView = UICollectionView(frame: CGRect(x: 0, y: 100, width: self.view.frame.width, height: self.view.frame.height - 100), collectionViewLayout: collectionViewLayout)
frame을 넣어주고 아래에서는 오토레이아웃을 잡아주네요. 이 코드의 의도는 뭔가요?

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +                fatalError("Unknown section!")
차라리 크기가 1인 section을 반환하는게 어떨까요?

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +        collectionView.isScrollEnabled = false
스크롤을 막은 이유가 궁금합니다!

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +    }
collectionView 내부의 content 크기를 조절하고싶다면 contentInset 프로퍼티를 수정하는게 어떨까요?

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +                return UICollectionViewCell()
이 코드가 실행된다면 앱이 죽지않을까요? collectionView에 register되지 않은 셀이나오니까요.
저는 이런 경우 미리 `UICollectionViewCell`을 collectionView에 register하고 반환합니다.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +        productInput["currency"] = value
`"currency"` 이런 key에 대한 정보는 view가 아니라 model에서 들고있어야할 정보 같습니다.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Model/HTTPManager.swift
> +import UIKit
UIImage를 다루기위해 UIKit을 임포트 하셨군요.
그런데 정말 HTTPManager에서 UIImage를 알아야할까요? HTTPManager는 Data를 서버로부터 받아오고, 클라이언트의 Data를 서버로 전달하는 역할같습니다.
여러개의 layer로(DataProvider가 HTTPManager를 감싸서 사용하는 것 처럼) 역할을 분리하는게 어떨까요?

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Model/HTTPManager.swift
> +            }
어떤 statusCode 에러인지도 같이 넘겨주세요.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Model/HTTPManager.swift
> +            }
error를 넘길일이 없어보이는데, error가 왜 들어간건가요?
141~144 번째 라인은 invalidStatusCode가 아니라 응답 에러 같습니다.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ImageCell.swift
> +    }()
이건 왜 필요한가요? contentView로는 해결이 안되는 부분이 있었을까요?

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ImageCell.swift
> +    }()
외부에서 알아야하는 프로퍼티인가요? 만약 프로퍼티에 접근해야한다면 따로 특정 동작을 하는 인터페이스를 만들어서 접근해주세요.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/TextCell.swift
> +    }
padding을 주는 코드네요. leftView라는 이름보다는 어떻게 사용되는지로 지으면 좋겠습니다.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ImageCell.swift
> +    }
내부 코드도 view 단위로 나눠주세요.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/TextCell.swift
> +    var delegate: ValueObserable?
강한 참조 약한 참조에 대해서 공부해보세요. 
또한 UIKit의 delegate는 어떻게 선언되어 있는지도 같이 보면 좋겠네요.

2022-05-29 16:36 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
beginRefreshing이 들어가야할 시점 같습니다.

2022-05-30 01:20 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/BaseViewController.swift
> +            collectionView?.setCollectionViewLayout(gridLayout, animated: false)
animation이 없는게 더 이쁜 것 같아서 false로 줬습니다!

2022-05-30 01:22 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/BaseViewController.swift
> +        configureHierarchy(collectionViewLayout: listLayout ?? UICollectionViewLayout())
configureHierarchy메서드의 매개변수를 옵셔널로 바꾸고 내부에서 guard let 으로 처리하도록 수정했습니다.

[00732f6](https://github.com/yagom-academy/ios-open-market/pull/160/commits/00732f6ec4de58dce60f4dd18cb408949b4b2cf5)

2022-05-30 01:34 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/BaseViewController.swift
> +    }
UICollectionView를 만들 때의 옵셔널 처리하는 방식이 이상해보여서 매개변수를 사용해서 레이아웃을 잡도록 수정했습니다.
collectionView는 guard let으로 바인딩 후 진행하도록 수정했습니다.

[72109a1](https://github.com/yagom-academy/ios-open-market/pull/160/commits/72109a1a12a18aee2c2618bb60c4d29e3996e9ee)

2022-05-30 02:26 UTC, papriOS commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +    private var refresh = UIRefreshControl()
var이어야하는 이유가 없습니다😅 프로퍼티 네이밍 refreshControl로 변경해주었습니다 감사합니다!

2022-05-30 02:38 UTC, papriOS commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
>          dataSource?.apply(currentSnapshot ?? NSDiffableDataSourceSnapshot())
옵셔널 바인딩 진행하고 [a098dba](https://github.com/yagom-academy/ios-open-market/pull/160/commits/a098dbab7d194ab4edc887f54de0fe9206555430)
에러처리로 알랏을 띄우도록 하였습니다! [f425831](https://github.com/yagom-academy/ios-open-market/pull/160/commits/f425831f6930abfd6113d9a67d3618cfebfc437a)

2022-05-30 02:46 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        dataProvider.pageNumber = 1
DataProvider에 첫 화면부터 load할 수 있는 메서드를 구현했습니다.

https://github.com/yagom-academy/ios-open-market/pull/160/commits/f97d711e4ca357797a90b04ba16b00e9191101df

2022-05-30 08:02 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
매개변수로 받은 indexpath를 어떤 것과 비교하냐의 차이인 것 같습니다.

아래 코드는 snapShot의 item을 확인해서 last의 index와 화면의 띄우려는 셀의 indexPath를 비교해서 같으면 데이터를 fetch 합니다.
+1과 같은 연산이 따로 필요없어서 가장 깔끔한 방식인 것 같습니다.
따라서 아래의 코드로 커밋했습니다.
4e6f3b77293e23014b00b1167548b75458736ade
```swift
        guard let product = currentSnapshot?.itemIdentifiers.last else {return}
        guard currentSnapshot?.indexOfItem(product) != indexPath.row else {
            dataProvider.fetchData() { products in
                DispatchQueue.main.async { [self] in
                    updateSnapshot(products: products)
                }
            }
            return
        }
```

아래 코드는 dataSource에서 `IndexPath(row: indexPath.row + 1, section: 0)` 에 값이 있는지를 확인하고 값이 없으면 fetch합니다.
```swift
       guard dataSource?.itemIdentifier(for: IndexPath(row: indexPath.row + 1, section: 0)) != nil else {
            dataProvider.fetchData() { products in
                DispatchQueue.main.async { [self] in
                    updateSnapshot(products: products)
                }
            }
            return
        }
```

기존의 코드는 collectionview에서 해당 `IndexPath(row: indexPath.row + 1, section: 0)`로 cell을 만들 수 있냐를 확인합니다.
cellForItem 메서드는 cell을 반환해줍니다.
```swift
        guard let _ = collectionView.cellForItem(at: IndexPath(row: indexPath.row + 1, section: 0)) else {
            dataProvider.fetchData() { products in
                DispatchQueue.main.async { [self] in
                    updateSnapshot(products: products)
                }
            }
            return
        }
```

2022-05-30 08:06 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
순환 참조 문제가 생기지 않도록 클로저 내부에서는 약한 참조를 하도록 수정했습니다.

dbdc5140a4c0c6fd4eea41b7c97e310d39416eed

2022-05-31 02:01 UTC, papriOS commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
>              }
`HTTPManager`는 클라이언트(앱)과 서버의 통신을 담당하고,
`DataProvider`는 서버와의 통신으로 받아온 데이터를 만들어둔 모델타입으로 만들어 뷰에 제공합니다.
역할 분리가 제대로 이루어지지 못하여 이 부분 수정하였습니다!

또한 서버에 데이터를 POST,  PATCH하는 과정은 `DataSender`를 만들어 이를 통해 모델타입의 데이터를 HTTPManager가 네트워크 통신으로 post와 patch가 가능하도록 역할분리를 해 주었습니다.

`DataProvider`와 `DataSender`는 설계상 유일한 컴포넌트라고 생각하여 싱글톤으로 구현했습니다. 
(`DataSender`의 경우 구조체로도 구현이 가능하지만 `DataProvider`와의 통일성을 위해 싱글톤으로 구현했습니다.)

2022-05-31 02:07 UTC, papriOS commented on OpenMarket/OpenMarket/Controller/MainViewControllerUnderiOS14.swift
> +    private var isFirstSnapshot = true
불필요한 프로퍼티가 맞습니다😅 삭제하였습니다. [9be6b1b](https://github.com/yagom-academy/ios-open-market/pull/160/commits/9be6b1b8d7337d54589e130a991188866cf2c096)

2022-05-31 02:24 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +    }()
TextProtocol을 구현했습니다.
입력란과 관력된 cell이 이 프로토콜을 채택하면 위 부분을 매번 수정하지 않아도 될 것 같습니다.

https://github.com/yagom-academy/ios-open-market/pull/160/commits/2fd8163891f489bf40a47748525630058ae537a6

2022-05-31 02:52 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +    }
viewController의 init에 대한 공부가 부족해서 메서드로 구현했습니다.😢

product 매개변수가 필요한 init을 convenience init으로 수정했습니다.

https://github.com/yagom-academy/ios-open-market/pull/160/commits/cc7d83c152966886a66a421613421ff174a15ed3

designated init에서는 super.init을 호출해야하지만 convenience init은 self.init을 호출해야 하는 차이가 있다고 알고 있습니다.

그렇다면 designated init과 convenience init을 구현하는 기준이 무엇이 되는지 궁금합니다.🤔

2022-05-31 02:54 UTC, papriOS commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +        setUpNavigationItem()
`loadView`와 `viewDidLoad`에 대한 이해가 부족했던 것 같습니다.
커스텀뷰를 해당 뷰 컨트롤러의 기본 뷰로 설정하는 것이 아니라,
`setUpNavigationItem()`는 뷰가 생성된 이후에 navigationItem을 세팅해 얹어주는 일을 하니, `viewDidLoad`로 위치를 변경시켰습니다. 감사합니다!
[5e8a70b](https://github.com/yagom-academy/ios-open-market/pull/160/commits/5e8a70b0d342fc41ac604ec672c7d52d997d6366)

2022-05-31 03:03 UTC, papriOS commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +        configureHierarchy(collectionViewLayout: collectionViewLayout ?? UICollectionViewLayout())
configureHierarchy()의 매개변수를 옵셔널로 변경하여, 내부에서 옵셔널 바인딩을 진행하는 것으로 수정했습니다!
[0e79efd](https://github.com/yagom-academy/ios-open-market/pull/160/commits/0e79efd6b3b318980140325b45d62555e5495598)

2022-05-31 06:44 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +    }
~키보드의 높이에 따라 constant가 변경되도로 수정했습니다.~

~de02434b30da89973f341bfc3058c6cde8e302e4~

조언해주신 방식 반영하여 수정 진행했습니다.

fc0fd5ed247d902a5f12a443ab2fe080c2d41dc0

2022-05-31 06:45 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +        }
DataSender 타입으로 구현했습니다.

0a2ece86f91c088a9dcba348daf19cc7d542e80a

2022-05-31 06:46 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +        collectionView = UICollectionView(frame: CGRect(x: 0, y: 100, width: self.view.frame.width, height: self.view.frame.height - 100), collectionViewLayout: collectionViewLayout)
불필요한 레이아웃 설정은 .zero로 수정했습니다.

dfc1e858af5ab34348764a9148c7f4d96d47a976

2022-05-31 06:56 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +                fatalError("Unknown section!")
fatalError 대신에 section을 할당하도록 수정했습니다.

9d6194d1dbb2abdd21a41485bcb0179298043976

section 설정을 위한 메서드를 NSCollectionLayoutSection에서 타입 메서드로 구현했는데요. 인스턴스 메서드로 만드는 방법이 궁금합니다. 🤔
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/70807352/171111183-c9eceeaf-b663-4d83-96d5-079e90f4eae6.png">

2022-05-31 07:05 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +        collectionView.isScrollEnabled = false
![May-31-2022 16-03-44](https://user-images.githubusercontent.com/70807352/171112545-41c74f08-a240-47f7-bd25-bb5ce5906d40.gif)

스크롤이 가능하면 위처럼 UI 요소가 겹쳐지는(?) 현상이 보이는데 이를 막고 싶었습니다

2022-05-31 07:44 UTC, papriOS commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +                return UICollectionViewCell()
넵 등록되지 않은 셀 때문에 문제가 생길 것 같습니다. 조언해주신대로 
`registerCell()`에서` UICollectionViewCell`을` register` 했습니다! [9119165](https://github.com/yagom-academy/ios-open-market/pull/160/commits/911916567389060f970914377116063aa68c675d)

2022-05-31 10:47 UTC, papriOS commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +        productInput["currency"] = value
ProductInput이라는 Model을 구현하여 key정보를 view가 갖지 않도록 수정하였습니다!

[5e01fa3](https://github.com/yagom-academy/ios-open-market/pull/160/commits/5e01fa3e82bf13342031c0d9ffbc39ad08286133)

2022-05-31 11:24 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Model/HTTPManager.swift
> +import UIKit
converImage 메서드를 DataSender에서 구현하고 HTTPManager에서는 Data 타입을 사용하도록 수정했습니다.

cc7f08cf9964f4a93a2c7facfc83e0610195b69f

2022-05-31 11:29 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Model/HTTPManager.swift
> +            }
statusCode도 알 수 있도록 수정했습니다.

fae8e546563c09b16a4e2dc217e7b202401e4fc5

2022-05-31 11:59 UTC, papriOS commented on OpenMarket/OpenMarket/Model/HTTPManager.swift
> +            }
넵 같이 전달할 수 있도록 수정하였습니다! [f13d06f](https://github.com/yagom-academy/ios-open-market/pull/160/commits/f13d06f0b70f86bb3bd6691797680b0cc726f63f)

2022-05-31 12:01 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/View/ImageCell.swift
> +    }()
구현 당시에 contentView에 넣으면 imageCell이 제대로 나오지 않는 문제가 있어서 view를 만들었던 것 같습니다.(오류를 기록하지 않아서 정확한 이유는 기억이 안 납니다😢 레이아웃의 문제였던 것 같기도 합니다.)

view를 삭제하고 contentView에 서브뷰를 추가하니 지금은 잘 되어서 view를 삭제하는 것으로 수정했습니다.

ecb6291222df590c3361acd06c42f1ad013bf7a9

2022-05-31 12:04 UTC, papriOS commented on OpenMarket/OpenMarket/Model/HTTPManager.swift
> +            }
넵 응답에러를 `responseError`라는 이름으로` NetworkError`에 추가하였습니다.
default 로 빠지게 되는 경우는 사용자의 요청이 잘못되었을때 라서, `invalidRequest`라는 case를 추가하고 [5914fdd](https://github.com/yagom-academy/ios-open-market/pull/160/commits/5914fdd7482f2cd9016b90f9f3032616c7863b6a)
해당 completionHandler에 statusCode만 전달 할 수 있도록 수정했습니다. [f13d06f](https://github.com/yagom-academy/ios-open-market/pull/160/commits/f13d06f0b70f86bb3bd6691797680b0cc726f63f)

2022-05-31 12:34 UTC, papriOS commented on OpenMarket/OpenMarket/View/ImageCell.swift
> +    }()
![contentView로하면cell이안눌림](https://user-images.githubusercontent.com/98319774/171173583-704a1627-7651-4dea-aef5-ee5fafd1101f.gif)

수정 후 다시 확인해보니 contentView에 subView를 추가하는 방향으로 변경한 이후, plusButton을 눌러 이미지를 추가하는 기능이 제대로 동작하지 않음을 확인했습니다. 아마 이러한 이유에서 이전에 contentView를 사용하지 않았던 것 같습니다.

2022-05-31 13:06 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/View/ImageCell.swift
> +    }()
메서드나 연산 프로퍼티를 통해 접근하도록 수정했습니다.

2e208da377f0f11564d34e0f14867bd679b57f22

2022-05-31 13:49 UTC, papriOS commented on OpenMarket/OpenMarket/View/ImageCell.swift
> +    }()
넵! ImageCell 뿐만아니라 TextCell, ProductListCell, ProductGridCell에서도 외부에 노출되지 않아도 될 프로퍼티에 대하여 은닉화를 진행하였습니다.
[2e208da](https://github.com/yagom-academy/ios-open-market/pull/160/commits/2e208da377f0f11564d34e0f14867bd679b57f22)
[17d4ad2](https://github.com/yagom-academy/ios-open-market/pull/160/commits/17d4ad297a9b4deec92da5ede42317ad0d5013a5)
[8d05391](https://github.com/yagom-academy/ios-open-market/pull/160/commits/8d05391d0d54fe45eec54003f9fe8b197b1e142f)
[915edd1](https://github.com/yagom-academy/ios-open-market/pull/160/commits/915edd1cc7b3a6be414101806cf5fa0c5213d373)

2022-05-31 14:08 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/View/TextCell.swift
> +    }
setUpLeftPadding으로 네이밍 변경하였습니다.

8a25a2ead74df70ef7ba76dff6651ff9677fc76c

2022-05-31 14:09 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/View/ImageCell.swift
> +    }
각 element layout을 설정하는 메서드와 addView로 뷰 계층을 만드는 부분을 메서드로 분리했습니다.

889a4c5d42156914063f4c796300f25f8b6da916

2022-05-31 14:11 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/View/TextCell.swift
> +    var delegate: ValueObserable?
약한 참조하도록 수정했습니다

https://github.com/yagom-academy/ios-open-market/pull/160/commits/496a895dedf9e9b7d0c623d0f4320925cb770cbc

2022-05-31 14:56 UTC, papriOS commented on OpenMarket/OpenMarket/View/TextCell.swift
> +    var delegate: ValueObserable?
UIKit의 delegate가 어떻게 선언되었는지 확인하는 과정에서
프로토콜 네이밍 또한, UITextField의 delegate가 `weak var delegate: UITextFieldDelegate`임을 확인하여
TextCellDelegate로 변경해보았습니다.
[c553036](https://github.com/yagom-academy/ios-open-market/pull/160/commits/c5530367f98503f6fbeacf9223b9c3ab41cb5e44)

또한 코드 전반에 걸쳐 클로저 캡쳐 시 약한 참조가 되도록 수정했습니다!
[ae1fc12](https://github.com/yagom-academy/ios-open-market/pull/160/commits/ae1fc126da2a9aea9c17224efc5900aee8559ca5)

2022-06-01 01:32 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
위에서 조언해주신 것 참고하여 코드 수정했습니다! 감사합니다

aec7469509c7c6cc131abf7139cd3a07caf880e5

2022-06-01 06:41 UTC, Kim-TaeHyun-A commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +    }
올라프가 말씀하신 contentInset을 사용해서 수정해보았습니다.

먼저 collectionView의 프로퍼티로 시도했는데 collectionView의 contentInset을 설정하는 부분을 위 코드 근처에서 작성했습니다. 이때, right와 bottom이 아예 적용되지 않았습니다.

레이아웃이 적용되는 순서를 디버깅해보니 `layoutCollectionView()` -> `createLayout()` 2번 -> `collectionView(_: cellForItemAt:)` -> ImageCell의 레이아웃 설정하는 메서드(ex. `plusButtonLayout()`) -> textCell의 레이아웃 설정하는 메서드(ex. `layout()`) 순으로 호출 됩니다.

`configureHierarchy` 메서드가 `createLayout` 메서드보다 먼저 호출되는 것이 이상한 것 같습니다. 비동기적으로 동작하는 코드인지 아니면 컴파일 과정에서 매개변수로 사용되는 시점에서 호출된 것인지 잘 모르겠습니다.🤔


---

section의 contentInset 프로퍼티를 사용해서 section과 contentView의 간격을 조절해서 이전의 모습과 유사하게 만드려고 수정했습니다.

c24bb2341e1dd43f2039a29306c921a5f86b540c

2022-06-01 08:04 UTC, papriOS commented on OpenMarket/OpenMarket/Controller/UpdateProductViewController.swift
> +    }()
셀 추가나 뷰 구조의 변화에 대응하기 위해 위에서 올라프가 알려주신 것을 참고하여, 
collectionView의 bottomConstraint를 키보드 높이 변화에 맞춰주도록 변경하였습니다! [fc0fd5e](https://github.com/yagom-academy/ios-open-market/pull/160/commits/fc0fd5ed247d902a5f12a443ab2fe080c2d41dc0)

그 과정에서 TextProtocol을 구현했던 걸 삭제하고, baseStackView를 은닉화 하였습니다. [c95305f](https://github.com/yagom-academy/ios-open-market/pull/160/commits/c95305f183aba9262a73dfc8b86b266a557f0604)

2022-06-01 14:25 UTC, papriOS commented
안녕하세요 올라프⛄️
조언해주신 것 반영해서 수정했는데 확인 부탁드립니다🙇‍♀️🙇‍♀️
아래는 저번 PR에서 답변이나 질문 주신 것에 대한 내용입니다.

---

### 전반적인 구조
> ☃️ viewController가 view의 역할 이외의 역할을 하고 있지는 않은가요? 코멘트에 남겼으니 참고해보세요.

`UpdateProductViewController`에서 역할 분리를 하려고 노력했는데 제대로 되었는지 확인 부탁드립니다.

### HTTPManager 코드 중복
> ☃️ dataTask의 completionHandler 부분은 하나의 메소드로 추상화 할 수 있어보입니다. 하지만 이 메소드를 사용하는 get, post, put, delete는 각각 별도의 메소드로 다른 동작을 가지는게 좋겠네요.

하나의 메소드로 추상화를 해보았습니다. 
[dataTask의 completionHandler를 dataTaskCompletionHandler로 추상화](https://github.com/yagom-academy/ios-open-market/pull/160/commits/cae54b8bc80b29f8f19fac253e7fa62bde3d4783)

`listenHealthChecker()`도 고려해서 `dataTaskCompletionHandler` 메서드를 구현해야 할지 궁금합니다.

고려하게 된다면 `dataTaskCompletionHandler`에 분기문을 만들어 줘야하여 메소드가 길어집니다.

또한 `listenHealthChecker`의 위치에 대해서도 의문이 들었습니다.
테스트를 할 때만 `listenHealthChecker`를 사용했는데 테스트 모듈에 넣는게 적절한지 고민이 됩니다!


### enter를 눌렀을 때 프로퍼티에 값 반영

> ☃️ 이건 그냥 정책의 문제 같은데요. 얼마나 자주 저장할지에 대해 팀 내부에서 정하고 그에 맞게 구현하면 되겠습니다.


`textField`와 `textView`에 값을 입력할 때마다 저장하는 방향으로 결정하였습니다
[textField의 input값 할당 메서드 변경](https://github.com/Kim-TaeHyun-A/ios-open-market/commit/b620b4cb1bbb3fda3fcce0a4f1ce559b3a0a1ede)


### post 문제
> ☃️ 어떤 에러가 발생했는지도 같이 알려주면 좋겠습니다. 에러 로그도 있으면 좋고요. 이부분만 가지고는 어떤 상황인지 알수가 없네요.

아예 iOS13에서는 post가 되지 않는 상황이었습니다.
statusCode 가 적절하지 않아서 발생한 문제여서 아래처럼 수정하고 해결했습니다.

[fix: 통신 성공 시 만족해야하는 StatusCode 변경](https://github.com/yagom-academy/ios-open-market/pull/160/commits/f7df8a5e2e9fee58871c29ad2203ab203f12d9a4)

2022-06-02 11:11 UTC, merged