오픈마켓 II [STEP 1] 우롱차, Donnie
yagom-academy/ios-open-market pull request #162
Opened 2022-05-27 17:17 UTC by westeastyear

안녕하세요! @TTOzzi...😭😭
[STEP 1] PR 보냅니다 🙇🏻‍♂️
늦어서 죄송한 마음뿐입니다.

## 🧐 고민한 점

### 1. 추가한 사진을 삭제하는 방법 & 5개로 제한걸기
> - 이미지 뷰를 위로 올렸을때 삭제가 되도록 `swipeGesterRecognizer`를 사용하여 만들었습니다. 애니매이션을 사용하여 움직이게끔 하면 더 좋을꺼 같습니다. 
> - 이전에 `UIPanGesterRecognizer`를 사용했었을 땐 가로 `scrollView`가 잘 동작하지 않는 이슈가 있었습니다.
> - 이미지 뷰 삭제시 + 버튼이 나오도록 하는 부분을 `if-else`문으로 구현하였습니다. 
> - 이미지 5개를 추가하면 버튼이 사라지게 되는데, 이후에 이미지를 삭제하면 버튼이 나오지가 않는걸 알게 되어 옵저버 패턴으로 구현되어야 할거 같다는 고민을 하였습니다.

<br>

```swift
if addImageHorizontalStackView.arrangedSubviews.count == 6 {
    addImageButton.isHidden = true
} else {
    addImageButton.isHidden = false
}
```

<br>

### 2. 조건에 충족하지 못할때마다 Alert으로 처리하려고 고민하였습니다.
> - 조건에 충족하지 못했을때 각 조건별로 `alert` 처리를 하려고 하였으나, 하지 못하였습니다...ㅠㅠ

<br>

```swift
func wrapperRegistrationParameter() -> RegistrationParameter? {
    guard let name = nameTextField.text, name.count >= 3 else {
    //알랏 띄워주기
    return nil
    }
    guard let descriptions = textView.text, descriptions.count < 1000 else {
        return nil
    }
    guard let price = Double(priceTextField.text ?? "0"), price >= 0 else {
        return nil
    }
    guard let selectedText = currencySegmentedControl.titleForSegment(at: currencySegmentedControl.selectedSegmentIndex), let currency = Currency(rawValue: selectedText) else {
        return nil
    }
    guard let discountedPrice = Double(discountPriceTextField.text ?? "0"), discountedPrice >= 0 else {
        return nil
    }
    guard let stock = Int(stockTextField.text ?? "0"), stock >= 0 else {
        return nil
    }
    let secret = Secret.registerSecret
```

<br>

## 😆 조언을 받고 싶은 부분
### 1. keyBoard가 UI를 가리는 현상
> - 4개의 `textField`는 키보드가 가리지 않았고, `textView`에서만 키보드가 UI를 가리는 현상이 있어 view를 올리는 작업을 `textView`에 포커싱이 되는 경우에만 작동하려고 하였지만 잘 되지 않았습니다.
> - 현업에서는 어떠한 스타일로 구성하는지 궁금합니다. 
> - 또, 원하는 `UI`에서 포커싱 되는 경우에서 `keyBoard`를 컨트롤 하려면 어떻게 해야 하는지 궁금합니다. 

<br>

### 2. 공통 뷰에서 상속 받는경우 어디만큼 private을 해줘야 되는지?
> - 현재 `RegisterEditBaseViewController`를 베이스 뷰로 사용하여 `RegisterViewController`를 사용하고 있는데 기본 뷰에서 버튼같은 요소들을 `private`으로 사용하다가 상속해서 사용해야되니까 `Private`을 풀어주었습니다. 
> - 마음 같아서는 다 `Private`을 해제하고 쓰고 싶은데 이에 대한 의견이 궁금합니다.

<br>

### 3. 상품등록 후, 첫화면으로 돌아가서 pullToRefresh를 하지 않고 화면을 업데이트 방법이 있을까요?
> - 상품을 등록한 후, 첫화면으로 돌아가게끔 만들었는데 화면을 밑으로 당기면 새로고침되도록 구현하였습니다. 
> - 사용자 입장에서 생각했을깨 번거로울 수 있다고 생각이 들었고 새로고침할 필요없이 화면이 변경되거나 하면 좋겠는데 잘 되지 않았습니다.
> - `navigationController.popViewController`을 하면서 데이터를 업데이트 하면 되지 않을까?란 생각을 했지만 결국 첫화면으로 돌아가서 `refreshControl`를 구현하였습니다.

<br>

### 4.Array에 접근할때 안전하지 않은 접근 
> - Array에 접근할때 안전하지 않다고 느끼는데 개선점이 있을까요?

```swift
func addLastBehind(view: UIView) {
        let lastViewCount = self.arrangedSubviews.count
        if lastViewCount <= 1 {
            self.insertArrangedSubview(view, at: 0)
        } else {
            self.insertArrangedSubview(view, at: lastViewCount - 1)
        }
    }
```

<br>

## 🥄 삽질한점 🥄
### 1. 명세서와 example Code의 파라미터가 동일하지 않아서 삽질...🤬🤬
> - `POST`방식으로 통신했을때 명세서에서의 `Parameter`와 `example code`에서의 네이밍이 달라서 오류 찾느라 삽질을 하였습니다.

<br>

2022-05-29 16:40 UTC, TTOzzi requested changes
안녕하세요 우롱차, 도니!
이전 스텝 수정사항까지 모두 반영하느라 힘드셨을텐데 정말 고생 많으셨습니다 :bow::bow:

한 가지 확인이 필요한 부분이 있는데요.
현재 PR 보내신 브랜치 최신 커밋 기준으로 상품 등록 화면 진입 시 크래시가 발생하고 있어요.
이번 스텝에선 UI 구현도 중요한 경험이라 직접 실행해보고 피드백을 드려야 할 것 같은데, 이 부분이 고쳐져야 가능할 것 같습니다 :cry:

확인 한 번 부탁드릴게요 :pray:

### keyBoard가 UI를 가리는 현상

> - 4개의 `textField`는 키보드가 가리지 않았고, `textView`에서만 키보드가 UI를 가리는 현상이 있어 view를 올리는 작업을 `textView`에 포커싱이 되는 경우에만 작동하려고 하였지만 잘 되지 않았습니다.

`textView`가 포커싱되는 시점은 `UITextViewDelegate`를 활용해볼 수 있을 것 같네요 :thinking:
어떤 시도를 해보셨는데 잘 되지 않았는지 말씀해주시면 좀 더 자세한 코멘트를 드릴 수 있을 것 같아요!

> - 현업에서는 어떠한 스타일로 구성하는지 궁금합니다.

키보드로 인해 UI가 가려질때의 처리를 말씀하시는 걸까요?
구현하신 것 처럼 `transform`을 활용하기도 하고, 뷰를 직접 옮겨주거나 스크롤뷰를 활용해 뷰를 이동시켜주기도 하고 상황에 따라 다르게 구현하는 것 같습니다.

> - 또, 원하는 `UI`에서 포커싱 되는 경우에서 `keyBoard`를 컨트롤 하려면 어떻게 해야 하는지 궁금합니다.

요건 위에서 답변드린 것처럼 제공되는 Delegate 메서드를 활용해보시면 될 것 같아요!

### 공통 뷰에서 상속 받는경우 어디만큼 private을 해줘야 되는지?

> - 현재 `RegisterEditBaseViewController`를 베이스 뷰로 사용하여 `RegisterViewController`를 사용하고 있는데 기본 뷰에서 버튼같은 요소들을 `private`으로 사용하다가 상속해서 사용해야되니까 `Private`을 풀어주었습니다.
> - 마음 같아서는 다 `Private`을 해제하고 쓰고 싶은데 이에 대한 의견이 궁금합니다.

다 `Private`을 해제하고 쓰고 싶으신 이유가 궁금해요 :eyes:
상속받은 클래스나 외부에서 접근이 필요한 부분만 열어주면 되지 않을까요?

### 상품등록 후, 첫화면으로 돌아가서 pullToRefresh를 하지 않고 화면을 업데이트 방법이 있을까요?

> - 상품을 등록한 후, 첫화면으로 돌아가게끔 만들었는데 화면을 밑으로 당기면 새로고침되도록 구현하였습니다.
> - 사용자 입장에서 생각했을깨 번거로울 수 있다고 생각이 들었고 새로고침할 필요없이 화면이 변경되거나 하면 좋겠는데 잘 되지 않았습니다.
> - `navigationController.popViewController`을 하면서 데이터를 업데이트 하면 되지 않을까?란 생각을 했지만 결국 첫화면으로 돌아가서 `refreshControl`를 구현하였습니다.

간단한 구현은 `viewWillAppear` 시점에서 업데이트 해줄 수 있을 것 같고, 좀 더 디테일하게 구현하면 상품 등록 화면에서 상품을 등록했을 때 delegate 패턴이나 클로저 등을 활용해 이벤트를 리스트 화면으로 전달해줄 수 있을 것 같아요.

### Array에 접근할때 안전하지 않은 접근

> - Array에 접근할때 안전하지 않다고 느끼는데 개선점이 있을까요?

`insertArrangedSubview`에서 `index`를 넘기는 부분을 말씀하시는 거라면, 호출 전 전달할 `index`가 범위 내에 있는지 확인하는 로직을 추가해줄 수 있을 것 같아요.
다만 현재 구현하신 로직에선 `arrangedSubviews`의 `count`를 꺼내 계산을 하고 있어서 방어로직을 추가해 줄 필요는 없을 것 같습니다.

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/EditViewController.swift
> +final class EditViewController: RegisterEditBaseViewController {
요건 사용되지 않는 화면인가요? 👀

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        switch MainCollectionView.LayoutType(rawValue: self.segmentedControl.selectedSegmentIndex) {
여기서 접근하는 `self`는 `weak`가 필요하지 않을까요? 🤔

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
>              return cell
아래쪽이 살짝 잘리긴 했는데, `enum`을 switch-case로 처리할 땐 가급적이면 `default`를 사용하지 않는 것이 좋습니다.
`enum` 타입에 변경이 생겼을 때, 해당 `enum` 타입을 사용하는 곳에 케이스 추가/제거 처리가 필요함을 알 수 있도록요 🙂

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        refreshControl.endRefreshing()
`requestList` 가 비동기 로직인 것 같은데, `requestList`의 로직이 완료된 후에 `reloadData`, `endRefreshing`을 해줘야 하지 않을까요? 🤔

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
이곳의 `self`도 `weak`가 필요하지 않을까요? 👀

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        switch sender.selectedSegmentIndex {
여기도 `rawValue`를 꺼내서 비교하기 보단 `LayoutType`의 생성자를 활용해주면 더 깔끔해질 것 같아요.

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    lazy var stockTextField = generateTextField(placeholder: "재고수량", keyboardType: .numberPad)
여기 뷰들은 모두 외부로 노출되어야 하는 건가요?
필요한 값만 외부로 전달할 수 있는 통로를 만들거나, `private(set)`이라도 붙여주면 더 좋을 것 같습니다.

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    }
텍스트를 따로 나눠두는 기준이 궁금해요 👀 
`"상품명"`, `"상품가격"` 등의 텍스트는 사용하는 부분에서 바로 할당해주고 있는 것 같아서요 🤔

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    }
화면이 보여지고 사라질 때 마다 노티를 추가/제거하는 이유가 있을까요?
어차피 화면과 생명주기를 함께 할 것이라면 `viewDidLoad`에서 한 번만 추가해줘도 될 것 같아서요 🤔

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +            self.textView.resignFirstResponder()
단순히 키보드를 숨기기 위함이라면 `endEditing`을 사용할 수도 있을 것 같아요.

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +        let keyboardFrame: NSValue = userInfo.value(forKey: UIResponder.keyboardFrameEndUserInfoKey) as! NSValue
강제 언래핑 사용은 피해주세요 🙏

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    }
구현 예정인 부분인가요? 👀

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +    func addImageToStackView(image: UIImage){
외부에서 호출하지 않는 메서드는 `private` 붙여주세요 🙏 
추가로 띄어쓰기도 빠진 것 같네요 +_+
```suggestion
    func addImageToStackView(image: UIImage) {
```

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +        }
좀 더 간단하게 바꿔볼 수 있을 것 같아요.
```suggestion
        addImageButton.isHidden = (addImageHorizontalStackView.arrangedSubviews.count == 6)
```
`(addImageHorizontalStackView.arrangedSubviews.count == 6)`를 따로 상수로 빼줘서 의미를 부여해주면 더 좋을 것 같구요!

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +    }
사용자로부터 입력받은 값들의 유효성 검사 로직은 다른 객체로 분리할 수 있지 않을까요? 🤔

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +        }
배열을 다른 배열로 변환하는 로직은 `map`이나 `compactMap`을 사용해 더 간단하게 나타낼 수 있을 것 같아요.

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +        }
사용자가 무언가를 조건에 맞게 입력하지 않았거나, 다른 문제로 인해 상품 등록에 실패하는 경우 에러를 표시해줘야 할 것 같아요 🤔

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +                self.navigationController?.popViewController(animated: true)
이곳의 `self`도 `weak` 사용이 필요하지 않을까요?

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +            fatalError("error")
`fatalError` 말고 다른 처리 방법은 없었을까요? 🤔

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ImageCache.swift
> +    var network: NetworkAble { get }
`Cacheable` 프로토콜이 이 두 프로퍼티를 강제할 필요가 있을까요? 
`Cacheable` 구현체를 사용하는 곳에선 `Cacheable`의 구현체가 네트워크 통신을 어떻게 하고 있는지, 어떤 방식으로 이미지를 캐싱하고 있는지 알 필요가 없을 것 같아요 🤔

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ImageCache.swift
> +        }
URL 변환에 실패하거나, 네트워크 통신, 받아온 데이터 이미지 변환에 실패했을 때 `loadImage` 메서드를 호출한 곳에서 실패했음을 알 수 있도록 결과를 전달해줘야 할 것 같아요.

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ImageCache.swift
> +            self.imageCache.setObject(image, forKey: urlString as NSString)
여기 `self`도 `weak`가 필요하진 않을지 확인 부탁드립니다!

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/Network.swift
> +struct Network: NetworkAble {
여긴 로직이 아예 없어졌군요 🤔 
이 정도면 `Cacheable` 처럼 `NetworkAble`을 채택하는 객체가 하나 뿐이니 로직을 여기로 옮겨줘도 될 것 같네요 🤔 🤔

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/NetworkError.swift
> +    case decodingError
기존 `NetworkError` 명확하게 네트워크 통신을 담당하는 객체가 통신 과정에서 발생한 에러를 표현하고 있었는데, `ProductListUseCase`에서 반환하는 `decodingError` 에러를 가지게 되면서 조금 애매해진 것 같아요.
`ProductListUseCase`에서 반환하는 에러는 따로 묶어줄 수 있지 않을까요?

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/OpenMarketApi.swift
>          }
앞으로 케이스가 추가되더라도 항상 같은 동작을 할 것 같은데 조금 더 간단하게 바꿔줄 수 있을 것 같아요.
`?? nil`도 불필요한 코드 같습니다.
```suggestion
    var url: URL? {
        let urlComponents = URLComponents(string: urlString)
        return urlComponents?.url
    }
```

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +import UIKit
`Foundation`은 지워줄 수 있을 것 같아요 +_+

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +    private let pageInforManager = PageInfoManager()
의존성을 가지는 객체들은 추상화 후 외부로부터 주입받도록 구현하면 더 유연한 구조를 만들 수 있습니다 🙂 
추가로 기존 싱글톤 구현이었던 `Network`를 각각의 객체에서 생성하도록 변경하신 이유가 궁금해요 👀 
(`pageInforManager` 오타인 것 같아요!)

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +        decodingErrorHandler: @escaping (Error) -> Void
`decodingErrorHandler` 라기엔 다른 에러들도 반환하고 있는 것 같아 "decoding" 을 붙여주지 않아도 될 것 같네요 🤔

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +    ) -> URLSessionDataTask? {
여기도 `URLSessionDataTask`를 반환하도록 구현해주신 건 요청을 취소하는 경우까지 고려해주신 걸까요?
`URLSessionDataTask` 와의 의존성은 `UseCase` 레이어 까지만 갖도록 하고, 만약 `UseCase`에 접근하는 레이어에서 요청 취소가 필요하다면 다른 방식으로 처리해주는 게 좋을 것 같아요.

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +            decodingErrorHandler(NetworkError.urlError)
현재 구조상 `ProductListUseCase`가 반환하는 에러는 화면에 표시해야 할 에러일거라 `NetworkError`를 그대로 사용하기보단, 따로 에러를 정의해주는 것이 좋을 것 같아요.

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +            data, urlResponse -> Void in
여기만 클로저 컨벤션이 살짝 다른 이유가 있을까요? 👀

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +                  let dcodedData = try? jsonDecoder.decode(PageInformation.self, from: data) else {
`dcodedData` 오타 같아요! +_+
추가로 `decode` 메서드가 실패했을 때 디코드 실패 이유가 담겨있는 `DecodingError`를 던져주는데, 지금은 `try?`로 에러를 무시하도록 처리하고 있어 디코딩에 문제가 생겼을 때 디버깅이 어려울 것 같아요 🤔

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +    func registerProduct(
`"ProductList" UseCase` 인데 상품 등록 화면에도 사용되고 있네요 🤔 
다른 객체로 나눠주는 게 좋을 것 같습니다.

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +            return nil
이곳은 위의 메서드와 달리 예외처리가 빠져있네요 👀

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +        """)
요런 key-value 형태의 문자열은 객체로 만들어줄 수 있지 않을까요?

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +            guard let imageData = image.jpegData(compressionQuality: 0.1) else {
`compressionQuality`를 0.1로 정하신 이유가 궁금해요!
혹시 0.1로 압축한 이미지 화질이 어떤지 확인해보셨나요? 👀 

추가로 프로젝트 요구사항에
> 이미지는 최소 1장, 최대 5장까지 등록할 수 있으며, 각 이미지당 용량은 최대 300KB로 제한합니다

요런 문구가 있는데 이 부분에 대한 로직은 없는 것 같네요 🤔

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +    private var network = Network()
`network`는 없어도 될 것 같네요!

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +                    self.productImage.image = image
여기도 `weak` 처리 필요없을까요? 👀

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +                    self.productImage.image = image
여기도 `weak` 처리 필요하지 않을지 확인해주세요 🙏

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/String+Extension.swift
> +//  String.swift
파일명과 동일하게 맞춰주면 더 좋을 것 같아요.

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/View+Extension.swift
> +    func addLastBehind(view: UIView) {
요건 어떤 상황에 쓰이는지 궁금해요 👀

2022-05-29 16:40 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/View+Extension.swift
> +        }
개인 취향에 따라 조금 갈릴 것 같긴 한데.. 삼항 연산자를 활용해 좀 더 간단하게 표현할 수도 있을 것 같아요.
```suggestion
        let index = lastViewCount <= 1 ? 0 : lastViewCount - 1
        self.insertArrangedSubview(view, at: index)
```

2022-05-30 12:14 UTC, westeastyear commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    }
viewDidLoad에서 노티를 추가하는 방향으로 수정하였습니다. 또, viewWillDisappear로 해제를 하였습니다.

2022-05-30 12:46 UTC, westeastyear commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +        let keyboardFrame: NSValue = userInfo.value(forKey: UIResponder.keyboardFrameEndUserInfoKey) as! NSValue
시간에 쫒겨 구글링한것을 따라하다 보니 신경쓰지 못하였습니다ㅠㅠ 수정하였습니다!

2022-05-30 12:47 UTC, dnwhd0112 commented
1차 수정 완료했습니다!

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +    }
extension이 계속 늘어나다 보니 관리가 좀 힘든거 같습니다. model, view controller 별로 따로 모아놓아서 extension을 관리하는 편이 나을까요? extension의 분류 기준을 정하기가 힘드네요. 현재는 extension 타입마다 파일을 하나씩 만들고 있는대 차라리 extension을 모아놓고 타입마다 파일 네이밍을 붙이는게 더 나은 방향이라고 생각되네요.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +        data.appendString("\r\n--\(boundary)--\r\n")
body를 만들어주는 메서드를 만들까도 했지만... 매개변수로 넘겨주는 값이 많아져서 오히려 복잡해지지 않을까 하는 생각에 만들지 않았습니다.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +    ) -> URLSessionDataTask? {
func들을 프로토콜로 추상화해서 사용하는편이 좀 더 낫지않았을까 싶네요. 또치의 생각은 어떠신가요?

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/Secret.swift
> +}
사실 이부분은 커밋할 생각이 없었습니다. 깃허브라도 보여주면 안된다고 생각해서 파일을 따로 만들어서 관리하는게 맞지않나 싶었거든요. 다시 생각해보니 이걸 static let으로 파일 안에 있을만한건 아니네요.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +        let secret = Secret.registerSecret
생각해보니 secret을 여기서 입력해줄것이 아니라 추후 나중에 ViewController쪽에서 사용자에게 입력을 받고 매게변수로 넘겨주는 쪽이 더 나은거 같네요... 설계를 잘못했습니다.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/EditViewController.swift
> +final class EditViewController: RegisterEditBaseViewController {
네 상품 수정화면인데 다음 step에서 같이 구현할려고 합니다.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
>              return cell
알겠습니다! default를 안쓸경우 문법에러가 나는경우가 많아서 썻는대 안써도 괜찮군요! 그럼 .none은 사용해도 괜찮을까요?

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        refreshControl.endRefreshing()
생각해보니 그러네요... ㅋㅋㅋ
위치를 requestList의 completion Handler에 넣어줬습니다. weak self와 같이요!

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        switch sender.selectedSegmentIndex {
앗! 알겠습니다! 수정하도록 할게요!

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    }
아뇨 빈 함수로 만들고 상속받은 곳에서 오버라이딩해서 사용하고 있습니다.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +        }
오... 요런 방법이... 참고해서 수정하겠습니다.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +    }
아.. .분리해보겠습니다!

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +        }
넵 고차함수를 사용해서 짧게 표현해보... 려 했는데 고차함수로 변경할시 filter와 map을 둘다 써야 되더군요! 그래서 바꾸지 않았습니다.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +        }
네 알럿 처리를 추가하도록 하겠습니다.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +            fatalError("error")
음... 좀 더 고민해볼게요!

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ImageCache.swift
> +    var network: NetworkAble { get }
음 맞네요 loadImage만 있으면 될꺼같습니다.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ImageCache.swift
> +        }
이 부분은 completionHandler 쪽에 Nil을 전달하여 알리도록 하겠습니다.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/Network.swift
> +struct Network: NetworkAble {
아... 그러네요!

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/OpenMarketApi.swift
>          }
생각 해보니 그러네요. 바꿔주도록 하겠습니다!

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +import UIKit
앗... 이런

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +    private let pageInforManager = PageInfoManager()
기존 싱글턴 패턴을 유지하려고 했으나 싱글톤 구현일경우 session을 변경하는 테스트가 불가능해져서 롤백시켰습니다. pageInfoManager가 맞겠네요! 의존성 주입방법으로 변경하도록 하겠습니다. 
다만 이니셜라이저를 오버로딩해서 사용하고 싶은대 괜찮을까요? 
좀 더 생각해보니 뭔가 아닌거 같아서 오버로딩은 사용하지 않았습니다.
```swift
init() {
    self.network = Network()
    self.jsonDecoder = JSONDecoder() 
    self.pageInforManager = PageInfoManager()
}

init(network: network, jsonDecoder: JsonDecoder, pageInforManager: PageInfoManager){
    self.network = network
    self.jsonDecoder = jsonDecoder
    self.pageInforManager = pageInfoManager
}

```

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +        decodingErrorHandler: @escaping (Error) -> Void
아... 생각해보니 이 네이밍은 좀 더 고민해볼게요

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +    ) -> URLSessionDataTask? {
음 discardableResult를 달았기 때문에 없는것보단 있는게 낫다! 라는 생각으로 리턴 값을 준거 같습니다. 실제로 사용하는 쪽에서 urlSessionDataTask를 사용하지는 않네요 ㅎ

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +            decodingErrorHandler(NetworkError.urlError)
결국 유저에게 보여줘야할 에러타입을 따로 만들어야 되는거군요

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +            data, urlResponse -> Void in
원래 urlResponse -> response가 맞죠?! 수정하겠습니다.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +    func registerProduct(
아... 이것도 나눠줘야 되는군요! 알겠습니다.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +        """)
네네 객체로 만들고 encoding하는 방법으로 시도해보겠습니다.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +            guard let imageData = image.jpegData(compressionQuality: 0.1) else {
사실 Resize하는 메서드(크기에대한)를 만들어서 사용했는데 그랬더니 화질이 어마어마하게 나쁘게 나와서 그 방법은 사용하면 안될꺼 같아 사용하지 않았습니다. compressionQuality의 경우 화질이 훨씬 좋아서 이 방법을 선택했습니다. 생각해보니 이미지 크기 검사 -> 이미지 축소 -> 전송하는 과정을 거쳐야 됬었겠네요.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +    private var network = Network()
아! 맞네요 로직이 변겨오디어서.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/View/String+Extension.swift
> +//  String.swift
앗 알겠습니다.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/View/View+Extension.swift
> +    func addLastBehind(view: UIView) {
제일 마지막 꺼 전에 삽입이 되도록 한건대요. 이미지를 추가할때 버튼이 가장 오른쪽에 있도록 쓰입니다.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/View/View+Extension.swift
> +        }
삼항연산자를 많이 써버릇안해서 그러네요! 다음부터 많이 써볼게요

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    lazy var stockTextField = generateTextField(placeholder: "재고수량", keyboardType: .numberPad)
func 을 만들어서 값을 바꾸는 것을 만들라는 말이죠? 알겠습니다.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        switch MainCollectionView.LayoutType(rawValue: self.segmentedControl.selectedSegmentIndex) {
weak self 로 고쳤습니다!

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
맞습니다! 근대 아직도 weak self를 사용하는 기준을 잘 모르겠어요! 이경우 MainViewController가 사라졌을때 실행이 안되어야 하는가를 기준으로 봐야될까요?

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    }
어디까지 텍스트들은 다 상수로 관리해주도록 변경하였습니다.

2022-05-30 12:48 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +            self.textView.resignFirstResponder()
이부분은... 좀 더 해봐야될꺼같습니다... 일단 scroll view여서 touch 자체가 안먹어요(touchesBegan 이 시작이 아예안됨) 다른분들의 조언으로 가장 바깥쪽에 스크롤뷰를 넣어서 그걸로 감싸고 키보드가 올라갈때 스크롤이 되게끔 할려고했는대 안되요.... ㅠ 눈물

2022-05-30 12:57 UTC, westeastyear commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +    func addImageToStackView(image: UIImage){
키워드 추가 및 수정하였습니다.

2022-05-30 13:00 UTC, westeastyear commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +        }
또치의 조언대로 수정하였습니다!

2022-05-30 14:27 UTC, westeastyear commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +            fatalError("error")
return 하는 형식으로 수정하였습니다.

2022-05-30 14:27 UTC, westeastyear commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +                self.navigationController?.popViewController(animated: true)
추가하였씁니다

2022-05-30 14:31 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ImageCache.swift
> +            self.imageCache.setObject(image, forKey: urlString as NSString)
이부분은 좀 애매한거 같아요... 일단 imageCache가 싱글톤 패턴으로 구현되어 있어 사라질리가 없을꺼 같아요... 잘 모르겠어요

2022-05-30 14:31 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/NetworkError.swift
> +    case decodingError
넵 따로 만들도록 할게요!

2022-05-30 14:40 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +                  let dcodedData = try? jsonDecoder.decode(PageInformation.self, from: data) else {
else 문에서 errorHandler(UseCaseError.decodingError) 를 검출하도록 변경했는대 혹시 jsonDecoder.decode에서 던져주는 error를 그대로 쓰라는 말씀이실까요?

2022-05-30 14:57 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +            return nil
추가하였습니다. 또한 network error, useCaseError 구분없이 알럿창을 띄우기 위해 프로토콜로 묶었습니다.

2022-05-30 14:59 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +                    self.productImage.image = image
여기는 필요할꺼 같습니다.

2022-05-30 14:59 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +                    self.productImage.image = image
여기도 필요할꺼같습니다.

2022-05-30 15:04 UTC, dnwhd0112 commented
안녕하세요! @TTOzzi 
인코딩 하는 부분을 제외하곤 수정 완료하였습니다!

2022-05-31 15:02 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
>              return cell
`default` 를 사용하지 않았을 때 왜 문법 에러가 났을까요? 지금 로직에서 switch-case의 `.none` 은 어떤 값을 의미하나요? 👀

2022-05-31 15:05 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
`MainViewController`가 `productListUseCase`를 프로퍼티로 갖고 있고, `productListUseCase`가 `requestPageInformation` 메서드의 클로저 인자를 통해 `self`를 캡처해서 가져가게 되니 순환 참조가 발생할 가능성이 있는 코드가 될 것 같습니다 🤔 
지금 당장은 클로저가 언젠간 실행될테니 순환 참조의 문제가 없을 것 같긴 하지만, 언제든 발생할 수 있는 코드.. 로 볼 수 있을 것 같아요.

2022-05-31 15:06 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    lazy var stockTextField = generateTextField(placeholder: "재고수량", keyboardType: .numberPad)
방법은 꼭 함수가 아니더라도 여러 가지가 있을 것 같아요~!

2022-05-31 15:07 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    }
(혹시나 오해하실까봐) 모든 텍스트를 상수로 관리하라는 의미는 아니었습니다.
명확한 기준을 갖고, 일관성 있는 코드를 작성하는 게 중요해요.

2022-05-31 15:08 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    }
`viewWillDisappear`에서 해제하도록 작성하신 이유가 궁금해요 👀 
`addObserver` 메서드의 공식 문서를 한 번 보시면 좋을 것 같아요.

2022-05-31 15:09 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +            self.textView.resignFirstResponder()
🤔

2022-05-31 15:10 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    }
상위 클래스에 로직이 없는데 상속/오버라이딩으로 처리 할 필요가 있을까요? 👀

2022-05-31 15:14 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +        }
어떤 방식으로 변경해보셨을까요? 👀 
코드를 보여드리는 건 정답을 제시하는 것으로 느끼실까봐 피하긴 하는데..
```suggestion
        let imageArray = addImageHorizontalStackView.arrangedSubviews.compactMap { ($0 as? UIImageView)?.image }
```
요렇게 바꿔볼 수 있을 것 같아요.

2022-05-31 15:18 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +    private let pageInforManager = PageInfoManager()
하나의 인스턴스만 사용하도록 하기 위해 생성자를 숨기는 게 정석이긴 하나.. 꼭 숨겨야할 필요는 없을 것 같아요.(개인적인 생각입니다)
말씀하신대로 오버로딩을 할 수도 있고, 생성자 인자에 기본값을 줄 수도 있을 것 같네요.
지금은 문제 없을 것 같지만, 네트워크 통신에서 설정값들을 공유해야하는 케이스가 많아 달아본 코멘트였습니다 🙇

2022-05-31 15:21 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +            decodingErrorHandler(NetworkError.urlError)
꼭 따로 만들어줘야만 하는 건 아니에요~! 🙏 
서버와 통신하는 계층에서 발생하는 에러와, 비즈니스 로직을 처리하는 계층에서 발생하는 에러를 나누면 좀 더 가독성 있는 코드가 될 것 같아서 남긴 코멘트입니다 🙇 
이곳까지 `NetworkError`를 사용하면 나중에 `NetworkError`가 수정될 때 함께 챙겨줘야할 코드의 범위가 커질 것 같아서요.

2022-05-31 15:21 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +            data, urlResponse -> Void in
앗 그런 것 보단 줄바꿈되어 있어서 말씀드렸어요. 반환값 `Void`는 생략 가능하기도 하구요 🤔

2022-05-31 15:25 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +                  let dcodedData = try? jsonDecoder.decode(PageInformation.self, from: data) else {
`decode` 메서드에서 던지는 에러를 그대로 사용하라는 코멘트는 아니었습니다.
디버깅하기 쉽도록 `decode`에서 발생하는 에러를 `try?`로 무시하기 보단, try-catch 를 활용해 에러까진 캐치할 수 있도록 구현하고 따로 정의하신 `decodingError`를 넘기도록 구현하면 좋을 것 같아요.
필요하다면 `enum`의 연관값으로 `decode`에서 발생하는 에러의 `localizedDescription`을 넘길 수 있기도 하구요.
지금은 디코딩에서 실패하더라도 어떤 키값이 잘못되어 실패했는지 알기 위해선 데이터를 하나하나 확인해보거나 코드의 수정이 필요할 것 같습니다 😢

2022-05-31 15:26 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +    func registerProduct(
하나의 객체가 두 가지 역할을 하고 있진 않은지 항상 확인해주세요 🙏 
각각의 메서드가 각기 다른 화면에서 사용하는 메서드이다 보니, `ProductListUseCase`를 사용하는 곳에선 해당 화면에서 필요로 하지 않는 정보도 알고 있을 것 같습니다 🤔

2022-05-31 15:27 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +        """)
넵 문자열로 처리하면 코드 작성 중 실수(오타)가 발생할 확률도 높고, 코드를 작성하지 않은 사람이 보기엔 이해가 어려울 수 있을 것 같아요.

2022-05-31 15:30 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/View+Extension.swift
> +        }
삼항 연산자는 사람마다 취향이 많이 갈리는 부분이라 굳이 많이 써보려고 하시진 않아도 됩니다 😅
이런 방법도 있다 정도만 알아주심 좋을 것 같아요~

2022-05-31 15:31 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +    }
넵 각자 정한 컨벤션마다 다르긴 하지만, 대체적으로 확장하는 타입별로 파일을 따로 나눠 관리하는 것 같아요.

2022-05-31 15:32 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +    ) -> URLSessionDataTask? {
> func들을 프로토콜로 추상화해서 사용하는편이 좀 더 낫지않았을까 싶네요.

라고 생각하신 이유가 궁금해요 👀 
여기서 추상화를 해주는 목적이 무엇인가요?

2022-05-31 15:33 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/Secret.swift
> +}
넵 요것도 정하기 나름일 것 같기도 한데, private 저장소라면 그냥 커밋하기도 하고 아니라면 따로 관리 또는 github 에서 제공해주는 secret 기능을 활용하기도 하는 것 같아요.

2022-05-31 16:09 UTC, TTOzzi approved these changes
안녕하세요~ 도니, 우롱차! 
수정하신 부분 확인했고 추가 코멘트도 남겨뒀어요.
수정이 필요한 부분이 남아있다면, 다음 스텝 진행하시면서 차근차근 수정해봅시다!
늘 그렇듯이 이해가 어려운 부분이 있다면 말씀해주세요!
고생하셨습니다 🙇 🙇 🙇

2022-05-31 16:09 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    var keyBoardSize: CGFloat = 0
`keyBoardSize` 는 외부, 하위 클래스에서 접근하는 값인가요?

2022-05-31 16:09 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +        }
여기도 입력받은 값이 유효한지 확인하는 로직인 것 같은데, 분리해주면 더 좋을 것 같아요 🤔

2022-05-31 16:09 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    }
`setSecret` 이란 네이밍만 봤을 땐 값을 세팅해주는 로직을 가질 것 같은데, 단순히 값을 반환해주기만 하네요 🤔 
swift api design guideline을 참고해서 좀 더 명확하게 의미를 표현할 수 있도록 변경해주면 좋을 것 같습니다.

2022-05-31 16:09 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    func setConstraint() {
여기도 외부에서 접근이 필요한 메서드인가요? 👀

2022-05-31 16:09 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    }
아래쪽으로 스와이프했을 때 키보드를 닫아주는 UX가 아이폰 사용자들에게 일반적인 UX 일까요? 👀

2022-05-31 16:09 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +        self.view.frame.origin.y = 0 - keyBoardSize
`UITextView` 에 입력을 시작했을 때, 키보드에 현재 입력하고 있는 `UITextView`가 가려지는지 여부와 관계없이 항상 뷰를 이동시켜 주는 건가요? 👀

2022-05-31 16:09 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +}
`Delegate` 패턴은 이렇게 구현되어야 한다! 는 규칙은 없지만.. 애플에서 제공해주는 Delegate 프로토콜, 메서드(UIScrollViewDelegate, UITableViewDelegate 등..)들을 참고하셔서 모두가 한 눈에 이해하기 쉬운 익숙한 네이밍, 구현으로 변경해보면 좋을 것 같네요 🤔

2022-05-31 16:09 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ErrorAlertProtocol.swift
> +    static var alertTitle: String { get }
`alertTitle`은 `static`으로 선언되어야 하는 이유가 궁금해요 👀

2022-05-31 16:09 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +                                          preferredStyle: .alert)
구현하신 `ErrorAlertProtocol`을 보다 의미있게 사용하려면 형변환 후 값을 하나씩 꺼내서 `UIAlertController`의 생성자로 전달하기 보단, `ErrorAlertProtocol`를 인자로 받는 생성자나 메서드를 만들어줬으면 더 좋을 것 같네요.

2022-05-31 16:09 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductRegisterUseCase.swift
> +        data.appendString("Content-Disposition: form-data; name=\"params\"\r\n\r\n")
각 요청에 맞는 `URLRequest`를 만들어주는 로직 또한 다른 객체로 분리해주면 좋을 것 같아요.
지금 만들어져 있는 객체를 사용한다면 `OpenMarketApi`가 될 수 있겠네요 🤔 
이런 부분은 잘 만들어진 Moya 같은 라이브러리 코드를 참고해보시면 좋을 것 같아요.

2022-05-31 16:09 UTC, TTOzzi commented on OpenMarket/OpenMarket/Model/Network/ProductRegisterUseCase.swift
> +        request.httpBody = data
여기까지 로직도 위 코멘트와 마찬가지로 분리해줄 수 있을 것 같아요.
지금은 `UseCase`가 맡은 역할이 많은 것 같네요.

2022-05-31 16:09 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +        )
현재 셀(뷰)이 가지고 있는 로직도 셀과 로직을 수행하는 객체 사이에 하나의 계층을 더 만들어 로직을 분리해줄 수 있을 것 같아요~ 
요런 건 앞으로 프로젝트 진행하시면서 천천히 생각해보아요 🙂

2022-05-31 16:09 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/View+Extension.swift
> +                self.insertArrangedSubview(view, at: index)
들여쓰기가 살짝? 이상하네요 +_+

2022-05-31 16:09 UTC, TTOzzi commented on OpenMarket/OpenMarketJSONTests/OpenMarketPOSTTest.swift
> +    var session: URLSessionProtocol!
이 테스트에서 `session`은 어떻게 사용되는 건가요? 👀

2022-05-31 16:09 UTC, TTOzzi commented on OpenMarket/OpenMarketJSONTests/OpenMarketPOSTTest.swift
> +            promise.fulfill()
단순히 에러가 발생하지 않고 응답이 온 것 만으로 `ProductRegisterUseCase`의 `registerProduct` 메서드 로직이 정상 동작함을 보장할 수 있을까요?
실패하더라도 구체타입 `Network`를 주입해주고 있어서 `ProductRegisterUseCase`의 로직때문에 실패한 것인지 `Network`의 로직때문에 실패한 것인지 알기 어려울 것 같습니다.
모의 객체를 활용해 의존성을 가지는 네트워크 통신 객체의 `requestData` 메서드를 호출했고 파라미터로 전달한 데이터와 이미지를 잘 전달했는지 확인이 필요할 것 같네요 🤔

2022-05-31 16:12 UTC, merged

2022-06-01 04:17 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
>              return cell
제가 생각하기론 `default` -> 위쪽 케이스에서 걸리지 않았을때 반환되는 값
`.none`-> `nil` 이 들어올경우 걸리는 값.

`defualt`를 사용하지 않았을때 문법 에러가 나는 이유는 모든 경우를 커버하지 못했기 때문입니다. 그래서 `default`를 쓴 경우 enum 타입이 추가되어도 오류가 나지 않는 반면 `.none`을 쓴 경우는 오류가 발생합니다.

2022-06-01 04:18 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
아항... 알겠습니다. 그럼 순환 참조가 발생할 수 있는가? 를 기준으로 보고 weak를 써야되는게 맞는걸까요?

2022-06-01 04:19 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    lazy var stockTextField = generateTextField(placeholder: "재고수량", keyboardType: .numberPad)
음... 잘 모르겠어요... 
요한 값만 외부로 전달할 수 있는 통로를 만들거나 -> func 을 통하여 외부에서 접근이 가능하도록 함
private(set)이라도 붙여주면 더 좋을 것 같습니다. -> 외부에서 읽기는 가능하도록 변경
다른 방법이 있을까요?

2022-06-01 04:25 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    }
관리가 필요한, 나중에 변경을 해야할 일이 있는경우. 중복이 많이 일어나는 경우, Const로 쓰는거 같습니다. 그리고 제가 다녔던 어떤 회사에서는 외국어 변역기능을 위해서 모든 보이는 문자열을 const로 관리하더라구요!

2022-06-01 04:29 UTC, westeastyear commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    }
문서를 확인해 보니 특정 버전 이상부터는 해제를 할 필요가 없군요!! 감사합니다

2022-06-01 04:36 UTC, westeastyear commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +            self.textView.resignFirstResponder()
키보드를 내리는 기능은 textView에 swipe기능을 추가하여 구현하였습니다
원래는 scrollView로 스코롤이 되게 하려고 하였는데, scrollView의 ContentSize가 0,0으로 잡히는 현상이 있었습니다...

2022-06-01 05:13 UTC, westeastyear commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    }
등록화면, 수정화면은 RegisterEditBaseViewController을 상속받아 같은 rightNavigationButton을 사용하게 됩니다. 
그런데 각 화면의 액션은 각각 달라야 합니다. 등록화면은 POST을 해야하고 수정화면은 PETCH를 해야 합니다.
RegisterEditBaseViewController에서 비어있는 액션함수를 구현을 해놓고 상속받은 곳에서 오버라이딩하여 각각의 액션을 처리하기 위하여 이렇게 작성하였습니다.

2022-06-01 05:34 UTC, westeastyear commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +            data, urlResponse -> Void in
수정하였습니다

2022-06-01 05:36 UTC, westeastyear commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +                  let dcodedData = try? jsonDecoder.decode(PageInformation.self, from: data) else {
```swift
network.requestData(url: url) { data, response in
            guard let data = data,
                  let decodedData = try? jsonDecoder.decode(PageInformation.self, from: data) else {
                errorHandler(UseCaseError.decodingError)
                return
            }
            completeHandler(decodedData)
        } errorHandler: { error in
            errorHandler(error)
        }
```
위와같이 수정하였습니다!

2022-06-01 05:37 UTC, westeastyear commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +    func registerProduct(
필요하지 않은 변수들을 삭제하여 수정하였습니당

2022-06-01 05:54 UTC, westeastyear commented on OpenMarket/OpenMarket/Model/Network/ProductListUseCase.swift
> +    ) -> URLSessionDataTask? {
생각해보니 과도한 추상화가 아닐까라는 생각이 있지만, 만약 쓴다면?! 의존성을 떨어트릴수 있다고 생각합니다.

2022-06-01 06:21 UTC, westeastyear commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    var keyBoardSize: CGFloat = 0
깜빡했네요...ㅎ private을 붙여주었습니다.

2022-06-01 06:26 UTC, westeastyear commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +        }
옵셔널을 해제하려고 위와같이 사용하였는데, 객체에 옵셔널을 넣고 나중에 유효한지 확인하는 메서드를 작성하는 것이 나을까요..?🤔

2022-06-01 06:29 UTC, westeastyear commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    }
requestUserSecret() 으로 변경하였습니다

2022-06-01 06:30 UTC, westeastyear commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    func setConstraint() {
앗... private 붙여주었습니다

2022-06-01 08:04 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    }
가장 바깥쪽에 ScrollView를 제거하고 tap이랑 아래쪽으로 스와이프 했을때 키보드를 닫아주도록 수정하였습니다.

2022-06-01 08:05 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +        self.view.frame.origin.y = 0 - keyBoardSize
가장 밑에쪽에 있는 TextView만 이동하도록 변경하였습니다! 항상이요!

2022-06-01 08:21 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +}
예제를 보니 `scrollViewWillBeginDragging(_ scrollView: UIScrollView) `이런식으로 구현되어 있는데 저희는 매개변수를 어떻게 해야될지 잘 모르겠어요...
코드 수정은 아래와 같이 했습니다.
```swift
protocol ViewControllerDelegate: AnyObject {
    func viewControllerSholdRefresh()
}
```

2022-06-01 08:25 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ErrorAlertProtocol.swift
> +    static var alertTitle: String { get }
enum 케이스에 Error 를 채택하도록 했는대 Enum의 경우 var 값을 가지지 못하다 보니 static으로 줬었는대 생각해보니 static으로 할 필요가 없었네요. 
다음과 같이 바꿧습니다.
```
var alertTitle: String {
        return "입력 에러!"
    }
```

2022-06-01 08:34 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +                                          preferredStyle: .alert)
다음과 같이 메서드로 만들어 줬습니다! UIAlertController 를 만드는건 뷰컨트롤러의 역할이라고 생각하여 뷰컨트롤러에서 함수를 만들었습니다.

```swift 
private func makeAlertAction(error: ErrorAlertProtocol) -> UIAlertController {
        let alert = UIAlertController(title: error.alertTitle,
                                      message: error.alertMessage,
                                      preferredStyle: .alert)
        return alert
    }
```

2022-06-01 12:35 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +        )
요건... 진짜 진짜 모르겠어요 ㅠㅠㅠㅠㅜㅜㅜㅜㅜ

2022-06-01 12:36 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/View/View+Extension.swift
> +                self.insertArrangedSubview(view, at: index)
앗! 고쳤습니다.

2022-06-01 12:37 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ProductRegisterUseCase.swift
> +        request.httpBody = data
일단 이미지를 인코딩 하는 부분을 객체를 만들어서 분리해줬습니다! 나머지 data도 객체를 만들어서 분리할까 했지만... 고민중입니다.

2022-06-01 12:37 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/ProductRegisterUseCase.swift
> +        data.appendString("Content-Disposition: form-data; name=\"params\"\r\n\r\n")
`OpenMarketApi` 에서 URLRequest를 만들어주도록 구현하였습니다.

2022-06-01 12:39 UTC, dnwhd0112 commented on OpenMarket/OpenMarketJSONTests/OpenMarketPOSTTest.swift
> +            promise.fulfill()
알겠습니다... 모의 객체를 활용한 테스트도 만들어 주도록 할게요. 응답은 response를 확인하는 쪽으로 하겠습니다...

2022-06-01 12:39 UTC, dnwhd0112 commented on OpenMarket/OpenMarketJSONTests/OpenMarketPOSTTest.swift
> +    var session: URLSessionProtocol!
사용되지 않습니다 ㅎ... 지우도록 할게요

2022-06-02 15:04 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    }
넵 제 코멘트는 의심하셔야 하지만 공식 문서는 믿으셔도 됩니다 ㅋㅋ
예외 케이스가 있긴 한데, 지금 사용하신 selector 를 활용한 옵저버와 달리 [클로저를 활용한 옵저버](https://developer.apple.com/documentation/foundation/notificationcenter/1411723-addobserver)는 여전히 해제해줘야 해요.

2022-06-02 15:09 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +        }
단순 옵셔널 해제라면 필요없을 것 같은데, 여긴 사용자가 꼭 필요한 값을 모두 입력하였는가 를 체크하는 로직 같아서요 🤔 
뷰에선 있는 그대로를 넘겨주고, 로직은 다른 객체에서 처리해주면 좋겠다는 생각이었어요.

2022-06-02 15:12 UTC, TTOzzi commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +}
애플에서 제공하는 메서드를 보시면 항상 첫 번째 인자로 동작을 위임하는 주체를 넘기고 있는 것을 보실 수 있는데요.
동작을 위임받는 객체 : 동작을 위임하는 객체가 1 : n 이 될 수 있어, 누구의 메서드가 불린 것인지 확인하기 위해 주로 첫 번째 인자를 사용하게 됩니다. 가장 흔히 볼 수 있는 예시는 회원가입 화면 등에서 화면 하나에 여러 개의 UITextField가 있는 상황이 있겠네요.
수정하신 것에서 **어떤 뷰컨**의 동작을 위임하는 것인지를 프로토콜의 이름으로 명확하게 표현해주고 첫 번째 인자로 동작을 위임하는 주체를 넘기도록 구현하시면 더 좋을 것 같아요!
그 외 인자는 넘겨야 할 값이 없다면 굳이 넘기지 않으셔도 됩니다~!

2022-06-02 15:15 UTC, TTOzzi commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +        )
나중에 MVVM 을 요구하는 프로젝트가 나올거예요! 그 때 뷰에서 로직을 분리하는 것에 대해 공부하시면 될 것 같습니다!

2022-06-02 15:17 UTC, TTOzzi commented on OpenMarket/OpenMarketJSONTests/OpenMarketPOSTTest.swift
> +            promise.fulfill()
ㅠㅠ 매번 강조하는 부분이지만, 모든 코멘트를 반영하려 하실 필요는 없어요.
아~ 그렇구나 하고 넘어가셔도 됩니다. 이 부분도 넘어가주세요 🙏 지금 테스트 코드까지 챙겨주기엔 너무 무리일 것 같아요 😢

2022-06-03 02:23 UTC, dnwhd0112 commented on OpenMarket/OpenMarketJSONTests/OpenMarketPOSTTest.swift
> +            promise.fulfill()
이미 처리해버렸습니다... ㅠ

2022-06-03 02:37 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +}
아~ 이해했습니다. 수정해보도록 할게요!

2022-06-03 02:38 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +        }
아~ 알겠습니다! 그럼 입력을 모두 옵셔널로 처리하도록 하고 체크로직 쪽에서 검사하는 쪽으로 변경하도록 하겠습니다.

2022-06-03 02:39 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Model/Network/Secret.swift
> +}
깃허브 secret기능이 있군요? 찾아보도록하겠습니다.

2022-06-03 02:40 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterEditBaseViewController.swift
> +    }
넵 참고하도록할게요.

2022-06-03 02:40 UTC, dnwhd0112 commented on OpenMarket/OpenMarket/Controller/RegisterViewController.swift
> +        }
수정완료하였습니다.