오픈마켓 II [STEP 1] 두기, Minseong
yagom-academy/ios-open-market pull request #163
Opened 2022-05-29 02:52 UTC by Minseong-yagom

@jungseungyeo 
안녕하세요! 린생! STEP1 완료해서 PR보냅니다!
POST하는 부분만 구현을 해놓기는 했는데 주말에 pr보내주는게 좋을 것 같다고 말씀해주셔서 정리가 많이 되지 않았지만 일단 pr보냅니다!

잘부탁드립니다!😁😄

## 고민한 점

#### 1. 시뮬레이터만을 위한 에러처리를  해줘야 할지?
사진 선택시 카메라 or 앨범 선택지를 두었는데 시뮬레이터의 경우 카메라 작동이 되지 않기 때문에 어플이 죽는 경우가 생겼습니다.
그래서 시뮬레이터만을 위한 처리를 따로 해줘야 할지(예를 들면 카메라가 작동가능한 상태인지를 확인하는 코드가 있더라구요) 아니면 실제 폰에서는 정상 작동되니까 그대로 두어야할지 궁금합니다

#### 2. 앨범에서 사진 edit모드에서 범위내에 꽉차게 설정하는 방법
![](https://i.imgur.com/006LKU9.png)
위와 같이 세로로 긴 사진의 경우에는 별도의 확대 없이 정사각형 범위내로 잘 선택이 되는데 오른쪽 사진과 같이 가로로 긴 경우 위 아래 공백이 생기게 됩니다.
이에 이 선택 범위를 꽉 차게 설정할 수 있는 방법이 있을 것 같은데 찾지 못해 질문하게 되었습니다!

#### 3. multiprat-data 형식에서 data에 image를 추가 할 때 filename의 역할이 무엇인지 궁금합니다.
![](https://i.imgur.com/C3ckmYG.png)

그냥 data에 appand할 때 이름을 정해주는 것 처럼 보이는데 어디에 사용하고 무엇때문에 필요한 지 궁금합니다
(실제 서버에 업로드 된 사진을 다운받아서 확인해 보니 저희가 설정한 이름이 아니었습니다)

2022-05-29 07:28 UTC, jungseungyeo requested changes
두기, 민성 고생하셨습니다. 

## 고민한 점

### 1. 시뮬레이터만을 위한 에러처리를 해줘야 할지?

`넵 당연히 해주면 좋습니다.  항상 방어 코드를 추가하여 작성하면 좋습니다. `

### 2. 앨범에서 사진 edit모드에서 범위내에 꽉차게 설정하는 방법

`iOS에서 제공하는 기본 화면에서는 불가능할거예요. 따로 커스텀을 하여 작업을 하면 가능 할겁니다. :) 이 부분은 너무 깊게 생각하지 말아주세요 학습 목표가 아니여서 깊게 생각하지 않아도 되지만 내용을 설명하자면
선택 된 이미지를 따로 커스텀 한 edit화면으로 이동하여 적용하면 가능합니다. 대표적으로 카카오톡 채팅방에서 사진을 가져오는 경우에 볼 수 있죠? ㅎㅎ
`

### 3. multiprat-data 형식에서 data에 image를 추가 할 때 filename의 역할이 무엇인지 궁금합니다.

`이것은 multiprat-data에서 클라이언트가 서버에게 어떤 파일을 보내는지 알려주기 위한 형식입니다. 파일명이 무엇이고 확장자는 무엇인지를 알려주는 형태이죠. 이런 형태를 서버 개발자와 클라이언트 간의 약속이라고 이해하면 좋을거같아요.`

두기, 민성 고생하셨어요. 처음 하는 collection와 networker의 처리가 많이 힘드시죠? ㅠㅠ 
열심히 노력한 흔적이 많이 보여요. 그래서 몇가지 리뷰를 하겠습니다.

## 1. 함수의 분리 ( SOLID 원칙 - 단일 책임 원칙 위반 )

```
코드의 형태를 보면 함수의 역할을 나눠서 작업을 할려는 노력이 보였습니다. 그러다보니 함수의 역할이 많이 커지게 되었고 내부에서 체크하는 부분이 많아 진 거 같아요.

하지만 이렇게 작업이 되면 될 수 록 함수 내부의 로직은 복잡해지는 결과를 나오게 됩니다. 이것은 솔리드 원칙에서 단일 책임원칙을 위반하는 형태로 이어지게 됩니다.

예를 들어 작업하신 코드를 보면 함수 내에서 많은 분기문과 조건문이 존재하여 많은 검사를 한 함수에서 진행이 되고 연쇄적으로 진행이 되고 있어요. 이러한 형태는 함수의 분리를 더욱 힘들게 되는 요인이 됩니다. 

이 부분을 어느 정도 수정하면 좋을거 같아요.


```

## 2.  Controller layer와 networker layer 역할 분리

```
현재 multipart/form-data의 form을 controller가 작업이 되고 있어요. 이 부분은 controller layer에서 작업이 된다면 networker와 강력하게 위존하게 됩니다.

강력하게 의존이 되는 원인은 networker layer에서 수행이 되어야 하는 로직이 controller가 대신 해주고 있기 때문입니다. 

각 layer에서 수행해야 하는 역할을 분리가 되고 역할의 맞는 기능을 구현하면 좋을거 같아요.

```

이러한 형태를 만들기 위한 코멘트를 달아 두었습니다. 코멘트를 보시고 수정해주시면 좋을거같아요. :) 
혹시 궁금하거나 질문하고 싶은 부분은 언제든지 질문해주세요 :) 

- 단일 책인 원칙 참고 - https://www.youtube.com/watch?v=sLTdtSJXNoQ
- networker layer의 역할 - https://ios-development.tistory.com/731

2022-05-29 07:28 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController/AddItemViewController.swift
> +            print(currency)
print는 디버깅 용도일까요? print문은 삭제해주세요 :)

2022-05-29 07:28 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController/AddItemViewController.swift
> +    private var currency: String = "KRW"
currency라는 string 타입의 값을 전역변수를 두었네요? 이 값이 여기에 존재하면 좋지 않아요. CurrencyType이라는 열거형안에서 같이 처리하면 좋을거같아요. enum 타입에서 string값을 생성할수있죠? 활용해보면 좋을거같아요.

2022-05-29 07:28 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController/AddItemViewController.swift
> +        itemImageCollectionView.register(UINib(nibName: "\(ItemImageCell.self)", bundle: nil), forCellWithReuseIdentifier: "\(ItemImageCell.self)")
아래의 형태로 되면 좋을거같아요. 특정 코드는 set이라는 함수로 세팅을 하지만 위의 것들은 아니네요? 특별한 기준이 있나요? 제 의견은 하나의 형태로 통일화 하면 좋을거같아요.

2022-05-29 07:28 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController/AddItemViewController.swift
> +    private func postItem() {
이 코드는 controller 단위에서 작업이 되면 안될거같네요. networker에게 역할을 주면 좋을거같아요.

2022-05-29 07:28 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController/AddItemViewController.swift
> +    private func checkComponents(){
체크 로직이 있어서 좋습니다. :) 하지만 객체지향에서 단일책임원칙을 위반하고 있어요. 단일 책인 원칙은 하나의 역할만하는 기능으로 구현하는 것입니다. 

지금 함수의 역할은 많은 것을 체크하고 에외처리를 하고 있어요. 단일 책임원칙을 지키는 코드로 작업이 되면 좋을거같아요.

기능 하나당 하나의 함수로 먼저 구현을 해주세요 :)

2022-05-29 07:28 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController/AddItemViewController.swift
> +    private func makeData() -> Data? {
post를 보내기 위한 포맷을 만드는 함수 같아요. 이 역할은 controller가 아닌 networker 영역에서 진행하면 좋을거같아요.

2022-05-29 07:28 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController/AddItemViewController.swift
> +        let secret = "zsxn8cy106"
위의 함수에서 검사하는 로직이 너무 많아요. 역할을 분산하면 좋을거같아요. 역할을 분산하는 방법은 위의 코멘트와 동일하게 단일책인원칙을 지키면서 작업하면 좋을거같아요.

2022-05-29 07:28 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController/AddItemViewController.swift
> +extension AddItemViewController: UIImagePickerControllerDelegate, UINavigationControllerDelegate {
extension으로 protocol을 채택시 하나의 protocol씩 나눠서 작업해주세요 :) 

역할을 분리하는데 도움이 됩니다.

2022-05-29 07:28 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController/MainViewController.swift
> +            myActivityIndicator.startAnimating()
위의 공통 된 부분은 위에서 한번에 작업하면 좋을거같아요.

2022-05-29 07:28 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController/MainViewController.swift
> +        self.myActivityIndicator.stopAnimating()
CellComponents를 만드는 부분과 configureCell를 하는 부분 그리고 stopAnimating를 하는 부분을 분리해주세요

기능 단위로 함수를 분리하면 좋을거같아요.

2022-05-29 07:28 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController/MainViewController.swift
> +        if cellType == .list {
if 문 보다는 swift문을 사용해주세요. else문이 존재하면 celltype이 추가 되어도 의존관계를 알기 힘들수있어요.

2022-05-29 07:28 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/APIModels.swift
> +struct HealthCheckerAPI: APIable {
enum으로 채택하는 것과 struct로 채택하는 것의 차이가 무엇인가요? struct로 채택 한 이유가 있을까요?

2022-05-29 07:28 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/Protocol/ItemCellable.swift
> +    func configureCell(components: CellComponents)
피드백 반영이 되었네요 ㅎㅎ 너무 좋습니다. where문을 적용하여 타입캐스팅 줄일 수 있었던 것을 기억해주세요 :)

2022-05-29 07:28 UTC, jungseungyeo commented on OpenMarket/OpenMarket/View/CellView/GridCell.swift
> +    private var dataTask: URLSessionDataTask?
싱글톤으로 구현하는 방식은 어려웠나요? ㅎㅎ.. 현재 task는 수정하지는 않아도 될거같아요.
싱글톤으로 구현하는것과 지금의 코드의 차이가 무엇일까요?

cell에서 task를 가지고 있는 것과 가지고 있는 것의 차이는 무엇일지 고민해보고 작성해주세요 :)

2022-05-29 07:28 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/ImageCacheManager.swift
> +    static let shared = NSCache<NSString, UIImage>()
싱글톤의 형태를 가지고 있지만 싱글톤으로 동작이 되는 코드는 아니에요. 디코에서 이야기 했든이 NSCache를 static으로 접근하는 코드입니다. ImageCacheManager라는 객체를 싱글톤으로 사용해게 수정해주세요 :)

2022-05-29 07:28 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/NetworkHandler.swift
> +        }
get형태에서 필요한 부분 같아요. 특별하게 get에서만 작업하기는 어려웠나요? 위의 makeURL함수는 post, delete, put과 같은 RESTAPI를 요청 할 때 마다 url에 파라미터를 모두 포함하게 될 거 같아요.

2022-05-29 07:28 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/NetworkHandler.swift
> +        }
RESTAPI 특성에 맞게 Query에 넣을지 body에 넣을지 구분하는 부분이 잘 이루어지지 않은거 같아요. 이 부분 수정이 가능 할까요? 
현재 코드를 보면 수정이 많이 필요해보여요 ㅠㅠ 

이 부분은 꼭 하지 않아도 되지만 위와 같이 작업이 될 경우 문제점은 코멘트로 남겨주세요.

2022-05-29 07:28 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/NetworkHandler.swift
> +                response(.success(responseResult.data))
이 부분은 모든 method가 동일하게 동작이 되는데 swift문으로 구분 한 이유가 있나요?

2022-05-30 01:40 UTC, doogie97 commented on OpenMarket/OpenMarket/Controller/ViewController/AddItemViewController.swift
> +    private var currency: String = "KRW"
물론 enum타입에서 string을 사용하도록 할 수 있었습니다
다만 오픈마켓1에서 segment의 index를 직접 비교하지 않았으면 좋겠다는 린생 피드백에 따라 이번에도 그런 형식으로 구현을 해봤는데요
저희 생각으로는 enum에서 string값을 사용하게 된다면 결국에는 segment의 index를 비교하는 방식으로밖에는 생각이 안나서 index비교를 하지 않고 작성하는 방법이 어떤게 있을지 여쭤보고 싶습니다!
(일단은 전역으로 둔 currency를 없애고 index를 비교하는 형태로 수정하였습니다)

2022-05-30 01:43 UTC, doogie97 commented on OpenMarket/OpenMarket/Controller/ViewController/AddItemViewController.swift
> +        itemImageCollectionView.register(UINib(nibName: "\(ItemImageCell.self)", bundle: nil), forCellWithReuseIdentifier: "\(ItemImageCell.self)")
아래의 형태가 어떤 부분을 말씀하시는 잘 모르겠습니다!
혹시 mainviewcontroller와 addviewcontroller에서 viewdidload부분의 차이를 말씀하신게 맞으실까요?

2022-05-30 03:26 UTC, doogie97 commented on OpenMarket/OpenMarket/Controller/ViewController/AddItemViewController.swift
> +    private func postItem() {
controller에서는 Post를 위한 API만 만들 수 있도록 하고 post기능이나 data를 만드는 기능 모두 networkHandler로 이동해 주었습니다

2022-05-30 03:26 UTC, doogie97 commented on OpenMarket/OpenMarket/Controller/ViewController/AddItemViewController.swift
> +    private func makeData() -> Data? {
controller에서는 Post를 위한 API만 만들 수 있도록 하고 post기능이나 data를 만드는 기능 모두 networkHandler로 이동해 주었습니다

2022-05-30 03:28 UTC, doogie97 commented on OpenMarket/OpenMarket/Model/NetworkHandler.swift
> +                response(.success(responseResult.data))
이전에 get만 구현할 때 post, patch등이 어떻게 구현될 지 가늠이 안되서 일단 case로 구별해 두었었습니다.
현재 구분이 필요없을 것 같아 제거해 주었습니다

2022-05-30 03:39 UTC, doogie97 commented on OpenMarket/OpenMarket/Model/APIModels.swift
> +struct HealthCheckerAPI: APIable {
enum은 저장프로퍼티를 갖지 못하니까 enum으로 만들 생각을 못했고 그런 방법이 있는지 몰랐습니다..
혹시 enum으로 채택을 하려면 애초에 프로토콜이 저장프로퍼티를 갖고있으면 안되고 메서드를 통해서 구현을 해야하는 걸까요??
어떤 방향으로 진행을 해야할 지 감이 잘 잡히지 않습니다...😥

2022-05-30 03:43 UTC, doogie97 commented on OpenMarket/OpenMarket/Controller/ViewController/AddItemViewController.swift
> +extension AddItemViewController: UIImagePickerControllerDelegate, UINavigationControllerDelegate {
바로 분리해주었습니다!

2022-05-30 03:48 UTC, doogie97 commented on OpenMarket/OpenMarket/Controller/ViewController/MainViewController.swift
> +            myActivityIndicator.startAnimating()
중복되는 부분을 제거해주었습니다!

2022-05-30 03:53 UTC, doogie97 commented on OpenMarket/OpenMarket/Controller/ViewController/MainViewController.swift
> +        self.myActivityIndicator.stopAnimating()
```swift
        if cellType == .list {
            guard let listCell = collectionView.dequeueReusableCell(withReuseIdentifier:  "\(ListCell.self)", for: indexPath) as? ListCell else { return ListCell() }
            listCell.configureCell(components: setCellComponents(itemCell: listCell, indexPath: indexPath))
            myActivityIndicator.stopAnimating()
            return listCell
        } else {
            guard let gridCell = collectionView.dequeueReusableCell(withReuseIdentifier: "\(GridCell.self)", for: indexPath) as? GridCell else { return GridCell() }
            gridCell.configureCell(components: setCellComponents(itemCell: gridCell, indexPath: indexPath))
            myActivityIndicator.stopAnimating()
            return gridCell
        }
```

이런 식으로 분리해주었는데 이런 방식을 말씀하신게 맞으실까요?

2022-05-30 03:56 UTC, doogie97 commented on OpenMarket/OpenMarket/Controller/ViewController/MainViewController.swift
> +        if cellType == .list {
switch로 변경 함으로써 추가되는 celltype에 대응할 수 있게 되었습니다!

2022-05-30 09:06 UTC, doogie97 commented on OpenMarket/OpenMarket/Model/ImageCacheManager.swift
> +    static let shared = NSCache<NSString, UIImage>()
싱글톤으로 만들어서 메서드를 통해 캐시에 저장하거나 이미지를 가져올 수 있도록 구현하였습니다

2022-05-30 09:38 UTC, doogie97 commented on OpenMarket/OpenMarket/Controller/ViewController/AddItemViewController.swift
> +        let secret = "zsxn8cy106"
검사하는 로직이 많아서 역할을 분산하면 좋을것 같다라는 말씀이
checkName() ->string {}
checkStock() -> Int {}
checkDescriptions -> String{} .....
이렇게 메서드를 분리하라는 말씀이실까요?

2022-05-30 10:22 UTC, doogie97 commented on OpenMarket/OpenMarket/Controller/ViewController/AddItemViewController.swift
> +    private func checkComponents(){
화면 요소 체크 기능(지금은 체크 후 에러를 던져주는 메서드로 변경됨)과 에러를 체크해서 에러가 없으면 post를, 에러가 있다면 에러에 따른 얼럿을 표현할 수 있도록 분리하였습니다

2022-05-30 10:28 UTC, doogie97 commented on OpenMarket/OpenMarket/View/CellView/GridCell.swift
> +    private var dataTask: URLSessionDataTask?
디스코드에서 말씀 드렸던 것 처럼 싱글톤으로 구현하려다 보니 resume과 cancel이 정상적으로 작동되지 않는데 또 원인을 찾기가 힘들었는데 그 부분이 많이 어려웠습니다..ㅠㅠ

일단 저희가 생각해본 바로는 각 cell이 task를 갖고있게 된다면 각각의  cell들이 접근하는 task가 전부 다 다를 것이라고 생각합니다
(다만 이 부분에 있어서 뭐가 좋고 어떤 문제가 발생될지에 대해서는 잘 생각이 나지 않습니다...)

2022-05-30 10:38 UTC, doogie97 commented on OpenMarket/OpenMarket/Model/NetworkHandler.swift
> +        }
일단은 위에서 역할에 맞게 networkHandler로 메서드들을 옮겨주면서 처리를 해주긴 했는데...
get일때만 query에 넣을 수 있고 post일때만 body에 포함할 수 있게 하였습니다(일단은 patch나 delete는 구현하지 않았기에)

2022-05-31 09:41 UTC, jungseungyeo reviewed
두기 민성 고생하셨습니다. 다음 스텝을 진행해도 될거같은데요. 코드 충돌이 발생하고 있어요 이부분 해결 부탁드립니다.

2022-05-31 09:41 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController/AddItemViewController.swift
> +        itemImageCollectionView.register(UINib(nibName: "\(ItemImageCell.self)", bundle: nil), forCellWithReuseIdentifier: "\(ItemImageCell.self)")
함수로 묶어서 해달라는 말이였습니다 :) 제가 구체적으로 적었어야 했는데 잘못했네요 ㅠ 아래 set이라는 함수로 초기화를 해주고 있어 위의 부분도 동일하게 묶어서 처리하여 통일해달라는 의견이였습니다 :)

2022-05-31 09:41 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/APIModels.swift
> +struct HealthCheckerAPI: APIable {
딱 정답이 있는거는 아니예요 ㅎㅎ 두 차이점을 알고 하는 느낌이 아니라서 질문을 드렸습니다. 

enum은 인스턴스를 생성하지 않지만 struct는 생성하지요 그래서 메모리 구조가 달르게 구성이 되는 부분이 있습니다.

2022-05-31 09:41 UTC, jungseungyeo commented on OpenMarket/OpenMarket/View/CellView/GridCell.swift
> +    private var dataTask: URLSessionDataTask?
동작의 문제는 없지만 관리 포인트와 MVC패턴의 문제가 생기게 됩니다. cell은 View의 해당하고 task는 네트워크 영역이라 cell에서 task를 가지고 관리를 한다면 MVC패턴이 위반하게 되죠 그래서 관리 할 수 있는 싱글톤 객체로 관리를 하는 것을 위임해서 적용를 하는 것을 권장하였습니다. 

관리가 안되는 것은 싱글톤이다보니 cell이 재사용 할 때마다 cancel이 다른 셀의 task를 cancel하여 발생하는 문제일거예요.

현재는 위와 같이 해결이 되었지만 다음번에는 관리하는 객체를 만들어서 사용하면 좋을거같아요 :)

2022-05-31 09:41 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController/AddItemViewController.swift
> +    private var currency: String = "KRW"
``` swift 
    private enum CurrencyType: Int {
        case KRW = 0
        case USD
       
        var toString: String {
              switch self {
              case KRW: return "KRW"
              case USD: return "USB"
             }
        }
    }
```

위와 같이 한다면 변수하나를 없애술 있죠? 또 didSet에서 조건문도 사라질수도 있고 그런 의미였습니다 :)

2022-05-31 09:41 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ViewController/AddItemViewController.swift
> +        let secret = "zsxn8cy106"
아니여 그런 의미가 아니였습니다. 함수에서 하는 역할이 많기 때문에 이것을 분리하는 연습이 필요하다는 말이였습니다. 위 코드를 보면 무슨 일을 하는지 어디서 무엇을 검사하는지 파악하기가 힘들죠? 

위와 같은 코드는 가독성 측면에서 매우 복잡한 코드가 생성 될 위험이 있어요.

2022-05-31 13:04 UTC, jungseungyeo approved these changes

2022-05-31 13:04 UTC, merged