오픈마켓 II [STEP 1] marisol, Eddy
yagom-academy/ios-open-market pull request #164
Opened 2022-05-29 09:04 UTC by kimkyunghun3

안녕하세요 @jungseungyeo 첫 번째 PR 보냅니다!
시간이 많이 늦어져서 죄송합니다!!!
기능만 구현하고 하려고 했으나 많은 부분에서 막혀서 이를 수정하고 바꾸다 보니 늦어졌습니다!
리뷰 잘부탁드립니다 린생 :)

## 구현되지 않은 부분
1. 키보드 사용 시 텍스트 뷰가 가려지지 않도록 하는 기능
2. 목록 화면 셀 페이징, Refresh 구현
3. PATCH를 통해 뷰에 업데이트(구현은 대부분 완성)
4. 상품등록 화면 사진을 버튼 -> 이미지로 변경할 예정
5. 상품 등록, 수정 시 필수 입력과 선택입력 가이드라인 로직

## 🧐 고민한점 & 해결방법
### 📌 1. 공통 코드에 프로토콜 기본 구현 활용
상품 등록 화면 (productDetailView)와 상품 수정 화면 (productEditView)에서 동일한 view를 그려주기 때문에, 프로토콜로 메서드를 명세하고, 기본 구현을 통해 공통된 부분을 한번만 구현해줄 수 있도록 했습니다.

Drawable이라는 프로토콜에 구현을 했는데, 프로토콜에는 stored property가 사용이 불가해서, 전부 computed property로 구현해주었습니다.
그리고 private 설정도 불가했습니다ㅠㅠ

중복된 코드 작성을 막을 수는 있었지만, 이로 인해 은닉화가 불가능해졌는데 혹시 다른 방법이 있을지 궁금합니다!

### 📌 2. endpoint 활용하기

아시다시피 처음에는 hostAPI, path, params, httpmethod를 가지고 있는 APIable 프로토콜을 생성해서 네트워크 통신을 했었는데요,
get, post마다 계속 APIable을 채택하는 구조체를 만들어줘야 해서 비효율적이라고 생각했습니다.
그래서 동료 캠퍼의 조언을 받아 endpoint 구조체를 만들었습니다.

그래서 case별로 선택하면 알아서 연관값을 활용하여 url을 만들어주도록 구현했습니다.

```swift
enum Endpoint {
  case healthChecker
  case productList(pageNumber: Int, itemsPerPage: Int)
  case productRegistration
  case productEdit(productId: Int)
}

extension Endpoint {
  var url: URL? {
    switch self {
    case .healthChecker:
      return .makeUrl(with: "healthChecker")
    case .productList(let page, let itemsPerPage):
      return .makeUrl(with: "api/products?page_no=\(page)&items_perpage=\(itemsPerPage)")
    case .productRegistration:
      return .makeUrl(with: "api/products")
    case .productEdit(let productId):
      return .makeUrl(with: "api/products/\(productId)")
    }
  }
}

private extension URL {
  static let baseURL = "https://market-training.yagom-academy.kr/"
  
  static func makeUrl(with endpoint: String) -> URL? {
    return URL(string: baseURL + endpoint)
  }
}
```

### 📌 3. 다른 뷰에 프로퍼티 전달하는 방법

MainViewController -> ProductDetailViewController로 넘어갈때 “선택된 상품의 product id”를 전달해주고, 
ProductDetailViewController -> ProductEditViewController로 넘어갈 때 “선택된 상품의 상세 정보 (ProductDetail 타입)”을 전달해줘야 한다고 생각했습니다.

그런데 그러려면 ProductDetailViewController의 id과 ProductEditViewController의 productDetail이 은닉화가 될 수 없는 문제가 있습니다.
프로퍼티는 은닉화를 하고, 메서드로 이 프로퍼티를 전달해주도록 변경해야할까요?🥲
조언 주시면 감사하겠습니다!🙇‍♀️

### 📌 4. UIImagePicker에서 선택한 이미지를 순서대로 보여주기

image가 선택되었을때, `didFinishPickingMediaWithInfo` 메서드 내에서 
선택된 이미지를 `imageArray에` append해주었습니다.

그리고 `cellForItemAt` 메서드에서 `imageArray[indexPath.row]`번째 이미지를 `button.setImage` 해주는 방식으로 이미지를 순서대로 보여주도록 구현했습니다.

## ❓ 궁금한점
### 📌 1.  compactMap에서만 가능한 이유
아래의 코드를 돌렸을 때 forEach에서는 append가 정상적으로 되지 않아서 값이 하나도 들어가지 않고 있습니다.
```swift
presenter.images = productDetail.images?.compactMap { image in
            image.url
        }
        print(presenter.images)
        
//        productDetail.images?.forEach { image in
//            guard let imageURL = image.url else { return }
//            presenter.images?.append(imageURL)
//
//        }
```

하지만 compactMap를 사용해서 하니 제대로 되는 것을 확인할 수 있었습니다.
compactMap으로 하면 nil이 아닌 값들만 배열에 추가해서 반환하는 특성이 있다고 생각합니다. 그래서 이곳에서 옵셔널이기 때문에 이게 제대로 된것인걸까요?
forEach는 단순 반복이라 옵셔널과 연관이 있어서 안되는 것일까요?

### 📌 2. 여러 개의 ImageView 보여지도록 하는 방법
현재 이미지뷰가 여러 개를 등록해도 하나로만 통일되어서 나오는 현상이 있습니다!

저희가 이걸 해결하기 위해서 배열을 만들어서 그곳에 이미지뷰를 넣은 다음 하나씩 부르면 될 것이라고 생각도 해봤는데 그게 잘 안되더라구요! 그래서 아래처럼 addSubview에 하나씩 넣으면 되지 않을까 싶었는데도 각 다른 이미지가 나오게 하는 것을 실패했습니다 ㅜㅜ

저희가 생각을 잘 못하고 있는것일까요?

```swift
func setImage(_ presenter: Presenter) {
        guard let productImages = presenter.images else {
            return
        }
        
        for image in productImages {
            guard let url = URL(string: image) else {
                return
            }
            
            guard let data = try? Data(contentsOf: url) else {
                return
            }
            
            imageView.image = UIImage(data: data)
            contentView.addSubview(imageView)
        }
    }
```

### 📌 3. PATCH 안되는 부분
저희가 PATCH를 구현했고 이를 뷰에서 업데이트하려고 하는데 동작이 되지않네요ㅜㅜ 
그래서 값이 안 바뀐 것인가싶어서 브레이크포인트를 통해 찍어보고 찾아봤는데도 값이 바뀌는 것을 확인할 수 있었습니다.
하지만 실제 뷰에서 업뎃이 안되고 통신을 확인했을 때에도 값이 변하지는 않고 있었습니다.
그래서 아직 이 에러를 수정하지 못하고 있습니다..!

### 📌 4. ImageView 용량 사이즈
저희가 이미지뷰의 용량을 줄이기 위해 여러 방법이 있다는 것을 찾았습니다.
해상도 낮추기, 이미지 크기 줄이기 등이 있는 것을 보았고 실제 요구사항을 보았을 때 이미지의 크기를 줄이라는 말로 이해해서 그렇게 진행했습니다.
그래서 용량을 체크한 후 resize하여 저장하도록 했습니다.
그러나 실제 리사이즈한 것을 보게 되면 요구사항 보다 더 작은 이미지 크기가 되는 것을 확인할 수 있었습니다. 그래서 이를 레이아웃으로 키워서 꽉차도록 해야 하는 것인지 아니면 이대로 작아진 크기가 적절한 방법이였는지 궁금합니다!

```swift 
// 구현부 
extension UIImage {
    func resize(newWidth: CGFloat) -> UIImage {
        let scale = newWidth / self.size.width
        let newHeight = self.size.height * scale

        let size = CGSize(width: newWidth, height: newHeight)
        let renderer = UIGraphicsImageRenderer(size: size)
        let renderedImage = renderer.image { context in
            self.draw(in: CGRect(origin: .zero, size: size))
        }
        
        return renderedImage
    }
    
    func checkImageCapacity() -> Double {
        var capacity: Double = 0.0
        guard let data = self.pngData() else {
            return 0.0
        }
        
        capacity = Double(data.count) / 1024
        
        return capacity
    }
}
```

```swift
// 호출부
  guard let image = info[UIImagePickerController.InfoKey.editedImage] as? UIImage else {
                return
        }

        let imageCapacity = image.checkImageCapacity()

        if imageCapacity > 300 {
            let resizedImage = image.resize(newWidth: 80)
            self.imageArray.append(resizedImage)

            guard let imageData = resizedImage.jpegData(compressionQuality: 1) else {
                return
            }

            let imageInfo = ImageInfo(fileName: "rimasol.jpeg", data: imageData, type: "jpeg")
            self.networkImageArray.append(imageInfo)
        } else {
            self.imageArray.append(image)
            guard let imageData = image.jpegData(compressionQuality: 1) else {
                return
            }

            let imageInfo = ImageInfo(fileName: "rimasol.jpeg", data: imageData, type: "jpeg")
            self.networkImageArray.append(imageInfo)
        }
    ```

2022-05-29 14:02 UTC, jungseungyeo requested changes
에디, 마리솔 고생하셨습니다.

## 구현되지 않은 부분

`꼭 구현해주세요.ㅠㅠ 
우선순위는 netowker 추상화, 페이징 처리, 키보드 사용 처리등 순으로 해주세요. 
`

### 1. 공통 코드에 프로토콜 기본 구현 활용

`protocol을 사용하면 private이 불가능합니다. 무조건 노출이 되어야 되기 때문에 공통화가 가능합니다. 그래서 노출하는 것은 역할의 노출해야됩니다. 

예를 들어 hasNext와 같은 값을 노출하는 것이 아니라, 
이 객체가 채택 할 경우 필수로 가지고 있어야 하는 요소들을 만들어 주어야 합니다.
`

### 2. endpoint 활용하기

`enum을 사용하는 부분은 좋았습니다. 하지만 추상화 작업이 되지 않아 controller에서 executeGET, executePOST와 같이 추상화가 되지 않는 함수가 만들어지는 결과를 만들게 되었습니다. struct를 사용하지 않는 점에서 좋았지만 본질을 지키면서 사용하면 좋을거같아요.`

### 3. 다른 뷰에 프로퍼티 전달하는 방법

`넵 절대로 캡슐활르 위반해서는 안됩니다. 또 id는 model에 존재하는 값인거 같아요.`

#❓ 궁금한점

### 1. compactMap에서만 가능한 이유

`넵 compactMap은 swift 4.1버전에서 추가 된 기능입니다. 옵셔널을 없애주는 역할을 하는 기능이고 forEach문에서 작성한 코드가 되어 있다고 생각하면 될거같아요. `

### 📌 2. 여러 개의 ImageView 보여지도록 하는 방법

`지금 코드는 문제가 있습니다. imageView가 하나이기 때문에 하나만 적용이 될겁니다. productImage갯수만큼 넣고 싶다면 imageView갯수가  productImage와 같이 생성 되어야 될거예요.`

### 3. PATCH 안되는 부분

`PATCH networker를 보니 요청을 하고 있지 않네요.. ㅎㅎ.. 요청을 보내주세요.`

### 📌 4. ImageView 용량 사이즈

`정확히 이해한거지는 모르겠지만 image를 줄이면 화면이 빈 공간이 생기게 노출되어서 이렇게 해도 되는지를 묻는거라면 imageView에서 제공하는 contentMode에서 fill이라는 기능으로 노출 조건을 표시할수있어요 이부분을 활요하면 될거같아요 그게 아니고 사이즈를 딱 300으로 맞추고 싶다. 이건 해당 로직으로는 안되고 사이즈를 측정하는 부분을 300이 되도록 알고리즘을 작성해야 됩니다. 딱 그냥 300 이렇게 작성하는 코드는 존재하지 않아요 resize 방법도 있지만 절삭이라는 방법도 있어요 특정 이미지의 크기를 잘라서 사용하는 방법이죠. 이건 구현하기 나름인거같아요 :) `

에디, 마리솔 전반적으로 코드를 확인해보니 미흡한 부분이 많아요. 캡술화 위법 및 각 객체의 데이터 전달 방식등의 코드가 매우 복잡해지고 있어요. 또 잘 주입 된 networker객체의 session이 존재하지만 post에서는 따로 만들어서 사용하는 등 매우 위반하는 코드가 자주 사용되고 있습니다. 

코드를 작성하는 과정에서 OOP 관점을 위반하는 코드를 작성하는 습관은 좋지 않아요. 코드를 작성 하다가 잘 못 설계가 되었다면 다시 처음부터 작성하는 용기도 필요해요. 코멘트를 보시고 천천히 적용해주세요 

궁금한 거나 질문이 있으면 언제든지 알려주세요 :)

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +            self.networkManager.execute(with: .productList(pageNumber: 1, itemsPerPage: 20), httpMethod: .get) { result in
pageNumber를 1로 되면 페이징 처리가 안되지 않나요?

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        DispatchQueue.global().async {
DispatchQueue.global()로 요청해야 하는 이유가 있나요?

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
>          let dispatchGroup = DispatchGroup()
DispatchGroup을 사용하는 이유가 있나요? Group을 생성 할 일이 없는거같은데.. 어떤 이유가 있나요?

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        productDetailViewController.id = item[indexPath.row].id
이건 캡슐화 위반인거같네요. 캡슐화를 지켜주세요

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/View/ProductDetailViewController.swift
> +    var id: Int?
전 화면에서 받은 모델이 있지 않나요? 이 값을 model에 있는 값인거 같네요.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/View/ProductDetailViewController.swift
> +    var id: Int?
이 부분은 step2에서 적용 할 내용이긴 한데.. 코멘트만 남겨주세요

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/View/ProductEditView.swift
> +        return PatchRequest(name: name, description: description, thumbnailID: nil , price: price, currency: currency, discountedPrice: discountedPrice, stock: stock, secret: secret)
뷰에서 Request를 생성하면 안됩니다. 이 포맷은 networker 레이어에서 작업을 진행해주세요.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/View/ProductEditView.swift
> +            let secret = "c7ne65d5oc"
위의 키값은 networker에서 관리가 되어야 될거같아요. 보안키는 view영역에서 노출되면 안됩니다.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/View/ProductEditView.swift
> +        if presenter.currency == Currency.KRW.rawValue {
이 부분은 LayoutType 타입에서 적용한 내용과 같죠? 이 부분도 동일하게 수정하면 좋을거같아요.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ProductEditViewController.swift
> +    var productDetail: ProductDetail?
캡슐화를 위반하고 있어요 private를 꼭 붙여주세요.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ProductEditViewController.swift
> +    private var presenter = Presenter()
ui프로퍼티와 value값을 구분해서 선언해주세요

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ProductEditViewController.swift
> +        collectionView.register(EditViewCell.self, forCellWithReuseIdentifier: EditViewCell.identifier)
아래와 동일하게 set이라는 초기화 함수로 통일하면 좋을거같아요. 코드 스타일이 달라지면 안됩니다.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ProductEditViewController.swift
> +        productEditView.setEditView(presenter)
이 값이 왜 여기서 setEditView를 통해서 업데이트가 되나요? 이렇게 되면 cell의 마지막 모델의 값으로 화면이 정보가 업데이트 되지 않나요?

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ProductEditViewController.swift
> +        let dispatchGroup = DispatchGroup()
흠.. api를 호출하는 부분에서 모두 Group을 사용하는거 같아요. 이 Group을 사용하는 이유를 꼭 남겨주세요.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ProductEditViewController.swift
> +                    print("success")
print로 성공만 호출하면 되나요? 이 부분에서 ui를 동작을 해주면 더욱 좋을거같ㄴ에ㅛ.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/ProductEditViewController.swift
> +            self.navigationController?.popViewController(animated: true)
success과 failure에서 처리를 하기 위해서는 group보다는 따로 처리하는 방식이 좋지 않나요?

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/RegistrationViewController.swift
> +        self.navigationController?.navigationBar.topItem?.title = "Cancel"
흠.. title = "Cancel"을 넣는거랑 차이가 있을까요? 동일 곳을 표시하는 거같네요 ㅎㅎ

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/RegistrationViewController.swift
> +    @objc private func executePOST() {
exexutePost, executeGET이라는 함수를 생성한다면 추상화를 한 이유가 없어지죠? networkManager에서 execute함수의 파라미터로 httpMethod를 받고 있어서 그런가같아요. Endpoint에서 method 정보를 가지고 있고 exexute함수를 만들고 파라미터로 Endpoint를 받으면 하나의 함수로 처리가 가능할거같아요.

비슷한 역할을 하는 코드를 하나로 만들면 좋을거같아요.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Extension/UIImageView+.swift
> +    static let shared = NSCache<NSString, UIImage>()
흠.... 이것은 싱글톤이 아니예요. ImageCacheManager를 싱글톤을 만들고 싶으면 shared 상수가 ImageCacheManager를 생성하게 하면 될 거 같아요 :)

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/Presenter.swift
> +    mutating func setData(of product: Products) -> Presenter {
주입 후 분기를 여기서 한다면 model에서 로직을 가지고 있는 거 같은데 controller로 옮기는 것은 힘들었나요?

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/Presenter.swift
> +        var presenter = Presenter()
함수내에서 또 자신을 생성하고 생성한 것을 리턴하는 거같아요.. 이러면 setData함수를 호출 할 때 마다 Presenter가 존재하는 이유가 없지 않나요?

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/Presenter.swift
> +    private func formatNumber(price: Int) -> String {
함수들의 기능이 model로 넣어졌네요. 이렇게 되면 presentmodel이라기 보다는 포맷터의 역할을 하는 거같아요.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +    mutating func execute(with endPoint: Endpoint, httpMethod: HTTPMethod, params: Encodable? = nil, images: [ImageInfo]? = nil, completion: @escaping (Result<T, NetworkError>) -> Void) {
Endpoint가 프로토콜이 아니고 enum이네요 enum으로 하게 되면 추상화 작업이 안될거같아요. 추상화 작업을 위해서 protocol을 사용하게 변경 해주세요.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Network/EndPoint.swift
> +enum Endpoint {
networker부분에서도 코멘트를 하긴 하였는데 protocol을 사용하여 추상화 작업을 진행하면 좋을거같아요.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Network/EndPoint.swift
> +      return .makeUrl(with: "api/products?page_no=\(page)&items_perpage=\(itemsPerPage)")
이렇게 되면 이 api는 무조건 get만 적용되지 않나요? method의 따라서 url, body 구분하여 적용이 되게 하면 좋을거같아요.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Network/EndPoint.swift
> +      return .makeUrl(with: "api/products?page_no=\(page)&items_perpage=\(itemsPerPage)")
위의 정보를 알기 위해서는 Endpoint의 값이 method 정보가 있어야 겠죠? 추상화 작업을 하면서 method를 포함하면 좋을거같아요.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +import UIKit
networker 레이어에서 UIKit을 import하면 안됩니다.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +    var imageData: UIImage?
이 값은 여기서 필요없지 않나요? 삭제해주세요.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
>      var session: URLSessionProtocol
private을 꼭 붙여주세요 캡슐화를 위반하면 안됩니다.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        URLSession.shared.dataTask(with: request) { (data, response, error) in
여기서 따로 URLSession 사용하면 안됩니다. 이렇게 사용한다면 URLSession을 주입받은 의미가 없어집니다. 추상화를 통해 하나의 session을 사용하게 해주세요.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        }.resume()
네트워크 레이어에서는 성공 실패 여부를 외부한테 알려주는 부분이 있어야합니다. 이 함수를 보면 그 부분이 없는거같아요. 클로져를 통해서 controller까지 콜백을 알려주는 부분을 추가해주세요.

2022-05-29 14:02 UTC, jungseungyeo commented on OpenMarket/OpenMarket/View/EditViewCell.swift
> +            imageView.image = UIImage(data: data)
전역변수를 변경하고 넣으면 하나만 들어가지 않나요? 함수를 통해서 UIImageView를 생성하고 넣어주어야 다른 UIImageView가 하나하나 생성될거같아요.

2022-05-30 08:44 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        DispatchQueue.global().async {
아 저희가 `ExecuteGET()` 메서드의 DataTask가 비동기로 작업하고 있으므로 global thread에서 하고 있는 거 같습니다. 그래서 이 메서드에서도 작성할 필요없고  여기에서 또 작성할 필요가 없었네요! 삭제했습니다! 다음에는 더 신경써서 작성해보겠습니다ㅜㅜ

2022-05-30 08:45 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
>          let dispatchGroup = DispatchGroup()
아 처음에 저희가 `ViewDidAppear()`를 활용해서 GET를 다시 불러오는 것을 생각못하고 이 방식으로 끝났을 경우 pop 되게하면 보이겠다고 생각해서 설계를 했었습니다. 하지만 `ViewDidAppear`를 구현하고 그곳에서 GET를 부르기 때문에 이는 불필요한 코드 같습니다..! 모두 삭제했습니다!

2022-05-30 08:50 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Controller/ProductEditViewController.swift
> +    private var presenter = Presenter()
UI프로퍼티값과 Value 값의 경계가 없었네요 공백으로 분리했습니다!

2022-05-30 08:58 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Controller/ProductEditViewController.swift
> +        collectionView.register(EditViewCell.self, forCellWithReuseIdentifier: EditViewCell.identifier)
모든 ViewController에 통일성있게 초기화 함수를 구현해서 넣어주었습니다! 통일성 유지하도록 신경쓰겠습니다!!!

2022-05-30 08:59 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
>      var session: URLSessionProtocol
붙였습니다..! 잘 인지하도록하겠습니다!

2022-05-30 12:18 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +    var imageData: UIImage?
삭제했습니다!

2022-05-30 12:19 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +import UIKit
networker 레이어에 UI 관련된 것이 없으므로 Foundation으로 하는 것이 맞는거 같습니다!!

2022-05-30 12:53 UTC, marisol-develop commented on OpenMarket/OpenMarket/Controller/RegistrationViewController.swift
> +        self.navigationController?.navigationBar.topItem?.title = "Cancel"
저렇게 설정해줬을때 다음화면에 갔다가 돌아오면 title이 "Cancel"이 되는 문제가있어서 backButtonItem으로 설정해주었습니다!

2022-05-30 13:03 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Controller/ProductEditViewController.swift
> +                    print("success")
alert 표시를 통해 사용자에게도 되었는지 안되었는지를 확인하도록 구현했습니다!

```swift
    private func showSuccessAlert() {
        let alert = UIAlertController(title: "수정 완료", message: "수정에 성공했습니다!", preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .default))
        self.present(alert, animated: true)
    }
    
    private func showFailureAlert() {
        let alert = UIAlertController(title: "수정 실패", message: "수정에 실패했습니다!", preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .default))
        self.present(alert, animated: true)
    }
```

2022-05-30 13:22 UTC, marisol-develop commented on OpenMarket/OpenMarket/Extension/UIImageView+.swift
> +    static let shared = NSCache<NSString, UIImage>()
저희가 싱글턴을 잘못 사용하고 있었네요ㅠㅠ 
shared 상수가 ImageCacheManager를 생성하도록 수정했습니다.
```
static let shared = ImageCacheManager()
let NScache = NSCache<NSString, UIImage>()
private init() {}
```

2022-05-31 01:51 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Controller/ProductEditViewController.swift
> +        productEditView.setEditView(presenter)
저희가 잘못생각하고 넣은거 같습니다! 생각해보니 cell 업데이트마다 뷰를 하면 동일한 것을 계속 업데이트 하는 것이기 이는 불필요한 작업인거 같습니다. 그래서 처음에 데이터를 넣고 뷰를 업데이트해서 한번 호출하도록 변경했습니다!
```swift
   private func setData() {
        guard let productDetail = productDetail else {
            return
        }
        
        presenter = presenter.setData(of: productDetail)
        productEditView.setEditView(presenter)
    }
```

2022-05-31 01:52 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Model/Presenter.swift
> +        var presenter = Presenter()
맞습니다! 불필요하므로 이를 제거했습니다 감사합니다!

2022-05-31 01:54 UTC, marisol-develop commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        productDetailViewController.id = item[indexPath.row].id
ProductDetailViewController의 생성자를 통해 item[indexPath.row]를 전달하는 방식으로 캡슐화 위반을 해결했습니다!

```swift
func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        let productDetailViewController = ProductDetailViewController(products: item[indexPath.row])
        
        self.navigationController?.pushViewController(productDetailViewController, animated: true)
    }
```

2022-05-31 01:56 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/View/ProductDetailViewController.swift
> +    var id: Int?
아 맞습니다! 그래서 init를 활용해서 MainController에서 선택한 것의 Products를 받아서 저장하도록 했으며 ProductDetailViewController에서 이를 활용해서 id를 비교하도록 수정했습니다!
```swift
// MainViewController
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        let productDetailViewController = ProductDetailViewController(products: item[indexPath.row])
        
        self.navigationController?.pushViewController(productDetailViewController, animated: true)
    }

// ProductDetailViewController
   init(products: Products) {
        self.products = products
        super.init(nibName: nil, bundle: nil)
    }
    
....

    private func executeGET() {
        guard let id = self.products.id else {
            return
        }
        
        self.networkManager.execute(with: .productEdit(productId: id), httpMethod: .get) { result in
            switch result {
            case .success(let result):
                self.productDetail = result
            case .failure(let error):
                print(error.localizedDescription)
            }
        }
    }
```

2022-05-31 01:56 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        productDetailViewController.id = item[indexPath.row].id
아래 댓글로 수정사항에 대해 적었습니다!

2022-05-31 01:59 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/View/ProductEditView.swift
> +            let secret = "c7ne65d5oc"
enum으로 처리해서 실제 사용하는 곳에 사용하는 식으로 변경했습니다!
```swift
enum UserInformation {
    static let identifer: String = "affb87d9-d1b7-11ec-9676-d3cd1a738d6f"
    static let secret: String = "c7ne65d5oc"
}
```

2022-05-31 01:59 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/View/ProductEditView.swift
> +        if presenter.currency == Currency.KRW.rawValue {
enum과 rawValue를 활용해서 switch문으로 처리하도록 변경했습니다!
```swift
        switch Currency(rawValue: presenter.currency ?? "0") {
        case .KRW:
            segmentedControl.selectedSegmentIndex = 0
        case .USD:
            segmentedControl.selectedSegmentIndex = 1
        case .none:
            segmentedControl.selectedSegmentIndex = 0
        }
```

2022-05-31 02:01 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/View/ProductDetailViewController.swift
> +    var id: Int?
위에 수정사항으로 적었습니다!

2022-05-31 02:01 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Controller/ProductEditViewController.swift
> +        let dispatchGroup = DispatchGroup()
다른 부분에서 사용하지 않고 지운다는 멘트를 적었습니다! 사용이유가 없었네요 ㅜㅜ

2022-05-31 03:00 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Controller/ProductEditViewController.swift
> +    var productDetail: ProductDetail?
초기화를 활용해서 캡슐화가 되도록 수정했습니다!!!

2022-05-31 04:31 UTC, marisol-develop commented on OpenMarket/OpenMarket/Model/Presenter.swift
> +    mutating func setData(of product: Products) -> Presenter {
stock을 controller에서 분기처리하도록 코드 변경했습니다

2022-05-31 06:48 UTC, marisol-develop commented on OpenMarket/OpenMarket/Model/Presenter.swift
> +    private func formatNumber(price: Int) -> String {
Int의 extension으로 formatNumber 메서드를 만들어주었고, controller에서 format 처리하도록 변경했습니다.

2022-05-31 14:24 UTC, jungseungyeo approved these changes

2022-05-31 14:24 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/RegistrationViewController.swift
> +        cell.button.addTarget(self, action: #selector(self.pickImage(_:)), for: .touchUpInside)
이렇게 작성이 되면 캡슐화 위반입니다. 캡슈를 지켜주세요. 다음 스텝에서 수정 해주세요 :)

2022-05-31 14:24 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Controller/RegistrationViewController.swift
> +        cell.button.addTarget(self, action: #selector(self.pickImage(_:)), for: .touchUpInside)
다른 cell을 구현한거처럼 configure를 설정해주세요 그리고 터치 이벤트를 처리 할 경우 delegate 패턴을 통해 의존성 역전으로 해결해주세요

2022-05-31 14:25 UTC, merged

2022-06-04 05:02 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +            self.networkManager.execute(with: .productList(pageNumber: 1, itemsPerPage: 20), httpMethod: .get) { result in
페이징 처리해서 구현했습니다!

2022-06-04 05:03 UTC, kimkyunghun3 commented on OpenMarket/OpenMarket/View/EditViewCell.swift
> +            imageView.image = UIImage(data: data)
수정해서 이미지뷰를 제대로 보이도록 구현했습니다!

2022-06-05 11:16 UTC, marisol-develop commented on OpenMarket/OpenMarket/View/ProductEditView.swift
> +        return PatchRequest(name: name, description: description, thumbnailID: nil , price: price, currency: currency, discountedPrice: discountedPrice, stock: stock, secret: secret)
뷰에서는 Request를 위한 모델에 정보만 업데이트 해주고, Request는 NetworkManager에서 생성하는 것으로 변경했습니다!

2022-06-05 11:17 UTC, marisol-develop commented on OpenMarket/OpenMarket/Controller/ProductEditViewController.swift
> +            self.navigationController?.popViewController(animated: true)
네ㅠㅠ Group은 사용할 필요가 없다고 판단해서, 모두 제거했습니다

2022-06-05 11:19 UTC, marisol-develop commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +    mutating func execute(with endPoint: Endpoint, httpMethod: HTTPMethod, params: Encodable? = nil, images: [ImageInfo]? = nil, completion: @escaping (Result<T, NetworkError>) -> Void) {
APIable이라는 프로토콜을 만들고, 그 APIable 프로토콜 내부에 httpMethod와 필요한 파라미터들을 갖고 있도록 만들었습니다

2022-06-05 11:20 UTC, marisol-develop commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        URLSession.shared.dataTask(with: request) { (data, response, error) in
하나의 urlsession을 사용하도록 수정했습니다!

2022-06-05 11:21 UTC, marisol-develop commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        }.resume()
성공 실패 여부를 알려주는 코드를 추가했습니다