오픈마켓 II [STEP2] mmim, cathy
yagom-academy/ios-open-market pull request #168
Opened 2022-06-02 12:29 UTC by JoSH0318

@Monsteel 안녕하세요 토니!💝
마지막 PR도 잘 부탁드립니다! 😀

---

### 고민한 점(트러블 슈팅)
#### 📌II-STEP2-1
1️⃣ 상품 상세화면은 어떻게 구현할까
- 상품 상세화면은 크게 3가지 파트로 나뉜다고 판단했다. 
    - 상단: scroll을 통해 나열된 Image가 보여지는 곳
    - 중단: 상품의 정보가 text로 보여지는 곳
    - 하단: 상품의 설명이 여러줄로 보여지는 곳
- 상, 중, 하가 수직으로 나열되어있기 때문에 vertical StackView를 사용하여 layout을 잡아주었다.
- vertical StackView의 aliment와 distribution을 fill로 주어서 모든 컨텐츠가 화면에 꽉 차도록 설정했다.
- image scroll view와 상품 정보 stack view의 높이값을 화면 비율에 맞추어 설정해주어서 모든 기기에 알맞은 사이즈를 갖도록 했다.
- 상품 이름 label과 설명 label은 길어질수도 있는 유동적인 정보임으로 line을 0으로 설정해주었다.
- 하단의 상품 설명은 scroll view로 구성했고, 글자의 line이 길어지면 scroll을 통해 모든 정보를 확인할 수 있도록 했다.
- 또한, 상품 설명 scroll view의 subview는 바로 label이 아니라 UIView로 설정했고, UIView 안에 label을 넣어주었다.

<image width="400" src="https://i.imgur.com/IxJKZZL.png"/>

2️⃣ 상품 상세화면을 들어왔을 때, 경로 찾기
- **상품 상세화면**에 뿌려질 데이터를 위해선 상품마다 각기 다른 Endpoint가 존재한다. 
    - {{api_host}}/api/products/{{product_id}} 
- 위의 예시처럼 상품 `product_id`가 있고, 그 상품의 상세 정보를 가져오기 위해선 `product_id`가 필요하다.
- 🤔 **상품 상세화면**에선 `product_id`가 없어서 아직 데이터를 받아오지 못하는데 어디에서 `product_id`를 알아내야 할지에 대해서 고민했다.
- 이전 화면인 **상품 리스트 화면**에선 GET의 response로 다양한 정보를 받을 수 있는데, 그 중 상품 식별번호인 `id` 값을 가지고있다.
- 따라서 상품 Cell을 클릭했을 때, 해당 `id`값을 상세화면에 전달해주면 된다고 판단했다.
> 이전 화면에서 메서드 주입으로 `id`을 받아오고 그것을 통해 해당 **상품 상세 정보**를 GET할 수 있었다.

3️⃣ 상품상세 화면 데이터 get
- 상품상세 화면에선 GET을 통해 데이터를 필요한 곳에 뿌려준다.
- 때문에 HTTP 통신을 담당하는 메서드와 같은 경우, 
    - 1) 최초 상품상세 화면 진입시 
    - 2)Edit 후 변경된 데이터가 적용된 상품상세 화면 진입시 
- 호출되어야한다.
- viewDidLoad()는 해당 VC의 인스턴스가 생성될 때, 호출된다.
- present된 화면을 들어갔다가 나온다 하더라도 VC의 인스턴스는 메모리에서 해제되지 않고있기 때문에 viewDidLoad()는 호출되지 않는다.
> 따라서 viewWillApear()에서 호출해주었고, 두 가지 경우에 모두 HTTP 통신을 할 수 있도록 해주었다.

#### 📌II-STEP2-2
1️⃣ HTTP통신 delete의 실패...🤔 productSecret(secretKey) 조회😭
- delete 구현을 하고 실행했을 때, network status 400 오류가 발생했다.
- 경로값에 `product_id`와 `product_secret`을 넣어주면 되기 때문에 오타의 가능성이 낮다고 판단했고, 다른 이유를 찾아보았다.
> 👏 delete에서 요구하는 `product_secret`에 대해서 오해하고 있었다. 
> `product_secret`는 판매자 비밀번호인 `secret`와 다르다.
- `product_secret`는 판매자 비밀번호가 아니라 상품 삭제에 필요한 secretKey였다.
- 이를 얻기 위해선 상품 삭제 Secret 조회 경로에 판매자 비밀번호를 바디에 넣어 POST해야한다.
> 이런 과정을 통해 response로 얻은 `productSecret(secretKey)`를 delete 경로값에 넣어주어서 문제를 해결하였다.

2️⃣ password가 실패했을 때, 처리방법
<image width="200" src="https://i.imgur.com/qxw2ZdM.png"/>
- 위처럼 게시 상품을 삭제하기 위해선 password를 입력해야한다. 
- 만약 사용자가 잘못된 password를 입력했을 경우, 그 다음은 어떠한 식으로 app이 동작해야하는 지에 대해서 고민했다. 
- 결정에 앞서 세 가지 사항을 목표로 했다.
    - 첫번째, 사용자 입장에게 비밀번호가 잘못 됐다는 것을 알려야한다.
    - 두번째, 사용자에게 계속해서 비밀번호를 입력할 기회를 주어야한다.
    - 세번째, 많은 선택지를 주는 것은 사용자로 하여금 혼동의 여지를 준다. 사용자의 선택지를 줄여서 행동을 단순화 시켜야한다.
    
<image width="200" src="https://i.imgur.com/6W56CNu.png"/>
- password가 틀렸을 경우, 비밀번호가 틀렸다는 것을 명확히 알리는 alert을 띄웠다.
- 확인 버튼을 누르면 다시 pssword 입력창이 뜨도록 구현했다.

3️⃣ delete에 대한 고민
- 판매자 비밀번호(password)를 입력하고, `상품 삭제 secret 조회` 통신이 성공하면 올바른 비밀번호, 실패하면 잘못된 비밀번호이다.
- 순서를 적어보면 **비밀번호 입력 -> 버튼 클릭 -> `상품 삭제 secret 조회` -> delete 성공 or 실패** 순서로 동작한다. 
- 하나의 트리거(버튼)로 `상품 삭제 secret 조회` 통신 결과에 delete의 여부가 달라진다.
> 이를 해결하기 해서 `상품 삭제 secret 조회` 메서드에 completionHandler를 파라미터로 받도록하고, 성공시 secretKey(String)과 성공여부(Bool)을 튜플타입으로 completionHandler에 전달하도록 했다.
```swift
private func checkSecretKey(
    _ inputPassword: String?,
    completionHandler: @escaping (String, Bool) -> Void
  ) {
    guard let pageId = self.pageId else {
      return
    }
    guard let inputPassword = inputPassword else {
      return
    }
    self.httpProvider.searchSecret(
      .secretKey(productId: pageId),
      inputPassword
    ) { result in
      switch result {
      case .success(let data):
        guard let reponseSecret = String(data: data, encoding: .utf8) else {
          return
        }
        completionHandler(reponseSecret, true)
      case .failure(let error):
        print(error)
        completionHandler(error.localizedDescription, false)
      }
    }
  }
```

4️⃣ scrollView paging
- scrollView의 paging를 적용하기 위해선 imageView의 frame 계산을 해야했고, 이를 구현하는데 가장 많은 고민을 했다.
<image width="600" src="https://i.imgur.com/jyfyWd5.png"/>

- 위 그림처럼 page마다 **scrollView의 bounds.origin**은 **view.frame * page수** 이다.
- imageView는 scrollView frame 영역의 중앙에 위치하기 때문에 margin을 더해줘야한다.
- 따라서 **imageView의 page당 origin**은 **view.frame * page수 + margin**이 된다.
- 이 계산을 바탕으로 아래와 같은 코드를 구현하였다.
```swift
for index in 0..<images.count {
      let imageView = UIImageView()
      imageView.loadImage(urlString: images[index].url)
      let margin = (imageScrollView.frame.width - imageScrollView.frame.height) / 2
      let originX = (self.frame.width * CGFloat(index)) + margin
      imageView.frame = CGRect(
        x: originX,
        y: 0,
        width: imageScrollView.frame.height,
        height: imageScrollView.frame.height
      )
      imageScrollView.addSubview(imageView)
      imageScrollView.contentSize.width = imageScrollView.frame.width * CGFloat(index + 1)
    }
```

5️⃣ pageControl
- 이번 프로젝트 요구 조건에는 없었지만 `pageControl`을 추가하면 UI적으로 더 좋을 것 같다고 생각하여 `UIPageControl`을 사용해보았다. 
- `pageControl`의 `numberOfPage`로 이미지 전체 개수를 설정해주고 `UIScrollViewDelegate`를 채택하여 `scrollViewDidScroll` 메서드에서 xPosition값으로 스크롤뷰의 현재 x의 위치에서 스크롤뷰의 가로를 나눈 값을 설정해주었다. 
- 그리고 현재 위치를 UIPageControl의 currentPage로 설정해주었다.
- 마지막으로 DetailViewController에서 viewWillAppear 시점에서 scrollview의 delegate를 Detailcontroller인 self로 설정해주었다.
```swift
extension DetailViewController: UIScrollViewDelegate {
  func scrollViewDidScroll(_ scrollView: UIScrollView) {
    let xPosition = scrollView.contentOffset.x / scrollView.frame.width
    let pageNumber = Int(round(xPosition))
    detailView.setCurrentPage(pageNumber)
  }
}
```

6️⃣ 자신의 게시물만 수정 가능하도록 하기
- 상품의 Edit은 애초에 상품 게시자만 접근할 수 있도록 하는 것이 논리적으로 당연하다고 판단했다.
- 자신이 등록한 상품이 아님에도 Edit를 시도하면 어차피 Edit은 실패하기 때문에 사용자 경험상 정말 좋지 않을 것이다.
- 따라서 상품의 게시자만 Edit에 접근할 수 있도록 구현해야 한다고 판단했다.
- 상품상세 화면에서는 get response로 받아온 데이터를 알고있다. 
- 이 데이터 중에서 해당 상품의 게시자를 식별할 수 있는 식별자는 `vender_ID` 밖에 없다.
- 사실상 우리는 식별자로 `user identifier`와 `password`만 알고있기 때문에 `vender_ID`와 현재 사용자가 같은지 다른지를 판단할 수 없다.
- 따라서 이전에 POST 과정에서 알아낸 `vender_ID` 값을 강제로 넣어줬다.
- 이를 통해 사용자의 id와 네트워크 통신을 통해 받은 작성자의 id가 같을 경우에만 `rightBarButtonItem`에 버튼을 추가하도록 구현하였다.
```swift
    if product?.venderId == Constants.venderId {
      self.navigationItem.rightBarButtonItem = UIBarButtonItem(
        barButtonSystemItem: .action,
        target: self,
        action: #selector(presentActionSheet)
      )
    }
```

### 질문사항 
1️⃣ Network 관련 추상화
Network 관련 객체를 보면 반복되는 코드가 많은 것 같습니다. 
또한, 호출되는 곳에서는 경우에 따라 사용하는 메서드가 달라지고, 메서드가 달라져 파라미터를 주입하는 방법도 달라집니다. 그렇기 때문에 매우 복잡해보입니다.
이러한 이유로 추상화가 안된 것 같다라는 생각을 했습니다.
막연하게 추상화가 안 됐다고만 판단되고 어떻게 해야할지는 모르겠습니다. 😭
추상화 시점에서 바라본 구조적인 문제를 지적해주시고 어떤 방법이 좋은지 말씀해주시면 정말정말정말 감사하겠습니다!!!

2️⃣ Alert layout 오류
<img width="500" src="https://i.imgur.com/z2cVS6Q.png">
detail view에서 수정/삭제 버튼을 탭하면 action sheet 후 비밀번호를 입력하는 alert창을 띄우도록 하였는데 위와 같이 alert창 내의 UIView에서 레이아웃 에러가 발생했습니다. UIAlertController에서의 에러인 것 같아서 해결하지 못하였는데 alert을 사용할 때 추가적으로 설정해줘야하는 부분이 있는건지 여쭤보고 싶습니다.

3️⃣ action sheet 선택 기준 (HIG)
- HIG의 action sheet 파트를 보면 
![](https://i.imgur.com/52EJjEe.png)
<image width="300" src="https://i.imgur.com/ZXrHuLr.png"/>
> 파괴적(destructive)이거나 위험한 작업을 수행하는 버튼에는 파괴적인(destructive) 스타일을 사용하고 이러한 버튼을 작업 시트의 맨 위에 배치합니다.

- 라고 나와있습니다!
- 하지만 저희 요구사항에는 반대로 나와있습니다. (하지만 HIG를...따르라고 하시기도 했어요.)
![](https://i.imgur.com/7GAfY5n.png)

저희가 HIG를 잘못 읽은건지 아니면 HIG에서 제안하는 경우와 다른 경우인 건지 궁금합니다.🤔

4️⃣ Edit 권한에 대해서
위에 고민한 점에서 `II-STEP2-2 > 6️⃣ 자신의 게시물만 수정 가능하도록 하기`를 보시면 저희가 요구사항과 다르게 작성한 점이 있습니다.
위와 같은 방법이 좋지 않은 방법임을 알고있지만, 내가 작성한 게시물이 아님에도 Edit을 허용해주는 것이 너무 논리적으로 말이 되지 않는다고 판단하여 저러한 방법을 선택했습니다.
vender_ID는 게시물을 POST할 때, response로 주어지는 데이터에서 알아냈습니다.
(vender_ID는 서버에서 유저의 identifier에 따라 생성해주는 것으로 예상하고 있습니다.)
만약 서버에서 vender_ID 책정하는 방법을 바꾼다면 아주아주 크리티컬한 버그가 발생될 것으로 생각이 들긴합니다 😭
어떻게 이 부분을 해결해야할까요? 좋은 방법이 있을까요?

2022-06-07 00:44 UTC, Monsteel requested changes
안녕하세요 캐시 밈~! 🙇🏻‍♂️ 리뷰 일정 배려해주셔서 감사합니다! 🙏

## 질문사항에 대한 답변
> 1️⃣ Network 관련 추상화
Network 관련 객체를 보면 반복되는 코드가 많은 것 같습니다.
또한, 호출되는 곳에서는 경우에 따라 사용하는 메서드가 달라지고, 메서드가 달라져 파라미터를 주입하는 방법도 달라집니다. 그렇기 때문에 매우 복잡해보입니다.
이러한 이유로 추상화가 안된 것 같다라는 생각을 했습니다.
막연하게 추상화가 안 됐다고만 판단되고 어떻게 해야할지는 모르겠습니다. 😭
추상화 시점에서 바라본 구조적인 문제를 지적해주시고 어떤 방법이 좋은지 말씀해주시면 정말정말정말 감사하겠습니다!!!

코드를 보고 어떤 부분에 대해 고민하셨는지, 그 고민을 어떻게 풀어내셨는지를 느낄 수 있었습니다.
우선 캐시와 밈이 적용한 방법도 네트워크 통신이 처음인점, URLSession을 사용한 점을 감안하면, 예쁘게 잘 추상화 했다고 생각합니다.

enum을 사용하였기에, 새로운 API가 추가되었을 때 사용자가 해당 API에 대한 설정을 누락하기는 어려울 것 같구요.

아래 opensource참고하시면, 더 명확하고 조금 더 사용하기 쉬운 방법을 찾으시는데에 도움이 될 것 같아요.
[Alamofire](https://github.com/Alamofire/Alamofire), [Moya](https://github.com/Moya/Moya)

요 두 Opensource가 어떻게 구현되어 있는지를 중심으로 살펴보면 밈과 캐시가 고민하셨던 포인트에서 영감을 얻으실 수 있는 포인트가 몇가지 있을거라 생각해요 🙌

"구현"에 대해 관심을 가지고 👀살펴봐 주시면 좋을 것 같습니다 :)

> 2️⃣ Alert layout 오류
> <img width="500" src="https://i.imgur.com/z2cVS6Q.png">
> detail view에서 수정/삭제 버튼을 탭하면 action sheet 후 비밀번호를 입력하는 alert창을 띄우도록 하였는데 위와 같이 alert창 내의 UIView에서 레이아웃 에러가 발생했습니다. UIAlertController에서의 에러인 것 같아서 해결하지 못하였는데 alert을 사용할 때 추가적으로 설정해줘야하는 부분이 있는건지 여쭤보고 싶습니다.

우선 제가 알고있는 사용법과 동일하게 작성해 주셨습니다!
별도의 빈 프로젝트에서 Alert를 띄웠을 때 동일한 문제가 발생하는것으로 보아.. Alert 자체의 문제가 아닌지 추측해 봅니다. 😭

> 3️⃣ action sheet 선택 기준 (HIG)
> - HIG의 action sheet 파트를 보면 
> ![](https://i.imgur.com/52EJjEe.png)
> <image width="300" src="https://i.imgur.com/ZXrHuLr.png"/>
> 파괴적(destructive)이거나 위험한 작업을 수행하는 버튼에는 파괴적인(destructive) 스타일을 사용하고 이러한 버튼을 작업 시트의 맨 위에 배치합니다.
>
> - 라고 나와있습니다!
> - 하지만 저희 요구사항에는 반대로 나와있습니다. (하지만 HIG를...따르라고 하시기도 했어요.)
> ![](https://i.imgur.com/7GAfY5n.png)
> 
> 저희가 HIG를 잘못 읽은건지 아니면 HIG에서 제안하는 경우와 다른 경우인 건지 궁금합니다.🤔

오! 그렇네요! 야곰아카데미 Contributor가 될 기회인것 같아요!! 👀

> 4️⃣ Edit 권한에 대해서
위에 고민한 점에서 `II-STEP2-2 > 6️⃣ 자신의 게시물만 수정 가능하도록 하기`를 보시면 저희가 요구사항과 다르게 작성한 점이 있습니다.
위와 같은 방법이 좋지 않은 방법임을 알고있지만, 내가 작성한 게시물이 아님에도 Edit을 허용해주는 것이 너무 논리적으로 말이 되지 않는다고 판단하여 저러한 방법을 선택했습니다.
vender_ID는 게시물을 POST할 때, response로 주어지는 데이터에서 알아냈습니다.
(vender_ID는 서버에서 유저의 identifier에 따라 생성해주는 것으로 예상하고 있습니다.)
만약 서버에서 vender_ID 책정하는 방법을 바꾼다면 아주아주 크리티컬한 버그가 발생될 것으로 생각이 들긴합니다 😭
어떻게 이 부분을 해결해야할까요? 좋은 방법이 있을까요?

reverse engineering을 통해서 vender_ID 를 책정하는 정책을 도출 해 내셨는데, 
**Demo서버이기 때문에 큰 문제는 없을것 같아요! 🙌**
다만, 현업에서는 서버개발자와 함께 협업을 통해서 product를 만들어 나가게 될거라, 서버 개발자와 소통하여 해결하실 수 있을거에요 🚀

이번 아카데미에서, 실제 유저의 사용성 측면을 고려하셔서 코드에 반영해주신 점, 굉장히 멋집니다!
단순히 기획에 따라 구현만 하는 코더가 아니라, 진짜 개발자, 엔지니어로 성장하실 수 있을것 같은 생각이 듭니다 🙌

리뷰 확인해 주시고, 추가로 궁금하신 점이 있으시다면 코멘트 부탁드립니다 🙏

2022-06-07 00:44 UTC, Monsteel commented on OpenMarket/OpenMarket/Controller/DetailViewController.swift
> +    static let wrongAlertMessage = "다시 시도해주세요."
요런 부분들을 상수로 분리해서 얻을 수 있는 장점이 있을까요? 🙋🏻‍♂️

2022-06-07 00:44 UTC, Monsteel commented on OpenMarket/OpenMarket/Controller/DetailViewController.swift
> +    if product?.venderId == Constants.venderId {
product를 guard 문을 사용해서 Unwrapping해주면 좋을것 같아요! 👀

2022-06-07 05:29 UTC, JoSH0318 commented on OpenMarket/OpenMarket/Controller/DetailViewController.swift
> +    static let wrongAlertMessage = "다시 시도해주세요."
사용자가 직접 접하는 문장들은 기획, 수정에 따라  언제든지 바뀐다고 생각했습니다.
(저런 문장들은 개발자가 정하지 않고, 기획에서 내려주는 대로 만드는 것이라 수시로 바뀔수도 있다고 판단했어요 🤓)
그때마다 코드를 뒤지고 바꿔줘야하는 과정이 조금 소모적이라고 생각이 들었어요!

사실 🤩
실제로 저희가 비밀번호를 틀렸을 시 알럿을 다시띄우는 기능을 추가했는데,
그때, 추가된 기능에 맞춰서 문장을 바꿔야했습니다. 
이처럼 한곳에 상수로 name space로 만들어 놓으니 코드 전체를 뒤지지 않아도 손쉽게 바꿀수 있더라구요 😊

2022-06-07 05:38 UTC, JoSH0318 commented on OpenMarket/OpenMarket/Controller/DetailViewController.swift
> +    if product?.venderId == Constants.venderId {
일단 말씀하신대로 수정했습니다!!😊

그런데 의문이 생겼는데요!!
서버에서 잘못된 값이 내려와서 product?.venderId 가 nil이 됐다고 가정했을 때,
저희가 원하는 동작은 edit 버튼만 나오지 않고 navigationBar는 생성되는 것 입니다.

그런데 토니 말씀대로 guard 문을 통한 Unwrapping을 해주게 되면 early return이기 때문에 configureNavigationBar() 메서드 자체를 빠져나가게되고 navigationBar가 생성되지 않을 것 같습니다!

이러한 경우에도 nil값에 대한 코드의 안정성을 위해 guard문을 이용한 Unwrapping을 해주는게 맞는 것 일까요?😭

2022-06-07 06:20 UTC, Monsteel commented on OpenMarket/OpenMarket/Controller/DetailViewController.swift
> +    if product?.venderId == Constants.venderId {
85번 라인(`if product?.venderId == Constants.venderId {`) 과
93번 라인(`self.navigationItem.title = self.product?.name`) 에서 중복으로 optional value를 사용하는 모습을 보고 요 부분 코드를 인상깊게 봤었는데요.

guard문을 통해 오히려 nil일 때, 그렇지 않을 때, 혹은 guard문 이전(nil유무에 관계없이)에 실행하는 code에 대해 조금 더 명시적으로 표현할 수 있을것 같다고 생각해서 남긴 코멘트였습니다!

그리고, 제 코멘트를 무조건 반영하실 필요는 없고 판단은 밈과 캐시가 해주시면 더 좋을것 같아요 🙌

2022-06-07 06:21 UTC, Monsteel commented on OpenMarket/OpenMarket/Controller/DetailViewController.swift
> +    static let wrongAlertMessage = "다시 시도해주세요."
오호 그렇군요 :) 좋습니다!
뭔가 변수명을 정하는데 있어서 많은 리소스가 소모될 것 같았고, 소모된 리소스에 비해 그 효과는 적을거라 생각했는데 멋진 이유가 있으셨군요! 🚀

2022-06-13 01:00 UTC, Monsteel approved these changes
캐시 밈 모두 수고하셨습니다~! 🫶🫶🫶

2022-06-13 01:00 UTC, merged