오픈마켓 [STEP1] bonf, Finnn
yagom-academy/ios-open-market pull request #173
Opened 2022-07-11 12:31 UTC by finnn1

# 오픈 마켓 STEP1 PR 💸

---

안녕하세요! 쿠마(@leejun6694) Bonf, Finnn입니다 😊
오픈 마켓 Step 1 PR 보냅니다!
이번 프로젝트 잘부탁드립니다 😚

---

### 코드 설명 🧑‍💻
> 
> ### Products
> products.json 파일을 파싱할 때 사용되는 Codable 타입
> CodingKeys 열거형을 사용해서, 프로퍼티의 컨벤션 스타일을 Swift 스타일로 변경해서 받을 수 있도록 했습니다.

> ### ProductsDataManager
> api정보를 갖고 있는 url을 가져와서 Products 모델의 형식에 맞게 Decoding 해주도록 했습니다.

### 궁금한 점 🤷🏻‍♂️
> **Decoding Error :**
> JSON 파일을 Decoding 해주는 과정에서, error처리를 해주기 위해서 DecodingError 타입을 정의해주려고 했습니다. 그런데 이미 해당 타입이 정의되어 있어서 그 타입을 사용해보았는데, 이렇게 사용하는 것이 맞는지 궁금합니다. 😢
```swift
guard let data = data else {
    let decodingContext = DecodingError.Context.init(codingPath: Products.CodingKeys.allCases, debugDescription: "")
    completion(.failure(DecodingError.dataCorrupted(decodingContext)))
    return
}
            
guard let decodedData = try? JSONDecoder().decode(Products.self, from: data) else {
    let decodingContext = DecodingError.Context.init(codingPath: Products.CodingKeys.allCases, debugDescription: "")
    completion(.failure(DecodingError.typeMismatch(Products.self, decodingContext)))
    return
}
```

### 고민한 점 🤔
> **@escaping completion closure :**
> URLSession을 사용해서 HTTPRequest를 호출하는 과정에서, 네트워크 작업이 완료될 경우 Response 받은 데이터를 어떻게 처리해줄지 고민하다가 작업이 완료되면 completion으로 실행할 클로저를 받아서 처리하는 방식으로 해결했습니다.

2022-07-11 15:22 UTC, leejun6694 requested changes
bonf, Finnn 안녕하세요 : )
step 1 을 빠르게 구현해주셨네요~!
몇가지 포인트에서 리뷰를 남겼는데, 확인 부탁드립니다ㅎㅎ

2022-07-11 15:22 UTC, leejun6694 commented on OpenMarket/OpenMarket/AppDelegate.swift
> -//
엇 이 주석은 안 지우셔도 괜찮습니다ㅎㅎ

2022-07-11 15:22 UTC, leejun6694 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +            if let error = error {
에러 핸들링은 따로 메서드를 만들어보는건 어떨까요?

2022-07-11 15:22 UTC, leejun6694 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +    func getData(pageNumber: Int, itemsPerPage: Int, completion: @escaping (Result<Products, Error>) -> Void) {
지금 method 로는 다른 API 통신이 필요한 경우, 중복되는 코드들이 많아질거에요.
공용으로 사용하는 API 관련 코드를 구현까지는 아니더라도, 이런 코드들은 공통으로 사용할 수 있을 것이다! 하는 부분을 고민해볼까요?
잘 이해가 안되신다면, 디스코드로 말씀주세요~~!

2022-07-11 15:22 UTC, leejun6694 commented on OpenMarket/JsonParsingTests/JsonParsingTests.swift
> +              let data = try? Data(contentsOf: fileLocation) else { return }
return 에 걸리면 test 결과가 어떻게 되나요!?

2022-07-11 15:22 UTC, leejun6694 commented on OpenMarket/JsonParsingTests/JsonParsingTests.swift
> +        let parsedData = try! JSONDecoder().decode(Products.self, from: data)
try 를 강제로 진행한 부분이 있고, 안전하게 해결하는 부분이 있는데
이렇게 구현한 이유가 있으신가요~!?

2022-07-11 15:22 UTC, leejun6694 commented on OpenMarket/OpenMarket/Models/Products.swift
> +struct Page: Codable {
`Codable` 도 한번 생각을 더 해볼까요?
꼭 `Codable` 이여야하는지

2022-07-11 15:35 UTC, leejun6694 commented
> Decoding Error

오..! 저도 요런게 있는지 몰랐네요 @.@
음... 예제를 몇개 찾아봤는데, 직접 정의하는게 아닌 try-catch 에서 활용해보는건 어떨까요?
혹시 잘 안되시면 같이 해봐요~!

2022-07-12 06:02 UTC, finnn1 commented on OpenMarket/OpenMarket/Models/Products.swift
> +struct Page: Codable {
해당 타입들이 Decode 관련 기능만 사용하고 있어 Decoable 을 채택하도록 수정했습니다! ☺️

2022-07-12 06:03 UTC, finnn1 commented on OpenMarket/JsonParsingTests/JsonParsingTests.swift
> +        let parsedData = try! JSONDecoder().decode(Products.self, from: data)
앗 그러네요..! 😢
어떤 부분은 강제언래핑을 사용하고 어떤 부분은 옵셔널 바인딩을 사용하고 있어, 통일감이 없는 것 같아 gurad let으로 전부 변경해주었습니다 🙏

2022-07-12 06:05 UTC, finnn1 commented on OpenMarket/JsonParsingTests/JsonParsingTests.swift
> +              let data = try? Data(contentsOf: fileLocation) else { return }
return에 걸릴 경우 테스트가 통과되는 것을 확인했습니다..!
알고보니 json파일의 TargetMembership을 설정해주지 않아서 발생하는 문제였습니다 😢
해당 부분에서 XCTFail() 발생하도록 수정해주었습니다
감사합니다 🙏

2022-07-12 07:38 UTC, finnn1 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +            if let error = error {
에러 처리해주는 부분을 메서드로 분리해 보았습니다! ☺️

2022-07-12 08:18 UTC, finnn1 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +    func getData(pageNumber: Int, itemsPerPage: Int, completion: @escaping (Result<Products, Error>) -> Void) {
곰곰히 생각해본 결과 URL을 다른 메서드에서 재사용할 수 있을 것이란 생각이 들어 별도의 프로퍼티로 분리해주었습니다 ☺️

2022-07-12 16:23 UTC, leejun6694 approved these changes
빠르게 반영해주셔서 감사합니다 : )
몇가지 추가로 코멘트를 남겼는데, step 2 에서 확인해주시면 감사합니다!

2022-07-12 16:23 UTC, leejun6694 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +    func getData(pageNumber: Int, itemsPerPage: Int, completion: @escaping (Result<Products, Error>) -> Void) {
음.. 만약 다른 API 호출 method 를 만든다고 하면, 중복되는 코드들이 있을 것 같아요!
task 를 생성하는 곳이라던가, 에러를 처리하는 곳이라던가..!
변하는 것은 param 과 result, type 들일텐데 이런걸 제외하고 공통화를 할 수 있을지 고민해보시면 좋을 것 같습니다!

2022-07-12 16:23 UTC, leejun6694 commented on OpenMarket/JsonParsingTests/JsonParsingTests.swift
> +        guard let fileLocation = Bundle.main.url(forResource: "products", withExtension: "json"), let data = try? Data(contentsOf: fileLocation) else { XCTFail(); return }
세미콜론 없이 그냥 엔터해주는건 어떨까요...?

2022-07-12 16:23 UTC, leejun6694 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +                return URLSessionError.redirection
띄어쓰기..!

2022-07-12 16:23 UTC, leejun6694 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +        let decodingContext = DecodingError.Context.init(codingPath: Products.CodingKeys.allCases, debugDescription: "Can't response \(errorDebugDescription)")
제가 남긴 코멘트도 확인해보셨을까요!?

2022-07-12 16:23 UTC, leejun6694 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +            if let error = error {
error, urlError 확인이 분리되어있는데, 아예 이 부분도 method 를 따로 묶어주면 좋을 것 같습니다.
이후에 그 method 안에서 조개서 호출해도 될 것 같네요?ㅎㅎ

2022-07-12 16:23 UTC, merged

2022-07-13 04:50 UTC, finnn1 commented on OpenMarket/JsonParsingTests/JsonParsingTests.swift
> +        guard let fileLocation = Bundle.main.url(forResource: "products", withExtension: "json"), let data = try? Data(contentsOf: fileLocation) else { XCTFail(); return }
넵 해당 부분은 줄바꿈으로 처리해주었습니다 ☺️

2022-07-13 04:54 UTC, finnn1 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +                return URLSessionError.redirection
앗 그러네요! 말씀해주신 부분 띄어쓰기 컨벤션 맞춰서 수정했습니다 🙏