오픈마켓 I [STEP 1] 주디, 재재
yagom-academy/ios-open-market pull request #178
Opened 2022-07-12 13:40 UTC by ZZBAE

@protocorn93 콘 안녕하세요! 이번 오픈마켓 프로젝트를 진행하게 된 주디와 재재입니다.
step1-1과 1-2의 PR 보냅니다. 리뷰 잘 부탁드리겠습니다 🙇🏻‍♀️

# 🛍 오픈마켓 OPEN MARKET
> **프로젝트 기간** : 2022.07.11 월  ~ 2022.07.12 화 </br>**팀원** : 주디, 재재</br>**리뷰어** : 콘
---

## 💾 개발환경 및 라이브러리
[![swift](https://img.shields.io/badge/swift-5.6-orange)]()
[![xcode](https://img.shields.io/badge/Xcode-13.4.1-blue)]()
<br>

## 💡 Step 1-1, 1-2 수행 중 핵심경험
- [x] 파싱한 JSON 데이터와 매핑할 모델 설계
- [x] URL Session을 활용한 서버와의 통신
- [x] CodingKeys 프로토콜의 활용
- [x] 네트워크 상황과 무관한 네트워킹 데이터 타입의 단위 테스트(Unit Test)
<br>

## 🧑‍💻 전반적인 코드 설명

### **Model** 
#### 1) Product
> 상품 정보를 파싱할 구조체
- JSON 키 값을 스위프트의 네이밍에 맞게 변환하기 위해 `CodingKeys` 프로토콜의 활용

#### 2) **Page**
> 상품 리스트를 가진 페이지 정보를 파싱할 구조체
- JSON 키 값을 스위프트의 네이밍에 맞게 변환하기 위해 `CodingKeys` 프로토콜의 활용

#### 3) **Currency**
> 통화의 단위를 나타내는 열거형
- case: `krw = "KRW"`, `usd = "USD"`
<br>

### **Protocol**
#### 1) URLSessionProtocol
```swift
dataTask(with request: URLRequest, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTaskProtocol
```
- 위 메서드를 구현하도록 함
- `URLSession`과 `MockURLSession`에서 채택

#### 2) URLSessionDataTaskProtocol
- `resume()`을 구현하도록 함
- `URLSessionDataTask`와 `MockURLSessionDataTask`에서 채택
<br>

### **URLSession**
#### 1) **URLSessionProvider**
> 네트워킹에 사용할 세션을 제공하는 클래스
- `session` : 통신에 사용할 세션 프로퍼티 -> `URLSession` 또는 `MockURLSession`
- `baseURL` : api-host를 담은 프로퍼티
- `dataTask` : `session`의 `dataTask` 메서드를 통해 서버로 부터 데이터를 받아오는 메서드
- `receivePage` : `URLRequest`를 만들어 `dataTask`를 통해 상품 리스트를 받아오는 메서드

#### 2) **DataTaskError**
> 통신 과정에서 발생할 수 있는 에러를 정의한 열거형
- case: `incorrectResponseError`, `invalidDataError`

### **Mock**
#### 1) **MockURLSession**
> Mock 테스트를 위해 사용할 가짜 세션
- `isSuccess`: 인위적으로 결정할 통신 성공, 실패 여부 프로퍼티
- `dataTask` : 실제로 통신하지 않고 지정된 결과를 반환하는 메서드

#### 2) **MockURLSessionDataTask**
> URLSessionDataTaskProtocol에 있는 resume 함수 변경
- `newResume()`은 `resume()`의 실행을 하는 함수
<br>

## ⁉️ **고민 및 궁금한 점**
### 1. **URLSession 관련 로직 고민**
요구명세서에 나와있는 것처럼 실제 API 서버와 통신하지 않고, `MockData`를 사용하여 테스트를 하기 위해 `MockURLSession`을 생성하고, `URLSession`도 동일하게 protocol을 채택하고 extension 구현을 해주었습니다. 처음에는 `mockURLSession`을 굳이 구현해주지 않고 어차피 나중에 사용할 (실제 서버와 소통을 하는) `URLSession`을 활용해주려고 했는데, 그러면 step 1의 명세대로 구현을 하기가 어려울 것 같아 따로 `mockURLSession`을 생성해주었습니다.<br>
그리고 `URLSessionProvider` 생성 후 `URLSessionProvider`에 있는 `dataTask` 메서드를 구현해준 뒤 `MockURLSession`에서 그 메서드를 가로채와서 상세구현 후 `MockData`로 UnitTest를 진행하는 방식으로 전반적인 step 1 의 방향을 잡았습니다.<br>

### 2. **Mock 테스트를 한 방법**
UnitTest는 서버와 소통을 하지 않는 `MockURLSession`으로 진행했습니다. `MockURLSession` 내부의 `dataTask`는 실제 서버 통신을 하지 않고 `isSuccess`프로퍼티를 통해 임의로 지정한 성공-실패 여부에 따라 `HTTPURLResponse`를 보내도록 했습니다. 성공 시 **MockData**를 반환하고, 실패 시 400번대 응답코드를 반환하도록 했습니다.<br>
UnitTest에서는`receivePage` 메서드를 통해 서버요청이 성공한 경우에는 받아온 **jsonData**가 이미 가지고 있는 **mockData**와 같은지, 서버요청이 실패한 경우에는 에러를 반환하는지를 테스트하는 함수를 만들어주었습니다. 혹시 추가로 할 수 있는 테스트는 어떤 종류가 있을지, 아니면 더 이상 테스트를 하지 않아도 되는지 콘의 의견이 궁금합니다.

### 3. **URLSessionDataTask deprecated warning 해결**
밑의 사진처럼 `URLSessionDataTask`에서 deprecated warning이 떴는데, 코드 빌드에는 문제가 되지 않았지만 애플에서 지양하도록 권장하는 경고이기 때문에 해결을 하고 싶었습니다.

![](https://i.imgur.com/iRiU811.png)

>    1. `URLSessionDataTask`를 상속받으면서 생기는 에러니까 상속 대신에 `URLSessionDatatTaskProtocol`을 만들고 conform하면?
>    2. `MockURLSessionDataTask`를 `URLSessionDataTask`의 상속이 아니라 `URLSessionDatatTaskProtocol`을 채택하도록 변경
>    3. `resume` 앞에 override 키워드 제거
>    4. `URLSessionProtocol`의 `dataTask` 함수에서 `URLSessionDataTask`를 반환한 부분을 `URLSessionDataTaskProtocol`을 반환하도록 변경
>    5. `URLSession`에는 `URLSessionDataTaskProtocol`을 반환하는 기본 메서드가 없어서 `URLSession`안에서 해당 함수를 선언해주고, 이 안에서는 `dataTask(with:completionHandler:)`함수 호출

<br> 이런 흐름의 생각을 반영하여 `URLSessionDatatTaskProtocol`을 생성한 후 `URLSessionDataTask`과 `MockURLSessionDataTask`이 protocol을 conform하게끔 만들어주었습니다.
<br>

## ⌨️ 커밋 규칙
* feat    : 기능 추가 (새로운 기능)
* fix      : 버그 수정
* refactor : 리팩토링 (네이밍 수정 등)
* style   : 스타일 (코드 형식, 세미콜론 추가: 비즈니스 로직에 변경 없음)
* docs    : 문서 변경 (문서 추가, 수정, 삭제)
* test    : 테스트 (테스트 코드 추가, 수정, 삭제: 비즈니스 로직에 변경 없음)
* chore   : 기타 변경사항 (빌드 스크립트 수정 등)

## 💻 코드 컨벤션
Swift Statements 형식 준수

2022-07-13 12:45 UTC, protocorn93 requested changes
두 분 모두 너무 잘 구현해주셨어요! 👍

특히 `URLSessionProtocol`로 추상화해주신 것 너무너무 잘해주셨어요! 실제 현업에서도 이런 방식으로 만힝 구현해주고 있어요. 그리고 이건 단순 네트워크 객체 뿐만 아니라 이후 나올 수 있는 다른 객체들에도 적용해보실 수 있으시면 좋을 것 같아요 👍

보통 해주신 방법대로 테스트를 진행하고 있어요! 🙌 

코멘트 남겨놓았고 확인 부탁드릴게요!

2022-07-13 12:45 UTC, protocorn93 commented on OpenMarket/OpenMarket/Models/Page.swift
> +struct Page: Codable {
`Codable`을 채택하신 이유가 있을까요? `Decodable`만 채택해도 될 것 같은데 말이죠🤔

2022-07-13 12:45 UTC, protocorn93 commented on OpenMarket/OpenMarket/Models/Currency.swift
> +}
`Currency`도 별도 모델로 분리하시기로 결정한 이유가 궁금하네요

2022-07-13 12:45 UTC, protocorn93 commented on OpenMarket/OpenMarket/Models/Extension.swift
> +    func dataTask(with request: URLRequest, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTaskProtocol {
먼저 `URLSessionProtocol`로 추상화를 시도하신 점 너무너무너무 훌륭해요! 👏👏👏

`URLSessionDataTask`를 반환하는 기본 메서드를 프로토콜 메소드로 정의해도 괜찮지 않을까요? 
`URLSessionDataTaskProtocol`은 필요없을 것 같아요! [이 글](https://wodylikeios.notion.site/URLSession-Unit-Test-7a57917280b84a92b5a644adfac6246c)을 참고해보시면 좋을 것 같아요

2022-07-13 12:45 UTC, protocorn93 commented on OpenMarket/OpenMarket/Models/MockURLSession.swift
> +class MockURLSession: URLSessionProtocol {
`MockURLSession`은 상속을 해도 무방할까요? 그게 아니라면 `final` 키워드를 습관적으로 붙여주시는걸 권장해요!

2022-07-13 12:45 UTC, protocorn93 commented on OpenMarket/OpenMarket/Models/URLSessionProvider.swift
> +    case invalidDataError
에러 케이스이기에 뒤에 `-Error`는 안붙여도 괜찮을 것 같아요~ 근데 이건 취향 차이라고 생각도 드네요!

2022-07-13 12:45 UTC, protocorn93 commented on OpenMarket/OpenMarket/Models/URLSessionProvider.swift
> +class URLSessionProvider {
이 객체의 역할이 네이밍 때문인지 모호하게 느껴져요. 

1. URLSessionProtocol을 사용해서 Product 리스트를 받아오는 목적으로 가져가갈지, 
2. 데이터 타입은 제네릭하고 페이징을 위한 객체로 가져갈지.

그에 따라 네이밍도 변경이 필요해보여요. 

1번이라면 `ProductListProvider`로 가져가고 각 메서드에서 `Data`를 반환하는게 아니라 `[Product]`를 반환하던지
2번이라면 `baseURL`도 외부에서 받고 페이징을 위한 객체로 가져가던지 하는게 좋을 것 같앙

2022-07-13 12:45 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductDecoder.swift
> +}
전역 함수로 존재하는건 지양하는게 좋아요. 이 친구도 URLSessionProtocol로 잘 만들어주신 것처럼 추상화된 객체로 만들어보시는게 좋을 것 같아요.

2022-07-13 12:45 UTC, protocorn93 commented on OpenMarket/MockURLSessionTests/MockURLSessionTests.swift
> +class MockURLSessionTests: XCTestCase {
sut을 보면 이 테스트는 `URLSessionProviderTests`가 되어야 할 것 같네요.

2022-07-13 12:45 UTC, protocorn93 commented on OpenMarket/OpenMarket/Models/MockURLSession.swift
> +class MockURLSession: URLSessionProtocol {
Mock 관련 객체는 Unit Test 타겟에 위치시켜주세요~

2022-07-13 12:45 UTC, protocorn93 commented on OpenMarket/OpenMarket/Models/URLSessionProvider.swift
> +        task.resume()
별도 변수로 빼지 않고 바로 `resume`을 호출해주면 좀 다 깔끔해질 수 있을 것 같아요.

2022-07-13 13:08 UTC, ZZBAE commented on OpenMarket/OpenMarket/Models/Page.swift
> +struct Page: Codable {
지금 스텝에서는 `Decodable`만 채택해도 되는걸로 알고 있지만, 다음 스텝에서는 인코딩까지 필요할 것 같다고 생각이 들어 `Codable`을 채택해보았습니다. 저희가 생각한 이유가 맞을까 의문이긴 합니다.🥲 `Decodable`로 변경하는게 좋을까요?

2022-07-13 13:08 UTC, ZZBAE commented on OpenMarket/OpenMarket/Models/Currency.swift
> +}
요구사항에 있는 서버 API 문서에 `currency` 타입이 string이 아닌 enum으로 되어있어서 `Currency`를 별도 모델로 분리했었습니다. string 타입으로 빼도 괜찮을까요?
<br>
<img width="677" alt="스크린샷 2022-07-13 오후 10 04 47" src="https://user-images.githubusercontent.com/98302604/178740329-cd967944-042e-4cf1-a0ec-18b58ca162a3.png">

2022-07-13 13:08 UTC, ZZBAE commented on OpenMarket/OpenMarket/Models/URLSessionProvider.swift
> +        task.resume()
task 변수로 빼놓은 부분을 변경해주고 resume을 바로 호출해주었습니다! 훨씬 깜끔해진 것 같아요. 감사합니다 😁

2022-07-13 13:14 UTC, ZZBAE commented on OpenMarket/OpenMarket/Models/MockURLSession.swift
> +class MockURLSession: URLSessionProtocol {
콘의 말씀대로 상속을 해도 무방하기 때문에 `final`키워드를 붙여주었습니다.
그리고 Mock관련 객체를 Unit Test 타겟에 위치시켜달라고 해주신 말씀이 정확하게 이해가 되지 않아서 MockURLSessionTest 파일 안으로 옮겨보았습니다. 저희가 이해한 방향이 맞을까요?

2022-07-13 13:20 UTC, Judy-999 commented on OpenMarket/OpenMarket/Models/URLSessionProvider.swift
> +    case invalidDataError
명확하게 에러임을 표현하고자 `Error`를 붙여줬는데 어차피 에러 케이스라 의미가 중복되는 느낌이라 제거했습니다!

2022-07-13 15:27 UTC, ZZBAE commented on OpenMarket/OpenMarket/Models/Extension.swift
> +    func dataTask(with request: URLRequest, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTaskProtocol {
`URLSessionDataTask`를 반환했을 때 생겼던 deprecated warning을 수정하려고 `URLSessionDataTaskProtocol` 프로토콜을 만들어주었습니다. 참고글을 읽고 더 공부하겠습니다!

2022-07-13 15:30 UTC, Judy-999 commented on OpenMarket/OpenMarket/Models/URLSessionProvider.swift
> +class URLSessionProvider {
이후에 상품 상세 정보도 받아와야 해서 2번 방식으로 하기로 했습니다!
변경하다보니 콘이 생각하셨던 의미가 맞는지  몇가지 궁금한 점이 생겼습니다.
 
1. 이후에도 받아올 서버는 변하지 않기 때문에 api-host인 `BaseURL`은 외부에서 받지 않고 실제로 요청하는 `receivePage` 메서드에서 나머지 **url**을 파라미터로 받아서 원하는 데이터를 선택해서 받을 수 있도록 했는데 맞는 방식일까요?

2. `URLSessionProvider`의 네이밍이 모호하다고 하셔서 여러 데이터를 서버에서 받아올 수 있게 도와준다는 의미로 `URLSessionManager`로 변경했는데, 혹시 2번에서는 변경할 필요 없이 `URLSessionProvider`를 그대로 사용해도 괜찮은거였을까요?

2022-07-13 15:31 UTC, Judy-999 commented on OpenMarket/MockURLSessionTests/MockURLSessionTests.swift
> +class MockURLSessionTests: XCTestCase {
`URLSessionManagerTest`로 변경하고 기존에 있던 `URLSessionTests` 역시 같은 맥락이라 하나의 테스트로 합쳤습니다!

2022-07-14 09:27 UTC, Judy-999 commented on OpenMarket/OpenMarket/ProductDecoder.swift
> +}
`DataDecoder`라는 **Struct**의 메서드로 넣어서 사용하도록 했습니다.
이 방법이 콘이 설명해주신 추상화된 객체로 만들라는 의미가 맞을까요..?

2022-07-14 10:04 UTC, protocorn93 commented on OpenMarket/OpenMarket/ProductDecoder.swift
> +}
네네 맞아요. 이렇게 파싱까지 별도 객체로 가져갈 수도 있고, 네트워크 객체를 의존성으로 갖는 레포지토리 객체가 내부적으로 파싱까지 담당할 수도 있어요! 

이번엔 이런 방식으로 한번 가보시죠!

2022-07-14 10:05 UTC, protocorn93 commented on OpenMarket/OpenMarket/Models/URLSessionProvider.swift
> +class URLSessionProvider {
네네~ 맞아요. 코드를 보았을 때 해당 객체의 역할이 모호했는데, 이렇게 되면 좀 더 명확해지기 때문에 현재 네이밍도 괜찮을 것 같아요.

2022-07-14 10:06 UTC, protocorn93 commented on OpenMarket/OpenMarket/Models/MockURLSession.swift
> +class MockURLSession: URLSessionProtocol {
현재는 MockURLSession이라는 테스트를 위한 객체가 앱 타겟에 존재하는데요. 보통 이런 Mock 객체는 Unit Test 타겟에 위치시키곤해요! 코드 레벨보단 프로젝트 레벨에서 말씀드린거였어요~!

2022-07-14 10:07 UTC, protocorn93 commented on OpenMarket/OpenMarket/Models/Currency.swift
> +}
네네~ 잘해주셨어요! enum으로 결정한 이유를 듣고싶었던거였어요! ㅎㅎ

2022-07-14 10:09 UTC, protocorn93 commented on OpenMarket/OpenMarket/Models/Page.swift
> +struct Page: Codable {
네네 이후 스탭에서 Codable로 바꾸는 것이 좋을 것 같아요. 물론 지금이야 다음 스탭의 명세를 알 수 있으나 실제 프로젝트를 진행하다보면 미래에 어떻게 변할지 모르기 때문에 오버엔지니어링을 유의해야해요. 미래에 쓰일꺼야, 라는 생각으로 이것저것 추가하다보면 오히려 나중에 유지보수나 코드를 이해하는데 어려움이 생길 수 있어요! (확장성과는 조금 다른 맥락이에요!)

물론 Decodable, Encodable, Codable이 오버엔지니어링이라고 말할 것 까지는 당연히 아니에요! 하지만 이런 부분도 염두해서 개발해보시면 좋을 것 같아요!

2022-07-14 10:52 UTC, merged