오픈마켓 [STEP 1] 키위, 휴
yagom-academy/ios-open-market pull request #180
Opened 2022-07-13 02:20 UTC by Hugh-github

@jryoun1 
안녕하세요 제이크 오픈마켓 STEP 1 리뷰 잘 부탁드립니다 ☺️

## 구현한 기능
#### `ItmeList`, `Page` 
+ 서버에서 받아오는 JSON 파일과 매칭할 데이터 모델
#### `OpenMarketURLSession` 
+ `getMethod`를 통해 서버에 있는 데이터를 조회하는 로직 구현
#### `RequestType` 
+ http Request Method를 정의하는 타입
#### `URLSessionProtocol` 
+ 의존성 주입 및 Mock test를 위해 생성한 프로토콜
#### `MockURLSessionDataTask` : 
+ `URLSessionDataTask` 상속받아 `resume()` 재정의
#### `MockURLSession` 
+ `OperMarketURLSession`에 주입하기 위해 `URLSessionProtocol` 채택

## 배운개념📚

1. MockData를 이용한 Network Unit Test 하기 
2. URL Session
3. @esacping closure

## 고민한점🤔
1. dataTask 과정에서 에러가 발생하면 어떻게 에러를 처리해야 하는지 고민했습니다. dataTask 메서드에 존재하는 escaping closure 같은 경우 throws 키워드가 존재하지 않아 에러를 던질 방법이 존재하지 않았습니다. 에러가 발생할 경우 해당 에러들을 처리해 주는 방법을 고민한 결과 Result 타입을 사용했습니다.

2. URLSession 내부에서 getMethod를 구현할 당시 파라미터를 클로저로 받은다음 escaping키워드 처리해야하는 이유에 대해서 고민을 하게 되었습니다. 알아본 결과 URLSession과 관련된 메서드들은 기본적으로 비동기 처리를 하고 있습니다. 그렇기 때문에 서버에서 받아온 data를 외부에서 사용하려면 data를 클로저의 파라미터로 받은 다음 @escaping 키워드를 사용하여 메서드가 종료된 후에 사용가능하게 만들어 주어야한다는 것을 알게 되었습니다.

## 궁금한점🧐
1. URLSession의 dataTask 메서드를 호출할때 아래의 사진 1번에서는 싱글톤을 통해서 호출하고 있으나, 사진 2번에서는 session이란 상수에 URLSession의 인스턴스를 생성하고 호출을 하고 있습니다. 코드를 실행하는데 있어 두가지 방법의 차이가 딱히 보이지 않는데 혹시 두 방법의 차이점을 알고 계신게 있다면 알려주시면 정말 감사하겠습니다!

- **사진 1**
![](https://i.imgur.com/3hhTGPS.png)
- **사진 2**
![](https://i.imgur.com/zjIdZly.png)

2. 서버가 존재하고 해당 서버에서 데이터를 가져올 수 있다면 네트워크와 무관한 테스틀 진행하는 이유에는 어떤게 있는지 궁금합니다. 실제 서버와 통시하여 테스트를 진행하면 속도가 느리지만 더 직관적으로 확인할 수 있다고 생각합니다.

2022-07-13 14:04 UTC, jryoun1 requested changes
@kiwi1023 @Hugh-github  
두 분 모두 step1 고생하셨습니다. 

너무 잘 구현해주셨습니다! 👍
특히 URLSessionProtocol로 추상화해주신 것은 정말 잘해주셨네요 💯 
현업에서도 테스트가 필요한 여러 객체들에 대해서 이런식으로 추상화를 시키고 mock 타입을 주입해서 테스트할 수 있도록 구현되고 있습니다. (앞으로 네트워크 객체 뿐만 아니라 다른 객체들에도 이런식으로 적용해보시면 좋을 것 같아요 🙏🏻)

이외에 몇 가지 코멘트 남겨놓았고 확인 부탁드립니다. 

### 궁금한 점에 대한 답변 
> 1. URLSession의 dataTask 메서드를 호출할때 아래의 사진 1번에서는 싱글톤을 통해서 호출하고 있으나, 사진 2번에서는 session이란 상수에 URLSession의 인스턴스를 생성하고 호출을 하고 있습니다. 코드를 실행하는데 있어 두 가지 방법의 차이가 딱히 보이지 않는데 혹시 두 방법의 차이점을 알고 계신게 있다면 알려주시면 정말 감사하겠습니다!

[URLSession의 configuration](https://developer.apple.com/documentation/foundation/urlsessionconfiguration)에 대해서 공부해보시면 두 개의 차이점에 대해서 발견하실 수 있을 것 같습니다. 
추가로 default인 싱글톤을 통해서 호출하는 dataTask는 configuration이 가능한지에 대해서도 알아보시면 좋을 것 같아요 🙏🏻

> 2. 서버가 존재하고 해당 서버에서 데이터를 가져올 수 있다면 네트워크와 무관한 테스틀 진행하는 이유에는 어떤게 있는지 궁금합니다. 실제 서버와 통시하여 테스트를 진행하면 속도가 느리지만 더 직관적으로 확인할 수 있다고 생각합니다.

지금 작성하시는 테스트의 목적은 response가 ItemList타입으로 데이터가 잘 decode 되었는지 확인하는 테스트라고 생각해주시면 될 것 같습니다. 
이는 2가지 과정이 포함된 것이라고 볼 수 있을 것 같네요. 

1. response가 서버로부터 잘 내려오는가 
2. 정상적으로 내려온 response를 decode해서 ItemList타입으로 잘 맵핑되는가

이때 1번의 경우에는 실제로 개발을 하다보면 아직 서버가 개발이 덜 된 상태에서도 클라이언트가 개발하는 경우도 있고, 클라이언트 개발자가 인터넷이 없는 환경에서도 코드를 작성할 수도 있습니다. 
서버의 개발이 끝날때까지 기다렸다가 클라이언트가 개발하면 바람직하겠지만 그렇지 않은 경우들이 많기도 하고, 또 서버에서 어떠한 문제가 생길지 모르니 네트워크 통신도 하나의 의존성이라고 생각해주시면 좋을 것 같습니다. 

따라서 네트워크라는 의존성을 배제하고나서 단순히 테스트를 하려는 목적인 2번을 달성하려면 mock데이터를 통해서 테스트를 할 수 있도록 코드를 작성하는 것이 중요합니다.

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/ItemListTest/ItemListTest.swift
> +//  ItemListTest.swift
ItemList를 테스트하는게 맞을까요? 🤔
구현하는 JSONDecoder+Extension의 코드가 제대로 동작되어서 파싱이 잘 되는지 테스트를 진행한 것 같습니다. 

현재 파일명은 명확하지 않은 것 같습니다.

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/ItemListTest/ItemListTest.swift
> +    var itemList: ItemList!
강제언래핑을 사용한 이유와 이를 다른 방법으로 표현하는 방법은 무엇이 있을까요? 🙋‍♂️

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/ItemListTest/ItemListTest.swift
> +        itemList = JSONDecoder.decodeJson(jsonName: "Products")
`setUpWithError()`는 오버라이드 된 함수인데, super를 호출하지 않아도 될까요? 🤔

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/ItemListTest/ItemListTest.swift
> +        // Put teardown code here. This method is called after the invocation of each test method in the class.
이 함수는 필요없는 함수인가요? 
불필요한 코드는 지워주세요 🙏🏻

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/ItemListTest/ItemListTest.swift
> +    }
성공하는 테스트 케이스만 존재하는데 실패하는 테스트케이스는 없어도 될까요? 🙋‍♂️

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +//  Created by Kiwi, Hugh.
이 프로젝트의 주인이 누구인지 변경해주셨군요 👏 좋습니다~

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/HTTP/OpenMarketURLSession.swift
> +class OpenMarketURLSession {
클래스 명이 명확하지 않은 것 같습니다. 
클래스 내부에 loadData, getMethod가 있는 것으로 봐서는 네트워킹 동작을 관리해주는 클래스인 것 같습니다.

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/HTTP/OpenMarketURLSession.swift
> +            self.session = session
들여쓰기가 맞지 않는 것 같네요.

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/HTTP/OpenMarketURLSession.swift
> +    func loadData(request: URLRequest, completion: @escaping (Result<Data?, ResponseError>) -> Void) {
이 함수는 외부에서 직접 호출될 일이 있을까요? 🤔

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/HTTP/OpenMarketURLSession.swift
> +                return completion(.failure(.defaultError))
이 경우에는 무슨 에러 일까요? 🤔 
에러의 네이밍이 defaultError인데 명확하지 않은 것 같습니다.

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/HTTP/OpenMarketURLSession.swift
> +            guard let safeData = data else {
이 경우 safeData보다는 result라고 네이밍을 주로 사용합니다.

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/HTTP/OpenMarketURLSession.swift
> +                return  completion(.failure(.dataError))
띄어쓰기가 두 번 있네요.

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/HTTP/OpenMarketURLSession.swift
> +    func getMethod(pageNumber: Int? = nil, itemsPerPage: Int? = nil, productId: Int? = nil, completion: @escaping (Result<Data?, ResponseError>) -> Void) {
getMethod는 지금 2개의 endPoint에 대해서 분기처리를 통해서 조회를 하는 메서드로 보입니다.
만약 get해야하는 endPoint가 늘어나게되면 함수의 크기가 점점 커질 것 같은데, endPoint에 따라서 메서드를 따로 분리하고 무엇을 요청하는 함수인지 네이밍을 명확하게 가져가는 것이 좋아보입니다.

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/HTTP/OpenMarketURLSession.swift
> +                  let url = URL(string: baseURL + "api/products?page_no=\(pageNumber)&items_per_page=\(itemsPerPage)") else { return }
뒤에 추가로 붙이 path도 직접 하드코딩이 아니라 어느 한 곳에 모아져 있으면 휴먼에러를 줄일 수 있을 것 같습니다. 🙏🏻

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/HTTP/RequestType.swift
> +enum RequestType {
HTTPMethod라는 네이밍은 어떤가요 🤔

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/HTTP/ResponseError.swift
> +enum ResponseError: Error {
Response에 대한 에러도 만들어주셨군요! 👏
프로젝트를 진행하면서 다른 에러가 발생할 가능성은 없을까요? 🤔
다른 에러가 발생할 수 있다면 네이밍의 변경이 필요해보입니다.

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/JSON/Page.swift
> +struct Page: Codable {
Decodable로만 채택해도 충분할 것 같은데 Codable을 채택하신 이유가 있을까요? 🙋‍♂️

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/JSON/JSONDecorder + Extension.swift
> +        let decoder = JSONDecoder()
파싱을 해주는 객체를 하나 따로 생성할 수도 있을 것 같은데 extension을 통해서 작성해주신 이유가 궁금합니다.

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/Mock/URLSessionProtocol.swift
> +protocol URLSessionProtocol {
`URLSessionProtocol`로 추상화를 시도하고 이를 바탕으로 의존성을 주입해서 테스트를 진행하신 부분은 아주 좋네요! 👏👏👏

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/Mock/MockURLSessionDataTask.swift
> +class MockURLSessionDataTask: URLSessionDataTask {
`MockURLSessionDataTask` 클래스는 상속될 일이 있을까요?
없다면 final 을 붙여주시는 것이 좋습니다! 
static dispatch, dynamic dispatch에 대해서 알아보시면 도움이 될 것 같아요 🙏🏻

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/Mock/MockURLSession.swift
> +class MockURLSession: URLSessionProtocol {
여기도 동일합니다! 상속될 일이 있을까요? 🙋‍♂️

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarketURLSessionTests/OpenMarketURLSessionTests.swift
> +        sut = .init(session: mockSession)
super를 호출하지 않아도 될까요?🤔

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarketURLSessionTests/OpenMarketURLSessionTests.swift
> +        // Put teardown code here. This method is called after the invocation of each test method in the class.
불필요한 코드는 지워주세요🙏🏻

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarketURLSessionTests/OpenMarketURLSessionTests.swift
> +                XCTAssertEqual(itemList?.pageNumber, response?.pageNumber)
이 테스트가 제대로 동작하고 있는지 궁금하네요. 🤔
현재 sut은 OpenMarketURLSession이고 이때 session을 주입해주지 않았기 때문에 URLSession.shared로 설정되어서 실제로 서버로 통신을 하고 있는 것 같습니다. 

step1에서는 실제로 서버와 테스트를 진행하는 것이 아니라 mock 데이터를 통해서 테스트를 진행해야합니다!
구현하신 mockSession을 사용부탁드립니다 🙏🏻

2022-07-13 14:04 UTC, jryoun1 commented on OpenMarket/OpenMarketURLSessionTests/OpenMarketURLSessionTests.swift
> +        let response: ItemList? = JSONDecoder.decodeJson(jsonData: MockData().data)
여기서 MockData()가 아닌 Products.json과 비교를 위해서 `MockURLSession`의 생성할 때 결과로 내려줄 mockData도 주입받을 수 있도록 수정하면 좋을 것 같습니다. 
```swift
if isRequestSuccess {
            sessionDataTask.resumeDidCall = {
            // 여기서 MockData가 아니라 test하고 싶은 mockData를 주입받아서 반환해줄 수 있도록 변경하면 좋을 것 같네요. 
                completionHandler(MockData().data, sucessResponse, nil) 
            }
        } else {
            sessionDataTask.resumeDidCall = {
                completionHandler(nil, failureResponse, nil)
            }
        }
```

2022-07-14 05:00 UTC, Hugh-github commented on OpenMarket/ItemListTest/ItemListTest.swift
> +//  ItemListTest.swift
JSONDecoderTest로 변경헀습니다!

2022-07-14 05:01 UTC, Hugh-github commented on OpenMarket/ItemListTest/ItemListTest.swift
> +        // Put teardown code here. This method is called after the invocation of each test method in the class.
해당 메서드를 제거해 주었습니다.

2022-07-14 05:01 UTC, Hugh-github commented on OpenMarket/OpenMarketURLSessionTests/OpenMarketURLSessionTests.swift
> +        // Put teardown code here. This method is called after the invocation of each test method in the class.
해당 메서드를 제거해 주었습니다.

2022-07-14 05:07 UTC, kiwi1023 commented on OpenMarket/ItemListTest/ItemListTest.swift
> +    var itemList: ItemList!
저희가 구현한 타입에 대한 테스트를 진행하는 것이기 때문에 옵셔널이 아님을 100% 확신할 수 있어서 암시적 추출 옵셔널을 사용했습니다!  다른 방법은 옵셔널로 선언한 다음 옵셔널 체이닝(?)을 이용한 테스트가 있지 않을까 합니다..ㅎ

2022-07-14 05:12 UTC, kiwi1023 commented on OpenMarket/ItemListTest/ItemListTest.swift
> +        itemList = JSONDecoder.decodeJson(jsonName: "Products")
호출해 주었습니다!!

2022-07-14 05:28 UTC, Hugh-github commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +//  Created by Kiwi, Hugh.
감사합니다!

2022-07-14 05:31 UTC, Hugh-github commented on OpenMarket/ItemListTest/ItemListTest.swift
> +    }
JOSN 파일명이 다를 때 정상적으로 nil을 반환하는지 확인하는 test를 추가해 주었습니다.

2022-07-14 05:33 UTC, kiwi1023 commented on OpenMarket/OpenMarket/Model/HTTP/OpenMarketURLSession.swift
> +class OpenMarketURLSession {
이름 변경해 주었습니다!

2022-07-14 05:41 UTC, Hugh-github commented on OpenMarket/OpenMarket/Model/HTTP/OpenMarketURLSession.swift
> +            self.session = session
수정해주었습니다 ☺️

2022-07-14 05:41 UTC, Hugh-github commented on OpenMarket/OpenMarket/Model/HTTP/OpenMarketURLSession.swift
> +    func loadData(request: URLRequest, completion: @escaping (Result<Data?, ResponseError>) -> Void) {
접근제어 수준을 private 설정해 주었습니다.

2022-07-14 05:42 UTC, Hugh-github commented on OpenMarket/OpenMarket/Model/HTTP/OpenMarketURLSession.swift
> +                return  completion(.failure(.dataError))
수정해 주었습니다

2022-07-14 05:43 UTC, Hugh-github commented on OpenMarket/OpenMarket/Model/Mock/MockURLSessionDataTask.swift
> +class MockURLSessionDataTask: URLSessionDataTask {
final 키워드 추가해 주었습니다

2022-07-14 05:43 UTC, Hugh-github commented on OpenMarket/OpenMarket/Model/Mock/MockURLSession.swift
> +class MockURLSession: URLSessionProtocol {
final 키워드 추가해 주었습니다

2022-07-14 05:44 UTC, Hugh-github commented on OpenMarket/OpenMarketURLSessionTests/OpenMarketURLSessionTests.swift
> +        sut = .init(session: mockSession)
super를 통해 상위 메서드를 호출해 주었습니다.

2022-07-14 05:48 UTC, Hugh-github commented on OpenMarket/OpenMarket/Model/Mock/URLSessionProtocol.swift
> +protocol URLSessionProtocol {
감사합니다!!!

2022-07-14 05:52 UTC, Hugh-github commented on OpenMarket/ItemListTest/ItemListTest.swift
> +        itemList = JSONDecoder.decodeJson(jsonName: "Products")
상위 메서드를 호출한다면 상위 메서드의 body에 작성된 코드를 가져와 사용하게 되는데 항상 super를 통해 상위 메서드를 호출해야 하는 걸까요? 
생성자 같은 경우 재정의를 하게 된다면 super.init을 통해 상위 클래스에 속성을 추가해 주는걸로 아는데 test에서도 안정성을 위해 상위 메서드를 호출해줘야 하는 걸까요?

2022-07-14 06:13 UTC, kiwi1023 commented on OpenMarket/OpenMarket/Model/HTTP/OpenMarketURLSession.swift
> +                return completion(.failure(.defaultError))
수정해주었습니다!

2022-07-14 06:13 UTC, kiwi1023 commented on OpenMarket/OpenMarket/Model/HTTP/OpenMarketURLSession.swift
> +            guard let safeData = data else {
수정해주었습니다!

2022-07-14 06:13 UTC, kiwi1023 commented on OpenMarket/OpenMarket/Model/HTTP/RequestType.swift
> +enum RequestType {
수정해주었습니다!

2022-07-14 07:13 UTC, Hugh-github commented on OpenMarket/OpenMarket/Model/HTTP/OpenMarketURLSession.swift
> +    func getMethod(pageNumber: Int? = nil, itemsPerPage: Int? = nil, productId: Int? = nil, completion: @escaping (Result<Data?, ResponseError>) -> Void) {
getMethod를 getItemList와 getProduct로 분리해 주었습니다.

2022-07-14 07:14 UTC, Hugh-github commented on OpenMarket/OpenMarket/Model/HTTP/OpenMarketURLSession.swift
> +                  let url = URL(string: baseURL + "api/products?page_no=\(pageNumber)&items_per_page=\(itemsPerPage)") else { return }
URLPath 타입을 만들어 path를 관리해 주었습니다.

2022-07-14 07:18 UTC, Hugh-github commented on OpenMarket/OpenMarket/Model/HTTP/ResponseError.swift
> +enum ResponseError: Error {
Response에 대한 에러만 관리해 주고 만약 다른 곳에서 발생하는 에러 같은 경우 별도의 타입을 만들어 관리해 주려고 합니다.
혹시 현업에서는 발생하는 모든 에러를 하나의 타입으로 만들어 관리해 주는지 궁금합니다.

2022-07-14 07:22 UTC, kiwi1023 commented on OpenMarket/OpenMarket/Model/JSON/Page.swift
> +struct Page: Codable {
추후 POST를 하게 될 때 Encoding 해줘야되는 경우가 존재 한다고 생각하여 Codable을 사용하였습니다! 

또한 Codable이 decodable과 encodable 두가지를 포함한 프로토콜로 알고 있습니다. 말씀해 주신 것처럼 Decodable로만 채택해도 충분할경우일지라도 어차피 두가지 모두가 포함된 Codable을 사용하는것이 성능에 커다란 영향을 끼치게 되는지 궁금합니다!

2022-07-14 07:22 UTC, Hugh-github commented on OpenMarket/OpenMarket/Model/JSON/JSONDecorder + Extension.swift
> +        let decoder = JSONDecoder()
제이크가 말씀해 주신 것처럼 객체를 생성하는 방법도 고민했습니다. 저희가 생각하기에는 extension을 통해 해당 메서드를 작성하는 것이 좀 더 가독성이 좋을 것 같다고 생각했습니다. 🤔

2022-07-14 07:45 UTC, Hugh-github commented on OpenMarket/OpenMarketURLSessionTests/OpenMarketURLSessionTests.swift
> +                XCTAssertEqual(itemList?.pageNumber, response?.pageNumber)
혹시 제이크가 말씀하시는 방법이 `func test_getMethod_실패()` 와 동일하게 session을 주입해야 한다는 건가요?
MockURLSession의 생성자 부분에서 isRequestSuccess가 true로 기본값이 설정되어 있기 때문에 따로 주입은 하지 않았습니다. setUpWithError에서 NetworkManager의 session은 MockURLSession으로 주입해주고 있습니다.

2022-07-14 07:47 UTC, Hugh-github commented on OpenMarket/OpenMarketURLSessionTests/OpenMarketURLSessionTests.swift
> +        let response: ItemList? = JSONDecoder.decodeJson(jsonData: MockData().data)
`let response: ItemList? = JSONDecoder.decodeJson(jsonName: "Products")` 테스트 코드를 이렇게 수정해 주었습니다.
혹시 좀 더 자세하게 설명 가능할까요? ㅠㅠ 😭

2022-07-14 07:51 UTC, Hugh-github commented on OpenMarket/OpenMarket/Model/HTTP/OpenMarketURLSession.swift
> +                  let url = URL(string: baseURL + "api/products?page_no=\(pageNumber)&items_per_page=\(itemsPerPage)") else { return }
URLQueryItem을 사용하면 path를 한곳에 모아 관리하는 것 같지 않아 별도의 타입을 만들었습니다.
혹시 제이크가 말씀하신 방식이 URLQueryItem을 사용하는 방식일까요?

2022-07-14 14:55 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/HTTP/ResponseError.swift
> +enum ResponseError: Error {
좋네요👍🏻 Networking과 관련된 에러를 따로 관리해주고, 앱을 사용하면서 발생할 수 있는 에러를 따로 관리해도 좋을 것 같습니다!

2022-07-14 14:59 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/JSON/Page.swift
> +struct Page: Codable {
> 추후 POST를 하게 될 때 Encoding 해줘야되는 경우가 존재 한다고 생각하여 Codable을 사용하였습니다!

다만 지금은 추후에 POST를 한다는 것을 예측할 수 있어서 Codable을 써도 괜찮을 것 같긴하지만, 가능하다면 현재 기획서에 필요한 정도로 구현을 해주시면 좋을 것 같네요! 성능적인 문제보다는 모든 타입을 Codable을 채택하도록 한다면, 기획서 없이 코드를 보는 사람은 이 타입이 encode 될 수도, decode 될 수도 있다고 판단할 수 밖에 없기 때문에 명시적으로 표현을 해주기 위해서 필요한 것만 채택하는 것이 좋아보입니다.

2022-07-14 15:04 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/JSON/JSONDecorder + Extension.swift
> +        let decoder = JSONDecoder()
두 분이 그렇게 생각하셨다면 좋네요 👍🏻 

extension을 통해서 메서드를 작성하게 되면 여러 곳에서 해당 함수를 사용할 수 있습니다. 
다만 viewController이 deinit 되지 않은 상태에서 계속해서 decode를 해야하는 일이 발생한다면, 예를 들어서 어떤 화면을 계속해서 reload한다고 했을 때 지금 extension의 구현에서는 JSONDecoder 객체를 매번 생성하게 됩니다. 

그러나 파싱을 해주는 객체를 하나 따로 생성했다면 해당 객체는 viewDidLoad 시점에 한 번만 생성되고, deinit 전까지는 계속해서 생성하지 않아도 되는 장점이 있을 수 있겠네요.

2022-07-14 15:08 UTC, jryoun1 commented on OpenMarket/OpenMarketURLSessionTests/OpenMarketURLSessionTests.swift
> +                XCTAssertEqual(itemList?.pageNumber, response?.pageNumber)
앗 이 부분 제가 breakpoint를 찍어보고 확인해보다가 제가 놓친 것 같네요 🙏🏻 미안합니다. 
말씀하신대로 setUpWithError에서 주입해주시는 것 확인했습니다.
다만 현재 구현에서도 아래 부분에 breakpoint를 찍어보시면 찍히지 않는 것을 확인하실 수 있을 겁니다.
그 이유는 비록 mock으로 작성했어도 현재 비동기로 테스트가 진행되기 때문에 결국 결과를 제대로 확인하고 테스트가 성공하지 못한 것입니다.
```swift
XCTAssertEqual(itemList?.pageNumber, response?.pageNumber)
XCTAssertEqual(itemList?.itemsPerPage, response?.itemsPerPage)
```

[비동기를 테스트하는 방법](https://developer.apple.com/documentation/xctest/asynchronous_tests_and_expectations)에 대해서 한 번 확인해보시고 수정해주시면 될 것 같습니다.

2022-07-14 15:37 UTC, jryoun1 commented on OpenMarket/OpenMarketURLSessionTests/OpenMarketURLSessionTests.swift
> +        let response: ItemList? = JSONDecoder.decodeJson(jsonData: MockData().data)
말씀드린 부분은 필수는 아니지만 이런식의 구현을 말씀드렸습니다. 
```swift
class MockURLSession: URLSessionProtocol {
    var isRequestSuccess: Bool
    var sessionDataTask: MockURLSessionDataTask?
    var mockData: Data

    init(isRequestSuccess: Bool = true, mockData: Data = Data()) {
        self.isRequestSuccess = isRequestSuccess
        self.mockData = mockData
    }
       ...
   if isRequestSuccess {
            sessionDataTask.resumeDidCall = {
                completionHandler(self.mockData, sucessResponse, nil)
            }
        }
   ...
  }
}


// 실제 mockSession을 초기화해주는 부분
let mock = load(fileName: "Products")
mockSession = .init(mockData: mock)

...
private func load(fileName: String) -> Data { } 
```

2022-07-14 15:43 UTC, jryoun1 reviewed
수정하신 부분 확인했습니다. 

달아주신 질문과 비동기 테스트 관련해서 코멘트 남겨두었습니다! 확인부탁드려요

2022-07-14 15:43 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/HTTP/URLPath.swift
> +enum URLPath: CustomStringConvertible {
URLPath 타입을 만들어주셨네요 👏

[URLComponents](https://developer.apple.com/documentation/foundation/urlcomponents)에 관해서도 나중에 한 번 보시면 좋을 것 같아요.

2022-07-14 15:43 UTC, jryoun1 commented on OpenMarket/OpenMarket.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 15.5;
test의 deployment target도 프로젝트의 deployment target version과 동일하게 맞춰주세요🙏🏻

2022-07-14 15:45 UTC, jryoun1 commented on OpenMarket/ItemListTest/ItemListTest.swift
> +        itemList = JSONDecoder.decodeJson(jsonName: "Products")
모든 케이스에서 항상 호출하지는 않아도 됩니다. 
다만 기존에 setUpWithError()의 상위메서드의 body에서 수행하는 역할을 수행하고, 
override된 함수의 body(테스트에서 사용할 객체들을 셋업하는 작업)를 진행할 수 있도록 super를 호출해주는 것이 바람직해보입니다.

2022-07-15 07:00 UTC, Hugh-github commented on OpenMarket/OpenMarketURLSessionTests/OpenMarketURLSessionTests.swift
> +        let response: ItemList? = JSONDecoder.decodeJson(jsonData: MockData().data)
데이터를 주입해 주었습니다.

2022-07-15 07:00 UTC, Hugh-github commented on OpenMarket/OpenMarket/Model/HTTP/URLPath.swift
> +enum URLPath: CustomStringConvertible {
감사합니다 !

2022-07-15 07:01 UTC, Hugh-github commented on OpenMarket/OpenMarketURLSessionTests/OpenMarketURLSessionTests.swift
> +                XCTAssertEqual(itemList?.pageNumber, response?.pageNumber)
`fullfill()` 과 wait을 이용해 비동기 테스트를 진행했습니다.

2022-07-15 07:10 UTC, Hugh-github commented on OpenMarket/OpenMarket.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 15.5;
test의 target도 13.2로 수정해 주었습니다

2022-07-15 13:27 UTC, jryoun1 approved these changes
고생하셨습니다!

코멘트 남겨두었습니다 🙂
해당 코멘트는 다음 스텝 진행하면서 반영해도 될 것 같아서 step1은 여기서 merge하겠습니다. 
step2도 화이팅입니다💪🏻

2022-07-15 13:27 UTC, jryoun1 commented on OpenMarket/OpenMarketURLSessionTests/NetworkManagerTests.swift
> +            promise.fulfill()
👏

2022-07-15 13:27 UTC, jryoun1 commented on OpenMarket/OpenMarketURLSessionTests/NetworkManagerTests.swift
> +                //resultPageNumber = itemList!.pageNumber
불필요한 주석은 제거해주세요!

2022-07-15 13:27 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/Mock/MockURLSession.swift
> +        let location = Bundle.main.url(forResource: "Products", withExtension: "json")
여기서 직접 Products를 매개변수로 지정해준다면 MockURLSession 객체는 Products 이외에 다른 Mock 데이터를 테스트할 때는 코드의 변경이 필요해보입니다!

파일명을 생성자에서 주입받거나 Data 타입 자체를 생성자에서 주입받는 방법으로 수정부탁드려요🙏🏻

2022-07-15 13:27 UTC, merged