오픈마켓 [STEP2] bonf, Finnn
yagom-academy/ios-open-market pull request #185
Opened 2022-07-20 06:53 UTC by finnn1

# 오픈 마켓 STEP2 PR 💸

---

안녕하세요! 쿠마(@leejun6694) Bonf, Finnn입니다 😊
오픈 마켓 Step 2 PR 보냅니다!
이번에도 잘 부탁드립니다! 🙏

---

### 구현 내용

|<center>**실행**</center>|<center>**List 하단 스크롤**</center>|<center>**List 새로고침**</center>|
|---|---|---|
|![](https://i.imgur.com/o7M5s8G.gif)|![](https://i.imgur.com/EImgRTh.gif)|![](https://i.imgur.com/cIH916P.gif)|
|<center>**Segment변경**</center>|<center>**Grid 하단 스크롤**</center>|<center>**Grid 새로고침**</center>|
|![](https://i.imgur.com/bpMr2XW.gif)|![](https://i.imgur.com/eCPsHGm.gif)|![](https://i.imgur.com/5ONbvQH.gif)|

---

### 궁금한 점 🤷🏻‍♂️
> **priceStackView :**
> `priceStackView` 내부에 있는 `itemPriceLabel`, `itemSaleLabel`의 `width`가 같아져서 할인된 가격의 `text`가 더 길 경우 공백이 생기는 문제가 발생하였습니다. `priceStackView`의 `alignment`와 `distribution`을 만져봤지만 해결되지 않는 이유가 궁금합니다. 

> **URLSession 데이터 전달 오류 :**
> `2022-07-20 13:37:44.974845+0900 OpenMarket[20858:611740] [boringssl] boringssl_metrics_log_metric_block_invoke(153) Failed to log metrics` URLSession을 이용하여 데이터를 받아오는 과정에서 다음과 같은 오류가 발생합니다. 어떤 오류인지 해결방법은 뭔지 파악하지 못하였습니다. 오류가 발생하는데도 불구하고 데이터는 문제없이 전달 되는데 어떤 오류인지 알고 싶습니다.

> **List를 만들때 Collection View를 사용할 경우 Separator :**
> 이번 프로젝트에서 `List`를 만들때 `Collection View`를 사용해서 진행했습니다. 다만, 컬렉션뷰로 리스트를 만들 경우 `Separator`에 대한 별도의 설정을 찾지 못해서, 우선은 `Separator`으로 사용할 `UIView`를 하나 만들어서 높이를 1로 설정한 후 셀 하단에 붙여놨는데, 정상적인 방법이 아니라는 생각이 들어 혹시 다른 방법은 없는지 궁금합니다 😢
> (`UICollectionLayoutListConfiguration(appearance:)`을 사용하면 `Separator`가 자동으로 생성이 되었지만, `GRID` 뷰로 전환 후 다시 `LIST` 뷰로 돌아올 때 `ContentView`가 높이를 잡지 못하는 문제때문에 사용하지 못했습니다.)

### 고민한 점 🤔
> **세그먼트 컨트롤 변경시 LIST와 GRID를 보여주는 방법 :**
> `STEP2`를 시작하면서 가장 큰 고민은 `LIST`와 `GRID`의 변경 방식이었습니다.
> 세그먼트가 변경될 때, 하나의 뷰에서 레이아웃을 변경해서 표현할지, 아니면 별도의 뷰를 따로 두어 보여줄지 고민을 했었습니다.
> 별도의 뷰를 만들 경우, 뷰가 변경될 때 마다 컬렉션뷰(테이블뷰)를 다시 업데이트 해줘야 한다는 점과, 사용하지 않는 데이터가 생길 수 있다고 생각을 하여 하나의 뷰에서 데이터를 모두 읽어온 후 레이아웃을 변경하는 방식으로 선택했습니다.

> **List와 Grid 변경시 셀 내부 레이아웃 :**
> 컬렉션 뷰의 레이아웃 같은 경우는 ViewController 에서 변경해주면 되지만, 셀 내부의 레이아웃 같은 경우는 변경되지 않았습니다.
> Cell 내부에서 StackView의 axis 및 레이아웃을 변경해줄 수 있는 메서드를 정의해서 해결했습니다.

2022-07-21 16:50 UTC, leejun6694 requested changes
bonf, Finnn 안녕하세요~!
coding convention, naming 등의 기본적인 부분과 좀 더 생각했으면 하는 코드에 코멘트를 남겼습니다.
확인 부탁드려요 : )

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Extension/String+Extension.swift
> +        attributeString.addAttribute(NSAttributedString.Key.strikethroughStyle, value: NSUnderlineStyle.single.rawValue, range: NSMakeRange(0, attributeString.length))
코드가 한줄 내에서 길어지는 경우, 줄바꿈을 해주면 좀 더 정리된 모습을 볼 수 있습니다~!

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Extension/String+Extension.swift
> +import UIKit
(한번 생각만 해보세요~!)

`import UIKit` 을 하는 이유가 `NSUnderlineStyle` 값을 사용하기 때문으로 보입니다.

이 케이스는 아니지만, 때론 MVC 중 model 에서도 UIKit 을 import 해야할 때가 있습니다.
하지만, model 에서 view 관련 framework 을 import 하는게 어색해보일 수 있습니다. (저는 지양하는 편입니다.)
최소한의 view 관련 코드를 선언하는 방법을 검색해볼까요?
그리고 import UIKit 과는 어떤 차이가 있을지도 공부해보면 좋을 것 같습니다~!

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Extension/UISegmentControl+Extension.swift
> +    func selectedConfiguration(color: UIColor = UIColor.red) {
method 의 이름엔 행위를 나타내는 동사가 있으면 좋을 것 같습니다~!
(selected 가 동사라면,, 넘어가주세요!)

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +    func getData<T: Decodable>(pageNumber: Int, itemsPerPage: Int, completion: @escaping (T) -> Void) {
👍👍👍

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +    private func isData(_ data: Data?, _ response: URLResponse?, _ error: Error?) throws -> Data {
저는 네이밍이 살짝 어색해보입니다..!
**is**Data, **need**Data, **should**Select 등과 같은 가능성의 이름은 Bool 타입을 위해 많이 사용합니다~! 참고 부탁드려요

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Models/Titles.swift
> +    case LIST
대문자...? 로 구현한 이유가 있을까요?
요건 보편적인 코딩 컨벤션을 따라주시면 감사하겠습니다!

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
>  class ViewController: UIViewController {
너무 일반적인 이름입니다.
목적의 맞는 이름으로 수정 부탁드려요 : )

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +
불필요한 줄바꿈이 있습니다.

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +// MARK: - Functions
extension 마다 어떤 method 들이 모여있는지를 `MARK` 로 표현해주면 어떨까요?
예) UI (Layout), Action, Delegate ...

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +    private var isFetchingEnd = true
이 값 관련해서는 discord 로 같이 얘기 나누면 좋을 것 같습니다.
코드만으로는 제가 잘 이해를 못했네요~!

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +    private let productsDataManager = ProductsDataManager()
보통 API 통신을 위한 `Network 구현체`는 인스턴스화하지 않습니다.
관련된 정보를 한번 찾아볼까요?

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +        productsDataManager.getData(pageNumber: currentPage + 1, itemsPerPage: 20) { (result: Products) in
`) { result in`
으로 사용해도 됩니다~!

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +            self.currentPage = result.pageNo
products 와 result 가 혼용되고 있습니다.
하나로 정리해주면 더 좋을 것 같네요.

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +        segmentControl?.addTarget(self, action: #selector(changeLayout), for: .valueChanged)
이렇게 많이 쓰는거면.. `guard` 로 꺼내주는게 어떨까요?
물음표 살인마 느낌이에요....

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +        let width = self.view.frame.width
`self.` 를 생략한 곳도 있고, 생략하지 않은 곳도 있습니다.
하나의 스타일로 통일 부탁드려요.

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +
줄바꿈 되어있네요!?

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +            if isFetchingEnd {
if 를 위와 합칠 수 있습니다~!

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Views/ItemCollectionViewCell.swift
> +    private let stackView: UIStackView = {
요것도 이름을 좀 더 명확하게 지어줄까요?

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Views/ItemCollectionViewCell.swift
> +    private let separator: UIView = {
`separatorView` 는 어떨까요?>

2022-07-21 16:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Views/ItemCollectionViewCell.swift
> +
줄바꿈!

2022-07-21 17:01 UTC, leejun6694 commented
> priceStackView

`fillEqually` 로 설정되어 있어서 아닐까요? 혹시 제가 잘못 이해했다면, discord 에서 같이 확인해봐요~!

> URLSession

https://developer.apple.com/forums/thread/697026
요 내용을 참고해볼까요?? 다른 점이 있다면 요것도 discord 에서 얘기해봐요~

> List를 만들때 Collection View를 사용할 경우 Separator :

TableView 를 사용하지 않은 이유도 궁금하네요...?

2022-07-23 09:59 UTC, finnn1 commented on OpenMarket/OpenMarket/Extension/String+Extension.swift
> +        attributeString.addAttribute(NSAttributedString.Key.strikethroughStyle, value: NSUnderlineStyle.single.rawValue, range: NSMakeRange(0, attributeString.length))
해당 메서드 파라미터 단위로 줄바꿈해서 정리되도록 했습니다 ☺️

2022-07-23 10:04 UTC, finnn1 commented on OpenMarket/OpenMarket/Extension/UISegmentControl+Extension.swift
> +    func selectedConfiguration(color: UIColor = UIColor.red) {
메서드 이름 앞에 동사를 붙여주어 행위를 나타낼 수 있도록 수정했습니다! ☺️
감사합니다 🙏

2022-07-23 10:04 UTC, finnn1 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +    func getData<T: Decodable>(pageNumber: Int, itemsPerPage: Int, completion: @escaping (T) -> Void) {
🙏🙏🙏

2022-07-23 10:07 UTC, finnn1 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +    private func isData(_ data: Data?, _ response: URLResponse?, _ error: Error?) throws -> Data {
아하! 그렇군요! 해당 메서드 이름은 checkValidData로 변경해주었습니다 ☺️ 감사합니다

2022-07-23 10:13 UTC, finnn1 commented on OpenMarket/OpenMarket/Models/Titles.swift
> +    case LIST
케이스명을 소문자로 변경해주었습니다. ☺️
감사합니다 🙏

2022-07-23 10:15 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
>  class ViewController: UIViewController {
해당 뷰컨트롤러의 이름은 ProductsViewController로 변경해주었습니다 👍

2022-07-23 10:17 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +
`MARK` 상단에 두 줄씩 띄어줬던 것인데, 생각해보니 불필요한 줄바꿈인 것 같아서 모두 한 줄로 변경해주었습니다. ☺️

2022-07-23 10:27 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +// MARK: - Functions
extension 마다 어떤 Method 들이 모여있는지 `MARK로 표시해주었습니다!
감사합니다 🙏

2022-07-23 10:33 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +            self.currentPage = result.pageNo
result를 products로 통일했습니다! ☺️🙏

2022-07-23 10:36 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +        segmentControl?.addTarget(self, action: #selector(changeLayout), for: .valueChanged)
그러고보니 물음표가 너무 많네요 🥲
guard let 옵셔널 바인딩으로 꺼내주었습니다!

2022-07-23 10:37 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +        let width = self.view.frame.width
`self.` 를 전부 넣어주는 것으로 컨벤션 통일했습니다 ☺️

2022-07-23 10:47 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +
줄바꿈 제거했습니다 🙏

2022-07-23 10:48 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +            if isFetchingEnd {
`&&` 연산자를 사용해서 하나로 합쳐주었습니다 👍

2022-07-23 10:49 UTC, finnn1 commented on OpenMarket/OpenMarket/Views/ItemCollectionViewCell.swift
> +    private let stackView: UIStackView = {
`productStackView`로 명확하게 변경해주었습니다 🙏

2022-07-23 10:49 UTC, finnn1 commented on OpenMarket/OpenMarket/Views/ItemCollectionViewCell.swift
> +    private let separator: UIView = {
앗 그 이름이 더욱 명확하고 좋은 것 같네요! 변경해주었습니다 ☺️
감사합니다 🙏🙏

2022-07-23 10:49 UTC, finnn1 commented on OpenMarket/OpenMarket/Views/ItemCollectionViewCell.swift
> +
줄바꿈 없애주었습니다 ☺️

2022-07-24 16:26 UTC, leejun6694 approved these changes
오픈마켓 프로젝트 기간 동안 고생 많으셨습니다 : )

2022-07-24 16:26 UTC, merged