오픈마켓 [STEP 2] 데릭, 수꿍, 케이
yagom-academy/ios-open-market pull request #187
Opened 2022-07-20 08:49 UTC by derrickkim0109

안녕하세요 제이슨! @ehgud0670
STEP02 PR 올립니다.! 
궁금한 사항들은 아래에 남겨 두었습니다!
잘 부탁드립니다!

## 📝 기능설명
    
### 네트워크 통신을 담당할 타입을 설계하고 구현
    - ProductList, Product
        - 서버 API 데이터 형식을 고려하여 모델 타입 구현
    - NetworkProvider
        - 서버로부터 데이터를 받아오는 기능을 수행
        - 기능을 수행한 위한 protocol, extension 별도 생성
    - NetworkError
        - 서버로부터 데이터를 받아오는 도중 발생하는 에러 표현

### CollectionView Cell을 각 Layout 별로 분리하여 구현 
    - GridCollectionCell, ListCollectionCell
        - CollectionView의 Cell 타입 구현 
    - ProductEntity
        - 서버 매핑 타입 중 Cell에 필요한 타입들 별도 구현
    
### Utilities 
    - String+Extensions
        - String 자료형을 확장시켜 필요 메서드 관리
            * strikeThrough - 해당 문자열의 처음부터 입력 받은 수의 인덱스까지 strikethroughStyle 적용.
    - Int+Extensions
        - Int 자료형을 확장시켜 필요 메서드 관리
            * numberFormatter - 10진수로 변환하고 String 타입으로 변환 후 반환

## 🚀 TroubleShooting
    
### STEP 2

#### T1. AutoLayout
    
- 하나의 Cell을 통하여 List에서 Grid로의 AutoLayout을 설정하기 위해 이전에 설정된 List Layout의 Constraints을 제거한 후, Grid의 Constraints를 설정하려 하였으나, 이미 Cell이 생성된 이후에 Constraint를 제거하기 위한 시도를 하기 때문에 오토레이아웃이 정상적으로 설정되지 않는 문제가 발생되었습니다. 이에 notification 등을 통해 알림을 바탕으로 해결할 수 있을까도 고민해보았으나, 해당 방법은 오히려 과하다고 판단하여, 위의 문제를 해결하기 위하여 list, grid 레이아웃을 위한 각각의 셀을 만든 다음, 서로 다른 오토레이아웃을 적용해 문제를 해결하였습니다.

#### T2. Server Mapping Model - Entity - ViewModel
    
- 서버로부터 데이터를 요청하여, 이에 대한 응답을 받은 다음, 이를 JSON 데이터 형식으로 변환하여, 해당 데이터를 저장하고, 관리되어야 하는 데이터의 집합을 만들 필요성을 느꼈습니다. 이에, 서버로부터 데이터를 요청하는 부분은 NetworkProvider 인스턴스를 생성하여 URL을 입력받아 requestAndDecode 메서드를 실행하였습니다. 다음으로, 응답을 받은 다음, 이를 JSON 데이터 형식으로 변환하는 부분은 서버로부터의 응답을 바탕으로 성공, 실패 케이스를 분기하여, 서버로부터 성공적으로 응답을 받을시, STEP1에서 구현한 서버 매핑 모델인 ProductList 구조체에 담은 다음, 실제 필요한 데이터를 추출하여 저장 및 관리하기 위해 ProductEntity 구조체를 생성하여 이를 처리하였습니다. 위의 방법들을 통하여 '서버 매핑 모델 - Entity - ViewModel'의 구조를 구현하고자 하였습니다.

## Questions & Answers

#### Q1. 한개의 Cell을 사용하여 두개의 CollectionLayout 생성시 발생하는 오토레이아웃 문제 
    

**기존 CollectionViewCell**
- 먼저 초기 화면이 구성이 되면, 컬렉션 뷰의 레이아웃을 ListLayout으로 설정하였습니다. 
- 하나의 CellRegistration 만을 바탕으로, Semented Control을 통해 ListLayout와 GridLayout를 전환하는 방식을 사용하였습니다.
    - segemented Control 전환시 List와 Grid 뷰의 axis를 변경해 주었습니다. 
    - 기본 Custom Cell은 UICollectionViewListCell을 채택한 UI입니다.
        - List의 accessory 설정을 활용하기 위해서 사용하였습니다.
    
**문제점**
- ListLayout을 위해 Cell 안의 UI 요소인 imageView의 width와 height의 Constraint를 설정해 두었습니다. 하지만 Grid Layout 화면으로의 전환시 이전에 설정한 Constraint가 그대로 남아 있어 Autolayout이 정상적으로 실행되지 않아 에러가 발생하였습니다. 
    
**시도한점**
- ListLayout 구현 과정에서 설정된 Constraint가 Grid Layout 화면으로의 전환시에 필요하지 않다면 제거하는 방법을 생각하였습니다. Segmented Control을 클릭시`collectionView.visibleCells.forEach` 코드를 통하여 forEach문 안에서 Constraint를 제거하려고 하였으나 Cell이 생성된 후에 Constraint를 제거하고자 하여 imageView에 설정된 constraint을 제거할 수 없었습니다.

**해결한점** 
- List와 Grid를 위한 View를 각각 두개로 만들어서 따로 Autolayout를 처리할 수 있도록 하였습니다. 

**궁금한점**
- Segmented Control을 클릭시에 Constraint를 다르게 적용하여 Auto-layout이 안전하게 처리될 방법이 있을까요?
- 똑같은 UIElement를 사용하는데 하나의 Cell로 Layout을 처리하는 것은 비효율적인 것일까요?
    
```swift
   @objc func segmentedValueChanged(_ sender:UISegmentedControl!) {
        let items = sender.selectedSegmentIndex
        
        switch items {
        case 0 :
            collectionView.setCollectionViewLayout(createListLayout(), animated: true)
            collectionView.visibleCells.forEach { cell in
                guard let cell = cell as? CustomCollectionViewCell else {
                    return
                }
            
                cell.contentView.layer.borderColor = .none
                cell.contentView.layer.borderWidth = 0
                cell.accessories = [.disclosureIndicator()]

                cell.configureStackView(of: .horizontal, textAlignment: .left)
            }
        case 1:
            collectionView.setCollectionViewLayout(createGridLayout(), animated: true)
            collectionView.visibleCells.forEach { cell in
                guard let cell = cell as? CustomCollectionViewCell else {
                    return
                }
                
                isSelected = true
                cell.accessories = [.delete()]
                cell.contentView.layer.borderColor = UIColor.black.cgColor
                cell.contentView.layer.borderWidth = 1
                
                cell.configureStackView(of: .vertical, textAlignment: .center)
            }
            
            collectionView.scrollToItem(at: IndexPath(item: -1, section: 0), at: .init(rawValue: 0), animated: false)
        default:
            break
        }
    }
    
    private func createListLayout() -> UICollectionViewLayout {
        let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0), heightDimension: .fractionalHeight(1.0))
        let item = NSCollectionLayoutItem(layoutSize: itemSize)
        let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0), heightDimension: .fractionalWidth(0.2))
        let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize, subitem: item, count: 1)
        let section = NSCollectionLayoutSection(group: group)
        let layout = UICollectionViewCompositionalLayout(section: section)
        
        return layout
    }
    
    private func createGridLayout() -> UICollectionViewLayout {
        let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0), heightDimension: .fractionalHeight(1.0))
        let item = NSCollectionLayoutItem(layoutSize: itemSize)
        item.contentInsets = .init(top: 4, leading: 8, bottom: 4, trailing: 8)
        let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0), heightDimension: .fractionalWidth(0.8))
        let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize, subitem: item, count: 2)
        let section = NSCollectionLayoutSection(group: group)
        
        let layout = UICollectionViewCompositionalLayout(section: section)
        return layout
    }
```

#### Q2. ListConfiguration이 아닐 때 separator 생성 방법
    
- list 형식의 CollectionView를 생성하는 가운데, list layout을 구성하는 방법은 listConfiguration을 통하여 간단하게 생성하는 방법 1과 compositional layout의 기본적인 형태로 item, group, section을 각각 설정하여, layout에 section을 넣어주어 이를 반환하는 방법 2가 있습니다.
    
- 코드
```swift
// 방법 1
private func createListLayout() -> UICollectionViewLayout {
    let config = UICollectionLayoutListConfiguration(appearance: .plain)
    
    return UICollectionViewCompositionalLayout.list(using: config)
}

// 방법 2
func createListLayout() -> UICollectionViewLayout {
    let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0), heightDimension: .fractionalHeight(1.0))
    let item = NSCollectionLayoutItem(layoutSize: itemSize)
    let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0), heightDimension: .fractionalWidth(0.2))
    let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize, subitem: item, count: 1)
    let section = NSCollectionLayoutSection(group: group)
    let layout = UICollectionViewCompositionalLayout(section: section)
    
    return layout
}
```
    
- 이에 따라, 셀을 등록하는 방법에 있어서 listConfiguration을 사용한 방법1의 경우에는 UICollectionViewListCell을 사용하였습니다. 방법2에서는 커스텀 셀인 ListCollectionCell을 사용하여 직접 cell 내 UI들의 오토레이아웃을 잡아주어야 했습니다. 저희는 방법 2에 따라 진행하였는데, 방법 1인listConfiguration의 경우에는 셀 간의 구분선을 separatorLayoutGuide을 통하여 설정해줄 수 있는데, 방법 2의 경우에는 구분선을 그려주기 위한 메서드를 찾지 못하였습니다. 혹시 제이슨께서 이를 해결하는 방법을 알고 있으신지 질문드리고 싶습니다!

```swift
// 방법 1
private func configureListDataSource() {
    let cellRegistration = UICollectionView.CellRegistration<UICollectionViewListCell, ProductEntity> { (cell, indexPath, item) in
        var content = cell.defaultContentConfiguration()
        
        content.image = item.thumbnailImage
        content.text = item.name
        content.secondaryText = String(item.originalPrice)
        content.imageProperties.maximumSize = CGSize(width: 60, height: 60)
        cell.contentConfiguration = content
        
        cell.separatorLayoutGuide.leadingAnchor.constraint(equalTo: self.view.leadingAnchor, constant: 10).isActive = true
        
        cell.accessories = [.disclosureIndicator [...]

2022-07-21 13:12 UTC, ehgud0670 commented
### Q3. 페이지 수에 따른 ListConfiguration cell과 custom cell의 오토레이아웃 에러 발생 유무

이 부분은 따로 제가 코드와 에러를 직접 봐야 알 수 있을 것 같은데 따로 브랜치 파서 보여주실수 있을까요?
현재는 customcell로만 구현되어있어서요~

2022-07-22 04:30 UTC, ehgud0670 commented
### Q1. 한개의 Cell을 사용하여 두개의 CollectionLayout 생성시 발생하는 오토레이아웃 문제

이것도 브랜치 따로 만들어서 보여주세요.

2022-07-22 05:31 UTC, ehgud0670 commented
Q3. 페이지 수에 따른 ListConfiguration cell과 custom cell의 오토레이아웃 에러 발생 유무

[what the fuck autolayout](https://www.wtfautolayout.com/) 페이지에서 아래 경고글을 복붙해서 확인해보세용 ㅎㅎ
(
    "<NSLayoutConstraint:0x600001c0cb40 UIImageView:0x13859f0b0.height == 60   (active)>",
    "<NSLayoutConstraint:0x600001c0dc70 V:|-(0)-[UIStackView:0x13859ed90]   (active, names: '|':UIView:0x1385a1210 )>",
    "<NSLayoutConstraint:0x600001c0dcc0 UIStackView:0x13859ed90.bottom == UIView:0x1385a1210.bottom   (active)>",
    "<NSLayoutConstraint:0x600001c0ee90 'UISV-canvas-connection' UIStackView:0x13859ed90.top == _UILayoutSpacer:0x600000064780'UISV-alignment-spanner'.top   (active)>",
    "<NSLayoutConstraint:0x600001c0ef30 'UISV-canvas-connection' UIStackView:0x13859ed90.centerY == UIImageView:0x13859f0b0.centerY   (active)>",
    "<NSLayoutConstraint:0x600001c0ec60 'UISV-spanning-boundary' _UILayoutSpacer:0x600000064780'UISV-alignment-spanner'.top <= UIImageView:0x13859f0b0.top   (active)>",
    "<NSLayoutConstraint:0x600001c30050 'UIView-Encapsulated-Layout-Height' UIView:0x1385a1210.height == 44   (active)>"
)

이유는 UICollectionLayoutListConfiguration의 plain은 height가 44로 설정되어있는데 CollectionListViewCell의 productImageView는 60이고 똑같이 cell의 height 도 60인것과 충돌해서 오토레이아웃 버그가 발생한 것 입니다. 
반면 ContentView는 설정값이 따로 존재하지 않아 경고가 출력이 되지 않는 것이고요~

2022-07-22 07:15 UTC, ehgud0670 commented
### Q1. 한개의 Cell을 사용하여 두개의 CollectionLayout 생성시 발생하는 오토레이아웃 문제

https://github.com/Jeon-Minsu/ios-open-market/commit/44bcdcdbb51091f7cf014be5cc42a2e8029da49b#r79135318

질문 1번은 위 커밋에 코멘트 드렸습니다.

2022-07-22 07:19 UTC, ehgud0670 commented
### Q2. ListConfiguration이 아닐 때 separator 생성 방법

1) CustomCell의 경우엔 SeparatorView가 따로 존재하지 않습니다. 따라서 uiview 로 만들어주셔야 해요. 그리고 디자이너가 디자인한 구분선은 ListConfiguration cell의 separtor처럼 생기지 않을 수 있기 때문에 따로 만들어주는 것이 더 좋을 때도 있다는 점 참고차 말씀드립니다! 
2) 두번째 방법은 CollectionViewFlowLayout을 쓰는 방법입니다.
link: https://stackoverflow.com/a/28691409 
아래 swift 코드도 있으니 참고하시면 좋을 거 같아요 :)

2022-07-22 08:41 UTC, ehgud0670 requested changes
고생하셨습니다 ㅎㅎ 
리뷰는 거의 다했고 뷰쪽 잘 구현하셨는지 살펴보고 필요하면 리뷰 드릴게요
그럼 피드백 반영 부탁드리고 모르는거나 의문가는 점 있으시면 말씀 주세요!

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/View/CustomCollectionViewCell.swift
> +class CustomCollectionViewCell: UICollectionViewCell {
이 파일은 이제 필요없으니 없애도 되겠어요 ㅎㅎ

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/View/GridCollectionCell.swift
> +        fatalError("not implemnted")
이것도 같이 super.init 으로 해두면 좋아요. 
나중에 인터페이스 빌더(xib, storyboard)로 구현이라도 한다면 크래시가 안 나게 조치를 취해줘야 합니다.

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/View/GridCollectionCell.swift
> +extension GridCollectionCell {
제가 볼때 configureGridCell이나 updateUI 정도는 이 클래스의 기본 메소드 같아 extension으로 너무 잘게 쪼갠거 아닌가 싶어요~
보통 특정 기능 관련 메소드를 모아놓으려고 extension으로 나누거나 프로토콜을 채택할때 extension으로 나눕니다. 
지금은 이 셀의 디폴트 메소드인데 잘게 나눈 감이 있습니다.

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/View/GridCollectionCell.swift
> +        originalPriceLabel.text = data.currency + " " + data.originalPrice.numberFormatter()
```suggestion
        originalPriceLabel.text = viewModel.originalPriceText
```

뷰모델을 만들어 뷰모델을 넘기면 이런식으로 바로 할당 가능합니다. 뷰모델은 프레젠터(Presenter)로서의 역할을 합니다.
이 방법의 좋은 점은 
1) 뷰의 할당되는 값이 잘 나오는지 뷰모델의 메소드나 연산프로퍼티를 테스트하면 되므로 즉 뷰와의 의존성이 없으므로 테스트하기 쉽습니다.
2) 기획이 바뀌어서 originalPriceLabel.text의 값을 바꾸려 할 때 viewModel의 메소드(`originalPriceText`)만 바꾸면 된다. 
즉 여기 예시처럼 여러 커스텀 뷰에서의 코드를 일일이 바꾸지 않아도 되는 장점이 있습니다.

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/View/GridCollectionCell.swift
> +        }
```suggestion
        iviewModel.isDiscountedItem == true ?  self.configureForBargain() : self.configureForOriginal()
```
이런식으로 로직을 분리하는게 유지보수에 좋습니다. 보기에도 좋고요. (예를 든거지 참고만 하십시오 ㅎㅎ)
뷰모델이나 모델에 메소드를 추가해보려고 노력해보세요. 
뷰는 최대한 멍청해야 하고 뷰모델, 모델이 로직을 담당해야 하는 말이 있습니다. 

> 뷰는 최대한 멍청해야 한다는 말 
뷰는 화면에 보이게 하는 로직, 유저와 인터렉션이 있을때 뷰컨에 알려야 하는 로직 등 뷰로서의 역할만 하는 코드가 있어야 하고 비즈니스 로직은 뷰모델쪽에 위치해야 합니다. 그래야 유지보수 하기 좋아요.

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +    private var productsModel: [ProductEntity] = []
아까 말씀드린대로 productsModel을 가지고 있는 상위 모델을 만드세요.

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +        let url = "https://market-training.yagom-academy.kr/api/products?page_no=1&items_per_page=50"
이런 endpoint는 따로 상수로 모아두는 것이 좋습니다.

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +        let openMarket = NetworkProvider(session: URLSession.shared)
그냥 networkProvider 라고 하는게 낫겠습니다. 
그리고 이런 객체는 매번 생성시키는 것 보단 그냥 뷰컨의 멤버 프로퍼티로 갖는게 좋아요. 한 화면에서 여러번의 api 요청을 할때도 하나의 객체로만 하는게 관리하기 좋습니다.

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +        openMarket.requestAndDecode(url: url, dataType: ProductList.self) { result in
[weak self] 캡쳐리스트에 대해 알아보세요. 왜 해야하는지도 알아보시구요.

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +                }
아까 말씀드린대로 이건 상위 모델(or 뷰모델)을 옵저빙하다가 모델의 변화가 있을때 뷰를 업데이트 하는 구조가 맞을 듯 합니다.
아래처럼 로직이 분리가 되어야 해요.
* 모델 값이 업데이트 됨 -> (notification or rx or combine) -> viewController - > view update
* 뷰(뷰컨)에서 사용자의 인터렉션 발생 -> (delegate or ibaction or rxcocoa) -> viewController -> model update

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +        self.present(alertController, animated: false)
현재 이 메소드에서 런타임 에러 발생합니다. 이런것도 일일이 테스트 해보어야 합니다.

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +    func setNavigationItems() {
아시다시피 set이라고 하는것보다 setup이 낫습니다.

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +    }
```suggestion
    @objc func addTapped() {
         #warning("추후 구현 예정입니다") 
    }
```
=> 이렇게 표시해주는 것이 좋습니다.

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +        ])
결국 만들고 설정하므로 create 보단 configure가 더 적절할듯 해요. 그리고 해당 함수는 viewDidLoad에 미리 호출해주는 것이 좋아요. 해당 뷰는 서버로부터 응답을 받든 안받든 원래 있어야 하는 뷰니까요

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +        }
여기도 viewDidLoad에서 미리 세팅해주는게 낫지 않을까요? 
서버 리스폰스 받으면 적용해야 할 건 applySnapShot 밖에 없을 것 같아요.

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +private extension MarketProductsViewController {
* private extension 은 유틸 성격의 객체를 특정 파일에서만 쓸때 적용하는 것이고 보통 나눌때는 extension + private func 조합이 나을 듯 합니다. 
* 여기도 extension으로 너무 나눠놨네요. 보통 최소한으로 viewDidLoad에서 호출되는 메소드는 extension으로 나누지 않는 것 같아요.

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +        let url = "https://market-training.yagom-academy.kr/api/products?page_no=1&items_per_page=50"
그리고 baseURL과 query 부분으로 나누세요. Request 객체를 만드셔도 좋고요.

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +                    let item = ProductEntity(thumbnailImage: product.thumbnailImage!, name: product.name, currency: product.currency, originalPrice: product.price, discountedPrice: product.bargainPri
```suggestion
                    let item = ProductEntity(
                       thumbnailImage: product.thumbnailImage!, 
                       name: product.name, 
                       currency: product.currency, 
                       originalPrice: product.price, 
                       discountedPrice: product.bargainPrice, 
                       stock: product.stock
                    )
```
너무 길면 띄워써주는 게 훨씬 좋아요. 여러 스타일 가이드를 참고해보세요~

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +                    let item = ProductEntity(thumbnailImage: product.thumbnailImage!, name: product.name, currency: product.currency, originalPrice: product.price, discountedPrice: product.bargainPri
image 그것도 서버로부터 받은 이미지를 forced unwrapping 하면 크래시 많이 나고 사용자 경험이 급격히 떨어집니다.
고치고 앱 제출하는데 시간도 매우 오래걸려요 
uiimage는 옵셔널 타입이어도 uimageview.image 에 할당가능하니 옵셔널타입 그대로 entity에 넘기시는게 나을듯 합니다.

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +    private var shouldHideListView: Bool? {
이 Bool값은 디폴트값을 미리 두면 옵셔널이 필요가 없을 것 같아요. 항상 있어야 하는 값으로 보여져서요.

2022-07-22 08:41 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +    private var gridDataSource: UICollectionViewDiffableDataSource<Section, ProductEntity>!
collectionView는 미리 생성시키면 옵셔널 타입일 필요가 없고 
dataSource도 lazy를 쓰면 미리 생성시켜서 옵셔널 타입일 필요가 없고 lazy가 별로다 싶으시면 `?` 을 쓰는 게 좋습니다. 
지금처럼 viewDidLoad에도 생성시키지 않고 서버 response올 때 생성시키는 객체들을 
forced unwrapping 으로 선언하면 크래시에 매우 치명적이다는 점 참고 부탁드려요!

2022-07-22 09:48 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +        openMarket.requestAndDecode(url: url, dataType: ProductList.self) { result in
지금은 weak self 로 안해도 메모리 누수가 나지 않습니다. 
다만 추후에 코드가 추가가 되면 충분히 메모리 누수가 날 수 있는 상황이 나올 수 있으니 
weak self 를 두시는 습관을 드리면 좋을 듯 합니다 🙂

2022-07-23 05:24 UTC, Jeon-Minsu commented on OpenMarket/OpenMarket/Application/Presentation/View/GridCollectionCell.swift
> +        fatalError("not implemnted")
이번 프로젝트에서는 코드 기반으로 UI를 구성할 것이기 때문에 인터페이스를 고려해보지 않으려고 합니다. 이에, 인터페이스 빌더 초기화 구문을 @available 키워드를 사용하여 블럭 처리를 시도해보았습니다.

2022-07-23 11:00 UTC, Jeon-Minsu commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +        self.present(alertController, animated: false)
현재 확인해보았으나 정상적으로 출력되는 것 같습니다! 혹시 어떻게 진행하였을때 문제가 발생하였는지 다시 여쭈어봐도 될까요?

2022-07-23 11:16 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/ViewController/MarketProductsViewController.swift
> +        self.present(alertController, animated: false)
해당 팝업을 메인스레드가 아닌 백그라운드 스래에서 띄웠을 때 현재 크래시 발생합니다!
즉 서버 요청 후 fail 뜰 때요.

2022-07-24 06:27 UTC, Jeon-Minsu commented
안녕하세요 제이슨!! 주말까지 공부하여 현재 STEP2 리팩토링을 완료해보았습니다!
아직도 부족한 점이 많지만 열심히 노력하여 수정해보았습니다!
rx 및 combine은 다음 스텝에서 적용해보겠습니다! 
이번에도 잘 부탁드립니다! 🙇‍♂️🙇‍♂️

2022-07-24 06:45 UTC, ehgud0670 commented on OpenMarket/OpenMarket/Application/Presentation/View/MarketProducts/MarketProductsView.swift
> +final class MarketProductsView: UIView {
뷰가 거의 뷰 컨트롤러가 될 정도로 비대해졌네요. 이렇게 구현하신이유가 있을까요~?

2022-07-25 03:21 UTC, merged