오픈마켓 [STEP 2] 휴, 키위
yagom-academy/ios-open-market pull request #188
Opened 2022-07-21 16:18 UTC by Hugh-github

@jryoun1
안녕하세요 제이크 늦었지만 STEP 2 리뷰 잘 부탁드립니다!! ☺️
PR이 늦어져 궁금한 점 위주로 작성했습니다.
고민한 점, 문제 해결 방법은 README에 추가하겠습니다.

### 기능 구현
`MainViewController`
+ CompositionalLayout을 이용해 CollectionView 구현
+ loadingView 구현
+ Segment를 이용한 CollectionView Layout 전환

`ListCollectionViewCell`
+ ListCollectionView에서 사용할 Custom Cell

`GridCollectionViewCell`
+ GridCollectionView에서 사용할 Custom Cell

### 고민한 점
+ Cell 재사용
+ Auto Layout
+ Segment를 이용한 CollectionView Layout 전환 

### 궁금한 점
+ [해당 문서](https://stackoverflow.com/questions/40773208/what-is-the-correct-way-to-use-prepareforreuse) 를 보면 cell에서 사용하는 content에 대해서는 prepareForReuse에서 초기화를 해주면 안 된다고 나와있습니다. 제이크는 Cell에 사용하는 Content를 초기화할 때 어떤 방식으로 하는지 궁금합니다.

+ GridCollection에 대한 layout을 설정할 때 groupSize의 높이를 저희가 설정한 높이보다 줄이게 되면 안에 있는 content들이 겹치는 현상이 발생했습니다. 이러한 경우 cell에 대한 layout을 수정해 group의 사이즈가 변해도 안에 있는 content들이 겹치는 현상이 발생하지 않도록 해야 하는지 궁금합니다.

+ configure 메서드를 통해 View에 대한 세부 설정을 해주었습니다. 하지만 configure 메서드가 너무 뚱뚱해져 가독성이 떨어진다고 생각하는데 어떤 방식으로 코드를 작성하는 것이 좋은지 궁금합니다.

+  groupSize에 따른 Cell 사라짐 현상
![](https://i.imgur.com/NJkn400.png)
- 사진2
![](https://i.imgur.com/RhfxR8f.png)
- 사진3
![](https://i.imgur.com/ErIgjHw.png)

위의 사진1과 같이 groupSize의 heightDimension을 .fractionHeight(0.09)로 설정하였을 경우에는 구동이 아무 문제 없이 잘 되고 있으나, 

위의 사진2와 같이 groupSize의 heightDimension을 .fractionHeight(0.1)로(아마도 0.1~0.3정도까지) 설정하게 되면,

사진3과 같이 중간의 데이터가 표현되지 않고 빈셀로 나오게 되는데 이를 swift의 버그로 봐야 하는건지 아니면 저희의 코드에 문제가 있는건지 궁금합니다!

2022-07-23 06:52 UTC, jryoun1 requested changes
@Hugh-github @kiwi1023 
step2 고생하셨습니다.

전반적으로 잘 작성해주셔서 코드 읽기가 편했습니다. 👍🏻 💯
다만 몇 가지 오류들이 있어서 코멘트와 아래에 남겨드립니다.

추가로 `UICollectionViewCompositionalLayout`을 사용해서 구현을 하셨는데, `UICollectionViewFlowLayout`을 사용하지 않은 이유가 있을까요? 🙋‍♂️ 선택하신 이유가 궁금합니다. 

### 오류 🚨
1. collectionView가 2개 → 이 부분은 아래 코멘트에 남겨져 있습니다.
2. navigationBar를 통과해서 상품들이 보여지고 있습니다.
<img width="250" height="300" alt="image" src="https://user-images.githubusercontent.com/45090197/180593209-6ff06caf-3ab6-47d4-b98c-cd688649f009.png">

3. layout issue 
상품명과 잔여수량의 layout이 모호하다고 나오고 있습니다.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/45090197/180593259-1582faea-6339-4198-80e1-e1722d25aca8.png">
 
### 궁금한점에 대한 답변
> [해당 문서](https://stackoverflow.com/questions/40773208/what-is-the-correct-way-to-use-prepareforreuse) 를 보면 cell에서 사용하는 content에 대해서는 prepareForReuse에서 초기화를 해주면 안 된다고 나와있습니다. 

음.. 일단 apple문서에서는 performance issues를 피하기 위해서는 attributes에 대한 것만 초기화하라고 하는데, 저는 지금까지 prepareForReuse에서 content에 대한 부분들도 초기화를 진행해주었습니다만 퍼포먼스상 문제는 없었던 것 같습니다 🤔

해당 문서에 나온 것을 바탕으로 content에 관련된 내용을 초기화해주려면, cellForRowAt에서 진행해주는 것이 바람직해보이긴 합니다. 물론 이 부분도 cell 내부에 resetAttributes()라는 함수를 만들고 cell.resetAttributes()를 호출해주면 될 것 같아보이네요. 

> GridCollection에 대한 layout을 설정할 때 groupSize의 높이를 저희가 설정한 높이보다 줄이게 되면 안에 있는 content들이 겹치는 현상이 발생했습니다. 이러한 경우 cell에 대한 layout을 수정해 group의 사이즈가 변해도 안에 있는 content들이 겹치는 현상이 발생하지 않도록 해야 하는지 궁금합니다.

말씀해주신 문제의 원인은 fractionHeight의 경우에는 전체 기기를 0~1 사이로 보고 값을 결정해주게 되는데, 이때 0.3으로 설정하시게되면 화면에 3개의 cell이 보여질 정도의 height를 가지게 됩니다. 그리고 cell에서 layout을 잡아주신 것은 3개 정도가 보여질 정도의 높이를 가졌을 때를 가정하고 잡았기 때문에 0.2로 변경하게 되면 당연히 cell의 내용이 잘릴 수 밖에 없습니다. 
이러한 부분을 해결하기 위해서는 heightDimension을 estimated로 설정하거나, 고정된 Height를 주는 방법이 있을 것 같네요. 
만약 cell 내부의 크기가 동적으로 변경되어야한다면 [이 글](https://corykim0829.github.io/ios/UICollectionViewCell-dynamic-height/)을 참고해보시면 도움이 될 것 같네요. 다만 현재 프로젝트에서는 동적으로 cell의 크기가 변경되는 것 같지는 않아보입니다!

> configure 메서드를 통해 View에 대한 세부 설정을 해주었습니다. 하지만 configure 메서드가 너무 뚱뚱해져 가독성이 떨어진다고 생각하는데 어떤 방식으로 코드를 작성하는 것이 좋은지 궁금합니다.

코멘트 남겨드렸습니다 🙏🏻

> groupSize에 따른 Cell 사라짐 현상

지금 listLayout에서 하나의 group을 하나의 아이템이라고 봐야하기 때문에 group을 아래와 같이 수정해주면 정상적으로 동작하네요 
```swift
        let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
                                              heightDimension: .fractionalHeight(1.0))
        let item = NSCollectionLayoutItem(layoutSize: itemSize)
        
        let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
                                               heightDimension: .fractionalHeight(0.1))
        let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize, subitem: item, count: 1)
```

2022-07-23 06:52 UTC, jryoun1 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +class MainViewController: UIViewController {
MainViewController가 상속될 일이 없다면 final을 붙어주세요 🙏🏻

2022-07-23 06:52 UTC, jryoun1 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        sleep(10)
sleep을 사용한 이유가 궁금합니다 🙋‍♂️

2022-07-23 06:52 UTC, jryoun1 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        self.navigationItem.titleView = segment
이 부분은 configureSegment 내부에 들어가도 될 것 같네요

2022-07-23 06:52 UTC, jryoun1 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        segment.setTitleTextAttributes([.foregroundColor : UIColor.systemBlue], for: .normal)
`[.foregroundColor : UIColor.white]` : 왼쪽은 붙여주세요

2022-07-23 06:52 UTC, jryoun1 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        self.navigationItem.titleView = segment
self를 사용하시는 기준이 있을까요? 🙋‍♂️

2022-07-23 06:52 UTC, jryoun1 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        manager.getItemList(pageNumber: 1, itemsPerPage: 100) { [self] result in
다음 페이지를 보고 싶은 경우에는 어떻게 하면 될까요? 
Pagination(paging)이 필요해보입니다.

2022-07-23 06:52 UTC, jryoun1 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        view.addSubview(collectionView)
collectionView를 하나 사용하고 두 개의 dataSource를 변경해주는 식으로 구현을 의도하신 것 같은데,
configureListHierarchy() 내부에서도 collectionView를 addSubview해줬는데 여기서도 중복으로 해주고 있는 것 같습니다. 

그래서 viewHierarchy를 보면 collectionView가 2개가 보이고 있습니다. 
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/45090197/180592679-77148585-4744-45f2-a73c-c4cf78f86010.png">

2022-07-23 06:52 UTC, jryoun1 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
cell의 프로퍼티를 여기서 접근하는 방법보다는 cell에 item 객체를 넘겨주어서 이러한 부분들을 설정하도록 분리시켜주세요.
e.g.
```swift
cell.configure(with: item)

// GridCollectionViewCell 내부
configure(item: Item) { // } 
```

2022-07-23 06:52 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/JSON/Page.swift
> +struct Page: Codable, Hashable {
이 모델이 Page 정보를 나타내고 있나요? 
아이템의 정보를 가지고 있는걸로 보입니다!

2022-07-23 06:52 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/JSON/Page.swift
> +struct Page: Codable, Hashable {
Hashable을 채택해주셨네요 👏 
Hashable은 어떤 프로토콜일까요? 채택해주신 이유는 뭘까요? 🙋‍♂️

2022-07-23 06:52 UTC, jryoun1 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
여기도 동일합니다.
cell에 item 객체를 넘겨주어서 위의 부분들을 설정하도록 분리시켜주세요.

2022-07-23 06:52 UTC, jryoun1 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +class GridCollectionViewCell: UICollectionViewCell {
상속될 일이 없다면 final 키워드를 붙여주세요!

2022-07-23 06:52 UTC, jryoun1 commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +class ListCollectionViewCell: UICollectionViewCell {
동일합니다!

2022-07-23 06:52 UTC, jryoun1 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +    private func configure() {
무엇을 configure하는지 함수명만 보고는 알 수가 없습니다.
아래 함수는 각 UIComponent들의 attributes를 configure하기도하고, layout적인 요소들도 configure해주고 있는데 이러한 부분을 분리시켜주세요. 🙏🏻

configureAttributes()
configureLayout()

2022-07-23 06:52 UTC, jryoun1 commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +    private func configureHorizontalStackView() {
함수명은 HorizontalStackView를 설정하는데 내부에는 다른 property들도 설정해주고 있네요.
이부분도 위에서 말씀드렸던 것과 같이 layout, attributes를 설정하는 함수로 분리해주세요 🙏🏻

2022-07-23 06:52 UTC, jryoun1 commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +    private let horizontalStackView = UIStackView()
개인적으로 attributes의 경우에는 아래와 같이 선언할 때 설정해주는 것을 선호합니다. 

```swift
    private lazy var verticalStackView: UIStackView = {
        let stackView = UIStackView()
        stackView.distribution = .equalSpacing
        stackView.axis = .vertical
        stackView.spacing = 5
        return stackView
    }()
```

2022-07-23 06:52 UTC, jryoun1 commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +        fatalError()
fatalError를 발생시키는 것은 앱이 강제 종료되기 때문에 지양해야합니다.

2022-07-23 06:52 UTC, jryoun1 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +        fatalError()
동일합니다.

2022-07-24 13:18 UTC, Hugh-github commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +class MainViewController: UIViewController {
final 키워드 추가했습니다.

2022-07-24 13:20 UTC, Hugh-github commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        sleep(10)
로딩이 되는지 확인하기 위해 추가했다가 제거하는 걸 까먹었습니다.
삭제했습니다!!

2022-07-24 13:20 UTC, Hugh-github commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +class GridCollectionViewCell: UICollectionViewCell {
final 키워드 추가했습니다

2022-07-24 13:20 UTC, Hugh-github commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +class ListCollectionViewCell: UICollectionViewCell {
final 키워드 추가했습니다

2022-07-24 13:26 UTC, Hugh-github commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +        fatalError()
우선 required init?(coder: NSCoder) 같은 경우 스토리보드나 xib 파일에 대한 초기화를 해주는 생성자라고 이해했습니다.
저희는 스토리보드를 사용하지 않기 때문에 @available을 사용해 해당 코드가 컴파일 시 에러가 발생하도록 설정해 주었습니다.

2022-07-24 13:26 UTC, Hugh-github commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +        fatalError()
우선 required init?(coder: NSCoder) 같은 경우 스토리보드나 xib 파일에 대한 초기화를 해주는 생성자라고 이해했습니다.
저희는 스토리보드를 사용하지 않기 때문에 @available을 사용해 해당 코드가 컴파일 시 에러가 발생하도록 설정해 주었습니다.

2022-07-24 13:39 UTC, Hugh-github commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        self.navigationItem.titleView = segment
저희가 MainViewController에서 선언한 property에 대해서는 self를 사용하지 않았고 기본적으로 가지고 있는 view와 같은 property에 대해서는 self 키워드를 사용했습니다.

2022-07-24 13:40 UTC, kiwi1023 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        self.navigationItem.titleView = segment
변경해주었습니다!

2022-07-24 13:40 UTC, kiwi1023 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        segment.setTitleTextAttributes([.foregroundColor : UIColor.systemBlue], for: .normal)
수정하였습니다!

2022-07-24 13:43 UTC, Hugh-github commented on OpenMarket/OpenMarket/Model/JSON/Page.swift
> +struct Page: Codable, Hashable {
DataSource에서 사용하는 타입은 Sendabler과 Hashable을 채택하고 있어야 하기 때문에 Page에서 Hashable 채택해 주었습니다.
Hashable 프로토콜 같은 경우 유일한 값임을 명시해주고 검색 속도가 빠르다는 장점이 있습니다.

2022-07-24 14:16 UTC, Hugh-github commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        view.addSubview(collectionView)
Hierarchy 내부에 있던 view.addSubView를 ViewDidLoad에서 한번만 진행해 주었습니다. 해당 과정을 통해 navigation bar를 관통해 view가 보이던 오류도 해결했습니다.

2022-07-24 14:18 UTC, kiwi1023 commented on OpenMarket/OpenMarket/Model/JSON/Page.swift
> +struct Page: Codable, Hashable {
item이라는 이름으로 변경해주었습니다~

2022-07-24 14:30 UTC, Hugh-github commented
titleLabel과 stockLabel 사이에 HuggingPriority와 CompressionPriority를 조절해 레이아웃을 다시 설정했습니다.

CompositionalLayout을 사용한 이유?
+ Modern Collection View를 활용하라고 명세서에 나와있어 사용했습니다.
+ 현재 프로젝트의 iOS 최소 버전을 14.0으로 설정했기 때문에 FlowLayout보다 Compositional Layout이 편리하다고 생각해 사용했습니다.
+ FlowLayout보다 유연한 CollectionView layout 설정이 가능하기 때문에 사용했습니다.

CompositionalLayout은 iOS 13버전 이후로 사용이 가능하기 때문에 현재 현업에서는 자주 사용되는 방법이 아닐수도 있다고 생각합니다. 혹시 FlowLayout이나 Custom Layout을 통해 구현해 보는 게 더 좋을까요?

2022-07-25 05:30 UTC, kiwi1023 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
네 수정하였습니다~!

2022-07-25 05:30 UTC, kiwi1023 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        }
네 수정하였습니다~!

2022-07-25 05:47 UTC, Hugh-github commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +    private func configureHorizontalStackView() {
layout과 Attribute로 분리해 주었습니다.

2022-07-25 05:48 UTC, Hugh-github commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +    private func configure() {
layout과 Attribute로 분리해 주었습니다.

2022-07-25 11:44 UTC, jryoun1 commented on OpenMarket/OpenMarket/Controller/MainViewController.swift
> +        self.navigationItem.titleView = segment
좋습니다 self에 대한 기준이 있으시군요. 👏

이러한 기준도 한 번 생각해 보시면 좋을 것 같습니다.
```swift
private let a: Int
private let b: Int

init(a: Int, b: Int) {
   self.a = a
   self.b = b
}
```
위와 같은 코드가 있을 때는 self.a는 self 키워드를 통해 전역 프로퍼티임을 명시해주기 위해 사용하고 있습니다. 또한 클로저 내부에서 사용하는 self 의 경우에도 위의 이유와 비슷하겠군요.

이런식으로 분명하게 명시적으로 표현을 해줘야하는 경우에(전역변수와 매개변수의 네이밍이 같은 경우, 이를 구분하기 위해서)는 self를 사용하고 그렇지 않은 경우에서는 self를 사용하지 않아도 충분히 알 수 있다고 생각합니다 :)

2022-07-25 12:20 UTC, jryoun1 approved these changes
@kiwi1023 @Hugh-github 
수정하신 부분 확인했습니다! 

잘 수정해주셔서 크게 말씀드릴게 없네요 👏 💯
다만 몇 가지 개선되면 좋을 것 같은 부분들이 있어서 코멘트 남겨두었습니다.
해당 부분들은 다음 step을 진행하면서 수정해주셔도 될 것 같아서 이번 step은 여기서 머지하겠습니다 🙏🏻

### 말씀해주신 부분에 대한 답변
> CompositionalLayout을 사용한 이유?
Modern Collection View를 활용하라고 명세서에 나와있어 사용했습니다.
현재 프로젝트의 iOS 최소 버전을 14.0으로 설정했기 때문에 FlowLayout보다 Compositional Layout이 편리하다고 생각해 사용했습니다.
FlowLayout보다 유연한 CollectionView layout 설정이 가능하기 때문에 사용했습니다.
CompositionalLayout은 iOS 13버전 이후로 사용이 가능하기 때문에 현재 현업에서는 자주 사용되는 방법이 아닐수도 있다고 생각합니다. 혹시 FlowLayout이나 Custom Layout을 통해 구현해 보는 게 더 좋을까요?

둘 중에 뭐가 더 좋다는 것은 무의미할 것 같습니다 ㅎㅎ 필요에 의해서 둘 중에 사용하시면 될 것 같습니다.
UICollectionViewFlowLayout와 UICollectionViewCompositionalLayout는 둘 다 UICollectionViewLayout를 상속받은 클래스입니다. 

따라서 UICollectionViewFlowLayout으로도 충분히 구현할 수 있는 화면이라면 UICollectionViewFlowLayout을 사용하면 되고, 만약 UICollectionViewFlowLayout을 사용하는 것보다 더 복잡하고 custom해야하는 화면을 구현해야한다면 UICollectionViewCompositionalLayout을 사용하시면 될 것 같아요!

이번에 UICollectionViewCompositionalLayout를 사용해보셨다면 다음번에는 UICollectionViewFlowLayout도 사용해보시는 걸 추천드립니다 👍🏻

2022-07-25 12:20 UTC, jryoun1 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +        verticalStackView.translatesAutoresizingMaskIntoConstraints = false
같은 프로퍼티끼리 분류하는것이 더 좋아보입니다.
```swift
titleLabel.translatesAutoresizingMaskIntoConstraints = false
titleLabel.textAlignment = .center
titleLabel.font = UIFont.boldSystemFont(ofSize: 18)

itemImageView.translatesAutoresizingMaskIntoConstraints = false
...
```

2022-07-25 12:20 UTC, jryoun1 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +        priceLabel.attributedText = .none
초기화를 해주는 부분들을 모아서 하나의 함수로 만드는 것이 좋아보입니다.

2022-07-25 12:20 UTC, jryoun1 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +            stockLabel.textColor = .systemYellow
일부 로직에 의해서 다시 textColor를 설정하는 부분을 제외하고는 configureAttribute() 내부에서 설정하는것은 어떨까요?

2022-07-25 12:20 UTC, jryoun1 commented on OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
> +    private func configureAttribute() {
함수 내부에서 여러 Attribute를 설정하고 있으므로 Attributes가 되어야할 것 같습니다 🙏🏻

2022-07-25 12:20 UTC, jryoun1 commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +    @available(*, unavailable)
작성하신 대로 @available을 사용할 수도 있지만, 
추후에 스토리보드나 xib를 사용했을 때도 정상적으로 동작할 수 있도록 fatalError, @available 대신 super.init(coder:)를 호출하는 방식이 좋아보입니다!

2022-07-25 12:20 UTC, jryoun1 commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +        let priceHuggingPriority = discountedLabel.contentHuggingPriority(for: .horizontal) + 1
여기도 위에서 드린 코멘트와 동일합니다!

2022-07-25 12:20 UTC, jryoun1 commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +        spacingView.isHidden = true
여기도 위에 드린 코멘트와 동일합니다!

2022-07-25 12:20 UTC, jryoun1 commented on OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
> +            guard let priceText = priceLabel.text else { return }
만약 priceText가 없는 경우에는 아래 다른 조건들은 실행되지 않고 return 이 되어버리는데 괜찮을까요? 🤔

2022-07-25 12:22 UTC, merged