오픈마켓[STEP2] 브래드, 백곰
yagom-academy/ios-open-market pull request #189
Opened 2022-07-22 05:56 UTC by bradheo65

안녕하세요 콘! @protocorn93 Step2 PR 보내드립니다. 🙇🏻‍♂️🙇🏻‍♂️
먼저 기간이 많이 늦은점 죄송합니다..  이번 스탭도 잘 부탁 드립니다.!

## 📝 기능설명
- URLCollection: URL주소를 Enum 타입으로 만들어주었습니다
- CustomError: Error 타입을 모아놓은곳 입니다
- ProductListResponse: API 주소에서 가져온 Json 타입의 상품 리스트 데이터들을 담을 Model 구조체 입니다
- Product: API 주소에서 가져온 Json 타입의 상품의 상세 데이터들을 담을 Model 구조체 입니다
- JsonParser 
    - dataTask(): 매개변수로 받은 URL 주소를 GET 방식으로 서버와 데이터를 주고받은후 Escaping Closure로 결과값을 반환해 줍니다.
- MockURLSession: 네트워크가 연결되지 않은 상태에서 Unit Test를 진행할때 사용할 코드 입니다
- PaddingLabel: Label에 Padding 기능을 구현하기 위한 코드입니다
- String+Extension
    - func strikeThrough(): DisCountPrice가 있으면 Label에 CancelLine 을 만들어줄 함수입니다
- ViewController: SegmentSwitch 를 컨트롤 하고 세그먼트 Select 에 따라 List 와 Grid 화면을 보여주는 코드 입니다.
- FirstViewController: UICollectionView List 화면을 구현하는 코드 입니다 
- SecondViewController: UICollectionView Grid 화면을 구현하는 코드 입니다

## STEP 2 Questions
Q1. UI 생성 시 스토리보드 vs 코드
아래 TroubleShooting에서 저희가 고민한 점에 대해서 UI설계시 스토리보드와 코드 중 어느 것으로 설계를 할 것인지에 대한 기준이 있는지 콘의 생각이 궁금합니다!

Q2. 한 ViewController에서 많은 view 생성
스토리보드로 구현하다 보니 CollectionView의 형태에 따른 view를 보여줄때 containerView를 써서 구현을 했습니다. 구현하고 나서 Debug View Hierarchy를 보니 한 화면에 많은 화면?이 나오는 걸 볼 수 있었는데 성능상 문제가 없을 지, 현업에서는 view를 한 화면에 구현을 해줄떄 어떤 방식으로 하는지 궁금합니다.

## STEP 2 TroubleShooting
T1. UI 생성 시 스토리보드 vs 코드
이번 프로젝트에서 스토리보드를 활용해 UI를 설계해보았는데, 코드로 설계했을 때와 많이 달랐습니다. 개인적으로 느끼기에는 큰 틀을 그릴때는 스토리보드가 빠르고 쉽게 가능 했지만 막상 세세한 설정을 해야할 상황에서는 코드로 하는 게 좋다고 느껴졌습니다. 특히 이번프로젝트에서 오토레아웃에 대한 고민을 많이 해봤을때 스토리보드로 하는 것보단 코드로 했으면 어떗을까 생각이 들었습니다. 다음 UI 설계시 코드로 하는 방향에 대해서 좀 더 생각해 보는게 좋을 것 같습니다.

T2. CollectionViewCell 재사용 문제
API에서 데이터를 적게 가져올 때는 문제가 없었지만, 데이터의 갯수가 30~40개가 넘어가게 되면 스크롤 시 해당 라벨에 대한 정보가 섞인 현상을 볼 수 있었습니다. 해결 방법에 대해서 생각해보았는데 셀 재사용시 호출되는 메소드 prepareForReuse()를 통해 해결해보긴 했지만 [애플에서는 prepareForReuse()에서 cell의 item을 초기화해주거나 변경시켜주는 기능 시 사용을 지양한다고 나와 있어 사용을 다른 생각을 해보았습니다.](https://developer.apple.com/documentation/uikit/uicollectionreusableview/1620141-prepareforreuse) 아래 구문에 해당 내용이 나와 있었습니다.

Override this method in your subclass to reset properties to their default values and make the view ready to use again. Don’t use this method to assign any new data to the view; that’s the responsibility of your data source object.

그래서 cell이 생성되는 메소드 func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell에서 각 라벨들의 데이터들을 초기화시켜주고 재 할당해주는 방식으로 코드를 작성해보니 원하는대로 동작하게 되었습니다. 무조건 prepareForReuse()사용해서 재사용성에 대한 고민을 해결했을텐데 생각의 전환이 되는 계기가 되었습니다.

T3. 데이터 로드 시 로딩 창 구현
요구사항에 데이터가 로드할 떄까지 별도로 로딩 창을 띄어주는 뷰를 추가해야 했었습니다. 그래서 viewDidLoad 해당 실행하는 함수를 넣어 실행해보니 viewDidLoad 메소드 내에 선언되어 있는 메소드들이 다 종료가 되어야지 첫 view가 보여주어서 별도로 로딩 창이 나오지 않았습니다. view 라이프 사이클에 대해 생각해 보았고 viewDidAppear에서 컬렉션뷰에 데이터를 넣어주는 메소드를 넣어주고 나머지는 viewDidLoad를 넣어줘서 로딩 창을 구현했고 API에서 데이터를 가져오는 시점에서 애니메이션을 종료시켜주고 컬렉션뷰를 reloadData() 메소드를 넣어주어 컬렉션뷰를 다시 그려주는 로직으로 구현해 해결했습니다.

T4. Grid CollectionView Column 2Line 으로 만들기 및 Cell 간격 띄우기
Grid 형태의 CollectionView 에서 2열형태 및 Cell 간격을 띄워주는 Layout이 요구사항이었습니다 처음엔 스토리보드로 하려고 했지만 Attributes inspector 에도 설정하는곳이 없어 UICollectionVIewDelegateFlowLayout 에 있는 Cell의 크기를 설정해주고 Cell사이의 Spacing 을 설정해주는 코드로 해당 요구사항을 구현했습니다.

2022-07-24 08:02 UTC, protocorn93 requested changes
두 분 모두 고생하셨어요! 👏

이후에 프로젝트를 개선해볼 기회가 생긴다면

- Modern Cell Configuration
- Diffable DataSource
- Compositonal Layout

을 적용해보면 좋을 것 같아요!

Q1. UI 생성 시 스토리보드 vs 코드

회사마다 다르고 팀마다 다를 수는 있지만 많은 회사들이 코드로 UI를 작성하는 것을 선호해요. 스토리보드를 쓰면 머지시 컨플릭이 너무 자주 나기 때문에 업무 퍼포먼스가 떨어지기 때문이에요. 그리고 코드 리뷰를 할 때도 스토리보드로 작성했다면 직접 실행해보기 전에는 레이아웃을 유추할 수 없어요. 

제가 속한 팀도 오로지 코드로만 작성하고 있어요!



Q2. 한 ViewController에서 많은 view 생성

화면 디자인에 따라 뷰가 많을 수 있지요~! 현재 프로젝트 상황을 보았을 땐 하나의 콜렉션 뷰 안에서 레이아웃을 그리도/리스트에 따라 별도로 가져가는 것도 방법일 수 있을 것 같아요. 

Compositional Layout을 활용하면 비교적 쉽게 이를 구현할 수 있을 것 같아요

2022-07-24 08:02 UTC, protocorn93 commented on OpenMarket/OpenMarket/Enum/URLCollection.swift
> +    static let productListInquery = "https://market-training.yagom-academy.kr/api/products?page_no=1&items_per_page=20"
이왕이면 `items_per_page`도 외부에서 주입해줄 수 있는 형태로 가면 좋겠네요.

2022-07-24 08:02 UTC, protocorn93 commented on OpenMarket/OpenMarket/FirstViewController/FirstViewController.swift
> +        activityIndicator.startAnimating()
필요할 때 `startAnimating`을 해주는게 적절할 것 같아요. api 호출 직전이라던지 말이죠.

2022-07-24 08:02 UTC, protocorn93 commented on OpenMarket/OpenMarket/FirstViewController/FirstViewController.swift
> +        productCollectionView.dataSource = self
`configureCollectionView`와 같이 별도 메서드로 분리하면 가독성이 더 좋아질 것 같아요.

2022-07-24 08:02 UTC, protocorn93 commented on OpenMarket/OpenMarket/FirstViewController/FirstViewController.swift
> +        URLSemaphore.wait()
네트워크 호출을 통해 데이터를 받아오는데 있어 세마포어는 어떤 목적으로 사용하셨을까요?

2022-07-24 08:02 UTC, protocorn93 commented on OpenMarket/OpenMarket/FirstViewController/FirstViewController.swift
> +                print(data)
알럿을 띄어주면 좋을 것 같아요.

2022-07-24 08:02 UTC, protocorn93 commented on OpenMarket/OpenMarket/FirstViewController/FirstViewController.swift
> +                print(data)
json parser가 네트워크 요청 역할을 가져가는 것이 적절한 것 같진 않네요. 네트워크 호출 객체로부터 raw data를 받아 parsing을 담당하도록 역할을 나누는게 좋을 것 같아요.

2022-07-24 08:02 UTC, protocorn93 commented on OpenMarket/OpenMarket/FirstViewController/FirstViewController.swift
> +    private func setData() {
`fetchData`, `requestData` 등이 좀 더 적절한 네이밍이 될 것 같네요!

2022-07-24 08:02 UTC, protocorn93 commented on OpenMarket/OpenMarket/FirstViewController/FirstViewController.swift
> +        cell.spacingView.isHidden = true
셀에는 데이터만 넘기고 화면에 그리는 행위는 셀에게 위임하는 것이 좋아요! 필요한 데이터만 넘기고 이를 어떻게 처리해서 보여줄지는 셀에서 해주시면 될 것 같아요.

2022-07-24 08:02 UTC, protocorn93 commented on OpenMarket/OpenMarket/FirstViewController/FirstViewController.swift
> +        }
여기도 마찬가지에요. 셀에서 처리해주세요.

2022-07-24 08:02 UTC, protocorn93 commented on OpenMarket/OpenMarket/SecondViewController/SecondViewController.swift
> +final class SecondViewController: UIViewController {
GridViewController, ListViewController라는 늬앙스의 네이밍으로 가져가면 좋을 것 같아요. 네이밍이 너무 모호하네요.

2022-07-24 08:02 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/FirstCollectionViewCell.swift
> +    @IBOutlet weak var spacingView: UIView!
셀들의 UI 컴포넌트에도 접근제어자를 붙여주세요~

2022-07-24 08:02 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/PaddingLabel.swift
> +    }
indent가 맞질 않네요~

2022-07-24 08:02 UTC, protocorn93 commented on OpenMarket/OpenMarket/ViewController.swift
> +    @IBOutlet weak var secondView: UIView!
마찬가지로 화면을 유추할 수 있는 네이밍이 필요해보여요.

2022-07-24 08:02 UTC, protocorn93 commented on OpenMarket/OpenMarket/SecondViewController/SecondViewController.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "secondCell", for: indexPath) as! SecondCollectionViewCell
셀 identifier 역시 셀 내부에 위치시키는게 좋아요.

```swift
final class SomeCell: UITableViewCell { 
  static let reuseIdentifier = "SomeCell"
}
```

2022-07-25 00:06 UTC, protocorn93 commented
> T2. CollectionViewCell 재사용 문제
API에서 데이터를 적게 가져올 때는 문제가 없었지만, 데이터의 갯수가 30~40개가 넘어가게 되면 스크롤 시 해당 라벨에 대한 정보가 섞인 현상을 볼 수 있었습니다. 해결 방법에 대해서 생각해보았는데 셀 재사용시 호출되는 메소드 prepareForReuse()를 통해 해결해보긴 했지만 [애플에서는 prepareForReuse()에서 cell의 item을 초기화해주거나 변경시켜주는 기능 시 사용을 지양한다고 나와 있어 사용을 다른 생각을 해보았습니다.](https://developer.apple.com/documentation/uikit/uicollectionreusableview/1620141-prepareforreuse) 아래 구문에 해당 내용이 나와 있었습니다.
Override this method in your subclass to reset properties to their default values and make the view ready to use again. Don’t use this method to assign any new data to the view; that’s the responsibility of your data source object.

그리고 두 분이 공식 문서를 잘못 이해하신 것 같아요. 재사용하는데 사용하고 새로운 데이터를 여기서 지정하지 말라고 되어 있어요! 여기선 재사용을 위해 reset을 해주는게 맞습니다

2022-07-25 05:51 UTC, bradheo65 commented on OpenMarket/OpenMarket/Enum/URLCollection.swift
> +    static let productListInquery = "https://market-training.yagom-academy.kr/api/products?page_no=1&items_per_page=20"
네 알맞게 수정해보았습니다!! 콘이 의도하신게 맞을까요?

[da7cde4](https://github.com/yagom-academy/ios-open-market/pull/189/commits/da7cde49e2fe45d26585490fa3faadc22b23785c)

2022-07-25 06:01 UTC, Baek-Gom-95 commented on OpenMarket/OpenMarket/FirstViewController/FirstViewController.swift
> +        activityIndicator.startAnimating()
API 호출 함수인 setData 매서드를 호출 하기 전과 후에 startAnimating 과 stopAnimating 을 넣어주었습니다.

2022-07-25 06:13 UTC, Baek-Gom-95 commented on OpenMarket/OpenMarket/FirstViewController/FirstViewController.swift
> +        productCollectionView.dataSource = self
별도의 메소드 fetchUICollectionViewConfiguration 로 분리해 주었습니다. https://github.com/yagom-academy/ios-open-market/pull/189/commits/a79c5a2669dea3c44f0f98ad03f0347d37aaa336

2022-07-25 06:15 UTC, bradheo65 commented on OpenMarket/OpenMarket/FirstViewController/FirstViewController.swift
> +        URLSemaphore.wait()
요청한 URL 데이터를 받아 오는 것을 기다려주기 위해서 세마포어를 사용해 주었습니다.

세마포어 없이 URL데이터를 받아올떄까지 기다려주는 방법이 따로 있을까요??🤔

2022-07-25 06:25 UTC, bradheo65 commented on OpenMarket/OpenMarket/FirstViewController/FirstViewController.swift
> +    private func setData() {
fetch로 메서드명 수정했습니다!

[9ec0134](https://github.com/yagom-academy/ios-open-market/pull/189/commits/9ec013498946c59ce98a55a7728b418e00baffb3)

2022-07-25 07:58 UTC, bradheo65 commented on OpenMarket/OpenMarket/FirstViewController/FirstViewController.swift
> +        cell.spacingView.isHidden = true
셀로 화면 구성하는 로직을 이동시켜 구현해보았습니다. 콘이 생각하시는 방향과 맞을까요??🤔

[36f0172](https://github.com/yagom-academy/ios-open-market/pull/189/commits/36f0172996ee9e73a7d3e639c11da14d3980da72)

2022-07-25 07:59 UTC, bradheo65 commented on OpenMarket/OpenMarket/FirstViewController/FirstViewController.swift
> +        }
위의 코멘트에서 작업을 같이 해보았습니다

[36f0172](https://github.com/yagom-academy/ios-open-market/pull/189/commits/36f0172996ee9e73a7d3e639c11da14d3980da72)

2022-07-25 08:17 UTC, bradheo65 commented on OpenMarket/OpenMarket/SecondViewController/SecondViewController.swift
> +final class SecondViewController: UIViewController {
넵 처음에 테스트용으로 네이밍 해둔것을 미처 수정하지 못했네요..! 감사합니다!

[ad2f754](https://github.com/yagom-academy/ios-open-market/pull/189/commits/ad2f754798467f1a4f316854e4b12ec34e50b4ce)

2022-07-25 08:20 UTC, bradheo65 commented on OpenMarket/OpenMarket/View/FirstCollectionViewCell.swift
> +    @IBOutlet weak var spacingView: UIView!
네 수정 했습니다!

[24343b8](https://github.com/yagom-academy/ios-open-market/pull/189/commits/24343b8e3b0befac91afba0b510f55d8b5156c54)

2022-07-25 08:31 UTC, Baek-Gom-95 commented on OpenMarket/OpenMarket/View/PaddingLabel.swift
> +    }
변경해주었습니다

2022-07-25 08:31 UTC, Baek-Gom-95 commented on OpenMarket/OpenMarket/ViewController.swift
> +    @IBOutlet weak var secondView: UIView!
화면유추가 가능한 변수명으로 변경해주었습니다 😊 https://github.com/yagom-academy/ios-open-market/pull/189/commits/1c179959e27853a361fb5ce094c0c1a6cf53ab66

2022-07-25 08:49 UTC, bradheo65 commented on OpenMarket/OpenMarket/SecondViewController/SecondViewController.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "secondCell", for: indexPath) as! SecondCollectionViewCell
셀 내부에서 선언을 해주어서 작업을 했습니다. 

궁금한 점이 있는데요! 스토리보드에서 identifier를 설정을 안할시엔 thread error가 발생되어서 스토리보드에도 해당 identifier를 넣어주었습니다. 

코드로 작성시엔 별다른 에러가 없었는데 단지 스토리보드와 코드로 UI구성에 있어 차이점이 있어서 그런건가요??

[d76b51f](https://github.com/yagom-academy/ios-open-market/pull/189/commits/d76b51fc2bbbfd3556641f51844eb009bdc5ee5d)

2022-07-25 11:18 UTC, protocorn93 commented on OpenMarket/OpenMarket/Enum/URLCollection.swift
> +    static let productListInquery = "https://market-training.yagom-academy.kr/api/products?page_no=1&items_per_page=20"
각 endpoint를 케이스로 갖는 enum의 연관값으로 받을 수 있을 것으로 생각했는데, 이 부분은 다음 스탭에서 개선해봐요!

2022-07-25 11:19 UTC, protocorn93 commented on OpenMarket/OpenMarket/FirstViewController/FirstViewController.swift
> +        URLSemaphore.wait()
서버 요청을 하는데는 기다려줄 필요가 없을 것 같아요. 한번에 하나의 요청만 할 수 있다는 것도 이상하구요! (물론 그런 요구사항이 있다면 해야겠지만요!)

현재 상황에선 세마포어를 사용할 이유는 없어보여요

2022-07-25 11:20 UTC, protocorn93 commented on OpenMarket/OpenMarket/FirstViewController/FirstViewController.swift
> +        URLSemaphore.wait()
동시성 이슈도 있을 것 같지 않구요

2022-07-25 11:21 UTC, protocorn93 commented on OpenMarket/OpenMarket/SecondViewController/SecondViewController.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "secondCell", for: indexPath) as! SecondCollectionViewCell
스토리보드를 사용한다면 아쉽지만 스토리보드에서도 명시해주어야해요! 다만 위치와 raw한 값을 바로 사용하는 것을 최대한 방비하고자 셀 안에 위치시키는게 좋아요!

2022-07-25 13:40 UTC, merged