[Step1] - JM, Kio
yagom-academy/ios-open-market pull request #19
Opened 2021-05-11 09:20 UTC by Kioding

@seizze
하이디, 안녕하세요😆
JM, Kio 첫 PR 보내봅니다.
[README - 타임라인 및 학습키워드](https://github.com/alwaysblu/ios-open-market/tree/step1)
<br>

## Step1 프로젝트 기능
- Step1 기능별 Request, Response 모델 타입 구현
- Unit Test 작성

<br>

## 조언을 얻고 싶은 점
- api문서를 보고 중복없이 공통된 부분을 묶어서 모델링을 할지 고민하다가, 가독성을 위해 중복하여 기능별로 모델을 나누었는데 이 부분에 대해 조언을 얻고 싶습니다😭
- JSON data를 가져올 때 개행을 위한 이스케이프 문자 `\n`가 있으면 문자열로 인식하지 않아 test가 통과하지 않더라구요. 사실, 이 개행이 문제라는 걸 알기까지가 오래 걸렸습니다. 이 부분이 왜 문제가 있는 건지 하이디에게 여쭤보고 싶습니다.
- Unit test를 작성해보았는데, 적절하게 잘 작성한 건지 조언을 얻고 싶습니다😓

2021-05-12 16:31 UTC, seizze requested changes
안녕하세요 JM, Kio~ 반갑습니다 ☺️

아래는 코멘트에 남겨두신 내용에 대한 제 의견입니다.

> api문서를 보고 중복없이 공통된 부분을 묶어서 모델링을 할지 고민하다가, 가독성을 위해 중복하여 기능별로 모델을 나누었는데 이 부분에 대해 조언을 얻고 싶습니다😭

이 부분은 네이밍 관련해서 드린 피드백에서 3번을 참고해 주세요! 1~3번 사항을 반영하신다면 가독성은 따라올 거라고 생각합니다 ☺️

> JSON data를 가져올 때 개행을 위한 이스케이프 문자 \n가 있으면 문자열로 인식하지 않아 test가 통과하지 않더라구요. 사실, 이 개행이 문제라는 걸 알기까지가 오래 걸렸습니다. 이 부분이 왜 문제가 있는 건지 하이디에게 여쭤보고 싶습니다.

코드에서 json 문자열 안에 `\n`을 넣었을 때 문제가 됐다고 하시는 것 맞나요? 만약 그렇다면 `\`는 코드에서 문자열이 아닌 다른 내용을 구분하기 위해 사용되는 특별한 문자이기 때문에, 진짜 `\n`을 입력하려면 `\\n` 이라고 써줘야 합니다.
참고로, 스위프트에서는 아래와 같이 문자열을 `#`으로 감싸면 `\\` 처리를 안해줘도 됩니다.

```swift
let json = #"""
 //  여기선 \n 이라고 쓸 수 있어요!
"""#
```

제가 상황을 잘 이해했는지 모르겠네요 ㅎㅎ 이게 아니라면 DM 편하게 주세요~!

> Unit test를 작성해보았는데, 적절하게 잘 작성한 건지 조언을 얻고 싶습니다😓

넵 ㅎㅎ 테스트 관련해서도 코드에다가 몇가지 피드백 드렸습니다!

2021-05-12 16:31 UTC, seizze commented on OpenMarket/OpenMarketTests/ModelTest.swift
> +            """
json 문자열을 따로 파일로 만드는 건 어떨까요? 그리고 이 정보가 뭘 의미하는지도 파일명에 잘 나타나도록 지어보면 좋을 것 같아요. 이런 테스트를 작성할 때 여러 다양한 경우(정상 응답, 에러 응답, 등등...)의 응답 파일들을 만들어 다양하게 테스트하기도 합니다. ㅎㅎ

2021-05-12 16:31 UTC, seizze commented on OpenMarket/OpenMarketTests/ModelTest.swift
> +class ModelTest: XCTestCase {
타입을 몇개 재사용하게 만든 후에, 타입별로 테스트를 나눠서 작성하면 더 가독성이 좋아질 것 같아요~

2021-05-12 16:31 UTC, seizze commented on OpenMarket/OpenMarketTests/ModelTest.swift
> +        XCTAssertEqual(getItemPageResponse.items[0].registrationDate, 1611523563.7237701)
GetItemPageResponse에 Equatable을 채택해서 비교해 보는건 어떨까요?

2021-05-13 15:26 UTC, alwaysblu commented on OpenMarket/Model/DeleteItemIdentity/DeleteItemIdentityResponse.swift
> +struct DeleteItemIdentityResponse: Decodable {
이름을 아래와 같이 바꿔보았습니다!

ItemsOfPageReponse : 해당 페이지의 상품들에 대한 응답을 의미하는 모델입니다.
InformationOfItemResponse : 상품의 정보에 대한 응답을 의미하는 모델입니다.
ItemEditRequest : 상품 수정 요청을 의미하는 모델입니다.
ItemRegisterRequest : 상품 등록 요청을 의미하는 모델입니다.
ItemDeleteRequest : 상품 삭제를 의미하는 모델입니다.

1.
```swift
struct ItemEditRequest: Codable, Equatable {
    var title: String?
    var descriptions: String?
    var price: Int?
    var currency: String?
    var stock: Int?
    var discountedPrice: Int?
    var images: [String]?
    var password: String

    private enum CodingKeys: String, CodingKey {
        case title
        case descriptions
        case price
        case currency
        case stock
        case discountedPrice = "discounted_price"
        case images
        case password
    }
}
```
2.
```swift
struct ItemRegisterRequest: Codable, Equatable {
    var title: String
    var descriptions: String
    var price: Int
    var currency: String
    var stock: Int
    var discountedPrice: Int?
    var images: [String]
    var password: String
    
    private enum CodingKeys: String, CodingKey {
        case title
        case descriptions
        case price
        case currency
        case stock
        case discountedPrice = "discounted_price"
        case images
        case password
    }
}
```
3.
```swift
struct Item: Decodable, Equatable {
    var id: Int
    var title: String
    var price: Int
    var currency: String
    var stock: Int
    var discountedPrice: Int?
    var thumbnails: [String]
    var registrationDate: Double
    
    private enum CodingKeys: String, CodingKey {
        case id
        case title
        case price
        case currency
        case stock
        case discountedPrice = "discounted_price"
        case thumbnails
        case registrationDate = "registration_date"
    }
}
```
4.
```swift
struct InformationOfItemResponse: Decodable, Equatable {
    var id: Int
    var title: String
    var descriptions: String
    var price: Int
    var currency: String
    var stock: Int
    var discountedPrice: Int?
    var thumbnails: [String]
    var images: [String]
    var registrationDate: Double
    
    private enum CodingKeys: String, CodingKey {
        case id
        case title
        case descriptions
        case price
        case currency
        case stock
        case discountedPrice = "discounted_price"
        case thumbnails
        case images
        case registrationDate = "registration_date"
    }
}
```

위의 4개의 모델에 중복된 프로퍼티들이 다수 존재하는데 
이 공통된 다수의 프로퍼티를 어떻게 묶어야할지에 대해서 조언을 얻고 싶습니다!

시도 해본 것으로 class를 이용하여 base 모델을 만들어 상속을 이용하여 묶어보았는데
어차피 모델의 개수는 동일한데 가독성은 떨어졌습니다

2021-05-13 15:28 UTC, alwaysblu commented on OpenMarket/OpenMarketTests/ModelTest.swift
> +            """
아래와 같이 가짜데이터를 테스트하기위한 MockData를 만들어보았습니다!

```swift
enum MockData {
    static let ItemsOfPageReponseJSON = #"""
                    {
                        "page": 1,
                        "items": [
                            {
                                "id": 1,
                                "title": "MacBook Pro",
                                "price": 1690,
                                "currency": "USD",
                                "stock": 0,
                                "discounted_price": 100,
                                "thumbnails": [
                                    "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/thumbnails/1-1.png",
                                    "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/thumbnails/1-2.png"
                                    ],
                                "registration_date": 1611523563.7237701
                            }
                        ]
                    }
            """#
    
    static let InformationOfItemResponseJSON = #"""
                {
                    "id": 1,
                    "title": "MacBook Pro",
                    "descriptions": "Apple M1 칩은 13형 MacBook Pro에 믿을 수 없을 만큼의 속도와 파워를 선사합니다.",
                    "price": 1690000,
                    "currency": "KRW",
                    "stock": 1000000000000,
                    "discounted_price" : 1,
                    "thumbnails": [
                        "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/thumbnails/1-1.png",
                        "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/thumbnails/1-2.png"
                        ],
                    "images": [
                        "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/images/1-1.png",
                        "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/images/1-2.png"
                        ],
                    "registration_date": 1611523563.719116
                }
            """#
    
    static let ItemEditRequestJSON = #"""
                {
                    "title": "MacBook Pro",
                    "descriptions": "Apple M1 칩은 13형 MacBook Pro에 믿을 수 없을 만큼의 속도와 파워를 선사합니다.최대 2.8배 향상된 CPU 성능, 최대 5배 빨라진 그래픽 속도, 최대 11배 빨라진 머신 러닝 성능을 구현하는 최첨단 Apple 제작 Neural Engine, 여기에 무려 20시간 지속되는 Mac 사상 가장 오래가는 배터리까지.외장은 Apple의 가장 사랑받는 프로용 노트북 그대로, 하지만 그 능력은 한 차원 더 높아졌습니다.",
                    "price": 1690000,
                    "currency": "KRW",
                    "stock": 1000000000000,
                    "images": [
                    "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/images/1-1.png",
                    "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/images/1-2.png"
                    ],
                    "password": "password"
                }
            """#
    static let ItemRegisterRequestJSON = #"""
                    {
                        "title": "MacBook Pro",
                        "descriptions": "Apple M1 칩은 13형 MacBook Pro에 믿을 수 없을 만큼의 속도와 파워를 선사합니다.최대 2.8배 향상된 CPU 성능, 최대 5배 빨라진 그래픽 속도, 최대 11배 빨라진 머신 러닝 성능을 구현하는 최첨단 Apple 제작 Neural Engine, 여기에 무려 20시간 지속되는 Mac 사상 가장 오래가는 배터리까지.외장은 Apple의 가장 사랑받는 프로용 노트북 그대로, 하지만 그 능력은 한 차원 더 높아졌습니다.",
                        "price": 1690000,
                        "currency": "KRW",
                        "stock": 1000000000000,
                        "discounted_price" : 1,
                        "images": [
                            "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/thumbnails/1-1.png",
                            "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/thumbnails/1-2.png"
                            ],
                        "password": "password"
                    }
                """#
    
    static let ItemDeleteRequestJSON = #"""
                    {
                        "password": "password"
                    }
                """#
}
```

2021-05-13 15:30 UTC, alwaysblu commented on OpenMarket/OpenMarketTests/ModelTest.swift
> +        XCTAssertEqual(getItemPageResponse.items[0].registrationDate, 1611523563.7237701)
모든 모델에 Equatable을 채택해서 아래와 같이 모델의 객체를 생성하여 비교하는 방식으로 테스트를 변경하여 보았습니다!

```swift
func test_ItemsOfPageReponse() throws {
        let jsonData = MockData.ItemsOfPageReponseJSON.data(using: .utf8)!
        let decodedData = try JSONDecoder().decode(ItemsOfPageReponse.self, from: jsonData)
        let items = [Item(id: 1,
                          title: "MacBook Pro",
                          price: 1690,
                          currency: "USD",
                          stock: 0,
                          discountedPrice: 100,
                          thumbnails: [
                            "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/thumbnails/1-1.png",
                            "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/thumbnails/1-2.png"
                          ],
                          registrationDate: 1611523563.7237701)]
        let itemsOfPageReponse = ItemsOfPageReponse(page: 1, items: items)
        
        XCTAssertEqual(decodedData, itemsOfPageReponse)
        
    }
    
    func test_ItemEditRequest() throws {
        
        let jsonData = MockData.ItemEditRequestJSON.data(using: .utf8)!
        let decodedData = try JSONDecoder().decode(ItemEditRequest.self, from: jsonData)
        
        let itemEditRequest = ItemEditRequest(
            title: "MacBook Pro",
            descriptions: "Apple M1 칩은 13형 MacBook Pro에 믿을 수 없을 만큼의 속도와 파워를 선사합니다.최대 2.8배 향상된 CPU 성능, 최대 5배 빨라진 그래픽 속도, 최대 11배 빨라진 머신 러닝 성능을 구현하는 최첨단 Apple 제작 Neural Engine, 여기에 무려 20시간 지속되는 Mac 사상 가장 오래가는 배터리까지.외장은 Apple의 가장 사랑받는 프로용 노트북 그대로, 하지만 그 능력은 한 차원 더 높아졌습니다.",
            price: 1690000,
            currency: "KRW",
            stock: 1000000000000,
            discountedPrice: nil,
            images:[
                "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/images/1-1.png",
                "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/images/1-2.png"
            ],
            password: "password")
        
        XCTAssertEqual(decodedData, itemEditRequest)
        
        
    }
    
    func test_InformationOfItemResponse() throws {
        
        let jsonData = MockData.InformationOfItemResponseJSON.data(using: .utf8)!
        let decodedData = try JSONDecoder().decode(InformationOfItemResponse.self, from: jsonData)
        let informationOfItemResponse = InformationOfItemResponse(
            id: 1,
            title: "MacBook Pro",
            descriptions: "Apple M1 칩은 13형 MacBook Pro에 믿을 수 없을 만큼의 속도와 파워를 선사합니다.",
            price: 1690000,
            currency: "KRW",
            stock: 1000000000000,
            discountedPrice: 1,
            thumbnails: [
                "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/thumbnails/1-1.png",
                "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/thumbnails/1-2.png"
            ],
            images: [
                "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/images/1-1.png",
                "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/images/1-2.png"
            ],
            registrationDate: 1611523563.719116)
        
        XCTAssertEqual(decodedData, informationOfItemResponse)
    }
    
    func test_ItemRegisterRequest() throws {
        
        let jsonData = MockData.ItemRegisterRequestJSON.data(using: .utf8)!
        let decodedData = try JSONDecoder().decode(ItemRegisterRequest.self, from: jsonData)
        let itemRegisterRequest = ItemRegisterRequest(title: "MacBook Pro", descriptions: "Apple M1 칩은 13형 MacBook Pro에 믿을 수 없을 만큼의 속도와 파워를 선사합니다.최대 2.8배 향상된 CPU 성능, 최대 5배 빨라진 그래픽 속도, 최대 11배 빨라진 머신 러닝 성능을 구현하는 최첨단 Apple 제작 Neural Engine, 여기에 무려 20시간 지속되는 Mac 사상 가장 오래가는 배터리까지.외장은 Apple의 가장 사랑받는 프로용 노트북 그대로, 하지만 그 능력은 한 차원 더 높아졌습니다.", price: 1690000, currency: "KRW", stock: 1000000000000, discountedPrice: 1, images: [
            "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/thumbnails/1-1.png",
            "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/thumbnails/1-2.png"
        ], password: "password")
        
        XCTAssertEqual(decodedData, itemRegisterRequest)
        
    }
    
    
    func test_ItemDeleteRequest() throws {
        
        let jsonData = MockData.ItemDeleteRequestJSON.data(using: .utf8)!
        let decodedData = try JSONDecoder().decode(ItemDeleteRequest.self, from: jsonData)
        let itemDeleteRequest = ItemDeleteRequest(password: "password")
        XCTAssertEqual(decodedData, itemDeleteRequest)
    }
```

2021-05-13 15:32 UTC, alwaysblu commented on OpenMarket/OpenMarketTests/ModelTest.swift
> +class ModelTest: XCTestCase {
중복되는 모델을 재사용하도록 만든 후 해당 모델별로 테스트틑 나눠서 작성하도록 하였습니다!

2021-05-14 01:37 UTC, alwaysblu commented
@seizze 

리뷰 감사합니다!

하이디께서 주신 리뷰에 맞게 수정해보았습니다!

2021-05-15 05:13 UTC, seizze approved these changes
수고 많으셨습니다! 👏👏
추가적으로 피드백 드렸는데, 이 내용들은 2단계에서 실제로 서버 요청을 해 보면서 적용해 보시면 좋을 것 같아요. 질문하신 내용들도 모두 코멘트로 드렸습니다~ 혹시 빼먹은게 있다면 알려주세요 ☺️

그럼 2단계도 파이팅입니다~!

2021-05-15 05:13 UTC, seizze commented on OpenMarket/OpenMarketTests/ModelTest.swift
> +        XCTAssertEqual(getItemPageResponse.items[0].registrationDate, 1611523563.7237701)
> JSON 파일의 키값과 모델의 프로퍼티가 항상 같아야 decode와 encode가 성공한다고 알고 있는데 왜 위의 이미지와 같은 현상이 생기는 건지에 대한 조언을 얻고 싶습니다!

추가적인 키가 더 있더라도 디코딩이 실패하진 않습니다! 그리고 키가 없더라도 그 프로퍼티를 옵셔널로 선언하면 디코딩이 성공합니다.

> decode가 정확하게 수행이 된다면 만약 데이터와 모델이 일치하지 않을시에 오류가 발생해서 테스트에 실패하게 되므로
굳이 XCTAssertEqual(decodedData, itemRegisterRequest) 와 같은 코드를 작성해서 비교할 필요가 없다는 생각이 드는데
이 부분에 대해서도 조언을 얻고 싶습니다!
그리고 decode에 실패하면 테스트가 실패하게 되는데 굳이 XCTFail() 을 이용해야하는지 궁금합니다!

현재 코드를 돌려보니, 디코딩에 실패해서 테스트가 실패한 것이 아니라, "디코딩이 실패할 때의 에러를 처리하지 않을 경우" 테스트가 실패하도록 작성되어 있네요~ 아마 함수를 `func test_ItemsOfPageReponse() throws`라고 에러를 던지도록 선언했기 때문에, 에러를 던지면 XCTest에서 알아서 실패하도록 처리해 주는 것 같습니다.ㅎㅎ 테스트 메서드를 throws로 선언하면 이런 장점이 있네요. 몰라서 throws 없이 사용하고 있었는데, 저도 사용해야겠어요 ☺️

반면, XCTFail()을 사용해야 하는 경우는 throws로 선언하지 않았을 때입니다. 이땐 do catch문 + XCTFail()을 쓰거나 try?를 사용해서 nil이 아닌지 체크하는 등의 처리를 해 줘야 합니다. 만약 try! 를 쓰면 디코딩이 실패했을 때 테스트가 실패하는 것이 아니라 크래시로 종료되고, 다음 테스트가 진행되지 않는 걸로 알고 있습니다.

만약 테스트 머신에 테스트 자동화를 시켜 놨는데, 테스트 코드에서 크래시가 나도록 작성해 놨다면, 크래시로 종료될 경우 테스트 로그를 보고.. 디버깅을 다시 시작하는 귀찮은 작업을 해야겠죠? 그런 추가 공수를 방지하기 위해 지금 안전하게 코드를 작성하는 방향이 더 좋지 않을까 생각합니다. 만약 100% 발생하는 크래시라면 코딩할 때 발견되기 때문에 괜찮겠지만, 어쩌다 한 번씩 발생하는 크래시라면 누군가 개발팀에서 시간을 내서 디버깅을 해야하니까요.

그리고 XCTAssertEqual(decodedData, itemRegisterRequest)와 같은 코드를 추가적으로 더 쓰는건... 저는 오히려 한 줄만 더 쓰면 몇가지 추가 검증을 더 해볼 수 있다는 생각인데요 ㅎㅎ 디코딩은 성공했지만 안에 들어있는 데이터가 다를 수도 있으니까요?

궁금증이 해결되셨는지 모르겠네요! 더 궁금한게 있다면 편하게 DM 주세요 ☺️

2021-05-15 05:29 UTC, merged

2021-05-15 07:57 UTC, alwaysblu commented on OpenMarket/Model/Request/ItemEditRequest.swift
> +struct ItemEditRequest: Codable, Equatable {
# < 메모 > 
## 질문 :
ItemEditRequest, ItemRegisterRequest 는 프로퍼티의 개수와 이름은 동일하지만 타입이 옵셔널로 달라서 모델을 구분하였는데

타입이 (옵셔널) 달라도 리뷰 주신 내용처럼 Request타입을 만들어서 메소드를 통해서 

공통적으로 사용되는 타입을 만들 수 있을지 궁금합니다 ㅠ

## 답변 :
옵셔널은 달라도 가능합니다~! ㅎㅎ 그리고 추가적으로 현재 메서드가 PATCH로 되어있는데, PATCH와 PUT의 차이도 한번 알아보시면 좋을 것 같아요! 그러면 수정 요청을 어떻게 해야할지 더 감을 잡으실 수 있을 것 같습니다

2021-05-15 08:19 UTC, alwaysblu commented on OpenMarket/Model/Request/ItemEditRequest.swift
> +struct ItemEditRequest: Codable, Equatable {
# < 메모 > 
## 질문 :
ItemEditRequest, ItemRegisterRequest 는 프로퍼티의 개수와 이름은 동일하지만 타입이 옵셔널로 달라서 모델을 구분하였는데

타입이 (옵셔널) 달라도 리뷰 주신 내용처럼 Request타입을 만들어서 메소드를 통해서 

공통적으로 사용되는 타입을 만들 수 있을지 궁금합니다 

## 답변 :
옵셔널은 달라도 가능합니다~! ㅎㅎ 그리고 추가적으로 현재 메서드가 PATCH로 되어있는데, PATCH와 PUT의 차이도 한번 알아보시면 좋을 것 같아요! 그러면 수정 요청을 어떻게 해야할지 더 감을 잡으실 수 있을 것  같습니다 🤓