오픈마켓 [STEP2] unchain, seohyeon2
yagom-academy/ios-open-market pull request #190
Opened 2022-07-22 15:26 UTC by seohyeon2

# PR

안녕하세요 라이언! @ryan-son 🦁
Step2 PR 보냅니니다.
요청이 늦어저서 정말 죄송합니다😭
먼저 기간이 많이 늦은점 죄송합니다.. 
이번 스텝도 잘 부탁 드립니다!!🙇🏻‍♀️🙇🏻

---
### ⚙️ 코드 소개

#### `Extension`
- String 타입 확장을 통해 취소선을 그리는 메서드를 구현했습니다.

#### `MarketInformation`
- 서버 매핑 모델을 구현한 타입입니다.

#### `MainViewController`
- UI Components, Segmented Control, API 처리를 구현한 뷰 컨트롤러입니다.

#### `ItemCollectionViewCell`
- ListCollectionCell, GridCollectionViewCell에서 중복되는 프로퍼티와 메서드를 사용하기 위해 UICollectionViewListCell타입의 새로운 셀 타입을 만들어준 클래스입니다.
- 
#### `configureListDataSource(), configureGridDataSource()`
- List형식의 화면과 GRID형식의 화면을 전환할 때 컬렉션뷰에 새로운 데이타 소스를 어플라이 해줘야 하기 때문에 두가지 셀 타입을 갖는 데이타 소스를 받는 메서드입니다.

#### `handleSegmentChange()`
- 세그먼트 컨트롤의 선택된 인덱스가 바뀌면 컬렉션뷰의 레이아웃과 데이타 소스를 변경해 주어서 컬렉션뷰의 타입을 변경해주는 메서드 입니다.

#### `loadingView`
- 처음 데이터를 받아오는 동안 빈화면을 보여줄 때 나타나는 뷰 입니다.

#### `configureCell()`
- 서버에 요청한 이미지는 String형태로 URl값이 넘어오기 때문에 이를 다시 요청해서 Data의 형태로 변경하여 이미지 뷰에 적용해주는 메서드 입니다.

#### `showPrice()`
- 서버에서 받아온 상품의 할인 가격이 있는지 확인하고 없으면 원래의 가격만 보여주고 있다면 원래가격에는 빨간줄을 긋고 할인된 가격을 보여주는 메서드입니다.

#### `showSoldOut()`
- 서버에서 받아온 상품의 재고 유무를 확인하고 재고가 없으면 품절메세지를 띄우고 재고가 있으면 잔여수량을 표시해주는 메서드입니다.

### ⭐️ 궁금한 점 및 조언 얻고 싶은 점

**1. 이미지 레이아웃 미적용 건**
- 비동기로 이미지를 받아온 후 cell에 이미지를 넣으면 이미지의 크기 각기 다르게 보입니다.
- 저희가 잡은 레이아웃대로 크기가 일정한 이미지도 있는 방면, 크기가 작았다가 cell을 누르면 레이아웃대로 커지는 현상이 발생했습니다.
- 왜 이런 현상이 발생하는지.. 어떤 키워드로 검색하면 해결할 수 있는지 조언을 얻고 싶습니다!😌

<img src = https://i.imgur.com/zzcSBGb.png width = 250 height = 450>

<br>

**2. CollectionViewcell 레이아웃 충돌 건**
- `segment Control`로 `List`와 `Grid`를 왔다갔다 여러번 누르면 레이아웃이 깨지는 현상이 발생합니다😥
- 디버깅 창에 충돌 오류가 찍히면 아래 사진과 같이 cell에 대한 레이아웃이 다 사라집니다.
- 저희가 어떤 점을 더 보완해야해야 할 지, 고려하지 못한 부분이 무엇인지 궁금합니다!😲  

<img src = https://i.imgur.com/GDcPz7m.png width = 250 height = 450>

2022-07-25 18:26 UTC, ryan-son requested changes
언체인, 현이! Step 2 내용이 굉장히 많았을텐데 고생 많으셨어요. 코드만 보아도 여러분이 얼마나 고생하셨는지 느껴지네요.

이번에는 PR 본문에 남겨주신 질문까지 개별 코멘트에서 다루었으니 참고해보시면 될 것 같습니다. 이번 피드백을 통해 나아가야할 방향이 조금 바뀔 수도 있을 것 같네요. 피드백이 이해하기 어렵거나 어디서 시작해야할지 감을 잡기 어렵다면 언제든지 찾아주세요~ 😉

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/MainViewController.swift
> +    private lazy var dataSource: UICollectionViewDiffableDataSource<Section, SaleInformation>? = configureListDataSource()
[P3]
초기화할 때 ViewController 인스턴스(`self`)를 사용하기 위한 목적으로만 `lazy` 키워드를 사용하는 것은 설득력이 부족해보일 수 있을 것 같아요. 이런 방식으로 `lazy` 키워드를 사용하는 프로퍼티는 실제로 어느 시점에 초기화가 되는지 추적하기 쉽지 않기 때문에 로직을 파악하기 어렵게 만들 수 있다고 생각합니다.

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/MainViewController.swift
> +    private var snapshot = NSDiffableDataSourceSnapshot<Section, SaleInformation>()
1. Diffable datasource에서 snapshot은 어떤 의미를 가지고 어떤 역할을 수행하나요?
2. `NSDiffableDataSourceSnapshot`의 section과 item이 되기 위한 제약사항이 있나요?

- [`NSDiffableDataSourceSnapshot` - Apple Developer](https://developer.apple.com/documentation/uikit/nsdiffabledatasourcesnapshot)
- [`UICollectionViewDiffableDataSource` - Apple Developer](https://developer.apple.com/documentation/uikit/uicollectionviewdiffabledatasource)

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/MainViewController.swift
> +    private var count = 1
[P3]
이 이름만으로는 본인이 어떤 목적을 가지는 프로퍼티인지 설명하기 어려울 수 있겠어요. 상품 페이지 count와 연관된 이름으로 변경해보는건 어떨까요?

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/MainViewController.swift
> +        setConstraint()
[P4]
이왕 코드 정리한 김에 addSubview도 메서드로 만드는건 어떨까요? 앞으로 subview의 구조가 변경될 때마다 `viewDidLoad`에 있는 코드를 수정하기는 껄끄러울 수 있을 것 같아요.

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/MainViewController.swift
> +        let networkManger = NetworkManager(session: urlSession)
[P3]
이전에 논의한대로 이 메서드, 상품 상세 요청 메서드 등 동일한 Path Parameter를 사용하는 단위로 네트워크 타입을 분리시켜봐도 좋을 것 같아요. 이렇게 구성한다면 ViewController와 네트워킹 로직의 결합도가 높아져 이 로직을 테스트하기 어려워질 수 있을 것 같네요.

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/MainViewController.swift
> +        self.snapshot.appendSections([.main])
snapshot에 section이나 item을 추가할 때 주의할 사항에는 어떤 것이 있었나요?

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/MainViewController.swift
> +                }
[P1]
마지막 페이지를 로드할 때까지 재귀적으로 자신을 호출하고 있네요. 사용자가 보지 않는 영역의 상품까지 미리 받아올 것이기 때문에 네트워크와 메모리 사용률이 의도치 않게 높아질 수 있습니다. 사용자가 다음 상품 페이지 목록을 필요로하면 다음 페이지를 불러오도록 로직을 수정해보는 것이 좋을 것 같아요. 평소에 사용하시던 앱들을 참고하셔서 어떤 방식으로 페이지 로드 정책을 수립하면 좋을지 논의해보세요~

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/MainViewController.swift
> +    func configureListDataSource() -> UICollectionViewDiffableDataSource<Section, SaleInformation>? {
[P4]
접근 제한 설정해볼까요? 😉

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/MainViewController.swift
> +        dataSource = UICollectionViewDiffableDataSource<Section, SaleInformation>(collectionView: collectionView) { (collectionView: UICollectionView, indexPath: IndexPath, product: SaleInformation)
이런 구문도.. 줄바꿈 대상에 포함되지 않는건가요..?

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/MainViewController.swift
> +        }
[P2]
[`UICollectionViewDiffableDataSource`](https://developer.apple.com/documentation/uikit/uicollectionviewdiffabledatasource) 문서의 important 섹션을 읽어보시고 앞으로의 방향을 잡아보면 좋겠습니다~!

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/MainViewController.swift
> +    }
[P1]
Segment control을 통해 레이아웃을 변경했을 때 셀 자체가 사라지는 이유는 레이아웃이 깨져서가 아닐 수 있어요. 무언가 과정을 하나 빠뜨린 것이 있을 수 있습니다. 아래 문서를 읽어보시고 빠뜨린 과정이 있는지 확인해보세요~
- [`NSDiffableDataSourceSnapshot` - Apple Developer](https://developer.apple.com/documentation/uikit/nsdiffabledatasourcesnapshot)

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/MainViewController.swift
> +        return layout
[P4]
여기는 다른 곳과 다르게 반환하기 전에 한 칸 띄우셨네요. 어떤 의미가 있나요?

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/MainViewController.swift
> +    }
[P4]
Literal 값이 많이 등장하네요. `Metric` 네임스페이스로 값들을 관리해보는건 어떨까요?

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/OpenMarket.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 14.0;
`CellRegistration`과 `UICollectionLayoutListConfiguration`을 사용해보시려고 target os 버전을 올리셨네요 😎. `CellRegistration`을 사용하지 않고 `NSCollectionViewDIffableDataSource`와 `UICollectionViewCompositionalLayout`으로 기존 버전에서 동일한 레이아웃을 구성하는 방법은 없을까요?

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/OpenMarket/Base.lproj/Main.storyboard
> +                <viewController id="BYZ-38-t0r" customClass="MainViewController" customModule="OpenMarket" customModuleProvider="target" sceneMemberID="viewController">
코드 기반으로만 UI를 구성하고 계신데 스토리보드 파일을 유지하는 이유가 있을까요?

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/OpenMarket/CollectionViewCell/GridCollectionViewCell.swift
> +    }
이 이니셜라이저는 어떤 역할을 하나요? `fatalError` 처리가 된 것을 미루어보았을 때 절대 호출되지 않을 것이라 판단하고 계신 것으로 추측되는데 정말 그런가요? 이 이니셜라이저와 NSCoder의 의미와 역할을 파악해보면 좋을 것 같아요.

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/OpenMarket/CollectionViewCell/GridCollectionViewCell.swift
> +        stackView.translatesAutoresizingMaskIntoConstraints = false
의도된 공백일까요?

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/OpenMarket/CollectionViewCell/ItemCollectionViewCell.swift
> +    func showPrice(priceLabel: UILabel, bargainPriceLabel: UILabel, product: SaleInformation) {
[P4]
외부에서 활용되지 않는 메서드나 프로퍼티가 몇 가지 있는 것 같네요.

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/OpenMarket/CollectionViewCell/ItemCollectionViewCell.swift
> +        NetworkManager().fetch(request: URLRequest(url: url)) { [weak self] result in
`weak self`를 사용한 이유를 공유해주실 수 있으실까요?

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/OpenMarket/CollectionViewCell/ItemCollectionViewCell.swift
> +    let productThumnail: UIImageView = {
[P4]
프로퍼티의 이름을 통해 타입을 파악할 수 있도록 이름에 타입을 포함하면 좋을 것 같아요. `productThumbnailImageVIew`

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/OpenMarket/CollectionViewCell/ItemCollectionViewCell.swift
> +    let productName: UILabel = {
[P4]
마찬가지로 `productNameLabel`이라고 하면 좋겠네요.

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/OpenMarket/CollectionViewCell/ItemCollectionViewCell.swift
> +                guard let images = UIImage(data: data) else { return }
복수형 이름을 사용한 이유가 있을까요?

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/OpenMarket/CollectionViewCell/ItemCollectionViewCell.swift
> +                MainViewController().showNetworkError(message: NetworkError.outOfRange.message)
[P2]
본인을 소유한 ViewController 타입의 인스턴스를 새로 만들어 받아온 에러를 무시하고 새 에러를 표시하는 것은 좋지 않은 방법일 수 있을 것 같아요. 생성한 인스턴스가 Window에 있지 않기 때문에 동작하지 않을 것이기도 하고요. delegate와 같은 방식을 이용해 본인을 소유한 인스턴스에게 발생한 에러를 전달해주는 방식을 적용해보는건 어떨까요?

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/OpenMarket/CollectionViewCell/ListCollectionViewCell.swift
> +class ListCollectionViewCell: ItemCollectionViewCell {
상속을 이용해 기능을 확장해보셨네요. 프로토콜을 이용한 기능 확장과 비교해보았을 때 어떤 장단점이 있었나요?

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/OpenMarket/CollectionViewCell/ListCollectionViewCell.swift
> +        productPrice.setContentHuggingPriority(UILayoutPriority.required, for: .horizontal)
CRCH가 잘 적용되어 있네요. 👍

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/OpenMarket/CollectionViewCell/ListCollectionViewCell.swift
> +            imageStackView.heightAnchor.constraint(lessThanOrEqualToConstant: 80),
썸네일 이미지가 의도한 크기보다 작아보이는건 지정한 크기보다 작을 수 있음을 허용했기 때문으로 보이네요. 아마 `equalToConstant`로 크기를 지정하면 오토레이아웃 에러가 발생해서 이렇게 적용한 것 같은데, 어떤 방법으로 해결할 수 있을까요? 이 키워드로 시작해봅시다~! `uiview-encapsulated-layout-height`

2022-07-25 18:26 UTC, ryan-son commented on OpenMarket/OpenMarket/Model/NameSpace/CollectionViewNamespace.swift
> +    }
이렇게 연산프로퍼티를 정의하는 것과 `rawValue`를 정의하는 방식은 어떤 장단점이 있다고 생각하시나요?

2022-07-27 12:17 UTC, unchain123 commented on OpenMarket/MainViewController.swift
> +    private var snapshot = NSDiffableDataSourceSnapshot<Section, SaleInformation>()
1. snapshot은 데이타소스의 현재 상태를 저장하고 apply를 통해 로드 할 수 있습니다
2. setionc과 item은 hashable해야합니다.

2022-07-27 12:41 UTC, seohyeon2 commented on OpenMarket/MainViewController.swift
> +    private var count = 1
`productPageNumber`라고 수정했습니다~

2022-07-27 12:46 UTC, seohyeon2 commented on OpenMarket/MainViewController.swift
> +        setConstraint()
`setUI()` 메서드로 묶어주었습니다!

2022-07-27 12:49 UTC, seohyeon2 commented on OpenMarket/OpenMarket/CollectionViewCell/ItemCollectionViewCell.swift
> +                MainViewController().showNetworkError(message: NetworkError.outOfRange.message)
말씀해주신 방법으로 수정했습니다!

2022-07-27 13:02 UTC, unchain123 commented on OpenMarket/MainViewController.swift
> +        self.snapshot.appendSections([.main])
snapshot의 swction과 Item은 Hashable해야 합니다.

2022-07-27 13:03 UTC, unchain123 commented on OpenMarket/MainViewController.swift
> +                }
재귀적으로 호출하던 함수를 제거하고 prefatchDataSource를 사용하여 페이지를 새로 받아올 때마다 네트워크와 통신하여 페이지를 로드하는 로직을 구현해 보았습니다.

2022-07-27 13:07 UTC, unchain123 commented on OpenMarket/MainViewController.swift
> +    func configureListDataSource() -> UICollectionViewDiffableDataSource<Section, SaleInformation>? {
private 키워드를 붙여줬습니다.

2022-07-27 13:11 UTC, seohyeon2 commented on OpenMarket/OpenMarket/Model/NameSpace/CollectionViewNamespace.swift
> +    }
연산 프로퍼티를 사용하면 연관값으로 다양한 타입의 값을 가질 수 있다는 장점이 있습니다.
또한 rawValue라는 명칭 대신 연산 프로퍼티의 명칭으로 접근할 수 있어,
어떤 값을 뜻하는지 rawValue보다 명시적으로 의미전달을 할 수 있습니다.
다만, 연산 프로퍼티를 사용할 경우 모든 값에 대해 연관값을 지정해줘야하는 단점이 있습니다.

2022-07-27 13:16 UTC, unchain123 commented on OpenMarket/MainViewController.swift
> +        dataSource = UICollectionViewDiffableDataSource<Section, SaleInformation>(collectionView: collectionView) { (collectionView: UICollectionView, indexPath: IndexPath, product: SaleInformation)
린트만 믿었는데.. 배신당했네요.. typealias를 사용해서 타입의 길이를 줄이고 개행을 넣어줬습니다.

2022-07-27 13:19 UTC, seohyeon2 commented on OpenMarket/OpenMarket/CollectionViewCell/ListCollectionViewCell.swift
> +            imageStackView.heightAnchor.constraint(lessThanOrEqualToConstant: 80),
listLayout을 `UICollectionLayoutListConfiguration(appearance: .plain)` 이 아닌 
`NSCollectionLayout`을 사용하는 방향으로 코드를 수정하여 해결했습니다!

2022-07-27 13:25 UTC, unchain123 commented on OpenMarket/MainViewController.swift
> +        }
important에서 하나의 컬렉션 뷰에서 datasource를 바꾸면 안된다고 되어 있었기 때문에 datasource를 바꾸지 않고 cellregistration을 두개 해서 변경 해주는 방법을 선택 했습니다.

2022-07-27 13:33 UTC, seohyeon2 commented on OpenMarket/OpenMarket/CollectionViewCell/ListCollectionViewCell.swift
> +class ListCollectionViewCell: ItemCollectionViewCell {
상속의 경우 저장 프로퍼티를 사용할 수 있지만, 프로토콜을 이용한 기능 확장을 이용한 경우는 사용이 불가합니다.

상속은 한 개의 클래스만 상속 받을 수 있지만, 프로토콜 기능 확장 방식은 여러 프로토콜을 채택할 수 있습니다,
또한 상속은 클래스에서만 사용 가능한 반면에 POP는 class, struct, enum에 적용할 수 있습니다. 
위 두가지 이유로 상속은 프로토콜 기능 확장 방식 보다 덜 유연하다는 단점이 있습니다.

2022-07-27 13:34 UTC, unchain123 commented on OpenMarket/MainViewController.swift
> +    }
snapshot을 apply해주는 부분을 getProductList메서드 내에서만 하고 있다 보니 처음 getProductList메서드를 호출할 때만 snapshot이 적용되었고 이 때의 코드는 상품목록이 끝날 때까지 재귀적으로 찍어내는 함수였기 때문에 이 상품들을 모두 불러올 때 까지는 snapshot이 적용되어 셀이 유지 될 수 있었고 모두 불러낸 이후에는 셀이 보이지 않는 현상이었습니다. 
 그래서 이 스냅샷을 Apply해주는 과정을 SegementedControl에서 변경이 될 때 마다 각각 넣어 주어 해결 할 수 있었습니다.

2022-07-27 13:36 UTC, unchain123 commented on OpenMarket/MainViewController.swift
> +        return layout
단순 실수 였습니다. return값은 모두 전에 한칸을 띄우지 않는것으로 통일 해 주었습니다.

2022-07-27 13:36 UTC, seohyeon2 commented on OpenMarket/OpenMarket/CollectionViewCell/ItemCollectionViewCell.swift
> +                guard let images = UIImage(data: data) else { return }
큰 이유는 없었습니다😅
Swift API Design Guidelines를 따라 단수형으로 수정했습니다.

2022-07-27 13:36 UTC, seohyeon2 commented on OpenMarket/OpenMarket/CollectionViewCell/ItemCollectionViewCell.swift
> +    let productName: UILabel = {
수정했습니다!

2022-07-27 13:36 UTC, seohyeon2 commented on OpenMarket/OpenMarket/CollectionViewCell/ItemCollectionViewCell.swift
> +    let productThumnail: UIImageView = {
수정했습니다!

2022-07-27 13:36 UTC, unchain123 commented on OpenMarket/MainViewController.swift
> +    }
Metric 열거형을 만들어서 관리해 주었습니다.

2022-07-27 14:08 UTC, seohyeon2 commented on OpenMarket/OpenMarket/CollectionViewCell/ItemCollectionViewCell.swift
> +        NetworkManager().fetch(request: URLRequest(url: url)) { [weak self] result in
해당 클로저는 escaping 클로저라서 안에서 `[weak self]`를 사용하지 않으면, 강한참조가 되어 reference count가 증가됩니다. 이는 클로저가 종료되어도 count가 해제되지 않아 메모리 누수를 발생시킬 수 있게 됩니다.
이를 해결하기 위해 `[weak self]`를 사용하여 약한 참조가 되도록 했습니다.

2022-07-27 14:08 UTC, seohyeon2 commented on OpenMarket/OpenMarket/CollectionViewCell/ItemCollectionViewCell.swift
> +    func showPrice(priceLabel: UILabel, bargainPriceLabel: UILabel, product: SaleInformation) {
수정했습니다..!

2022-07-27 14:09 UTC, seohyeon2 commented on OpenMarket/OpenMarket/CollectionViewCell/GridCollectionViewCell.swift
> +        stackView.translatesAutoresizingMaskIntoConstraints = false
아닙니다..🥲
공백 삭제했습니다!

2022-07-27 14:10 UTC, seohyeon2 commented on OpenMarket/OpenMarket/Base.lproj/Main.storyboard
> +                <viewController id="BYZ-38-t0r" customClass="MainViewController" customModule="OpenMarket" customModuleProvider="target" sceneMemberID="viewController">
큰 이유는 없었습니다.
스토리보드 파일 삭제했습니다!

2022-07-27 14:10 UTC, unchain123 commented on OpenMarket/OpenMarket.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 14.0;
CellRegistration을 사용하지 않고 아래 사진과 같이 register를 활용하여 dataSource를 활용했습니다.
<img width="300" alt="스크린샷 2022-07-27 오후 11 09 14" src="https://user-images.githubusercontent.com/98506825/181268436-8d60fb16-d65d-46ba-9395-6f62d92a954c.png">

2022-07-27 14:52 UTC, unchain123 commented on OpenMarket/MainViewController.swift
> +        let networkManger = NetworkManager(session: urlSession)
오픈마켓II 에서 진행해 보면서 네트워크 타입을 분리 해서 적용하도록 하겠습니다.

2022-07-27 15:12 UTC, seohyeon2 commented on OpenMarket/OpenMarket/CollectionViewCell/GridCollectionViewCell.swift
> +    }
`requird init`은 자식 클래스에서 지정 이니셜라이저를 따로 작성하지 않는 경우 명시 해줘야하는 초기화 구문으로,
부모 클래스의 이니셜라이저들을 상속하기 위한 역할을 합니다. 

`NSCoder`는  아카이빙과 배포를 위해서 객체를 인코딩과 디코딩 하는 역할을 합니다.

원래는 절대 호출되지 않을 것이라 생각했는데.. 찾아보니 `fatalError`가 발생할 수 있는 경우는 잘못된 셀을 다시 가져올 때 라고 이번 피드백을 통해 알게 되었습니다!

2022-07-27 15:28 UTC, seohyeon2 commented on OpenMarket/MainViewController.swift
> +    private lazy var dataSource: UICollectionViewDiffableDataSource<Section, SaleInformation>? = configureListDataSource()
`dataSource` 프로퍼티 에 `lazy` 키워드 생략했습니다.

참고로 저희 생각에 dataSource는 한번만 초기화 되는 것을 보장 받아야 생각해서 저장 프로퍼티로 수정했지만,
피드백 주신 부분을 제외한 다른 지연 프로퍼티는 그대로 유지했습니다.

유지한 이유는 다음과 같습니다.
`collectionView`를 비롯한 다른 지연 프로퍼티는 UI 부분이라 오히려 `lazy` 키워드를 붙이는 것이 컴파일 시간도 줄일 수 있고, 
호출되는 시점에 생성이 되어 뷰가 로드될 때 메모리에 과부화되는 현상을 막아 메모리를 효율적으로 관리할 수 있다고 판단했기 때문입니다.

2022-07-28 17:52 UTC, ryan-son commented on OpenMarket/MainViewController.swift
> +        self.snapshot.appendSections([.main])
`Hashable`하기 때문에 아이템을 고유하게 인식할 수 있고, 동일한 hash값을 가진 아이템을 두 번 append하면 런타임 에러가 발생합니다.

2022-07-28 17:55 UTC, ryan-son commented on OpenMarket/OpenMarket/CollectionViewCell/GridCollectionViewCell.swift
> +    }
그럼 이 이니셜라이저가 호출된다는 의미일까요? '잘못된 셀을 다시 가져올 때'에 대해 자세히 설명해주실 수 있을까요?

2022-07-28 17:57 UTC, ryan-son commented on OpenMarket/OpenMarket/CollectionViewCell/ItemCollectionViewCell.swift
> +        NetworkManager().fetch(request: URLRequest(url: url)) { [weak self] result in
escaping closure는 항상 `weak` 방식으로 캡처해야 할까요? `weak` 키워드를 제거하고 디이니셜라이저를 통해 인스턴스가 정상적으로 해제되는지 확인해보면 좋을 것 같아요.

2022-07-28 17:59 UTC, ryan-son approved these changes
고생하셨습니다! 다음 프로젝트에서 만나요~ 👋

2022-07-28 17:59 UTC, merged