오픈마켓 II [STEP 1] Bonf, Finnn
yagom-academy/ios-open-market pull request #193
Opened 2022-07-29 08:04 UTC by finnn1

# 오픈 마켓 II STEP1 PR 💸

---

안녕하세요! 쿠마(@leejun6694) Bonf, Finnn입니다 😊
오픈 마켓 Step 3 PR 보냅니다!
이번에도 잘 부탁드립니다!! 🙏

---

# 구현 내용

|**상품등록**|**이미지 선택**|**Post**|
|:---:|:---:|:---:|
|![](https://i.imgur.com/LqXgcYQ.gif)|![](https://i.imgur.com/l14ZEQU.gif)|![](https://i.imgur.com/8fzFZmz.gif)|

---

# 궁금한 점 🤷🏻‍♂️
![](https://i.imgur.com/4CZZOMj.gif)

> **`UITextView`에 텍스트 입력시 자동 스크롤 :**
> 상품 설명을 위해서 `UITextView`를 `UIScrollView` 안에 넣는 방식으로 구현했습니다.
> `UITextView`에 텍스트를 입력할 경우 스크롤에 관련한 문제가 발생해서 질문드립니다. 😭
>
> `UITextView`의 `isScrollEnabled` 프로퍼티를 `true`로 설정하고, `UITextView`의 크기를 일정하게 고정시킬 경우, 텍스트 입력시 자동 스크롤이 정상적으로 되었습니다. 하지만 `UITextView` 내부에서만 자동스크롤이 될 뿐, **메인 `UIScrollView`가 동적으로 늘어나진 않았습니다.**
> 
> 이 때문에 메인 `UIScrollView`가 동적으로 늘어나도록 해주기 위해서 `UITextView`의 **`isScrollEnabled` 프로퍼티를 `false`로 설정해주었습니다.**
> 이 경우, 메인 `UIScrollView`의 길이가 `UITextView`의 내용에 따라 동적으로 늘어나긴 했지만, 입력하는 텍스트가 키보드 아래로 넘어갈 경우 **자동으로 스크롤이 되지는 않았습니다.**
> 
> 해당 문제를 해결하기 위해서 여러가지로 시도해봤지만 결국 해결되지 않아서 혹시 좋은 방법이 있는지 궁금합니다. 😢

---

# 고민한 점 🤔

#### 이미지가 추가되는 순서
> 이미지를 추가할 때, 이미지를 추가하는 버튼과 같은 `StackView`에 들어가 있어 정상적인 순서로 보여지지 않았습니다. 해당 `StackView`의 `arrangedSubviews`를 불러와 확인해 본 결과 다행히 스택에 들어가 있는 순서대로 인덱스가 할당되는 것을 확인했습니다. `arrangedSubviews`가 리턴해준 배열의 인덱스를 활용해서 리팩토링 한 결과, 이미지의 순서를 정상적으로 보여지게 할 수 있었습니다.

---

#### Description에서 여러 줄을 작성했을 때 DecodingError가 발생하는 문제 
> `Descripton`에 한 줄만 작성했을 경우 `Post`가 잘 되는 반면, 여러 줄을 작성하면 에러가 발생하였습니다. `LLDB`를 이용하여 `json` 데이터로 타입 변경하는 중 "\n"이 추가되지 않는 문제를 발견하였습니다.
따라서 """ 를 이용하여 저장되던 정보를 `Dictionary`를 사용하여 각 `String`을 저장하고, `JSONSerialization`를 사용하여 타입을 변경하였습니다.
```swift
let jsonData = try JSONSerialization.data(withJSONObject: parameterDictionary, options: [])
```

---

#### 갑자기 DecodingError가 발생하여 Decoding이 안되는 문제 
> 어떤 문제 때문인지 인지하는 것에도 시간이 꽤 걸릴 정도로 되던 것에서 문제가 발생하여 당황스러웠습니다. 문제는 `Double` 타입의 데이터가 저희가 구현한 이래로 처음 발생된 것이었습니다. `Double`로 들어오는 데이터의 모델 타입을 `Double`로 변경하여 문제를 해결하였습니다.

2022-07-31 12:50 UTC, leejun6694 requested changes
안녕하세요 Bonf, Finnn : )
`긴 코드 한줄`, `필요없는 줄바꿈`, `수행해야하는 역할이 많은 메서드` 등 가독성을 해치는 코드가 등장하는 것 같습니다.
한차례 정리가 필요해보입니다.

2022-07-31 12:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +
줄바꿈이 중간중간에 굉장히 많이 들어가있네요...!

2022-07-31 12:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +    func presentAlertMessage(message: String) {
access control !

2022-07-31 12:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +    override func loadView() {
뭔가 빠진거 같지 않나요...!

2022-07-31 12:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +        view = ProductDetailView()
`ViewController` 의 `기본 view` 를 바꿔준 이유가 궁금합니다 : )

2022-07-31 12:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +
중간중간 빈 줄바꿈들이 있네요. 확인 부탁드립니다.

2022-07-31 12:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +        }
에러는 따로 method 로 빼주면 어떨까요?

2022-07-31 12:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Views/ProductDetailView.swift
> +        mainScrollView.addSubview(mainStackView)
scroll view 안에 scroll view 가 있고, UITextView 까지 있어서 스크롤들이 겹치게될 것 같습니다.
Apple 은 `scroll 이 겹치는 것`을 지양해달라고 하고 있는데, 이를 해결할 수 있는 방법이 있을까요?

2022-07-31 12:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Views/ItemCollectionViewCell.swift
> +    func returnNameLabelText() -> String {
저는 `return` 을 메서드 네이밍으로 사용하는 것을 지양하고 있습니다..! (너무 컴퓨터 용어...ㅎㅎ)
`get` 이나 `다른 단어`로 대체하는건 어떨까요?

2022-07-31 12:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +import UIKit
Data 를 다루는 곳에서 UIKit 이 import 되어 있습니다.
꼭 필요한 경우가 아니라면 지양해볼까요?

2022-07-31 12:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +            guard let convertedImage = ImageInfo(withImage: $0) else { return }
에러 처리가 없어도 괜찮을까요?

2022-07-31 12:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +            let decoded = String(data: jsonData, encoding: .utf8)!
강제 언래핑은 지양해주세요❗️

2022-07-31 12:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +            print(decoded)
pr 제출 시엔, print 등 불필요한 코드를 삭제해주세요 : )

2022-07-31 12:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsViewController.swift
> +    override func viewWillAppear(_ animated: Bool) {
놓친 코드가 있네요~?

2022-07-31 12:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsViewController.swift
> +        guard let collectionView = collectionView else { return }
하나의 메서드 내 코드가 너무 많아보입니다.
분리할 수 있는 코드가 없을지 고민해볼까요?

2022-07-31 12:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +        let parameter = Parameters(name: productName, descriptions: productDesciprtion, price: productPrice, currency: productCurrency, secret: UserInfo.secret.rawValue, discountedPrice: productSale,
한줄의 코드가 너무 길어지는 경우는 적절한 줄바꿈을 부탁드려요~

2022-07-31 12:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +        return textField == detailView.itemNameTextField && detailView.itemSaleTextField.text?.isEmpty ?? false && detailView.itemStockTextField.text?.isEmpty ?? false
보통은 && 앞에서 줄바꿈을 많이 해줘요~!
줄이 너무 길어지네요...!

2022-07-31 12:50 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +    let imageChangePicker = UIImagePickerController()
picker 가 꼭 두개로 나눠져야할까요?
다른 값을 활용해보는건 어떨까요?

2022-08-01 06:56 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +
줄바꿈 삭제했습니다! 🙏

2022-08-01 06:57 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +    func presentAlertMessage(message: String) {
접근 제어 private 으로 설정했습니다 ☺️

2022-08-01 07:07 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +        view = ProductDetailView()
기본 뷰를 그대로 사용할 경우, `ViewController`에서 `View`의 화면을 구성하는 코드도 들어 갈 것 같아서 MVC 패턴을 적용하고자 View를 분리해주었습니다 ☺️ 혹시 더 좋은 방법이 있을까요?

2022-08-01 07:08 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +
넵 리뷰 남겨주신 부분 공백 제거했습니다! 🙏

2022-08-01 07:11 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +        }
그러네요! 메서드로 분리해서 가독성이 높아진 것 같습니다 ☺️ 감사합니다 🙏

2022-08-01 07:13 UTC, finnn1 commented on OpenMarket/OpenMarket/Views/ItemCollectionViewCell.swift
> +    func returnNameLabelText() -> String {
좀 더 알아보기 쉽도록 네이밍을 `return`을 `get`으로 변경해주었습니다

2022-08-01 07:14 UTC, finnn1 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +import UIKit
앗 그러네요! `UIKIt` 전체가 아닌 `NSDataAsset` 만 `import` 하도록 리팩토링 해주었습니다!

2022-08-01 07:18 UTC, finnn1 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +            guard let convertedImage = ImageInfo(withImage: $0) else { return }
이미지가 변환에 실패해도 나머지 작업들을 수행할 수 있도록 return을 없애고, if let 구문으로 바꾸어주었습니다!

2022-08-01 07:20 UTC, finnn1 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +            let decoded = String(data: jsonData, encoding: .utf8)!
해당 부분은 확인용으로 작성했었는데 미처 지우지 못했던 것 같습니다 😢
해당 부분 삭제했습니다!

2022-08-01 07:20 UTC, finnn1 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +            print(decoded)
해당 부분은 확인용으로 작성했었는데 미처 지우지 못했던 것 같습니다 😢
해당 부분 삭제했습니다!

2022-08-01 07:21 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsViewController.swift
> +    override func viewWillAppear(_ animated: Bool) {
앗 super.viewWillAppear 메서드를 깜빡했네요!
추가해주었습니다 감사합니다 🙏

2022-08-01 07:33 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsViewController.swift
> +        guard let collectionView = collectionView else { return }
내부에 역할이 많은 것 같아 메서드로 나누어주었습니다!

2022-08-01 07:38 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +        let parameter = Parameters(name: productName, descriptions: productDesciprtion, price: productPrice, currency: productCurrency, secret: UserInfo.secret.rawValue, discountedPrice: productSale,
파라미터 단위로 줄바꿈을 해주었습니다!

2022-08-01 07:38 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +        return textField == detailView.itemNameTextField && detailView.itemSaleTextField.text?.isEmpty ?? false && detailView.itemStockTextField.text?.isEmpty ?? false
&& 앞에서 줄바꿈 해주었습니다! 감사합니다 🙏

2022-08-01 07:57 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +    let imageChangePicker = UIImagePickerController()
imagePicker 를 하나로 통일해습니다 ☺️

2022-08-01 08:34 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +    override func loadView() {
loadView 제거 했습니다! 🙏

2022-08-01 08:35 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +        view = ProductDetailView()
커스텀 뷰를 컨트롤러 내의 프로퍼티로 만들어서 사용하는 방식으로 리팩토링 했습니다! ☺️

2022-08-02 16:47 UTC, leejun6694 approved these changes
step 1 리뷰 내용을 반영하느라 고생 많으셨습니다~!
detail view 관련해서 디코로 좀 더 얘기를 나누면 좋겠네요 : )

2022-08-02 16:47 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +    let imagePicker = UIImagePickerController()
`ViewController` 가 생성될 때, 꼭 같이 생성하진 않아도 될 것 같습니다.
`lazy` 를 사용해보는건 어떨까요?

2022-08-02 16:47 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +    var selectedImageView: UIImageView?
access control ...!!

2022-08-02 16:47 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +    private func presentAlertMessage(message: String) {
Life Cycle 과는 다른 분류의 method 로 보입니다.
구분해주면 더 좋겠네요~

2022-08-02 16:47 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +        view = detailView
detailView 가 view 를 대체하는건 같이 디코로 얘기해봐요~~!

2022-08-02 16:47 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +        } else if detailView.itemPriceTextField.text?.isEmpty ?? true {
`else if detailView.itemPriceTextField.text?.isEmpty == true`
로 조건을 해주는건 어떨까요?
isEmpty 의 default value 가 true 인 경우는 조금 어색하네요~!

2022-08-02 16:47 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +        if let selectedImageView = selectedImageView {
imageView 가 아닌 image 로 체크해도 되겠네요~!?

2022-08-02 16:47 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +        }
```
ProductsDataManager.shared.postData(
   identifier: UserInfo.identifier.rawValue,
   paramter: parameter,
   images: images
) { (data: PostResponse) in
   DispatchQueue.main.async {
```

저는 요렇게 줄바꿈 하는 스타일이에요~ 참고만 해주세요 : )

2022-08-02 16:47 UTC, leejun6694 commented on OpenMarket/OpenMarket/Controllers/ProductsViewController.swift
> +                collectionView.scrollToItem(at: topCellIndexPath, at: .top, animated: false)
몇 `parameter` 만 다르고 전체적으로 같은 구조의 코드가 반복되고 있습니다.
`case` 에 따른 변수들을 만들고, 구현은 하나로 정리해보면 어떨까요?

2022-08-02 16:47 UTC, leejun6694 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +struct ImageInfo {
ImageInfo 를 위한 파일을 따로 만들면 어떨까요?

2022-08-02 16:47 UTC, merged

2022-08-03 06:53 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +    let imagePicker = UIImagePickerController()
앗 그러네요! lazy var로 수정해주었습니다 ☺️

2022-08-03 06:53 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +    var selectedImageView: UIImageView?
`private` 붙여주었습니다 🙏🙏

2022-08-03 06:57 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +    private func presentAlertMessage(message: String) {
해당 메서드 extension으로 빼서 구분해주었습니다!

2022-08-03 07:00 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +        view = detailView
`detailView`를 `view`에 `addSubView`로 넣어주었습니다 🙏🙏

2022-08-03 07:17 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +        } else if detailView.itemPriceTextField.text?.isEmpty ?? true {
앗 옵셔널끼리 바로 비교 가능한 것을 생각하지 못했네요 😭
`==` 연산자로 수정했습니다! 🙏

2022-08-03 07:23 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +        if let selectedImageView = selectedImageView {
image로 체크해주었습니다! ☺️

2022-08-03 07:24 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsDetailViewController.swift
> +        }
오 훨씬 깔끔하네요! 해당 컨벤션으로 수정했습니다 ☺️
감사합니다 🙏🙏

2022-08-03 07:52 UTC, finnn1 commented on OpenMarket/OpenMarket/Controllers/ProductsViewController.swift
> +                collectionView.scrollToItem(at: topCellIndexPath, at: .top, animated: false)
말씀해주신 리뷰 참고하여 리팩토링 했습니다! ☺️
감사합니다 🙏

2022-08-03 07:53 UTC, finnn1 commented on OpenMarket/OpenMarket/Models/ProductsDataManager.swift
> +struct ImageInfo {
해당 구조체를 별도의 파일로 분리해주었습니다! ☺️