오픈마켓 II [STEP1] unchain, heyon2
yagom-academy/ios-open-market pull request #197
Opened 2022-08-02 10:12 UTC by unchain123

# PR
오픈마켓 II
안녕하세요 라이언! @ryan-son  🦁
Step1 PR 보냅니다.
점심시간이 좀 길어 졌습니다,,
저녁시간이 됐네요..ㅎㅎ
이번 스텝도 잘 부탁 드립니다!!🙇🏻‍♀️🙇🏻

---
### ⚙️ 코드 소개

- postProduct() : 서버에 "POST"를 하는 메서드
- createPostRequest(): "POST"의 Request를 만드는 메서드
- createPostBody(): "POST"의 body를 만드는 메서드
- createPostImage(): "POST"할 이미지를 데이터로 바꿔주는 메서드
- compress(): "POST"할 이미지를 300KB이하로 제한해주는 메서드
- postSecret(): "DELET"를 위한 상품 시크릿키를 서버로 부터 받아오기 위한 메서드

- patchProduct(): "PATCH"를 실행하는 메서드
- deleteProduct(): "DELETE"를 실행하는 메서드
- imagePickerController(): 사진을 추가하는 메서드
- showCustomAlert(): 얼럿메세지를 커스텀하는 메서드
- @objc goBackMainViewController: "cancel"버튼을 터치 했을 때 원래 화면으로 복귀 하는 메서드
- @objc registerProduct(): "done"버튼이 터치되면 postProduct를 실행하는 메서드
- resetRegistrationPage(): "done"버튼을 터치하고 나면 상품등록화면을 초기화 하는 메서드

### ⭐️ 궁금한 점 및 조언 얻고 싶은 점

#### 1. 이미지를 줄이는 과정에서 jpegData(compressionQuality: quality)사용시 용량 제한이 되는게 맞는지 
- 이번 프로젝트를 진행하는 과정에서 업로드할 이미지의 크기를 300KB이하로 제한 해야 한다는 기술 요구서를 보고 어떻게 용량 제한을 해줘야 할 지 고민 하다가 아래와 같은 로직의 메서드를 짜게 되었습니다.
- 테스트 결과 아래의 메서드를 사용하게 되면 확연하게 줄어든 이미지의 용량을 확인 할 수는 있었지만 과연 이게 300KB를 제한하는 메서드가 맞는지는 의문이 들었습니다. 
- jpegData(compressionQuality: CGFloat)은 명확하게 얼마의 용량으로 압축이 되는게 아닌 0~1까지 소수점 단위의 quality로만 압축하고 있었습니다.
- 이렇게 되면 300kb보다 큰값이 나오게 되는 경우도 있다고 판단되는데 이걸 막기 위해서 추가로 분기를 만들어서 처리해 주는게 맞는지 아니면 이미 만들어져 있는 메서드가 있는지 궁금합니다.
```swift
   func compress() -> Data? {
        let quality: CGFloat = 300 / self.sizeAsKilobyte()
        let compressedData: Data? = self.jpegData(compressionQuality: quality)
        return compressedData
    }
    
    private func sizeAsKilobyte() -> Double {
        guard let dataSize = self.pngData()?.count else { return 0 }
        
        return Double(dataSize / 1024)
    }
```

#### 2. 상품등록 화면에서 다시 돌아올 때 리셋이 안됨
- 상품등록 후, 새롭게 등록한 상품을 화면에 보여주기 위해 아래와 같이 `getProductList`를 `viewDidLoad`에서 `viewWillAppear`로 변경했습니다.
- 이와 같이 변경해주면, `viewWillAppear`가 될 때 새 상품이 cell에 보여지지만 순서가 엉망인 상태로 cell에 들어오게 됩니다.
- 새 상품이 들어온걸 화면에 바로 표시하려면 어떤 방식으로 접근하는게 좋을 지 궁금합니다.
```swift
override func viewWillAppear(_ animated: Bool) {
    getProductList(pageNumber: Metric.firstPage, itemPerPage: Metric.itemCount)
}
```

#### 3. httpbody에 "Content-Type: image/png\r\n\r\n"으로 넣어도 모든 파일이 들어감
- 처음 "POST"를 하기 위해 httpbody를 추가 할 때 content-Type이 추가할 사진의 확장자명과 body에 들어가는 확장자명을 맞춰줘야 한다고 생각해서 여러가지 메서드를 찾아 봤지만 찾지 못했습니다.
- 처음 POST를 테스트 할 때 png파일을 보낼 때 body에 jpeg나 jpg를 쓰면 POST가 되지 않았어서 그렇게 판단을 하고 방법을 찾고 있었는데 어떤 로직이 변경 됐는지 정확히 파악하지 못했지만 마지막으로 테스트를 진행할 때는 png파일이어도 body를 jpeg를 써도 POST가 되고 jpg파일도 png로 body를 작성해도 POST가 되는 현상이 발생했습니다.
- body에서 저 부분에 써주는 확장자는 의미가 없는것인지 아니면 저희가 만든 로직에서 어떤 작용을 하고 있는건지 궁금합니다.

2022-08-03 20:42 UTC, ryan-son requested changes
언체인, 현이! STEP 1 수행하시느라 고생 많으셨습니다~! 형식에 민감한 multipart/form-data 꼴로 만들어보시느라 고군분투한 모습이 엿보이네요.

이번 피드백은 글로 표현하는 것보다 회의실에서 큰 맥락을 같이 짚어보는 시간을 가지면 좋을 것 같아요. 질문해주신 내용에 대해서는 답변을 달아둘테니 궁금하신 점이 있으시면 회의실에서 이야기 나누어보시죠~

# 질의응답
>1. 이미지를 줄이는 과정에서 jpegData(compressionQuality: quality)사용시 용량 제한이 되는게 맞는지 

메서드 매개변수 이름 그대로 이미지 품질을 낮추는 방식으로 이미지를 압축합니다. 다만 jpeg 이미지로 1은 가장 높은 품질, 0은 가장 낮은 품질을 의미하는 것일 뿐 품질을 0으로 설정한다고해서 파일 크기가 0이 되는 것은 아닙니다. 따라서 여러분께서 작성해주신 아래 구문이 파일 크기를 반드시 300 kB로 제한하는 것은 아닙니다.

```swift
let quality: CGFloat = 300 / {PNG 이미지 데이터 크기}
let compressedData: Data? = self.jpegData(compressionQuality: quality)
```

위 코드에서 살펴볼 점은 두 가지가 있습니다.
1. 압축 품질이 파일 크기를 단순히 0 ~ 100 %로 나타내는 것이 아님
2. 무손실 압축 형식인 PNG의 크기를 기준으로 JPEG 압축 품질을 결정함

1 번은 앞서 언급한 내용과 같은 내용이고, 2 번은 이미지 형식의 특성과 관련된 내용입니다. 이와 관련해서는 같은 이미지에 대해 `pngData()`와 `jpegData(compressionQuality: 1)`의 결과를 비교해보시면 명확할거에요. 이번 기회에 왜 이런 차이가 발생하는지도 학습해두시면 좋을 것 같네요. 1 번 내용도 `jpegData(compressionQuality: 1)`과 `jpegData(compressionQuality: 0.9)` 정도만 비교해보셔도 바로 이해되실겁니다(품질을 조금만 낮추어도 파일 크기를 엄청나게 낮출 수 있는 원리에 대해서는 회의실에서 함께 알아보도록 합시다).

결국 이 기능을 개발하려면 `jpegData(compressionQuality:)` 메서드에 0 ~ 1 사이의 값 중 어떤 값을 인자로 전달할 것인지 탐색해야 합니다. 여기에서 binary search와 같은 방식으로 여러분의 알고리즘 구현 능력을 뽐내보셔도 좋고, 특정한 step 단위를 정해서 반복문을 돌려보셔도 좋습니다.

>2. 상품등록 화면에서 다시 돌아올 때 리셋이 안됨

등록을 하면 상품 목록으로 pop 시키면서 이전 시간에 알아보았던 인스턴스 간 커뮤니케이션 방식 4가지 중 하나를 이용해 목록을 갱신하게 만들면 되지 않을까요? 갱신 과정은 기존 목록을 제거하는 과정도 포함하고 있다는 것을 기억해둡시다~!

>3. httpbody에 "Content-Type: image/png\r\n\r\n"으로 넣어도 모든 파일이 들어감

아래 RFC를 통해 `multipart/form-data`에서 각 파트의 `Content-Type`은 optional 사항임을 알 수 있습니다. 하지만 파일일 경우 명확히 작성하되, 해당하는 것이 없으면 `application/octet-stream`을 사용하라고 하네요. 🤔
- [RFC 7578 - Returning Values from Forms: multipart/form-data - IETF](https://tools.ietf.org/html/rfc7578)
![image](https://user-images.githubusercontent.com/69730931/182706367-12557dbc-e679-4cf8-ae3d-9b79255de008.png)

실제로 `Content-Type`이 들어갈 자리에 어떤 내용을 넣어도 문제 없이 서버에 리소스가 생성되는 모습을 보실 수 있으실텐데, RFC 권고와 달리 잘 동작하는 이유는 무엇일까요? 그 원리는 저도 정확히는 파악하기가 어렵네요. 구현하신 분을 찾아야할 시점인 것 같아요. 아마도 [MIME sniffing](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#mime_sniffing)과 유사한 방식을 사용하는게 아닌가 추측합니다. 다만 MIME sniffing은 외부 공격에 취약해 보안 문제가 있어 [X-Content-Type-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options) 헤더를 통해 스니핑을 방지하는 경우가 많으므로 서버에서 전달받은 내용을 올바르게 다루어 문제가 일어나지 않을 수 있도록 RFC 7578의 권고사항과 같이 `Content-Type`을 정확히 전달해 주는 것이 좋습니다.

# 의견
- 코드 소개 섹션을 통해 각 메서드가 수행하는 역할을 PR에 작성하시기보다 코드가 이용되고 유지보수되는동안 참고할 수 있도록 문서화 주석을 통해 관리해보는건 어떨까요? 참고할만한 링크를 남겨둘게요.
- [Markup Formatting Reference - Apple Developer Documentation Archive](https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_markup_formatting_ref/SymbolDocumentation.html)
- [Swift Documentation - Sarunw](https://sarunw.com/posts/swift-documentation/)

그럼 계속해서 화이팅입니다 ! 💪

2022-08-03 20:42 UTC, ryan-son commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        let postData = OpenMarketRequest().createPostBody(parms: newParms as [String: Any], images: images)
[P4]
`OpenMarketRequest` 타입의 인스턴스가 필요한 것이 아니라면 관련된 메서드를 모두 타입 메서드로 변경해도 괜찮을 것 같은데, 어떻게 생각하시나요?

2022-08-03 20:42 UTC, ryan-son commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        fetch(request: request) { result in
[P3]
메서드 이름은 `post`인데 내부적으로 `fetch` 메서드를 호출하는 것이 부자연스러워 보일 수 있을 것 같네요. 네트워크 '요청' 또는 네트워킹 '수행'과 같은 이름을 사용해보는건 어떨까요?

2022-08-03 20:42 UTC, ryan-son commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        var request = URLRequest(url: url, timeoutInterval: Double.infinity)
[P3]
timeout이 발생할 시간을 적절히 설정해서 사용자의 네트워크 환경이 좋지 않다면 네트워크 환경 개선하도록 사용자에게 요청해보는건 어떨까요? 여러분들이 이용하시고 계신 앱에서는 네트워크가 연결되지 않은 상태를 어떻게 처리하고 있나요?

2022-08-03 20:42 UTC, ryan-son commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +            }
[P4] 
indentation 단위가 다른 곳과 달라보이네요. 에러처리도 `print`보다 좋은 방법이 있을 것 같아요.

2022-08-03 20:42 UTC, ryan-son commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        request.addValue(identifier, forHTTPHeaderField: Request.identifier)
[P3]
요청을 생성할 때마다 반복적으로 이 작업을 수행하네요. header에 `identifier`를 설정하는 작업은 authentication의 일환이라 매 요청시마다 필요할 것 같은데, 더 쉽게 작업하는 방법은 없을까요?

2022-08-03 20:42 UTC, ryan-son commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        }
아직 만드시는 중이시겠죠~? 😉

2022-08-03 20:42 UTC, ryan-son commented on OpenMarket/OpenMarket/Network/OpenMarketRequest.swift
> +            postData.append(form: Multipart.imageContentDisposition + "\"\(arc4random()).jpg\"" + Multipart.lineFeed)
여러분께서 적용하신 `SwiftLint`에서는 `arc4random()` 메서드가 legacy API라 권장하지 않는다고 하는 것 같은데, 이 메서드를 이용하신 이유가 있으실까요?

2022-08-03 20:42 UTC, ryan-son commented on OpenMarket/OpenMarket/ViewController/MainViewController.swift
>                  }
[P3]
`fatalError`를 적용하기엔 아직 실수할 여지가 있어보이네요. 정말 `fatalError`를 이용할 예정이라면 literal string이 전혀 개입되지 않는 방식을 고안해서 type-safe한 방식으로 register하고 reusableCell을 dequeue할 수 있도록 만들어보면 좋겠어요.

2022-08-03 20:42 UTC, ryan-son commented on OpenMarket/OpenMarket/ViewController/RegistrationViewController.swift
> +        button.addTarget(self, action: #selector(registerProduct), for: .touchUpInside)
iOS 14부터 `addTarget(_:action:for:)`을 대체할 재미있는 API들이 출시되었으니 살펴보세요~
- [`addAction(_:for:)` - Apple Developer](https://developer.apple.com/documentation/uikit/uicontrol/3600490-addaction/)
- [`UIAction` - Apple Developer](https://developer.apple.com/documentation/uikit/uiaction)
- [`init(title:image:identifier:discoverabilityTitle:attributes:state:handler:)` - Apple Developer](https://developer.apple.com/documentation/uikit/uiaction/3358590-init)
- [`init(type:primaryAction:)` - Apple Developer](https://developer.apple.com/documentation/uikit/uibutton/3600777-init)

2022-08-03 20:42 UTC, ryan-son commented on OpenMarket/OpenMarket/ViewController/RegistrationViewController.swift
> +    }
Observer를 제거하는 과정은 꼭 필요한 것인지, 만약 제거해줄 것이라면 어느 시점에 해주는 것이 적합할지 아래 문서를 통해 알아보면 좋겠습니다~!
- [`addObserver(_:selector:name:object:)` - Apple Developer](https://developer.apple.com/documentation/foundation/notificationcenter/1415360-addobserver)
- [`removeObserver(_:name:object:)` - Apple Developer](https://developer.apple.com/documentation/foundation/notificationcenter/1407263-removeobserver)

2022-08-03 20:42 UTC, ryan-son commented on OpenMarket/OpenMarket/ViewController/RegistrationViewController.swift
> +    }
매 ViewController마다 Alert를 보여주는 메서드는 꼭 작성하게되지 않나요~? 일을 조금 줄여보는 방법은 없을까요?

2022-08-03 20:42 UTC, ryan-son commented on .gitignore
>  #           - AS PER https://guides.cocoapods.org/using/using-cocoapods.html NEVER IGNORE THE LOCK FILE
이 자료는 한 번 읽어보면 도움이 될 것 같네요.
- https://guides.cocoapods.org/using/using-cocoapods.html

2022-08-04 05:28 UTC, unchain123 commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        let postData = OpenMarketRequest().createPostBody(parms: newParms as [String: Any], images: images)
OpenMarketRequest타입의 인스턴스가 필요없다고 판단되어 타입메서드로 변경하였습니다.

2022-08-04 05:51 UTC, seohyeon2 commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        fetch(request: request) { result in
`networkPerform`으로 수정했습니다.

[refactor: 네트워크 통신하는 메서드 명을 networkPerform으로 변경](https://github.com/yagom-academy/ios-open-market/pull/197/commits/21e1e06794531523de0f0a3e8f2e61c4443a6d98)

2022-08-04 14:43 UTC, seohyeon2 commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        var request = URLRequest(url: url, timeoutInterval: Double.infinity)
request = URLRequest(url: url, timeoutInterval: Double.infinity)테스트해본 결과,

2022-08-04 14:58 UTC, seohyeon2 commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        var request = URLRequest(url: url, timeoutInterval: Double.infinity)
`request`의 `timeoutInterval`이 일어난 경우를 테스트해 본 결과, 아래 사진 같이 앱 자체에서 얼럿창으로 알려주고 있었습니다.
저희 생각엔 `URLSession` 쪽에서 자체적으로 이 얼럿창이 뜨게 한 것 같은데, 정확히 어디에서 뜨는지 찾지 못했습니다😓
혹시 이 얼럿창이 어디서 뜨는지 알고 계시다면 답변 부탁드립니다..!

또한 얼럿창을 끈 다음엔, 저희가 만든 `UIActivityIndicatorView`가 실행되게 처리하고 있습니다!
| 애플 제공 | 우리 제공 |
| :--: | :--: |
|<img src = "https://user-images.githubusercontent.com/50102522/182878928-8effa8f3-1bb7-46e1-b93f-b990e2a9f606.png" width = 200 height = 400>|<img src = "https://user-images.githubusercontent.com/50102522/182879475-afcc9262-1bf6-4b34-89f5-0481682e9504.png" width = 200 height = 400>|

2022-08-04 15:00 UTC, seohyeon2 commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +            }
얼럿창으로 에러 띄우게 수정했습니다!

2022-08-04 15:01 UTC, seohyeon2 commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        }
`print`로 처리했던 에러처리 모두 얼럿창으로 수정했습니다😂

2022-08-04 15:05 UTC, seohyeon2 commented on OpenMarket/OpenMarket/Network/OpenMarketRequest.swift
> +            postData.append(form: Multipart.imageContentDisposition + "\"\(arc4random()).jpg\"" + Multipart.lineFeed)
참고한 예제에서 `arc4random()` 를 사용하고 있어서 똑같이 진행했었습니다..😅
`arc4random()` 대신 `images.description.hashValue`를 사용하여 이미지마다 다른 값을 갖도록 수정했습니다.

2022-08-04 15:08 UTC, seohyeon2 commented on OpenMarket/OpenMarket/ViewController/RegistrationViewController.swift
> +    }
`UIViewController`를 `extension` 하여 얼럿을 생성하는 메서드를 넣어주었습니다.
이를 통해 모든 ViewController에서 사용할 수 있게 했습니다!

2022-08-04 15:09 UTC, unchain123 commented on OpenMarket/OpenMarket/ViewController/RegistrationViewController.swift
> +    }
removeObserver메서드의 공식문서를 확인하여 아래와 같은 문구를 확인 할 수 있었습니다.
저희가 만든 앱은 iOS버전 14.0이상을 지원하고 있기 때문에 아래에서 언급하는 iOS 9.0이상에 해당하므로 removeObserver메서드를 해줄 필요가 없다고 판단하여 삭제 했습니다.
<img width="1160" alt="removeobserver" src="https://user-images.githubusercontent.com/98506825/182881396-7a64e898-20c6-4f85-96d7-307eeecac5a3.png">

2022-08-04 15:23 UTC, seohyeon2 commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        request.addValue(identifier, forHTTPHeaderField: Request.identifier)
회의실에서 알려주신 방법을 토대로 다음 스텝 때 적용하여 PR 드리도록 하겠습니다!

2022-08-04 15:23 UTC, unchain123 commented on OpenMarket/OpenMarket/ViewController/MainViewController.swift
>                  }
fatalError 대신 빈 셀을 리턴하는 방식으로 변경하였습니다.
회의실에서 말씀 해주셨던 방법은 아직 저희가 사용해 보기에는 좀 더 공부가 필요 할것 같다고 판단되어 추후에 공부를 한 후에 반영을 해 보도록 하겠습니다.

2022-08-07 02:41 UTC, ryan-son commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        fetch(request: request) { result in
[P4]
타입 이름이 `NetworkManager`이니 `perform`이라고만 해도 이해할 수 있을 것 같아요~

2022-08-07 02:43 UTC, ryan-son commented on OpenMarket/OpenMarket/ViewController/RegistrationViewController.swift
> +    }
네, 좋습니다. 필요한 경우 observer의 적절한 제거 위치는 deinit 시점이라는 것을 기억해두시면 됩니다!

2022-08-07 02:43 UTC, merged