Step 1 : 모델 및 네트워킹 담당 타입 구현 (리나, 찌로)
yagom-academy/ios-open-market pull request #2
Opened 2021-01-26 07:07 UTC by zziro95

[구현 내용]
 - JSON 데이터를 받기 위한 타입 ProductList, Product 구현
 - API에 요청하는 부분과 JSON 디코딩하는 부분을 나누기 위해서 completionHandler 사용
 - Error에 대한 처리를 뷰 컨트롤러에서 한꺼번에 하기 위해 중첩 completionHandler 사용

[고민 내용]
 - OpenMarketAPIManager의 메서드를 이용하기 위해 인스턴스를 생성하는 것보다  static 함수로 만들어서 바로 접근 할 수 있게 구현했는데, 그러다 보니 메서드간의 접근을 위해 다른 함수까지 static 함수로 만들어야 하는 상황이 발생하였습니다.
 - static 함수의 사용 이유는 접근을 좀 더 쉽게 하기 위해 static 함수를 사용하였는데, 인스턴스를 생성해서 접근하는게 더 권장하는 방법인지? 고민이 되었습니다.

2021-01-27 12:06 UTC, cmindy requested changes
리나, 찌로 고생하셨습니다!! 👏 
네트워크 쪽을 나눠서 구성해주신게 인상적이네요! (개인적으로 조금 범용적으로 사용할 수 있도록 다듬어서 패키지로 만들어보는 것도 추천드려용. 전에 해봤는데 이렇게 하면 다른 플젝에서도 재활용가능해서 신기하더라구요ㅋㅋㅎㅎ... ~TMI..~)

몇가지 개선할 점에 대해 코멘트를 남겨놓았으니 확인해보시고 궁금한게 있다면 언제든 코멘트나 dm해주세요!

2021-01-27 12:06 UTC, cmindy commented on OpenMarket/OpenMarket/Model/Product.swift
> +struct Product: Codable {
LGTM 💖

2021-01-28 12:07 UTC, zziro95 commented
@cmindy 
코멘트에 대해서 생각해보고 수정 적용해봤습니다~ 확인부탁드려요:)

[주요 수정 사항]
- mock 값을 이용해 테스트하기위해 타입구현 & 테스트


[주요 질문!!]
> 구조체명은 `OpenMarketJsonDecoder`라서 오픈마켓에 대한 모든 처리를 해줄 것 같은데 타입에 제네릭이 설정되어있어서 디코딩할 타입이 달라질때마다 이 구조체를 새로 생성해줘야겠네요 👀 개선할 방법이 있을까요?

대답: 타입메서드를 사용하고 있어서 구조체 인스턴스를 생성하지 않고 있고, 디코딩해야 하는 타입이 Product, ProductList 두가지 타입이여서 제네릭설정을 통해 두가지타입으로 메서드를 사용하고 있습니다.

`(제네릭에 대한 학습이 부족해서 질문이 좀 어수선하다고 생각이 들긴하지만 저희 나름 최대한 정리해보았습니다!)`
궁금사항: `디코딩할 타입이 달라질때마다 이 구조체를 새로 생성해줘야겠네요?` 라는 말을 정확히 이해를 못한것 같아요.  
디코딩하는 함수에 접근할때 `OpenMarketJSONDecoder<Product or ProductList>.decodeData()` 로 접근을 하게 되서 문제가 없을거라고 생각을 했습니다.
아니면 제네릭 함수를 사용하는게 개선 방법인지??? 궁금합니다.


[코멘트에 대한 대답~!!]
> 네트워크 쪽을 나눠서 구성해주신게 인상적이네요! (개인적으로 조금 범용적으로 사용할 수 있도록 다듬어서 패키지로 만들어보는 것도 추천드려용. 전에 해봤는데 이렇게 하면 다른 플젝에서도 재활용가능해서 신기하더라구요ㅋㅋㅎㅎ... ~~TMI..~~)

- 프로젝트 마무리 단계때 이 부분에 알아보고 패키지로 만들어 보고자 합니다!

> `description`을 이용한 것과`case get = "GET"` 하는 것과 어떤 차이가 있나요?

`case get = "GET"` 을 하는 경우 GET이라는 문자열 값을 얻어오려면 case의 rawValue로 접근을 해야하는데, `CustomStringConvertible`프로토콜을 준수하는 경우 `description` 에 출력하고 싶은 형태를 만들면 case까지만 접근을 해도 GET이라는 문자열을 받아올 수 있습니다. (LocalizedError에 대해 공부후 적용하여 결국 localizedDescription를 이용하였습니다.)


> Error 타입을 따로 구현해주셨네용 굿굿 💯
> 이 `StringFormattingError` 가 사용되는 곳이나 케이스를 보면 네트워크 에러일때도 이 error로 처리하는 것 같네요.
> 네이밍을 변경하거나 역할을 구분해주는 게 좋지 않을까요 ?

NetworkError와 JSONError로 구분해보려 했지만 컴플리션 핸들러가 중첩되어 있어서 분리가 어려웠습니다.
`Alamofire`에서 에러네이밍에 대해 봤는데 AFError로 되어있어서 통합적인 네이밍인  OpenMarketError로 바꿨습니다.


> `LocalizedError` 라는 타입을 찾아보셔도 좋을 것 같아용 ❣️
> 이걸 쓰려면,, `import Foundation`을 먼저해줘야겠네요 😂

`LocalizedError` 에 대해 공부후 적용해 보았고,  `import Foundation` 을 선언해야하는 이유에 대해서도 `Foundation` 프레임워크 문서를 살펴보아 알게되었습니다.


> `decodeData` 함수가 안에서는 네트워크 코드를 사용하고 있네요.
> 실제로 네트워킹을 통해 이뤄지기 때문에 속도도 느리고 , 인터넷 연결을 끊고 테스트를 실행하게 되면 실패하겠죠? 😢
> 네트워킹을 하는게 아니라 로컬에서 mock값을 이용해 테스트를 하도록 개선해볼까요? 💪

mock값을 이용해 테스트 시도해보았습니다.


> 프로토콜을 이용해서 dataTask를 실행할 수 있는 객체를 주입받도록 하면 테스트가 더 용이해지지 않을까요? `static`이 아니라 인스턴스 메서드로 함수를 구현하고, 이니셜라이저에서 protocol을 주입받으면, 가짜 객체를 만들어서 테스트할 수 있을 것 같은 느낌적인 느낌~~? 🤓

`URLSessionProtocol`프로토콜 선언, 채택을 통해서 테스트를 하게 되었어요!

민디의 멘트가 너무나도 많이 도움이 되었습니다. 감사해요😍

2021-01-29 12:59 UTC, cmindy approved these changes
고생많으셨습니다 ❣️ 고민을 많이 하신 흔적이 보이네요. Alamofire까지 참고하시다니,, 넘 멋지십니당 여러분

> 디코딩하는 함수에 접근할때 OpenMarketJSONDecoder<Product or ProductList>.decodeData() 로 접근을 하게 되서 문제가 없을거라고 생각을 했습니다.

이거는 제가 코드를 좀 잘못 봤었던 것 같네요 😅  일단 킵고잉하시죠 ㅎㅎ! 다음 스텝에서 오타 몇개 수정해주시면 될 것 같아요.

2021-01-29 12:59 UTC, cmindy commented on OpenMarket/OpenMarket/Model/Network/APIRequestType.swift
> +    }
👍

2021-01-29 12:59 UTC, merged