오픈마켓 II [STEP 2] 주디, 재재
yagom-academy/ios-open-market pull request #200
Opened 2022-08-04 06:49 UTC by ZZBAE

@protocorn93  콘 안녕하세요!
오픈마켓II의 step2 (브랜치의 step4) PR 보냅니다.
리뷰 잘 부탁드리겠습니다 🙇🏻‍♀️

# 🛍 **오픈마켓2 "OPEN MARKET II"**
> **프로젝트 기간** : 2022.08.01 월  ~ 2022.08.04 목 </br>**팀원** : 주디, 재재</br>**리뷰어** : 콘

## 💾 **개발환경 및 라이브러리**
[![swift](https://img.shields.io/badge/swift-5.6-orange)]()
[![xcode](https://img.shields.io/badge/Xcode-13.4.1-blue)]()

---

## 💡 **Step 2 수행 중 핵심경험**
- [x] UIAlertController 액션의 completion handler 활용
- [x]  UIAlertController의 textFields 활용
- [x]  UICollectionView 를 통한 좌우 스크롤 기능 구현
<br>

## 📱 **구현한 화면**

| 상품 수정 기능 | 상품 삭제 실패 | 상품 삭제 성공 |
|:---:|:---:|:---:|
|![](https://i.imgur.com/njUf4Eo.gif)|![](https://i.imgur.com/sZ7jE9U.gif)|![](https://i.imgur.com/Cftre8Y.gif)|
| 등록되어 있는 상품정보를 수정할 수 있음 | 등록된 상품의 비밀번호와 일치하지 않을 시 삭제 불가능 | 등록되어 있는 상품의 비밀번호와 일치할시 삭제 가능 |

| 상세 화면 이미지 넘기기 | 타인이 등록한 상품에 대한 수정 제한 |
|:---:|:---:|
|![](https://i.imgur.com/iNOMbSk.gif)|![](https://i.imgur.com/plDa6pZ.gif)|
| 좌우로 밀어서 다음/이전 이미지 확인 | 본인이 등록하지 않은 상품은 수정할 수 없음 |

<br>

---

## 🤔 **고민한 점 및 궁금한 점**

### 1. 상품 상세 화면의 이미지 섹션 스냅샷
```swift
enum Section: Int ,Hashable {
    case image // 이미지를 스크롤 할 수 있는 섹션
    case info	// 상품의 정보를 보여주는 섹션
 }
```

이미지의 **snapshot**을 지정할 때 어려움이 있었습니다. 우선 상품 정보를 컬렉션 뷰에 띄우기 위해 서버에서 **GET**한 데이터를 `DetailProductItem` 타입으로 디코드한 후 사용합니다. 따라서 **snapshot**의 타입도 `DetailProductItem`인데 문제는 이미지를 표현하는 섹션의 데이터 역시 `DetailProductItem`으로 표현해야 했습니다.

그래서 처음에는 `DetailProductItem`이 `[String]`으로 이미지 **url**을 가지도록 했으나 이미지 데이터가 상품의 사진 개수만큼 있어야 띄울 수 있었습니다. 그래서 단순하게 동일한 `DetailProductItem`를 배열에 넣어서 **snapshot**으로 사용하려 했으나 그러면 **Hashable**하지 않아 사용할 수 없었습니다. 

```swift
// DetailProductItem.swift
init(detailItem: DetailProductItem, image: String) { ... }
```

결국 단일한 이미지 **url**을 가지는 `DetailProductItem`을 사진 개수만큼 가진 배열을 사용해야 했습니다. 최종적으로는 `DetailProductItem`에 이미지 **url**만 변경하는 `init`을 추가했습니다.

```swift
typealias SnapShot = NSDiffableDataSourceSnapshot<Section, DetailProductItem>
private var detailProductItem: DetailProductItem? // 서버에서 받은 상품 상세 데이터를 decode한 정보
private var images: [String] = [] // 서버에서 받은 상품 이미지 url 배열

// 스냅샷 적용하는 코드
private func applySnapshots() {
    var itemSnapshot = SnapShot()
    guard let detailProduct = detailProductItem else { return }
    var detailImages: [DetailProductItem] = []
        
    images.forEach {
        detailImages.append(DetailProductItem(detailItem: detailProduct, image: $0))
    }
    itemSnapshot.appendSections([.image, .info])
    itemSnapshot.appendItems(detailImages , toSection: .image)
    itemSnapshot.appendItems([detailProduct], toSection: .info)
        
    dataSource.apply(itemSnapshot, animatingDifferences: false)
}
```
전체 이미지 **url**을 담은 배열을 `forEach`를 통해 **url**만 변경한 `DetailProductItem`을 생성해 배열로 만들어서 **image** 섹션의 **snapshot**으로 사용했습니다.

이미지만을 위해 `DetailProductItem` 타입을 사용하고, `init`을 통해 불필요하게 타입을 복제하는 것 같은데 이런 방식으로 적용해도 괜찮은걸까요? 😭
<br>

### 2. 상품 상세 화면에서 이미지를 넘길 때
상품 상세 화면에서 1개 이상의 이미지가 가로로 나열되어 있어 다음 이미지를 보기 위해 수평 스크롤을 하였을 때, 이미지가 천천히 가면서 좌우의 여백이 맞지 않는 상태여서 사용자 입장에서 보기 불편하다고 느껴졌습니다.

그래서 `orthogonalScrollingBehavior` 설정을  `.continuousGroupLeadingBoundary`에서 `.groupPagingCentered`로 변경해주었습니다. 변경을 해준 뒤, 다음 이미지로 스크롤 하였을 때 이미지가 cell의 중앙에 맞춰져 멈추게 되어 보기 편해졌습니다.

**변경 전 코드**
![](https://i.imgur.com/KMzYocm.png)

**변경 후 코드**
![](https://i.imgur.com/ZQP9qD7.png)
<br>

### 3. jpg 이외의 이미지 형식 Post
이전 step 1 (브랜치 step 3) 리뷰에서 알려주신 것처럼 이미지 타입을 구분하는 방법을 아래 사진처럼 적용해보았습니다. 여기서 저희가 발견한 문제점은, jpg는 구분이 잘 되지만 png 타입인 이미지를 어떤 방식으로 넣어도 png로 구분되지도 않고 출력되지도 않았습니다. 맥북에서 jpg나 jpeg로 변환을 해준 사진, 기존 앨범에 있는 사진, 저희의 핸드폰으로 직접 찍은 사진이 아닌 스크린샷 또는 포털에서 다운받은 사진들은 아예 들어가지도 않았습니다. 혹시나 시뮬레이터에서는 jpg 타입의 이미지만 가질 수 있는 것인가 의문이 들었습니다.

![](https://i.imgur.com/dAtwB0T.png)

<br>

---

## ⌨️ 커밋 규칙
* feat    : 기능 추가 (새로운 기능)
* fix      : 버그 수정
* refactor : 리팩토링 (네이밍 수정 등)
* style   : 스타일 (코드 형식, 세미콜론 추가: 비즈니스 로직에 변경 없음)
* docs    : 문서 변경 (문서 추가, 수정, 삭제)
* test    : 테스트 (테스트 코드 추가, 수정, 삭제: 비즈니스 로직에 변경 없음)

## 💻 코드 컨벤션
Swift Statements 형식 준수

-----

2022-08-04 07:59 UTC, ZZBAE commented
[2e9ace1](https://github.com/yagom-academy/ios-open-market/pull/200/commits/2e9ace188bc8007e36486bea96ae0afa2428a1da)
@protocorn93 저희가 PR 보낸 후 고민한 점 3번에서 jpg 외 이미지 형식이 post가 안되는 점을 해결해보았습니다. 
저희가 사진 용량을 조절하는 메서드에서 지정해준 용량보다 작은 사진들이 들어가면, 빈 Data가 나왔기 때문에 변환이 되지 않았던 것을
이미지 타입을 구분해주지 못했다고 착각을 했습니다.
그리고 jpg로만 나오는 문제의 원인은 저희 코드에서 이미지 데이터를 jpegData함수를 사용하여 모든 타입의 이미지를 jpeg(jpg)로 변환해주었기 때문이였습니다..😅

2022-08-07 03:14 UTC, protocorn93 requested changes
두 분 모두 고생하셨어요! 제가 피드백이 많이 늦엇네요; 죄송해요..!!

궁금한 부분에 대해서는 코멘트로도 남겼지만 모델을 쪼개는 연습을 해보시면 좋을 것 같아요. `image` 섹션의 연관 값을 위한 별도의 모델을 정의하고 이를 사용한것으로 말이죠~ 

이렇게 계층에 따라 모델을 나누는 것은 중요한데요. https://youtu.be/M58LqynqQHc 이 영상을 한번 간단하게 참고해보셔도 좋을 것 같아요.

2022-08-07 03:14 UTC, protocorn93 commented on OpenMarket/OpenMarket/Models/Item.swift
> +    init(detailItem: DetailProductItem, image: String) {
아규먼트 레이블을 `imageURL`이나 `thumbnailURL`로 가져가는건 어떨까요?

2022-08-07 03:14 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/AddProductView.swift
> +    func configure(data: DetailProduct) {
모델에도 계층이 있다고 생각해요. 매핑 모델(Decodable을 채택한), 엔티티, 뷰모델 등. 

보통 뷰모델을 별도로 정의하고 뷰에서 configure 할 때는 뷰모델을 사용하곤해요. 말그대로 뷰가 사용하는 모델로 이 메서드에서 처럼 따로 타입 변환이나 분기가 들어갈 일이 없고 그대로 사용할 수 있는 형태로 말이죠!

2022-08-07 03:14 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/ViewCell/DetailImageCollectionViewCell.swift
> +//    }
불필요한 주석은 제거해주시면 좋을 것 같아요. 그게 아니라면 `// TODO: -` 와 같은 주석으로 남겨둔 이유를 명시해두면 좋을 것 같아요

2022-08-07 03:14 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/ViewCell/DetailImageCollectionViewCell.swift
> +    }()
접근제어자를 추가해주시고 configure 메서드를 통해 값을 할당해주도록 해주시면 좋을 것 같아요.

2022-08-07 03:14 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/ViewCell/DetailInfoCollectionViewCell.swift
> +    }
위에서 언급한 뷰모델을 적용한다면 

```swift 
final class DetailInfoCollectionViewCell: UICollectionViewCell { 
  struct ViewModel { 
    ...    
  }

  func configure(with viewModel: ViewModel) { 
    self.nameLabel.text = viewModel.productName
    self.priceLabel.attributedText = viewModel.priceLabelText
    self.stockLabel.text = viewModel.stock
    ...
  }
}
```

이런식으로 작성될 수 있겠죠!

2022-08-07 03:14 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/ViewCell/MarketGridCollectionViewCell.swift
> +        label.adjustsFontSizeToFitWidth = true
이 프로퍼티가 의미하는 것이 무엇인지 간단하게 설명해주실 수 있으신가요?

2022-08-07 03:14 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/SessionImageView.swift
> +    func configureImage(url: String, _ cell: UICollectionViewCell, _ indexPath: IndexPath, _ collectionView: UICollectionView) {
이전 스탭에서 indexPath를 비교해서 동일한 이미지가 다른 셀에 fetch 되는 이슈를 수정했는데, 원인과 다른 방법도 찾아보셨을까요? `UICollectionView`와 `UICollectionViewCell`을 직접 알고 작업하는 것은 적절하지 않아보여요.

2022-08-07 03:14 UTC, protocorn93 commented on OpenMarket/OpenMarket/ViewController/AddProductViewController.swift
> +        viewModeTitle = "상품수정"
화면을 재활용하는 것은 맞는데, 수정 모드인지, 추가 모드인지에 대한 부분을 코드로 인지하기가 조금 어려운 것 같아요. enum을 사용해서 모드에 따른 분기가 필요한 곳마다 switch-case로 처리하는게 코드는 많아질 수 있지만 오히려 직관적일 수 있지 않을까 생각이 되네요

2022-08-07 03:14 UTC, protocorn93 commented on OpenMarket/OpenMarket/ViewController/AddProductViewController.swift
> +        if viewModeTitle == "상품등록" {
결국 추가하는 상황일텐데 title로 분기하는 것은 적절하지 않아보여요

2022-08-07 03:14 UTC, protocorn93 commented on OpenMarket/OpenMarket/ViewController/AddProductViewController.swift
> +        }
여기를 main async로 감싼 이유가 있을까요?

2022-08-07 03:14 UTC, protocorn93 commented on OpenMarket/OpenMarket/View/AddProductView.swift
> +    func configure(data: DetailProduct) {
결국 요점은 해당 객체가 필요한 정보만을 알 수 있도록 모델을 쪼개는 것이라고 할 수 있어요~

2022-08-07 03:14 UTC, protocorn93 commented on OpenMarket/OpenMarket/Models/DetailProduct.swift
> +    let `url`: String
url을 ``으로 감싼 이유가있을까요?

2022-10-06 08:58 UTC, closed without merging