오픈마켓 [STEP 1] 로빈, 스톤
yagom-academy/ios-open-market pull request #204
Opened 2022-11-16 02:51 UTC by yuvinrho

안녕하세요 알라딘(@junbangg)! 스톤, 로빈입니다~
오픈마켓 step1 잘부탁 드립니다~ 아낌없는 조언 부탁드립니다!🙏

## 구현내용
#### NetworkManager 타입 구현
- `checkAPIHealth()` : API 서버 상태코드가 200(정상인지) 확인하는 메서드 입니다.
- `fetchItemList()` : 서버로 부터 `ItemList`를 가져옵니다. completion 을 통해 `Result<ItemList, NetworkError>`를 전달합니다.
- `fetchItem()` :  서버로 부터 `Item`상세정보를 가져옵니다. completion 을 통해 `Result<Item, NetworkError>`를 전달합니다.

## 고민되었던 점
### `step1-1`에서 제공된 products.json 파일과 실제 서버 통신시 json파일의 형식이 다른 문제점
- `step1-1`에서 제공받은 products.json파일의 경우 아래와 같은 형식입니다.
```json
{
  "page_no": 1,
  "items_per_page": 20,
  "total_count": 10,
  "offset": 0,
  "limit": 20,
  "last_page": 1,
  "has_next": false,
  "has_prev": false,
  "pages": [
    {
      "id": 20,
      "vendor_id": 3,
      "name": "Test Product",
      "thumbnail": "https://s3.ap-northeast-2.amazonaws.com/media.yagom-academy.kr/training-resources/3/thumb/5a0cd56b6d3411ecabfa97fd953cf965.jpg",
      "currency": "KRW",
      "price": 0,
      "bargain_price": 0,
      "discounted_price": 0,
      "stock": 0,
      "created_at": "2022-01-04T00:00:00.00",
      "issued_at": "2022-01-04T00:00:00.00"
    }
  ]
}
```
- 실제 서버와 통신했을때 반환되는 JSON형식은 아래형식입니다.
```json
{
  "pageNo": 1,
  "itemsPerPage": 1,
  "totalCount": 113,
  "offset": 0,
  "limit": 1,
  "lastPage": 113,
  "hasNext": true,
  "hasPrev": false,
  "pages": [
    {
      "id": 193,
      "vendor_id": 29,
      "vendorName": "wongbing",
      "name": "테스트",
      "description": "Post테스트용",
      "thumbnail": "https://s3.ap-northeast-2.amazonaws.com/media.yagom-academy.kr/training-resources/29/20221115/2e4728b864ef11eda917ff060c8f69d7_thumb.png",
      "currency": "KRW",
      "price": 1200.0,
      "bargain_price": 1200.0,
      "discounted_price": 0.0,
      "stock": 3,
      "created_at": "2022-11-15T00:00:00",
      "issued_at": "2022-11-15T00:00:00"
    }
  ]
}
```
`step 1-2`로 넘어가는 과정에서 두가지 데이터 형식이 달라, parse하는 부분에서 문제가 발생하여 실제 API통신에 맞게 `ItemList`의 형식을 변경했습니다.
- 이 부분에서 step1에 사용된 `ParsingTests`의 테스트는 항상 실패하게됩니다.
## 조언을 얻고 싶은 부분
- JSON 데이터와 매칭되는 모델의 프로퍼티 네이밍에 대한 알라딘의 의견 궁금합니다!
    - 서버에서 받아온 JSON타입에 맞게 프로퍼티를 매칭하는 것과 아니면 보다 명확한 프로퍼티 네이밍을 커스텀하여 사용하는게 더 좋을지 알라딘의 의견이 궁금합니다..!
- 스텝1-3에 테스트 더블에 대해 공부하니깐 딥한 느낌이 있었습니다. 현재 저희가 구현한 것은 세션 바꿔치기 방법 구현 정도로 느껴졌는데, 현재로썬 이렇게 한 번 구현해본것에 의미를 두면 될지 궁금합니다.

2022-11-16 14:21 UTC, junbangg requested changes
수고하셨습니다!! 코드가 깔끔하군요:)
댓글 확인해주세요~

질문 주신 내용에 대한 개인적인 의견을 드리자면
1.
```
JSON 데이터와 매칭되는 모델의 프로퍼티 네이밍에 대한 알라딘의 의견 궁금합니다!
서버에서 받아온 JSON타입에 맞게 프로퍼티를 매칭하는 것과 아니면 보다 명확한 프로퍼티 네이밍을 커스텀하여 사용하는게 더 좋을지 알라딘의 의견이 궁금합니다..!
```

음 물론 프로젝트/회사/팀 마다 다 다르겠지만 만약에 서버에서 내려오는 이름들이랑 통일을 하기로 정해둔 규칙같은게 있다면 이야기가 다르겠지만 저는 지금 해주신것 처럼 적절히 네이밍을 바꿔주시면 좋을것 같아요! 

2.
```
스텝1-3에 테스트 더블에 대해 공부하니깐 딥한 느낌이 있었습니다. 현재 저희가 구현한 것은 세션 바꿔치기 방법 구현 정도로 느껴졌는데, 현재로썬 이렇게 한 번 구현해본것에 의미를 두면 될지 궁금합니다.
```

지금은 `Stub Testing` 을 해주신것 같네요!

음 `Stub Testing` 을 하는 이유에 대해서는 두분께서 어떻게 생각하시는지 궁금합니다 🤔

2022-11-16 14:21 UTC, junbangg commented on OpenMarket/OpenMarket/Models/Item.swift
> +    let price, bargainPrice, discountedPrice: Double
요런식으로 한줄로 작성한 프로퍼티들이 있는 반면에 그렇지 않은 친구들도 보이네요! 
통일하면 더 보기 좋을것 같습니다:)

2022-11-16 14:21 UTC, junbangg commented on OpenMarket/OpenMarket/Models/Item.swift
> +    let issuedAt: String
요기도 `issuedAt` 만 한줄처리 안한 이유가 있을까요??

2022-11-16 14:21 UTC, junbangg commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +
의도된 줄바꿈인가요???

2022-11-16 14:21 UTC, junbangg commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +    init(url: String = "https://openmarket.yagom-academy.kr/", session: URLSessionProtocol = URLSession(configuration: .default)) {
요런 기다란 파라미터/생성자 들은 줄바꿈을 적절히 시켜주면 좋을것 같아요!
참고로 `SwiftLint` 에서는 `col` 이 120줄까지 컨벤션으로 강제하는걸로 알고있어요

2022-11-16 14:21 UTC, junbangg commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +struct NetworkManager {
요거 구조체로 하신 이유가 있나요??(틀렸다는거 절대 아닙니다🙂)

2022-11-16 14:21 UTC, junbangg commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        let urlString = "\(url)healthChecker"
여기서는 `urlString` 이라고 하셨는데 위에서는 그냥 `url` 이네요!?

2022-11-16 14:21 UTC, junbangg commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        guard let url: URL = URL(string: urlString) else { return }
위에도 `url` 라는 프로퍼티가 있어서 혼동이 생길지도 모르겠네요🤔

2022-11-16 14:21 UTC, junbangg commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +            return completion(httpResponse.statusCode == 200)
`httpResponse.statusCode == 200` 요 부분 그냥 상수로 빼서 이름 잘 지어주고 넣어주는건 어떨까요?? 가독성이 올라가지않을까?라는 개인적인 의견입니당

2022-11-16 14:21 UTC, junbangg commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +
위에서는 `return` 을 한줄로 처리하는 경우가 있었는데 여기서는 줄바꿈한 이유가 있나요?? 틀렸다는건 아니지만 특별한 기준이 있었는지 궁금합니다~~

2022-11-16 14:21 UTC, junbangg commented on OpenMarket/OpenMarket/Network/Mock/URLSessionProtocol.swift
> +public protocol URLSessionProtocol {
오 요부분 `public` 으로 하신 이유가 있나요??( 틀렸다는거 아닙니다:) )

2022-11-16 14:21 UTC, junbangg commented on OpenMarket/OpenMarket/Network/Mock/StubURLSession.swift
> +        self.dummyData?.completionHandler = completionHandler
`dummyData` 의 프로퍼티를 여기서 주입받아서 설정해주는 이유가 있나요???

2022-11-16 14:21 UTC, junbangg commented on OpenMarket/OpenMarket/Network/Mock/StubURLSession.swift
> +class StubURLSession: URLSessionProtocol {
`final` 처리가 가능할것 같은데 `final` 을 사용하는 이유에 대해서 공부하신 적 있으신가요????

2022-11-16 14:21 UTC, junbangg commented on OpenMarket/OpenMarket/Network/Mock/StubURLSession.swift
> +class StubURLSessionDataTask: URLSessionDataTask {
여기도 `final` 이 가능할것 같아요~

2022-11-16 14:21 UTC, junbangg commented on OpenMarket/MockTests/MockTests.swift
> +    func test_checkAPIHelath를_통해_정상적으로_응답을하는_true_값을_반환하는지() {
메서드명에 오타가 있어요! `health`!

2022-11-16 14:21 UTC, junbangg commented on OpenMarket/MockTests/MockTests.swift
> +        let stubUrlSession = StubURLSession(dummy: dummy)
`stubUrlSession` 보다는 `stubURLSession` 이 어떠신가요??다른 곳에서도 그렇게 하신것 같아요

2022-11-16 14:21 UTC, junbangg commented on OpenMarket/MockTests/MockTests.swift
> +        let perPage = 20
위에만 타입을 명시해주셨네요!! 별개로 타입 명시 하고 안하고의 차이가 뭐라고 생각하시는지 궁금합니당

2022-11-16 14:21 UTC, junbangg commented on OpenMarket/NetworkingTests/NetworkingTests.swift
> +    func test_checkAPIHelath를_통해_서버가_정상적으로_응답을하는_true값을_반환하는지() {
여기도 `Health` 오타가 있네요:)

2022-11-17 00:41 UTC, junbangg commented on OpenMarket/MockTests/MockTests.swift
> +        sut.fetchItem(productId: productId) { result in
다른곳들도 가끔 있었는데 여기처럼 줄바꿈 해주신건 기준이 있을까요???

2022-11-17 00:41 UTC, junbangg commented on OpenMarket/OpenMarket/Models/Item.swift
> +    let createdAt, issuedAt: String
이친구들 날짜 말하는거겠죠..? 쪼금 더 친절하게 바꿀 수도 있을것 같은데 개인적인 의견일 뿐입니다ㅎ 이 프로퍼티를 접근해서 사용하는 상황을 생각했을때는 네이밍이 뭔가 어색할것 같은 느낌???
요거 네이밍에 대해서 어떻게 생각하시나요🤔

2022-11-17 09:26 UTC, lws2269 commented on OpenMarket/OpenMarket/Models/Item.swift
> +    let price, bargainPrice, discountedPrice: Double
넵! 연속되는 타입에 대하여 한줄로 통일하였습니다😄 !

2022-11-17 09:27 UTC, lws2269 commented on OpenMarket/OpenMarket/Models/Item.swift
> +    let issuedAt: String
37번째는 URL을 뜻하는 두가지를 묶어서 처리하였는데, 타입이 같아서 한줄에 처리해도 된다고 생각하여 통일하였습니다!

2022-11-17 09:27 UTC, lws2269 commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +
불필요한 개행 삭제하였습니다..!

2022-11-17 09:28 UTC, yuvinrho commented on OpenMarket/OpenMarket/Models/Item.swift
> +    let createdAt, issuedAt: String
아하~ 프로퍼티만 보고 날짜를 파악할 수 없다는 점 동의합니다.
아래와 같이 수정하였습니다~

```swift
let createdDate, issuedDate: String
```

2022-11-17 09:28 UTC, lws2269 commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +    init(url: String = "https://openmarket.yagom-academy.kr/", session: URLSessionProtocol = URLSession(configuration: .default)) {
좋은 의견 감사합니다! 줄바꿈 처리로 인해 가독성이 조금 더 좋아진 것 같습니다! 😄

2022-11-17 09:29 UTC, lws2269 commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +struct NetworkManager {
아직은 상속이나, 싱글턴 패턴을 적용하거나 하지 않아서 class의 필요성을 느끼지 못해 struct로 사용했습니다!

2022-11-17 09:30 UTC, yuvinrho commented on OpenMarket/MockTests/MockTests.swift
> +        sut.fetchItem(productId: productId) { result in
다른곳들과 통일을 위해서 선언부는 개행없이 다 붙여주었습니다~

2022-11-17 09:30 UTC, lws2269 commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        let urlString = "\(url)healthChecker"
전역변수로 가지고 있는 `url`을 `baseURL`로 처리하여 프로퍼티 네이밍의 중복과 모호함을 제거하려 노력해보았습니다!

2022-11-17 09:31 UTC, lws2269 commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        guard let url: URL = URL(string: urlString) else { return }
위에 해주신 리뷰와 함께 생각해봤을때 전역변수를 `baseURL`로 변경하여 해결해보았습니다!

2022-11-17 09:34 UTC, yuvinrho commented on OpenMarket/MockTests/MockTests.swift
> +    func test_checkAPIHelath를_통해_정상적으로_응답을하는_true_값을_반환하는지() {
감사합니다. 오타 못찾을 뻔했습니다. 수정하였습니다~

2022-11-17 09:34 UTC, yuvinrho commented on OpenMarket/NetworkingTests/NetworkingTests.swift
> +    func test_checkAPIHelath를_통해_서버가_정상적으로_응답을하는_true값을_반환하는지() {
매의눈!👍 알라딘이 아니었으면 못찾을뻔 했습니다😂 수정하였습니다. 감사합니다!

2022-11-17 09:35 UTC, onestone23 commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +            return completion(httpResponse.statusCode == 200)
컴플리션핸들러로 전달하는 타입이 `Bool`타입이라 연산식을 안에 작성해 보았는데, 모르는 사람이 봤을땐 200이라는 숫자가 무엇을 뜻하는지 모를 수도 있다는 생각이 문뜩 들었습니다!
`NetworkManager` 타입 내부에 `StatusCode`라는 열거형을 선언하여 ok는 200을 채택함으로써 해결해보았습니다.
추후에 404 Not Found라던지 필요하다면 추가 선언하여 사용할 수 있을 것 같습니다.!
좋은 의견 감사합니다

2022-11-17 09:38 UTC, lws2269 commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +
아무 처리없이 `return`하게 되는 경우에는 한줄로 처리하고 `return`하면서 처리해야 될 로직이 있으면 줄바꿈 처리를 하기로 기준을 세웠는데 누락된 부분이 몇 군데 있었던 것 같습니다! 기준에 맞게 통일하였습니다!

2022-11-17 09:38 UTC, yuvinrho commented on OpenMarket/MockTests/MockTests.swift
> +        let perPage = 20
앗.. 통일을 위해 타입을 삭제하였습니다. 
타입을 명시하면 한눈에 어떤 타입인지 볼 수있습니다.
타입을 붙여주지 않는다면 프로퍼티 타입이 Int를 사용하는지 Double을 사용하는지 불명확할 것 같습니다.

2022-11-17 09:39 UTC, yuvinrho commented on OpenMarket/MockTests/MockTests.swift
> +        let stubUrlSession = StubURLSession(dummy: dummy)
아하~ 감사합니다. 애플공식문서에도 URL은 대문자로 쓰여있어서 `stubURLSession` 으로 수정하였습니다~

2022-11-17 09:40 UTC, lws2269 commented on OpenMarket/OpenMarket/Network/Mock/URLSessionProtocol.swift
> +public protocol URLSessionProtocol {
테스트 코드를 실행할 때 접근하지 못한다는 에러를 표출하여, public처리를 하였었습니다.
지금 확인해보니 지워도 별다른 에러가 발생하지 않네요....... xcode 이슈였을까요....?😭
- 불필요하다고 생각하여 삭제하였습니다!

2022-11-17 09:40 UTC, yuvinrho commented on OpenMarket/OpenMarket/Network/Mock/StubURLSession.swift
> +class StubURLSessionDataTask: URLSessionDataTask {
final 키워드 붙여주었습니다~

2022-11-17 09:43 UTC, yuvinrho commented on OpenMarket/OpenMarket/Network/Mock/StubURLSession.swift
> +class StubURLSession: URLSessionProtocol {
`final`은 클래스가 더이상 상속이 필요하지 않을때 붙여주고, 디스패치를 정적으로 호출하여 성능개선에 도움을 준다고 알고있습니다. 디스패치 정적, 동적에 대해서는 아직 정확하게 이해하지는 못했습니다😭

2022-11-17 10:16 UTC, lws2269 commented on OpenMarket/OpenMarket/Network/Mock/StubURLSession.swift
> +        self.dummyData?.completionHandler = completionHandler
`StubURLSession`의 `dataTask`메서드의 인자 중 completionHandler에 들어오는 클로져를 사용하기 위해 StubURLSessionDataTask 클래스의 생성자에서 설정해줍니다..! 제가 알라딘의 질문의 의도를 파악한게 맞을까요?😭

2022-11-17 10:23 UTC, yuvinrho commented
> 지금은 Stub Testing 을 해주신것 같네요!
음 Stub Testing 을 하는 이유에 대해서는 두분께서 어떻게 생각하시는지 궁금합니다 🤔

추측이지만) 나중에 실제로 서버에 데이터를 생성하는게 아닌 테스트를 통해 가짜 데이터를 생성하여 정말 서버에 데이터가 입력된 것 처럼 속이기 위해와
실제 네트워크를 통해 데이터를 받아오는 것이 아닌 더미 데이터를 활용하기 때문에 빠른 테스트가 가능하기 위해 사용하는 것 같습니다!

2022-11-17 12:52 UTC, junbangg commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +    init(url: String = "https://openmarket.yagom-academy.kr/", session: URLSessionProtocol = URLSession(configuration: .default)) {
팁 하나 드리자면 
```
Xcode->Preferences->Text Editing->Display->Page guide at column
```
여기서 `col` 설정하시면 Xcode 에서 하얀색 줄을 보여줘요!!
하얀색 넘어가면 줄바꿈 해야겠구나~ 할 수 있어서 편하더라고요:)

2022-11-17 13:09 UTC, junbangg approved these changes

2022-11-17 13:09 UTC, junbangg commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +struct NetworkManager {
좋습니다~ 이참에 `struct` 안에 `class` 가 있을때, `class` 안에 `struct` 가 있을때 무슨 일이 일어나는지
한번 고민/공부하시면 좋을것 같습니다! 지금 아니더라도 나중에?!

2022-11-17 13:09 UTC, junbangg commented on OpenMarket/OpenMarket/Network/NetworkManager.swift
> +        let urlString = "\(url)healthChecker"
아하 저는 그냥 그것도 urlString으로 하면 어떨까하고 의견을 드린거긴 합니다! 👍
`baseURL` 도 나쁘지 않은것 같네요~

2022-11-17 13:09 UTC, junbangg commented on OpenMarket/MockTests/MockTests.swift
> +        let perPage = 20
넵! 그리고 타입을 명시해주면 컴파일러가 조금 더 고마워할 수도 있을것 같아요!
타입 추론을 따로 할 필요가 없으니까??
물론 애플은 스위프트가 타입추론 잘한다고 주장하고 있기 때문에 성능적인 이점이 클것 같지는 않지만 저는 그냥 웬만하면 타입을 명시해주고 있어요!
`let pageNo: Int = 3` 처럼~~

이건 근데 개인적인 스타일인거라서 꼭 하실 필요 없습니다🙅‍♂️

2022-11-17 13:11 UTC, merged

2022-11-17 13:17 UTC, junbangg commented
> > 지금은 Stub Testing 을 해주신것 같네요!
> > 음 Stub Testing 을 하는 이유에 대해서는 두분께서 어떻게 생각하시는지 궁금합니다 🤔
> 
> 추측이지만) 나중에 실제로 서버에 데이터를 생성하는게 아닌 테스트를 통해 가짜 데이터를 생성하여 정말 서버에 데이터가 입력된 것 처럼 속이기 위해와 실제 네트워크를 통해 데이터를 받아오는 것이 아닌 더미 데이터를 활용하기 때문에 빠른 테스트가 가능하기 위해 사용하는 것 같습니다!

넵 중요한 포인트를 잘 짚어주신것 같아요! 
저희가 테스트 코드를 짤때 말하는 중요한 원칙(?) 들이 있잖아요?
테스트 코드는 실제코드와 분리되어있어야한다~ 테스트 코드는 빨라야한다~  등등?

실제 네트워크를 통해 데이터를 받아오는 일을 테스트 코드에 포함시키면 테스트코드가 빠를 수가 없으니까! Stub Testing 을 많이 활용하는것 같아요~
그래서 다시 처음으로 돌아와서 질문에 대한 답변을 드리자면 지금 `Mock Tests` 처럼 해주셔도 충분할것 같아요!

[배민형님들께서 작성해주신 Stub Testing](https://techblog.woowahan.com/2704/) 관련 글 하나 공유드립니다:) 
이미 보셨을수도 있겠네요 ㅎㅎ