오픈마켓 [STEP 1] 애런, 제이푸시
yagom-academy/ios-open-market pull request #205
Opened 2022-11-16 06:46 UTC by jjpush

안녕하세요 태태 @uuu1101
스텝 1-2까지 구현이 완료 되어 PR 보내드립니다

1-3은 개념이 생각보다 이해가 어려워서 조금 더 공부해본 뒤에
스텝 2 진행 후에 다시 적용해보도록 하겠습니다.

## 🤔고민했던점
### fetch() 메서드의 네트워크 비동기 처리에 대한 고민. 
URLsession의 dataTask를 생성 resume 메서드를 실행하고 반환값을 받으면 비동기적으로 처리되어 `ViewController`에서 반영되지 않는 부분에 대해서 함께 이야기를 나누어 보았습니다.
해당 부분에 대해서는 컴플리션 핸들러를 사용해 `ViewContorller` 내부에서 동기화를 시키는 방식으로 해결을 했습니다..!😎

```swift
func fetch(type: requestType, completion: @escaping (completionable) -> Void) {
        ...
        
        switch type {
        case .healthChecker:
            getHealthChecker(url) { statusCode in
                completion(statusCode)
            }
        case .searchProductList(_, _):
            getProductsList(url) { productsList in
                completion(productsList)
            }
        case .searchProductDetail(_):
            getProductDetail(url) { product in
                completion(product)
            }
        }
    }
```
```swift
func getHealthChecker(_ url: URL, completion: @escaping (Int) -> Void) {
    let dataTask = URLSession.shared.dataTask(with: url) { data, response, error in
        ...
    }
    dataTask.resume()
}
```

### Json 파일의 형식 불일치
서버 API 문서에 기재된 형식, 제공받은 json 테스트 파일, 실제로 서버에서 받은 json 파일이 모두 key가 달라 어떤 것을 기준으로 삼아 진행해야 할지에 대해 고민이 있었습니다.

> 실제 서버에서 받아온 json 형식--
```json
{
  "id": 21,
  "vendor_id": 12,
  "name": "더블",
  "description": "",
  "thumbnail": "https://s3.ap-northeast-2.amazonaws.com/media.yagom-academy.kr/training-resources/12/20221016/a237ef554d5f11eda2009b68861433a6_thumb.jpg",
  "currency": "KRW",
  "price": 0.0,
  "bargain_price": 0.0,
  "discounted_price": 0.0,
  "stock": 34,
  "created_at": "2022-10-16T00:00:00",
  "issued_at": "2022-10-17T00:00:00",
  "images": [
    {
      "id": 23,
      "url": "https://s3.ap-northeast-2.amazonaws.com/media.yagom-academy.kr/training-resources/12/20221016/a237ef544d5f11eda200efed6e41448d_origin.jpg",
      "thumbnail_url": "https://s3.ap-northeast-2.amazonaws.com/media.yagom-academy.kr/training-resources/12/20221016/a237ef554d5f11eda2009b68861433a6_thumb.jpg",
      "issued_at": "2022-10-16T00:00:00"
    }
  ],
  "vendors": {
    "id": 12,
    "name": "judy123"
  }
}
```

함께 고민해보다 실제로 서버 api와 통신해서 받아온 데이터를 기준으로 진행하는 것이 맞다고 생각되어 진행했습니다..!

또한 product에는 존재하나 produ
## 🙏조언을 얻고 싶은 부분

### Completionable 프로토콜에 대한 고민

구현을 하는 방법을 생각해 보았습니다.
1. 각 작업별로 메서드를 구현한다.
2. completion의 파라미터로 작업에 대한 데이터를 받는다.

여기서 저희는 2번을 경험해 보고 싶어서 fetch메서드에 어떤 작업이 들어와도 유연하게 대응할 수 있도록 completion에 실행할 파라미터를 넣어주었습니다.

```swift
func fetch(작업, completion: (작업타입) -> Void) {
    switch 작업 {
    case 1작업:
        1작업() { completion(1작업타입) }
    case 2작업:
        2작업() { completion(2작업타입) }
    case 3작업:
        3작업() { completion(3작업타입) }
    }
}
```

작업1은 Int
작업2는 ProductsList
작업3은 Product

를 반환하고 있기 때문에

completionable이라는 프로토콜을 만들어 각 타입에 채택해 준 후 값을 사용할 때 풀어서 사용하도록 했습니다.

```swift
networkManager.fetch(type: 작업) { result in
            // 1. int일 경우
            if let result = result as? Int { 
                print(result)
            // 2. ProductsList일 경우
            } else if let result = result as? ProductsList { 
                print(result)
            // 3. Product일 경우
            } else if let result = result as? Product { 
                print(result)
            }
        }
```
 
이렇게 작성하고 보니
만약 fetch 메서드를 여러번 사용한다면 사용할 때마다 `if let` 구문을 계속해서 사용해 주어야 할 것 같아서 좋은 방법이 아닌 것 같다는 생각이 들었는데
유연하게 대응할 수 있는 다른 좋은 방법이 있을까요?

아니면 1번의 내용대로 작업별로 메서드를 분리하는게 좋을까요?
 
## 💻 개발환경 및 라이브러리
[![swift](https://img.shields.io/badge/swift-5.6-orange)]()
[![xcode](https://img.shields.io/badge/Xcode-13.4.1-blue)]()

2022-11-17 08:16 UTC, uuu1101 requested changes
안녕하세요! @jjpush @hashswim 
STEP1 하시느라 고생하셨습니다.
몇가지 코멘트 남겨두었습니다.

**[고민점에 대한 답변]**
`fetch()` 메서드를 일원화 하는 과정에서 현재 구조에서는 if let 을 반복해서 사용해야하는 부분을 개선하기는 힘들어 보입니다.
`fetch()` 메서드 하나로 모든 케이스들을 처리할 수 있다면 가장 좋은 방법이겠지만, 현재 구조에서는 Generic 타입을 받거나 현재 방법처럼 처리하는게 각각 나눠져 있는 부분들을 모두 하나로 모았다가 다시 각각 나눠서 처리해주는 느낌이라.. 차라리 각 메서드들을 나눠서 작성을 해주는게 더 낫지 않을까 라는 생각이 들어요. 각 메서드로 나누는 과정에서 공통된 부분들은 하나의 메서드로 묶어서 각각 메서드에서 공통된 부분들을 묶어둔 메서드를 사용하는 방법도 있을 것 같아요.
또한, 현재 방식으로 작성하게 된다면 `requestType`이 추가된다면 `enum` 에서 case를 추가하고 `fetch()` 메서드가 사용되는 부분에도 각각 추가해주어여하는 등 부가적인 작업이 많아질것 같습니다.

항상 메서드를 세분화해서 나누는게 좋은 방법은 아니고, 각 상황에 맞는 방법이 있을 것 같아요.

두 분은 어떤 이유로 1번이 아닌 2번의 방법을 선택하셨을까요?! 👀

2022-11-17 08:16 UTC, uuu1101 commented on OpenMarket/OpenMarket/Network/Completionable.swift
> +extension Product: Completionable {}
extension으로 프로토콜을 채택하신 이유가 있나요?
이 방법보다 각 타입을 정의할때 명시해주는건 어떤가요?
```suggestion
struct ProductList: Coadble, Completionable { 
   ... 
}
struct Product: Coadble, Completionable { 
   ... 
}
```
}

2022-11-17 08:16 UTC, uuu1101 commented on OpenMarket/OpenMarket/Network/NetworkMananger.swift
> +        }
`fetch()`를 일원화 하려고 하시는 이유가 궁금합니다.
(= 모든 `type`을 하나의 함수로 처리하시려고 하는 이유가 궁금합니다.)

2022-11-17 08:16 UTC, uuu1101 commented on OpenMarket/OpenMarket/Network/NetworkMananger.swift
> +    private func getHealthChecker(_ url: URL, completion: @escaping (Int) -> Void) {
```suggestion
    private func getHealthChecker(_ url: URL, completion: @escaping (StatusCode) -> Void) {
```
`typealias`해둔 StatusCode를  사용하시는건 어떤가요?

2022-11-17 08:16 UTC, uuu1101 commented on OpenMarket/OpenMarket/Product/Product.swift
> +    let vendors: Vendor?
`vendors` 라고하면 복수형이라 Array라고 생각할수도 있을것 같은데 어떻게 생각하시나요?

2022-11-17 08:16 UTC, uuu1101 commented on OpenMarket/OpenMarket/Product/ProductsList.swift
> +    let pages: [Product]
`pages` 라고 네이밍 하신 이유가 궁금합니다 !

2022-11-18 01:13 UTC, Hashswim commented on OpenMarket/OpenMarket/Product/ProductsList.swift
> +    let pages: [Product]
서버로부터 받는 json 파일의 key가 pages란 이름으로 되어 있어 ProductList 타입을 선언 할 때 같도록 맞춰 주었습니다..!

2022-11-18 01:14 UTC, Hashswim commented on OpenMarket/OpenMarket/Product/Product.swift
> +    let vendors: Vendor?
서버로부터 받는 json 파일의 key가 vendors로 되어 있어 같도록 명시해 주었습니다..!

2022-11-18 01:15 UTC, jjpush commented on OpenMarket/OpenMarket/Network/Completionable.swift
> +extension Product: Completionable {}
원래는 각 타입에 명시를 해주었는데 만약 타입이 엄청 많아진다면 해당 프로토콜을 채택한 타입이 무엇인지 찾기 어렵지 않을까 생각했습니다. POP같은 방법으로 기능을 구현해야 한다면 타입에 명시를 해주는게 좋다고 생각하지만 Completionable 을 채택만하고 있는 타입들을 한눈에 보기위해서 Completionable에서 달아주었습니다.

이런 상황에서도 타입에 명시를 해주는 것이 좋았을까요?

2022-11-18 01:16 UTC, Hashswim commented on OpenMarket/OpenMarket/Network/NetworkMananger.swift
> +    private func getHealthChecker(_ url: URL, completion: @escaping (Int) -> Void) {
해당 부분 statusCode로 수정했습니다!

2022-11-18 01:17 UTC, jjpush commented on OpenMarket/OpenMarket/Network/NetworkMananger.swift
> +        }
type 매개변수로 enum 타입을 받기 때문에 생각했던 방법이었습니다. fetch 함수에서 작업만을 넣어준다면 훨씬 사용하기 쉽지 않을까 생각했는데 completion 에 넣어주는 타입이 다양해져버려서 수정해야할 것 같습니다 😭

2022-11-21 12:50 UTC, uuu1101 approved these changes
고생하셨습니다! STEP2에서 또 이야기를 나눠보도록 하죠!! 😊

2022-11-21 12:55 UTC, merged