오픈마켓 [STEP 1] Ayaan, 준호
yagom-academy/ios-open-market pull request #206
Opened 2022-11-16 12:04 UTC by junho15

안녕하세요, 태태(@uuu1101)🙇‍🙇‍🙇‍♀️!
[Ayaan🦖](https://github.com/oneStar92), [준호](https://github.com/junho15)
대망의 오픈 마켓 프로젝트의 첫 번째 PR 입니다.😁
프로젝트 기간동안 잘부탁드립니다.🙏

# 📍고민했던 부분 

## Decodable Model Property Optional
|상품 리스트 조회시 아이템|상품 상세 조회시 아이템|
|:---:|:---:|
|![](https://i.imgur.com/mnpGzkb.png)|![](https://i.imgur.com/GfPoqcb.png)|

- OpenMarket API에서 상품 리스트 조회시 전달되는 아이템과 와 상품 상세 조회시 전달되는 아이템의 프로퍼티가 서로 달라서 하나의 Model로는 데이터를 불러올 수 없는 문제가 있었습니다.
- 구현된 Model에서 서로 상이한 부분을 Optional로 지정해 줌으로써 해당 문제를 해결했습니다.
```swift
    struct Product: Decodable {
        let id, vendorID: Int
        let name, thumbnail: String
        let description: String? // 옵셔널 타입
        let currency: Currency
        let price, bargainPrice, discountedPrice: Double
        let stock: Int
        let createdAt, issuedAt: String
        let images: [ProductImage]? // 옵셔널 타입
        let vendor: Vendor? // 옵셔널 타입
```

## API 통신 기능별 Protocol화
- URLSession에 API 통신과 관련된 기능을 extension을 통해 구현했었습니다. POP의 관점에서 구현해 보고자하여 기능별로 프로토콜을 만들어서 `URLSession` 이 채택하도록 구현했습니다.
```swift
    extension URLSession: OpenMarketURLSessionProtocol { }
    extension URLSession: OpenMarketHealthFetchable { }
    extension URLSession: OpenMarketPageFetchable { }
    extension URLSession: OpenMarketProductFetchable { }
```

## 중복된 Guard문

- URLSessionDataTask의 CompletionHandler에서 data, response, error에 따른 분기처리를 해주지 않고 data를 처리하는 로직에서 guard문을 이용해 분기처리를 해줌으로써 중복된 코드가 발생하는 부분이 있었습니다.
- URLSessionDataTask의 CompletionHandler에서 if let을 이용하여 분기 처리를 해주어 중복된 코드를 줄일 수 있었습니다.

```swift
    // 수정 전
    private func fetchOpenMarketAPIDataTask(query: String,
                                            completion: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionDataTask {
        guard let hostURL = URL(string: "https://openmarket.yagom-academy.kr"),
              let url = URL(string: query, relativeTo: hostURL) else {
            fatalError()
        }
        
        return self.dataTask(with: url) { (data, response, error) in
            guard let data = data, error == nil else {
                completion(nil, response, error)
                return
            }
            completion(data, response, nil)
        }
    }

    func checkHealthTask(completion: @escaping (Bool) -> Void) {
        let query: String = "healthChecker"
        fetchOpenMarketAPIDataTask(query: query) { (_, response, error) in
            // 중복된 코드 발생 구간
            guard error == nil, let httpResponse = response as? HTTPURLResponse,
                  httpResponse.statusCode == 200 else {
                completion(false)
                return
            }
            // 모든 로직에서 해당 코드가 존재.
            completion(true)
        }.resume()
    }

    // 수정 후
    func fetchOpenMarketDataTask(query: String,
                                 completion: @escaping (Data?, Error?) -> Void) -> URLSessionDataTask? {
        guard let hostURL = URL(string: host),
              let url = URL(string: query, relativeTo: hostURL) else {
            return nil
        }
        
        return self.dataTask(with: url) { (data, response, error) in
            if let error = error {
                completion(nil, error)
            } else if (response as? HTTPURLResponse)?.statusCode != 200 {
                completion(nil, OpenMarketError.badStatus)
            } else if let data = data {
                completion(data, nil)
            } else {
                completion(nil, nil)
            }
        }
    }

    func fetchHealth(completion: @escaping (OpenMarketHealth) -> Void) {
        let query: String = "healthChecker"
        
        fetchOpenMarketDataTask(query: query) { (data, error) in
            if let error = error {
                print(error.localizedDescription)
                completion(.bad)
            } else if data != nil {
                completion(.ok)
            } else {
                completion(.bad)
            }
        }?.resume()
    }

```

# 📍조언을 얻고 싶은 부분

## Test Double 관련

### Stub, Mock, Spy
- Stub은 상태 기반 테스트로 값을 넣어주면 어떤 값이 출력되는 등의 결과값과 예상 값을 비교하는 객체로 알고있습니다.
- Mock은 행위 기반 테스트로 해당 기능이 원하는 시나리오대로 동작했는지에 대한 여부를 확인하는 객체로 알고있습니다.
- Spy는 Stub의 역활을 수행할 수 있으며 호출에 대한 내용을 기록할 수 있는 객체로 알고있습니다.
- Stub과 Mock의 차이점은 알겠으나 Spy와 Mock의 차이점은 모르겠습니다... 원하는 시나리오대로 동작했는지에 대한 여부를 판단하기 위하면 Mock 또한 호출에 대한 간단한 정보를 기록하는 것으로 알고있는데... Spy또한 해당 기능을 수행할 수 있는 것으로 알고있습니다. Mock과 Spy이의 차이점에 대한 태태의 의견이 궁금합니다!!! 또한 저희가 구현한 Test Double이 각 역활에 맞게 구현되었는지에 대한 태태의 의견이 궁금합니다...

2022-11-18 13:22 UTC, uuu1101 requested changes
STEP1 진행하시느라 고생하셨습니다 👍🏻
데이터를 어떻게 사용할지와 프로토콜에 대한 고민을 많이 해보신것 같네요.
몇가지 코멘트 남겨두었어요 ! 

**[조언을 얻고 싶은 부분에 대한 답변]**

- spy 와 mock의 차이가 무엇인가요? 
> 먼저 Mock만 행동(올바른 호출을 했는지?)을 검증하는 걸로 알고 있습니다.
보통 나머지 Test Double들은 은 일반적으로 상태(최종 결과물)를 검증을 위해 사용하는것으로 알고 있어요.
Mock은 행동검증, Stub은 상태검증이라면 Spy는 행동검증도 사용하는 Stub이라고 이해해보시면 조금 더 이해하기 좋을 것 같아요.

상태검증과 행동검증에 대한 것은 크게 중요하지 않고 Classical TDD vs Mockist TDD 로 나누는게 더 중요하다고 보았어요. 
두 가지 차이점을 알아보시는 것도 좋을 것 같아요! 
위 내용에 대해서는 [마틴 파울러의 글](https://martinfowler.com/articles/mocksArentStubs.html)을 참고 하였습니다.

2022-11-18 13:22 UTC, uuu1101 commented on OpenMarket/OpenMarket/Model/Page.swift
> +        case products = "pages"
서버에서 `pages`로 내려오지만, 작업하기 용이하게 잘 정의하셨네요 👍🏻

2022-11-18 13:22 UTC, uuu1101 commented on OpenMarket/OpenMarket/Model/Product.swift
> +        case vendor = "vendors"
vendor 또한 마찬가지 입니다 👍🏻

2022-11-18 13:22 UTC, uuu1101 commented on OpenMarket/OpenMarket/Model/ProductImage.swift
> +struct ProductImage: Decodable {
필요한 프로토콜만 쓰셨네요 👍🏻

2022-11-18 13:22 UTC, uuu1101 commented on OpenMarket/OpenMarket/URLSession/URLSession.swift
> +extension URLSession: OpenMarketProductFetchable { }
어떻게보면 개인적인 차이가 있을수 있는 부분이라고 생각되는부분인데, 저는 아래와 같이 작성하고 있어요.
그 이유는 어떠한 프로토콜을 따르는지에 대해서 한번에 파악하기 더 편한다고 생각하기 때문입니다.
```suggestion
extension URLSession: OpenMarketURLSessionProtocol, OpenMarketHealthFetchable, OpenMarketPageFetchable, OpenMarketProductFetchable { 
   ...
}
```
여러분들은 어떠한 기준으로 프로토콜 채택에 관한 내용 작성하고 계시는지 궁금합니다 👀

2022-11-18 13:22 UTC, uuu1101 commented on OpenMarket/OpenMarket/Error/Error.swift
> +}
errorDescription이 있다면 더 좋을것 같아요!

2022-11-19 02:56 UTC, oneStar92 commented on OpenMarket/OpenMarket/Model/Page.swift
> +        case products = "pages"
감사합니다 🙇🏻‍♂️

2022-11-19 02:57 UTC, oneStar92 commented on OpenMarket/OpenMarket/Model/Product.swift
> +        case vendor = "vendors"
감사합니다 🙇🏻‍♂️

2022-11-19 02:58 UTC, oneStar92 commented on OpenMarket/OpenMarket/Error/Error.swift
> +}
[5e856ad](https://github.com/yagom-academy/ios-open-market/pull/206/commits/5e856ad2823e8458e52989d6a3ded58ca2a3eb0a)
구현 했습니다 !!

2022-11-19 03:03 UTC, oneStar92 commented on OpenMarket/OpenMarket/URLSession/URLSession.swift
> +extension URLSession: OpenMarketProductFetchable { }
[4cd27d0](https://github.com/yagom-academy/ios-open-market/pull/206/commits/4cd27d0be0a9742095b407a8f85358c0b2006348)
프로토콜을 채택하고 기능 구현이 필요할 때에는 저희가 작성한 코드처럼 작성하면, 채택한 프로토콜의 기능만 구분해서 볼 수 있기 때문에 가독성 면에서 더 좋은 것 같습니다.
하지만 현재 프로토콜에서 default로 메서드를 구현해놓고 해당 메서드를 그대로 사용하기 때문에 태태가 제안해 주신 코드가 가독성 면에서 더 좋은 것 같아 수정했습니다!

2022-11-21 12:53 UTC, uuu1101 commented
고생하셨습니다! 저는 단지 의견을 드리는것이고, 항상 좋은 의견을 드리고 싶지만 그러지 못할 수도 있어요!
혹시나 서로의 생각을 이야기해보고 싶을때는 언제든지 말씀해주세요 ! 
STEP2에서 또 많은 이야기를 나눠보도록 해요!

2022-11-21 12:53 UTC, merged