오픈마켓 [STEP 1] Zhilly, Dragon
yagom-academy/ios-open-market pull request #209
Opened 2022-11-17 03:03 UTC by FlameYG

안녕하세요, 하비(@havilog)🙇‍🙇‍♀️!
[zhilly🔥](https://github.com/zhilly11), [Dragon🐉](https://github.com/FlameYG)입니다!
오픈마켓 STEP-1 코드 작성을 완료하여 PR드립니다!
리뷰 잘 부탁드립니다 :)

# 📍고민했던 부분 

## 서버 데이터타입과 `products.json`파일의 데이터타입이 다름
- 서버 데이터 타입으로 `Testproducts.json`파일을 만들어 하나의 데이터타입으로 UnitTest를 수행했습니다

## 브랜치 전략
- STEP-1이 3단계로 나눠져 있어서 브랜치를 어떻게 만들지 고민했었습니다. main에서 각각의 브랜치를 따로따로 만들어 주는 것보다, STEP-1브랜치를 생성하고 여기서 브랜치를 새로 만들어 주는 방식으로 진행했습니다. 만약 STEP-1-1이 끝난다면 STEP-1으로 Merge 시키는 방식으로 브랜치 전략을 짜 봤습니다.

# 📍조언을 얻고 싶은 부분

- `import`할 때 부분적인 클래스나 메서드만 필요할 경우 `import UIkit.NSDataAsset`와 같이 작성해 작성하는게 좋은 방법일까요?
    - `UIkit` 전체가 아닌 `UIkit.NSDataAsset`만 불러오면 속도측면에서 장점이 있을 것 같은데 이렇게 작성하는걸 현업에서도 선호하는지 궁금합니다
    ```swift
        // 예시
        import UIKit
        import UIKit.NSDataAsset
    ```
- JSONDecodeTests에서 사용할 TestProducts.json파일을 따로 만들어주었는데 이 방법이 좋은 방법인지 궁금합니다
    - 추가로, testProducts.json파일을 Asset에 추가하는 것이 아닌 따로 불러와 사용하는 것이 좋은 방법인지 의견주시면 감사하겠습니다!
- JSONDecodeTests에 작성된 테스트케이스가 적절한지 확인부탁드립니다... 
    - 동일 기능을 테스트하는데 현재 테스트 케이스가 반복적인 테스트라는 느낌을 받아서 최소화로 Int, String, Bool 3가지만 테스트해줘야하는건지 아니면 확실하게 전체 데이터 하나하나를 확인해줘야하는건지 모르겠어서 의견 부탁드립니다!
- Date()타입으로 디코딩
    - `createdAt`나 `issuedAt`를 `Date`타입으로 바로 디코딩 작업을 해주면 좋을 것 같다고 생각을 해서 시도했었으나, 들어오는 데이터가 `Date`타입에 바로 디코딩이 되지 않아서 일단은 `String`타입으로 입력을 받고 추후에 사용할 일이 있을 때 가공을 해서 진행하기로 했습니다. 궁금한 점은 만약 아래처럼 데이터가 들어 올 때 `Date`타입으로 바로 디코딩을 할 수 있는 방법이 있을까요?

        JSON 파일에서 들어오는 데이터 : `2022-01-04T00:00:00.00`
        DateISO8601Format을 print해보았을 때 : `2022-01-25T00:53:06Z`
        
- Test Doubles
    -  현재는 Mock 데이터를 만들고, MockURLSession도 만들어서 실제 네트워크와 통신하는 URLSession에 테스트 할 때 MockURLSession을 주입하여 테스트를 진행했습니다. 이런 방식으로 진행 하는 것이 맞는지 궁금합니다!

P.S. 어제 질문하려던 것은 해결했습니다!.. Mock Unit 테스트에서 뒤에 트레일링 클로저가 실행되지 않는 오류가 있었는데 원인 찾아서 수정해주었습니다🥲

2022-11-18 10:00 UTC, havilog requested changes
안녕하세요 드래곤 질리!
코멘트를 많이 작성하느라 조금 딱딱하게 느껴질 수도 있을거 같지만,,ㅎㅎ
이해안되거나 궁금한거 있으시면 언제든 디코나 커멘트로 문의주시구,
오픈마켓 화이팅입니다!!

cc. 브랜치를 STEP1-1, STEP1-2, STEP1-3으로 쪼개서 STEP1에 머지한다고 하셨는데,
지금 STEP1-3이 바로 ic_7로 머지되는거 같네요!
STEP1이 머지되어야하는거 아닐까요?

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +struct NetworkManager {
NetworkManager를 포함한 네트워크 객체들이 모델 폴더 안에 있네요.
질리와 드래곤이 생각하시는 Model의 정의가 무엇일까요?

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +    private let hostUrlAddress: String = ProductsAPIEnum.hostUrl.address
hostUrlAddress를 self의 property로 가지고 있게 한 이유가 뭘까요?

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +    init(session: URLSessionProtocol = URLSession.shared) {
parameter에 default값을 주신 이유가 있으실까요?

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +    init(session: URLSessionProtocol = URLSession.shared) {
프로토콜로 추상화해주셨는데 이렇게 했을 때 이점이 뭘까요?
이렇게 설계하신 이유를 설명해주시면 좋을거 같아요 :)

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +    }
모든 API 통신들이 네트워크 매니저에서 일어나고 있는데요,
이렇게하면 한 앱에 100개의 API가 있을 때 네트워크 매니저에 100개의 함수가 생기게 되는걸까요?
네트워크 매니저의 역할이 어떤거라고 생각하고 작성해주셨을까요??

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +}
이 함수가 하는 역할은 무엇이라고 생각하시나요?
(Result<Data, NetworkError> -> Void)를 컴플리션으로 넣어주셨는데,
Data를 return하도록 한 이유는 무엇일까요?

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +        task.resume()
.resume()을 안해주면 어떻게 될까요?
반대로, 이 task를 취소해주고 싶으면 어떻게 해야할까요?

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +struct NetworkManager {
이 네트워크 매니저를 struct로 설계하신 근거는 무엇일까요?
네트워크 매니저는 어떠한 프로토콜을 준수한 필요는 없는걸까요?

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/URLSession+Extension.swift
> +extension URLSession: URLSessionProtocol {}
요렇게 사용하려면 아마 completion이 @Sendable 해야할텐데
요 개념은 지금은 어려우니 나중에 공부하시져 ㅎㅎ..

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkEnum/HttpMethodEnum.swift
> +enum HttpMethodEnum {
1. 이미 이 객체는 enum인데 HttpMethod뒤에 Enum이라는 포스트 픽스가 필요할까요?
2. HttpMethodEnum: String을 준수하고, rawValue를 줄 수도 있을텐데 name이라는 computed property를 정의해주신 이유가 있으실까요?

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkEnum/ProductsAPIEnum.swift
> +            return "https://openmarket.yagom-academy.kr"
Host의 경우는 여기에 같이 있지않고 따로 빼는게 좋을거 같아요!
또한 address라는 이름 보다는 path라는 단어로 사용하는 것도 고려해볼 수 있을거 같습니다.
또한 파라미터들을 여기에 정의해주신거 같은데, 파라미더 인코딩하는 부분은 다시 고민해보시면 좋을거 같아요!

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/Get/CurrencyEnum.swift
> +}
[currencySymbol](https://developer.apple.com/documentation/foundation/nslocale/1642814-currencysymbol) 이라는게 있는데 혹시 아시나요?

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/Get/ProductDetail/Image.swift
> +struct Image: Codable {
Codable이 어떤 프로토콜인지 알고 계실까요?

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/Get/ProductDetail/Image.swift
> +    enum CodingKeys: String, CodingKey {
CodingKeys는 해당 객체 내부에서만 사용하기 때문에 private 처리 해주시면 좋을거 같아요!

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/Get/ProductList/Page.swift
> +struct Page: Codable {
Page가 ProductList내부에서만 쓰인다면, ProductList내부나, 같은 파일에 있는것도 고려해볼 수 있을 거 같아요.

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/Get/CurrencyEnum.swift
> +enum Currency: String, Codable {
Get이라는 폴더 내부에 존재하는데, Get이라는 네이밍이 어떤의미인지 잘 파악이 안되네요!
Get이라는 이름에 어떤 유래가 있을까요?

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/JSONDecode+Extension.swift
> +import UIKit.NSDataAsset
UIKit 내부에서 사용할 모듈만 가져와서 좋습니다!
다만 현업에서 어떤지 물어보셨는데, 회바회 팀바팀이겠지만
보통은 저렇게까지 최적화하기 귀찮아서(?) 필요한 경우 UIKit만 import해주는거 같은 느낌을 받긴 했어요!

요런 디테일한 부분을 고민하시는거 좋지만, 너무 많은 시간을 사용해서 전체적인 설계에 영향을 안미칠 정도로 고민하시면 좋을거 같다고 생각합니다 :)

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/JSONDecode+Extension.swift
> +}
JSONDecoder의 extension을 정의해주셨는데,
이 파일이 Model폴더 내부에 있어야하는 이유가 뭘까요?

또한 JSONDecoder의 extension으로 static 함수를 설계하신 이유가 뭘까요?
JSONDecoder를 활용해 질리와 드래곤이 원하는 디코딩 로직을 가진 객체를 생성할 수도 있었을 거 같은데,
두 방법의 차이점과 왜 그걸 선택하셨는지가 궁금해요

2022-11-18 10:00 UTC, havilog commented on OpenMarket/MockURLSessionTests/Mock/MockURLSession.swift
> +final class MockURLSession: URLSessionProtocol {
URLSession을 모킹하는거에는 크게 이상한 점은 없는거 같습니다!
[우아한 형제들 블로그](https://techblog.woowahan.com/2704/) 보셨는지 모르겠지만 참고하시면 좋을 것 같구요,

개인적으로는 
테스터블한 코드를 설계하는게 매우 중요한 일이지만,
현 시점에서는 테스트 코드를 짜는 것 보다는
모 앱의 로직이나 설계적인 부분을 완벽하게 구현한 뒤에 
테스트를 짜는게 더 좋지 않을까라고
조심스럽게 의견드려봅니다!

2022-11-18 10:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/Get/ProductDetail/ProductDetail.swift
> +    let issuedAt: String
요런 부분 Date()로 디코딩하고 싶으시면 디코딩 하는 로직에서 DateFormatter를 통해 해주는 방법이 있다고 알고있는데요,
요건 아마 구글링하면 많이 나올거 같아서 구체적인 방법은 작성하지는 않을게요!

2022-11-18 10:00 UTC, havilog commented on OpenMarket/JSONDecodeTests/JSONDecodeTests.swift
> +final class JSONDecodeTests: XCTestCase {
테스트를 위해 필요한 Mock객체를 json으로 들고 있는거에 대해서는 팀원들끼리 상의해서 괜찮다고 생각하면, 이상한 점은 없는거 같아요!
다만, 모앱에서 테스트를 위한 파일을 asset으로 가지고 있는건 조금 어색하다고 느껴집니다.
또한 테스트를 위한 mock파일을 찾아오는 테스트코드라고 보여지는데,
이 테스트코드가 필요한지도 조금의문이 드네요.
테스트가 필요한 부분은
파일의 이름이 주어졌을 때 해당 파일을 불러올 수 있는지,
어떠한 data가 주어졌을 때 드래곤, 질리가 작성하신 decoding 로직이 정상 동작하는지
이렇게 두개만 있어도 될거 같다고 생각해요!

2022-11-21 01:51 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +struct NetworkManager {
저희가 생각하는 Model의 정의는 MVC 패턴으로 나눴을 때,
Model에는 데이터가 저장되고, 비즈니스 로직을 관리하는 것이라고 생각합니다
그래서 MVC 중 적합한 위치를 고르다보니 NetworkManager가 View와 관련된 작업을 하지 않는다고 생각되어 Model에 포함시켰습니다!

2022-11-21 01:58 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +    private let hostUrlAddress: String = ProductsAPIEnum.hostUrl.address
원래는 자주 사용할 것 같아서 내부에 property로 가지고 있게 했었습니다.
추후에 enum으로 분리하는 작업을 했었습니다.
저희 생각에는 자주 사용하는 값들은 사용할 때마다 enum에서 복사하는 것보다 한 번만 enum에서 값을 복사하는 것이 이득이라고 생각해서 작성했습니다!

2022-11-21 02:07 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +    init(session: URLSessionProtocol = URLSession.shared) {
기본적으로는 NetworkManager를 사용할 때, URLSession.shared를 사용하기 위해 Default값으로 사용하였습니다

2022-11-21 02:17 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +    init(session: URLSessionProtocol = URLSession.shared) {
프로토콜을 채택하는 클래스마다 다르게 구현해서 커스텀 하게 메서드를 구현할 수 있는 이점이 있다고 생각합니다.
추후에 또 다른 URLSession 객체를 만들 때에도 채택하게 해서 만들 수 있습니다.

이렇게 설계한 이유는 MockURLSession을 커스텀 URLSession으로 만들기 위해서 설계했습니다 :)

2022-11-21 02:27 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +}
URL Request를 받아 Load Error 확인 후 Response-Status Code에 따라 나눠지는 에러를 확인한 다음 Data에 값이 있다면 Data 값을 가져올 수 있도록 하는 역할이라고 생각합니다.
받아온 Data를 사용할 수 있도록 completion return값으로 사용하였습니다~!

2022-11-21 02:37 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +        task.resume()
모든 작업은 `suspend` 상태로 시작한다고 알고 있습니다.
그래서 `.resume()`을 안해주면 `suspend` 상태로 있게 됩니다.
반대로 취소를 해주고 싶다면 `cancel`을 사용하면 됩니다!

2022-11-21 02:39 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +struct NetworkManager {
NetworkManager에서 상속받을 것이 없어서 Struct로 설계하였습니다...!
현 단계에서는 프로토콜을 준수할 게 없다고 생각하였습니다.

2022-11-21 02:48 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkEnum/HttpMethodEnum.swift
> +enum HttpMethodEnum {
1. `httpMethod`가 이미 있어서 뒤에 `Enum`키워드를 붙여서 작성했습니다.
2.  `HttpMethod.get.name`이 `HttpMethod.get.rawValue`로 사용하는 것보다 가독성이 좋다고 생각해서 computed property를 사용하여 작성했습니다 :)

2022-11-21 02:53 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Model/Network/Get/ProductDetail/Image.swift
> +struct Image: Codable {
`Codable`은 `Decodable`+`Encodable`을 합쳐놓은 것으로 알고 있습니다~!
그래서 JSON파일을 만들 수 있고, 추출할 수도 있습니다
현재는 `Encodable`하는 경우가 없을 것으로 생각되어 `Decodable`로 수정하도록 하겠습니다!

2022-11-21 03:16 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Model/JSONDecode+Extension.swift
> +}
> JSONDecoder의 extension을 정의해주셨는데,
이 파일이 Model폴더 내부에 있어야하는 이유가 뭘까요?

폴더를 MVC 구조를 살려서 가자 라는 생각에 Model 안에 들어가게 되었습니다만, 하비 의견을 듣고 새로운 폴더를 만들어서 관리해 줘도 좋을 것 같다는 생각을 했습니다. 저희가 만약 수정한다면 MVC 폴더 외에 extension 폴더를 만들어 거기에 넣어 줄 것 같습니다. 
또한 저희 파일들만 보시면 하비는 어떻게 폴더를 구분 지으실지 궁금하기도 합니다!

>또한 JSONDecoder의 extension으로 static 함수를 설계하신 이유가 뭘까요?

decode 기능을 자주 사용할 것 같아서 그때마다 JSONDecoder를 불러와서 할당해 주고 하는 것보다 쉽게 사용할 수 있고 코드 중복을 막을 수 있다고 생각해서 작성했습니다.

>JSONDecoder를 활용해 질리와 드래곤이 원하는 디코딩 로직을 가진 객체를 생성할 수도 있었을 거 같은데,
두 방법의 차이점과 왜 그걸 선택하셨는지가 궁금해요

디코딩을 할 때마다 디코딩 로직을 가진 객체를 생성하는 것보다 extension을 활용하는 게 메모리 관점에서 봤을 때 어느 정도 이득이 있다고 생각했습니다. 또한 수평적 확장이라고 생각해서 extension을 이용한 이유도 있습니다!

2022-11-21 11:43 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +    }
네트워크 매니저에서 API를 호출할 때 `URL` 때문에 많은 메서드들이 생긴다고 생각을 했습니다.
따라서 API를 호출할 때 사용하는 `URL`들을 관리하고 만들어 줄 수 있는 `URLManager` 타입을 새로 생성하여 리팩토링 진행했습니다. 

사실 처음 네트워크 관련한 작업을 하면서 네트워크 매니저의 역할에 대해서 잘 모르고 진행했던 부분이 있습니다.
저희가 하비의 질문을 듣고 다시 생각해 봤을 때에는 URL을 가지고 서버에 요청해서 성공 여부나 데이터까지 가져오는 역할로 정의를 내리고 코드 작성을 했습니다.

하비가 생각하시는 네트워크 매니저의 역할은 어디서부터 어디까지일까요? 궁금합니다!

2022-11-21 11:48 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkEnum/ProductsAPIEnum.swift
> +            return "https://openmarket.yagom-academy.kr"
[4417b3a](https://github.com/yagom-academy/ios-open-market/pull/209/commits/4417b3aa3427b16d585c8438c5a327f1ab264ce3)

에서 URL 관련한 부분들 새로 작성해 봤습니다!
`URLComponents`를 사용해 봤는데 이런 식으로 사용하는 게 적절할 지도 궁금합니다

2022-11-21 12:00 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Model/Network/Get/CurrencyEnum.swift
> +}
아니요... 몰랐는데 덕분에 찾아보고 코드에 적용할 수 있었습니다! 감사합니다 😃
[5e09dd3](https://github.com/yagom-academy/ios-open-market/pull/209/commits/5e09dd39a59cdd3e16db9cc0195ea2de455488f7)

2022-11-21 13:11 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Model/Network/Get/ProductDetail/Image.swift
> +    enum CodingKeys: String, CodingKey {
[91347ce](https://github.com/yagom-academy/ios-open-market/pull/209/commits/91347cec9efcf1b5ce01f8b694135ada772f3d70)
네! 덕분에 놓친 부분 보완하였습니다~!

2022-11-21 13:14 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Model/Network/Get/ProductList/Page.swift
> +struct Page: Codable {
[91347ce](https://github.com/yagom-academy/ios-open-market/pull/209/commits/91347cec9efcf1b5ce01f8b694135ada772f3d70)
네! Page와 ProductDetail 파일도 겹치는 타입이 많아서 Product라는 파일로 통합하였고,
Product관련된 JSON파일은 Product폴더에 같이 넣는 것으로 변경하였습니다.

2022-11-21 14:18 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Model/Network/Get/CurrencyEnum.swift
> +enum Currency: String, Codable {
[32c3b68](https://github.com/yagom-academy/ios-open-market/pull/209/commits/32c3b68fb802047c2e7a3a22d755b0450747b47f)
HTTPMethod(Get,Post,Delete...)로 구분을 하고자 Get이라는 이름을 사용했었습니다~!
코드 리팩토링 과정에서 파일들을 정리하다보니 다시 한번 파일구분을 해주었습니다!

그런데 저희가 파일 구분에 대한 명확한 개념이 없다보니... 
지금 정리된 파일 상태에서 추가적으로 보완할만 내용이 있으시다면 피드백 부탁드립니다!~ 😃

2022-11-21 14:38 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +struct NetworkManager {
음 제가 생각했을 때의 MVC는 presentation layer단에서의 패턴이고, 네트워크나 비즈니스로직, extension등이 Model이 들어있는건 어색하다고 느껴졌어요!
따라서 Model, View, Controller와 네트워크, extension 등은 폴더가 분리되는게 자연스러워 보인다고 생각되어요!

2022-11-21 14:39 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +    private let hostUrlAddress: String = ProductsAPIEnum.hostUrl.address
아래 네트워크 매니저의 역할 코멘트에서 한번에 대체할게요!

2022-11-21 14:40 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +    init(session: URLSessionProtocol = URLSession.shared) {
이게 틀린건 아니지만, 정말 의존성을 분리하려면 하위 객체는 주입받을 상위 객체를 모르고 있어야 하는게 원론적(?)인 개념으로 맞는 일이어서, 요렇게 쓰는게 위험할 수도 있다는거만 인지하고 사용하시면 좋을거 같아요

2022-11-21 14:44 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +    init(session: URLSessionProtocol = URLSession.shared) {
질문이 조금 애매했는데요, ㅠㅠ
질문의 의도는 프로토콜로 추상화해서 13번 라인에서 주입해주었는데,
이때 dependency inversion principle, dependency injection 등의 개념을 알고,
왜 이렇게 해줘야 테스트가 가능한지 등까지 알고 계셨으면 좋겠어서  질문드렸습니다~!

2022-11-21 14:52 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +    }
네트워크 매니저란, 해당 앱에서 전반적인 모든 네트워크 통신을 담당하는데요.
예를 들면 홈, 설정, 로그인 등 모든 API 통신이 이 네트워크 매니저를 타야해요.
따라서 이 네트워크 매니저는 어떤 API 통신을 하던 재사용과 확장에 용이해야할거 같아요
그래서 특정 도메인의 URL을 들고 있는게 이상해보였구요!

따라서 제가 생각했을 때에는 어떠한 요청이 왔을 때, 그 요청을 네트워크를 태우고, 응답을 받아서 넘겨주는거 까지가 네트워크 매니저의 역할이라고 생각해요.
그 과정에서 URLRequest를 만들고, validate하고, error 핸들링하는 등의 역할은 또 다른 객체들의 역할이라고 생각합니다 ㅎㅎ

2022-11-21 14:54 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +}
이게 틀린 코드는 아니지만,
보통 일반적인 네트워크 매니저 코드에서는 decoding까지 해주는게 보통이라서 여쭤봤었고,
여기서 decoding을 안해준다면, viewcontroller에 data를 주기 전에 decoding하는 객체가 있을거라 생각했었어요!

2022-11-21 15:02 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +struct NetworkManager {
오 사실 이 질문은 훨씬 더 많은 대답을 기대했었는데요,

1. 프로토콜을 준수할 필요가 없다고 하셨는데, 프로토콜이란 해당 객체가 하는 역할을 명시하는 역할도 있다고 생각해요.
``` swift
protocol NetworkRequestable {
// func request...
}
```
이런식으로 명시해서 준수시켜주면,
외부에서 네트워크 매니저가 어떤 역할을 하는지도 명시하고, 더불어 MockNetworkManager를 넣어주어 테스터블한 코드의 작성도 가능해질거라 생각해요.
2. 상속받을 것이 없다고 하셨는데, 왜 상속받을것이 없는지, class와 struct의 차이는 상속밖에 없는지, 재사용성과 성능상의 이점에 대한 측면들도 설명해주시면 좋을거 같구요
3. 가지고 있는 property들이 자주 바뀔 여지가 있는지, 그에 의해 data race등이 발생할 수 있는지
등 드래곤과 질리가 가지고 계시는 지식들을 전부 말해주시는게
면접에서 물어보는 질문에 대비하기 좋다고 생각합니다~!

2022-11-21 15:06 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkEnum/HttpMethodEnum.swift
> +enum HttpMethodEnum {
postfix로 enum이 한번 더 있는건 뭔가 redundant한 시그니처를 전달하는거 같아서
기존에 있던 httpMethod의 이름이 다른게 되면 어떨지 제안드려봅니다!

2022-11-21 15:48 UTC, havilog approved these changes
두 분 모두 고생하셨어요!!
랩업해서 말씀드리자면,

1. 네트워크 매니저가 확장성에 더 열려있으면 좋을거 같다고 생각했어요.
request함수도 endpoint같은 걸 받는 방법도 찾아보시면 좋을 거 같구요,
현 시점에서는 힘들 수도 있지만, alamofire도 반드시 까보시는거 추천드려요~!

2. 폴더링 관련해서는 MVVM이나 clean-architecture 같은 개념들 읽어보시면 도움이 될거 같지만,
Model은 보통 Product 내부에 있는 아이들을 지칭하는거 같아요!

잘 짜여진 네트워크 구글링해서 이 사람들이 어떻게 짰는지, 왜 이렇게 짰는지를 분석해보는 것도 좋은 방법 일 것 같습니다.

2022-11-22 01:53 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +    init(session: URLSessionProtocol = URLSession.shared) {
네네 하비가 말씀해 주신 개념들 생각해서 코드 수정했습니다!

2022-11-22 02:47 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +}
[675f2a1](https://github.com/yagom-academy/ios-open-market/pull/209/commits/675f2a169a633922c37616158ce1aa974b5c60e7)
아하...! 조언주신 내용으로 질리와 상의한 후 적용하는게 맞다고 판단하여
NetworkManager에서 JSONDecoding까지 처리하도록 수정하였습니다!

2022-11-22 03:07 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +struct NetworkManager {
1. 하비의 의견처럼 어떤 역할을 하는지 명시 가능하다는 말에 동의합니다! 그래서 `NetworkManager`가 `NetworkRequestable`을 채택해서 이런 역할을 한다는 것을 코드로 작성해 줬습니다. 이렇게 작성하니까 하비의 의견처럼 Unit Test에서도 `NetworkRequestable`을 통해 테스트할 수 있다는 것도 깨닫고 수정해 주었습니다.

2. 아직까지는 `NetworkManager`의 상속이 필요 없어서 struct로 구현을 했습니다. class와 struct의 차이점은 여러 가지가 있지만 애플에서는 기본적으로 struct 사용을 권장하고 상속이 필요하거나, obj-c 메서드를 상속 등을 할 때 class를 사용하면 된다고 알고 있습니다! 또한 속도 측면에서도 struct가 class 보다 빠르다고 알고 있고, class보단 final class가 빠르다고 알고 있습니다.

3. 3번에 관련해서는 깊게 고민해 본 적이 없는 것 같습니다! 드래곤과 한 번 학습해 보도록 하겠습니다!~~

2022-11-22 03:07 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkEnum/HttpMethodEnum.swift
> +enum HttpMethodEnum {
네! 질리랑 이야기해서 `httpMethodEnum` -> `httpMethod` 로 변경하였습니다

2022-11-22 03:13 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Model/Network/Get/ProductDetail/ProductDetail.swift
> +    let issuedAt: String
[bd7bdf2](https://github.com/yagom-academy/ios-open-market/pull/209/commits/bd7bdf259e3bb494f2740100fb7ab05ee4a9854f)

Date타입 적용해보았습니다!

2022-11-22 03:15 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Model/Network/NetworkManager.swift
> +    }
의견 감사합니다!
주신 의견으로 질리랑 이야기 나눠보았는데, 아직 네트워크를 어떻게 사용하는지 전체적인 그림이 그려지지 않아
네트워크매니저의 역할도 조금은 애매모호했던 것 같습니다... (좋은 네트워크설계 코드를 한번 찾아봐야겠습니다...)
그래서 일단은 현재 코드를 유지하고 스텝을 진행하며 네트워크에 대한 방향성이 세워지면 네트워크매니저를 다시 한번 손보도록 하겠습니다!

2022-11-22 03:31 UTC, merged