[STEP 1] Fezz, Tak
yagom-academy/ios-open-market pull request #21
Opened 2021-05-12 13:29 UTC by Fezravien

# [STEP 1] Open Market 🥕

@O-O-wl 
### 안녕하세요 붱이 🦉

저희가 고민하고, 적용했던 부분에 대해 구체적으로 작성해볼게요! 잘 부탁드려요 😄

---

## 배경

 저희는 프로토콜간의 `상속`과 `컴포지션`으로 각각의 모델에 적합한 프로토콜을 조합하여 채택할 수 있도록 고민해봤어요. 

단순하게 구조체를 나열하는 것 보다 프로토콜을 통해서 모델의 확장성과 유연성을 증가시키려고 사용해봤어요

- 프로토콜지향 설계 

<img src="https://raw.githubusercontent.com/Fezravien/UploadForMarkdown/forUpload/img/OpenMarketModel.jpg" alt="OpenMarketModel" style="zoom:40%;" />

<br/>

## 작업내용

#### 파싱 모델

##### 모델 분류

<img src="https://raw.githubusercontent.com/Fezravien/UploadForMarkdown/forUpload/img/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202021-05-12%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%209.56.00.png" alt="스크린샷 2021-05-12 오후 9.56.00" width="30%"  /> 

`Product` : 프로토콜 

`MarketItems` : 목록 조회

`MarketItem` : 상품 조회

`ItmeUpdate` :  상품 등록

`ItemDetailUpload` :  상품 수정

`ItemDelete` : 상품 삭제 

<br/>

##### 이니셜라이져

```swift
// MarketItme 예시 
struct MarketItem: ProductInfo, ProductDetail {
    let id: UInt
    let title: String
    let descriptions: String
    let price: UInt
    let currency: String
    let stock: UInt
    let discountedPrice: UInt?
    let thumbnails: [String]
    let images: [String]
    let registrationData: Double
    
    enum CodingKeys: String, CodingKey {
        case id, title, descriptions, price, currency, stock, thumbnails, images
        case discountedPrice = "discounted_price"
        case registrationData = "registration_date"
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = (try? container.decode(UInt.self, forKey: .id)) ?? 0
        self.title = (try? container.decode(String.self, forKey: .title)) ?? ""
        self.descriptions = (try? container.decode(String.self, forKey: .descriptions)) ?? ""
        self.price = (try? container.decode(UInt.self, forKey: .price)) ?? 0
        self.currency = (try? container.decode(String.self, forKey: .currency)) ?? ""
        self.stock = (try? container.decode(UInt.self, forKey: .stock)) ?? 0
        self.discountedPrice = (try? container.decode(UInt?.self, forKey: .discountedPrice)) ?? 0
        self.thumbnails = (try? container.decode([String].self, forKey: .thumbnails)) ?? []
        self.images = (try? container.decode([String].self, forKey: .images)) ?? []
        self.registrationData = (try? container.decode(Double.self, forKey: .registrationData)) ?? 0.0
    }
}
```

`MarketItem` 예시에서 처럼 `Codingkeys`를 활용한 이니셜라이져로 네트워크 과정에서 JSON 데이터와 모델간에 다른 부분이 존재할때 **앱이 종료되는 상황**을 막기 위해 사용했어요. (기대 타입 : `Int`, JSON: `String`)

<br/>

#### 네트워크 

#### 네트워크 분류

Method 별로 네트워크 작업을 분류해봤어요 

조회, 등록, 수정, 삭제

<img src="https://raw.githubusercontent.com/Fezravien/UploadForMarkdown/forUpload/img/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202021-05-12%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%2010.01.09.png" alt="스크린샷 2021-05-12 오후 10.01.09" width="30%" />  

`MarketAPI` : Open Market API의 Base URL, Method, Path 정리

`GetItems` : Method - "GET", Path - "/items/"  네트워크 작업 

`GetItem` : Method - "GET", Path - "/item"  네트워크 작업

나머지 (POST, PATCH) 부분은 추후 구현할 예정이에요 파일만 나눴습니다 ! 

<br/>

#### Unit 테스트 

##### Mock

`Assets` 파일에 저장된 `Mock` file (Items, Item)을 가지고 파싱 테스트 

```swift
func test_목록조회_Items_테스트() {
        guard let marketItems = NSDataAsset(name: "Items") else {
            XCTAssert(false)
            return
        }
        do {
            let result = try JSONDecoder().decode(MarketItems.self, from: marketItems.data)
            XCTAssertEqual(result.items.first?.id, 1)
            XCTAssertEqual(result.items.first?.title, "MacBook Pro")
            XCTAssertEqual(result.items.first?.price, 1690)
            XCTAssertEqual(result.items.first?.currency, "USD")
            XCTAssertEqual(result.items.first?.stock, 0)
            XCTAssertEqual(result.items.first?.thumbnails, [
                "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/thumbnails/1-1.png",
                "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/thumbnails/1-2.png"
            ])
            XCTAssertEqual(result.items.first?.registrationData, 1611523563.7237701)
        } catch {
            XCTAssert(false)
        }
    }
```

##### 비동기 네트워크

`GetItems`, `GetItem` 비동기 네트워크 테스트

```swift
func test_네트워크_Items_잘들어오냐() {
        let exception = XCTestExpectation()
        getItems?.network(completion: { data in
            guard let data = data else {
                XCTAssert(false)
                return
            }
            self.marketItemsData = data
            exception.fulfill()
        })
        wait(for: [exception], timeout: 10.0)
        XCTAssertEqual(marketItemsData?.page, 1)
        XCTAssertEqual(marketItemsData?.items.first?.id, 43)
        XCTAssertEqual(marketItemsData?.items.first?.title, "Apple Pencil")
        XCTAssertEqual(marketItemsData?.items.first?.price, 165)
        XCTAssertEqual(marketItemsData?.items.first?.currency, "USD")
        XCTAssertEqual(marketItemsData?.items.first?.discountedPrice, 160)
        XCTAssertEqual(marketItemsData?.items.first?.stock, 5000000)
        XCTAssertEqual(marketItemsData?.items.first?.thumbnails, [
              "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/thumbnails/3371E602-2C29-4734-8A9A-83A37DD24EAE.png",
              "https://camp-open-market.s3.ap-northeast-2.amazonaws.com/thumbnails/847BD5A2-8BFF-4A7F-BAD4-75E59330445D.png"
        ])
        XCTAssertEqual(marketItemsData?.items.first?.registrationData, 1620633347.3906322)
    }
```

```swift
let exception = XCTestExpectation()
exception.fulfill()
wait(for: [exception], timeout: 10.0)
```

`URLSession`은 비동기 작업이라 데이터가 들어오기 전에 `XCTAssertEqual(...)`을 하는 문제점이 존재했어요 
그래서 저희는 `XCTestExpection`을 이용해서 비동기 작업으로 데이터가 들어오는 시간 최대 10.0초 기다리도록 하여 테스트를 진행해봤어요 

<br/>

---

## 궁금한 점 

저희가 이번 프로젝트 아키텍처로 `MVVM`을 생각하고 있는데요. 

- 저희가 프로토콜을 이용하여 설계한 모델이 적합할지 궁금해요 
- 네트워크는 `ViewModel`에 들어갈지, 지금 처럼 네트워크로 따로 빼고 `ViewModel`에서 이용하는게 더 좋을지 궁금해요
- 앞으로 스텝을 진행해 가면서 어떻게 하면 `Testable` 하게 구현할 수 있을지 ! 

### `붱이`의 의견이 필요해요 !!

2021-05-13 21:06 UTC, O-O-wl requested changes
고생하셨어요 피즈 탁! 🎉
몇가지 코멘트를 남겨보았습니다 

> 저희가 이번 프로젝트 아키텍처로 MVVM을 생각하고 있는데요.
> 
> 저희가 프로토콜을 이용하여 설계한 모델이 적합할지 궁금해요
> 네트워크는 ViewModel에 들어갈지, 지금 처럼 네트워크로 따로 빼고 ViewModel에서 이용하는게 더 좋을지 궁금해요

MVVM을 채택하셨다니 아키텍처를 좋아하는 저로써는 기대가 되는 부분이네여
MVVM에 ViewModel에 네트워크 로직 처리에 대해서 말씀하셨는데
음 관점에 따른 차이가 있겠지만 ViewModel이라는 컴포넌트가 가지는 역할에 대해서 생각해보시면 좋을 것 같아요 - 또 아래의 Testable 관점에 대해서도 같이 생각해보면 
ViewModel에서 아예 네트워크로직을 가지고 있으면 테스트가 가능할지?  (저는 안될 것 같은데 .. ㅎ ㅡㅎ ...)
MVC - MVVM의 차이를 느끼기 전에 앞서 
C - VM 을 제외한 V, M 에 대한 정의를 잘 내리는 것도 중요한 것 같아요.
개인,회사 마다 V의 정의는 비슷하지만 M의 정의는 정도의 차이가 있어서 이 부분은 답이 있지않지만 어떻게 M을 구성할지? M을 어떻게 구성해야 Testable할지? 와 같은 고민들을 해보실 수 있지 않을까 싶어요

> 처음에 URLComponents(base URL), queryItem로 연결을 했었는데 url을 인코딩하니 오히려 안되는 경우가 있었어요. 그래서 지금 수정된 방식은 단순히 문자열을 이어 붙이는 방식으로 구현했어요. 왜 URLComponests로 이어 붙이면 왜 안될지? 궁금해요

요건 있었던 상황을 자세히 좀 더 설명해주시면 도움이 될 것 같아요 현재의 질문으로는 어떤 상황인지 잘 이해가 되지 않아서요 🤔

> 앞으로 스텝을 진행해 가면서 어떻게 하면 Testable 하게 구현할 수 있을지 !
몇가지 Testable에 필요한 요소들이 있어요, 현재 제가 떠오르는 것은
- 객체가 작게 역할의 분리될 것
- 추상화를 통해 테스트 환경에서는 테스트 대역으로  다른 오브젝트와의 의존성을 뜯어내어 격리화된 UnitTest를 시행할 수 있게 구현할 것

이러한 코드를 의식적으로 작성하기 어렵다면 강제화 하는 방법도 있어요 (ex: TDD ...) ㅎ ㅡㅎ

2021-05-15 06:59 UTC, Tak95 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +            XCTAssert(false)
네! 의도한게 맞긴한데 XCTFail()을 썼을때와 XCTAssert(false)를 썼을 때의 차이점을 찾지 못했는데 혹시 둘의 차이가 어떤게 있을까요? XCTAssert(false)를 사용해도 읽히는데는 무리가 없을것 같아서요!

2021-05-15 07:46 UTC, Tak95 commented on OpenMarket/OpenMarket/Network/MarketAPI.swift
> +    }
`CustomStringConvertible` 프로토콜을 채택한 타입에서 인스턴스를 문자열로 반환하는 커스텀 프로토콜이라고 찾아봤어요. 
rawValue는 말그대로 해당 타입의 원시값이고, description은 인스턴스의 텍스트 표현이라고 생각해요.
저 상황에선 `CustomStringConvertible` 프로토콜을 사용하는건 적절하지 않았던 표현이었던 것 같아요.
위 상황에선 그냥 각 case에 rawValue로 값을 정해주는게 더 맞는 것 같습니다. 수정하겠습니다!

2021-05-15 07:49 UTC, Tak95 commented on OpenMarket/OpenMarket/Network/MarketAPI.swift
> +    static let api = "https://camp-open-market-2.herokuapp.com"
찾아보고 수정하겠습니다!🙆🏻‍♂️

2021-05-15 07:49 UTC, Tak95 commented on OpenMarket/OpenMarket/Network/GetItems.swift
> +        guard let MarketUrl = combineURL() else {
🙆🏻‍♂️수정하겠습니다!

2021-05-21 14:21 UTC, Fezravien commented
# [STEP 1] Open Market 🥕 - 2


@O-O-wl 
안녕하세요 `붱이` 🦉

생각치 못하게 많이 늦어졌네요 😅

그 동안 `붱이`랑 얘기 하며 개선하고 새롭게 구현된 부분을 구체적으로 작성해 볼게요 잘 부탁드립니다 !! 

<br/>

---

#### Network 구조도

![OpenMarket](https://raw.githubusercontent.com/Fezravien/UploadForMarkdown/forUpload/img/OpenMarket.jpg)



### 작업 내용 🔨

#### 모델

> 해당형태로 데이터 모델이 늘어나다보면 키 하나의 변경에 여러 데이터모델의 프로퍼티가 바뀔 것 같아요
> 관리할 데이터모델 수를 줄이는 방법도 있을 것 같아요
> 각각의 API의 데이터 모델 형태가 완전히 가지는 별도의 데이터 모델로 선언하신 것 같아요
> **관리할 데이터 모델의 수가 많아진다 vs 불필요한 옵셔널 프로퍼티가 생긴다**
> 에서의 의사결정만 잘 되신다면 좋을 것 같아요 🙇‍♂️

저희는 이번 프로젝트에서는 **"관리할 데이터 모델의 수가 많아진다"** 라는 방향이 더 적절하다고 생각했어요. 그래서 이 부분을 **잘** 관리하기 위해서 `Protocol`의 상속과 컴포지션을 활용했어요.

`붱이`가 말씀해주신 나중에 어떤 것이 프로토콜에 있는지 하나하나 확인하는 것이 힘들 수 있다고 하셨는데, 저희는 그런 관점보다는 추후에 추가되는 모델, 데이터에 있어서 확장성, 유연성 (**프로토콜에 추가, 삭제가 일어나면 컴파일 오류**)에 초점을 두었어요 !! 

<br/>

#### 네트워크

이번 프로젝트의 **꽃**이라 생각되네요 ... 🥀



##### Testable Network 만들기

첫 번째로 `URLSession` 부분 (네트워크 작업), 네트워크 요청을 받는 부분으로 나눴습니다.  

그 이유는 `URLSession`, `JSONDecoder` 가 메서드에 의존하는 상황 때문에 테스트가 힘들기 때문에 `프로토콜`로 추상화하여 그 `프로토콜`에 의존하게 함으로써 의존성을 역전시켰어요. 

```swift
// 의존성 역전을 위한 추상화 프로토콜
// Network
protocol MarketNetwork {
    func excuteNetwork(request: URLRequest, completion: @escaping (Result<Data, Error>) -> Void)
}

// Decoder
protocol DecoderProtocol {
    func decode<T>(_ type: T.Type, from: Data) throws -> T where T : Decodable
}

extension JSONDecoder: DecoderProtocol {
    
}

// 의존성 역전 및 주입 부분
let loader: MarketNetwork
let decoder: DecoderProtocol

// 네트워크 요청 부분
func excute<T>(request: URLRequest, decodeType: T.Type, completion: @escaping (Result<T, Error>) -> Void) where T: Decodable {
        loader.excuteNetwork(request: request) { result in
            switch result {
            case .failure(let error):
                completion(.failure(error))
            case .success(let data):
                do {
                    let jsonDecode = try decoder.decode(T.self, from: data)
                    completion(.success(jsonDecode))
                } catch {
                    completion(.failure(error))
                }
            }
        }
    }

// 네트워크 실행 부분
func excuteNetwork(request: URLRequest, completion: @escaping (Result<Data, Error>) -> Void) {
        session.dataTask(with: request) { data, response, error in
            guard error == nil else {
                completion(.failure(MarketError.request))
                return
            }
            
            guard let response = response as? HTTPURLResponse, (200...299) ~= response.statusCode else {
                completion(.failure(MarketError.response))
                return
            }
            
            guard let data = data else {
                completion(.failure(MarketError.data))
                return
            }
            completion(.success(data))
            
        }.resume()
    }
```



##### Request 만들기 

HTTP Method에 `"GET","POST", "PATCH", "DELETE"` 부분의 네트워크를 URLRequest, 제네릭을 통해 하나의 메서드로 구현했어요

그 이유는 Requset에는 `URL, Method, Body, forHTTPHeaderField` 등 여러가지 설정을 넣거나 변경할 수 있어서 그러한 특성을 이용했어요 

그래서 외부에서 `URLRequest`를 주입 받아서 사용하도록 구현했습니다 !

```swift
func excute<T>(request: URLRequest, decodeType: T.Type, completion: @escaping (Result<T, Error>) -> Void) where T: Decodable {
        loader.excuteNetwork(request: request) { result in
            switch result {
            case .failure(let error):
                completion(.failure(error))
            case .success(let data):
                do {
                    let jsonDecode = try decoder.decode(T.self, from: data)
                    completion(.success(jsonDecode))
                } catch {
                    completion(.failure(error))
                }
            }
        }
    }
```



HTTP Method에 따라 Request를 만든 방식에도 차이가 있었는데요 

- GET : URL 
- POST, PATCH : URL, Method, Body, forHTTPHeaderField (**"multipart/form-data; boundary"**)
- DELETE : URL, Method, Body, forHTTPHeaderField (**"application/json"**)

그 중에서 `multipart/form-data` 은 단순히 JSONEncoder를 사용하는 것이 아닌 형식을 만들어줘야 했어요 

`프로토콜`과 `익스텐션`을 활용해서 구현했습니다.  

```swift
// 이미지 아닌것 
func convertMulitPartForm(name: String, value: Any, boundary: String) -> Data {
        var element = Data()
        
        element.append("--\(boundary)\r\n")
        element.append("Content-Disposition: form-data; name=\"\(name)\"\r\n\r\n")
        element.append("\(value)\r\n")
        
        return element
}

// 이미지 
func convertMulitPartForm(imageName: String, images: [Data], boundary: String) -> Data {
        var element = Data()
        
        for image in images {
            element.append("--\(boundary)\r\n")
            element.append("Content-Disposition: form-data; name=\"images[]\"; filename=\"\(imageName)\"\r\n")
            element.append("Content-Type: image/png\r\n\r\n")
            element.append(image)
            element.append("\r\n")
		}
        
        return element
}
```

- 고민 : `Any` 을 지양하고 싶은데... 혹시 다른 방법이 있을까요 ?

```swift
let mirror = Mirror(reflecting: body)
var bodyToDictionary: [String: Any] = [:]
        
mirror.children.forEach {
		guard let label = $0.label else { return }
		bodyToDictionary["\(label)"] = $0.value	
}
```



##### 테스트

네트워크에 의존하지 않기 위해서 `Mock`을 활용했어요 

- MockNetwork : 가짜 네트워크로 성공, 실패를 지정해서 반환할 수 있음
- MockDecoder : 파싱은 `MarketItems`, `MarketItem` 타입이므로 조건문을 통해서 맞다면 기본값을 반환 

```swift
// MockNetwork 
class MockNetworkloader: MarketNetwork {
    var inputRequest: URLRequest?
    var executeCalled = false
    var resultToreturn: Result<Data, Error>?
    
    func excuteNetwork(request: URLRequest, completion: @escaping (Result<Data, Error>) -> Void) {
        executeCalled = true
        inputRequest = request
        completion(resultToreturn!)
    }
}

// MockDecoder 
class MockDecoder: DecoderProtocol {
    func decode<T>(_ type: T.Type, from: Data) throws -> T where T : Decodable {
        if type == MarketItems.self {
            return MarketItems(page: 1,
                               items: []) as! T
        } else if  type == MarketItem.self {
            return MarketItem(id: 1,
                              title: "",
                              descriptions: "",
                              price: 1,
                              currency: "",
                              stock: 1,
                              discountedPrice: 1,
                              thumbnails: [],
                              images: [],
                              registrationData: 0.0) as! T
        } else {
            throw(MarketError.decoding)
        }
    }
}
```

<br/>

- 테스트 수행 예시 GET, POST 성공

```swift
// GET 성공 테스트 
func test_network_excute_GET_성공() {
        mockClient?.resultToreturn = .success(mockItems!)
        let sut = MarketNetworkManager(loader: mockClient!, decoder: mockDecode!)
        let url = MarketAPI.Path.items(page: 1).url
        let request = URLRequest(url: url!)
        let expectation = XCTestExpectation(description: "GET 목록조회")
        
        sut.excute(request: request, decodeType: MarketItems.self) { (result: Result<MarketItems, Error>) in
            switch result {
            case .success(_):
                XCTAssert(true)
            case .failure(_):
                XCTFail()
            }
            
            expectation.fulfill()
        }
        wait(for: [expectation], timeout: 5)
        XCTAssertTrue(mockClient!.executeCalled)
    }

// POST 성공 테스트
func test_network_excute_POST_상품등록_성공() {
        mockClient?.resultToreturn = .success(Data())
        let sut = MarketNetworkManager(loader: mockClient!, decoder: mockDecode!)
        let url = MarketAPI.Path.registrate.url
        let request = sut.createRequest(url: url, encodeBody: TestData.registrateData, method: .post)
        let result = try! request.get()
        let expectation = XCTestExpectation(description: "POST 상품등록")
        
        sut.excute(request: result!, decodeType: MarketItem.self) { (result: Result<MarketItem, Error>) in
            switch result {
            case .success(_):
               [...]

2021-05-22 03:33 UTC, O-O-wl approved these changes
고생하셨습니다! 
너무 지체 되었으니 머지 진행하겠습니다!

코멘트로 남겨둔 부분만 참고해주세요 🙇‍♂️

2021-05-22 03:33 UTC, O-O-wl commented on OpenMarket/OpenMarket/Error/MarketError.swift
> +    case unknown
에러가 여러개로 나뉘어 있는데, 에러에 대한 추가적인 정보들이 따로 정의된 것이 없는 것 같아요.
에러에는 어떤 정보들이 포함되면 좋을까요?
JSONDecoder 에서 decode 메서드의 에러같은 것들을 참고해보면 좋을 것 같아요

2021-05-22 03:33 UTC, O-O-wl commented on OpenMarket/OpenMarket/Model/Network/MarketAPI.swift
> +            case .items(let page):
URL의 구조를 참고해보셨을까요?
path가 어느 부분인지 참고해보셔도 좋을 것 같아요
`http://www.example.com:80/path/to/myfile.html?key1=value1&key2=value2#SomewhereInTheDocument`에서 path는 어느 부분일까요?

```swift
URL(string: "http://www.example.com:80/path/to/myfile.html?key1=value1&key2=value2#SomewhereInTheDocument")!.path
```
 를 참고해보셔도 좋을 것 같아요

2021-05-22 03:33 UTC, O-O-wl commented on OpenMarket/OpenMarket/Model/Network/MarketNetwork.swift
> +
파일도 관심사 별로 분리 한번 해볼까요?

2021-05-22 03:33 UTC, O-O-wl commented on OpenMarket/OpenMarket/Model/Network/MarketNetworkManager.swift
> +            case .success(let data):
enum의 정의 순서를 참고해도 좋을 것 같아요 🙇‍♂️

2021-05-22 03:33 UTC, O-O-wl commented on OpenMarket/OpenMarket/Model/Network/MarketNetworkManager.swift
> +    let decoder: DecoderProtocol
이 친구들은 숨겨도 되지 않을까요?

2021-05-22 03:33 UTC, O-O-wl commented on OpenMarket/OpenMarket/Model/Network/MulitPartFormConvert.swift
> +    func createBody(dictionaryData: [String: Any?], _ boundary: String) -> Data
`baseBoundary,  createBody`가 프로토콜의 메서드로 정의된 이유가 혹시 있을까요?

2021-05-22 03:33 UTC, O-O-wl commented on OpenMarket/OpenMarketTests/DecodeTest.swift
> +    var mockDecode: MockDecoder?
이 테스트 케이스에서는 어떤 걸 테스트하고 있는 건가요? MockDecoder를 테스트하는건가요?

2021-05-22 03:33 UTC, O-O-wl commented on OpenMarket/OpenMarketTests/DecodeTest.swift
> +    var mockDecode: MockDecoder?
Mocking한 객체를 테스트하신 이유가 있을까요?

2021-05-22 03:33 UTC, O-O-wl commented on OpenMarket/OpenMarketTests/NetworkTest.swift
> +        let url = MarketAPI.Path.items(page: 1).url
sut는 혹시 어떤 이유로 매 메소드마다 생성하고 있으신가요?
mockDecoders나 mockClient처럼 프로퍼티로 두지 않으신 이유가 있으실까요?

2021-05-22 08:58 UTC, Fezravien commented on OpenMarket/OpenMarket/Error/MarketError.swift
> +    case unknown
추가적인 정보들을 구체적으로 나타내기 위해서 값을 받았어요. 
```swift
case request(Error), response(Int)
case casting(String), network(Error), encoding(Error), decoding(Error)
case url, data, get
```

`JSONDecoder`에서 `decode` 메서드의 에러를 활용하기 위해서 발생한 에러를 받아서 처리하도록 했어요
```swift
do {
    let jsonDecode = try decoder.decode(T.self, from: data)
    completion(.success(jsonDecode))
} catch  {
    completion(.failure(MarketError.decoding(error)))
}
```

`decode` 에러에서 아래와 같이 발생하기 때문에 그 `error` 를 받으면 되지 않을까 싶었어요 
```swift
case dataCorrupted(DecodingError.Context)
case keyNotFound(CodingKey, DecodingError.Context)
case typeMismatch(Any.Type, DecodingError.Context)
case valueNotFound(Any.Type, DecodingError.Context)
```

2021-05-22 09:27 UTC, Fezravien commented on OpenMarket/OpenMarket/Model/Network/MarketAPI.swift
> +            case .items(let page):
`baseURL` : "https://camp-open-market-2.herokuapp.com"
`path`: "/items" or "/item"
`query` : "/page" or "id"

저희가 url 부분을 수정하면서 빼먹었던 것 같아요 😅
Path 열거형을 삭제하고 URL을 만드는 부분으로 수정했어요 

```swift 
var url: URL? {
        switch self {
        case .items(let page):
            return URL(string: MarketAPI.baseURL + "/items" + "\(page)")
        case .registrate:
            return URL(string: MarketAPI.baseURL + "/item")
        case .item(let id):
            return URL(string: MarketAPI.baseURL + "/item" + "\(id)")
        case .edit(let id):
            return URL(string: MarketAPI.baseURL + "/item" + "\(id)")
        case .delete(let id):
            return URL(string: MarketAPI.baseURL + "/item" + "\(id)")
        }
    }
```

2021-05-22 10:02 UTC, Fezravien commented on OpenMarket/OpenMarket/Model/Network/MarketNetwork.swift
> +
<img width="230" alt="스크린샷 2021-05-22 오후 7 01 01" src="https://user-images.githubusercontent.com/44525561/119222575-0f08ee80-bb30-11eb-877b-70f0b70838f8.png">

관심사 별로 파일 구조를 수정해봤습니다 !

2021-05-22 10:09 UTC, Fezravien commented on OpenMarket/OpenMarket/Model/Network/MarketNetworkManager.swift
> +            case .success(let data):
```swift
switch result {
    case .success(let data):
    ...
    case .failure(let error):
    ...
}
```

`Result` enum의 정의 순서를 보니 success, failure 순서였어요
순서 수정했습니다 !!

2021-05-22 10:09 UTC, Fezravien commented on OpenMarket/OpenMarket/Model/Network/MarketNetworkManager.swift
> +    let decoder: DecoderProtocol
🙆‍♂️

2021-05-22 10:15 UTC, Fezravien commented on OpenMarket/OpenMarket/Model/Network/MulitPartFormConvert.swift
> +    func createBody(dictionaryData: [String: Any?], _ boundary: String) -> Data
`request`를 만들어서 반환하는 객체로 만들 수 있지만
`프로토콜`과 `익스텐션`을 이용해 객체를 생성하지 않고 어디서나 `프로토콜 타입`을 이용해서 사용할 수 있어서 더 효율적이라고 생각했어요
- 객체를 생성하지 않아도 된다.
- 타입을 가지고 사용 가능하다

2021-05-22 10:35 UTC, Fezravien commented on OpenMarket/OpenMarketTests/DecodeTest.swift
> +    var mockDecode: MockDecoder?
저희는 `MarketItems` 모델을 테스트 하고 싶었어요. 
`mockDecode` 을 넣는게 아니라 `JSONDecoder`로 테스트 하는 방법을 사용해야 될까요 ?
아니면 이 테스트는 네트워크 테스트에서 하는 것들이라 의미가 없는건가요?

```swift
func test_MarketItems_Decode_성공() {
        XCTAssertNotNil(try? mockDecode!.decode(MarketItems.self, from: mockItems!))
}
    
func test_MarketItems_Decode_실패() {
       XCTAssertNil(try? mockDecode!.decode(StubMarketItems.self, from: mockItems!))
}
```

2021-05-22 10:45 UTC, Fezravien commented on OpenMarket/OpenMarketTests/NetworkTest.swift
> +        let url = MarketAPI.Path.items(page: 1).url
```swift
var sut: MarketNetworkManager?
    
override func setUpWithError() throws {
    sut = MarketNetworkManager(loader: mockClient!, decoder: mockDecode!)
}

override func tearDownWithError() throws {
    sut = nil
}
```

`sut` 도 `mockDecode`, `mockClient` 처럼 프로퍼티로 활용하는게 더 효율적인것 같아요 수정했습니다 !

2021-05-22 10:50 UTC, Fezravien commented
@O-O-wl 

`붱이` 빠른 피드백 감사합니다 👍👍
말씀해주신 수정 사항들 개선해봤어요 ! 

🤔 궁금한 점들은 코멘트에 남겼습니다 !!

2021-05-24 01:13 UTC, O-O-wl commented on OpenMarket/OpenMarketTests/DecodeTest.swift
> +    var mockDecode: MockDecoder?
테스트환경에서만 쓰이는 객체를 테스트한 이유가 있을까 궁금했었어요 ㅎ ㅡㅎ 
Mocking을 하신 의도가 Network의 의존성으 뜯어내기 위함이라고 생각했었거든요

2021-05-24 01:15 UTC, O-O-wl commented on OpenMarket/OpenMarket/Model/Network/MulitPartFormConvert.swift
> +    func createBody(dictionaryData: [String: Any?], _ boundary: String) -> Data
프로토콜에 정의후 구현과 extension에서만 구현하는것도 차이가 있지 않을까 싶어서 질문드려봤어요 ㅎ ㅡㅎ

2021-05-24 01:15 UTC, merged

2021-05-25 14:28 UTC, Fezravien commented on OpenMarket/OpenMarketTests/DecodeTest.swift
> +    var mockDecode: MockDecoder?
저희도 작성하고 `테스트 환경에서만 쓰이는 객체`를 테스트 하는 것에 대해 이상하게 생각했지만, 확신이 서지 않았어요 ㅜ
이 테스트는 필요없는 테스트 인가요 ? 아니면 `mockDecode` -> `JSONDecode`로 하면 모델을 테스트 하는게 될까요?