오픈마켓 [Step 1] Gundy, Wonbi
yagom-academy/ios-open-market pull request #210
Opened 2022-11-17 03:31 UTC by wonbi92

@wonhee009
안녕하세요 라자냐~ 첫 번째 PR을 보내게 되어서 기분이 좋자냐~
여러부분 신경써서 구현하고자 하였습니다!
부족한 부분이나 잘못된 부분이 있다면 가차없는 피드백 부탁드립니다!!
잘 부탁 드립니다!!

## ✓ 진행단계 : Step-1

## 📝 STEP 진행 중 경험하고 배운 것
- JSONParsing
    ☑️ DTO 생성
- Networking 구현
    ☑️ URLSession을 활용한 서버와의 데이터 통신
    ☑️ 각 네트워킹 요소를 프로토콜을 이용하여 추상화
- Test Double 작성
    ☑️ 테스트를 위한 객체 생성
    ☑️ Unit Test 진행

## ⚒️ 코드 구현내용 
<details>
<summary>구현내용</summary>
    
###  구현
- Network
    - HttpMethod 
        - HttpMethod를 나타내는 열거형 타입입니다.
    - NetworkRequest
        - 네트워킹을 위한 URL과 Request를 가지고 이를 구현하기 위한 필수 프로퍼티를 선언하는 프로토콜입니다.
    - NetworkManager
        - 네트워크에서 데이터를 가져와 오류를 처리하고 데이터를 파싱해주는 객체입니다.
    - URLSessionProtocol
        - DIP적용을 위해 `dataTask`메서드를 정의하는 프로토콜입니다.
        - 이 프로토콜을 채택하면 `dataTask`메서드의 로직을 구현해주어야 합니다.
    - URLSessionDataTaskProtocol
        - `URLSessionProtocol`의 `dataTask`메서드에서 반환하는 타입을 지정하는 프로토콜입니다.
        - 이 프로토콜을 채택하면 `resume`메서드의 로직을 구현해주어야 합니다.
- Extension
    - JSONDecoder
        - 제네릭 타입과 데이터를 받아 디코딩하는 타입 메서드를 추가하였습니다.
    - String
        - `"yyyy-MM-dd'T'HH:mm:ss"`의 형식의 문자열을 `Date`타입의 값으로 변경시켜주는 메서드를 추가하였습니다.
- OpenMarket
    - Product
        - `Codable`을 채택하는 DTO입니다.
    - ProductList
        - `Codable`을 채택하는 DTO입니다.
    - HealthCheckerRequest
        - NetworkRequest를 채택하고, Application HealthChekcer를 리퀘스트하기위한 프로퍼티를 갖고 있는 구조체입니다.
    - ProductListRequest
        - NetworkRequest를 채택하고, 상품 리스트 조회를 리퀘스트하기위한 프로퍼티를 갖고 있는 구조체입니다.
    - ProductDetailRequest
        - NetworkRequest를 채택하고, 상품 상세 조회를 리퀘스트하기위한 프로퍼티를 갖고 있는 구조체입니다.
- OpenMarketTests
    - products
        - 테스트를 위한 Mock JSON데이터입니다.
    - DataLoader
        - Mock JSON데이터를 코드로 연결시켜 data를 생성해주는 클래스입니다.
    - DummyData
        - 실제 네트워킹이 아닌 테스트를 진행할 때 반환할 데이터 구조체입니다.
    - MockURLSession
        - 테스트를 위해 실제 네트워킹이 아니라 `DummyData`를 사용하는 클래스입니다.
    - MockURLSessionDataTask
        - 테스트를 위해 실제 네트워킹 테스트가 아닌 `DummyData`를 반환하는 클래스 입니다.
    
### Unit Test 작성
- JSONDecoder, DTO
    - JSONParsingTests
- NetworkManager
    - NetworkManagerTests
- OpenMarketNetworkRequest
    - NetworkRequestTests
    
</details>

## 💭 고민한 부분

### 테스트용 JSON 파일과 서버 API 문서
- 이번 프로젝트 안내페이지에서 제공하는 테스트용 JSON 파일과 앞으로 작업을 진행할 API의 JSON이 서로 CodingKey나 value의 형식이 달랐습니다. 
- 우선 테스트용 파일에 맞게 DTO를 구현했었는데, 실제 API Network를 진행해보면서 서로 다르다는 것을 알게 되었습니다. 
- 테스트의 취지가 네트워크가 없는 상황에서도 정상적으로 동작하는지를 검증하는 것이기 때문에 서버 API 문서의 데이터 형식에 맞추는 것이 적절하다고 생각해 테스트용 JSON 파일을 서버 API 문서의 데이터 형식에 맞게 수정하였습니다. 

### DIP적용을 위한 Protocol 구현하기
- 실제로 네트워킹을 하지 않고, 정상적으로 fetch가 진행되는지 로직을 테스트 하기위해 `MockURLSession`이라는 test double객체를 만들고 `MockData` 객체를 반환하도록 로직을 구현해야 했습니다.
- 이 과정에서 URLSession의 dataTask메서드에서 네트워킹 하는 부분을가로채 실제 네트워킹이 아니라 미리 만들어둔 `MockData` 객체를 반환하게 구현하여야 했습니다.
- 실제 `URLSession`과 이런 `MockURLSession`은 다르게 작동해야 하므로, 프로토콜을 통해 의존성을 역전시켜 네트워크 매니저가 프로토콜을 바라보게 하여 테스트를 할 때는 `MockURLSession`을 주입시키고, 실제 네트워킹을 할 때는 `URLSession`을 주입시키는 방법으로 진행해 보았습니다.
- 이 때 `URLSessionDataTask`타입도 Mock데이터로 만들어 주었는데, 이 타입의 초기화 구문이 iOS13버전 부터 더 이상 사용되지 않는(deprecated) 로직이어서 이 타입도 프로토콜을 채택하게 하여 구현 해 보았습니다.

## ❓ 조언을 얻고 싶은 부분
### 재사용이 가능한 Request객체 구현하기
- 이번 프로젝트에서 네트워킹의 요소가 총 3가지 였습니다.
- 그리고 실제 오픈마켓 서버에서도 GET메서드 말고도 POST, PATCH, DEL 등의 httpMethod를 사용할 수 있었습니다.
- 이에 각각의 리퀘스트마다 URL주소가 달라졌었고, 이를 String으로 써주는건 코드의 재사용이 많고, 확장성에도 문제가 있어보인다 판단하였습니다.
- 그래서 `NetworkRequest` 프로토콜을 만들고, 각 네트워킹 요소를 객체화하여 이를 채택하도록 하였습니다.
- 이로써 URL을 String으로 직접 작성할 필요가 없이 프로토콜을 채택하고 그 프로토콜을 각자의 역할에 맞게 구현만 해주면 알아서 URL과 Request를 만들게 되었습니다.
- 혹시 저희가 구현한 `NetworkRequest`에서 부족한 부분이나 잘못된 부분, 혹은 개선할 부분이 있을까요??

### 각 파일의 위치가 적절한지
- 테스트를 위한 JSON 파일은 `OpenMarketTests` 내부에 위치시켰고, 범용적으로 네트워크에 사용할 수 있는 프로토콜이나 타입은 `OpenMarket` 외부에 `Network`라는 그룹을 따로 생성하여 관리하였습니다. Network 기능을 수행하지만 그 용도가 OpenMarket 프로젝트에만 사용될 `OpenMarketNetworkRequest` 등은 `OpenMarket` 내부에 위치시켰습니다.
- 저희가 네트워크 통신 작업이 처음이다보니, 이런 방식으로 파일을 정리하는 것이 적절한지 조언을 얻고 싶습니다.

### BoringSSL에 대하여
- Step 1-2를 진행하면서 서버와 실제로 데이터를 주고 받을 때, `boringssl_metrics_log_metric_block_invoke(153)` 라는 메시지가 콘솔에 뜨게 되었습니다. 
- [boringssl_metrics_log_metric_block_invoke(151) Failed to log metrics](https://github.com/firebase/firebase-ios-sdk/issues/9262)의 내용 및 여러 게시글들을 찾아본 결과 기능에는 문제가 없고, 콘솔에 나타나기만 하는 메시지로 파악했습니다. 
- 스키마에서 OS_ACTIVITY_MODE를 disable로 바꿔주면 이 에러 메세지가 콘솔에서 나타나지 않지만, `NSLog`도 사라지는 문제가 있어서 이 방법은 적절한 방법이 아니라 판단하였습니다.
- 또 다른 방법으로는 `xcrun simctl spawn booted log config --subsystem com.apple.network --category boringssl --mode level:off` 처럼 Xcode 설정을 건드리는 방법도 있었는데, 이는 Xcode의 설정을 건드리는 것이고, 어떤 사이드 이펙트가 발생할지 몰라, 적용하기에 적절하지 않다 판단하여 적용하지 않았습니다.
- 혹시 이 메시지를 신경쓰지 않고 작업을 이어나가도 괜찮은지 여쭙고 싶습니다!

2022-11-18 13:16 UTC, wonhee009 requested changes
수고하셨습니다:)
코멘트 남겨두었으니 확인 부탁드려요!

- 폴더링은 팀마다도 룰이 다르고 개인 취향도 있어서 뭐가 맞다고 말씀 드릴 순 없을거 같습니다.
그래도 각자의 역할에 맞게 분리되면 될거 같습니다.
- 넵 그냥 이어나가면 될거 같습니다.

2022-11-18 13:16 UTC, wonhee009 commented on OpenMarket/Network/HttpMethod.swift
> +    case delete
해당 메서드를 모두 사용하나요?

2022-11-18 13:16 UTC, wonhee009 commented on OpenMarket/OpenMarketTests/MockData/DataLoader.swift
> +final class DataLoader {
static func만 갖고 있는 클래스로 보이는데요.
클래스로 정의한 이유가 있을까요?

2022-11-18 13:16 UTC, wonhee009 commented on OpenMarket/OpenMarket/Network/OpenMarketNetworkRequest.swift
> +        self.queryParameters["items_per_page"] = String(itemsPerPage)
```suggestion
    var queryParameters: [String : String]
    
    init(pageNo: Int, itemsPerPage: Int, searchValue: String = "") {
        queryParameters[
           "page_no": String(pageNo),
           "items_per_page": String(itemsPerPage)
```
이렇게도 가능할거 같습니다.

2022-11-18 13:16 UTC, wonhee009 commented on OpenMarket/OpenMarket/Network/DTO/ProductList.swift
> +struct ProductList: Codable {
Model을 정의한 파일들이 DTO라는 폴더 안에 위치한거로 보이는데요.
DTO보다는 Model이라는 폴더명은 어떤가요?

2022-11-18 13:16 UTC, wonhee009 commented on OpenMarket/OpenMarket/ViewController.swift
> +                print(error)
테스트 해보기 위한 코드일까요?
현재 스텝 요구사항에는 없는 부분인거 같아 질문드립니다.

2022-11-18 13:16 UTC, wonhee009 commented on OpenMarket/Network/NetworkRequest.swift
> +    }
해당 프로퍼티는 외부에서 접근할 일이 있나요?

2022-11-18 13:16 UTC, wonhee009 commented on OpenMarket/Extension/String+.swift
> +    }
모든 String 타입에서 해당 프로퍼티에 접근가능할거 같은데요.
해당 프로퍼티는 한정된 곳에서만 사용될거 같은데 어떻게 생각하시나요?

2022-11-18 13:16 UTC, wonhee009 commented on OpenMarket/Extension/String+.swift
> +    }
해당 메서드도 동일하게 모든 String 타입에서 접근가능할거 같은데요.
모든 String 타입에서 접근 가능한 방식 말고 DateConverter(예시) 같은 하나의 class/struct를 추가하는건 어떤가요?

2022-11-18 13:16 UTC, wonhee009 commented on OpenMarket/Extension/JSONDecoder+.swift
> +            print("data found to be corrupted in JSON: \(context.debugDescription)")
catch 문에서 다른 부분이 출력 메시지가 다른거로 보이는데요.
[localizedError](https://developer.apple.com/documentation/foundation/localizederror)의 errorDescription을 이용해 보는건 어떤가요?

2022-11-21 01:13 UTC, wonbi92 commented on OpenMarket/Network/HttpMethod.swift
> +    case delete
step1에서는 get만 사용을 하긴 하지만, 이후 스탭에서 post, patch, delete등의 다른 메서드를 사용하기도 하고, httpMethod의 종류를 공부해보자는 의미로 주요한 메서드들은 구현해보자 라고 결론을 내려서 5개의 주요한 메서드 케이스를 모두 작성해 보았습니다!

2022-11-21 01:18 UTC, wonbi92 commented on OpenMarket/OpenMarketTests/MockData/DataLoader.swift
> +final class DataLoader {
DataLoader는 로컬에 있는 데이터를 Data타입으로 로드시켜주는 객체입니다. 로컬에 있는 파일의 URL을 만들어주는 메서드 안에 Bundle(for:)메서드에서 매개변수로 self를 넣어주는데, 이 과정에서 매개변수 타입이 클래스만 가능한 AnyClass이기 때문에 class로 정의하게 되었습니다.

2022-11-21 01:23 UTC, wonbi92 commented on OpenMarket/OpenMarket/Network/OpenMarketNetworkRequest.swift
> +        self.queryParameters["items_per_page"] = String(itemsPerPage)
오 이렇게도 가능할 것 같습니다! 조언주신 방법으로 수정 해보았습니다!

2022-11-21 01:30 UTC, wonbi92 commented on OpenMarket/OpenMarket/Network/DTO/ProductList.swift
> +struct ProductList: Codable {
코맨트 주신 부분을 토대로 Gundy와 상의해본 결과, Model로 바꾸는것이 코드를 이해하는 데 더 나은 방법이라는 결론이 나왔습니다. 폴더명을 Model로 변경하였습니다!

2022-11-21 01:44 UTC, Gundy93 commented on OpenMarket/OpenMarket/ViewController.swift
> +                print(error)
네트워킹에 대한 테스트 코드가 맞습니다! 현재는 지웠습니다!

2022-11-21 01:53 UTC, Gundy93 commented on OpenMarket/Network/NetworkRequest.swift
> +    }
URL을 매개변수로 fetchData를 구현했기 때문에 테스트 과정에서 url이라는 프로퍼티에 접근하여 사용했습니다. 해당 프로퍼티를 private 처리하고, URLRequest 객체에서 url 프로퍼티에 접근하는 방식으로 로직을 수정하였습니다.

2022-11-21 02:13 UTC, Gundy93 commented on OpenMarket/Extension/String+.swift
> +    }
String Extension을 삭제하고, 이후 `price` 및 다른 가격에 대해서도 numberFormatter를 사용하게 될 것 같아 FormatConverter라는 구조체를 구현하였습니다.

2022-11-21 02:20 UTC, Gundy93 commented on OpenMarket/Extension/String+.swift
> +    }
아래 내용과 연결되는 부분 같아서 아래에 더 자세히 적었습니다! 해당 부분을 String Extension에서 제거하였습니다.

2022-11-21 02:55 UTC, wonbi92 commented on OpenMarket/Extension/JSONDecoder+.swift
> +            print("data found to be corrupted in JSON: \(context.debugDescription)")
코맨트 주신 부분을 정확하게 이해하지 못했지만, error의 localizedDescription 프로퍼티를 활용하게 바꿔보았습니다.
```Swift
extension DecodingError {
    public var errorDescription: String {
        switch self {
        case .typeMismatch(let type, let context):
            return "type mismatch for type \(type) in JSON: \(context.debugDescription)"
        case .valueNotFound(let type, let context):
            return "could not find type \(type) in JSON: \(context.debugDescription)"
        case .keyNotFound(let key, let context):
            return "could not find key \(key) in JSON: \(context.debugDescription)"
        case .dataCorrupted(let context):
            return "data found to be corrupted in JSON: \(context.debugDescription)"
        @unknown default:
            return localizedDescription
        }
    }
}

do {
    decodedData = try decoder.decode(type, from: data)
} catch let error as DecodingError {
    print(error.errorDescription)
} catch {
    print(error.localizedDescription)
}
```
혹시 라자냐가 코맨트 주신 부분의 방향성이 위 코드와 같은 걸까요? 저희가 올바르게 이해했는지 잘 모르겠습니다 ㅠㅠ

2022-11-21 03:05 UTC, wonhee009 commented on OpenMarket/Network/HttpMethod.swift
> +    case delete
post, patch, delete에 대해서는 이후 스텝에서 필요한 사항이라 구현했다고 이해했습니다.
그럼 put은 제외하는건 어떨까요?
"httpMethod의 종류를 공부해보자는 의미로 주요한 메서드들은 구현해보자" 이 부분은 `case put`과는 관계 없다고 생각 듭니다.
이렇게 모든 httpMethod가 열려 있으면 이후 다른 개발자가 봤을때 put에 대한 API 구현이 있다 생각할 수 있을거 같고, 이런 부분들이 이후 에러를 발생시킬 수 있을거 같습니다.
이 부분은 이후 스텝에서 확인해주셔도 좋습니다:)

2022-11-21 03:07 UTC, wonhee009 commented on OpenMarket/Extension/JSONDecoder+.swift
> +            print("data found to be corrupted in JSON: \(context.debugDescription)")
LocalizedError를 확인해보면 프로토콜인데요.
```swift
enum DecodingError: LocalizedError {
}
```

2022-11-21 06:35 UTC, Gundy93 commented on OpenMarket/Extension/JSONDecoder+.swift
> +            print("data found to be corrupted in JSON: \(context.debugDescription)")
이미 `DecodingError`는 LocalizedError 프로토콜을 채택한 에러인데, `errorDescription`은 nil을 반환하더라고요! extension을 통해 nil이 아닌 적절한 String을 반환하게끔 만들어본거였습니다. 😃

2022-11-21 08:24 UTC, wonhee009 approved these changes
수고하셨습니다 :)

2022-11-21 08:25 UTC, merged