오픈마켓 [STEP 1] inho, Hamo, Jeremy
yagom-academy/ios-open-market pull request #211
Opened 2022-11-17 04:33 UTC by lxodud

@GREENOVER 
안녕하세요 그린!
Step1 PR드립니다.
잘부탁드립니다 🙇🏼‍♂️🙇🏼‍♂️🙇‍♂️

## 📝 STEP 진행 중 경험하고 배운 것

- 파싱한 JSON 데이터와 매핑할 모델 설계
     ☑️ 서버 API문서와 일치할 데이터 타입을 구현했습니다.
- URL Session을 활용한 서버와의 통신
     ☑️ `URL Session`과 `data task`를 이용하여 데이터를 받아옵니다.
     ☑️ Completion handler 응용
     ☑️ escaping closure 동작 이해

- Test Double 적용
     ☑️ `Dummy`데이터와 `Stub`을 구현해서 네트워크와 무관하게 동작하는 테스트를 수행합니다. 

## ⚒️ 코드 구현내용 
### 1️⃣ API문서에서 받아올 DTO 모델타입 구현
- 상품리스트와 상품상세 정보에 필요한 타입들을 구현했습니다.
    - `ProductListData`, `ProductData`, `VendorData`, `ImageData`
    - JSON을 디코딩해 받는 데이터라는걸 명시하기 위해 각 타입 뒤에는 `Data`를 명시해주었습니다.

### 2️⃣ 서버에서 데이터를 가져올 `NetworkManager`타입 구현
- 받아올 요청에 대한 정보(url과 디코딩 타입)를 매개변수로받아 해당하는 정보를 서버에서 받아옵니다.
- 기본적으로는 `shared`세션의 `dataTask(with: url)`을 이용하여 전달한 `url`의 정보를 받아오는 메서드를 사용합니다.
    - `loadData<T>(of:dataType:completion)`

### 3️⃣ Test Double을 위한 `Dummy`와 `Stub`구현
- 네트워킹으로 받아올 대신 직접 구현한 `DummyData`를 `completionHandler`에 전달합니다.
- 기존의 `URLSession`과 `DataTask`대신 가짜 객체인 `StubURLSession`과 `StubURLSessionDataTask`를 사용합니다.

## 💭 고민한 부분

### 로컬의 JSON (테스트할때 사용할)키 값과 API문서 상의 키 값이 다른 문제
|<img src="https://i.imgur.com/4Kl6HGR.png" width="300px"/> | <img src="https://i.imgur.com/cpGzC9E.png" width=500px/>|
|:-:|:-:|
|`API문서의 키 값`|`로컬 JSON파일의 키값`|

서버(pageNo)와 JSON(page_no)의 현재 페이지 번호의 key값이 일치하지 않는 문제점이 있었습니다. 
코딩키를 `pageNO`로 작성하면 `JSON`파일을 디코딩할 수 없었습니다.
이를 해결하기 위해 서버의 키와 JSON키 모두 `camelCase`로 변환하는 프로퍼티를 사용했습니다.

```swift
let decoder = JSONDecoder()
decoder.keyDecodingStrategy = .convertFromSnakeCase                 
```
해당 프로퍼티를 사용함으로써 아래와 같이 들어오는 `vendor_id` 키 값을 카멜케이스로 변환하여 원하는 케이스 네임으로 수정할 수 있었습니다.
|||
|--|--|
|API문서의 키|![](https://i.imgur.com/gFcg0AL.png)|
|코드로 구현한 키|`case vendorIdentifier = "vendorId"`|

### 같은 상품 상세에 대해서 요구하는 키값이 서로 다른 문제
- 서버에 상품 리스트 조회, 상품 상세 조회 두 가지 요청을 보낼 때 받아오는 JSON파일의 키가 일치하지 않아서 ProductData DTO를 중복으로 사용하였을 때 디코딩이 되지 않는 문제가 있었습니다.
- `ProductList`에서는 `Product`의 `description`과 `vendorName`을 요구하고,
`Product`상세에서는 `images`와 `vendors`를 요구하는 부분을 어떻게 해결할지 고민후에 겹치지 않는 키에 해당하는 프로퍼티를 옵셔널 처리하여 해결하였습니다.
```swift
struct ProductData: Decodable {    
    ...
    let vendorName: String?
    let description: String?
    let images: [ImageData]?
    let vendors: VendorData?
}
```

### 비동기로 동작하는 `dataTask`가 끝난 시점에 데이터를 받는 방법
- `NetworkManager`의 `loadData`메서드 내부에서 호출하는 `dataTask` 메서드는 파라미터인 `completionHandler`를 이용하여 `data, response, error`를 받을 수 있는데 비동기적으로 동작하기 때문에 끝나는 시점을 알수없어서 받아온 데이터를 어떻게 전달할지 고민이었습니다.
- `loadData의` 파라미터로 `escaping closure`를 받아서 `dataTask`의 `completionHandler`가 해당 클로저를 캡처하여 비동기적으로 작업이 끝난 시점에 캡처한 클로저를 호출하는 방법으로 해결하였습니다.

### `Test Double`에서의 코드 흐름과 테스트를 위해 구현한 타입들
- 네트워크가 없는 환경에서도 테스트를 수행하기 위해서 네트워킹을 수행하는 `URLSession`과 `URLSessionDataTask`대신하는 `Stub`객체를 구현했습니다. 그래서 `DummyData`를 만들어놓고 이를 `dataTask`의 `completionHandler`까지 전달합니다.

    ```swift
    //테스트 코드 예시
    func test_productListData를받았을때_전달받은값을_리턴해야한다() {
        //given
        guard let url = NetworkRequest.productList.url else { return }

        let expectedData = """
                        {
                            ...
                            "totalCount": 116,
                            ...
                            
                            """.data(using: .utf8)
        let response = HTTPURLResponse(url: url,
                                       statusCode: 200,
                                       ...)
        let dummyData = DummyData(data: expectedData,
                                  response: response,
                                  error: nil)
        stubUrlSession.dummyData = dummyData

        //when
        sut.loadData(of: NetworkRequest.productList,
                        dataType: ProductListData.self) { result in
            switch result {
            case .success(let productListData):
            //then
                XCTAssertEqual(productListData.totalCount, 116)
            case .failure(let error):
                XCTFail("loadData failure: \(error)")
            }
        }
    }
    ```
    - 위 예시에서, 받아올 것이라고 예상되는 데이터를 작성하고, 응답이 성공한다고 가정해서 성공하는`response`를 작성하였습니다. 이 정보들을 `dummyData`에 포함하여 가짜 객체인 `stubUrlSession`에 전달하고, `NetworkManager`의 `loadData`메서드를 호출해서 의도한 결과와 일치하는지 확인합니다.

2022-11-17 08:10 UTC, GREENOVER requested changes
@inho-98 @lxodud @yjjem 
세분 모두 잘 구현해주시느라 고생 많으셨습니다!
전체적으로 스텝 일감별로 요청사항들을 잘 구현하였고 코드 관심사 분리가 잘되있어서 리뷰하기 편했어요👍
***
### 칭찬 드리고 싶은 부분
- 모델 타입 설계를 잘 이해하시고 공통적인 부분은 잘 묶어주신것 같아요 💯
- 커밋 이력 관리가 잘되어서 원하는 부분 파악에 도움이 아주 많이 되었어요 💯
- 발생할 수 있는 네트워크 에러 케이스들을 잘 다뤄주신점 💯
- 최대한 중복 부분없이 깔끔한 코드를 지향하신점 💯
***
### 보완되면 좋을 부분
전체적으로 너무 잘해주셔서 크게 보완할 부분은 없지만 몇가지 코멘트로 남겨 놓은 부분이 있습니다..!
그 중 가장큰 대표적으로 하나는 URL 파라미터로 매개변수 값을 주입하여 네트워킹을 호출해야될것 같아요.
요 부분의 수정만 되면 큰건 없어 보입니다!
***
다시 한번 고생 많으셨어요👍
수정 후 재리뷰 요청을 해주시면 빠르게 확인하도록 하겠습니다😄

2022-11-17 08:10 UTC, GREENOVER commented on OpenMarket/OpenMarket.xcodeproj/project.pbxproj
>  		C70FB0FD25BEF61C00C9924E /* SceneDelegate.swift in Sources */ = {isa = PBXBuildFile; fileRef = C70FB0FC25BEF61C00C9924E /* SceneDelegate.swift */; };
이런 파일들도 그룹화로 관리해보면 어떨까요~?🙋🏻

2022-11-17 08:10 UTC, GREENOVER commented on OpenMarket/OpenMarket.xcodeproj/project.pbxproj
> +			sourceTree = "<group>";
Network 그룹이 Model 내부에 속한 이유가 궁금합니다🙋🏻

2022-11-17 08:10 UTC, GREENOVER commented on OpenMarket/OpenMarket/Model/Network/NetworkRequest.swift
> +    case product
해당 케이스들에서 파라미터로 pageNo및 per Page 값을 주입받아 아래 url 프로퍼티에서 사용하는게 더 적절하다고 보입니다🙋🏻
현재 구조라면 페이지넘버와 특정 상품에 대해 선택적이 아닌 항상 같은 값을 요청할것 같아요.

2022-11-17 08:10 UTC, GREENOVER commented on OpenMarket/OpenMarketTests/ProductListDataTest.swift
> +        jsonDecoder.keyDecodingStrategy = .convertFromSnakeCase
디코딩 전략 아주 잘 사용하셨네요👍

2022-11-17 08:10 UTC, GREENOVER commented on OpenMarket/OpenMarket/Model/Network/URLSessionProtocol.swift
> +extension URLSession: URLSessionProtocol { }
컴파일 및 빌드에는 이상이 없지만 warning을 발생시키지는 않으셨을까요~?🤔

2022-11-17 08:10 UTC, GREENOVER commented on OpenMarket/OpenMarketTests/StubURLSessionTest.swift
> +    var stubUrlSession: StubURLSession!
테스트 코드긴 하지만 강제 언래핑은 지향해보면 어떨까요?
추후 Lint 기본룰을 도입하거나 할때도 해당 Test Code를 예외로 처리하지 않으면 경고를 발생할것이고 강제 언래핑은 항상 예기치 못한 이슈를 발생시키기에 더 좋은 방법이 있을것 같습니다🙋🏻

2022-11-17 08:10 UTC, GREENOVER commented on OpenMarket/OpenMarket/Model/ImageData.swift
> +struct ImageData: Decodable {
인코딩, 디코딩만 하는 용도라면 모델을 Enum 타입으로 만드는 방법도 있는데 어떤 차이가 있을까요?

2022-11-17 08:10 UTC, GREENOVER commented on OpenMarket/OpenMarket/Model/Network/NetworkRequest.swift
> +            return URL(string: "https://openmarket.yagom-academy.kr/healthChecker")
옵셔널하지만 search_value의 값을 넣어줘야할때도 있을것 같은데 어떻게 생각하시나요?🙋🏻

2022-11-17 08:10 UTC, GREENOVER commented on OpenMarket/OpenMarket/Model/Network/URLSessionProtocol.swift
> +    func dataTask(with request: URL, completionHandler: @escaping DataTaskCompletionHandler) -> URLSessionDataTask
파라미터가 많아지고 네이밍이 길어지면 파라미터 인자들 사이 적절한 개행을 해주면 더 코드가 깔끔해질것 같습니다🙋🏻

2022-11-17 08:10 UTC, GREENOVER commented on OpenMarket/OpenMarket/Model/OpenMarketError.swift
> +}
네트워킹에 관한 에러들 같은데 추후 오픈마켓을 진행하며 여기 뷰와 네트워크 로직들의 에러들이 한번에 다 들어오면 가독이 조금 우려되는데, 네이밍을 조금 더 구체적으로 가져가면서 분리해보면 어떨까요?🙋🏻

2022-11-18 14:42 UTC, lxodud commented on OpenMarket/OpenMarket.xcodeproj/project.pbxproj
>  		C70FB0FD25BEF61C00C9924E /* SceneDelegate.swift in Sources */ = {isa = PBXBuildFile; fileRef = C70FB0FC25BEF61C00C9924E /* SceneDelegate.swift */; };
Controller의 역할이라 판단하여 Controller 폴더내부에 포함시켰습니다!!
> https://github.com/yagom-academy/ios-open-market/pull/211/commits/4c3a35ac9ca1f258ade39b94cbb2c0c735244f17

2022-11-18 14:53 UTC, lxodud commented on OpenMarket/OpenMarket.xcodeproj/project.pbxproj
> +			sourceTree = "<group>";
`Model`은 특정한 데이터를 캡슐화 하고 해당 데이터를 조작, 처리하는 논리와 계산을 정의하는 역할인데
구현한 네트워크 그룹에서 앱에 필요한 데이터를 가져오고 처리하기 때문에 `Model`에 속한다고 생각했습니다!!

2022-11-18 14:57 UTC, lxodud commented on OpenMarket/OpenMarket/Model/Network/NetworkRequest.swift
> +    case product
`enum`의 연관 값을 이용하여 `path`와 `query`를 받아 `URL`을 구성하고 `url` 연산 프로퍼티 `case` 바디에 중복되는 로직을 메서드로 분리하였습니다.
bb5b514

2022-11-18 14:59 UTC, lxodud commented on OpenMarket/OpenMarketTests/StubURLSessionTest.swift
> +    var stubUrlSession: StubURLSession!
강제 언래핑 대신 옵셔널을 적용하고 옵셔널 바인딩과 체이닝을 이용하였습니다!
cbef89c

2022-11-18 15:28 UTC, lxodud commented on OpenMarket/OpenMarket/Model/ImageData.swift
> +struct ImageData: Decodable {
`Enum`으로 모델을 만드는 것을 생각해보지 못해서 공부해보았습니다.
`Enum`에 `rawValue`, `associatedValue`의 여부에 따라서 인코딩, 디코딩되는 방식이 다르게 나타났습니다. 
`rawValue`와 `String`을 이용하면 열거형의 케이스를 `JSON``key`의 `value`로 사용할 수 있고,
`associatedValue`를 사용하면 한번 더 그룹화하여 연관값의 레이블과 값을 `JSON`의 `key`, `value`로 변환된다고 이해했습니다.

열거형을 이용하면 인코딩 시 구조체와 달리 인스턴스를 만들지 않아도 되지만, 정해진 케이스대로만 변환되고, 케이스가 많은 경우에 일일이 작성해야 한다는 문제점을 파악했습니다.
그래서 저희 모델에는 적용하기 어렵다고 생각하여 구조체를 사용했습니다!

2022-11-18 15:31 UTC, lxodud commented on OpenMarket/OpenMarket/Model/Network/NetworkRequest.swift
> +            return URL(string: "https://openmarket.yagom-academy.kr/healthChecker")
넣을 수 있어야 한다고 생각되네요 👍👍👍
연관값에 옵셔널로 적용하여 필요할 때 넣을 수 있게 하였습니다.
5ea0d18

2022-11-18 15:32 UTC, lxodud commented on OpenMarket/OpenMarket/Model/Network/URLSessionProtocol.swift
> +    func dataTask(with request: URL, completionHandler: @escaping DataTaskCompletionHandler) -> URLSessionDataTask
개행 추가했습니다 👍👍👍

2022-11-18 15:35 UTC, lxodud commented on OpenMarket/OpenMarket/Model/OpenMarketError.swift
> +}
추후에 `View`에 대한 코드가 추가되면 에러 케이스가 누적될 것이라고 생각됩니다 😀😀😀
`NetworkError`라는 구체적인 네이밍으로 분리 완료했습니다!!
4c3a35a

2022-11-18 15:58 UTC, lxodud commented on OpenMarket/OpenMarket/Model/Network/URLSessionProtocol.swift
> +extension URLSession: URLSessionProtocol { }
인호와 하모의 `xcode` 버전에서는 아무런 `warning`이 발생하지 않고 14.0을 사용하는 제레미의 `xcode`에서는 `warning`이 발생하여서 찾아보니 `dataTask` 메서드의 `definition`에 `@Sendable`이 명시되어 있는 것을 알게되었습니다.
그래서`@Sendable`을 찾아보니, 클로저가 값을 캡쳐할때 참조 캡처를 하지 않고 값 캡처만 할 수 있도록 하여 동시성 작업을 안정적으로 수행한다고 이해했습니다!

2022-11-20 08:21 UTC, GREENOVER approved these changes
@inho-98 @lxodud @yjjem 
고생 많으셨습니다!
전체적으로 리팩토링이 잘되었네요👍
이번 스텝은 여기서 어프로브 및 머지하겠습니다ㅎㅎ
다음 스텝도 화이팅입니다!
아..! 혹시 리뷰 재요청을 해주실때는 PR에서 우측 상단 아래와 같은 리뷰어 탭에서 갱신 버튼을 눌러 주시면 제가 더 빠르게 캐치할 수 있습니다🙌
![스크린샷 2022-11-20 오후 5 14 40](https://user-images.githubusercontent.com/72292617/202892490-0e7c27ee-b193-457f-86a0-be3cc21a7528.png)

2022-11-20 08:21 UTC, merged