오픈마켓 [STEP 1] Kyo, LJ
yagom-academy/ios-open-market pull request #212
Opened 2022-11-17 04:39 UTC by KyoPak

@Monsteel
안녕하세요 토니! 쥬스메이커때 이후로 또 보게되서 반갑습니다~~!
Kyo(@KyoPak)와 LJ(@lj-7-77)가 Step1의 구현 후 PR 작성해보았습니다! 
가장 처음 네트워크 관련된 메서드들을 구현할 때는 조금만 어려웠지만..
Mock을 적용하고 난 후에는 네트워크 관련 공부가 더필요하다고 느껴졌습니다..
아직 조금 더 고민해보고 공부를 한 후에 추가적인 질문을 드려야할 것 같습니다!
코드 보시고 저희가 잘모르고 있는 듯한 낌새가 보이시면 공격해주시면 감사하겠습니다 !! 
토니의 좋은 + 많은 코멘트 부탁드립니다 :)

## ✓ 진행단계 : Step-1

## 📝 STEP 진행 중 경험하고 배운 것

☑️파싱한 JSON 데이터와 매핑할 모델 설계
☑️ResultType을 적용한 에러처리
☑️URL Session을 활용한 서버와의 통신
☑️CodingKeys 프로토콜의 활용
☑️Json파일과 서버 데이터 모두 적용하기 위한 keyDecodingStrategy 사용
☑️단위 테스트(Unit Test)를 통한 설계의 검증
☑️Test Double(Mock)을 이용한 네트워크 테스트
☑️Mock Test를 위한 Network 추상화

    
## ⚒️ 코드 구현내용 

### `NetworkRequest`, `NetworkManager`, `URLSessionProtocol`, `URLSessionDataTaskProtocol`, `MockURLSession`

<details>
<summary>Details</summary>
<div markdown="1">
    
- NetworkRequest
    - 필요한 작업case별로 `requestURL`이라는 URL타입으로 바꿔주는 타입입니다. 
- NetworkManager
    - 네트워크에 관련된 작업을 담당하는 클래스입니다.
    - 가장 처음에는 싱글톤 패턴을 구현하였었습니다. 하지만 step1-3에서 Moct Test 구현을 위해 초기화하는 방식을 바꿨습니다.
    - `checkHealth()`는 서버에 요청이 잘 되었다는 응답값을 받기위한 요청메서드입니다.
        - 초기에는 escaping 클로저를 사용하지 않았지만, Test 진행시 responseStatusCode 값을 가져오기 위해 escaping 클로저를 사용하였습니다.
    - `fetchData()`는 서버에 데이터를 요청하는 메서드입니다.
        - productList와 productDetail 데이터를 가져오는 메서드이며 이 두가지의 요청은 각각 Decode하는 방식이 다르기 때문에 옵셔널을 사용하였습니다.
        - 그리고 추후에 받아온 데이터를 사용하기 위해 escaping 클로저를 사용하였습니다.
- URLSessionProtocol
    - MockURLSession과 URLSession을 상황에 맞게끔 NetworkManager에서 사용되게끔 만든 프로토콜입니다.
    - 내부에서 필수적으로 구현해야할 `dataTask()`메서드를 새롭게 정의하였습니다.
- URLSession Extension
    - `URLSessionProtocol`을 채택한 후, 내부에서 프로토콜에서 정의한 메서드를 구현해주었습니다. Mock이 아닌 실제 사용될 `URLSession`이기 때문에 프로토콜에서 정의한 메서드의 반환값을 실제 `dataTask()`메서드를 호출하는 방식으로 구현하였습니다.
- MockURLSession
    - dataTask
        - `MockURLSession`이 실행할 `dataTask()`메서드입니다.
        - 실제 네트워크에 요청을 하는 것이 아니기 때문에 곧바로 `return`이 되게끔 하였습니다.
    - makeMockSenderSession
        - 이 타입 메서드는 `MockURLSession`의 Mock응답을 만드는 메서드입니다. 실제 네트워크에 요청을 해서 응답값을 받아오는 목적이 아니기 때문에 이 메서드를 통해 Mock응답을 만들었습니다.
</div>
</details>

## ❓ 고민 및 조언을 얻고 싶은 부분

- step 1-1 에서는 CodingKey 프로토콜을 채택하여 구현하였으나 step 1-2에서 제이슨파일과 서버에서의 파일 모두 받아들일 수 있도록 멀티 코딩키를 사용하려했습니다. 
`keyDecodingStrategy` 프로퍼티를 `convertFromSnakeCase`로 설정하여 사용하였습니다. `json`파일의 항목명을 변환하여 모델타입의 변수와 매칭하는 방법이 더 간단하다 판단했습니다. 
현재 프로젝트에서는 항목이 20개 이내여서 일일히 다른 것이 무엇인지 찾을 수 있지만, `Parsing` 할 데이터의 표기양식 종류가 두가지 이상이라면 `CodingKey`를 채택하여 사용하는것이 더 좋다고 판단했습니다.

- 진짜 메서드와 Mock이용 테스트목적 메서드의 네이밍
`TestDouble`진행 시 원래 구현되어있는 `dataTask`메서드와 Mock객체를 이용한 테스트 진행시 호출하는 우리가 구현한 `dataTask` 메서드의 네이밍을 같게 해도 되는것인지 현업에서도 이렇게 하시는지 궁금합니다.

- NetworkRequest enum 타입에서 작업에 맞는 URL들을 반환하게 구현을 하였습니다.
queryItem이 나중에는 사용자의 클릭혹은 스크롤로 내부의 값이 변경되어야 한다고 생각이 되는데,
이 부분을 enum 타입을 유지하여 연관값을 해야할지, 혹은 Class 타입으로 변경하여 객체를 생성해서 값을 받아오는 방향으로 구현을 해야할지 고민이 됩니다.

2022-11-18 12:07 UTC, Monsteel requested changes
안녕하세요 Kyo, LJ 👍  반갑습니다!!
첫 Step1 PR까지 수고 많으셨습니다 👍 

전반적으로 크게 리뷰할 포인트가 많지 않은, 이유있는 코드들이였습니다 👍 
앞으로 차차 Step이 진행되면서 이 코드들이 base가 되어 어떤 코드가 나오게 될지 기대됩니다 ✨

> 토니의 좋은 + 많은 코멘트 부탁드립니다 :)
코멘트가 많다고 꼭 좋은 리뷰는 아니라고 생각합니다만 👍 의견을 전달드리고 싶은 부분들에 대해 리뷰드립니다 👍 

아래엔 남겨주신 고민에 대한 제 의견입니다.
### 2️⃣ 실제 사용할 메서드와 Mock 이용 테스트목적 메서드의 네이밍
약간의 혼선이 있을것 같다는 생각도 들긴 합니다만, 사실 칭찬드리고 싶은 마음이 큽니다 👍 
`URLSessionProtocol`, 역할에 맞는 일을 하고 있다고 생각합니다 👍 

하지만, URLSession의  dataTask function은 URLSessionProtocol에 의해서 작성된 function이 아니기에 이런 코드가 작성되었다고 볼 수 있는데요, 이런 상황을 조금 더 명시적으로 처리할 수 있으면 더 좋을것 같다는 생각이 듭니다 💯 

### 3️⃣ NetworkRequest enum 타입의 추후 타입 변경에 대한 고민
어느 방향성이 더 좋을지 잘 비교해서 결정해 보셨으면 좋겠습니다.

요즘 여러 코드를 보면서 느낀점을 조금 적어봅니다.

사실 우리에게 도움이 될거라는 생각, 더 깔끔한, 더 생산성 좋은 코드가 될거라는 생각에
이런 개념, 저런 개념들을 도입하고, 구조를 작성하게 되는데요,

사실 그 개념 도입으로 인해서 실제로 생산성이나 가독성의 측면에서 크게 도움이 되는지 조금은 더 깊게 고민해 볼 필요가 있다고 생각합니다.

집중해서 보면 오히려 독이되는 경우도 있더라구요.

여러분들의 코드와 상황이 그렇다는게 아니라, 여러분들의 이번 판단에 도움이 되었으면 해서 제 생각을 적어봅니다. 👍 

***
모두 수고 많으셨구요,
추가적인 질문이나, 논의는 언제나 환영이니, 깃헙 코멘트나, 디스코드로 연락주세요! 👍

2022-11-18 12:07 UTC, Monsteel commented on OpenMarket/OpenMarket/Common/NetworkError.swift
> +enum NetworkError: Error {
오류를 Enum으로 정의하셨네요 👍 깔끔하니 좋습니다 ✨

2022-11-18 12:07 UTC, Monsteel commented on OpenMarket/OpenMarket/Extensions/Formatter+.swift
> +        formatter.timeZone = TimeZone(identifier: "UTC")
TZ을 UTC로 설정하신 이유가 있나요~? 👀

2022-11-18 12:07 UTC, Monsteel commented on OpenMarket/OpenMarket/Extensions/String+.swift
> +//  String+.swift
오잉 뭔가 파일명이 이상합니다 😵‍💫

2022-11-18 12:07 UTC, Monsteel commented on OpenMarket/OpenMarket/Extensions/Formatter+.swift
> +//  Formatter+.swift
오잉 뭔가 파일명이 이상합니다 😵‍💫

2022-11-18 12:07 UTC, Monsteel commented on OpenMarket/OpenMarket/Extensions/URLComponents+.swift
> +extension URLComponents {
`URLComponents`를 활용해서 명시적으로 잘 진행해 주셨네네요! 좋습니다 👍

2022-11-18 12:07 UTC, Monsteel commented on OpenMarket/OpenMarket/Models/DecodeManager.swift
> +    func decodeJsonFile(file: String) -> Result<T, NetworkError> {
`file`이라는 표기는 `file`의 어떤(path인지, name인지..등등 ..) 정보를 받고자 하는지 정확하게 파악하기가 어려워 보입니다 😭
조금 더 fit한 이름을 붙여주는건 어떨까요 ?

2022-11-18 12:07 UTC, Monsteel commented on OpenMarket/OpenMarket/Models/Product.swift
> +struct Product: Decodable {
`Decodable`로 역할을 decode로 한정지어 주셨네요! 좋습니다 👍

2022-11-18 12:56 UTC, KyoPak commented on OpenMarket/OpenMarket/Extensions/Formatter+.swift
> +//  Formatter+.swift
Formatter+Extension로 좀더 명시적으로 파일명 변경해주었습니다!.😅

2022-11-18 12:56 UTC, KyoPak commented on OpenMarket/OpenMarket/Extensions/String+.swift
> +//  String+.swift
아래와 같이 String+Extension로 좀더 명시적으로 파일명 변경해주었습니다!.😅

2022-11-18 13:09 UTC, lj-7-77 commented on OpenMarket/OpenMarket/Models/DecodeManager.swift
> +    func decodeJsonFile(file: String) -> Result<T, NetworkError> {
넵😁 fileName으로 매개변수명을 정확히 파악할 수 있도록 수정하였습니다. 
그리고 메서드명도 decodeJsonFile에서 File 이 중복되어 
decodeJsonFile(file:) ➡️ decodeJson(fileName:) 으로 변경하였습니다.
[bb5e960](https://github.com/yagom-academy/ios-open-market/pull/212/commits/bb5e960213dfd2012203df82f0170a81de1c5ff5)

2022-11-18 13:12 UTC, lj-7-77 commented on OpenMarket/OpenMarket/Extensions/Formatter+.swift
> +        formatter.timeZone = TimeZone(identifier: "UTC")
처음에 TimeZone 없이 했을 때 시차가 났었습니다. UTC로 변경하니 시차발생이 안되었고 그대로 넘어간것 같습니다. 좀 더 정확히 알아보니 KST(한국표준시)도 있다는 것을 알게되었습니다. KST로 수정하는 것이 더 적절해 보여서 수정하였습니다.👍

2022-11-20 10:07 UTC, Monsteel approved these changes
고생하셨습니다~ 이어서 Step2 진행부탁드려요 ☺️

2022-11-20 10:07 UTC, merged