오픈마켓 [STEP 1] 애종, 토털이
yagom-academy/ios-open-market pull request #213
Opened 2022-11-17 14:52 UTC by jonghancha

# STEP 1 PR

 안녕하세요. 올라프(@1Consumption)!
이번 오픈마켓 프로젝트 리뷰를 부탁드리게 된 애종, 토털이 입니다!! PR 예정계획을 미리 말씀 못드린 점 다시한번 죄송합니다. `네트워크 fetching`, `@escaping` 처럼 처음 접하는 개념들을 공부하며 프로젝트를 진행하다보니 시간이 지체된 것 같습니다. 이번 Step1에서는 네트워크 통신을 어떻게 구현할 지, completion handler를 어떻게 사용할 지, 그리고 mock를 사용한 UnitTest구현 이렇게 세 가지 정도를 중점적으로 고민했습니다! 잘 부탁드립니다!
🙇‍🙇‍🙇‍🙇‍🙇‍🙇‍🙇‍🙇‍🙇‍🙇‍🙇‍

## 구현내용

- 디코딩을 위한 Decodable struct `ProductList` 생성
- 네트워크 통신을 담당할 타입인 `NetworkAPIProvider` 클래스를 설계하고 구현, extension에 fetch 함수를 구현함
- `NetworkAPI` enum으로 url components를 분리하여 관리할 수 있도록 설계
- `URLComponents` extension에 `setQueryItems()`를 추가해주어 쿼리를 효율적으로 관리할 수 있도록 설계
- MockURLSession을 구현하여 테스트 할 수 있도록 설계
- Test Double를 적용하여 Mock URLsession을 만들어 네트워크와 무관하게 동작하는 테스트를 수행

## 고민되었던 점
 ### 1. **URL을 어떻게 쓰면 좋을지에 대한 고민**
dataTask()메서드 사용을 위해 url을 사용할 때 아래와 같이 String형태로 쓰는 것보다 
"https://openmarket.yagom-academy.kr/api/products"
   URl Components를 사용해 분리해서 관리하는 것이 더 좋다고 생각했습니다. 저희는 열거형NetworkAPI 와 Query를 사용해 URL을 관리했습니다. 
```swift
enum NetworkAPI {
    
    static let scheme = "https"
    static let host = "openmarket.yagom-academy.kr"
    
    case productList(query: [Query: String]?)
    case product(productID: Int)
    case healthCheck
}
```
step1에서 필요한 세 가지 네트워킹요소를 case로 구분하고, url구성에 더 필요한 query의 경우 매개변수를 통해 추가되도록 구현했습니다. 최종적으로 enum 내부의 연산프로퍼티 urlComponents 를 통해 URL Components를 완성시키게 됩니다.

### 2.**NetworkAPIProvider fetch함수 설계의 고민**
NetworkAPIProvider에서 `fetch()`라는 제너럴한 함수를 구현해서 extension에 넣어주어 각각의 api 호출에 따른 fetch 함수들을 만들때 fetch를 불러와서 쓰면 되는 형태로 설계를 해보았습니다. completionHandler를 계속 전달해 주는 형태로 설계를 해보았는데 흔한 설계는 아닌 것 같아 고민이 들었습니다.
```swift
final class NetworkAPIProvider {
    ...
    func fetchProductList(query: [Query: String]?, completion: @escaping (ProductList) -> Void) {
        fetch(path: .productList(query: query)) { data in
            guard let productList: ProductList = DecodeManger.shared.fetchData(data: data) else {
                return
            }
            completion(productList)
        }
    }
}

extension NetworkAPIProvider { 
    
    func fetch(path: NetworkAPI, completion: @escaping (Data) -> Void) {
        guard let url = path.urlComponents.url else { return }

        session.dataTask(with: url) { data, response, error in
            if let error = error {
                dump(error)
                return
            }
            
            guard let httpResponse = response as? HTTPURLResponse,
                  (200...299).contains(httpResponse.statusCode) else {
                self.handleServerError(response)
                return
            }
            
            guard let data = data else { return }
            
            completion(data)
        }.resume()
    }

```

### 3. **Mock 를 사용한 네트워킹 유닛 테스트**
실제 네트워크를 통신이 아닌, URLsession을 `흉내내는 객체`를 생성해 UnitTest를 진행해보았습니다.
원래는 `URLsession.shared`의 dataTask메서드를 통해 네트워킹을 진행하지만, MockURLSession의 dataTask는 `successResponse`, `failureResponse` 의 response를 미리 구현한 후 받아오는 형태로 구현했습니다.
```swift
let successResponse = HTTPURLResponse(url: url,
                                      statusCode: 200,
                                      httpVersion: "2",
                                      headerFields: nil)
        
let failureResponse = HTTPURLResponse(url: url,
                                      statusCode: 410,
                                      httpVersion: "2",
                                      headerFields: nil)

```
성공 혹은 실패의 결과는 MockURLSessionDataTask의 resumeDidCall() 메서드를 통해 저희가 생성한 MockDatatask가 resume() 될 때 아래와 같이 호출되도록 구현했습니다.
```swift
sessionDataTask.resumeDidCall = {
            if self.makeRequestFail {
                completionHandler(nil, failureResponse, nil)
            } else {
                completionHandler(MockData.sampleData, successResponse, nil)
            }
        }
```

## 조언을 얻고 싶은 부분
### **fetch 함수**
현재 fetch와 관련된 escaping closure들에서는 Data타입을 리턴해주고 있습니다. Result타입이 아닌 data 타입으로 값을 리턴하고 있는데 Result 타입으로 리턴해주는 것이 더 나을지 고민이 되어 여쭙고 싶습니다.

---

2022-11-18 01:28 UTC, 1Consumption requested changes
안녕하세요 @jonghancha @tottalE 고생하셨습니다.

고민하신 점에 적어주신 `Result` 타입 사용은 적극 권장하는 바입니다. 그리고 클로저의 `매개변수`로 값을 넘기고 있으니 `리턴` 이라는 표현은 맞지 않다고 생각합니다.

나머지는 코멘트를 확인해주세요.

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/NetworkTests/NetworkTests.swift
> +@testable import OpenMarket
`@testable` 어노테이션은 어떤 역할을 하나요? 왜 import 하셨나요?

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/NetworkTests/NetworkTests.swift
> +        sut = .init(session: MockURLSession())
Mock이라는 용어를 사용하셨는데, 혹시 test double에 대해서 알고 계신가요?
또 mock과 stub의 차이는 뭘까요? 지금 짠 코드는 mock에 가까울까요 stub에 가까울까요?

잘 모르겠으면 아래 링크를 참고해보세요.
https://martinfowler.com/articles/mocksArentStubs.html
https://academy.realm.io/kr/posts/making-mock-objects-more-useful-try-swift-2017/

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/NetworkTests/NetworkTests.swift
> +                                                 from: MockData.sampleData)
여기서 `MockData.sampleDate`로 Assertion이 가능한 이유는 `MockURLSession` 내부에서도 `MockData.sampleDate`을 사용하고 있어서네요. 근데 만약 둘 중 한 곳에서 다른 프로퍼티를 사용한다면 Assertion이 실패하겠네요. 고로 여기서 `MockURLSession`에 데이터를 전달해주고, 그 데이터로 Assertion을 진행하는게 더 안정적으로 보입니다.

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/OpenMarket/Errors/DataError.swift
> +    public var failureReason: String? {
접근제어자가 `public`인 이유가 있나요?
접근제어자는 어떤게 있으며 어떻게 사용되나요?

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/OpenMarket/Extensions/URLComponents+Extension.swift
> +        self.queryItems = parameters.map { URLQueryItem(name: $0.key.rawValue, value: $0.value) }
`rawValue`에 직접 접근하지말고, `Customstringconvertible`이라는 프로토콜을 사용해보는건 어떨까요?

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/OpenMarket/MockForTest/MockURLSession.swift
> +import UIKit
UIKit과 Foundation의 관계는 어떻게 되나요?

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/OpenMarket/MockForTest/MockURLSession.swift
> +final class MockURLSession: URLSessionProtocol {
이 클래스는 테스트를 위한 클래스니까 테스트 타겟에 있어야한다고 생각합니다. 실제로 유저가 사용하는 코드는 아니니까요.

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/OpenMarket/MockForTest/MockURLSession.swift
> +            return MockURLSessionDataTask()
<img width="731" alt="image" src="https://user-images.githubusercontent.com/37682858/202540916-b240afff-d6ec-41c5-984e-7b52d62d0003.png">
이런 워닝이 뜨는 것을 무시하면서까지 코드를 짠 이유가 있을까요?

네트워크 mocking을 위한거라면 아래 링크를 참고해보세요.
https://developer.apple.com/videos/play/wwdc2018/417/
https://developer.apple.com/documentation/foundation/urlprotocol

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/OpenMarket/Model/ProductList.swift
> +struct ProductList: Codable {
`Codable`은 어떤 프로토콜의 집합체인가요? 지금 `Codable`의 모든 기능이 다 필요한 상황인가요?

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/OpenMarket/Utilities/DecodeManager.swift
> +import UIKit
`UIKit`이 필요한가요?

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/OpenMarket/Utilities/DecodeManager.swift
> +    static let shared = DecodeManger()
싱글톤을 사용한 이유가 궁금합니다. 상태를 유지하면서 전역적으로 사용되는 클래스인가요?

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/OpenMarket/Utilities/DecodeManager.swift
> +    func fetchData<T: Decodable>(name: String) throws -> T? {
Result 타입을 사용하면 에러를 보다 명확하게 보낼 수 있지 않을까요?

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/OpenMarket/Utilities/DecodeManager.swift
> +        return itemData
이 객체의 역할은 `Data` 타입을 특정 객체 타입으로 변경해주는 것 이라고 생각됩니다. 그런데 여기서 어디서 `Data`를 받아올지 까지 알아야할까요?

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/OpenMarket/Utilities/NetworkAPI.swift
> +            if let query = query {
swift 5.7에서는 아래와 같이 사용할 수 있어요.
```suggestion
            if let query {
```

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +    let session: URLSessionProtocol
외부에서 알아야하는 변수인가요?

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +final class NetworkAPIProvider {
final은 왜 추가하셨나요? 이걸 하면 뭐가 달라지나요?

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +    }
만약 `fetchData(data:)` 메소드가 nil을 반환했을 때, 어떻게 어러처리를 해야하나요? 지금은 아무런 동작도 하고 있지 않네요.

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +extension NetworkAPIProvider {
extension으로 분리한 이유가 있을까요?

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +                dump(error)
불필요한 코드 같습니다.

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +                self.handleServerError(response)
여기서 self를 붙여준 이유는 뭔가요?

2022-11-18 01:28 UTC, 1Consumption commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +        print(httpResponse.statusCode)
print 메소드는 지양해주세요. 이러면 아무도 에러가 발생한지 모릅니다.

2022-11-18 02:22 UTC, jonghancha commented on OpenMarket/NetworkTests/NetworkTests.swift
> +@testable import OpenMarket
현재 NetworkTests 타깃은 OpenMarket타깃과 별개로 존재하고 있습니다. OpenMarket 타깃의 코드들은 대부분 internal 수준의 접근 제한 수준으로 설정되어 있습니다. internal은 하나의 모듈 안에서만 접근이 가능하기 때문에 테스트 타깃에서는 기본적으로 접근이 불가능합니다. 이 때 테스트 코드에서 OpenMarket 내부의 타입들에 접근할 수 있도록 도와주는 것이 `@testable`이라고 생각합니다. 테스트하는 동안에는 import해주는 타깃의 코드에 접근할 수 있도록 해줍니다.

2022-11-18 02:53 UTC, tottalE commented on OpenMarket/NetworkTests/NetworkTests.swift
> +        sut = .init(session: MockURLSession())
상태를 검증하는지 behavior를 검증하는지에 따라 stub와 mock를 구분할 수 있는 것으로 일단 이해해 보았습니다. 이 경우 저희는 상태를 비교하기 때문에 stub에 더 가까운 것 같습니다!

2022-11-18 03:15 UTC, jonghancha commented on OpenMarket/NetworkTests/NetworkTests.swift
> +                                                 from: MockData.sampleData)
위 코드의 response와 MockURLSession 내부에서 각각 sampleData를 사용하기 때문에 안정적이지 않다는 말씀으로 이해했습니다. 그래서 MockURLSession에 데이터를 전달해줄 수 있도록 refactor했습니다. 그리고 Test파일 내부적으로도 같은 프로퍼티를 전달하도록 코드를 변경했습니다. 아래 커밋링크도 첨부하겠습니다!


- 커밋 링크
[3c7b10b](https://github.com/yagom-academy/ios-open-market/pull/213/commits/3c7b10b757e885026d12a618c008b203c07c6bf0)

2022-11-18 03:29 UTC, tottalE commented on OpenMarket/OpenMarket/Errors/DataError.swift
> +    public var failureReason: String? {
public 일 이유가 없는데 LocalizedError의 사용법에만 집중하다 보니 접근제어자를 놓쳤습니다. 실험 결과 프로토콜의 접근제어자는 internal로만 정의가 가능했고, 채택한 인스턴스에서는 더 넓은 범위인 public과 open만이 사용이 가능했습니다! 접근제어자는 아래와 같이 있고, 접근 수준을 관리해 주기 위해 사용합니다!
open: 개방 접근 수준(모듈 외부까지), 클래스에서만 사용
public: 공개 접근 수준(모듈 외부까지)
internal: 내부 접근 수준(모듈 내부)
fileprivate: 파일 외부 비공개 접근 수준(파일 내부)
private: 비공개 접근 수준(기능 정의 내부)

아래에 커밋 첨부드립니다!
[b8d72a5](https://github.com/yagom-academy/ios-open-market/pull/213/commits/b8d72a5e86e26ce9cf5f2480c4bd088c791b81ae)

2022-11-18 07:13 UTC, tottalE commented on OpenMarket/OpenMarket/Extensions/URLComponents+Extension.swift
> +        self.queryItems = parameters.map { URLQueryItem(name: $0.key.rawValue, value: $0.value) }
프로토콜 사용하여 수정해 주었습니다!!

[3611bd8](https://github.com/yagom-academy/ios-open-market/pull/213/commits/3611bd80af9daeb20c6f6eb50a5d4276fa84aea9)

2022-11-18 07:16 UTC, tottalE commented on OpenMarket/OpenMarket/MockForTest/MockURLSession.swift
> +import UIKit
UIKit 내에 Foundation이 포함이 되어 있습니다! foundation import를 해줬다는 걸 깜빡했네요! 
여기 수정해 주었습니다!

[5d765d8](https://github.com/yagom-academy/ios-open-market/pull/213/commits/5d765d83145f2379f8eaa9df1e890e6754895f04)

2022-11-18 07:25 UTC, jonghancha commented on OpenMarket/OpenMarket/MockForTest/MockURLSession.swift
> +final class MockURLSession: URLSessionProtocol {
넵 protocol을 제외한 MockForTest폴더를 NetworkTest타깃으로 옮겨주었습니다!

2022-11-18 07:41 UTC, jonghancha commented on OpenMarket/OpenMarket/Model/ProductList.swift
> +struct ProductList: Codable {
Codable은 Encodable 과 Decocdable의 집합체입니다. 현재 저희는 Decodable 프로토콜만 사용하기 때문에 Decodable로 변경해주었습니다.

2022-11-18 07:44 UTC, jonghancha commented on OpenMarket/OpenMarket/Utilities/DecodeManager.swift
> +import UIKit
json 파일을 Asset에 넣어주고 decode하는 과정에서 NSDataAsset 클래스를 사용하기 위해 UIKit를 import해주었습니다!

2022-11-18 07:53 UTC, tottalE commented on OpenMarket/OpenMarket/Utilities/DecodeManager.swift
> +    static let shared = DecodeManger()
생각 해 보니 싱글톤을 사용할 만큼 메모리에 계속 올라와 있어야 하는 인스턴스는 아니라고 생각이 되어 decoder extension에 다시 코드를 작성해 주었습니다!
[7a4df30](https://github.com/yagom-academy/ios-open-market/pull/213/commits/7a4df300bd2edbef3e09d43b12ef48d946d84d57)

2022-11-18 08:00 UTC, jonghancha commented on OpenMarket/OpenMarket/Utilities/DecodeManager.swift
> +        return itemData
해당 객체의 역할은 Data 타입을 객체 타입으로 변경해주기만 하면 되는 것이 맞는것 같습니다. 다만 현재 asset을 사용하지 않고 서버에서 json 데이터를 받아오거나, sampleData를 통해 test를 해주고 있기 때문에, 해당 객체는 삭제 후 decode 기능만 extension으로 분리해주었습니다!

2022-11-18 11:52 UTC, 1Consumption commented on OpenMarket/OpenMarket/Extensions/URLComponents+Extension.swift
> +        self.queryItems = parameters.map { URLQueryItem(name: $0.key.rawValue, value: $0.value) }
왜 그렇게 수정하셨나요?

2022-11-19 05:30 UTC, tottalE commented on OpenMarket/OpenMarket/Extensions/URLComponents+Extension.swift
> +        self.queryItems = parameters.map { URLQueryItem(name: $0.key.rawValue, value: $0.value) }
아래 코드와 수정한 코드 중 고민하다가, 더 description이 저희가 아는 연산 프로퍼티이고 Customstringconvertible이 결국 인스턴스를 스트링으로 바꾸어주는데, 공식 문서 상에서는 프린트 밖에 없어 사용법이 익숙하지 않아 익숙한 방법으로 일단 수정해 보았습니다. 아래의 코드가 더 울라프가 말씀하신 의도와 가까운가요?
```swift
self.queryItems = parameters.map { URLQueryItem(name: "\($0.key)", value: $0.value) }
```

2022-11-19 06:16 UTC, tottalE commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +        print(httpResponse.statusCode)
네 Result 타입을 사용해 주어 이 문제는 해결해 주었습니다! 감사합니다!네 Result 타입을 사용해 주어 이 문제는 해결해 주었습니다! 감사합니다!

[7536fb0](https://github.com/yagom-academy/ios-open-market/pull/213/commits/7536fb0f5a69290e0e3737db8e379f3dff8cf2f1)

2022-11-19 06:17 UTC, tottalE commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +                self.handleServerError(response)
공식 문서에 나와 있어 그렇게 작성해 주었는데, 생각해 보니 불필요하고, Result 타입을 적용해 줌으로써 문제가 해결되었습니다! 감사합니다.

2022-11-19 06:17 UTC, tottalE commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +                dump(error)
completion으로 에러를 Result내에 담아 클로저의 매개변수로 넘겨줄 수 있도록 다시 만들어 주었습니다!

2022-11-19 06:18 UTC, jonghancha commented on OpenMarket/OpenMarket/Utilities/DecodeManager.swift
> +    func fetchData<T: Decodable>(name: String) throws -> T? {
NetworkError를 정의하고 Result 타입을 escaping 클로저에 넣어줌으로써 에러처리가 되도록 구현했습니다.
```swift
sut.fetchProductList(query: nil) { result in
            switch result {
            case .failure:
                XCTFail()
            case .success(let productList):
                XCTAssertEqual(productList.pageNumber, response?.pageNumber)
                XCTAssertEqual(productList.itemsPerPage, response?.itemsPerPage)
            }
            expectation.fulfill()
        }
```

해당 커밋링크 첨부하겠습니다!
[3c7b10b](https://github.com/yagom-academy/ios-open-market/pull/213/commits/3c7b10b757e885026d12a618c008b203c07c6bf0)

2022-11-19 06:20 UTC, tottalE commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +extension NetworkAPIProvider {
저희는 상세한 url의 request의 경우에 fetch[특정리소스] 메서드 형태로 NetworkPovider의 기능을 만들어주기 위해 설계를 계획했습니다. 그 중에서 fetch() 함수는 모든 fetch[특정리소스] 메서드가 사용할 수 있는 fetch만을 수행하는 (데이터 fetch만을 수행하고 decoding은 수행하지 않는) 모든 fetch[특정메서드]가 get으로 사용할 수 있는 메서드를 만들어 주었고 이는 분리시켜주는 것이 맞다고 생각하였습니다!

2022-11-19 06:21 UTC, jonghancha commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +    let session: URLSessionProtocol
아닙니다. 현재 session은 NetworkAPIProvider의 인스턴스가 생성될 때 주입해주는 곳 말고는 사용되지 않아 private 을 붙여주었습니다!

2022-11-19 06:30 UTC, jonghancha commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +final class NetworkAPIProvider {
final 키워드는 명시적으로 상속이 안되고 런타임 성능을 향상시켜줍니다. 런타임 성능을 향상시켜주는 이유는 final 키워드를 붙여주면 static 디스패치방식을 이용해 컴파일 시점에서 사용할 지 안할지 알 수 있기 때문이라고 알고 있습니다. 저희도 공식문서에서 확인한 부분은 아니라서 혹시 틀린 부분이 있다면 말씀해주세요!!

2022-11-19 06:31 UTC, jonghancha commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +    }
이 부분도 마찬가지로 NetworkError의 decodeFailed라는 에러로 Result타입을 통해 처리하고 있습니다.

2022-11-21 15:16 UTC, 1Consumption commented on OpenMarket/OpenMarket/Extensions/URLComponents+Extension.swift
> +        self.queryItems = parameters.map { URLQueryItem(name: $0.key.rawValue, value: $0.value) }
저는 토털이가 적어주신 방법이 더 나아보여요.

2022-11-21 15:17 UTC, 1Consumption commented on OpenMarket/OpenMarket/Utilities/DecodeManager.swift
> +    static let shared = DecodeManger()
생각해보니 fetch보다는 decode가 조금 더 맞는 네이밍 같네요.

2022-11-21 15:19 UTC, 1Consumption approved these changes
고생하셨습니다. 다음 스텝을 진행해주세요.

2022-11-21 15:19 UTC, merged