오픈마켓 [STEP 2] 로빈, 스톤
yagom-academy/ios-open-market pull request #217
Opened 2022-11-23 05:04 UTC by lws2269

안녕하세요 알라딘(@junbangg)! 스톤, 로빈입니다~
오픈마켓 step2에서 코드로 모든걸 구현하고 ModernCollectionView를 사용하려다보니 어려운 점이 꽤 많아서 PR이 많이 딜레이된 것 같습니다..!
이번 스텝도 잘부탁 드립니다! 아낌없는 조언 부탁드립니다!🙏

## 구현내용
### Modern Collection View 구현
- `ViewController`에서 `Grid`, `List`에 해당하는 `CollectionView`를 `addView`한 후, `segmentedControl`의 `index`를 사용해 두개의 컬렉션뷰를 `Switching` 합니다
- Grid와 List에 사용하는 `DiffableDataSource`가 다르기때문에 각각의 `CollectionView를` 생성하였고, `segmetedControl`을 통해 Grid 또는 List `CollectionView`가 숨겨지도록 설정하여 구현하였습니다.
#### ListCollectionView
- `updateWithItem(_ newItem: Item)` 메서드를 통해 item값으로 cell을 그릴 수 있도록하였습니다.
    - `UICellConfigurationState`를 사용하여 `CollectionView의` `ContentView.configuration`을 세팅해주는 방법을 통해 data를 설정해주었습니다.
#### GridCollectionView
- `updateWithItem(_ newItem: Item)`메서드를 통해 item값으로 cell을 그릴 수 있도록하였습니다.
---
### Item 이미지 캐시처리
- `ImageCacheManager` : 이미지 캐시처리를 하기위한 클래스 입니다.
```swift
class ImageCacheManager {
    static let shared = NSCache<NSString, UIImage>()
    private init() {}
}
```
- `NetworkManager().fetchImage()` : url을 통해 가져온 이미지를 컴플릿핸들러로 넘겨줍니다. 이미지가 캐시되어 있으면 로컬에 저장된 이미지를 컴플릿핸들러로 넘겨주고, 아니면 서버에서 이미지를 가져온 후 캐시에 저장 및 컴플릿핸들러로 넘겨줍니다.
```swift
func fetchImage(url: URL, completion: @escaping (UIImage) -> ()) {
    let cachedKey = NSString(string: "\(url)")
    if let cachedImage = ImageCacheManager.shared.object(forKey: cachedKey) {
        return completion(cachedImage)
    }
    DispatchQueue.global(qos: .utility).async {
        if let data = try? Data(contentsOf: url),
           let image = UIImage(data: data) {
            ImageCacheManager.shared.setObject(image, forKey: cachedKey)
            completion(image)
        }
    }
}
```

---
### UIActivityIndicatorView 를 사용한 Spinner 처리
- **Controllers - LoadingSpinner**
    - itemList를 받아오기 전 화면을 표시하기 위한 클래스입니다.
        - 데이터를 받아오기 전 `showLoading()` 메서드를 사용해 Spinner를 표현하고 데이터를 받아온 후에 `hideLoading()`을 통해 종료합니다.

## 조언을 얻고 싶은 부분
### ListCollectionView <-> GridCollectionView
- 저희 코드에서 두가지 뷰를 스위칭을 `isHidden`프로퍼티를 통하여 숨기고 보여주는 식의 컬렉션 뷰를 전환했습니다.
    - 레이아웃을 갈아끼는 식으로 해보려 했지만, 두가지 `CollectionView` 타입이 `data`를 다루는 부분이 달라 두가지 컬렉션 뷰를 추가하여 `isHidden`으로 처리했습니다.

[UICollectionViewDiffableDataSource](https://developer.apple.com/documentation/uikit/uicollectionviewdiffabledatasource) 여기 문서 **important** 부분이 아래와 같습니다.

> Don’t change the dataSource on the collection view after you configure it with a diffable data source. If the collection view needs a new data source after you configure it initially, create and configure a new collection view and diffable data source.

저희는 이 부분을 보고, 새 데이터 소스가 필요한 경우 새 콜렉션 뷰와 새로운 `diffable dataSource`를 작성하고 구성하라고 되어있어서, 2개의 콜렉션뷰(그리드, 리스트)를 만들고 `segmentedControl` 에 따라 `hidden` 시키는 것을 맞다고 판단했습니다.`isHidden`을 통해 처리하는 것이 좋은지 알라딘의 의견이 궁금합니다!

2022-11-24 15:10 UTC, junbangg requested changes

2022-11-24 15:10 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ImageCacheManager.swift
> +class ImageCacheManager {
Final 처리 할 수 있을것 같아요!

2022-11-24 15:10 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/LoadingController.swift
> +class LoadingIndicator {
요거 클래스로 구현하신 이유가 있나요???(틀렸다는건 아닙니다🙂)

2022-11-24 15:10 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +final class ViewController: UIViewController {
이름을 조금 더 알맞게 지을 수 있을것 같아요!

2022-11-24 15:10 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +    private func checkCollectionType(segmentIndex: Int) {
하는 일이랑 이름이 잘 매칭되는지는 모르겠습니다! 체크한다기보다는 숨기고 보여주는 역할을 하는거 같아서요🤔

2022-11-24 15:10 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +        let config = UICollectionLayoutListConfiguration(appearance: .plain)
요친구는 왜 이름이 짤렸을까요?!

2022-11-24 15:10 UTC, junbangg commented on OpenMarket/OpenMarket/Extension/Double+Extension.swift
> +            return "error"
여기서 "error" 이라는 문자열을 리턴 하기로 정한 이유?근거?가 궁금합니다

2022-11-24 15:10 UTC, junbangg commented on OpenMarket/OpenMarket/SceneDelegate.swift
> +        let navVC = UINavigationController(rootViewController: rootVC)
축약어는 웬만하면 지양하는게 좋을것 같아요!

2022-11-24 15:10 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/LoadingController.swift
> +class LoadingIndicator {
그리거 final 도!🙌

2022-11-24 15:10 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/LoadingSpinner.swift
> +class LoadingSpinner {
Final 가능할것 같습니다

2022-11-24 15:10 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/LoadingSpinner.swift
> +class LoadingSpinner {
위에거랑 하는 일이 다른건가요????

2022-11-24 15:10 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +    private func configureCollectionView() {
여기서 갑자기 self 를 사용하기 시작하신 이유가 있나요?!

2022-11-24 15:17 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/LoadingSpinner.swift
> +class LoadingSpinner {
하는 일도 같아보이고 위에거 `LoadingIndicator` 는 안쓰이는것 같네요!🤔

2022-11-24 15:17 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +    }
요건 무슨 친구죠.?!

2022-11-24 15:19 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/LoadingSpinner.swift
> +class LoadingSpinner {
이 친구 이런식으로 타입 메서드로 사용하기로 결정한 이유가 궁금합니다!  뷰컨에 프로퍼티로 갖고 있게 했을 수도 있고 여러 방법이 있었을텐데 말이죠(그게 맞다는건 아닙니다)

2022-11-24 15:21 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +extension ViewController {
여기부터 `extension` 을 이용해서 메서드들을 나누셨는데 이렇게 한 이유가 있나요???(틀렸다는거 아닙니다)

2022-11-24 15:25 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +        LoadingSpinner.showLoading()
요 친구를 여기 `viewDidLoad` 에서 호출한 이유가 있을까요?🤔

2022-11-24 15:31 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +                    LoadingSpinner.hideLoading()
이런 구조라면 네트워크 요청이 실패하는 경우에는 `hideLoading()` 이 호출 될 수가 없어서 로딩 애니메이션이 계속 돌게 되는 현상이 생길 수도 있을것 같아요!

2022-11-24 15:42 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +                self.viewDidLoad()
네트워크 재호출을 위해서 `viewDidLoad` 를 다시 호출하는게 맞는 방법일까요?? `viewDidLoad` 는 뷰가 그려지기 직전에 한번만 호출되기 위해 있는 녀석일텐데요!

그리고 만약에 API 호출 실패해서 `self.viewDidLoad()` 가 호출되면 백그라운드에서 뷰에 접근하는 형태가 될것 같아요
뷰는 `main` 쓰레드에서만 접근하도록 해야합니다! (요거에 대한 이유를 알고 계실까요??)

뷰와 네트워크 호출이 이런식으로 종속이 되어있으면 좋지 않은 유저 경험을 초래할 수 있을것 같습니다.

2022-11-24 15:46 UTC, junbangg commented on OpenMarket/OpenMarket/Views/GridCollectionViewCell.swift
> +    }()
밑에도 쭉 있지만 요런 뷰 프로퍼티들을 `lazy var` 로 사용하는 방법도 있는데 혹시 고려를 해보셨을까요??

2022-11-24 15:47 UTC, junbangg commented on OpenMarket/OpenMarket/Views/ListCollectionViewCell.swift
> +    private let stockLabel: UILabel = {
위에도 언급을 했었는데 28번째 줄은 지연 속성으로 사용하시고 밑에는 안한 이유가 있나요??(틀렸다는건 아닙니다)

2022-11-24 15:50 UTC, junbangg commented
수고하셨습니다! `isHidden` 으로 `List` 와 `Grid` 형태를 왔다갔다리 하는거 질문 주셨는데

비교군이 있었을까요?? `removeFromSuperView` 도 가능했을것 같은데 두개를 비교해보면 어떤 장단점이 있었을까요???

2022-11-25 05:34 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/ImageCacheManager.swift
> +class ImageCacheManager {
앗.. 알려주셔서 감사합니다! final 키워드 붙여주었습니다~

```swift
final class ImageCacheManager {
    static let shared = NSCache<NSString, UIImage>()
    private init() {}
}
```

2022-11-25 05:35 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +final class ViewController: UIViewController {
`MainViewController`로 수정하였습니다~

2022-11-25 05:39 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +    private func checkCollectionType(segmentIndex: Int) {
감사합니다. 해당 메서드는 매개변수로 들어온 세그먼트 인덱스값의 뷰를 보여주는 역할을 하기 때문에 `showCollectionType(segmentIndex: Int)`로 이름을 다시 지어주었습니다~

2022-11-25 05:40 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +        let config = UICollectionLayoutListConfiguration(appearance: .plain)
아래와 같이 이름을 수정해주었습니다~

```swift
let configuration = UICollectionLayoutListConfiguration(appearance: .plain)
```

2022-11-25 05:42 UTC, lws2269 commented on OpenMarket/OpenMarket/Views/ListCollectionViewCell.swift
> +    private let stockLabel: UILabel = {
다른 속성은 다 상수로 선언하였는데 `itemListContentView`만 선언한 이유는 해당 속성을 상수로 선언하게 되면, 프로퍼티는 인스턴스 생성 이전에 생성되고 메서드는 인스턴스 생성 이후에 부를 수 있다? 라는 오류 문구에 의해 해당 프로퍼티에 접근할때 메모리에 할당시키는 
지연 속성을 사용했습니다..! 아래는 오류 문구입니다.

`Cannot use instance member 'defaultListContentConfiguration' within property initializer; property initializers run before 'self' is available`

2022-11-25 05:43 UTC, yuvinrho commented on OpenMarket/OpenMarket/Extension/Double+Extension.swift
> +            return "error"
테스트를 위해 "error"를 반환하도록 해놓고 나중에 수정을 안해주었습니다😂
아래와 같이 string을 넘버포맷으로 변환하지 못하면 nil을 반환하도록 하였습니다~

```swift
guard let string = numberFormatter.string(for: self) else {
    return nil
}
```

2022-11-25 05:44 UTC, yuvinrho commented on OpenMarket/OpenMarket/SceneDelegate.swift
> +        let navVC = UINavigationController(rootViewController: rootVC)
감사합니다~ 아래와 같이 변수명을 수정해주었습니다~
```swift
let rootViewController = MainViewController()
let navigationViewController = UINavigationController(rootViewController: rootViewController)
```

2022-11-25 05:45 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/LoadingController.swift
> +class LoadingIndicator {
앗😅 감사합니다!! final 키워드 붙여주었습니다~

2022-11-25 05:45 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/LoadingSpinner.swift
> +class LoadingSpinner {
감사합니다! 여기도 final 키워드 붙여주었습니다~

2022-11-25 05:47 UTC, lws2269 commented on OpenMarket/OpenMarket/Views/GridCollectionViewCell.swift
> +    }()
`let`을 우선으로 채택하고 `lazy`가 필요한 속성에 대해서만 `lazy`를 채택하였습니다.
지연속성을 사용한다면 `프로퍼티에 접근할 시 접근 시점에 메모리에 할당된다.`로 알고 있어서 꼭 필요한 상황이 아니면 채택하지 않았습니다.

`lazy`로 선언하게 된다면 다중 스레드 환경에서 동시다발적으로 접근할 때에는 한번만 초기화 된다는 보장이 없다고 합니다.. 

저희 로직 상에서는 그런 부분이 없는 것 같은데 해당 사례 이외의 사례들은 모두 lazy 속성을 채택하는게 좋을까요? 
알라딘의 의견 부탁드립니다!

제가 알고 있는 점이 잘못됐거나 문제가 있다면 매질 부탁드립니다...!!

2022-11-25 05:53 UTC, lws2269 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +                self.viewDidLoad()
`viewDidLoad`보다는 해당 함수를 다시 부르는 재귀처리를 하여 다시 부르도록 하는게 맞는방법 같습니다!
`viewDidLoad`에 대한 역할을 한번 더 생각하고 설계하도록하겠습니다!

뷰는 main쓰레드에서만 접근하도록 해야하는 이유는 스위프트의 UI업데이트를 담당하는 쓰레드는 메인쓰레드여서 다른 쓰레드에서는 처리하면 안된다로 알고있습니다..!

틀린 부분이 있다면 지적 부탁드립니다! 감사합니다

2022-11-25 05:56 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/LoadingSpinner.swift
> +class LoadingSpinner {
하나를 지워준다는 것을 놓쳤습니다🥲 알려주셔서 감사합니다!
타입메서드를 사용한 이유는 추후 다른 뷰컨트롤러에서도 로딩화면을 보여줄 경우,
동일한 기능을 하는 메서드를 또 정의하지 않고 사용하기 위함이었습니다~

2022-11-25 05:57 UTC, lws2269 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +                    LoadingSpinner.hideLoading()
실패 사례의 경우 재귀시키는것이 목적이였는데 그런 부분은 생각지도 못하고 있었습니다..!

로직 변경으로 인해 해결해보았는데 틀린점 있다면 지적 부탁드립니다!
`configureFetchItemList()`메서드 내부에  `LoadingController.showLoading()`를 호출하게 하고
성공과 실패 사례 모두 `LoadingController.hideLoading()`메서드를 호출하고, 실패 사례의 경우 `configureFetchItemList()`메서드를 재호출 함으로써 재귀하는 로직으로 구현해보았습니다.

2022-11-25 05:59 UTC, lws2269 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +        LoadingSpinner.showLoading()
데이터를 받아오기 전까지 로딩을 표현하기 위해 viewDidLoad에 놓았었는데 알라딘의 의견을 토대로 리팩토링을 진행하면서 `configureFetchItemList()` 메서드 내부로 위치시켰습니다..!

2022-11-25 05:59 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +    private func configureCollectionView() {
해당 클래스가 갖고 있는 프로퍼티 모두 self를 붙여주기로 기준을 만들었습니다~

2022-11-25 06:02 UTC, lws2269 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +extension ViewController {
컬렉션뷰의 레이아웃을 그리고 컬렉션뷰를 addView하는 부분을 분리하였습니다..!!

2022-11-25 06:02 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +    }
네비게이션 바에 +버튼을 누르면 아이템추가 화면으로 넘어가도록 구현하려고 한 메서드인데 내부 코드수정을 깜빡하였습니다.
더 꼼꼼히 한번 더 확인해보겠습니다😭

아래와 같이 수정하였습니다~
```swift
@objc private func addItem() {
    navigationController?.pushViewController(ItemAddViewController(), animated: false)
}
```

2022-11-25 06:07 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/LoadingController.swift
> +class LoadingIndicator {
앗... 딱히 이유는 없습니다ㅠㅠ 뷰와 관련된 것들은 클래스로 작성하다 보니깐 이것도 클래스가 맞다고 생각해여 작성하였습니다.ㅠㅠ

2022-11-25 06:15 UTC, yuvinrho commented
안녕하세요 알라딘 리뷰 감사드립니다!
처음에 `diffableDataSource를` 사용하기 전에는 `FlowLayout`을 변경함으로써, 같은 셀의 레이아웃만 변경하는 방법을 생각하다가, 모던 컬렉션 뷰를 사용하다보니 해당 방법은 사용할 수 없을 것 같아, `isHidden을` 통해 처리하였습니다. 
사실 모던컬렉션뷰가 익숙치 않다보니 다른 선택지가 떠오르지 않은것도 있습니다..

`removeFromSuperView`를 사용하여 처리한다면 매번 로직이 불릴때 마다 다소 무거운 작업을 하게될 것 같은 점이 단점으로 다가올 수 있고, 장점으로 생각해본다면 현재 보여주고있는 컬렉션뷰 이외의 컬렉션 뷰는 메모리에 올라가있지 않다는 점? 이 이점으로 다가올 것 같습니다. 
잘못된 점 있다면 아낌없이 팍팍 집어주세요!!🙇‍♂️🙇‍♀️

2022-11-25 10:47 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/LoadingSpinner.swift
> +class LoadingSpinner {
흠 그런 이유라면 싱글톤으로도 가능했을것 같은데 고려를 해보셨을까요??(이 또한 정답은 아님🙂)

2022-11-25 11:01 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +                    LoadingSpinner.hideLoading()
흠 재귀로 네트워크 호출을 계속 하는거에 대한 말씀을 해주셨는데요!
그게 과연 좋은 유저 경험을 제공하는 방법일지는 모르겠네요🤔

만약에 네트워크 호출이 계속해서 실패하는 경우에 그럼 사용자는 계속 별다른 응답이 없는 로딩 인디케이터만 바라보다가 앱을 꺼버리게 될것 같아요!

만약에 네트워크 호출이 실패해서 뷰가 그러질 수 없는 상황이 생기면 그거에 대한 대응을 해주는건 어떨까요?? 예를 들어 사용자에게 알리고(얼럿으로 네트워크 요청이 실패했다고) 재시도 버튼을 제공한다던지? 아니면 디폴트 뷰를 그려준다던지?? 여러 방법이 있겠지만 우린 사용자한테 최대한 친절한 UI를 제공해주는것에 대해 고민을 끊임없이 해야하는 사람들입니다🥴

이건 한번 고민 해보시고 시간나시면 변경해보는것고 좋은 경험일것 같아요!🙂

2022-11-25 11:17 UTC, junbangg commented on OpenMarket/OpenMarket/Views/GridCollectionViewCell.swift
> +    }()
맞습니다! 추가적으로 생각해볼만한건 만약에 해당 타입이 생성될때 무조건 같이 생성될 필요가 없는(지연 시켜도 되는) 요소들이 있다면 고런건 lazy로 만들면 메모리적으로 이점이 생길 수도 있답니다!
정리하자면 무조건 그릴 필요 없고 필요할때만 접근해서 생성되게끔 하고싶르면 lazy를 써도 된다~ 가 되겠습니다:)

여기서 그게 꼭 필요하다는 얘기는 아니고! 알고 계신다면 나중에 고민해볼 수도 있고 좋을것 같아서 한번 말씀 드려봤습니다:)

2022-11-25 13:21 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +extension ViewController {
요거 관련해서 잠깐 디코로 이야기 나눠봐도 좋을것 같네요👍 그렇게 막 엄청 중요한건 아닌데 글로 뭔가 설명하기가 애매해서요ㅎㅎ

2022-11-25 13:25 UTC, junbangg commented
> 안녕하세요 알라딘 리뷰 감사드립니다! 처음에 `diffableDataSource를` 사용하기 전에는 `FlowLayout`을 변경함으로써, 같은 셀의 레이아웃만 변경하는 방법을 생각하다가, 모던 컬렉션 뷰를 사용하다보니 해당 방법은 사용할 수 없을 것 같아, `isHidden을` 통해 처리하였습니다. 사실 모던컬렉션뷰가 익숙치 않다보니 다른 선택지가 떠오르지 않은것도 있습니다..
> 
> `removeFromSuperView`를 사용하여 처리한다면 매번 로직이 불릴때 마다 다소 무거운 작업을 하게될 것 같은 점이 단점으로 다가올 수 있고, 장점으로 생각해본다면 현재 보여주고있는 컬렉션뷰 이외의 컬렉션 뷰는 메모리에 올라가있지 않다는 점? 이 이점으로 다가올 것 같습니다. 잘못된 점 있다면 아낌없이 팍팍 집어주세요!!🙇‍♂️🙇‍♀️

저도 동의합니다! `removeFromSuperview` 를 사용하면 슈퍼뷰와 슈퍼뷰의 윈도우에서 해당 뷰를 떼면서 리스폰더 체인에서도 떼어지게 되죠!
그리고 해당 뷰와 관련된 컨스트레인트들도 전부 해제가 되기 때문에 꽤 무거운 일이라고 볼 수 있겠네요!
List랑 Grid 왔다갔다 할때마다 이렇게 무거운 일이 발생하는것보다 `isHidden`이 좋은것 같습니다~

2022-11-25 13:26 UTC, merged