[Step1] Steven, SJ
yagom-academy/ios-open-market pull request #22
Opened 2021-05-13 07:25 UTC by stevenkim18

@delmaSong 
👐🏻안녕하세요👐🏻 델마!  날씨가 많이 더워졌네요🐳

이번 프로젝트를 시작하면서 저🤡의 제안으로 SJ와 함께 '프로젝트 게시판을 만들어서 프로젝트에 대한 정보를 기록하기로 했습니다

👇👇👇👇👇👇👇
[프로젝트 게시판(SJ, Steven)](https://www.notion.so/SJ-Steven-001b04ff04d941a4a0696572e0d32988)

모델👯‍♀️ 타입을 작성하고 유닛🤖테스트에서 서버간 통신테스트를 구현하느라 시간을 많이 잡아먹은 것 같습니다

이제야 ☝🏻첫번째 PR을 보내네요! 잘 부탁드립니다!🙇🏻‍♂️

# 구현한 부분

## 모델

서버 통신에 필요한 모델을 구현했습니다.

- 상품 조회 모델 - `ItemInfo`
- 목록 조회 모델 - `ItemsList`
- 상품 등록 모델 - `ItemRegistrationForm`

### 클래스 다이어그램
![Step1](https://user-images.githubusercontent.com/35272802/118092708-6956d080-b407-11eb-8cca-e0353cff2c0d.png)

## 구현한 테스트

- url로 서버 api에 요청을 해서 잘 응답이 되는지
- 상품 목록 페이지를 요청해서 데이터(json)를 받아오고 페이지와 아이템 정보가 모델 인스턴스로 잘 파싱이 되었는지
- DELETE메소드로 상품 삭제 요청을 보냈을 때 서버에서 상품 정보가 잘 삭제되는지
- POST메소드로 상품 등록 요청을 보냈을 때 서버에 상품이 잘 등록 되는지
- items.json 파싱하기
- item.json 파싱하기

# 고민했던 부분

### 테스트의 방법과 범위

- 지금과 같이 함수 제목에 테스트 내용을 적고 저희가 작성한 방식으로 하나씩 테스트를 해보는 방법은 괜찮나요?
- 테스트 코드는 어느 정도까지 코드 스타일을 유지하면서 작성해야되나요?(테스트라서 많이 신경쓰지는 않았습니다)

### 중복된 모델을 어떻게 처리 할지

모델 타입을 구현할때 HTTP 메서드별로 중복되는 값이 많아 각각의 타입을 모두 작성하는건 불필요하다 생각하여 보내는 타입과 받는 타입 두개로 나누어서 구현하였습니다. 다른 메서드에서 불필요한 값은 옵셔널로 처리하여 대응하도록 하였는데, HTTP 메서드별로 모든 타입을 구현하는 것과 어떤 차이가 있을지 궁금합니다!

그 외에도 지적하실 거나 조금 더 생각해봤으면 하는 부분들 있으면 거침없이 피드백 남겨주세요! ㅎㅎ

2021-05-14 17:20 UTC, delmaSong requested changes
Steven, SJ 안녕하세요! 수고 많으셨습니다 🌀

### 고민하신 부분
#### 테스트의 방법과 범위
> 지금과 같이 함수 제목에 테스트 내용을 적고 저희가 작성한 방식으로 하나씩 테스트를 해보는 방법은 괜찮나요?

음.. 유닛테스트라는 관점에서 봤을 때는 메서드 이름만 보고 한번에 무슨 테스트를 하고있다! 를 바로 알아볼 수 있게끔 작성해주신 것 같아요.
참고로 유닛테스트가 가능한 메서드의 조건으로는
```
1. 메서드 이름이 test로 시작한다
2. 파라메터를 가지지 않는다
3. 리턴값을 가지지 않는다
```
가 있답니다. 다만 지금은 실서버 API에 너무 많은 의존성이 있어서 이부분을 덜어내는 방향으로 개선이 필요해보입니다.

> 테스트 코드는 어느 정도까지 코드 스타일을 유지하면서 작성해야되나요?(테스트라서 많이 신경쓰지는 않았습니다)

테스트 코드도 실제 코드가 변경될 때 같이 변경되고 관리되어야 하는 코드이므로 실제 코드를 작성하시는 것처럼 신경써서 작성하시면 될 것 같습니다

#### 중복된 모델을 어떻게 처리 할지
> 모델 타입을 구현할때 HTTP 메서드별로 중복되는 값이 많아 각각의 타입을 모두 작성하는건 불필요하다 생각하여 보내는 타입과 받는 타입 두개로 나누어서 구현하였습니다. 다른 메서드에서 불필요한 값은 옵셔널로 처리하여 대응하도록 하였는데, HTTP 메서드별로 모든 타입을 구현하는 것과 어떤 차이가 있을지 궁금합니다!

저도 Steven, SJ와 같은 생각입니다. 하나의 모델(혹은 어떤 타입)을 가지고 읽고, 쓰고, 삭제하는 작업인데 HTTP 메서드별로 타입이 있는 건 불필요한것 같아요. A라는 타입에 HTTP별로 타입이 별개로 있다고 하면 B, C, D... 늘어갈수록 `x HTTP 메서드 갯수` 만큼 숫자가 늘어나게 되는거니까요

아래 코멘트에도 말씀드렸지만 스텝1의 요구사항이 충족되지 않은 부분이 있습니다. 이부분 확인하시고 마저 구현 부탁드려요!

2021-05-14 17:20 UTC, delmaSong commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +        XCTAssertEqual(result.items[0].registrationDate, 1620633347.3906322)
decode가 잘 되었는지를 테스트하기 위함일까요? 아니면 `result.items[0].id`가 정말 `43`인지를 확인하기 위한 테스트일까요?
실제 저 URL 주소로 요청을 보냈는데 데이터가 변경된거라면 이 테스트는 실패하겠군요

2021-05-14 17:20 UTC, delmaSong commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +
이런 주석코드는 클린한 main 브랜치를 위해 pr에서는 제거하고 보내주셔요
커밋만 잘 해두면 다 남아있습니다🤓

2021-05-14 17:20 UTC, delmaSong commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +
실제 서버에 테스트 요청을 보내는 작업이라 한번 테스트를 돌리고 나면 없는 데이터를 삭제해달라고 요청하는거니 무조건 실패하게 되겠군요.. 앞선 코멘트처럼 실제 데이터를 이용해 테스트하는 경우 삭제하면 안 될 데이터를 삭제할 여지도 생기게 되고, 서버에서 다루는 데이터가 변경된 경우에 테스트 코드를 매번 수정해줘야하는 번거로움이 있습니다. 
현재 보내주신 pr에는 스텝1 요구사항인 `서버의 API를 통해 통신할 타입을 구현합니다`가 충족되지 않고있는데
해당 타입을 먼저 구현한 후 만든 타입이 제대로 동작하는지를 테스트하는 게 더 적절해보입니다.

2021-05-14 17:20 UTC, delmaSong commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    }
그리고 `URL요청하기` 라는 이름의 의미가 무엇인지 이해되지 않네요.

2021-05-17 06:12 UTC, stevenkim18 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +
넵!! 주석은 삭제했습니다!

2021-05-17 06:33 UTC, stevenkim18 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    }
음.. 지금 보니 필요가 없는 테스트 같네요! 저희가 맨 처음에서 URL을 요청 했을 때 그 대한 응답이 잘 되는지 학습하기 위해서 만든 테스트입니다!

2021-05-20 14:28 UTC, delmaSong reviewed
수고하셨습니다! 코드 보면서 이야기 나누고 싶은 부분에 대해 코멘트 달아놨으니 확인해주세요 !
그리고 코멘트 남긴 부분에 아직 답변이 안 달린 부분들이 있어서 이쪽도 확인 부탁드려요~!

2021-05-20 14:28 UTC, delmaSong commented on OpenMarket/OpenMarket/Model/ItemRegistrationForm.swift
> +        }
CRUD 중 Create, Update 할 모든 데이터 타입이 이런 변수를 가지고 있어야 하는 건가요?

2021-05-20 14:28 UTC, delmaSong commented on OpenMarket/OpenMarket/Model/ItemRegistrationForm.swift
> +//    }
주석처리된 코드는 아예 제거해주세요. 먼저도 얘기했듯이 커밋 잘하면 다 남아있습니다.

2021-05-20 14:28 UTC, delmaSong commented on OpenMarket/OpenMarket/Network/HttpBodyCreater.swift
> +
HttpBody를 만드는 작업을 별개의 타입에서 하는 건 좋은 아이디어 같아요
다만 `ItemRegistrationForm`에 의존적인데 다른 타입인 경우에도 이렇게 http 바디를 만들려면 어떻게 해야 할까요?
그리고 참고로 말씀드리자면 `creater`는 분화구라는 의미이고 생성자, 창조자라는 의미는 `creator` 입니다

2021-05-20 14:28 UTC, delmaSong commented on OpenMarket/OpenMarket/Network/NetworkHelper.swift
> +        append(string)
`append(string)`에서 `string`이라는 변수의 타입은 `Data`네요. 
그냥 읽었을 때는 혼란을 줄 여지가 있는 것 같아요

2021-05-20 14:28 UTC, delmaSong commented on OpenMarket/OpenMarket/Network/NetworkHelper.swift
> +            completion(.failure(fatalError()))
NetworkHelper 내에서 실패하는 경우 전부 fatalError를 던지는데, 앱이 크래시날 가능성을 내포함에도 불구하고 다른 에러가 아니라 fatalError를 던지도록 만드신 이유가 궁금합니다.

2021-05-21 01:22 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Model/ItemRegistrationForm.swift
> +    }
처음에 설계를 했을 때 상품 등록과 상품 수정을 할 때 여러개의 타입을 사용하지 않고 같은 타입을 사용하려고 했습니다.
상품을 수정할 때는 비밀번호를 제외한 다른 프로퍼티들은 필수가 아니라서 그 프로퍼티가 있을 때만 저장하라는 의도에서 `decodeIfPresent`를 사용했습니다.

2021-05-21 01:32 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Model/ItemRegistrationForm.swift
> +        }
http에서 멀티파트 폼 데이터 형식으로 요청을 보낼 때 body를 만들 때 `multiFormData`는 반드시 필요하다고 생각돼요. 상품을 등록할 때는 모든 프로터피가 다 필요하고 수정을 할때도 비번을 제외한 한가지 이상의 프로퍼티는 꼭 필요합니다!! 만약 사용자가 이미지를 수정하고 싶지 않다고 했을 때는 `imagesDatas`는 꼭 가지고 있을 필요는 없을 것 같아요!

2021-05-21 01:32 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Model/ItemRegistrationForm.swift
> +//    }
앗!!! 푸쉬 올릴 때 주석은 주의 하겠습니다!!
그런데 간단하게 함수나 변수를 설명하는 한줄 주석도 메인에는 푸쉬하지 않는 것이 바람직 한가요?

2021-05-21 01:47 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Network/HttpBodyCreater.swift
> +
저희의 경우에는 모든 요청을 `ItemRegistrationForm`에서 하기 떄문에 내부 프로퍼티로 만들어 주었습니다. 하지만 의존성 주입을 해서 내부가 아닌 생성자나 메소드의 매게변수로 받아서 처리하면 의존성 낮아 질 것 같아요!!

그리고 만약 상품 등록이나 요청을 하는 타입을 모두 가능하게 하고 싶다면 공통된 상위 클래스를 상속 받거나 프로토콜을 채택해서 그 타입을 매개변수를 받게 하면 여러가지 타입인 경우도 처리해 줄 수 있을 것 같아요!!

2021-05-21 01:48 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Network/HttpBodyCreater.swift
> +
오! creator로 수정했습니다!

2021-05-21 02:12 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Network/NetworkHelper.swift
> +        append(string)
stringData로 변경했어요!

2021-05-21 02:21 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Model/ItemInfo.swift
> +struct ItemInfo: Codable {
일단 그냥 Item이라고 한 이유는 프로젝트가 OpenMarket 인데 앞에 또 MarketItem하면 중복이 되는 것 같아서 앞에 단어는 뺴주었습니다. 아니면 단어를 다르게 하는 것이 좋을까요 goods 나 product? ㅎㅎ 델마의 생각은 어떠신가요?

저도 Item만 쓰면 추상 클래스의 느낌이 날 것 같아서 Info를 붙여주었는데.. 또 생각해보면 파일에 대한 상세정보의 느낌도 나네요... 
info 보다 details ? 를 쓰는건 어떻게 생각하세요? ㅎㅎ

2021-05-21 02:26 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Model/ItemRegistrationForm.swift
> +    let password: String
이 부분은 그때 디코에서 설명드렸듯이 상품 등록 수정 모두 한개의 타입에서 처리하기 위해서 이렇게 구현을 했어요!!
상품 등록에는 할인 가격을 제외하고 모두 필요하고 상품 수정시에는 비번만 제외하고는 필수 요소가 아니라서 나머지를 다 옵셔널로 주었습니다!

id는 없는데 무엇을 말씀하시는지 잘모르겠어요 ^^

2021-05-21 02:27 UTC, stevenkim18 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +        XCTAssertEqual(result.items[0].registrationDate, 1620633347.3906322)
이 테스트는 잘못된 테스트라는 것을 델마와의 미팅을 통해서 알았습니다. 네트워크에 의존하지 않는 테스트를 고민해볼게요!

2021-05-21 02:35 UTC, stevenkim18 commented on OpenMarket/OpenMarket/Network/NetworkHelper.swift
> +            completion(.failure(fatalError()))
어... 일단 서버 api통신을 하는 타입 구현하기에 급급했습니다..  
fatalError는 정말 제대로 실패를 하는지 확인하고 싶어서 임시로 넣어두었고 
추후에Error 타입을 따로 만들어서 구현하려고 했습니다!

2021-05-21 11:45 UTC, stevenkim18 commented
@delmaSong 델마!! 오전에 말하신대로 mock객체를 만들어 보았습니다.
`MockURLSession`과 `MockURLSessionDataTask` 를 만들어서 네크워크에 의존하지 않는 테스트를 해봤어요!!
일단 오늘이 지나면 또 주말로 넘어가서 오늘까지 한 부분을 푸쉬해두었습니다!! 같이 확인해주시면 감사할게요! :) (아직 완벽한 코드는 아니에요 ㅜㅜ)

2021-05-22 03:11 UTC, delmaSong commented on OpenMarket/OpenMarket/Model/ItemRegistrationForm.swift
> +    let password: String
응답받을 때 id값도 받지 않나요? 그 얘기였습니다 ㅎㅎ

2021-05-22 03:13 UTC, delmaSong commented on OpenMarket/OpenMarket/Model/ItemInfo.swift
> +struct ItemInfo: Codable {
훨씬 좋네요 ㅎㅎ 마켓에서 상품을 파는거니까 Goods나 Product 의미가 담기면 좋을 것 같아요 ㅎㅎ 수지랑 같이 고민해보시고 결정하시면 될듯요!

2021-05-22 03:15 UTC, delmaSong commented on OpenMarket/OpenMarket/Model/ItemRegistrationForm.swift
> +        }
그렇다면 Create, Update가 필요한 타입을 프로토콜로 추상화 할 수도 있겠군요

2021-05-22 03:17 UTC, delmaSong commented on OpenMarket/OpenMarket/Model/ItemRegistrationForm.swift
> +//    }
되도록 이해하기 쉽게 변수 이름이나 메서드 등을 작성하는 것이 가장 좋겠으나, 동작을 설명하기 위한 주석이 필요한 경우도 있으니 때에 따라 다를 것 같아요. 하지만 위와같은 코드 주석은 사용하지 않을땐 제거해주세요!

2021-05-25 11:26 UTC, stevenkim18 commented
@delmaSong 

## 구현한 부분
### Error 타입을 구현했습니다!
### MockURLProtocol을 만들어서 네트워크에 의존하지 않는 테스트를 했습니다
- 상품목록 조회와 상품 목록 조회는 주어진 mock json을 방식으로 테스트 했습니다.
- 상품 등록은 가짜 URLProtocol로 들어온 request에서 httpbody를 비교하려고 했으나 실패하고 잘 들어왔다는 가정을 하고 저희가 만든 임의 json 데이터를 응답으로 주어서 테스를 했습니다.
- 상품 수정, 삭제는 상품 등록과 같은 맥락이라서 생략하였습니다.
### 모델의 네이밍을 모두 product로 바꿔주었습니다.

2021-05-26 12:41 UTC, delmaSong approved these changes
오랜 시간동안 수고 많으셨어요!!
네트워크 요청 객체와 의존성을 덜어낸 테스트 코드가 인상적이었습니다!
아래 코멘트는 참고해주시고 스텝2에서 반영해주세요~!
수고하셨습니다 👏🏼👏🏼

2021-05-26 12:41 UTC, delmaSong commented on OpenMarket/OpenMarketTests/MockURLProtocol.swift
> +
에러를 받고있는데 사용하지 않고있네요~ 적절한 처리가 추가되거나 사용하지 않는 변수면 아예 지우는 게 어떨까요

2021-05-26 12:41 UTC, delmaSong commented on OpenMarket/OpenMarketTests/MockURLProtocol.swift
> +            fatalError("Handler is unavailable.")
다른 에러 처리 방법을 고려해주세요~

2021-05-26 12:41 UTC, delmaSong commented on OpenMarket/OpenMarketTests/NetworkHelperTest.swift
> +        let idNum = 43
매번 메서드에서 NetworkHelper를 생성해주고있네요
setUp()과 tearDown()에 대해 알아보셔요

2021-05-26 12:42 UTC, merged