오픈마켓 [Step2] Kyo, LJ
yagom-academy/ios-open-market pull request #220
Opened 2022-11-24 08:46 UTC by KyoPak

@Monsteel
안녕하세요 토니!
Kyo(@KyoPak)와 LJ(@lj-7-77)가 Step2의 구현 후 PR 작성해보았습니다! 
생각보다 구현내용이 어렵고 로직적으로 생각할 내용이 많아 PR이 많이 늦어졌습니다..!
이번에 `ModernCollectionView`를 사용해보려 했지만 기본 `CollectionView` 를 먼저 경험해보고 싶어 `ModernCollectionView`는 추후 Refactoring과제로 남겨두었습니다!
토니의 좋은 코멘트 부탁드립니다 :) 

## ✓ 진행단계 : Step-2

## 📝 STEP 진행 중 경험하고 배운 것

- 컬렉션 뷰
☑️Collection View의 활용
☑️커스텀 셀 구현 (List, Grid)

- 이미지 비동기 처리
☑️이미지 비동기로 처리
☑️이미지 표시할 때 raceCondition 해결

- 캐싱
☑️ 이미지 로컬에 캐싱 (NSCache)

---
## ⚒️ 코드 주요 구현내용 

### `MainViewController`, `MainView`, `ListCollectionViewCell`, `GridCollectionViewCell`

<details>
<summary>Details</summary>
<div markdown="1">

- MainView
    - `segmentedControl`과 `listLayout`, `gridLayout`, `collectionLayout`이 있는 view입니다.
    - segmentedControl에서 `List`와 `Grid`를 누를 때 마다, `layoutStatus`라는 property Observer을 사용하여 필요한 메서드가 호출될수 있도록 구현하였습니다.
    - `collectionViewLayout`이 변경되는 `changeLayout()` 메서드가 호출되게 끔 구현하였습니다. 그리고 `collectionView`가 `reload`되게끔 하였습니다.
- ListCollectionViewCell
    - List Layout을 구성할 CollectionViewCell 내부 요소와 오토레이아웃을 구현하였습니다.
- GridCollectionViewCell
    - Grid Layout을 구성할 CollectionViewCell 내부 요소와 오토레이아웃을 구현하였습니다. 
- AddViewController, AddProductView
    - `UIBarButtonItem`인 `+`버튼을 눌렀을 때 전환될 다음 뷰(`AddProductView`)를 담당하는 뷰컨트롤러입니다.
- ImageCacheManager
    - 이미지캐싱을 위한 클래스 타입입니다.
- UILabel+Extension
    - 할인 전 가격에 취소선을 표시해주는 메서드 `applyStrikeThroughStyle`를 구현해주었습니다.
    
</div>
</details>

---
## 🤔 고민 

### 1️⃣ 이미지 표현시 사진이 연속적으로 바뀌는 이슈
- 가장 처음에 구현을 하였을때 아래와 같이 구현을 하였고, 이미지 스크롤을 빠르게 내리고 멈추었을 경우 이미지가 바뀌는 오류가 있었습니다.

```swift
DispatchQueue.main.async { [weak self] in
    if indexPath == collectionView.indexPath(for: cell) {
        guard let data = self?.productData[indexPath.item] else { return }
            cell.setupData(with: data)
    }
}
```

- `setupData()` 내부에서 또 비동기로 이미지를 서버에서 다운받은 후, `imageView`에 image를 넣어주는 로직이었습니다. 
- 이런 로직은 스크롤을 빠르게 내린 후 멈추었을 때, main Thread에 쌓인 (image를 넣어주는) Task들이 실행되기 때문에 이미지들이 계속 바뀌었습니다.

- 그래서 이미지을 받아오는 `fetchImage()`라는 메서드를 `NetworkManager`에 새롭게 구현하였습니다.
- 그리고 이미지가 모두 받아져오면 completionHandler로 image를 전달해주었습니다.

```swift
// NetworkManager
func fetchImage(with stringURL: String, completionHandler: @escaping (UIImage) -> Void) {
    guard let imageURL = URL(string: stringURL) else { return }
        
    DispatchQueue.global().async {
        guard let data = try? Data(contentsOf: imageURL),
            let image = UIImage(data: data) else { return }
            
        completionHandler(image)
    }
}
```

```swift
// MainViewController
networkManager.fetchImage(with: data.thumbnail) { image in
    DispatchQueue.main.async {
        if indexPath == collectionView.indexPath(for: cell) {
            productImageView.image = image
        }
    }
}
```

- 이미지를 바꾸기 직전에 `indexPath`와 현재 `collectionView`의 indexPath와 비교하여 이미지를 넣어주었습니다.
- 이렇게 한다면 스크롤을 빠르게 내렸을때 여러 이미지들이 로드되는 동작 자체를 없앨 수는 없지만 이미지가 올라온 후에 이미지가 다시 바뀌는 오류를 해결할 수 있었습니다. 

### 2️⃣ Indicator View의 사용

- 사용자에게 이미지가 로드되는 시간동안 비어있는 이미지를 보여주지 않기 위해서 사용하였습니다.
- 가장 먼저 `Indicator View`를 `productImageView`와 동일한 위치에 위치시켰습니다.
- 그리고 `productImageView`에 서버에서 가져온 image를 주입하는 시점에서 indicator을 hidden시켰습니다.

- `collectionView(collectionView:, cellForItemAt indexPath:)` 메서드에서 데이터를 받아오는 `setupData()`메서드 실행 전에 `startAnimating()`을 호출하였습니다.
- 이미지 업로드하는 `uploadImage()`메서드에서 `productImageView`에 `image`를 담은 후 `stopAnimating()`으로 멈추도록 구현하였습니다.

### 3️⃣ 만약 할인을 하는 경우 Label이 추가되는 상황

| 할인가격Label 추가 | 정가 판매 |
| :--------: | :--------: | 
|![](https://i.imgur.com/y71yJPq.png) | ![](https://i.imgur.com/VTfQGL3.png)    |

- 위의 그림과 같이 할인하는 경우 할인된 가격`Label`을 추가해야했습니다.
- 처음의 방법은 할인률이 존재한다면 할인된 가격`Label`을 `addSubView` 하고, `prepareForReuse()`에서 해당 할인 가격 Label을 remove해주는 방식으로 구현을 했습니다. 
- 하지만 이렇게 `Cell` 마다 `View`를 그려주고 `remove` 해준다면 상당한 리소스가 요구될 것이고 앱의 동작에 부담이 갈것이라고 생각하고 다른 방안을 생각했습니다. <br> </br>

- 해당 뷰를 `Hidden`처리하는 방식을 선택했습니다.
- 아래 처럼 할인률이 없는 경우는 할인가격을 `Hidden`처리하고 그렇지 않은 경우은 그대로 할인 `Label`을 보여주도록 하였습니다.
```swift
private func setupPriceLabel() {
    if discountPrice == Double.zero {
        productSalePriceLabel.isHidden = true
    } else {
    ...    
}
    
private func clearPriceLabel() {
    productPriceLabel.isHidden = false
    productPriceLabel.textColor = .gray
    productPriceLabel.attributedText = .none
}
```

---
## ❓ 조언을 얻고 싶은 부분
### 1️⃣ NSCache 범용적인 사용 위치

- NSCache의 `object(forKey:)` 메서드와 `setObject(image, forKey:)` 메서드를 `MainViewController`에서 호출하였습니다.
- 추후에 `Cache` 관련 메서드들을 NetworkManager의 `FetchImage()`라는 이미지를 받아오는 부분에서 호출되어도 좋을 것 같다는 생각이 들었습니다.
- 보통 `Cache`관련된 메서드들은 Network 관련 메서드 내부에 위치시키는지 혹은 데이터를 주입해주는 메서드에 위치시키는지 궁금합니다!!
 

### 2️⃣ List 구현시 오토레이아웃 이슈...

- List와 유사한 Custom Cell을 구현했을때 내부의 요소들을 StackView로 묶어주었습니다.
- 그리고 오토레이아웃을 설정하였는데 작은화면이나 상품의 제목, 상품의 가격, 재고 Label의 text가 길어지면 잘리거나 가격이 아예 보이지 않는 현상이 있습니다..
- 빠른 시일내에 List는 `Custom Cell`이 아닌 `UICollectionViewListCell`로 Refactoring하여 기본적으로 구현되어있는 오토레이아웃과 UIComponent들을 쓸 계획이지만 이런 상황에서는 실무였다면 기획자와 이야기를 해봐야할 것같다고 생각이 들지만 토니라면 어떻게 해결을 해야하는지..? 정답은 `UICollectionViewListCell` 밖에 없는지? 궁금합니다!

2022-11-25 05:40 UTC, Monsteel requested changes
안녕하세요 Kyo, LJ :) 
이번 step2도 수고 많으셨습니다 👍 

이번에도 두분모두 역시 깔끔한, 이유있는 코드를 작성해주신것 같아 크게 드리고싶은 피드백은 없고 간단한 코멘트 하나정도만 남겼습니다! 답변 부탁드려요! 👍 
고민하신 부분을 잘 남겨주셔서 코드랑 함께 생각의 흐름을 따라 리딩하기 좋았습니다 👍 

아래에 조언을 얻고싶은 부분에 대한 제 생각을 남겨볼게요!
==

>### 1️⃣ NSCache 범용적인 사용 위치
>
>- NSCache의 `object(forKey:)` 메서드와 `setObject(image, forKey:)` 메서드를 >`MainViewController`에서 호출하였습니다.
>- 추후에 `Cache` 관련 메서드들을 NetworkManager의 `FetchImage()`라는 이미지를 받아오는 부분에서 호출되어도 좋을 것 같다는 생각이 들었습니다.
>- 보통 `Cache`관련된 메서드들은 Network 관련 메서드 내부에 위치시키는지 혹은 데이터를 주입해주는 메서드에 위치시키는지 궁금합니다!!

해당 상황에서 전자의 방법보다는 후자의 방법을 택하게 될 것 같아요 👍 
요청했을 때 똑같은 작동을 보장자히 못하는 형태,
사용부(View단)에서 주요한 로직을 작성하는 방향을 지양하기 때문입니다.

그러면, fetchImage() 라는 함수가 한가지의 역할이 아닌 두가지의 역할을 하는것이 아닌가? 라는 의문이 들 수 있는데요, [Repository Pattern](https://4z7l.github.io/2020/11/24/repository-pattern.html) 이라는 개념을 잘 찾아보시면 도움이 되지 않을까 싶네요 👍 

좀 찾아보고 간결하게 설명된 링크를 걸긴 했습니다만.. 잘 이해가 되지 않는다면 링크보다는 개념에 집중하시면 도움이 될 것 같네요!

>### 2️⃣ List 구현시 오토레이아웃 이슈...
>
>- List와 유사한 Custom Cell을 구현했을때 내부의 요소들을 StackView로 묶어주었습니다.
>- 그리고 오토레이아웃을 설정하였는데 작은화면이나 상품의 제목, 상품의 가격, 재고 Label의 text가 길어지면 잘리거나 가격이 아예 보이지 않는 현상이 있습니다..
>- 빠른 시일내에 List는 `Custom Cell`이 아닌 `UICollectionViewListCell`로 Refactoring하여 기본적으로 구현되어있는 오토레이아웃과 UIComponent들을 쓸 계획이지만 이런 상황에서는 실무였다면 기획자와 이야기를 해봐야할 것같다고 생각이 들지만 토니라면 어떻게 해결을 해야하는지..? 정답은 `UICollectionViewListCell` 밖에 없는지? 궁금합니다!

정확하게 질문을 이해한건지 잘 모르겠지만, 답변을 남겨보면,
StackView로 묶어준 각 요소들의 너비를 지정해주거나, 감싼 StackView에 좌우 anchor를 설정해주면 
정해진 범위 내에서 Stackview가 위치를 잡을 수 있도록 제약을 설정해주는 방향으로 해결할 수 있을듯 한데,
정확한 상황을 알지 못해서 확인이 어렵네요 😭

==

추가로 더 궁금하신 부분이 있으시면 언제든 코멘트 Or 디코 부탁드립니다 ✨

2022-11-25 05:40 UTC, Monsteel commented on OpenMarket/OpenMarket/Common/Protocol/ReuseIdentifierProtocol+Extension.swift
> +extension ReuseIdentifierProtocol {
`ReuseIdentifierProtocol`로 분리하여 `reuseIdentifier`를 선언하셨네요! 
멋진 방향인것 같아요! ✌️

2022-11-25 05:40 UTC, Monsteel commented on OpenMarket/OpenMarket/Network/NetworkRequest.swift
> +                                                                  value: String(1000))
어떤 이유에서 100 -> 1000으로 변경하셨나요?! 👀

2022-11-27 13:48 UTC, KyoPak commented on OpenMarket/OpenMarket/Network/NetworkRequest.swift
> +                                                                  value: String(1000))
스크롤을 내릴때 데이터를 더 받아오기 위해 일단 1000이라고 명시를 해놓았는데 
해당 부분은 자동으로 저 값이 바뀌게끔 변경할 예정입니다!!

2022-11-28 06:29 UTC, Monsteel approved these changes
수고많으셨습니다 :) 이어서 다음 스텝 진행 부탁드려요 🙇🏻‍♂️🙇🏻‍♂️

2022-11-28 06:29 UTC, merged