오픈마켓 [STEP 2] inho, Hamo, Jeremy
yagom-academy/ios-open-market pull request #222
Opened 2022-11-24 13:23 UTC by yjjem

@GREENOVER
안녕하세요 그린!
Step2 PR드립니다.
잘부탁드립니다 🙇🏼‍♂️🙇🏼‍♂️🙇‍♂️

## 📝 STEP 진행 중 경험하고 배운 것

☑️ Safe Area을 고려한 오토 레이아웃 구현
☑️ Mordern Collection View 활용
☑️ Diffable Datasource 활용
☑️ Segmented Control 활용
☑️ Composition Layout Configuration

## ⚒️ 코드 구현내용
### 1️⃣ UICollectionViewCompositionalLayout
- 컬렉션뷰의 레이아웃을 구성할때, `CompositionLayout`객체를 이용하여 구현했습니다.
- 리스트 형식에 `ListConfiguration`와 그리드 형식에 `CompositionalLayout`과 섹션을 이용해서 구현하였습니다.

### 2️⃣ ListCell & GridCell
- ListCell은 `UICollectionViewListCell`을 상속받아 `UIListContentView`에서 제공하는 기본 셀 타입의 구성을 이용합니다.
- GridCell은 커스텀 셀로 필요한 뷰들을 요구사항과 일치하게 구성합니다.

### 3️⃣ UICollectionView.CellRegistration
- `CellRegistration`을 이용하여 컬렉션뷰에 셀을 등록하고, 각 셀을 구성하는 역할을 수행합니다. 제네릭타입으로 전달한 셀과 데이터 타입으로 셀을 구성하고, `registration`핸들러에서 셀의 프로퍼티에 값을 지정합니다.

### 4️⃣ UICollectionViewDiffableDataSource
- 컬렉션뷰의 데이터 소스 객체로는 `DiffableDataSource`를 이용하였습니다.

## 💭 고민한 부분
### 1️⃣ 모던 컬렉션뷰를 이용한 컬렉션뷰 구현
- 컬렉션 뷰를 구현할때, `flowLayout`과 `dataSource` 대신, `composableLayout`과 `diffableDataSource`를 이용해서 구현하였습니다. 
- `snapshot`은 뷰의 데이터의 특정 시점의 상태를 나타낸다 섹션별로 나누어서 원하는 섹션과 아이템으로 구성하고, `dataSource`의 `apply`메서드를 이용하여 `snapshot`의 데이터를 현재 `state`와 새 state를 비교하여 업데이트합니다.
- 애플의 `Implementing Modern Collection Views`를 기반으로 `Customize List Cells`를 구현하려했습니다. 
- 이때 `custom`한 `state`를 만들어서 이용하였는데 이번 프로젝트에서는 셀에서 선택, 하이라이트, 이동 등의 상태에 따른 변경이 없어서 `custom state`를 사용할 필요성이 없다고 생각하여 제외하였습니다.

### 2️⃣ `UICollectionViewListCell`의 크기를 커스텀으로 지정하는 방법
```swift
let configure = UICollectionLayoutListConfiguration(appearance: .plain)
let layout = UICollectionViewCompositionalLayout.list(using: configure)
```
`list`형태의 `collectionView`를 `cell`이 기본적으로 제공하는 레이아웃을 이용하여 위 코드처럼 간편하게 만들었습니다.
그런데 셀이 `self-sizing`을 하여서 클릭되었을 때 의도치 않게 높이가 늘어나는 문제가 발생했습니다.
이를 셀이 레아이웃에 전달되기 전에 수동으로 크기를 조절할 수 있도록 하는`preferredLayoutAttributesFitting()` 메서드를 이용해서 커스텀한 `cell size`를 정해주어 해결하였습니다.

### 3️⃣ 세그먼트 컨트롤을 이용하여 화면전환시 컬렉션뷰가 중첩되는 문제
|<img src="https://i.imgur.com/orXxNVB.jpg" width=600>|
|--|
- 세그먼트 컨트롤의 값에 따라 `grid` 레이아웃, `list` 레이아웃을 가지는 컬렉션 뷰를 다시 그려서 `viewController의` `root view`에 `addSubview`하여 화면이 전환되도록 구현했습니다.
- 이때 기존에 있던 `collectionView`가 사라지지 않고 중첩되는 문제가 있었습니다.
- `productCollectionView` 변수에 새로운 `collectionView`를 할당하기 때문에 참조가 사라져서 `deinit`될거라 생각했는데 `UIView의` `addSubView`를 사용하면 추가한 뷰를 강하게 참조하여서 `deinit`되지 않는다는 점을 확인하고, 자신을 상위 뷰로부터 해제하는 `removeFromSuperview()` 메서드를 사용하여 해결하였습니다.

### 4️⃣ 셀을 빠르게 스크롤했을때 셀의 데이터와 일치하지 않는 이미지가 로드되는 문제
- 네트워킹을 통해서 셀의 이미지를 서버에서 가져오는데 빠르게 스크롤했을 때 셀의 이미지가 여러번 바뀌는 문제가 있었습니다.
- 셀이 재사용될 때마다 이미지를 가져오는 작업이 생성되고 여러개의 작업들이 끝날때마다 셀의 이미지를 바꾸기 때문에 발생하는 문제였습니다.
- 네트워킹 작업을 생성하는 시점의 `indexPath`와 현재 `cell`의 `indexPath`를 비교하여 두 값이 같은 경우에만 이미지를 변경하여 해결하였습니다.
```swift
if indexPath == self.productCollectionView.indexPath(for: cell) {
    cell.imageView.image = image
}
```

## ❓ 조언을 얻고 싶은 부분
### 1️⃣ `ViewController`의 역할에 대한 고민
`MVC`패턴에만 국한된 개념은 아니라고 생각하지만 `MVC`를 예로 들어보겠습니다.
`🧵실`로 표현해보자면 `MVC`에서`Model`과 `View`는 실을 만드는 녀석들이고 `Controller`는 그 실들이 이어지도록 묶는 역할이라고 생각합니다. 

즉 로직은 최대한 줄이고 `View`와 `Model`을 합쳐주기만 해야되고 ViewController가 데이터를 직접적으로 가지는 것이 아니고 따로 저장하는 객체가 있어야한다고 생각합니다. 현재 프로젝트에는 이 부분이 적용되어있지 않습니다.

그린의  `ViewController` 역할에 대한 견해와 아래의 예시처럼 진행하는 것은 올바른 방향성을 가졌는지 궁금합니다.

`예시` 
**`ViewController` 내부 메소드**
- `createGridCellRegistration()`
- `createListCellRegistration()`

위의 두 함수들은 `ViewController`에서 너무 많은 자리를 차지하는 것 같아서 `Registration` 객체를 생성하여 분리해볼 수 있을 것 같습니다. 

```swift
struct Registration {
    let gridCellRegistration: UICollectionView.CellRegistration<GridCell, ProductData>
    let listCellRegistration: UICollectionView.CellRegistration<ListCell, ProductData>
    ...
    
    func createGridCellRegistration() { ... }
    
    func createListCellRegistration() { ... }
}
```
- 비슷하게, `ListCell`과 `GridCell`을 구성할때, 위의 두 메서드 내에서 셀을 구성하도록 구현했습니다. `Cell`타입에 자신의 뷰를 구성하는 메서드를 만들고, 뷰컨트롤러에서는 해당 메서드에 필요한 데이터를 전달하여 `cell`이 직접 뷰를 구성하게 할수도 있었지만, **뷰는 데이터를 알 필요가 없다**는 관점으로 뷰 컨트롤러에서 직접 셀을 구성하고 있습니다. 

### 2️⃣ 애플이 제공하는 `UICollectionLayoutListConfiguration`
이번 프로젝트에서 애플이 제공하는 `UICollectionViewLayoutListConfiguration`을 사용하였을 때 기본적으로 있는 뷰들을 사용하는 것은 편하지만 다른 뷰들을 추가해주려할 때 힘들었습니다. 
이번에는 공부하는 목적으로 기본 리스트셀을 고수했는데 실제로 앱을 만들때에는 기본 셀 구성보단 커스텀 셀 형식을 이용하게 될것이라 생각에 확신이 없었습니다. 애플이 제공하는 기본셀의 사용 방향성에 대한 그린의 의견이 궁금합니다.

2022-11-25 01:37 UTC, GREENOVER requested changes
@inho-98 @lxodud @yjjem 
안녕하세요 여러분!
이번 스텝도 역시나 아주 가독성 좋고 잘 구현해주셨네요ㅎㅎ
너무 고생 많으셨어요🥳🥳🥳
전체적으로 스텝에서 요구하는 기능도 충실히 이행되었고 코드 자체도 깔끔해서 리뷰하기 아주 수월했습니다.
그렇기에 조금 더 디테일한 부분이나 보완되면 좋을 부분 그리고 여러분들의 적절하게 사용된 코드에 대해 선택 기준 혹은 사용 이유들에 대한 질문을 리뷰로 남겨보았습니다!
***
### 칭찬 드리고 싶은 부분
- 코드 가독성이 매우 뛰어나요 💯
- Diffable Datasource에 대해 잘 학습이 되어 snapshot, apply등의 개념을 이해하고 사용하였다고 보입니다 💯
- 코드로 뷰를 그리는것은 이제 여러분들에게 아무것도 아닌것 같네요 💯
- 전체적으로 코드의 관심사 분리를 잘 가져가려고 하시는 흔적들이 보입니다 💯
***
### 조언을 얻고싶으신 부분에 대한 저의 의견
1. ViewController의 역할에 대한 고민
- 첨언을 크게 드릴 부분이 없을만큼 MVC에서 C의 역할과 적절하게 사용할 수 있는 더 나은 방향에 대한 이해를 기본적으로 잘 하고 계신것 같고 생각하고 구현해주신 분리의 기준들이 명확하고 적절하다고 생각합니다.
MVC에서 사실 완전한 분리가 어려운것이 사실이지만, (C에서 결국 너무 많은 일을 하게 되고 비대해지기에 MVVM을 도입하게 되는 등의 단점..) MVC를 여러분들이 사용함에 있어 이런 고민을 가지고 있다는것만으로도 최곤데 그걸 가지고 의견을 도출하신것에 대해 더 최고네요!
결론적으로는 저도 말씀하신 C가 가져야할 방향에 대해 여러분들의 의견에 동의합니다👍
2. 애플이 제공하는 UICollectionLayoutListConfiguration
- 아하 이 부분은 정말 답은 없지만 애플의 기본 방향성을 따르는것도 중요하지만 프로덕트의 디자인 요구사항을 따르는것이 더 중요하다고 생각해요.
그게 당연히 HIG에 어긋나지 않도록 하는 부분에 있어서는 다른 부서 동료들과 협업 시 논의가 되어야 하지만 개발 구현에서 애플이 제공하는 기본적인것을 따르는것은 편의를 위함이 아닐까 싶습니다.
실제 협업에서는 커스텀한 구성이 훨씬 많기에 기본적인 제공만으로는 하기 힘들거에요😭
그렇기에 정리하자면 어떤 프로덕트의 디자인을 구현해야되는지 파악하고 이에 맞게 기본셀 제공되는 API로만 가능하다면 사용하면 좋고 아니라면 커스텀하게 입맛대로 구성하는게 좋아보입니다.
그런데 기본적으로 구성을 한다해도 추후 유지보수 시에는 차라리 커스텀하게 만드는게 더 나중 공수를 줄일 수 있을것 같아요.
***
### 사용성에서 보완되었으면 좋을것 같은 부분
- 유저 입장에서 보완되면 좋을 사용성에 대해서는 리뷰에도 남겨두었지만 요 코멘트에서 하나 말씀드리고 싶습니다🙋🏻
![버튼 탭](https://user-images.githubusercontent.com/72292617/203883113-5585d18b-861d-4167-8281-9e41aadd355f.png)
위 캡쳐와 같이 리스트 셀을 클릭 시 변경되는 셀 색상이 클릭 이후에도 돌아오지 않습니다.
요 부분은 기본적으로 셀에서 제공되는 메서드를 적용하면 될것 같아요.
지금 스텝에서는 물론 필요없어서 안넣어두셨을것 같은데 추후 스텝에서 놓치지 않게 한번 말씀드립니다!
***
모두 아주 좋은 코드 구현하시느라 고생 많으셨습니다ㅎㅎ
우선 보완되면 좋을 부분도 있어 리퀘스트 드리겠습니다!
언제든 머지 혹은 리뷰 재요청을 해주세요🙌
좋은 하루 되세요🚀

2022-11-25 01:37 UTC, GREENOVER commented on OpenMarket/OpenMarket/ProductRegistrationViewController.swift
> +//  ProductRegistrationViewController.swift
해당 파일이 프로젝트 파일 내에서는 Controller 폴더 내에 위치한것 처럼 보이지만 사실 실제 폴더 구조에서는 OpenMarket내에 있어 보입니다🙋🏻
![파일 폴더](https://user-images.githubusercontent.com/72292617/203877693-13636061-79d5-408b-b284-06f94dc3f38c.png)
파일을 옮기실때 프로젝트 내에서만 옮겨서 파인더에서는 반영되지 않은것 같아 보여요.
추후 동료들이 해당 파일을 컨트롤러로 옮기고 그 커밋을 pull 받으면 기존 파인더에서는 구조가 바뀌지 않아 문제가 생길 수 있어 보입니다🙋🏻
project.pbxproj에는 반영되어도 실제 파인더에서도 동일한 그룹핑이 될 수 있도록 하면 더 좋을것 같습니다~!

2022-11-25 01:37 UTC, GREENOVER commented on OpenMarket/OpenMarket/Assets.xcassets/loading.imageset/Contents.json
> +      "filename" : "loading.jpeg",
로딩 이미지를 jpeg로 사용하신 이유가 궁금합니다🙋🏻
현재 배수별로는 특별히 지정되있지 않은데 해상도별 문제는 없을까요?
SVG라는 이미지 형식과 jpeg, jpg 등은 어떤 차이가 있는지 학습해보시면 현업에서 도움이 많이 되실것 같아요😄

2022-11-25 01:37 UTC, GREENOVER commented on OpenMarket/OpenMarket/View/ListCell.swift
> +        layoutIfNeeded()
해당 코드가 실제로 어떤 역할을 해주는지 궁금합니다🙋🏻
해당 구문에 setNeedsLayout 메서드로 갈아끼면 어떤 차이가 있나요~?
혹은 실제로 해당 코드가 없을때 뷰를 제대로 그려주지 못하거나 문제가 발생하는건가요🙋🏻

2022-11-25 01:37 UTC, GREENOVER commented on OpenMarket/OpenMarket/View/GridCell.swift
> +    }
해당 메서드가 실제 현재 프로젝트에서 어떤 역할을 해주나요?
없을때와 실제 뷰가 나타나고 그려지는 동작의 차이가 있는건지 궁금해요🙋🏻

2022-11-25 01:37 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +final class ViewController: UIViewController {
어떤 역할의 VC인지 조금 더 명확한 네이밍이면 좋을것 같아요🙋🏻
추후 VC가 많아진다면 레거시가 되어 고쳐야할 확률이 높을것 같습니다.

2022-11-25 01:37 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +    }
해당 코드가 필요한 이유는 어떤걸까요?🙋🏻

2022-11-25 01:37 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +    private enum ViewType: Int {
Int를 채택해주신 이유가 있을까요?

2022-11-25 01:37 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +        loadProductData(pageNumber: 1, itemsPerPage: 100)
상품은 고정적으로 100개만 받아오게끔 되는것 같은데 더 많이 받아올 수 있도록 스크롤 시 혹은 스크롤 최하단으로 갔을때 등 적절한 페이지네이션 적용 등 로직 추가가 있어야 되지 않을까 싶습니다🙋🏻

2022-11-25 01:37 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +    private func configureLayout(of type: ViewType) -> UICollectionViewCompositionalLayout {
코드에 영향은 없지만 여러분들은 메서드끼리의 순서는 어떻게 구성하시나요?🙋🏻
configureProductCollectionView 메서드에서 configureLayout 메서드를 호출하는데 있어 여기서는 configureLayout의 코드가 상단에 위치하고 다른 부분에서는 역전되는 곳도 있어서 여쭤봅니다..!

2022-11-25 01:37 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +        dataSource = UICollectionViewDiffableDataSource<Section, ProductData>(collectionView: productCollectionView) {
Diffable DataSource가 가진 특징 혹은 장점을 한마디로 정의해보신다면 무엇이였나요?

2022-11-25 01:37 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +                    print(error)
스텝 요구사항에는 없지만 조금 더 의미있는 에러 처리를 해보면 어떨까요?
사용자에게 어떤 방식이든 노티를 줄 수 있고 다시 이미지를 불러오도록 처리하면 좋을것 같다고 생각합니다🙋🏻

2022-11-25 01:37 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +    private func createListCellRegistration() -> UICollectionView.CellRegistration<ListCell, ProductData> {
전체적으로 list > grid로 코드들이 작성되고 있었는데 요 부분에서는 해당 메서드가 createGridCellRegistration 메서드보다 뒤에 작성되는것이 통일성을 조금 해치는 느낌이 드는데 맞춰주면 어떨까요🤔

2022-11-25 01:37 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +                    print(error)
grid에서와 마찬가지로 유의미한 에러 처리가 되면 좋을것 같아요~!

2022-11-25 01:37 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +extension ViewController {
액션 메서드들을 extension으로 관심사를 분리해 가독성을 높인점 아주아주 좋네요!
코드 가독성 아주 높아요👍

2022-11-25 01:37 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +        let viewController = ProductRegistrationViewController()
상품 등록 화면을 노출시켜줄때 네비게이션 방식이 아닌 모달 방식을 채택하신 여러분들의 이유가 궁금합니다🙋🏻

2022-11-28 12:18 UTC, yjjem commented on OpenMarket/OpenMarket/ProductRegistrationViewController.swift
> +//  ProductRegistrationViewController.swift
수정하였습니다 😃👍

2022-11-28 12:23 UTC, inho-98 commented on OpenMarket/OpenMarket/Assets.xcassets/loading.imageset/Contents.json
> +      "filename" : "loading.jpeg",
이미지 형식으로 jpg, png, svg에 대해 찾아보았습니다!
jpg는 용량이 가볍고, png는 투명도까지 표현할 수 있지만 무겁다는 단점이 있었습니다.
svg는 png보다 가벼우면서 투명도를 가질수 있고, 또 벡터로 그림을 그려서 사진의 비율에 상관없이 해상도 문제가 없는 형식입니다.
그래서 기존의 사진들을 svg로 변환하고 single scale로 적용해주었습니다!

2022-11-28 12:41 UTC, yjjem commented on OpenMarket/OpenMarket/View/ListCell.swift
> +        layoutIfNeeded()
`layoutIfNeeded()`는 다음 레이아웃 업데이트 싸이클을 기다리지 않고 그 즉시 레이아웃을 업데이트 합니다.
`setNeedsLayout()`은 레이아웃이 다음 싸이클에서 업데이트 되도록 해줍니다.
frame의 값이 중간에 변할 일이 없고 맞지않을 일이 없다고 추측했습니다. 그래서 호출할 필요가 없다고 생각합니다.


📎 b28db95

2022-11-28 12:45 UTC, yjjem commented on OpenMarket/OpenMarket/View/GridCell.swift
> +    }
셀의 재사용되는 성질때문에 이전의 이미지가 그대로 보이는 문제가 있었습니다.
재사용전에 이미지에 nil값을 할당해서 재사용되는 시점에 보이지않게 했습니다.

2022-11-28 12:47 UTC, yjjem commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +final class ViewController: UIViewController {
OpenMarketViewController로 수정했습니다 👍 
감사합니다 😇

2022-11-28 12:54 UTC, yjjem commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +    }
스냅샷 객체를 만들 때 제네릭 타입 2개가 `Hashable`을 채택해야 합니다. 
이때 `Int`나 `String` 대신 열거형을 사용해서 가독성을 높이려고 했습니다. 추후에 섹션이 추가될 시 가독성을 유지하면서 확장이 가능하다고 생각합니다.

감사합니다 👍

2022-11-28 12:58 UTC, yjjem commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +    private enum ViewType: Int {
ViewType의 rawValue와 segmentColtrol의 selectedIndex를 비교하려 했습니다.
그러나 사용되지 않아서 삭제했습니다.

📎 d648c9c

2022-11-28 13:13 UTC, yjjem commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +        loadProductData(pageNumber: 1, itemsPerPage: 100)
페이지네이션 구현에 성공하여 잘 돌아가는 것을 확인했습니다.
그러나 DiffableDataSource의 SnapShot에 이미 존재하는 값을 추가하려는 시도가 있다는 오류가 발생했습니다. 이를 찾아보니 서로 다른 페이지에서 같은 아이템을 전달하는 서버의 오류임을 확인했습니다.
> DiffableDataSource 콘솔 오류 화면
![image](https://user-images.githubusercontent.com/88357373/204284651-740130bd-9935-44f3-ada4-96d0aab3927c.png)

아래의 예시에는 서로 다른 페이지이지만 같은 id값의 데이터가 들어가있는 것을 확인할 수 있습니다.
> `왼쪽` - 2 페이지 아이템 20개
> `오른쪽` - 3페이지 아이템 20개
<div>
<img src="https://user-images.githubusercontent.com/88357373/204283987-04f3ab97-8f8c-4b6d-98c3-57b11829b39f.png" height="450px"/>
<img src="https://user-images.githubusercontent.com/88357373/204284204-4ebb4533-bf8b-4229-82cc-71865969ab04.png" height="450px"/>


📎 a8d7fd3
</div>

2022-11-28 13:42 UTC, yjjem commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +    private func configureLayout(of type: ViewType) -> UICollectionViewCompositionalLayout {
현 프로젝트에서는 보통 선언부가 아래에 있는 식으로 구성을 했습니다.
말씀해주신 부분은 빼먹은 것 같네요. 통일시켰습니다.

사실 구성 방식은 개인차가 있는 것 같은데 그린은 보통 어떻게 구성하시나요?

2022-11-28 13:53 UTC, yjjem commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +        dataSource = UICollectionViewDiffableDataSource<Section, ProductData>(collectionView: productCollectionView) {
데이터소스와 달리 컬렉션뷰 `DataSource`와 달리 `DiffableDataSource`를 사용하면 셀 섹션 수 를 메소드 호출을 통해 반환해주지 않고 `SnapShot`을 통해 아이템만 전달해주면 자동으로 설정해줘서 에러를 줄일 수 있습니다.
그리고 데이터 변경에 대한 애니메이션 효과를 추가적인 작업 없이 얻을 수 있습니다.

2022-11-28 13:56 UTC, yjjem commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +                    print(error)
`ErrorManager` 객체를 생성하여 썸네일 로드시 발생하는 에러는 에러 이미지로 대체하고
데이터 로드시 발생하는 에러는 `Alert`를 띄우는 방식으로 처리했습니다.

📎 e634a04

2022-11-28 13:59 UTC, yjjem commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +    private func createListCellRegistration() -> UICollectionView.CellRegistration<ListCell, ProductData> {
이 부분 수정했습니다. 감사합니다 🌱

📎 37eb571

2022-11-28 14:05 UTC, yjjem commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +        let viewController = ProductRegistrationViewController()
해당 부분은 POST를 하는 새로운 흐름이 생성된다고 생각했기 때문에 모달을 사용했습니다.
이후에 구현할 상품 상세화면 같은 경우는 정보의 흐름이 이어지도록 네비게이션 방식으로 구현할 예정입니다! 👍

2022-11-28 14:06 UTC, yjjem commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +                    print(error)
위의 코멘트에서 언급한대로 수정했습니다. 감사합니다. 👍

2022-11-29 02:09 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +    private func configureLayout(of type: ViewType) -> UICollectionViewCompositionalLayout {
아하 통일만 되면 충분히 어떤것이든 좋습니다!
저는 실제 호출되는 순서로 구성합니다.
즉 여러분과 비슷한 구조로 하고 있어요!

2022-11-29 02:13 UTC, GREENOVER commented
@inho-98 @lxodud @yjjem 
리팩토링 하느라 너무 고생 많으셨어요!!
훨씬 더 가독성이 좋은 코드가 되었네요ㅎㅎ
그런데 하나 문제가 있습니다😭
특정 상황에서 탭 전환 시 런타임 에러가 나요ㅠㅠ
예를들어, 빠르게 스크롤을 내리는 도중 탭 전환을 하거나 혹은 맨 아래 스크롤에서 탭 전환을 하면 100% 발생하는것 같네요🥲
이 부분만 확인해보시면 바로 머지하겠습니다~!

2022-11-29 02:43 UTC, inho-98 commented
탭 전환시 생기는 런타임 에러 수정하였습니다!

기존에 코드에서는 탭을 전환할때 `snapshot`에 가지고 있는 `product`를 그대로 보여주는게 아닌 `products`를 한번더 추가한뒤에 `dataSoure`에 적용해서 중복되는 문제가 있었습니다.

그래서 탭 전환시 가지고 있는 상품 리스트를 활용하여 화면을 구성하도록 수정했습니다!


```swift
//기존 코드
@objc private func switchView(_ sender: UISegmentedControl) {
    if sender.selectedSegmentIndex == 0 {
            ...
        }
        snapshot.appendItems(products)
        dataSource.apply(snapshot, animatingDifferences: false)
}

//✅ 수정한 코드
@objc private func switchView(_ sender: UISegmentedControl) {
    if sender.selectedSegmentIndex == 0 {
            ...
        }
        dataSource.apply(snapshot, animatingDifferences: false)
}
```

2022-11-29 02:46 UTC, GREENOVER approved these changes
고생하셨습니다!
스텝 2는 여기서 마무리 지으면 될것 같아요!
다들 스텝3도 화이팅입니다🥳

2022-11-29 02:47 UTC, merged