오픈마켓 [STEP 2] Mangdi, Woong
yagom-academy/ios-open-market pull request #223
Opened 2022-11-24 15:59 UTC by iOS-Woong

@SungPyo  안녕하세요 웨더! 
이번 스텝도 만만치 않네요 ㅎㅎ 구현하는데 꽤나 애먹었습니다..
코드를 보시고 부족한 부분이 보이면 알려주세요!

## 🤔 고민했던 점

- 콜렉션뷰를 List랑 Grid로 어떻게 구현해야하는지에대한 고민
    - 콜렉션뷰를 List전용으로 하나 Grid 전용으로 하나 2개를 만들어줘야하나 고민했었습니다. 그런데 좀 더 고민해보니 데이터만 공유하고 셀만 다르게 해줄수 있을거란 생각이 들었습니다. 데이터를 담당하는 하나의 UICollectionViewCell class를 만들어놓고 List와 Grid 전용 custom셀을 생성해서 class를 적용했습니다. segmentedControl의 index값에 따라 List와 Grid셀을 로드하게 구현했습니다.
    
- 이미지 캐싱하기
    - 처음에 NSCache를 이용해서 각 셀의 이미지를 구현을했었습니다. 그런데 앱을 종료했다 키면 저장된 캐쉬데이터들이 사라져서 실행할때마다 버벅거림을 경험해야했습니다. NSCache는 Memory Cache영역에 저장되기때문에 발생하게 된 문제인데 이를 해결하기 위해 FileManager로 Disk Cache영역에 저장하는 방식으로 바꾸었습니다. Disk Cache 영역은 앱을 종료했다 켜도 지워지지않는 영역이기때문에 처음 의도한대로 구현할수있었습니다.

|처음설치|종료후다시실행|
|:--:|:--:|
|![Simulator Screen Recording - iPhone 11 - 2022-11-25 at 00 57 15](https://user-images.githubusercontent.com/49121469/203825802-c1a9679c-89b2-4506-917c-05cb88236e39.gif)|![Simulator Screen Recording - iPhone 11 - 2022-11-25 at 00 31 56](https://user-images.githubusercontent.com/49121469/203821039-8767d88d-eedb-492c-ab84-47fb8d534190.gif)|

## 🙏 조언을 얻고 싶은 부분

- 컬렉션뷰의 이미지영역에 이미지 캐싱을 적용했을 때, 메모리캐싱, 디스크캐싱 무엇이 더 적합한 방식일까요? 
    - 저희가 채택한 메모리캐싱 방식으로는 셀의 모든 이미지데이터를 Library-Cache 폴더에 저장하는 방식이기 때문에 만약, 셀의 갯수가 현재의 10배~ 이상으로 늘어나게된다면 용량이 엄청나게 커질 것이 우려됩니다. (물론, 자동적으로 일정용량이 넘어가면 삭제를 해준다고하니 앱이 죽어버리진 않겠지만요.) 
    - woong의 생각으로는 당근마켓을 스크롤해서 셀들을 보았다고 그 이미지들을 Library-cache 폴더 내에 모두 저장하지는 않을 것이라고 생각합니다.(용량문제) 저희가 구현한 오픈마켓이 비슷한 구조의 앱이라고 가정했을 때, 컬렉션뷰에서 메모리캐싱을 선택하는게 적절한 것 인지 혹은 디스크캐싱이 적절한 것인지 구현하면서도 고민이 되네요. 어떤 방법으로 보완할 수 있을까요?
    - MemoryCache구현커밋 https://github.com/yagom-academy/ios-open-market/commit/79f455a0cb70efc44f918cadd70a5d43718ebfbd, DiskCache구현커밋 https://github.com/yagom-academy/ios-open-market/commit/7564b74b7450e9c75bd7edbfc1d00112f42e1757

2022-11-25 06:47 UTC, SungPyo commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +    var detailProduct: DetailProduct?
지금 당장 안 쓰는 부분들은 주석이면 좋을 것 같아요.

2022-11-25 06:47 UTC, SungPyo commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +                self.searchListProducts = data
self. 가 어떤 문제가 생길까요? ARC와 관련된 학습을 추천합니다. 중복되는 부분이 많으니 여기에만 적을게요.

2022-11-25 06:47 UTC, SungPyo commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +        collectionView.collectionViewLayout = compositionalLayout
self.가 있는게 있고 없는게 있네요 차이가 뭐죠?

2022-11-25 06:47 UTC, SungPyo commented on OpenMarket/OpenMarket/Model/NetworkCommunication.swift
> +            if let response = response as? HTTPURLResponse {
if let 을 쓰는경우와 guard let 을 쓰는 경우의 본인 기준이 있나요?

2022-11-25 06:47 UTC, SungPyo commented on OpenMarket/OpenMarket/Model/CustomCollectionViewCell.swift
> +                    fileManager.createFile(atPath: filePath.path,
이 부분은 캐시를 하려고 구성한 건가요? 만약 그렇다면 다른 방법은 없을까요? 또는 이대로 사용하면 문제는 없을까요?

2022-11-25 06:55 UTC, SungPyo commented
> @SungPyo 안녕하세요 웨더! 이번 스텝도 만만치 않네요 ㅎㅎ 구현하는데 꽤나 애먹었습니다.. 코드를 보시고 부족한 부분이 보이면 알려주세요!
> 
> ## 🤔 고민했던 점
> * 콜렉션뷰를 List랑 Grid로 어떻게 구현해야하는지에대한 고민
>   
>   * 콜렉션뷰를 List전용으로 하나 Grid 전용으로 하나 2개를 만들어줘야하나 고민했었습니다. 그런데 좀 더 고민해보니 데이터만 공유하고 셀만 다르게 해줄수 있을거란 생각이 들었습니다. 데이터를 담당하는 하나의 UICollectionViewCell class를 만들어놓고 List와 Grid 전용 custom셀을 생성해서 class를 적용했습니다. segmentedControl의 index값에 따라 List와 Grid셀을 로드하게 구현했습니다.
> * 이미지 캐싱하기
>   
>   * 처음에 NSCache를 이용해서 각 셀의 이미지를 구현을했었습니다. 그런데 앱을 종료했다 키면 저장된 캐쉬데이터들이 사라져서 실행할때마다 버벅거림을 경험해야했습니다. NSCache는 Memory Cache영역에 저장되기때문에 발생하게 된 문제인데 이를 해결하기 위해 FileManager로 Disk Cache영역에 저장하는 방식으로 바꾸었습니다. Disk Cache 영역은 앱을 종료했다 켜도 지워지지않는 영역이기때문에 처음 의도한대로 구현할수있었습니다.
> 
> 처음설치	종료후다시실행
> ![Simulator Screen Recording - iPhone 11 - 2022-11-25 at 00 57 15](https://user-images.githubusercontent.com/49121469/203825802-c1a9679c-89b2-4506-917c-05cb88236e39.gif)	![Simulator Screen Recording - iPhone 11 - 2022-11-25 at 00 31 56](https://user-images.githubusercontent.com/49121469/203821039-8767d88d-eedb-492c-ab84-47fb8d534190.gif)
> ## 🙏 조언을 얻고 싶은 부분
> * 컬렉션뷰의 이미지영역에 이미지 캐싱을 적용했을 때, 메모리캐싱, 디스크캐싱 무엇이 더 적합한 방식일까요?
ㄴ `둘 다 하면 안되나요?`
>   
>   * 저희가 채택한 메모리캐싱 방식으로는 셀의 모든 이미지데이터를 Library-Cache 폴더에 저장하는 방식이기 때문에 만약, 셀의 갯수가 현재의 10배~ 이상으로 늘어나게된다면 용량이 엄청나게 커질 것이 우려됩니다. (물론, 자동적으로 일정용량이 넘어가면 삭제를 해준다고하니 앱이 죽어버리진 않겠지만요.)
ㄴ `관련된 내용을 코멘트에 적어놨는데, Cache를 위와같은 방식으로 하는걸 어떻게 찾아보셨나요?`
>   * woong의 생각으로는 당근마켓을 스크롤해서 셀들을 보았다고 그 이미지들을 Library-cache 폴더 내에 모두 저장하지는 않을 것이라고 생각합니다.(용량문제) 저희가 구현한 오픈마켓이 비슷한 구조의 앱이라고 가정했을 때, 컬렉션뷰에서 메모리캐싱을 선택하는게 적절한 것 인지 혹은 디스크캐싱이 적절한 것인지 구현하면서도 고민이 되네요. 어떤 방법으로 보완할 수 있을까요?
ㄴ `둘 다 있어도 상관없습니다. 적절함 부분에서는.. 서비스마다 다르기때문에 무조건 그게 적절하다 할 수가 없겠네요`
>   * MemoryCache구현커밋 [79f455a](https://github.com/yagom-academy/ios-open-market/commit/79f455a0cb70efc44f918cadd70a5d43718ebfbd), DiskCache구현커밋 [7564b74](https://github.com/yagom-academy/ios-open-market/commit/7564b74b7450e9c75bd7edbfc1d00112f42e1757)
ㄴ `이 커밋들은 pr에 없는것 같네요..? 저는 가능하면 현재 코드 상태에 대한 리뷰만 합니다. :) 실제 업무에서도 그렇구요`

고생하셨습니다.

이번에는 추가적으로 필요한 부분이 있는것 같은데요.

일단 빠진 커밋들도 pr에 추가로 넣어주셨으면 좋겠구요. 

질문을 몇개 코멘트에 달아놨는데 그 부분들도 답변 부탁드릴게요 :)

준비가 완료되면 디엠 부탁드리겠습니다.

수고하셨어요.

2022-11-28 06:38 UTC, SungPyo requested changes
댓글 및 수정사항 확인 후 다시한번 DM부탁드릴게요 :)

2022-11-28 09:09 UTC, iOS-Woong commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +    var detailProduct: DetailProduct?
불필요한 프로퍼티 searchListProducts, detailProduct를 제거하였고, 
데이터를 불러오는 메서드 역시 삭제하였습니다.
[85a39df](https://github.com/yagom-academy/ios-open-market/pull/223/commits/85a39df3607fe1a48cb5ff44790e9854a2a24fa4)

2022-11-28 09:30 UTC, MangDi-L commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +                self.searchListProducts = data
클로저 안에 self로 캡처가되면 순환참조가 발생하게되므로 [weak self]를 붙여주어 더이상 RC가 증가하지 않도록 수정하였습니다!
[f6dc1eb](https://github.com/yagom-academy/ios-open-market/pull/223/commits/f6dc1eb2e3a35974837de74db672606662efbf37)

2022-11-28 09:42 UTC, iOS-Woong commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +        collectionView.collectionViewLayout = compositionalLayout
1. 전역변수와 지역변수를 구분해주기 위해 좀 더 정확하게 명시하려는 목적으로 사용하였습니다!
2. 하지만, 해당 함수에서는 전역변수와 지역변수를 구분할 이유가 없습니다 (매개변수로 collectionView가 없음)
3. 그 외에도 전역&지역을 구분 해 줄 필요가 없음에도 self. 를 쓴 부분이 있어서 수정해보았습니다! [4de3a0d](https://github.com/yagom-academy/ios-open-market/pull/223/commits/4de3a0d6a12c9a0404dc26226ae88bb47e087cd6)

2022-11-28 09:51 UTC, MangDi-L commented on OpenMarket/OpenMarket/Model/NetworkCommunication.swift
> +            if let response = response as? HTTPURLResponse {
guard let은 보통 함수내에서 활용하거나 early exit를 통해 간략하게 표현 할 수 있을때 사용을하고
if let은 true랑 false 두가지처리 외에 추가적으로 작성이 필요하지 않다면 사용하는 편입니다.

2022-11-28 10:06 UTC, MangDi-L commented on OpenMarket/OpenMarket/Model/CustomCollectionViewCell.swift
> +                    fileManager.createFile(atPath: filePath.path,
원래는 NSCache로 구현을 했습니다. 그런데 앱을 껏다키면 다시 새롭게 다운로드를 받아야했기때문에
디스크영역을 사용하는 FileManager로 구현했습니다. 더이상 앱을 껏다 킬때마다 다시 다운로드 받는일이 발생하지않았기때문에 이 방식으로 적용해보았습니다. 어플을 지워도 디스크에 데이터가 계속 남아있을지 확인을 해보았는데 어플을 지우면 데이터도 지워지는것을 확인했습니다. 그래서 이 FileManager로 구현하면 발생하는 문제점이 무엇일까 생각이 잘 나지 않습니다 ㅠㅠ

2022-11-30 16:53 UTC, SungPyo commented on OpenMarket/OpenMarket/Model/CustomCollectionViewCell.swift
> +                    fileManager.createFile(atPath: filePath.path,
음.. 어플을 껏다 키면 FileManager에 저장된 데이터가 남아있다는건 어떻게 확인하셨나요?

2022-11-30 17:05 UTC, SungPyo commented
수정사항 확인했습니다.

일단 시간상 오픈마켓 STEP3는 진행하셔야 할 것 같고.

FileManager관련된 부분에 추가 질문을 했는데요.

추가로 답변 부탁드릴게요 :)

머지 시점에 DM 부탁드릴게요. 

고생하셨습니다.

2022-11-30 17:05 UTC, SungPyo approved these changes

2022-12-01 01:22 UTC, iOS-Woong commented on OpenMarket/OpenMarket/Model/CustomCollectionViewCell.swift
> +                    fileManager.createFile(atPath: filePath.path,
```swift
   func configureImage(imageSource: String) {
        let fileManager = FileManager()
        
        guard let path = NSSearchPathForDirectoriesInDomains(.cachesDirectory,
                                                             .userDomainMask,
                                                             true).first else { return }
```
1. createFile 해줄 때, 경로를 cashDirectory 로 해주었습니다.
2. 위의 `path`를 Print 해봤을 때 저장 경로의 위치가  User/Woong/..../Library/Cache 라는 저장경로가 출력되었습니다.
3. terminal을 통해서 cd User/woong.../Library/Cache 로 접근하여 .open을 해주었고,
4. 앱을 켜고 종료했을 때, Library/Cache에 파일이 계속 남아있다는 것을 확인했고, 삭제했을 때 폴더가 완전히 지워진다는 것을 확인하였습니다!

2022-12-02 07:01 UTC, SungPyo commented on OpenMarket/OpenMarket/Model/CustomCollectionViewCell.swift
> +                    fileManager.createFile(atPath: filePath.path,
저장 경로가 변경된다는걸 새벽에 눈으로 직접 확인하셨으니 다음 Step에는 수정될 것 같네요 :)

2022-12-02 07:01 UTC, SungPyo commented
고생했어요 수정할 부분 수정해서 다음 Step에 봬요

2022-12-02 07:01 UTC, merged