오픈마켓 [STEP 2] 애종, 토털이
yagom-academy/ios-open-market pull request #224
Opened 2022-11-25 04:26 UTC by jonghancha

안녕하세요. 올라프(@1Consumption)! modern collectionView가 무엇인지 최선을 다해 이해하려고 노력했습니다. 설명에 혹시 틀린 점이 있다면 알려주시면 정말정말 감사할것같습니다.ㅜ 아무래도 처음 배우는 개념을 설명하다 보니 PR이 좀 길어졌습니다. 참고하실 만한 스크린샷을 첨부하려고 찾아보았지만 마땅치 않아 이렇게 PR 보내드리는 점 양해부탁드립니다!

## 구현내용
![Simulator Screen Recording - iPhone 14 Pro - 2022-11-25 at 13 25 14](https://user-images.githubusercontent.com/73284068/203901041-7b830c28-2484-4adb-8436-534b9c32c6fb.gif)

- segmented control 커스텀 및 화면전환 구현
- 모던 컬렉션 리스트 뷰 구현
- 모던 컬렉션 그리드 뷰 구현
- 이미지 비동기 네트워킹 구현
 
## 고민 된 점
### 1. collection view의 state
configurationState란 셀의 모양에 영향을 미치는 모든 공통 상태(선택됨, 집중 또는 비활성화와 같은 보기 상태 및 편집 또는 스와이프됨과 같은 셀 상태)와 함께 특성 컬렉션을 포함합니다. 
 저희는 `configurationState` 프로퍼티를 통해 state가 product를 가지고 있도록 구현했습니다.
 ```swift
override var configurationState: UICellConfigurationState {
        var state = super.configurationState
        state.productData = self.productData
        return state
    }
```
UICellConfigurationState가 productData를 가지도록 extension을 통해 구현하였고, "product" 키 값을 통해 state의 productData에 접근할 수 있도록 했습니다.
```swift
private extension UIConfigurationStateCustomKey {
    
    static let product = UIConfigurationStateCustomKey("product")
}

private extension UICellConfigurationState {
    
    var productData: Product? {
        set { self[.product] = newValue }
        get { return self[.product] as? Product }
    }
}
```

#### **데이터가 리스트에 데이터가 띄워지는 과정**
1. 뷰 컨트롤러의 `configureDataSource()` 내의 `update(with: product)`를 통해 해당 셀에 보여질 product의 정보를 `ProductListCell.productData` 에게 넘겨줍니다.
```swift
func update(with newProduct: Product) {
        guard productData != newProduct else { return }
        self.productData = newProduct
        setNeedsUpdateConfiguration()
    }
```
2. 프로퍼티에 할당된 `productData`는 위에서 정의한 `configurationState`의 `state.productData`에 할당됩니다.
3. 해당 `state`는 `updateConfiguration(using: -->> State <<--)` 의 매개변수로 전해집니다. 결론적으로 현재 상태의 `productData`를 토대로 cell을 구성해줍니다. 

### 2. modern collection List view 구현 방법
1. `collectionView` View controller 내에 프로퍼티로 선언
2. `CollectionViewListCell` 생성
    2-1. `UIConfigurationStateCustomKey` 생성
    2-2. `UIConfigurationState`를 extension하여 state의 데이터 프로퍼티 생성
    2-3. `ConfigurationState`를 재정의하여 현재 상태의 cell이 가지고 있는 새로운 값을 위 프로퍼티에 넣어줘 `configurationState`을 새롭게 정의해준다.
    2-4. cell에서 사용할 `UIListContentView`를 생성한다.
    2-5. cell내의 Layout을 잡아준다.
    2-6. updateConfiguration(using state: UICellConfigurationState) 재정의하여 만들어준 `UIListContentView`의 configuration을 설정해준다.
3. collectionView의 layout 생성 (`UICollectionViewCompositionalLayout`)
4. 레이아웃 생성하여 collectionView 프로퍼티에 주입
5. dataSource에 CellRegistration, UICollectionViewDiffableDataSource 할당
6. snapshot을 dataSource에 apply
    6-1. 모델에 Hashable 프로토콜 채택

### 3. translateAutoResizingIntoConstraint = false 
왜 코드로 구현시에 이 부분을 false로 지정해 주어야 하는지 의문이 들어 공부해 보았습니다.
`translateAutoResizingIntoConstraint`는 Autoresizing mask를 Auto Layout constarints로 바꿀지 말지를 결정하는 Boolean 값입니다.
autoresizing mask constraints는 뷰의 크기와 위치를 지정해버리기 때문에, 이후에 추가적인 constraints를 추가할 수 없습니다. 그렇기 때문에 constraints를 추가해 주기 위해서는 false로 지정해 주어야 합니다.

### 4. segmented control로 화면 전환 구현

segment가 바뀔 때마다, 기존에 있던 view는 `removeFromSuperview`를 통해 지워준 후, view controller가 프로퍼티로 가지고 있는 datasource와 collectionview 프로퍼티에 새롭게 만들어준 datasource와 colection view를 넣어주었습니다. 그 이후 바뀐 collectionview를 `addSubview`를 통해 넣어주었습니다!

## 궁금한 점
### 1. 커스텀 State를 만들어 준 부분
공식 문서에서 커스텀 List Cell의 경우 State를 만들어 주었기에 저희도 커스텀 State를 만들어 주었습니다. 하지만 State에 대한 완벽한 이해가 되지 않아 State를 왜 커스텀으로 등록하여 추가해 주는지, 이 추가해 주었을 때의 이점이 무엇인지 찾거나 이해하기 힘들었습니다. 조언 부탁드립니다 ㅠㅠ

### 2. cellRegistration에 대한 이해. 
`cellRegistration`에서 커스텀 List Cell의 경우, updateConfiguration을 사용해 주었고, Grid Cell에서는 사용해 주지 않았습니다. 
Grid Cell에서는 `configureCell`에서 직접 데이터를 view의 label 등등에 넣어줍니다. 반면, 커스텀 List Cell에서는 단순히 데이터 만을 update 시켜주는데, 이 데이터를 업데이트 시켜준 뒤 `setNeedsUpdateConfiguration()` 메서드가 불려집니다. 
이 다음에  `updateConfiguration()`메서드를 불러 내는 것이 맞는지. 그리고 그 이후에는 데이터를 집어넣는 작업을 직접 하는 것인지, 단순히 데이터를 넣을 것이라는 설정을 해주고 snapshot과 datasource가 데이터를 넣어주는 것인지 잘 모르겠어 질문을 드립니다.

```swift
let cellRegistration = UICollectionView.CellRegistration<ProductListCell, Product> { (cell, indexPath, product) in
            cell.update(with: product)
            cell.accessories = [.disclosureIndicator()]
        }
```

### 3. self?.productListContentView.configuration = content 와 setNeedsUpdateConfiguration()의 차이
updateConfiguration() 내부에서 이미지를 fetch해온 후 cell에 반영이 되지 않는 문제를 겪었습니다. 이미지 fetch 성공 후 setNeedsUpdateConfiguration()를 호출해 state가 업데이트 되도록 하려고 했으나 실패했습니다.
```swift
override func updateConfiguration(using state: UICellConfigurationState) {
    
        ...
    
        let networkProvider = NetworkAPIProvider()
        networkProvider.fetchImage(url: productData.thumbnail) { result in
            switch result {
            case .failure(_):
                DispatchQueue.main.async { [weak self] in
                    content.image = UIImage(systemName: "xmark.seal.fill")
                    // setNeedsUpdateConfiguration()  실패          
                    self?.productListContentView.configuration = content // 성공
                }
                return
            case .success(let image):
                DispatchQueue.main.async { [weak self] in
                    content.image = image
                    // setNeedsUpdateConfiguration()  실패     
                    self?.productListContentView.configuration = content // 성
                }
            }
        }
        
        productListContentView.configuration = content
    
        ...
    }
```
`setNeedsUpdateConfiguration()`메서드가 실패한 이유는

해당 시점의 `configuration state`를 토대로 update해주는 것이 이 메서드의 역할인데 
해당 시점의 `productListContentView.configuration`은 image가 포함되지 않은 state 이기 때문이라고 생각했습니다.

### 4. snapshot에 대한 이해 

 공식문서에서는 스냅샷을 사용하여 표시되는 데이터의 변경 사항을 반영한다고 쓰여있는데 데이터소스와 스냅샷의 관계가 잘 이해가 되지 않았습니다.

2022-11-25 12:09 UTC, 1Consumption requested changes
고생하셨습니다.

modern collectionView를 사용한 부분이 인상적이네요. 

그런데 아직 cell configuration에 대한 이해도가 부족하다고 생각됩니다. 이는 cell에 어떤 데이터를 넣어줄지를 가지고있는 객체 같습니다. 또한 상태에 따라 달라질 수 있고요. 그런데 이 상태는 애플에서 정한 상태를 따라야하는데,(Highlighted, Selected, Disabled, Focused일 때 어떻게 보여줄 것인가) 이를 따르지 않아서 수많은 불필요한 코드가 생겼다고 생각됩니다. 여기에 이미지를 받아오는 비동기 작업이 추가되어서 더 복잡해졌다고 생각합니다.
따라서 Configuration과 state에 대해 더 공부해보시는걸 추천드립니다.

또한 질문해주신 snapshot과 dataSource의 상관관계에 대해서 제가 아는 내용은 다음과 같습니다.
1. DiffableDataSoruce는 snapshot을 가진다.
2. 이 snapshot은 어떤 UI 요소가 아니라 hash 덩어리이다. 
3. DiffableDataSource에 apply 할 때마다 기존 snapshot과 새로 적용되는 snapshot을 비교해 바뀐 부분만 교체한다.
4. 이때 hash를 기반으로 비교한다.

나머지는 코멘트를 참고해주세요.

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +    var productData: ProductList?
외부에서 알아야하는 프로퍼티인가요?

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +    private var dataSource: UICollectionViewDiffableDataSource<Section, Product>!
강제언래핑을 `꼭` 해야하나요?

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        }
왜 그때그때 매번 생성하나요? 만약 리퀘스트를 취소하고싶은데, 지금 같은 경우라면 어떻게 처리해야하나요?

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        networkProvider.fetchProductList(query: [.itemsPerPage: "200"]) { [weak self] result in
view에서 직접 네트워크 호출을 하지 말고 객체로 한번 더 감싸면 좋겠습니다. view는 이벤트를 보낼 뿐이지 어떤 동작을 하는지를 알면 안된다고 생각해요. 특히 어떤 `query`를 보낼지 아는건 view의 역할이 아니라고 생각해요.

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        self.present(addProductViewController, animated: true, completion: nil)
어디는 self를 붙이고 어디는 안 붙이네요. 특별한 이유가 있나요?

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +extension ProductListViewController {
private을 붙이면 어떨까요? 그리고 이 extension의 의도를 잘 모르겠습니다. 왜 나누신건가요?

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +                                  NSLocalizedString("GRID", comment: "")]
`NSLocalizedString`는 왜 사용하셨나요?

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +    @objc func segControlChanged(segcon: UISegmentedControl) {
private이 빠졌네요.

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        }
index로 접근하지말고 enum으로 관리하면 어떨까요?

```suggestion
eum SegmentItem: Int, CaseIterable {

    case list
    case grid
}

guard let selection = SegmentItem(rawValue: segcon.selectedSegmentIndex) else {
    return
}

switch segmentItem {
~~~
}
```

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +extension ProductListViewController {
저는 이 extension들을 굳이 나눌 필요가 없다고 생각해요. 오히려 가독성을 해치는거 같습니다.

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +    }
메소드 이름에 list가 들어가는게 좋아보입니다.

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        }
이건 왜 필요한 코드인가요? collectionView를 여러번 addSubview 해야하는 상황이 있나요?

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        collectionView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
여기는 왜 오토레이아웃을 사용하지 않았나요?

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +
이 레이아웃이 어떤식으로 구성되는지 설명해주시겠어요?

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        collectionView = UICollectionView(frame: .zero, collectionViewLayout: createGridLayout())
layout을 바꾸기 위해 collectionView를 매번 초기화 하는건가요? 많이 이상하다고 생각됩니다.

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        snapShot.appendItems(productData?.pages ?? [])
item이 없으면 안넣는게 맞지않나요?

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Model/ProductList.swift
> +    }
이거는 여기서 하지말고 이걸 사용하는 객체에서 하는게 어떨까요? View의 비즈니스 로직을 담당하는 곳에서 했으면 좋겠습니다.

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Model/ProductList.swift
> +struct Product: Decodable, Hashable {
Hashable을 채택한 이유는 뭔가요? DiffableDataSource는 어떻게 작동하나요?

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
왜 바꾸셨나요? 이유가 있을까요?

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +    }
이걸 NetworkProvider에서 해야하나요? 만약 다른 기능이 추가되면 또 NetworkProvider에 추가해야할까요? 그렇다면 NetworkProvider는 하나의 역할만 하는걸까요? 
저는 이런 구체적인 기능은 따로 객체를 만들어서 정의합니다. 그 내부에서 NeotwkrProvider를 구체적으로 사용하는거죠.

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +
불필요한 변경사항은 올리지 말아주세요.

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ProductGridCell.swift
> +    }
이 init은 언제 호출되나요?

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ProductGridCell.swift
> +        self.stockLabel.attributedText = product.stock == 0 ? "품절".foregroundColor(.orange) : "잔여수량: \(product.stock)".attributed
모델을 가공한 결과를 view가 사용만 했으면 좋겠습니다. 즉 이 동작을 다른 객체에서 했으면 좋겠어요.

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ProductListCell.swift
> +    override func updateConfiguration(using state: UICellConfigurationState) {
이 메소드는 override되었는데 왜 super호출이 없나요?

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        dataSource.apply(snapShot)
dataSource를 설정하는 기능과 dataSource에 apply하는 기능이 혼합되어있는 메소드 같습니다. 분리해주세요.

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +                                               heightDimension: .absolute(self.view.frame.height * 0.3))
view에 직접 접근하지말고, CompositionalLayout 생성자 중에 sectionProvider를 제공하는 생성자가 있습니다. 그 생성자에 제공되는 `NSCollectionLayoutEnvironment`에 대해 알아보세요.

2022-11-25 12:09 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ProductListCell.swift
> +    }
view hierarchy잡는 작업을 init 시점에 해주면 안되나요? 이 메소드는 configuration이 불릴때마다 호출되고, guard문에 걸리는데, 특별히 이렇게 해야하는 이유가 있나요?

2022-11-28 09:37 UTC, tottalE commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +    private var dataSource: UICollectionViewDiffableDataSource<Section, Product>!
꼭 해야하는 것은 아니지만 공식 문서의 샘플 코드를 토대로 코드를 작성해 보았습니다! 강제 언래핑이 문제가 된다면 수정하겠습니다!

2022-11-28 10:01 UTC, tottalE commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        networkProvider.fetchProductList(query: [.itemsPerPage: "200"]) { [weak self] result in
아래와 같이 생성해 주었습니다! 혹시 저희의 이해가 틀리다면 말씀해주세요!!
[cf07299](https://github.com/yagom-academy/ios-open-market/pull/224/commits/cf0729983343e50ec9204d9dd1269c3e3efd5bbc)

2022-11-28 10:09 UTC, jonghancha commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +    var productData: ProductList?
내부에서만 알고있는 프로퍼티입니다 private처리해주었습니다!

2022-11-28 10:30 UTC, jonghancha commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        self.present(addProductViewController, animated: true, completion: nil)
self는 다 붙여주려고 했는데 빼먹은것 같습니다 ! 다시 다 붙여서 수정했습니다

2022-11-28 10:31 UTC, tottalE commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +    var productData: ProductList?
접근 제어자 변경해 주었습니다 감사합니다!

2022-11-28 10:38 UTC, tottalE commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +                                  NSLocalizedString("GRID", comment: "")]
UISegmentItem에 items가 [Any]? 로 되어 있고 공식 문서상  Items may be NSStrings, UIImages, or (as of iOS 14.0) UIActions이라고 되어 있습니다. NSLocalizedString은 key-vaule 개념이 적용된 NSString으로 (실은 아직 이해하기 어려운 상태입니다.) 기능이 불필요하다고 생각되어 String으로 바꾸어 주었습니다!

2022-11-28 10:39 UTC, jonghancha commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +    @objc func segControlChanged(segcon: UISegmentedControl) {
네 추가해주었습니다!

2022-11-28 10:46 UTC, tottalE commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +extension ProductListViewController {
네 합쳐 주었습니다!! 감사합니다

2022-11-29 06:44 UTC, tottalE commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        }
네 기존에 addsubview를 통해서 collectionview를 넣어주는 방식으로 해주었었습니다! 그래서 collectionview가 있는 경우에는 지워주고 거기에 새로운 collectionview를 넣어주는 방법을 사용해주었었는데 지금은 바꾸어준 상태입니다!

2022-11-29 06:56 UTC, tottalE commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        }
segment enum으로 처리하도록 바꾸어 보았습니다!

2022-11-29 06:58 UTC, tottalE commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        collectionView = UICollectionView(frame: .zero, collectionViewLayout: createGridLayout())
디스코드에서 말씀해주신 방법을 참고하여 수정해보았습니다!!

[f2fcef1](https://github.com/yagom-academy/ios-open-market/pull/224/commits/f2fcef110ac1ebf34961c36b190282c89329bdf0)

2022-11-29 06:59 UTC, tottalE commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +extension ProductListViewController {
현재 extension은 segment관련, layout관련 이렇게 두가지로 구분해서 작성해 보았습니다!

2022-11-29 06:59 UTC, tottalE commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +    }
네 segment의 로직을 바꾸면서 함께 바꾸어 주었습니다

2022-11-29 07:05 UTC, tottalE commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        collectionView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
autosizingmask같은 경우 bounds가 변경 되었을 때 위치를 조정해주는 것인데, 저희는 bounds가 바뀌지 않는다고 생각이 들어 오토레이아웃으로 수정해 주었습니다.

2022-11-29 07:28 UTC, jonghancha commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +
아래의 사진처럼 section이 group을, 그리고 group은 item들을 담고있습니다.  하나의 group은 grid뷰 상태에서 가로로 2개의 item을 가지고, 그 폭은 group을 담고있는 container와 같고, 높이는container의 0.3배입니다.  itemSize 또한 `.fractionalWidth(1.0)`으로 item을 담고있는 container 와 폭이 같지만, group에서 subitem count로 2개를 가지고 있기 때문에 자동으로 폭은 절반으로 줄어듭니다. 아이템 사이의 간격, 그룹 사이의 간격은 모두 CGFloat(10)으로 설정했습니다.
<img src="https://user-images.githubusercontent.com/73284068/204463741-3285df01-53dc-4164-8e20-b39a69a99247.png" width="300" >

2022-11-29 07:42 UTC, jonghancha commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        collectionView = UICollectionView(frame: .zero, collectionViewLayout: createGridLayout())
추가적으로 `collectionView.collectionViewLayout`을 변경해 List와 Grid형태를 오갈 때 이전의 셀 형태를 그대로 들고 가는 현상이 발견되었습니다. 

**오류현상**
<img src= "https://user-images.githubusercontent.com/73284068/204466795-6a60f6b0-418d-47ae-951c-dd45a6925e8e.gif" width ="250" >

문제의 원인은 `List -> Grid` 로 변경되는 과정에서, layout은 변경되었지만 이미 dataSource에서 `listCellRegistration`의 형태로 dequeue된 cell들을 그대로 가지고 가기 때문이라고 판단했습니다. 

이에 [reloadSections(_:)](https://developer.apple.com/documentation/uikit/nsdiffabledatasourcesnapshot/3375784-reloadsections) 을 사용해 해 오류는 해결했습니다. 하지만 dequeue된 녀석들을 처리하기 위해 snapShot의 데이터를 모두 reload하는게 과연 맞는지에 대한 의문이 남았습니다.

혹시 다른 방법이 있는지 여쭤보고 싶습니다!

2022-11-29 07:44 UTC, tottalE commented on OpenMarket/OpenMarket/View/ProductListCell.swift
> +    }
여러번 호출 될 필요가 없는데 당시 이해 부족으로 여러번 호출했었습니다!! 지금은 init과 함께 호출될 수 있도록 바꾸어준 상태입니다!

2022-11-29 07:50 UTC, jonghancha commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        snapShot.appendItems(productData?.pages ?? [])
네 저희도 다시 생각해보니 item이 없을 경우 아예 넣지 않는게 맞다고 생각해 수정했습니다 !
[ac7e51e](https://github.com/yagom-academy/ios-open-market/pull/224/commits/ac7e51eefb70b46378576511759492d825ee03d3)

2022-11-29 08:15 UTC, tottalE commented on OpenMarket/OpenMarket/Model/ProductList.swift
> +    }
Protocol을 적용해서 고쳐줘 보았습니다!!! model에서 view의 역할까지 분담하고 있었던것 같습니다 !!

[619f6ef](https://github.com/yagom-academy/ios-open-market/pull/224/commits/619f6efbca44164f02995df4e49359d0978177aa)

2022-11-29 08:20 UTC, tottalE commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        dataSource.apply(snapShot)
Datasource가 하는 일에 대한 이해도가 부족했던 것 같습니다! datasource 내부에 분기를 해주면서 snapshot도 나누어 주었습니다!

2022-11-29 08:20 UTC, tottalE commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +
네!!!

2022-11-29 08:27 UTC, tottalE commented on OpenMarket/OpenMarket/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
storyboard 없이 코드로 구현을 해보고 싶어 바꾸어 보았습니다! SceneDelegate은 화면에 무엇을 보여줄지 정하는 역할을 하는데 그 중 첫 화면을 설정하는 scene(_: willConnectTo: options: ) 메서드 내부를 수정하여 코드로 네비게이션 컨트롤러와 뷰컨트롤러를 만들어줄 수 있었습니다!

2022-11-29 08:51 UTC, tottalE commented on OpenMarket/OpenMarket/Model/ProductList.swift
> +struct Product: Decodable, Hashable {
Hashable을 채택해야만 DiffableDataSource로 사용할 수 있는데, 저희 코드 내에서는 product가 hashable해서 구분 가능하도록 구현해 주었는데요. snapshot을 어플라이하면 데이터소스가 이전 스냅샷이랑 해쉬값으로 비교하기 때문에 product가 hashable 해야한다고 생각했습니다! DiffableDataSource는 이전 snapshot의 state와 current snapshot의 state를 비교하여 업데이트 해주는 방식으로 작동합니다.

2022-11-29 08:58 UTC, tottalE commented on OpenMarket/OpenMarket/View/ProductListCell.swift
> +    override func updateConfiguration(using state: UICellConfigurationState) {
당시에는 updateConfiguration이 내용이 없는 비어있는 메서드라고 생각해 super 호출을 해주지 않았었습니다! 현재는 override를 하지 않고 있어 삭제가 된 상태이지만, super를 부르는 것으로 통일하는 것도 좋은 것 같습니다. 💪🏽

2022-11-29 09:03 UTC, tottalE commented on OpenMarket/OpenMarket/View/ProductGridCell.swift
> +    }
xib 나 스토리보드에서 생성이 될때에는 init(coder: NSCoder) 를 통해서 객체가 생성됩니다. 저희의 경우 모드 코드로 구현해 주어 호출되는 일이 없을 것 같습니다!

2022-11-30 07:24 UTC, tottalE commented on OpenMarket/OpenMarket/View/ProductGridCell.swift
> +        self.stockLabel.attributedText = product.stock == 0 ? "품절".foregroundColor(.orange) : "잔여수량: \(product.stock)".attributed
그렇게 적용해서 ImageManger를 만들어 주었습니다!
[6358066](https://github.com/yagom-academy/ios-open-market/pull/224/commits/63580663336191f7cde25fd304a6de0b5b2b2c32)

2022-11-30 07:25 UTC, tottalE commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        }
prepareForReuse에서 리퀘스트를 취소시킬 수 있도록 적용해 보았습니다!

[6358066](https://github.com/yagom-academy/ios-open-market/pull/224/commits/63580663336191f7cde25fd304a6de0b5b2b2c32)

2022-11-30 07:47 UTC, jonghancha commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +    }
네 이미지를 fetch하는 객체를 따로 만들어 그 안에서 NetworkProvider를 사용하게 해주었습니다.

2022-11-30 07:47 UTC, jonghancha commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +                                               heightDimension: .absolute(self.view.frame.height * 0.3))
이 부분은 해결하지 못했습니다 ㅠ

2022-11-30 15:27 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        collectionView = UICollectionView(frame: .zero, collectionViewLayout: createGridLayout())
지금 방법 좋네요. 괜찮다고 생각합니다.

2022-11-30 15:29 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ProductGridCell.swift
> +    }
그러면 만약 이 init이 불리는건 정상 동작이 아니겠네요. 사용하는 개발자에게 알릴 수 있도록 `fatalError()`를 사용하는건 어떨까요?

2022-11-30 15:36 UTC, 1Consumption commented
고생하셨습니다.
다음 스텝에서는 API paging도 추가되면 좋겠습니다.
다음 스텝을 진행해주세요.

2022-11-30 15:36 UTC, merged