오픈마켓 [STEP 2] Zhilly, Dragon
yagom-academy/ios-open-market pull request #225
Opened 2022-11-25 07:04 UTC by zhilly11

안녕하세요, 하비(@havilog)🙇‍🙇‍♀️!
[zhilly🔥](https://github.com/zhilly11), [Dragon🐉](https://github.com/FlameYG)입니다!
오픈마켓 STEP-2 코드 작성을 완료하여 PR드립니다!
생각보다 어려운 부분도 많고 세세하게 수정포인트도 많아서 시간이 오래 걸렸습니다...!
부족한 코드이지만 많은 조언해주시면 감사하겠습니다😃 리뷰 잘부탁드립니다 :-)

# 📍고민했던 부분 

## 오토레이아웃 코드vs스토리보드
- 전반적인 UI구성을 어떻게 할지 고민하다가 CollectionViewCell에서 코드가 아닌 xib파일을 활용할 수 있다는 것을 알게되어, 처음 접해보는 CollectionView에서 아직 낯선 코드보단 스토리보드를 통해서 작성해보고자 했습니다.

- UI를 스토리보드로 작성했을 때 장점은 UI구성을 한눈에 확인할 수 있고 View요소에 어떤 속성값을 설정했는지 확인하기 쉬운 장점도 있습니다.
    단점은 협업시 스토리보드의 충돌 혹은 이슈가 있다고 합니다만 장점이 더 크다고 생각되어 애플리케이션 내에 뷰가 많지 않아서 스토리보드로 작성했습니다.

## AttributedText 구현 및 초기화
- String타입에 확장으로 `strikeThrough(length: Int, color: UIColor)` 메서드를 구현했습니다. 처음엔 취소선 구현해주는 메서드, text의 색상을 변경해주는 메서드 따로 구현을 하려고 했습니다만, 따로 해줄 경우에 `attribute`를 두 번 덮어 씌우는 형식이라 하나의 메서드로 한 곳에서 추가를 해주는 방식으로 구현했습니다.

- `CollectionViewCell`에 넣어준 `Label.Text`에 `String-Extension`으로 `AttributedText`를 적용해주어 `Cell`이 `Dequeue`되는 과정에서 초기화가 필요했습니다
그 후 초기화를 위해 `prepareForReuse()`메서드에서 text값과 `AttributedText`를 초기화하는 과정에서 text를 먼저 초기화해준 후 `AttributedText`를 초기화를 해주니, 초기화가 정상적으로 되지않는 문제가 발생하였고, 확인결과 `AttributedText`를 초기화 해준 뒤 Text를 초기화해주어야 원하는 동작을 구현할 수 있었습니다.

## ViewController에서 API통신 비동기 처리
- ViewController에서 URL에 접근해서 가져온 데이터를 어떻게 받아올지 고민했습니다.
STEP1에서 구현한 `NetworkManager-request`가 **비동기적으로 작업을 진행**하기에 UI에 Data 넣어주는 과정에서 문제가 발생하였습니다.
이를 해결하기 위해 request함수에서 데이터를 모두 가져왔을 때 collectionViewCell에 데이터를 넣어줄 수 있도록 `request함수`를 처리해주는 메서스를 만들어준 뒤 `completion: @escaping`을 적용하여 데이터를 모두 가져왔을 때, UI에 Data를 넣어주는 식으로 진행했었으나, `CollectionView.reloadData()`라는 메서드를 알게되어 main.async하게 작성해줘서 동작하도록 재구현 했습니다.
```swift
// 처음 구현한 방법
override func viewDidLoad() {
     super.viewDidLoad()
     configureCollectionView()
     DispatchQueue.global().async {
         self.loadData { data in
             DispatchQueue.main.sync {
                 self.configureCollectionView()
             }
         }
     }
 }

func loadData(complete: @escaping(ProductList) -> ()) {
     networkManager.request(from: URLManager.productList(pageNumber: 1, itemsPerPage: 200).url, httpMethod: HttpMethod.get, dataType: ProductList.self) { result in
         switch result {
         case .success(let data):
             self.product = data
             complete(data)
         case .failure(_):
             break
         }
     }
}

// reloadData()를 활용한 방법
override func viewDidLoad() {
    super.viewDidLoad()
    configureCollectionView()
    loadData()
}
    
func loadData() {
    networkManager.request(from: URLManager.productList(pageNumber: 1, itemsPerPage: 200).url,
                           httpMethod: HttpMethod.get,
                           dataType: ProductList.self) { result in
        switch result {
        case .success(let data):
            self.product = data
            DispatchQueue.main.async {
                self.collectionView.reloadData()
            }
        case .failure(_):
            break
        }
    }
}
```

## 셀 테두리라인 전체 및 부분적으로 그리기
- 테두리라인을 주기 위해 처음에 생각한 방법은 UIView에 테두리를 적용하고자 하였으나, 원하는대로 적용이 안되었습니다.
그래서 다른 방법을 알아보니 CollectionViewCell에 Code를 적용하여 테두리라인을 추가할 수 있었고, 조사한 방법을 통해 구현을 시켜보니 GridCell에서는 정상적으로 동작하였으나, ListCell에서는 셀간의 간격이 있는 문제로 인해 셀간의 1개의 라인이 아닌 2개의 라인이 그려지는 문제점이 발생하였습니다. 이를 해결하기 위해 cell의 바텀라인에만 구분선을 추가해주면 된다고 생각하여 바텀라인에만 라인을 그리는 방법을 확인하여 적용하여 해결하였습니다.
```swift
// 전체 테두리 그리는 방법
func addBorderLine(color: UIColor, width: CGFloat) {
    self.layer.cornerRadius = 10
    self.layer.borderWidth = width
    self.layer.borderColor = color.cgColor
}

// 부분적으로 테두리 그리는 방법
func addBottomLine(color: UIColor, width: CGFloat) {
    let bottomLine: CALayer = CALayer()
        
    bottomLine.frame = CGRectMake(0, self.frame.height - width, self.frame.width, width)
    bottomLine.backgroundColor = color.cgColor
        
    self.layer.addSublayer(bottomLine)
}
```

- 리스트 셀에 처음 바텀라인에 줄을 주기위해 Cell.layer를 기준으로 했었더니 아래의 cell과 공간이 비어있게 보였습니다. 그래서 frame을 기준으로 잡고 진행했습니다!

## 세그먼트 컨트롤을 통해 셀을 변경할 경우 Reload 처리

- 세그먼트 컨트롤을 통해 셀을 변경할 때, 레이아웃을 다시 잡고 데이터를 넣어줘야한다고 생각하고 구현하였습니다.
그런데, 처음에 보이는 Cell들의 이미지가 잘못 들어오는 경우가 종종 보이는 문제가 확인되었습니다.
왜 이런 현상이 발생하는지 고민해보니, 레이아웃을 다시 잡는 과정에서 이전 데이터로 레이아웃을 잡고 다시 데이터를 넣어주는 과정에서 문제가 발생한 것으로 예상되어, 어떻게 해결해야할지 고민하다가 데이터를 넣고, 레이아웃을 다시 잡아주니 문제를 해결할 수 있었습니다.

## 비동기 안에서 activityIndicator Stop 처리
- 현재 URL에 접근하여 데이터를 가져오는 로딩시간동안 activityIndicator를 표시하도록 구현하였습니다.
그 후 데이터를 모두 가져온 뒤 activityIndicator를 삭제하는 작업이 UI 작업이기에 `Dispatch.main`을 사용하여 정상적으로 구현했습니다.

# 📍조언을 얻고 싶은 부분

## UI에 URL데이터 가져오는 방법
- STEP-2에서 가장 중요했던 내용이 아닐까 싶습니다.
그러하여, 저희가 구현한 방법이 좋은 접근이였는지와 부족한 부분이 있었다면 조언 꼭 부탁드리겠습니다🥹
위에 `고민했던 부분 - ViewController에서 API통신 비동기 처리`에 작성한 내용을 참고하여 코드를 봐주시면 더 쉽게 코드를 이해할 수 있을 것 같다고 생각합니다.

## 세그먼트 컨트롤을 눌렀을 때 다른 셀로 교체하는 방법
- 저희는 세그먼트 컨트롤을 눌렀을 때 ListCell <-> GridCell의 Code와 Xib을 다시 가져와서 레이아웃을 잡아주는 방식을 사용했습니다.
세그먼트 컨트롤을 처음 사용하다보니 이렇게 구현하는게 올바른 구현방법이였는지에 대한 의문이 들었습니다🤔
현재 구현방법 확인과 다른 접근방법이 있다면 조언 부탁드리겠습니다!👍

## 세그먼트 컨트롤에서 수행되는 동작 순서

- 현재 세그먼트 컨트롤에서 버튼이 눌릴때 동작하는 방법에 문제가 없는지 확인부탁드립니다.
동작순서는 아래 확인 부탁드립니다. 

- 현재 코드상 동작순서
1. `ViewController`의 파라미터값으로 있는 `cell의 identifier`값을 바꿔준다
2. 콜렉션 뷰를 다시 `reload` 시켜준다.
3. 바뀐 `identifier`값을 기준으로 `nib`파일을 다시 등록해준다.
4. 바뀐 `cell`에 맞게 다시 `FlowLayout`을 설정해준다.

## StackView의 성능
공식문서는 아니지만 [벤치마크 깃헙](https://github.com/layoutBox/LayoutFrameworkBenchmark) 에 따르면 `StackView`의 렌더링 속도가 제일 오래걸린다고 표기되어 있습니다! 따라서 cell이 조금더 빠릿하게 동작하기 위해서 이번 프로젝트에서는 `StackView`를 사용하지 않았습니다!

애플에서 제공하는 공식문서가 없기에 100퍼센트 신빙성이 있지는 않지만 생각을 해보았을때 안 쓰는 방법이 조금더 수행 속도가 빠를 것이라고 생각되어 `StackView`없이 코드를 작성했습니다.

현업에서도 `StackView`의 사용을 지양하는 편인가요? 보통 어떻게 레이아웃을 구현하는지 궁금합니다!

2022-11-25 17:20 UTC, havilog requested changes
grid에서 default image가 보이는데 수정 부탁드려요!

>UI에 URL데이터 가져오는 방법
사실 가장 중요한 부분일거 같은데,

뷰가 로드되면 -> API를 찌르고 -> 정상 일 때 내용 표시 -> 이미지 다운이 필요할 경우 요청 -> 성공 시 표시
의 플로우는 잘 작성하신거 같아요.

앞으로 아키텍쳐나 구조적인 측면에서 어떤 객체가 어떤 역할을 담당하고,
이미지 처리를 고도화 시키는 부분을 공부해보시면 좋을 것 같습니다.
이미지를 다운로드 받는 객체와 캐싱하는 객체, 그 전체 플로우를 담당하는 객체 등 
킹피셔를 참고하시면 좋을 거 같아요

>세그먼트 컨트롤에서 수행되는 동작 순서
요거는 근본적인 UI 설계를 다시 생각해보시는 것도 좋을거 같습니다!

>StackView의 성능
저는
스택 뷰 + 스크롤 뷰 vs 테이블 or 콜렉션 뷰를 그릴 때에는 
해당 뷰에 재사용되는 아이들이 존재하고, 그 수가 많은지로 판단하는거 같아요.

사실 성능적인 측면도 중요하지만, 이런 의사 결정에서는 유지보수가 더 중요한 factor일거 같다고 생각합니다.

저는 일반적인 뷰 그릴 때 거의 스택뷰로 그리는 편이에요.

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        }
cell의 identifier를 protocol에서 extension으로 정의하는 방법이 있는데 혹시 알고 계실까요?

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +    private let networkManager: NetworkRequestable = NetworkManager(session: URLSession.shared)
networkManager는 의존성주입을 해주시는데,
뷰컨에서는 안해주시고 여기서 생성하는 이유가 있을까요?

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +    private var cellIdentifier: String = cellType.list.identifier
요 아이는 여기서 지역변수로 반드시 필요하지는 않을거 같아요

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +    @IBOutlet weak var viewModeController: UISegmentedControl!
private 안붙여줘도 괜찮을까요?

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +    private lazy var activityIndicator: UIActivityIndicatorView = {
이 프로퍼티는 생성될 수도 있고 아닐 수도 있나요?
lazy var 키워드의 시그니쳐가 무엇일까요?

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        activityIndicator.center = self.view.center
이 closure에서 self를 반드시 잡고 있을 필요가 있을까요?

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        initCollectionView()
init과 configure의 차이는 뭘까요??
처음보는 사람이 이 함수명을 보고 내부에서 어떤 역할을 하는지 유추할 수 있을까요?

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        activityIndicator.startAnimating()
뷰가 로드된 시점부터 시작해야하나요?

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        networkManager.request(from: URLManager.productList(pageNumber: 1, itemsPerPage: 200).url,
페이지가 여러장일 경우 어떻게 될지 고민해보셨나요?

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +                               dataType: ProductList.self) { result in
self를 strong capture하고 있네요

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +            self.collectionView.reloadData()
reloadData가 어떻게 동작하는지 알고 계신가요?
만약 셀의 갯수가 많을 때 계속 reload를 한다면 어떤 동작이 일어날까요?

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        self.collectionView.register(collectionViewCellNib,
어디에는 self가 붙고, 어디에는 안 붙고 있는데 컨벤션이 통일 되면 좋을거 같아요

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        }
메인 뷰컨에서 containerView 하나를 가지고 있고, 세그먼트를 눌렀을 때, 그 뷰의 content를 바꿔주는 방식으로도 설계할 수 있었을거 같고,
아니면 뷰컨 자체를 두개 만드는 방법도 있었을 거같은데
설계 단계에서 어떤 고민을 하셨는지 궁금해요

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        switch sender.selectedSegmentIndex {
매직넘버를 사용하면 0번째 index가 어떤 탭인지 코드만 보고 유추하기 힘들거 같아요.
enum을 활용하는 방법은 고민해보셨을까요?

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        let flowLayout: UICollectionViewFlowLayout = UICollectionViewFlowLayout()
flowlayout을 사용하기로 결정하신 이유가 무엇인가요?

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        let flowLayout: UICollectionViewFlowLayout = UICollectionViewFlowLayout()
이렇게 되면 gridCollectionViewFlowLayout이 불릴 때마다 layout을 새로 만들어줄거 같은데 재사용할 수는 없을까요?

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        return count
```suggestion
        return product?.pages.count ?? .zero
```

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +                                           for: indexPath) as! ListCollectionViewCell
강제 캐스팅이 반드시 필요할까요?

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        guard let productItem = product?.pages[indexPath.item] else {
safe하게 subscript에 접근하는 방법도 찾아보시면 좋을 거 같아요

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/View/GridCollectionViewCell.swift
> +class GridCollectionViewCell: UICollectionViewCell {
상속이 가능한 셀인가요?

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/View/GridCollectionViewCell.swift
> +    override func prepareForReuse() {
prepareForReuse가 어떤 시점에 어떤 역할을 하기 위해 불리는지 알고 계실까요?

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/View/GridCollectionViewCell.swift
> +                                NameSpace.whiteSpace.text +
요거는 이렇게 쓰는게 오히려 더 읽기 힘든거 같은 느낌도 들어서 그냥 스트링 리터럴 박아도 괜찮을거 같다는 개인적인 의견입니다 ㅎㅎ

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/View/GridCollectionViewCell.swift
> +        }
함수로 쪼개도 좋을거 같아요

2022-11-25 17:20 UTC, havilog commented on OpenMarket/OpenMarket/Sources/View/GridCollectionViewCell.swift
> +        }
이 시그니쳐만 보면 thumbnail이 있을 수도 있고, 없을 수도 있어서
있을 때만 이미지를 로드한다.
로 보여지는데, 의도하신 바가 맞을까요?

2022-11-29 02:59 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +    private let networkManager: NetworkRequestable = NetworkManager(session: URLSession.shared)
2가지 방법을 고민해 보았습니다.

- 1번 방법 : viewDidLoad에서 주입시켜주는 방법
```swift
private let session: URLSessionProtocol = URLSession.shared
private var networkManager: NetworkRequestable?

override func viewDidLoad() {
        super.viewDidLoad()
        networkManager = NetworkManager(session: session)
    }
```


- 2번 방법 : lazy var를 이용해서 networkManager가 사용될 때 할당해 주는 방법
```swift 
private let session: URLSessionProtocol = URLSession.shared
private lazy var networkManager: NetworkRequestable =  NetworkManager(session: session)
```

1번 방법으로 하면 만약 NetworkManager를 쓰지 않는 상황이 오지 않을 때에도 할당을 해줘야 할 것 같다고 생각해서 2번 방법을 이용해서 networkManager를 사용할 때 할당해 주도록 lazy var 키워드를 사용하여 수정했습니다.

2022-11-29 06:14 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        }
```swift
protocol CellIdentifierInfo {
    static func stringIdentifier() -> String
}

extension CellIdentifierInfo {
    static func stringIdentifier() -> String {
        return String(describing: self)
    }
}
```
위와 같이 구현해보았는데 하비가 알고 계신 방법과 동일한 것인지 확인부탁드립니다~ 😃
그리고 MainViewController에서 CellMode 판단이 필요하여 CellMode를 추가해주었습니다.
(최대한 사용하지 않고 구현해보려고 하였으나, 현재 저희 코드구조상 꼭 필요한 부분이라고 생각하였습니다!

2022-11-29 06:16 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +    private var cellIdentifier: String = cellType.list.identifier
네! 그런데 위에서 코멘트 단 것처럼 CellMode를 판단할 수 있는 코드가 필요하다고 생각되어 CellMode를 아래와 같이 추가해주었습니다
```swift
enum CellMode {
    case listType
    case gridType
}

final class MainViewController: UIViewController {
    private var product: ProductList?
    private var cellMode: CellMode = .listType
```

2022-11-29 06:17 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +    private let networkManager: NetworkRequestable = NetworkManager(session: URLSession.shared)
+ `session`, `networkManager` 변수를 `loadData() `에서만 사용해서 메서드 내부로 이동했습니다!

2022-11-29 06:23 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        initCollectionView()
아 그렇네요...!
`initColletionView()` -> `configureColletionViewDelegate()`로 수정하였습니다~!

2022-11-29 06:28 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +    @IBOutlet weak var viewModeController: UISegmentedControl!
`private` 붙여주었습니다..!

2022-11-29 06:35 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        }
먼저 생각한 방법으로는 뷰 컨트롤러를 2개 만드는 방법과 지금의 Cell을 바꿔주는 방식 두 가지 방법을 생각했었는데요. 2개의 뷰 컨트롤러로 만들게 되면 데이터가 왔다 갔다 하는 방식이 복잡할 듯하여 하나의 뷰컨으로 일단 구현을 해 보았습니다.

지금 단계에서 유지 보수성이나 객체지향 프로그래밍적 관점에서 보았을 때 containerView 안에 ListView, GridView 두 가지 View를 만들어 세그먼트를 눌렀을 때 뷰를 교체해 주거나, 위아래 순서를 변경해 주거나, 하나를 숨기고 하나를 보여주는 방식 등으로 구현하는 것이 괜찮은 리팩토링 방법으로 생각됩니다!

2022-11-29 06:44 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        switch sender.selectedSegmentIndex {
고민은 못해봤습니다...
덕분에 enum 사용하여 수정하였습니다~!

2022-11-29 06:44 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        switch sender.selectedSegmentIndex {
enum을 활용하여 수정해 주었습니다!

2022-11-29 06:46 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +                                           for: indexPath) as! ListCollectionViewCell
guard let으로 옵셔널 처리해주었습니다... 놓친 부분인 것 같네요...!

2022-11-29 06:49 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/View/GridCollectionViewCell.swift
> +class GridCollectionViewCell: UICollectionViewCell {
`final` 키워드 추가하였습니다

2022-11-29 06:52 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/View/GridCollectionViewCell.swift
> +                                NameSpace.whiteSpace.text +
아 넵! 수정하였습니다! ㅎㅎㅎㅎ

2022-11-29 06:56 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +    private lazy var activityIndicator: UIActivityIndicatorView = {
`lazy var` 키워드는 변수를 선언하면 사용하기 전까지 메모리에 할당하지 않습니다.
그래서 사용할 때 메모리에 할당되기 때문에 초깃값이 외부에 의존되어 있거나 변수의 사용이 확실하지 않을 때 붙이는 키워드라고 생각합니다~

2022-11-29 06:57 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        activityIndicator.startAnimating()
아닌듯합니다... 고민해본 결과, `ViewWillAppear`로 수정하였습니다

2022-11-29 06:57 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        activityIndicator.center = self.view.center
self 키워드는 굳이 필요없다고 생각하여서 제거했습니다!

2022-11-29 06:57 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        self.collectionView.register(collectionViewCellNib,
컨벤션 더 신경쓰도록 하겠습니다~!

2022-11-29 07:30 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        let flowLayout: UICollectionViewFlowLayout = UICollectionViewFlowLayout()
프로젝트에서 구현해야하는 CollectionView Cell이 일정한 비율과 동일한 셀의 모양을 이루고 있기에 `flowlayout`을 사용하면 좋을 것 같다라고 판단했었습니다 😀
추가로, `https://developer.apple.com/documentation/uikit/uicollectionviewlayout` 링크에서 레이아웃 성능향상에도 도움이 된다고 추가 확인하였습니다~!

2022-11-29 08:25 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/View/GridCollectionViewCell.swift
> +    override func prepareForReuse() {
CollectionView의 delegate가 reusable cell이 재사용 될 수 있도록 준비할 수 있는 메서드라고 알고 있습니다.
추가로 찾아본 결과 cellForRowAt에서 원래 해당 cell의 content를 reset 하기 때문에 성능을 위해서 prepareForReuse 메서드 안에서는 content와 무관한 property들만 reset 하는 게 좋다고 합니다.

따라서 prepareForReuse에서 cell의 속성값들만 수정해 주었고 콘텐츠들은 cellForItem에서 해주도록 수정하였습니다~

2022-11-29 08:28 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        let flowLayout: UICollectionViewFlowLayout = UICollectionViewFlowLayout()
```swift
final class MainViewController: UIViewController {
    private var product: ProductList?
    private var cellMode: CellMode = .listType
    private var flowLayout: UICollectionViewFlowLayout = UICollectionViewFlowLayout()
```
위와 같이 지역변수를 한번만 생성해주고, 메서드에서는 설정값만 바꾸는 식으로 변경하였습니다.
그런데 지역변수를 선언해주는 것이 맞는건지 잘 모르겠네요... 

혹시 다른 좋은 방안이 있다면 조언 부탁드리겠습니다!

2022-11-29 09:04 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/View/GridCollectionViewCell.swift
> +        }
```swift
let url = URL(string: item.thumbnail)
```

이런 식으로 작성하면 `url`이 옵셔널 타입으로 할당되어서 `url`을 옵셔널 바인딩 해주고자 하는 의도로 작성했습니다.
또한 thumbnail의 주소가 없을 경우도 있어서 없을 경우엔 load 메서드 자체로 넘어가지 않게 하고자 했습니다~

2022-11-29 09:05 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/View/GridCollectionViewCell.swift
> +        }
[18def55](https://github.com/yagom-academy/ios-open-market/pull/225/commits/18def5586718e679db1350269bf6d312e2a1f98c) 분리하였습니다!

2022-11-29 09:11 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        guard let productItem = product?.pages[indexPath.item] else {
덕분에 확인해서 적용하였습니다! 감사합니다! 👍

2022-11-29 09:26 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +                               dataType: ProductList.self) { result in
클로저에서 캡쳐하는 `result`의 타입이 `enum(값타입)`이기에 Strong Capture를 해줘도 문제없지 않을까 싶습니다...!

2022-11-29 12:06 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +            self.collectionView.reloadData()
reloadData()는 콜렉션 뷰의 현재 보이는 전체를 업데이트할 때 사용합니다.

특정 열 섹션의 부분적인 업데이트가 아닌, 보이는 영역 전체를 업데이트할 때 효율적입니다.

reloadData 메서드를 호출한 후 콜렉션 뷰가 데이터를 완벽히 업데이트했다면 delegate, datasource 관련 메서드는 상황과 조건에 맞게 호출됩니다.

일부만 업데이트할 때는 비효율적이라고 생각합니다.

셀의 개수가 많을 때 계속 reloadData를 하게 된다면 셀의 로딩 시간 때문에 앱이 버벅거릴 것 같습니다

2022-11-29 13:30 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        networkManager.request(from: URLManager.productList(pageNumber: 1, itemsPerPage: 200).url,
현재 구조는 페이지 1장을 기준으로 최대한 많은 아이템들을 보여주는 방식이기에, 페이지 여러장의 경우는 고려하지 않았습니다...

하비의 질문을 받아 고민해본 결과, 페이지를 여러장을 사용한다는 조건을 두고 코드를 설계해야한다면 스크롤을 내릴때마다 화면에 띄울수있는 아이템의 갯수만을 서버로부터 가져와서 보여주는 방식으로 구현해야할 것 같습니다.🥲

하지만... 현재 시간적 여유가 없는 상황이기에 추후에 코드 리팩토링을 해서 구현해보도록 하겠습니다.

2022-11-29 14:39 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +    private let networkManager: NetworkRequestable = NetworkManager(session: URLSession.shared)
`lazy var` 키워드의 경우 사용될 수도 있고, 안사용될 수도 있다는 의미를 담고있는 키워드인데 `networkManager`의 경우 반드시 사용되는 아이 같아요.
ViewController가 initialize되는 시점에 의존성 주입을 해주는게 일반적인데 init 시점을 고려하지 않으신 이유가 뭘까요?

2022-11-29 14:40 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +    private var cellIdentifier: String = cellType.list.identifier
이렇게 되면 CellMode는 앱 전역에서 접근이 가능할거 같은데,
이 부분 고려해보셨을까요??
어떻게 하면 해결할 수 있을까요?

2022-11-29 14:42 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +    private lazy var activityIndicator: UIActivityIndicatorView = {
말씀하신대로 사용되거나/ 사용되지 않는 변수인데,
`activityIndicator`는 조건부로 로드되지 않고 항상 로드되는 아이인거 같아요.
따라서 클로저에서 self를 쓰기 위해 lazy var를 사용하는건 고려해봐야 할 사항이라고 생각합니다.
극단적인 예시로 viewDidAppear 시점에 누군가가 activityIndicator가 variable 하기 떄문에 새로운 UIActivityIndicatorView를 넣을 수도 있는 경우도 있어요.

2022-11-29 14:57 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +                               dataType: ProductList.self) { result in
request의 escaping closure가 self(MainViewController) 를 잡고 있다고 생각되는데요,
지금 구조에서는 memory leak이 나지는 않을거 같은데 구조가 바뀔 경우 위험할 수도 있을거 같아요.

2022-11-29 15:00 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +            self.collectionView.reloadData()
네 맞아요.
그래서 업데이트가 필요한 셀만 업데이트 하는 방법을 찾아보면 좋을거 같구요,
grid로 바꿨을 때 API를 다시 찔러서 다른 결과를 받아왔을 때 어떻게 될지도 한 번 생각해보시면 좋을거 같아요~!

2022-11-29 15:02 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        }
맞아요 이런 경우에는 아예 독립적인 UI로 가는게 추후 변경사항이 생겼을 때 대처하기 좋을거 같아요~!

2022-11-29 15:04 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        let flowLayout: UICollectionViewFlowLayout = UICollectionViewFlowLayout()
일정한 비율과 동일한 셀의 모양을 이루고 있어 flowlayout을 사용했다는 말이 잘 이해가 안되는데요,
compositional layout을 사용하면 셀의 모양을 동일하게 설정할 수 없을까요?

2022-11-29 15:09 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        let flowLayout: UICollectionViewFlowLayout = UICollectionViewFlowLayout()
사실 List의 경우 테이블 뷰, Grid의 경우 콜렉션 뷰와 같이 뷰를 분리해서 선언해주면 레이아웃은 각각 한번만 정해주면 될거 같은데, 지금 구조에서는,, 힘들거 같네요 ㅠ

2022-11-29 15:12 UTC, havilog commented on OpenMarket/OpenMarket/Sources/View/GridCollectionViewCell.swift
> +        }
configurationCell함수는 셀의 UI를 그리는 함수인데,
url을 만들어주는 부분은 configurationCell에서 하는것보다 `load(url:)` 함수에서 처리해주는게
낫지않을까 라고 생각해서 말씀드렸습니다 ㅎㅎ

2022-11-30 01:19 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +    private var cellIdentifier: String = cellType.list.identifier
MainViewController안에서 지역변수로 enum을 추가해주면 될 것 같다고 생각하여 수정하였습니다~!

2022-11-30 01:23 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +    private lazy var activityIndicator: UIActivityIndicatorView = {
[b151db2](https://github.com/yagom-academy/ios-open-market/pull/225/commits/b151db258cb4b1cc787f7e5d276cd253f10afc2a)  lazy var에 대해 깊이 고찰해보지 못했던 것 같습니다! var 로 선언해준뒤 따로 메서드에서 설정하도록 수정했습니다!

2022-11-30 01:26 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/View/GridCollectionViewCell.swift
> +        }
[1fbffcb](https://github.com/yagom-academy/ios-open-market/pull/225/commits/1fbffcb792053e630abf9637acf3001aa101a75c) 확실하게 역할 분리 해주었습니다~ 조언 감사해요 :)

2022-11-30 01:44 UTC, zhilly11 commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +    private let networkManager: NetworkRequestable = NetworkManager(session: URLSession.shared)
저희가 처음에 생각했던 방법은 2번 방법이었으나 추후 과정에서 

```swift
 private func loadData() {
        let session: URLSessionProtocol = URLSession.shared
        let networkManager: NetworkRequestable = NetworkManager(session: session)
        
        networkManager.request(from: URLManager.productList(pageNumber: 1,
...
```
이렇게 ViewController 내부의 프로퍼티로 가지고 있는 것보다 NetworkManager를 사용하는 메서드 내에서만 변수로 가지고 있게 하자는 생각으로 구현을 해보았습니다. 이 방법은 어떤가요?

>ViewController가 initialize되는 시점에 의존성 주입을 해주는게 일반적 

이 코멘트는 1번 방법으로 사용했을 때 ViewController에 init()을 통해서 주입을 시켜주라는 말씀이신가요??
아니면 `loadView` 시점에서 주입을 하라는 말씀이신가요?

2022-11-30 01:45 UTC, FlameYG commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +        let flowLayout: UICollectionViewFlowLayout = UICollectionViewFlowLayout()
`compositional layout`의 존재를 몰랐습니다...😅
CollectionView를 스터디하는 과정에서 FlowLayout만을 알았고,
현재 요구사항은 위에서 말씀드린것처럼 FlowLayout만 사용하여도 가능하다고 판단하고 FlowLayout을 사용하였습니다...!

`compositional layout`은 추가적으로 스터디해보도록 하겠습니다~!

2022-11-30 02:15 UTC, havilog commented on OpenMarket/OpenMarket/Sources/Controller/MainViewController.swift
> +    private let networkManager: NetworkRequestable = NetworkManager(session: URLSession.shared)
init()시점을 말한거였는데,
loadView와 init은 다른 사이클인데 헷갈리신 이유가 잘 이해가 안되네용

2022-11-30 02:16 UTC, merged