오픈마켓 [Step 2] Aaron, Jpush
yagom-academy/ios-open-market pull request #227
Opened 2022-11-26 05:02 UTC by Hashswim

안녕하세요 태태 @uuu1101
스텝 2까지 구현이 완료 되어 PR 보내드립니다

ios 이번 오픈마켓을 구현하면서 새로운 기술인 `modern collection view`를 사용해 보고 싶었습니다. `diffable data source`와 `compositional layout`을 사용해보았습니다..! 
그중 셀을 등록하는 방법이 ios14 버전에서 `registeration`을 사용하는 방법이 있어 사용해보고 싶어 버전을 14로 올렸습니다..!

## 🤔고민했던 점

### viewController와 View의 역할 구분
view에 보여주기 위해 데이터를 처리하는 부분중 어느부분을 viewController에 두고 view에 
두어야 할지 애매해지는 부분과 viewController가 너무 비대해지는 문제.
서로 이야기해보며 view에 보여주기 위해 필요한 연산과 로직은 viewController에 위치시키는 것으로 고수하는 게 옳다고 생각되어 대부분의 logic을 viewController에 구현하였습니다.

### 셀의 높이를 다이나믹하게 지정하는 방법
```swift
let itemSize = NSCollectionLayoutSize(
            widthDimension: .fractionalWidth(1.0),
            heightDimension: .estimated(120))
        let item = NSCollectionLayoutItem(layoutSize: itemSize)
        
        let groupSize = NSCollectionLayoutSize(
            widthDimension: .fractionalWidth(1.0),
            heightDimension: .estimated(120))
        let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize, subitem: item, count: 1)
```
compositional layout을 사용하여 셀의 높이를 다이나믹하게 지정해주기 위해서 여러가지 방법을 고민하다 estimate 방식을 사용해 지정해 주었습니다.
하지만, 앱이 실행중에 몇몇 셀의 높이가 계산되지 않아서 값이 다 표출되지 않는 현상이 남아 있었습니다.

2022-11-29 09:03 UTC, uuu1101 requested changes
STEP2 구현하느라 고생하셨습니다.
관련해서 코멘트 남겨두었습니다.

## **셀의 UI 업데이트 시점에 대한 조언** 

List 형태의 Cell의 업데이트 시점에 대해서, 한번 고민해보셔야 할 것 같아요.
이 부분에 대해서 답을 드리기보다는, 해당 부분은 앞으로의 프로젝트 뿐만 아니라 실제 업무를 하게 되셨을 때에도 매우 중요한 부분이니 한번 LLDB를 통해서 어느 시점에 뷰가 그려지고 어느 시점에 데이터가 들어오며 Layout을 언제 업데이트 해주는게 좋을지에 대해서 한번 꼭 경험해보셨으면 합니다.

방법은 여러가지가 있을거에요. LLDB를 활용하셔서 디버깅하는것을 추천드리며 추가적으로 이해를 돕기 위한 print문을 사용하셔도 괜찮을 것 같습니다.

2022-11-29 09:03 UTC, uuu1101 commented on OpenMarket/OpenMarket/ViewController.swift
>              print(product)
불필요한 코드는 지워주셔도 될것 같아요 :)

2022-11-29 09:03 UTC, uuu1101 commented on OpenMarket/OpenMarket/AddProductViewController.swift
> +        text.text = "😎"
질문을 드리기 전에 이모지를 사용하는것은 문제가 되지 않습니다.
하지만, 텍스트에 이모지를 넣게 되었을때 어떠한 애로사항이 있을 수 있을지 한번 생각해볼까요?

2022-11-29 09:03 UTC, uuu1101 commented on OpenMarket/OpenMarket/CollectionView/Grid/GridCell.swift
> +    let productName: UILabel = {
let productName: 이라고 선언하면,
사용부에서 해당 프로퍼티가 UILabel인지 ProductName을 담고 있는 String 타입인지
네이밍으로만 확인하는데에 문제는 없을까요?

2022-11-29 09:03 UTC, uuu1101 commented on OpenMarket/OpenMarket/CollectionView/Grid/GridCell.swift
> +    let price: UILabel = {
위와 동일합니다.

2022-11-29 09:03 UTC, uuu1101 commented on OpenMarket/OpenMarket/CollectionView/Grid/GridCell.swift
> +    let bargainPrice: UILabel = {
위와 동일합니다.

2022-11-29 09:03 UTC, uuu1101 commented on OpenMarket/OpenMarket/CollectionView/Grid/GridCell.swift
> +    let stock: UILabel = {
위와 동일합니다.

2022-11-29 15:09 UTC, Hashswim commented on OpenMarket/OpenMarket/ViewController.swift
>              print(product)
해당 부분 삭제했습니다..!

2022-11-29 15:11 UTC, jjpush commented on OpenMarket/OpenMarket/CollectionView/Grid/GridCell.swift
> +    let productName: UILabel = {
뒤쪽에 Label을 추가해주는 형태로 수정했습니다..!

2022-11-29 15:11 UTC, jjpush commented on OpenMarket/OpenMarket/CollectionView/Grid/GridCell.swift
> +    let price: UILabel = {
마찬가지로 뒤쪽에 Label을 추가해주는 형태로 수정했습니다..!

2022-11-29 15:12 UTC, jjpush commented on OpenMarket/OpenMarket/CollectionView/Grid/GridCell.swift
> +    let bargainPrice: UILabel = {
위와 동일하게 수정했습니다!

2022-11-29 15:12 UTC, jjpush commented on OpenMarket/OpenMarket/CollectionView/Grid/GridCell.swift
> +    let stock: UILabel = {
위와 동일하게 수정했습니다!!

2022-11-29 15:19 UTC, Hashswim commented on OpenMarket/OpenMarket/AddProductViewController.swift
> +        text.text = "😎"
text에 이모지를 넣을 경우 어떤 타입(UTF-8, UTF-16, Unicode Scalar)으로 인코딩 하냐에 따라서 값이 달라지는 애로사항이 있을 수 있습니다..
예를 들어 서버에 이모지 값을 보냈을 경우 다른 플랫폼(window, android)에서 확인했을 때 값이 이상하게 보여질 수 있을것 같습니다.

해당 부분에서 이모지를 사용했던 것은 단순하게 상품등록 화면을 빈화면으로 두기 허전해서 넣어봤습니다...🥲

2022-12-01 01:07 UTC, merged

2022-12-01 01:08 UTC, uuu1101 commented
고생하셨습니다! 다음 STEP 진행하면서 같이 고민하도록 해봐요 :)