오픈마켓2 [STEP 1] 로빈, 스톤
yagom-academy/ios-open-market pull request #230
Opened 2022-12-02 13:43 UTC by lws2269

안녕하세요 알라딘(@junbangg)! 스톤, 로빈입니다~
이번 스텝은 상품 등록, 수정, 삭제 하는 과정에서 특히(멀티파트폼ㅠㅠ) 어려웠습니다.
네트워크하는 과정이 이렇게 복잡하고 어렵구나를 다시한번 뼈아프게 느꼈습니다.
다행히 네트워크 부분 해결해서 상품등록 및 수정 UI에 적용해보았습니다.
이번 스텝은 네트워크 통신에 중점을 두었습니다. 
그리고, 아이템 리스트를 받아오는 부분에서 alert의 handler를 통해 재귀처리를 구현해보았습니다!
잘부탁드립니다! 

## 구현내용
### ItemViewController
상품을 등록과 수정에서 상속받아 사용하는 클래스로 공통으로 사용되는 로직을 담고있습니다.
- `func showAlert(title, message, actionMessage, dismiss)`
    - 같은 형식으로 사용되는 `alert`의 갯수가 많아 메서드로 분리해주었습니다.
- `@objc func doneButtonTapped()`
    - 하위 네비게이션컨트롤러의 우측 버튼으로, 하위 뷰컨트롤러에서 재정의하여 사용합니다.

### ItemAddViewController
- `@objc private func presentAlbum()`
    - 앨범에서 이미지를 가져오는 메서드입니다. 이미지가 5개 이하일 경우에만 동작합니다.
- `func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey : Any])`
    - 앨범에서 선택된 이미지를 `itemImages`와 `imageStackView`에 추가해주는 메서드입니다.
### ItemEditViewController
- `private func fetchItem()`
    - 컬렉션 뷰에서 전달받은 `itemId`을 통해 아이템의 정보를 가져오는 메서드입니다.

### NetworkManager
- createRequestBody : HTTP Request Body 만드는 메서드
    - multipart/form 구문을 처음 이하해는 것도 어려웠지만, 포스트하는데 계속 400번 에러가 나와서 힘들었습니다.ㅠㅠ
    - 오픈마켓 API 명세서를 보니 `params`가 아래와 같이 `jsonObject` 타입이었습니다.
    ![](https://i.imgur.com/bdp0pL6.png)
    - 그래서 `params`를 아래와 같이 json으로 변환하여 `createRequestBody()` 메서드로 넘겨주어서 해결하였습니다.
    
    ```swift
    guard let jsonData = try? JSONSerialization.data(withJSONObject: params) else { return }
    ```

```swift
func createRequestBody(params: [String: Data], images: [UIImage], boundary: String) -> Data {
        let newLine = "\r\n"
        let boundaryPrefix = "--\(boundary + newLine)"
        let imgDataKey = "images"
        let mimeType = "image/jpeg"
        
        var body = Data()
        
        for (key, value) in params {
            body.append(boundaryPrefix)
            body.append("Content-Disposition: form-data; name=\"\(key)\"\(newLine + newLine)")
            body.append(value)
            body.append(newLine)
        }
        
        for image in images {
            guard let imageData = image.compressTo(expectedSizeInKb: 300) else { return Data() }
            body.append(boundaryPrefix)
            body.append("Content-Disposition: form-data; name=\"\(imgDataKey)\"; filename=\"\(UUID())\"\(newLine)")
            body.append("Content-Type: \(mimeType + newLine + newLine)")
            body.append(imageData)
            body.append(newLine)
        }
        body.append("--".appending(boundary.appending("--")))
        
        return body
    }
```
- addItem : 아이템 등록하는 메서드
- deleteURI : 아이템 삭제 URI 조회하는 메서드
- deleteItem : 아이템 삭제하는 메서드
- editItem : 등록된 아이템 수정하는 메서드

### UIImage 크기 압축
- compressTo : 이미지를 파라미터로 들어온 이미지 크기이하로 압축하여 반환해줍니다.
```swift
extension UIImage {
    func compressTo(expectedSizeInKb:Int) -> Data? {
        let sizeInBytes = expectedSizeInKb * 1024
        var needCompress:Bool = true
        var imgData:Data?
        var compressingValue:CGFloat = 1.0
        
        while (needCompress && compressingValue > 0.0) {
            if let data:Data = self.jpegData(compressionQuality: compressingValue) {
            if data.count < sizeInBytes {
                needCompress = false
                imgData = data
            } else {
                compressingValue -= 0.1
            }
        }
    }
    if let data = imgData {
        if (data.count < sizeInBytes) {
            return data
        }
    }
        return nil
    }
}
```

2022-12-06 09:58 UTC, junbangg requested changes
수고하셨습니다! 요번에 작업량이 상당하셨겠습니다:) 코드가 더 깔끔해지는거 같은건 기분타일까요🤔 
댓글 참고해주세요!

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/NetworkingTests/NetworkingTests.swift
> +        sut.addItem(params: params, images: [UIImage()]){ result in
축약은 일단 피합시다..!

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +class ItemAddViewController: ItemViewController {
상속이 더 필요 없다면 Final 확인 해주세요~

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +    override func configureNavigation() {
메스드명을 봤을때 자칫하면 네비게이션 자체를 세팅하는걸로 착각할 수 있을것 같아요!

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +        guard !isPost else {
isPost == false 는 어떠신가요????
느낌표보다는 가독성이 좀 괜찮다고 생각하는 편인데 어떠신가요?? 정답은 아닙니다~

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +                    LoadingController.hideLoading()
LoadingController.hideLoading은 어떻게든 호출이 될텐데 switch 문 바로 위로 이동 시켜서 한번만 쓰는건 어떠신가요???

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +extension ItemAddViewController: UIImagePickerControllerDelegate, UINavigationControllerDelegate {
여기도 마크주석을 달아주는건 어떠십니까:)

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemEditViewController.swift
> +class ItemEditViewController: ItemViewController {
이 친구도 더이상 상속이 없다먄 final 이 괜찮겠습니다!

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +    // MARK: - Method
마크주석들이 보이는군요! 
어떤 기준으로 달기로 하셨는지 궁금합니다!

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemEditViewController.swift
> +                LoadingController.hideLoading()
요 LoadingController.hideLoading  관련해서 위에서 코멘트 남겼습니다~!

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemEditViewController.swift
> +    private func retryAlert() {
요기 갑자기 줄바꿈이 없네요!

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemEditViewController.swift
> +    private func configureData() {
여기도요!

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemEditViewController.swift
> +    private func configureData() {
메서드가 하는 일을 보면 메서드명이 맞는지 모르겠습니다..!🤔
그리고 하는 일도 좀 많아보이네요!

살짝 다른 얘기이긴한데🙋‍♂️
저는 개인적으로 메서드가 너무 많은 일을 하고있는게 아닌지 체크하는 방법이
메서드명이 짓기 쉽나?어렵나? 너무 길지는 않은가? 체크하는것입니다💁‍♂️
보통 메서드명 짓기 어려우면 하는 일이 많아서 그런거더라고요🙂

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +    private lazy var registrationImageView: UIView = {
요기도 그렇고 밑에 lazy 쓰신 이유가 어떻게 되는지 궁금합니다:)

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +        self.view.backgroundColor = .systemBackground
메서드 만들어서 넣어주는건 어떠신가요??!

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +    override func doneButtonTapped() {
요 메서드가 굉장히 기네요! 
분리할 수 있는 방법은 없을까요?🤔

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +
불필요해보이는 줄바꿈이 있네요!

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemEditViewController.swift
> +    override func doneButtonTapped() {
요 메서드도 마찬가지로 하는 일이 많아보입니다!ㅜ

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemViewController.swift
> +class ItemViewController: UIViewController {
전반적으로 final, private 필요한 부분들이 보이네요!

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemViewController.swift
> +    let imageScrollView: UIScrollView = {
다른 곳에서는 private lazy를 쓰셨은데 여기서는 안한 이유가 있나요??(틀렸다는건 아닌데 다르게 한 이유가 있을까 해서요!)

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemViewController.swift
> +    @objc func doneButtonTapped() { }
여긴 아직 구현부가 앖네요???

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/MainViewController.swift
> +    // MARK: - Private Method
어차피 해당 extension 내의 메서드들은 다 private이면 마크 주석을 extension위로 옮기는건 어떨까요???
위에도 비슷한게 많았는데 여기다 남기네요ㅎ

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Extension/UIImage+Extension.swift
> +        var needCompress:Bool = true
Bool 전에 띄어쓰기가 필요해보야요!

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Extension/UIImage+Extension.swift
> +        var compressingValue:CGFloat = 1.0
여기도요 !

2022-12-06 09:58 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemEditViewController.swift
> +        guard let itemId = itemId else { return }
스위프트 5.7 부터는
`guard let item else { return }`
되는거 아시죠?? 그렇게 중요한건 아니지만 그냥 참고요!

2022-12-07 02:57 UTC, lws2269 commented on OpenMarket/OpenMarket/Controllers/ItemEditViewController.swift
> +        guard let itemId = itemId else { return }
xcode 14버전 업데이트 이전에는 사용이 안되어서 까먹을뻔 했었는데 짚어주셔서 감사합니다!! 
앞으로 조금 더 간결한 코드 작성이 가능할 것 같아요!

2022-12-07 02:57 UTC, yuvinrho commented on OpenMarket/NetworkingTests/NetworkingTests.swift
> +        sut.addItem(params: params, images: [UIImage()]){ result in
감사합니다! `parameter`로 수정하였습니다~

2022-12-07 02:57 UTC, onestone23 commented on OpenMarket/OpenMarket/Extension/UIImage+Extension.swift
> +        var needCompress:Bool = true
처리하였습니다! 👍

2022-12-07 02:58 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +class ItemAddViewController: ItemViewController {
앗.. 놓친부분 알려주셔서 감사합니다!  아래와 같이 수정하였습니다~
```swift
final class ItemEditViewController: ItemViewController
final class ItemAddViewController: ItemViewController
```

2022-12-07 02:58 UTC, lws2269 commented on OpenMarket/OpenMarket/Controllers/MainViewController.swift
> +    // MARK: - Private Method
컨트롤러 내부에서 나뉘지 않는 부분은 모두 extension 위에 작성하는 방향으로 변경해보았습니다~!

2022-12-07 03:04 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +        guard !isPost else {
알라딘 의견대로 isPost == false가 가독성이 좋은듯 하여 수정해주었습니다. 감사합니다~

2022-12-07 03:06 UTC, lws2269 commented on OpenMarket/OpenMarket/Controllers/ItemViewController.swift
> +    @objc func doneButtonTapped() { }
`ItemViewController`를 상속받는 `ItemAddViewController` `ItemEditViewController` 두 클래스에서 재정의하여 사용하였는데, 
`configureNavigation`함수의 공통되는 부분을 상위 클래스에서 정의하고, 서브클래스에서 재정의하여 사용하다보니 네비게이션 버튼에 대한 Action을 정의해주기 위해 상위 클래스에서 빈 구현부로 작성했었습니다.

>>>
리팩토링 과정에서 `ItemAddViewController` `ItemEditViewController` 두 클래스의 로직이 완전 동일하여 `ItemViewController`의 `doneButtonTapped()`구현부를 작성해주고 하위 클래스에서의 재정의하는 부분을 제거해주었습니다!

2022-12-07 03:06 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +                    LoadingController.hideLoading()
아하~ 그렇네요!  `LoadingController.hideLoading` 을 스위치문 바로 위로 올려주었습니다~

2022-12-07 03:07 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +extension ItemAddViewController: UIImagePickerControllerDelegate, UINavigationControllerDelegate {
오! 좋은 의견이라고 생각합니다~
코드 전체적으로 마크주석을 달아주면 좋을것 같은 부분은 마크주석을 달아주었습니다!

2022-12-07 03:08 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/ItemEditViewController.swift
> +class ItemEditViewController: ItemViewController {
감사합니다~~ final 키워드를 붙여주었습니다!

2022-12-07 03:10 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +    // MARK: - Method
뷰컨트롤에서 기본적으로 프로퍼티, 메소드, 라이프사이클 이렇게 세 부분으로 나눠주었고, 익스텐션하여 프로토콜 채택해준 부분은 추가로 마크주석을 달아주었습니다~

2022-12-07 03:11 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/ItemEditViewController.swift
> +                LoadingController.hideLoading()
위 코멘트 답글과 동일하게 ` LoadingController.hideLoading`을 스위치 문 위로 올려주었습니다~

2022-12-07 03:12 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/ItemEditViewController.swift
> +    private func retryAlert() {
앗..😅 줄바꿈 수정하였습니다~~

2022-12-07 03:12 UTC, lws2269 commented on OpenMarket/OpenMarket/Controllers/ItemEditViewController.swift
> +    private func configureData() {
맞아요..!! 하는 일이 많아 네이밍에 어려움이 있어 통용되는 의미를 채택하다 보니 Data라는 단어가 나온 것같습니다!
이미지에 관한 메서드,  텍스트 값들에 필요한 메서드 두가지 메서드로 분리해보았습니다!
메서드에 대한 꿀팁 감사합니다!👍👍👍👍👍👍👍👍👍👍👍

2022-12-07 03:12 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/ItemEditViewController.swift
> +    private func configureData() {
여기도 수정해주었습니다. 감사합니다~~

2022-12-07 03:12 UTC, lws2269 commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +        self.view.backgroundColor = .systemBackground
메서드 사이에 프로퍼티 값을 세팅하는 부분이 어색하게 느껴지긴해서 고민했던 부분인데 시원하게 긁어주셔서 감사합니다!!
메서드로 분리하였습니다~!

2022-12-07 03:16 UTC, lws2269 commented on OpenMarket/OpenMarket/Controllers/ItemViewController.swift
> +class ItemViewController: UIViewController {
`ItemAddViewController`, `ItemEditViewController`의 상위클래스이고 하위클래스에서 접근해야하다보니 접근제어자에 대한 처리를 따로 해주지 않았습니다..!
final 키워드 또한 상속해야하는 클래스이다보니 작성할 수 없을 것 같습니다!

2022-12-07 03:18 UTC, lws2269 commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +    override func doneButtonTapped() {
값에 대한 유효성 체크하는 부분과 parameter를 생성하는 부분을 같이 분리해보았는데 더 좋은 방법이 있을까요!?

2022-12-07 03:19 UTC, lws2269 commented on OpenMarket/OpenMarket/Controllers/ItemEditViewController.swift
> +    override func doneButtonTapped() {
itemAddViewController와 하는 일이 완전히 동일하여 상위 클래스로 이사후 리팩토링 하였습니다!

2022-12-07 03:20 UTC, lws2269 commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +    private lazy var registrationImageView: UIView = {
해당 부분은 let으로 선언되어도 무관하다고 생각합니다!
저희가 꼭 필요한 부분에만 lazy를 채택하기로 했었는데 이부분이 누락된 것 같습니다!

2022-12-07 03:23 UTC, yuvinrho commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +    override func configureNavigation() {
`ItemAddViewController` 화면으로 이동할 때, 부모클래스(`ItemViewController`)의 `configureNavigation()`가 호출되기 때문에 `configureNavigation()`를 오버라이드하여 네비게이션 타이틀을 설정해주기 위함이었습니다. 그러면 오버라이드보다 따로 네비게이션 타이틀 설정하는 메서드를 viewDidLoad() 쪽에서 호출해주는게 나을지 알라딘의 의견이 궁금합니다~~

2022-12-08 00:56 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemAddViewController.swift
> +    override func configureNavigation() {
음 부모클래스의 configureNavigation 메서드명을 조금 더 친절하게 바꿔준다면 해걀이 될것 같은데요??만약에 configureNavigation 의 역할과 네비게이션 타이틀 수정하는게 안맞다면 로빈 밀씀대로 하는갓도 좋구여!

2022-12-08 00:57 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemViewController.swift
> +class ItemViewController: UIViewController {
아 요친구가 왕뷰컨이었군요 ㅎㅎ 제가 놓쳤었네요!!

2022-12-08 01:09 UTC, junbangg approved these changes
수고하셨습니다~

2022-12-08 01:09 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemEditViewController.swift
> +    private func configureImageValue() {
Value 대신 그냥 Images 는 어떠신가요??

2022-12-08 01:09 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemEditViewController.swift
> +    private func configureUIValue() {
뒤에 밸류는 빼도 될것 같아요 개인적으로는..!

2022-12-08 01:09 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/ItemViewController.swift
> +                                     "secret": NetworkManager.secret]
딕셔너리 인덴트 정리가 필요해보이네요!

2022-12-08 01:09 UTC, junbangg commented on OpenMarket/OpenMarket/Controllers/MainViewController.swift
> +                LoadingController.hideLoading()
여기 130, 137 줄에 있는 hideLoading 스위치문 위로 변경하면 좋을것 같아요!

2022-12-08 01:09 UTC, merged