오픈마켓II [STEP 1] Mangdi, Woong
yagom-academy/ios-open-market pull request #232
Opened 2022-12-05 14:10 UTC by MangDi-L

@SungPyo  안녕하세요 웨더!
초반에 multipart/form-data 구성을 파악하느라 시간을 많이 뺏겼습니다 ㅠㅠ
이번 프로젝트 진짜 역대급으로 어려운것같아요 ㅎㅎㅎ
많이 부족하지만 이번에도 코드리뷰 잘 부탁드립니다!

## 🤔 고민했던 점
- **상태코드 413**
이미지 5장을 넣어주었을때 요구사항대로 이미지 각각 300kb용량이 넘어가지 않음을 확인했습니다. (300000byte == 300kb)
```swift
데이터크기: 295226bytes
데이터크기: 211832bytes
데이터크기: 298155bytes
데이터크기: 273927bytes
데이터크기: 167566bytes
POST CODE Error : <<413>>
```
그런데 413오류가 떠서 이것에 대해 찾아봤는데 요청 엔터티가 서버에 의해 정의된 제한보다 크다는 것을 나타낸다고 합니다.
요구사항대로 각각의 이미지가 300kb를 넘지 않도록 준수했는데 왜 이런 상태코드가 나오게 된걸까 고민해보았습니다.
고민해보다가 요구사항엔 이미지 '총 용량'에 대해선 언급이 없지만 있을것같단 생각이 들었습니다.
왜 이런생각이 들었냐 하면 jpegData(compressionQuality:) 메서드의 compressionQuality 값을 0.99에서 0.2로 설정하고 post를 보내봤는데
```swift
데이터크기: 26358bytes
데이터크기: 29516bytes
데이터크기: 27742bytes
데이터크기: 42750bytes
데이터크기: 44020bytes
```
5장 다 보내지는것을 확인했습니다.
이점을 보았을때 보내는 이미지 총 용량이 있기때문에 제한이 걸린게 아닌가 추측해보았습니다. (사실은 잘 모르겠어요)

- **DiskCache 구현에 관해서**
```swift
guard let imageUrl = URL(string: imageSource) else { return }
        guard let path = NSSearchPathForDirectoriesInDomains(.cachesDirectory,
                                                             .userDomainMask,
                                                             true).first else { return }
        var filePath = URL(fileURLWithPath: path)
        filePath.appendPathComponent(imageUrl.lastPathComponent)
        
        if fileManager.fileExists(atPath: filePath.path) != true {
```
저희는 앱 종료 후, 다시 켰을 때 filePath가 변하더라도 코드가 문제없이 잘 작동한다 라고 최종적으로 판단하였습니다.

- **문제점 :**
1. 앱 종료 시, .../Library-Cache의 폴더 경로가 변한다는 것 
2. 따라서, 위 보기의 코드의 조건문:if절로 들어갈 때, 변하기 이 전 경로에서 파일을 탐색하므로 true의 결과로 계속해서 파일을 생성하게 된다는 점.

- **저희가 다시 코드를 보며 생각한 점 :**
1. 앱을 종료했다가 다시 켰음에도 파일을 생성하진 않는다. 이것은 왜일까?
2. path 변수에 할당한 경로를 종료 전 경로/종료 후 경로를 비교해보고, 두 폴더가 전부 살아있을까? 만약, 새롭게 생성되었다면 기존의 폴더는 삭제 되는 것인가?
---
```
// print(path)를 했을 때의 결과
// - 종료 전
.../E6F80671-DE6F-43A2-9043-D620A7533C28/Library/Caches

// - 종료 후 재실행
.../7E0C224F-721F-4684-9EDB-2B2BC993AB49/Library/Caches

```
위를 비교해보았습니다.   
저희는 종료 전의 경로와 종료 후 경로를 비교해보고, 두 폴더에 접근 해보았습니다.   
먼저 종료 후의 경로의 폴더를 실행하였는데요.  
종료 전 경로로 terminal을 통해 open. 을 해 봤을 때,   
종료 후 경로의 폴더와 같은 폴더가 실행되었습니다.   
이상하더라구요. 종료 전의 경로를 실행했는데 종료 후의 경로로 접근되다니...?

이 때문에 filePath의 값이 종료 전 후와 다르더라도 문제없이 잘 작동했던 것이 아닐까? 하는 생각이 들었습니다.

결론 : filePath를 종료 전의 경로값으로 지정하였지만, filePath가 종료 후 재실행한 경로값으로 변경되더라도 종료 전 경로값으로 해당 폴더로 접근하면 자동으로 종료 후 경로로 연결해준다. 따라서, 이 코드는 변경되지 않아도 될 것이다. 라고 판단하였습니다.

## 🙏 조언을 얻고 싶은 부분
- **이미지 용량 조절**
이미지 용량이 300KB를 초과하지 않도록 jpegData(compressionQuality:) 메서드를 이용하여 구현해주었습니다.
이미지 용량이 300000byte (약 300kb) 이상이면 compressionQuality를 0.01씩 낮추고 재귀함수로 호출하게해서 결국 300kb 이하가 되게 구현했는데 만약 이미지 용량이 너무 크다면 그만큼 재귀함수가 많이 호출이 되어 오버헤드가 증가하게 될것 같습니다.
웨더라면 어떤 방식으로 이미지 용량을 조절해주실지 궁금합니다!
    ```Swift
    private func compressQualityImage(image: UIImage, value: Double) -> Data? {
        guard let imageData = image.jpegData(compressionQuality: value) else { return nil }
        if imageData.count >= 300000 {
            return compressQualityImage(image: image, value: value - 0.01)
        }
        return imageData
    }
    ```
 - **키보드를 꺼낼때 보여줄 화면 설정**

상품등록화면에서 textField를 클릭 했을때랑 textView를 클릭했을때 두가지로 나누어서 키보드와 함께 화면을 어떻게 보여줄지 구현해보았습니다.
textField를 클릭하면 사용자가 바로 textField 입력란에 신경을 쓸수 있도록 아래와 같이 보이게 했습니다.
textView를 클릭하면 textView를 키보드가 가리지 않게 설정해주었습니다.
여기서 textField를 클릭했을때 이미지를 추가하는 부분은 잘 보이지 않게됩니다.
원래 의도는 textField에 값을 입력하려고 클릭한거니까 textField부분에 focus를 둔건데 위의 이미지는 보이지않게되니 단점이 될것같다고도 느꼈습니다. 어떻게 디자인 해주는것이 좋은가 고민이 되었습니다. 웨더라면은 어떻게 설정해주셨을지 궁금합니다.
|일반화면|textField클릭|
|:--:|:--:|
|![](https://i.imgur.com/AueSfk5.png)|![](https://i.imgur.com/5nBdtu5.png)|
|**textView클릭**|
|![](https://i.imgur.com/9O3jgQc.png)
| |

- **MVC패턴 관련**
 이번과 같이 기능이 많은 앱을 3주 이상 장기적으로 구현하다보니 자연스럽게 함수들의 기능과 뷰의 요소 및 로직이 많아졌습니다. 하지만, 뷰를 그려주는 부분을 담당하는 코드가 VC, ResisterViewController 등에 나타나 있는 등 몇가지 예제로 보던 MVC패턴을 준수하는 코드와는 다소 다른부분이 있는데 어떤 방향으로 수정해주면 좋을까요?
현재로서는 MVC패턴을 개념으로는 많이 접하였지만, 직접적인 코드로는 많이 접해보지 못하여 저희 코드에서 어떤 요소들이 뷰에 있어야하며 어떤 요소들이 모델에 있어야하는지 명확하게 분리되지 못하고 있는 것 같습니다. 이 부분에 대해서 조언해주시면 감사합니다!

2022-12-05 17:38 UTC, SungPyo commented
> 상품등록화면에서 textField를 클릭 했을때랑 textView를 클릭했을때 두가지로 나누어서 키보드와 함께 화면을 어떻게 보여줄지 구현해보았습니다.
> textField를 클릭하면 사용자가 바로 textField 입력란에 신경을 쓸수 있도록 아래와 같이 보이게 했습니다.
> textView를 클릭하면 textView를 키보드가 가리지 않게 설정해주었습니다.
> 여기서 textField를 클릭했을때 이미지를 추가하는 부분은 잘 보이지 않게됩니다.
> 원래 의도는 textField에 값을 입력하려고 클릭한거니까 textField부분에 focus를 둔건데 위의 이미지는 보이지않게되니 단점이 될것같다고도 느꼈습니다. 어떻게 디자인 해주는것이 좋은가 고민이 되었습니다. 웨더라면은 어떻게 설정해주셨을지 궁금합니다.



> @SungPyo 안녕하세요 웨더! 초반에 multipart/form-data 구성을 파악하느라 시간을 많이 뺏겼습니다 ㅠㅠ 이번 프로젝트 진짜 역대급으로 어려운것같아요 ㅎㅎㅎ 많이 부족하지만 이번에도 코드리뷰 잘 부탁드립니다!
> 
> ## 🤔 고민했던 점
> * **상태코드 413**
>   이미지 5장을 넣어주었을때 요구사항대로 이미지 각각 300kb용량이 넘어가지 않음을 확인했습니다. (300000byte == 300kb)
> 
> ```swift
> 데이터크기: 295226bytes
> 데이터크기: 211832bytes
> 데이터크기: 298155bytes
> 데이터크기: 273927bytes
> 데이터크기: 167566bytes
> POST CODE Error : <<413>>
> ```
> 
> 그런데 413오류가 떠서 이것에 대해 찾아봤는데 요청 엔터티가 서버에 의해 정의된 제한보다 크다는 것을 나타낸다고 합니다. 요구사항대로 각각의 이미지가 300kb를 넘지 않도록 준수했는데 왜 이런 상태코드가 나오게 된걸까 고민해보았습니다. 고민해보다가 요구사항엔 이미지 '총 용량'에 대해선 언급이 없지만 있을것같단 생각이 들었습니다. 왜 이런생각이 들었냐 하면 jpegData(compressionQuality:) 메서드의 compressionQuality 값을 0.99에서 0.2로 설정하고 post를 보내봤는데
> 
> ```swift
> 데이터크기: 26358bytes
> 데이터크기: 29516bytes
> 데이터크기: 27742bytes
> 데이터크기: 42750bytes
> 데이터크기: 44020bytes
> ```
> 
> 5장 다 보내지는것을 확인했습니다. 이점을 보았을때 보내는 이미지 총 용량이 있기때문에 제한이 걸린게 아닌가 추측해보았습니다. (사실은 잘 모르겠어요)
> 
> * **DiskCache 구현에 관해서**
> 
> ```swift
> guard let imageUrl = URL(string: imageSource) else { return }
>         guard let path = NSSearchPathForDirectoriesInDomains(.cachesDirectory,
>                                                              .userDomainMask,
>                                                              true).first else { return }
>         var filePath = URL(fileURLWithPath: path)
>         filePath.appendPathComponent(imageUrl.lastPathComponent)
>         
>         if fileManager.fileExists(atPath: filePath.path) != true {
> ```
> 
> 저희는 앱 종료 후, 다시 켰을 때 filePath가 변하더라도 코드가 문제없이 잘 작동한다 라고 최종적으로 판단하였습니다.
> 
> * **문제점 :**
> 
> 1. 앱 종료 시, .../Library-Cache의 폴더 경로가 변한다는 것
> 2. 따라서, 위 보기의 코드의 조건문:if절로 들어갈 때, 변하기 이 전 경로에서 파일을 탐색하므로 true의 결과로 계속해서 파일을 생성하게 된다는 점.
> 
> * **저희가 다시 코드를 보며 생각한 점 :**
> 
> 1. 앱을 종료했다가 다시 켰음에도 파일을 생성하진 않는다. 이것은 왜일까?
> 2. path 변수에 할당한 경로를 종료 전 경로/종료 후 경로를 비교해보고, 두 폴더가 전부 살아있을까? 만약, 새롭게 생성되었다면 기존의 폴더는 삭제 되는 것인가?
> 
> ```
> // print(path)를 했을 때의 결과
> // - 종료 전
> .../E6F80671-DE6F-43A2-9043-D620A7533C28/Library/Caches
> 
> // - 종료 후 재실행
> .../7E0C224F-721F-4684-9EDB-2B2BC993AB49/Library/Caches
> ```
> 
> 위를 비교해보았습니다. 저희는 종료 전의 경로와 종료 후 경로를 비교해보고, 두 폴더에 접근 해보았습니다. 먼저 종료 후의 경로의 폴더를 실행하였는데요. 종료 전 경로로 terminal을 통해 open. 을 해 봤을 때, 종료 후 경로의 폴더와 같은 폴더가 실행되었습니다. 이상하더라구요. 종료 전의 경로를 실행했는데 종료 후의 경로로 접근되다니...?
> 
> 이 때문에 filePath의 값이 종료 전 후와 다르더라도 문제없이 잘 작동했던 것이 아닐까? 하는 생각이 들었습니다.
> 
> 결론 : filePath를 종료 전의 경로값으로 지정하였지만, filePath가 종료 후 재실행한 경로값으로 변경되더라도 종료 전 경로값으로 해당 폴더로 접근하면 자동으로 종료 후 경로로 연결해준다. 따라서, 이 코드는 변경되지 않아도 될 것이다. 라고 판단하였습니다.
> 
> ## 🙏 조언을 얻고 싶은 부분
> * **이미지 용량 조절**
>   이미지 용량이 300KB를 초과하지 않도록 jpegData(compressionQuality:) 메서드를 이용하여 구현해주었습니다.
>   이미지 용량이 300000byte (약 300kb) 이상이면 compressionQuality를 0.01씩 낮추고 재귀함수로 호출하게해서 결국 300kb 이하가 되게 구현했는데 만약 이미지 용량이 너무 크다면 그만큼 재귀함수가 많이 호출이 되어 오버헤드가 증가하게 될것 같습니다.
>   웨더라면 어떤 방식으로 이미지 용량을 조절해주실지 궁금합니다!
>   ```swift
>   private func compressQualityImage(image: UIImage, value: Double) -> Data? {
>       guard let imageData = image.jpegData(compressionQuality: value) else { return nil }
>       if imageData.count >= 300000 {
>           return compressQualityImage(image: image, value: value - 0.01)
>       }
>       return imageData
>   }
>   ```
ㄴ `꼬리재귀를 사용해보면 어떨까요? :) 저도 결국 for문이든 while 문이든 재귀든 할것 같은데요?`

> * **키보드를 꺼낼때 보여줄 화면 설정**
> 
> 상품등록화면에서 textField를 클릭 했을때랑 textView를 클릭했을때 두가지로 나누어서 키보드와 함께 화면을 어떻게 보여줄지 구현해보았습니다. textField를 클릭하면 사용자가 바로 textField 입력란에 신경을 쓸수 있도록 아래와 같이 보이게 했습니다. textView를 클릭하면 textView를 키보드가 가리지 않게 설정해주었습니다. 여기서 textField를 클릭했을때 이미지를 추가하는 부분은 잘 보이지 않게됩니다. 원래 의도는 textField에 값을 입력하려고 클릭한거니까 textField부분에 focus를 둔건데 위의 이미지는 보이지않게되니 단점이 될것같다고도 느꼈습니다. 어떻게 디자인 해주는것이 좋은가 고민이 되었습니다. 웨더라면은 어떻게 설정해주셨을지 궁금합니다.
> 
> 일반화면	textField클릭
> ![](https://camo.githubusercontent.com/9ce3ca14082c20a81eb3f5f5b2752fda493f6d2787ec6c5fcc2ceee821237d2c/68747470733a2f2f692e696d6775722e636f6d2f41756553666b352e706e67)	![](https://camo.githubusercontent.com/033132cdc461c1bbcb91e141e253e3d462d2baee4283ba57a64632b66201ec17/68747470733a2f2f692e696d6775722e636f6d2f356e42647475352e706e67)
> **textView클릭**	
> ![](https://camo.githubusercontent.com/94d12a33bda9dd8f400cc413e4be8d810db13feca06a6f55339afd30cb6e6246/68747470733a2f2f692e696d6775722e636f6d2f394f336a6751632e706e67)	
ㄴ `말씀하신대로 이건 개발의 영역이 아닌 기획과 디자인의 영역입니다. 기획과 디자인이 어떻게 나오냐에 따라서 방향이 정해질 것 같아요. :) 입력 부분과 별개로 맨 위 사진추가도 할 수 있도록 스크롤 할 수 있게 제안 정도는 할 수 있을 것 같네요.`

> * **MVC패턴 관련**
>   이번과 같이 기능이 많은 앱을 3주 이상 장기적으로 구현하다보니 자연스럽게 함수들의 기능과 뷰의 요소 및 로직이 많아졌습니다. 하지만, 뷰를 그려주는 부분을 담당하는 코드가 VC, ResisterViewController 등에 나타나 있는 등 몇가지 예제로 보던 MVC패턴을 준수하는 코드와는 다소 다른부분이 있는데 어떤 방향으로 수정해주면 좋을까요?
>   현재로서는 MVC패턴을 개념으로는 많이 접하였지만, 직접적인 코드로는 많이 접해보지 못하여 저희 코드에서 어떤 요소들이 뷰에 있어야하며 어떤 요소들이 모델에 있어야하는지 명확하게 분리되지 못하고 있는 것 같습니다. 이 부분에 대해서 조언해주시면 감사합니다!
ㄴ `음 MVC 패턴 그대로 비즈니스 로직과 뷰는 VC에 그 외 필요한 데이터들은 모델에.. 제가 보기에 특별히 이상하다고 생각되는 부분은 따로 없어요. 굳이 꼽자면 네트워크 관련 부분이나 extension들이 모델 폴더 내부에 있는거...? 혹시 불편하신게 있나요?`

2022-12-05 18:20 UTC, SungPyo commented on OpenMarket/OpenMarket/Controller/ViewController.swift
>          networkCommunication.requestProductsInformation(
접근 제한자는 왜 빼신거에요?

2022-12-05 18:30 UTC, SungPyo requested changes
기능 구현은 다 잘 되신것 같아요 :) 그래서 추가적으로 기존 코드에서 추가적으로 질문을 더 드려볼까 합니다.

1. ViewController
`func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {`
내부에 `activityIndicatorView.stopAnimating()` 이 첫번째 줄에 있는데요. cellForItemAt의 경우는 cell이 그려지는 갯수만큼 호출됩니다. 그렇다면 해당 코드의 위치는 의도하신 걸까요?

2. CustomCollectionViewCell
셀이 그러질때 `func configureImage(imageSource: String) {` 를 계속 호출합니다. 응답이 오기 전 셀이 재사용 된다면 어떤 문제가 발생할까요?

3. 메모리 캐시도 함께 추가해 주셨으면 좋겠어요 :)

마지막이니 만큼 기존 코드들을 한번 정리해 봅시다.

2022-12-06 08:19 UTC, iOS-Woong commented
1. ViewController`func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {`내부에 `activityIndicatorView.stopAnimating()` 이 첫번째 줄에 있는데요. cellForItemAt의 경우는 cell이 그려지는 갯수만큼 호출됩니다. 그렇다면 해당 코드의 위치는 의도하신 걸까요?

    - [432219a](https://github.com/yagom-academy/ios-open-market/pull/232/commits/432219a425d4f98c2cd8a73c5a910a6087673150)
    
    - 처음에 콜렉션뷰에 이미지가 그려지기 시작하면 indicator의 애니메이팅을 멈추도록 했습니다. 
    - 그런데 질문해주신것처럼.
    - cell이 그려질때마다 불필요한 호출이 있다는것을 확인했습니다.
    - 여기서 개선이 필요하다는것을 느끼고 컬렉션뷰의 각 이미지마다 indicator를 달아서 비동기로 가져오는게 완료된 그 순간에 애니메이팅을 멈추도록 새롭게 구현해주었습니다.

---

2. CustomCollectionViewCell셀이 그러질때 `func configureImage(imageSource: String) {` 를 계속 호출합니다. 응답이 오기 전 셀이 재사용 된다면 어떤 문제가 발생할까요?

    - 비동기처리로 해당 셀에 대한 이미지가 들어올때 스크롤을 아래나 위로 휙휙 이동했을경우 셀의 재사용으로 인해 원래 '10'이라는 이미지가 보여야할곳에 이제막 비동기처리를 끝낸 엉뚱한'3'이라는 이미지가 보여지는 것 같습니다.
    - 그래서 이 문제는 재사용을 거치는 prepareForReuse() 메서드 안에서 모든 요소들을 초기화 (nil) 해주어야 해결이 가능할거란 생각이 들었습니다.
    - 하지만 이렇게 처리를 해주어도 셀에 엉뚱한 이미지가 들어오는건 해결할 수 없었습니다.
    - 다행스럽게도 엉뚱한 이미지가 들어와있어도 잠깐 위아래로 스크롤하다 돌아오면 정상적인 이미지로 변경된걸 확인하였습니다.
    - 결론적으로 이 문제는 prepareForReuse()로 초기화해주면 해결이 될거라 생각했는데 아니어서 어떻게 해결할수 있을까 생각해보았는데 답이 나오지 않네요..ㅎㅎ 혹시 조그만 힌트라도 알려주신다면 정말 감사합니다..🙏

---

3. 메모리 캐시도 함께 추가해 주셨으면 좋겠어요 :)
메모리 캐시도 함께 추가했습니다!

    - [364dc32](https://github.com/yagom-academy/ios-open-market/pull/232/commits/364dc3260ff5a7c4dde23a56587d88a2b1b644c2)

|앱 처음 실행했을때|앱 다시 실행했을때|
|:--:|:--:|
|![networkandmemory](https://user-images.githubusercontent.com/96489602/205856689-dbb21584-19d7-4cae-9e57-8ed76d160127.gif)|![diskandMemory](https://user-images.githubusercontent.com/96489602/205856739-4f8c44cf-fe36-4112-b871-8aa32f94628f.gif)|

2022-12-06 08:26 UTC, MangDi-L commented on OpenMarket/OpenMarket/Controller/ViewController.swift
>          networkCommunication.requestProductsInformation(
오잉.. 저희도 모르는사이에 삭제되었네요
다시 수정했습니다!
[e81e2ef](https://github.com/yagom-academy/ios-open-market/pull/232/commits/e81e2efa8dba6a9efb4aefe1e009b67ceee8e59c)

2022-12-06 16:30 UTC, SungPyo commented
> 1. ViewController`func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {`내부에 `activityIndicatorView.stopAnimating()` 이 첫번째 줄에 있는데요. cellForItemAt의 경우는 cell이 그려지는 갯수만큼 호출됩니다. 그렇다면 해당 코드의 위치는 의도하신 걸까요?
>    
>    * [432219a](https://github.com/yagom-academy/ios-open-market/pull/232/commits/432219a425d4f98c2cd8a73c5a910a6087673150)
>    * 처음에 콜렉션뷰에 이미지가 그려지기 시작하면 indicator의 애니메이팅을 멈추도록 했습니다.
>    * 그런데 질문해주신것처럼.
>    * cell이 그려질때마다 불필요한 호출이 있다는것을 확인했습니다.
>    * 여기서 개선이 필요하다는것을 느끼고 컬렉션뷰의 각 이미지마다 indicator를 달아서 비동기로 가져오는게 완료된 그 순간에 애니메이팅을 멈추도록 새롭게 구현해주었습니다.
ㄴ `👏`
> 
> 2. CustomCollectionViewCell셀이 그러질때 `func configureImage(imageSource: String) {` 를 계속 호출합니다. 응답이 오기 전 셀이 재사용 된다면 어떤 문제가 발생할까요?
>    
>    * 비동기처리로 해당 셀에 대한 이미지가 들어올때 스크롤을 아래나 위로 휙휙 이동했을경우 셀의 재사용으로 인해 원래 '10'이라는 이미지가 보여야할곳에 이제막 비동기처리를 끝낸 엉뚱한'3'이라는 이미지가 보여지는 것 같습니다.
>    * 그래서 이 문제는 재사용을 거치는 prepareForReuse() 메서드 안에서 모든 요소들을 초기화 (nil) 해주어야 해결이 가능할거란 생각이 들었습니다.
>    * 하지만 이렇게 처리를 해주어도 셀에 엉뚱한 이미지가 들어오는건 해결할 수 없었습니다.
>    * 다행스럽게도 엉뚱한 이미지가 들어와있어도 잠깐 위아래로 스크롤하다 돌아오면 정상적인 이미지로 변경된걸 확인하였습니다.
>    * 결론적으로 이 문제는 prepareForReuse()로 초기화해주면 해결이 될거라 생각했는데 아니어서 어떻게 해결할수 있을까 생각해보았는데 답이 나오지 않네요..ㅎㅎ 혹시 조그만 힌트라도 알려주신다면 정말 감사합니다..🙏
ㄴ `음.. 재사용하는 셀이 가진 요청이 유효한지 검사할 수 있고, 그 요청이 올바른 요청(올바른 순서)인지 검사할 수도 있습니다. 검사에 따라 올바른 이미지를 삽입하면 되겠죠? 이미지 삽입에 대한 디테일한 부분도 올바른 방법이 한가지는 아니니 마음에 드는 방식을 고민해 보시면 좋을 것 같아요.`
> 
> 3. 메모리 캐시도 함께 추가해 주셨으면 좋겠어요 :)
>    메모리 캐시도 함께 추가했습니다!
ㄴ`👏`
>    
>    * [364dc32](https://github.com/yagom-academy/ios-open-market/pull/232/commits/364dc3260ff5a7c4dde23a56587d88a2b1b644c2)
> 
> 앱 처음 실행했을때	앱 다시 실행했을때
> ![networkandmemory](https://user-images.githubusercontent.com/96489602/205856689-dbb21584-19d7-4cae-9e57-8ed76d160127.gif)	![diskandMemory](https://user-images.githubusercontent.com/96489602/205856739-4f8c44cf-fe36-4112-b871-8aa32f94628f.gif)

2022-12-06 16:31 UTC, SungPyo commented
고생하셨습니다.

2번 문제를 해결하시면서 셀의 오토레이아웃 에러도 함께 수정해주시면 좋을 것 같아요 :)

이렇게 두가지 먼저 진행해볼까요?

2022-12-08 18:18 UTC, MangDi-L commented
늦은시간임에도 불구하고 디코에 오시고 설명해주셔서 감사합니다 웨더! 덕분에 꽉 막힌부분이 해결되었습니다 ㅎㅎ
2가지 모두 수정 완료했습니다!
오토레이아웃 수정 [1128a96](https://github.com/yagom-academy/ios-open-market/pull/232/commits/1128a967d22e74ff1fcc7f924b5b7549afd9d9b2)
셀 재사용문제 해결 [ee621ce](https://github.com/yagom-academy/ios-open-market/pull/232/commits/ee621ce3ec86cb0deef230c812fdf455206d851f)

2022-12-12 05:10 UTC, SungPyo approved these changes
고생하셨습니다.
취소하는 방향으로 잡았군요 :)

2022-12-12 05:10 UTC, merged