오픈마켓 II [STEP 1] 아얀, 준호
yagom-academy/ios-open-market pull request #233
Opened 2022-12-06 02:31 UTC by junho15

안녕하세요, 태태(@uuu1101)🙇‍🙇‍🙇‍♀️!
오픈마켓 2 Step1 구현을 완료해서 PR보냅니다!!!😁
나름 최선을 다해서 이것저것 구현해 보느냐고 오래 걸렸습니다 😵‍💫
이번 Step도 잘 부탁드립니다!!
궁금한 부분은 코드에 코멘트 남겨놨습니다!!!
[Ayaan🦖](https://github.com/oneStar92), [준호](https://github.com/junho15)

# 📍고민했던 부분 

## NetWork 통신 역할
- URLSession에 API 통신과 관련된 기능을 extension을 통해 구현했었습니다. POP의 관점에서 구현해 보고자하여 기능별로 프로토콜을 만들어서 `URLSession` 이 채택하도록 구현했습니다.
- 하지만, URLSession이 OpenMarketAPI의 작업들을 메서드로 가지고 있는 것은 URLSession의 역할이 아니라고 생각했습니다.
- NetworkManager Type이 URLSession을 이용해 네트워크 통신을 하도록 구현했습니다.
- NetworkManager는 생성될 때 OpenMarketAPI를 주입받으며 그에 따른 네트워크 작업을 수행합니다.

## ImagePicker
- 제품 등록 및 수정에서 이미지를 등록하고, 보여주는 View를 `CollectionView`와 `ScrollView`중 어떤 것을 사용해서 구현할지에 대한 고민을 했습니다.

- `CollectionView`
    - `CollectionView`의 마지막에 `ImagePicker`를 띄어주는 Button이 위치해야 함으로 `footerView`를 이용해 구현하려고 했습니다.
    - `Section`의 `footerView`는 가로의 끝이 아닌 세로의 끝에만 위치될 수 있는 문제가 있었습니다.
    - 해당 문제를 해결하고자 마지막 Cell에 `StackView`에 Content에 해당하는 `View`를 담아줌으로써 해당 문제를 해결했습니다.

|문제 발생|해결|
|:---:|:---:|
|<img src="https://i.imgur.com/iwMdsUD.png" width="200">|<img src="https://i.imgur.com/hhafwQN.png" width="200">|

- `ScrollView`
    - `ScrollView`에 `StackView`를 위치시키고 `StackView`에 `ImageView`와 `Button`을 `addArrangedSubview()`해주었습니다.
    - 하지만 `ImageView`와 `Button`에 고유크기를 지정해 주어도 `StackView`에 `addArrangedSubview()`하게되면 지정해준 크기는 무시되고 `StackView`의 정렬기준에 의해 크기가 변경되는 문제가 발생했습니다.
    - `ImageView`와 `Button`을 `StackView`에 `addArrangedSubview()`해줄때 `Constraint`를 직접 작성해주어 해당 문제를 해결했습니다.
- `CollectionView`와 `StackView` 중에서 어떤 것을 사용할지 고민하다 두개 다 구현해 봤으며, 최종적으로는 `CollectionView` 를 사용해서 구현했습니다.

|문제 발생|해결|
|:---:|:---:|
|<img src="https://i.imgur.com/7anNkVz.png" width="200">|<img src="https://i.imgur.com/gKUfwHK.png" width="200">|

## 상품 등록시 최소 요구사항 충족 확인
- 상품 등록시에 이미지는 최소 1장, 이름은 최소 3글자, 가격은 기본값 없음, 설명은 최소 10글자가 필요했습니다.
- 해당 기능을 구현하기 위해서 done버튼을 클릭시 최소 조건이 맞는지 일일이 확인하여 조건이 맞으면 done버튼의 기능을 수행하도록 구현하려 했습니다.
- 사용자가 조건을 충족했는지 확인하기 위해서는 done버튼을 클릭해 봐야 되는 문제가 발생했고, `NotificationCenter`를 이용해 정보가 수정되면 수정된 항목은 조건을 충족하는지 확인하고 모든 항목이 충족되면 done버튼을 활성화 시켜서 해당 문제를 해결했습니다.

```swift
    private func setUpNotification() {
        ...
        NotificationCenter.default.addObserver(self,
                                               selector: #selector(checkEnoughContents),
                                               name: UITextField.textDidChangeNotification,
                                               object: nil)
        NotificationCenter.default.addObserver(self,
                                               selector: #selector(checkEnoughContents),
                                               name: UITextView.textDidChangeNotification,
                                               object: nil)
    }
```

## 상품 List PageNation
- 상품 List를 스크롤할 때 다음 Page에 해당하는 값을 불러오도록 하는 기능을 두가지 방법중 어떤 방법을 통해서 구현할지 고민했습니다.
    - extension UIScrollView 활용
        - 일정 수준 스크롤이 내려가면 다음 페이지를 요청하는 방식
    - UICollectionView supplementaryViewProvider 활용
        - supplementaryViewProvider를 Section Footer로 사용해서 해당 View가 불리게 되면 다음 페이지를 요청하는 방식
- 위 두 방식 중 CollectionView의 supplementaryViewProvider를 이용해서 구현했습니다.

```swift
private func registerSupplementaryView() {
    indicatorViewRegistration = UICollectionView.SupplementaryRegistration<IndicatorView>(elementKind: UICollectionView.elementKindSectionFooter) { [weak self] (supplementaryView, elementKind, indexPath) in
        if elementKind == UICollectionView.elementKindSectionFooter {
            self?.hasNextPage = self?.openMarketDelegate?.openMarketCollectionView(didRequestNextPage: true)
            if self?.hasNextPage == true {
                supplementaryView.startIndicator()
            }
        }
    }
}
```

## Cell 이미지를 할당
- Cell이 reuse되기 때문에 비동기로 처리되는 image를 다운로드받아 할당되는 작업은 계속해서 수행되는 문제가 발생했습니다.
- 단순히 indexPath에 해당하는 Cell이 지금 Cell과 같으면 할당되는 방법으로 해결하려고 했으나, 해당 방법은 문제는 해결되나 그 속도가 느린 문제가 발생했습니다.
- DispatchWorkItem 및 Operation을 이용해서 reuse될때 cancel하는 방법 또한 위와 같은 문제가 발생했습니다.
- 이러한 문제는 Image를 다운받는 URLSession이 이미 어려개 호출되어 발생하는 문제로 파악했고, Image를 다운받는 Task를 reuse될때마다 취소시켜 해당 문제를 해결했습니다.

```swift

private mutating func fetchImage(_ urlString: String,
                                     completion: @escaping (UIImage?) -> Void) {
    guard let url: URL = URL(string: urlString) else {
        completion(nil)
        return
    }
        
    fetchImageTask = URLSession.shared.dataTask(with: url) { (data, response, error) in
        if let data: Data = data,
           let image: UIImage = UIImage(data: data) {
            completion(image)
        } else {
                completion(nil)
        }
    }
        
    fetchImageTask?.resume()
}

mutating func cancelTask() {
    fetchImageTask?.cancel()
    fetchImageTask = nil
}

```

## 키보드가 콘텐츠를 가리지 않도록 처리
- 텍스트 입력 중 키보드가 콘텐츠를 가리지 않도록 키보드가 보이고 숨겨질 때 scrollView의 contentInset과 verticalScrollIndicatorInsets bottom을 키보드의 높이만큼 조절하도록 했습니다.

![](https://i.imgur.com/5p9oEpC.gif)

```swift
    @objc
    private func keyboardWillShow(_ sender: Notification) {
        guard let userinfo = sender.userInfo,
              let keyboardFrame = userinfo[UIResponder.keyboardFrameEndUserInfoKey] as? CGRect else {
            return
        }
        let keyboardHeight: CGFloat = keyboardFrame.size.height
        scrollView.contentInset.bottom = keyboardHeight
        scrollView.verticalScrollIndicatorInsets.bottom = keyboardHeight
        
        if let focusedTextView = UIResponder.currentFirstResponder as? UITextView {
            scrollView.scrollRectToVisible(focusedTextView.frame, animated: false)
        }
    }
```

2022-12-06 02:33 UTC, oneStar92 commented on OpenMarket/OpenMarket/Controller/ProductManagementViewController.swift
> +    }
이러한 구조로 필수 조건 충족 여부를 확인하는데 이러한 방법이 괜찮은 방법인지 궁금합니다!!

2022-12-06 02:35 UTC, oneStar92 commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +    }
위 delegate를 이용해 다음 페이지를 요청을 하는데 이러한 방법이 괜찮은 방법인가요??

2022-12-06 02:37 UTC, oneStar92 commented on OpenMarket/OpenMarket/Model/JSONDataModel/Product.swift
> +        try container.encode("xwxdkq8efjf3947z", forKey: .secret)
POST 해줄때 Body의 params에 해당하는 JSON객체에 secret이 포함되어 있었습니다.
이를 해결하고자 encode를 custom해서 해결했습니다...
이러한 방법이 좋은지 아니면 POST용 객체를 따로 만드는게 좋은지 궁금합니다!!

2022-12-06 02:41 UTC, oneStar92 commented on OpenMarket/OpenMarket/Network/OpenMarketAPI.swift
> +}
URLSession의 extension을 통해 페이지 불러오기, 상품 수정, 상품 등록, 상품 삭제 등을 URLSession이 메서드로 가지고 있는 것은 맞지 않다고 생각해서 다음과 같이 작성해봤는데 태태는 이러한 사용을 어떻게 생각하시는지 궁금합니다...?

2022-12-07 06:51 UTC, oneStar92 commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +}
collectionView에서 VC에게 다음 페이지를 요청하는 것을 delegate로 수행해도 되는지가 궁금합니다!!

2022-12-07 11:39 UTC, uuu1101 commented on OpenMarket/OpenMarket/Network/OpenMarketAPI.swift
> +}
해당 작업들을 잘 분리하셨다고 생각합니다 👍
조금 첨언드리자면, 고정된 값들(path, headers)들은 API 에서 가지고 있고, Body를 만들어주는 로직들은 NetworkManager가 가지고있는게 더 낫지 않을까? 라는 생각이 들어요 !

2022-12-07 11:43 UTC, uuu1101 commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +}
요청하는것은 괜찮다고 생각합니다.
VC에서 method로 만들어서 사용하는 방법보다 좋다고 생각해요.
다만 현재 ViewController의 네이밍을 수정할 필요성이 있어보입니다. 
해당 ViewController가 어떠한 ViewController인지 알려주면 더 좋겠죠 (ProductListViewController 라든지..?!)

2022-12-07 11:48 UTC, uuu1101 commented on OpenMarket/OpenMarket/Model/JSONDataModel/Product.swift
> +        try container.encode("xwxdkq8efjf3947z", forKey: .secret)
Request용과 POST용 객체를 분리해주는게 좋아보입니다 !

2022-12-07 12:33 UTC, uuu1101 requested changes
안녕하세요 아얀, 준호 !
오픈마켓II Step1 하시느라 고생하셨습니다.
고민하신점들이 아주 좋네요 :)
코드 관련하여 몇가지 코멘트를 남겨두었으니 확인부탁드립니다 ! 

궁금하신 부분들은 코멘트로 남겨두었어요!
답변이 더 필요하시다면 추가적으로 DM이나 코멘트를 남겨주세요.

2022-12-07 12:33 UTC, uuu1101 commented on OpenMarket/OpenMarket/Controller/ProductManagementViewController.swift
> +    func setUpViewsIfNeeded() {
setUpViews() 라는 네이밍은 어떠신가요?
IfNeeded를 포함하신 이유가 궁금합니다 :)

2022-12-07 12:33 UTC, uuu1101 commented on OpenMarket/OpenMarket/Controller/ProductManagementViewController.swift
> +    func setUpDelegateIfNeeded() {
setUpDelegate() 라는 네이밍은 어떠신가요?
IfNeeded를 포함하신 이유가 궁금합니다 :)

2022-12-07 12:33 UTC, uuu1101 commented on OpenMarket/OpenMarket/Controller/ProductManagementViewController.swift
> +    }
관심사 분리가 잘 되어있고, 알맞은 위치에 해당 로직이 있다면 괜찮습니다 !

2022-12-07 12:33 UTC, uuu1101 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +
해당 부분의 개행은 어떠한 의도로 넣어주신걸까요?

2022-12-07 12:33 UTC, uuu1101 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +
여기는 개행이 없어도 될것 같은데, 어떠한 의도로 개행을 두셨을까요?

2022-12-07 12:33 UTC, uuu1101 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +
해당 부분에 개행이 들어가 있는 의도가 있으실까요?

2022-12-07 12:33 UTC, uuu1101 commented on OpenMarket/OpenMarket/Model/JSONDataModel/Currency.swift
> +        let usdRawNumber: Int = 1
krw, usd 는 대문자로 사용하시는게 좋아보입니다 (약어이기에)

2022-12-08 09:43 UTC, oneStar92 commented on OpenMarket/OpenMarket/Model/JSONDataModel/Currency.swift
> +        let usdRawNumber: Int = 1
[597dc69](https://github.com/yagom-academy/ios-open-market/pull/233/commits/597dc69e00121d422b3e50486c83ccda47851218) 수정했습니다!!

2022-12-08 09:44 UTC, oneStar92 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +
[597dc69](https://github.com/yagom-academy/ios-open-market/pull/233/commits/597dc69e00121d422b3e50486c83ccda47851218) 컨벤션이 이상하게 작성된 부분이 많네요... 수정했습니다!!

2022-12-08 09:44 UTC, oneStar92 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +
[597dc69](https://github.com/yagom-academy/ios-open-market/pull/233/commits/597dc69e00121d422b3e50486c83ccda47851218) 왜 그랬을까요...? 수정했습니다!!

2022-12-08 09:44 UTC, junho15 commented on OpenMarket/OpenMarket/Network/OpenMarketAPI.swift
> +}
[0dd6eda](https://github.com/yagom-academy/ios-open-market/pull/233/commits/0dd6edaf36680bb65651372764238a354224a80f) 에서 Body를 만들어주는 로직들을 NetworkManager 로 옮겼습니다.

2022-12-08 09:44 UTC, oneStar92 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +
[597dc69](https://github.com/yagom-academy/ios-open-market/pull/233/commits/597dc69e00121d422b3e50486c83ccda47851218) 한줄이 더 나아보입니다... 의도는 없었습니다 ㅠㅠ 수정했습니다!!

2022-12-08 09:47 UTC, junho15 commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +}
[597dc69](https://github.com/yagom-academy/ios-open-market/pull/233/commits/597dc69e00121d422b3e50486c83ccda47851218) 어떤 ViewController 인지 알 수 있도록 `ProductListViewController` 로 네이밍 수정했습니다.

2022-12-08 09:47 UTC, oneStar92 commented on OpenMarket/OpenMarket/Controller/ProductManagementViewController.swift
> +    func setUpViewsIfNeeded() {
상속시 자식 객체에서 `setUpViews()`를 쓰지 않는 경우가 있을 수 있다고 생각해서 해당 의도로 필요하면 `setUpView()`를 해라 라는 의도로 네이밍 했습니다.
하지만 준호와 상의한 결과 View는 공통된 부분이기 때문에 `setUpViews()`로 수정했습니다. [597dc69](https://github.com/yagom-academy/ios-open-market/pull/233/commits/597dc69e00121d422b3e50486c83ccda47851218)

2022-12-08 09:48 UTC, oneStar92 commented on OpenMarket/OpenMarket/Controller/ProductManagementViewController.swift
> +    func setUpDelegateIfNeeded() {
위와 같은 맥락으로 네이밍 했었습니다.. 현재는 수정했습니다! [597dc69](https://github.com/yagom-academy/ios-open-market/pull/233/commits/597dc69e00121d422b3e50486c83ccda47851218)

2022-12-08 09:49 UTC, oneStar92 commented on OpenMarket/OpenMarket/Model/JSONDataModel/Product.swift
> +        try container.encode("xwxdkq8efjf3947z", forKey: .secret)
[03c8f77](https://github.com/yagom-academy/ios-open-market/pull/233/commits/03c8f7713e443bcce136dc15c3954b734b6aefdf) 분리했습니다!!

2022-12-08 10:01 UTC, oneStar92 commented
안녕하세요 태태🙇🏻‍♂️
컨벤션에서 이상한 부분이 많아서 다시 한번 확인해서 수정했습니다!!!
추가적으로 수정이 필요한 부분은 리뷰 주시면 감사하겠습니다!!👍

### 코멘트 주신 내용에 대한 답변
> 품목상세란이 TextField로 되어 있습니다, TextView로 변경하는건 어떨까요?

<img src="https://user-images.githubusercontent.com/32012924/206416566-d46d9df7-f19a-4622-acdf-7b9974e3c506.png" width="400" height="500">

아쉽게도 TextView였습니다.. 제약조건때문에 TextField처럼 보였네요...😵‍💫 제약조건 수정해서 TextField의 모습을 찾아줬습니다!! [92e1a22](https://github.com/yagom-academy/ios-open-market/pull/233/commits/92e1a2200e2ad2e03fe52a59e468e91db5f4d7e7)

2022-12-09 08:33 UTC, merged