오픈마켓II [STEP 1] inho, Hamo, Jeremy
yagom-academy/ios-open-market pull request #238
Opened 2022-12-07 08:03 UTC by inho-98

@GREENOVER 
안녕하세요 그린!
오픈마켓II Step1 PR드립니다.
잘부탁드립니다 🙇🏼‍♂️🙇🏼‍♂️🙇‍

## 📝 STEP 진행 중 경험하고 배운 것
☑️ `multipart/form-data`의 구조 파악
☑️ `http request` 구조 파악
☑️ `uploadTask` 메서드 사용
☑️ `NSCache`
☑️ `Notification Center`
☑️ `ImagePickerController`
☑️ 텍스트필드의 입력값에 따른 키보드 설정
☑️ 스크롤뷰의 `Content Inset`

## ⚒️ 코드 구현내용 
### 1️⃣ `ProductFormView`
- 상품 등록과 상품 수정에 사용되는 양식을 구현한 뷰입니다.
    - 추가될 이미지와 이미지 추가 버튼을 `imagesCollectionView`와 `cell`로 보여줍니다.
    - 상품의 이름, 가격, 재고 등을 `textField & textView`로 입력받습니다.
    - 전체 요소들을 `scrollView`안에 포함하여 컨텐츠가 화면을 초과하면 스크롤 가능하도록 구현하였습니다.

### 2️⃣ `ProductRegistrationViewController`
- 상품 등록을 위한 뷰컨트롤러 입니다.
    - 뷰에 입력받은 요소들을 확인하고, 조건이 충족된다면 `Done`버튼을 눌렀을때 상품 등록하는 `registerProduct`메서드가 실행됩니다.

### 3️⃣ `ProductEditViewController`
- 상품 수정을 위한 뷰컨트롤러입니다.
    - 상품 등록과 같은 양식으로 이루어진 뷰를 보여주지만, 초기화면의 셀을 눌렀을때 해당 셀의 상품 정보를 이미지, 텍스트필드 등에 추가한 상태로 보여지게 됩니다.
    - 수정과 삭제 과정은 개인벤더 정보와 일치할때 진행할 수 있다고 생각하여, 현재에는 `Done`버튼에 액션을 추가하지 않았고 다음 스텝에서 기능을 구현할 예정입니다.

## 💭 고민한 부분
### 상품 등록을 위한 `PostData`메서드 구현
- 상품 정보에 이미지 파일을 포함하고 있기 때문에 `POST`와 `multipart/form-data`형식을 이해해야 했습니다.
- 형식에 맞게 `request`의 헤더와 바디를 구성하고, 이미지를 데이터 형식으로 바디에 추가한 후 이를 `uploadTask`메서드의 매개변수로 전달합니다. (`request & data`)

### 상품 등록 화면에서 사진 개수에 따른 `imagePicker` 구현?
- 상품 등록 화면에서 사진을 선택하기 위한 방법으로 `phpickerViewController`와 `imagePickerViewController` 2가지가 있습니다.
- 요구사항에 선택된 사진을 `crop`하는 기능이 추가되어야 하는데 `phpickerViewController`의 경우 `crop` 기능이 없기 때문에 `imagePickerViewController`를 선택하였습니다.

### 키보드 높이만큼 스크롤뷰 올리기
- 텍스트뷰에 입력을 할 때 키보드가 올라와서 화면을 가리는 문제가 있어서 키보드가 올라왔을 때 키보드 높이만큼 `scrollView`의 `contentOffSet`을 높여주었습니다.
- `contentOffSet`을 조절하여도 `content`의 `height`가 증가하는게 아니기 때문에 스크롤하거나 타이핑을 하거나 스크롤했을 때 `contentOffSet`이 이전으로 변하는 문제가 발생했습니다.
- `scrollView`의 `contentInset`을 이용하여 키보드가 올라올 때 그 높이 만큼의 여백을 주고 내려갈 때 다시 0으로 만들어주어서 해결하였습니다.

### 상품 등록, 수정 뷰에서 텍스트 필드, 텍스트 뷰를 제외한 곳을 터치했을 때 키보드 내리기
- 터치 이벤트가 `responder chain`을 타고 내려오기 때문에 `viewController`에서 이벤트를 처리하는 `touchBegan`을 재정의하여 내부에서 `endEditing`을 호출하려 하였는데 특정 부분에서는 `viewController`가 이벤트를 처리하지 못하는 상황이 발생하였습니다.
- 해당 뷰에서 `viewController`위에 `scrollView`가 있게 그 위에 `contentView`가 있는 계층이었고 터치 이벤트를 `scrollView`가 가져가기 때문에 `viewController`에서 이벤트를 처리하지 못하는 문제임을 파악하고 `scrollView`에 `gesture`를 추가하여 터치 이벤트가 발생했을 때 `endEditing`하도록 하였습니다.

### 유저의 입력을 확인하는 과정 및 POST 시도 제한
- `ProductFormView`에서 각각의 `TextField`의 요구사항 충족 및 타입을 확인하는 연산 프로퍼티를 구현했습니다.
- 상품 등록 조건을 충족하지 않으면 `nil`을 반환하도록하여 값이 `nil`이면 `POST`가 진행되지 않도록 구현했습니다.
```swift
var nameInput: String? {
    guard let text = productNameTextField.text,
          (3...100).contains(text.count) else { return nil } //글자수 제한
        return text
    }
}
...
```

### `Done`버튼을 여러번 눌러 중복 `POST`되는 현상과 `POST`가 완료된 후에 `dismiss`작업
- `Done` 버튼을 여러번 누르면 한 게시물이 여러번 등록되는 문제가 있었습니다. 
- 이를 해결하기 위해 POST가 진행될 때 버튼이 한번 눌리면 `button`의 `isEnabled` 프로퍼티를 이용해서 비활성화 되도록 구현하였습니다.
- 상품 등록화면은 등록이 성공적으로 진행된 후에 내려가야 한다고 생각하여, 업로드를 수행하는 `postData`에 `completion handler`를 추가하여 작업이 완료된 후에 `dismiss`하도록 구현하였습니다.
```swift
networkManager.postData(request: request, data: data) {
    DispatchQueue.main.async {
        self.dismiss(animated: true)
    }
}
```

## ❓ 조언을 얻고싶은 부분
### `Request`의 추상화 방법
- `Post`할 때 `request`의 바디와 헤더를 해당 뷰컨트롤러에서 구성하여 `NetworkManager`의 `postData`메서드의 인자로 넣어서 호출하였습니다.
- 삭제, 등록, 수정 3가지 기능을 수행할 때 `request`의 바디와 헤더를 구성하는 코드들이 중복된다고 생각해서 추상화하고 싶은데 아직 감이 잡히지않아서 가능하시다면 키워드나 조언 부탁드립니다...🥲

### `URLSession`의 `dataTask` vs `uploadTask`
- 현재 이해하기로는 `DataTask`는 `NSData` 객체를 사용하여 데이터를 송수신을 하고 `UploadTask`는 `DataTask` 처럼 `NSData`를 "대게 파일 형태"로 송수신을 한다고 이해했습니다.
![](https://i.imgur.com/pgNDFEt.png)

- `UploadTask`가 `DataTask`의 작업을 수행할 수 있도록 되어있다면 이 둘을 구분하여 사용하는 기준이 있으신지 궁금합니다.🧐

2022-12-07 10:21 UTC, GREENOVER requested changes
@inho-98 @lxodud @yjjem 
세분 오픈마켓2 스텝1 너무 고생 많으셨습니다🥳🥳🥳
완성도 높은 코드 품질을 위해 많은 고민을 하신것이 너무 잘 보이네요!
전체적으로 관심사 분리와 조금 더 나은 사용성에 대해 리뷰를 주로 드려봤어요ㅎㅎ
***
### 칭찬 드리고 싶은 부분
- 전반적으로 코드 가독성이 아주 좋아요 💯
- 공통된 뷰를 잘 설계하셨으며 관심사 별 VC 및 파일을 잘 나눠주셨네요 💯
- 코드로 뷰가 오토레이아웃도 명확하게 잘 잡혀있네요 💯
***
### 궁금하신 부분에 대한 저의 의견
1. Request의 추상화 방법
- 요 부분에 대해서는 코멘트로 짧게 남기긴했지만, 공통된걸 추상화하기 위해 각 VC에서가 아닌 이미 존재하는 NetworkManager로 관심사를 옮기면 어떨까하는 의견이 있습니다🙋🏻
VC는 단순 NetworkManager에 상품에 대한 data만 넘겨줘서 지금 VC에서 공통적으로 구현될 로직들의 처리를 네트워크 매니저가 뚝딱뚝딱 처리할 수 있도록 함이 적절하지 않을까 싶습니다.
2. URLSession의 dataTask vs uploadTask
- 저는 지금 사용하신것처럼 dataTask는 조금 더 간편하게 서버에 리소스 요청 및 리스폰스를 받아올때 사용하고 그와 반대로 uploadTask를 사용하는 이유는 조금 더 request body를 구성해야하며 리스폰스가 오기 전 데이터를 서버에 업로드 하는것에 용이할때 사용합니다.
둘의 또하나의 차이는 dataTask는 session을 백그라운드에서 요청할 수 없지만 uploadTask는 백그라운드에서도 요청할 수 있습니다.
즉, 상품 등록 및 수정과 같이 request body를 구성해야하고 요청을 백그라운드에서 처리해야하는 경우 uploadTask를 사용합니다🙋🏻
조금 정리하자면 uploadTask는 주로 서버에 데이터 및 파일을 업로드해야하는 경우 사용합니다~!
왜냐하면 위에서 말한것과 마찬가지로 request body 구성을 제공하는 방식이 더 쉽습니다.
URLSessionUploadTask는 URLSessionDataTask의 서브클래스로 Post, Put의 요청에 조금 더 특화되었다고 보며 URLSessionDataTask는 주로 Get 요청에 사용합니다.
***
### 보완되면 좋을 부분에 대한 저의 의견
- 전체적으로 코드 품질이 좋아 금방 리팩토링 하실 수 있어 보입니다!
코멘트로도 많이 남긴 부분인데 사용자 입장에서 사용성을 조금 더 보완할 수 있는곳들이 있습니다🙌
요 부분들이 요구사항은 아니지만 구현되면 아주 좋을것 같아요ㅎㅎ
***
스텝1 너무 고생 많으셨어요 정말!
조금 더 힘내서 화이팅입니다ㅎㅎ 이번주도 거의 끝났어요🕺🏻
리팩토링 해보셔도 좋고 요구사항은 다 만족하기에 다음 스텝으로 넘어가도 무방합니다.
편하게 진행해보시고 재요청 혹은 말씀해주세요!
화이팅입니다🥳🥳🥳

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/Assets.xcassets/sample1.imageset/Contents.json
> +      "filename" : "m_하기싫어.jpeg",
ㅋㅋㅋㅋㅋ인상적이네요
해당 이미지 에셋을 unassigned에 지정하신 이유가 있을까요~?

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +        }
상품 등록을 위한 필수 정보 및 사진이 비어 있다면 Done을 눌러도 아무 반응이 없는것보다 유저에게 "상품명 / 가격을 입력해주세요~"와 같은 얼럿이 노출시키는것이 더 좋을것 같습니다..!
지금은 입력이 누락 혹은 잘못되었는지 아니면 서버 에러인지 사용자가 판단할 수 없어보여요🥲

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/View/ProductFormView.swift
> +    let imagesCollectionView: UICollectionView = {
요구사항에는 없지만 등록 혹은 수정 과정에서 이미 선택된 이미지를 제거하고 싶을때 이미지 영역 상단에 x 버튼들을 오버레이해서 지울 수 있으면 더 사용성이 좋을것 같습니다🙋🏻

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +              let description = productRegistrationView.descriptionInput,
현재 descriptionInput의 조건이 10~1000자 인데 유저가 10자 미만으로 입력하고 Done을 눌렀을때 등록되지 않는 이유를 알 수가 없는것 같아요ㅠ
얼럿을 띄워주거나 해당 텍스트뷰에서 placeHorder로 안내하는것도 좋을것 같습니다!
UITextViewDelegate의 textViewDidBeginEditing를 이용하면 어떨까요?🙋🏻
https://developer.apple.com/documentation/uikit/uitextviewdelegate/1618610-textviewdidbeginediting

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +        }
현재 실제 상품 등록이 된 후 해당 뷰가 닫히고 상품 목록으로 돌아갔을때 등록된 상품이 바로 반영되지 않는 로직인것 같습니다🙋🏻
뷰의 갱신이 이뤄져야 할것 같아요🤔

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/View/RegistrationImageCell.swift
> +    func addImage(_ image: UIImage) {
아마 이부분에서 상품 이미지가 등록될때 삭제를 할 수 있도록 x 버튼도 같이 구성되거나 혹은 다른 방향이라도 사용성의 개선이 있으면 어떨까 싶습니다🙋🏻

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/Model/Network/NetworkManager.swift
> +        let task = URLSession.shared.uploadTask(with: request, from: data) { data, response, error in
해당 타입에서 의존성 주입으로 받은 session 프로퍼티를 통해 사용하지 않고 URLSession.shared를 직접 다시 사용한 의도가 있을까요~?
프로토콜로 정의하신 URLSessionProtocol에 uploadTask 메서드를 같이 포함해 session 프로퍼티로 사용되면 어떨까요?

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
> +        let navigationController = UINavigationController(rootViewController: viewController)
상품을 클릭했을때 수정 모드로 바로 넘어가는것이 요구사항과 조금 다른것 같습니다..!
스텝2와 이어질것 같긴한데 스텝2에서 로직 수정이 있으면 좋을것 같아요🙋🏻

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +            return nil
이전에 NetworkRequest에서 정의한걸 사용하는 방법은 어떨까요?
더 나아가서 request를 구성하는 아래 일련의 과정들을 VC에서가 아닌 NetworkManager에서 처리해주는것이 관심사 분리가 조금 더 잘 이뤄질것 같은데 어떻게 생각하시나요?🙋🏻

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +            print(convertedImage.count)
불필요한 코드 구문 같습니다🙋🏻

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +                                         fileName: "inho.png",
여러 이미지 및 다른 상품 등록 시의 이미지 파일명은 모두 같아지는게 맞을까요?🤔

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +    private func convertImageData(_ image: Data, fileName: String, mimeType: String) -> Data {
이미지 Data를 관리하는 별도 매니저 역할을 하는 타입이 따로 있는것도 관심사 분리를 한단계 높일 수 있을것 같습니다🙋🏻

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +extension ProductRegistrationViewController {
여러 extension들 시작부에 MARK 주석으로 어떤 역할들을 모은 extension인지 있으면 더 가독성이 좋을것 같아요!ㅎㅎ

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +    @objc private func moveDownScrollView(_ notification: NSNotification) {
사용성을 배려한 세심한 구현 아주 좋네요!👍👍

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +            return
실제 request를 구성하지 못한 상황에서 얼럿을 노출시켜주면 더 사용성이 좋을것 같습니다~!

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +    mutating func appendString(_ input: String) {
추후 해당 메서드가 다른 VC 혹은 파일들에서 사용될 경우는 없을까요?
fileprivate하게 extension하신 이유가 궁금합니다🙋🏻

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +fileprivate extension UIImage {
위 Data extension과 마찬가지로 다른 부분에서 사용될 여지가 없는 extension 메서드일까요?

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ProductEditViewController.swift
> +                print(error)
실제 동작에서 필요하지 않은 코드 같습니다🙋🏻
에러 처리를 조금 더 의미있게 가져가면 어떨까요~?

2022-12-07 10:21 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ProductEditViewController.swift
> +                print(error)
사용에 의미있는 코드가 아니라면 제거되어도 좋습니다👍

2022-12-10 15:17 UTC, lxodud commented on OpenMarket/OpenMarket/Model/Network/NetworkManager.swift
> +        let task = URLSession.shared.uploadTask(with: request, from: data) { data, response, error in
URLSessionProtocol에 uploadTask 메서드를 요구사항으로 구현하였습니다!!
해당 메서드의 test는 추후 과제로 남겨두었습니다😆😆😆

2022-12-10 15:18 UTC, inho-98 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +        }
등록 실패했을때 어떤 이유로 실패했는지 보여주기 위해서 `UserInputError`를 만들고 아래 이미지와 같이 각 케이스에 맞는 에러 메세지나 요구 사항을 보여주도록 수정했습니다!

|<img width=200, src="https://user-images.githubusercontent.com/71054048/206862057-5960f985-b892-41b2-89cb-46b8e975cafd.png">|<img width=200, src="https://user-images.githubusercontent.com/71054048/206862177-fdf12756-1d0c-42c1-ad76-58e696f14bb3.png">|<img width=200, src="https://user-images.githubusercontent.com/71054048/206862221-f279f455-69bd-4f2e-9ff1-2d4004de6c40.png">|
|--|--|--|

> e6240a4

2022-12-10 15:22 UTC, inho-98 commented on OpenMarket/OpenMarket/View/ProductFormView.swift
> +    let imagesCollectionView: UICollectionView = {
말씀해 주신대로 이미지에 사진 삭제 버튼을 추가하여 해당 사진을 삭제할 수 있도록 구현하였습니다!

<img width="200" src="https://user-images.githubusercontent.com/71054048/206862349-a8b09150-90d4-4f59-b067-a5d679d95d4f.png">

> 958deeb

2022-12-10 15:23 UTC, lxodud commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +            print(convertedImage.count)
삭제했습니다 👍👍👍

2022-12-10 15:26 UTC, inho-98 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +              let description = productRegistrationView.descriptionInput,
입력 상황의 에러를 처리하면서 10~1000자 사이의 텍스트를 입력해야한다는 알림을 보여주도록 수정하였습니다!

텍스트뷰를 생성할때 `placeHolder`의 문구를 추가하고, `textViewDidBeginEditing`를 이용하여 입력이 시작됐을때 해당 문구를 삭제해 `placeHolder`를 구현하는 방법도 이해하였습니다!

2022-12-10 15:29 UTC, inho-98 commented on OpenMarket/OpenMarket/View/RegistrationImageCell.swift
> +    func addImage(_ image: UIImage) {
`RegistrationImageCell`에 `addDeleteButton`메서드를 추가하여 이미지가 추가될때 버튼도 같이 추가하도록 구현하였습니다!

```swift
func collectionView(_ collectionView: UICollectionView,
                    cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
    ...
    cell.addImage(images[indexPath.item])
    cell.addDeleteButton(selector: #selector(deleteImage))
    ...    
}
```

2022-12-10 15:33 UTC, inho-98 commented on OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
> +        let navigationController = UINavigationController(rootViewController: viewController)
셀을 눌렀을때 상품 상세화면이 보여지고, 거기서 수정 모드로 넘어가야 하기때문에 
셀이 선택되면 `ProductDetailViewController`를 보여주고, 수정 버튼을 눌렀을때 수정화면으로 이동하도록 리팩토링하였습니다.
`ProductDetailViewController`의 뷰는 추후에 구현할 예정입니다!

|<img width=200 src="https://user-images.githubusercontent.com/71054048/206862762-a40b34ff-8cdd-4282-b21e-45c133c6f349.png">|
|--|

> 1f61735

2022-12-10 15:36 UTC, inho-98 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +            return nil
`NetworkRequest`에 `postProduct` 케이스를 추가하여 필요한 `URL`을 리턴하도록 수정했습니다!
그리고 `request`와 `body`를 구성하는 메서드는 `NetworkManager`의 메서드로 분리해 주었습니다!

> 5f4993d

2022-12-10 15:41 UTC, inho-98 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +                                         fileName: "inho.png",
사진마다 고유한 파일이름을 가지도록 `UUID`를 파일명으로 가지도록 수정하였습니다!
디스코드나 카톡에서 사진을 다운받았을때 랜덤한 문자와 숫자로 이루어진 파일명을 보고 위의 방법을 떠올렸는데요,
이러한 방법이 적절한지 궁금합니다..! 🤔

2022-12-10 15:43 UTC, inho-98 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +    private func convertImageData(_ image: Data, fileName: String, mimeType: String) -> Data {
이미지를 변환하는 부분도 `ImageDataManager`타입을 구현하여 뷰컨에서 분리하였습니다!

> 5f4993d

2022-12-10 15:50 UTC, inho-98 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +    mutating func appendString(_ input: String) {
해당 `extension`은 기존 위치의 뷰컨트롤러에서만 사용된다고 판단하여 `fileprivate`을 적용하였는데요,
리팩토링 과정에서 다른 곳에서도 필요하게 되여 `Data+Extension`에 분리해주었습니다!

2022-12-10 16:01 UTC, inho-98 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +fileprivate extension UIImage {
이미지데이터를 관리하기 위해 만든 `ImageDataManager`구조체에서 사용되는 코드라고 판단하여 
`ImageDataManager` 파일로 이동시켰습니다!

2022-12-10 16:04 UTC, inho-98 commented on OpenMarket/OpenMarket/Controller/ProductEditViewController.swift
> +                print(error)
이미지 로딩을 실패했을때는 이미지 없음을 보여주도록 코드를 수정하였습니다.

```swift
case .failure(_):
    DispatchQueue.main.async {
        cell.addImage(self.errorManager.showFailedImage() ?? UIImage())
    }
}
```

2022-12-10 16:05 UTC, inho-98 commented on OpenMarket/OpenMarket/Controller/ProductEditViewController.swift
> +                print(error)
이미지 로딩을 실패했을때는 이미지 없음을 보여주도록 코드를 수정하였습니다.

```swift
case .failure(_):
    DispatchQueue.main.async {
        cell.addImage(self.errorManager.showFailedImage() ?? UIImage())
    }
}
```

2022-12-10 16:18 UTC, inho-98 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +        }
상품 등록 후 `Done`버튼이 눌렸을때, `NotificationCenter`를 이용하여 `reloadData()`메서드를 호출하고, 추가된 상품이 보여질 수 있도록 수정하였습니다!

> 923853c

2022-12-10 16:20 UTC, inho-98 commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +extension ProductRegistrationViewController {
각 `extenstion`의 역할을 보여주도록 주석을 추가하였습니다! 
```swift
//MARK: - CollectionViewDataSource
```

> bcd0def

2022-12-10 16:48 UTC, lxodud commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +            return
alert를 이용해서 사용자에게 에러가 발생했음을 알려주었습니다!!

2022-12-10 17:04 UTC, inho-98 commented on OpenMarket/OpenMarket/Assets.xcassets/sample1.imageset/Contents.json
> +      "filename" : "m_하기싫어.jpeg",
이전에 `POST`를 테스트하기 위해 에셋에 임시로 추가했던 사진입니다..!🤣
지금은 필요없어서 삭제해둔 상태입니다!

말씀해주신 에셋을 `unassigned`로 지정했다는 부분은 저희 엑스코드에선 확인이 안됐는데요,
에셋에서 `Devices`의 `universal`을 지정하지 않으면 `unassigned`가 발생하는 정도만 발견하고
그린의 `xcode`에서 발생하는 이유는 알아내지 못했습니다..🥲

2022-12-11 09:23 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
> +                                         fileName: "inho.png",
아주 좋네요!
저도 동의하며 적절하다고 생각해요ㅎㅎ

2022-12-11 09:36 UTC, GREENOVER approved these changes
@inho-98 @lxodud @yjjem 
고생 많으셨습니다!
몇개의 사소한 리뷰와 함께 어프로브 및 머지하겠습니다ㅎㅎ
현 시점에서 오픈마켓 서버가 인증서 만료때문에 죽은것 같아 상품 등록의 테스트 제외하고 봤을때 사용성 등 매우 매우 좋아졌어요👍
다들 정말 2주간 고생 많으셨고 저도 많이 배웠습니다🙇🏻
오픈 마켓 스텝 2-2도 꼬옥 방학 끝나고 해보시면 좋을것 같아요🙌
제 도움이 필요하시면 언제든 말씀해주세요ㅎㅎ
이제는 곧 현업에서 뵙죠!

2022-12-11 09:36 UTC, GREENOVER commented on OpenMarket/OpenMarket/Extension/Data+Extension.swift
> +}
요렇게 기본 타입들에 대해 public한 Extension 시 파일로 따로 빼는것 너무너무 좋습니다👍 (파일명도 적절하구요)

2022-12-11 09:36 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
> +                case .failure(_):
`case .failure:`의 표현과 어떤 차이가 있나요~?

2022-12-11 09:36 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
>                  case .success(let image):
`case let .success(image):` 로도 나타낼 수 있을것 같아요🙋🏻

2022-12-11 09:36 UTC, GREENOVER commented on OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
> +        viewController.productData = product
조금 더 명확한 VC의 이름이 주어지면 좋을것 같습니다🙋🏻
나중에 요러한 코드가 많아지고 바로 연달아 사용되지 않는 시점에서는 유추하기 조금 어려울 수 있겠다 싶었어요🤔

2022-12-11 09:36 UTC, merged