오픈마켓 II [STEP 1] 애종, 토털이
yagom-academy/ios-open-market pull request #239
Opened 2022-12-07 08:52 UTC by jonghancha

안녕하세요. 올라프(@1Consumption)!
 이제 막 구현을 마치고 PR 보내 드립니다...!!
 이번에는 저희가 이해한 것을 바탕으로 (이미지 resizing 제외) 구현해 보았습니다! 잘 부탁드려요~
 

## 구현 내용

### 1. 이미지 추가 버튼을 통해 이미지 추가 구현

|                    상품 등록 과정                    |
|:----------------------------------------------------:|
| <img src= https://i.imgur.com/ouBBoaI.gif width=200> |

- 스크롤 뷰와 스택뷰를 활용하여 구현해 주었습니다.
- `self.imageStackView.insertArrangedSubview(imageView, at: self.imageStackView.subviews.count - 1)`를 이용하여 이미지뷰에 추가시 오른쪽 부터 사진이 들어갈 수 있도록 해주었습니다.

### 2. keyboard textView 클릭 시 사진부분 hidden
|       사진부분 hidden과정        |
|:----------------------------------------------------:|
| <img src= https://i.imgur.com/G3OmlYT.gif width=200> |

- 텍스트뷰를 클릭시에 오토레이아웃을 바꾸고, Image 부분을 hidden 시켜 키보드가 텍스트뷰를 가리지 않도록 구현해 주었습니다.

### 3. 새로운 상품post 과정의 기능 분리
- NetworkAPIProvider
    - post()
- ProductNetworkManager
    - postNewProduct()
    - generatePostRequest()
    - createBody()

위와 같이 메서드를 추가하여 post를 구현해 주었습니다. `multipart/form-data`로 전송하기 위해서 body를 직접 만들어주고 request를 만들어줄 수 있도록 하였습니다.

### 4. delegate으로 alert 구현
상품을 post 한 후에 상품등록 화면은 pop이 되고, 상품 등록이 완료 되었을 때 delegate를 통해 이전 리스트 화면에서 alert을 띄워줄 수 있도록 구현해 보았습니다.

### 5. 수정화면과 등록화면의 공통기능 구현
등록화면인 `AddProductViewController`를 상속받은 `EditProductViewController`를 통해서 수정화면을 만들어주었습니다. 다음 화면에 넘어갈 때 이미 데이터를 이전 화면이 가지고 있을 것이라고 가정하여 커스텀 init을 만들어 주었습니다.

## 조언을 얻고 싶은 부분
### 1. newProduct 업로드 성공하고, 무슨무슨 제품을 업로드 하는데 성공했습니다! 알려주고 싶은데 alert 대신 보여줄 수 있는 방법 
Alert의 HIG문서에 따르면, Alert는 `단순히 정보를 제공할 때에는 사용하지 말라고` 쓰여있는 것을 봤습니다. post의 성공 혹은 실패여부는 Alert을 띄울만큼 `destructive`하거나 `심각한 문제`가 발생한 것은 아니지만, 사용자 입장에서는 꼭 알아야 하는 정보라고 생각합니다. 이러한 정보를 알리고 싶을 때 어떤 방법을 사용하는게 좋을지 궁금합니다!

### 2. List에서 Grid로 layout을 바꿔줄 때 item 두 개 정도가 위에서 잘리는 현상 ( listCell을 선택해주면 잘리지 않습니다)
추측으로는 List 뷰와 Grid뷰가 한 화면에서 보여주는 `item의 개수 차이`에서 오는 현상이라고 생각했지만, list의 아이템을 한번 선택한 후에는 이러한 현상이 사라지는 것을 보고 이유를 더욱 알 수 없게 되었습니다...

|              cell을 선택하지 않았을 때               |                  cell을 선택했을 때                  |
|:----------------------------------------------------:|:----------------------------------------------------:|
| <img src= https://i.imgur.com/FEyFS7G.gif width=200> | <img src= https://i.imgur.com/UKzJH6P.gif width=200> |

### 3. 키보드의 화면 추가에 따른 뷰의 변화에 대한 고민

키보드가 밑에서 올라오는 과정에서 뷰의 content가 가리지 않도록 구현하는 과정에서 어떤 방법이 좋은지에 대해 고민을 많이 했습니다. 
<img src= https://i.imgur.com/Skw1dkP.png width=600>
공식문서에서는 입력중인 text를 담는 TextField 뿐 아니라 button까지 전부 보이도록 뷰 전체적으로 조금씩 위로 올려준 모습입니다. 현재 저희 뷰는 아래와 같이 화면에 UI로 가득 찬 형태인데
<img src= https://i.imgur.com/Q8TLkmg.png width=200>
이때 hidden이나 뷰의 윗부분을 잘라내면서 화면을 구성하는 것이 좋은지, 아니면 뷰 전체가 보이면서 비율이 달라지도록 구성하는 것이 좋은지 궁금합니다!!

|                       뷰 축소                        |
|:----------------------------------------------------:|
| <img src= https://i.imgur.com/bqXINcT.gif width=200> |

### 4. View와 Controller 분리 문제
- 코드로 뷰와 컨트롤러를 분리하여 사용해 주었는데, 뷰의 역할과 컨트롤러의 역할을 적절하게 나누어서 구현하였는지 궁금합니다!

2022-12-07 16:10 UTC, 1Consumption requested changes
고생하셨습니다👍  @jonghancha @tottalE 

대부분의 코드에 고민한 흔적이 보이네요.
다만 아직 이유 없는 코드가 조금 보이는게 아쉽습니다.

또한 커밋이 한번에 여러개의 역할을 하고 있고, 너무 큽니다.
커밋은 한번에 하나의 역할만 하도록, 그리고 작게 해주세요.

아래는 조언을 얻고 싶은 점에 대한 제 생각입니다.

### 1. newProduct 업로드 성공하고, 무슨무슨 제품을 업로드 하는데 성공했습니다! 알려주고 싶은데 alert 대신 보여줄 수 있는 방법 
> "단순한 정보"를 어디까지로 볼지부터 정하면 좋겠습니다. 저는 현재 알러트가 적절하게 쓰이고 있다고 생각해요.

### 2. List에서 Grid로 layout을 바꿔줄 때 item 두 개 정도가 위에서 잘리는 현상 ( listCell을 선택해주면 잘리지 않습니다)
> 글쎄요. 이부분은 잘 모르겠습니다. 다만 저라면 layout을 변경할 때마다 contentOffset을 초기화 해줄 거 같아요.

### 3. 키보드의 화면 추가에 따른 뷰의 변화에 대한 고민
> 저라면 내부의 view를 scrollView에 넣고 키보드 높이만큼 올려줄 거 같습니다.

### 4. View와 Controller 분리 문제
> ViewController는 view인가요 controller인가요? 저는 View라고 생각합니다. 따라서 제가 봤을 때는 View와 로직이 분리되었다고 보기는 조금 어렵다고 생각합니다.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 15.0;
타겟을 올린 이유가 있나요?

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Assets.xcassets/pearl.imageset/Contents.json
> +}
이 asset은 사용되지 않는데 왜 추가하셨나요?

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +
불필요한 변경사항이네요.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +        configureView()
view를 configure한다는 메소드로 묶으면 어떨까요?

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +    var textFieldConstraint: NSLayoutConstraint?
몇가지 프로퍼티는 private이어도 될거같습니다.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +        self.productManageView.descriptionTextView.delegate = self
이 메소드는 viewDidLoad에서 불리는데, 굳이 view가 메모리에 올라오고 난 후에 다시 view를 바꾸는 이유가 있나요?
https://developer.apple.com/documentation/uikit/uiviewcontroller/1621454-loadview 에 대해서 알아보세요.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +        configureView()
메소드가 불리는 순서와 메소드가 선언된 순서가 맞지 않아 읽기 어렵습니다. 되도록이면 순서를 맞춰주세요.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +    }
개행의 기준이 궁금합니다. 뭔가 이도저도 아닌 느낌이네요.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +        self.productManageView.photoAddButton.addTarget(self, action: #selector(imageAddButtonPressed), for: UIControl.Event.touchUpInside)
```suggestion
        self.productManageView.photoAddButton.addTarget(self, action: #selector(imageAddButtonPressed), for: .touchUpInside)
```
이미 `for`에는 어떤 타입이 들어갈지 알기 때문에 위와같이 변경하는게 더 좋아보입니다.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +    }
`버튼이 눌렸다` 라는게 이 메소드의 동작인가요? 메소드의 이름을 다시 고민해보세요.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +        guard imageCount < 5 else { return }
이런 정보를 view에서 알아야하나요? 
그리고 지금 상태에서 5개 초과해서 추가했을 때 사용자가 이상 동작임을 인지할 수 있나요?

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +}
개행 컨벤션을 통일해주세요. 계속해서 컨벤션 관련 코멘트를 드리는 거 같습니다. 컨벤션은 코드의 통일성, 가독성에 영향을 미치는 중요한 요인입니다.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +        imageCount += 1
이 부분도 view에서 할 역할이 아니라고 생각합니다. view는 이벤트만 보낼 뿐이지 판단을 하면 안된다고 생각합니다. 판단을 할 별도의 객체가 있으면 좋겠어요.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +            self.view.layoutIfNeeded()
`layoutIfNeeded`는 어떤 역할을 하나요? `setNeedsLayout`, `setNeedsDisplay`와는 어떤 차이가 있나요?
Constraint를 on off 하는 작업은 비용이 많이 듭니다.  constant를 변경하는 쪽으로 방향을 잡았으면 좋겠습니다.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +    }
외부에서 몰라도 되는 메소드 같습니다. 접근 제어자를 변경해주세요.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +    @objc func dismissMyKeyBoard() {
어디서 참고한 네이밍인가요? 많이 어색하네요.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +    }
이 코드 모두 로직 같습니다. view에서는 몰라도 되는게 아닐까요?
혹시 ViewController는 view가 아니라고 생각하시나요? 그렇다면 그 이유가 궁금합니다.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +        else { return nil }
브레이크포인트를 else절에 찍고 싶으면 어떻게 해야하나요?
```suggestion
        else { 
            return nil 
        }
```
위와 같이 코드를 짜야 명확하게 찍을 수 있지 않을까요?

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +        let stock = Int(self.productManageView.productStockTextField.text ?? "0")
값이 없을 때는 기본값을 넣는게 맞을까요? 아니면 guard 문으로 검사를 해서 만들지 않는게 맞을까요?
정책을 어떻게 정하느냐의 차이라고 생각이 됩니다.
지금 정책은 기본값을 주기로 정한건가요?

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +        let images: [UIImage] = self.productManageView.imageStackView.subviews.compactMap { $0 as? UIImageView }.compactMap { $0.image }
image를 view에서 꺼내오지말고, 따로 객체로 관리하면 좋겠습니다. picker에서 이미지를 받아올 때 이미지를 관리하는 객체에 저장하면 어떨까요? 그리고 그 변경사항을 delegate를 통해 받아 처리했으면 좋겠습니다.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +        else { return }
이 else문에서도 실패를 알려야하지 않을까요?

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +            }
self를 강하게 참조한 이유가 있을까요?

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +                    }
Result의 success, failure에 해당하는 연관값은 따로 사용하지 않는건가요?

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/EditProductViewController.swift
> +class EditProductViewController: AddProductViewController {
final을 붙여주세요.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +}
`:` 사이에 공백을 통일해주세요.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Extensions/UIImage+Extension.swift
> +    }
View에서 압축하는 로직을 알아야할까요?

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Extensions/UITextField+extension.swift
> +  }
indent 통일이 안되어있네요.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +    func post(request: URLRequest, completion: @escaping (Result<Data, Error>) -> Void) {
Result의 Error가 보다 더 구체적인 타입이면 좋겠습니다. Result타입의 장점 중 하나는 Error를 특정할 수 있다 라고 생각하거든요.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +        guard let session = self.session as? URLSession else { return }
여기서도 completionHandler에 뭔가를 전달해야하지 싶어요.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/Utilities/NetworkAPIProvider.swift
> +    func post(request: URLRequest, completion: @escaping (Result<Data, Error>) -> Void) {
post의 httpMethod나 ~body~를 만드는건 여기서 해야하는 일 같습니다. 네트워크에 관련된 내용이니까요. 외부에서 하지 않도록 코드를 여기로 옮기는게 좋아보입니다.
`ProductNetworkManager`의 `generatePostRequest`, ~`createBody`~ 메소드가 코멘트에 해당하는 메소드 같습니다.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ImageAddButton.swift
> +    }()
외부에서 알아야하는 뷰인가요?

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ImageAddButton.swift
> +        clipsToBounds = true
이 옵션은 어떤걸 뜻하나요?

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ImageAddButton.swift
> +            self.plusImage.heightAnchor.constraint(equalTo: self.plusImage.widthAnchor, multiplier: 1)
```suggestion
            self.plusImage.heightAnchor.constraint(equalTo: self.plusImage.widthAnchor)
```

multiplier가 1이라면 생략해도 좋습니다.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ProductManageView.swift
> +class ProductManageView: UIView {
상속되지 않는 뷰 같습니다.

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ProductManageView.swift
> +    }()
이 view들을 꼭 외부에서 직접 알아야하나요? 인터페이스를 뚫어서 필요한 기능만 외부에 노출하는건 어떨까요?

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ProductManageView.swift
> +    }
이 init들에는 중복되는 코드가 많네요. `init(product: Product, images: [UIImage])`에서 frame init을 호출하고 있으니까 중복되는 코드를 줄일 수 있어보입니다.
그리고 required인 이유가 있을까요?

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ProductManageView.swift
> +            self.imageStackView.heightAnchor.constraint(equalTo: imageView.widthAnchor).isActive = true
이미지 배열을 돌면서 매번 constraint를 잡아주는 이유가 궁금합니다.
그리고 imageView의 translateAutoResizingMask가 false가 아닌거 같은데 맞나요?

2022-12-07 16:10 UTC, 1Consumption commented on OpenMarket/OpenMarket/View/ProductManageView.swift
> +        imageScrollView.layoutIfNeeded()
layoutIfNeeded를 호출하는 이유는 뭔가요?

2022-12-08 01:31 UTC, jonghancha commented on OpenMarket/OpenMarket.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 15.0;
키보드가 올라옴에 따라 뷰의 레이아웃을 변경하는 과정에서 keyboardLayoutGuide를 사용하려 할 때 target을 올렸습니다. 결국 keyboardLayoutGuide은 사용하지 않아서 14로 내려주어야했으나 깜빡했습니다..다시 내리겠습니다!

2022-12-08 01:33 UTC, jonghancha commented on OpenMarket/OpenMarket/Assets.xcassets/pearl.imageset/Contents.json
> +}
뷰를 만드는 과정에서 Test용도로 사용했던 이미지들인데 마찬가지로 삭제하는 것을 깜빡했습니다.. 더 이상 사용하지 않으니 삭제하도록 하겠습니다!

2022-12-08 01:38 UTC, tottalE commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +
저희도 모르게 변경이 되었네요... 죄송합니다!!

2022-12-08 01:52 UTC, jonghancha commented on OpenMarket/OpenMarket/Controller/AddProductViewController.swift
> +        configureView()
configureView메서드를 추가해서 그 안에 묶어주었습니다

2022-12-15 05:12 UTC, closed without merging