[Step1] 강경, Kane
yagom-academy/ios-open-market pull request #26
Opened 2021-05-14 14:01 UTC by kane-young

@corykim0829 

Cory!!!!! 안녕하세요ㅎㅎ 첫번째 PR이 너무 늦었네요...ㅠ 욕심을 부리다보니ㅠㅠ

## 간략한 프로젝트 소개 🎉 🎊
이번 PR은 commit 순서대로 봐주시면 저희의 의식의 흐름을 보실 수 있어, 피드백이 빠르실 수도 있을 것 같네요ㅎㅎ

`Model` 의 struct 들은 json을 통해서 Encode, Decode 파싱될 자료들의 타입입니다
- `Request` : Encode할 타입
- `Response` : Decode할 타입

`Error`은 OpenMarket의 error에 대해서 정의했습니다
`Network`에는 실제로 네트워크를 진행하는 타입이 정의되어 있습니다
- Test를 바로 진행할 `GET` 함수에 해당되는 타입만 빠르게 만들었습니다
- 추후에 POST, DELETE, FETCH 해당 타입을 구현하겠습니다

### 한가지 빠진 점은
현재 `ItemSearcher`, `ItemListSearcher` 에서 

![스크린샷 2021-05-14 오후 10 41 50](https://user-images.githubusercontent.com/64566207/118279062-a43f2e00-b505-11eb-95f0-59170888560e.png)

Data가 원활하게 들어오지 않는경우에 Log만 찍고 return 되도록 구현되어 있는데, 이 부분은

![스크린샷 2021-05-14 오후 10 42 01](https://user-images.githubusercontent.com/64566207/118279066-a608f180-b505-11eb-9944-ae9ce1e66900.png)

completionHandler의 parameter로 error를 추가해서 

```swift
func search(id: Int, completionHandler: @escaping (ProductSearchResponse?, OpenMarketError?) -> ()) {

}
```
와 같이 수정한 후에 `completionHandler(nil, OpenMarketError.invalidSearchResult)` 처리를 하여 수정하도록 하겠습니다
**PR을 보내면서 뒤늦게 알게되었어요ㅠㅠ**

그리고 마지막 Test 부분은 고뇌한 끝에 최대한 네트워크에 의존하지 않도록 Test Doubles(Mock)를 생성하여 Test 하였습니다

### 여기서 고민되었던 점
![스크린샷 2021-05-14 오후 10 55 01](https://user-images.githubusercontent.com/64566207/118280752-7529bc00-b507-11eb-9600-fa60ff7d6e31.png)

위 처럼 저희는 TestDoubles 안에 XCTFail를 사용했는데, 이렇게 타입에 XCTAssert함수를 써도 될까요??
뭔가 Test 함수에만 있어야지 않을까? 라는 생각이 듭니다...ㅠ

<br>

- 이상입니다 - 
여과 없는 피드백 부탁드리겠습니다 🙌🏼😄

2021-05-16 13:23 UTC, corykim0829 requested changes
수고 정말정말 많으셨어요 강경, Kane! 👏👏👏👏

🔥 굉장히 많은 고민을 하고, 이것저것 시도하려는게 눈에 보여서 리뷰도 더 오래 걸린 것 같아요! 🔥

특히나 프로토콜과 테스트를 적극적으로 사용해보려고 하는 모습이 보여서 좋았습니다! 👍

현재 Mock이 붙은 객체는 JSON Data를 직접 파싱하는 객체이고, Mock이 붙지 않은 객체는 URL을 통해서 JSON 데이터를 받아오는 객체인데, 각각의 테스트가 필요한 것 같아요! 현재는 어떤 특정한 객체를 테스트하고 있지 않아서 테스트라고 보기 애매한 것 같아요.

Mock의 의미는 조금 더 찾아보셔서 comment로 저와 이야기해보면 좋을 것 같아요!

2021-05-16 13:23 UTC, corykim0829 commented on OpenMarket/OpenMarket/Model/Protocol/Detailable.swift
> +protocol Detailable: InfoSearchable {
프로토콜을 사용하려는 시도는 매우 좋습니다! 그런데 왜 이 프로토콜이 Detailable이고, 이 프로토콜이 왜 InfoSearchable을 채택하고 있는지 이해가 잘 안되네요 🤔

2021-05-16 13:23 UTC, corykim0829 commented on OpenMarket/OpenMarket/Model/Response/ProductDeleteResponse.swift
> +struct ProductDeleteResponse: InfoSearchable, Detailable {
Detailable이 InfoSearchable 프로토콜을 채택하고 있기 때문에 Detailable만 채택해도 될 것 같습니다!

2021-05-16 13:23 UTC, corykim0829 commented on OpenMarket/OpenMarketTest/Mock/MockItemListSearcher.swift
> +class MockItemListSearcher {
Mock을 떠나서 ItemListSearcher을 테스트를 하는 코드처럼 보이지 않네요!

2021-05-16 13:41 UTC, corykim0829 commented on OpenMarket/OpenMarketTest/Mock/MockItemListSearcher.swift
> +      print(MockServiceError.search)
질문 주셨던 부분이라 다시 커멘트하겠습니다! 클래스 내부에 테스트 관련 코드가 있어도 상관은 없습니다!
하지만 현재 이렇게 작성하면 테스트를 명확하게 하기 힘들어보여요.
어떤 객체의 어느 부분을 테스트 하는지 명확하게 보여야할 것 같아요!

2021-05-22 13:14 UTC, kane-young commented
@corykim0829
Cory!
열심히 고뇌한 :thinking: 끝에,
늦은 PR을 보내게 됐습니다..:sob:

## 대대적인 프로젝트 공사:pick:

### 일단은 Cory의 피드백을 바탕으로 필요없는 Protocol 구현을 전부 걷어내고 새롭게 구성했습니다

- Protocol을 제대로 활용하는 방법에 대해서 열심히 고민해봤습니다

`Uploadable` 
-> Patch, Post 작업을 할 객체로 multipart-form 작업에 사용될 parameters를 요구

`MultipartProtocol`
-> multipart/form-data 형식의 Body작성하는 function을 구현

`URLRequestProtocol`
-> URLRequest를 만들고 해당 Request 내의 Body를 만드는 function을 구현

<br>

### 그리고 Network Post, Get, Patch, Delete를 하는 객체(OpenMarketAPIProvider)를 구현했습니다
![Untitled Diagram-2](https://user-images.githubusercontent.com/64566207/119227790-9e230000-bb4a-11eb-8f5d-f4fb1cad1fb8.png)

<br>

### 제일 많이 고민했던 Test에 관한 부분입니다
특히 네트워크에 의존하지 않고 테스트하는 방법에 대해 집중적으로 다뤘습니다~!

URLProtocol 를 활용하여 실패했을 경우 / 성공했을 경우의 Response가 제대로 나오는지 확인하였습니다
![스크린샷 2021-05-22 오후 10 13 18](https://user-images.githubusercontent.com/64566207/119227848-f65a0200-bb4a-11eb-8f8e-20909e8d8826.png)

2021-05-24 17:11 UTC, corykim0829 requested changes
수고 많았어요!! 정말 많이 바뀌었네요! 🤩

전반적인 구조는 많이 개선되어서 전보다 코드 가독성도 좋았습니다 😀

많은 삽질(?)을 통해 많은 것을 배웠을 것 같네요!

테스트 코드를 왜 작성하는지를 좀 더 고민해보고 작성해보면 좋을 것 같아요!
우선은 테스트 코드 먼저 수정하고 다른 부분 리뷰 반영해주세요!

2021-05-24 17:11 UTC, corykim0829 commented on OpenMarket/OpenMarketTest/OpenMarketAPIProviderTest.swift
> +      }
NSDataAsset 파일 추출을 따로 분리하여 테스트하면 매번 함수를 호출할 때마다 테스트를 안해도 될 것 같아요!

2021-05-24 17:11 UTC, corykim0829 commented on OpenMarket/OpenMarketTest/OpenMarketAPIProviderTest.swift
> +    setRequestHandler(shouldSuccess: true)
테스트 코드 전에 네트워크 요청에 대한 성공여부를 지정해주고 이에따라서 성공여부만 체크한다면, 당연한 결과가 나와서 테스트의 의미가 없어지는 것 같아요 🥲

알맞은 baseURL, parameter 등이 잘 요청되는지 확인하는게 어떨까요?

그러면 테스트 코드도 줄어들 것 같아요 😃

2021-05-25 01:10 UTC, kane-young commented on OpenMarket/OpenMarketTest/OpenMarketAPIProviderTest.swift
> +      }
넵! url, asset에 대한 유효성 검사를 따로 테스트 해주겠습니다~!!!ㅎㅎ

2021-05-25 04:35 UTC, KangKyung commented on OpenMarket/OpenMarket/Model/Response/TheOthers.swift
> +typealias ProductDeleteResponse = ProductSearchResponse
기존에 테스트코드를 작성하면서 필요했던 부분인데, 현재 쓰이지 않고 있어서 삭제하였습니다..!
꼼꼼하게 확인하지 못했어요..😥

2021-05-25 05:06 UTC, kane-young commented on OpenMarket/OpenMarket/Model/Request/ProductRegisterRequest.swift
> +}
OpenMarketAPIProvider 혹은 해당 struct가 채택하고 있는 프로토콜로 이전해보도록 하겠습니다!!

2021-05-25 13:02 UTC, kane-young commented on OpenMarket/OpenMarket/Network/URLRequestProtocol.swift
> +protocol URLRequestProtocol: MultiPartProtocol {
multiPart가 필요한 네트워크와 json이 필요한 네트워크가 따로 있기에 나중에 확장성을 위해 분리하여 구조를 다시 편성했습니다

2021-05-25 17:30 UTC, corykim0829 approved these changes
수고하셨습니다! 😀

2021-05-25 17:31 UTC, merged