[Step1] Coda, Ian
yagom-academy/ios-open-market pull request #27
Opened 2021-05-17 10:41 UTC by LeeSungNo-ian

@wonhee009 

## [Step1] PR
안녕하세요 라자냐 ! Step1 PR이 조금 늦었죠? 그만큼 깊게, 많이 공부하려고 노력했습니다 ! 라자냐의 냉철한 PR 부탁드리겠습니다 !

### 연습
1. 이번 프로젝트를 진행하기에 앞서 이안이 JSON Data를 Parsing 하는데 어려움을 느꼈어요. 그래서 코다의 도움으로 JSON Data를 Parsing 하는 **연습**을 해봤어요. 
2. String, Int, Bool 타입이 들어있는 JSON Data ('PersonJSON')를 생성한 후 Asset에 넣고, Parsing 을 하는 struct를 만들어보려 노력했어요 ! 😁
3. JSON Data 안에 여러 유형의 타입이 존재하므로 제네릭을 이용하면 Parsing을 했을 때, 어떤 타입에도 유연하게 대응할 수 있다고 생각해서 제네릭을 이용해봤습니다 ! 
4. JSONDecoder 타입에는 제네릭이 활용된 decode(_:from:) 인스턴스 메서드가 작성되어 있습니다. 이 인스턴스 메서드는 디코드할 데이터를 필요로 하는데 이 데이터를 NSDataAsset 타입을 통해 만들 수 있습니다! -> Ryan 블로그 
5. 또, UIKit을 import 를 해주며 NSDataAsset를 활성화 시켜줍니다.
6. 파라미터를 통해 값을 전달하는 원리를 알게 됐어요 !
<br>

7. Unit Test Target 을 추가해서 Unit Test 를 만들어봤어요 !
8. 오픈마켓은 Unit Test Target과 별개의 파일이다보니 사용할 수 없어서 @testable import OpenMarket 사용했어요. 저 attribute를 사용하면 오픈마켓 안에 있는 요소들을 쓸 수 있게 됩니다.
9. 테스트 함수 명을 만드는 것에 대해 알게 됐어요 ! `test_ItemJSON데이터가_JSONParser에_Decoding_돼서_thumbnails의_값을_확인하는함수()` 와 같이 한글을 사용해도 된다는 걸 알게 됐어요 😁
10. XCTAssertEqual 메서드를 사용해서 Parsing 이 잘 됐는지 확인해줍니다 🧑🏻‍💻
11. 타입을 활용할 땐 인스턴스로 구체화를 한 후 사용을 해줍니다 ! `var jsonPersonData = JSONPersonData()`
 

### 프로젝트
1. 연습을 토대로 item, items JSON Data 를 Asset 에 넣고 이것을 받아주는 타입을 구현해줬습니다 !

* item 
``` swift
struct Item: Codable {
    var id: Int
    var title: String
    var descriptions: String?
    var price: Int
    var currency: String
    var stock: Int
    var thumbnails: [String]
    var images: [String]?
    var registration_date: Double
}
```
* items
``` swift
struct Items: Codable {
    var page: Int
    var items: [Item]
}
```

2. item, items JSON Data 파일을 Parsing 하는 struct를 만들어봤습니다 !
``` swift
struct JSONParser<T: Codable> {
    var convertedData: T?
    
    mutating func parse(assetName: String) {
        let decoder = JSONDecoder()
        
        guard let assetData = NSDataAsset(name: assetName) else { return }
        guard let convertedData = try? decoder.decode(T.self, from: assetData.data) else { return }
        self.convertedData = convertedData
    }
}
```
<br>

3. Unit Test Target 을 추가해서 Unit Test 를 만들어봤어요 ! 
3. 테스트를 진행하던 도중 오타때문에 애먹은 기억이 나네요.. 오타에 더욱 더 신경 쓰겠습니다..
4. XCTFail()를 사용하여 오류가 생겼을 때를 확인 할 수 있었습니다 🕵🏻‍♂️ 

### 궁금한 점
1. Step 1 에서는 JSON Data 를 받아와 JSON Parser Struct를 사용했습니다 !
그런데 결국 저희가 사용하게 될 데이터는 서버에 있는 데이터인데,,
그렇다면 Step 1에서 만든 Struct는 추후에는 사용하지 않는 Struct가 될까요?

2. Unit Test 중 item JSON Data 가 올바르게 Parsing 됐는지 확인해보기 위해 item JSON Data를 mockData에 일일히 선언을 해줬어요 !
선언 후 `XCTAssertEqual(mockData, data)` 를 사용하여 Unit Test를 진행했는데, 혹시 이것보다 더 좋은 방법이 있을까요 ?
_( data: Item == jsonParserItem.convertedData )_

2021-05-17 13:52 UTC, wonhee009 requested changes
@LeeSungNo-ian @dacodaco 기다리던 PR~~~🎉
이안과 코다가 디스코드에서 열심히 하던거 제가 다 봤습니다👀
적어준 PR 메시지 보니까 이후에도 열심히 하셨군용!

- 현재 이안이랑 코다가 파싱 연습하면서 에셋에 json 파일이 여러개 들어가 있는데 이후에는 스텝에 필요한 json 파일만 남겨주세요😀
(현재 연습하면서 남겨진 파일들이 있는데 스텝에 필요한 파일들만 남겨주세요😆)

- 현재 PR에서는 서버와 통신하는 부분이 빠져있는거 같아요😢 이 부분 추가해주세요!

이안과 코다 수고하셨어요!
코멘트 확인하시고 이해 안가는 부분이나 논의하고 싶은 부분은 언제든 연락해주세요!

2021-05-17 13:52 UTC, wonhee009 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    }
`setUpWithErorr()`와 `tearDownWithError()`를 사용하지 않고 빈 메서드로 두었네요?!
저 두 메서드는 무슨 기능을할까요?🤔
그리고 빈 메소드는 코드의 가독성을 해치므로 제거해주세요☺️

2021-05-17 13:52 UTC, wonhee009 commented on OpenMarket/OpenMarket/Model/Item.swift
> +    var registration_date: Double
등록 일자를 `registration_date`로 정의했군요!
`registration_date`는 어떤 표기법일까요?👀
그리고 **Swift에서는 어떤 표기법을 사용하라고 권장할까요?**

2021-05-17 13:52 UTC, wonhee009 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +        }
🤔데이터 파싱 과정을 살펴볼까요?

1. `JSONParser` struct의 인스턴스 `jsonParserItem`을 생성
2. 인스턴스 메서드 `jsonParserItem.parse(assetName: _)`으로 인스턴스 내의 프로퍼티`convertedData`에 파싱된 데이터를 저장
3. 파싱된 데이터를 가져오기 위해서는 인스턴스에 접근해서 그 안의 `convertedData`에 접근

위와 같은 방식으로 이뤄지고 있네요!

- 위와 같이 **인스턴스를 생성해 `인스턴스 메서드`와 `인스턴스 프로퍼티`에 접근하는 방식의 장점과 단점은 무엇일까요?**
- 인스턴스를 생성하지 않고 어떻게 데이터를 파싱할 수 있을까요? ([이 문서](https://docs.swift.org/swift-book/LanguageGuide/Methods.html) 참고하면 좋을거 같아요☺️)

2021-05-18 00:45 UTC, dacodaco commented on OpenMarket/OpenMarket/Model/JSONParser.swift
> +struct JSONParser<T: Codable> {
`Item` 을 파싱하는 경우와 `Items` 를 파싱하는 경우에 
둘 다 사용해줄 수 있는 범용성 있는 타입을 만들고 싶었어요!

서버에서 받아오는 경우도 제네릭을 활용해보면 좋...을 것 같아요 (?)

2021-05-18 00:55 UTC, LeeSungNo-ian commented on OpenMarket/OpenMarket/Model/Item.swift
> +}
`Codable` 은 `Encodable` 과 `Decodable` 이 합쳐진 프로토콜이에요 !
`Encodable` 은 data 타입을 Encoding이 가능하도록 바꿔주는 프로토콜이고, `Decodable` 은 data 타입을 Decoding이 가능하도록 바꿔주는 프로토콜 입니다!
또, `Codable` 은 프로토콜이기 때문에 struct, enum, class 에서 전부 사용 가능합니다 😁

2021-05-18 01:19 UTC, LeeSungNo-ian commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    }
`setUpWithError()` 메서드는 테스트 코드를 시작하기 전에 값을 세팅해줍니다 !
`tearDownWithError()` 메서드는 반대로 테스트 코드가 실행이 된 후에 호출됩니다 !

언제 쓰일 수 있을까 생각해봤는데, Mock 의 상태를 초기화 해줄 때 사용하면 중복되는 코드를 줄일 수 있지 않을까 생각해봤어요 🤯

<img width="459" alt="스크린샷 2021-05-18 오전 10 04 52" src="https://user-images.githubusercontent.com/78950704/118575004-80f3d780-b7c0-11eb-8112-e14d9f6f1726.png">

2021-05-18 01:38 UTC, wonhee009 commented on OpenMarket/OpenMarket/Model/Item.swift
> +}
그렇다면 `Endocable`과 `Decodable`을 모두 채택할 필요가 있을까요?🤔

2021-05-18 08:04 UTC, dacodaco commented on OpenMarket/OpenMarket/Model/Item.swift
> +}
`Decodable` 만 채택해줘도 될 것 같아요 :)

2021-05-18 08:04 UTC, dacodaco commented on OpenMarket/OpenMarket/Model/Item.swift
> +    var registration_date: Double
뱀표기법이요 ^~^

2021-05-18 08:12 UTC, dacodaco commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +        }
호오.. 타입 메서드 말씀하시는거군요 !? 좋아요!! 꼭 기억해서 
프로젝트 진행하면서 공부해보겠습니다!!

2021-08-06 09:14 UTC, closed without merging