Step 1 : 모델 및 네트워킹 담당 타입 구현 [Joons,라자냐]
yagom-academy/ios-open-market pull request #3
Opened 2021-01-26 15:30 UTC by elddy0948

@delmaSong 
Delma 안녕하세요! 
리뷰 부탁드립니다 😄
Step 1 : 모델 및 네트워킹 담당 타입 구현

[구현한 부분]
- Networking 클래스에서 통신하는 부분을 하나의 메서드에서 처리하도록 분리
- 데이터 Encoding, Decoding 하는 부분을 제네릭을 사용하여 따로 구현
- HTTP 메서드와 URL을 각각 enum으로 구현
- model에 데이터가 알맞게 들어가는지 Unit Test 코드 작성.

2021-01-27 13:02 UTC, delmaSong requested changes
모델과 네트워킹 타입 만드느라 Joons와 라자냐 모두 수고하셨습니다 🔥
api 메소드에 따른 요청부가 어떻게 달라져야하는지 한번 확인해주시면 좋을 것 같고
이번에는 네트워크 요청부를 새로 만들어보았으니 그부분에 대한 테스트코드가 추가되면 좋을 것 같습니다!
자세한 사항은 아래 코멘트 확인해주세요 🌴

2021-01-28 01:55 UTC, wonhee009 commented on OpenMarket/OpenMarket/ViewController.swift
> +        Networking.registerGoods(form: form)
@delmaSong 

register 요청 보내고 response로 등록된 상품 JSON 받아오는거 확인했습니다!
생성된 상품의 id가 240번여서 해당 id로 상품 조회한 결과도 같이 첨부합니다!
(이미지도 잘 들어갔습니다!ㅎㅎ)

![스크린샷 2021-01-28 10 53 01](https://user-images.githubusercontent.com/30456206/106078591-02aeef00-6157-11eb-9704-ab24add2c129.png)
<img width="765" alt="스크린샷 2021-01-28 10 52 44" src="https://user-images.githubusercontent.com/30456206/106078601-05114900-6157-11eb-95a8-5285a3beebfd.png">
![스크린샷 2021-01-28 10 52 37](https://user-images.githubusercontent.com/30456206/106078602-05114900-6157-11eb-83dd-467608d8fb79.png)

2021-01-28 03:17 UTC, elddy0948 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +        }
forResource: 에 들어가는 파일명이 달라서 각각 파일을 가지고 테스트 하는 부분에서 거기에 맞는 목데이터를 가져오는 코드라서 setUp() 메서드에 합칠 수 없다고 생각했습니다.

2021-01-28 03:18 UTC, elddy0948 commented on OpenMarket/OpenMarket/Utility/MethodType.swift
> +}
- GET : 클라이언트가 서버측에 리소스를 요청 (CRUD - Read)
 - POST : 클라이언트가 서버의 리소스를 새로 만들 때 사용(CRUD - Create)
 - PATCH : 클라이언트가 서버의 리소스를 수정 할 때 사용(CRUD - Update. - 전체 수정)
 - DELETE : 클라이언트가 서버의 리소스를 삭제 할 때 사용(CRUD - Delete)

2021-01-28 04:11 UTC, elddy0948 commented
@delmaSong 
delma 리뷰 고마워요!

[register 요청을 보내고, 제대로 register되었는지 확인해보셨나요?]
 - 이 리뷰에 대해서 우선 register 요청에 대한 응답이 잘 오는 것을 확인은 했습니다. 그런데, [생성, 수정 요청도 위와같은 value면 될까요? api 문서를 다시 한번 확인해주세요] 이 리뷰에 대한 'multipartFormData' 에 대해서 찾아봤는데 'application/json' 으로 했을 때도 위의 리뷰에 달린 코멘트처럼 데이터가 잘 보내지는 것을 확인했는데, 어떤 부분에서 multipartFormData를 쓰는 이점이 있는지 궁금합니다 ! 

[Form 모델을 하나로 합치는 부분]
 - 기존에 3개의 Form 모델이 존재했었는데, 하나의 Form 모델로 합치고, 두개의 이니셜라이저를 통해 필요한 프로퍼티만 설정하도록 변경했습니다!

2021-01-28 14:21 UTC, delmaSong requested changes
> 이 리뷰에 대해서 우선 register 요청에 대한 응답이 잘 오는 것을 확인은 했습니다. 그런데, [생성, 수정 요청도 위와같은 value면 될까요? api 문서를 다시 한번 확인해주세요] 이 리뷰에 대한 'multipartFormData' 에 대해서 찾아봤는데 'application/json' 으로 했을 때도 위의 리뷰에 달린 코멘트처럼 데이터가 잘 보내지는 것을 확인했는데, 어떤 부분에서 multipartFormData를 쓰는 이점이 있는지 궁금합니다 !

음 현재 이미지를 파일 형태가 아닌 문자열로 보내고 있는데 API 문서에는 File Array로 받는다고 나와있네요 이부분 다시한번 확인해주세요!

> 기존에 3개의 Form 모델이 존재했었는데, 하나의 Form 모델로 합치고, 두개의 이니셜라이저를 통해 필요한 프로퍼티만 설정하도록 변경했습니다!

전보다 훨씬 나아졌어요! 뭔가 더 줄일 수 있을 것 같은??? 느낌도 드는데 이부분은 개발을 좀 더 진행해나가면서 봐도 좋을 것 같네요

라자냐와 Joons 수고하셨습니다! 
api 문서 다시한번 확인해주시고 관련 코드 수정해주세요! 
그리고 요청 보내는 메소드의 작업을 조금 더 잘게 쪼개볼 수 있을 것 같아요
프로토콜을 이용해서 관련 Request 타입만 설정하도록 만드는 것도 좋은 방법이 될 수도?

2021-01-28 14:21 UTC, delmaSong commented on OpenMarket/OpenMarket/Utility/Networking.swift
> +    }
현재는 API가 추가될때마다 그에맞는 새로운 CRUD 관련 메소드를 생성하게 되는 구조인데 이걸 어떻게 개선할 수 있을까요?
좀 더 잘게 쪼개서 재사용 가능한 관점에서 생각해볼까요?

2021-01-28 14:21 UTC, delmaSong commented on OpenMarket/OpenMarket/Utility/Networking.swift
> +    }
그러고보니 여기 메소드들은 그냥 JSONDecoder().decode를 쓴 것과 무슨 차이가 있을까요? 이걸 쓰는 requestToServer 메소드 쪽에서 제너릭을 받는 게 더 유연하게 쓸 수 있을 것 같군요

2021-01-28 14:52 UTC, delmaSong commented
테스터블한 네트워크 레이어에 관해 참고할만한 글 첨부해요😀 화이띵

https://medium.com/ios-os-x-development/isolating-tasks-in-swift-or-how-to-create-a-testable-networking-layer-d0380e69f7e3

2021-01-29 02:20 UTC, wonhee009 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +                  (200...299).contains(response.statusCode) else {
해당 테스트는 네트워킹의 한 흐름이라고 생각해 쪼갤 수 없다 판단했습니다. 
실패하는 원인을 좀 더 명확하게 알기 위해 Fail Message를 추가했습니다.

2021-01-29 14:56 UTC, wonhee009 commented
@delmaSong 

델마가 말해준대로 네트워크 레이어를 쪼개봤습니다!👋
`Request` 프로토콜을 통해 URLRequest에 관련한 info를 관리했습니다.
`NetworkDispatcher`에서는 네트워크 통신만 하도록 구성했고, `NetworkTask`에서는 통신 response를 통해 받은 data를 디코딩해 전달하도록 했습니다.
제네릭을 이용해 유연한 디코딩을 구현했습니다.

2021-01-30 04:57 UTC, delmaSong commented
개별 요청을 관통하는 요청 객체 등을 잘 만들어 주셨네요 👍🏼
그런데 지난번에 DeleteGoods, EditGoods를 줄이고 Goods를 생성자로 상황에 맞게 잘 생성해주셨는데  이번에 다시 프로토콜의 모습으로 부활해버렸네요😂

1. 모델이 하나 존재한다고 했을 때, 개별 CRUD 모델들이 따로 있게 된다면 모델의 갯수가 늘어가면 그와 관련한 CRUD 모델은 x4개씩 생기니 지난 번 생성자를 이용하셨던 것처럼 한 모델이 각 역할에 맞게 생성되게 만들어 이 부분은 줄여볼 수 있을 것 같아요!
2. 모델이 하나 존재한다고 했을 때, 개별 요청을 보내는 CRUD 메소드들이 있지요? 그게 현재 EditGoods, DeleteGoods라는 구조체들로 감싸져 있는데 이것도 1번과 동일하게 모델이 증가할때마다 x4개씩 증가해야하는 구조로 만들어져있습니다. 이는 1번을 개선한다면 함께 개선 될 여지가 있을 것 같아요

위에 말씀드린 1,2번 사항들은 스텝을 모두 마친 뒤에 개선해보면 좋겠습니다!
이것 저것 고민해보느라 너무 너무 수고 많으셨고 다음 스텝에서 뵙겠습니다.!

2021-01-30 04:57 UTC, merged