[Step 2] - JM, Kio
yagom-academy/ios-open-market pull request #30
Opened 2021-05-19 14:30 UTC by alwaysblu

@seizze 

[step 2] JM, Kio

안녕하세요 step2 PR 드립니다.

# 📌 코드를 작성할 때 고민되었던 점 :

1. 서버에 있는 아이템의 총 개수(테이블 뷰의 셀의 개수를 위해서)를 어떻게 하면 알 수 있을까 고민하였습니다.
2. 테이블뷰 discoutedPrice의 아래 이미지와 같은 레이아웃 문제가 있었습니다.
이러한 경우를 어떻게 처리하면 좋을지 고민해보았습니다.

<img width="530" alt="스크린샷 2021-05-20 오전 12 51 22" src="https://user-images.githubusercontent.com/75533266/118844215-c0780c00-b905-11eb-83cd-f4e74b8b4eaa.png">

3. 콜렉션 뷰 스크롤을 천천히 내리면 문제 셀에 데이터가 안들어가는 문제를 발견했습니다.
로그를 찍어본 결과 콜렉션뷰의 셀이 시뮬레이터에 등장하기 전에 검사하고 있는 것을 발견했습니다.
따라서 느리게 콜렉션뷰를 스크롤하면 데이터가 들어가지 않고 빠르게 스크롤을 하면 콜렉션뷰에 데이터가 들어가는 것을 확인하였습니다.
이 문제를 어떻게 해결할까 고민하였습니다.

4. 테이블 뷰의 셀의 높이를 셀의 콘텐츠의 크기에 따라 동적으로 하려고 하다가 잘안되서 모든 셀의 높이를 80으로 고정하여 문제를 해결하였습니다.

5. MVVM 패턴으로 리팩토링하려고 했는데 모델이 없어서 리팩토링하지 않았는데 진짜 모델이 없는데 맞는지 고민하였습니다.

# 📌 해결하지 못한 부분 :    

1. 아이템의 총 개수를 직접 119개를 코드로 작성해서 해결하였습니다.
2. 테이블뷰 discoutedPrice의 아래 이미지와 같은 레이아웃 문제 처리 방법을 결정하지 못하였습니다.
 
<img width="530" alt="스크린샷 2021-05-20 오전 12 51 22" src="https://user-images.githubusercontent.com/75533266/118844215-c0780c00-b905-11eb-83cd-f4e74b8b4eaa.png">

3. 콜렉션 뷰 스크롤을 천천히 내리면 문제 셀에 데이터가 안들어가는 문제를 발견했습니다.
로그를 찍어본 결과 콜렉션뷰의 셀이 시뮬레이터에 등장하기 전에 검사하고 있는 것을 발견했습니다.
따라서 느리게 콜렉션뷰를 스크롤하면 데이터가 들어가지 않고 빠르게 스크롤을 하면 콜렉션뷰에 데이터가 들어가는 것을 확인하였습니다.
이 문제를 어떻게 해결할까 고민하고 있습니다.

# 📌 조언을 얻고 싶은 부분 :
1. step1에서 말씀주신 것처럼 Request 로 모델을 통합해 봤는데 이 부분에 대해서 조언을 얻고 싶습니다.
2. 어떻게 하면 전체 아이템의 개수를 알 수 있을지에 대해서 조언을 얻고 싶습니다.
3. discountedPrice와 price의 글자의 개수를 직접 세서 글자가 깨지는 글자수 이상이면 수평방향으로 가격을 나열하는게 아니라 수직방향으로 나열하려고 하는데 이 부분에 대해서 조언을 얻고 싶습니다.
4. 콜렉션 뷰 스크롤을 천천히 내리면 문제 셀에 데이터가 안들어가는 문제에 대해서 조언을 얻고 싶습니다.
5. 테이블 뷰의 셀의 높이를 셀의 콘텐츠의 크기에 따라 동적으로 하는 부분이 잘안되는데 이부분에 대한 팁을 얻고 싶습니다.
(xib 파일의  높이의 레이아웃을 아래 그림과 같이 잘 맞춰주면 된다는 건 알겠는데 잘했다고 생각해도 동적으로 셀의 높이가 구현되지 않았습니다.)

![](https://images.velog.io/images/alwaysblu/post/660d026e-d463-4be8-94af-39ae7fbfd990/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202021-05-19%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%205.18.49.png)

예를들어 셀안에 수평방향 스택뷰([이미지][레이블]) 하나만 있다고 할때 
* 스택뷰의 Alignment와 Distribution을 모두 Fill로 설정하고
* 스택뷰의 위, 아래, 오른쪽, 왼쪽를 각각 edge로부터 10씩 떨어지도록 하고 
* 레이블의 줄수를 0으로 하고 
* 레이블의 수직을 compression resistance priority를 1000으로 하면 

레이블의 텍스트에 크기에 따라 테이블뷰 셀의 크기가 변동되어야 하는게 아닌지 궁금합니다.

6. MVVM 패턴으로 구현할 모델이 현재 없는 것이 맞는지에 대한 조언을 얻고 싶습니다. 감사합니다!

7. 아래의 segmented control의 모양이 프로젝트에서와 조금 다른데 이 부분을 어떻게 고치는 것이 좋을지 조언을 주신다면 감사하겠습니다.

<img width="141" alt="스크린샷 2021-05-19 오후 11 38 43" src="https://user-images.githubusercontent.com/75533266/118832196-62462b80-b8fb-11eb-867c-8650621613e6.png">

![](https://images.velog.io/images/alwaysblu/post/54a6c2d3-3d0c-449f-9596-baa827b6975a/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202021-05-19%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%2011.23.04.png)

8. 취소선이 전부 제거되지 않고 한 두개씩 남아 있는데 cell의 prepare 함수가 실행되지 않고 재사용되는 cell도 있어서 그런건지 궁금합니다. 

감사합니다!

2021-05-20 23:00 UTC, seizze requested changes
수고 많으셨습니다~~ 👏👏👏

아래에 코멘트에 써주신 내용에 대해 의견 남겼으니 참고해 주세요. 🙂

> step1에서 말씀주신 것처럼 Request 로 모델을 통합해 봤는데 이 부분에 대해서 조언을 얻고 싶습니다.

해당 부분에 코멘트 남겼습니다~!

> 어떻게 하면 전체 아이템의 개수를 알 수 있을지에 대해서 조언을 얻고 싶습니다.

이 내용에 대해서도 코멘트로 남겼습니다. ㅎㅎ

> discountedPrice와 price의 글자의 개수를 직접 세서 글자가 깨지는 글자수 이상이면 수평방향으로 가격을 나열하는게 아니라 수직방향으로 나열하려고 하는데 이 부분에 대해서 조언을 얻고 싶습니다.

<img width="400" src=https://user-images.githubusercontent.com/49332230/119058932-45e4e480-ba0a-11eb-9fc4-ea32df98b51e.jpg>
위 이미지에서와 같이 레이블들의 총 길이가 가로폭을 넘어갈 때 다음줄로 넘기는 기능은, 컬렉션뷰를 이용할 수 있습니다.ㅎㅎ


> 콜렉션 뷰 스크롤을 천천히 내리면 문제 셀에 데이터가 안들어가는 문제에 대해서 조언을 얻고 싶습니다.

일단 서버 요청 및 셀을 그리는 로직에 대한 코멘트 남겼는데요, 이 부분이 먼저 근본적으로 해결되어야 그 다음 순서로 문제를 파악해볼 수 있을 것 같아요. 중요한 부분이니 데이터소스 메서드 호출, 서버 요청 등의 흐름을 정확히 파악하고 중점적으로 수정해 보시면 좋을 것 같습니다. 수정 후에도 계속 문제가 발생한다면 그때 다시 체크해 봐요~!

> 테이블 뷰의 셀의 높이를 셀의 콘텐츠의 크기에 따라 동적으로 하는 부분이 잘안되는데 이부분에 대한 팁을 얻고 싶습니다. (xib 파일의 높이의 레이아웃을 아래 그림과 같이 잘 맞춰주면 된다는 건 알겠는데 잘했다고 생각해도 동적으로 셀의 높이가 구현되지 않았습니다.)

잘 하셨네요~! 아마 빠진 부분이 있어서 그럴거에요. ㅎㅎ [Working with Self-Sizing Table View Cells](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AutolayoutPG/WorkingwithSelf-SizingTableViewCells.html) 여기를 참고해 보시면 좋을 것 같아요. 블로그를 여러 곳 둘러다니며 보는 것보다 공식 문서 하나를 완벽하게 이해하는게 더 좋은 방향입니다.

> MVVM 패턴으로 구현할 모델이 현재 없는 것이 맞는지에 대한 조언을 얻고 싶습니다. 감사합니다!

JM,Kio가 현재 생각하고 있는 "모델"의 정의가 뭘까요? 궁금하네요~
질문이 이해가 잘 안가는데, 현재는 기능이 별로 없어서 MVVM으로 구현할 만한 내용이 없냐고 물어보신 거라면 답은 아닙니다~!

> 아래의 segmented control의 모양이 프로젝트에서와 조금 다른데 이 부분을 어떻게 고치는 것이 좋을지 조언을 주신다면 감사하겠습니다.

아마 요구사항 문서의 이미지를 캡쳐한 앱과 iOS 버전이 달라서인 것 같아요. 현재는 크게 신경쓰지 않으셔도 될 것 같지만, 꼭 동일하게 고치고 싶다면 컨트롤을 커스텀하는 방법에 대해 알아보시면 좋을 것 같습니다.

> 취소선이 전부 제거되지 않고 한 두개씩 남아 있는데 cell의 prepare 함수가 실행되지 않고 재사용되는 cell도 있어서 그런건지 궁금합니다.

취소선이 어떨 때 어디에 남아있나요? 이미지라던지, 재현 경로라던지 좀 더 구체적인 정보가 필요할 것 같아요. prepare 함수가 실행되지 않고 재사용되는 경우는 없습니다!


추가로, 현재 콘솔에 레이아웃이 깨졌다고 출력되고 있는데요, 이 부분은 원인을 파악해 보시고 해결하는 게 좋을 것 같습니다. 디버깅하는 과정을 경험하는 것도 중요합니다 ☺️

잘 이해가 가지 않거나 제가 빼먹은 부분이 있다면 언제든지 디엠 주세요.

2021-05-24 17:04 UTC, alwaysblu commented on OpenMarket/Cell/TableViewCell.swift
> +        self.itemImage.image = UIImage(named: "indicator")
UIActivityIndicatorView 를 이용하여 로딩을 구현해봤습니다!

2021-05-24 17:06 UTC, alwaysblu commented on OpenMarket/View/ItemListViewController.swift
> +    }
페이지의 번호를 키값으로 하고 해당 페이지의 item 배열을 값으로 하는 딕셔너리를 구현하여 딕셔너리의 count 만큼 셀을 생성하도록 구현했습니다.

2021-05-24 17:07 UTC, alwaysblu commented on OpenMarket/View/ItemListViewController.swift
> +        getItemsOfPageData(tableViewCell: cell, collectionViewCell: nil, indexPath: indexPath)
scrollViewDidScroll 함수를 이용하여 스크롤뷰가 설정한 위치만큼 내려왔을때 서버에 데이터를 요청하는 방식으로 구현했습니다!

2021-05-24 17:09 UTC, alwaysblu commented on OpenMarket/Cell/TableViewCell.swift
> +        let itemIndex = indexPath.row % 20
이 코드는 나머지를 이용하여 아이템을 업데이트 해주던 코드였는데 구현이 변경되어 삭제했습니다!

2021-05-24 17:09 UTC, alwaysblu commented on OpenMarket/View/ItemListViewController.swift
> +    @IBOutlet var superView: UIView!
넵 네이밍에 주의하겠습니다! 이 코드는 구현이 변경되어 삭제했습니다!

2021-05-24 17:11 UTC, alwaysblu commented on OpenMarket/View/ItemListViewController.swift
> +        }.resume()
NetworkManager라는 네트워크 모듈을 만들어 분리했습니다!

2021-05-24 17:13 UTC, alwaysblu commented on OpenMarket/Cell/TableViewCell.swift
> +                }
기존에 가로 스택뷰에서 레이아웃을 변경하여 겹쳐지지 않도록 했습니다!

취소선 설정도 한번만 되도록 변경하였습니다!

2021-05-24 18:01 UTC, alwaysblu commented
@seizze 

안녕하세요 하이디!
 
테이블뷰와 콜렉션뷰를 모두 사용하는 방식에서 콜렉션뷰만 사용하고 레이아웃만 변경시키는 방식으로 변경하였습니다.        

또 데이터를 딕셔너리에 캐싱하는 방식으로 변경하였습니다.       

남겨주신 코드리뷰 중에서 Request 모델을 합치는 부분과 URL을 안전하게 보관하는 방법에 대해서 고민해보고 있습니다.     

swift에서 암호화하는 방식을 검색해본 결과 많이 사용되는 암호화 방식인 AES 방식 중 하나를 사용해서 암호화를 시도해보려고 하는데

이 부분에 대해서 조언을 얻고 싶습니다.

감사합니다!

2021-05-24 18:15 UTC, alwaysblu commented on OpenMarket/Constant/Network.swift
> +}
1. info.plist에 저장하는 방법
2. 난독화하는 방법
3. 파일로 저장한 후에 불러오는 방법
4. 프라이빗 데이터 베이스에 저장하는 방법

추가적으로 어떤 방식이 더 있는지 조사하고 있습니다.

또 조사한 방법 중에 어떤 것을 사용해야할지 기준을 세우려고 고민하고 있습니다.

2021-05-24 18:23 UTC, alwaysblu commented on OpenMarket/View/ItemListViewController.swift
> +        }.resume()
```swift
class NetworkManager {
    
    static var shared = NetworkManager()
    var isPaginating = false
    let session: URLSession
    
    init() {
        let config = URLSessionConfiguration.default
        session = URLSession(configuration: config)
    }
    
    func getItemsOfPageData(pagination: Bool, pageNumber: Int, completion: @escaping (Data?, Int?)->(Void))  {
        if pagination {
            isPaginating = true
        }
        let url = Network.baseURL + "/items/\(pageNumber)"
        guard let urlRequest = URL(string: url) else { return  }
        URLSession.shared.dataTask(with: urlRequest) { [weak self] (data, response, error) in
            self?.checkValidation(data: data, response: response, error: error)
            if pagination {
                self?.isPaginating = false
            }
            completion(data, pageNumber)
        }.resume()
    }
    
    private func checkValidation(data: Data?, response: URLResponse?, error: Error?) {
        if let error = error {
            fatalError("\(error)")
        }
        
        guard let httpResponse = response as? HTTPURLResponse else {
            print("Invalid Response")
            return
        }
        
        guard (200...299).contains(httpResponse.statusCode) else {
            print("Status Code: \(httpResponse.statusCode)")
            return
        }
        
        guard let _ = data else {
            print("Invalid Data")
            return
        }
    }
    
}

```

2021-05-26 05:33 UTC, seizze approved these changes
안녕하세요 JM, Kio!

레이아웃 변경 방식이 이전 방식보다 좋아졌네요 👍 수고 많으셨습니다.
추가로 드린 피드백들은 다음 스텝을 진행하며 참고해 주세요.

> CellViewModel 을 만들어서 Cell이라는 View와 Item이라는 Model이 직접 접근하지 못하도록 MVVM 패턴을 구성해보았습니다.
이외에 MVVM 패턴을 또 어디에 적용을 시켜보면 좋을지 조언을 얻고 싶습니다.

MVVM 관련 코멘트도 하나 남겼는데요, 만약 MVVM을 하실 거라면 잘 된 예시를 리서치해서 이해하고, 실제 해당 예제대로 적용해보는 과정이 필요할 것 같습니다. 지금의 CellViewModel은 ViewModel이라고 할 수 없습니다 😢

> swift에서 민감한 정보를 숨기는 방식을 조사해본 결과
많이 사용되는 난독화 방식을 사용해서 암호화를 시도해보려고 하는데,
적절한 선택을 한 것인지 아니면 다른 방법을 선택하면 좋을지 아니면 다른 방법을 더 조사하면 좋을지
이 부분에 대해서 조언을 얻고 싶습니다.

스레드에 답변 남겼습니다~!

2021-05-26 05:33 UTC, seizze commented on OpenMarket/View/ItemListViewController.swift
> +            return cell
여기 코드는 호출되지 않는 것으로 보이는데 맞나요?

2021-05-26 05:33 UTC, seizze commented on OpenMarket/View/Cell/ListCollectionViewCell.swift
> +            let imageData = try Data(contentsOf: imageURL!)
스크롤 시 앱이 많이 버벅이던데, 아마 이 줄 때문일 것 같아요. 어떻게 해결하면 좋을까요? Data(contentsOf:)는 동기일까요 비동기일까요? ㅎㅎ

2021-05-26 05:33 UTC, merged

2021-05-26 05:33 UTC, seizze commented on OpenMarket/Constant/Network.swift
> +}
간단하게는 .gitignore로 해당 파일을 git으로 관리하지 않도록 만드는 방법도 있습니다.
요지는 버전 스냅샷에 포함시키지 않는거라서요 ☺️

2021-05-26 05:38 UTC, seizze commented on OpenMarket/View/ItemListViewController.swift
> +        getItemsOfPageData(tableViewCell: cell, collectionViewCell: nil, indexPath: indexPath)
💯 좋습니다~