[Step1] Kio
yagom-academy/ios-open-market pull request #38
Opened 2021-06-02 17:53 UTC by Kioding

@corykim0829 

코리🙋🏻‍♂️   PR을 보내봅니다😆
지난 프로젝트에 이어 한번 더 하는 내용인데도 아직 부족한 게 많은 것 같네요😭
제가 중점으로 공부한 부분은 `API문서 보는 방법`, `JSON 파싱`, `Unit Test`입니다.
[README](https://github.com/Kioding/ios-open-market/tree/main)

<br>

# Step1
### API 모델 타입 구현

<details>
<summary>Response</summary>
<div markdown="1">

<br>

- ItemPage
  
```swift
struct ItemPage: Decodable {
    var page: Int
    var items: [ItemShortInfo]
}

struct ItemShortInfo: Decodable {
    var id: Int
    var title: String
    var price: Int
    var currency: String
    var stock: Int
    var discountedPrice: Int?
    var thumbnails: [String]
    var registrationDate: Int
    
    private enum CodingKeys: String, CodingKey {
        case id, title, price, currency, stock, thumbnails
        case discountedPrice = "discounted_price"
        case registrationDate = "registration_date"
    }
}
```
  
- ItemDetail
  

```swift
struct ItemDetail: Decodable {
    var id: Int
    var title: String
    var descriptions: String
    var price: Int
    var currency: String
    var stock: Int
    var discountedPrice: Int?
    var thumbnails: [String]
    var images: [String]
    var registrationDate: Int

    private enum CodingKeys: String, CodingKey {
        case id, title, descriptions, price, currency, stock, thumbnails, images
        case discountedPrice = "discounted_price"
        case registrationDate = "registration_date"
    }
}
```

</div>
</details>

<details>
<summary>Request</summary>
<div markdown="1">    
  
  <br>
  
- ItemRegistraion

```swift
struct ItemRegistration {
    var title: String
    var descriptions: String
    var price: Int
    var currency: String
    var stock: Int
    var discountedPrice: Int?
    var images: [String]
    var password: String
    
    private enum CodingKeys: String, CodingKey {
        case title, descriptions, price, currency, stock, images, password
        case discountedPrice = "discounted_price"
    }
}
```

- ItemModification
  
```swift
struct ItemModification {
    var title: String?
    var descriptions: String?
    var price: Int?
    var currency: String?
    var stock: Int?
    var discountedPrice: Int?
    var images: [String]?
    var password: String
    
    private enum CodingKeys: String, CodingKey {
        case title, descriptions, price, currency, stock, images, password
        case discountedPrice = "discounted_price"
    }
}
```
  
- ItemDelete
```swift
struct ItemDelete: Encodable {
    var password: String
}
```

</div>
</details>

### Unit Test
- Mock Data 파일로 decoding 하고, 같은 정보를 가진 가짜 객체를 만들어 XCTAssertEqual로 비교 

<br>

# 조언을 얻고 싶은 부분
1. API 모델 타입부분에서 Request 3가지 모델로 구현하고, Response 2가지 모델로 구현하였습니다. Request 모델은 옵셔널로 합치는 방법도 고민했지만, 옵셔널이라는 걸 다른 옵션으로 보고 나누었고, Response 모델에서는 반복되는 내용은 하나로 구현하였습니다. API 모델을 짜면서 잘 와닿지 않았는데, 실제 웹사이트에서는 `HTTP Method`에 따로 구별하여 구현하는지 궁금합니다. 

2. test에서 `item` mock data를 진행할 때는 객체에 equatable을 채택하여 가짜 객체를 하나 만들어 비교하였는데, `items` mock data도 같은 방법으로 비교할까 고민했는데 가짜 객체를 만들기 위한 시간이 많이 소요될 것 같아 만들지 않았습니다. 디코딩이 된 상태에서 `XCTAssertEqual` 을 하는 의미가 있을지 궁금합니다.

3. Unit Test에서 코드 상에서 `fatalError()`를 사용했는데 `XCTFail()`도 크게 다른 기능이 없는 게 아닌가 싶은데 어떤 구별점을 두고 쓰면 좋을 지 궁금합니다🖐 
[Any way to test that fatalError() is called?](https://github.com/Quick/Nimble/issues/234)
[Unit Test fatalError in Swift](https://stackoverflow.com/questions/32873212/unit-test-fatalerror-in-swift)

2021-06-04 05:46 UTC, corykim0829 requested changes
수고하셨어요 Kio! 👏👏👏👏
궁금하신 부분에 대해서 답변을 했는데, 혹시나 헷갈리거나 애매한 부분은 DM 주세요!

같이 이야기 좀 더 해보면서 step1은 조금만 더 수정해봐요 ㅎ

> API 모델 타입부분에서 Request 3가지 모델로 구현하고, Response 2가지 모델로 구현하였습니다. Request 모델은 옵셔널로 합치는 방법도 고민했지만, 옵셔널이라는 걸 다른 옵션으로 보고 나누었고, Response 모델에서는 반복되는 내용은 하나로 구현하였습니다. API 모델을 짜면서 잘 와닿지 않았는데, 실제 웹사이트에서는 HTTP Method에 따로 구별하여 구현하는지 궁금합니다.

➡️ 제 생각에는 서버 환경에서 optional 차이도 다르기 때문에, 다른 모델로 구현하는게 맞는 것 같아요! 잘 하셨어요 👍 만약 메소드가 다르더라도, 객체 타입이 동일했다면 같은 객체로 처리하면 됩니다 ㅎ

> test에서 item mock data를 진행할 때는 객체에 equatable을 채택하여 가짜 객체를 하나 만들어 비교하였는데, items mock data도 같은 방법으로 비교할까 고민했는데 가짜 객체를 만들기 위한 시간이 많이 소요될 것 같아 만들지 않았습니다. 디코딩이 된 상태에서 XCTAssertEqual 을 하는 의미가 있을지 궁금합니다.

➡️ 맞아요! 사실 큰 의미가 없어요! 그래서 값이 잘 처리 됐는지만 확인하는 정도만 테스트해도 좋을 것 같아요. 그래서 json 파일을 해보고 mock 이용한 테스트를 하기 보다는 실제 네트워크쪽을 사용한 테스트로 바로 넘겨가도 괜찮을 것 같아요. 물론 실제 네트워크를 연결하지 않고 하는 테스트로요!

> Unit Test에서 코드 상에서 fatalError()를 사용했는데 XCTFail()도 크게 다른 기능이 없는 게 아닌가 싶은데 어떤 구별점을 두고 쓰면 좋을 지 궁금합니다🖐
Any way to test that fatalError() is called?
Unit Test fatalError in Swift

➡️ fatalError는 앱을 강제종료 시키기 때문에, 정말정말 특별한 경우가 아니라면 사용하지 않는게 좋아요!

> api문서에 있는 HTTP Method를 현재로써는 어떻게 다루어야 할지 모르겠어서 도움을 구하고 싶습니다. URLsession을 본다고는 봤는데, 무엇을 먼저 보는 게 좋을까요?😭

➡️ HTTP 메소드 자체에 집중하시기 보다는 네트워크에 대해서 공부하는게 좋을 것 같기는 해요. 그 중에서도 GET 메소드가 가장 많이 쓰이니까. URLSession과 GET 메소드를 사용한 네트워크 예시를 찾아보는 것도 좋을 것 같아요!

2021-06-04 05:46 UTC, corykim0829 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +            fatalError("Item 정보 읽기 실패")
fatalError 보다는 다른 XCT 함수를 사용하는게 좋을 것 같아요!

2021-06-04 06:01 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController.swift
> +        print()
의미 없는 코드는 다 지우겠습니다 😆

2021-06-04 06:02 UTC, Kioding commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +            fatalError("Item 정보 읽기 실패")
`XCTfail()` 로 변경하였어요!

2021-06-04 06:09 UTC, Kioding commented on README.md
> +### 트러블슈팅 (Troubleshooting)
cory 감사합니다😁

2021-06-10 08:36 UTC, Kioding commented
@corykim0829 👨‍💻

코리!!! 초큼 수정해봤습니다!
- `Feat: APIError 열거형 추가` 커밋메시지에서 나누지 않고 한번에 업로드한 게 많습니다😭
- 코리가 보내준 [Custom Mock Network Request](http://minsone.github.io/ios/mac/ios-mock-network-request)와, [iOS Networking and Testing](https://woowabros.github.io/swift/2020/12/20/ios-networking-and-testing.html)를 참고하였고, 코다에게도 도움을 많이 받았습니다. 
- fake라는 단어는 아무 생각없이 썼었는데, 찾아보니 여기서는 비교객체라면 dummy를 쓰는 게 좋지 않나 생각이드네요. 덕분에 여러 용어에 대해 접할 수 있었습니다!
- 테스트는 여전히 난관이지만, 처음보다는 구성이 많이 바뀐 것 같습니다. 그렇다고 잘 짰다는 건 미지수지만, 마구마구 한마디 부탁드립니다!

2021-06-14 18:38 UTC, corykim0829 requested changes
Kio 수고 많았어요!

고민을 많이하고 많은 시도를 한게 보이네요 👍

MockURLSession이나, URLSessionProtocol은 구현을 잘 했는데, 실제 테스트에서는 사용하지 않은 것 같아요. 이유가 있나요?

전반적으로 테스트를 위한 코드를 작성한 것 같아서 아쉬워요. 네트워크 관련 코드를 작성하면서 테스트를 할 수 있는 구조로 코드를 작성해야한다는 점을 생각하면서 공부하면 좋을 것 같아요!

실제 네트워크 요청하는 객체를 통해서 테스트를 하고, 실제 통신에도 사용하면 좋을 것 같아요!!

궁금한점은 또 물어봐주세요!

2021-06-14 18:38 UTC, corykim0829 commented on OpenMarket/OpenMarketTests/MockURLSession.swift
> +    var isRequestSuccess: Bool
isRequestSuccess라고 변수명이 있으면 MockURLSession 인스턴스를 생성할 때 요청의 성공 여부에 대한 결과를 주입하는 것 처럼 보여요!

2021-06-14 18:38 UTC, corykim0829 commented on OpenMarket/OpenMarket/Model/NetworkManger/MockURLSessionProtocol.swift
> +protocol MockURLSessionProtocol {
이 프로토콜에 역할은 무엇인가요?

2021-06-15 14:25 UTC, Kioding commented on OpenMarket/OpenMarketTests/MockURLSession.swift
> +import UIKit
아 따라 해보는 예제에서 사용하여 저렇게 사용해봤는데 알려주셔서 감사합니다!!

2021-06-15 14:26 UTC, Kioding commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +                    completion(.failure(error ?? APIError.unknownError))
아 그럴 수 있겠네요! 코리 말대로 따로따로 처리해주는 게 좋을 것 같아요!

2021-06-15 14:27 UTC, Kioding commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +                    guard let decodingData = try? JSONDecoder().decode(ItemDetail.self, from: data) else {
그냥 디코딩이라고만 생각했는데 네이밍에 대한 조언을 이렇게 주셔서 감사합니다. 수정해보겠습니다 :)

2021-06-19 08:01 UTC, closed without merging