Step 1 : 모델 및 네트워킹 담당 타입 구현 (Sole, Bam)
yagom-academy/ios-open-market pull request #4
Opened 2021-01-26 20:02 UTC by hcooch2ch3

@O-O-wl 
붱이 안녕하세요. 늦은 밤(이른 아침?) 중에 죄송합니다... Step 1 리뷰 부탁드립니다!

<구현 내용>
1. Item, ItemToDelete, ItemToGet 등 JSON 디코딩, 인코딩을 위한 struct 구현.
2. URLManager : OpenMarketAPI에서 사용할 url을 저장하고 있는 구조체.
3. OpenMarketAPI : 상품등록,  상품조회 등의 요청을 담당하는 클래스.
4. Parser : decode, encode의 기능을 담당하는 구조체.
5. 모듈 내 메서드를 테스트 하기 위한 테스트 코드 구현.

2021-01-27 16:44 UTC, O-O-wl requested changes
네트워크를 구조화하고 테스트까지 해보셨군요 👍👍👍👍
모델과 typealias도 의도에 맞게 잘 사용하신 것 같아요

개발단계에서 계획했던 객체들의 역할들을 간단히 답변으로 달아주실 수 있으실까요? 
답변을 달면서 정리를 해보시는 것도 좋을 것같아요 🙇‍♂️

2021-01-27 16:44 UTC, O-O-wl commented on OpenMarket/OpenMarket/NetWork/OpenMarketAPI.swift
> +    static func getItem(id: Int, _ completionHandler: @escaping (ItemToGet) -> Void) {
- requst를 만들고
- 네트워크 요청 하고
- 디코드를 하는 것
 까지 한 곳에서 하고 있네요 
이부분을 아토믹하게 테스트할 수 있을까요? 
더 잘게 쪼개야 각각을 테스트할 수 잇을것 같아요

2021-01-27 16:44 UTC, O-O-wl commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +        wait(for: [testExpectation], timeout: 5)
실제 네트워크를 테스트하고있네요
네트워크가 정상적으로 동작하지 않는다면 실패하는 테스트가 될 것 같아요
OpenMarketAPI의 역할을 좀더 세분화하고 의존성 주입을 이용하면 더 많은 것들을 독립적으로 테스트하실 수 있을 것 같아요

2021-01-28 10:48 UTC, hcooch2ch3 commented on OpenMarket/OpenMarket/NetWork/NetworkMethod.swift
> +    case getItem
@O-O-wl 
표준을 따른다는 것이 case를 표준 이름처럼 GET, POST, PATCH 이렇게만 남겨 놓는 것가요? 아니면 getList, getItem 을 GETList, GETItem 이렇게 대문자로 바꾸는것을 의미하는 건가요? 아니면 이 두 경우가 다 아닌가요? 🤔

2021-01-28 10:51 UTC, hcooch2ch3 commented on OpenMarket/OpenMarket/JsonData/ServerError.swift
> +    let error: Bool
@O-O-wl 
네 명세에 Bool로 나와 있습니다.
> {
  "error": true,
  "reason": "Not Found"
}
출처: [오픈마켓 명세](https://docs.google.com/spreadsheets/d/1P5CblgFsgq_7FbYbe1_KslQz2Pf3p4Vi9cnH_fVD6RE/edit#gid=1153044612)

2021-01-29 11:21 UTC, O-O-wl commented on OpenMarket/OpenMarket/NetWork/NetworkMethod.swift
> +    case getItem
RESTful API에는 어떤 요소들이 있을까요?
HTTPMethod / Endpoint 는 어떤 차이가 있을까요? 한번 공부해보셔도 좋을 것 같아요 🙇‍♂️

2021-01-29 11:25 UTC, O-O-wl commented on OpenMarket/OpenMarket/JsonData/ServerError.swift
> +    let error: Bool
네넵 그런 뜻의 코멘트는 아니었어요
ServerError.error 보다 더 명시적인 이름이 있지 않을까 했어요

error 프로퍼티의 이름은 뭔가 에러의 정보또는 에러 자체를 표현하는 느낌이라서 다른 좀 더 명시적인 네이밍은 없을까요?

2021-02-01 15:58 UTC, myssun0325 commented on OpenMarket/OpenMarket/NetWork/OpenMarketAPI.swift
> +    static func getItemList(page: Int, _ completionHandler: @escaping (ItemsToGet) -> Void) {
부엉이: 요거럐요.
https://github.com/Moya/Moya/blob/master/Sources/Moya/TargetType.swift

2021-02-02 14:15 UTC, hcooch2ch3 commented on OpenMarket/OpenMarket/JsonData/ItemToGet.swift
> +    var registrationDate: Double
let은 init 에서 초기화한 이후로는 값 변경이 불가능하고, var는 계속 변경이 가능합니다.

2021-02-02 14:24 UTC, hcooch2ch3 commented on OpenMarket/OpenMarket/NetWork/OpenMarketAPI.swift
> +    private static var ephemeralSession = URLSession(configuration: .ephemeral)
static 메서드만 가진 클래스는 메소드만 데이터 영역에 저장되고, 싱글턴은 객체 하나가 데이터 영역에 저장되는 차이가 있습니다.

2021-02-02 14:45 UTC, hcooch2ch3 commented
@O-O-wl 
- OpenMarketAPI 의 URLRequest를 만드는 기능, Decode 기능, Encode 기능, 네트워크 요청 기능을 제네릭을 이용하여 분리해보았습니다.
- MultipartDataForm을 다룰 수 있는 모듈을 구현하였습니다. (아이템 등록 및 수정은 MultipartDataForm로 상품 정보를 보내는 것으로 서버가 바뀌어서요)
- 이외에 리뷰해주신 내용 수정해서 반영해보았습니다.

재리뷰 부탁드려요 😃

2021-02-03 16:18 UTC, O-O-wl approved these changes
고생하셨어요 솔밤~.~ 
머지할게요  다음 스탭진행하면서 코멘트를 참고해주세요 😎

2021-02-03 16:18 UTC, O-O-wl commented on OpenMarket/OpenMarket/MultipartFormData/MultipartFormData.swift
> +        return "Boundary-\(NSUUID().uuidString)"
NS는 어떤 키워드일까요?
NSString - String 
NSData - Data
Apple NextStep에 대해 알아볼까요

2021-02-03 16:18 UTC, O-O-wl commented on OpenMarket/OpenMarket/NetWork/NetworkMethod.swift
> +            return "/item"
이런경우라면 
```
case .getItem, .post, . patch, . delete : return "return/item"
```

2021-02-03 17:04 UTC, soleJin commented on OpenMarket/OpenMarket/NetWork/URLManager.swift
> +        }
기능적인 차이라기 보다는
enum HTTPMethod: String 이렇게 원시값을 줘서 HTTPMethod.get.rawValue로 표현할 수 있지만 이것보다는
description으로 표현하면 더 잘 읽히지 않을까 한건데 기능적으로도 차이가 있을까요?? 
(사실 저번 은행? 프로젝트에서 우선순위를 표현할 때 rawValue보다는 priority로 표현했을 때 눈에 잘 읽혀서 앞으로 이렇게 해야겠다 생각했던거라 이번에도 똑같이 적용했습니다)

2021-02-03 17:08 UTC, soleJin commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +                dump(d)
print는 간략한 정보를 출력한다면 dump는 조금더 자세한 정보를 출력하는 차이점이 있어요 :)

보통 ItemToGet에서 원하는 정보만 쏙 빼서 볼 때 print를, 그렇지 않을때 dump를 이용하는데  
개인적으로 해당 오브젝트가 어떻게 구성되어있는지 한 번에 확인할 수 있어서 애용하고 있습니다 :)

2021-02-03 17:29 UTC, soleJin commented on OpenMarket/OpenMarket/MultipartFormData/MultipartFormData.swift
> +        return "Boundary-\(NSUUID().uuidString)"
Object-C에서 Swift로 넘어가면서 이미 작성된 코드와의 호환을 유지하기 위해 NS접두사가 쓰이고 있습니다 :)

2021-02-04 01:44 UTC, O-O-wl commented on OpenMarket/OpenMarket/MultipartFormData/MultipartFormData.swift
> +        return "Boundary-\(NSUUID().uuidString)"
권장될까요? ㅎ ㅡㅎ 
UUID 라는 타입도 있답니답

2021-02-04 01:49 UTC, merged

2021-02-04 01:53 UTC, O-O-wl commented on OpenMarket/OpenMarket/NetWork/URLManager.swift
> +        }
아하 이건 CustomStringCovertible 이라는 Foundation에서 제공하는 프로토콜이 있어요 
구현 사항에는 description이라는 프로퍼티가 있어요. 이 프로토콜에서는 이 프로퍼티가 이런 역할을 하네요 😯

![스크린샷 2021-02-04 오전 10 52 47](https://user-images.githubusercontent.com/39197978/106833597-20d89a00-66d7-11eb-9582-aa28cbed01aa.png)