[Step1] Bobby
yagom-academy/ios-open-market pull request #42
Opened 2021-06-09 06:26 UTC by Babywalnut

## Step1 - PR
@corykim0829 

**안녕하세요 코리!**
늦었지만 Step1 PR 보냅니다! 깜빡하고 커밋을 한번에 다해서 너무 많은 코드가 한번에 들어왔습니다..😭
이후의 코드에 대해서는 커밋단위를 더 나누도록 하겠습니다!
현재 MockTest와 GET에 대한 코드만 테스트가 이루어졌고 POST는 아직 테스트는 해보지 못했습니다!

### 📘**구현내용**

1. MockObject URLProtocol을 활용한 유닛테스트

   * 실제 앱을 실행할때는 URLSession.shared 를 활용하여 응답이 이루어지면 data, response, error를 받게됩니다.
      테스트 상황시에는 네트워크에 관계없이 이루어져야하므로 URLProtocol의 필수 메서드(canInit(), canonicalRequest(), startloading(), stoploading())들을 상속받아 MockURLProtocol을 구현하여 configuration을 통하여 사용하였습니다.
  
   * 테스트 코드에서 URL을 Setup해주고 URLSession에서 실제 사용하는 URL과 다를시 에러를 반환하게 했습니다.
   * 제대로  response와 data를 받았다면 실제 앱 상에서는 당연히 api를 통해 데이터를 가지고올거라 생각하여 data는 Asset에 저장되어 있는 json데이터를 가지고오도록 하였습니다.
 
2. API의 http통신에 필요한 모델 구현(Models)
(각 파일에 대한 내용은 commit에 남겨뒀습니다!)
 
3. 실제 앱상에서 사용할 http메소드별 통신모델 구현(Network)
(각 파일에 대한 내용은 commit에 남겨뒀습니다!)

### 📕**궁금한점 및 조언을 얻고 싶은점**

* 저는 URLProtocol에 대해서 상속받아 MockURLProtocol이라는 하나의 타입을 새로 작성해주었습니다. Let's TDD영상에서  Alamofire를 적용시킨 방법대로 한다면 
URLProtocol에 정의되어있는 메서드들을 프로토콜에 명시해주고 해당 프로토콜을 새로운 프로토콜 오브젝트가 따르도록 만들어주었습니다. 
그리고 해당 타입을 사용하는곳에 의존성주입을시켜 사용했는데 이렇게 사용할때 이점이 궁금합니다!

### 이외에도 많은 피드백 부탁드립니다!🙏

2021-06-11 11:47 UTC, corykim0829 requested changes

2021-06-11 12:03 UTC, corykim0829 commented
바비! 수고 너무너무 많으셨어요!

전체적으로 많은 시도를 하고 계신 것 같아서 보기 좋습니다! 잘 하고 계세요 ㅎ 👍

> 저는 URLProtocol에 대해서 상속받아 MockURLProtocol이라는 하나의 타입을 새로 작성해주었습니다. Let's TDD영상에서 Alamofire를 적용시킨 방법대로 한다면, URLProtocol에 정의되어있는 메서드들을 프로토콜에 명시해주고 해당 프로토콜을 새로운 프로토콜 오브젝트가 따르도록 만들어주었습니다.
그리고 해당 타입을 사용하는곳에 의존성주입을시켜 사용했는데 이렇게 사용할때 이점이 궁금합니다!

➡️ 말씀하신 부분이 Let's TDD 몇초 부분에 나왔는지 말해주실 수 있나요? 저도 영상을 다 본게 아니라서 정확하게 어디를 말씀하는지 모르겠네요!

2021-06-14 08:50 UTC, Babywalnut commented on OpenMarket/OpenMarket/Errors/Errors.swift
> +enum OpenMarketErrors: LocalizedError {
리뷰 감사드립니다! 
에러타입의 명을 HttpCommunicationError로 변경해주었고 
케이스를 requestError, serverError, unknownError 로 각각 response status code에 따라 반환할 수 있도록 변경해주었습니다

2021-06-14 08:51 UTC, Babywalnut commented on OpenMarket/OpenMarket/NetWork/GETProcess.swift
> +    init(commonURLProcess: URLProcessUsable, urlSession: URLSession = .shared) {
사실 이전에 Calculator 프로젝트에서 decimal calculator와 binary calculator 구조가 거의 일치해서 둘을 프로토콜로 추상화하여서 주입을 했었는데 
생각해보니 이번경우는 CommonURLProcess에 대해서만 주입해주면되는거같아서 굳이 프로토콜을 따르지않고 해당 타입을 주입시켜주어도 괜찮을거같은데 맞을까요??

2021-06-14 08:52 UTC, Babywalnut commented on OpenMarket/OpenMarket/NetWork/GETProcess.swift
> +    func dataParsing<T: Decodable>(index: String?, completionHandler: @escaping (Result<T, Error>) -> Void) {
startLoader로 명칭을 변경해주었습니다!

2021-06-14 08:52 UTC, Babywalnut commented on OpenMarket/OpenMarket/NetWork/GETProcess.swift
> +class GETProcess {
전반적으로 봤을때 데이터를 요청하고 받은 데이터에 대해서 디코딩 후 반환하는 과정에 대한 구체타입인거 같아서 DataLoader로 타입명을 수정하였습니다!

2021-06-14 09:31 UTC, Babywalnut commented
@corykim0829 

제가 말한 부분은 let's tdd 영상의 17분쯤 부터 보시면 확인하실 수 있습니다! 혼자 고민하다가 어느정도 해결된거 같습니다!
섦명을 추가해보자면

저는 Foundation > NSURLProtocl에 존재하는 URLProtocol이라는 클래스를 상속받아서 MockURLProtocol을 다시 정의하였습니다.

```swift
class MockURLProtocol: URLProtocol {
    
    static var requestHandler: ((URLRequest) throws -> (HTTPURLResponse, Data?))?
    
    override class func canInit(with request: URLRequest) -> Bool {
        return true
    }
    
    override class func canonicalRequest(for request: URLRequest) -> URLRequest {
        return request
    }
    
    override func startLoading() {
        guard let handler = MockURLProtocol.requestHandler else {
            fatalError("Handler is unavailable")
        }
        
        do {
            let (response, data) = try handler(request)
            
            client?.urlProtocol(self, didReceive: response, cacheStoragePolicy: .notAllowed)
            
            if let data = data {
                client?.urlProtocol(self, didLoad: data)
            }
            
            client?.urlProtocolDidFinishLoading(self)
        } catch {
            client?.urlProtocol(self,didFailWithError: error)
        }
    }
    
    override func stopLoading() {
    }
}
```

영상에서 설명한 방식을 제 코드에 만약 적용시킨다면 제가 구현한 방법과 다르게

임의로 정의한 protocol을 URLProtocol클래스가 따르게한 후에 해당 protocol을  제가 새로 정의한 클래스인 MockURLProtocol이 따르게하여 테스트시 URLSession의 Configuration.protocolClass 주입시 protocol로써 주입해주려했는데 

protocolClass의 타입이 [AnyClass]로 되어 있어서 protocol로 구현해봤자 클래스로서 주입해주어야할 거 같습니다!

2021-06-14 19:09 UTC, corykim0829 commented on OpenMarket/OpenMarket/NetWork/GETProcess.swift
> +    init(commonURLProcess: URLProcessUsable, urlSession: URLSession = .shared) {
제가 보기에는 굳이 `URLProcessUsable`을 주입시킬 필요없이 `GETProcess`가 `URLProcessUsable` 프로토콜을 준수하면 될 것 같아서 드린 말씀이였습니다!

2021-06-14 19:20 UTC, corykim0829 approved these changes
수고 많으셨습니다!

MockURLProtocol도 잘 구현하셔서 스텝2 하시면서 테스트 부분 더 수정해서 PR 보내주시면 될 것 같아요!

궁금한점은 항상 물어봐주세요 😀

2021-06-15 03:22 UTC, Babywalnut commented on OpenMarket/OpenMarket/NetWork/GETProcess.swift
> +    init(commonURLProcess: URLProcessUsable, urlSession: URLSession = .shared) {
urlProtocolUsable은 CommonURLProcess에 정의되어있는 메서드를 쓰기위해서 준수하던 프로토콜인데

CommonURLProcess에 정의되어 있는 메서드들은 http메서드별로 url형식이 다르기때문에 해당 url을 경우에 따라 만들어서 반환해주는 completedURL()과 http메서드별로 필요한 Request의 헤더부분을 반환해주는 requiredURLRequest()로 이루어져 있습니다

따라서 get, post, patch, delete 각각 데이테 처리를 해주는 타입내에 구현하면 비슷한 메서드가 중복될거 같아서 주입해서 사용하려고 의도한 것인데 구조를 바꿔야할까요??

2021-08-06 09:14 UTC, closed without merging