[Step2]
yagom-academy/ios-open-market pull request #49
Opened 2021-06-19 08:02 UTC by Kioding

@corykim0829

Cory!!! 
중간중간 매번 연락주시고, 도움주셔서 감사해요😆
step2 한곳까지 PR을 보냅니다!
[오픈마켓 README](https://github.com/Kioding/ios-open-market/tree/main)

<br>

# 구현상황
- SegmentedControl을 통한 보기모드 변경
- discountedPrice 취소선 적용
- 상품 정보 표시
- 로드 중임을 표시 ❌
- 상품 등록 버튼 ❌
![화면 기록 2021-06-19 오전 12 29 59](https://user-images.githubusercontent.com/65153742/122584973-ee33aa80-d095-11eb-8eb2-57d08c8fb06b.gif)

<br>

# 조언을 얻고 싶은 부분
- 그림A
    
<img width="872" alt="스크린샷 2021-06-19 오전 12 41 04" src="https://user-images.githubusercontent.com/65153742/122587191-7f0b8580-d098-11eb-94ae-c4465976f759.png">

1.  그림A - 빨간 박스 
   `strikeThrough`을 통해 취소선을 적용하였는데 초기화면은 잘 적용되지만, 
뷰를 위아래로 넘긴 후 다시 돌아오면 `원가`에도 취소선이 적용되어 있습니다. 
그래서 제 생각으로는 `discountedPrice(할인가격)`이 nil일 경우, 
취소선 제거코드도 추가했는데 여전히 그대로네요😭😭😭. Cell이 재사용되어서 그렇지 않나라고 생각이 드는데 이 부분은 해결하지 못하여 조언을 얻고 싶습니다.
2. 그림A - 파란 박스
   `TableViewCell`에서 잔여수량에 따라 상품명, 상품가격의 크기가 달라집니다. 사용자 입장에서 보기 좋게 하려면 잔여수량 4자리수부터는 `여유` or `1000개 이상`으로 표시하고, 그 아래는 실제 재고로 표기하면 좋지 않나 라고 생각해보았습니다. 아! 이제 질문인데 잔여수량의 사이즈를 고정하고 싶다면, 직접 사이즈 지정 or cell 넓이의 퍼센트 지정 그 외의 방법이 있을지 궁금합니다!
3. 그림A - 분홍 박스
   `CollectionViewCell`에서 상품명이 긴 경우, 좌우로 짤린 상태로 나오게 되는데 글자크기를 줄이는 것 말고, 사이즈 그대로 아래칸으로 넘길 수 있는 방법이 있을까요? 한 label의 line을 2줄로 해도 적용이 되지 않더라구요.
4. 현재는 1페이지에 해당하는 20개의 상품만 가져오고 있는데 전체를 가져오려면 어떤 방식으로 해야할지 아직도 감이 부족한 것 같아요. 시뮬레이터를 위아래로 움직이는 이벤트를 줄 때마다 어떻게 구동되는지, 실제로 아이템 변동이 있게 하려면, 제가 어떤 쪽으로 더 찾아봐야할지 알고 싶습니다.
5. cell을 구성하는 방법에 `스토리보드`, `xib`, `코드`로 짜는 방법이 있는데 아직은 코드로 UI를 작성하는 게 익숙치 않아, 저는 이번에는 xib 형태로 구성하였습니다. `스토리보드` or `xib`로 UI를 짜게 되면, 실행과는 상관없지만 스토리보드 상에서 오류가 많이 발생하여 그 부분을 해결하고자 시간을 많이 쓰게 되는 것 같더라구요. 기본적으로 먼저 알아가야할 단계가 있을까요? 가령 스토리보드를 먼저 할줄 알고 코드로 넘어가야 한다랄지, cory는 어떤 쪽을 선호하는지도 궁금합니다!

2021-06-19 10:30 UTC, corykim0829 requested changes
키오 정말 수고 많으셨어요 👏👏👏👏

> 1.  그림A - 빨간 박스 
   `strikeThrough`을 통해 취소선을 적용하였는데 초기화면은 잘 적용되지만, 
뷰를 위아래로 넘긴 후 다시 돌아오면 `원가`에도 취소선이 적용되어 있습니다. 
그래서 제 생각으로는 `discountedPrice(할인가격)`이 nil일 경우, 
취소선 제거코드도 추가했는데 여전히 그대로네요😭😭😭. Cell이 재사용되어서 그렇지 않나라고 생각이 드는데 이 부분은 해결하지 못하여 조언을 얻고 싶습니다.

➡️ 제가 생각했을 때에는 재사용 문제가 맞는 것 같고, remove가 잘 처리가 안되는 것 같아요!

> 2. 그림A - 파란 박스
   `TableViewCell`에서 잔여수량에 따라 상품명, 상품가격의 크기가 달라집니다. 사용자 입장에서 보기 좋게 하려면 잔여수량 4자리수부터는 `여유` or `1000개 이상`으로 표시하고, 그 아래는 실제 재고로 표기하면 좋지 않나 라고 생각해보았습니다. 아! 이제 질문인데 잔여수량의 사이즈를 고정하고 싶다면, 직접 사이즈 지정 or cell 넓이의 퍼센트 지정 그 외의 방법이 있을지 궁금합니다!

➡️ TableViewCell은 xib로 구현했으니 xib 내부에서 constraint를 잘 설정해주면 충분히 원하시는대로 처리할 수 있습니다. 제 생각에는 고정된 폰트 크기를 준다면, 고정된 사이즈로 제한하는게 좋을 것 같아요. 

> 3. 그림A - 분홍 박스
   `CollectionViewCell`에서 상품명이 긴 경우, 좌우로 짤린 상태로 나오게 되는데 글자크기를 줄이는 것 말고, 사이즈 그대로 아래칸으로 넘길 수 있는 방법이 있을까요? 한 label의 line을 2줄로 해도 적용이 되지 않더라구요.

➡️ 이 부분은 현재 collectionViewCell의 사이즈가 고정되어있고, 해당 UILabel의 높이가 고정되어있다면 적용이 되지 않을거에요. 동적으로 collectionViewCell 크기를 조절할 수 있는데, 구현 난이도가 조금 있습니다. 좌우 constraint 잘 정해주면 ...으로 잘 처리될 것 같기는 해요!

> 4. 현재는 1페이지에 해당하는 20개의 상품만 가져오고 있는데 전체를 가져오려면 어떤 방식으로 해야할지 아직도 감이 부족한 것 같아요. 시뮬레이터를 위아래로 움직이는 이벤트를 줄 때마다 어떻게 구동되는지, 실제로 아이템 변동이 있게 하려면, 제가 어떤 쪽으로 더 찾아봐야할지 알고 싶습니다.

➡️ 전체를 한번에 가져온다는 말인가요? 이 부분은 네트워크 처리 작업 처리 방식을 고민해보면 해답을 얻을 수 있을 것 같아요. 그런데 제 생각에는 서버에서 페이지 단위로 줬다면, 스크롤 하면 추가로 요청하는 방식이거나 정말 다음 페이지 버튼 같은게 있어서 다음 페이지 버튼을 누르면 다음 페이지의 네트워크 요청해서 값을 받아오는 방식일 것 같아요. 

pagination, paging과 같은 키워드로 검색해보면 될 것 같아요 ㅎ

> 5. cell을 구성하는 방법에 `스토리보드`, `xib`, `코드`로 짜는 방법이 있는데 아직은 코드로 UI를 작성하는 게 익숙치 않아, 저는 이번에는 xib 형태로 구성하였습니다. `스토리보드` or `xib`로 UI를 짜게 되면, 실행과는 상관없지만 스토리보드 상에서 오류가 많이 발생하여 그 부분을 해결하고자 시간을 많이 쓰게 되는 것 같더라구요. 기본적으로 먼저 알아가야할 단계가 있을까요? 가령 스토리보드를 먼저 할줄 알고 코드로 넘어가야 한다랄지, cory는 어떤 쪽을 선호하는지도 궁금합니다! 

➡️ 저도 이 부분을 공부할 때 많이 고민했던 것 같아요. 회사 입장에서 본다면, 이건 팀바팀이라서 팀에서 어떤 방식을 사용하냐에 따라 다른 것 같아요.
코드와 XIB를 섞어서 사용하는 곳도 있고, 스토리보드 사용하는 곳도 있고, 코드로만 UI를 작성하는 곳도 있죠. 결론은 다 해보는게 좋습니다!!!
XIB 사용은 스토리보드나 코드로만 하는 것보다 까다로운 부분이 있어서 꼭 해보는걸 추천합니다! 스토리보드 상의 오류도 잡을 수 있으니 잡는게 좋습니다. 특수한 경우는 제외하구요!
저는 개인적으로 코드와 XIB를 섞는게 좋아하는데, 또 상황에 맞게 유동적으로 사용하는것도 좋더라구요 ㅎ

2021-06-20 14:53 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +    @IBOutlet weak var SegmentedControl: UISegmentedControl!
앗, 수정하였습니다!

2021-06-20 15:38 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +}
이 부분은 삭제하고 다른 부분에 `UITableViewDelegate`를 채택하였습니다!

2021-06-20 15:38 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +}
이 부분은 삭제하고 다른 부분에 `UICollectionViewDelegate`를 채택하였습니다!

2021-06-20 16:12 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +    @IBAction func ChangeViewBySegmentedControl(_ sender: UISegmentedControl) {
함수명의 대소문자 주의하겠습니다!

2021-06-20 16:14 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +    @IBAction func ChangeViewBySegmentedControl(_ sender: UISegmentedControl) {
@IBAction, @IBOutlet 2개 다 있어야한다고 생각했는데, 굳이 모두 사용할 필요가 없군요! 조언 감사합니다. @IBOutlet을 삭제하였습니다😆

2021-06-20 16:49 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +    private func tableViewRegisterXib(fileName: String, cellIdentifier: String) {
파라미터를 제거하고 `registerTableViewCellXib()` 로 변경하였습니다!

2021-06-20 16:51 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +        if SegmentedControl.selectedSegmentIndex == 0 {
```swift 
enum ViewType: Int {
    case List = 0
    case Grid = 1
}
```
```swift
    @IBAction func changeViewBySegmentedControl(_ sender: UISegmentedControl) {

        switch sender.selectedSegmentIndex {
        case ViewType.List.rawValue:
            collectionView.isHidden = true
            tableView.isHidden = false
        case ViewType.Grid.rawValue:
            collectionView.isHidden = false
            tableView.isHidden = true
        default:
            break
        }
    }
```

2021-06-21 06:44 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +class ViewController: UIViewController {
현재 ViewController이 하나인 상태여서 현재 네이밍은 MainViewController라고 변경했는데, 적절할지 궁금합니다. 

그리고 제가 `extension MainViewController`를 통해 tableView, CollectionView의 dataSource, Delegate를 채택하고 있는데 보기 편하게 하기 위해 tableView를 나누는 부분과 CollectionView를 다루고 있는 extension 부분을 각각 파일분리로 하려고 했는데, 파일 분리를 하면 MainViewController파일에서 아래의 부분, 즉 extension하여 채택한 부분을 인식하지 못해 작동하지 않더라구요. 
```swift
        tableView.delegate = self
        tableView.dataSource = self
        collectionView.delegate = self
        collectionView.dataSource = self
```
제가 접근이 잘못되었을지 궁금합니다!

2021-06-21 06:45 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +        mainView.addSubview(collectionView)
이 부분은 간과했던 부분인 것 같아요. 스토리보드상에서는 큰 의미를 두지 않아, 코드가 기반이라고 생각했는데 굳이 있을 필요가 없을 것 같아요!

2021-06-21 06:46 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +    private func tableViewRegisterXib(fileName: String, cellIdentifier: String) {
사실, 처음시작은 테이블뷰셀, 컬렉션뷰셀을 resiterXib를 하나로 퉁치고 싶어서 만든건데, 각기 다른 뷰의 셀로 파라미터가 들어가지 않는 것 같더라구요

2021-06-21 06:48 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +}
Delegate 프로토콜을 채택한 코드가 쓰이지 않았지만, 앱구현에 있어 필수적이라고 생각이 드는데, 굳이 내부코드가 없으니 따로 분류할 필요가 없다는 말이었을까요?!

2021-06-21 06:50 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +            cell.priceLabel.attributedText = cell.priceLabel.text?.removeStrikeThrough()
removeStrikeThrough()는 지우고, prepareforreuse에서 취소선에 nil값을 주는 형태로 바꾸었습니다!

2021-06-21 06:58 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +extension String {
ExtensionString이라는 파일로 따로 분리했습니다ㅎㅎㅎ

2021-06-21 13:06 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +        return CGSize(width: collectionView.frame.width/2-5, height: collectionView.frame.height/3)
```swift
 let twoItem = 2
 let threeItem = 3
 let spacingBetweenItems = 5
        
 return CGSize(width: Int(collectionView.frame.width)/twoItem-spacingBetweenItems, height: Int(collectionView.frame.height)/threeItem)
```
이런식으로 바꾸어보았는데 어떨까요? 누가 보았을 때 모르는 숫자일 수 있다는 생각을 못해봤네요! 그냥 숫자만 집어넣으면 되는게 아니네요!

2021-06-21 13:07 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +        return 70
```swift
let cellHeight = 70
        
return CGFloat(cellHeight)
```
상수를 선언하고 cellHeight가 return됨을 알리고자 했습니다!

2021-06-21 13:59 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +    override func viewDidLoad() {
viewDidLoad() 안에 있던 `getItemPageInfo()` 함수로 분리하였습니다.

저는 NetworkManager 아래의 메서드로 넣고 싶었는데 아래 mainView, tableView, collectionView를 static으로 선언이 안되더라구요. @IBOutlet을 static으로 사용할 수 있는 방법이 있을까요? 아니면 데이터 받았다는 걸 Bool타입으로 받고 디스패치만 MainViewController에서 해줘야할지 궁금합니다!
```swift
    @IBOutlet var mainView: UIView!
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var collectionView: UICollectionView!
    
    var items: [ItemShortInformaion] = []
    let activityIndicator = UIActivityIndicatorView()

              DispatchQueue.main.async {
                    self.tableView.reloadData()
                    self.collectionView.reloadData()
                    self.navigationController?.isNavigationBarHidden = false
                    self.tableView.isHidden = false
                    self.activityIndicator.stopAnimating()
                }
```

2021-06-21 14:58 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +        cell.ImageView.image = UIImage(data: imageData)
- 커밋메시지 :: `Chore: cell 모델에 넘겨주기 실패`
- 제가 Cell 파일에서 `configure()` 메서드를 통해 cell을 업데이트하려고 시도 했는데 항상 nil이 발견된다는 오류가 뜨더라구요. 메서드 시작전 print문을 통해 item을 보았을 때도 discountPrice외에는 알맞게 들어온 것으로 확인되는데 왜 그런지 이부분은 모르겠어서 주석처리로 남겨놓았습니다😭

2021-06-21 15:56 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +        guard let imageData = try? Data(contentsOf: imageURL) else { return cell }
```swift
        DispatchQueue.main.async {
            guard let imageURL = URL(string: item.thumbnailURLs[0]) else { return }
            guard let imageData = try? Data(contentsOf: imageURL) else { return }
            cell.itemImage.image = UIImage(data: imageData)
        }
```
error를 만들까 하다가 디스패치큐를 사용하여 바로 return 하는 방식으로 하였습니다. 이미지 데이터 가져오는 게 실패하면 placeholder인 상태로 머물게 하였습니다!

디스패치큐를 사용하여 비동기를 사용하니, UIActivityIndicator가 먼저 끊기고 그 이후에 이미지가 조금 늦게 로딩이 됩니다. `UIActivityIndicator.stopAnimating()`를 이미지까지 받은 후에 호출하고 싶은데 디스패치큐 비동기를 사용하는 것이 서로 상극(?)일까요. 아니면 제가 `UIActivityIndicator.stopAnimating()`메서드 호출 위치가 적절한지 잘 모르겠어서 질문 드리고 싶습니다😅

2021-06-21 16:03 UTC, Kioding commented
@corykim0829 

`pagination, paging`에 대해서는 아직 공부를 못하였고
그외 코리가 준 코멘트를 바탕으로 수정해보았습니다!

먼저 매직넘버라는 용어 자체도 모르고 있었는데 알게 되었고, 
UIActivityIndicator 기능도 알게 되었네요!
덕분에 이것저것 더 해볼 수 있었습니다. 감사합니다☺️

질문은 댓글로 남겨놓았습니다!
 질문댓글에는 이 이모티콘을 남겨두었습니다 `🙋🏻‍♂️🙋🏻‍♂️🙋🏻‍♂️`

[오픈마켓 README](https://github.com/Kioding/ios-open-market/tree/main)

## UIActivityIndicator 적용
1차 ('21.06.19)

![화면 기록 2021-06-19 오전 12 29 59](https://user-images.githubusercontent.com/65153742/122584973-ee33aa80-d095-11eb-8eb2-57d08c8fb06b.gif)

2차 ('21.06.22)

![화면 기록 2021-06-22 오전 12 40 07](https://user-images.githubusercontent.com/65153742/122790195-0a805300-d2f3-11eb-8edb-d9a5db47fa75.gif)

2021-06-21 16:28 UTC, Kioding commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +            fatalError("cell 생성 실패")
🙋🏻‍♂️🙋🏻‍♂️🙋🏻‍♂️
```swift
    static let identifier = "CustomTableViewCell"
    static let identifier = "CustomCollectionViewCell"
```
각 cell 파일에 static 상수를 선언하여 사용할 수 있도록 하였습니다. 
cell 파일명도 같아 이 상수로 사용하였는데, 이러면 알아보기가 어려울까요? 파일명의 상수도 하나 더 만드는게 나을지 궁금합니다!

2021-06-26 14:17 UTC, corykim0829 commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +class ViewController: UIViewController {
delegate, dataSource 대상만 잘 설정하면 extension, 파일로 분리해도 잘 작동할거에요! private이면 접근이 안될 수도 있어요! 다시 한번 확인해보면 좋을 것 같아요!

2021-06-26 14:20 UTC, corykim0829 commented on OpenMarket/OpenMarket/ViewController/ViewController.swift
> +        return CGSize(width: collectionView.frame.width/2-5, height: collectionView.frame.height/3)
twoItem 보다는 두개의 열을 가진 collectionView의 레이아웃을 설정해주기 때문에 numberOfColumns 같은 변수명이 적절해보여요. 그리고 height는 왜 3으로 나누는건가요? 3개의 행이여서 그런건가요? 3행보다 더 적게 또는 더 많이 데이터가 들어오면 그 때는 어떻게 되나요? 많은 경우의 수를 생각해 보면서 코드를 작성해야합니다!

2021-06-26 14:51 UTC, corykim0829 approved these changes
이번 프로젝트 수고 많았어요 Kio! 😀

열심히 자기 것으로 만들어가는 모습 보기 좋았습니다. 앞으로도 화이팅!

2021-06-26 14:51 UTC, corykim0829 commented on OpenMarket/OpenMarket/Model/Request/ItemRegistration.swift
> +        case discountedPrice = "discounted_price"
이렇게 camelCase로만 바꾸는 거라면, Key decoding strategy도 참고하면 좋아요!

2021-06-26 14:51 UTC, corykim0829 commented on OpenMarket/OpenMarket/View/Cell/CustomTableViewCell.swift
> +    }
사용하지 않는 코드는 정리해주세요~

2021-06-26 14:51 UTC, corykim0829 commented on OpenMarket/OpenMarket/View/Cell/CustomTableViewCell.swift
> +    let mainVC = MainViewController()
View가 Controller를 하위 객체로 두는건 구조상 매끄럽지 못한 부분인 것 같아요!
여기에 MainVC 인스턴스를 선언한 이유가 있나요?

2021-06-26 14:51 UTC, corykim0829 commented on OpenMarket/OpenMarket/View/ViewController/MainViewController.swift
> +        let item: ItemShortInformaion = self.items[indexPath.row]
이곳에서 타입을 명시하지 않아도 충분히 어떤 타입인지 확인할 수 있을 것 같아요! 참고하세요

2021-06-26 14:51 UTC, corykim0829 commented on OpenMarket/OpenMarket/View/ViewController/MainViewController.swift
> +        }
cell에 데이터를 넘기면 뷰단인 셀이 업데이트하는 로직으로 가면 좋을 것 같아요. 그러면 Controller가 비대해지는 것도 막을 수 있어요.

2021-08-06 09:14 UTC, closed without merging