OpenMarket [STEP1] 타코캣,지스
yagom-academy/ios-open-market pull request #56
Opened 2021-08-17 06:51 UTC by hrjy6278

안녕하세요 라자냐! PR이 좀 늦었습니다 하하..
잘부탁드립니다!!😁 @wonhee009 

# step1-1, 1-2 요구조건에 관하여 
- step 1-1
    - 실제통신을 했다고 가정하고 가져온 Mock 데이터인 Items, Item JSON파일을 Assect에 추가한 후 OpenMarketItemTests 파일에서 디코딩을 정상적으로 하고 있는지를 확인하였습니다. 
    
- stpe 1-2
    - 서버와 데이터 통신을 주고 받도록 NetworkManager라는 타입을 구현하였습니다. 
    - 1-2의 요구사항을 어떻게 테스트할 수 있는지를 고민했습니다. 저희는 이를 위해선 Server Mock 객체를 만들어야 한다고 판단했습니다. 하지만 Mock객체를 만드는 것 보단 타입이 잘 구현되었는지 확인하는것이 우선이라고 생각했습니다. 그래서 우선 테스트 브랜치에서 해당 타입이 잘 동작하는지 확인하는 쪽으로 진행습니다.

# 질문 
1. URLSession을 통해 서버로부터 받아온 데이터를 디코딩 할 때 쓰는 타입 OpenMarketItems을 구현 할 때 HTTP Method마다 Response Key의 종류가 조금씩 달랐고 저희는 이에 해당하는 모든 Key들을 OpenMarketItems을 내부에서 옵셔널로 처리했습니다. 이에 대해 어떻게 생각하시는지 궁금합니다. ![](https://i.imgur.com/WHfdlXt.png)
    - ex) images, descriptions key는 POST메소드의 response Body에는 있지만 GET에는 없는 상황

2. NetworkManager의 타입에 관하여
- NetworkManager타입을 구현할 때 Class로 해야하는 이유가 없는 것 같아서 Struct로 하였습니다. 혹시 저희 놓친 것이 있다면 무엇인지 궁금합니다. 

5. NetworkManager  -  session가져야하는지?
 - 이 부분이 의견이 좀 나뉘었는데요.. 해당 매니저가 URLSession 타입인 프로퍼티를 
  가지고 있는게 나을지, request 메소드 사용시 파라미터로 session을 받을지 판단이 잘 서지 않습니다...
    ```swift=
    struct NetworkManager {
        let session: URLSession
    ```

5. private createRequest 메서드에 대해.
- 현재 NetworkManager 타입에 있는 request 메소드는 URLRequest를 만들기 위한, 파라미터를 받고 있습니다. 왜냐면 URLRequest를 만들어주는 createRequest 메서드가 private 상태이기 때문입니다. 이에따라 request를 사용시 파라미터가 많아져, 기능이 복잡해지는 느낌입니다.
(네트워크 통신을 하는 기능과, URLRequest를 만드는 기능까지 합쳐진 느낌입니다)
private을 풀고 createRequest 메서드를 사용할지? 아니면 지금 처럼 private을 사용할지
판단이 잘 서지 않습니다.

    ```swift=
    private func createRequest(httpMethod: HTTPMethod, url: URL, body: Data?) -> URLRequest {
            var request = URLRequest(url: url)
            request.httpMethod = String(describing: httpMethod)
            request.httpBody = body
            
            return request
        }
    ```

6. NetworkManager 내부에서 httpBody를 속성으로 가질 것인지에 대한 질문
  - NetworkManager 인스턴스를 만들때 httpBody를 속성으로 가지게 한다면 어떨지 라자냐의 의견이 궁금합니다!!!

2021-08-17 13:43 UTC, wonhee009 requested changes
@hrjy6278 @Ldoy 스텝1 수고하셨습니다!😀
리뷰 남겨놨으니 확인 부탁드립니다!🙏

1. OpenMarketItems을 내부에서 옵셔널로 처리 <- 이 부분은 `let discountedPrice: Int?`처럼 OpenMarketItems의 프로퍼티 타입을 옵셔널로 지정했다는 말씀이실까요?
그 외에 옵셔널로 처리한 부분이 없는거 같아서 질문드립니다.

2. NetworkManager를 Class가 아닌 struct로 구현하신 자세한 이유가 궁금합니다. 예를 들어 상속의 불필요 등등..

3. NetworkManager가 session을 갖고 있으면 어떤 장단점이 있을까요? 또 session을 따로 받으면 어떤 장단점이 있을까요?

4. 현재 `request()`에서 받고 있는 파라미터는 completionHandler를 제외하고 3개로 보이는데요.
이 부분이 많다고 느껴진다면 `struct RequestBody`와 같이 구조체를 정의하고 활용하는 것도 하나의 방법이 될 수 있을거 같습니다. (네이밍은 신경쓰지 말아주세여..ㅋ.ㅋ)

5. httpBody는 API 요청을 할때마다 달라질텐데요.
현재 NetworkManager가 struct로 정의되어 있는데 계속 수정되야 하는 프로퍼티는 한 번 생각해봐야할 문제일거 같아요.
그리고 그 전에 NetworkManager가 httpBody를 가지고 있어야할 이유가 무엇인지 궁금합니다.

2021-08-17 13:43 UTC, wonhee009 commented on OpenMarket/OpenMarket/Model/ItemDeleteEncodeType.swift
> +}
struct의 이름도 ItemDelete'Encode'Type인데 `Codable`을 채택하고 있네요?🤔
[Codable](https://developer.apple.com/documentation/swift/codable)을 확인해 보면 Decodable과 Encodable로 이뤄져 있는걸 확인할 수 있어요.
`Decodable`과 `Encodable`은 각각 어떤 기능을 가지고 있을까요?

2021-08-17 13:43 UTC, wonhee009 commented on OpenMarket/OpenMarket/Model/ParsingManager.swift
> +enum ParsingManager {
struct가 아닌 enum으로 정의하신 이유가 있을까요?

2021-08-17 13:43 UTC, wonhee009 commented on OpenMarket/OpenMarket/PlaceHolder/NameSpace.swift
> +enum OpenMarketUrl: CustomStringConvertible {
`CustomStringConvertible`을 채택하신 이유가 있나요?

2021-08-17 13:43 UTC, wonhee009 commented on OpenMarket/OpenMarket/Model/NetworkManager.swift
> +    typealias userInput = [String: Any]
`userInput`이라고 네이밍한 이유가 있나요?
HTTPBody에 들어가는 parameter 타입인데 userInput과는 거리가 있는거 같아서요!

2021-08-17 13:43 UTC, wonhee009 commented on OpenMarket/OpenMarket/Model/NetworkManager.swift
> +        }
코드가 복잡하다고 느껴지는데요.
`if let parameters = parameters ...`같은 코드는 반복해서 사용하고 있으니 개선가능할거 같습니다.

2021-08-17 13:43 UTC, wonhee009 commented on OpenMarket/OpenMarket/PlaceHolder/NameSpace.swift
> +    case title, descriptions, price, currency, stock, discountedPrice, images, password
`APIKey`라는 네이밍이 직관적으로 어떤 enum인지 나타내기 힘든거 같아요. 좀 더 직관적인 네이밍으로 바꿔볼 수 있을까요?:)

2021-08-17 13:43 UTC, wonhee009 commented on OpenMarket/OpenMarket/Model/ParsingManager.swift
> +enum ParsingManager {
ParsingManager가 현재 Model 폴더에 있는데 좀 더 적절한 자리가 없을까요?

2021-08-19 11:34 UTC, Ldoy commented on OpenMarket/OpenMarket/Model/ItemDeleteEncodeType.swift
> +}
Encodable은 인코딩 할 때 사용하는 타입, Decodable은 디코딩 하는 타입에 채택하는 프로토콜이라고 알고 있습니다. 위에 언급 해 주신 것처럼 현재 ItemDeleteEncodeType 은 인코딩할 때 사용하는 타입이므로 Encodable을 채택하는 것이 맞는 것 같습니다.

2021-08-19 11:41 UTC, Ldoy commented on OpenMarket/OpenMarket/Model/ParsingManager.swift
> +enum ParsingManager {
> 1. struct 이 아닌 enum으로 정의한 이유 
enum 인스턴스가 생성되지 않기 때문에 동일한 기능을 수행한다면 enum이 실수방지 측면에서 더 좋을 것이라 생각했습니다. 

>2. ParsingManager가 현재 Model 폴더에 있는데 좀 더 적절한 자리가 없을까요?
현재 Model폴더에 존재하기에 어색한 이유가 있을까요..?🥲 이번 프로젝트에 MVC패턴을 사용하였는데 그 중 Model에 가깝다고 생각해여 해당 폴더에 위치시켰습니다. 혹시 저희가 잘 모르고 있는 개념이 있다면 알려주세요~😄

2021-08-19 11:44 UTC, Ldoy commented on OpenMarket/OpenMarket/PlaceHolder/NameSpace.swift
> +enum OpenMarketUrl: CustomStringConvertible {
`CustomStringConvertible` 를 채택한 이유는 하드코딩을 피하기 위해서입니다! 사실 이 방법을 사용하기 전에 static let 을 사용할지 해당 방법을 사용할지 고민했었는데 static은 앱이 종료 될 때 까지 메모리에 위치하기 때문에 해당 방법을 사용하였습니다. 😄

2021-08-19 11:47 UTC, Ldoy commented on OpenMarket/OpenMarket/Model/NetworkManager.swift
> +    typealias userInput = [String: Any]
HTTPBody에 들어가는 parameter는 사용자가 입력한 값이 담길공간이기 때문에 해당 이름을 사용하였습니다😄😄😄

2021-08-19 11:48 UTC, Ldoy commented on OpenMarket/OpenMarket/Model/NetworkManager.swift
> +        }
아하 그렇네요!!! 수정하겠습니다~~

2021-08-19 11:51 UTC, Ldoy commented on OpenMarket/OpenMarket/PlaceHolder/NameSpace.swift
> +    case title, descriptions, price, currency, stock, discountedPrice, images, password
아하!! 고민해서 수정 해 보겠습니다🌟

2021-08-19 12:26 UTC, Ldoy commented
> 1. OpenMarketItems을 내부에서 옵셔널로 처리 <- 이 부분은 let discountedPrice: Int?처럼 OpenMarketItems의 프로퍼티 타입을 옵셔널로 지정했다는 말씀이실까요?
그 외에 옵셔널로 처리한 부분이 없는거 같아서 질문드립니다.

네 맞습니다! 만약 이런 경우에 해당하는 APIKey들이 많다면 보통 어떤식으로 처리하는지 궁금합니다~~!🤩

> NetworkManager를 Class가 아닌 struct로 구현하신 자세한 이유가 궁금합니다. 예를 들어 상속의 불필요 등등..

네! 말씀하신 것처럼 상속이 필요하지 않다고 판단했습니다. 그리고 참조타입의 값을 가져야 하는 경우도 없다고 생각했습니다.
 
> NetworkManager가 session을 갖고 있으면 어떤 장단점이 있을까요? 또 session을 따로 받으면 어떤 장단점이 있을까요?

저희가 생각한 장점으로는 NetworkManager의 초기화 단계에서 session을 정해주면 `request` 메소드에서 파라미터로 session을 넣지 않아도 된다는 것이었습니다. 단점은... 저희의 생각으로는 없는 것 같습니다..!! 라자냐의 생각은 어떠신가요??🤓

> 현재 request()에서 받고 있는 파라미터는 completionHandler를 제외하고 3개로 보이는데요.
이 부분이 많다고 느껴진다면 struct RequestBody와 같이 구조체를 정의하고 활용하는 것도 하나의 방법이 될 수 있을거 같습니다. (네이밍은 신경쓰지 말아주세여..ㅋ.ㅋ)

아하 그런 방법이 있군요!!! 말씀하신 방법을 어떻게 적용할 수 있을지 고민해보겠습니다~~!

> httpBody는 API 요청을 할때마다 달라질텐데요.
현재 NetworkManager가 struct로 정의되어 있는데 계속 수정되야 하는 프로퍼티는 한 번 생각해봐야할 문제일거 같아요.

라자냐가 말씀해 주신 이 부분이 잘 이해가 되지 않습니다..🥲🥲🥲(혹시 createHTTPBody 메서드를 계속 호출해서 httpBody를 만들어주어야 한다는 의미이실까요??)

> 그리고 그 전에 NetworkManager가 httpBody를 가지고 있어야할 이유가 무엇인지 궁금합니다.

그 부분에 대해서 저희가 확신 할 수가 없어서 라자냐의 의견이 궁금했습니다.😄

2021-08-21 07:50 UTC, wonhee009 commented on OpenMarket/OpenMarket/Model/ParsingManager.swift
> +enum ParsingManager {
1. 인스턴스가 생성되지 않기 때문에 실수방지 측면에서 더 좋다라는 말이 잘 이해가 가지 않는데요. 어떤 실수 방지에서 좋은건가요??

2. Model은 어떤 역할을 가지고 있을까요? ParsingManager를 어떤 역할로 사용하고 있나요?

2021-08-22 12:23 UTC, wonhee009 commented on OpenMarket/OpenMarket/Model/NetworkManager.swift
> +    typealias userInput = [String: Any]
타코캣과 지스 이외에 사람이 해당 코드를 보고 `userInput`이 HTTPBody에 들어가는 parameter임을 알 수 있을까요?🤔

2021-08-22 13:17 UTC, wonhee009 commented
1. 타코캣과 지스가 정의한 OpenMarketItems.Item에서는 `discountedPrice`만 Optional로 정의되어 있네요? <- 이 부분은 API 명세에서도 Optional로 정의되어 있듯이 **OpenMarketItems을 내부에서 옵셔널로 처리**했다는 타코캣과 지스의 말에는 아무런 문제가 없어보입니다.

다만, 타코캣과 지스가 궁금했던 부분은 **images, descriptions key는 POST메소드의 response Body에는 있지만 GET에는 없는 상황** <- 이 부분일거 같아요.
타코캣과 지스는 OpenMarketItems.Item을 GET과 POST에서 사용하고 싶은건가요?

2. struct를 사용하신 부분에 대해서는 따로 의견은 없습니다. NetworkManager에서 사용하고 있는 메서드들을 `static` 메서드로 사용하는 방향은 어떠신가요?
현재 구조에서는 네트워크가 필요한 VC에서 NetworkManager의 인스턴스를 가지고 있어야하는데 그럴 이유가 있을까 해서요.

3. [URLSession 공식문서](https://developer.apple.com/documentation/foundation/urlsession)를 확인해보면 URLSession을 싱글톤으로써 사용할 수 있는데요. custom하게 session을 사용하고 싶으신건가요?

5. **그리고 그 전에 NetworkManager가 httpBody를 가지고 있어야할 이유가 무엇인지 궁금합니다.** <- 이 부분은 타코캣과 지스가 어떤 이유 때문에 **NetworkManager 내부에서 httpBody를 속성으로 가져야 하나?**라고 생각했는지 궁금해서 질문했습니다😀
현재 NetworkManager가 struct로 정의되어 있는데 계속 수정되야 하는 프로퍼티는 한 번 생각해봐야할 문제일거 같아요.

2021-08-23 02:04 UTC, Ldoy commented on OpenMarket/OpenMarket/Model/ParsingManager.swift
> +enum ParsingManager {
제 생각에 Model은 앱을 작동하기 위해 쓰이는 객체들의 설계도가 있는 곳이라고 생각했습니다! ParsingManager는 네트워크 통신을 요청 한 후 받아온 JSON 데이터를 decode 해주거나 우리가 보낼 데이터를 encode 해 주는 객체라고 생각했고 그래서 Model에 조금 더 가깝다고 생각했습니다~!

2021-08-23 02:04 UTC, Ldoy commented on OpenMarket/OpenMarket/Model/NetworkManager.swift
> +    typealias userInput = [String: Any]
아하!! 그렇네요!!! 수정하겠습니다~~~!!!!

2021-08-24 04:43 UTC, Ldoy commented
> 타코캣과 지스가 정의한 OpenMarketItems.Item에서는 discountedPrice만 Optional로 정의되어 있네요? <- 이 부분은 API 명세에서도 Optional로 정의되어 있듯이 OpenMarketItems을 내부에서 옵셔널로 처리했다는 타코캣과 지스의 말에는 아무런 문제가 없어보입니다.
다만, 타코캣과 지스가 궁금했던 부분은 images, descriptions key는 POST메소드의 response Body에는 있지만 GET에는 없는 상황 <- 이 부분일거 같아요.
타코캣과 지스는 OpenMarketItems.Item을 GET과 POST에서 사용하고 싶은건가요?

네! 맞습니다~!

> struct를 사용하신 부분에 대해서는 따로 의견은 없습니다. NetworkManager에서 사용하고 있는 메서드들을 static 메서드로 사용하는 방향은 어떠신가요?
현재 구조에서는 네트워크가 필요한 VC에서 NetworkManager의 인스턴스를 가지고 있어야하는데 그럴 이유가 있을까 해서요.

아하! 그러네요!! static 메소드로 수정하였습니다~

>  URLSession 공식문서를 확인해보면 URLSession을 싱글톤으로써 사용할 수 있는데요. custom하게 session을 사용하고 싶으신건가요?

네! 추후 URLSession.shared가 아닌 다른 session을 사용할 수도 있다고 생각했습니다. 

> 그리고 그 전에 NetworkManager가 httpBody를 가지고 있어야할 이유가 무엇인지 궁금합니다. <- 이 부분은 타코캣과 지스가 어떤 이유 때문에 **NetworkManager 내부에서 httpBody를 속성으로 가져야 하나?**라고 생각했는지 궁금해서 질문했습니다😀
> 현재 NetworkManager가 struct로 정의되어 있는데 계속 수정되야 하는 프로퍼티는 한 번 생각해봐야할 문제일거 같아요. <- 이 부분은 상품을 등록하는 페이지를 만든다고 생각해보면 될 것 같습니다.
상품 등록 페이지에서 A라는 상품을 POST하고 B라는 상품을 POST하게 된다면 현재 구조에서는 상품 등록 페이지에 NetworkManager 인스턴스 N 생성 -> N을 생성할 때 상품 A라는 HTTPBody를 지정 후 POST -> 상품 B를 등록하기 위해 N에 B HTTPBody를 지정 이런 플로우로 될 것 같습니다. (이 부분은 제가 잘못 이해하고 있다면 말씀해 주세요🙏)
HTTPBody를 NetworkManager가 들고있기보다는 사용할때 주입하는 편이 좀 더 낫지 않나라고 의견 드려봅니다.

라자냐의 질문처럼 생각해보니 httpBody를 받는 쪽이 역할 분리가 더 잘 된 설계같습니다! HTTPBodyMaker타입을 만들어 httpBody를 주입받는쪽으로 진행하였습니다.

2021-08-24 07:32 UTC, wonhee009 approved these changes
타코캣 지스 스텝1 수고하셨습니다🎉
몇 가지 리뷰 남겨놨는데요. 이 부분은 확인하시고 스텝2에서 다시 얘기해보도록 해요!

2021-08-24 07:32 UTC, wonhee009 commented on OpenMarket/OpenMarket/Model/Media.swift
> +}
MimeType은 `struct Media`에서만 사용하고 있는거 같아요.
Media 내부 enum으로 정의하는건 어떤가요?

2021-08-24 07:32 UTC, wonhee009 commented on OpenMarket/OpenMarket/Model/ParsingManager.swift
> +    }
이 부분은 디코드 하는 부분에서는 `<T: Decodable>` 인코딩하는 부분에서는 `<T: Encodable>`로 해도 될거 같은데요.
이 부분 어떻게 생각하실까요?

2021-08-24 07:32 UTC, merged