오픈마켓 [Step 1] Shapiro, 승기
yagom-academy/ios-open-market pull request #57
Opened 2021-08-17 09:22 UTC by shapiro711

@jungseungyeo 

안녕하세요 린생!! 우여곡절 끝에 step-1을 마무리 지어서 PR을 보냅니다.
린생이 많은 부분을 알려주셨는데 반영을 잘 못한것 같아서 아쉬움이 남습니다...
고칠 부분이 정말 많아 보이지만 린생에게 리뷰를 받고 방향성을 정하고 수정을 하는 방향이 좋아보여서
부족하지만 PR을 날립니다!! 잘 부탁드려요 :)

## 구현한 부분
---
1. 서버와 통신할 Model 타입 구현 - 서버와 데이터를 주고 받을때 사용할 model들을 구현했습니다.
2. 통신을 위한 NetWorkManager 타입 구현
3. multi-part-form 데이터 생성 해주는 로직 구현
4. 테스트를 위한 MockURLProtocol 타입 구현

##궁금한 부분
---
1. NetworkManager 의 request부분에 body에 데이터가 들어가지 않은 경우(get)를 처리하기 위해서 request 메서드를 오버로딩하여 구현했습니다. 린생이 말씀해주신 파라미터 값으로만 처리하는 방법을 사용하지 못했는데 지금 저희의 request 메서드 동작 방식이 괜찮은지 궁금합니다.
2. URLSessionTests - 저희가 한 테스트가 괜찮은 방향인지 궁금합니다. 많은 케이스들을 작성하지는 않았는데 이대로 나머지 케이스도 테스트를 하면 될까요?
3. 현재 저희의 코드가 너무 api 문서에 한정되어있어 확장성이 낮은 코드라는 생각이 듭니다. 현업에서는 이런 통신을 할때 모델을 만들고 사용을 하는지 혹은 딕셔너리로 파라미터만 넘겨주면서 통신을 하는지 궁금합니다.
4. 모델들의 추상화가 잘 되어있는지 궁금합니다. 최대한 사용자 입장에서 잘 쓰기위해 추상화를 하려고 노력했는데 현재 코드에서 새로운 모델이 생긴다면 문제가 있을것 같아 이부분에 대한 린생의 생각이 궁금합니다.

2021-08-18 14:22 UTC, jungseungyeo requested changes
1. NetworkManager 의 request부분에 body에 데이터가 들어가지 않은 경우(get)를 처리하기 위해서 request 메서드를 오버로딩하여 구현했습니다. 린생이 말씀해주신 파라미터 값으로만 처리하는 방법을 사용하지 못했는데 지금 저희의 request 메서드 동작 방식이 괜찮은지 궁금합니다.

> 좋지 않은거 같아요! request 안에서 타입 캐스팅을 하고 있어 RESTAPI의 위한 networker를 만든것 보다는 하나의 API를 위해서만 존재하는 request를 만들었어요! 공통화하는 방법을 고민하면 좋을거같아요! 무엇 때문에 공통화 코드가 되지 않았는지 고민해보면 좋을거같네요! 

2. URLSessionTests - 저희가 한 테스트가 괜찮은 방향인지 궁금합니다. 많은 케이스들을 작성하지는 않았는데 이대로 나머지 케이스도 테스트를 하면 될까요?

> 테스트 코드를 작성하는 형태는 너무 좋아요! MockURLProtocol를 만들어서 사용하는 부분이 너무 좋았습니다.

3. 현재 저희의 코드가 너무 api 문서에 한정되어있어 확장성이 낮은 코드라는 생각이 듭니다. 현업에서는 이런 통신을 할때 모델을 만들고 사용을 하는지 혹은 딕셔너리로 파라미터만 넘겨주면서 통신을 하는지 궁금합니다.

> 이건 따로 날짜를 잡아서 이야기하면 좋을거같네요!

4. 모델들의 추상화가 잘 되어있는지 궁금합니다. 최대한 사용자 입장에서 잘 쓰기위해 추상화를 하려고 노력했는데 현재 코드에서 새로운 모델이 생긴다면 문제가 있을것 같아 이부분에 대한 린생의 생각이 궁금합니다.

> 현재 추상화를 한 것보다는 하나의 형태를 protocol로 만든거 같아요! 그래서 post, get, fetch와 케이스에서 타입 케이스팅이 발생하고 있어요. 이렇게 된다면 하나의 API만 실행하는 코드가 됩니다.

승기, shpiro 테스트 코드를 작성하는 부분은 너무 좋았어요! 하지만 networker의 형태가 좋아보이지는 않아요! 좋지 않는 이유는 하나의 API만 지원하게 코드가 설계가 되어 있어요! 네트워크의 테스트를 너무 고민하여 이부분에 할 여유가 없었던거 같아요! 이부분을 어떻게 같이 사용 할 수 있을지 고민해서 만들면 좋을거같아요!

post, fetch, delete등에서 타입 케스팅이 발생하여 이런한 형태가 되는거같아요! 하나의 형태를 묶는 protocol 하나만 있으면 좋을거같아요!

2021-08-18 14:22 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/NetworkManager.swift
> +            guard let deleteModel = model as? DeleteItem else {
여기서 Model로 타입 케스팅이 된다면 network layer와 model에 강하게 의존관계가 되는거 같아요. networker가 model을 의존하지 않게 해주세요. POP 구조로 구현하면 좋을거같아요!

2021-08-18 14:22 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/NetworkManager.swift
> +            guard let postModel = model as? PostItem else {
PstIem은 Networker Layer에 의존하면 안될거같아요!, Post는 한 API를 위해 존재하는게 아니라 모든 post API를 지원해주어야해요

2021-08-18 14:22 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/NetworkManager.swift
> +            guard let patchModel = model as? PatchItem else {
전체저적으로 RESTAPI에서 Model를 의존하고 있어요 모델을 의존하지 않게 해주세요

2021-08-18 14:22 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/NetworkManager.swift
> +    func request<T: APIModelProtocol>(requsetType: RequestType, url: String, model: T, completion: @escaping URLSessionResult) {
여기서 Model을 받는게 이상한거 같아요. Model이 아닌 파라미터를 받아서 처리 해주세요 단순히 Model을 받는게 아니라 파라미터를 받아야 해요. POP 구조를 생각해주세요!

2021-08-18 14:22 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/NetworkManager.swift
> +    func request(requsetType: RequestType, url: String, completion: @escaping URLSessionResult) {
request 함수는 하나로 하면 좋을거 같아요! 하나로 해야 되는 이유는 endPoint는 하나로 통일하는게 유지보수에서도 좋아서 하나로 관리하면 좋을거같아요!

2021-08-18 14:22 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/Media.swift
> +protocol Media: Codable {
이 프로토콜이 필요한 이유가 무엇인가요?

2021-08-18 14:22 UTC, jungseungyeo commented on OpenMarket/OpenMarket/Model/APIModel/APIModelProtocol.swift
> +protocol APIModelProtocol: Codable {
이 프로토콜이 있어서 RESTAPI에서 타입 케스팅이 발생하는거 같아요! 하나의 형태로 만들 수 있는 형태로 구현을 하는 방법을 생각해보면 어떤가요?

2021-08-18 14:22 UTC, jungseungyeo commented on OpenMarket/OpenMarketTests/URLSessionTests.swift
> +            //then
then은 클로져안에서 하지말고 마지막으로 해주세요!

2021-08-18 14:22 UTC, jungseungyeo commented on OpenMarket/OpenMarketTests/URLSessionTests.swift
> +            switch result {
then은 마지막으로 옮겨주세요

2021-08-18 14:22 UTC, jungseungyeo commented on OpenMarket/OpenMarketTests/URLSessionTests.swift
> +            //then
클로져 밖에서 처리해주세요!

2021-08-20 07:13 UTC, shapiro711 commented
@jungseungyeo 

안녕하세요 린생!! 말씀해주신 부분들을 토대로 리펙토링해서 푸시했습니다 :)

##구현한 내용 
1. api모델 리펙토링
2. NetworkManager - request, createBody메서드 로직 수정, test코드 수정한 내용에 맞게 변경 

##궁금한 점
1. body에 들어갈 contentType별 분기 처리를 고민했습니다. 현재 api 문서에는 그런 내용이 없지만 post 일때 json 형태로 보내는 일도 있을 수도 있다고 생각해서 APIable 프로토콜에 contentType을 받아서 분기처리를 해주었습니다. 괜찮은 방법인지 궁금합니다!

2021-08-21 00:34 UTC, jungseungyeo commented
Shapiro, 승기 코드가 너무 좋아요! 고민한 흔적이 보이네요! api의 리펙토링과 구조가 좋아진거 같아요! 테스트 코드도 외부로 뻇내어 작성한 부분도 좋구요. 다음 스텝으로 진행해도 좋은거 같아요.

1.body에 들어갈 contentType별 분기 처리를 고민했습니다. 현재 api 문서에는 그런 내용이 없지만 post 일때 json 형태로 보내는 일도 있을 수도 있다고 생각해서 APIable 프로토콜에 contentType을 받아서 분기처리를 해주었습니다. 괜찮은 방법인지 궁금합니다!

> 나쁘지 않은거 같아요. swiftch를 사용해서 하는 방법도 괜찮은데 이런 형태로 만들어주는 것도 괜찮은거 같아요! 큰 문제는 없는거 같아요.

다음 스텝에서는 .get, post이런 파일 네임도 수정하면 좋을거같아요! 우리가 알고 싶은건 ~ api 인거지 get, post인지가 알고 싶은건 아니잖아요. 네이밍을 특정 method를 알리기보다는 무엇을 하는 객체인지를 나타내면 좋을거같아요!

정말 고생하셨습니다.

2021-08-21 00:34 UTC, merged