Step 1 : 모델 및 네트워킹 담당 타입 구현 - Green, Jake
yagom-academy/ios-open-market pull request #6
Opened 2021-01-28 02:37 UTC by jryoun1

@Limwin94 
안녕하세요 림윈!! 
오늘 내일 폭설이니까 출퇴근 조심하세요!!🌨

[구현사항]
1. 상품 모델 타입 구현
2. URL을 설정해주는 Config 타입 구현
3. ItemManager 타입을 두어, item을 서버에서 GET,POST,PATCH,DELETE 해줄 수 있도록 구현
4. Unit 테스트 작성
(이때 delete는 한번 테스트 실행하면 param이라는 변수 값을 변경해서 넣어줘야합니다!!)

리뷰 부탁드립니다!!

2021-01-28 15:16 UTC, Limwin94 requested changes
그린, 제이크 Step1 진행하시느라 고생하셨습니다!

폴더랑 파일들을 각자의 역할에 맞게 정말 잘 분리해놓으신것 같아요ㅎㅎ
쉽지 않으셨을텐데 고민을 많이 하신것 같았습니다 :)

파일도 많은 만큼 코멘트가 조오금 많게 느껴지실것 같아요..😅
그리고 다음부터는 스텝을 진행하면서 고민했던 사항이 있으면 들려주실 수 있을까요? 궁금하네요ㅎㅎ

혹시 이해가 되지 않는 코멘트나 제가 의도를 다르게 파악해서 남긴것이 있다면 언제든 DM 주셔도 됩니다!
(그리고 Lin으로 불러주세요..림윈하니깐 어색하네요..ㅋㅋㅋ)

2021-01-28 15:16 UTC, Limwin94 commented on OpenMarket/OpenMarket/Assets.xcassets/testImage2.imageset/Contents.json
> +      "filename" : "testImage2.jpeg",
테스트에 쓰이는 이미지라 테스트가 끝나고 나면 더 이상 쓰이지 않을 수도 있지만, 사용할 당시 / 혹은 이 프로젝트를 다른 동료들이 보았을때 testImage2가 어떤 이미지인지 와닿지 않을수도 있다는 생각이 들었습니다.

개발하는데 아주 큰 영향은 미치지 않긴해요..ㅎㅎ 정말 개인적으로 테스트(혹은 디버깅)에 관련된 값들도 의미를 명확하게 나타내려고 노력하는 편이라 개인적인 의견을 나타내 보았습니다.

그린이나 제이크는 어떻게 생각하시나요? 궁금합니다!

2021-01-29 07:11 UTC, jryoun1 commented on OpenMarket/OpenMarket/Network/UrlPath.swift
> +enum UrlPath: String {
@Limwin94 
url과 같은 단어에 대해서는 URL 대문자로 사용하거나, url 소문자로 사용할 수 있도록 수정하였습니다. 
(즉, 대소문자를 섞어서 쓰지 않도록 수정해주었습니다. )

2021-01-29 07:14 UTC, jryoun1 commented on OpenMarket/OpenMarket/Network/ItemManager.swift
> +            guard let mimeType = httpResponse.mimeType, mimeType == "application/json" else {
@Limwin94 
mimeType을 검사하는 이유는 일단 네트워크 통신을 하는 부분에 관련된 [공식문서](https://developer.apple.com/documentation/foundation/url_loading_system/fetching_website_data_into_memory)에서 발생할 수 있는 에러들에 대해서는 처리를 해주는 것 같아서 작성을 해주었습니다.

그리고 해당 `loadData()`함수에서만 mimeType을 검사했던 이유는 사실 load할때는 확실히 데이터를 가져오니까 체크를 해줘야한다고 생각해서 작성했는데, 사실 `uploadData()`나 `deleteData()`도 response로 JSON 타입 데이터를 반환해주기 때문에 체크를 해주는 것이 옳다고 생각해서 체크를 해주도록 수정하였습니다.

2021-01-29 07:24 UTC, jryoun1 commented on OpenMarket/OpenMarket/Network/ItemManager.swift
> +        let session: URLSession = URLSession(configuration: .default)
@Limwin94 
[공식문서](https://developer.apple.com/documentation/foundation/urlsession) 에서 
> Types of URL Sessions
The tasks within a given URL session share a common session configuration object, which defines connection behavior, like the maximum number of simultaneous connections to make to a single host, whether connections can use the cellular network, and so on.
URLSession has a singleton shared session (which doesn’t have a configuration object) for basic requests. It’s not as customizable as sessions you create, but it serves as a good starting point if you have very limited requirements. You access this session by calling the shared class method. For other kinds of sessions, you create a URLSession with one of three kinds of configurations:
A default session behaves much like the shared session, but lets you configure it. You can also assign a delegate to the default session to obtain data incrementally.

이 부분을 보면 `shared`의 경우에는 **configuration object를 가질 수 없다**고 나와 있고, 반면에 직접 session 객체를 설정해서 default로 만들게 되면 **configuration을 default, Ephemeral, background** 로 구성을 해줄 수 있는 걸로 알고 있습니다.

default의 경우에는 shared와 하는 역할은 비슷하지만 **delegate의 할당해서 데이터를 점진적으로 가져올 수 있다는 점**에서 shared와 다른점이 있는걸로 알고있습니다!!

물론 여기서는 굳이 session 객체를 만들어 사용하지 않고 shared를 사용해도 되긴하지만 한 번 사용해보았습니다,,

2021-01-29 07:33 UTC, jryoun1 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    func testPatchItem() {
@Limwin94 
이부분에 대해서는 사실 저희가 제출할때는 `testPostItem()` 함수를 먼저 테스트하여 올라간 아이템의 id를 알아내어서
해당 id를 가지고 테스트 코드가 돌아가도록 구현을 해놨는데, upload된 아이템이 지워진 것 같아서 fail이 난것 같아요!!

따라서 `testPostItem()` 테스트를 먼저 진행하고 올라간 아이템의 id를 가져와서 `testPatchItem()` 을 진행해야할 것 같아요,,

2021-01-29 07:38 UTC, jryoun1 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    func testPatchItem() {
![image](https://user-images.githubusercontent.com/45090197/106245741-518c7f80-6250-11eb-947a-533d90f4a49a.png)

2021-01-29 08:02 UTC, jryoun1 commented on OpenMarket/OpenMarket/Network/ItemManager.swift
> +    static func loadData(path: UrlPath, param: UInt, completion: @escaping errorHandler) {
loadData() 메서드의 경우에는 ItemList를 받아올때는 page를 매개변수로 전달하게 되고, 
Item을 데이터를 받아오는 경우에는 id를 받아오게 되는데 이러한 부분을 나누기가 애매해서 
parameter인 param이라고 네이밍을 붙였습니다!!

2021-01-29 08:22 UTC, jryoun1 commented on OpenMarket/OpenMarket/Assets.xcassets/testImage2.imageset/Contents.json
> +      "filename" : "testImage2.jpeg",
@Limwin94 
사실 저희도 Lin의 생각과 동일한데, 이 코드를 작성할 당시에 정말 되는지 안되는지 테스트를 해보고 
안되면 지울 것 같아서 변수명을 짓는데에 별 생각없이 작성했던 것 같아요! 
이후에 수정을 하지 못하고 PR을 날리게 된 것 같네요,,ㅠ

비록 간단한 테스트 일지라도 앞으로는 네이밍에 좀 더 신경을 쓰도록 해야할 것 같아요!! 
좋은 코멘트 감사합니다🙇‍♂️👍🏻

2021-01-30 05:27 UTC, Limwin94 commented on OpenMarket/OpenMarket/Assets.xcassets/testImage2.imageset/Contents.json
> +      "filename" : "testImage2.jpeg",
이런 의견은 정말 개개인 마다 다를수도 있는데 긍정적이게 받아들여주셔서 감사합니다! 화이팅입니다ㅎㅎ

2021-01-30 05:54 UTC, Limwin94 commented on OpenMarket/OpenMarket/Network/ItemManager.swift
> +    static func loadData(path: UrlPath, param: UInt, completion: @escaping errorHandler) {
그렇군요 :)
`loadData` 내부에서 URLPath로 아이템 목록을 받아올때와 단일로 받아올때를 구분해주고 있는걸로 알고있습니다.

아마 저라면 단계를 하나 더 둘것 같아요. (절대 제가 맞다는게 아닙니다..!)
URLSession을 분리해내면 상위객체에서 아이템 목록 / 단일로 받아오는 함수를 호출할때 더 명확하게 나눌 수 있을 것 같아요.
상위객체(호출하는 곳) -> loadItemList / loadItem -> URLSession

아마 예를 들면 이런식으로 구성할 수 있겠네요. 제가 말씀드린 방식은 어떤 장/단점이 있을것 같나요?

2021-01-30 06:06 UTC, Limwin94 commented on OpenMarket/OpenMarket/Network/ItemManager.swift
> +        let session: URLSession = URLSession(configuration: .default)
알겠습니다 👍🏻 
저도 `URLSession`은 아니지만 단순히 다른걸 적용해보고 싶어서 사용해본 경험이 있었는데요.

그러고 난뒤 PR을 요청했을때 이러한 피드백을 받았던 적이 있어서 가져와보았습니다.
```
combine으로 바인딩하고 싶은 욕구를 몰라서 물어보는 건 아니었습니다.
그걸 왜 그래야 하는가 입니다. 엔지니어라면 하고 싶어서 보다는 더 객관적인 자료가 있으면 어떨까요?
뭐가 어떻게 얼마나 좋아진다거나, 어떤 단점이 있지만 더 장점이 크다거나
이런저런 비교해보니 이걸 선택하게 됐습니다. 정도로 남들을 설득하는 연습을 해보세요.
PR을 보내는 건 다른 사람에게 내가 선택한 과정과 결과로 만들어진 코드를 설득하는 과정입니다.
merge 권한을 가진 시니어가 하고 싶어서, 하기 싫어서 여러분과 다른 선택을 하면 어떨까요?
물론 감정싸움이 될 수도 있지만 그런 상황이 되지 않도록 설득하는 과정을 염두해보세요.
```

사실 지금도 어려운 부분이라 항상 기존에 사용해왔던걸 바꾸거나 새로운 걸 적용해볼때 항상 이 멘트가 머릿속에서 남더라구요ㅎㅎ
도움이 되었으면 좋겠습니다 🤓

2021-01-30 06:09 UTC, Limwin94 commented on OpenMarket/OpenMarket/Network/ItemManager.swift
> +            guard let mimeType = httpResponse.mimeType, mimeType == "application/json" else {
개인적으로 저는 memeType은 따로 검사하지 않는편입니다, 하지만 저렇게 방어코드가 있으면 안정성이 더 좋아질것 같네요 👍🏻

2021-01-30 06:09 UTC, Limwin94 commented on OpenMarket/OpenMarket/Network/UrlPath.swift
> +enum UrlPath: String {
피드백 반영 감사합니다 :)

2021-01-30 06:14 UTC, Limwin94 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    func testPatchItem() {
캡쳐까지..! 감사합니다ㅎㅎ

수정/삭제/등록을 하나의 id로 하는것 보다는 각각 다른 id로 진행하는것과 같이 각 테스트이 결과가 다른 테스트에 영향을 주지 않게 구성하는것도 좋을것같아요.

이건 다른 문제인데요. 만약 네트워크가 되지 않는 상황에서 해당 메소드들을 검증하려면 어떻게 해야할까요?
예를 들어 서버와의 데이터 구조 정의는 끝난 상태지만 아직 API가 만들어지지 않는 상황이 있을 수 있겠네요.

2021-01-31 12:57 UTC, jryoun1 commented on OpenMarket/OpenMarket/Network/ItemManager.swift
> +        let session: URLSession = URLSession(configuration: .default)
@Limwin94 
정말 좋은 멘트 감사합니다 Lin👍🏻
덕분에 그냥 한 번 사용해 본다는 것이 엔지니어로서는 지향해야하는 태도라는 것을 다시 한 번 생각해보게 되었습니다!!
그래서 URLSession shared와 default의 차이를 다시 한 번 찾아보게 되었습니다.
그리고 다음과 같은 [공식문서](https://developer.apple.com/documentation/foundation/urlsession/1409000-shared)를 발견하게 되었습니다. 

읽어본 결과 짧게 결론만 얘기해보면 
> 만약 cache, cookies, authentication, custom networking protocols을 사용하는 것이라면 shared session이 아닌 default session을 사용해야 한다고 합니다.

따라서 현재 저희 프로젝트에서는 위의 어떠한 기능도 사용하는 것이 아니면 즉, 위의 그 어떠한 것도 다시 구현해서 사용하는 것이 아니므로 default가 아닌 shared를 사용하는 것이 더 나을 것이라는 생각이 들어서 수정하게 되었습니다!!

2021-01-31 13:04 UTC, jryoun1 commented on OpenMarket/OpenMarket/Network/ItemManager.swift
> +    static func loadData(path: UrlPath, param: UInt, completion: @escaping errorHandler) {
@Limwin94 
저와 그린이 상의를 해 본 결과 `loadItemList()`, `loadItem()`로 수정하게 되면 
중복되는 코드가 많은 것 같아서 이 부분은 그대로 진행하기로 하였습니다.
장점 : 다른 객체에서 **해당 함수를 호출할 때 좀 더 명확하게 호출**을 할 수 있을 것 같습니다. 
단점 : **코드의 중복이 많이 발생**하는 것 같습니다. 

그리고 Lin이 말씀해주셨던 것처럼 `loadData()`라는 함수가 많은 역할을 가지고 있는거 같아서 
안에 내부의 로직을 다음과 같은 3가지 로직으로 나눠서 구현해보았습니다. 
1. URL을 만드는 함수
2. URLRequest를 생성하는 함수
3. Network와 통신을 하는 함수

이렇게 3가지로 나눠주었습니다.

2021-01-31 13:08 UTC, jryoun1 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    func testPatchItem() {
@Limwin94 
> 수정/삭제/등록을 하나의 id로 하는것 보다는 각각 다른 id로 진행하는것과 같이 각 테스트이 결과가 다른 테스트에 영향을 주지 않게 구성하는것도 좋을것같아요.

이 부분은 적극적으로 반영하여 수정해보았습니다!! 
(그런데 실제 네트워크 통신을 해서 하면 테스트를 진행하게 되면 param의 값을 변경해주어야지 
다음 테스트를 통과하는 부분은 어쩔수 없는것 같아요!! e.g. delete)

> 이건 다른 문제인데요. 만약 네트워크가 되지 않는 상황에서 해당 메소드들을 검증하려면 어떻게 해야할까요?
예를 들어 서버와의 데이터 구조 정의는 끝난 상태지만 아직 API가 만들어지지 않는 상황이 있을 수 있겠네요.

윗부분에서 로직을 3단계로 나눈 뒤에 3가지 로직을 각각 따로 UnitTest로 작성해보았습니다.
1. URL을 만드는 함수
2. URLRequest를 생성하는 함수
3. Network와 통신을 하는 함수

따라서 API가 아직 구현이 되지 않은 상태라면 3번인 network통신을 해주는 부분은 테스트를 진행 할 수 없는 것 같고,
나머지 **1,2 번 단계는 API 구현과는 별도로 테스트를 할 수 있도록 수정**하였습니다. 
그리고 3번 네트워크 통신 부분은 mockup 데이터를 사용하면 테스트를 해볼 수 있을 것 같습니다!!!

2021-01-31 13:45 UTC, jryoun1 commented
@Limwin94 
코드리뷰 다시 부탁드립니다!!

[수정사항]
1. 네트워크 통신하는 부분 따로 빼기
2. ItemManager 함수에서 loadData, postData, deleteData 함수 내부 로직을 3개로 나눠서 구현
2-1. 로직 3개로 나눈 부분을 따로 UnitTest로 작성
3. XCTest에서 각각 다른 id로 테스트 할 수 있도록 변경

내일은 다시 월요일이네요!! 화이팅해요~~👍🏻

2021-02-01 15:05 UTC, Limwin94 reviewed
고생하셨습니다~!

코드가 더 깔끔해진것 같습니다 👍🏻  역할을 나누는 데에 있어서 고민을 많이 하신것 같았습니다. :)
다음 스텝 넘어가기전에 제가 이전에 코멘트 해드린 '네트워크가 되지 않는 상황에서의 테스트'정도만 진행해주시면 좋겠습니다.😊

몇가지 코멘트들을 남겨보았습니다. 해당 부분들은 다음 스텝 진행하면서 변경해도 될것같아요~!

2021-02-02 04:02 UTC, jryoun1 commented on OpenMarket/OpenMarket/Network/ItemManager.swift
> +    func makeURL(method: HttpMethod, path: PathOfURL, param: UInt?) -> URL? {
@Limwin94 
해당 메소드들은 UnitTest를 진행하기 위해서 접근제어를 private-> internal로 변경하였습니다!!

2021-02-02 04:27 UTC, jryoun1 commented
@Limwin94 
Lin 안녕하세요~ 오늘 날씨가 많이 춥네요 🥶
감기 조심하세요!!

[수정사항]
1. 네이밍 변경
2. uploadData(), makeURL() 함수에서 param 초기값 설정
3. makeURL() 에서 분기코드 삭제

[구현사항]
Lin이 보내주신 링크를 참고해서 작성해보았습니다!! 
1. 네트워크가 되지 않는 상황에서의 테스트 진행을 위해서 protocol 및 mock객체, mockURLSession 구현
2. loadItem()을 네트워크가 없는 사항에서도 진행할 수 있도록 테스트 작성 (HTTP method GET만 테스트 코드작성해봤습니다!!)

2021-02-03 15:23 UTC, Limwin94 approved these changes
그린, 제이크 안녕하세요 :)

몇가지 코멘트를 남겨보았는데요. 해당 부분은 다음스텝 진행하시면서 수정해보시면 좋을것 같습니다. 👍🏻 
테스트 코드 작성하시느라 고민 많이하셨을텐데 고생하셨습니다~!

2021-02-03 15:23 UTC, Limwin94 commented on OpenMarket/OpenMarket/Model/ItemToUpload.swift
> +struct ItemToUpload: Encodable {
삭제할 아이템의 정보와 업로드할 아이템의 정보를 담은 구조체네요. 잘 나누신것 같습니다 👍🏻 
하나 궁금한건 API 문서에는 discounted_price만 optional로 명시가 되어있는데 다른 속성들을 optional로 선언한 이유가 있을까요?

2021-02-03 15:24 UTC, merged

2021-02-04 01:44 UTC, jryoun1 commented on OpenMarket/OpenMarket/Model/ItemToUpload.swift
> +struct ItemToUpload: Encodable {
@Limwin94 
저희는 PATCH와 POST할 때 ItemToUpload라는 모델을 공통적으로 사용하기 위해서 
password를 제외한 나머지 타입들은 전부 다 옵셔널로 작성할 예정이었습니다.

그러나 확인해본결과 password도 옵셔널로 작성이 되어있는 것 같아서 
step2에서는 password를 제외한 나머지 타입들만 optional로 선언해놓을 예정입니다!!