오픈마켓 [Step1] 수박
yagom-academy/ios-open-market pull request #61
Opened 2021-08-19 12:59 UTC by soo941226

@wonhee009 

안녕하세요 라자냐!!! 드디어 스텝1 PR을 보냅니다... 감격스럽네요

궁금한 게 정말 한가득인데요... 궁금한 걸 모아놓고 보니 중간중간에 물어보는 게 나았을 것 같기도 합니다..! 😅

질문하는 내용이 많아서 좀 죄송스럽기도 하고, 답변하시는 데에도 오래 걸릴 것이라 짐작이 되는데... 천천히 해주셔도 괜찮습니다..!

잘 부탁드립니다!! 🙏

---

### 모델링 관련

1. Resposne body의 모델을 작성하는 과정에서, ItemList의 아이템과 POST, PATCH, DELETE 등에 사용되는 아이템이 조금씩 다른 걸 확인했습니다. 이 다른 내용을 같은 구조체 안에서 옵셔널 프로퍼티로 처리를 할 것인지, 서로 다른 구조체로 분리할 것인지를 고민했습니다. 하지만 각각의 요청마다 각각의 타입을 관리하는 것은, 요청이 많아지면 힘들어질 수도 있겠다는 짐작을 하게 되어 일단은 어떻게든 하나로 뭉쳐 현재와 같은 ItemRequestable을 만들게 되었는데, 현재는 어떻고 더 좋은 방법이 있을지 궁금합니다!

1. 네트워크 통신 객체의 네이밍 관련하여 고민이 들었습니다. 기존에는 예약어를 사용하지 말라는 말을 자주 들어서, 메소드의 이름이 get이나 set과 같은 이름으로 시작하는 것은 지양해 왔는데요. 그런데 어떻게 보면 HTTP 메소드도 예약어의 일종이라는 생각이 들었고, 그래서 HTTP의 성질을 나타내기 위해서는, 결국 get과 같은 예약어를 조금은 사용해야 하지 않나 하고 생각했습니다. 잘못된 생각일까요? 또 직관적인 명명법이 있을까요? 

1. 현재의 protocol 타입들과 이에 대한 extension이 잘 읽히시는지, 또 괜찮다고 생각을 하시는지 궁금합니다. POP를 추구하기 위해, protocol의 extension을 작성하는데에 굉장히 많은 시간과 공을 들였는데요... 내용에 어떤 허점이 있는지, 지적을 해주시면 정말 감사하겠습니다!!

1. ItemList에 subscript를 추가하였는데, itemList.item[x]으로 접근하여 아이템을 얻는 것보다, itemList[x]으로 아이템을 얻는 게 직관적인 것 같아 이렇게 해보았는데요. 작성해놓고 보니 뭔가 직관적이지 않은 것 같기도 해서... 이에 대해 어떻게 생각하시는지, 개선한다면 어떻게 개선하는 게 좋을지 궁금합니다!!

### 테스트 관련

1. 프로젝트 명세서에서는 옵셔널 강제 언래핑(!)을 쓰지 말라고 명시하고 있는데, 테스트에서는 약간 주저하다가 그냥 느낌표를 쭉 썼는데요. 테스트를 하려고 하는데 이것저것 고민을 하려니 배보다 배꼽이 너무 커지는 것 같아서... 테스트 목적에만 집중하려고 해보았는데 스스로도 많이 탐탁치 않긴 합니다... 이래도 괜찮을까요? 

1. async한 closure를, 특히 실제로 네트워크 통신을 하는 것은 어떻게 테스트를 해야하는지 고민입니다. semaphore 따위를 활용해서 지연을 시키는 게 맞는 건지... 이건 진짜 갈피를 못잡겠어서... 결국엔 ViewController에서 테스트를 하고 print를 찍어보고 하게 되었는데요... 도와주시면 감사하겠습니다...

1. POST, PATCH, DELETE 등을 protocol에 추가한 뒤, mock 객체를 활용하여 테스트를 해보려고 했으나 뭔가 소꿉놀이를 하는 것 같은... 탐탁치 않은 느낌이 들었습니다
그래서 일단은 제외하였는데, 그러다보니 mock 객체가 protocol을 준수하지 않게 되어서... 빌드조차 되지 않는 이슈가 있었습니다. 메소드에 optional을 붙여보려고 했으나 의도한 데로 되지 않고, 컴파일러가 @objc 와 같은 키워드를 붙여야한다고 경고를 날려 이것을 반영했으나, 그럼에도 불구하고 제대로 동작하지 않아 그냥 body는 없이 extension으로 빼게 되었는데요. 괜찮은 것인지... 의문이 강하게 듭니다...

1. 만약 네트워킹 테스트를 하게 된다면, 현재의 파싱 테스트 프로젝트와는 별개로 새로운 테스트 프로젝트를 만들어서 테스트를 해보고 싶은데 그래도 괜찮은 것일까요?

---

2021-08-22 04:47 UTC, wonhee009 requested changes
안녕하세요 수박! 스텝1 수고하셨습니다🎉
바로 리뷰 남기려 했는데 시간이 조금 걸렸네요 죄송해요🥲
리뷰 남겼으니 확인 부탁드립니다🙏
나중에 시간 되시면 `Moya`나 `Alamofire`같은 네트워크 라이브러리 컨셉?정도 보는 것도 좋을거 같아요. (왠지 수박이 좋아할거 같아옄ㅋㅋ) <- 이 부분은 정말 급한거도 아니고 나중에 볼 기회가 있으니 무조건 보라는 얘기는 **절대 절대** 아닙니다!

### 모델링

1.
우선 저도 수박이 작성한 ItemRequestable처럼 작성할거 같아요.
수박이 작성한 코드를 보면 ItemRequestable의 모든 프로퍼티가 Optional이고 기본적으로 nil로 정의되어 있네요.
```swift
struct ItemRequestable: Loopable, Codable {
    private(set) var title: String? = nil
```

인스턴스를 생성할때 프로퍼티를 입력할텐데 이때 nil인지 아닌지 알 수 있을거 같아요. 
```swift
ItemRequestable(title: nil, descriptions: nil
```
프로퍼티를 기본적으로 nil로 정의하고 있는건 실수를 방지하기 위해서일까요?

`buildedFormData()`와 같은 메서드를 ItemRequestable이 가지고 있는건 어떨까요?


2.
예약어를 사용하지 말라는 말을 자주 들어서 <- 저는 이 맥락에서 말하는 예약어는 Swift 예약어라고 생각하고 있습니다.
따라서 get, patch, delete 등과 같은 HTTP 메서드 관련 prefix를 사용하고 있기도 하고요.
그리고 네이밍에서도 get, patch, delete만큼 직관적인 네이밍은 없다고 생각합니다:)

3.
POP를 적용해 구현해보셨네요🎉
POP를 적용한 이유가 있을까요?(그냥 궁금한 점입니다:))
Session Struct에서 get/이외의 메서드에서 url이 생성되는 위치가 다른거 같아요.
Get 메서드는 메서드 내부에서 `let path = HttpConfig.baseURL + HttpMethod.items.path`로 생성해주고,
이외의 메서드는 `buildedRequestWithFormDataAbout()`내부에서 생성해주고 있네요.

수박이 작성한 Session에 다른 사람이 getA(), postA() 메서드가 추가된다고 생각해볼게요.
url을 메서드 내부에서 생성해줘야하는지 `buildedRequestWithFormDataAbout()`를 호출해 알아서 url을 만들어줄지 헷갈리지 않을까요?
url을 생성할때 필요한 component들을 주입하면 url을 만들어주는 역할을 하나 더 두는건 어떨까요?

4.
itemList[x] <- 이게 보기에는 좀 더 직관적인거 같습니다.
다만 ItemList가 page라는 프로퍼티를 가지고 있기도 하고 이후에 ItemList에 다른 배열 프로퍼티가 추가된다면 어떻게 될까요?

### 테스트

1.
[이 링크](https://www.swiftbysundell.com/articles/avoiding-force-unwrapping-in-swift-unit-tests/)가 도움이 될까요?

2.
테스트 가능한 통신에 관해서 고민하셨네요! 저도 해당 프로젝트를 진행할때 이 부분에서 많이 고민했던 경험이 있는데요;
[이 게시물](https://medium.com/mobile-app-developers/testable-network-layer-in-swift-part-1-dd9aa4f31e0e) 확인해 보시면 좋을거 같아요!

3.
Mock 객체가 어떤 프로토콜을 준수하지 않았던 걸까요?
그냥 body는 없이 extension으로 빼게 되었는데요 <- 이 부분에 대해서도 자세하게 듣고 싶어요😀

4.
네 괜찮을거 같습니다😀

2021-08-22 04:47 UTC, wonhee009 commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +//        undesirableTest()
사용하지 않는 코드는 지워주세요:)

2021-08-22 04:47 UTC, wonhee009 commented on OpenMarket/Model/Item.swift
> +struct Item: Decodable {
어떤 아이템을 의미하는 걸까요? 무슨 뜻인지 상세하게 알 수 있었으면 좋겠습니다!

2021-08-22 04:47 UTC, wonhee009 commented on OpenMarket/Model/ItemDetail.swift
> +struct ItemDetail: Decodable, Equatable {
`struct Item`과 `struct ItemDetail`를 분리해서 작성한 이유가 궁금해요.
Item과 ItemDetail의 사용처가 다른가요?
가지고 있는 프로퍼티가 거의 동일해서요!😀

2021-08-22 04:47 UTC, wonhee009 commented on OpenMarket/Model/ItemList.swift
> +struct ItemList: Decodable {
어떤 Item의 리스트인걸까요?🤔

2021-08-22 04:47 UTC, wonhee009 commented on OpenMarket/Network/Http.swift
> +}
이 부분은 왜 extension으로 뽑은 이유도 궁금합니다🤔

2021-08-22 04:47 UTC, wonhee009 commented on OpenMarket/Network/HttpConfig.swift
> +    static let invailedPath = "AppError: current path is invailed"
사용하지 않는 프로퍼티인거 같은데요. 추가한 이유가 있나요?

2021-08-22 04:47 UTC, wonhee009 commented on OpenMarket/Network/HttpConfig.swift
> +    static let requestHeader = "multipart/form-data; boundary="
`requestHeader`라는 프로퍼티로 네이밍했네요. HTTP request header에는 멀티파트 폼만 들어갈 수 있나요?

2021-08-22 04:47 UTC, wonhee009 commented on OpenMarket/Protocol/Coder.swift
> +protocol Coder {
Coder라는 이름으로는 어떤 역할을 하는 프로토콜인지 잘 모를거 같아요. 좀 더 직관적인? 어떤 역할을 하는지 보이도록 네이밍을 개선할 수 있을까요?

2021-08-22 04:47 UTC, wonhee009 commented on OpenMarket/Constants/String+Constants.swift
> +    static let blank = ""
blank는 사용하지 않는거 같은데 작성하신 이유가 있을까요?

2021-08-22 04:47 UTC, wonhee009 commented on OpenMarket/Constants/String+Constants.swift
> +extension String {
extension으로 String타입에 blank, newLine, parsingError 타입 프로퍼티를 추가해줬네요.
해당 타입 프로퍼티들을 String 타입이 가지고 있어야하는 이유가 있을까요?
사용자에게 보여지는 화면을 작성하기 위해 alert message를 작성한다고 가정해보면 우리가 필요한 것은 **alert message text**뿐인데 이 text는 String 타입이므로 사용하지 않는 blank, newLine, parsingError 프로퍼티를 가지고 있겠네요.

2021-08-22 04:47 UTC, wonhee009 commented on OpenMarket/Protocol/ErrorMessage.swift
> +}
`Messagable` 프로토콜의 역할이 무엇인가요?

2021-08-22 04:47 UTC, wonhee009 commented on OpenMarket/Protocol/ErrorMessage.swift
> +typealias ErrorMessage = Error & Messagable & Codable
`Codable`이 필요한 이유가 있나요?

2021-08-22 04:47 UTC, wonhee009 commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +    func undesirableTest(){
어떤 역할을 하는 함수인가요?

2021-08-22 04:47 UTC, wonhee009 commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +            print("")
print("")를 하는 이유가 있나요?

2021-08-22 04:47 UTC, wonhee009 commented on OpenMarket/Network/Session.swift
> +struct Session: Http, Coder {
이 한 줄만 보면 Session이 Http 프로토콜을 채택하고 있는게 어색해 보여요.
Http 프로토콜의 네이밍이 어색한거 같은데 개선해볼 수 있을까요?

2021-08-22 06:39 UTC, soo941226 commented
> 안녕하세요 수박! 스텝1 수고하셨습니다🎉
> 바로 리뷰 남기려 했는데 시간이 조금 걸렸네요 죄송해요🥲
> 리뷰 남겼으니 확인 부탁드립니다🙏
> 나중에 시간 되시면 `Moya`나 `Alamofire`같은 네트워크 라이브러리 컨셉?정도 보는 것도 좋을거 같아요. (왠지 수박이 좋아할거 같아옄ㅋㅋ) <- 이 부분은 정말 급한거도 아니고 나중에 볼 기회가 있으니 무조건 보라는 얘기는 **절대 절대** 아닙니다!
> > 오 다른 캠퍼 분들에게도 실무에서는 이걸 많이 쓴다고 들었습니다. 그냥 그렇구나 싶었고, 컨셉을 살펴본다는 생각은 못했는데... 다음주에 프로젝트가 마무리가 되면 한번 살펴보면서 제가 작성한 네트워크 타입과 비교를 해보겠습니다!!!
> ### 모델링
> 
> 우선 저도 수박이 작성한 ItemRequestable처럼 작성할거 같아요.
> 수박이 작성한 코드를 보면 ItemRequestable의 모든 프로퍼티가 Optional이고 기본적으로 nil로 정의되어 있네요.
> 인스턴스를 생성할때 프로퍼티를 입력할텐데 이때 nil인지 아닌지 알 수 있을거 같아요.
> 프로퍼티를 기본적으로 nil로 정의하고 있는건 실수를 방지하기 위해서일까요?
> `buildedFormData()`와 같은 메서드를 ItemRequestable이 가지고 있는건 어떨까요?
> > 제가 생각했던 목적은 delete를 할 때에 password만 필요한데, 이 때 다른 프로퍼티들을 입력하는 것을 생략하고 싶었습니다! 
> > buildedFormData는 세션이 만들어야 한다고만 생각하고 있었는데... 생각해보니 이름부터가 Requestable이니 자기가 직접 하면 훨씬 명료하고 직관적인 타입이 될 수 있겠네요.... 머리를 한 대 얻어맞은 거 같습니다.. 정말 감사합니다!!!
> 
> 예약어를 사용하지 말라는 말을 자주 들어서 <- 저는 이 맥락에서 말하는 예약어는 Swift 예약어라고 생각하고 있습니다.
> 따라서 get, patch, delete 등과 같은 HTTP 메서드 관련 prefix를 사용하고 있기도 하고요.
> 그리고 네이밍에서도 get, patch, delete만큼 직관적인 네이밍은 없다고 생각합니다:)
> > 😄 감사합니다~!!
> 
> POP를 적용해 구현해보셨네요🎉
> POP를 적용한 이유가 있을까요?(그냥 궁금한 점입니다:))
> > 저는 POP의 목적을 수평적 확장을 통해 값타입을 더 강력하게 사용할 수 있기 위함이라고 이해했는데요. 지금이 특히 그것을 사용할 수 있는 지점이라고 생각을 했습니다! 지금은 이것을 사용하는 곳이 한곳뿐이지만, 다른 곳에도 충분히 범용적으로 사용할 수 있는 내용이라고 생각하여 POP를 통해 적용을 해보았습니다!
>
> Session Struct에서 get/이외의 메서드에서 url이 생성되는 위치가 다른거 같아요.
> Get 메서드는 메서드 내부에서 `let path = HttpConfig.baseURL + HttpMethod.items.path`로 생성해주고,
> 이외의 메서드는 `buildedRequestWithFormDataAbout()`내부에서 생성해주고 있네요.
> 수박이 작성한 Session에 다른 사람이 getA(), postA() 메서드가 추가된다고 생각해볼게요.
> url을 메서드 내부에서 생성해줘야하는지 `buildedRequestWithFormDataAbout()`를 호출해 알아서 url을 만들어줄지 헷갈리지 않을까요?
> url을 생성할때 필요한 component들을 주입하면 url을 만들어주는 역할을 하나 더 두는건 어떨까요?
> > 전혀 생각해보지 못했던 지점인데요... 정말 타당한 말씀이신 거 같습니다. URL을 만들어주는 걸 전체적으로 훨씬 명료한 코드가 될 수 있을 거 같습니다. 아니면 저도 하나 생각이 난 건데 아예 URL을 통해 요청을 하는 것을 없애고 URLRequest를 통해서만 요청을 하는 건 별로일까요? 
> 
> itemList[x] <- 이게 보기에는 좀 더 직관적인거 같습니다.
> 다만 ItemList가 page라는 프로퍼티를 가지고 있기도 하고 이후에 ItemList에 다른 배열 프로퍼티가 추가된다면 어떻게 될까요?
> > 정말 난감한 상황이겠네요... subscript를 계속 사용한다면, 각각의 서브스크립트에 키값을 줘야할까요? 아니면 없애는 게 나을까요? 잘 모르겠습니다..
> 
> ### 테스트
> 
> [이 링크](https://www.swiftbysundell.com/articles/avoiding-force-unwrapping-in-swift-unit-tests/)가 도움이 될까요?
> > 강제 언래핑을 사용하지 않는게 오히려 더 테스트 코드를 확실히 신뢰할 수 있는, 특히 런타임에 에러가 발생하지 않는다는 지표가 될 수 있겠네요... 좋은 자료 공유해주셔서 감사합니다. 도움이 되었습니다!!
> 
> 테스트 가능한 통신에 관해서 고민하셨네요! 저도 해당 프로젝트를 진행할때 이 부분에서 많이 고민했던 경험이 있는데요;
> [이 게시물](https://medium.com/mobile-app-developers/testable-network-layer-in-swift-part-1-dd9aa4f31e0e) 확인해 보시면 좋을거 같아요!
> > 공유해주신 링크가 3편까지 있어서 모두 읽어보고, 어떻게 코드를 작성했는지도 확인을 해보았는데 3편의 코드에서 의문이 해결되었습니다!! 정말 감사합니다!!!!!!!!!!
> 
> Mock 객체가 어떤 프로토콜을 준수하지 않았던 걸까요?
> 그냥 body는 없이 extension으로 빼게 되었는데요 <- 이 부분에 대해서도 자세하게 듣고 싶어요😀
> > 처음에는 Http의 postItem, deleteItem, patchItem이 프로토콜 안에 있었는데, 이걸 제가 SessionMock에서 어떻게 구현을 해야할지 갈피를 못잡았습니다. 그래서 일단은 구현을 안하려고 했더니 SessionMock이 Http 프로토콜을 준수하지 않는 객체가 되어서... 어떻게 해야하나 생각하다가 Http의 해당 메소드들을 옵셔널하게 만들면 될 거라고 생각하여 메소드들에 optional이라는 키워드를 붙여보았습니다. 그런데 제 뜻대로 되질 않고 오류가 계속 나와서... 현재의 extension Http처럼 구현을 하게 되었습니다...
> 
> 네 괜찮을거 같습니다😀
> > 감사합니다!!!

2021-08-22 06:40 UTC, soo941226 commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +//        undesirableTest()
넵.. 완전히 사용을 안하지는 않는 게 테스트용 코드였습니다... 테스트 프로젝트를 새로 만들어서 내용을 반영한 뒤 삭제하도록 하겠습니다!!

2021-08-22 06:41 UTC, soo941226 commented on OpenMarket/Model/Item.swift
> +struct Item: Decodable {
말씀을 듣고 보니 굉장히 막연한 네이밍이였던 거 같습니다... 반성하기 되네요. 고민을 좀 해보겠습니다!

2021-08-22 06:43 UTC, soo941226 commented on OpenMarket/Model/ItemDetail.swift
> +struct ItemDetail: Decodable, Equatable {
ItemDetail은 원본 이미지 URL을 가지고 있고, Item은 썸네일 이미지 URL만 가지고 있습니다! 해당 프로퍼티를 옵셔널로 처리할까 싶었는데, 두 타입을 사용하는 뷰가 달라서 조금 더 명료한 코드를 작성하는 데에 도움이 되지 않을까 싶었습니다..!

2021-08-22 06:45 UTC, soo941226 commented on OpenMarket/Model/ItemList.swift
> +struct ItemList: Decodable {
이 부분도 위에서 말씀드린 것처럼 이름에 대해 고민을 더 해보겠습니다!

2021-08-22 06:46 UTC, soo941226 commented on OpenMarket/Network/Http.swift
> +}
질문 드렸던 내용 중 테스트 관련 3번 질문의 내용 때문입니다...

2021-08-22 06:47 UTC, soo941226 commented on OpenMarket/Network/HttpConfig.swift
> +    static let invailedPath = "AppError: current path is invailed"
헉... 중간까지는 사용을 했던 것 같은데, 리팩토링을 자꾸 하다가 캐치를 못한 거 같습니다... 지우도록 하겠습니다!

2021-08-22 06:48 UTC, soo941226 commented on OpenMarket/Network/HttpConfig.swift
> +    static let requestHeader = "multipart/form-data; boundary="
application/json도 들어갈 수 있습니다. 이것도 부적절한 이름인 것 가네요. 이름에 대해 고민을 조금 더 해보겠습니다...

2021-08-22 06:48 UTC, soo941226 commented on OpenMarket/Protocol/Coder.swift
> +protocol Coder {
아예 Decodable과 Encodable에 대해 extension으로 내용을 구현하는 게 나을까요?

2021-08-22 06:52 UTC, soo941226 commented on OpenMarket/Constants/String+Constants.swift
> +    static let blank = ""
이전 프로젝트들을 진행하면서, 문자열을 사용하는 경우에는 빈문자열이 자주 필요하게 되어서 일단은 추가를 했었는데 사용하지 않고 있는 걸 캐치를 못했네요... 정확한 건 아니지만, 추후에 patch, delete, post를 사용할 때 패스워드가 빈문자열인지 확인하는데 사용해볼 수는 있을 거 같습니다.. 지우는 게 나을까요?

2021-08-22 06:55 UTC, soo941226 commented on OpenMarket/Constants/String+Constants.swift
> +extension String {
앱 전반적으로 사용할 수 있는 상수의 경우에는 해당 타입의 확장을 통해 프로퍼티를 추가하는 게 좋은 경험으로 다가왔었습니다.  Int.zero처럼요! 말씀하시는 text가 String의 인스턴스라면, static으로 String 타입에 대해 추가한 것이기 때문에 이 프로퍼티는 안갖고 있지 않을까요?

2021-08-22 07:00 UTC, soo941226 commented on OpenMarket/Protocol/ErrorMessage.swift
> +}
파일의 이름처럼 초기의 목적은 Error프로토콜을 채택하는 ErrorMessage를 작성하는 것이었는데, 이게 어떤 구조체나 클래스로 되면, 이것을 사용하는 Coder.decode와 Coder.encode에서 항상 이 타입에만 의존해야하는 단점이 있을 수 있을 것 같았습니다
그래서 Error와 같은 역할을 갖고 있으면서도, 서버 API에서 정의된 error처럼 meesage라고 하는 프로퍼티를 사용하는 ErrorMessage라고 하는 프로토콜을 정의를 할 필요가 생기게 되었습니다.
다만 서버에서 message라고는 했지만, 앱에서도 반드시 그 네이밍을 따라갈 필요성은 없을 것이라는 짐작을 하게 되어 message가 될 수 있는, message라고 하는 스트링을 인자로 받는 프로토콜을 작성하게 되었습니다!

2021-08-22 07:02 UTC, soo941226 commented on OpenMarket/Protocol/ErrorMessage.swift
> +typealias ErrorMessage = Error & Messagable & Codable
생각을 해보니 실제로 사용할 때에는 Decodable만 필요하겠네요... 이 부분을 지적하신 게 맞을까요?

2021-08-22 07:03 UTC, soo941226 commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +    func undesirableTest(){
테스트 프로젝트에서 제가 테스트를 작성하기가 어려워서 실제 앱에서 테스트를 했던 내용입니다.. 😭

2021-08-22 07:05 UTC, soo941226 commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +            print("")
해당 컨텍스트에서 사용되는 다른 session 메소드들의 결과들을 쉽게 구분하고자 넣게 되었습니다...

2021-08-22 07:07 UTC, soo941226 commented on OpenMarket/Network/Session.swift
> +struct Session: Http, Coder {
어떤 부분에서 어색하다고 느끼셨는지 여쭤봐도 괜찮을까요? 그 부분을 알면 더 좋은 고민을 할 수 있을 거 같습니다!!

2021-08-22 13:27 UTC, wonhee009 commented on OpenMarket/Protocol/Coder.swift
> +protocol Coder {
이런식으로 파싱만 해주는 구조체는 어떤가요?
```swift
struct ParsingManager {
    static func decode<Model: Decodable>(
        from data: Data,
        to model: Model.Type) { ... }

    static func encode<Model: Encodable>(
        from data: Model) { ... }
}
```

2021-08-22 13:28 UTC, wonhee009 commented on OpenMarket/Constants/String+Constants.swift
> +    static let blank = ""
빈문자열인지 확인하는데에는 String.isEmpty로 확인할 수 있지 않을까요?🤔

2021-08-22 13:35 UTC, wonhee009 commented on OpenMarket/Constants/String+Constants.swift
> +extension String {
타입 프로퍼티였군요! 네 이 부분은 수박의 말씀대로 예시로 든 alert message text가 가지고 있지는 않겠네요.
`blank`, `newLine` 같은 부분은 String 타입과 관련된 부분이라고 생각할 수는 있을거 같긴 한데요. 
`parsingError`는 String 타입과 큰 관련은 없어 보이는데 수박의 의견이 궁금합니다😀

`blank`, `newLine`과 같은 부분도 formData를 만들어 주는 부분에서 사용하기 위해 정의한 것으로 보입니다.
따라서 이런 부분을 수박이 정의한 Session에서만 사용하는 부분이기에 Session의 내부에 정의하는건 어떤지 의견 드려봅니다.
현재는 String 타입에 정의되어 있어 앱 전반적으로 String.blank와 같은 방식으로 접근할 수 있는데요.
앱 전반적으로 필요한 부분이 아니니 필요한 부분의 내부에 정의하여 접근을 제한하는게 낫지 않나라는 생각이 들어서요.

2021-08-22 13:37 UTC, wonhee009 commented on OpenMarket/Protocol/ErrorMessage.swift
> +}
[해당 링크](https://developer.apple.com/documentation/foundation/localizederror)가 도움이 될까요?

2021-08-22 13:42 UTC, wonhee009 commented on OpenMarket/OpenMarket/Controller/ViewController.swift
> +            print("")
아하... 의미 없는 출력문을 앞으로 삭제 부탁드립니다!🙏

2021-08-22 13:50 UTC, wonhee009 commented on OpenMarket/Network/Session.swift
> +struct Session: Http, Coder {
Session과 Http 네이밍 모두 어색한거 같은데요.
[URLSession 문서](https://developer.apple.com/documentation/foundation/urlsession/)를 보면 
> An object that coordinates a group of related, network data transfer tasks.

라고 정의가 나와 있습니다.
이런 정의와는 Session이 하는 일이 좀 다르다고 느껴져서 Session이 어색한거 같습니다.
현재 수박이 정의한 Session은 URLSession보다는 그들을 매니징해주는? 그런 역할에 좀 더 가까운거 같아서요!

수박이 정의한 프로토콜인 Http도 같은 맥락에서 어색하다고 느껴졌는데요.
<img width="420" alt="image" src="https://user-images.githubusercontent.com/30456206/130357541-a41389d9-e0d6-41b3-bcd7-897beb7d1424.png">
위의 이미지처럼 사실상 저희가 사용하고 있는 HTTP는 서버/클라이언트 간의 약속 즉 프로토콜입니다.

이 부분 네이밍 개선이 필요한거로 느껴지는데요 수박은 어떠신가요?

2021-08-22 14:04 UTC, wonhee009 commented
> 제가 생각했던 목적은 delete를 할 때에 password만 필요한데, 이 때 다른 프로퍼티들을 입력하는 것을 생략하고 싶었습니다!

```swift
struct ItemRequestable: Loopable, Codable {
    private(set) var title: String? 
    private(set) var descriptions: String?
    private(set) var price: Int?
    private(set) var currency: String?
    private(set) var stock: Int?
    private(set) var discountedPrice: Int?
    
    let password: String

    init(title: String? = nil,
         descriptions: String? = nil,
         price: Int? = nil,
         currency: String? = nil,
         stock: Int? = nil,
         discountedPrice: Int? = nil,
         password: String) {
        self.title = title
        self.descriptions = descriptions
        self.currency = currency
        self.stock = stock
        self.discountedPrice = discountedPrice
        self.password = password
    }
}
```
이런 방식도 하나의 방법이 될 수 있을거 같아요!
수박이 작성하신 방식은 **초기값이 nil이고 이후에 값을 수정**해주는 느낌이 들었거든요.
위의 코드는 nil 혹은 입력한 값으로 프로퍼티를 초기화하는 느낌이라서 의견 드려봅니다!😀

> 아예 URL을 통해 요청을 하는 것을 없애고 URLRequest를 통해서만 요청을 하는 건 별로일까요?

이런 방식도 좋을거 같아요!👍

> subscript를 계속 사용한다면, 각각의 서브스크립트에 키값을 줘야할까요? 아니면 없애는 게 나을까요? 잘 모르겠습니다..

현재 프로젝트에서는 subscript를 사용해도 별 다른 문제가 없겠지만 예시와 같은 상황을 고려한다면 ItemList.items[indexPath.row] 이런식의 접근도 나쁘지 않다고 생각합니다.😀
(그래도 해당 프로젝트에서는 subscript를 살리고 가볼까요?)

> 테스트 4번 질문

이 부분은 위의 링크들로 Testable Network Layer로 구현하다보면 답을 찾을 수 있지 않을까 생각이 듭니다😀

2021-08-22 14:21 UTC, soo941226 commented on OpenMarket/Protocol/Coder.swift
> +protocol Coder {
오 아주 직관적인 거 같습니다. Code...로 시작하는 게 어떤게 있을까 생각하고 있었는데, 무슨 메소드를 가지고 있을지 이름에서부터 짐작할 수 있어서 훨씬 명료하네요..!

2021-08-22 14:22 UTC, soo941226 commented on OpenMarket/Constants/String+Constants.swift
> +    static let blank = ""
헉 그런 프로퍼티가 있는 줄 미처 몰랐습니다. 이걸로 충분히 역할을 할 수 있을 거 같습니다!! 감사합니다~~

2021-08-22 14:29 UTC, soo941226 commented on OpenMarket/Constants/String+Constants.swift
> +extension String {
일리가 있는 말씀이네요... parsingError는 실제로 parsing을 해주는 타입이 가지고 있는게 책임도 분명하고 읽기도 쉬울 거 같습니다..!
두번째 문단에서 말씀하신 부분도 납득이 되는 말씀이네요... 일단은 Session으로 옮겨놓은 뒤 추후에 다른 곳에서도 이러한 값을 사용할 일이 생긴다면 그때 String을 통해 확장해도 늦지 않을 거 같습니다!

2021-08-22 14:34 UTC, soo941226 commented on OpenMarket/Protocol/ErrorMessage.swift
> +}
이런 게 있었군요...... 초기 구현에 필요한 내용이 많이 디테일해서 선뜻 바꾸기가 조금 걱정스러운데 이 프로토콜이 제가 작성한 내용을 충분히 대신할 수 있을 거 같습니다! 한번 사용해보도록 하겠습니다!!

2021-08-22 14:44 UTC, soo941226 commented on OpenMarket/Network/Session.swift
> +struct Session: Http, Coder {
말씀을 듣고 보니 제가 정의를 정확히 모르고 이 둘을 사용한 것 같습니다. 문서를 다시 읽어보고 고민을 해보겠습니다... 쉽지 않네요..😅

2021-08-22 15:15 UTC, soo941226 commented
> 이런 방식도 하나의 방법이 될 수 있을거 같아요!
> 수박이 작성하신 방식은 **초기값이 nil이고 이후에 값을 수정**해주는 느낌이 들었거든요.
> 위의 코드는 nil 혹은 입력한 값으로 프로퍼티를 초기화하는 느낌이라서 의견 드려봅니다!😀
> > 말씀을 듣고 보니 init을 통해 처리를 하는 것이 불필요한 동작이 줄어들겠네요... 의견 감사합니다!!! 꼭 반영하겠습니다!
> 
> 이런 방식도 좋을거 같아요!👍
> > 감사합니다!! 😄
>
> 현재 프로젝트에서는 subscript를 사용해도 별 다른 문제가 없겠지만 예시와 같은 상황을 고려한다면 ItemList.items[indexPath.row] 이런식의 접근도 나쁘지 않다고 생각합니다.😀
> (그래도 해당 프로젝트에서는 subscript를 살리고 가볼까요?)
> > 넵..! 쉽지 않네요...
> > 테스트 4번 질문
> 
> 이 부분은 위의 링크들로 Testable Network Layer로 구현하다보면 답을 찾을 수 있지 않을까 생각이 듭니다😀
> > 감사합니다~~~!

2021-08-24 07:26 UTC, soo941226 commented
@wonhee009 

안녕하세요 라자냐~!!!! 먼저 바쁘신 와중에도 질문에 하나하나 정성껏 답변해주셔서 정말 감사합니다!!! 🙏
이번 PR은 라자냐의 피드백을 반영한 뒤, 제 고민을 더 얹어서 코드를 수정한 내용입니다.
주요 변경점과 왜 이렇게 했는지를 설명해보고자 합니다! 혹시 말씀하신 의도가 이런 의도가 아니었거나 미적지근하다고 생각되시면... 가차없이 지적을 해주시면 감사하겠습니다 ㅋㅋ

## 주요 변경점
### 1. NetworkTest
* 기존의 ViewController에서 테스트를 하던 내용을 모두 삭제한 뒤, 해당 프로젝트에서 테스트를 진행하도록 변경하였습니다!
* 라자냐의 피드백과 공유해주신 레퍼런스를 참고하여, XCTestExpectation을 활용하여 async한 내용들을 기다리도록 구현하였는데 괜찮은지 잘 모르겠습니다
* 그런데 Delete와 Patch의 경우, 타겟 ID가 필요한데... Patch는 그렇다치더라도 Delete의 경우 한번 삭제하면 다음 테스트에는 아이디를 바꿔줘야하는 필요성?이 생겨 어떻게 테스트를 해야할지 갈피를 잡지 못했습니다. 그러다가 이렇게 질문을 남기게 되었습니다..

### 2. AboutFormData.swift
* buildedFormData가 ItemRequestable에 있으면 좋겠다고 하신 내용을 조금 더 확장하여, Loopable을 채택한 프로토콜이 해당 메소드를 가지고 있게 하였고, 배열도 Element가 UIImage인 배열만 해당 메소드를 사용할 수 있게끔 확장하였습니다. 
* 처음에는 Loopable 파일에 이러한 내용을 집어넣고, Array를 extension한 파일을 만들어서 여기에 또 이러한 내용을 집어넣으려다가, 같은 파일에 정의하는 게 더 보기 좋을 것 같아 이렇게 해보았는데 괜찮게 보시는지 궁금합니다!

### 3. Http, Session
* Http는 프로젝트 명세서에서 정의한 서버API와 짝을 맞추면 더 읽기 쉬울 것 같아 ClientAPI로 명명하였고 Session은 URLSession의 정의와 라자냐가 피드백을 해주신 내용을 혼합하여 NetworkManger라는 이름으로 바꿔보았습니다!

### 4. Item, ItemList
* 라자냐의 말씀을 듣고 보니 Item은 너무 막연하다는 느낌이 들어, 좀 더 명료한 표현을 찾고 싶었으나 쉽지 않았습니다... 그래도 가격이나 갯수 등이 있다는 점을 생각하여 판매중인 상품을 영어로 작성하여 GoodsOnSale이라고 명명하였는데 괜찮게 읽히시는지 궁금합니다!
* ItemList는 GoodsOnSaleList 라고 명명하다가 너무 장황한듯하여, GoodsList라고 해도 충분히 의미가 전달이 될 것 같아 약간의 생략을 하였는데 괜찮을까요?

---
이상입니다!! 할 땐 힘들었는데 어느 정도 해결을 한듯하여 많이 뿌듯하네요. 지적 많이 해주시면 정말 감사하겠습니다~~

2021-08-24 09:49 UTC, wonhee009 reviewed
1. Delete에 대해서는 Mock으로 테스트하지 않을까 싶은데요! 이 부분은 저도 좀 더 알아볼게요.
2. 이 부분은 리뷰에 남겨놨습니다!

리뷰 내용을 스텝2에서 적용하고 싶다면 머지 요청하셔도 좋습니다!

2021-08-24 09:49 UTC, wonhee009 commented on OpenMarket/Model/GoodsOnSale.swift
> +struct GoodsOnSale: Decodable {
on sale은 세일중이라는 뜻인데요 판매중이라는 의미는 for sale입니다:)
GoodsForSale이라는 네이밍보단 Goods로 해도 상품으로 충분히 의미가 통용될거 같아요 어떻게 생각하실까요?

2021-08-24 09:49 UTC, wonhee009 commented on OpenMarket/Network/ClientAPI.swift
> +protocol ClientAPI {
`ClientAPI`를 프로토콜로 정의한 이유가 있을까요?
테스트를 제외하면 NetworkManager에서만 채택하고 있는거로 보이는데요.
`struct API{ ... }`는 어떨까요?

2021-08-24 09:49 UTC, wonhee009 commented on OpenMarket/Network/HttpConfig.swift
> +    static let unknownError = "Error: unknown error occured"
`HttpConfig`라는 이름을 봐서는 HTTP 통신을 할때 설정?과 같은 것들을 모아둔거 같은데요.
unknownError의 위치가 여기가 맞을까라는 의문이 생겼습니다.
이 부분은 `HttpError`에 있어도 되지 않을까요?

2021-08-24 09:49 UTC, wonhee009 commented on OpenMarket/Network/HttpMethod.swift
> +    case delete(id: String)
`associatedType`을 사용해보셨네요🎉

2021-08-24 09:49 UTC, wonhee009 commented on OpenMarket/Network/HttpMethod.swift
> +}
`HTTPMethod`란 무엇일까요? [해당 링크](https://developer.mozilla.org/ko/docs/Web/HTTP/Methods)에서 확인할 수 있는데요.
수박의 HttpMethod는 urlPath를 생성하는 역할도, HTTPMethod에 대한 역할도 가지고 있는거 같아요.
이를 좀 분리해보는건 어떨까요?

2021-08-24 09:49 UTC, wonhee009 commented on OpenMarket/Network/NetworkManager.swift
> +            return
request를 생성하는데 실패하면 바로 반환되고 있는데요. 에러를 반환하도록 할 수 있을까요?

2021-08-24 09:49 UTC, wonhee009 commented on OpenMarket/Network/NetworkManager.swift
> +    }
이 메서드의 역할이 무엇인가요?
파라미터의 `response`는 사용하지 않는거 같은데 작성하신 이유가 있을까요?

2021-08-24 09:49 UTC, wonhee009 commented on OpenMarket/Network/NetworkManager.swift
> +    private func buildedRequestWithFormDataAbout<Model>(
메서드 네이밍에 About은 조금 어색한거 같아요.

2021-08-24 09:49 UTC, wonhee009 commented on OpenMarket/Protocol/ErrorMessage.swift
> +}
흠.... 이런 프로토콜이 필요할까요?

```swift
enum HttpError: Error, LocalizedError {
    case unknowedError

    var errorDescription: String? {
        switch self {
        case .unknowedError:
            return "unknown"
        }
    }
}
```
이런식으로 Error를 작성하는건 어떻게 생각하시나요?

2021-08-24 09:49 UTC, wonhee009 commented on OpenMarket/Extension/AboutFormData.swift
> +//  AboutFormData.swift
가독성?을 위해서 시도해보신거 같아요.
그럼 나중에 수박의 후임이 와서 `buildedFormData()` 메서드를 찾고 싶다면 해당 파일의 명만 보고 잘 찾을 수 있을까요?

2021-08-24 10:15 UTC, soo941226 commented on OpenMarket/Model/GoodsOnSale.swift
> +struct GoodsOnSale: Decodable {
😅민망하네요... 제가 영어에 좀 약해서 프로젝트를 하면서 같이 공부하느라... Goods로 정정해놓겠습니다!! 불필요한 말인 거 같아요

2021-08-24 10:22 UTC, soo941226 commented on OpenMarket/Network/ClientAPI.swift
> +protocol ClientAPI {
가장 큰 목적은 네트워크를 사용하지 않은 모델의 사용가능성에 대한 테스트를 위해서였습니다! 이 테스트를 유지하기 위해서는 프로토콜인 게 좋지 을까요?
Client는 생략을 해도 되겠네요... 어차피 여기가 클라이언트니까...😅

2021-08-24 10:23 UTC, soo941226 commented on OpenMarket/Network/HttpConfig.swift
> +    static let unknownError = "Error: unknown error occured"
헉 전혀 생각해보지 못했던 부분입니다... 맞는 말씀인 거 같습니다 꼭 고쳐놓겠습니다!

2021-08-24 10:26 UTC, soo941226 commented on OpenMarket/Network/HttpMethod.swift
> +}
URL을 생성하는 부분은 API도 그 기능을 가지고 있어서 책임이 나뉘어져 있는 거 같네요... 각각의 부분들을 하나로 합쳐서 URL만 만들어주는 타입을 정의할 수도 있을 거 같습니다... 고민을 좀 더 해보겠습니다!

2021-08-24 10:28 UTC, soo941226 commented on OpenMarket/Network/NetworkManager.swift
> +            return
한번 해보겠습니다!!

2021-08-24 10:32 UTC, soo941226 commented on OpenMarket/Network/NetworkManager.swift
> +    }
각각의 요청 메소드에서 공통적으로 사용되는 부분을 하나의 메소드로 만들어보았습니다!
처음에는 URLResponse.statusCode? 이런 이름의 프로퍼티를 통해 결과의 상태코드를 확인하여 각각의 상태에 따라 분기를 해서 서로 다른 얼럿을 띄운다거나... 이런 생각을 했었는데 아직은 반영이 안된 상태입니다... 에러의 경우는 메시지라는 프로퍼티를 갖는 JSON으로 잘 던져줘서 사용할 필요가 없어보였습니다..!

2021-08-24 10:33 UTC, soo941226 commented on OpenMarket/Network/NetworkManager.swift
> +    private func buildedRequestWithFormDataAbout<Model>(
😅 조금 더 고민해서 수정을 해보겠습니다!!

2021-08-24 10:39 UTC, soo941226 commented on OpenMarket/Protocol/ErrorMessage.swift
> +}
서버에서 던져주는 에러 타입이 message라고 하는 프로퍼티를 가지고 있어서, parser에서  사용되는 에러가 이 메시지를 통해 초기화가 될 필요가 있다고 생각했습니다...
디코딩을 할 때 저러한 규격?을 따로 지키지 않아도 디코딩을 할 수 있는 방법이 있는 건가요?

2021-08-24 10:40 UTC, soo941226 commented on OpenMarket/Extension/AboutFormData.swift
> +//  AboutFormData.swift
파일 이름만 가지고서는 조금 헤맬 수도 있을 거 같습니다. 파일 이름도 메소드명과 일치시키는 게 나을까요?

2021-08-24 11:04 UTC, wonhee009 commented on OpenMarket/Extension/AboutFormData.swift
> +//  AboutFormData.swift
저는 개인적으로 Loopable 파일에서 extension으로 구현하고 Array에 관한 buildedFormData()는 ArrayExtension이라는 파일을 생성해서 놓는건 어떻게 생각하실까요?

2021-08-24 11:04 UTC, wonhee009 commented on OpenMarket/Network/NetworkManager.swift
> +    }
이정도 동작은 
```swift
guard let data = data else {
     return
}
```
정도로도 될거 같은데요.

2021-08-24 11:04 UTC, wonhee009 commented on OpenMarket/Protocol/ErrorMessage.swift
> +}
아하... 제가 이해한 부분이 수박과 조금 다른거 같은데요.
수박은 서버에서 던져주는 에러 메세지를 표현하고 싶었던걸까요?
제가 제안 드렸던 부분은 custom하게 에러를 정의하는 방법였습니다.

2021-08-24 11:29 UTC, soo941226 commented on OpenMarket/Network/NetworkManager.swift
> +    }
헉... 일단은 에러가 있으면 먼저 걸러주고 싶었는데 현시점에서는 별차이가 없었겠네요...

2021-08-24 11:30 UTC, soo941226 commented on OpenMarket/Protocol/ErrorMessage.swift
> +}
넵 맞습니다! 🤣 활자의 한계인 거 같네요ㅋㅋ 그러면 여기서 다시 Messagable이 괜찮았는지 여쭤봐도 괜찮을까요?

2021-08-24 11:34 UTC, soo941226 commented on OpenMarket/Network/NetworkManager.swift
> +    }
이렇게 되면 인자를 받을 필요도 없었겠군요... 추후에 인자가 정말로 필요할 때 확장을 하는 게 나을 거라는 말씀으로 이해해도 될까요?

2021-08-24 11:35 UTC, soo941226 commented on OpenMarket/Protocol/ErrorMessage.swift
> +}
```
protocol Messagable {
   init(meesage: String)
}

typealias ErrorMessage = Error & Messagable & Decodagble
```
이런 내용이었습니다!

2021-08-24 11:37 UTC, soo941226 commented on OpenMarket/Extension/AboutFormData.swift
> +//  AboutFormData.swift
그것도 좋은 거 같습니다! 각각의 타입을 읽으면서 명확한 책임을 가지고 있는 게 분명히 보일 거 같습니다! 라자냐의 말씀대로 해보겠습니다~

2021-08-25 12:41 UTC, wonhee009 commented on OpenMarket/Network/NetworkManager.swift
> +    }
네 추후 필요하면 만들어도 될거 같아요!

2021-08-25 13:00 UTC, wonhee009 commented on OpenMarket/Protocol/ErrorMessage.swift
> +}
`Decodagble`<- 오타 났어요(소근소근)
서버에서 내려주는 에러 메세지를 표현하는 경우는 본적이 없는거 같아서 조금 낯설었습니다!(제가 아직 쪼랩이라 그럴수도...)
보통은 에러 코드를 받아서 컨버팅해서 사용자에게 표시해주고 에러 메세지는 로그로 남긴다던지 했던거 같습니다!
이런 코드가 나쁘다는게 아니라 흠... Messagable보다는 ErrorMessagable...?이런식으로 좀 더 직관적인 네이밍이 좋을거 같아요!
이 부분은 저도 하나의 의견이기 때문에 나중에 수박의 의견을 들려주면 좋을거 같아요!

2021-08-25 13:00 UTC, wonhee009 commented
수박 스텝2에서 만나요👍

2021-08-25 13:00 UTC, merged