[Step1] Charlotte
yagom-academy/ios-open-market pull request #75
Opened 2021-09-06 14:05 UTC by yaewonLee

@lina0322 

안녕하세요 엘림 😊  늦은 스탭1 PR 을 보냅니다 ㅎㅎ 저번에 했던 부분을 복습하면서 작성하느라 조금 늦어졌네요..! 새로운 개념을 적용하기보다는 공부했던 부분을 더 확실히 제 것으로 만드는 게 낫겠다고 판단하여 저번 프로젝트와 전체적인 코드는 크게 달라진 점이 없는 것 같습니다 ㅎㅎ

## 해결 못한 점
1. swiftLint를 적용하고 싶었는데 swift.yml 파일에서 특정한 파일을 제외하고 적용시키는것이 계획대로 되지 않아서 아직 해결하지 못하였습니다.  다음 스탭부터 적용해보도록 하겠습니다!

## 궁금한 점
1. 코드를 작성하다 보니 APIManager 클래스의 메소드가 너무 많아지는 것 같아 분리해보려고 했으나 multipartform 부분에서 계속 에러가 발생하여 함수를 나누지 못하고 모두 집어넣게 되었습니다.. 이렇게 한 클래스 안에 메소드가 많은 것이 괜찮을까요? 
2. 유닛 테스트는 검증이 필요하다고 생각되는 부분을 작성해보았는데요! 제대로 검증이 되고 있는 것인지, 더 검증이 필요한 부분이 있을지 궁금합니다. 
3. 혼자 프로젝트를 진행하면서  커밋 단위를 어떻게 해야 할지가 가장 고민스러웠습니다. 기능의 목적에 따라 나누려고 해봤는데 신경 쓰지 못한 것 같네요 혼자 프로젝트를 진행할 때는 커밋 단위를 어떻게 나누는 게 가장 좋을지 궁금합니다.

잘 부탁드립니다 😀

2021-09-09 10:44 UTC, lina0322 requested changes
샬롯 반가워용~☺️
제가 리뷰를 조금 늦게했죠ㅠㅠ? 기다려줘서 정말 고마워요!!

전체적으로 함수들을 분리하고, 객체를 나누는데 신경을 많이 쓴거같아요!
제가 남긴 피드백 보면서 살짝만 보충하면 좋아질거같아요~

지금은 중복된 코드나, 안쓰는 파일들이 있어서
이런부분은 앞으로 좀 더 신경쓰면 좋을 것 같습니다!!😆

## 1. 코드를 작성하다 보니 APIManager 클래스의 메소드가 너무 많아지는 것 같아 분리해보려고 했으나 multipartform 부분에서 계속 에러가 발생하여 함수를 나누지 못하고 모두 집어넣게 되었습니다.. 이렇게 한 클래스 안에 메소드가 많은 것이 괜찮을까요?

클래스 안에 메소드가 적다는게 꼭 좋은것은 아니니까요! 불필요한 코드들만 좀 줄이면 더 좋을 것 같습니다. multipartform을 분리한다기보다는, URLRequest를 만드는 부분을 잘 나누어보면(?) 좋을거같아요!

## 2. 유닛 테스트는 검증이 필요하다고 생각되는 부분을 작성해보았는데요! 제대로 검증이 되고 있는 것인지, 더 검증이 필요한 부분이 있을지 궁금합니다.

XCTAssertEqual처럼 NotEqual을 사용한 실패하는 것도 작성해보면 어떨까요?! 

## 3. 혼자 프로젝트를 진행하면서 커밋 단위를 어떻게 해야 할지가 가장 고민스러웠습니다. 기능의 목적에 따라 나누려고 해봤는데 신경 쓰지 못한 것 같네요 혼자 프로젝트를 진행할 때는 커밋 단위를 어떻게 나누는 게 가장 좋을지 궁금합니다.

커밋을 자주하고 잘 하는것은 좋다고 생각합니다! 하지만 꼭 틀에 박혀서 할 필요는 없어요ㅎㅎ 
스스로 알아볼 수 있고, 만약에라도 다시 되돌릴 수 있도록 저장해두는 것이니까 지금도 좋아요.
(사실 조금만 더 작게 하면 좋을 것 같기도!)

이해가 안 가는 부분이 있다면, 디엠 주세용~!

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/API/APIManager.swift
> +}
baseUrl은 static let으로 하지 않은 이유가 있나요?
또 저희 스위프트 약어 컨벤션에 대해서 알아볼까요:)? baseUrl? baseURL?

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/API/APIManager.swift
> +class APIManager {
class로 선언한 이유는 무엇인가요?

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/API/APIManager.swift
> +    static let shared = APIManager()
오, shared라서 뭔가 싱글톤일것 같은데 그건 또 아니네요? 요렇게 만든 이유가 있을까요?

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/API/APIManager.swift
> +                completion(.failure(APIError.requestFailed))
여기서 `completion(.failure(.requestFailed))` 요렇게 표현이 가능할까요?

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/API/APIManager.swift
> +                completion(.failure(APIError.unknown))
이 에러가 `알 수 없는`에러인가요?

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/API/APIManager.swift
> +                }
fetchProductList에서 decode까지 하면, 너무 많은 일을 하게되는건 아닐까 고민스럽네요!

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/API/APIManager.swift
> +        task.resume()
fetchProductList랑 겹치는 부분이 많은데, 어떻게하면 좋을까욥?!

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/API/APIManager.swift
> +        return "Boundary-\(UUID().uuidString)"
위에서 선언한 `let boundary = "Boundary-\(UUID().uuidString)"`와는 어떤 차이가 있을까요??

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/API/CreateHTTPBody.swift
> +    }
APIManager에서 같은 코드를 본거같은데...?!

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/API/CreateHTTPBody.swift
> +}
이 코드는 어떤 작업을 하는지 자세히 설명해줄 수 있나요?😀

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/Controllers/ViewController.swift
> +//        }
사용하지 않는 코드는 어떻게 하는 것이 좋다아~?😆

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/API/APIManager.swift
> +                    print(error)
print 문이 보이네요..?👀

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/Extention+Data/Extension+Data.swift
> +}
오잉! 똑같은 코드가 또 있어여!

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/MockObject/MockURLSession.swift
> +    }
따로 설정하지 않았을때는 성공하도록 설정하면 어떨까요?!

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/MockObject/MockURLSessionDataTask.swift
> +}
override는 보통 super을 호출해야한다는데, 왜 여기는 호출하지 않아도 될까요?😀

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/Item.swift
> +
오잉? 이 파일은 무엇이죵!

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/Items.swift
> +struct Items: Codable {
codable은 무엇과 무엇이 합쳐진 프로토콜인가요?

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/MultipartForm/MultiPartForm.swift
> +typealias HTTPBodyParameter = [String : Any]
typealias💯

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/MultipartForm/MultiPartForm.swift
> +enum MultiPartForm: CustomStringConvertible {
흠.. 그러게요 이 MultiPartForm이라는 이름이 어색하네요. 어떤게 좋을까요..
이 안에 경우들을 다르게 배치할 수 있는 방법은 없을까용?

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/ProductListSearchModel.swift
> +    var registrationDate: Double?
image는 UIImage로, date는 Date타입으로 착각할 수 있겠어요!

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/RegistProductModel.swift
> +    let password: String
등록하는 모델을 따로 만들지 않고, 기존의 모델 하나로 하는 방법은 없을까요?ㅎㅎ

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarketTests/NetworkingTest.swift
> +    }
이것은..?!

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    func test_네트워킹하지않고fetchProductList함수호출에실패하면_error를throw한다() throws{
어떤곳에는 줄바꿈이 있고, 어떤곳에는 없네용~
3기분들 사이에 한글로 테스트 함수명 짓는게 유행인가용ㅎㅎㅋㅋ

2021-09-09 10:44 UTC, lina0322 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +        XCTAssertNoThrow(try decoder.decode(ProductListSearchModel.self, from: data))
XCTAssertNoThrow을 사용해보았네요! 좋습니다!!

2021-09-10 09:58 UTC, yaewonLee commented on OpenMarket/OpenMarket/API/APIManager.swift
> +}
찾아보니 약어로 시작하는 경우에 보통 시작하는 앞부분은 소문자로 표기하고 나머지는 대문자로 하는군요! 
baseURL 또한 static let 으로 지정해주는게 좋을 것 같아서 수정하였습니다 😀

2021-09-10 10:39 UTC, yaewonLee commented on OpenMarket/OpenMarket/API/APIManager.swift
> +class APIManager {
클래스는 참조메모리를 가르키지만 구조체는 값을 복사하기 때문에 싱글톤 객체가 함수만 모아 놓은 경우가 아니라면 웬만하면 class를 사용하는 것이 좋다고 공부해서 class로 선언하였습니다..!

2021-09-10 10:42 UTC, yaewonLee commented on OpenMarket/OpenMarket/API/APIManager.swift
> +    static let shared = APIManager()
뷰컨트롤러에서 싱글톤 패턴을 사용하여 데이터가 불러와지는지 테스트해보았는데요,  주석 처리 해놓아서 현재 코드에서는 사용되는 곳이 없는 것 같습니다. 스탭2에서 활용할 것 같습니다!

2021-09-10 10:43 UTC, yaewonLee commented on OpenMarket/OpenMarket/API/APIManager.swift
> +                completion(.failure(APIError.requestFailed))
넵 나머지 failure 컴플리션들도 수정하였습니다 :)

2021-09-10 10:45 UTC, yaewonLee commented on OpenMarket/OpenMarket/API/APIManager.swift
> +                completion(.failure(APIError.unknown))
네 invalidURL, emptyData, requestFailed 의 케이스가 아닌 나머지 경우의 에러를 unknown의 케이스로 처리해보았습니다..!

2021-09-10 12:45 UTC, yaewonLee commented on OpenMarket/OpenMarket/API/APIManager.swift
> +        return "Boundary-\(UUID().uuidString)"
엇 삭제했었는데 커밋할 때 파일을 잘못 올렸네요 수정했습니다!

2021-09-10 12:59 UTC, yaewonLee commented on OpenMarket/OpenMarket/API/CreateHTTPBody.swift
> +    }
이 파일도 커밋 실수로 잘못 올라갔네요..ㅎㅎ.. 다음부터 주의하겠습니다

2021-09-10 15:45 UTC, yaewonLee commented on OpenMarket/OpenMarket/API/APIManager.swift
> +                    print(error)
불필요한 프린트문은 수정하였습니다 !

2021-09-10 15:45 UTC, yaewonLee commented on OpenMarket/OpenMarket/Extention+Data/Extension+Data.swift
> +}
커밋 실수네요...😭

2021-09-10 15:48 UTC, yaewonLee commented on OpenMarket/OpenMarket/MockObject/MockURLSession.swift
> +    }
넵 괜찮은 것 같아요 수정하였습니다!

2021-09-11 13:38 UTC, yaewonLee commented on OpenMarket/OpenMarket/API/CreateHTTPBody.swift
> +}
멀티파트폼 데이터를 전송할 때 body 부분이 String 형식으로 작성되기 때문에 append 함수 내부에서 utf8형식으로 인코딩해주는 과정이 필요하기 때문에 그 작업을 하는 함수입니다!

2021-09-12 05:48 UTC, yaewonLee commented on OpenMarket/OpenMarket/MockObject/MockURLSessionDataTask.swift
> +}
super 클래스의 함수를 오버라이드 하는 것이 아니라서 호출하지 않아도 되는 것이라고 생각합니다!

2021-09-12 05:49 UTC, yaewonLee commented on OpenMarket/OpenMarket/Model/Items.swift
> +struct Items: Codable {
Decodable 과 Encodable이 합쳐진 프로토콜 입니다

2021-09-12 06:21 UTC, yaewonLee commented on OpenMarket/OpenMarket/Model/ProductListSearchModel.swift
> +    var registrationDate: Double?
각각 productImages 와 registrationTime으로 수정하였는데 둘 다 뭔가 어색하네요.. 더 괜찮은 변수명이 있을까요?

2021-09-12 06:29 UTC, yaewonLee commented on OpenMarket/OpenMarketTests/NetworkingTest.swift
> +    }
커밋실수로 올라간 파일이네요 😭

2021-09-12 06:57 UTC, yaewonLee commented on OpenMarket/OpenMarket/Model/RegistProductModel.swift
> +    let password: String
Items.swift 와 Item.swift 모델로 통일해 보았습니다

2021-09-12 07:18 UTC, yaewonLee commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +    func test_네트워킹하지않고fetchProductList함수호출에실패하면_error를throw한다() throws{
swiftLint 적용하여 전체적으로 수정해보았습니다 ㅎㅎ

2021-09-14 15:48 UTC, lina0322 commented on OpenMarket/OpenMarket/API/APIManager.swift
> +    static let shared = APIManager()
싱글톤이 정확하게 무엇일까요? 싱글톤이 되기위해서는 어떤 조건이 갖춰져야하는지 다시 공부해보면 좋을거같아요😊
(지금은 외부에서 인스턴스 생성이 가능하니까요!)

2021-09-14 15:48 UTC, lina0322 commented on OpenMarket/OpenMarket/API/APIManager.swift
> +                completion(.failure(APIError.unknown))
음... 저의 뜻은 response가 넘어오는데 잘못된 Response가 와서 요기서 실패한다고 생각했거든요ㅎㅎ
알 수 없다는건 정말 알 수 없는(?) 경우에 사용하는게 좋을거같아서 말씀드려보았습니당!

2021-09-14 15:48 UTC, lina0322 commented on OpenMarket/OpenMarket/API/APIManager.swift
> +                    print(error)
혹시 `debugPrint`와 `assert`를 알고있나욥?

2021-09-14 15:48 UTC, lina0322 commented on OpenMarket/OpenMarket/Model/Items.swift
> +struct Items: Codable {
혹시 해당 Item이 Encode할때도 필요한가요?!

2021-09-14 15:59 UTC, lina0322 approved these changes
샬롯~ 고생했어요!
다음 스텝에서 이번 피드백 반영하면서 진행해봅시다:)
이번에도 필요하면 디엠주세요~

2021-09-14 15:59 UTC, lina0322 commented on OpenMarket/OpenMarket/API/Extention+URLRequest.swift
> +//  Created by 이예원 on 2021/09/12.
샬롯 이름이 예뿌네여~🥰

2021-09-14 15:59 UTC, lina0322 commented on OpenMarket/OpenMarket/API/Extention+URLRequest.swift
> +}
오! 좋은 방법인거같아요👀

2021-09-14 15:59 UTC, lina0322 commented on OpenMarket/OpenMarket/API/Extention+URLRequest.swift
> +}
자 여기서! 왜 super.init이 아니라 self.init을 호출해야 했을까요!

2021-09-14 15:59 UTC, lina0322 commented on OpenMarket/OpenMarket/API/APIManager.swift
> +    func networking(request: URLRequest, completion: @escaping (Result<Data, APIError>) -> Void) {
크.. 많은 발전이 있었네요👍

2021-09-14 15:59 UTC, lina0322 commented on OpenMarket/OpenMarket/API/ParsingManager.swift
> +    func decode<T: Codable>(_ data: Data, to modelType: T.Type) throws -> T {
오! 제네릭을 사용하다니👏

2021-09-14 15:59 UTC, lina0322 commented on OpenMarket/OpenMarket/MockObject/MockURLSession.swift
> +        self.isRequestSuccess = true
호에에! 제가 의도한 것은 이것이 아니었답니다ㅠ..
제가 전달을 정확히 하지 못했나보군요!

```swift
init(isRequestSuccess: Bool = true){
        self.isRequestSuccess = isRequestSuccess
}
```
혹시 요건 어때보이나요?

2021-09-14 15:59 UTC, merged