오픈마켓 [STEP 1] 니콜라스, 호박
yagom-academy/ios-open-market pull request #80
Opened 2022-01-05 11:38 UTC by hoBahk

안녕하세요 라이언! @ryan-son 
@Kim-EunsooSilver

이번에 오픈마켓 프로젝트 코드 리뷰를 받게된 니콜라스, 호박입니다.
오픈마켓 STEP1 작성하여 PR 보내드립니다.
잘부탁드립니다! 🙏 

# 고민했던 점

- JSON 파싱관련한 객체 생성
    - 이번 프로젝트에서는 JSON관련 Encoding, Decoding이 빈번히 사용된다고 분석하였습니다. 중복적인 작업을 회피하기 위해 `JSONParser` 타입을 구현하였습니다.
- escaping 클로저 사용
    - `session.dataTask`메서드는 비동기 방식 이기 때문에 `escaping` 클로저를 사용하여 request를 하고 나서 response가 올 때까지 기다렸다가 response가 오면 해당 `escaping`클로저를 실행하도록 했습니다.

# 조언을 얻고 싶은부분

## ❓   step1 명세 분석
 - 아래 명세를 저희는 `제공된 Mock 데이터` 를 Asset파일에 import 시켜서 test를 진행했습니다.
        
> 제공된 Mock 데이터를 활용하여 모델이 ** 네트워크 통신의 결과 데이터(실제 네트워크 통신 아님 주의) **를 문제없이 표현하고 활용할 수 있는지 단위 테스트(Unit Test)를 수행합니다.
> 
- 서버 API 문서관련해서 지금 현재로서는 서버 API 문서에 기재된 `상품 등록`, `상품 수정`, `상품 삭제` 는 Request 관련된 상세한 정보가 없기에 구현하지 못했고 `GET`와 메서드 관련된 `상품 목록,` `상품 상세정보`를 구현하였습니다.
- 저희가 분석한 내용대로 구현하여 PR 전송을 합니다. 만일, 저희가 잘못 분석했다건나 부족한 부분이 있다면 조언 부탁드리도록 하겠습니다.
   
## ❓ URLSession 구현
- 이번 프로젝트를 진행하면서 URLSession을 처음 이용해보았습니다. 기능 구현 부분에 있어서는 문제 없이 구동은 되어지나, 저희가 올바르게 사용한건지에 대해서 궁금합니다. 
    또한, 소스 분리, 중복제거등 리팩터링에 대해서도 생각을 해보고 레퍼런스도 찾아보았는데, 어떤 방식이 좋은건지에 대해서 결론이 도출이 되지 않았습니다. 레퍼런스를 따라서 구현하는 것도 좋지만, 저희가 생각한 부분을 먼저 보여드리고 부족한 부분에 대해서 조언을 얻고 싶습니다.
    따끔한 조언 부탁드리겠습니다.

## ❓ 데이터를 가져오는 동안의 비동기 처리
- 아래 코드의 `productList` 메서드에서 네트워크 통신을 통해 데이터를 불러온 후 `ProductList` 타입을 반환하도록 구현 하였습니다.
    그런데 세마포어를 사용하지 않으면 URLSession을 통해 데이터를 가져오는 작업이 끝나기 전에 `productList` 를 반환하게 되어 반환값이 nil이 됩니다.
    
    그래서 이를 해결하기 위해 여러 시도를 해보았으나 해결하지 못하고 세마포어를 통해 문제를 해결하였으나,
    세마포어를 이렇게 사용하면 메인큐에서 사용이 되어 데이터를 가져오는 동안 UI가 멈추는 현상이 발생할 것으로 보입니다.
- UI가 멈추지 않도록 하고 데이터를 가져오는 동안 기다렸다가 값을 할당하고 리턴할 수 있는 방법이 어떤 것이 있을지 궁금합니다.🤔
    여러가지를 검색해 보았는데  메서드의 리턴타입을 `Void`로 하고 클로저 안에서 UI를 업데이트 해주는 방식(메인큐에 넣어서)을 많이 보았습니다. 그런데 저희는 현재 리턴타입을 `ProductList`로 하려고 여러 시도를 해보았으나 해결하지 못하였습니다.
    이런 상황에서 어떻게 구현하면 좋을지 라이언의 의견을 듣고 싶습니다!
    
    ```swift
    func productList(pageNumber: Int, itemsPerPage: Int) -> ProductList? {
        
    		//...
    
        URLSession.shared.dataTask(request) { response in
          switch response {
          case .success(let data):
            productList = JSONParser<ProductList>.decode(data: data)
          case .failure(_):
            productList = nil
          }
          semaphore.signal()
        }
        semaphore.wait()
        return productList
      }
    ```

2022-01-05 21:47 UTC, ryan-son requested changes
니콜라스, 호박, 요구사항 분석하시고, 네트워킹 공부에 구현까지 고생 많으셨습니다! 👏

거두절미하고 질문해주신 내용 답변드릴게요. 더 궁금하신 내용은 코드에 남긴 코멘트를 참고해주세요.

# 고민했던 점

> - JSON 파싱관련한 객체 생성
>   - 이번 프로젝트에서는 JSON관련 Encoding, Decoding이 빈번히 사용된다고 분석하였습니다. 중복적인 작업을 회피하기 위해 `JSONParser` 타입을 구현하였습니다.

중복 작업은 `JSONDecoder`의 `decode(_:from:)`가 에러를 던지는 메서드라 `try` 성공 여부를 옵셔널 처리하는 부분을 말씀하시는게 맞나요? 어떤 이점이 있었는지 궁금합니다~

> - escaping 클로저 사용
>   - `session.dataTask`메서드는 비동기 방식 이기 때문에 `escaping` 클로저를 사용하여 request를 하고 나서 response가 올 때까지 기다렸다가 response가 오면 해당 `escaping`클로저를 실행하도록 했습니다.

좋습니다! 👍 앞으로 escaping 클로저가 보이는 위치와 다른 시점에 실행되는 점에 유의해서 작업하시면 됩니다~ 인스턴스 프로퍼티를 이용할 경우에는 self를 강하게 캡처링하니 메모리 누수가 발생하지 않도록 유의하세요~

##  step1 명세 분석

> - 아래 명세를 저희는 `제공된 Mock 데이터` 를 Asset파일에 import 시켜서 test를 진행했습니다.

이제 네트워크 관련 타입을 테스트할 때도 네트워크 연결 여부와 관계 없이 해당 데이터를 이용하도록 구현해주시면 완벽하겠네요~! 해결이 어려운 부분이 있다면 저를 찾아주세요~

> > 제공된 Mock 데이터를 활용하여 모델이 ** 네트워크 통신의 결과 데이터(실제 네트워크 통신 아님 주의) **를 문제없이 표현하고 활용할 수 있는지 단위 테스트(Unit Test)를 수행합니다.
> 
> - 서버 API 문서관련해서 지금 현재로서는 서버 API 문서에 기재된 `상품 등록`, `상품 수정`, `상품 삭제` 는 Request 관련된 상세한 정보가 없기에 구현하지 못했고 `GET`와 메서드 관련된 `상품 목록,` `상품 상세정보`를 구현하였습니다.

네, 상세한 정보가 제공되면 구현하시고 테스트 해보시면 되겠습니다!

##  URLSession 구현

> - 이번 프로젝트를 진행하면서 URLSession을 처음 이용해보았습니다. 기능 구현 부분에 있어서는 문제 없이 구동은 되어지나, 저희가 올바르게 사용한건지에 대해서 궁금합니다. 

결과가 잘 도출된다면 올바르게 사용한 것입니다. 정답이 있다고 생각하지 않으셔도 돼요~
이번에는 `URLRequest` 인스턴스를 생성해서 요청해 보셨네요. 단순히 `URL` 인스턴스를 생성해서 `URLSessionDataTask`를 생성할 수 있는 메서드도 있으니 한 번 이용해보세요~

>   또한, 소스 분리, 중복제거등 리팩터링에 대해서도 생각을 해보고 레퍼런스도 찾아보았는데, 어떤 방식이 좋은건지에 대해서 결론이 도출이 되지 않았습니다. 레퍼런스를 따라서 구현하는 것도 좋지만, 저희가 생각한 부분을 먼저 보여드리고 부족한 부분에 대해서 조언을 얻고 싶습니다.
>   따끔한 조언 부탁드리겠습니다.

타입의 역할 분리와 리팩터링 관련해서는 코드에 코멘트를 달아두었으니 참고해주세요~ 더 보완하시고 싶으신 부분이 있으시면 공유해주시면 더 자세히 코멘트 남기도록 하겠습니다!

## 데이터를 가져오는 동안의 비동기 처리

> - 아래 코드의 `productList` 메서드에서 네트워크 통신을 통해 데이터를 불러온 후 `ProductList` 타입을 반환하도록 구현 하였습니다.
>   그런데 세마포어를 사용하지 않으면 URLSession을 통해 데이터를 가져오는 작업이 끝나기 전에 `productList` 를 반환하게 되어 반환값이 nil이 됩니다.

원인을 잘 도출하셨네요. 👍 그 시점에는 escaping closure가 실행되지 않아 반환값을 받을 수 없죠.

>   그래서 이를 해결하기 위해 여러 시도를 해보았으나 해결하지 못하고 세마포어를 통해 문제를 해결하였으나,
>   세마포어를 이렇게 사용하면 메인큐에서 사용이 되어 데이터를 가져오는 동안 UI가 멈추는 현상이 발생할 것으로 보입니다.

스레드를 유의해서 관리한다면 UI에 영향을 주지 않을 수 있겠지만 유의하지 않을 수 있는 환경을 만드는 것이 더 좋은 길일 수 있겠네요. 

> - UI가 멈추지 않도록 하고 데이터를 가져오는 동안 기다렸다가 값을 할당하고 리턴할 수 있는 방법이 어떤 것이 있을지 궁금합니다.🤔
>   여러가지를 검색해 보았는데  메서드의 리턴타입을 `Void`로 하고 클로저 안에서 UI를 업데이트 해주는 방식(메인큐에 넣어서)을 많이 보았습니다. 그런데 저희는 현재 리턴타입을 `ProductList`로 하려고 여러 시도를 해보았으나 해결하지 못하였습니다.

이미 해결 방법을 잘 알고 계시네요. 왜 메인 스레드로 전환해서 escaping closure로 전달할까요?
반환 타입을 `ProductList`로 만들어주려면 Swift 5.5 (iOS 15.0)에서 도입된 async-await을 사용하면 됩니다. WWDC21에 등장할만큼 신규 기술이라 추세를 보았을 때 2~3년 이후에 실제 프로덕트에 적용되겠지만 시간이 남으시면 미리 공부해보시는 것도 재미있으실거에요.

- [Concurrency - Swift Programming Language Guide](https://docs.swift.org/swift-book/LanguageGuide/Concurrency.html)
- [`data(for:delegate:)` - Apple Developer](https://developer.apple.com/documentation/foundation/urlsession/3767352-data)
- [Use async/await with URLSession - WWDC21](https://developer.apple.com/videos/play/wwdc2021/10095/)

모자라거나 궁금하신 부분 있으시면 언제든지 말씀해주세요~ 응원합니다! 💪

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarket.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 15.0;
테스트 타겟의 최소 OS 버전은 15.0인데, 프로젝트와 제품은 어땠나요?
프로젝트와 제품, 그리고 테스트 타겟의 최소 OS 버전이 다르면 빌드가 실패하거나 기본 내장 프레임워크에서 활용 가능한 메서드의 범위가 달라 성가신 일이 발생할 수 있을 것 같다는 생각이 들어요~

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
> +//  Created by 박병호 on 2022/01/04.
번갈아가며 파일 생성한 흔적들을 보니 번갈아가며 작업하신 페어프로그래밍의 흔적이 보이네요! 👍

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
> +  func productList(pageNumber: Int, itemsPerPage: Int) -> ProductList? {
본문에서 질문해주셨듯이 `ProductList?` 타입으로 반환할 수 있는가의 여부는 코멘트로 따로 다루겠습니다~

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
> +                        "/api/products?page-no=\(pageNumber)&items-per-page=\(itemsPerPage)") else {
URL이 base + path + query로 복잡하게 구성되어 있네요. 때에 따라 쿼리에 넣어주어야 하는 정보도 달라지고요. URL 생성을 담당하는 `무언가`가 있으면 좋겠어요. 
1. [`URLComponents`](https://developer.apple.com/documentation/foundation/urlcomponents)와 해당 타입의 [`path`](https://developer.apple.com/documentation/foundation/urlcomponents/1780144-path), [`queryItems`](https://developer.apple.com/documentation/foundation/urlcomponents/1779966-queryitems)를 살펴보는게 좋은 시작이 되겠네요.
2. `무언가`는 어떤 형태로 구성하면 좋을까요? (같은 타입 안의 메서드?, 전용 타입 내 메서드?, 인스턴스 or 타입 메서드) 정답은 없습니다. 길을 만들어 나가봅시다~

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
> +    var request = URLRequest(url: url, timeoutInterval: Double.infinity)
`timeoutInterval`을 무한하게 해두신 이유가 있나요? 저는 적절한 시간 안에 요청이 성공하지 않으면 실패하는 것도 합리적인 방안이라고 생각하는데, 여러분의 생각이 궁금합니다~ 그리고, `URLRequest`는 별도로 이 값을 설정하지 않아도 인스턴스를 생성할 수 있는데, 이런 경우에는 `timeoutInterval`이 얼마였나요?

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
> +    request.httpMethod = "GET"
GET 메서드 요청을 여러 메서드에서 생성할 경우에 언젠간 오타로 인해 실수할 수도 있어보이네요. 기능을 구현하는 위치에서 최대한 string literal 값을 적게 사용하는 방향으로 구현해보는건 어떨까요?

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
> +    URLSession.shared.dataTask(request) { response in
이 메서드는 내부에서 자체적으로 생성한 default session을 이용하고 있어 `shared`를 이용할 소요는 없어 보이네요. 
1. 시간이 부족해서 바로 수정해서 결과물을 내야한다면, 최대한 오해를 피할 수 있게 `URLSession.dataTask(request)`와 같은 방식으로 사용할 수 있는 방법이 있을지 생각해 볼 것 같아요. 방법이 있을까요?
2. 조금 더 시간이 있다면 원하는 session을 사용하여 task를 생성하는 방법이 있으면 더 좋겠네요! 테스트할 때도 더 편할거예요.
3. 메서드 이름으로 인해 이 메서드가 [`URLSessionDataTask`](https://developer.apple.com/documentation/foundation/urlsessiondatatask/)를 반환할 것으로 예상할 수 있을 것 같아요.
4. 이 메서드 내부에서 생성된 task를 취소하고 싶을 때는 어떻게 해야하나요? 인터페이스가 사용자에게 제공되면 좋겠어요.
5. 싱글턴 인스턴스로 제공되는 shared의 한계는 어디까지일까요? 한계를 명확히 해두면 어느 범위까지 shared를 활용할 수 있고, 어떤 경우에 커스텀 세션을 생성하여 사용할지 판단할 수 있을 것 같아요.

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
> +        productList = nil
디코딩에 실패할 경우에도 nil을 반환할 수 있는 여지가 있네요. 이 메서드를 이용해서 completion을 통해 실패한 반환값을 받았을 때 어떤 이유로 실패하였는지 정확히 알려줄 수 있는 수단이 있으면 좋겠어요.

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
> +    semaphore.wait()
본문 코멘트에서 자세히 다루겠지만, 여러분께서 `URLSession+Extension`을 작성하셨던 내용을 잘 살펴보시면 방향이 보일거에요. `dataTask(with:completionHandler:)` 메서드를 사용할 때 컴플리션 핸들러를 통해 전달 받은 응답을 이용하는 쪽에서 받아볼 수 있도록 어떻게 해주었나요?

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
> +  func DetailProduct(productId: Int) -> Product? {
대문자 발견~

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
> +        dump(product)
로그를 남기는 용도가 아니라 단순히 테스트를 위한 것이라면 제거할 수 있을까요?

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarket/JSONParser.swift
> +enum JSONParser<Element: Codable> {
이름이 참 세련됐어요. 제 취향입니다..! 👍 이 타입을 열거형으로 작성한 이유는 무엇인가요~?

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarket/JSONParser.swift
> +    let decodedData = try? JSONDecoder().decode(Element.self, from: data)
`try?`로 인해 `decode(_:from:)` 메서드가 실패할 때 기본적으로 제공되는 실패의 원인을 제공받지 못할 것 같아요. 사용자들이 `nil`보다 정확한 실패의 원인을 알 수 있도록 도와준다면 문제가 생겼을 때 디버깅이 훨씬 편리해지지 않을까요~?
에러 처리는 크게 아래와 같이 세 가지가 있는데, 상황과 취향에 따라 취사선택 하시면 되겠습니다~
1. nil 반환
2. Error handling (try-catch)
3. Result 타입 활용

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarket/JSONParser.swift
> +    let encodedData = try? JSONEncoder().encode(data)
`JSONDecoder`, `JSONEncoder`는 Thread-safe할까요? 직접 Swift Foundation 프레임워크 코드를 보면서 알아봅시다~
- https://github.com/apple/swift-corelibs-foundation/blob/main/Sources/Foundation/JSONDecoder.swift
- https://github.com/apple/swift-corelibs-foundation/blob/main/Sources/Foundation/JSONSerialization%2BParser.swift

만약 그렇다면 공용 인스턴스를 만들어 사용할 수도 있겠네요. 인스턴스 생성 비용이 작은 경우에는 취향이라고도 할 수 있지만, `DateFormatter` 같은 경우에는 인스턴스 생성 비용이 커서 공용 인스턴스를 만들어 사용하는 경우가 있어요.
- https://sarunw.com/posts/how-expensive-is-dateformatter/

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarket/Model/ProductList.swift
> +  }
간단히 camelCase와 snake_case를 오가는거라면 `CodingKey` 프로토콜을 활용하지 않고 `JSONDecoder`, `JSONEncoder`의 [`keyDecodingStrategy`](https://developer.apple.com/documentation/foundation/jsondecoder/2949119-keydecodingstrategy/), [`keyEncodingStrategy`](https://developer.apple.com/documentation/foundation/jsonencoder/2949141-keyencodingstrategy/)로 해결할 수 있어요. 하지만 여기에서는 명백히 네이밍이 다른 프로퍼티가 있어 활용이 제한되겠네요.

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarket/Model/Vendor.swift
> +  let secret: String?
이름만으로는 이 프로퍼티가 어떤 역할을 하는지 알기 쉽지 않네요. 문서화 주석으로 한마디 적어둔다면 새로 합류하는 개발자가 이 내용을 볼 때 API 문서를 찾아보지 않더라도 쉽게 파악할 수 있을 것 같아요.

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarket/URLSession+Extension.swift
> +  func dataTask(_ request: URLRequest, completion: @escaping (Result<Data, NetworkError>) -> ()) {
문법이 허용하는 한도 안에서 어떤 방식으로 작성할지는 온전히 개발자 개인 취향 또는 팀의 합의를 통해 정하면 됩니다. 지금은 많은 개발자들이 사용하는 방식을 먼저 공부해둔다면 향후에 유연하게 적용할 수 있을거라고 생각합니다~!
- [Types with Shorthand Names - Google Swift Style Guide](https://google.github.io/swift/#types-with-shorthand-names)
- [Function Declarations - Raywenderlich Swift Style Guide](https://github.com/raywenderlich/swift-style-guide#function-declarations)

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarket/URLSession+Extension.swift
> +    }.resume()
여기서는 이 메서드를 사용하는 대상에게 어떤 방식을 사용해서 결과를 보내주고 있나요? `productList(pageNumber:itemsPerPage:)` 메서드에도 이 방식을 통해 데이터를 전달해주면 되겠네요!

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarketTests/APIManagerTests.swift
> +    let apiManager = APIManager()
이렇게 반복적으로 사용되는 인스턴스의 경우에 각 테스트케이스가 시작하기 전후로 초기화하고 할당해제를 해줄 수 있다고 하더라구요. 기본 템플릿이 남아있는 `OpenMarketTests.swift` 파일을 살펴보면 찾을 수 있을 것 같아요.

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarketTests/APIManagerTests.swift
> +    let itemList = apiManager.productList(pageNumber: 1, itemsPerPage: 10)
`productList(pageNumber:itemsPerPage:)` 메서드는 내부적으로 실제로 네트워킹을 수행하는 세션(`URLSession.shared`)을 이용하고 있어 네트워크 연결이 되지 않은 경우에는 테스트에 실패할 것 같아요. 
`APIManager`가 객체지향설계 5대 원칙인 SOLID 중 하나인 Dependency Inversion Principle (의존성 역전 원칙)을 지킬 수 있도록 설계하면 이 문제를 해결할 수 있을 것 같아요.

PR을 일찍 보내셨으니 위의 내용을 충분히 고민해 보시면서 APIManager를 다시 설계해보시고, 막히신다면 아래 내용을 참고해보세요~
1. 핵심은 실제 네트워킹 프로토콜에 따라 네트워킹을 수행하는 `URLSession.shared` 혹은 커스텀 세션을 이용하지 않고 상황에 따라 원하는 세션으로 네트워크 요청 작업을 생성할 수 있게 만드는 것입니다.
2. 실제 네트워킹을 수행하지 않도록 만드는 방법은 크게 두 가지 방법이 있습니다.
  - 프로토콜 타입을 통해 테스트하기를 원하는 메서드 인터페이스를 추상화하고, 테스트를 위한 타입을 만들고 실제 타입과 테스트를 위한 타입이 해당 프로토콜을 준수하도록 만듦. 이후 테스트를 위한 타입에서는 입력에 대해 원하는 결과가 나오도록 구현부를 조작.
  - `URLSession`의 네트워킹 프로토콜을 네트워크 연결 여부에 의존하지 않도록 커스텀 프로토콜을 구현하여 교체

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarketTests/APIManagerTests.swift
> +    XCTAssertNotNil(result)
- 이미 옵셔널 바인딩 구문을 통과한 상태라 이 구문은 실행될 일이 없어보여요.
- 네트워크 연결 여부와 무관한 테스트를 수행하게 되면 asset 패키지에 넣어두신 json 파일을 활용하시면 되겠네요. 그 때는 nil 여부 이외에도 여러가지 단언문(assert)을 작성해보시는 것을 권합니다~ 예를들어 파라미터에 요청한대로 결과물이 10개가 나오는지 같은 것들을 확인해보면 좋겠네요.

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarketTests/JSONTests.swift
> +    guard let asset = NSDataAsset.init(name: "products") else {
여긴 인스턴스를 `.init`을 통해 수행하셨네요. 스타일은 통일하는 것이 좋을 것 같아요.
1. asset 패키지에 넣어두신 것을 사용하신다면 이 곳의 String literal이 잘못되지 않도록 어딘가에 문자열을 보관해두고 불러다 사용하는 것이 좋아보여요.
2. json 파일 내부의 내용을 문자열이나 데이터 형태로 swift 확장자 파일로 옮겨서 변수로 선언해두고 사용하는 것도 한 가지 방법이겠네요.

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarketTests/APIManagerTests.swift
> +      XCTFail()
테스트가 실패한 이유를 알려주시면 더 좋겠어요~

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarketTests/APIManagerTests.swift
> +    XCTAssertEqual(result.id, 16)
APIManager가 다시 작성되면 다른 내용도 검증해봅시다~

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarketTests/JSONTests.swift
> +    XCTAssertEqual(result.pageNumber, 1)
파싱이 정상적으로 이루어지면 당연히 페이지 번호도 존재하겠지만, 파싱 성공 여부를 현재 페이지 번호가 1 번이냐는 것으로 결정하기에는 논리가 약해보이네요. 오히려 옵셔널 바인딩을 통해 옵셔널을 벗겨내지 않고 result가 nil이 아니라는 내용이 테스트의 통과 조건으로 하는건 어때보이시나요?

2022-01-05 21:47 UTC, ryan-son commented on OpenMarket/OpenMarketTests/JSONTests.swift
> +  }
잘못된 제네릭 정보를 작성한 경우 이외에도 디코딩 메서드가 nil을 반환하는 경우가 있어보여요. 어떤 에러인지 파악할 수 있도록 내용을 제공해주고 알맞은 에러 내용을 반환하거나 던지는지 유닛테스트에서 확인해보면 더 명확한 정보를 주는지 검증할 수 있을 것 같아요.

2022-01-06 05:55 UTC, hoBahk commented on OpenMarket/OpenMarket.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 15.0;
테스트 타겟의 버전과 다르군요..!
모두 13.2버전으로 맞추었습니다!

2022-01-06 08:03 UTC, Kim-EunsooSilver commented on OpenMarket/OpenMarket/APIManager.swift
> +    var request = URLRequest(url: url, timeoutInterval: Double.infinity)
아! 넵!!!
라이언 의견주신거에 동의 합니다.
이에 저희는 기본 derault로 설정해줬습니다.

질문 주신부분에 대해 찾아 보았는데 default는 60초라고 하네요!

2022-01-06 08:04 UTC, hoBahk commented on OpenMarket/OpenMarket/APIManager.swift
> +                        "/api/products?page-no=\(pageNumber)&items-per-page=\(itemsPerPage)") else {
`URLGenerator` enum 타입을 만들고 `URLComponents`를 사용하여 변경해보았습니다!

2022-01-06 08:23 UTC, hoBahk commented on OpenMarket/OpenMarket/APIManager.swift
> +    request.httpMethod = "GET"
`HttpMethod`열거형 타입에 `static`을 사용하여 문자열 관리를 할 수 있도록 했습니다!

2022-01-07 00:24 UTC, hoBahk commented on OpenMarket/OpenMarket/APIManager.swift
> +        productList = nil
Result 타입을 활용하여  디코딩에 실패할 경우, 실패한 반환값을 받은 경우에 대해서 오류처리 하였습니다.

2022-01-07 00:40 UTC, Kim-EunsooSilver commented on OpenMarket/OpenMarket/APIManager.swift
> +    semaphore.wait()
컴플리션 핸들러를 활용하여 `Result`를 반환하도록 수정하였습니다.

2022-01-07 00:41 UTC, Kim-EunsooSilver commented on OpenMarket/OpenMarket/APIManager.swift
> +  func DetailProduct(productId: Int) -> Product? {
수정했습니다~~

2022-01-07 00:42 UTC, Kim-EunsooSilver commented on OpenMarket/OpenMarket/APIManager.swift
> +        dump(product)
제거 했습니다~~

2022-01-07 00:48 UTC, hoBahk commented on OpenMarket/OpenMarket/JSONParser.swift
> +enum JSONParser<Element: Codable> {
static을 통해 타입 메서드를 사용하려고 의도한 것이어서 인스턴스 생성을 방지하도록 하기 위함입니다!

2022-01-07 01:39 UTC, hoBahk commented on OpenMarket/OpenMarket/JSONParser.swift
> +    let decodedData = try? JSONDecoder().decode(Element.self, from: data)
JSONParser에서 Result타입을 반환하도록 하여 오류처리 하도록 했습니다!!

2022-01-07 01:46 UTC, Kim-EunsooSilver commented on OpenMarket/OpenMarket/Model/ProductList.swift
> +  }
맞습니다 라이언~!!
`keyDecodingStrategy`, `keyEncodingStrategy`를 사용할까 생각해 보았지만 카멜 케이스 외에 네이밍이 다른 프로퍼티가 있어서 `CodingKeys`를 활용했습니다!!!

2022-01-07 02:17 UTC, Kim-EunsooSilver commented on OpenMarket/OpenMarket/Model/Vendor.swift
> +  let secret: String?
라이언 말씀대로 새로운 개발자가 API 문서를 찾아 보지 않게끔 관련 모델 타입에 문서화 주석 처리를 해주었습니다.

주석 처리를 진행하면서 API 문서를 다시 찾아보니 `Product`타입의 `vendors`라는 프로퍼티는 어울리지 않는 복수형이기에  `vendor`로 변경해주었습니다.

2022-01-07 02:41 UTC, hoBahk commented on OpenMarket/OpenMarket/URLSession+Extension.swift
> +  func dataTask(_ request: URLRequest, completion: @escaping (Result<Data, NetworkError>) -> ()) {
아래와 같이 변경해보았습니다.
```swift
func dataTask(
    _ request: URLRequest,
    completion: @escaping (Result<Data, NetworkError>) -> ()
  ) -> URLSessionDataTask {
```

2022-01-07 02:43 UTC, hoBahk commented on OpenMarket/OpenMarket/URLSession+Extension.swift
> +    }.resume()
complition을 통해 Result타입으로 데이터를 전달해주도록 변경하였습니다~!!

2022-01-07 03:50 UTC, Kim-EunsooSilver commented on OpenMarket/OpenMarketTests/APIManagerTests.swift
> +    let apiManager = APIManager()
넵 참고 해서 `setUpWithError`, `tearDownWithError`를 활용해 보았습니다.

2022-01-07 03:53 UTC, hoBahk commented on OpenMarket/OpenMarketTests/APIManagerTests.swift
> +    let itemList = apiManager.productList(pageNumber: 1, itemsPerPage: 10)
`URLProtocol`을 커스텀 하여 네트워크 연결에 의존하지 않도록 하였습니다. 
그리고 테스트에서 커스텀한 URLSession을 사용하였습니다.!

2022-01-07 04:26 UTC, hoBahk commented on OpenMarket/OpenMarketTests/APIManagerTests.swift
> +    XCTAssertNotNil(result)
아래와 같이 두가지의 assert를 작성하여 테스트 해보았습니다!
```swift 
switch result {
      case .success(let data):
        XCTAssertEqual(5, data.pages.count)
        XCTAssertEqual(1, data.pageNumber)
      case .failure:
        XCTFail()
      }
```

2022-01-07 04:26 UTC, Kim-EunsooSilver commented on OpenMarket/OpenMarketTests/JSONTests.swift
> +  }
JSONParser 의 리턴을 `Result`타입으로 변경해주었습니다. 
이를 이용하여 JSONParser에서 디코딩을 실패했을 경우에 대해 좀 더 명확하게 검증이 가능하도록 수정하였습니다.

2022-01-07 04:27 UTC, Kim-EunsooSilver commented on OpenMarket/OpenMarketTests/JSONTests.swift
> +    XCTAssertEqual(result.pageNumber, 1)
`XCTAssertNotNil`메서드를 이용하여 수정하였습니다.

2022-01-07 04:30 UTC, Kim-EunsooSilver commented on OpenMarket/OpenMarketTests/JSONTests.swift
> +    guard let asset = NSDataAsset.init(name: "products") else {
코멘트 달아주셨던 .init 관련해서는 스타일 통일을 위해 서정했습니다.

asset 관련해서는 테스트에서만 사용이 가능하도록 namespace를 이용하여 처리 하였습니다.

2022-01-07 04:33 UTC, hoBahk commented on OpenMarket/OpenMarketTests/JSONTests.swift
> +    XCTAssertEqual(result.pageNumber, 1)
`XCTAssertNotNil` 를 사용하여 nil이 아니면 테스트를 통과할 수 있도록 했습니다.

2022-01-07 04:35 UTC, hoBahk commented on OpenMarket/OpenMarket/APIManager.swift
> +  func productList(pageNumber: Int, itemsPerPage: Int) -> ProductList? {
complition Handler를 통해 Result 타입을 사용할 수 있도록 하여 변경하였습니다.

2022-01-07 04:59 UTC, Kim-EunsooSilver commented on OpenMarket/OpenMarket/APIManager.swift
> +    URLSession.shared.dataTask(request) { response in
전일 디스코드 회의실에서 큰 도움을 주셔서 감사합니다.

2022-01-07 05:34 UTC, Kim-EunsooSilver commented on OpenMarket/OpenMarket/JSONParser.swift
> +    let encodedData = try? JSONEncoder().encode(data)
첨부해주신 웹 페이지를 보니 Thread-safe 하다는 것을 알게 되었습니다.
그리고 3번째 첨부 문서를 보고 동일한 작업이 반복되고, 만약 그 작업이 새로운 인스턴스에 대해서 생성 - 소멸을 한다면 비용이 발생한다는 것을 알게되었습니다.

이에 해당 타입을 enum에서 class로 변경을 하고 싱글턴으로 구현하였습니다.

2022-01-09 08:49 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
> +    request.httpMethod = "GET"
열거형 타입에 타입 프로퍼티로 선언하신 이유는 무엇인가요? 클래스와 구조체에서도 타입 프로퍼티 선언이 가능하고, 열거형의 케이스+rawValue 조합으로도 선언할 수 있었을텐데 고민의 과정이 궁금합니다~

2022-01-09 08:54 UTC, ryan-son commented on OpenMarket/OpenMarket/JSONParser.swift
> +    let encodedData = try? JSONEncoder().encode(data)
커뮤니티에서는 `JSONEncoder`, `JSONDecoder`의 생성 비용이 크지 않다는 의견도 있어 취향의 영역이라고 볼 수도 있다고 판단됩니다. 하지만 인스턴스 생성 비용과 기존 열거형 타입이 어떤 관계가 있었나요? 싱글턴으로 구현하게 된 고민의 과정이 궁금하네요~

2022-01-09 08:58 UTC, ryan-son commented on OpenMarket/OpenMarket/URLSession+Extension.swift
> +  func dataTask(_ request: URLRequest, completion: @escaping (Result<Data, NetworkError>) -> ()) {
선언부가 길어질 때 해당 방법도 선호되는 방법이지만 저는 컴플리션 타입 선언 방식에 대해 이야기하려고 했었어요~

![image](https://user-images.githubusercontent.com/69730931/148675775-dbecef45-3c65-459d-9cc8-c0f29a81030d.png)

클로저 타입 선언에서 매개변수(input)이 없을 때는 `(Void)`보다 `()`을 선호하고, 반환타입이 없을 경우 `()`보다 `Void`를 선호한다는 내용입니다~ `(Result<Data, NetworkError>) -> Void`

2022-01-09 19:41 UTC, ryan-son approved these changes
호박, 니콜라스, 주말은 잘 쉬셨나요? 😊
단기간에 많은 것을 공부하시고 적용해 보셨네요! 작성하신 내용에서 크게 성장하셨다는 느낌을 받았어요. 
STEP 1에서 요구한 내용을 훌륭하게 수행하셨다고 판단하여 머지합니다!
이야깃거리가 더 있는 내용은 코멘트에 댓글 또는 신규 코멘트를 달았으니 고려해보시고 적합하다고 판단되시면 다음 스텝에서 반영해보세요~
고생 많으셨습니다! 즐거운 한 주의 시작이 되길! 😊💪

2022-01-09 19:41 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
>    let semaphore = DispatchSemaphore(value: 0)
사용하지 않는 프로퍼티는 혼선을 방지하기 위해서 없애는 것도 좋겠어요~

2022-01-09 19:41 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
> +  let urlSession: URLSession
외부에 드러나지 않아도 괜찮은 요소는 접근을 제어해보는건 어떨까요?

2022-01-09 19:41 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
> +        itemsPerPage: "\(itemsPerPage)")
사용하는 쪽을 더 고려해서 이 매개변수의 타입을 정수형으로 설정해두는 것도 나쁘지 않을 것 같아요~

2022-01-09 19:41 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
> +      request.httpMethod = HttpMethod.get
앞으로도 반복적으로 URLRequest 인스턴스를 생성하고 메서드를 지정해주는 반복적인 작업이 일어날 것으로 예상되는데, 생성할 때부터 메서드를 지정해줄 수 있는 수단을 만들어보는건 어떨까요?

2022-01-09 19:41 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
> +    complition: @escaping (Result<ProductList, ResponseError>) -> Void
오타가 났네요~ 아래 캡처와 같이 속성을 켜두시면 오탈자가 발생했을 때 밑줄으로 알려주니 필요하시다면 활용해보세요~

![image](https://user-images.githubusercontent.com/69730931/148696813-e78c69c2-c036-4391-b746-e480b38b7498.png)

![image](https://user-images.githubusercontent.com/69730931/148696869-d82810a5-c809-47a9-b899-599952314520.png)

2022-01-09 19:41 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
> +            print(error)
이 실패 케이스에 대해서도 completion으로 에러 상황을 반환해주는 것이 좋지 않을까요~?

2022-01-09 19:41 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
> +            print(error)
마찬가지로 발생한 에러를 completion으로 반환하면 더 좋을 것 같아요!

2022-01-09 19:41 UTC, ryan-son commented on OpenMarket/OpenMarket/APIManager.swift
> +      print(error)
에러 반환~!

2022-01-09 19:41 UTC, ryan-son commented on OpenMarket/OpenMarket/JSONParser.swift
> +  static let shared = JSONParser()
이 타입을 싱글턴으로 구현한 이유가 있나요? 아래 메서드를 보니 이제 JSONEncoder, JSONDecoder를 반복적으로 생성하지 않고있는데, 싱글턴으로 구현하시게 된 연관 관계가 궁금합니다~

2022-01-09 19:41 UTC, ryan-son commented on OpenMarket/OpenMarket/Model/Image.swift
>    let issuedAt: String
👍 회사였다면 API 문서 링크까지 남겼을 것 같네요. 캠프 API 문서를 노출할 수는 없으니 이게 최선이라고 생각합니다 😊

2022-01-09 19:41 UTC, ryan-son commented on OpenMarket/OpenMarket/URLGenerator.swift
> +  static func DetailProduct(productId: Int) throws -> URL {
대문자가 있네요~

2022-01-09 19:41 UTC, ryan-son commented on OpenMarket/OpenMarket/URLGenerator.swift
> +  }
👍 이런 방식으로도 하실 수 있고, 열거형 case와 associated value, 연산 프로퍼티를 이용해 상황에 따라 알맞은 URL을 반환하는 방식으로도 구현해볼 수 있어요. 저는 두 방식 모두 선호합니다~

2022-01-09 19:41 UTC, ryan-son commented on OpenMarket/OpenMarket/URLSession+Extension.swift
> +    return dataTask
👏

2022-01-09 19:41 UTC, ryan-son commented on OpenMarket/OpenMarketTests/APIManagerTests.swift
> +  var sutSession: URLSession!
암시적 옵셔널 해제 방식을 사용해 보셨네요. 취향에 따라 엄격하게 `?` 방식의 옵셔널로 표현하는 것이 더 안전한건 확실해요. 하지만 테스트인만큼 미리 필요한 내용을 세팅해두지 않았을 때 실수를 발견하기는 용이하니 이 방식도 괜찮다고 생각합니다. 이 방식을 선호하시지 않으시는 동료 (회사/캠퍼/리뷰어)가 있을 수도 있다는 점은 염두에 두시고 성향에 맞게 규칙을 정하면 되겠습니다.
하지만 실제 프로덕트 코드에서 이런 방식을 채택하는 것은 피해주세요~

2022-01-09 19:41 UTC, ryan-son commented on OpenMarket/OpenMarketTests/APIManagerTests.swift
> +    sutAPIManager!.productList(pageNumber: 1, itemsPerPage: 10) { result in
```suggestion
    sutAPIManager.productList(pageNumber: 1, itemsPerPage: 10) { result in
```

2022-01-09 19:41 UTC, ryan-son commented on OpenMarket/OpenMarketTests/APIManagerTests.swift
>    }
비동기 테스트를 수행해 보셨네요 👏 깔끔합니다!

2022-01-09 19:41 UTC, ryan-son commented on OpenMarket/OpenMarketTests/TestDouble/MockURLProtocol.swift
> +class MockURLProtocol: URLProtocol {
공부하시느라 고생하셨습니다~! 완벽하네요! 😊

2022-01-09 19:42 UTC, merged

2022-01-10 05:20 UTC, hoBahk commented on OpenMarket/OpenMarket/APIManager.swift
> +    request.httpMethod = "GET"
클래스와 구조체를 사용하지 않고 enum을 사용한 이유는 불필요한 인스턴스를 만들지 못하도록 하기 위해서 입니다!!
그리고 열거형의 case+rawValue를 사용하지 않고 타입 프로퍼티를 사용한 이유는 외부에서 호출할 때 뒤에 rawValue를 써주지 않고 HttpMethod.get으로 호출할 수 있어서 간편하고 가독성 측면에서도 더 좋다고 생각했습니다 😄

2022-01-10 05:32 UTC, Kim-EunsooSilver commented on OpenMarket/OpenMarket/JSONParser.swift
> +    let encodedData = try? JSONEncoder().encode(data)
🤔 첨부해주신 문서에서는 JSONEncoder, JSONDecoder 객체에 대한 생성 비용이 언급되지는 않으나, 반복적인 생성시에는 비용이 발생할수 있겠다라는 깨달음을 얻었습니다.
 지금 진행중인 프로젝트인 경우, 현재는 데이터가 소량이기에 당장은 생성비용보다는 싱글턴에 의해 참조하고 있는 비용(?)이 덜생산적일수 있겠습니다. 하지만, 오픈마켓 특성상 데이터는 금방 축적되어 질것으로 생각되어집니다.
  데이터가 많아졌을 경우 기존의 코드로 구현이 된다면, 데이터를 전달받고 파싱을 할때마다 객체를 생성 후, 해제하기때문에 이로 인한 생성비용보다는 JSONEncoder, JSONDecoder를 항상 참조하고 있는 비용이 더 생산적일거 같다라는 생을 하게 되었습니다.

2022-01-10 05:47 UTC, hoBahk commented on OpenMarket/OpenMarket/URLSession+Extension.swift
> +  func dataTask(_ request: URLRequest, completion: @escaping (Result<Data, NetworkError>) -> ()) {
놓친 부분이 있군요!  수정하겠습니다~

```swift
func dataTask(
    _ request: URLRequest,
    completion: @escaping (Result<Data, NetworkError>) -> Void
  ) -> URLSessionDataTask {
```

2022-01-10 05:54 UTC, Kim-EunsooSilver commented on OpenMarket/OpenMarket/APIManager.swift
>    let semaphore = DispatchSemaphore(value: 0)
맞아요.. 라이언... 제거했어요...

2022-01-10 05:56 UTC, hoBahk commented on OpenMarket/OpenMarket/APIManager.swift
> +  let urlSession: URLSession
아..! 넵 접근제어 설정했습니다!

2022-01-10 06:45 UTC, Kim-EunsooSilver commented on OpenMarket/OpenMarket/APIManager.swift
> +        itemsPerPage: "\(itemsPerPage)")
좋은 조언 감사합니다~~🙏🏻

2022-01-10 07:11 UTC, hoBahk commented on OpenMarket/OpenMarket/APIManager.swift
> +      request.httpMethod = HttpMethod.get
URLRequest에 익스텐션을 통해서 method를 설정해서 인스턴스를 생성할 수 있도록 수정했습니다!

```swift
extension URLRequest {
  enum HttpMethod {
    case get
    case post
    case patch
    case delete
  }
  
  init(url: URL, httpMethod: HttpMethod){
    self.init(url: url)
    
    switch httpMethod {
    case .get:
      self.httpMethod = "GET"
    case .post:
      self.httpMethod = "POST"
    case .delete:
      self.httpMethod = "DELETE"
    case .patch:
      self.httpMethod = "PATCH"
    }
  }
}
```

2022-01-10 07:17 UTC, Kim-EunsooSilver commented on OpenMarket/OpenMarket/APIManager.swift
> +    complition: @escaping (Result<ProductList, ResponseError>) -> Void
🙇🏻좋은 기능 배웠습니다!!!

2022-01-10 07:24 UTC, hoBahk commented on OpenMarket/OpenMarket/APIManager.swift
> +            print(error)
오류를 completion을 통해 반환하도록 수정했습니다~
```swift
case .success(let data):
  completion(.success(data))
case .failure(let error):
  completion(.failure(error))
}
```

2022-01-10 07:46 UTC, Kim-EunsooSilver commented on OpenMarket/OpenMarket/JSONParser.swift
> +  static let shared = JSONParser()
이전 리코멘트에서 답변을 진행했었는데요!

> 🤔 첨부해주신 문서에서는 JSONEncoder, JSONDecoder 객체에 대한 생성 비용이 언급되지는 않으나, 반복적인 생성시에는 비용이 발생할수 있겠다라는 깨달음을 얻었습니다.
지금 진행중인 프로젝트인 경우, 현재는 데이터가 소량이기에 당장은 생성비용보다는 싱글턴에 의해 참조하고 있는 비용(?)이 덜생산적일수 있겠습니다. 하지만, 오픈마켓 특성상 데이터는 금방 축적되어 질것으로 생각되어집니다.
데이터가 많아졌을 경우 기존의 코드로 구현이 된다면, 데이터를 전달받고 파싱을 할때마다 객체를 생성 후, 해제하기때문에 이로 인한 생성비용보다는 JSONEncoder, JSONDecoder를 항상 참조하고 있는 비용이 더 생산적일거 같다라는 생을 하게 되었습니다.

다시 한번 리코멘트를 읽다보니 굳이 싱글턴으로 구현을 안해도 되겠다는 생각을 했습니다.
그래서 이번에는 struct로 타입을 변경하였고 JSONParser내부에서 인스턴스로 생성해주었습니다.

2022-01-10 07:49 UTC, hoBahk commented on OpenMarket/OpenMarketTests/APIManagerTests.swift
> +    sutAPIManager!.productList(pageNumber: 1, itemsPerPage: 10) { result in
아! 수정했습니다~!!