오픈마켓 [STEP 1] aCafela coffee, 호댕
yagom-academy/ios-open-market pull request #81
Opened 2022-01-05 13:18 UTC by yanghojoon

안녕하세요, 콘 @protocorn93 
오픈 마켓 프로젝트 Step 1 마무리되어 PR 보내드립니다! 
이번 프로젝트에서 새롭게 적용한 개념이 많아, 부족한 점이 있을 수 있습니다.😅
잘 부탁드립니다 🙏

## 🤔 고민했던 점

### 1. 줄바꿈 규칙

```swift
// 처음 규칙
private static func buildBody(with salesInformation: SalesInformation,
                              images: [String: Data]) -> Data? {
```

```swift
// 변경된 규칙
private static func buildBody(
    with salesInformation: SalesInformation,
    images: [String: Data]
) -> Data? {
```

Parameter가 길어서 이전 줄바꿈 규칙으로 문제가 있었습니다.
줄바꿈 규칙을 [Swift Style Guide](https://github.com/StyleShare/swift-style-guide#%EC%A4%84%EB%B0%94%EA%BF%88) 를 따르도록 변경했습니다.

### 2. 구조체의 프로퍼티에 var를 사용

구조체의 프로퍼티는 var를 사용했습니다.
구조체는 사용하는 곳에서 let, var를 고민하면 될 것입니다.

### 3. Snake-Case와 Date를 변환하는 방법

Mock 데이터와 서버에서 받아야 하는 데이터 모두 SnakeCase로 작성되어 있었습니다. 또한 Date의 경우도 Mock 데이터에서 String으로 되어 있어 변환하는 방법에 대해 고민했습니다. 
처음에는 따로 `init(from decoder: Decoder)`을 만들어 바꿔주는 방식을 택했습니다. 

```swift
init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: Self.CodingKeys)
    id = try container.decode(Int.self, forKey: .id)
    vendorId = try container.decode(Int.self, forKey: .vendorId)
    name = try container.decode(String.self, forKey: .name)
    thumbnail = try container.decode(String.self, forKey: .thumbnail)
    currency = try container.decode(Currency.self, forKey: .currency)
    price = try container.decode(Int.self, forKey: .price)
    bargainPrice = try container.decode(Int.self, forKey: .bargainPrice)
    discountedPrice = try container.decode(Int.self, forKey: .discountedPrice)
    stock = try container.decode(Int.self, forKey: .stock)

    let createdAt = try container.decode(String.self, forKey: .createdAt)
    let issuedAt = try container.decode(String.self, forKey: .issuedAt)

    let formatter = DateFormatter()
    formatter.dateFormat = "yyyy-MM-dd HH:mm:ss.SSS"
    guard let formattedCreatedAt = formatter.date(from: createdAt),
          let formattedIssuedAt = formatter.date(from: issuedAt) else {
              throw FormattingError.dateFormattingFail
          }
     self.issuedAt = formattedIssuedAt
     self.createdAt = formattedCreatedAt
}
```

하지만 이후 `dateDecodingStrategy`와 `keyDecodingStrategy` 중 `convertFromSnakeCase`이 있는 것을 알았고 위 방법이 아닌 Decoding Strategy를 사용하는 방법을 선택했습니다. 

### 4. URLSession.dataTask(with:) `URLRequest` 타입만 사용

```swift
let dataTask = URLSession.shared.dataTask(with: request) { data, response, error in
    if let error = error {
        completionHandler(.failure(error))
        return
    }
    guard let httpResponse = response as? HTTPURLResponse,
          (200...299).contains(httpResponse.statusCode) else {
              completionHandler(.failure(NetworkError.httpError))
              return
          }
    guard let data = data else { return }
    completionHandler(.success(data))
}
```

위 코드가 `NetworkTask`에서 반복적으로 사용되었음에도 URL을 사용하는 부분과 URLRequest를 사용하는 부분으로 나눠져 있어 함수로 분리하는데 어려움이 있었습니다. 
처음에는 저희가 만든 `dataTask` 메서드에서 with request 매개변수에 제네릭을 사용하려고 했으나 이렇게 할 경우 `URLSession.shared.dataTask(with: request)`에서 문제가 발생했습니다. 

>No exact matches in call to instance method 'dataTask’

따라서 여기선 항상 `URLRequest`를 받도록 구현했고, URL을 사용하는 경우 다음과 같이 `URLRequest`로 변환하는 과정을 추가해주었습니다. 
`var request = URLRequest(url: url)`

### 5. `URLSession.dataTask(with:completionHandler:)` 에서 error와 response를 처리하는 방법

```swift
enum NetworkResponse {
    case response(URLResponse, Data?)
    case error(Error)
}
```

`Result<Data, Error>` 타입 대신 위의 `NetworkResponse` 타입을 사용할지 고민했습니다.
지금은 http status code를 따로 처리할 필요가 없을듯 해서 Result 타입을 사용했습니다.

### 6. `multipart/form-data` 를 위한 body 만들기

다른 곳에선 `application/json`을 사용해서 문제가 없었으나 상품 등록에선 `multipart/form-data`을 사용해야 해서 이를 위한 body를 구현해줘야 하는 문제가 있었습니다. 
따라서 따로 `buildBody`라는 메서드를 만들어 `multipart/form-data`에 맞는 body를 만들어줄 수 있도록 구현했습니다. 

`multipart/form-data`의 body를 만들기 위해 지켜야 할 점

1. 바운더리를 구분하기 위한 문자열을 임의로 정한다. 
→ 저희의 경우 UUID().uuidString을 통해 임의의 문자열을 생성해주었습니다.
2. 각 폼 필드 요소의 값은 `--바운더리` 모양의 라인 하나로 구분된다. 
3. 이후 해당 필드 요소 데이터에 대한 헤더를 정의한다. 
→ ex: `"Content-Disposition: form-data; name=\"params\"\r\n\r\n"`
4. 헤더와 내용에는 반드시 빈 줄 1개가 있어야 한다.
5. 모든 요소의 기입이 끝났으면 줄을 바꾸고 `--바운더리--`의 모양으로 데이터를 기록하고 끝낸다.

## 📝 조언을 얻고 싶은부분

### 1. `else { return nil }` 을 한줄에 써도 될까요?

`return` 만 있는 코드블럭은  한줄로 썼습니다.
`return nil` 의 경우는 지금 규칙으로는 줄바꿈을 해야 합니다. 그런데 바인딩 실패는 덜 중요한 내용이라고 생각됩니다. 그래서 한줄에 쓰면 좋을듯 합니다. 콘은 어떻게 생각하시는지 궁금합니다.

2022-01-06 03:30 UTC, protocorn93 requested changes
두 분 모두 수고하셨습니다!  전체적으로 좋은 가독성을 가진 코드를 작성해주셨네요! 

코멘트 확인 부탁드립니다. 제 피드백에 대한 3줄 요약은 

1. 코드의 추상화 레벨을 좀 더 고민해보시는 건 어떨까요? (클린코드에서의 추상화 레벨)
2. 추상화에 대한 고민이 필요해보입니다. (OOP에서의 추상화) 
3. 불필요한 프로토콜을 채택하고 있지 않은지에 대한 고민을 해보세요. 

## 고민했던 점 

> 구조체의 프로퍼티에 `var` 사용 

사용하는 곳에서 고민하면 된다는 것이 어떤 뜻인지 좀 더 자세히 설명해주실 수 있으신가요? 

> URLSession.dataTask(with:completionHandler:) 에서 error와 response를 처리하는 방법

`Result` 타입을 사용하기로 한 결정은 좋은 것 같아요! 👏

--- 

## 조언을 얻고 싶은 부분 

>  else { return nil } 을 한줄에 써도 될까요? 

어디서는 `return` 하기 전에 추가 코드가 들어갈 경우가 있는데, 그럴 때는 줄바꿈이 필요하잖아요? (`;`를 사용할 수도 있지만) 그렇기 때문에 저는 개인적으로는 줄바꿈으로 통일해서 사용하긴 합니다!

2022-01-06 03:30 UTC, protocorn93 commented on OpenMarket/OpenMarket/Model/Currency.swift
> +enum Currency: String, Codable {
`Codable`은 `Encodable & Decodable`인데, `Currency`는 두 프로토콜이 모두 필요한건가요?

2022-01-06 03:30 UTC, protocorn93 commented on OpenMarket/OpenMarket/Model/Currency.swift
> +    case usd = "USD"
저도 `rawValue`를 즐겨 사용합니다. 다만 목적에 따라 다른데요. 현재 프로젝트 명세에서 `Currency`는 네트워크 응답 매핑 모델이기에 `rawValue`를 통해 쉽게 디코딩을 해줄 수 있기에 적절히 잘 사용하신 것 같아요.

다만 이후 프로젝트를 진행하거나 스스로 공부를 하실 때는 `rawValue`를 사용할지, 아니면 사용자 정의 get-only 프로퍼티를 사용할지에 대해서도 한번쯤은 고민해보시게 좋아요. `someCase.rawValue`보다 `someCase.unitString`과 같은 코드의 가독성이 더 중요시 되는 경우도 있으니까요~

2022-01-06 03:30 UTC, protocorn93 commented on OpenMarket/OpenMarket/Model/Image.swift
> +struct Image: Codable {
프로퍼티들을 `let`이 아닌 `var`로 정의한 이유가 있을까요?

2022-01-06 03:30 UTC, protocorn93 commented on OpenMarket/OpenMarket/Util/JSONParser.swift
> +    static func decode(from data: Data) throws -> Element {
`static`을 사용하면 보다 편리하게 해당 기능을 사용할 수 있는데요. 하지만 쉽게 접근할 수 있기 때문에 사용하는 클라이언트와의 강결합을 유발합니다. 싱글톤과 동일한 성격의 문제를 갖고 있어요. 이를 보통 “Sacrificing Transparency for Convenience” 라고 표현하곤 합니다. 

이상적인 접근방법은 `JSONParser`가 필요한 곳에 의존성으로 넣어주는 것입니다. 좀 더 나아가 json parsing을 추상화한 프로토콜을 주입하고, `JSONParser`가 이를 채택하는 것이겠죠

2022-01-06 03:30 UTC, protocorn93 commented on OpenMarket/OpenMarket/Util/JSONParser.swift
> +        return data
너무 잘 작성해주셨어요~ 여기서 살짝 제 의견을 드리자면, 저장 프로퍼티로 `JSONDecoder` 인스턴스와 `DateFormatter` 인스턴스를 갖고 정의와 동시에 속성을 지정해주면(혹은 생성자에서) 보다 나은 가독성과 메서드의 역할이 디코딩에 집중할 수 있을 것 같아요. 

그렇게 되면 각각의 인스턴스는 디코딩과 인코딩시 재활용되겠죠~ 그렇게 되면 `JSONDecoder`, `JSONEncoder` 인스턴스를 재활용해도 되나의 대한 의문이 생길 수 있을 것 같아요. 이 부분에 대해서는 한번 간단히 구글링 해보시면 원하시는 답을 쉽게 찾을 수 있을거에요! 직접 확인해보시길 권장드립니다!

2022-01-06 03:30 UTC, protocorn93 commented on OpenMarket/OpenMarket/Model/ProductsList.swift
> +struct ProductsList: Codable {
마찬가지로 `Codable` 채택이 필요한가에 대한 고민도 해보시면 좋을 것 같아요

2022-01-06 03:30 UTC, protocorn93 commented on OpenMarket/OpenMarket/Util/NetworkTask.swift
> +    static func requestHealthChekcer(completionHandler: @escaping (Result<Data, Error>) -> Void) {
`JSONParser`와 마찬가지로 `static` 사용에 대한 고민을 함께 해보시는건 어떨까요

2022-01-06 03:30 UTC, protocorn93 commented on OpenMarket/OpenMarket/Util/NetworkTask.swift
> +        var request = URLRequest(url: url)
`buildBody` 처럼 `URLRequest`를 만들고 값을 채우는 것도 메서드로 분리하는건 어떨까요?

2022-01-06 03:30 UTC, protocorn93 commented on OpenMarket/OpenMarket/Util/NetworkTask.swift
> +        for (fileName, image) in images {
`forEach` 고차함수를 사용해보는건 어떨까요?

2022-01-06 03:30 UTC, protocorn93 commented on OpenMarket/OpenMarket/Util/NetworkTask.swift
> +        static let apiHost = "https://market-training.yagom-academy.kr"
실제 앱을 만들거나, 회사에 들어가 팀에 소속되어 개발을 한다면, 기능에 따라 api마다 도메인이 다를 수 있습니다. 당연히 도메인에 따른 경로도 다르겠죠! 어떻게 하면 이를 좀 더 유연하게 대응할 수 있을까요?

2022-01-06 03:30 UTC, protocorn93 commented on OpenMarket/OpenMarket/Util/NetworkTask.swift
> +        case removeProduct(productId: Int, productSecret: String)
api 경로와 api 요청별 필요한 정보를 associated value로 표현한 점 훌륭합니다! 👍

2022-01-06 03:30 UTC, protocorn93 commented on OpenMarket/OpenMarket/Util/NetworkTask.swift
> +    struct SalesInformation: Codable {
여기도 `Codable`을 채택하고 있네요!

2022-01-06 03:30 UTC, protocorn93 commented on OpenMarket/JSONParseTests/JSONParseTests.swift
> +enum JSONParser<Element: Decodable> {
프로덕트 코드에도 `JSONParser`가 있는데, 단위 테스트 타겟에도 동일하게 정의해준 이유가 궁금하네요! 프로덕트에 있는 코드를 테스트해야하지 않을까요?

2022-01-06 03:30 UTC, protocorn93 commented on OpenMarket/JSONParseTests/JSONParseTests.swift
> +class JSONParseTests: XCTestCase {
API 요청 객체에 대한 단위 테스트 코드는 작성해보셨을까요?

2022-01-06 05:55 UTC, yanghojoon commented on OpenMarket/OpenMarket/Model/Currency.swift
> +enum Currency: String, Codable {
Currency의 경우 Encodable, Decodable 모두 가능해야 해서 Codable로 그대로 두었고, 다른 것의 경우 Encodable과 Decodable로 분리해줬습니다.

2022-01-06 06:09 UTC, yanghojoon commented on OpenMarket/OpenMarket/Model/Image.swift
> +struct Image: Codable {
`var`로 선언한 경우 인스턴스를 생성할 때 let으로 선언해주면 내부 프로퍼티도 전부 let으로 변경이 불가능하고, var로 선언해주면 내부 프로퍼티를 수정할 수 있다고 알고 있습니다. 

따라서 let으로 선언해주는 것보다 코드를 유동적으로 사용할 수 있다고 판단했고 var로 프로퍼티들을 정의했습니다.

2022-01-06 06:40 UTC, aCafela-coffee commented on OpenMarket/OpenMarket/Util/JSONParser.swift
> +    static func decode(from data: Data) throws -> Element {
JSONParsable 프로토콜을 만들고, NetworkTask는 의존성 주입하도록 수정했습니다.

2022-01-06 06:52 UTC, yanghojoon commented on OpenMarket/OpenMarket/Util/JSONParser.swift
> +        return data
이 부분은 init으로 값을 받을 수 있도록 수정했습니다. 

혹시 JSONEncoder와 JSONDecoder의 인스턴스를 재활용하는 것이 잘 이해가 안가는데, 어떤 내용이었을까요?

2022-01-06 06:52 UTC, yanghojoon commented on OpenMarket/OpenMarket/Model/ProductsList.swift
> +struct ProductsList: Codable {
이 부분도 위와 함께 수정 완료했습니다.

2022-01-06 07:04 UTC, aCafela-coffee commented on OpenMarket/OpenMarket/Util/NetworkTask.swift
> +    static func requestHealthChekcer(completionHandler: @escaping (Result<Data, Error>) -> Void) {
인스턴스를 만들어서 사용하도록 변경합니다.

2022-01-06 07:11 UTC, aCafela-coffee commented on OpenMarket/OpenMarket/Util/NetworkTask.swift
> +        var request = URLRequest(url: url)
```swift
var request = URLRequest(url: url)
request.httpMethod = "POST"
request.addValue("multipart/form-data; boundary=\(boundary)", forHTTPHeaderField: "Content-Type")
```

URLRequest는 충분히 짧고, NetworkTask의 각 함수가 필요한 값이 달라서 지금 상태로 두는게 좋지 않을까요?

2022-01-06 07:17 UTC, yanghojoon commented on OpenMarket/OpenMarket/Util/NetworkTask.swift
> +        for (fileName, image) in images {
이 부분은 forEach로 변경했습니다.

2022-01-06 07:30 UTC, aCafela-coffee commented on OpenMarket/OpenMarket/Util/NetworkTask.swift
> +        static let apiHost = "https://market-training.yagom-academy.kr"
`apiHost`를 `marketTrainingApiHost`로 이름을 변경합니다.
다른 도메인이 필요할 때 타입 프로퍼티를 추가해서 사용하도록 했습니다.

2022-01-06 07:30 UTC, yanghojoon commented on OpenMarket/OpenMarket/Util/NetworkTask.swift
> +    struct SalesInformation: Codable {
이 부분도 일괄적으로 수정 완료했습니다!

2022-01-06 07:45 UTC, yanghojoon commented on OpenMarket/JSONParseTests/JSONParseTests.swift
> +enum JSONParser<Element: Decodable> {
프로젝트를 진행할 때 네트워크에서 데이터를 파싱하는 JSONParser 보다 테스트 코드를 먼저 작성해서 테스트에 따로 JSONParser를 두었습니다. 

현재는 프로덕트 코드의 JSONParser를 충분히 활용할 수 있어 프로덕트 코드의 JSONParser를 사용해 테스트를 진행했습니다.

2022-01-06 07:57 UTC, aCafela-coffee commented on OpenMarket/JSONParseTests/JSONParseTests.swift
> +class JSONParseTests: XCTestCase {
요구사항에 Mock 데이터로만 테스트 하라고 해서 단위 테스트 코드는 작성하지 않았습니다. 

NetworkTask.requestProductRegistration() 함수 하나는 테스트 해봤습니다.
form-data가 원하는 모양대로 보내지는지, 응답이 잘 오는지 따로 확인했습니다.

2022-01-06 13:34 UTC, protocorn93 commented on OpenMarket/OpenMarket/Model/Image.swift
> +struct Image: Codable {
네 경우에 따라서 구조체 인스턴스 값을 직접 변경해야하는 경우도 필요합니다. 다만 네트워크 매핑 모델의 같은 경우는 `let`으로 불변성을 유지하는게 좀 더 바람직한 접근법 같아요. 이렇게 원천 데이터에 변경을 직접 가하는건 예상치 못한 사이드 이펙트를 발생시키는 경우도 있거든요. 그래서 저는 보통 

원격 저장소 데이터 매핑 모델 - 비즈니스 로직 수행을 위한 모델 - 화면에 그려주는데 필요한 모델

이렇게 모델도 계층을 나누어 관리합니다. 한 계층에서의 변경의 여파가 외부로 퍼저나가지 않도록 하기 위해말이죠

2022-01-06 13:37 UTC, protocorn93 commented on OpenMarket/OpenMarket/Util/JSONParser.swift
> +        return data
아~ 네 저는 처음 이 클래스들에 대해 공부할 때 `JSONEncoder`나 `JSONDecoder` 인스턴스를 매번 생성하지 않고 요청마다 재사용하면 사이드 이팩트가 발생하는줄 알았거든요. 하지만 애플의 공식문서나 swift open source의 코드를 보면 그렇지 않음을 알 수 있습니다. 

혹시 똑같은 고민을 하셨을까하는 생각에 말씀드렸습니다! 😄

2022-01-06 13:41 UTC, protocorn93 commented on OpenMarket/OpenMarket/Util/NetworkTask.swift
> +        var request = URLRequest(url: url)
네네~ 그럴수도 있다고 생각합니다. 아카펠라와 호댕이 서로 협의를 하고 정했다면 충분히 이유가 될 수 있다고 생각해요.

저는 보통 코드를 작성할 때 한 줄 짜리라도 그 역할이 명확하고 재사용이 된다면 메서드로 분리하는 편이에요. 메서드명으로 보다 명확한 의미 전달을 할 수 있거든요. 또한 메서드 안에서의 추상화 레벨이 일정하면 코드 가독성도 좋아진다는 장점도 있구요. task마다 다른 요소는 인자를 전달하는 방식으로 구현해볼 수 있지 않을까 합니다.

2022-01-06 13:48 UTC, protocorn93 commented on OpenMarket/OpenMarket/Util/NetworkTask.swift
> +        static let apiHost = "https://market-training.yagom-academy.kr"
음 저는 네이밍에 문제가 있다고 생각하진 않았습니다. 다양한 도메인 그리고 경로가 추가될 때 이를 어떻게 하면 보다 유연하게 대응할 수 있을지에 대해 질문을 드린거였는데요~ 이 부분은 스탭 진행하면서 천천히 고민해보면 좋겠네요!

2022-01-07 02:24 UTC, aCafela-coffee commented on OpenMarket/OpenMarket/Model/Image.swift
> +struct Image: Codable {
let으로 수정합니다.

2022-01-07 02:45 UTC, yanghojoon commented on OpenMarket/OpenMarket/Util/NetworkTask.swift
> +        var request = URLRequest(url: url)
이 부분도 충분히 메서드로 분리할 수 있을 것 같아 메서드로 분리해주었습니다. 감사합니다!

2022-01-07 04:41 UTC, merged