오픈 마켓 [STEP1] Jiseong, Chacha
yagom-academy/ios-open-market pull request #86
Opened 2022-01-06 13:51 UTC by ChaminLee

안녕하세요 도미닉! @AppleCEO 
이번 프로젝트 리뷰받게 된 지성, 차차입니다!

Step1 완료하여 PR요청드립니다!
(PR이 말씀드렸던 일정보다 조금 많이 늦어졌습니다...ㅠ🙏🏻)
네트워킹은 처음이었는데... 최대한 재사용성이나 역할에 대해서 고민하여 코드를 작성해봤습니다. 
이번 프로젝트 잘 부탁드리겠습니다! 

---

## Step 1

## 고민했던 점 

### 1. 네트워크 무관 테스트

프로젝트의 Step1에서 요구되는 실제 네트워크와 통신하지 않으며 진행하는 테스트를  Mock을 생성하여 구현해봤습니다.

실제 `Session`과 통신하지 않기 위해 기존 `URLSession`에 의존하는 것이 아닌 `URLSessionProtocol`을 생성하여 이에 의존하도록 했습니다. APIService내의 프로퍼티가 이제 `URLSession` 타입이 아니라, `URLSessionProtocol` 타입을 갖게 되고, 이 프로퍼티를 상황에 따라 실제/가짜 Session을 넣어주기 위해 생성자 주입 방식을 사용했습니다. 

먼저 `URLSessionDataTask`를 대체할 `MockURLDataTask` 타입을 생성했습니다. 이 또한 `URLSessionDataTask`를 상속하도록 하고, `URLSessionDataTask`의 `resume()` 메서드를 재정의하여 `MockURLDataTask`에서 정의한 클로저를 실행시켜주도록 구현했습니다. 

이후 `URLSessionProtocol`을 채택한 `MockURLSession` 타입을 구현하여 Unit Test시 `APIService` 인스턴스를 생성할 때 `MockURLSession`을 주입하였고, 해당 세션이 채택한 프로토콜에 정의되어있는 `dataTask()`를 구현해주었습니다.

생성한 task가 `resume()`될 때 앞서 `MockURLDataTask`에서 정의한 클로저가 이어서 실행되면서 사전에 만들어둔 성공/실패 결과를 반환하게 됩니다. 

이제 Unit test를 할 때, `APIService의` session에 `MockURLSession`을 넣어주어 항상 성공/실패하도록 설정해두었습니다. 이에 기대하던 데이터를 미리 디코딩해두고, `APIService`의 메서드를 실행 결과가 이와 동일한지 비교하여 네트워크와 무관한 로직 테스트를 수행했습니다. 

### 2. URLRequest initializer 추가 

`URLRequest` 인스턴스를 커스텀하게 생성해주기 위해 extension을 사용하여 이니셜라이저를 생성하였습니다. 생성과 함께 httpHeader/Body도 설정해주고, url도 달아주기 위해 부가적으로 `API`, `URLCreator`와 같은 타입을 생성하였습니다.

### 3. `dataTask()` 공통 사용 

서버 요청에 반복적으로 사용될 수 있는 `dataTask()`를 하나로 묶어 사용하였습니다. 이 덕분에 상품 상세 조회, 상품 리스트 조회, 상품 삭제 등 여러 요청에서 해당 메서드를 재사용할 수 있었습니다. 

### 4. `@escaping` closure 및 `Result` 타입 사용 

메서드가 리턴되더라도 추후에 데이터를 전달받기 위해 `@escaping`을 클로저에 사용해주었습니다. 이와 함께 `Result` 타입을 활용하여 성공/실패에 따른 정상적인 결과/에러를 반환해 줄 수 있도록 했습니다. 

## 궁금한 부분

### 1. `URLSessionDataTask` init() deprecate문제 

> 'init()' was deprecated in iOS 13.0: Please use -[NSURLSession dataTaskWithRequest:] or other NSURLSession methods to create instances

테스트를 위한 `MockURLSessionDataTask`를 생성할 때 위와 같은 에러를 마주했습니다. 지성과 이야기를 나눠서 낸 결론은 애플이 직접적으로 URLSessionDataTask 타입을 인스턴스화 하는 것을 막고, `dataTask()`와 같이 URLSessionDataTask를 반환해주는 메서드를 사용해서 URLSessionDataTask를 얻을 것을 권장하는 것이라고 생각했습니다. 

저희가 생각한 부분이 맞는지 궁금하고, 저렇게 init()이 불가하다면 현재 상황에서 어떻게 개선하여 테스트 할 수 있는지 궁금합니다!

### 2. 상품 등록, 상품 secret 조회, 상품 삭제 관련 코드

현재 상품 등록, 상품 secret 조회, 상품 삭제의 경우 실제로 서버와 제대로 통신이 되는지 확인하지 못했습니다. vendor ID를 추후에 발급해주신다고 하여 그 때 테스트해보려고 하는데, 현재 코드로도 정상적으로도 작동이 되는 것인지, 코드는 잘 구성이 된 것인지 궁금합니다!

관련해서 개선해야 할 부분이 있을지 궁금합니다!
    
### 3. multipart/form-data 변환을 시도해봤지만.. 상품 등록 시도를 해봤을 때 정상적인 응답이 오지않았습니다.

상품 등록할 모델을 인코딩하여 httpBody에 넣어줄 multipart/form-data의 형식으로 변환을 시도하였습니다. 해당 과정에서 Boundary를 생성하여 추가하였고 정형화된 multipart/form-data 형식에 따라 인덴트 또한 추가해주었습니다.

그럼에도 불구하고 body를 포함한 HttpRequest를 보내는 Post의 경우 정상적인 응답이 오지 않는 문제가 있었습니다.

body를 사용하지 않고 header나 path를 통해 request를 보내는 GET, PATCH등에 대한 응답은 정상적이여서 저희는 POST에서 사용하는 request의 body에 문제가 있다고 생각하였지만, 이를 해결하지 못하였습니다.

혹시 저희가 body를 형식에 맞게 잘 만들어준게 맞는건지, 그것이 아니라면 어느 부분이 문제가 되고있는지 궁금합니다.

## 조언 받고 싶은 부분

### 1. 모델 분리

요구되는 request/response 타입이 다 제각각이다보니, 모델을 여러 개 생성하게 된 것 같습니다. 현재 모델을 잘 분리하여 구현했는지 궁금합니다!

또한 네트워킹 관련한 코드들도 분리가 잘 되어있는지 궁금합니다!

2022-01-07 05:10 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다
@ChaminLee & @yim2627 고생하셨습니다!
노력한 모습들이 많이 보여지는 코드였습니다~
코멘트들보고 답변해주세요.

질문에 대한 답변
1. URLSessionDataTask init() deprecate문제
- 이 링크 한번 참고해보시면 좋을 것 같습니다! https://forums.raywenderlich.com/t/chapter-8-init-deprecated-in-ios-13/102050/2

2. 상품 등록, 상품 secret 조회, 상품 삭제 관련 코드
- 코드만 보고는 예상하기 힘들 것 같습니다. 현업 개발자도 포스트맨 등으로 따로 테스트를 진행도 해보고 셋팅해도 잘 안되는 경우가 있고 합니다. ID가 발급되면 해보면 될 것 같습니다!

3. multipart/form-data 변환을 시도해봤지만.. 상품 등록 시도를 해봤을 때 정상적인 응답이 오지않았습니다.
- 상품 등록은 아직 테스트 못한다고 하지 않았나요? 포스트맨으로 한번 시도해보시고 잘 안되면 오늘 저녁에 포스트맨으로 같이 업로드 시도해보도록 제가 도와드릴 수도 있을 것 같습니다~

4. API 문서 내 HealthChecker
- 현업에서 본 적은 없습니다. 각 API에서 보통 http 상태코드 값이나 별도의 상태 값(result) 등으로 true 나 1을 내려줘서 그 값을 확인한 적은 있습니다!

2022-01-07 05:10 UTC, AppleCEO commented on OpenMarket/OpenMarket/Error/APIError.swift
> +enum APIError: Error {
어떤 에러들이 모여있는지 명확하게 이름을 정한 부분 좋습니다! 👍

2022-01-07 05:10 UTC, AppleCEO commented on OpenMarket/OpenMarket/Error/APIError.swift
> +    }
description 으로 오류 메시지를 저장해보셨군요. 더 나은 방법이 혹시 어떤게 있을까요?

2022-01-07 05:10 UTC, AppleCEO commented on OpenMarket/OpenMarket/Extensions/Data+append.swift
> +}
이렇게 extension 으로 모든 Data 에 이 함수를 추가해주는 것과 다른 객체를 만들어서 이 메소드를 선언해주는 것 어떤 차이가 있을까요? 장단점은 어떻게 될까요?

2022-01-07 05:10 UTC, AppleCEO commented on OpenMarket/OpenMarket/Extensions/URLRequest+httpmethod.swift
> +            self.addValue(id, forHTTPHeaderField: "identifier")
이렇게 .productDetail 과 .productList 를 위 쪽에 배치해서 return 을 한 이유가 있을까요?
default 를 사용해보는 것은 어떨까요?

2022-01-07 05:10 UTC, AppleCEO commented on OpenMarket/OpenMarket/Models/ProductImage.swift
> +}
이름들이 명확하고 좋습니다!

2022-01-07 05:10 UTC, AppleCEO commented on OpenMarket/OpenMarket/Network/API.swift
> +enum API {
API 같은 간단한 용어는 자제하는 것이 좋습니다.
예약어와 중복되서 예상치 못한 동작을 할 수도 있기 때문인데요.
조금 더 긴 이름을 정해보면 좋겠습니다!

2022-01-07 05:10 UTC, AppleCEO commented on OpenMarket/OpenMarket/Network/APIService.swift
> +        }
메소드마다 이 부분이 반복되고 있는 것 같네요.
반복을 줄여볼 수 있을까요?

2022-01-07 05:10 UTC, AppleCEO commented on OpenMarket/OpenMarket/Network/APIService.swift
> +        }
이 부분도 메소드마다 반복되고 있군요! 🔢

2022-01-07 05:10 UTC, AppleCEO commented on OpenMarket/OpenMarket/Network/URLCreator.swift
> +    }
이 부분 가독성이 떨어지는 것 같네요.
한번 개선해 볼 수 있을까요?

2022-01-07 05:10 UTC, AppleCEO commented on OpenMarket/OpenMarket/ViewController.swift
>  }
사용하지 않는 코드를 제거한 부분 아주 좋습니다! 💯

2022-01-07 05:10 UTC, AppleCEO commented on OpenMarket/OpenMarketTests/APIServiceTests.swift
> +    func test_retrieveProductData호출시_반환되는_상품리스트_데이터의_첫_상품명이_팥빙수인지() {
메소드명이 아주 명확하네요~ 🥇

2022-01-07 05:10 UTC, AppleCEO commented on OpenMarket/OpenMarketTests/Test Double/MockURLSession.swift
> +            }
이 동작을 똑같이하면서 else문을 한번 없애볼 수 있을까요?

2022-01-07 05:55 UTC, yim2627 commented on OpenMarket/OpenMarket/Error/APIError.swift
> +    }
LocalizedError 프로토콜을 해당 에러타입이 채택받아 프로토콜에 정의되어 있는 errorDescription을 구현하는 방법도 있을 것 같습니다!

저희가 LocalizedError의 errorDescription을 사용하지 않은 이유는 Description이 String? 타입이어서 추후 사용할 때 바인딩을 해야한다는 번거로움때문에 사용하지 않았습니다.

그냥 Description을 저희가 만들어서 사용하는 것이 좋지 않은 방법일까요?

2022-01-07 06:05 UTC, yim2627 commented on OpenMarket/OpenMarket/Extensions/Data+append.swift
> +}
Extension: 이 경우는 별도의 타입을 정의할 필요가 없어 프로젝트 내에서 사용하는 Data 타입에 해당 메소드를 사용할 수 있다는 장점이 있는 것 같습니다.
하지만 특정 기능을 지원하는 만큼 기능을 사용하는 범주도 한정되어 있어야하는데, Data 타입을 확장한다면 의도하지 않는 곳에서도 사용되거나, 눈에 보일 수 있다는 단점이 있는 것 같습니다.

객체 만드는 방법: 해당 함수가 필요한 부분에만 호출하여 사용할 수 있도록 제한을 할 수 있다는 장점이 있는 것 같습니다.
하지만 해당 기능을 지원해주기 위해서 인스턴스화를 매번 해줘야 한다는 단점이 있는 것 같습니다.

저희가 생각해본 것은 해당 기능이 사용되는 파일 내에 private extension을 하여 사용 범위를 한정짓고, 편리하게 사용할 수 있다는 장점을 가질 수 있을 것 같습니다.

2022-01-07 06:07 UTC, ChaminLee commented on OpenMarket/OpenMarket/Extensions/URLRequest+httpmethod.swift
> +            self.addValue(id, forHTTPHeaderField: "identifier")
처음에는 케이스를 명시해주는게 좋을 것 같다고 생각했는데, default로 묶어서 관리하는 것이 더 좋을 것 같습니다!

2022-01-07 06:09 UTC, ChaminLee commented on OpenMarket/OpenMarket/Network/API.swift
> +enum API {
말씀하신 것 처럼 더 명시적으로 나타내주는 것이 좋을 것 같아서 `API` -> `OpenMarketAPI`로 수정해주려고 합니다!

2022-01-07 06:17 UTC, yim2627 commented on OpenMarket/OpenMarket/Network/APIService.swift
> +        }
해당 부분은 케이스마다 받는 파라미터가 달라 불필요한 반복이라고 보기 어려울 것 같은데, 왜 반복된다고 생각하신건지 궁금합니다!

URLCreator 내에 메서드를 만드는 등 다른 방식을 생각해봤지만, 결국 케이스마다 받는 파라미터가 달라 재사용해주기가 어렵다고 판단이 됩니다 🥲

2022-01-07 06:52 UTC, yim2627 commented on OpenMarket/OpenMarket/Network/APIService.swift
> +        }
```swift
func registerProduct(newProduct: ProductRegisterInformation, images: [ImageData], completion: @escaping (Result<Data, APIError>) -> Void) {
    guard let url = URLCreator.productRegister.url else {
        return
    }
                
    guard let body = createBody(productRegisterInformation: newProduct, images: images) else {
        return
    }
        
    let request = URLRequest(url: url, api: .productRegister(body: body, id: identifier))
        
    let task = dataTask(request: request, completion: completion)
        
    task.resume()
}
```

dataTask 메서드의 파라미터로 completion을 넣어 불필요한 반복을 제거하였습니다!

2022-01-07 07:04 UTC, ChaminLee commented on OpenMarket/OpenMarket/Network/URLCreator.swift
> +    }
urlquery를 만들어주는 부분이 다른 부분에 비해 길어 가독성을 해치는 것 같아 메서드로 분리해주어 해당 부분 개선하였습니다!

```swift
private func createURLQuery(queries: [String: String]) -> URL? {
    var components = URLComponents(string: URLCreator.baseURL)
    
    queries.forEach { query in
        let queryItem = URLQueryItem(name: query.key, value: query.value)
        components?.queryItems?.append(queryItem)
    }
    
    return components?.url
}
```

2022-01-07 07:12 UTC, ChaminLee commented on OpenMarket/OpenMarketTests/Test Double/MockURLSession.swift
> +            }
```swift
if self.isSuccess {
    completionHandler(productData, successResponse, nil)
    return
}

completionHandler(nil, failResponse, APIError.invalidRequest)   
```

위와 같이 else 문을 제외하여 수정해주었습니다.

2022-01-07 07:21 UTC, AppleCEO commented on OpenMarket/OpenMarket/Error/APIError.swift
> +    }
오.. errorDescription 을 알고 있는군요! 그냥 description 변수를 사용하면 이것이 오류에 대한 설명인지, 오류 메시지인지 정확히 알기 힘들 것 같아요. 더 나은 구조를 알고 있다면 번거롭더라도 사용하는 것이 좋다고 생각합니다~

2022-01-07 07:23 UTC, AppleCEO commented on OpenMarket/OpenMarket/Extensions/Data+append.swift
> +}
오호.. private extension 으로 구성할 수도 있겠군요! 저는 객체로 만드는 것을 좋아합니다. 원하는 동작을 프로젝트 내의 모든 객체에서 굳이 가지고 있을 필요는 없다고 생각해서요. extension 을 사용하면 해당하는 타입의 모든 객체에게 그 동작이 추가될 것인데요. 그 메소드가 필요하지 않은 객체들에게도 생기는 부작용이 있을 것 같습니다.

2022-01-07 07:42 UTC, ChaminLee commented on OpenMarket/OpenMarket/Extensions/Data+append.swift
> +}
넵 말씀주신 부분 참고하도록 하겠습니다!

2022-01-07 07:46 UTC, merged

2022-01-10 04:00 UTC, AppleCEO commented on OpenMarket/OpenMarket/Extensions/Data+append.swift
> +}
인스턴스화를 안해줘도 구조체로 만들고 static 함수로 선언해주는 방법도 있습니다~